### PR TITLE
Stop updating AutoSuggestBox on selection redux

### LINKED ISSUE #17916: [Windows Terminal - Settings - Defaults]: Unable to navigate 'Font face' suggestions using keyboard in Appearance settings.
### Windows Terminal version

1.22.2362.0

### Windows build number

27695.1000

### Other Software

**Test Environment:**
OS: Windows 11 Version Dev (OS Build 27695.1000)
App: Windows Terminal Preview

### Steps to reproduce

**Repro steps:**
1. Open the 'windows terminal' application.
2. Open 'Settings' tab by pressing 'Ctrl+,' keys.
3. Navigate to the 'Defaults' tab and activate it.
4. Navigate to the 'Appearance' button and activate it.
6. Now navigate to 'Font face' edit field by tab key.
7. Suggestion will appear.
8. Now try to navigate in suggestion list by up/down arrow key. 
9. Observe the issue.

**User experience:**
Keyboard users, including those relying on assistive technologies, cannot efficiently browse and select font options from the 'Font face' suggestions. This significantly limits accessibility and hinders smooth navigation in the Appearance settings.

**WCAG Reference Link:**
https://www.w3.org/WAI/WCAG21/Understanding/keyboard

Attachment:
[Users are not able to navigate among the suggestions using keyboard.zip](https://github.com/user-attachments/files/16974239/Users.are.not.able.to.navigate.among.the.suggestions.using.keyboard.zip)

### Expected Behavior

Users should be able to navigate through the font suggestions using the up and down arrow keys without the list closing prematurely. The focus should remain within the list until a selection is made or the user navigates away.

### Actual Behavior

When focus lands on the 'Font face' edit field and suggestions appear, pressing the up or down arrow keys immediately selects the first option from the suggestion list and closes the list. Users cannot browse through the available font suggestions using the keyboard.

### LINKED ISSUE #18070: Preview: Selecting fonts
### Windows Terminal version

1.22.2702.0

### Windows build number

10.0.22635.0

### Other Software

I actually have more than one problem with the font selection in Windows Terminal Preview.

1. When trying to select fonts in Settings -> Profiles: Defaults -> Appearance: Font Face ... it crashes to desktop if I hit "Enter" while _typing in the font selection text box_

2. When typing in the font selection box, if I stop typing and select from the list, and then hit save, it reverts to only the part I typed (and then saves) resulting an error popup that the font doesn't exist.

### Steps to reproduce

1. Open Settings -> Profiles: Defaults -> Appearance ... and click in the Font Face text box, and press Enter.

Then reopen Terminal and try again ... 

1. Type part of a font name in the Font Face box
2. Stop typing and select your font from the list
3. Hit save

### Expected Behavior

I should be able to use my keyboard and mouse together for settings

### Actual Behavior

Terminal crashes and pops up error messages.
Here's a video of the second problem, in case I'm confusing

https://github.com/user-attachments/assets/8c6b5cd9-0c0f-43e0-b87b-b019976ef910

### PR DESCRIPTION
**Pull request by lhecker**
I wrote a big comment next to the changes I made.
This is a redo of #17961 which had various issues.

Closes #17916
Closes #18070 

## Validation Steps Performed
* Pressing Enter within the input line doesn't crash ✅
* Type "Cour" and pick Courier New, press Save = Saved ✅
* Pick any other font from the dropdown, press Save = Saved ✅
* Picking an option dismisses focus but not to the tab row ✅
* The first time after launching the SUI, when the setting is still
  unmodified, when you focus the box and pick an option,
  it'll unfocus the box ✅
* When the setting is unmodified, and you pick the default
  (Cascadia Mono), it'll still unfocus the box ✅

### CODE REVIEW

**Review by carlos-zamora — APPROVED** [review]
Nice! Thank you!

**Comment by zadjii-msft** [comment]
Service to 1.22?

**Comment by DHowett** [comment]
> 1.22

Nah. It didn't _fix_ anything to begin with AFAIK

File: src/cascadia/TerminalSettingsEditor/Appearances.cpp [hunk 1]
```diff
@@ -1049,6 +1045,22 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
         }
 
         sender.Text(fontSpec);
+
+        // Normally we'd just update the model property in LostFocus above, but because WinUI is the Ralph Wiggum
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/Appearances.cpp:1049]: `BODGY`

**Review by DHowett — APPROVED** [review]
My god.
