### PR TITLE
Don't crash when the checking for updates without a network

### LINKED ISSUE #15459: About Dialog update check **crashes** after some time when network is slow or unreachable
Coroutines and exceptions, man, coroutines and exceptions. Wrap it in a try, it still don't catch.

### PR DESCRIPTION
**Pull request by zadjii-msft**
You can't catch an A/V. 

Closes #15459

### CODE REVIEW

File: src/cascadia/TerminalApp/AboutDialog.cpp [hunk 1]
```diff
@@ -90,10 +90,13 @@ namespace winrt::TerminalApp::implementation
             {
                 const auto updates = co_await storeContext.GetAppAndOptionalStorePackageUpdatesAsync();
                 co_await wil::resume_foreground(strongThis->Dispatcher());
-                const auto numUpdates = updates.Size();
-                if (numUpdates > 0)
+                if (updates)
```
Comment (DHowett) [inline src/cascadia/TerminalApp/AboutDialog.cpp:93]: nit: short circuit allows for `if (updates && updates.Size() > 0)` (which may also just read more svelte-ly

**Review by DHowett — APPROVED** [review]

**Comment by lhecker** [comment]
> You can't catch an A/V.

Well........ 😄

**Review by lhecker — APPROVED** [review]
