### PR TITLE
Connect clipboard functionality to their keybindings

### LINKED ISSUE #968: Copy & Paste Keybindings
# Environment

```none
Windows build number: 10.0.18362.86
Windows Terminal version (if applicable):
```

# Steps to reproduce

In the standard Windows 10 console, you can enable the use of Ctrl+C/V for copy and paste. Windows Terminal doesn't have this, and it is extremely frustrating.

# Expected behavior

Enable the use of Ctrl+C for copy and Ctrl+V for paste.

# Actual behavior

Ctrl+C doesn't copy anything, and Ctrl+V just writes ^V at the prompt.

### PR DESCRIPTION
**Pull request by d-bingham**
## Summary of the Pull Request

Connects copy and paste keybindings to the appropriate clipboard functionality within Terminal.

 
## References

#1072, #968

## PR Checklist
* [x] Closes #968
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Requires documentation to be updated
* [x] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #1072, #968 his connects the (mostly) pre-existing copy/paste mechanics to the keyboard shortcut mechanics.

## Detailed Description of the Pull Request / Additional comments

Changes:

- Added TermControl::PasteTextFromClipboard which does what it says on the tin. Refactored the paste code from the right-click handling in TermControl here.
- Added App::_PasteText, mirroring the pre-existing App::_CopyText
- Added connections from keybindings to copy/paste functionality in App::_HookupKeyBindings

Notes:

- This PR interprets the keybinding "copy" as a copy trimming trailing whitespace (the operation performed by a right-click with a selection active). It may be appropriate to add a keybinding for a whitespace-preserving copy (which is now done as a shift-right-click with a selection active).

### CODE REVIEW

File: src/cascadia/TerminalApp/App.cpp [hunk 1]
```diff
@@ -875,6 +877,19 @@ namespace winrt::TerminalApp::implementation
         control.CopySelectionToClipboard(trimTrailingWhitespace);
     }
 
+    // Method Description:
+    // - Paste text from the Windows Clipboard to the focused terminal
+    // Arguments:
+    // - <none>
```
Comment (carlos-zamora) [inline src/cascadia/TerminalApp/App.cpp]: nit: please remove line 882/883 since we don't really need them. :)

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 2]
```diff
@@ -1162,6 +1156,21 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
         _clipboardCopyHandlers(copiedData);
     }
 
+    // Method Description:
+    // - Initiate a paste operation.
+    // Arguments:
+    // - <none>
```
Comment (carlos-zamora) [inline src/cascadia/TerminalControl/TermControl.cpp]: nit: please remove line 1161/1162 since we don't really need them. :)

File: src/cascadia/TerminalApp/App.cpp [hunk 3]
```diff
@@ -428,6 +428,8 @@ namespace winrt::TerminalApp::implementation
         bindings.ScrollDownPage([this]() { _ScrollPage(1); });
         bindings.SwitchToTab([this](const auto index) { _SelectTab({ index }); });
         bindings.OpenSettings([this]() { _OpenSettings(); });
+        bindings.CopyText([this]() { _CopyText(true);  });
```
Comment (carlos-zamora) [inline src/cascadia/TerminalApp/App.cpp]: 2 things:
 1) nit: extra space on the right side of the first semicolon
 2) If I recall correctly, the parameter for `_CopyText()` decides whether or not to copy new lines (usually determined by the SHIFT button). So we'll have to detect that too and use that for this parameter (we'll probably need to make that button rebindable too).

File: src/cascadia/TerminalApp/App.cpp (hunk 1 above)
Comment (d-bingham) [reply src/cascadia/TerminalApp/App.cpp]: Fixed in commit

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 2 above)
Comment (d-bingham) [reply src/cascadia/TerminalControl/TermControl.cpp]: Fixed in commit

**Comment by d-bingham** [comment]
>If I recall correctly, the parameter for `_CopyText()` decides whether or not to copy new lines (usually determined by the SHIFT button). So we'll have to detect that too and use that for this parameter (we'll probably need to make that button rebindable too).

Right-click checks for shift and toggles the copy mode.  If we implement a toggle key for the keyboard shortcut, one of the following happens:

- we choose a non-bindable toggle key, and invalidate various keybindings as a result (e.g., I _want_ the trim-whitespace-copy to fire on ctrl-shift-c, and if the toggle is shift, that doesn't work)
- we implement a keybinding for "toggle whitespace-trimming on copy" which means there's a toggle keybinding for exactly one command that can use the toggle _and_ that implementation is both more complex and is less configurable than just adding a keybinding for "copy-without-whitespace-trimming".

So I think the best (or, at a minimum, "least bad") solution here is to add a separate keybinding for whitespace-preserving copy.  I'm also unclear how much actual _use_ this whitespace-preserving copy sees.

Regarding passing ctrl-c to the terminal in all cases... that's not really appropriate to clipboard stuff _per se_, and should be handled generically in the keybinding code.  But in any case, I'd _hope_ the default keybinding for copy is ctrl+ins or ctrl+shift+c _precisely_ because (in my opinion) there is no elegant handling for copy being ctrl+c anyway -- you either cannot send a ^C to the terminal, or you are forced to do so when copying to the clipboard from the keyboard...

**Comment by zadjii-msft** [comment]
This seems fine to me for now - it doesn't add a default keybinding for these, so we can discuss that later (though I think we're all pretty highly in favor of ctrl+shift+c/v).

I think we can discuss the potential for adding a non-trimming copy keybinding later

File: src/cascadia/TerminalApp/App.cpp (hunk 1 above)
Comment (dlong11) [reply src/cascadia/TerminalApp/App.cpp]: @DHowett-MSFT @zadjii-msft I thought you would enjoy this! 😄 #890 (note - discussion around function documentation and specifically Arguments and return values when to include them / not to include them)   Currently lots of good opinions.  🤕

**Comment by carlos-zamora** [comment]
> > If I recall correctly, the parameter for `_CopyText()` decides whether or not to copy new lines (usually determined by the SHIFT button). So we'll have to detect that too and use that for this parameter (we'll probably need to make that button rebindable too).
> 
> Right-click checks for shift and toggles the copy mode. If we implement a toggle key for the keyboard shortcut, one of the following happens:
> 
> * we choose a non-bindable toggle key, and invalidate various keybindings as a result (e.g., I _want_ the trim-whitespace-copy to fire on ctrl-shift-c, and if the toggle is shift, that doesn't work)
> * we implement a keybinding for "toggle whitespace-trimming on copy" which means there's a toggle keybinding for exactly one command that can use the toggle _and_ that implementation is both more complex and is less configurable than just adding a keybinding for "copy-without-whitespace-trimming".
> 
> So I think the best (or, at a minimum, "least bad") solution here is to add a separate keybinding for whitespace-preserving copy. I'm also unclear how much actual _use_ this whitespace-preserving copy sees.

Hmm... well, SHIFT serves as a modifier to a classic copy. So I guess this is more of a discussion of "should modifiers be rebindable (and how to represent that)". In that case, let's just hard-code SHIFT like we did with mouse selection copy/paste. That way that feature is still in. You can take a look at `TermControl.cpp::_MouseClickHandler()`. I'll create an issue to talk about this in a separate thread.

**Comment by d-bingham** [comment]
> Hmm... well, SHIFT serves as a modifier to a classic copy. So I guess this is more of a discussion of "should modifiers be rebindable (and how to represent that)". In that case, let's just hard-code SHIFT like we did with mouse selection copy/paste. That way that feature is still in. You can take a look at `TermControl.cpp::_MouseClickHandler()`. I'll create an issue to talk about this in a separate thread.

Do you mean in the right-click copy, or for any copy key binding?  If the latter, the "standard" copy key binding of ctrl-shift-c (per @zadjii-msft above) doesn't function correctly.

I don't think using hard-coded modifiers on bindable keys is a good idea for that reason.  And if there's only one shortcut affected by the modifier, implementing it as a bindable modifier is kinda pointless.

**Comment by carlos-zamora** [comment]
> Regarding passing ctrl-c to the terminal in all cases... that's not really appropriate to clipboard stuff _per se_, and should be handled generically in the keybinding code. But in any case, I'd _hope_ the default keybinding for copy is ctrl+ins or ctrl+shift+c _precisely_ because (in my opinion) there is no elegant handling for copy being ctrl+c anyway -- you either cannot send a ^C to the terminal, or you are forced to do so when copying to the clipboard from the keyboard...

Well, the current behavior for non-Windows Terminal is (in pseudocode):
```
if (selectionActive)
{
    // copy selection
}
else
{
    // send ^C through
}
```
So I think I just figured out how we can get around this issue. We'll have to do that check when we commit that action in `AppKeyBindings.cpp::_DoAction()`. I should be able to do it and move stuff around appropriately so don't worry about it. 😊 I'll write it and submit that as a PR soon.

**Comment by carlos-zamora** [comment]
> > Hmm... well, SHIFT serves as a modifier to a classic copy. So I guess this is more of a discussion of "should modifiers be rebindable (and how to represent that)". In that case, let's just hard-code SHIFT like we did with mouse selection copy/paste. That way that feature is still in. You can take a look at `TermControl.cpp::_MouseClickHandler()`. I'll create an issue to talk about this in a separate thread.
> 
> Do you mean in the right-click copy, or for any copy key binding? If the latter, the "standard" copy key binding of ctrl-shift-c (per @zadjii-msft Mike Griese FTE above) doesn't function correctly.
> 
> I don't think using hard-coded modifiers on bindable keys is a good idea for that reason. And if there's only one shortcut affected by the modifier, implementing it as a bindable modifier is kinda pointless.

Yeah. So then let's not worry about making the modifier re-bindable. But would you be able to figure out how to detect if the SHIFT key was pressed so that we can pass that in to the `_CopyText(bool)` function?

After that, we should be good. 😊

**Comment by d-bingham** [comment]
> Yeah. So then let's not worry about making the modifier re-bindable. But would you be able to figure out how to detect if the SHIFT key was pressed so that we can pass that in to the `_CopyText(bool)` function?

I can do that, but that literally _breaks_ the keybinding, since you could no longer bind whitespace-trimming copy to ctrl-shift-c.  Can we do it in a way that actually allows whitespace-trimming copy to be able to be bound to ctrl-shift-c?

**Comment by carlos-zamora** [comment]
> > Yeah. So then let's not worry about making the modifier re-bindable. But would you be able to figure out how to detect if the SHIFT key was pressed so that we can pass that in to the `_CopyText(bool)` function?
> 
> I can do that, but that literally _breaks_ the keybinding, since you could no longer bind whitespace-trimming copy to ctrl-shift-c. Can we do it in a way that actually allows whitespace-trimming copy to be able to be bound to ctrl-shift-c?

Ok. Sorry. I've been jumping around all day. Just talked it over with @DHowett-MSFT and @zadjii-msft. Here's the plan:
- let's create a new keybinding action titled something like "CopyTextWithoutNewlines"
- then we'll hook that up like we did here, but it'll be slightly different and we'll just call `_CopyText(false)`

That way, that specific action can be bindable and we can get both functionalities in. If you feel comfortable working on it, add it in. If not, let me know and I can just add it in after this PR goes in 😊 Up to you

**Comment by d-bingham** [comment]
I can get that this evening.

**Comment by d-bingham** [comment]
Ok, "copyTextWithoutNewlines" option added.

Is it safe to add ctrl+shift+c/ctrl+shift+v as defaults for copy (with newlines) and paste?

**Comment by carlos-zamora** [comment]
> Ok, "copyTextWithoutNewlines" option added.
> 
> Is it safe to add ctrl+shift+c/ctrl+shift+v as defaults for copy (with newlines) and paste?

Awesome! Thanks!

Go for it. That shouldn't interfere with passing the `^C` along.

File: src/cascadia/TerminalApp/App.cpp [hunk 4]
```diff
@@ -935,6 +937,17 @@ namespace winrt::TerminalApp::implementation
...
     }
 
+    // Method Description:
+    // - Paste text from the Windows Clipboard to the focused terminal
+    void App::_PasteText()
+    {
+        const int focusedTabIndex = _GetFocusedTabIndex();
+        std::shared_ptr<Tab> focusedTab{ _tabs[focusedTabIndex] };
+
+        const auto control = focusedTab->GetTerminalControl();
```
Comment (carlos-zamora) [inline src/cascadia/TerminalApp/App.cpp]: >GetTerminalControl [](start = 41, length = 18)

With the Pane's PR, this got changed. So now I think you're looking for `GetFocusedTerminalControl()` :)

Comment (d-bingham) [reply src/cascadia/TerminalApp/App.cpp]: Excellent.  The lack of the method for that was mildly annoying me anyway ;)

**Comment by carlos-zamora** [comment]
Just fix the "Terminal CI (Static Analysis Build x64)" and it should be good:
`"code formatting bad, run Invoke-CodeFormat on branch"`

**Comment by d-bingham** [comment]
Got it.
