### PR TITLE
Exit the process after commandline-only invocations

### LINKED ISSUE #15443: wt --help process never exits
### Windows Terminal version

1.18.1421.0

### Windows build number

10.0.22621.0

### Other Software

_No response_

### Steps to reproduce

Run `wt --help` or `wt -v` and then close the resulting window. (The `compatibility.allowHeadless` setting doesn't appear to change anything.)

### Expected Behavior

The `WindowsTerminal.exe` process exits.

### Actual Behavior

The help/version window closes, but the process remains running.

### PR DESCRIPTION
**Pull request by zadjii-msft**
Yep it's that dumb

Closes #15443

### CODE REVIEW

File: src/cascadia/WindowsTerminal/WindowEmperor.cpp [hunk 1]
```diff
@@ -109,7 +109,7 @@ bool WindowEmperor::HandleCommandlineArgs()
         if (!res.Message.empty())
         {
             AppHost::s_DisplayMessageBox(res);
-            ExitThread(res.ExitCode);
+            ExitProcess(res.ExitCode);
```
Comment (lhecker) [inline src/cascadia/WindowsTerminal/WindowEmperor.cpp:112]: Could you call `exit(res.ExitCode)` instead? It'll correctly call any `atexit()` handlers and call `TerminateProcess` instead of `ExitProcess` for immediate shutdown.

Comment (DHowett) [reply src/cascadia/WindowsTerminal/WindowEmperor.cpp:112]: Are you _sure_ you want to run all our static deinitializers? ;)

Comment (lhecker) [reply src/cascadia/WindowsTerminal/WindowEmperor.cpp:112]: In that case I'd call `quick_exit()`. The implementation can be found at:
```
C:\Program Files (x86)\Windows Kits\10\Source\10.0.22621.0\ucrt\startup\exit.cpp
```

Comment (lhecker) [reply src/cascadia/WindowsTerminal/WindowEmperor.cpp:112]: There's also `_Exit()` btw, which is another proper C standard function. Using OS primitives here doesn't do us any favors as it breaks app verifier and other debugging tools.

**Review by lhecker — APPROVED** [review]
yay~

**Review by DHowett — APPROVED** [review]
