### PR TITLE
Selection Code Cleanup and Double Click Delimiter Runs

### LINKED ISSUE #1327: Revisit TerminalSelection to add tests, clean up, proper selection mechanics
More of a mental note of all the misc. selection stuff I need to do. Hopefully I can get this in very soon so that we can verify that nothing was broken.

- [x] Add testing for the following scenarios:
  - [x] `endSelectionPosition` being located out of bounds
- [ ] `_GetSelectionRects()` clean up
  - the pre-processing part is just a bit nasty now. There should be a way to simplify it. Need to be careful with testing this though.
- [x] Proper selection mechanics
  - when your `endSelectionPosition` is out of bounds **vertically**, the x-position should still update, but the y-position should be at the boundary
  -  when your `endSelectionPosition` is out of bounds **horizontally**, the y-position should still update, but the y-position should be at the **buffer** boundary
  - this is particularly important for #1247. As the y-position must be detected to be out of the bounds, so that's still valid. But it should be displayed as updating the x-position.

### LINKED ISSUE #2206: Bug Report: Double Click should select delimiter runs
# Environment

Caused by #1197.
More apparent in #2184.

# Steps to reproduce

1. ensure double click delimiters includes " "
2. double click on empty line

# Expected behavior

Selection should encompass entire line.

# Actual behavior

Selection encompasses one cell.

# Additional Info

This one's on me. Idk why I thought that double clicking a delimiter should only select the delimiter itself. That's not useful.

Instead, the selection seems like it should expand to the first non-delimiter in either direction (exclusive range). For example,
`O` is non-delimiter
`X` is delimiter
Double clicking on any of the X would result in the following selection (denoted by [ and ])
`OOOXXXXXXOOO`
`OOO[XXXXXX]OOO`

### LINKED ISSUE #2261: Bug Report: Failing Wide Glyph Tests (x86)
Not sure why x86 wide glyph tests are failing in CI. They work fine locally. Need to investigate what's going on here.

### PR DESCRIPTION
**Pull request by carlos-zamora**
## Summary of the Pull Request

Just some housekeeping work on our selection. Added a few more tests and refactored some of the functionality to improve code clarity. 

Reenabled x86 tests. They work on my machine. I hope they work on CI?

Added support for double clicking delimiter runs.

Double Click Delimiter runs now operate as follows. Characters are separated into 3 classes:
- class 0: spaces and control characters
- class 1: delimiters imported from settings
- class 2: all other characters
If you double click a cell, the selection will expand until the class of the next cell differs from the preceding one.

This is slightly different than before in that the following example will only highlight the ">" char instead of the ">" and all the surrounding spaces:
```
C:\Terminal>
           ^
double click here
```

## References
N/A

## PR Checklist
* [x] Closes #1327 
* [x] Closes #2261 
* [x] Closes #2206 
* [x] CLA signed
* [x] Tests added/passed
* [x] ~Requires documentation to be updated~
* [x] I am a core contributor

## Detailed Description of the Pull Request / Additional comments
Added some testing to ensure we don't crash on out-of-bounds selection anchors.
Consolidated the vertical offset for the anchors since they're always the same.
Broke up `GetSelectionRects()` into a more clear format with several helper methods.

## Validation Steps Performed
All tests pass. I manually did some ALT+selections and regular selections w/ and w/out the scroll area and it still seems fine.

### CODE REVIEW

File: src/cascadia/TerminalCore/TerminalSelection.cpp [hunk 1]
```diff
@@ -19,77 +19,116 @@ std::vector<SMALL_RECT> Terminal::_GetSelectionRects() const
...
+{
+    const auto row = selectionRow.Top;
 
-        // expand selection for Double/Triple Click
-        if (_multiClickSelectionMode == SelectionExpansionMode::Word)
+    // expand selection for Double/Triple Click
+    if (_multiClickSelectionMode == SelectionExpansionMode::Word)
+    {
+        const auto cellChar = _buffer->GetCellDataAt({ _selectionAnchor.X, row })->Chars();
+        if (_isSingleCellSelection() && _isWordDelimiter(cellChar))
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalCore/TerminalSelection.cpp]: this may be a trivial time and place to fix #2206 too

Comment (carlos-zamora) [reply src/cascadia/TerminalCore/TerminalSelection.cpp]: Done. Makes the code look nicer too.

File: src/cascadia/TerminalCore/Terminal.hpp [hunk 2]
```diff
@@ -166,14 +166,19 @@ class Microsoft::Terminal::Core::Terminal final :
         Word,
         Line
     };
+    enum DelimiterClass
```
Comment (miniksa) [inline src/cascadia/TerminalCore/Terminal.hpp]: Prefer `enum class` to bare `enum`.

File: src/cascadia/TerminalCore/TerminalSelection.cpp [hunk 3]
```diff
@@ -12,84 +13,126 @@ using namespace Microsoft::Terminal::Core;
 // - A vector of rectangles representing the regions to select, line by line. They are absolute coordinates relative to the buffer origin.
 std::vector<SMALL_RECT> Terminal::_GetSelectionRects() const
 {
-    std::vector<SMALL_RECT> selectionArea;
+    std::vector<SMALL_RECT> result = {};
```
Comment (miniksa) [inline src/cascadia/TerminalCore/TerminalSelection.cpp]:
```suggestion
    std::vector<SMALL_RECT> result;
```

File: src/cascadia/TerminalCore/TerminalSelection.cpp [hunk 4]
```diff
@@ -12,84 +13,126 @@ using namespace Microsoft::Terminal::Core;
...
+        // NOTE: (0,0) is the top-left of the screen
+        // the physically "higher" coordinate is closer to the top-left
+        // the physically "lower" coordinate is closer to the bottom-right
+        auto [higherCoord, lowerCoord] = _PreprocessSelectionCoords();
+
+        SHORT selectionRectSize;
+        THROW_IF_FAILED(ShortSub(lowerCoord.Y, higherCoord.Y, &selectionRectSize));
+        THROW_IF_FAILED(ShortAdd(selectionRectSize, 1, &selectionRectSize));
+
+        std::vector<SMALL_RECT> selectionArea = {};
```
Comment (miniksa) [inline src/cascadia/TerminalCore/TerminalSelection.cpp]:
```suggestion
        std::vector<SMALL_RECT> selectionArea;
```

File: src/cascadia/TerminalCore/TerminalSelection.cpp [hunk 5]
```diff
@@ -12,84 +13,126 @@ using namespace Microsoft::Terminal::Core;
...
+        selectionArea.reserve(selectionRectSize);
+        for (auto row = higherCoord.Y; row <= lowerCoord.Y; row++)
```
Comment (miniksa) [inline src/cascadia/TerminalCore/TerminalSelection.cpp]:
```suggestion
        for (const auto row = higherCoord.Y; row <= lowerCoord.Y; row++)
```

File: src/cascadia/TerminalCore/TerminalSelection.cpp [hunk 6]
```diff
@@ -12,84 +13,126 @@ using namespace Microsoft::Terminal::Core;
...
-        return selectionArea;
+        return result;
     }
 
+    try
+    {
+        // NOTE: (0,0) is the top-left of the screen
+        // the physically "higher" coordinate is closer to the top-left
+        // the physically "lower" coordinate is closer to the bottom-right
+        auto [higherCoord, lowerCoord] = _PreprocessSelectionCoords();
```
Comment (miniksa) [inline src/cascadia/TerminalCore/TerminalSelection.cpp]:
```suggestion
        const auto [higherCoord, lowerCoord] = _PreprocessSelectionCoords();
```

File: src/cascadia/TerminalCore/TerminalSelection.cpp [hunk 7]
```diff
@@ -12,84 +13,126 @@ using namespace Microsoft::Terminal::Core;
 // - A vector of rectangles representing the regions to select, line by line. They are absolute coordinates relative to the buffer origin.
 std::vector<SMALL_RECT> Terminal::_GetSelectionRects() const
```
Comment (miniksa) [inline src/cascadia/TerminalCore/TerminalSelection.cpp]:
```suggestion
std::vector<SMALL_RECT> Terminal::_GetSelectionRects() const noexcept
```

File: src/cascadia/TerminalCore/TerminalSelection.cpp [hunk 8]
```diff
@@ -332,23 +379,35 @@ COORD Terminal::_ExpandDoubleClickSelectionLeft(const COORD position) const
...
-// - expand the double click selection to the right (stopped by delimiter)
+// - expand the double click selection to the right
+// - stopped by delimiter if started on delimiter
 // Arguments:
-// - position: viewport coordinate for selection
+// - position: buffer coordinate for selection
 // Return Value:
 // - updated copy of "position" to new expanded location (with vertical offset)
-COORD Terminal::_ExpandDoubleClickSelectionRight(const COORD position) const
+const COORD Terminal::_ExpandDoubleClickSelectionRight(const COORD position) const
```
[the remark this answers is not in the document]
Comment (miniksa) [reply src/cascadia/TerminalCore/TerminalSelection.cpp]: Given `COORD` is a struct of primitive types with only implicit definitions of its copy/move operators generated by the compiler.... this should be doing nothing and could be dropped.

File: src/cascadia/TerminalCore/TerminalSelection.cpp [hunk 9]
```diff
@@ -358,14 +417,26 @@ COORD Terminal::_ExpandDoubleClickSelectionRight(const COORD position) const
...
-// - check if buffer cell data contains delimiter for double click selection
+// - get delimiter class for buffer cell data
+// - used for double click selection
 // Arguments:
 // - cellChar: the char saved to the buffer cell under observation
 // Return Value:
-// - true if cell data contains the delimiter.
-const bool Terminal::_isWordDelimiter(std::wstring_view cellChar) const
+// - the delimiter class for the given char
+const Terminal::DelimiterClass Terminal::_GetDelimiterClass(const std::wstring_view cellChar) const noexcept
```
Comment (dlong11) [inline src/cascadia/TerminalCore/TerminalSelection.cpp]: Returning a const here doesn't make sense.  Same comment as minks above.

File: src/cascadia/TerminalCore/TerminalSelection.cpp (hunk 5 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalCore/TerminalSelection.cpp]: Can't do this one. Incrementing row at the end of the line.

File: src/cascadia/TerminalCore/TerminalSelection.cpp [hunk 10]
```diff
@@ -3,93 +3,136 @@
...
+// NOTE: (0,0) is top-left so vertical comparison is inverted
+// Arguments:
+// - row: the buffer y-value under observation
+// - higherCoord: the physically "higher" coordinate (closer to the top-left)
+// - lowerCoord: the physically "lower" coordinate (closer to the bottom-right)
+// Return Value:
+// - the selection row needed for rendering
+SMALL_RECT Terminal::_GetSelectionRow(const SHORT row, const COORD higherCoord, const COORD lowerCoord) const
+{
+    SMALL_RECT selectionRow;
```
Comment (dlong11) [inline src/cascadia/TerminalCore/TerminalSelection.cpp]: nit: Even though each member of SMALL_RECT gets set currently it is best practice to always initialize a struct.   I am not sure what the team's stance is on this though.

 SMALL_RECT selectionRow{0};

File: src/cascadia/TerminalCore/TerminalSelection.cpp [hunk 11]
```diff
@@ -19,77 +20,108 @@ std::vector<SMALL_RECT> Terminal::_GetSelectionRects() const
...
+    {
+        selectionRow.Left = _ExpandDoubleClickSelectionLeft({ selectionRow.Left, row }).X;
+        selectionRow.Right = _ExpandDoubleClickSelectionRight({ selectionRow.Right, row }).X;
     }
-    return selectionArea;
+    else if (_multiClickSelectionMode == SelectionExpansionMode::Line)
+    {
+        selectionRow.Left = _buffer->GetSize().Left();
+        selectionRow.Right = _buffer->GetSize().RightInclusive();
+    }
```
[the remark this answers is not in the document]
Comment (dlong11) [reply src/cascadia/TerminalCore/TerminalSelection.cpp]: @carlos-zamora @DHowett-MSFT side note: The check for cell here with a do nothing is kind of ugly but it does tell future devs looking at the code that the "cell" case was considered.   One thing I miss in the MSVC C++ compiler is the [-Wswitch-enum](https://clang.llvm.org/docs/DiagnosticsReference.html#wswitch-enum) warning in clang.  If the compiler had this warning then you could make this a switch statement and cover each enum case. (including the Cell's do nothing case) When this flag is used it really helps by giving you compile errors when enum values are added.   It forces you to look at each usage and fix potential errors.

Since the compiler doesn't yet support this we don't have that luxury.   Even so I think adding the do nothing case is still useful for future developers who don't know the history of the code.

[the remark this answers is not in the document]
Comment (dlong11) [reply src/cascadia/TerminalCore/TerminalSelection.cpp]: I did a quick check and MSVC does support this warning - [C4062](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4062?view=vs-2019), but it is off by default.   It is a shame because this warning can be very useful when adding new values to enums/enum classes.

File: src/cascadia/UnitTests_TerminalCore/SelectionTest.cpp [hunk 12]
```diff
@@ -94,8 +94,123 @@ namespace TerminalCoreUnitTests
...
+                Terminal term;
+                DummyRenderTarget emptyRT;
+                term.Create({ 10, 10 }, scrollback, emptyRT);
+
+                term.TripleClickSelection(maxCoord);
+                ValidateSelection(term, expected);
+            };
+
+            // Test with no scrollback
+            ValidateSingleClickSelection(0, { 9, 9, 9, 9 });
```
Comment (miniksa) [inline src/cascadia/UnitTests_TerminalCore/SelectionTest.cpp]: Given you're testing 6 things in one test, you might consider having a few Log::Comments sprinkled in so one can tell which subsegment of this has failed should the test fail.

File: src/cascadia/UnitTests_TerminalCore/SelectionTest.cpp [hunk 13]
```diff
@@ -94,8 +94,123 @@ namespace TerminalCoreUnitTests
...
+            DummyRenderTarget emptyRT;
+            term.Create({ 10, 10 }, 0, emptyRT);
+
+            auto viewport = term.GetViewport();
+            const SHORT leftBoundary = viewport.Left();
+            const SHORT rightBoundary = viewport.RightInclusive();
+            const SHORT topBoundary = viewport.Top();
+            const SHORT bottomBoundary = viewport.BottomInclusive();
+
+            auto ValidateSelection = [&](SMALL_RECT expected) {
```
Comment (miniksa) [inline src/cascadia/UnitTests_TerminalCore/SelectionTest.cpp]: This lambda looks REALLY CLOSE to the one above. Should it just be a helper method in the test class instead of a lambda defined in each of these two tests?

File: src/cascadia/UnitTests_TerminalCore/SelectionTest.cpp [hunk 14]
```diff
@@ -94,8 +94,123 @@ namespace TerminalCoreUnitTests
...
+                // Validate selection area
+                VERIFY_ARE_EQUAL(selectionRects.size(), static_cast<size_t>(1));
+                auto selection = viewport.ConvertToOrigin(selectionRects[0]).ToInclusive();
+
+                VERIFY_ARE_EQUAL(selection, expected);
+            };
+
+            // Case 1: Simulate click past right (x,y) = (20,5)
+            // should clamp to right boundary
+            term.SetSelectionAnchor({ 20, 5 });
```
Comment (miniksa) [inline src/cascadia/UnitTests_TerminalCore/SelectionTest.cpp]: Probably a few log subcomments here too so we can see which specific subcase failed.
