### PR TITLE
CUU and CUD should not move "across" margins.

### LINKED ISSUE #2929: CUU and CUD should not move "across" margins
# Environment

Windows build number: Version 10.0.18362.295
Also tested with a recent commit 7faf3342e0187841d590fd018452c5c69fd52271

# Steps to reproduce

In a conhost WSL shell, execute the following command:

    echo -e "\e[6;19r\e[24H\e[99ACUU\e[1H\e[99BCUD\e[r"

This does the following:

- sets the top and bottom [`DECSTBM`](https://vt100.net/docs/vt510-rm/DECSTBM.html) margins to 6 and 19
- moves to line 24 (i.e. below the bottom margin)
- executes the [`CUU`](https://vt100.net/docs/vt510-rm/CUU.html) sequence with a count of 99, to move up 99 lines
- writes out *CUU*
- moves to line 1 (i.e. above the top margin)
- executes the [`CUD`](https://vt100.net/docs/vt510-rm/CUD.html) sequence with a count of 99, to move down 99 lines
- writes out *CUD*

# Expected behavior

Quoting from the DEC STD 070 manual:

> If the Active Position is at or below the Top Margin when the CUU control is executed, and an attempt is made to move the Active Position above the Top Margin, the control will be executed until the Active Position reaches the Top Margin. The Active Position will not move beyond the Top Margin. 

Similarly for the `CUD` command:

> If the Active Position is at or above the Bottom Margin when the CUD control is executed, and an attempt is made to move the Active Position below the Bottom Margin, the control will be executed until the Active Position reaches the Bottom Margin. The Active position will not move beyond the Bottom Margin. 

So I would expect the `CUU` sequence to stop on line 6, the top margin, and the `CUB` sequence to stop on line 19, the bottom margin.

This is what the output looks like in XTerm:

image

# Actual behavior

In the Windows console, the movement isn't constrained by the margins. As a result, the `CUU` sequences ends up at the top of the viewport, and the `CUD` sequences ends up at the bottom.

image

Note that this isn't a regression of #170. We do get it right if the initial cursor position was inside the margins. It's just when it starts off outside the margins that it's not being constrained.

The complication is that you sometimes *don't* want the cursor position constrained. For example, if you're moving up (with `CUU`), and you started off above the top margin, then there's no need to constrain the position below that margin.

### PR DESCRIPTION
**Pull request by zadjii-msft**
## Summary of the Pull Request

If we're moving the cursor up, its vertical movement should be stopped at the top margin. It should not magically jump up to the bottom margin. Similarly, this applies to moving down and the bottom margin. Furthermore, this constraint should always apply, not just when the start position is within BOTH margins

## References
#170

## PR Checklist
* [x] Closes #2929
* [x] I work here
* [x] Tests added/passed
* [n/a] Requires documentation to be updated

## Detailed Description of the Pull Request / Additional comments

Shout-out to @j4james as always, for keeping the VT implementation honest 😋

### CODE REVIEW

File: src/host/getset.cpp [hunk 1]
```diff
@@ -1417,18 +1417,45 @@ void DoSrvPrivateAllowCursorBlinking(SCREEN_INFORMATION& screenInfo, const bool
...
+        // See microsoft/terminal#2929 - If the cursor is _below_ the top
+        // margin, it should stay below the top margin. If it's _above_ the
+        // bottom, it should stay above the bottom. Cursor movements that stay
+        // outside the margins shouldn't necessarily be affected. For example,
+        // moving up while below the bottom margin shouldn't just jump straight
+        // to the bottom margin. See
+        // ScreenBufferTests::CursorUpDownOutsideMargins for a test of that
+        // behavior.
+        const bool cursorBelowTop = cursorY > lo;
+        const bool cursorAboveBottom = cursorY < hi;
```
Comment (j4james) [inline src/host/getset.cpp]: I think these are both off by one. If the cursor Y position exactly matches the top margin, it is still "inside" that margin, and shouldn't be able to move up. Similarly, if it exactly matches the bottom margin, it shouldn't be able to move down.

File: src/host/getset.cpp [hunk 2]
```diff
@@ -1417,18 +1417,45 @@ void DoSrvPrivateAllowCursorBlinking(SCREEN_INFORMATION& screenInfo, const bool
...
+        if (cursorAboveBottom)
         {
-            const auto margins = screenInfo.GetAbsoluteScrollMargins().ToInclusive();
-            const auto v = clampedPos.Y;
-            const auto lo = margins.Top;
-            const auto hi = margins.Bottom;
-            clampedPos.Y = std::clamp(v, lo, hi);
+            try
+            {
+                clampedPos.Y = std::min(newY, hi);
```
Comment (j4james) [inline src/host/getset.cpp]: If the cursor is inside both margins, this line can potentially overwrite the `clampedPos.Y` that was adjusted in the condition above, since `newY` holds the original value. It may be easier to drop the `newY` variable and always just work with `clampedPos.Y` directly.

**Comment by DHowett-MSFT** [comment]
(love the branch name)
