### PR TITLE
Expand env. vars in backgroundImage

### LINKED ISSUE #2922: Terminal takes an unexpected dirt nap when backgroundImage contains environment variables
I literally can't believe we're not expanding environment variables.

### PR DESCRIPTION
**Pull request by bitcrazed**
## Summary of the Pull Request
* Adds HasBackgroundImage() and GetExpandedBackgroundImagePath() to
Profiles.cpp/h
* Fills Terminal Settings with expanded path, rather than path value
from profiles.json
* Adds simple regression tests to detect and fail if this fix is
circumvented in the future

## PR Checklist
* [X] Closes #2922
* [X] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [X] Tests added/passed
* [ ] Requires documentation to be updated
* [X] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Validation Steps Performed
* Comprehensive debugging with expected, unexpected and empty path strings
* Tests executed & validated

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
:crying: :cry: why'd you make a new PR and not just force push the old one

File: src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp [hunk 1]
```diff
@@ -1366,4 +1369,37 @@ namespace TerminalAppLocalTests
...
+                {
+                    "name": "profile0",
+                    "icon": "%WINDIR%\\System32\\x_80.png"
+                }
+            ]
+        })" };
+
+        VerifyParseSucceeded(settingsJson);
+        CascadiaSettings settings;
+        settings._ParseJsonString(settingsJson, false);
```
Comment (DHowett-MSFT) [inline src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp]: these tests don't actually test that the value got turned into something

Comment (bitcrazed) [reply src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp]: Why a new PR? Sometimes it's just quicker to kill & recreate rather than perform surgery ;)

Agree re. tests. Will update them tomorrow.

**Comment by DHowett-MSFT** [comment]
I don't think these tests are going to pass. We expand the env vars on _read_, not on _storage_. This is by design so that if the env vars change at runtime they'll be reflected.

**Comment by DHowett-MSFT** [comment]
I have no idea why these tests pass.

**Comment by bitcrazed** [comment]
Interestingly, these tests should NOT be passing - they're failing on my box. 

If they are passing, there's a good chance our tests aren't running correctly.

**Comment by DHowett-MSFT** [comment]
This latest commit says "ignore don't look at", but I can't tell _why_ we shouldn't -- it looks like they answer the creative brief?
Do the tests pass on your machine?

File: src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp [hunk 2]
```diff
@@ -1366,4 +1369,46 @@ namespace TerminalAppLocalTests
...
+        GlobalAppSettings globalSettings{};
+        auto terminalSettings = settings._profiles.at(0).CreateTerminalSettings(globalSettings.GetColorSchemes());
+        VERIFY_ARE_EQUAL(expectedPath, terminalSettings.BackgroundImage());
```
Comment (DHowett-MSFT) [inline src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp]: test is called "icon", this checks background ;P

**Comment by bitcrazed** [comment]
"Do the tests pass on your machine?"

Nope, hence "In-progress. Incomplete. Ignore" ;)

File: src/cascadia/LocalTests_TerminalApp/precomp.h [hunk 3]
```diff
@@ -25,6 +25,8 @@ Author(s):
 #undef GetCurrentTime
 #endif
 
+#include <wil/win32_helpers.h>
```
Comment (zadjii-msft) [inline src/cascadia/LocalTests_TerminalApp/precomp.h]: This is curious to me that this isn't needed in `LibraryIncludes`, and just adding it here works...

**Comment by bitcrazed** [comment]
Okay y'all. The tests now run too - had to layer JSON into userSettings. Please final-review and approve if no more changes needed. TIA.

File: src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp [hunk 4]
```diff
@@ -1366,4 +1369,49 @@ namespace TerminalAppLocalTests
...
+            "profiles": [
+                {
+                    "name": "profile0",
+                    "icon": "%WINDIR%\\System32\\x_80.png"
+                }
+            ]
+        })" };
+
+        VerifyParseSucceeded(settingsJson);
+        CascadiaSettings settings;
```
Comment (carlos-zamora) [inline src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp]:
```suggestion
        CascadiaSettings settings{};
```

File: src/cascadia/LocalTests_TerminalApp/precomp.h (hunk 3 above)
Comment (bitcrazed) [reply src/cascadia/LocalTests_TerminalApp/precomp.h]: Wasn't required to build & test. Feel free to include in future if necessary.

File: src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp (hunk 2 above)
Comment (bitcrazed) [reply src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp]: Not any longer. That was part of the "in-progress, ignore" commit

File: src/cascadia/LocalTests_TerminalApp/precomp.h (hunk 3 above)
Comment (DHowett-MSFT) [reply src/cascadia/LocalTests_TerminalApp/precomp.h]: I'm sorry, you added an include that _isn't required to build or test_?

... can we just delete it?

File: src/cascadia/TerminalApp/Profile.cpp [hunk 5]
```diff
@@ -208,9 +208,9 @@ TerminalSettings Profile::CreateTerminalSettings(const std::unordered_map<std::w
         terminalSettings.ScrollState(result);
     }
 
-    if (_backgroundImage)
+    if (HasBackgroundImage())
     {
-        terminalSettings.BackgroundImage(_backgroundImage.value());
+        terminalSettings.BackgroundImage(GetExpandedBackgroundImagePath().c_str());
```
[the remark this answers is not in the document]
Comment (bitcrazed) [reply src/cascadia/TerminalApp/Profile.cpp]: Want to make intent clear and unambiguous

File: src/cascadia/LocalTests_TerminalApp/precomp.h (hunk 3 above)
Comment (bitcrazed) [reply src/cascadia/LocalTests_TerminalApp/precomp.h]: Ohhhhhh ... duh ... yeah ... ahem ... it's been a long week.  Deleting now ;)

Comment (miniksa) [reply src/cascadia/LocalTests_TerminalApp/precomp.h]: Sorry, I'm unclear why this wil thing is still here and not in libraryincludes?

**Comment by carlos-zamora** [comment]
@DHowett-MSFT putting this on your radar 😊

File: src/cascadia/LocalTests_TerminalApp/precomp.h (hunk 3 above)
Comment (DHowett-MSFT) [reply src/cascadia/LocalTests_TerminalApp/precomp.h]: RICH WHY IS THIS HERE AND NOT IN LIBRARYINCLUDES

Comment (bitcrazed) [reply src/cascadia/LocalTests_TerminalApp/precomp.h]: 'CAUSE I WAS OOF LAST WEEK ON VACATION AND SWAMPED THE WEEK BEFORE BECAUSE I WAS GOING ON VACATION.

MR. SHOUTY! ;)

Comment (bitcrazed) [reply src/cascadia/LocalTests_TerminalApp/precomp.h]: Made the change. Plz. review.

**Comment by DHowett-MSFT** [comment]
Congrats!
