### PR TITLE
Fix missing paths when items dropped from archive

### LINKED ISSUE #14628: Dragging and dropping paths to terminal stops at 16 items
### Windows Terminal version

1.15.2713.0

### Windows build number

10.0.22000.0

### Other Software

_No response_

### Steps to reproduce

1. Highlight more than 16 items from an archive (7zip, WinRAR, etc.)
2. Drag and drop highlighted items into terminal

### Expected Behavior

Should write paths equal to the amount of items highlighted

### Actual Behavior

Only writes up to 16 paths

### PR DESCRIPTION
**Pull request by jiejasonliu**
Grab all paths from `DROPFILES` struct provided in drag event data

`GetStorageItemsAsync()` only giving up to 16 items when items are dropped from any archives
- When this occurs, we should look into `FileDrop` key for a stream of the [`DROPFILES struct`](https://learn.microsoft.com/en-us/windows/win32/shell/clipboard#cf_hdrop)
- This struct contains a null-character delimited string of paths which we can just read out

## Validation Steps Performed
* [X] Unit tests pass locally
* [X] Drag and drop paths work for both archives and non-archives files, folders, shortcuts, etc.

Closes #14628

### CODE REVIEW

**Comment by jiejasonliu** [comment]
@microsoft-github-policy-service agree

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 1]
```diff
@@ -2526,16 +2527,55 @@ namespace winrt::Microsoft::Terminal::Control::implementation
...
+                    if (fileDropData != nullptr)
+                    {
+                        auto stream = fileDropData.as<IRandomAccessStream>();
+                        stream.Seek(0);
+
+                        uint32_t streamSize = (uint32_t)stream.Size();
+                        Buffer buf(streamSize);
+                        auto buffer = co_await stream.ReadAsync(buf, streamSize, InputStreamOptions::None);
+
+                        const HGLOBAL hGlobal = buffer.data();
```
Comment (zadjii-msft) [inline src/cascadia/TerminalControl/TermControl.cpp:2546]: Does this need to be wrapped up in some wort of `wil` smart object to manage its lifetime? Kinda seems like we'd just leak it here, but I don't know who owns it's lifetime.

**Review by zadjii-msft — APPROVED** [review]
I mean, I see how this works, but is there any documentation on this? It seems like ~ m a g i c ~ that getting the `"FileDrop"` out of a `DataPackageView` just so happens to have the value of a `HDROP` embedded in the stream. It's just crazy.

Though, https://learn.microsoft.com/en-us/uwp/api/Windows.ApplicationModel.DataTransfer.StandardDataFormats?view=winrt-22621 does list a bunch of other magic strings that seem to return `HGLOBAL`s, so I'm not doubting it, I'd just like to have an official reference to point to.

**Comment by jiejasonliu** [comment]
> I mean, I see how this works, but is there any documentation on this?

I totally get that and I'll try my best to compile all the resources I've used.
Admittedly, I can't give you exact answers since a lot of things are closed source.
It really came down to relying on older references and anticipating backward compatibility was kept.

> just so happens to have the value of a HDROP 

My initial discovery was looking through the data package's `AvailableFormats` property. 

Upon finding `FileDrop`, I dug into the .NET reference source and [found this line of code](https://referencesource.microsoft.com/#PresentationCore/Core/CSharp/System/Windows/DataObject.cs,1803) where the callee stores it in an `HDROP` format. So yes, an `HDROP` embedded directly in the stream!

Then combining these [(one)](https://learn.microsoft.com/en-us/windows/win32/shell/datascenarios#extracting-the-file-names-from-the-data-object) [(two)](https://learn.microsoft.com/en-us/windows/win32/shell/clipboard#cf_hdrop) sources, I was able to successfully parse the file paths out. 
Technically, you _could_ manually parse them, but the intrinsic `DragQueryFile` does exactly that for you.

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 1 above)
Comment (jiejasonliu) [reply src/cascadia/TerminalControl/TermControl.cpp:2546]: I thought that too, but it turns out that `IBuffer.data()` is a `cppwinrt` extension method [implemented directly as](https://github.com/microsoft/cppwinrt/blob/a2131900b9dc9a317ea041abc2927656246089dd/cppwinrt/code_writers.h#L1307):
```cpp
auto data() const
{
    uint8_t* data{};
    static_cast<D const&>(*this).template as<IBufferByteAccess>()->Buffer(&data);
    return data;
}
```
Meaning that the lifetime of the pointer ["is controlled by the lifetime of the buffer object."](https://learn.microsoft.com/en-us/cpp/cppcx/obtaining-pointers-to-data-buffers-c-cx?view=msvc-170#getpointertopixeldata)
With the way we initialized the buffer, it has a scoped lifetime which means we should be safe from leaks.

Now, I admit I have no idea how `Buffer` is implemented internally (closed-source...) so I can't say whether having it stack allocated or heap allocated. I imagine that the data is marshalled through and we are really only storing a pointer (COM pointer?) on the stack as it is.

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 2]
```diff
@@ -2526,16 +2527,55 @@ namespace winrt::Microsoft::Terminal::Control::implementation
...
                 {
-                    // Join the paths with spaces
-                    if (!allPaths.empty())
+                    auto fileDropData = co_await e.DataView().GetDataAsync(winrt::hstring{ L"FileDrop" });
+                    if (fileDropData != nullptr)
+                    {
+                        auto stream = fileDropData.as<IRandomAccessStream>();
+                        stream.Seek(0);
+
+                        uint32_t streamSize = (uint32_t)stream.Size();
```
Comment (carlos-zamora) [inline src/cascadia/TerminalControl/TermControl.cpp:2542]:
```suggestion
                        const uint32_t streamSize = gsl::narrow_cast<uint32_t>stream.Size();
```

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 3]
```diff
@@ -2526,16 +2527,55 @@ namespace winrt::Microsoft::Terminal::Control::implementation
...
+                        Buffer buf(streamSize);
+                        auto buffer = co_await stream.ReadAsync(buf, streamSize, InputStreamOptions::None);
```
Comment (carlos-zamora) [inline src/cascadia/TerminalControl/TermControl.cpp:2544]:
```suggestion
                        const auto buffer = co_await stream.ReadAsync(buf, streamSize, InputStreamOptions::None);
```

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 4]
```diff
@@ -2526,16 +2527,55 @@ namespace winrt::Microsoft::Terminal::Control::implementation
...
-                    // Join the paths with spaces
-                    if (!allPaths.empty())
+                    auto fileDropData = co_await e.DataView().GetDataAsync(winrt::hstring{ L"FileDrop" });
+                    if (fileDropData != nullptr)
+                    {
+                        auto stream = fileDropData.as<IRandomAccessStream>();
+                        stream.Seek(0);
+
+                        uint32_t streamSize = (uint32_t)stream.Size();
+                        Buffer buf(streamSize);
```
Comment (carlos-zamora) [inline src/cascadia/TerminalControl/TermControl.cpp:2543]:
```suggestion
                        const Buffer buf(streamSize);
```

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 5]
```diff
@@ -2526,16 +2527,55 @@ namespace winrt::Microsoft::Terminal::Control::implementation
...
+                        auto buffer = co_await stream.ReadAsync(buf, streamSize, InputStreamOptions::None);
+
+                        const HGLOBAL hGlobal = buffer.data();
+                        auto count = DragQueryFile((HDROP)hGlobal, 0xFFFFFFFF, nullptr, 0);
```
Comment (carlos-zamora) [inline src/cascadia/TerminalControl/TermControl.cpp:2547]:
```suggestion
                        const auto count = DragQueryFile((HDROP)hGlobal, 0xFFFFFFFF, nullptr, 0);
```

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 6]
```diff
@@ -2526,16 +2527,55 @@ namespace winrt::Microsoft::Terminal::Control::implementation
...
+                        fullPaths.reserve(count);
+
+                        for (unsigned int i = 0; i < count; i++)
+                        {
+                            WCHAR szPath[MAX_PATH];
+                            auto charsCopied = DragQueryFile((HDROP)hGlobal, i, szPath, MAX_PATH);
```
Comment (carlos-zamora) [inline src/cascadia/TerminalControl/TermControl.cpp:2553]:
```suggestion
                            const auto charsCopied = DragQueryFile((HDROP)hGlobal, i, szPath, MAX_PATH);
```

**Review by carlos-zamora — APPROVED** [review]
Looks great! Just sprinkled a few `const` throughout. Thanks!

**Comment by carlos-zamora** [comment]
@msftbot merge this in 20 minutes

**Comment by carlos-zamora** [comment]
Extracted from PR body:

## Attachments

https://user-images.githubusercontent.com/29434693/211170533-03251319-e746-4b00-90e6-891c34349957.mp4

https://user-images.githubusercontent.com/29434693/211170538-fa80ef89-42d7-44c6-ae05-e0661efeeb51.mp4

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 7]
```diff
@@ -2526,16 +2527,55 @@ namespace winrt::Microsoft::Terminal::Control::implementation
...
                 {
-                    // Join the paths with spaces
-                    if (!allPaths.empty())
+                    auto fileDropData = co_await e.DataView().GetDataAsync(winrt::hstring{ L"FileDrop" });
+                    if (fileDropData != nullptr)
+                    {
+                        auto stream = fileDropData.as<IRandomAccessStream>();
+                        stream.Seek(0);
+
+                        const uint32_t streamSize = gsl::narrow_cast<uint32_t>stream.Size();
```
Comment (carlos-zamora) [inline src/cascadia/TerminalControl/TermControl.cpp:2542]:
```suggestion
                        const uint32_t streamSize = gsl::narrow_cast<uint32_t>(stream.Size());
```
derp, this one's on me. Sorry!

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 8]
```diff
@@ -2526,16 +2527,55 @@ namespace winrt::Microsoft::Terminal::Control::implementation
...
+                        const Buffer buf(streamSize);
+                        const auto buffer = co_await stream.ReadAsync(buf, streamSize, InputStreamOptions::None);
+
+                        const HGLOBAL hGlobal = buffer.data();
+                        const auto count = DragQueryFile((HDROP)hGlobal, 0xFFFFFFFF, nullptr, 0);
```
Comment (DHowett) [inline src/cascadia/TerminalControl/TermControl.cpp:2547]:
```suggestion
                        const auto count = DragQueryFileW(static_cast<HDROP>(hGlobal), 0xFFFFFFFF, nullptr, 0);
```

two changes - explicitly use the `W` API, and avoid a C-style cast

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 9]
```diff
@@ -2526,16 +2527,55 @@ namespace winrt::Microsoft::Terminal::Control::implementation
...
+                        fullPaths.reserve(count);
+
+                        for (unsigned int i = 0; i < count; i++)
+                        {
+                            WCHAR szPath[MAX_PATH];
+                            const auto charsCopied = DragQueryFile((HDROP)hGlobal, i, szPath, MAX_PATH);
+
+                            if (charsCopied > 0)
+                            {
+                                fullPaths.push_back(std::wstring{ szPath });
```
Comment (DHowett) [inline src/cascadia/TerminalControl/TermControl.cpp:2557]:
```suggestion
                                fullPaths.emplace_back(szPath);
```
one change - emplace so that the string can be constructed directly inside the vector rather than constructed and moved/copied in

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 10]
```diff
@@ -2526,16 +2527,55 @@ namespace winrt::Microsoft::Terminal::Control::implementation
...
+                        const auto buffer = co_await stream.ReadAsync(buf, streamSize, InputStreamOptions::None);
+
+                        const HGLOBAL hGlobal = buffer.data();
+                        const auto count = DragQueryFile((HDROP)hGlobal, 0xFFFFFFFF, nullptr, 0);
+                        fullPaths.reserve(count);
+
+                        for (unsigned int i = 0; i < count; i++)
+                        {
+                            WCHAR szPath[MAX_PATH];
+                            const auto charsCopied = DragQueryFile((HDROP)hGlobal, i, szPath, MAX_PATH);
```
Comment (DHowett) [inline src/cascadia/TerminalControl/TermControl.cpp:2553]:
```suggestion
                            const auto charsCopied = DragQueryFileW(static_cast<HDROP>(hGlobal), i, szPath, MAX_PATH);
```

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 11]
```diff
@@ -2526,16 +2527,55 @@ namespace winrt::Microsoft::Terminal::Control::implementation
...
+                        }
+                    }
+                }
+                else
+                {
+                    fullPaths.reserve(items.Size());
+                    for (auto item : items)
                     {
-                        allPaths += L" ";
+                        fullPaths.push_back(std::wstring{ item.Path() });
```
Comment (DHowett) [inline src/cascadia/TerminalControl/TermControl.cpp:2567]:
```suggestion
                        fullPaths.emplace_back(item.Path());

```

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 12]
```diff
@@ -2526,16 +2527,55 @@ namespace winrt::Microsoft::Terminal::Control::implementation
...
                     }
+                }
 
-                    std::wstring fullPath{ item.Path() };
+                std::wstring allPathsString;
+                for (auto fullPath : fullPaths)
```
Comment (DHowett) [inline src/cascadia/TerminalControl/TermControl.cpp:2572]:
```suggestion
                for (auto& fullPath : fullPaths)
```

No point taking an extra copy if we don't need to!

**Review by DHowett — APPROVED** [review]
Few style notes, otherwise: Thanks so much for doing this!

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 1 above)
Comment (DHowett) [reply src/cascadia/TerminalControl/TermControl.cpp:2546]: This seems totally safe; thanks for the explanation!

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 13]
```diff
@@ -2562,10 +2562,9 @@ namespace winrt::Microsoft::Terminal::Control::implementation
                 else
                 {
                     fullPaths.reserve(items.Size());
-                    for (auto item : items)
```
Comment (DHowett) [inline src/cascadia/TerminalControl/TermControl.cpp]: ah right, thanks! i think this is an hstring (reference counted, not copied) but it being close to the other one it's better for us to match the style on both sides of the if

**Comment by DHowett** [comment]
I had one last drive-by change, as I'd checked the code out to verify my casts/emplaces worked, to reduce another copy. Opportunistic, not required :)

Marked for automatic merge and servicing to 1.16. Thanks again!

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 14]
```diff
@@ -2526,16 +2527,57 @@ namespace winrt::Microsoft::Terminal::Control::implementation
...
+                        const auto buffer = co_await stream.ReadAsync(buf, streamSize, InputStreamOptions::None);
+
+                        const HGLOBAL hGlobal = buffer.data();
+                        const auto count = DragQueryFileW(static_cast<HDROP>(hGlobal), 0xFFFFFFFF, nullptr, 0);
+                        fullPaths.reserve(count);
+
+                        for (unsigned int i = 0; i < count; i++)
+                        {
+                            std::wstring path;
+                            path.resize(wil::max_path_length);
```
Comment (jiejasonliu) [inline src/cascadia/TerminalControl/TermControl.cpp:2553]: `wil::max_path_length` is 259, it doesn't include the null terminator
maybe a potential issue for files with max name lengths?

Comment (DHowett) [reply src/cascadia/TerminalControl/TermControl.cpp:2553]: Ah, so basic_string has one CharT-sized unit at the end of its allocated buffer that is safe to overwrite with `\0`. That should give us the 260 we need, right?

I almost switched over to `wil::AdaptFixedSizeToAllocatedResult`, but a quick cross reference with the implementation of DragFileQuery revealed that we would never need anything more than MAX_PATH

Comment (jiejasonliu) [reply src/cascadia/TerminalControl/TermControl.cpp:2553]: oh cool! that will definitely work then.
if we wanted to be more optimal, `DragQueryFile` returns the exact chars needed if you pass in `null` as the buffer.

lmk if this is something we want to do before we merge
```cpp
  for (unsigned int i = 0; i < count; i++)
  {
      const auto charsNeeded = DragQueryFileW(static_cast<HDROP>(hGlobal), i, nullptr, 0);
      std::wstring path;
      path.resize(charsNeeded);
      const auto charsCopied = DragQueryFileW(static_cast<HDROP>(hGlobal), i, path.data(), path.capacity());

      if (charsCopied > 0)
      {
          path.resize(charsCopied);
          fullPaths.emplace_back(std::move(path));
      }
  }
```

Comment (DHowett) [reply src/cascadia/TerminalControl/TermControl.cpp:2553]: I'm cool with keeping a 260-char buffer somewhere; I know I moved it from the stack to (likely) the heap, but honestly... eh.
