### PR TITLE
Set Tab tooltip explicitly

### LINKED ISSUE #8199: Tab tooltip is empty when zooming pane
# Environment
```none
Microsoft Windows [Version 10.0.19041.572]

Windows Terminal version (if applicable): dev mainline
```

# Steps to reproduce
- Split pane
- Zoom pane
- Hover on the tab

# Expected behavior
The tooltip shows the active title

# Actual behavior
The tooltip is blank

### PR DESCRIPTION
**Pull request by Hegunumo**
## Summary of the Pull Request
The tab tooltip is no longer empty when it was toggle zoomed.
 
## PR Checklist
* [x] Closes #8199 
* [ ] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Documentation updated. If checked, please file a pull request on [our docs repo](https://github.com/MicrosoftDocs/terminal) and link it here: #xxx
* [ ] Schema updated.
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

### CODE REVIEW

**Comment by mpela81** [comment]
Hi - I'd like to give my humble comments from a non-reviewer if you don't mind:
- If you set the tooltip explicitly only when you are in zoomed mode, then when you exit zoom and switch to another pane, the tooltip is not updated automatically to reflect the selected pane. You may need to set it explicitly in all cases.
- Is it required to set a Run+Textbox, instead of just the tabText?
- If I remember correctly when I experimented on this, by default the 'explicit' tooltip is not positioned the same as the 'non-explicit' tooltip. You may need to adjust it.

**Comment by Hegunumo** [comment]
@mpela81  From my experience it won't work if I don't use `Run+Textbox`.

**Comment by DHowett** [comment]
This will probably need to be updated for the new TabHeaderControl! :smile:

**Comment by zadjii-msft** [comment]
Hey thanks for putting this together - mind merging `main` into this branch? I'm fairly certain the work in #8227 is gonna end up conflicting with this PR a decent amount 😄

**Comment by Hegunumo** [comment]
I will update it  for the new TabHeaderControl.

**Comment by Hegunumo** [comment]
@DHowett I updated for TabHeaderControl!

File: src/cascadia/TerminalApp/CommandPalette.cpp [hunk 1]
```diff
@@ -290,7 +290,6 @@ namespace winrt::TerminalApp::implementation
                                          Windows::UI::Xaml::Input::KeyRoutedEventArgs const& e)
     {
         auto key = e.OriginalKey();
-        auto const ctrlDown = WI_IsFlagSet(CoreWindow::GetForCurrentThread().GetKeyState(winrt::Windows::System::VirtualKey::Control), CoreVirtualKeyStates::Down);
```
Comment (DHowett) [inline src/cascadia/TerminalApp/CommandPalette.cpp:293]: This change doesn't seem related to fixing the tooltip in the tab header!

File: src/cascadia/TerminalApp/TerminalTab.cpp [hunk 2]
```diff
@@ -71,6 +71,17 @@ namespace winrt::TerminalApp::implementation
...
     }
 
+    void TerminalTab::_SetToolTip(const winrt::hstring& tabTitle)
+    {
+        auto toolTip = WUX::Controls::ToolTip{};
+        auto newTabRun = WUX::Documents::Run();
+        newTabRun.Text(tabTitle);
+        auto textBlock = WUX::Controls::TextBlock{};
+        textBlock.Inlines().Append(newTabRun);
+        toolTip.Content(textBlock);
```
Comment (DHowett) [inline src/cascadia/TerminalApp/TerminalTab.cpp:81]: we might be able to get away with `tooltip.Content(winrt::box_value(tabTitle))` and avoid the Run and TextBlock completely. Does that work?

File: src/cascadia/TerminalApp/TerminalTab.cpp [hunk 3]
```diff
@@ -231,6 +242,7 @@ namespace winrt::TerminalApp::implementation
 
             // Update the control to reflect the changed title
             _headerControl.Title(activeTitle);
+            _SetToolTip(_GetActiveTitle());
```
Comment (DHowett) [inline src/cascadia/TerminalApp/TerminalTab.cpp:245]: Are we sure this is called at all the right times? How about during initialization when we set the first title

**Review by DHowett — CHANGES_REQUESTED** [review]

**Comment by Hegunumo** [comment]
@DHowett I've been trying to execute `_SetToolTip()` during initialization, but none of them works. I also realized that `tab->SetTabText(title)` in line 45 is actually calling `UpdateTitile()`.

**Comment by Hegunumo** [comment]
@DHowett I hope this is what you meant!

**Comment by zadjii-msft** [comment]
Notes from playing with the branch:
* The tooltip doesn't seem to change when the application changes the title
* The tooltip doesn't change when the tab is renamed with the renamer
* The tooltip _does_ change when the tab zooms

Additionally
* There's currently _no_ tooltip on any tabs: 
  image 
  so this is definitely still an improvement

**Comment by Hegunumo** [comment]
It seems like putting `_SetToolTip()` in `_UpdateTitle()` resolve all the issues above.

**Review by DHowett — APPROVED** [review]
This looks great. Thank you!

File: src/cascadia/TerminalApp/TerminalTab.cpp [hunk 4]
```diff
@@ -71,6 +70,13 @@ namespace winrt::TerminalApp::implementation
         _RecalculateAndApplyTabColor();
     }
 
+    void TerminalTab::_SetToolTip(const winrt::hstring& tabTitle)
+    {
+        auto toolTip = WUX::Controls::ToolTip{};
```
Comment (DHowett) [inline src/cascadia/TerminalApp/TerminalTab.cpp:75]:
```suggestion
        WUX::Controls::ToolTip toolTip{};
```

optional change to improve code readability. we usually don't use "auto x = type{y}" because auto is only good when you _don't have to say the type_. `type x{y};` is shorter :smile:

**Review by zadjii-msft — APPROVED** [review]
This is great, thanks!
