### PR TITLE
AtlasEngine: Improve robustness against TextBuffer bugs

### LINKED ISSUE #13522: Crash in AtlasEngine::_emplaceGlyph
### Windows Terminal version

1.15.1862.0

### Windows build number

10.0.19044.1826

### Other Software

_No response_

### Steps to reproduce

1. Enable experimental text rendering engine in WT settings.
2. Rename the attached [Crash._emplaceGlyph.cmd.txt](https://github.com/microsoft/terminal/files/9126808/Crash._emplaceGlyph.cmd.txt) to `Crash._emplaceGlyph.cmd`.
3. Run WT.
4. Locate and execute `Crash._emplaceGlyph.cmd`.
5. Press any key when asked.

### Expected Behavior

No crash

### Actual Behavior

```
Unhandled exception at 0x00007FFE30AE286E (ucrtbase.dll) in WindowsTerminal.exe: Fatal program exit requested.
```

```
ucrtbase.dll!abort()
ucrtbase.dll!terminate()
[Inline Frame] Microsoft.Terminal.Control.dll!gsl::details::terminate() Line 116
Microsoft.Terminal.Control.dll!Microsoft::Console::Render::AtlasEngine::_emplaceGlyph(IDWriteFontFace * fontFace=0x00000221688e98c0, unsigned __int64 bufferPos1, unsigned __int64 bufferPos2) Line 1436
Microsoft.Terminal.Control.dll!Microsoft::Console::Render::AtlasEngine::_flushBufferLine() Line 1304
Microsoft.Terminal.Control.dll!Microsoft::Console::Render::AtlasEngine::PaintBufferLine(gsl::span<Microsoft::Console::Render::Cluster const ,-1> clusters={...}, til::point coord, bool fTrimLeft, bool lineWrapped=false) Line 461
Microsoft.Terminal.Control.dll!Microsoft::Console::Render::Renderer::_PaintBufferOutputHelper(Microsoft::Console::Render::IRenderEngine * const pEngine=0x000002215f689040, TextBufferCellIterator it={...}, const til::point target, const bool lineWrapped=false) Line 874
Microsoft.Terminal.Control.dll!Microsoft::Console::Render::Renderer::_PaintBufferOutput(Microsoft::Console::Render::IRenderEngine * const pEngine=0x000002215f689040) Line 718
Microsoft.Terminal.Control.dll!Microsoft::Console::Render::Renderer::_PaintFrameForEngine(Microsoft::Console::Render::IRenderEngine * const pEngine=0x000002215f689040) Line 160
Microsoft.Terminal.Control.dll!Microsoft::Console::Render::Renderer::PaintFrame() Line 78
Microsoft.Terminal.Control.dll!Microsoft::Console::Render::RenderThread::_ThreadProc() Line 214
kernel32.dll!BaseThreadInitThunk()
ntdll.dll!RtlUserThreadStart()
```

### PR DESCRIPTION
**Pull request by lhecker**
The current TextBuffer implementation will happily overwrite the
leading/trailing half of a wide glyph with a narrow one without
padding the other half with whitespace. This could crash AtlasEngine
which aggressively guarded against such inconsistencies.

Closes #13522

## Validation Steps Performed
* Run .bat file linked in #13522
  (Override wide glyph with a single space.)
* `AtlasEngine` doesn't crash ✅

### CODE REVIEW

File: src/renderer/atlas/AtlasEngine.cpp [hunk 1]
```diff
@@ -1410,32 +1414,53 @@ void AtlasEngine::_flushBufferLine()
...
+    //                              /   \
+    //                      bufferPos1  bufferPos2
+    //   x1: _api.bufferLineColumn[bufferPos1] == 3
+    //   x1: _api.bufferLineColumn[bufferPos2] == 3
+    // --> cellCount (which is x2 - x1) is now 0 (invalid).
+    //
+    // Assuming that the TextBuffer implementation doesn't have any bugs...
+    // I'm not entirely certain why this occurs, but to me, a layperson, it appears as if
+    // IDWriteFontFallback::MapCharacters() doesn't respect extended grapheme clusters.
+    // It could also possibly be due to a difference in the supported Unicode version.
```
Comment (lhecker) [inline src/renderer/atlas/AtlasEngine.cpp:1456]: FYI This issue also occurs with the Unicode-correct TextBuffer rewrite. I've already written this comment with that in mind.

File: src/renderer/atlas/AtlasEngine.cpp [hunk 2]
```diff
@@ -1410,32 +1414,53 @@ void AtlasEngine::_flushBufferLine()
...
+                                beg = i + 1;
+                            }
                         }
                     }
                 }
             }
         }
     }
 }
+// ^^^ Look at that amazing 8-fold nesting level. Lovely. <3
```
Comment (lhecker) [inline src/renderer/atlas/AtlasEngine.cpp:1428]: I'll improve the code quality one day. I promise. 😄

**Review by zadjii-msft — APPROVED** [review]

**Comment by DHowett** [comment]
@lhecker somebody marked this for servicing, but it conflicts with what's already in 1.15. What are your thoughts?

**Comment by lhecker** [comment]
@DHowett I think it's fine if this only goes into 1.16 like many of the other AtlasEngine improvements.
