### PR TITLE
Fix unbalanced unlock in PtySignalInputThread::_Shutdown

### LINKED ISSUE #12168: `FAST_FAIL_FATAL_APP_EXIT` in `UnlockConsole()`
### Windows Terminal version

main 7061c54

### Windows build number

10.0.22000.434

### Other Software

_No response_

### Steps to reproduce

1. Open the terminal
2. Close the terminal

### Expected Behavior

The instance of `OpenConsole.exe` shouldn't crash.

### Actual Behavior

The instance of `OpenConsole.exe` crashes. The `FAIL_FAST_IF` was added in 7061c54 (#11890), here: https://github.com/microsoft/terminal/blob/2bf10007ffc368e8a0ccf31f47de9fb045d38f40/src/host/consoleInformation.cpp#L81-L90

cc @lhecker 

```
0:001> !analyze -v
*******************************************************************************
*                                                                             *
*                        Exception Analysis                                   *
*                                                                             *
*******************************************************************************

DEBUG_FLR_EXCEPTION_CODE(8000ffff) and the ".exr -1" ExceptionCode(c0000409) don't match

KEY_VALUES_STRING: 1

    Key  : Analysis.CPU.mSec
    Value: 1734

    Key  : Analysis.DebugAnalysisManager
    Value: Create

    Key  : Analysis.Elapsed.mSec
    Value: 26653

    Key  : Analysis.Init.CPU.mSec
    Value: 296

    Key  : Analysis.Init.Elapsed.mSec
    Value: 237998

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 122

    Key  : FailFast.Name
    Value: FATAL_APP_EXIT

    Key  : FailFast.Type
    Value: 7

    Key  : Timeline.Process.Start.DeltaSec
    Value: 7

    Key  : WER.OS.Branch
    Value: co_release

    Key  : WER.OS.Timestamp
    Value: 2021-06-04T16:28:00Z

    Key  : WER.OS.Version
    Value: 10.0.22000.1


FILE_IN_CAB:  OpenConsole.exe.16980.dmp

NTGLOBALFLAG:  0

PROCESS_BAM_CURRENT_THROTTLED: 0

PROCESS_BAM_PREVIOUS_THROTTLED: 0

APPLICATION_VERIFIER_FLAGS:  0

CONTEXT:  (.ecxr)
rax=000000e8760fdf80 rbx=000000e8760fe500 rcx=000000e8760fdf80
rdx=000000e8760fe430 rsi=000000e8760fe500 rdi=000000e8760fdf80
rip=00007ff88b042492 rsp=000000e8760fdea0 rbp=0000000000000001
 r8=0000000000000000  r9=000000e8760fe3e0 r10=00000fff11608469
r11=0000020000020008 r12=00007ff79ebcb2ee r13=0000000000000001
r14=0000000000000000 r15=00007ff79ec73f98
iopl=0         nv up ei pl nz na po nc
cs=0033  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00000204
KERNELBASE!RaiseFailFastException+0x152:
00007ff8`8b042492 0f1f440000      nop     dword ptr [rax+rax]
Resetting default scope

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 00007ff79ebcb2ee (OpenConsole!CONSOLE_INFORMATION::UnlockConsole+0x000000000000005e)
   ExceptionCode: c0000409 (Security check failure or stack buffer overrun)
  ExceptionFlags: 00000001
NumberParameters: 3
   Parameter[0]: 0000000000000007
   Parameter[1]: ffffffff8000ffff
   Parameter[2]: 0000000000000054
Subcode: 0x7 FAST_FAIL_FATAL_APP_EXIT 

PROCESS_NAME:  OpenConsole.exe

EXCEPTION_CODE_STR:  8000ffff

STACK_TEXT:  
000000e8`760fdea0 00007ff7`9eb84239     : 00000000`00000000 00007ff8`8b042340 00000000`00000000 000000e8`760fe6b0 : KERNELBASE!RaiseFailFastException+0x152
000000e8`760fe480 00007ff7`9eb84038     : 000000e8`760fe5d0 00007ff7`9ebcc092 00000000`00000000 00000000`00000000 : OpenConsole!wil::details::WilDynamicLoadRaiseFailFastException+0x49
000000e8`760fe4b0 00007ff7`9eb8510d     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : OpenConsole!wil::details::WilRaiseFailFastException+0x18
000000e8`760fe4e0 00007ff7`9eb86ca8     : 000000e8`760ffb60 000000e8`760fe6b0 00007ff7`9ebcc092 00000000`00000000 : OpenConsole!wil::details::WilFailFast+0xdd
000000e8`760fe5b0 00007ff7`9eb85140     : 00000000`00000000 00000000`00000000 00000000`00000000 00007ff7`9ebcc092 : OpenConsole!wil::details::ReportFailure_NoReturn<3>+0x248
000000e8`760ffab0 00007ff7`9eb851af     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : OpenConsole!wil::details::ReportFailure_Base<3,0>+0x30
000000e8`760ffb10 00007ff7`9eb8ee8b     : 00000000`00000002 00000000`00000000 00000000`00000000 00007ff8`8a8e218b : OpenConsole!wil::details::ReportFailure_Hr<3>+0x5f
000000e8`760ffb90 00007ff7`9ebcb2ee     : 00000223`b1238dd0 00000000`00000000 00000000`00000002 00000000`00000000 : OpenConsole!wil::details::in1diag3::_FailFast_Unexpected+0x1b
000000e8`760ffbe0 00007ff7`9ebcc092     : 00000000`00000002 00000000`00000000 00000000`00000000 000000e8`760ffc40 : OpenConsole!CONSOLE_INFORMATION::UnlockConsole+0x5e
000000e8`760ffc10 00007ff7`9ebcbf01     : 00000000`00000000 00000000`00000000 00000000`00000000 00000223`b1232230 : OpenConsole!Microsoft::Console::PtySignalInputThread::_GetData+0x52
000000e8`760ffc60 00007ff8`8c1b54e0     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : OpenConsole!Microsoft::Console::PtySignalInputThread::_InputThread+0x31
000000e8`760ffcb0 00007ff8`8d3e485b     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : kernel32!BaseThreadInitThunk+0x10
000000e8`760ffce0 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x2b


FAULTING_SOURCE_LINE:  F:\windows-terminal\src\host\consoleInformation.cpp

FAULTING_SOURCE_FILE:  F:\windows-terminal\src\host\consoleInformation.cpp

FAULTING_SOURCE_LINE_NUMBER:  84

FAULTING_SOURCE_CODE:  
    80: void CONSOLE_INFORMATION::UnlockConsole()
    81: {
    82:     // See description of recursionCount a few lines above.
    83:     const auto rc = --recursionCount;
>   84:     FAIL_FAST_IF(rc == ULONG_MAX);
    85:     if (rc == 0)
    86:     {
    87:         lock.unlock();
    88:     }
    89: }


SYMBOL_NAME:  OpenConsole!CONSOLE_INFORMATION::UnlockConsole+5e

MODULE_NAME: OpenConsole

IMAGE_NAME:  OpenConsole.exe

STACK_COMMAND:  ~1s ; .ecxr ; kb

FAILURE_BUCKET_ID:  FAIL_FAST_FATAL_APP_EXIT_8000ffff_OpenConsole.exe!CONSOLE_INFORMATION::UnlockConsole

OS_VERSION:  10.0.22000.1

BUILDLAB_STR:  co_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

FAILURE_ID_HASH:  {71c04470-b2ad-a39c-f89f-e94a80ecb962}

Followup:     MachineOwner
---------
```

### PR DESCRIPTION
**Pull request by lhecker**
The only way to notice that LeaveCriticalSection() was called more
often than EnterCriticalSection() is by calling EnterCriticalSection()
again in the future, which will then deadlock.
Since this bug occurs on exit it wasn't noticeable with the old console lock.
With the new, stricter ticket lock this bug causes a fail-fast exit.

## PR Checklist
* [x] Closes #12168
* [x] I work here
* [x] Tests added/passed

## Validation Steps Performed
* Launch and then exit Windows Terminal
* OpenConsole cleanly exits ✅

### CODE REVIEW

File: src/host/PtySignalInputThread.cpp [hunk 1]
```diff
@@ -227,14 +227,6 @@ void PtySignalInputThread::_Shutdown()
     // Trigger process shutdown.
     CloseConsoleProcessState();
 
-    // If we haven't terminated by now, that's because there's a client that's still attached.
-    // Force the handling of the control events by the attached clients.
-    // As of MSFT:19419231, CloseConsoleProcessState will make sure this
-    //      happens if this method is called outside of lock, but if we're
-    //      currently locked, we want to make sure ctrl events are handled
-    //      _before_ we RundownAndExit.
-    ProcessCtrlEvents();
```
Comment (zadjii-msft) [inline src/host/PtySignalInputThread.cpp:236]: Why do we not have to do this anymore? IIRC there's a very bizarre edge case bug that can occur if we don't dispatch ctrl events before tearing down

**Review by zadjii-msft — CHANGES_REQUESTED** [review]

File: src/host/PtySignalInputThread.cpp (hunk 1 above)
Comment (lhecker) [reply src/host/PtySignalInputThread.cpp:236]: I believe this might be a copy-paste mistake...
This function is never called while the console is locked (see `_GetData` in the same file), so this can't possibly happen.
However I've just pushed a change which makes the entire code a lot more robust in general in my opinion. 🙂

Comment (DHowett) [reply src/host/PtySignalInputThread.cpp:236]: I'm definitely worried about making changes here. If it's a copy/paste error, we should make sure we understand when it was introduced and when it became an error. Pull up the team OneNote and use the guidance on importing pre-github history if you need to! :)

Comment (lhecker) [reply src/host/PtySignalInputThread.cpp:236]: I found the original comments on the PR that added this function (!2698602):
> Yeah, my point was that the two functions (`PtySignalInputThread::_Shutdown` and `VtIo::_ShutdownIfNeeded`) should probably have the same signature, one way or the other, because you fixed the jiggling the handle thing. Either one of them is double-processing ctrl events or the other is not processing them at all. They should be consistent.
> [...]
> Derp yea, actually I believe `_ShutdownIfNeeded` is the right one. For both of these, if they're called under lock, we don't want to `RundownAndExit` before `ProcessCtrlEvents` is called.

This issue has now been resolved by jiggling in a different way instead. 😅

File: src/host/PtySignalInputThread.cpp [hunk 2]
```diff
@@ -170,7 +170,6 @@ bool PtySignalInputThread::_GetData(_Out_writes_bytes_(cbBuffer) void* const pBu
         if (lastError == ERROR_BROKEN_PIPE)
         {
             _Shutdown();
-            return false;
```
Comment (zadjii-msft) [inline src/host/PtySignalInputThread.cpp:173]: (okay sorry to nitpick, but all this code is terribly fragile)

why are we removing these `return false`s in `_GetData`? Aren't these needed to get the input threads to break out of their while loops?

File: src/interactivity/base/HostSignalInputThread.cpp [hunk 3]
```diff
@@ -163,7 +163,6 @@ bool HostSignalInputThread::_GetData(gsl::span<gsl::byte> buffer)
         if (lastError == ERROR_BROKEN_PIPE)
         {
             _Shutdown();
-            return false;
```
Comment (zadjii-msft) [inline src/interactivity/base/HostSignalInputThread.cpp:166]: (the other ones)

File: src/host/PtySignalInputThread.cpp (hunk 2 above)
Comment (zadjii-msft) [reply src/host/PtySignalInputThread.cpp:173]: Oh right, cause we'll `ExitProcess` in `RundownAndExit` in `_Shutdown`, that makes sense.

File: src/host/output.cpp [hunk 4]
```diff
@@ -512,13 +512,9 @@ void CloseConsoleProcessState()
...
-    // Jiggle the handle: (see MSFT:19419231)
-    // When we call this function, we'll only actually close the console once
-    //      we're totally unlocked. If our caller has the console locked, great,
-    //      we'll dispatch the ctrl event once they unlock. However, if they're
-    //      not running under lock (eg PtySignalInputThread::_GetData), then the
-    //      ctrl event will never actually get dispatched.
-    // So, lock and unlock here, to make sure the ctrl event gets handled.
+    // MSFT:19419231
+    // Ensure ctrl events are processed before exiting,
+    // no matter whether the console is locked or not.
```
Comment (zadjii-msft) [inline src/host/output.cpp:517]: May want to add an archeological 
```suggestion
    // no matter whether the console is locked or not.
    // GH#12181: we used to "jiggle the handle" here to trigger ProcessCtrlEvents in the scenario where we were called outside of lock (e.g. PtySignalInputThread::_GetData). WE no longer need to worry about that.....
```

**Review by zadjii-msft — COMMENTED** [review]
I don't know why I'm having a hard time following this anymore.... Not enough coffee in the world for this level of changes

If we got to `CloseConsoleProcessState` and we were 
* Unlocked: We'd lock, then unlock at the bottom. That would set the recursion count to 0, which would dispatch the Ctrl events. (and unlock again, which would theoretically be bad and **the source of this bug**)
* Locked: we'd lock and unlock, and the recursion count would still be >0. Whoever the last one to unlock would eventually set the recursion count to 0 which would dispatch the Ctrl events.


Now:
* Unlocked: we lock, then process Ctrl events, and unlock 
* Locked: we lock again, then process Ctrl events, and unlock. Theoretically, the person holding the lock can **dispatch the ctrl events again when they're unlocked**
we worried about that?


Sorry to be super nitpicky. Just wanna be careful, debugging this area is an absolute pain and I don't want to get a bug on us in 6 months 😅

File: src/host/PtySignalInputThread.cpp (hunk 2 above)
Comment (lhecker) [reply src/host/PtySignalInputThread.cpp:173]: So here's the story behind this change:
Initially I tried to add some code after `ServiceLocator::RundownAndExit(ERROR_BROKEN_PIPE);`. This doesn't make any sense though, as `RundownAndExit` never returns, but neither the regular compilation nor the AuditMode marked this as an issue. If we use the `[[noreturn]]` annotation however we can turn this programming error into an immediate compilation warning. This is why this PR adds `[[noreturn]]`.

But now that code after calling a `[[noreturn]]` function is a warning I was forced to remove such unreachable code. This is why this PR removes the above line (and the other one).

Do you agree with this change? If not, would you like me to revert it?

Comment (zadjii-msft) [reply src/host/PtySignalInputThread.cpp:173]: oh yea no, this makes sense, more sense than before. Defs keep this.

File: src/host/output.cpp [hunk 5]
```diff
@@ -520,5 +520,5 @@ void CloseConsoleProcessState()
     //      ctrl event will never actually get dispatched.
     // So, lock and unlock here, to make sure the ctrl event gets handled.
     LockConsole();
-    auto Unlock = wil::scope_exit([&] { UnlockConsole(); });
+    UnlockConsole();
```
Comment (lhecker) [inline src/host/output.cpp:523]: @zadjii-msft I've drastically simplified the PR now. In fact if we want to, we can just keep the two added `LockConsole()` lines. 🙂

Technically we can remove these two lines now, because the only place where `CloseConsoleProcessState` is called apart from these two places is in window.cpp, where it's done so under lock. As such these two lines serve no purpose anymore.

**Comment by DHowett** [comment]
The build is failing -- what's up?

**Comment by lhecker** [comment]
> The build is failing -- what's up?

Forgot to include the header file. 😅

**Comment by lhecker** [comment]
I re-tested the latest in Windows Terminal, by launching a blocking application listening for input and exiting Windows Terminal. The shell and CLI application are both properly killed. ✅

**Review by zadjii-msft — APPROVED** [review]
okay I think my questions were answered. Lets get this in the 1.13 cut for tonight, @DHowett @miniksa

**Review by DHowett — APPROVED** [review]

**Review by miniksa — APPROVED** [review]
This makes sense to me based on what Leonard said. I also trust him to have gone over this with a very fine-tooth comb given how much he's managed to school me on synchronization and threading. Let's go for it.
