### PR TITLE
Fix the TabTests!

### LINKED ISSUE #2472: TabTests.cpp test cases fail to run - TAEF harness fails to run with "[HRESULT: 0x80270254] Failed to create the test host process for out of process test execution"
On my computer, the test case file `src\cascadia\LocalTests_TerminalApp\TabTests.cpp` fails to run test setup with the above error message. I'm not sure if this is a general problem or just in my setup, but these tests don't seem to run in Azure DevOps CI ([I checked test run 31597](https://dev.azure.com/ms/Terminal/_build/results?buildId=31597&view=ms.vss-test-web.build-test-results-tab)) so I can't be sure.

### Environment
Windows build number: Microsoft Windows [Version 10.0.18362.295]
Windows Terminal version: current master commit 734fc1dcc6de4315d4cc91944c5ea83b7b8a7e1a

### Steps to reproduce
1. Checkout the Terminal repo.
1. Run `tools\razzle.cmd & bz rel` to get a successful build.
1. Run: `"%TAEF%" bin\%PLATFORM%\Release\LocalTests_TerminalApp\TerminalApp.LocalTests.dll /name:"TerminalAppLocalTests::TabTests::*"`

### Expected behavior
All tests pass.

### Actual behavior
The test file does not run at all, with error 0x80270254 == E_APPLICATION_NOT_REGISTERED (lines manually wrapped):

```
X:\> "%TAEF%"
  bin\x64\Release\LocalTests_TerminalApp\TerminalApp.LocalTests.dll
  /name:"TerminalAppLocalTests::TabTests::*"

Test Authoring and Execution Framework v10.38k for x64
TAEF: Deploying custom AppXManifest...
  Copying X:\bin\x64\Release\LocalTests_TerminalApp\TerminalApp.LocalTests.AppxManifest.xml
  to X:\bin\x64\Release\LocalTests_TerminalApp\AppXManifest.xml
Warning: TAEF: Using TE.ProcessHost.exe as the Application Executable for UAP tests
  is deprecated, please consider using TE.ProcessHost.UAP.exe in your custom manifest.
Error: TAEF: [HRESULT: 0x80270254] Failed to create the test host process for
  out of process test execution. (The IApplicationActivationManager::
  ActivateApplication call failed while using a default host. TAEF's ETW logs
  which are gathered with the /enableEtwLogging switch should contain
  events from relevant providers that may help to diagnose the failure.)

StartGroup: TerminalAppLocalTests::TabTests::TryInitXamlIslands
EndGroup: TerminalAppLocalTests::TabTests::TryInitXamlIslands [Blocked]

StartGroup: TerminalAppLocalTests::TabTests::TryCreateLocalWinRTType
EndGroup: TerminalAppLocalTests::TabTests::TryCreateLocalWinRTType [Blocked]

StartGroup: TerminalAppLocalTests::TabTests::TryCreateXamlObjects
EndGroup: TerminalAppLocalTests::TabTests::TryCreateXamlObjects [Blocked]

StartGroup: TerminalAppLocalTests::TabTests::TryCreateTab
EndGroup: TerminalAppLocalTests::TabTests::TryCreateTab [Blocked]

Summary of TAEF Warnings:
    Warning: TAEF: Using TE.ProcessHost.exe as the Application Executable for UAP tests
      is deprecated, please consider using TE.ProcessHost.UAP.exe in your custom manifest.

Summary of Errors Outside of Tests:
    Error: TAEF: [HRESULT: 0x80270254] Failed to create the test host process for
      out of process test execution. (The IApplicationActivationManager::
      ActivateApplication call failed while using a default host. TAEF's ETW logs
      which are gathered with the /enableEtwLogging switch should contain
      events from relevant providers that may help to diagnose the failure.)

Summary of Non-passing Tests:
    TerminalAppLocalTests::TabTests::TryInitXamlIslands [Blocked]
    TerminalAppLocalTests::TabTests::TryCreateLocalWinRTType [Blocked]
    TerminalAppLocalTests::TabTests::TryCreateXamlObjects [Blocked]
    TerminalAppLocalTests::TabTests::TryCreateTab [Blocked]

Summary: Total=4, Passed=0, Failed=0, Blocked=4, Not Run=0, Skipped=0
```

Creating the ETW log and parsing it with Windows' built-in `tracerpt.exe` tool yields a number of interesting errors. As best as I can tell from my very limited knowledge, there was a problem with the AppX package extensions (&lt;Extension&gt; elements in AppXManifest.xml).
```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="CombaseTraceLoggingProvider" Guid="{1aff6089-e863-4d36-bdfd-3581f07440be}" />
    <EventID>0</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x0</Keywords>
    <TimeCreated SystemTime="2019-08-18T22:19:27.701635500-07:00" />
    <Execution ProcessID="8272" ThreadID="11028" ProcessorID="0" KernelTime="315" UserTime="405" />
    <Channel />
    <Computer />
  </System>
  <EventData>
    <!-- Michael: This is 0x80040154 == REGDB_E_CLASSNOTREG
         "Class not registered" -->
    <Data Name="hresult">-2147221164</Data>
    <Data Name="code"></Data>
    <Data Name="message"></Data>
    <Data Name="function"></Data>
    <Data Name="fileName">onecore\com\combase\extensioncatalog\extensioncatalog.cpp</Data>
    <Data Name="lineNumber">    1215</Data>
  </EventData>
  <RenderingInfo Culture="en-US">
    <Task>ComError</Task>
  </RenderingInfo>
</Event>

[snip snip]

<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="ActivationManager" Guid="{cf7f94b3-08dc-5257-422f-497d7dc86ab3}" />
    <EventID>0</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x0</Keywords>
    <TimeCreated SystemTime="2019-08-18T22:19:27.702335700-07:00" />
    <Execution ProcessID="8272" ThreadID="11028" ProcessorID="2" KernelTime="315" UserTime="405" />
    <Channel />
    <Computer />
  </System>
  <EventData>
    <Data Name="PartA_PrivTags">16777216</Data>
    <ComplexData Name="wilActivity">
      <!-- Michael: This is 0x80270254 == E_APPLICATION_NOT_REGISTERED
           "This app does not support the contract specified or is not installed." -->
      <Data Name="hresult">2150040148</Data>
      <Data Name="fileName">onecoreuap\base\appmodel\execmodel\modern\activationmanager\extensionhelpers.cpp</Data>
      <Data Name="lineNumber">     221</Data>
      <Data Name="module">activationmanager.dll</Data>
      <Data Name="failureType">       1</Data>
      <Data Name="message"></Data>
      <Data Name="threadId">   11028</Data>
      <Data Name="callContext">\ForegroundActivation</Data>
      <Data Name="originatingContextId">       8</Data>
      <Data Name="originatingContextName">ForegroundActivation</Data>
      <Data Name="originatingContextMessage"></Data>
      <Data Name="currentContextId">       8</Data>
      <Data Name="currentContextName">ForegroundActivation</Data>
      <Data Name="currentContextMessage"></Data>
      <Data Name="failureId">      32</Data>
      <Data Name="failureCount">      32</Data>
      <Data Name="function"></Data>
    </ComplexData>
  </EventData>
  <RenderingInfo Culture="en-US">
    <Task>ActivityError</Task>
  </RenderingInfo>
</Event>
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="ActivationManager" Guid="{cf7f94b3-08dc-5257-422f-497d7dc86ab3}" />
    <EventID>0</EventID>
    <Version>0</Version>
    <Level>5</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x0</Keywords>
    <TimeCreated SystemTime="2019-08-18T22:19:27.702384600-07:00" />
    <Execution ProcessID="8272" ThreadID="11028" ProcessorID="2" KernelTime="315" UserTime="405" />
    <Channel />
    <Computer />
  </System>
  <EventData>
    <!-- Michael: This is E_APPLICATION_NOT_REGISTERED
         "This app does not support the contract specified or is not installed." -->
    <Data Name="HRESULT">0x80270254</Data>
    <Data Name="File">onecoreuap\base\appmodel\execmodel\modern\activationmanager\extensionhelpers.cpp</Data>
    <Data Name="Line">     221</Data>
    <Data Name="failure-&gt;pszFunction"></Data>
    <Data Name="failure-&gt;pszMessage"></Data>
    <Data Name="failure-&gt;pszCode"></Data>
    <Data Name="GetCurrentThreadId()">   11028</Data>
    <Data Name="static_cast&lt;DWORD&gt;(failure-&gt;type)">       1</Data>
    <Data Name="failure-&gt;cFailureCount">32</Data>
  </EventData>
  <RenderingInfo Culture="en-US">
    <Task>WIL_Failover</Task>
  </RenderingInfo>
</Event>
```

### PR DESCRIPTION
**Pull request by zadjii-msft**
## Summary of the Pull Request

Fix the `TabTests`, and enable testing of types with XAML content. The `TabTests` were written many, many moons ago. they were intended to be our tests of XAML-like content within the Terminal app, so we could have unittests of Tabs, Panes, etc. Between their initial authoring and the day they were checked in, we had a bunch of build changes come in and break them irreperably. 

We've gotten them fixed now with _one weird trick_ <sup>doctors hate me</sup>. As long as there isn't an `App.xbf` in the test's output directory, then the tests will deploy just fine.

We also needed a bit of magic, cribbed straight from TAEF, to enable running test code synchronously on the UI thread. Hence, `CppwinrtTailored.h`.

## PR Checklist
* [x] Closes #2472
* [x] I work here
* [x] Tests added/passed - you better believe it
* [n/a] Requires documentation to be updated

## Validation Steps Performed

image

### CODE REVIEW

**Comment by zadjii-msft** [comment]
(draft PRs don't run the CI but treat this as a draft)

**Comment by zadjii-msft** [comment]
(this guy is ready for review now)

File: src/cascadia/LocalTests_TerminalApp/pch.h [hunk 1]
```diff
@@ -25,15 +25,19 @@ Author(s):
...
 #include <json.h>
 #include "consoletaeftemplates.hpp"
 
 // Needed just for XamlIslands to work at all:
 #include <winrt/Windows.system.h>
 #include <winrt/Windows.Foundation.Collections.h>
-#include <winrt/Windows.UI.Xaml.Hosting.h>
-#include <windows.ui.xaml.hosting.desktopwindowxamlsource.h>
+// #include <winrt/Windows.UI.Xaml.Hosting.h>
+// #include <windows.ui.xaml.hosting.desktopwindowxamlsource.h>
```
Comment (carlos-zamora) [inline src/cascadia/LocalTests_TerminalApp/pch.h]: stray comments

File: src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.vcxproj [hunk 2]
```diff
@@ -69,13 +71,16 @@
   <ItemDefinitionGroup>
     <ClCompile>
       <AdditionalIncludeDirectories>..;$(OpenConsoleDir)\dep\jsoncpp\json;$(OpenConsoleDir)src\inc;$(OpenConsoleDir)src\inc\test;$(WinRT_IncludePath)\..\cppwinrt\winrt;"$(OpenConsoleDir)\src\cascadia\TerminalApp\lib\Generated Files";%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
-      <PrecompiledHeaderFile>precomp.h</PrecompiledHeaderFile>
+      <!-- <AdditionalIncludeDirectories>..;$(OpenConsoleDir)\dep\jsoncpp\json;$(OpenConsoleDir)src\inc;$(OpenConsoleDir)src\inc\test;$(WinRT_IncludePath)\..\cppwinrt\winrt;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories> -->
```
Comment (carlos-zamora) [inline src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.vcxproj]: Do we want to remove these commented `AdditionalIncludeDirectories` and `AdditionalOptions`?

File: src/cascadia/LocalTests_TerminalApp/CppWinrtTailored.h [hunk 3]
```diff
@@ -0,0 +1,103 @@
+// Copyright (c) Microsoft Corporation.
+// Licensed under the MIT license.
+//
+// Module Name:
+// - CppWinrtTailored.h
+//
+// Abstract:
+// - This is effectively a copy-paste of TAEF's Tailored.h, proted to cppwinrt.
```
Comment (carlos-zamora) [inline src/cascadia/LocalTests_TerminalApp/CppWinrtTailored.h]:
```suggestion
// - This is effectively a copy-paste of TAEF's Tailored.h, ported to cppwinrt.
```

File: src/cascadia/TerminalConnection/EchoConnection.cpp [hunk 4]
```diff
@@ -42,12 +42,9 @@ namespace winrt::Microsoft::Terminal::TerminalConnection::implementation
     {
         rows;
         columns;
-
-        throw hresult_not_implemented();
     }
 
     void EchoConnection::Close()
     {
-        throw hresult_not_implemented();
```
Comment (carlos-zamora) [inline src/cascadia/TerminalConnection/EchoConnection.cpp]: Were these supposed to be removed?

Comment (zadjii-msft) [reply src/cascadia/TerminalConnection/EchoConnection.cpp]: Yea, if left in they crash the test when the connection gets torn down 😬

**Comment by miniksa** [comment]
image
image
image

I love these commit messages.

File: src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.AppxManifest.prototype.xml [hunk 5]
```diff
@@ -28,7 +28,7 @@
   </Properties>
 
   <Dependencies>
-    <TargetDeviceFamily Name="Windows.Universal" MinVersion="10.0.18362.0" MaxVersionTested="10.0.18362.0" />
+    <TargetDeviceFamily Name="Windows.Universal" MinVersion="10.0.17763.0" MaxVersionTested="10.0.18362.0" />
```
Comment (miniksa) [inline src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.AppxManifest.prototype.xml]: Explain?

File: src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.vcxproj [hunk 6]
```diff
@@ -9,6 +9,7 @@
     <ConfigurationType>DynamicLibrary</ConfigurationType>
     <WindowsTargetPlatformMinVersion>10.0.18362.0</WindowsTargetPlatformMinVersion>
     <WindowsTargetPlatformVersion>10.0.18362.0</WindowsTargetPlatformVersion>
+    <OpenConsoleUniversalApp>true</OpenConsoleUniversalApp>
```
Comment (miniksa) [inline src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.vcxproj]: Uh, what's keying on this? Did I miss it?

File: src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.vcxproj [hunk 7]
```diff
@@ -69,13 +71,13 @@
...
       <AdditionalIncludeDirectories>..;$(OpenConsoleDir)\dep\jsoncpp\json;$(OpenConsoleDir)src\inc;$(OpenConsoleDir)src\inc\test;$(WinRT_IncludePath)\..\cppwinrt\winrt;"$(OpenConsoleDir)\src\cascadia\TerminalApp\lib\Generated Files";%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
-      <PrecompiledHeaderFile>precomp.h</PrecompiledHeaderFile>
+      <PrecompiledHeaderFile>pch.h</PrecompiledHeaderFile>
 
       <!-- Manually disable unreachable code warning, because jconcpp has a ton of that. -->
       <DisableSpecificWarnings>4702;%(DisableSpecificWarnings)</DisableSpecificWarnings>
     </ClCompile>
     <Link>
-      <AdditionalDependencies>WindowsApp.lib;%(AdditionalDependencies)</AdditionalDependencies>
+      <AdditionalDependencies>User32.lib;WindowsApp.lib;shell32.lib;%(AdditionalDependencies)</AdditionalDependencies>
```
Comment (miniksa) [inline src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.vcxproj]: Does linking onecoreuap.lib (instead of WindowsApp.lib) satisfy this with a single umbrella in lieu of adding user32.lib and shell32.lib?

File: src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.AppxManifest.prototype.xml (hunk 5 above)
Comment (zadjii-msft) [reply src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.AppxManifest.prototype.xml]: The CI is running 17763 not 18362. Granted, this particular PR doesn't make the CI work, but if I set this to 18362 then it fails in the CI saying "I can't install this package because it's for a newer version of Windows". I guess this is pre-emptive work that I didn't revert.

File: src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.vcxproj (hunk 6 above)
Comment (zadjii-msft) [reply src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.vcxproj]: That's a good question. I think I had to add this when I made the project a winrt project, but maybe I didn't need to. Lemme check.

File: src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.vcxproj (hunk 7 above)
Comment (zadjii-msft) [reply src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.vcxproj]: Unsure. I'll test.

File: src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.AppxManifest.prototype.xml (hunk 5 above)
Comment (miniksa) [reply src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.AppxManifest.prototype.xml]: Ah OK.

File: src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.vcxproj (hunk 7 above)
Comment (zadjii-msft) [reply src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.vcxproj]: Yep this works.

File: src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.vcxproj (hunk 6 above)
Comment (zadjii-msft) [reply src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.vcxproj]: Yep, didn't need this.

**Comment by zadjii-msft** [comment]
@miniksa @carlos-zamora @DHowett-MSFT @leonMSFT 

Heads up, if you want to run the LocalTests after merging this - you'll need to manually delete the old `App.xbf` out of the `bin\x64\Debug\LocalTests_TerminalApp` directory. It won't get cleaned up automatically, and if it's there, the TabTests will fail. Fortunately the rest of the tests will still pass.

File: src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.vcxproj [hunk 8]
```diff
@@ -77,7 +76,7 @@
       <DisableSpecificWarnings>4702;%(DisableSpecificWarnings)</DisableSpecificWarnings>
     </ClCompile>
     <Link>
-      <AdditionalDependencies>User32.lib;WindowsApp.lib;shell32.lib;%(AdditionalDependencies)</AdditionalDependencies>
+      <AdditionalDependencies>onecoreuap.lib;%(AdditionalDependencies)</AdditionalDependencies>
```
Comment (DHowett-MSFT) [inline src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.vcxproj]: I mean, wait, if this is using the cppwinrt pre props you don't even need the link block at all.

Comment (zadjii-msft) [reply src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.vcxproj]: :facepalm:

Comment (zadjii-msft) [reply src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.vcxproj]: wait no though I do?

Comment (zadjii-msft) [reply src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.vcxproj]: The cppwinrt preprops only was WindowsApp.lib...
