### PR TITLE
Force LTR / logical order for text in GdiEngine

### LINKED ISSUE #12294: RTL text in conhost is no longer rendered correctly
### Windows Terminal version

Commit eb7559733d3cc9062c7de610f3b95d9143099ca1

### Windows build number

10.0.19041.1415

### Other Software

_No response_

### Steps to reproduce

1. Build a recent version of OpenConsole.
2. Open a conhost bash shell.
3. Execute the following command: `printf "\u05ea\u05d7\u05d0\n"`

### Expected Behavior

RTL characters should be displayed in the exact order they were output, and not reversed. This is what it looks like in my inbox conhost (10.0.19041.1415):

image

This also matches the behaviour of XTerm.

### Actual Behavior

In the current version of OpenConsole (I think since PR #10478), RTL characters are reversed, like this:

image

I realise that some people might consider this a good thing, since it gives the superficial appearance that it's rendering RTL languages correctly, but it is not compatible with the original conhost and breaks genuine RTL-aware applications (which rely on characters being displayed exactly where they've been positioned).

### PR DESCRIPTION
**Pull request by lhecker**
Some applications like `vim -H` implement their own BiDi reordering.
Previously we used `PolyTextOutW` which supported such arrangements,
but with a0527a1 and the switch to `ExtTextOutW` we broke such applications.
This commit restores the old behavior by reimplementing the basics
of `ExtTextOutW`'s internal workings while enforcing LTR ordering.

## Validation Steps Performed
* Create a text file with "ץחסק פחופפסנ חס קוח ז׳חסש ץקקטק פחטסץ"
  Viewing the text file with `vim -H` presents the contents as expected ✅
* Printing enwik8 is as fast as before ✅
* Font fallback for various eastern scripts in enwik8 works as expected ✅
* `DECDWL` double-width sequences ✅
* Horizontal scrolling (apart from producing expected artifacts) ✅

Closes #12294

### CODE REVIEW

File: src/renderer/gdi/state.cpp [hunk 1]
```diff
@@ -456,7 +445,9 @@ GdiEngine::~GdiEngine()
                                                 const SIZE cellSize,
                                                 const size_t centeringHint) noexcept
 {
-    // If the soft font is currently selected, replace it with the default font.
+    // If we previously called SelectFont(_hdcMemoryContext, _softFont), it will
+    // still hold a reference to the _softFont object we're planning to overwrite.
+    // --> First revert back to the standard _hfont, lest we have dangling pointers.
```
Comment (lhecker) [inline src/renderer/gdi/state.cpp:450]: With the introduction of `FontType::Undefined` I was wondering if I should remove the if condition after this comment. I realized that this code is (potentially? probably?) critical for memory safety, so wrote a "Why?" comment here, stating why this is important to keep.

File: src/host/exe/Host.EXE.vcxproj [hunk 2]
```diff
@@ -91,7 +91,7 @@
     </ClCompile>
     <Link>
       <AllowIsolation>true</AllowIsolation>
-      <AdditionalDependencies>WinMM.Lib;%(AdditionalDependencies)</AdditionalDependencies>
+      <AdditionalDependencies>WinMM.Lib;usp10.lib;%(AdditionalDependencies)</AdditionalDependencies>
```
[the remark this answers is not in the document]
Comment (miniksa) [reply src/host/exe/Host.EXE.vcxproj:94]: `gdi32.lib` is probably inside the "Umbrella" of `onecoreuap_apiset.lib` included here: https://cs.github.com/microsoft/terminal/blob/ce6ce50e7e9eeb2d7377527d9512da9d43674bc0/src/common.build.post.props#L16

**Comment by miniksa** [comment]
> * `DECDWL` double-width sequences ❔
> * horizontal scrolling ❔

I presume you're actively checking these right now.

File: src/renderer/gdi/state.cpp (hunk 1 above)
Comment (miniksa) [reply src/renderer/gdi/state.cpp:450]: Yes. Good. Thanks.

**Comment by lhecker** [comment]
> I presume you're actively checking these right now.

Yeah I'll check those before we merge this PR. 🙂
I'm confident it'll just work, because I technically didn't really change the implementation.

File: src/host/exe/Host.EXE.vcxproj (hunk 2 above)
[the remark this answers is not in the document]
Comment (DHowett) [reply src/host/exe/Host.EXE.vcxproj:94]: This part of the codebase does not need to run on Windows 7, and you can safely break it. GDI is not part of TerminalControl. :)

File: src/renderer/gdi/lib/gdi.vcxproj [hunk 3]
```diff
@@ -22,6 +22,11 @@
     <ClInclude Include="..\gdirenderer.hpp" />
     <ClInclude Include="..\precomp.h" />
   </ItemGroup>
+  <ItemDefinitionGroup>
+    <Lib>
+      <AdditionalDependencies>usp10.lib;%(AdditionalDependencies)</AdditionalDependencies>
```
Comment (DHowett) [inline src/renderer/gdi/lib/gdi.vcxproj:27]: as above, you can safely remove this as conhost/gdi is windows 8.1+ only

File: src/renderer/gdi/state.cpp [hunk 4]
```diff
@@ -142,15 +142,6 @@ GdiEngine::~GdiEngine()
     _hwndTargetWindow = hwnd;
     _hdcMemoryContext = hdcNewMemoryContext;
 
-    // If we have a font, apply it to the context.
-    if (nullptr != _hfont)
-    {
-        LOG_HR_IF_NULL(E_FAIL, SelectFont(_hdcMemoryContext, _hfont));
```
Comment (DHowett) [inline src/renderer/gdi/state.cpp:148]: this code is not important?

File: src/renderer/gdi/paint.cpp [hunk 5]
```diff
@@ -445,10 +456,42 @@ using namespace Microsoft::Console::Render;
...
+
+                SCRIPT_STRING_ANALYSIS ssa;
+                hr = ScriptStringAnalyse(_hdcMemoryContext, t.lpstr, t.n, 0, -1, SSA_GLYPHS | SSA_FALLBACK, 0, nullptr, &ss, t.pdx, nullptr, nullptr, &ssa);
+                if (FAILED(hr))
+                {
+                    break;
+                }
+
+                hr = ScriptStringOut(ssa, t.x, t.y, t.uiFlags, &t.rcl, 0, 0, FALSE);
+                std::ignore = ScriptStringFree(&ssa);
```
Comment (DHowett) [inline src/renderer/gdi/paint.cpp:490]: clever! is std::ignore supported in the version of C++ that Windows builds with?

Comment (DHowett) [reply src/renderer/gdi/paint.cpp:490]: keep in mind thsi may be backported to earlier versions of Windows, stuck on c++17

**Review by DHowett — APPROVED** [review]

File: src/renderer/gdi/lib/gdi.vcxproj (hunk 3 above)
Comment (lhecker) [reply src/renderer/gdi/lib/gdi.vcxproj:27]: We do need this dependency because otherwise the linker complains that it can't find the Script* Unicode symbols. The docs only warn that the import order is apparently important on older OS.

File: src/renderer/gdi/paint.cpp (hunk 5 above)
Comment (lhecker) [reply src/renderer/gdi/paint.cpp:490]: Yeah `std::ignore` is C++11.

File: src/renderer/gdi/lib/gdi.vcxproj (hunk 3 above)
Comment (DHowett) [reply src/renderer/gdi/lib/gdi.vcxproj:27]: I see. In that case, you must make sure that any sources file that consumes RendererGdi is updated to link with this library as well

File: src/renderer/gdi/state.cpp (hunk 4 above)
Comment (lhecker) [reply src/renderer/gdi/state.cpp:148]: It works without this and allowed me to centralize the `FontHasWesternScript` call.
AtlasEngine doesn't set up any font related state until `UpdateFont` is called and it works properly. As such I'm sure that `SetHwnd` doesn't need to do that either. `UpdateFont` remains unmodified in this PR (apart from `_lastFontType` which is now part of `BeginPaint`).

My original intention was to write some code that ensures that `_fontHasWesternScript` is updated whenever `_lastFontType` is changed. Unfortunately GdiEngine is rather stateful and I was unable to come up with something that works properly. I'll try and see if I can do something about that.

File: src/renderer/gdi/lib/gdi.vcxproj (hunk 3 above)
Comment (miniksa) [reply src/renderer/gdi/lib/gdi.vcxproj:27]: Specifically the "sources" and "dirs" files for the Windows nmake build. It will be very important to ensure those work after this change.

**Review by miniksa — CHANGES_REQUESTED** [review]
We need to double check that this has the right nmake build changes too.

**Comment by j4james** [comment]
FYI, here's what it looks like using double width/height formatting. The second sample is the title from [Arabic Wikipedia article](https://ar.wikipedia.org/wiki/%D8%A7%D9%84%D9%84%D8%BA%D8%A9_%D8%A7%D9%84%D8%B9%D8%B1%D8%A8%D9%8A%D8%A9). Both samples have been manually reversed so they make sense.

image

Note that scrolling horizontally has some issues with the Arabic text, but that was to be expected. If you pan to the right and then back again, it has to redraw the characters individually (if you're going slow enough), so the ligatures won't render correctly and you can get something like this.

image

Cursoring over the text can have the same effect. I suspect using full-row invalidation might fix that, but this is not a new problem, and isn't specific to RTL content.

This is so much better than I ever thought we would achieve, so I'm thrilled with this PR.

File: src/renderer/gdi/lib/sources [hunk 6]
```diff
@@ -6,3 +6,4 @@
 
 TARGETNAME              = ConRenderGdi
 TARGETTYPE              = LIBRARY
+TARGETLIBS              = $(SDK_LIB_PATH)\usp10.lib
```
Comment (DHowett) [inline src/renderer/gdi/lib/sources:9]: Unfortunately, this won't work because ConRenderGdi is a static lib itself. Windows' build system doesn't roll up `TARGETLIBS` from dependency projects.

Your best bet will be to find _any `sources` file_ that mentions `ConRenderGdi.lib` by name and add this to its existing `TARGETLIBS`.

**Comment by DHowett** [comment]
From chat:

> you know what? you probably don't need to add usp10 to any sources files in this repo at all. _we already have a dependency on ​`ext-ms-win-gdi-internal-desktop-l1`_. that's the Extension APIset that hosts usp10.

**Review by miniksa — APPROVED** [review]
Dustin told me to quit blocking over sources files.

**Review by DHowett — APPROVED** [review]
