### PR TITLE
Reduce CursorChanged Events for Accessibility

### LINKED ISSUE #5143: Accessibility: jumps in review
# Environment

Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]: 1909 (18363.720)

Windows Terminal version (if applicable): Terminal as of 5bcf0fc.

Any other software? NVDA, Narrator.

# Steps to reproduce

1. type:

``` shell
echo 1
echo 2
echo 3
```

2. Using NVDA with Windows Terminal support or Narrator, review a few previous lines of output. You should see the prompt, then 3, 2, 1.
3. wait about three seconds.
4. Try to review previous line again.

# Expected behavior
The screen reader keeps its position, reporting "2" for example if the last-reviewed line was "3".

# Actual behavior
The screen reader reads the prompt again, then starts back over with 3, almost as if the cursor bounced back.

### PR DESCRIPTION
**Pull request by carlos-zamora**
## Summary of the Pull Request
Reduce the number of times we dispatch a cursor changed event. We were firing it every time the renderer had to do anything related to the cursor. Unfortunately, blinking the cursor triggered this behavior. Now we just check if the position has changed.

## PR Checklist
* [X] Closes #5143

## Validation Steps Performed
Verified using Narrator
Also verified #3791 still works right

### CODE REVIEW

File: src/renderer/uia/UiaRenderer.cpp [hunk 1]
```diff
@@ -246,7 +255,6 @@ UiaEngine::UiaEngine(IUiaEventDispatcher* dispatcher) :
     _selectionChanged = false;
     _textBufferChanged = false;
     _cursorChanged = false;
-    _prevSelection.clear();
```
Comment (DHowett-MSFT) [inline src/renderer/uia/UiaRenderer.cpp]: ???

Comment (DHowett-MSFT) [reply src/renderer/uia/UiaRenderer.cpp]: wots all this then eh

Comment (carlos-zamora) [reply src/renderer/uia/UiaRenderer.cpp]: Well, I realized, why should we clear the previousSelection between frames? If it's clear when we render a new frame, we'll always have the selection be "new". So, this should reduce the number of times we send a selection event too.

**Comment by codeofdusk** [comment]
It seems that Azure CI doesn't provide artefacts for PRs. Could you please upload (or point me at) a build for testing?

**Comment by carlos-zamora** [comment]
> It seems that Azure CI doesn't provide artefacts for PRs. Could you please upload (or point me at) a build for testing?

Your best bet would be that you have to build the branch yourself. I tried uploading a ZIP of the package but GitHub said it was too large. I'm merging this change into master now, though, so let us know if you encounter any issues.

**Comment by codeofdusk** [comment]
Working great with NVDA, thanks!

As an aside, it doesn't look like the .msix packages from Azure are installable. Renaming to .zip and extracting allows me to run the terminal/console, but just opening the package gives me an error that the package isn't signed. Is there any way to disable the signature check? Developer mode is enabled on my machine.

**Comment by DHowett-MSFT** [comment]
Unfortunately, that's one of the huge pain points with this project on the development side. There's no way to turn off signature checking, even for locally-installed locally-produced packages :frowning:

Sometimes it's just easier to extract the msix like a zip file and run WindowsTerminal.exe out of it. We haven't broken that, and we do _sorta_ try to make sure it doesn't break. :smile:

**Comment by DHowett-MSFT** [comment]
Thanks again for testing. There's probably something we can do to make this more palatable.
