### PR TITLE
GetGuid noexcept Fix

### LINKED ISSUE #3763: GetGuid noexcept function throws
# Environment

```none
Windows build number: 0.0.1.0 Dev Build
Windows Terminal version (if applicable): 10.0.18363
```

# Steps to reproduce

Invoke [`Profile::GetGuid`](https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalApp/Profile.cpp#L141) on a `Profile` object without a GUID.

# Expected behavior

`GetGuid` is specified as `noexcept`, the compiler and users expect the function to never throw.

# Actual behavior

Exception thrown by a `noexcept` function.

New function semantics need to be decided for `GetGuid` and functions affected by `GetGuid` no longer being `noexcept`. Could be fixed by removing the `noexcept` specifier from the function and all affected functions.

### PR DESCRIPTION
**Pull request by mkitzan**
## Summary of the Pull Request
Fixed the noexcept specifier on `GetGuid`, and corrected `FindProfile` and `FindGuid` so they don't throw. Also, adjusted `SettingsTests` to reflect these changes.

 
## PR Checklist
* [x] Closes #3763
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [x] Tests added/passed updated a test group in `SettingsTests`
* [ ] Requires documentation to be updated
* [x] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #3763

## Detailed Description of the Pull Request / Additional comments
The `noexcept` specifier on `GetGuid` was not removed when `Profile` was [updated](https://github.com/microsoft/terminal/issues/3763#issuecomment-559497094) to `std::optional<GUID>`. This PR fixes that and modifies two helper functions `FindProfile` and `FindGuid` in `CascadiaSettings` to work correctly if `GetGuid` does throw. 

## Validation Steps Performed
Updated the `TestHelperFunctions` test group in `SettingsTests` and made sure the tests pass.

### CODE REVIEW

File: src/cascadia/TerminalApp/CascadiaSettings.cpp [hunk 1]
```diff
@@ -78,7 +78,15 @@ std::optional<GUID> CascadiaSettings::FindGuid(const std::wstring& profileName)
...
         {
-            profileGuid = profile.GetGuid();
+            try
+            {
+                profileGuid = profile.GetGuid();
+            }
+            catch (...)
+            {
+                LOG_CAUGHT_EXCEPTION();
+            }
```
Comment (carlos-zamora) [inline src/cascadia/TerminalApp/CascadiaSettings.cpp]: You should be able to replace this with `CATCH_LOG();` I think.

Comment (mkitzan) [reply src/cascadia/TerminalApp/CascadiaSettings.cpp]: That makes sense. I thought something was off with this.

**Comment by mkitzan** [comment]
Wonder what the deal is with x86 build? Stalled out at unit testing.

**Comment by DHowett-MSFT** [comment]
/azp run

It happens sometimes :smile:

**Comment by DHowett-MSFT** [comment]
_really_?

/azp run

**Comment by mkitzan** [comment]
Thanks for the re-run 🎉
