### PR TITLE
Workaround C++/WinRT's multi-level composition class refcount issue

### LINKED ISSUE #1339: [~75% IMPACT] Crash on natural app exit because of composition class issue (XamlApplication)
The "correct" fix for this is to make our `XamlApplication` `AddRef` its `outer`. C++/WinRT generates bad code here. Long term, we need to fix our XamlApplication stack.

_Bug 22116519: C++/WinRT composable+composing types don't delegate calls during construction_

### PR DESCRIPTION
**Pull request by DHowett-MSFT**
Fixes #1339.

* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [x] I've discussed this with core contributors already.

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
@ocalvo I brought this change over from your branch. Is it correct to fix the teardown crash? It started hitting us very hard in version 0.2.

File: src/cascadia/TerminalApp/App.cpp [hunk 1]
```diff
@@ -51,6 +51,8 @@ namespace winrt::TerminalApp::implementation
         // then it might look like App just failed to activate, which will
         // cause you to chase down the rabbit hole of "why is App not
         // registered?" when it definitely is.
+        AddRef();
```
Comment (zadjii-msft) [inline src/cascadia/TerminalApp/App.cpp]:
```suggestion

        // See GH#1339. This is a workaround for MSFT:22116519
        // We need this to prevent an occasional crash on teardown
        AddRef();
```
