### PR TITLE
Fix Windows 10 support for nearby font loading

### LINKED ISSUE #12420: Unable to find the selected font "Cascadia Mono"
### Windows Terminal version

1.13.10336.0

### Windows build number

10.0.19044.0

### Other Software

I have both Windows Terminal (1.11.3471.0) and Windows Terminal Preview (1.13.10336.0) installed. The Store says Windows Terminal Preview updated today, but both apps are unable to find the "Cascadia Mono" font, which I'm told should be bundled with the app.

### Steps to reproduce

Open Windows Terminal Preview

### Expected Behavior

A "Warning" popup does not appear.

### Actual Behavior

A "Warning" popup in the Terminal window appears with the following text
```
Unable to find the selected font "Cascadia Mono".

"Consolas" has been selected instead.

Please either install the missing font or choose another one.
```

### PR DESCRIPTION
**Pull request by lhecker**
By replacing `IDWriteFontSetBuilder2::AddFontFile` with
`IDWriteFactory5::CreateFontFileReference` and
`IDWriteFontSetBuilder1::AddFontFile` we add nearby
font loading support for Windows 10, build 15021.

This commit also fixes font fallback for AtlasEngine,
which was crashing during testing.

Finally it fixes a bug in DxEngine, where we only created a "nearby" font
collection if we couldn't find the font in the system collection. This doesn't
fix the bug, if the font is locked or broken in the system collection.

This is related to #11648.

## PR Checklist
* [x] Closes #12420
* [x] I work here
* [x] Tests added/passed

## Validation Steps Performed
* Build a Debug version of Windows Terminal
* Put Jetbrains Mono into the writeable AppX directory
* Jetbrains Mono is present in the settings UI ✅
* DxEngine works with Jetbrains Mono ✅
* AtlasEngine works with Jetbrains Mono ✅

### CODE REVIEW

File: src/renderer/atlas/FontCache.h [hunk 1]
```diff
@@ -0,0 +1,114 @@
+// Copyright (c) Microsoft Corporation.
+// Licensed under the MIT license.
+
+#pragma once
+
+#include <dwrite_3.h>
+
+namespace Microsoft::Console::Render::Atlas::FontCache
```
Comment (lhecker) [inline src/renderer/atlas/FontCache.h:8]: I really didn't know where to put this stuff, so I put it here in the hopes we'll remove DxEngine one day and then it's just ~me and you~ AtlasEngine and two calls from WT-land.

File: src/renderer/atlas/AtlasEngine.api.cpp [hunk 2]
```diff
@@ -401,7 +403,50 @@ void AtlasEngine::ToggleShaderEffects() noexcept
...
+#pragma endregion
+
+void AtlasEngine::_resolveAntialiasingMode() noexcept
+{
+    // If the user asks for ClearType, but also for a transparent background
+    // (which our ClearType shader doesn't simultaneously support)
+    // then we need to sneakily force the renderer to grayscale AA.
+    const auto forceGrayscaleAA = _api.antialiasingMode == D2D1_TEXT_ANTIALIAS_MODE_CLEARTYPE && !_api.backgroundOpaqueMixin;
+    _api.realizedAntialiasingMode = forceGrayscaleAA ? D2D1_TEXT_ANTIALIAS_MODE_GRAYSCALE : _api.antialiasingMode;
+}
```
Comment (lhecker) [inline src/renderer/atlas/AtlasEngine.api.cpp:447]: This code isn't new. It's just moved up from down below to group the code better.

File: src/renderer/atlas/FontCache.h (hunk 1 above)
Comment (lhecker) [reply src/renderer/atlas/FontCache.h:8]: Maybe we should put this into the DxEngine project so that we can backport it to 1.12?

Comment (DHowett) [reply src/renderer/atlas/FontCache.h:8]: Yes please. I'd rather it be somewhere easy to backport. :)

File: src/cascadia/TerminalApp/AppLogic.cpp [hunk 3]
```diff
@@ -1065,6 +1065,7 @@ namespace winrt::TerminalApp::implementation
         _ApplyStartupTaskStateChange();
 
         Jumplist::UpdateJumplist(_settings);
+        ::Microsoft::Console::Render::Atlas::FontCache::Invalidate();
```
Comment (DHowett) [inline src/cascadia/TerminalApp/AppLogic.cpp:1068]: This is not going to do the right thing once @zadjii-msft lands "content process" terminal hosting. Do we need to do this? Unless our new font cache messes up _system font loading_ i'd rather not...

File: src/cascadia/TerminalSettingsEditor/ProfileViewModel.cpp [hunk 4]
```diff
@@ -166,15 +119,8 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
...
-        // get a DWriteFactory
-        com_ptr<IDWriteFactory> factory;
-        THROW_IF_FAILED(DWriteCreateFactory(
-            DWRITE_FACTORY_TYPE_SHARED,
-            __uuidof(IDWriteFactory),
-            reinterpret_cast<::IUnknown**>(factory.put())));
-
         // get the font collection; subscribe to updates
-        const auto fontCollection = NearbyCollection(factory.get());
+        const auto fontCollection = ::Microsoft::Console::Render::Atlas::FontCache::Get(true);
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/ProfileViewModel.cpp:123]: reading this, i do not love "get true". What does it mean?

File: src/renderer/atlas/AtlasEngine.api.cpp (hunk 2 above)
Comment (DHowett) [reply src/renderer/atlas/AtlasEngine.api.cpp:447]: this makes it difficult to review the diff -- can you point out the part that fixed the fallback issue you mentioned?

File: src/cascadia/TerminalApp/AppLogic.cpp (hunk 3 above)
Comment (lhecker) [reply src/cascadia/TerminalApp/AppLogic.cpp:1068]: Which function gets called in the content processes when we reload the settings.json?

File: src/renderer/atlas/AtlasEngine.api.cpp (hunk 2 above)
Comment (lhecker) [reply src/renderer/atlas/AtlasEngine.api.cpp:447]: Well, frankly, I didn't move the code.
It's just git diffing it poorly and no builtin algorithm improves this diff. The `_updateFont` function is new.

File: src/cascadia/TerminalApp/AppLogic.cpp (hunk 3 above)
Comment (DHowett) [reply src/cascadia/TerminalApp/AppLogic.cpp]: Good question. @zadjii-msft?

File: src/renderer/base/FontCache.h [hunk 5]
```diff
@@ -0,0 +1,120 @@
...
+
+namespace Microsoft::Console::Render::FontCache
+{
+    namespace details
+    {
+        struct Cache
+        {
+            void Invalidate() noexcept
+            {
+                _lock.lock();
```
[the remark this answers is not in the document]
Comment (lhecker) [reply src/renderer/base/FontCache.h:16]: Premise: I want this function to be `noexcept`.
Problem: None of the stdlib RAII wrappers are declared as noexcept, even though for all practical purposes a SRWLOCK as used in `std::shared_mutex` cannot throw. In order to not have to use `#pragma` annotations I'm using manual locking here.

What do you think about this problem?

File: src/renderer/base/FontCache.h [hunk 6]
```diff
@@ -0,0 +1,120 @@
...
+            }
+
+            wil::com_ptr<IDWriteFontCollection> Get(bool forceUpdate)
+            {
+                std::lock_guard guard{ _lock };
+
+                if (!_fontCollection || forceUpdate)
+                {
+                    _init(forceUpdate);
+                    FAIL_FAST_IF(!_fontCollection);
```
[the remark this answers is not in the document]
Comment (lhecker) [reply src/renderer/base/FontCache.h:28]: The PR that introduced all these fail-fasts into our code base made a pretty good point which I've never considered before: Fail-fasts make invariant-violations very obvious and easy to debug in our code base.
While exceptions are supposed to be just as easy to use, the existence of COM makes that a bit more difficult, because of their catch-all clauses.

So this fail-fast here is because I want to `assert()` that `_init()` really did create a `_fontCollection`, even if someone where to modify the code in the future. It ensures we don't return a null-pointer basically.

Alternatively I'd use `assert()` here or throw an exception.

File: src/renderer/base/FontCache.h (hunk 5 above)
[the remark this answers is not in the document]
Comment (DHowett) [reply src/renderer/base/FontCache.h:16]: I'm okay with this solution! :)

File: src/renderer/base/FontCache.h (hunk 6 above)
[the remark this answers is not in the document]
Comment (DHowett) [reply src/renderer/base/FontCache.h:28]: Sounds great to me -- I was imagining the failfasts that we used to have in buffer motion/coordinate walk that blew up the product for folks anyway.

**Comment by lhecker** [comment]
> What if the font exists in the system set, but is unreadable due to a permission error? Would we find a "nearby" version **of the same** font and load it? That is the core of the issue with Cascadia on upgrade.

With the Windows Font Cache Service enabled I can't get my system in a state where Jetbrains Mono isn't available since it remains cached even after the .ttf file had its ACLs changed. If I disable that service, DirectWrite properly won't support the font at all. In short: I can't get my system to replicate the issue even after changing the ACLs.

In theory this approach should fix the issue, because we append the "nearby fonts" last to the collection, due to which they should take priority over the system fonts. I suspect that the people for whom this doesn't work, mostly used Windows 10, where this fix didn't work.

File: src/cascadia/TerminalApp/AppLogic.cpp [hunk 7]
```diff
@@ -1065,6 +1065,7 @@ namespace winrt::TerminalApp::implementation
         _ApplyStartupTaskStateChange();
 
         Jumplist::UpdateJumplist(_settings);
+        ::Microsoft::Console::Render::FontCache::Invalidate();
```
Comment (DHowett) [inline src/cascadia/TerminalApp/AppLogic.cpp:1068]: Notes lost in rebase:

> This is not going to do the right thing once @zadjii-msft lands "content process" terminal hosting. Do we need to do this? Unless our new font cache messes up _system font loading_ i'd rather not...

> Which function gets called in the content processes when we reload the settings.json?

I want to understand why we're clearing the cache here, and what this cache means for Terminal being able to access system fonts that are installed after it is launched...

File: src/renderer/base/FontCache.h [hunk 8]
```diff
@@ -0,0 +1,120 @@
...
+
+                    const std::filesystem::path module{ wil::GetModuleFileNameW<std::wstring>(nullptr) };
+                    const auto folder{ module.parent_path() };
+
+                    for (const auto& p : std::filesystem::directory_iterator(folder))
+                    {
+                        if (til::ends_with(p.path().native(), L".ttf"))
+                        {
+                            wil::com_ptr<IDWriteFontFile> fontFile;
+                            if (SUCCEEDED_LOG(factory5->CreateFontFileReference(p.path().c_str(), nullptr, fontFile.addressof())))
```
Comment (DHowett) [inline src/renderer/base/FontCache.h:65]: will this log generate a telemetry event using WIL's registered logging handler? Should we log on success? Am I getting this backwards, and it logs if failed only?

File: src/renderer/dx/DxFontInfo.cpp [hunk 9]
```diff
@@ -335,48 +335,14 @@ void DxFontInfo::SetFromEngine(const std::wstring_view familyName,
...
-
-    ::Microsoft::WRL::ComPtr<IDWriteFontSet> fontSet;
-    THROW_IF_FAILED(fontSetBuilder2->CreateFontSet(&fontSet));
-
-    ::Microsoft::WRL::ComPtr<IDWriteFontCollection1> fontCollection;
-    THROW_IF_FAILED(factory6->CreateFontCollectionFromFontSet(fontSet.Get(), &fontCollection));
-
-    _nearbyCollection = fontCollection;
-    return _nearbyCollection.Get();
+    return _nearbyCollection.get();
```
Comment (DHowett) [inline src/renderer/dx/DxFontInfo.cpp:345]: since FontCache is managing the cache... do we need to keep `_nearbyCollection` at all? Won't it result in torn state when the cache is flushed, but existing dwrite engines use the OLD cache?

File: src/renderer/dx/lib/dx.vcxproj [hunk 10]
```diff
@@ -41,4 +41,4 @@
   </ItemGroup>
   <!-- Careful reordering these. Some default props (contained in these files) are order sensitive. -->
   <Import Project="$(SolutionDir)src\common.build.post.props" />
-</Project>
+</Project>
```
Comment (DHowett) [inline src/renderer/dx/lib/dx.vcxproj:44]: mind reverting this file and the filters file for this project?

**Review by DHowett — CHANGES_REQUESTED** [review]

File: src/renderer/base/FontCache.h (hunk 8 above)
Comment (lhecker) [reply src/renderer/base/FontCache.h]: Yeah, `SUCCEEDED_LOG` only logs on failure. It's a shorthand for `SUCCEEDED(LOG_IF_FAILED(hr))`.

**Comment by lhecker** [comment]
FYI I made the following changes to the PR:
* No more caching of the font collection (ergo no invalidation required)
* DxEngine now always creates a nearby font collection, so that we never try to use the installed Cascadia font
* Added feature flagging to remove the nearby font loading from conhost, if we ever decide to ship Atlas/DxEngine with conhost
  We should do the same with OpenConsole, however we don't have a macro to control that just yet.

File: src/renderer/base/FontCache.h [hunk 11]
```diff
@@ -0,0 +1,96 @@
...
+                    }
+                }
+
+                files.shrink_to_fit();
+                return files;
+            }();
+            return fontFiles;
+        }
+
+        inline wil::com_ptr<IDWriteFontCollection> getFontCollection(bool forceUpdate)
```
Comment (zadjii-msft) [inline src/renderer/base/FontCache.h:36]: I'm kinda just trusting that this bit of the code will work as expected. I don't totally know the mechanical differences between a `IDWriteFactory6` and a `IDWriteFactory`, or a `IDWriteFontSetBuilder1` and a `IDWriteFontSetBuilder2`, but I'm trusting it works

**Review by zadjii-msft — APPROVED** [review]
k I'm happy the spooky action at a distance is gone

File: src/renderer/base/FontCache.h (hunk 11 above)
Comment (lhecker) [reply src/renderer/base/FontCache.h:36]: BTW the new code is what `IDWriteFontSetBuilder2::AddFontFile` does internally. It's implemented in terms of `IDWriteFontSetBuilder1::AddFontFile`.

File: src/renderer/atlas/AtlasEngine.api.cpp [hunk 12]
```diff
@@ -401,7 +403,50 @@ void AtlasEngine::ToggleShaderEffects() noexcept
 }
 
 [[nodiscard]] HRESULT AtlasEngine::UpdateFont(const FontInfoDesired& fontInfoDesired, FontInfo& fontInfo, const std::unordered_map<std::wstring_view, uint32_t>& features, const std::unordered_map<std::wstring_view, float>& axes) noexcept
-try
+{
+    static constexpr std::array fallbackFaceNames{ static_cast<const wchar_t*>(nullptr), L"Consolas", L"Lucida Console", L"Courier New" };
+    auto it = fallbackFaceNames.begin();
+    const auto end = fallbackFaceNames.end();
```
[the remark this answers is not in the document]
Comment (DHowett) [reply src/renderer/atlas/AtlasEngine.api.cpp:409]: > In the future

should we track this work?

File: src/renderer/base/FontCache.h [hunk 13]
```diff
@@ -0,0 +1,96 @@
...
+
+                const std::filesystem::path module{ wil::GetModuleFileNameW<std::wstring>(nullptr) };
+                const auto folder{ module.parent_path() };
+
+                for (const auto& p : std::filesystem::directory_iterator(folder))
+                {
+                    if (til::ends_with(p.path().native(), L".ttf"))
+                    {
+                        wil::com_ptr<IDWriteFontFile> fontFile;
+                        if (SUCCEEDED_LOG(factory5->CreateFontFileReference(p.path().c_str(), nullptr, fontFile.addressof())))
```
Comment (DHowett) [inline src/renderer/base/FontCache.h:23]: so it's safe to use these objects on different threads because it is a SHARED-type factory? neato

**Review by DHowett — APPROVED** [review]

File: src/renderer/atlas/AtlasEngine.api.cpp (hunk 12 above)
[the remark this answers is not in the document]
Comment (lhecker) [reply src/renderer/atlas/AtlasEngine.api.cpp:409]: I added a short note in #9999.

File: src/renderer/base/FontCache.h (hunk 13 above)
Comment (lhecker) [reply src/renderer/base/FontCache.h:23]: `DWRITE_FACTORY_TYPE_SHARED` only enables the use of the Windows Font Cache service for DirectWrite. It's unspecified whether DirectWrite is thread-safe, but it should be, since Direct2D can be used across threads. I'm gonna ask one of the dwrite devs about this...
