### PR TITLE
Fix invoking the rightmost breadcrumb bringing you back to Profiles_Base

### LINKED ISSUE #12325: SUI Breadcrumbs should have better keyboard navigation
### Windows Terminal version

1.13.10321.0

### Windows build number

22548.1002

### Other Software

None

### Steps to reproduce

(Part 1)
1. Open Settings UI
2. Go to a profile page
3. Press <kbd>Tab</kbd> repeatedly

(Part 2)
4. From a profile page, now open "Advanced" or "Appearance"
5. Press <kbd>Tab</kbd> repeatedly

### Expected Behavior

The right-most breadcrumb should not be a tab stop or invokable (or if it is invoked, it shouldn't do anything)

### Actual Behavior

Invoking "Advanced" or "Appearance" takes you back to the main profile page. 

### Additional Information
There's a chance that this (or some of this) should be filed on XAML. The goal here is to match what the settings app does.

### PR DESCRIPTION
**Pull request by PankajBhojwani**
## Summary of the Pull Request
We no longer do anything when the rightmost breadcrumb is invoked

## PR Checklist
* [x] Closes #12325 
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Documentation updated. If checked, please file a pull request on [our docs repo](https://github.com/MicrosoftDocs/terminal) and link it here: #xxx
* [ ] Schema updated.
* [x] I work here

## Validation Steps Performed
Tested manually, cannot repro #12325 anymore

### CODE REVIEW

File: src/cascadia/TerminalSettingsEditor/MainPage.cpp [hunk 1]
```diff
@@ -476,15 +476,18 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
 
     void MainPage::BreadcrumbBar_ItemClicked(Microsoft::UI::Xaml::Controls::BreadcrumbBar const& /*sender*/, Microsoft::UI::Xaml::Controls::BreadcrumbBarItemClickedEventArgs const& args)
     {
-        const auto tag = args.Item().as<Breadcrumb>()->Tag();
-        const auto subPage = args.Item().as<Breadcrumb>()->SubPage();
-        if (const auto profileViewModel = tag.try_as<ProfileViewModel>())
+        if (gsl::narrow_cast<uint32_t>(args.Index()) < (_breadcrumbs.Size() - 1))
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/MainPage.cpp:479]: you can make the diff smaller if you flip the condition around and do an early return. FWIW. No need, but good to think about!

**Review by DHowett — APPROVED** [review]

**Review by carlos-zamora — APPROVED** [review]

File: src/cascadia/TerminalSettingsEditor/MainPage.cpp (hunk 1 above)
Comment (PankajBhojwani) [reply src/cascadia/TerminalSettingsEditor/MainPage.cpp:479]: Ah I tend to avoid early returns but I guess for small functions like this it doesn't matter
