### PR TITLE
Display Unicode URIs side-by-side with their Punycode encoding

### LINKED ISSUE #15432: Homoglyphs in URL tooltips
### Windows Terminal version

1.18.1421.0

### Windows build number

10.0.19045.2913

### Other Software

_No response_

### Steps to reproduce

1. Open a bash shell in Windows Terminal
2. Execute the following command:
```
printf "\n\e]8;;https://www.xn--fcbook-3nf5b.com/\e\\TOTALLY REAL FACEBOOK LINK. YOU CAN TRUST ME.\e]8;;\e\\ \n\n"
```
3. Hover over the resulting link text to see where the URL is going to take you.

### Expected Behavior

There was a new feature advertised in the v1.18.1421.0 release notes that said "when you're hovering over a URL, we now display it in a partially-encoded form to help you avoid homoglyph attacks". So I expected there would be something in the tooltip indicating that this link was not exactly what it seemed.

### Actual Behavior

The URL displayed in the tooltip gives the impression that it's linking to `https://www.facebook.com/`, which is very misleading.

image

Does PR #15095 perhaps rely on functionality that's only available in Windows 11?

### PR DESCRIPTION
**Pull request by lhecker**
06174a9 didn't properly fix the issue of us showing homoglyphs in our
URI tooltip. This commit introduces a different approach where we
display both, the Punycode and Unicode encoding, whenever we encounter
an IDN. This isn't perfect but simple to implement.

Closes #15432

## Validation Steps Performed
* `https://www.xn--fcbook-3nf5b.com/` (which contains confusing glyphs)
  is shown both in its Punycode and Unicode form simultaneously. ✅

### CODE REVIEW

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 1]
```diff
@@ -3042,56 +3042,85 @@ namespace winrt::Microsoft::Terminal::Control::implementation
         _core.ClearHoveredCell();
     }
 
-    winrt::fire_and_forget TermControl::_hoveredHyperlinkChanged(IInspectable /*sender*/,
-                                                                 IInspectable /*args*/)
+    // Attackers abuse Unicode characters that happen to look similar to ASCII characters. Cyrillic for instance has
```
Comment (lhecker) [inline src/cascadia/TerminalControl/TermControl.cpp:3045]: [You should suppress whitespace changes!](https://github.com/microsoft/terminal/pull/15488/files?w=1)

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 2]
```diff
@@ -3042,56 +3042,85 @@ namespace winrt::Microsoft::Terminal::Control::implementation
...
+
+    void TermControl::_hoveredHyperlinkChanged(const IInspectable& /*sender*/, const IInspectable& /*args*/)
+    {
+        const auto lastHoveredCell = _core.HoveredCell();
+        if (!lastHoveredCell)
+        {
+            return;
         }
+
+        const auto uriText = sanitizeURI(_core.HoveredUriText());
```
Comment (lhecker) [inline src/cascadia/TerminalControl/TermControl.cpp:3098]: I'm not sure if we should encode URIs to Punycode a little earlier than this... If the encoding to Punycode fails, we shouldn't even allow the option to click it.

**Comment by zadjii-msft** [comment]
wait can you ctrl+click invalid URIs?

**Comment by DHowett** [comment]
send a screenshot!

**Comment by lhecker** [comment]
> wait can you ctrl+click invalid URIs?

Yep, you can. It just might not work, because the OS validates them. For instance, this doesn't work:
```pwsh
"`n`e]8;;https://www.`u{202e}xn--fcbook-3nf5b.com/`e\TOTALLY REAL FACEBOOK LINK. YOU CAN TRUST ME.`e]8;;`e\ `n`n"
```
but this does (the a and e in "facebook" are not ASCII):
```pwsh
"`n`e]8;;https://www.`u{202e}fаcеbook.com/`e\TOTALLY REAL FACEBOOK LINK. YOU CAN TRUST ME.`e]8;;`e\ `n`n"
```
...which is a little concerning. You get this message instead:
image

> send a screenshot!

What would you like to see? A comment above shows 2 situations - I'd be happy to make more.

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 2 above)
Comment (DHowett) [reply src/cascadia/TerminalControl/TermControl.cpp:3098]: Honestly, I am OKAY with this.

Thanks so much.

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 3]
```diff
@@ -3042,56 +3042,85 @@ namespace winrt::Microsoft::Terminal::Control::implementation
...
+    // xn--cnn.com for instance looks confusingly similar to cnn.com, but actually represents U+407E.
+    //
+    // An optimal solution would detect any URI that contains homoglyphs and show them in their Punycode form.
+    // Such a detector however is not quite trivial and requires constant maintenance, which this project's
+    // maintainers aren't currently well equipped to handle. As such we do the next best thing and show the
+    // Punycode encoding side-by-side with the Unicode string for any IDN.
+    static winrt::hstring sanitizeURI(winrt::hstring uri)
     {
-        auto weakThis{ get_weak() };
-        co_await wil::resume_foreground(Dispatcher());
```
Comment (DHowett) [inline src/cascadia/TerminalControl/TermControl.cpp:3049]: This is another instance where we were switching to the foreground to make touching UI objects safe. _Are we convinced that this is safe?_

**Review by DHowett — CHANGES_REQUESTED** [review]
Notes and Qs.

Generally, I am 100% happy with this. Just the UI thread concern!

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 3 above)
Comment (lhecker) [reply src/cascadia/TerminalControl/TermControl.cpp:3049]: The only place `_hoveredHyperlinkChanged` is called from is the `_core.HoveredHyperlinkChanged()` event. `_HoveredHyperlinkChangedHandlers` is only called in `ControlCore::_updateHoveredCell`, which in turn is only called by `SetHoveredCell` and `ClearHoveredCell`. The former is only called by `ControlInteractivity::PointerMoved` which is a UI-thread-only function and the latter is only called by `TermControl::_PointerExitedHandler` which is the same. BTW It's somewhat weird that `PointerMoved` us in `ControlInteractivity`, but "pointer exited" isn't.

So yeah this can only be called from the UI thread.

File: src/cascadia/TerminalControl/Resources/en-US/Resources.resw [hunk 4]
```diff
@@ -178,6 +178,10 @@
   <data name="HowToOpenRun.Text" xml:space="preserve">
     <value>Ctrl+Click to follow link</value>
   </data>
+  <data name="InvalidUri" xml:space="preserve">
+    <value>Invalid URI</value>
+    <comment>Whenever we encounter an invalid URI or URL we show this string as a warning.</comment>
```
Comment (carlos-zamora) [inline src/cascadia/TerminalControl/Resources/en-US/Resources.resw:183]:
```suggestion
    <comment>Whenever we encounter an invalid URI or URL we show this string as an error.</comment>
```
nit

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 5]
```diff
@@ -3042,56 +3042,85 @@ namespace winrt::Microsoft::Terminal::Control::implementation
         _core.ClearHoveredCell();
     }
 
-    winrt::fire_and_forget TermControl::_hoveredHyperlinkChanged(IInspectable /*sender*/,
-                                                                 IInspectable /*args*/)
+    // Attackers abuse Unicode characters that happen to look similar to ASCII characters. Cyrillic for instance has
+    // its own glyphs for а, с, е, о, р, х, and у that look practically identical to their ASCII counterparts.
+    // This is called a "IDN homoglyph attack".
```
Comment (carlos-zamora) [inline src/cascadia/TerminalControl/TermControl.cpp:3047]:
```suggestion
    // This is called an "IDN homoglyph attack".
```

**Review by carlos-zamora — APPROVED** [review]

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 3 above)
Comment (DHowett) [reply src/cascadia/TerminalControl/TermControl.cpp:3049]: That's technically an implementation detail, but I'll allow it ;P

**Review by DHowett — APPROVED** [review]
I am okay merging without fixing Carlos' comments honestly

File: src/cascadia/TerminalControl/Resources/en-US/Resources.resw (hunk 4 above)
Comment (lhecker) [reply src/cascadia/TerminalControl/Resources/en-US/Resources.resw:183]: Hmm I feel like "as a warning" is better in this case. 🤔
