### PR TITLE
Fix title being stuck after toggling "showTerminalTitleInTitlebar"

### LINKED ISSUE #12871: Application title stuck on "Settings" after Use active terminal title as application title is disabled
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.19044.1586

### Other Software

_No response_

### Steps to reproduce

Enable "Use active terminal title as application title"
Disable "Use active terminal title as application title"

image

### Expected Behavior

Title should revert to "Windows Terminal"

### Actual Behavior

Title remains "Settings"

### PR DESCRIPTION
**Pull request by DHowett**
We already have the logic to fall back when the setting is disabled, we just _also_ had a terrible eventing architecture and never used the `Title` getter that was smart enough to figure it out.

This pull request somewhat disentangles the mess that is title handling. For example, TerminalPage had a facility to get its current title! It was never used. Once we started using it, it wouldn't work for the Settings page... because it only read the title out of the active control.

Closes #12871
Closes #19139 (superseded)

### CODE REVIEW

File: src/cascadia/TerminalApp/TerminalPage.cpp [hunk 1]
```diff
@@ -3694,6 +3684,9 @@ namespace winrt::TerminalApp::implementation
         _updateThemeColors();
 
         _updateAllTabCloseButtons();
+
+        // The user may have changed the "show title in titlebar" setting.
+        TitleChanged.raise(*this, nullptr);
```
Comment (DHowett) [inline src/cascadia/TerminalApp/TerminalPage.cpp:3689]: This is the actual heart of the fix. When the settings change, just fire off this event indiscriminately.

Comment (DHowett) [reply src/cascadia/TerminalApp/TerminalPage.cpp:3689]: Yes, it will go through and recalculate the title for every window. That is _so small_ compared to the burden of reloading the entire settings. :)

File: src/cascadia/WindowsTerminal/AppHost.cpp [hunk 2]
```diff
@@ -395,19 +395,10 @@ void AppHost::_revokeWindowCallbacks()
...
-// Arguments:
-// - sender: unused
-// - newTitle: the string to use as the new window title
-// Return Value:
-// - <none>
-void AppHost::_AppTitleChanged(const winrt::Windows::Foundation::IInspectable& /*sender*/, winrt::hstring newTitle)
+//   a window message so we can update the window's title on the main thread.
+void AppHost::_AppTitleChanged(const winrt::Windows::Foundation::IInspectable& /*sender*/, const winrt::Windows::Foundation::IInspectable& /*args*/)
 {
-    if (_windowLogic.GetShowTitleInTitlebar())
```
Comment (DHowett) [inline src/cascadia/WindowsTerminal/AppHost.cpp:407]: removing these checks across the codebase consolidates the behavior in TerminalPage::Title.

**Review by que-mark — APPROVED** [review]

**Review by carlos-zamora — APPROVED** [review]
