### PR TITLE
Remove a heap of legacy settings deserialization

### LINKED ISSUE #1069: Remove deserialization of legacy json keys
I'm thinking primarily of:
* Globals in the root of the json object (which changed with #1005)
* the `table` in a colorscheme as an array, not names
* the entirely missing keybindings key (maybe we want to leave this however, or it could be fixed by #754 )
* The legacy `colorscheme` key (changed to `colorScheme` with #1054 )
* remove `colorTable` (#4091)

### LINKED ISSUE #4091: `profile.colorTable` is broken
Setting a `colorTable` in a profile was broken in microsoft/terminal@8ba8f35dc5 when we set the default `_schemeName` to `Campbell`. During the construction of a `TerminalSettings`, we apply the table and _then_ the scheme. If we do it in a different order, or delete `_schemeName` when we find `colorTable`, it works fine.

_However:_ nobody noticed. This is the perfect opportunity to _kill that feature_ or _replace it with "`colorTable` overlays on top of the scheme"_!

Related: #1069.

### PR DESCRIPTION
**Pull request by DHowett-MSFT**
This pull request removes support for:

* legacy keybindings of all types
* `colorScheme.colors`, as an array
* A `globals` object in the root of the settings file
* `profile.colorTable` and `profile.colorscheme` (the rare v0.1 all-lowercase variety)

### bba1d651f3d532f8d46be6e29c72a6097cab60b4 - Settings: Remove support for /globals

Fixes #4091.
Fixes #1069.

### CODE REVIEW

File: src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp [hunk 1]
```diff
@@ -56,8 +56,6 @@ namespace TerminalAppLocalTests
         TEST_METHOD(TestInvalidColorSchemeName);
         TEST_METHOD(TestHelperFunctions);
 
-        TEST_METHOD(TestLayerGlobalsOnRoot);
```
Comment (carlos-zamora) [inline src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp]: You're right that we don't need a test for this anymore. But now I'm curious, what happens if a user still had globals? Is everything inside globals just ignored?

Comment (DHowett-MSFT) [reply src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp]: Yes, it’s ignored.
