### PR TITLE
Fix crash when closing multiple splits from the tab context menu

### LINKED ISSUE #9021: Crash when closing a tab with multiple splits from the tab context menu
1. open two tabs
2. in the first, make two panes
3. try to close the tab from the right-click "Close Tab" option. 
4. Experience exception:

```
    TerminalApp.dll!std::_Throw_bad_optional_access() Line 54   C++
    TerminalApp.dll!std::optional<unsigned short>::value() Line 379 C++
    TerminalApp.dll!Pane::Id() Line 1558    C++
>   TerminalApp.dll!<lambda_1a1e553ee07ffde1f0ed98f661a0b933>::operator()<winrt::Windows::Foundation::IInspectable$_ResumeCoro$1 const &,winrt::Windows::Foundation::IInspectable$_ResumeCoro$1 const &>() Line 699 C++
    TerminalApp.dll!<lambda_1a1e553ee07ffde1f0ed98f661a0b933>::operator()<winrt::Windows::Foundation::IInspectable$_InitCoro$2 const &,winrt::Windows::Foundation::IInspectable$_InitCoro$2 const &>() Line 685 C++
    TerminalApp.dll!<lambda_1a1e553ee07ffde1f0ed98f661a0b933>::operator()<winrt::Windows::Foundation::IInspectable const &,winrt::Windows::Foundation::IInspectable const &>(const winrt::Windows::Foundation::IInspectable &) Line 707 C++
    TerminalApp.dll!winrt::impl::delegate<winrt::Windows::Foundation::EventHandler<winrt::Windows::Foundation::IInspectable>,<lambda_1a1e553ee07ffde1f0ed98f661a0b933>>::Invoke(void * sender, void * args) Line 883    C++
    TerminalApp.dll!winrt::Windows::Foundation::EventHandler<winrt::Windows::Foundation::IInspectable>::operator()(const winrt::Windows::Foundation::IInspectable & sender, const winrt::Windows::Foundation::IInspectable & args) Line 2500    C++
    TerminalApp.dll!winrt::impl::invoke<winrt::Windows::Foundation::EventHandler<winrt::Windows::Foundation::IInspectable>,std::nullptr_t,std::nullptr_t>(const winrt::Windows::Foundation::EventHandler<winrt::Windows::Foundation::IInspectable> & delegate, void * const & <args_0>, void * const & <args_1>) Line 5567  C++
    TerminalApp.dll!winrt::event<winrt::Windows::Foundation::EventHandler<winrt::Windows::Foundation::IInspectable>>::operator()<std::nullptr_t,std::nullptr_t>(void * const & <args_0>, void * const & <args_1>) Line 5702 C++
    TerminalApp.dll!Pane::Close() Line 424  C++
    TerminalApp.dll!<lambda_4e44f426db787ef722ec55bc42fe1f5e>::operator()<winrt::Windows::Foundation::IInspectable const &,winrt::Windows::UI::Xaml::RoutedEventArgs const &>(const winrt::Windows::Foundation::IInspectable & __formal, const winrt::Windows::UI::Xaml::RoutedEventArgs & __formal) Line 754   C++
    TerminalApp.dll!winrt::impl::delegate<winrt::Windows::UI::Xaml::RoutedEventHandler,<lambda_4e44f426db787ef722ec55bc42fe1f5e>>::Invoke(void * sender, void * e) Line 4671    C++
    Windows.UI.Xaml.dll!DirectUI::CRoutedEventSourceBase<DirectUI::IUntypedEventSource,Windows::UI::Xaml::IRoutedEventHandler,IInspectable,Windows::UI::Xaml::IRoutedEventArgs>::Raise(IInspectable * pSource, Windows::UI::Xaml::IRoutedEventArgs * pArgs) Line 1041   C++
    Windows.UI.Xaml.dll!DirectUI::MenuFlyoutItem::Invoke() Line 208 C++
    Windows.UI.Xaml.dll!DirectUI::MenuFlyoutItem::PerformPointerUpAction() Line 186 C++
    Windows.UI.Xaml.dll!DirectUI::MenuFlyoutItem::OnPointerReleased(Windows::UI::Xaml::Input::IPointerRoutedEventArgs * pArgs) Line 146 C++
    Windows.UI.Xaml.dll!DirectUI::ControlGenerated::OnPointerReleasedProtected(Windows::UI::Xaml::Input::IPointerRoutedEventArgs * pE) Line 1518    C++
    Windows.UI.Xaml.dll!DirectUI::Control::FireEvent(KnownEventIndex nDelegate, DirectUI::DependencyObject * pSender, IInspectable * pArgs) Line 259    C++

```

Which has a root cause here:
```c++
        pane->Closed([weakThis, weakPane](auto&& /*s*/, auto && /*e*/) -> winrt::fire_and_forget {
        ...
                        if (*i == pane->Id()) // <---------------- This line right here, throws. The pane's ID might be nullopt!!
                        {
                            tab->_mruPanes.erase(i);
                            break;
                        }

```

Turn out, the pane's ID was `nullopt`. So when we tried to compare the mru pane ID to the pane's ID, it tried to compare against the value of the optional, which threw. 

WEIRDLY, if you add a `closeTab` action, and try doing this from the command palette, it _doesn't_ repro. It also doesn't repro if you just close the tab by middle clicking it. 

This is _not_ the same bug as the "menu flyout crash" - I was very sure to not hover over the nested menu entry when doing this.

### PR DESCRIPTION
**Pull request by PankajBhojwani**
## Summary of the Pull Request
Fix for #9021 

Turns out that what was happening is that the _parent_ pane's `Closed` event was being caught by the tab, and parent panes always have `nullopt` as their id. So now the `Pane::Id()` call always returns an optional, allowing us to check if it has a value before we access it. 

## PR Checklist
* [x] Closes #9021 

## Validation Steps Performed
No more crash

### CODE REVIEW

File: src/cascadia/TerminalApp/TerminalTab.cpp [hunk 1]
```diff
@@ -607,7 +607,7 @@ namespace winrt::TerminalApp::implementation
                 {
                     for (auto i = tab->_mruPanes.begin(); i != tab->_mruPanes.end(); ++i)
                     {
-                        if (*i == pane->Id())
+                        if (pane->Id().has_value() && *i == pane->Id().value())
```
Comment (DHowett) [inline src/cascadia/TerminalApp/TerminalTab.cpp:610]: optional has a cool feature: you can do a comparison directly with the optional.

```suggestion
                        if (*i == pane->Id())
```

except here's the difference: it will be _false_ if `Id` is nullopt.

**Review by DHowett — APPROVED** [review]

**Comment by DHowett** [comment]
You'll need to merge main to get the spellbot happy.

**Comment by DHowett** [comment]
(the crash is still fixed with my recommended change, right? I'd hate to just make your whole PR a no-op lol)

**Review by zadjii-msft — CHANGES_REQUESTED** [review]
Wait shouldn't we be checking if `pane->Id().has_value()` first in both of these cases? I know that's weird and unexpected for the `_activePane` to not have an `Id`, but I'd rather be defensive

**Comment by PankajBhojwani** [comment]
> (the crash is still fixed with my recommended change, right? I'd hate to just make your whole PR a no-op lol)

Yes it is!

> Wait shouldn't we be checking if pane->Id().has_value() first in both of these cases? I know that's weird and unexpected for the _activePane to not have an Id, but I'd rather be defensive

So I felt like it was guaranteed that the active pane and the pane being split are leaves, but yeah better be safe - added those checks! Also once the pane refactor comes in we won't have these kind of issues anymore (no comment on the 99 other issues we get though)

**Review by zadjii-msft — APPROVED** [review]
