### PR TITLE
Don't dismiss the command palette when the new tab menu closes

### LINKED ISSUE #15305: Opening command palette from new tab dropdown dismisses immediately
### Windows Terminal version

main 10c6206

### Windows build number

10.0.22621.1555

### Other Software

_No response_

### Steps to reproduce

1. Open terminal
2. Click new tab dropdown
3. Select Command Palette

### Expected Behavior

The command palette opens and is usable.

### Actual Behavior

The command palette opens and then disappears. Opening the command palette via the keyboard shortcut works fine.

https://user-images.githubusercontent.com/5821575/236624660-9ac34063-5d99-4faf-85c0-880fd6adc2d5.mp4

### PR DESCRIPTION
**Pull request by zadjii-msft**
Transient UIs are hard.

Regressed in #15077.

Closes #15305

### CODE REVIEW

File: src/cascadia/TerminalApp/TerminalPage.cpp [hunk 1]
```diff
@@ -851,7 +851,14 @@ namespace winrt::TerminalApp::implementation
         });
         // Necessary for fly-out sub items to get focus on a tab before collapsing. Related to #15049
         newTabFlyout.Closing([this](auto&&, auto&&) {
-            _FocusCurrentTab(true);
+            if (const auto p = CommandPaletteElement(); p && p.Visibility() == Visibility::Visible)
```
Comment (lhecker) [inline src/cascadia/TerminalApp/TerminalPage.cpp:854]: With this we now have 3 places where we ask for the visibility of the `CommandPaletteElement()`. I think this shows that it isn't just a pattern/occurrence. If you wanted to, we could now consider deduplicating them. One option to do that would be a function like this:

```cpp
bool TerminalPage::_commandPaletteIs(Visibility visibility)
{
    const auto p = CommandPaletteElement()
    return p && p.Visibility() == visibility;
}
```

Then we could write:
```cpp
if (!_commandPaletteIs(Visibility::Visible))
{
    _FocusCurrentTab(true);
}
```

But it's also very basic code so I don't mind not doing this at all.

**Review by lhecker — APPROVED** [review]

File: src/cascadia/TerminalApp/TerminalPage.cpp (hunk 1 above)
Comment (DHowett) [reply src/cascadia/TerminalApp/TerminalPage.cpp:854]: To build off Leonard's "we now have 3 places"...

we now have like a hundred places where we do manual visibility checks (search box, command palette, settings UI, etc.) and manual focus yeeting.

It makes me wonder... are we using the UI framework wrong?

Comment (zadjii-msft) [reply src/cascadia/TerminalApp/TerminalPage.cpp:854]: Indubitably. But the Terminal also does have a bit of a unique UX pattern, where we _almost always_ want the TermControl focused, kinda like a browser. I'm not sure how much other precedence there is for that in WinUI apps

Comment (DHowett) [reply src/cascadia/TerminalApp/TerminalPage.cpp:854]: Meh. Fair. I'm more invested in Leonard's suggestion, so I may block for it.

**Review by DHowett — APPROVED** [review]
