### PR TITLE
[v1.6] Add help text to 'more options' in command palette

### LINKED ISSUE #9247: CommandPalette's "More Options" chevron is ignored by screen readers
# Environment

WT version: after #9234 merges

# Steps to reproduce

1. open command palette
2. Navigate focus to a command with more options '>'

# Expected behavior

The screen reader should probably read that as "more options" or something like that.

# Actual behavior

Chevron ignored.

### PR DESCRIPTION
**Pull request by carlos-zamora**
## Summary of the Pull Request

This adds help text (automation property) to command palette commands that expand to more options.

## PR Checklist
* [ ] Resolves ~#9247~ #7908

## Validation Steps Performed
If I have a nested command called "color tab", NVDA reads it as...
"Color tab. More options. 5 of 79."

### CODE REVIEW

**Comment by DHowett** [comment]
(just so you know - we cannot close a11y bugs until they validate them, so you cannot use the "closes" verbiage.)

File: src/cascadia/TerminalApp/HasNestedCommandsVisibilityConverter.cpp [hunk 1]
```diff
@@ -36,4 +39,23 @@ namespace winrt::TerminalApp::implementation
     {
         throw hresult_not_implemented();
     }
+
+    Foundation::IInspectable HasNestedCommandsHelpTextConverter::Convert(Foundation::IInspectable const& value,
```
Comment (DHowett) [inline src/cascadia/TerminalApp/HasNestedCommandsVisibilityConverter.cpp:43]: are we seriously adding another converter
for the life of me
come on

**Comment by carlos-zamora** [comment]
> (just so you know - we cannot close a11y bugs until they validate them, so you cannot use the "closes" verbiage.)

(totally forgot. Thanks)

File: src/cascadia/TerminalApp/HasNestedCommandsVisibilityConverter.cpp (hunk 1 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalApp/HasNestedCommandsVisibilityConverter.cpp:43]: I hate it so much. But this was the workaround I was able to think of to get access to the `ListViewItem`. If we can somehow get access to that item, a simple `AutomationProperty::SetHelpText()` call would do all of this for us.

**Comment by DHowett** [comment]
Carlos and I reached a decision:

We will use this version for 1.6 (where the is no Data Template).

We will use a new Data Template based version to delete _both_ converters for main/1.7.

**Comment by carlos-zamora** [comment]
@DHowett this is ready for you now 🙂

File: src/cascadia/TerminalApp/HasNestedCommandsVisibilityConverter.cpp [hunk 2]
```diff
@@ -36,4 +39,23 @@ namespace winrt::TerminalApp::implementation
...
         throw hresult_not_implemented();
     }
+
+    Foundation::IInspectable HasNestedCommandsHelpTextConverter::Convert(Foundation::IInspectable const& value,
+                                                                         Windows::UI::Xaml::Interop::TypeName const& /* targetType */,
+                                                                         Foundation::IInspectable const& /* parameter */,
+                                                                         hstring const& /* language */)
+    {
+        const auto paletteItem{ value.try_as<winrt::TerminalApp::ActionPaletteItem>() };
+        const auto& hasNestedCommands = paletteItem && paletteItem.Command().HasNestedCommands();
```
Comment (DHowett) [inline src/cascadia/TerminalApp/HasNestedCommandsVisibilityConverter.cpp:49]:
```suggestion
        const auto hasNestedCommands = paletteItem && paletteItem.Command().HasNestedCommands();
```

**Review by DHowett — APPROVED** [review]
**admin sign off** I'm merging this to 1.6 to fix an a11y bug. We have a plan for 1.7 and main that differs from this. I am going to move the Automation loc key into main myself to maintain loc consistency.
