### PR TITLE
AtlasEngine: Minor bug fixes

### LINKED ISSUE #15960: Characters have black background in Terminal Preview 1.18.1462.0
### Windows Terminal version

1.18.1462.0

### Windows build number

10.0.22622.0

### Other Software

_No response_

### Steps to reproduce

I'm not sure yet what the reproduction steps but the rendering issue seems to present itself immediately upon opening the terminal application.

### Expected Behavior

Rendering of text to be normal

### Actual Behavior

Each character has a black background which is very noticeable if using a light colour scheme, for example:

image

Changing the font or font size does not seem to have any effect.

### PR DESCRIPTION
**Pull request by lhecker**
This commit fixes 4 minor bugs:
* Forgot to set the maximum swap chain latency. Without it, it defaults
  to up to 3 frames of latency. We don't need this, because our renderer
  is simple and fast and is expected to draw frames within <1ms.
* ClearType treats the alpha channel as ignored, whereas custom shaders
  can manipulate the alpha channel freely. This meant that using both
  simultaneously would produce weird effects, like text having black
  background. We now force grayscale AA instead.
* The builtin retro shader should not be effected by the previous point.
* When the cbuffer is entirely unused in a custom shader, it has so far
  resulted in constant redraws. This happened because the D3D reflection
  `GetDesc` call will then return `E_FAIL` in this situation.
  The new code on the other hand will now assume that a failure
  to get the description is equal to the variable being unused.

Closes #15960

## Validation Steps Performed
* A custom passthrough shader works with grayscale and ClearType AA
  while also changing the opacity with Ctrl+Shift+Scroll ✅
* Same for the builtin retro shader, but ClearType works ✅
* The passthrough shader doesn't result in constant redrawing ✅

### CODE REVIEW

File: src/renderer/atlas/BackendD3D.cpp [hunk 1]
```diff
@@ -403,30 +403,36 @@ void BackendD3D::_recreateCustomShader(const RenderingPayload& p)
             /* ppCode      */ blob.addressof(),
             /* ppErrorMsgs */ error.addressof());
 
-        // Unless we can determine otherwise, assume this shader requires evaluation every frame
-        _requiresContinuousRedraw = true;
-
         if (SUCCEEDED(hr))
         {
-            THROW_IF_FAILED(p.device->CreatePixelShader(blob->GetBufferPointer(), blob->GetBufferSize(), nullptr, _customPixelShader.put()));
+            THROW_IF_FAILED(p.device->CreatePixelShader(blob->GetBufferPointer(), blob->GetBufferSize(), nullptr, _customPixelShader.addressof()));
```
Comment (DHowett) [inline src/renderer/atlas/BackendD3D.cpp:408]: for my edification: why change from `put` to `addressof`?

File: src/renderer/atlas/BackendD3D.cpp [hunk 2]
```diff
@@ -447,8 +453,6 @@ void BackendD3D::_recreateCustomShader(const RenderingPayload& p)
     else if (p.s->misc->useRetroTerminalEffect)
     {
         THROW_IF_FAILED(p.device->CreatePixelShader(&custom_shader_ps[0], sizeof(custom_shader_ps), nullptr, _customPixelShader.put()));
-        // We know the built-in retro shader doesn't require continuous redraw.
-        _requiresContinuousRedraw = false;
```
Comment (DHowett) [inline src/renderer/atlas/BackendD3D.cpp:451]: This will result in continuous redraw when you go from custom-shader-with-cbuffer-time to retro-shader-builtin, because this is never reset.

File: src/renderer/atlas/BackendD3D.cpp [hunk 3]
```diff
@@ -403,30 +403,36 @@ void BackendD3D::_recreateCustomShader(const RenderingPayload& p)
...
+            THROW_IF_FAILED(p.device->CreatePixelShader(blob->GetBufferPointer(), blob->GetBufferSize(), nullptr, _customPixelShader.addressof()));
 
             // Try to determine whether the shader uses the Time variable
             wil::com_ptr<ID3D11ShaderReflection> reflector;
-            if (SUCCEEDED_LOG(D3DReflect(blob->GetBufferPointer(), blob->GetBufferSize(), IID_PPV_ARGS(reflector.put()))))
+            if (SUCCEEDED_LOG(D3DReflect(blob->GetBufferPointer(), blob->GetBufferSize(), IID_PPV_ARGS(reflector.addressof()))))
             {
+                // Depending on the version of the d3dcompiler_*.dll, the next two functions either return nullptr
+                // on failure or an instance of CInvalidSRConstantBuffer or CInvalidSRVariable respectively,
+                // which cause GetDesc() to return E_FAIL. In other words, we have to assume that any failure in the
```
Comment (DHowett) [inline src/renderer/atlas/BackendD3D.cpp:416]: That doesn't seem like what this code does?

This code only changes `_requiresContinuous...` when we successfully get all the buffers, variables, and descriptors.

Therefore, we just use whatever value was previously set. Isn't that worse?

**Review by DHowett — CHANGES_REQUESTED** [review]

File: src/renderer/atlas/BackendD3D.cpp (hunk 3 above)
Comment (lhecker) [reply src/renderer/atlas/BackendD3D.cpp:416]: My answer to all 3 comments is: If you expand the section above this diff, you'll see that it resets all relevant members before making any further changes (including `_requiresContinuousRedraw`).

Comment (DHowett) [reply src/renderer/atlas/BackendD3D.cpp:416]: UGH thanks. Sorry for the bad code.

**Review by DHowett — APPROVED** [review]

File: src/renderer/atlas/AtlasEngine.api.cpp [hunk 4]
```diff
@@ -490,20 +490,20 @@ void AtlasEngine::UpdateHyperlinkHoveredId(const uint16_t hoveredId) noexcept
...
 void AtlasEngine::_resolveTransparencySettings() noexcept
 {
+    // An opaque background allows us to use true "independent" flips. See AtlasEngine::_createSwapChain().
+    // We can't enable them if custom shaders are specified, because it's unknown, whether they support opaque inputs.
+    const bool useAlpha = _api.enableTransparentBackground || !_api.s->misc->customPixelShaderPath.empty();
     // If the user asks for ClearType, but also for a transparent background
     // (which our ClearType shader doesn't simultaneously support)
     // then we need to sneakily force the renderer to grayscale AA.
-    const auto antialiasingMode = _api.enableTransparentBackground && _api.antialiasingMode == AntialiasingMode::ClearType ? AntialiasingMode::Grayscale : _api.antialiasingMode;
-    const bool enableTransparentBackground = _api.enableTransparentBackground || !_api.s->misc->customPixelShaderPath.empty() || _api.s->misc->useRetroTerminalEffect;
```
Comment (carlos-zamora) [inline src/renderer/atlas/AtlasEngine.api.cpp:497]: `_api.s->misc->useRetroTerminalEffect` is completely gone now. Is that intentional?

Comment (lhecker) [reply src/renderer/atlas/AtlasEngine.api.cpp:497]: Yep! It's the 3rd bullet point in the commit message. 😅

**Review by carlos-zamora — APPROVED** [review]

**Comment by DHowett** [comment]
image
builds failed? wot

**Comment by DHowett** [comment]
oh it was a rebuild. ugh sorry.
