### PR TITLE
Fix opacity restore for command palette previews

### LINKED ISSUE #12228: Opacity is not correctly restored when cancelling the command palette preview
### Windows Terminal version

1.13.10181.0

### Windows build number

10.0.22540.0

### Steps to reproduce

* Select `Set background opacity...` action in the command palette
* Cycle through some options
* Press Escape

### Actual Behavior

jAL8iT3unYWAyLDw

### Fixed Behavior

au9Qve43gAqYHbSn

### PR DESCRIPTION
**Pull request by lhecker**
This commit correctly restores the previous opacity when the command palette
preview is cancelled. It includes an additional change in order to make the
`AdjustOpacity` setter consistent and symmetric with the `Opacity` getter.

## PR Checklist
* [x] Closes #12228
* [x] I work here
* [x] Tests added/passed

## Validation Steps Performed

* Open Windows Terminal command palette
* Choose "Set background opacity..."
* Cycle through the items without selecting one
* Press Escape
* Previous opacity is restored ✅

### CODE REVIEW

File: src/cascadia/TerminalControl/ControlCore.cpp [hunk 1]
```diff
@@ -1718,9 +1718,8 @@ namespace winrt::Microsoft::Terminal::Control::implementation
         return _settings->HasUnfocusedAppearance();
     }
 
-    void ControlCore::AdjustOpacity(const int32_t& opacity, const bool& relative)
+    void ControlCore::AdjustOpacity(const double opacityAdjust, const bool relative)
```
Comment (lhecker) [inline src/cascadia/TerminalControl/ControlCore.cpp:1721]: I wrote the reason for this in the commit description:
> It includes an additional change in order to make the AdjustOpacity setter consistent and symmetric with the Opacity getter.

Let me know what you all think. 🙂

File: src/cascadia/TerminalApp/ActionPreviewHandlers.cpp [hunk 2]
```diff
@@ -70,12 +70,14 @@ namespace winrt::TerminalApp::implementation
         // Apply the reverts in reverse order - If we had multiple previews
         // stacked on top of each other, then this will ensure the first one in
         // is the last one out.
-        for (auto i{ _restorePreviewFuncs.rbegin() }; i < _restorePreviewFuncs.rend(); i++)
+        const auto cleanup = wil::scope_exit([this]() {
+            _restorePreviewFuncs.clear();
+        });
```
Comment (lhecker) [inline src/cascadia/TerminalApp/ActionPreviewHandlers.cpp:75]: Just in case a `f()` call below fails. This ensures the correct behavior for
```cpp
const auto backup = _restorePreviewFuncs.empty();
```

**Review by zadjii-msft — APPROVED** [review]
Ah okay. So only the first preview action now emplaces the revert. That makes enough sense I suppose.

**Review by DHowett — APPROVED** [review]

**Comment by DHowett** [comment]
@msftbot merge this in 10 minutes
