### PR TITLE
Only honor Ctrl+Z during ReadFile if the console is in PROCESSED mode

### LINKED ISSUE #4958: Ctrl+Z sends EOF even if console is in 'raw' mode
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.153]
.NET Core 3.1.200
```

# Steps to reproduce

C# program:

```csharp
using System;
using System.Diagnostics;
using System.Text;
using static Vanara.PInvoke.Kernel32;

namespace Test
{
    static class Program
    {
        unsafe static void Main()
        {
            var stdin = GetStdHandle(StdHandleType.STD_INPUT_HANDLE);
            var stdout = GetStdHandle(StdHandleType.STD_OUTPUT_HANDLE);

            Debug.Assert(GetConsoleMode(stdin, out CONSOLE_INPUT_MODE inMode));

            inMode |= CONSOLE_INPUT_MODE.ENABLE_VIRTUAL_TERMINAL_INPUT;
            inMode &= ~(CONSOLE_INPUT_MODE.ENABLE_PROCESSED_INPUT |
                        CONSOLE_INPUT_MODE.ENABLE_LINE_INPUT |
                        CONSOLE_INPUT_MODE.ENABLE_ECHO_INPUT);

            Debug.Assert(SetConsoleMode(stdin, inMode));

            Debug.Assert(GetConsoleMode(stdout, out CONSOLE_OUTPUT_MODE outMode));

            outMode |= CONSOLE_OUTPUT_MODE.ENABLE_VIRTUAL_TERMINAL_PROCESSING |
                       CONSOLE_OUTPUT_MODE.DISABLE_NEWLINE_AUTO_RETURN;
            outMode &= ~(CONSOLE_OUTPUT_MODE.ENABLE_PROCESSED_OUTPUT |
                         CONSOLE_OUTPUT_MODE.ENABLE_WRAP_AT_EOL_OUTPUT);

            Debug.Assert(SetConsoleMode(stdout, outMode));

            byte b = 0;

            Debug.Assert(ReadFile(stdin, (IntPtr)(&b), 1, out var r, IntPtr.Zero));

            Console.Write("Read {0} bytes; value = 0x{1:x2}", r, b);
        }
    }
}
```

(Uses the Vanara.PInvoke.Kernel32 NuGet package for convenience.)

Run the program in any console host / shell (CMD, PowerShell, Windows Terminal, etc).

# Expected behavior

Output: `Read 1 bytes; value = 0x1a` (behavior on Linux)

# Actual behavior

Output: `Read 0 bytes; value = 0x00`

---

I understand that Ctrl+Z is (roughly) Windows's equivalent to Ctrl+D to send EOF. However, I would expect it not to send EOF when the console has been put in 'raw' mode as described [here](https://docs.microsoft.com/en-us/windows/console/high-level-console-modes). This is the behavior on Unix systems for Ctrl+D when you unset `ICANON` (see [this](https://linux.die.net/man/3/tcsetattr) manual page).

Perhaps there's an additional step that I'm missing?

### PR DESCRIPTION
**Pull request by DHowett**
This restores the behavior of ReadFile to that of Windows 7.

Closes #4958

### CODE REVIEW

**Comment by DHowett** [comment]
Perhaps of interest to @Tig and @eryksun

File: src/server/ApiDispatchers.cpp [hunk 1]
```diff
@@ -270,6 +270,16 @@ constexpr T saturate(auto val)
     }
     CATCH_RETURN();
 
+    if (a->ProcessControlZ)
+    {
+        // ProcessControlZ is only set for CONSOLE_IO_RAW_READ. To restore
+        // the behavior from Windows 7 (see filehops.c:123) we need to honor
+        // ^Z only if PROCESSED_INPUT is enabled.
+        ULONG InputMode{ 0 };
+        m->_pApiRoutines->GetConsoleInputModeImpl(*pInputBuffer, InputMode);
```
Comment (DHowett) [inline src/server/ApiDispatchers.cpp:279]: This probably has a `[[nodiscard]]` hanging out on it

Comment (DHowett) [reply src/server/ApiDispatchers.cpp:279]: sike, it returns void

File: src/server/ApiDispatchers.cpp [hunk 2]
```diff
@@ -270,6 +270,16 @@
     }
     CATCH_RETURN();
 
+    if (a->ProcessControlZ)
+    {
+        // ProcessControlZ is only set for CONSOLE_IO_RAW_READ. To restore
+        // the behavior from Windows 7 (see filehops.c:123) we need to honor
```
[the remark this answers is not in the document]
Comment (DHowett) [reply src/server/ApiDispatchers.cpp:276]: really bud
