### PR TITLE
Azure connector only shows up if available

### LINKED ISSUE #2170: Azure Cloud Shell Connector Not Working
# Environment

```none
Windows build number: 10.0.18941.1001
Windows Terminal version (if applicable): Source
```

# Steps to reproduce

- Fresh Install of Terminal from Source
- Try to open Azure Cloud Shell Connector

# Expected behavior

- Device Flow kicks off and you can connect to Azure
 
# Actual behavior

- Get following message
> Could not connect to Azure. You may not have internet or the server might be down.

Opening up Fiddler, the request is failing, here is the request

```
POST https://login.microsoftonline.com/common/oauth2/devicecode HTTP/1.1
Connection: Keep-Alive
Content-Type: application/x-www-form-urlencoded; charset=utf-8
User-Agent: cpprestsdk/2.10.13
Content-Length: 57
Host: login.microsoftonline.com

client_id=0&resource=https://management.core.windows.net/
```

and response
```
HTTP/1.1 400 Bad Request
Cache-Control: no-cache, no-store
Pragma: no-cache
Content-Type: application/json; charset=utf-8
Expires: -1
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
x-ms-request-id: 036d9b04-0b15-4948-88e3-1298fe521f00
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
Set-Cookie: fpc=AgBw0kjQZyJGh-9yya_oOWo; expires=Fri, 30-Aug-2019 13:29:10 GMT; path=/; secure; HttpOnly
Set-Cookie: esctx=AQABAAAAAAAP0wLlqdLVToOpA4kwzSnx6Nn0i9n3KONl8oqKUDrwVI49N60kNuXitGhI2l65usEtATWKSOh8_SSS6SxU8qs6Mc2TKjto45yvCwsR1FnOxysOiKELlbMM8oFUyR0pRNEedN5J_pDsAlMLiz5CCixbFrYu1kevQ7G277G0tWGQ1Bmr6yQvertj7I1EFoMdyWkgAA; domain=.login.microsoftonline.com; path=/; secure; HttpOnly
Set-Cookie: x-ms-gateway-slice=prod; path=/; secure; HttpOnly
Set-Cookie: stsservicecookie=ests; path=/; secure; HttpOnly
Date: Wed, 31 Jul 2019 13:29:10 GMT
Content-Length: 468

{"error":"invalid_request","error_description":"AADSTS50059: No tenant-identifying information found in either the request or implied by any provided credentials.\r\nTrace ID: 036d9b04-0b15-4948-88e3-1298fe521f00\r\nCorrelation ID: 62f6beea-e136-430d-8262-d762ad319f00\r\nTimestamp: 2019-07-31 13:29:10Z","error_codes":[50059],"timestamp":"2019-07-31 13:29:10Z","trace_id":"036d9b04-0b15-4948-88e3-1298fe521f00","correlation_id":"62f6beea-e136-430d-8262-d762ad319f00"}
```

Looks like no client_ id is being set in code. Do you need to set this somewhere?

### PR DESCRIPTION
**Pull request by PankajBhojwani**
## Summary of the Pull Request
The Azure connection profile will not show up as an option anymore if the user is on an ARM64 build or if they're on a local build (and so they do not have the required clientID). 

 
## PR Checklist
* [X] Closes #2170 
* [ ] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Requires documentation to be updated
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

### CODE REVIEW

File: src/cascadia/TerminalConnection/AzureConnection-ARM64.cpp [hunk 1]
```diff
@@ -0,0 +1,47 @@
+#include "pch.h"
```
Comment (zadjii-msft) [inline src/cascadia/TerminalConnection/AzureConnection-ARM64.cpp]: nit: pretty sure this needs a copyright header

File: src/cascadia/TerminalConnection/AzureConnection-ARM64.h [hunk 2]
```diff
@@ -0,0 +1,27 @@
+#pragma once
```
Comment (zadjii-msft) [inline src/cascadia/TerminalConnection/AzureConnection-ARM64.h]: nit: copyright header here too

File: src/cascadia/TerminalConnection/AzureConnection-ARM64.h [hunk 3]
```diff
@@ -0,0 +1,27 @@
...
+#include "AzureConnection.g.h"
+
+namespace winrt::Microsoft::Terminal::TerminalConnection::implementation
+{
+    struct AzureConnection : AzureConnectionT<AzureConnection>
+    {
+        AzureConnection() = default;
+
+        AzureConnection(uint32_t rows, uint32_t columns);
+        static bool IsAzureConnectionAvailable();
```
Comment (zadjii-msft) [inline src/cascadia/TerminalConnection/AzureConnection-ARM64.h]: I'm wondering if it makes sense to get rid of the cpp for the arm version of this and have all the implementations just in the header, since they're all just E_NOTIMPL

File: src/cascadia/TerminalConnection/AzureConnection.cpp [hunk 4]
```diff
@@ -25,6 +25,12 @@ using namespace winrt::Windows::Security::Credentials;
 
 namespace winrt::Microsoft::Terminal::TerminalConnection::implementation
 {
+    // This file only builds for non-ARM64 so we don't need to check that here
+    bool AzureConnection::IsAzureConnectionAvailable()
```
Comment (zadjii-msft) [inline src/cascadia/TerminalConnection/AzureConnection.cpp]: nit: Might want to add a note that this check is because the clientId is added by the release pipeline and might not be available in local builds

File: src/cascadia/TerminalConnection/AzureConnection.idl [hunk 5]
```diff
@@ -7,7 +7,8 @@ namespace Microsoft.Terminal.TerminalConnection
 {
     [default_interface] runtimeclass AzureConnection : ITerminalConnection
     {
-        AzureConnection(UInt32 rows, UInt32 columns);
+        static Boolean IsAzureConnectionAvailable();
+		AzureConnection(UInt32 rows, UInt32 columns);
```
Comment (zadjii-msft) [inline src/cascadia/TerminalConnection/AzureConnection.idl]: nit: these guys aren't aligned

File: src/cascadia/TerminalConnection/AzureConnection-ARM64.h (hunk 3 above)
Comment (PankajBhojwani) [reply src/cascadia/TerminalConnection/AzureConnection-ARM64.h]: They're all not implemented _except_ IsAzureConnectionAvailable, which always returns false in arm64

Comment (zadjii-msft) [reply src/cascadia/TerminalConnection/AzureConnection-ARM64.h]: er, yea that's more technically correct. Point still stands though :)

Comment (PankajBhojwani) [reply src/cascadia/TerminalConnection/AzureConnection-ARM64.h]: Gonna resolve this since we tried and ended up in a cppwinrt mess

File: src/cascadia/TerminalConnection/AzureConnection-ARM64.cpp (hunk 1 above)
Comment (PankajBhojwani) [reply src/cascadia/TerminalConnection/AzureConnection-ARM64.cpp]: Done

File: src/cascadia/TerminalConnection/AzureConnection-ARM64.h (hunk 2 above)
Comment (PankajBhojwani) [reply src/cascadia/TerminalConnection/AzureConnection-ARM64.h]: Done

File: src/cascadia/TerminalConnection/AzureConnection.cpp (hunk 4 above)
Comment (PankajBhojwani) [reply src/cascadia/TerminalConnection/AzureConnection.cpp]: Done

File: src/cascadia/TerminalConnection/AzureConnection.idl (hunk 5 above)
Comment (PankajBhojwani) [reply src/cascadia/TerminalConnection/AzureConnection.idl]: Idk why this was happening, it looked fine when I opened it up in visual studio... I fixed it so it looks weird on visual studio for me but should be fine on github

File: src/cascadia/TerminalConnection/AzureConnection.idl [hunk 6]
```diff
@@ -7,7 +7,9 @@ namespace Microsoft.Terminal.TerminalConnection
 {
     [default_interface] runtimeclass AzureConnection : ITerminalConnection
     {
-        AzureConnection(UInt32 rows, UInt32 columns);
+        static Boolean IsAzureConnectionAvailable();
+
+	AzureConnection(UInt32 rows, UInt32 columns);
```
Comment (zadjii-msft) [inline src/cascadia/TerminalConnection/AzureConnection.idl]: oh no this got worse somehow

Comment (PankajBhojwani) [reply src/cascadia/TerminalConnection/AzureConnection.idl]: github

this is what it looks like on my computer... what is happening

File: src/cascadia/TerminalConnection/AzureConnection.cpp [hunk 7]
```diff
@@ -25,6 +25,15 @@ using namespace winrt::Windows::Security::Credentials;
 
 namespace winrt::Microsoft::Terminal::TerminalConnection::implementation
 {
+    // This file only builds for non-ARM64 so we don't need to check that here
+    // This function exists because the clientID only gets added by the release pipelines
+    // and is not available on local builds, so we want to be able to make sure we don't
+    // try to make an Azure connection if its a local build
+    bool AzureConnection::IsAzureConnectionAvailable()
+    {
+        return (AzureClientID != L"0");
```
Comment (zadjii-msft) [inline src/cascadia/TerminalConnection/AzureConnection.cpp]: Actually, out of curiosity, how is `AzureClientID` set? Is there like a global `extern` variable we're setting somewhere in a file that's only included in the release pipeline build? An environment variable?  Some other dark magic we're not allowed to discuss externally?

Comment (PankajBhojwani) [reply src/cascadia/TerminalConnection/AzureConnection.cpp]: @DHowett could answer this better

File: src/cascadia/TerminalConnection/AzureConnection.idl (hunk 6 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalConnection/AzureConnection.idl]: image

Comment (DHowett-MSFT) [reply src/cascadia/TerminalConnection/AzureConnection.idl]: Tabs versus spaces? Visual Stu defaults to tabs for most file types.

Comment (DHowett-MSFT) [inline src/cascadia/TerminalConnection/AzureConnection.idl]:
```suggestion
        AzureConnection(UInt32 rows, UInt32 columns);
```

File: src/cascadia/TerminalConnection/AzureConnection.cpp (hunk 7 above)
Comment (DHowett-MSFT) [reply src/cascadia/TerminalConnection/AzureConnection.cpp]: Stomped in by the build :)
