### PR TITLE
Fix tab contrast colors when in high contrast

### LINKED ISSUE #13067: [High Contrast] Colored tabs lose color when unfocused
### Windows Terminal version

1.14.1262.0

### Windows build number

10.0.22621.0

### Other Software

_No response_

### Steps to reproduce

1. Enter high contrast mode
2. color a tab
3. switch focus to another tab

### Expected Behavior

colored tab should still retain the color

### Actual Behavior

colored tab reverted to high contrast color (until focused again).

### LINKED ISSUE #17913: [Windows Terminal]: Name of the current tab is not visible in high contrast desert theme.
### Windows Terminal version

1.22.2362.0

### Windows build number

27695.1000

### Other Software

**Test Environment:**
OS: Windows 11 Version Dev (OS Build 27695.1000)
App: Windows Terminal Preview

### Steps to reproduce

**Pre-requisite:**
Settings>Accessibility>Contrast themes>Desert theme>Reopen the application.

**Repro steps:**
1. Open the 'windows terminal' application.
2. Follow the above-mentioned pre-requisite step.
3. Now open any application like 'Windows Terminal'.
4. Observe the issue.

**User experience:**
Users relying on high contrast themes, such as those with visual impairments, may struggle to identify the current active tab, hindering their ability to navigate efficiently in the terminal. Proper contrast is crucial for accessibility and usability in high contrast modes.

**MAS Reference Link:**
[MAS 4.3.1 – No Disruption of Accessibility Features.docx (sharepoint.com)](https://microsoft.sharepoint.com/:w:/s/accessibility/EegntkLK4KBBvzE1qsKpIoABG2UIxUY2y3uo1LomKoz_bg?e=wLbDEr)

Attachment:
[MAS4.3.1 - Name of the current tab is not visible in high contrast desert theme.zip](https://github.com/user-attachments/files/16973501/MAS4.3.1.-.Name.of.the.current.tab.is.not.visible.in.high.contrast.desert.theme.zip)

### Expected Behavior

The name of the current active tab should be clearly visible in high contrast themes, such as the Desert theme. Proper color contrast should be maintained to ensure the active tab’s name stands out from the background, ensuring easy identification.

### Actual Behavior

The name of the current active tab is not visible or is poorly visible when using the High Contrast Desert theme. The tab name blends with the background, making it hard to distinguish which tab is active.

### PR DESCRIPTION
**Pull request by carlos-zamora**
## Summary of the Pull Request
Originally, the XAML resources were being applied on the TabView's ResourceDictionary directly. However, high contrast mode has a few weird scenarios as it basically reduces the color palette to just a few colors to ensure high contrast. This PR now stores the resources onto the ThemeDictionaries so that we have more control over the colors used.

## References and Relevant Issues
Closes #17913
Closes #13067 (fixed by 5be0056)

## Validation Steps Performed
Compared the following scenarios to WinUI 2 gallery's TabView when in High Contrast mode:
✅ (Un)selected tab
✅ hover over x of (un)selected tab
✅ hover over unselected tab

### CODE REVIEW

**Comment by carlos-zamora** [comment]
## Demo

### Selected vs unselected
image

### Unselected (hovered)
image
image

### Unselected (Hover over X)
image
image

### Selected (Hover over X)
image
image

**Comment by carlos-zamora** [comment]
## Discussion
The OS allows users to set a contrast theme:
{C32FE595-6B43-4FE6-9F47-F2D2C004E24C}

This is achieved by using the following XAML resource keys:
{D84E0F24-DC90-4C1C-9892-57B9A8A5B6A6}

However, Windows Terminal offers a lot of built-in customizability, namely through color schemes and theming. In fact, the default theme is:
```js
{
    "name": "dark",
    "window": {
        "applicationTheme": "dark"
    },
    "tab": {
        "background": "terminalBackground",
        "unfocusedBackground": "#00000000"
    },
    "tabRow": {
        "unfocusedBackground": "#333333FF"
    }
},
```

So, the question is, how do we balance the two? What I've done here is ignore the OS theme, basically. The main one I'm looking at in the default theme is `tab.background="terminalBackground"` since that's a dynamic value. There may be some scenarios where high contrast may not be guaranteed. Though, the default color scheme with default theme works, and that's really the important one.

CC @zadjii-msft as the father of WT Theming

**Comment by carlos-zamora** [comment]
>> Discusion

Discussed as a team. The current solution works just fine. We'll keep an eye on the tab row and other reported High Contrast issues for the future.

**Review by lhecker — APPROVED** [review]

File: src/cascadia/TerminalApp/TabBase.cpp [hunk 1]
```diff
@@ -542,6 +583,15 @@ namespace winrt::TerminalApp::implementation
             {
                 tabItemResources.Remove(key);
             }
+
+            for (const auto& [k, v] : tabItemThemeResources)
+            {
+                const auto& currentDictionary = v.as<ResourceDictionary>();
+                if (currentDictionary.HasKey(key))
```
Comment (lhecker) [inline src/cascadia/TerminalApp/TabBase.cpp:590]: The `IDictionary` docs say that `Remove()` does not throw if the key does not exist. I'm assuming the same is true for WinRT's `IMap`. Is this extra check really needed?

**Review by DHowett — APPROVED** [review]
