### PR TITLE
Plumb Focus events through VT Input

### LINKED ISSUE #11682: Terminal + Neovim: FocusLost/Gained events don't fire.
### Windows Terminal version (or Windows build number)

1.12.2931.0

### Other Software

Neovim 0.5+

### Steps to reproduce

Steps to reproduce:
1) Run Neovim 0.5 or higher using the following `min.vim` file, with the command `nvim -u min.vim --clean`
```vimL
" min.vim
autocmd FocusLost * echo "Focus Lost"
autocmd FocusGained * echo "Focus Gained"
```
2) Click away from terminal. Click to.
3) Vim command line output at the bottom of the screen should update with the echoed text.

### Expected Behavior

See title and steps to reproduce. This works in all Linux/MacOS terminals I've used, including Alacritty, Kitty, and iTerm2, as well as in tmux sessions if focus-events are enabled.

The Vim/Neovim release is not particularly important unless you would also like to test in tmux; in that case, choose a release any time after April 2021 and put `set -g focus-events on` in your `.tmux.conf`

### Actual Behavior

Nothing happens.

### PR DESCRIPTION
**Pull request by zadjii-msft**
Further builds on #12799. #12799 assumes that the connection is prepared to receive FocusIn/FocusOut events as input. For ConPTY we can be relatively sure of that, but that's not _technically_ correct. In the hypothetical world where the connection is not a ConPTY connection, then the other side might not be expecting those sequences. 

This remedies the issue by
* ConPTY will always request focus event mode (from the terminal) when it starts up
* when a client tries to disable focus events in conpty, conpty is gonna note that internally, but never transmit that to the hosting terminal, to leave the terminal in focus event mode.
* `TerminalDispatch` and `ControlCore` are hooked up now to only send focus events when the Terminal is in focus event mode (which will be always for conpty)
* At this point, it was like, 4LOC in `terminalInput.cpp` to add support for focus events to conhost as well.

## checklist
* [x] closes #11682
  * This combined with #12515 will finally close out #2988 as well, but we can do that manually.
* [x] I work here
* [ ] There aren't tests for this. There probably should be.

### CODE REVIEW

File: src/host/outputStream.cpp [hunk 1]
```diff
@@ -202,7 +202,14 @@ bool ConhostInternalGetSet::SetInputMode(const TerminalInput::Mode mode, const b
     // us that SSH 7.7 _also_ requests mouse input and that can have a user interface
     // impact on the actual connected terminal. We can't remove this check,
     // because SSH <=7.7 is out in the wild on all versions of Windows <=2004.
-    return !(IsConsolePty() && IsVtInputEnabled());
+    const bool inConpty = IsConsolePty();
+    const bool shouldPassthrough = inConpty && IsVtInputEnabled();
+
+    // GH#12799 - If the app requested that we disable focus events, DON'T pass
+    // that through. ConPTY would _always_ like to know about focus events.
+    const bool disabledFocusEvents = inConpty && (!enabled && mode == TerminalInput::Mode::FocusEvent);
```
Comment (lhecker) [inline src/host/outputStream.cpp:210]: FYI purely from a boolean logic, this extra `inConpty` check is unneccessary.
```
!(IsConsolePty && IsVtInputEnabled) || (IsConsolePty && (!enabled && mode == FocusEvent))
```
is equivalent to
```
!IsConsolePty || !IsVtInputEnabled || (!enabled && mode == FocusEvent))
```
Such a expression IMO is also a bit more readable as it's like a "filter" left to right. Due to the early return via `!IsConsolePty` once you're at the `!enabled` part `IsConsolePty` can only be `true` anymore.

**Review by lhecker — APPROVED** [review]
I can't review this from a architectural POV unfortunately.

File: src/terminal/input/terminalInput.cpp [hunk 2]
```diff
@@ -674,6 +682,16 @@ bool TerminalInput::HandleKey(const IInputEvent* const pInEvent)
     return false;
 }
 
+bool TerminalInput::HandleFocus(const bool focused)
+{
+    const bool enabled{ GetInputMode(Mode::FocusEvent) };
+    if (enabled)
```
Comment (j4james) [inline src/terminal/input/terminalInput.cpp:688]: Nit: Everywhere else in this class we just test these flags with something like

    if (_inputMode.test(Mode::FocusEvent))

Comment (j4james) [inline src/terminal/input/terminalInput.cpp:688]: Nit: Everywhere else in this class we just test these flags with something like

    if (_inputMode.test(Mode::FocusEvent))

File: src/host/outputStream.cpp (hunk 1 above)
Comment (zadjii-msft) [reply src/host/outputStream.cpp:210]: > I'm not sure why these changes haven't been recognised as a merge conflict

I bet it's because of the way I've stacked like 3 PRs up here. I bet only the lowest layer got caught for the conflict. Resolved most of these now.

File: src/terminal/input/terminalInput.cpp (hunk 2 above)
Comment (zadjii-msft) [reply src/terminal/input/terminalInput.cpp:688]: Huh. We only use `GetInputMode` for a test class. Bet we could yank that now....

File: src/host/outputStream.cpp (hunk 1 above)
Comment (zadjii-msft) [reply src/host/outputStream.cpp:210]: also added gratuitous comments, because boolean logic is hard some times

File: src/terminal/input/terminalInput.cpp (hunk 2 above)
Comment (j4james) [reply src/terminal/input/terminalInput.cpp]: No, it's going to be needed for feature reporting at some point.

File: src/terminal/adapter/InteractDispatch.cpp [hunk 3]
```diff
@@ -188,7 +188,7 @@ bool InteractDispatch::IsVtInputEnabled() const
 //   which will end up here. This will update the console's internal tracker if
 //   it's focused or not, as to match the end-terminal's state.
 // - Used to call ConsoleControl(ConsoleSetForeground,...).
-// - Full support for this sequence is tracked in GH#11682.
+// - Full support for this sequence was added in GH#11682.
```
Comment (DHowett) [inline src/terminal/adapter/InteractDispatch.cpp:191]: We can just kill this line. Otherwise we're gonna litter our code with historical artifacts pointing to GitHub issues that we could relegate to `git blame` :)

File: src/terminal/adapter/InteractDispatch.cpp [hunk 4]
```diff
@@ -248,8 +248,5 @@ bool InteractDispatch::FocusChanged(const bool focused) const
     }
     // Does nothing outside of ConPTY. If there's a real HWND, then the HWND is solely in charge.
 
-    // Theoretically, this could be propagated as a focus event as well, to the
-    // input buffer. That should be considered when implementing GH#11682.
-
     return true;
```
Comment (DHowett) [inline src/terminal/adapter/InteractDispatch.cpp:251]: we should make sure that a VT Input client on the far receiving end doesn't get _two events each focus change_. I was wondering if it would because:

1. we might pass one through (original one)
2. we add a `FOCUS_EVENT` to the input buffer, which TerminalInput later converts into another focus VT sequence

Comment (zadjii-msft) [reply src/terminal/adapter/InteractDispatch.cpp:251]: WHOOPS IT DOES THE OPPOSITE.

Terminal doesn't send _any_ focus events to the client. It sets the terminal into focus mode, it sends the focus in, `InteractDispatch` then enables CONSOLE_FOREGROUND, and then returns _and never writes the focus event to the buffer._

Comment (DHowett) [reply src/terminal/adapter/InteractDispatch.cpp:251]: _oops_!

Comment (zadjii-msft) [reply src/terminal/adapter/InteractDispatch.cpp:251]: fixed it

gh-11682-in-terminal

**Comment by DHowett** [comment]
I did unmark automerge if you wanted to think about HandleFocusEvent; it's optional of course
