### PR TITLE
Fixed self reference capture in Tab and TerminalPage

### LINKED ISSUE #3776: Crash when opening and closing a tab
Environment
```
Windows 10 Home 18363.476
Windows Terminal (Preview) Store installation - v0.7.3291.0
```

When opening and closing a 3rd tab, when two tabs are already openend and a single tab is executing a command, the Terminal crashes completely.

I had a Windows PowerShell tab open as my first tab and a Ubuntu shell open as my second tab, opening and closing a new Windows PowerShell tab as the third one.

### PR DESCRIPTION
**Pull request by mkitzan**
## Summary of the Pull Request
Every lambda capture in `Tab` and `TerminalPage` has been changed from capturing raw `this` to `std::weak_ptr<Tab>` or `winrt::weak_ref<TerminalPage>`. Lambda bodies have been changed to check the weak reference before use. 

Capturing raw `this` in `Tab`'s [title change event handler](https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalApp/Tab.cpp#L299) was the root cause of #3776, and is fixed in this PR among other instance of raw `this` capture.

The lambda fixes to `TerminalPage` are unrelated to the core issue addressed in the PR checklist. Because I was already editing `TerminalPage`, figured I'd do a [weak_ref pass](https://github.com/microsoft/terminal/issues/3776#issuecomment-560575575).

 
## PR Checklist
* [x] Closes #3776, potentially #2248, likely closes others
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Requires documentation to be updated
* [x] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #3776

## Detailed Description of the Pull Request / Additional comments
`Tab` now inherits from `enable_shared_from_this`, which enable accessing `Tab` objects as `std::weak_ptr<Tab>` objects. All instances of lambdas capturing `this` now capture `std::weak_ptr<Tab>` instead. `TerminalPage` is a WinRT type which supports `winrt::weak_ref<TerminalPage>`. All previous instance of `TerminalPage` lambdas capturing `this` has been replaced to capture `winrt::weak_ref<TerminalPage>`. These weak pointers/references can only be created after object construction necessitating for `Tab` a new function called after construction to bind lambdas.

Any anomalous crash related to the following functionality during closing a tab or WT may be fixed by this PR:
- Tab icon updating
- Tab text updating
- Tab dragging
- Clicking new tab button
- Changing active pane
- Closing an active tab
- Clicking on a tab
- Creating the new tab flyout menu

Sorry about all the commits. Will fix my fork after this PR! 😅 

## Validation Steps Performed
Attempted to repro the steps indicated in issue #3776 with the new changes and failed. When before the changes, the issue could consistently be reproed.

### CODE REVIEW

**Comment by mkitzan** [comment]
Azure pipeline got stuck in unit testing again. I imagine I don't have the god power /azp run

File: src/cascadia/TerminalApp/Tab.h [hunk 1]
```diff
@@ -5,11 +5,15 @@
 #include <winrt/Microsoft.UI.Xaml.Controls.h>
 #include "Pane.h"
 
-class Tab
+// TODO: make Tab a WinRT type
```
Comment (zadjii-msft) [inline src/cascadia/TerminalApp/Tab.h]: We typically like to avoid bare todos in the code like this, without an issue linked to them. Either we should file a follow-up task (and link it here with `// TODO:microsoft/terminal#<issue_number>: Make Tab a WinRT Type`, or just pull the todo entirely. Frankly I don't think this one needs to be in the code, but go with what you feel 😄

File: src/cascadia/TerminalApp/TerminalPage.cpp [hunk 2]
```diff
@@ -60,23 +60,36 @@ namespace winrt::TerminalApp::implementation
...
+                auto& from{ page->_rearrangeFrom };
+                auto& to{ page->_rearrangeTo };
 
-            _rearranging = false;
-            _rearrangeFrom = std::nullopt;
-            _rearrangeTo = std::nullopt;
+                if (from.has_value() && to.has_value() && to != from)
+                {
+                    auto& tabs{ page->_tabs };
+                    auto tab = tabs.at(to.value());
```
Comment (zadjii-msft) [inline src/cascadia/TerminalApp/TerminalPage.cpp]: This `tab` was `_rearrangeFrom` originally - is this intentional?

File: src/cascadia/TerminalApp/TerminalPage.cpp [hunk 3]
```diff
@@ -762,19 +793,25 @@ namespace winrt::TerminalApp::implementation
         // Add an event handler when the terminal wants to paste data from the Clipboard.
         term.PasteFromClipboard({ this, &TerminalPage::_PasteFromClipboardHandler });
 
+        // Bind Tab events to the TermControl and the Tab's Pane
+        hostingTab->BindEventHandlers(term);
```
[the remark this answers is not in the document]
Comment (mkitzan) [reply src/cascadia/TerminalApp/TerminalPage.cpp]: We are constructing `Tab`s through `make_shared<Tab>`, so it didn't make sense at first why it was throwing [`bad_weak_ptr`](https://en.cppreference.com/w/cpp/memory/bad_weak_ptr). But after some digging, I got a theory 🕵. Since all [`shared_ptr` constructors](https://en.cppreference.com/w/cpp/memory/shared_ptr/shared_ptr) don't construct the managed object directly. `make_shared` at some point must call `::new T`, and at this moment `T` won't have the context that it will become a managed object. So at the time of `Tab`'s construction we can't call and weaken `shared_from_this`. Look the try/catch section of the example [from cppreference](https://en.cppreference.com/w/cpp/memory/enable_shared_from_this). I think it demonstrates our issue here.

File: src/cascadia/TerminalApp/TerminalPage.cpp (hunk 2 above)
Comment (mkitzan) [reply src/cascadia/TerminalApp/TerminalPage.cpp]: Nope, good catch! Late nite coding artifact, sorry about that.

File: src/cascadia/TerminalApp/Tab.h (hunk 1 above)
Comment (mkitzan) [reply src/cascadia/TerminalApp/Tab.h]: Sorry about that, I'll remove it. I wasn't aware of the todo guideline. Let's stick with repo's format for todos.

Comment (mkitzan) [reply src/cascadia/TerminalApp/Tab.h]: Sorry about that, I'll remove this. Best to stick with the standard todo format.

File: src/cascadia/TerminalApp/TerminalPage.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (mkitzan) [reply src/cascadia/TerminalApp/TerminalPage.cpp]: We are constructing `Tab`s through `make_shared<Tab>`, so it didn't make sense at first why it was throwing [`bad_weak_ptr`](https://en.cppreference.com/w/cpp/memory/bad_weak_ptr). But after some digging, I got a theory 🕵. Since all `shared_ptr` constructors don't construct the managed object directly. `make_shared` at some point must call `::new T`, and at this moment `T` won't have the context that it will become a managed object. So at the time of `Tab`'s construction we can't call and weaken `shared_from_this`. Look the try/catch section of the example [from cppreference](https://en.cppreference.com/w/cpp/memory/enable_shared_from_this). I think it demonstrates our issue here.

File: src/cascadia/TerminalApp/TerminalPage.cpp (hunk 2 above)
Comment (mkitzan) [reply src/cascadia/TerminalApp/TerminalPage.cpp]: Nope, good catch! Late nite coding artifact, sorry about that.

File: src/cascadia/TerminalApp/TerminalPage.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (zadjii-msft) [reply src/cascadia/TerminalApp/TerminalPage.cpp]: Oh. Well I learned something new, thanks!

File: src/cascadia/TerminalApp/TerminalPage.cpp (hunk 2 above)
Comment (zadjii-msft) [reply src/cascadia/TerminalApp/TerminalPage.cpp]: We've all been there 😝

File: src/cascadia/TerminalApp/Tab.h (hunk 1 above)
Comment (zadjii-msft) [reply src/cascadia/TerminalApp/Tab.h]: Thanks!

**Comment by mkitzan** [comment]
Happy to help! Also, feel free to assign any goon work to me. I'm sure there's a lot of issues in the backlog with identified solutions that just need a goon to implement them.

**Comment by zadjii-msft** [comment]
> feel free to assign any goon work to me. I'm sure there's a lot of issues in the backlog with identified solutions that just need a goon to implement them.

Be careful what you wish for 😜 I'll look for some things that might be up your alley
