### PR TITLE
Fix crash in terminal when tab closed while data is being output

### LINKED ISSUE #8734: Windows Terminal can crash if a tab is closed while data is being output
# Environment

Windows build number: Version 10.0.18363.1256
Windows Terminal version (if applicable): Commit 49d008537f0bb73c8bfc85df773a46a2b3e9ac79

# Steps to reproduce

This is rather difficult to reproduce, but here is one sequence of events that is known to trigger it sometimes.

1. Open Windows Terminal.
2. Open a second tab with a bash shell.
3. Output a large file (e.g. `cat /mnt/c/Windows/explorer.exe`).
4. While the content is still being output, close the tab.
5. Repeat steps 2 to 4 until it crashes.

# Expected behavior

The tab should always be able close without crashing the app.

# Actual behavior

Sometimes closing the tab will cause Windows Terminal to terminate with an unhandled exception.

The problem is that the `TerminalControl` is trying to process output when it has already been destroyed in the main thread (when the tab was closed). The exact location of the crash will vary, but it's quite often inside the `Cursor::_RedrawCursorAlways` method, triggered from somewhere like `Terminal::_AdjustCursorPosition` when adjusting the cursor position.

The reason it doesn't crash all the time, is because the renderer is often going to be painting a frame, in which case it will have grabbed the console lock, so the `TerminalConnection` thread wouldn't be able to output anything. And while the renderer is painting the frame, the shutdown will be blocked in the `Renderer::TriggerTeardown` call while waiting for the `_hPaintCompletedEvent`.

If you get the timing just right, though, the frame will have just finished painting, so the `_hPaintCompletedEvent` will have been set, and the console won't be locked. The `TerminalConnection` thread would then be free to grab the lock and start processing output, and the main thread wouldn't need to wait on `_hPaintCompletedEvent`, so could happily kill the `TerminalControl` while it is still in use.

Bottom line is I think we need another lock somewhere in the shutdown sequence.

### PR DESCRIPTION
**Pull request by j4james**
If there is data being output when a tab is closed, that can sometimes
result in the application crashing, because the renderer may still be in
use at the time is it destroyed. This PR attempts to prevent that from
happening by adding a lock in the `TermControl::Close` method.

What we're trying to prevent is the connection thread still being
active, and potentially accessing the renderer, after it has been
destroyed. So by acquiring the terminal lock in `TermControl::Close`,
after we've stopped accepting new output, we can be sure that the
connection thread is no longer active (it holds the lock while it is
processing output). So once we've acquired and released the lock, it
should be safe to tear down and destroy the renderer.

## Validation Steps Performed

While this crash is difficult to reproduce in general usage, it occurred
quite frequently when testing my `DECPS` implementation (there is some
tricky thread synchronisation, which seems more likely to trigger the
issue). With this patch applied, though, those crashes have stopped
occurring.

I've also stepped through the shutdown code in the debugger, manually
freezing threads to get them aligned in the right way to trigger the
crash (as explained in issue #8734). Again with the patch applied, I can
no longer get the crash to occur.

Closes #8734

### CODE REVIEW

**Review by carlos-zamora — APPROVED** [review]

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 1]
```diff
@@ -2598,6 +2598,16 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
             // closed. We can just do it whenever.
             _AsyncCloseConnection();
 
+            {
+                // We lock the terminal here to make sure it isn't still being
```
Comment (zadjii-msft) [inline src/cascadia/TerminalControl/TermControl.cpp:2602]:
```suggestion
                // GH#8734:
                // We lock the terminal here to make sure it isn't still being
```

Only suggestion is to add a note to the original issue, because I'm _certain_ we're not going to remember where this came from

**Review by zadjii-msft — APPROVED** [review]

**Review by DHowett — APPROVED** [review]
Clever fix. I hate it. I mean, I very much appreciate you fixing it, but I hate that our locking story is so poorly-told that you need to take and then surrender a lock as a sort of acq-rel barrier. :smile:

**Comment by DHowett** [comment]
(Thank you, as always!)
