### PR TITLE
Fix line drawing during IME operations.

### LINKED ISSUE #803: Lines are not drawn correctly during IME edit line operations
Ported from MSFT: 20973297

> The underscores and the cursor bar aren't being transmitted or drawn correctly when working with the IME. Compare to v1 behavior.
> 
> I think there's something wrong with the communication of both the underscores and the positioning of the caret after the refactoring to use the unified output buffer. Investigate.

### PR DESCRIPTION
**Pull request by miniksa**
## Summary of the Pull Request
Restores proper line drawing during IME operations in `conhost`

## PR Checklist
* [x] Closes #803
* [x] I work here.
* [x] Tested manually.
* [x] Check the performance of this and see if it's worse-enough to merit a more confusing algorithm. It was worse for the majority case so I scoped it.
* [x] No doc, it should have worked this way.
* [x] Am core contributor.

## Detailed Description of the Pull Request / Additional comments
- Changed `ConsoleImeInfo::s_ConvertToCells` to be less confusing. It's doing about the same thing, but it's way easier to read now and the compiler/linker/optimizer should just be the same.
- Edited `Renderer::_PaintBufferOutputHelper` to check each attribute for line drawing characters as the right half of a two-col character might have different line drawing characters than the left-half.

## Validation Steps Performed
- [x] Manual operation of IME in conhost with Japanese IME.
- [x] Manual operation of IME in conhost with Chinese IME.
- [x] Manual operation of IME in conhost with Chinese (Traditional) IME.
- [x] Manual operation of IME in conhost with and Korean IME. - @leonMSFT says Korean doesn't work this way. But Korean is broken worse in that it's not showing suggestions at all. Filing new bug. #6227 
- [x] Validated against API-filling calls through `SetConsoleTextAttribute` per @j4james's sample code

### CODE REVIEW

**Comment by miniksa** [comment]
@j4james, this is my proposal.

**Comment by j4james** [comment]
OK, this is much better than what I had. I ended up having to extend the `OutputCellView` and `TextBufferCellIterator` which is the part I hated the most (I need to look at the code again to see what made me think that was necessary). I was also concerned about the renderer having to draw the grid one character at a time, and wondering whether we might be able to optimise that a bit. But having that as a special case for wide characters does at least limit when that happens, so that's not too bad either.

I'm busy geeking out over the upcoming SpaceX launch at the moment, so I'll try and look at this in more detail later, but my initial impression is very positive.

File: src/renderer/base/renderer.cpp [hunk 1]
```diff
@@ -774,8 +785,35 @@ void Renderer::_PaintBufferOutputHelper(_In_ IRenderEngine* const pEngine,
             // If we're allowed to do grid drawing, draw that now too (since it will be coupled with the color data)
             if (_pData->IsGridLineDrawingAllowed())
             {
-                // We're only allowed to draw the grid lines under certain circumstances.
-                _PaintBufferOutputGridLineHelper(pEngine, currentRunColor, cols, screenPoint);
+                // If we found a wide character while we looped above, it's possible we skipped over the right half
```
Comment (DHowett) [inline src/renderer/base/renderer.cpp:788]: please link this back up to the github issue it closes -- that's important context for "why we decided we had to do this"

**Comment by DHowett** [comment]
I hate that this is possible. :smile:

#6224 probably needs separate "line drawing runs" ...
that actually makes this way easier.

File: src/renderer/base/renderer.cpp [hunk 2]
```diff
@@ -774,8 +785,35 @@ void Renderer::_PaintBufferOutputHelper(_In_ IRenderEngine* const pEngine,
...
+                    // (like with the IME) that the line drawing characters will vary from the left to right half
+                    // of a wider character.
+                    // We could theoretically pre-pass for this in the loop above to be more efficient about walking
+                    // the iterator, but I fear it would make the code even more confusing than it already is.
+                    // Do that in the future if some WPR trace points you to this spot as super bad.
+                    for (auto colsPainted = 0; colsPainted < cols; ++colsPainted, ++lineIt, ++lineTarget.X)
+                    {
+                        auto lines = lineIt->TextAttr();
+
+                        // We're only allowed to draw the grid lines under certain circumstances.
```
Comment (j4james) [inline src/renderer/base/renderer.cpp:808]: Just a minor point, but this comment doesn't really make sense here anymore.

**Comment by miniksa** [comment]
> I hate that this is possible. 😄
> 
> #6224 probably needs separate "line drawing runs" ...
> that actually makes this way easier.

Agreed. Each thing should probably be its own pass. If it can be efficient enough.

**Comment by j4james** [comment]
I've had a chance to run some more tests now, and I'm not sure this is working as well as I had thought. I have a little test case that tries to render every combination of grid flag around a wide character, and that doesn't seem to work with this PR. This is my test code:

```C
#include <windows.h>
#include <stdio.h>

void test(WORD attr)
{
  HANDLE handle = GetStdHandle(STD_OUTPUT_HANDLE);
  SetConsoleTextAttribute(handle, 0x07);
  printf(" ");
  SetConsoleTextAttribute(handle, 0x07 | attr);
  printf("\xE5\xA4\xA7");
  SetConsoleTextAttribute(handle, 0x07);
}

void main()
{
  SetConsoleOutputCP(CP_UTF8);
  printf("\n");
  test(COMMON_LVB_GRID_LVERTICAL);
  test(COMMON_LVB_GRID_HORIZONTAL);
  test(COMMON_LVB_GRID_RVERTICAL);
  test(COMMON_LVB_UNDERSCORE);
  test(COMMON_LVB_UNDERSCORE | COMMON_LVB_GRID_LVERTICAL);
  test(COMMON_LVB_GRID_LVERTICAL | COMMON_LVB_GRID_HORIZONTAL);
  test(COMMON_LVB_GRID_HORIZONTAL | COMMON_LVB_GRID_RVERTICAL);
  test(COMMON_LVB_GRID_RVERTICAL | COMMON_LVB_UNDERSCORE);
  test(COMMON_LVB_UNDERSCORE | COMMON_LVB_GRID_HORIZONTAL);
  test(COMMON_LVB_GRID_LVERTICAL | COMMON_LVB_GRID_RVERTICAL);
  test(COMMON_LVB_GRID_LVERTICAL | COMMON_LVB_GRID_RVERTICAL | COMMON_LVB_UNDERSCORE);
  test(COMMON_LVB_GRID_LVERTICAL | COMMON_LVB_GRID_RVERTICAL | COMMON_LVB_GRID_HORIZONTAL);
  test(COMMON_LVB_GRID_LVERTICAL | COMMON_LVB_GRID_RVERTICAL | COMMON_LVB_GRID_HORIZONTAL | COMMON_LVB_UNDERSCORE);
  printf("\n");
}
```
This is what I expected it to look like (more or less - not sure about the center grid lines, but I think that's a separate issue):

image

This is what I'm seeing with this PR:

image

I'm hoping maybe I've just screwed up the build somehow. Will do some more digging.

File: src/renderer/base/renderer.cpp [hunk 3]
```diff
@@ -772,10 +783,38 @@ void Renderer::_PaintBufferOutputHelper(_In_ IRenderEngine* const pEngine,
...
-                _PaintBufferOutputGridLineHelper(pEngine, currentRunColor, cols, screenPoint);
+                // See GH: 803
+                // If we found a wide character while we looped above, it's possible we skipped over the right half
+                // attribute that could have contained different line information than the left half.
+                if (containsWideCharacter)
+                {
+                    // Start from the original position.
+                    auto lineIt = originalIt;
+                    // Start from the original target.
+                    auto lineTarget = target;
```
Comment (j4james) [inline src/renderer/base/renderer.cpp:797]: I think I've figured out where's it's going wrong, We're resetting the iterator and target here every time we render a section of the line. So when there are multiple sections, only the first part gets rendered correctly. The only way I can see this working is if we do the entire grid rendering in one go outside the main while loop. But that means you lose the non-widechar optimization, unless you can calculate that up front somehow.

Comment (miniksa) [reply src/renderer/base/renderer.cpp:797]: Nnnn. Thanks for digging. I'll check this against your test code on Friday when I'm back to work.

**Comment by j4james** [comment]
One other thing I wanted to mention. It's not essential for this PR, but I thought while you're looking at this grid code, it might be a good time to get rid of `COMMON_LVB_GRID_SINGLEFLAG`. As far I could make out, it doesn't actually serve any purpose, and that would free up another bit for us to use in the attributes.

File: src/renderer/base/renderer.cpp (hunk 3 above)
Comment (miniksa) [reply src/renderer/base/renderer.cpp:797]: Friday I learned I needed a new roof so I took the rest of the day to rage at that. Going to peek in what's left of today and/or Wednesday now. Thanks.

Comment (miniksa) [reply src/renderer/base/renderer.cpp:797]: Hmmmmm I'm rooting through this and as I patch it up and patch it up to make it happen inside the same loop, it's only getting more and more complicated. I think I either need to

1. Make the line drawing a separate pass through the iterators.
2. Make this pass through the loop, that is gathering up `Cluster` as a rendering unit, also gather up some sort of `LineCluster` units. And then dispatch the two of those later.

The only reason I'd lean toward the latter is because walking the iterators isn't super cheap, as of my memory from last time I profiled it. 

Additionally, I need to check what the v1 console does here with your sample code. I was under the presumption that one could set a different set of lines to the right half of the character than the left half, for whatever reason. If that wasn't possible in the v1 console and it did something like, say, only use the left-half lines for drawing around the entire 2-col character... then I'd like to change this back to do the same thing.

Comment (j4james) [reply src/renderer/base/renderer.cpp:797]: FWIW, my attempt to solve this was using the second approach, i.e. building up a cluster of grid lines for each pass of the main loop. What I was storing was the result of the `s_GetGridlines` call rather than the original `TextAttribute`, since I thought that would be a little more efficient. The actual grid color you should be able to get from the `currentRunColor` for each pass. 

That said, I'm not sure I had all the edge cases correct (like backing up when you have a trailing DBCS char), and I actually thought your iterator approach was much nicer since it avoided the extra memory allocations needed for the list.

**Comment by miniksa** [comment]
大 is
| encoding | code |
|---|---|
| UTF-8 | 0x35 0xa4 0xa7 |
| UTF-16 | 0x59 0x27 | 
| Shift-JIS | 0x91 0xe5 |

**Comment by miniksa** [comment]
Conhost v1 with the scratch code:
image

Repaired OpenConsole on commit https://github.com/microsoft/terminal/pull/6223/commits/e1c757fdc5ba80e989c3ff6de768c647ff4637e8:
image

**Comment by miniksa** [comment]
> One other thing I wanted to mention. It's not essential for this PR, but I thought while you're looking at this grid code, it might be a good time to get rid of `COMMON_LVB_GRID_SINGLEFLAG`. As far I could make out, it doesn't actually serve any purpose, and that would free up another bit for us to use in the attributes.

I went and read the code for this from conhostv1.

`COMMON_LVB_GRID_SINGLEFLAG` literally indicated to the IME output-buffer writer code that it needed to remove RVERTICAL from the left half of a two column character and LVERTICAL from the right half of a two column character. You know. Instead of determining that some other way and just stripping it out or only applying it to half the character.

So yeah, I think it can go away and/or be repurposed.

**Comment by miniksa** [comment]
I believe this is good for merge. It restores the behavior to match v1 conhost in both through-the-API and IME cases.

File: src/renderer/base/renderer.cpp (hunk 3 above)
Comment (miniksa) [reply src/renderer/base/renderer.cpp]: 2 days of not looking at it and one gentle nudge got my change working. So I'm resolving this.

**Comment by j4james** [comment]
For the record this looked good to me too. Your solution turned out much simpler than what I thought would be required. 👍
