### PR TITLE
Rejuvenate the color schemes page

### LINKED ISSUE #9775: People think the Color Scheme editor will change the current colors
### Windows Terminal version (or Windows build number)

10.0.21354 (Dev)

### Other Software

_No response_

### Steps to reproduce

1. Launch Terminal
2. Open Settings
3. Color Schemes
4. Select another color scheme from combo
5. Click to Save
6. Reopen Settings -> Color Scheme didn't applied

### Expected Behavior

_No response_

### Actual Behavior

Color Scheme.

### PR DESCRIPTION
**Pull request by PankajBhojwani**
Update the color schemes page with the new Win 11 style.
With the rejuvenated experience, we now have two pages:

- `ColorSchemes.xaml`: "color scheme selection" page
	- This is the starting page for the "color schemes" nav view
	  item. It is intended to have the user select a color scheme
	  they want to modify. The user can also click the "Add new"
	  button to add a new color scheme or the "delete" button to
	  delete the selected scheme.
	- If a scheme cannot be deleted, the delete button is disabled
	  and a disclaimer is shown.
	- A "set as default" button sets the selected scheme as the
	  color scheme for profiles.default (aka "base layer"). 
	- The list view item for each scheme includes the name of the
	  scheme, the default tag (if the scheme is the one set in base
	  layer), a text preview of the foreground/background, and a
	  grid of 16 color chips showing the colors for the scheme.
	- Implementation details:
		- View - `ColorSchemes`:
			- "Enter" --> edit the selected scheme
			- "Delete" --> delete the selected scheme
			- if the selected scheme cannot be deleted, we
			  show the disclaimer
		- View model - `ColorSchemesPageViewModel`
			- when possible, the XAML binds directly to the
			  view model functions. Thus, we include logic
			  to delete, edit, and set the selected scheme
			  as default.
			- store the current page, so that we know which
			  page to navigate to upon saving/discarding
			  changes.
- `EditColorScheme.xaml`: "color scheme modification" page
	- a terminal preview of the color scheme is shown at the top of
	  the page.
	- all colors for the scheme are displayed as color chips in an
	  expander that starts as expanded.
	- renaming a color scheme is also inside an expander, but
	  there's no need for "renaming mode" anymore
	- Implementation details:
		- View - `EditColorScheme`:
			- include logic to display the disclaimer and
			  add the automation properties
			- include logic for "Enter" and "Escape" in the
			  rename editor
		- View Model - `ColorSchemeViewModel`:
			- as before, when possible, the XAML binds
			  directly to the view model functions.
			- To enable the "default" tag functionality, we
			  had to expose knowledge of being the default
			  via "IsDefaultScheme()" which compares the
			  current name to the one in the settings model.
- Miscellaneous implementation details:
	- to get the expander to start as expanded, we had to modify the
	  setting container style.
	- Since "set as default" is a button on the selector page, we
	  needed a way to refresh the view model's knowledge of being
	  the default. So we added a `RefreshIsDefault` API to the
	  `ColorSchemeViewModel` to notify changes.
	- With the new layout, we no longer need an 'enter rename mode'
	  button, so all that logic has been removed
	- Add logic to `MainPage` to handle navigating to the correct
	  page upon saving/discarding changes.

Closes #9775

Co-authored-by: Carlos Zamora <cazamor@microsoft.com>

### CODE REVIEW

**Comment by PankajBhojwani** [comment]
Screenshots:
schemes1

All expanders expanded:
schemes2

**Comment by DHowett** [comment]
So, I've got some feelings about this new Color Schemes page. I think we might have gone "too hard" on Expanders, to the point where the page has lost coherence. It's a page for editing color schemes, it should not take so many clicks to _edit a color scheme_, you know? Hiding the various types of color, which are all kinda the same setting at the end of the day, in different groups... it rubs me the wrong way.

In addition to that, Add New and Rename getting their own areas, separate from the scheme, feels like they were just bolted on as an afterthought.

I want us to stop and reconsider this page, and how it flows. The preview on top, the scheme selector (which is a _single setting_ that controls the _contents of the page_), and then the colors might be the wrong order in which to tackle it.

If we had a ground-up redo, what would our color scheme editor look like? How would we want the user to flow through it?

**Comment by zadjii-msft** [comment]
> If we had a ground-up redo, what would our color scheme editor look like? How would we want the user to flow through it?

<bad idea time>

It's a giant list of all the schemes as expando buttons. Clicking them takes you to a subpage that's basically the same thing we have today, but with a preview?


Or they're all expanders with the 20 buttons and renamer nested in the expanders, all on the main page

**Comment by cinnamon-msft** [comment]
Okay actually I just checked out the Colors page in Windows Settings, and it opened with the Accent color expander already opened. Maybe we can just have the Terminal colors and System colors expanders open by default, so there isn't an extra click and you can see the colors instantly?

File: src/cascadia/TerminalSettingsEditor/ColorSchemeViewModel.cpp [hunk 1]
```diff
@@ -10,12 +10,14 @@
...
-    ColorSchemeViewModel::ColorSchemeViewModel(const Model::ColorScheme scheme) :
+    ColorSchemeViewModel::ColorSchemeViewModel(const Model::ColorScheme scheme, const Editor::ColorSchemesPageViewModel parentPageVM) :
         _scheme{ scheme },
         _NonBrightColorTable{ single_threaded_observable_vector<Editor::ColorTableEntry>() },
-        _BrightColorTable{ single_threaded_observable_vector<Editor::ColorTableEntry>() }
+        _BrightColorTable{ single_threaded_observable_vector<Editor::ColorTableEntry>() },
+        _parentPageVM{ parentPageVM }
     {
         _Name = scheme.Name();
+        _isInBoxScheme = std::find(std::begin(InBoxSchemes), std::end(InBoxSchemes), scheme.Name()) != std::end(InBoxSchemes);
```
[the remark this answers is not in the document]
Comment (PankajBhojwani) [reply src/cascadia/TerminalSettingsEditor/ColorSchemeViewModel.cpp]: Thanks for pointing that out! Fixed by having the PageVM tell the SchemeVM if the scheme is in box or not

**Comment by zadjii-msft** [comment]
> if the user deleted the scheme with the keyboard, shouldn't we yeet focus back to the list? also, do we throw focus anywhere _else_ for any reason?

We should probably follow #11971 (or just generally make sure that still works). In that one, we were always yeeting back to the list, esp if the next scheme selected would be a default scheme that's not editable

**Comment by zadjii-msft** [comment]
_disclaimer: I am not a UX designer_

As a side thought, should we have little arrows at the right of these "expanders" that lead to the edit page?

image

They wouldn't _say_ edit (except in a tooltip), but they would _intuitively_ lead me to think there's more for that scheme if I follow that arrow.

I don't think we should get rid of the "edit" button (as another highly visible, intentional button), but just a thought.

**Comment by DHowett** [comment]
I don't know if we should put buttons _inside_ the thing. We may want to consider double-click pushing on the Edit page, but... what do we do in the future when inbox schemes can't be edited (only copied)?

**Comment by PankajBhojwani** [comment]
> if the user deleted the scheme with the keyboard, shouldn't we yeet focus back to the list? also, do we throw focus anywhere else for any reason?

Focus gets sent back to the list now, and we don't throw focus anywhere else for any reason

> are these readable by screen readers?

Only the name of the color scheme gets read out by narrator as the keyboard focus moves through the list view items

**Comment by PankajBhojwani** [comment]
> are these readable by screen readers?

Oh wait you meant the preview window in the edit page, keyboard focus cannot land on it so nope, screen readers can't read it

**Comment by zadjii-msft** [comment]
I think we can now say that this PR will close out #9775, yea?

**Comment by PankajBhojwani** [comment]
> I think we can now say that this PR will close out https://github.com/microsoft/terminal/issues/9775, yea?

yes

**Comment by zadjii-msft** [comment]
Yeet and fix in post?

**Comment by DHowett** [comment]
Does this actually close 9775? Even if the checkbox is unchecked, saying `Closes xxx` _will_ close issue xxx when the PR merges. :)

**Comment by PankajBhojwani** [comment]
> Does this actually close 9775?

I think it does... I suppose we could wait on feedback before actually closing it though?

**Comment by carlos-zamora** [comment]
Notes from bug bash (8/2):
- [ ] remove big gap at bottom of CS page
- [ ] add disclaimer for why "Delete" button is disabled
- [ ] update "rename color scheme" disclaimer to only say "cannot be renamed"
- [ ] **NIT:** clicking "Save" shows the expander animation. It'd be nice if the animation wasn't shown
- [ ] (offline) keyboard navigation issue

**Comment by DHowett** [comment]
If we're cracking the seal on this we might want to consider:

1. making double click open up the color scheme, as it is equivalent to Enter in many contexts
2. Somehow resolving the visual margin issue of having a nested "expander" looking thing inside the list
3. Maybe we should not start with one selected; otherwise, it looks like that is the "default" one (which could lead to the same confusion we have had in the past over selecting a scheme and having it not apply to profiles?)

**Comment by carlos-zamora** [comment]
> 1. making double click open up the color scheme, as it is equivalent to Enter in many contexts

XAML doesn't seem to provide a way to detect a double click 🙃. We should be able to add logic to detect it ourselves (similar to [ControlInteractivity](https://github.com/microsoft/terminal/blob/258a3f32ad40d07f73953354a531bfa4d245d161/src/cascadia/TerminalControl/ControlInteractivity.cpp#L50)), but I'm gonna say we should do that as a follow-up since it's a bit more complex.

> 2. Somehow resolving the visual margin issue of having a nested "expander" looking thing inside the list

Writing down some notes so that we have a log of what I've tried. I initially took this as "make the selector pill appear _inside_ the container". That was relatively easy, actually. I leveraged `ListView.ItemContainerStyle` to set the `Background` to `ExpanderHeaderBackground` and that made it look right... _at first_. The problem was that I then had to go down the rabbit hole of styling the hover/pressed state. I was able to borrow the resources from the `Navigator` (i.e. the "Advanced" navigator in a profile page), but was left to figure out (1) what color to use to make the selected item stand out and (2) how to change the border color (because in light theme, the border becomes more important, but `ListViewItem` has no key for border customization).

So I've given up on the approach above (at least for this PR), and am now removing the container entirely to make it look more like the Actions page (except with the selector pill on the left).'

> 3. Maybe we should not start with one selected; otherwise, it looks like that is the "default" one (which could lead to the same confusion we have had in the past over selecting a scheme and having it not apply to profiles?)

Fixed

**Comment by carlos-zamora** [comment]
Screenshots for 6e6c0fd:
color schemes selection page
color schemes editor page

**Comment by carlos-zamora** [comment]
This now includes #13839 (and any propagated changes)

Ready for review!

**Comment by DHowett** [comment]
I removed this from the body. Kayla's experience suggests the opposite.

> * [ ] Closes #9775

**Review by DHowett — APPROVED** [review]

**Comment by DHowett** [comment]
Whoops, i clicked Approve instead of collapsing the first file I read

File: src/cascadia/TerminalSettingsEditor/ColorSchemeViewModel.h [hunk 2]
```diff
@@ -42,6 +49,7 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
     private:
         winrt::hstring _Name;
         Model::ColorScheme _scheme;
+        Editor::ColorSchemesPageViewModel _parentPageVM{ nullptr };
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/ColorSchemeViewModel.h:52]: Concern: this could result in a memory leak if CSPVM has strong references to its CSVMs.

File: src/cascadia/TerminalSettingsEditor/ColorSchemeViewModel.idl [hunk 3]
```diff
@@ -5,11 +5,14 @@ import "ColorSchemes.idl";
 
 namespace Microsoft.Terminal.Settings.Editor
 {
-    runtimeclass ColorSchemeViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
+    runtimeclass ColorSchemeViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged, Windows.Foundation.IStringable
     {
-        ColorSchemeViewModel(Microsoft.Terminal.Settings.Model.ColorScheme scheme);
+        ColorSchemeViewModel(Microsoft.Terminal.Settings.Model.ColorScheme scheme, ColorSchemesPageViewModel parentPageVM);
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/ColorSchemeViewModel.idl:10]: This doesn't need to be part of the public interface! Actually, the whole constructor can be removed from the IDL. Only put things in an IDL if somebody should be allowed to construct them from a different DLL!

File: src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw [hunk 4]
```diff
@@ -1225,7 +1233,7 @@
     <value>Rename</value>
     <comment>Text label for a button that can be used to begin the renaming process.</comment>
   </data>
-  <data name="ColorScheme_DeleteButtonDisclaimerInBox.Text" xml:space="preserve">
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw:1228]: Please keep this key exactly as-is. If we need to change it, duplicate it with the new name.

File a bug for removing it later (incl. any other keys that this PR would have removed.)

Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw:1228]: We should **prefer** this kind of resource: a UID with a `.Property`. XAML automatically wires them up with the right `x:Uid`.

Loading these xaml UI string resources via code should be a last resort!

File: src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw [hunk 5]
```diff
@@ -1337,13 +1345,9 @@
     <value>Reset to inherited value.</value>
     <comment>This button will remove a user's customization from a given setting, restoring it to the value that the profile inherited. This is a text label on a button.</comment>
   </data>
-  <data name="ColorScheme_TerminalColorsHeader.Text" xml:space="preserve">
-    <value>Terminal colors</value>
-    <comment>A header for a grouping of colors in the color scheme. These colors are used for basic parts of the terminal.</comment>
-  </data>
-  <data name="ColorScheme_SystemColorsHeader.Text" xml:space="preserve">
-    <value>System colors</value>
-    <comment>A header for a grouping of colors in the color scheme. These colors are used for functional parts of the terminal.</comment>
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw:1346]: Do not remove; file bug to remove later

File: src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw (hunk 4 above)
Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw:1228]: Do we even need to change this one? It looks like it's been outmoded by the two new separate ones.

File: src/cascadia/TerminalSettingsEditor/CommonResources.xaml [hunk 6]
```diff
@@ -283,7 +283,7 @@
 
     <Style x:Key="IconButtonTextBlockStyle"
            TargetType="TextBlock">
-        <Setter Property="Margin" Value="10,0,0,0" />
+        <Setter Property="Margin" Value="0,0,0,0" />
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/CommonResources.xaml:286]: This seems quite unrelated. Doesn't this mean that we might be using the wrong style for a contro lwhere we didn't want a margin?

Also, this style seems to be the same as "no style", because the default is "no margin"

File: src/cascadia/TerminalSettingsEditor/ColorSchemesPageViewModel.idl [hunk 7]
```diff
@@ -5,20 +5,27 @@ import "ColorSchemeViewModel.idl";
...
         void RequestDeleteCurrentScheme();
 
         ColorSchemeViewModel CurrentScheme;
+        Boolean HasCurrentScheme { get; };
         Boolean CanDeleteCurrentScheme { get; };
-        Boolean InRenameMode { get; };
+        ColorSchemesSubPage CurrentPage;
         Windows.Foundation.Collections.IObservableVector<ColorSchemeViewModel> AllColorSchemes { get; };
+
+        void Edit_Click(IInspectable sender, Windows.UI.Xaml.RoutedEventArgs e);
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/ColorSchemesPageViewModel.idl:29]: this should not need to be in the IDL.

If it's in the IDL, _anybody could call it_ even, again, from another DLL. 
That's not a great public API :)

**Review by DHowett — CHANGES_REQUESTED** [review]
18/24; notes while I go

**Review by zadjii-msft — COMMENTED** [review]
Largely just the same questions dustin has

File: src/cascadia/TerminalSettingsEditor/CommonResources.xaml (hunk 6 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/CommonResources.xaml:286]: Sorta. Resolved locally haha. Still need to push my changes to the PR.

File: src/cascadia/TerminalSettingsEditor/ColorSchemeViewModel.h (hunk 2 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/ColorSchemeViewModel.h:52]: made this a weak ref to the parent page (and do the `.get` thing when we're about to use it)

File: src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw [hunk 8]
```diff
@@ -1165,8 +1169,12 @@
     <value>Add new</value>
     <comment>Button label that creates a new color scheme.</comment>
   </data>
-  <data name="ColorScheme_DeleteButton.Text" xml:space="preserve">
-    <value>Delete color scheme</value>
```
Comment (carlos-zamora) [inline src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw:1169]: I'll fix this after lunch. We crash because the button doesn't have text. This used to work because we had icons on all of these buttons, so the resource would bind to the text block inside the button. Now, these buttons don't have icons.

We should probably add icons to all of these. I'll do that in this next commit.

**Comment by carlos-zamora** [comment]
Screenshots for 5a6ab36
image
image

File: src/cascadia/TerminalSettingsEditor/ColorSchemeViewModel.cpp [hunk 9]
```diff
@@ -48,6 +50,25 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
...
 
+    bool ColorSchemeViewModel::IsDefaultScheme()
+    {
+        return _Name == _settings.ProfileDefaults().DefaultAppearance().ColorSchemeName();
+    }
+
+    void ColorSchemeViewModel::RefreshIsDefault()
+    {
+        _NotifyChanges(L"IsDefaultScheme");
+    }
```
Comment (carlos-zamora) [inline src/cascadia/TerminalSettingsEditor/ColorSchemeViewModel.cpp:61]: For the record, I hate this. But I think it's a necessary evil, and I tried to limit how exposed this is by making it only available through the impl type.

### Why do we need it?
- The "default" tag is visibly bound to the `IsDefaultScheme` getter above, which queries the model to know the answer.
- When the user clicks the "Set as default" button, we update the "base layer" (yes, I'm still calling it that haha) to have the new color scheme as the default. The key thing here is that the base layer stores the _name_ not the CS object. So we _need_ to query the settings model to answer the question "are we the default?". 
- So now we have a problem: the model updated, but the view model has no idea what's changed. We need the view model to refresh it's value for `IsDefaultScheme`.
- the solution: in `ColorSchemesPageViewModel`, we go through all the schemes and notify that `IsDefaultScheme` has changed.
- alternatively, why not store `IsDefaultScheme` as an observable bool: decided against this because this just makes constructing the list of scheme VMs nasty. This also means that we're not "pure"-ly knowing if we're the default scheme. We're just caching whatever the parent VM tells us, which just feels icky.

Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/ColorSchemeViewModel.cpp:61]: I understand, and agree. You are seen. :D

File: src/cascadia/TerminalSettingsEditor/ColorSchemes.cpp [hunk 10]
```diff
@@ -73,12 +72,17 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
         }
     }
 
+    void ColorSchemes::Edit_Click(const IInspectable& /*sender*/, const RoutedEventArgs& /*e*/)
+    {
+        _ViewModel.RequestEditSelectedScheme();
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/ColorSchemes.cpp:84]: confused - why isn't this hooked up directly to the viewmodel from the xaml? no need for an event handler in the View

File: src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw [hunk 11]
```diff
@@ -1493,4 +1497,8 @@
     <value>This color scheme cannot be renamed because it is included by default.</value>
     <comment>Disclaimer presented near the controls to rename the color scheme when that functionality is disabled.</comment>
   </data>
+  <data name="ColorSchemes_TextPreview.Text" xml:space="preserve">
+    <value>Text</value>
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw:1501]: Ah, does that text preview resize appropriately when the string is long?

should we just choose a rather language-agnostic "`AaBbCc...`" instead? That might even be better.

FWIW: i hope it's not read out by narrator!

File: src/cascadia/TerminalSettingsEditor/ColorSchemeViewModel.cpp [hunk 12]
```diff
@@ -49,6 +50,16 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
         return _Name;
     }
 
+    bool ColorSchemeViewModel::IsDefaultScheme()
+    {
+        return _Name == _settings.ProfileDefaults().DefaultAppearance().ColorSchemeName();
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/ColorSchemeViewModel.cpp:55]: _clever_. renaming a scheme updates all profiles using it, so this will be true after a rename too. very clever.

File: src/cascadia/TerminalSettingsEditor/ColorSchemeViewModel.cpp (hunk 9 above)
Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/ColorSchemeViewModel.cpp:61]: After reading the PR, I still agree! This is _fine_. We can eventually fix the settings model.

FWIW: the way to make this observable is to just call PropertyChangedHandlers with the name `IsDefaultScheme`. Less icky, and you could hook it up by chaining the propertychanged handler.

Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/ColorSchemeViewModel.cpp:61]: Hey, how does this work if you go edit Base Layer directly? and select a different scheme?

File: src/cascadia/TerminalSettingsEditor/ColorSchemes.xaml [hunk 13]
```diff
@@ -54,14 +54,29 @@
...
+                                    Margin="10,0,0,0"
+                                    Padding="2,0,2,0"
+                                    HorizontalAlignment="Left"
+                                    VerticalAlignment="Center"
+                                    Background="{ThemeResource SystemAltMediumLowColor}"
+                                    BorderBrush="{ThemeResource SystemControlForegroundBaseMediumBrush}"
+                                    BorderThickness="1"
+                                    CornerRadius="1"
+                                    Visibility="{x:Bind IsDefaultScheme, Mode=OneWay}">
+                                <TextBlock x:Uid="ColorScheme_DefaultTag"
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/ColorSchemes.xaml:75]: should we give this a better Narrator description? "This is the current default color scheme"

File: src/cascadia/TerminalSettingsEditor/ColorSchemes.xaml [hunk 14]
```diff
@@ -228,11 +243,18 @@
...
                 </Button>
 
-                <TextBlock x:Name="SelectedSchemeDisclaimer"
-                           Margin="10,0,0,0"
-                           VerticalAlignment="Center"
-                           Style="{StaticResource DisclaimerStyle}" />
+                <Button x:Name="SetAsDefaultButton"
+                        x:Uid="ColorScheme_SetAsDefaultButton"
+                        Margin="10,0,0,0"
+                        Click="SetAsDefault_Click"
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/ColorSchemes.xaml:249]: you can bind this directly to the ViewModel

File: src/cascadia/TerminalSettingsEditor/ColorSchemeViewModel.cpp (hunk 9 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/ColorSchemeViewModel.cpp:61]: > Hey, how does this work if you go edit Base Layer directly? and select a different scheme?

Good catch, but surprisingly this works as expected! I guess XAML automatically handles it since the binding is in the markup.

File: src/cascadia/TerminalSettingsEditor/ColorSchemes.cpp (hunk 10 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/ColorSchemes.cpp:84]: yup, that's exactly what I missed haha. Didn't realize you can bind a click handler directly to the view model :P

File: src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw (hunk 11 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw:1501]: > Ah, does that text preview resize appropriately when the string is long?

image

> should we just choose a rather language-agnostic "`AaBbCc...`" instead? That might even be better.

Eh. Up to you. We could also bind it to the color scheme name but then the previews wouldn't be guaranteed to align.

> FWIW: i hope it's not read out by narrator!

Hah. They weren't when you would select a color scheme, but they were "focusable" when navigating with the arrow keys with Narrator. Just fixed it.

File: src/cascadia/TerminalSettingsEditor/ColorSchemes.xaml (hunk 13 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/ColorSchemes.xaml:75]: This is the only one I couldn't figure out. The "default" text is "focusable" by narrator so it should be somewhat clear which item is the default.

Ideally, the help text would be set like you said, but I'm having trouble accessing the `ListViewItem` and setting the help text on it. This help text would then have to be updated each time the default tag moves. I think this makes sense as a follow-up since the solution is going to be fairly ugly.

**Review by DHowett — APPROVED** [review]
Let's do this and fix the issues in post eh?

**Review by zadjii-msft — APPROVED** [review]

File: src/cascadia/TerminalSettingsEditor/ColorSchemes.xaml (hunk 13 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/ColorSchemes.xaml:75]: moved to #13891

File: src/cascadia/WindowsTerminal/AppHost.cpp [hunk 15]
```diff
@@ -145,17 +145,6 @@ AppHost::~AppHost()
 
     _showHideWindowThrottler.reset();
 
-    // From a mail thread: Should a UnhandledException be raised by XAML, while
-    // we're tearing down, let's eat it, log it, and just die immediately. This
-    // will prevent unhandled XAML exceptions from crashing with a dump bucket
-    // when the window has already been closed.. We feel this is okay though,
-    // because WE'RE ALREADY IN TEARDOWN! The app is exiting. We don't want a
-    // XAML bug here to create a crash bucket.
-    _app.UnhandledException([](auto&& /*sender*/, const UnhandledExceptionEventArgs& args) {
```
Comment (DHowett) [inline src/cascadia/WindowsTerminal/AppHost.cpp]: i didn't notice this sneak in. gosh!

**Comment by carlos-zamora** [comment]
Huh, I guess the bot's broken today. Merging!
