### PR TITLE
Filter out control characters that don't do anything

### LINKED ISSUE #10786: Terminal shows SOH and STX characters in Ruby's `pry` for some reason
### Windows Terminal version (or Windows build number)

Terminal 1.8.1521.0, Windows 10.0.19043.0

### Other Software

WSL2, running Manjaro Linux: https://github.com/sileshn/ManjaroWSL
Using Zsh and oh-my-zsh (but reproduced with Bash)
Fira Code Retina font (but run into this with other fonts)

```
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]
```

```
Pry version 0.14.1 on Ruby 3.0.2
```

### Steps to reproduce

With everything installed properly (`pry` in `$PATH`):

```sh
➜  ~  pry
[1] pry(main)> ls Module
```

### Expected Behavior

No special characters or control codes should be shown:

```ruby
[1] pry(main)> ls Module
Module.methods: constants  nesting  used_modules
Module#methods:
  <              attr_writer              const_set              method_defined?             protected_method_defined?
  <=             autoload                 const_source_location  module_eval                 public_class_method
  <=>            autoload?                constants              module_exec                 public_constant
  ==             class_eval               define_method          name                        public_instance_method
  ===            class_exec               deprecate_constant     prepend                     public_instance_methods
  >              class_variable_defined?  freeze                 pretty_print                public_method_defined?
  >=             class_variable_get       include                pretty_print_cycle          remove_class_variable
  alias_method   class_variable_set       include?               private_class_method        remove_method
  ancestors      class_variables          included_modules       private_constant            singleton_class?
  attr           const_defined?           inspect                private_instance_methods    to_s
  attr_accessor  const_get                instance_method        private_method_defined?     undef_method
  attr_reader    const_missing            instance_methods       protected_instance_methods
[2] pry(main)>
```

### Actual Behavior

For some reason, special characters/control codes are being shown:

image

```ruby
[1] pry(main)> ls Module
Module.methods: constants  nesting  used_modules
Module#methods:
  <              attr_writer              const_set              method_defined?             protected_method_defined?
  <=             autoload                 const_source_location  module_eval                 public_class_method
  <=>            autoload?                constants              module_exec                 public_constant
  ==             class_eval               define_method          name                        public_instance_method
  ===            class_exec               deprecate_constant     prepend                     public_instance_methods
  >              class_variable_defined?  freeze                 pretty_print                public_method_defined?
  >=             class_variable_get       include                pretty_print_cycle          remove_class_variable
  alias_method   class_variable_set       include?               private_class_method        remove_method
  ancestors      class_variables          included_modules       private_constant            singleton_class?
  attr           const_defined?           inspect                private_instance_methods    to_s
  attr_accessor  const_get                instance_method        private_method_defined?     undef_method
  attr_reader    const_missing            instance_methods       protected_instance_methods
[2] pry(main)>
```

### PR DESCRIPTION
**Pull request by j4james**
On a real VT terminal, most of the control characters that don't do
anything are supposed to be filtered out, and not written to the buffer.
Up to to now, though, we've only been filtering out `NUL`. This PR
extends our control processing to filter the remaining characters that
aren't supposed to be displayed.

We introduced filtering for the `NUL` control in PR #3015.

The are two special cases worth mentioning.

1. The `SUB` control's main purpose is to the cancel a control sequence
that is in progress, but it also needs to output an error character (a
reverse question mark) to the display.

2. The `DEL` control is typically filtered out, but when a 96-character
set is designated, it can sometimes be mapped to a printable glyph that
needs to be displayed.

## Validation Steps Performed

I've manually tested that all the controls that are meant to be filtered
out are no longer being displayed.

I've also extended the existing `NUL` unit test to cover the full set of
controls characters that are supposed to be filtered.

Closes #10786

### CODE REVIEW

**Review by carlos-zamora — APPROVED** [review]

File: src/terminal/parser/OutputStateMachineEngine.cpp [hunk 1]
```diff
@@ -79,9 +79,23 @@ bool OutputStateMachineEngine::ActionExecute(const wchar_t wch)
...
+    case AsciiChars::SUB:
+        // The SUB control is used to cancel a control sequence in the same
+        // way as CAN, but unlike CAN it also displays an error character,
+        // typically a reverse question mark.
+        _dispatch->Print(L'\u2E2E');
+        break;
+    case AsciiChars::DEL:
+        // The DEL control can sometimes be translated into a printable glyph
+        // if a 96-character set is designated, so we need to pass it through
+        // to the Print method. If not translated, it will filtered out there.
```
Comment (DHowett) [inline src/terminal/parser/OutputStateMachineEngine.cpp:91]:
```suggestion
        // to the Print method. If not translated, it will be filtered out
        // there.
```

I wrapped it because under-filling was preferable to breaking the perfect right column symmetry of the comment by going wider... :)

**Review by DHowett — APPROVED** [review]

**Comment by DHowett** [comment]
Want to make sure @zadjii-msft signs as well, since VT was once his wheelhouse

**Review by zadjii-msft — APPROVED** [review]
