### PR TITLE
Filter focus events that came from the API

### LINKED ISSUE #13238: `[O` erroneously inputted after exiting from Neovim 0.7.0 in latest Terminal Preview
### Windows Terminal version

1.14.1451.0

### Windows build number

10.0.19044.1706

### Other Software

Neovim 0.7.0 (https://github.com/neovim/neovim/releases/tag/v0.7.0)

### Steps to reproduce

1. Install Neovim
2. Open it by running `nvim` in your shell (works both in `cmd` and `pwsh`)
3. exit it (`:q`)

### Expected Behavior

Neovim exits, nothing else happens.

### Actual Behavior

Neovim exits, and the shell receives `[O` on its console input.

image

My guess would be that the characters are part of a response to some VT escape code from Neovim, but for some reason they get written separately and the shell gets them instead of Neovim.

### PR DESCRIPTION
**Pull request by zadjii-msft**
As described in #13238. libuv sends a focus event to jiggle the handle. Now that we support focus events as VT input (#12900), we'd translate those focus events to VT input as well. That combination of things caused exiting neovim to emit a `\x1b[O` to the input line of the shell when exited. 

To fix this, we're going to secretly filter out any focus events that came from the API, before translating to VT. We're fortunate here, the `FOCUS_EVENT_RECORD` version of the ctor is only called by the API. 

* [x] Closes #13238

### CODE REVIEW

**Comment by zadjii-msft** [comment]
Big s/o to @j4james for coming up with this one.

File: src/terminal/input/terminalInput.cpp [hunk 1]
```diff
@@ -527,6 +527,12 @@ bool TerminalInput::HandleKey(const IInputEvent* const pInEvent)
     if (pInEvent->EventType() == InputEventType::FocusEvent)
     {
         const auto& focusEvent = *static_cast<const FocusEvent* const>(pInEvent);
+
+        // BODGY
+        // GH#13238 - Filter out focus events that came from the API.
+        if (focusEvent.CameFromApi())
+            return true;
```
Comment (j4james) [inline src/terminal/input/terminalInput.cpp:534]: I think policy dictates that this needs to have braces.

**Review by j4james — APPROVED** [review]

File: src/types/inc/IInputEvent.hpp [hunk 2]
```diff
@@ -514,12 +514,14 @@ class FocusEvent : public IInputEvent
 {
 public:
     constexpr FocusEvent(const FOCUS_EVENT_RECORD& record) :
-        _focus{ !!record.bSetFocus }
```
Comment (DHowett) [inline src/types/inc/IInputEvent.hpp:517]: and we're certain that nobody else uses this ctor?

**Review by DHowett — APPROVED** [review]

**Comment by DHowett** [comment]
It turns out the unit tests use that ctor to inject focus events ;) and then make sure focus VT comes out

```
Error: Verify: AreEqual(false, pInput->HandleKey(inputEvent.get())): Verify FOCUS_EVENT was NOT handled. - Values (0, 1) [File: C:\a\_work\1\s\src\terminal\adapter\ut_adapter\inputTest.cpp, Function: Microsoft::Console::VirtualTerminal::InputTest::TerminalInputTests, Line: 306]
```

File: src/types/inc/IInputEvent.hpp (hunk 2 above)
Comment (j4james) [reply src/types/inc/IInputEvent.hpp:517]: Other than `WriteConsoleInputAImpl` and `WriteConsoleInputWImpl`, it's potentially used in a few places in the `InputBuffer` class when moving `IInputEvent` records around (calling `IInputEvent::Create` on the result of a `ToInputRecord` call). I don't think those are likely to be a problem though.

`IInputEvent::Create` is also called in a couple of places in `InputStateMachineEngine`, but those are exclusively for keyboard and mouse events as far as I can see.

I think the rest are all in tests, which I didn't bother looking at, but I see now they've resulted in some test failures. Hopefully those are just tests that need to be updated, though, and not an indication that there's something fundamentally wrong with this approach.

**Comment by j4james** [comment]
> It turns out the unit tests use that ctor to inject focus events ;) and then make sure focus VT comes out

I think that particular test is just checking whether `HandleKey` returns false for focus events, which we could "fix" by changing the return value here:
https://github.com/microsoft/terminal/blob/cbdbdbb9bf948a556462928e8e44a468cb1780fb/src/terminal/input/terminalInput.cpp#L533-L536

Semantically I'm not actually sure what the correct return should be though. Prior to this PR it would have depended on whether mouse focus mode was enabled or not, so maybe false would be more appropriate given we're not generating the focus reports in this case. I'm curious what the implications are for any `HandleKey` callers though.

File: src/types/inc/IInputEvent.hpp [hunk 3]
```diff
@@ -539,8 +541,15 @@ class FocusEvent : public IInputEvent
...
 
+    // BODGY - see FocusEvent.cpp for details.
+    constexpr bool CameFromApi() const noexcept
+    {
+        return _cameFromApi;
+    }
+
 private:
     bool _focus;
+    const bool _cameFromApi;
```
Comment (lhecker) [inline src/types/inc/IInputEvent.hpp:552]: Generally, don't use `const`. It prevents `std::move` and other kinds of language/compiler features, because C++ is weird.

Comment (zadjii-msft) [reply src/types/inc/IInputEvent.hpp:552]: > It prevents `std::move` and other kinds of language/compiler features

TIL, thanks

File: src/terminal/adapter/ut_adapter/inputTest.cpp [hunk 4]
```diff
@@ -300,10 +301,62 @@ void InputTest::TerminalInputTests()
     inputEvent = IInputEvent::Create(irUnhandled);
     VERIFY_ARE_EQUAL(false, pInput->HandleKey(inputEvent.get()), L"Verify MENU_EVENT was NOT handled.");
 
-    Log::Comment(L"Testing FOCUS_EVENT");
-    irUnhandled.EventType = FOCUS_EVENT;
-    inputEvent = IInputEvent::Create(irUnhandled);
-    VERIFY_ARE_EQUAL(false, pInput->HandleKey(inputEvent.get()), L"Verify FOCUS_EVENT was NOT handled.");
+    Log::Comment(L"Testing FOCUS_EVENTs is handled by TestFocusEvents");
```
Comment (DHowett) [inline src/terminal/adapter/ut_adapter/inputTest.cpp:304]: This seems more like noise than signal -- it'll print up in every test run, _moments before TestFocusEvents runs_

**Review by lhecker — APPROVED** [review]

**Review by DHowett — APPROVED** [review]
