### PR TITLE
Disable acrylic material (temporarily) when opacity is set to 100%

### LINKED ISSUE #12880: Ctrl+Shift+Scrollwheel can no longer fully disable transparency when using Acrylic
### Windows Terminal version

1.12.10733.0

### Windows build number

10.0.22000.593

### Other Software

_No response_

### Steps to reproduce

"useAcrylic": true
"opacity": 100 / "acrylicOpacity": 1.0

### Expected Behavior

Terminal window with fully opaque, solid color background

### Actual Behavior

image

Terminal window still presents minor Acrylic effect, 
thus making switch between Acrylic% and Opaque with C+S+Wheel impossible.

### PR DESCRIPTION
**Pull request by JerBast**
If the opacity is set to 100%, the background becomes solid instead of 'fully opaque acrylic'. If the opacity is below 100% the acrylic material is re-enabled (depending on the user's settings).

## Validation Steps Performed

I updated two unit tests to reflect the change in behavior and manually tested the transition from <100% opacity to 100% opacity (and vice versa) on win11.

Steps:
1. Start with 100% opacity and acrylic material enabled.
2. Decrease opacity and observe acrylic effect.
3. Increase opacity back to 100% and disable the acrylic effect.
4. Decrease opacity and notice that acrylic effect is no longer there.

Closes #12880

### CODE REVIEW

File: src/cascadia/TerminalControl/ControlCore.cpp [hunk 1]
```diff
@@ -584,10 +584,7 @@ namespace winrt::Microsoft::Terminal::Control::implementation
         // Windows 10.
         // We'll also turn the acrylic back off when they're fully opaque, which
         // is what the Terminal did prior to 1.12.
-        if (!IsVintageOpacityAvailable())
-        {
-            _runtimeUseAcrylic = newOpacity < 1.0;
-        }
+        UseAcrylic(opacity < 1.0 && (!IsVintageOpacityAvailable() || _settings->UseAcrylic()));
```
Comment (lhecker) [inline src/cascadia/TerminalControl/ControlCore.cpp:587]: I'm not quite familiar with this code... Is the change from `_runtimeUseAcrylic` to `UseAcrylic()` correct?

Comment (JerBast) [reply src/cascadia/TerminalControl/ControlCore.cpp:587]: `UseAcrylic(...)` also updates the value of `_runtimeUseAcrylic`. I only changed it to be consistent with the way the opacity is updated a few lines above. Both are defined in a similar fashion.

https://github.com/microsoft/terminal/blob/e4b80e2ef33834a56f3c93582d0b87016aeb1bea/src/cascadia/TerminalControl/ControlCore.h#L35-L38
https://github.com/microsoft/terminal/blob/e4b80e2ef33834a56f3c93582d0b87016aeb1bea/src/cascadia/TerminalControl/ControlCore.h#L209

**Review by carlos-zamora — APPROVED** [review]
Looks good to me. Thanks!

**Comment by carlos-zamora** [comment]
## Extracted from commit message

screen_recording_terminal

(Apologies for the poor quality of the gif...)

File: src/cascadia/TerminalControl/ControlCore.cpp [hunk 2]
```diff
@@ -584,10 +584,7 @@ namespace winrt::Microsoft::Terminal::Control::implementation
         // Windows 10.
         // We'll also turn the acrylic back off when they're fully opaque, which
         // is what the Terminal did prior to 1.12.
-        if (!IsVintageOpacityAvailable())
-        {
-            _runtimeUseAcrylic = newOpacity < 1.0;
-        }
+        UseAcrylic(newOpacity < 1.0 && (!IsVintageOpacityAvailable() || _settings->UseAcrylic()));
```
Comment (DHowett) [inline src/cascadia/TerminalControl/ControlCore.cpp:587]: Worried about this one instance of calling `UseAcrylic()` where below we directly-set `_runtimeUseAcrylic`. Should we decide on one or the other?

Comment (DHowett) [reply src/cascadia/TerminalControl/ControlCore.cpp:587]: Also, we will want to change the implementation of `_isBackgroundTransparent` to account for this, right?

**Review by DHowett — CHANGES_REQUESTED** [review]
(Noted)

File: src/cascadia/TerminalControl/ControlCore.cpp (hunk 2 above)
Comment (DHowett) [reply src/cascadia/TerminalControl/ControlCore.cpp:587]: Unless, changing this here feeds into `_isBackgroundTransparent` correctly. But then, why does `_isBackgroundTransparent` check `Opacity` on its own? I'm confused.

Comment (JerBast) [reply src/cascadia/TerminalControl/ControlCore.cpp:587]: > Unless, changing this here feeds into `_isBackgroundTransparent` correctly.

Yes, this does seem to be the case because `_runtimeUseAcrylic` is updated (with the new constraints) before `_isBackgroundTransparent` is called on [L715](https://github.com/microsoft/terminal/blob/a0b526ef112fc2e1f5dfda0a432d1b1f8f62bcc4/src/cascadia/TerminalControl/ControlCore.cpp#L715). This was not something that I took into account when I created this PR, and I fully agree that it should be modified to take the new constraints into account. This amounts to removing `UseAcrylic` from the expression.

> But then, why does `_isBackgroundTransparent` check `Opacity` on its own? I'm confused.

I suppose the `Opactity` was checked on its own to account for the regular transparent background on win11.

**Review by DHowett — APPROVED** [review]
thanks so much!
