### PR TITLE
Prevent the virtual viewport bottom being updated incorrectly

### LINKED ISSUE #9754: The virtual viewport bottom is not maintained correctly
### Windows Terminal version (or Windows build number)

10.0.18363.1379, 7f5a19b627037353fc988755ed25e6ecb5bf4675

### Other Software

_No response_

### Steps to reproduce

1. Start a bash shell in conhost.
2. Open the Properties page, and enable the _Disable Scroll-Forward_ option on the _Terminal_ tab.
3. Generate some output to get a few pages of content in the backscroll buffer.
4. Execute `printf "\e[H"` to move the cursor to the top of the current page.
5. Scroll back to the top of the buffer so the cursor is now out of view.
6. Type a printable character

### Expected Behavior

All of the buffer contents should be preserved.

### Actual Behavior

The line that the cursor was on becomes the bottom of the buffer, and everything below that point is truncated. Technically the data is still there - if you press enter a few times, it'll start scrolling into view. The problem is that the virtual viewport bottom is incorrectly set, so with _Scroll-Forward_ disabled, everything below that point is hidden.

There are a number of ways this bug can be triggered - even just resizing the window can do it - but the above described method is probably the easiest to reproduce consistently. Anything that calls `SCREEN_INFORMATION::UpdateBottom` can potentially trigger it, and there are a quite a few code paths leading to that.

### PR DESCRIPTION
**Pull request by j4james**
The "virtual bottom" marks the last line of the mutable viewport area,
which is the part of the buffer that VT sequences can write to. This
region should typically only move downwards as new lines are added to
the buffer, but there were a number of cases where it was incorrectly
being moved up, or moved down further than necessary. This PR attempts
to fix that.

There was an earlier, unsuccessful attempt to fix this in PR #9770 which
was later reverted (issue #9872 was the reason it had to be reverted).
PRs #2666, #2705, and #5317 were fixes for related virtual viewport
problems, some of which have either been extended or superseded by this
PR.

`SetConsoleCursorPositionImpl` is one of the cases that actually does
need to move the virtual viewport upwards sometimes, in particular when
the cmd shell resets the buffer with a `CLS` command. But when this
operation "snaps" the viewport to the location of the cursor, it needs
to use the virtual viewport as the frame of reference. This was
partially addressed by PR #2705, but that only applied in
terminal-scrolling mode, so I've now applied that fix regardless of the
mode.

`SetViewportOrigin` takes a flag which determines whether it will also
move the virtual bottom to match the visible viewport. In some case this
is appropriate (`SetConsoleCursorPositionImpl` being one example), but
in other cases (e.g. when panning the viewport downwards in the
`AdjustCursorPosition` function), it should only be allowed to move
downwards. We can't just not set the update flag in those cases, because
that also determines whether or not the viewport would be clamped, and
we don't want change that. So what I've done is limit
`SetViewportOrigin` to only move the virtual bottom downwards, and added
an explicit `UpdateBottom` call in those places that may also require
upward movement.

`ResizeWindow` in the `ConhostInternalGetSet` class has a similar
problem to `SetConsoleCursorPositionImpl`, in that it's updating the
viewport to account for the new size, but if that visible viewport is
scrolled back or forward, it would end up placing the virtual viewport
in the wrong place. So again the solution here was to use the virtual
viewport as the frame of reference for the position. However, if the
viewport is being shrunk, this can still result in the cursor falling
below the bottom, so we need an additional check to adjust for that.
This can't be applied in pty mode, though, because that would break the
conpty resizing operation.

`_InternalSetViewportSize` comes into play when resizing the window
manually, and again the viewport after the resize can end up truncating
the virtual bottom if not handled correctly. This was partially
addressed in the original code by clamping the new viewport above the
virtual bottom under certain conditions, and only in terminal scrolling
mode. I've replaced that with a new algorithm which links the virtual
bottom to the visible viewport bottom if the two intersect, but
otherwise leaves it unchanged. This applies regardless of the scrolling
mode.

`ResizeWithReflow` is another sizing operation that can affect the
virtual bottom. This occurs when a change of the window width requires
the buffer to be reflowed, and we need to reposition the viewport in the
newly generated buffer. Previously we were just setting the virtual
bottom to align with the new visible viewport, but that could easily
result in the buffer truncation if the visible viewport was scrolled
back at the time. We now set the virtual bottom to the last non-space
row, or the cursor row (whichever is larger). There'll be edge cases
where this is probably not ideal, but it should still work reasonably
well.

`MakeCursorVisible` was another case where the virtual bottom was being
updated (when requested with a flag) via a `SetViewportOrigin` call.
When I checked all the places it was used, though, none of them actually
required that behavior, and doing so could result in the virtual bottom
being incorrectly positioned, even after `SetViewportOrigin` was limited
to moving the virtual bottom downwards. So I've now made it so that
`MakeCursorVisible` never updates the virtual bottom.

`SelectAll` in the `Selection` class was a similar case. It was calling
`SetViewportOrigin` with the `updateBottom` flag set when that really
wasn't necessary and could result in the virtual bottom being
incorrectly set. I've changed the flag to false now.

## Validation Steps Performed

I've manually confirmed that the test cases in issue #9754 are working
now, except for the one involving margins, which is bigger problem with
`AdjustCursorPosition` which will need to be addressed separately.

I've also double checked the test cases from several other virtual
bottom issues (#1206, #1222, #5302, and #9872), and confirmed that
they're still working correctly with these changes.

And I've added a few screen buffer tests in which I've tried to cover as
many of the problematic code paths as possible.

Closes #9754

### CODE REVIEW

**Comment by j4james** [comment]
I know these fixes are a bit hacky, and it feels like we're just papering over the cracks, but this is the best I could come up for now. I'm a little concerned that the changes in PR #12703 might expose these virtual buffer problems more frequently (since we're no longer calling `MoveToBottom` all the time), so I thought it might be a good idea to try and get this resolved sooner rather than later.

File: src/host/screenInfo.cpp [hunk 1]
```diff
@@ -1239,23 +1242,21 @@ void SCREEN_INFORMATION::_InternalSetViewportSize(const COORD* const pcoordSize,
...
-    if (gci.IsTerminalScrolling() && newViewport.Height() >= _viewport.Height())
+    // In general we want to avoid moving the virtual bottom unless it's aligned with
+    // the visible viewport, so we check whether the changes we're making would cause
+    // the bottom of the visible viewport to intersect the virtual bottom at any point.
+    // If so, we update the virtual bottom to match. We also update the virtual bottom
+    // if it's less than the new viewport height minus 1, because that would otherwise
+    // leave the virtual viewport extended past the top of the buffer.
+    const auto newViewport = Viewport::FromInclusive(srNewViewport);
+    if ((_virtualBottom >= _viewport.BottomInclusive() && _virtualBottom < newViewport.BottomInclusive()) ||
+        (_virtualBottom <= _viewport.BottomInclusive() && _virtualBottom > newViewport.BottomInclusive()) ||
```
Comment (lhecker) [inline src/host/screenInfo.cpp:1253]: I had a bit trouble understanding this visually until I realized that it basically moves the virtual bottom if the viewport changed the side it is relative to the virtual bottom. In other words: If the viewport used to be above the virtual bottom and is now below, then the virtual bottom is moved and vice versa.

In order to understand this I expressed the boolean condition in an equivalent "numeric" expression. These two lines are equivalent to:
```cpp
const auto delta1 = _virtualBottom - _viewport.BottomInclusive();
const auto delta2 = _virtualBottom - newViewport.BottomInclusive();
// Notes:
// * `delta2 != 0` is required because _virtualBottom and newViewport.BottomInclusive()
//   are only ever compared via < and >
// * `delta1 == 0` is required because _virtualBottom and _viewport.BottomInclusive()
//    are also implicitly compared for == (due to >= / <=)
// * (a ^ b) < 0 is true if a/b have opposing sign bits
delta2 != 0 && (delta1 == 0 || (delta1 ^ delta2) < 0);
```

It seems it doesn't matter whether we check for `delta2 == 0`, because if it is 0, then `_virtualBottom == srNewViewport.Bottom` and the line below won't change anything. This is why we can also write:
```cpp
const auto delta1 = _virtualBottom - _viewport.BottomInclusive();
const auto delta2 = _virtualBottom - newViewport.BottomInclusive();
delta1 == 0 || (delta1 ^ delta2) < 0;
```

With this expression in place I found it easier to understand that the virtual bottom moves if either:
* the virtual bottom is currently following the viewport along (`delta1 == 0`) 
* the new viewport has changed direction and is now on the other side
  relative to the virtual bottom (`(delta1 ^ delta2) < 0`)

**Review by lhecker — APPROVED** [review]

File: src/host/screenInfo.cpp [hunk 2]
```diff
@@ -1462,12 +1464,17 @@ bool SCREEN_INFORMATION::IsMaximizedY() const
 
     if (SUCCEEDED(hr))
     {
-        auto& newCursor = newTextBuffer->GetCursor();
+        // Make sure the new virtual bottom is far enough down to include both
+        // the cursor row and the last non-space row.
+        const auto cursorRow = newTextBuffer->GetCursor().GetPosition().Y;
+        const auto lastNonSpaceRow = newTextBuffer->GetLastNonSpaceCharacter().Y;
```
[the remark this answers is not in the document]
Comment (j4james) [reply src/host/screenInfo.cpp:1470]: Yeah. I would have thought the `TextBuffer::Reflow` should have been able to provide that information for us, since it's just created that new buffer. But then that made me ask why the `TextBuffer` isn't tracking the virtual bottom in general? And why we've rewritten essentially the same resizing code in the `Terminal` class but in a completely different way? (Although it's worth noting that the `Terminal` implementation also uses `GetLastNonSpaceCharacter`.) And my conclusion was that all of this buffer management code really needs a unified rewrite, but that was way more effort than I wanted to get into now, if ever. Hence the quick fix hack.

File: src/host/screenInfo.cpp (hunk 1 above)
Comment (j4james) [reply src/host/screenInfo.cpp:1253]: > I had a bit trouble understanding this visually until I realized that it basically moves the virtual bottom if the viewport changed the side it is relative to the virtual bottom. In other words: If the viewport used to be above the virtual bottom and is now below, then the virtual bottom is moved and vice versa.

The code as written is almost an exact reproduction of your final sentence. I don't get how you can find that difficult to understand? It's essentially self-documenting.

Whereas this looks to me like the winning entry in a code-obfuscation contest!

    delta1 == 0 || (delta1 ^ delta2) < 0;

If you were suggesting that as a performance improvement, I'd get it. But I can't fathom how you see that as easier to understand? Our minds clearly work in completely different ways. But if someone else chimes in here agreeing with you, I'm happy to be overruled.

Although I should also ask, how sure are you about the portability of that code? Is it really safe to XOR negative numbers like that?

Comment (lhecker) [reply src/host/screenInfo.cpp:1253]: > The code as written is almost an exact reproduction of your final sentence.

No, not as I perceive it. You wrote:
> [...] we check whether the changes we're making would cause the bottom of the visible viewport to intersect the virtual bottom at any point.

So I was wondering, how would you know that the visible viewport is intersecting the virtual bottom by just comparing `BottomInclusive()` but not `Top()`? Because your code is disagreeing with your comment: It's not intersecting a rectangle ("viewport") with a line. It's comparing the position of 2 lines (old and new viewport bottom) relative to 1 "point of reference" line (the current `_virtualBottom`). The condition is true if the 2 lines are on opposing sides of the reference.

> But I can't fathom how you see that as easier to understand? Our minds clearly work in completely different ways.

I'm sorry. 😥
I think I could properly explain it in person, but I'll try it via text anyways.

I read your explanation and then the first half of the first line of your if condition - `_virtualBottom >= _viewport.BottomInclusive()`. Afterwards I tried to join that with the second half `_virtualBottom < newViewport.BottomInclusive()` and I had about this image in my mind:
12972_viewport

I mean clearly the bottom of the `newViewport` must be below the `_virtualBottom`, but where? What does it mean to the terminal if a viewport's bottom "intersects" a line? And most importantly: What happens if the `_viewport` is below the `_virtualBottom`?

In either case I guess what I'm trying to say is that it took me a bit to grok that the code is basically just:
```
   (oldViewport <= virtualBottom < newViewport)
|| (oldViewport >= virtualBottom > newViewport)
```
...but the `<` and `<=` sides are flipped in your code.

In human terms one could say: "Jiggle the virtual bottom around as long as it's in between the bottoms of the old and new viewport."

And I find this "in between old and new" just as easy to reason about if one were to write `differentSignBit(ref - new, ref - old)` or equivalent `(ref < new) != (ref < old)` (which btw also works for your if condition). The `differentSignBit` thing makes sense to me, because the difference `ref - new` and `ref - old` are only ever negative if the new/old value is smaller than the reference point. Since we want them on opposing sides, we're basically asking them to have different signs. I... I just like that. 😥

But even at this point there was one "aha" realization left about why the `newViewport` is compared with `<` and the old one with `<=`. Of course it was easy to see then that this distinction doesn't matter, because they lead to the same outcome.

Basically, to finish my ramblings and leave it at something useful... This is the same code, but all comparison signs are the same and point in the same direction:
```cpp
if ((_viewport.BottomInclusive() <= _virtualBottom && _virtualBottom <= newViewport.BottomInclusive()) ||
    (newViewport.BottomInclusive() <= _virtualBottom && _virtualBottom <= _viewport.BottomInclusive()) ||
```

And now we _could_ abstract that as:
```cpp
static constexpr auto isBetween = [](auto lo, auto mid, auto hi) {
    return (lo <= mid) && (mid <= hi);
}

if (isBetween(_viewport.BottomInclusive(), _virtualBottom, newViewport.BottomInclusive()) ||
    isBetween(newViewport.BottomInclusive(), _virtualBottom, _viewport.BottomInclusive()) ||
```

> Although I should also ask, how sure are you about the portability of that code? Is it really safe to XOR negative numbers like that?

Yeah, I'm fairly certain. Bitwise operations on signed integers are defined to operate on their bitwise representation and since both integers are of the same type, the (undefined) position of their sign bits are the same, making this operation well defined.
But this doesn't matter as much anymore, because C++20 requires signed integers to use two's complement without padding bits. 🙂

Comment (j4james) [reply src/host/screenInfo.cpp:1253]: > So I was wondering, how would you know that the visible viewport is intersecting the virtual bottom by just comparing `BottomInclusive()` but not `Top()`?

You missed part of the comment - I said "the _bottom_ of the visible viewport". The top of the viewport is not relevant at all.

> But even at this point there was one "aha" realization left about why the `newViewport` is compared with `<` and the old one with `<=`. Of course it was easy to see then that this distinction doesn't matter, because they lead to the same outcome.

OK, I can see how that might be confusing, and I'd be happy to make both include the `=` if that's clearer. If it's already equal to the new viewport bottom it's essentially a noop, but that doesn't really matter.

> Basically, to finish my ramblings and leave it at something useful... This is the same code, but all comparison signs are the same and point in the same direction:
> 
> ```c++
> if ((_viewport.BottomInclusive() <= _virtualBottom && _virtualBottom <= newViewport.BottomInclusive()) ||
>     (newViewport.BottomInclusive() <= _virtualBottom && _virtualBottom <= _viewport.BottomInclusive()) |
> ```

I did consider ordering it that way, but in the end I thought it might be clearer to align it with how it was described in the comments. I don't think it makes much difference either way, though, so again I'd be happy to make that change, if that's what you're proposing.

What I don't get is how you reached that point, and then decided it would be even easier to understand if you rewrote everything with a bitwise XOR operator.

> C++20 requires signed integers to use two's complement without padding bits.

That's nice to know. I never would expected that.

Comment (lhecker) [reply src/host/screenInfo.cpp:1253]: > What I don't get is how you reached that point, and then decided it would be even easier to understand if you rewrote everything with a bitwise XOR operator.

You know, I think I got it the first time.
I'll make sure to not comment something like that again.

Comment (j4james) [reply src/host/screenInfo.cpp:1253]: Sorry, I didn't meant to be overly critical of that suggestion. I'm just trying to figure out what exactly I should be changing this code to so it's understandable for everyone. In short, would you be happy with the reordered condition with all the comparisons the same?

**Review by raghavthind2005 — APPROVED** [review]

**Comment by DHowett** [comment]
@msftbot make sure @zadjii-msft signs off

File: src/host/screenInfo.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (zadjii-msft) [reply src/host/screenInfo.cpp:1470]: That's mostly on me. SCREEN_INFO is pretty tightly bound to the rest of the _console_ itself. It was a lot harder to separate out from... everything else that makes the console _the console_. I was trying to create a version with a cleaner interface in `Terminal`.

In retrospect, yes, a unified implementation would have been smart. I think I would have liked to create a cleaner boundary around SCREEN_INFO so that terminal could have reused it too.

**Review by zadjii-msft — APPROVED** [review]

File: src/host/screenInfo.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (j4james) [reply src/host/screenInfo.cpp:1470]: Yeah, I realise it won't be easy decoupling that code from the console, but I think it'll be worth revisiting at some point, possibly when/if we get around to implementing VT paging. Because ideally I'd like for us to have a unified buffer management class that can handle both the console buffers and the VT pages in the same way (along with XTerm's alt/main weirdness). And that class could hopefully then be shared between conhost and Terminal and reduce some of the duplication. But it's not urgent.
