### PR TITLE
Accounting padding when calculating the initial window size

### LINKED ISSUE #1143: initialCols (and initialRows) have an off-by-padding error
# Environment

```
Windows build number: 10.0.18908.1000
Windows Terminal version (if applicable): 880272c7483a3bb6893dbec3725d0eb7375ab78a
```

# Steps to reproduce

0. Set `initialCols` to `16`
0. Launch a new Terminal
0. `echo 0123456789abcdef`

# Expected behavior

`echo`'s output oughtta fit in one line

# Actual behavior

```
0123456789abcde
f
```

### PR DESCRIPTION
**Pull request by Summon528**
## Summary of the Pull Request
Accounting padding when calculating the initial window size

 
## PR Checklist
* [x] Closes #1143
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Requires documentation to be updated
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Validation Steps Performed
Set `"padding": "100"` and observe the window becomes larger
Set `"padding": "100, 200"` and observe the window becomes larger
Set `"padding": "50, 100, 150, 200"` and observe the window becomes larger

### CODE REVIEW

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 1]
```diff
@@ -1274,36 +1274,56 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
...
     //      Single Double value provides uniform padding
     //      Two Double values provide isometric horizontal & vertical padding
     //      Four Double values provide independent padding for 4 sides of the bounding rectangle
     // Return Value:
-    // - Windows::UI::Xaml::Thickness object
-    Windows::UI::Xaml::Thickness TermControl::_ParseThicknessFromPadding(const hstring padding)
+    // - A std::vector object
+    // - If parsed successfully the vector will have the same size as the number of padding values.
+    // - If parsing failed the vector will be empty.
+    std::vector<double> TermControl::_ParsePadding(const hstring padding)
```
Comment (Summon528) [inline src/cascadia/TerminalControl/TermControl.cpp]: This function probably does not belong in this file but I don't know where should I put it.

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 2]
```diff
@@ -1274,36 +1274,56 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
...
     {
         const wchar_t singleCharDelim = L',';
         std::wstringstream tokenStream(padding.c_str());
         std::wstring token;
-        uint8_t paddingPropIndex = 0;
-        std::array<double, 4> thicknessArr = {};
+        std::vector<double> paddingArr = {};
```
Comment (dlong11) [inline src/cascadia/TerminalControl/TermControl.cpp]: nit: paddingArr  - unnecessary initialization.

File: src/cascadia/TerminalControl/TermControl.h [hunk 3]
```diff
@@ -123,7 +123,8 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
         void _MouseTransparencyHandler(const double delta);
 
         void _ScrollbarUpdater(Windows::UI::Xaml::Controls::Primitives::ScrollBar scrollbar, const int viewTop, const int viewHeight, const int bufferSize);
-        Windows::UI::Xaml::Thickness _ParseThicknessFromPadding(const hstring padding);
+        static std::vector<double> _ParsePadding(const hstring padding);
+        static Windows::UI::Xaml::Thickness _ParseThicknessFromPadding(const hstring padding);
```
Comment (dlong11) [inline src/cascadia/TerminalControl/TermControl.h]: Can the newly added methods be const?

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 4]
```diff
@@ -1314,27 +1334,44 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
...
         {
-            for (; std::getline(tokenStream, token, singleCharDelim) && (paddingPropIndex < thicknessArr.size()); paddingPropIndex++)
+            for (uint8_t paddingPropIndex = 0; std::getline(tokenStream, token, singleCharDelim) && (paddingPropIndex < 4); paddingPropIndex++)
             {
                 // std::stod internall calls wcstod which handles whitespace prefix (which is ignored)
                 //  & stops the scan when first char outside the range of radix is encountered
                 // We'll be permissive till the extent that stod function allows us to be by default
                 // Ex. a value like 100.3#535w2 will be read as 100.3, but ;df25 will fail
-                thicknessArr[paddingPropIndex] = std::stod(token, idx);
+                paddingArr.push_back(std::stod(token, idx));
```
Comment (dlong11) [inline src/cascadia/TerminalControl/TermControl.cpp]: nit: idx is not used or needed here.  Consider removing this since we are modifying the code?

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 5]
```diff
@@ -1274,36 +1274,56 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
...
+            // No case for 3 padding values, since it's not a norm to provide just Left, Top & Right padding values leaving out Bottom
+            case 4:
+                width += paddingArr[0] + paddingArr[2];
+                height += paddingArr[1] + paddingArr[3];
+                break;
+            default:
+                break;
+        }
+        
+        return { static_cast<float>(width), static_cast<float>(height) };
```
Comment (dlong11) [inline src/cascadia/TerminalControl/TermControl.cpp]: nit: gsl::narrow is the preferred cast here.

File: src/cascadia/TerminalControl/TermControl.h (hunk 3 above)
Comment (dlong11) [reply src/cascadia/TerminalControl/TermControl.h]: Totally missed the static declaration.  🤦‍♂  I am not sure what the "teams" guidance is here.  Should these be const member functions, static member functions or static helpers in the cpp file?  @zadjii-msft

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 5 above)
Comment (Summon528) [reply src/cascadia/TerminalControl/TermControl.cpp]: Is `gsl::narrow` preferred? From my understanding and testing, `gsl::narrow` will throw if I set padding to something like 0.3 due to some floating point precision issue.

File: src/cascadia/TerminalControl/TermControl.h (hunk 3 above)
Comment (Summon528) [reply src/cascadia/TerminalControl/TermControl.h]: I had to change this to `static` because `GetProposedDimensions()` is static

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 5 above)
Comment (Summon528) [reply src/cascadia/TerminalControl/TermControl.cpp]: However, I should've use `gsl::narrow_cast` right?

Comment (dlong11) [reply src/cascadia/TerminalControl/TermControl.cpp]: gsl::narrow_cast is better than static_cast in my opinion. (I'm not sure that is a requirement or not though by the team)  With that said it looks like the original author went to a lot of trouble to use float math here.   I am not sure if that was on purpose or not.  @zadjii-msft might have an opinion on this.

Comment (zadjii-msft) [reply src/cascadia/TerminalControl/TermControl.cpp]: I'm not sure I actually have an opinion here - if `gsl::narrow` will throw for something like .3 but `narrow_cast` won't, then I'd probably use narrow_cast. Usually @adiviness is more of an expert for these sorts of things

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 6]
```diff
@@ -1274,37 +1274,56 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
...
         {
             width += scrollbarSize;
         }
-
-        const float height = gsl::narrow<float>(rows * fFontHeight);
-
-        return { width, height };
+        
+        // Reserve space for padding
+        const auto paddingArr = _ParsePadding(settings.Padding());
```
[the remark this answers is not in the document]
Comment (Summon528) [reply src/cascadia/TerminalControl/TermControl.cpp]: That's probably a more elegant solution

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 7]
```diff
@@ -1274,17 +1274,20 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
...
+        double width = cols * fFontWidth;
 
         // Reserve additional space if scrollbar is intended to be visible
         if (settings.ScrollState() == ScrollbarState::Visible)
         {
             width += scrollbarSize;
         }
 
-        const float height = gsl::narrow<float>(rows * fFontHeight);
+        double height =rows * fFontHeight;
```
Comment (Summon528) [inline src/cascadia/TerminalControl/TermControl.cpp]:
```suggestion
        double height = rows * fFontHeight;
```

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 5 above)
Comment (dlong11) [reply src/cascadia/TerminalControl/TermControl.cpp]: I think narrow_cast if fine here too.    I haven't pulled this branch and I didn't understand why .3 would cause the value to change.  It could be that my mental compiler is broken though. 😄  I was curious with "some floating point precision issue".   If this is a valid case then I would go with narrow_cast.

Comment (Summon528) [reply src/cascadia/TerminalControl/TermControl.cpp]: This is what happened if I set padding to "0, 0.3, 0, 0". std::stod actually put `0.29999999999999999` into the array.   
And when `height` was cast to `float`, it became 

Therefore, the two values are not equal and `gsl::narrow` threw.

Comment (dlong11) [reply src/cascadia/TerminalControl/TermControl.cpp]: @Summon528 Thanks for the great explanation. (you went beyond what you needed to do - you didn't need to  - this was my responsibility to debug it. 😄  Much appreciated.)  This makes perfect sense.   gsl::narrow for floating point values doesn't make sense because of floating point issues.  So gsl::narrow_cast is the way to go.

**Comment by DHowett-MSFT** [comment]
Thank you, @summon528!
