### PR TITLE
Prevent ConPTY from de-snapping the terminal

### LINKED ISSUE #13158: [1.14.1433*] Opening a tab can cause the Terminal window to change size
### Windows Terminal version

1.14.1433.0

### Windows build number

 10.0.22000.0

### Other Software

_No response_

### Steps to reproduce

Open Terminal and snap the window to your choice of left, right, or top. One may also snap another app to the right or left (opposite the terminal). Then open a new tab. 

Uploading ellgramar-WinTermPrev-SnapBehaviour.mp4…

### Expected Behavior

When opening a new tab, The window was expected to stay snapped to where it was placed.

https://user-images.githubusercontent.com/5509462/170111340-15b6e919-3d93-4262-b2e3-0a62a70e320a.mp4

### Actual Behavior

When a new tab was opened, the window de-snapped, resized to the default launch dimensions and returned to the last free floating location it had been.

### LINKED ISSUE #13162: Opening a new tab when the window is maximized causes it to restore down
### Windows Terminal version

1.14.1433.0

### Windows build number

10.0.22000.0

### Other Software

_No response_

### Steps to reproduce

1. Open Terminal.
2. Maximize the window.
3. Open a new tab.
    - It doesn't matter how; `Ctrl+T`, new tab button, new tab from profile selector menu, etc.

### Expected Behavior

A new tab is opened, and the Terminal window stays maximized.

### Actual Behavior

A new tab is opened, but the window is restored down.

### PR DESCRIPTION
**Pull request by zadjii-msft**
This is a big hammer to put out this fire. We're keeping the hiding around for now, cause we think that's likely the one that the internal tests use that we really care about here. If we need to bring this back, we can. 

* [x] Closes #13158
* [x] Closes #13162
* [x] Validated these both manually 
* [x] `[Native]::ShowWindow([Native]::GetConsoleWindow(), 6)` still works

### CODE REVIEW

File: src/interactivity/base/InteractivityFactory.cpp [hunk 1]
```diff
@@ -478,7 +478,18 @@ void InteractivityFactory::SetPseudoWindowCallback(std::function<void(bool)> fun
...
 void InteractivityFactory::_WritePseudoWindowCallback(bool showOrHide)
 {
-    if (_pseudoWindowMessageCallback)
+    // BODGY
+    //
+    // GH#13158 - At least temporarily, only allow the PTY to HIDE the terminal
+    // window. There seem to be many issues with this so far, and the quickest
+    // route to mitigate them seems to be limiting the interaction here to
+    // allowing ConPTY to minimize the terminal only. This will still allow
+    // bodgy scripts to hide the Terminal via GetConsoleWindow(), but should
```
Comment (DHowett) [inline src/interactivity/base/InteractivityFactory.cpp:487]: Can you use ShowWindow to minimize it, then restore it, _and then use ShowWindow again in the same session_? Or does it get into a torn state?

**Review by lhecker — APPROVED** [review]

File: src/interactivity/base/InteractivityFactory.cpp (hunk 1 above)
Comment (zadjii-msft) [reply src/interactivity/base/InteractivityFactory.cpp:487]: Sure does! This is only preventing `ShowWindow(GetConsoleWindow(), SW_SHOW)` from going out to the terminal, the rest of the state still flows _in_ to the pty window

Comment (DHowett) [inline src/interactivity/base/InteractivityFactory.cpp:487]:
```suggestion
    // applications to hide the Terminal via GetConsoleWindow(), but should
```

I am doing this because speel cheek didn't like it but mysteriously didn't block the build

Comment (DHowett) [reply src/interactivity/base/InteractivityFactory.cpp:487]: it only accepts capital BODGY

Comment (DHowett) [reply src/interactivity/base/InteractivityFactory.cpp:487]: I'm not merging it until the test passes so I can admin merge later
