### PR TITLE
Sanitize C1 control chars in SetConsoleTitle API

### LINKED ISSUE #10312: C1 control characters break SetConsoleTitleW API
### Windows Terminal version (or Windows build number)

1.9.1445.0

### Other Software

_No response_

### Steps to reproduce

- Compile and run the following code:

```C++
#include <windows.h>

int main()
{
	if (!SetConsoleTitleW(L"\x80 Spanish Inquisition"))
		return 1;

	MessageBox(0, "I didn't expect that", 0, 0);
}
```
- Look at the screen and listen.

### Expected Behavior

The title is set.

### Actual Behavior

- Terminal *beeps* and prints the string *on the screen*. [MSDN](https://docs.microsoft.com/en-us/windows/console/setconsoletitle) doesn't mention any such visual or sound effects.
- The console title is not set, yet the function returns TRUE.

This is true for other C1 characters as well, not only 0x80.

P.S. The example is not synthetic: these characters can appear in directory and file names and applications can display the current path, the name of the opened file etc. in the console title.

### PR DESCRIPTION
**Pull request by j4james**
When the `SetContoleTitle` API is called with a title containing control
characters, we need to filter out those characters before we can forward
the title change over conpty as an escape sequence. If we don't do that,
the receiving terminal will end up executing the control characters
instead of updating the title. We were already filtering out the C0
control characters, but with this PR we're now filtering out C1 controls
characters as well.

I've simply updated the sanitizing routine in `DoSrvSetConsoleTitleW` to
filter our characters in the range `0x80` to `0x9F`. This is in addition
to the C0 range (`0x00` to `0x1F`) that was already excluded. 

## Validation Steps Performed

I've added a conpty unit test that calls `DoSrvSetConsoleTitleW` with
titles containing a variety of C0 and C1 controls characters, and which
verifies that those characters are stripped from the title forwarded to
conpty.

I've also confirmed that the test case in issue #10312 is now working
correctly in Windows Terminal.

Closes #10312

### CODE REVIEW

File: src/host/getset.cpp [hunk 1]
```diff
@@ -1935,9 +1935,10 @@ void DoSrvPrivateRefreshWindow(_In_ const SCREEN_INFORMATION& screenInfo)
         sanitized.reserve(title.size());
         for (size_t i = 0; i < title.size(); i++)
         {
-            if (title.at(i) >= UNICODE_SPACE)
+            const auto ch = title.at(i);
```
Comment (lhecker) [inline src/host/getset.cpp:1938]: Can you convert this to a `for (const auto ch : title)` loop? The exception-checked

On top of that I'd _personally_ do it this way - it reduces binary size by half:
```
std::wstring sanitized{title};
sanitized.erase(std::remove_if(sanitized.begin(), sanitized.end(), [](auto ch) -> bool {
    return ch < 0x20 || (ch > 0x7f && ch < 0xa0);
}), sanitized.end());
return sanitized;
```
`push_back` and `emplace_back` are very expensive once they're inlined.

Comment (DHowett) [reply src/host/getset.cpp:1938]: I'm fine with James keeping the code the way that it was (it's not his mess to clean up!), but if he wants to fix it all the more power to him. :smile:

**Review by DHowett — APPROVED** [review]

**Review by zadjii-msft — APPROVED** [review]

File: src/host/getset.cpp (hunk 1 above)
Comment (j4james) [reply src/host/getset.cpp]: Yeah, I like that approach. Not that thrilled with the code health bot's formatting, but at least it's more efficient now. Thanks @lhecker.

Comment (j4james) [reply src/host/getset.cpp]: I guess this range stuff gets a bit neater with C++20, but I'm assuming we're not using that yet?

Comment (zadjii-msft) [reply src/host/getset.cpp]: > I guess this range stuff gets a bit neater with C++20, but I'm assuming we're not using that yet?

alas no, we can't use c++20 in the OS build system quite yet ☹️
