### PR TITLE
Remove `startOnUserLogin` from the settings; use OS APIs only

### LINKED ISSUE #12564: We shouldn't have our own startup setting, we should just use the OS one
From MSFT:34529127

> Steps to repro:
> 1. Open Settings - App - Start up.
> 2. Enable start up setting for Windows Terminal.
> 3. Reboot.
>
> Expected results:
> Windows Terminal can launch automatically after enter desktop and App start up setting should be on for Windows Terminal.
> Actual results:
> Windows Terminal can launch automatically after enter desktop, but App start up setting become off for Windows Terminal.

----

More notes, circa Dec 2023:

Okay so we all re-read all the docs and I think we were wrong entirely here. 

We should have never had this setting in our settings JSON in the first place. It should have always just been backed by the OS setting. This probably dates back to us just having a JSON settings file. We should make the settings in the Terminal Settings UI reflect the OS settings. We shouldn't maintain our own _separate_ setting. 

> We need the Windows Settings Startup being Enabled to trigger Windows to start Terminal on next reboot.
And, we need the Terminal Settings Startup to be Enabled, to keep it in the Enabled state for Windows. If this is not enabled, when Windows launches Terminal after reboot, Terminal app itself disables the startup task here: https://github.com/microsoft/terminal/blob/306f31acf482ce84701aabee52981575277f16bb/src/cascadia/TerminalApp/AppLogic.cpp#L382
> 
> Quickly glancing through the Terminal code, Terminal Settings Startup relies on "`startOnUserLogin`" value and is saved in a default file. This value does not change if the user changes startup state in Windows Settings. 
>  
> I am not sure, why the startup task is disabled when `StartupTaskState::Enabled` in the above link. But in my opinion it shouldn't be disabled if the user has enabled it in Windows settings. and use the value returned by `StartupTask::GetAsync(StartupTaskName)` for "`startOnUserLogin`".

> [!Note]
> ## Walkthrough

I need to write a new one!

We need to:
* Ditch the old setting entirely. 
* Make the toggle in the Settings tab reflect the OS setting
* probably remove `Enabled="false"` from our manidest, ala #16244

### PR DESCRIPTION
**Pull request by DHowett**
Before we had a Settings UI, we added support for a setting called `startOnUserLogin`. It was a boolean, and on startup we would try to yeet the value of that setting into the Windows API responsible for registering us as a startup task.

Unfortunately, we failed to take into account a few things.

- Startup tasks can be independently controlled by the user in Windows Settings or by an enterprise using enterprise policy
- This control is not limited to *disabling* the task; it also supports enabling it!

Users could enable our startup task outside the settings file and we would never know it. We would load up, see that `startOnUserLogin` was `false`, and go disable the task again. :facepalm:

Conversely, if the user disables our task outside the app _we can never enable it from inside the app._ If an enterprise has configured it either direction, we can't change it either.

The best way forward is to remove it from our settings model and only ever interact with the Windows API.

This pull request replaces `startOnUserLogin` with a rich settings experience that will reflect the current and final state of the task as configured through Windows. Terminal will enable it if it can and display a message if it can't.

My first attempt at this PR (which you can read in the commit history) made us try harder to sync the state between the settings model and the OS; we would propagate the disabled state back to the user setting when the task was disabled in the OS or if we failed to enable it when the user asked for it. That was fragile and didn't support reporting the state in the settings UI, and it seems like it would be confusing for a setting to silently turn itself back off anyway...

Closes #12564

### CODE REVIEW

**Comment by htcfreek** [comment]
might be interesting to track "by policy" for showing in ui. 🤔

**Comment by DHowett** [comment]
image
image
image

**Comment by htcfreek** [comment]
> image
> image
> image
> 

For UI consistency you should add a lock icon as on the AI page.

File: src/cascadia/TerminalSettingsEditor/LaunchViewModel.cpp [hunk 1]
```diff
@@ -365,4 +368,88 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
...
+
+    safe_void_coroutine LaunchViewModel::PrepareStartOnUserLoginSettings()
+    {
+        if (!StartOnUserLoginAvailable())
+        {
+            co_return;
+        }
+
+        auto strongThis{ get_strong() };
+        co_await winrt::resume_background();
```
Comment (lhecker) [inline src/cascadia/TerminalSettingsEditor/LaunchViewModel.cpp:380]: Any reason to not call this on the main thread?

**Review by lhecker — APPROVED** [review]
Nice! ...Lock symbol or not. 😄

**Comment by DHowett** [comment]
image

lock icon

File: src/cascadia/TerminalSettingsEditor/LaunchViewModel.cpp (hunk 1 above)
Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/LaunchViewModel.cpp]: fixed!

**Review by carlos-zamora — APPROVED** [review]
Nice work! Please be sure to update the docs site

File: src/cascadia/TerminalSettingsEditor/SettingContainer.cpp [hunk 2]
```diff
@@ -215,6 +182,50 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
...
+                    }
+                });
+
+                // apply name (automation property)
+                Automation::AutomationProperties::SetName(child, RS_(L"SettingContainer_OverrideMessageBaseLayer"));
+            }
+        }
+
+        _UpdateOverrideSystem();
+        _UpdateHelpText();
```
[the remark this answers is not in the document]
Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/SettingContainer.cpp:226]: So yes! SettingContainer did not support dynamic updates to HelpText!
