### PR TITLE
TermControl: force all ambiguous glyphs to be narrow

### LINKED ISSUE #2066: Consider making ConPTY and Windows Terminal treat all ambiguous-width characters as 1 cell instead of asking the font
> > Note that the SCS escape sequence doesn't work in the Linux text console [...]
> 
> You're absolutely right here.
> 
> I also realized I was wrong with PuTTY. Up to version 0.70 (which I tested) PuTTY didn't support line drawing in UTF-8 (as per Markus Kuhn's recommendation for UTF-8 being stateless). You either have to have a legacy charset, or version 0.71 with "Window -> Translation -> Enable VT100 line drawing even in UTF-8 mode". I now tried the latter, and it indeed converts the underscore to a space.
> 
> So it looks like Windows Terminal and VTE are the buggy ones here. I've just filed [VTE 157](https://gitlab.gnome.org/GNOME/vte/issues/157).
> 
> Just for curiosity: Are you aware of any application which emits this? Why would any app do so, given that the regular space is also a space? :)
> 
> > As for the choice of diamond character, I don't think the width is something that can be "fixed" in the terminal code. I believe the dimensions of an ambiguous width character are decided by the font.
> 
> I firmly disagree here. In terminal emulation, apps have to be able to print something and keep track of the cursor, whereas they by design have no idea of the font being used. In many terminals the font can also be changed runtime and it's absolutely not feasible to then rearrange the cells. In some other cases there is no font at all (e.g. the libvterm headless terminal emulation library, or a detached screen/tmux), or there are multiple fonts at once (a screen/tmux attached from multiple graphical emulators).
> 
> The only way to do that is via some external agreement on the number of cells, which is typically the Unicode EastAsianWidth, often accessed via `wcwidth()`. It's not perfect (changes through Unicode versions, has ambiguous characters, etc.) but is still the best we have.
> 
> glibc's `wcwidth()` reports 1 for ambiguous width characters, so the de facto standard is that in terminals they are narrow.
> 
> If the glyph is wider then the terminal has to figure out what to do. It could crop it (newer versions of Konsole, as far as I know), overflow to the right (VTE), shrink it (Kitty I believe does this), etc.
> 
_Originally posted by @egmontkob in https://github.com/microsoft/terminal/issues/2049#issuecomment-513588977_

### LINKED ISSUE #2375: Crash: Use after free of std::function through CodepointWidthDetector
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.267]
Windows Terminal version (if applicable): 0.3.2171.0
```

# Steps to reproduce

I'm honestly not sure what I was doing. This might be #2251?

# Expected behavior

The terminal shouldn't crash.

# Actual behavior

```
ExceptionAddress: 00007ffdd2990f60 (uiautomationcore!MenuOpened_Event_GUID)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 0000000000000008
   Parameter[1]: 00007ffdd2990f60
Attempt to execute non-executable address 00007ffdd2990f60

 # Child-SP          RetAddr           Call Site
0c 00000004`2aefe098 00007ffd`b226761b uiautomationcore!MenuOpened_Event_GUID
0d (Inline Function) --------`-------- TerminalControl!std::_Invoker_pmf_pointer::_Call+0x17 [C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.22.27905\include\type_traits @ 1457] 
0e (Inline Function) --------`-------- TerminalControl!std::invoke+0x17 [C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.22.27905\include\type_traits @ 1457] 
0f (Inline Function) --------`-------- TerminalControl!std::_Invoker_ret<std::_Unforced,0>::_Call+0x17 [C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.22.27905\include\type_traits @ 1492] 
10 (Inline Function) --------`-------- TerminalControl!std::_Call_binder+0x17 [C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.22.27905\include\functional @ 1485] 
11 (Inline Function) --------`-------- TerminalControl!std::_Binder<std::_Unforced,bool (__cdecl Microsoft::Console::Render::Renderer::*)(std::basic_string_view<wchar_t,std::char_traits<wchar_t> >),Microsoft::Console::Render::Renderer *,std::_Ph<1> const &>::operator()+0x17 [C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.22.27905\include\functional @ 1531] 
12 (Inline Function) --------`-------- TerminalControl!std::_Invoker_functor::_Call+0x17 [C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.22.27905\include\type_traits @ 1457] 
13 (Inline Function) --------`-------- TerminalControl!std::invoke+0x17 [C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.22.27905\include\type_traits @ 1457] 
14 (Inline Function) --------`-------- TerminalControl!std::_Invoker_ret<bool,0>::_Call+0x17 [C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.22.27905\include\type_traits @ 1483] 
15 00000004`2aefe0a0 00000000`00000000 TerminalControl!std::_Func_impl_no_alloc<std::_Binder<std::_Unforced,bool (__cdecl Microsoft::Console::Render::Renderer::*)(std::basic_string_view<wchar_t,std::char_traits<wchar_t> >),Microsoft::Console::Render::Renderer *,std::_Ph<1> const &>,bool,std::basic_string_view<wchar_t,std::char_traits<wchar_t> > >::_Do_call+0x1b [C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.22.27905\include\functional @ 1007] 
```

I'm happy to share the crash dump out of band.

### PR DESCRIPTION
**Pull request by DHowett-MSFT**
From Egmont Koblinger:
> In terminal emulation, apps have to be able to print something and
keep track of the cursor, whereas they by design have no idea of the
font being used. In many terminals the font can also be changed runtime
and it's absolutely not feasible to then rearrange the cells. In some
other cases there is no font at all (e.g. the libvterm headless terminal
emulation library, or a detached screen/tmux), or there are multiple
fonts at once (a screen/tmux attached from multiple graphical
emulators).

> The only way to do that is via some external agreement on the number
of cells, which is typically the Unicode EastAsianWidth, often accessed
via wcwidth(). It's not perfect (changes through Unicode versions, has
ambiguous characters, etc.) but is still the best we have.

> glibc's wcwidth() reports 1 for ambiguous width characters, so the de
facto standard is that in terminals they are narrow.

> If the glyph is wider then the terminal has to figure out what to do.
It could crop it (newer versions of Konsole, as far as I know), overflow
to the right (VTE), shrink it (Kitty I believe does this), etc.

See Also:
https://bugzilla.gnome.org/show_bug.cgi?id=767529
https://gitlab.freedesktop.org/terminal-wg/specifications/issues/9
https://www.unicode.org/reports/tr11/tr11-34.html

Salient point from proposed update to Unicode Standard Annex #11:
> Note: The East_Asian_Width property is not intended for use by modern
terminal emulators without appropriate tailoring on a case-by-case
basis.

Fixes #2066
Fixes #2375

## PR Checklist
* [x] Closes stuff
* [x] written by an employee
* [x] Testing sorta done
* [ ] ~Requires documentation to be updated~
* [x] I've discussed this with core contributors already. AT LENGTH.

## Validation Steps Performed

This one has some followup issues. I went wild on it, but it does still have some issues. It makes #900 worse, and introduces a debug break you hit when the renderer and the column counter disagree. It might make the renderer discard the rest of the line it was working on.

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
@zadjii-msft i can produce a table of all the emoji that exist, and which ones are miscolumned. Would that be sufficient evidence to move #900 forward, do you reckon?

**Comment by zadjii-msft** [comment]
@DHowett-MSFT Probably. I'm probably not going to be the one solving #900 though, that seems more like @miniksa's wheelhouse

**Comment by miniksa** [comment]
> @zadjii-msft Mike Griese FTE i can produce a table of all the emoji that exist, and which ones are miscolumned. Would that be sufficient evidence to move #900 forward, do you reckon?

> @DHowett-MSFT Dustin Howett FTE Probably. I'm probably not going to be the one solving #900 though, that seems more like @miniksa Michael Niksa FTE's wheelhouse

I'm fine with building such a table, @DHowett-MSFT and resolving the columns. It looks like in #900 that Fcharlie already did something like that

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 1]
```diff
@@ -22,6 +22,25 @@ using namespace winrt::Microsoft::Terminal::Settings;
...
+    // See microsoft/terminal#2066 for more info.
+    static bool _IsGlyphWideForceNarrowFallback(const std::wstring_view /* glyph */)
+    {
+        return false; // glyph is not wide.
+    }
+
+    static bool _EnsureStaticInitialization()
+    {
+        // use C++11 magic statics to make sure we only do this once.
+        static bool initialized = []() {
```
Comment (miniksa) [inline src/cascadia/TerminalControl/TermControl.cpp]: const?
