### PR TITLE
Fix local tests

### LINKED ISSUE #14623: Local tests are failing again - seemingly due to a race initializing the page/control
### Windows Terminal version

Commit 547349af77df16d0eed1c73ba3041c84f7b063da

### Windows build number

10.0.19044.2364

### Other Software

_No response_

### Steps to reproduce

1. Check out a recent version of the project.
2. Build it.
3. Run the unit tests.

### Expected Behavior

All tests should pass.

### Actual Behavior

A number of the local tests are failing:

    TerminalAppLocalTests::TabTests::TryInitializePage [Failed]
    TerminalAppLocalTests::TabTests::TryDuplicateBadTab [Failed]
    TerminalAppLocalTests::TabTests::TryDuplicateBadPane [Failed]
    TerminalAppLocalTests::TabTests::TryZoomPane [Failed]
    TerminalAppLocalTests::TabTests::MoveFocusFromZoomedPane [Failed]
    TerminalAppLocalTests::TabTests::CloseZoomedPane [Failed]
    TerminalAppLocalTests::TabTests::SwapPanes [Failed]
    TerminalAppLocalTests::TabTests::NextMRUTab [Failed]
    TerminalAppLocalTests::TabTests::VerifyCommandPaletteTabSwitcherOrder [Failed]
    TerminalAppLocalTests::TabTests::TestWindowRenameSuccessful [Failed]
    TerminalAppLocalTests::TabTests::TestWindowRenameFailure [Failed]
    TerminalAppLocalTests::TabTests::TestPreviewCommitScheme [Failed]
    TerminalAppLocalTests::TabTests::TestPreviewDismissScheme [Failed]
    TerminalAppLocalTests::TabTests::TestPreviewSchemeWhilePreviewing [Failed]
    TerminalAppLocalTests::TabTests::TestClampSwitchToTab [Failed]
    SettingsModelLocalTests::SerializationTests::CascadiaSettings [Failed]

### LINKED ISSUE #19610: Repair failed LocalTests disabled in #15770
```
TerminalAppLocalTests::TabTests::TryZoomPane [Failed]
TerminalAppLocalTests::TabTests::MoveFocusFromZoomedPane [Failed]
TerminalAppLocalTests::TabTests::CloseZoomedPane [Failed]
TerminalAppLocalTests::TabTests::SwapPanes [Failed]
TerminalAppLocalTests::TabTests::NextMRUTab [Failed]
TerminalAppLocalTests::TabTests::VerifyCommandPaletteTabSwitcherOrder [Failed]
TerminalAppLocalTests::TabTests::TestWindowRenameSuccessful [Failed]
TerminalAppLocalTests::TabTests::TestWindowRenameFailure [Failed]
TerminalAppLocalTests::TabTests::TestPreviewCommitScheme [Failed]
TerminalAppLocalTests::TabTests::TestPreviewDismissScheme [Failed]
TerminalAppLocalTests::TabTests::TestPreviewSchemeWhilePreviewing [Failed]
TerminalAppLocalTests::TabTests::TestClampSwitchToTab [Failed]
TerminalAppLocalTests::TabTests::TryDuplicateBadPane [Failed]
TerminalAppLocalTests::TabTests::TryDuplicateBadTab [Failed]
```

### PR DESCRIPTION
**Pull request by carlos-zamora**
## Summary of the Pull Request
Fixes TabTests.cpp. Changes include:
- add `"closeOnExit": "never"` to some tests to avoid the race condition discussed in #14623. It keeps the tabs/panes around so that we can actually test them.
- removes the `assert(false)` in `TermControl::MinimumSize()`. I've been hitting this assert in dev builds _every time_ I split a pane. I think it isn't adding value, but if we want to investigate it further, we can.
- update MRU tests to not use the command palette (aka tab switcher) UI. The UI requires you to hold a modifier key down to keep it displayed. That isn't something we can simulate. Instead we just use the relevant APIs to simulate switching tabs. This is ok because the `MRU` list is still updated, so we're still able to validate that we're updating it properly.
- Add `Tab[idx]` and `MRU[idx]` notation to MRU tests to make them easier to follow

## Validation Steps Performed
✅ local tests pass

Closes #19610
Closes #14623

### CODE REVIEW

File: src/cascadia/LocalTests_TerminalApp/TabTests.cpp [hunk 1]
```diff
@@ -1454,10 +1411,6 @@ namespace TerminalAppLocalTests
 
     void TabTests::TestPreviewSchemeWhilePreviewing()
     {
-        BEGIN_TEST_METHOD_PROPERTIES()
-            TEST_METHOD_PROPERTY(L"Ignore", L"True") // GH#19610 tracks re-enabling this test
```
Comment (DHowett) [inline src/cascadia/LocalTests_TerminalApp/TabTests.cpp:1458]: Oh interesting, were these also failing due to the closeOnExit race?

**Review by DHowett — APPROVED** [review]
thanks for doing this!

File: src/cascadia/LocalTests_TerminalApp/TabTests.cpp (hunk 1 above)
Comment (carlos-zamora) [reply src/cascadia/LocalTests_TerminalApp/TabTests.cpp:1458]: Yup! Because the tab would exit immediately, so you'd get a race condition and we wouldn't be able to verify what we wanted to.
