### PR TITLE
Make sure to update the selection pivot while circling

### LINKED ISSUE #14462: Unable to select text correctly while new lines are printed and history buffer is full
### Windows Terminal version

1.15.2875.0

### Windows build number

10.0.22621.819

### Other Software

_No response_

### Steps to reproduce

See #10319 for the previous report, it was supposedly fixed in v1.11, but I still see this behaviour.

1. Set `"historySize": 100,` for the profile.
2. Run a script that echoes new lines
3. Try to select text

Example script to test the issue:
```powershell
Do {
	echo $(Get-Random)
	sleep 0.1
}
while ($true)
```

https://user-images.githubusercontent.com/613331/204636943-b8f8f4b5-e6da-4fdb-88cd-b59bc8e8ad17.mp4

### Expected Behavior

Correctly select text. It works when the history buffer is full.

### Actual Behavior

The selection scrolls away from you, selecting different text.

### PR DESCRIPTION
**Pull request by zadjii-msft**
This builds upon #10749. When we added a separate pivot to track the "active" anchor, we forgot to update the pivot while circling. What does that mean? Moving the mouse would trigger us to update the selection using new endpoint and the old _pivot_, which hadn't been updated. 

There's probably a more elegant way of doing this, but it's good enough. 

Updated the test to cover this as well. 

Closes #14462

### CODE REVIEW

File: src/cascadia/UnitTests_Control/ControlInteractivityTests.cpp [hunk 1]
```diff
@@ -811,8 +813,86 @@ namespace ControlUnitTests
...
+
+            VERIFY_ARE_EQUAL(expectedAnchor, anchor);
+            VERIFY_ARE_EQUAL(expectedAnchor, end);
+        }
+        VERIFY_ARE_EQUAL(scrollbackLength - 2, core->_terminal->GetScrollOffset());
+
+        Log::Comment(L"Move the mouse a little, to update the selection");
+        // At this point, there should only be one selection region! The
+        // viewport moved up to keep the selection at the same relative spot. So
+        // wiggling the cursor shoudld continue to select only the same
```
Comment (carlos-zamora) [inline src/cascadia/UnitTests_Control/ControlInteractivityTests.cpp:849]:
```suggestion
        // wiggling the cursor should continue to select only the same
```

**Review by carlos-zamora — APPROVED** [review]
✅

File: src/cascadia/TerminalCore/Terminal.cpp [hunk 2]
```diff
@@ -1197,6 +1199,15 @@ void Terminal::_AdjustCursorPosition(const til::point proposedPosition)
                         _selection.reset();
                     }
                 }
+
+                // If we still have a selection, make sure to sync the pivot
+                // with whichever value is the right one.
+                //
+                // Failure to do this might lead to GH #14462
```
Comment (DHowett) [inline src/cascadia/TerminalCore/Terminal.cpp:1206]:
```suggestion
```

I respect that this is true, but also... `git blame` could probably tell you that, and I don't know that every time we make a change we need to decorate the code with signposts that say "this was a bug back when xyz" :)

File: src/cascadia/UnitTests_Control/ControlInteractivityTests.cpp [hunk 3]
```diff
@@ -811,8 +813,86 @@ namespace ControlUnitTests
...
+                                    cursorPosition1.to_core_point(),
+                                    true);
+        VERIFY_IS_TRUE(core->HasSelection());
+        VERIFY_ARE_EQUAL(1u, core->_terminal->GetSelectionRects().size());
+        {
+            const auto anchor{ core->_terminal->GetSelectionAnchor() };
+            const auto end{ core->_terminal->GetSelectionEnd() };
+            Log::Comment(fmt::format(L"expectedAnchor:({},{})", expectedAnchor.x, expectedAnchor.y).c_str());
+            Log::Comment(fmt::format(L"anchor:({},{})", anchor.x, anchor.y).c_str());
+            Log::Comment(fmt::format(L"end:({},{})", end.x, end.y).c_str());
```
Comment (DHowett) [inline src/cascadia/UnitTests_Control/ControlInteractivityTests.cpp:891]: this seems like it should be one really long `fmt::format` instead of three, but.. \\\_(shrug)\_/

**Review by DHowett — APPROVED** [review]

File: src/cascadia/TerminalCore/Terminal.cpp (hunk 2 above)
Comment (zadjii-msft) [reply src/cascadia/TerminalCore/Terminal.cpp:1206]: sorry missed this - FWIW I still add these out of habit. After being through 4 different source control trees, I find it's 1000% easier to leave the history for weird lines of code next to them in the source. Then, when one of these lines is inevitably refactored, we can see the comment moved/deleted and check the original bug for regressions, rather than manually `git blame`ing every time we _think_ a line of code comes from a weird bug report. 

That's my 2c. LOC are cheap.
