### PR TITLE
Correct scrolling invalidation region for tmux in pty w/ bitmap

### LINKED ISSUE #5104: Screen content does not update in tmux
# Environment

Windows 10.0.18363.0
tmux over ssh in cygwin

# Steps to reproduce

1. Attach to tmux session
2. Fill the screen for example with `echo test` multiple times
3. Keep printing `test`, you should alternate with some different text to see if console is scrolled properly.

# Expected behavior

Whole screen buffer is redrawn

# Actual behavior

Only first line in terminal is redrawn, the rest of the screen space is static and doesn't update while it should. If the output is one line (i.e without new line). If I do `echo 'test\n'` whole screen is properly redrawn. 

## Bisect result

This is regression from this commit https://github.com/microsoft/terminal/commit/ca33d895a359664c337c6482b853489823c216d3 before that everything was working fine. 

// CC @miniksa

### PR DESCRIPTION
**Pull request by miniksa**
Correct scrolling invalidation region for tmux in pty w/ bitmap

Add tracing for circling and scrolling operations. Fix improper
invalidation within AdjustCursorPosition routine in the subsection about
scrolling down at the bottom with a set of margins enabled.

## References
- Introduced with #5024 

## Detailed Description of the Pull Request / Additional comments
- This occurs when there is a scroll region restriction applied and a
  newline operation is performed to attempt to spin the contents of just
  the scroll region. This is a frequent behavior of tmux.
- Right now, the Terminal doesn't support any sort of "scroll content"
  operation, so what happens here generally speaking is that the PTY in
  the ConHost will repaint everything when this happens.
- The PTY when doing `AdjustCursorPosition` with a scroll region
  restriction would do the following things:

1. Slide literally everything in the direction it needed to go to take
   advantage of rotating the circular buffer. (This would force a
   repaint in PTY as the PTY always forces repaint when the buffer
   circles.)
2. Copy the lines that weren't supposed to move back to where they were
   supposed to go.
3. Backfill the "revealed" region that encompasses what was supposed to
   be the newline.

- The invalidations for the three operations above were:

1. Invalidate the number of rows of the delta at the top of the buffer
   (this part was wrong)
2. Invalidate the lines that got copied back into position (probably
   unnecessary, but OK)
3. Invalidate the revealed/filled-with-spaces line (this is good).

- When we were using a simple single rectangle for invalidation, the
  union of the top row of the buffer from 1 and the bottom row of the
  buffer from 2 (and 3 was irrelevant as it was already unioned it)
  resulted in repainting the entire buffer and all was good.

- When we switched to a bitmap, it dutifully only repainted the top line
  and the bottom two lines as the middle ones weren't a consequence of
  intersect.

- The logic was wrong. We shouldn't be invalidating rows-from-the-top
  for the amount of the delta. The 1 part should be invalidating
  everything BUT the lines that were invalidated in parts 2 and 3.
  (Arguably part 2 shouldn't be happening at all, but I'm not optimizing
  for that right now.)

- So this solves it by restoring an entire screen repaint for this sort
  of slide data operation by giving the correct number of invalidated
  lines to the bitmap.

## Validation Steps Performed
- Manual validation with the steps described in #5104
- Automatic test `ConptyRoundtripTests::ScrollWithMargins`.

Closes #5104

### CODE REVIEW

**Comment by miniksa** [comment]
Still needs some sort of automated test and for me to finish the description...

File: src/renderer/vt/tracing.cpp [hunk 1]
```diff
@@ -127,6 +127,20 @@ void RenderTracing::TraceTriggerCircling(const bool newFrame) const
 #endif UNIT_TESTING
 }
 
+void RenderTracing::TraceInvalidateScroll(const til::point scroll) const
```
Comment (zadjii-msft) [inline src/renderer/vt/tracing.cpp]: lol at d972b5e

File: src/renderer/vt/tracing.cpp [hunk 2]
```diff
@@ -127,6 +127,20 @@ void RenderTracing::TraceTriggerCircling(const bool newFrame) const
 #endif UNIT_TESTING
 }
 
+void RenderTracing::TraceInvalidateScroll(const til::point scroll) const
+{
+#ifndef UNIT_TESTING
```
Comment (DHowett-MSFT) [inline src/renderer/vt/tracing.cpp]: lkjfgdkjhgfdlkjhfgkjhlfg

File: src/renderer/vt/XtermEngine.cpp [hunk 3]
```diff
@@ -402,25 +402,28 @@ XtermEngine::XtermEngine(_In_ wil::unique_hfile hPipe,
...
+        _trace.TraceInvalidateScroll(delta);
+
         // Scroll the current offset and invalidate the revealed area
-        _invalidMap.translate(til::point(*pcoordDelta), true);
+        _invalidMap.translate(delta, true);
 
         COORD invalidScrollNew;
-        RETURN_IF_FAILED(ShortAdd(_scrollDelta.X, dx, &invalidScrollNew.X));
-        RETURN_IF_FAILED(ShortAdd(_scrollDelta.Y, dy, &invalidScrollNew.Y));
+        RETURN_IF_FAILED(ShortAdd(_scrollDelta.X, delta.x<SHORT>(), &invalidScrollNew.X));
```
Comment (zadjii-msft) [inline src/renderer/vt/XtermEngine.cpp]: Should we theoretically convert `_scrollDelta` to a `til::point` so that this can just work automagically?

File: src/renderer/vt/tracing.cpp (hunk 1 above)
Comment (miniksa) [reply src/renderer/vt/tracing.cpp]: LOL.

File: src/renderer/vt/XtermEngine.cpp (hunk 3 above)
Comment (miniksa) [reply src/renderer/vt/XtermEngine.cpp]: Yes.

File: src/renderer/vt/tracing.cpp (hunk 2 above)
Comment (miniksa) [reply src/renderer/vt/tracing.cpp]: Yeah I know.

**Comment by miniksa** [comment]
Tests on Friday. Gotta be done for the day.

**Comment by miniksa** [comment]
### Future notes that may need work items (per discussion):
- We could implement a scrolling region communication between the PTY and the Terminal so we wouldn't have to invalidate all of this and re-communicate it all.
- We don't really need to be invalidating the modeline. It's just a consequence of "move everything up and then some things back down." This would mean improving the algorithm in `AdjustCursorPosition` to maybe just send all operations that it wants to do directly to a scroll method and let it handle the optimization if it should circle things itself.
- We probably shouldn't be having the PTY emit a command for turning on the cursor for no good reason during some of this output.
- There's likely an extraneous cursor positioning message from the PTY as well.
- All of this will become less relevant as we focus more and more on letting pass-through occur.

File: src/renderer/vt/math.cpp [hunk 4]
```diff
@@ -64,7 +64,7 @@ void VtEngine::_OrRect(_Inout_ SMALL_RECT* const pRectExisting, const SMALL_RECT
 bool VtEngine::_WillWriteSingleChar() const
 {
     // If there is scroll delta, return false.
```
Comment (DHowett-MSFT) [inline src/renderer/vt/math.cpp]:
```suggestion
    // If there is no scroll delta, return false.
```

nit

Comment (miniksa) [reply src/renderer/vt/math.cpp]: got it.
