### PR TITLE
Fixed self capture in TermControl

### LINKED ISSUE #2947: Access Violation in TerminalControl!winrt::impl::consume_Windows_UI_Xaml_Controls_Primitives_IRangeBase<winrt::Windows::UI::Xaml::Controls::Primitives::ScrollBar>::Maximum
# Environment
```none
Windows build number: 10.0.18975.0
Windows Terminal version: 0.5.2622.0
```
# Steps to reproduce
1. Run wt.exe to start an instance of Windows Terminal
2. Press Ctrl-t 4 or 5 times to open a few tabs (running PowerShell)
3. In each tab, run `dir c:\ -rec`
4. Wait a few seconds, then click the 'x' on one of the tabs to close it while it is writing text to the console

# Expected behavior
The tab closes.

# Actual behavior
The terminal crashes with an Access Violation due to a null pointer dereference in `TerminalControl!winrt::impl::consume_Windows_UI_Xaml_Controls_Primitives_IRangeBase<winrt::Windows::UI::Xaml::Controls::Primitives::ScrollBar>::Maximum`

# Notes
I can reproduce this consistently. Let me know if you would like a memory dump.

Here is a link to the feedback issue I opened:
https://aka.ms/AA65up1

# Call stack
```
rax=0000d0e9f60fae3a rbx=00000000000002d6 rcx=0000000000000000
rdx=0000000000000000 rsi=00000000000002d6 rdi=000000000000001c
rip=00007ffd75b073d1 rsp=00000095845ff250 rbp=000001afa9234f70
 r8=0000000010000000  r9=0000000000000000 r10=0000000000000000
r11=0000000000000246 r12=0000000000000000 r13=000000000000001c
r14=00007ffda8394d10 r15=0000000000000000
iopl=0         nv up ei pl zr na po nc
cs=0033  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010246
TerminalControl!winrt::impl::consume_Windows_UI_Xaml_Controls_Primitives_IRangeBase<winrt::Windows::UI::Xaml::Controls::Primitives::ScrollBar>::Maximum+0x51:
00007ffd`75b073d1 488b01          mov     rax,qword ptr [rcx] ds:00000000`00000000=????????????????

 Child-SP          RetAddr           Call Site
00 00000095`845ff250 00007ffd`75b1812c TerminalControl!winrt::impl::consume_Windows_UI_Xaml_Controls_Primitives_IRangeBase<winrt::Windows::UI::Xaml::Controls::Primitives::ScrollBar>::Maximum+0x51 [E:\BA\35\s\src\cascadia\TerminalControl\Generated Files\winrt\Windows.UI.Xaml.Controls.Primitives.h @ 2838] 
01 (Inline Function) --------`-------- TerminalControl!winrt::Microsoft::Terminal::TerminalControl::implementation::TermControl::_ScrollbarUpdater+0x14 [E:\BA\35\s\src\cascadia\TerminalControl\TermControl.cpp @ 1373] 
02 (Inline Function) --------`-------- TerminalControl!winrt::Microsoft::Terminal::TerminalControl::implementation::TermControl::_TerminalScrollPositionChanged::__l2::<lambda_d4673cfb40ab3bbddd63d78386fc20ac>::operator()+0x43 [E:\BA\35\s\src\cascadia\TerminalControl\TermControl.cpp @ 1396] 
03 00000095`845ff2c0 00007ffd`9f91c471 TerminalControl!winrt::impl::delegate<winrt::Windows::UI::Core::DispatchedHandler,<lambda_d4673cfb40ab3bbddd63d78386fc20ac> >::Invoke+0x5c [E:\BA\35\s\src\cascadia\TerminalControl\Generated Files\winrt\windows.ui.core.h @ 1275] 
04 (Inline Function) --------`-------- Windows_UI!Windows::UI::Core::CDispatcher::EnqueueAsyncWork::__l16::<lambda_59517943c03487243f9bea31c6c1a784>::operator()+0x67 [onecoreuap\windows\advcore\winrt\onecoreiwindow\corewindow\common\dispatcher.cpp @ 908] 
05 00000095`845ff310 00007ffd`a8394d26 Windows_UI!Microsoft::WRL::Details::DelegateArgTraits<long (__cdecl Windows::System::IDispatcherQueueHandler::*)(void)>::DelegateInvokeHelper<Microsoft::WRL::Implements<Microsoft::WRL::RuntimeClassFlags<2>,Windows::System::IDispatcherQueueHandler,Microsoft::WRL::FtmBase>,<lambda_59517943c03487243f9bea31c6c1a784>,-1>::Invoke+0x71 [onecore\external\sdk\inc\wrl\event.h @ 245] 
06 00000095`845ff340 00007ffd`a836423b CoreMessaging!Windows::System::DispatcherQueue::DeferInvokeCallback+0x16 [mincore\coreui\dev\dispatcherqueue\WrtDispatcherQueue.cpp @ 893] 
07 00000095`845ff370 00007ffd`a8361d64 CoreMessaging!Microsoft__CoreUI__Dispatch__TimeoutHandler$CallbackThunk+0x11b [temp\42829c929effddb13f17f63c5ec49c58\Common__DllInterop.cpp @ 505] 
08 (Inline Function) --------`-------- CoreMessaging!System::Action::Invoke+0x1a [mincore\cn\cnruntime\lib\fullstr\fre\objfre\amd64\CnRuntime\Common__Delegate.cpp @ 91] 
09 00000095`845ff3f0 00007ffd`a83616fe CoreMessaging!Microsoft::CoreUI::Dispatch::DeferredCall::Callback_Dispatch+0x2c4 [mincore\CoreUI\Dev\System\Dispatch\DeferredCall.cs @ 62] 
0a 00000095`845ff4b0 00007ffd`a8368d1a CoreMessaging!Microsoft::CoreUI::Dispatch::DeferredCallDispatcher::Callback_OnDispatch+0x15e [mincore\CoreUI\Dev\System\Dispatch\DeferredCallDispatcher.cs @ 337] 
0b (Inline Function) --------`-------- CoreMessaging!Microsoft::CoreUI::Dispatch::Dispatcher::DispatchNextItem+0x685 [mincore\CoreUI\Dev\System\Dispatch\Dispatcher.cs @ 892] 
0c (Inline Function) --------`-------- CoreMessaging!Microsoft::CoreUI::Dispatch::Dispatcher::Callback_DispatchLoop+0x7d7 [mincore\CoreUI\Dev\System\Dispatch\Dispatcher.cs @ 465] 
0d 00000095`845ff520 00007ffd`a8367df6 CoreMessaging!Microsoft::CoreUI::Dispatch::EventLoop::Callback_RunCoreLoop+0xada [mincore\CoreUI\Dev\System\Dispatch\EventLoop.cs @ 779] 
0e (Inline Function) --------`-------- CoreMessaging!Microsoft::CoreUI::Dispatch::UserAdapterBase::DrainCoreMessagingQueue+0x143 [mincore\CoreUI\Dev\System\Dispatch\UserAdapterBase.cs @ 674] 
0f 00000095`845ff640 00007ffd`a83668d1 CoreMessaging!Microsoft::CoreUI::Dispatch::UserAdapter::OnUserDispatch+0x1d6 [mincore\CoreUI\Dev\System\Dispatch\minwin\UserAdapter.cs @ 224] 
10 (Inline Function) --------`-------- CoreMessaging!Microsoft::CoreUI::Dispatch::UserAdapter::OnUserDispatchRaw+0x9c [mincore\CoreUI\Dev\System\Dispatch\minwin\UserAdapter.cs @ 153] 
11 00000095`845ff730 00007ffd`a83666f3 CoreMessaging!Microsoft::CoreUI::Dispatch::UserAdapter_DoWork+0xf1 [mincore\CoreUI\Dev\System\Dispatch\minwin\UserAdapterN.cpp @ 424] 
12 00000095`845ff810 00007ffd`ac99f903 CoreMessaging!Microsoft::CoreUI::Dispatch::UserAdapter_WindowProc+0xa3 [mincore\CoreUI\Dev\System\Dispatch\minwin\UserAdapterN.cpp @ 659] 
13 00000095`845ff890 00007ffd`ac99f2ac USER32!UserCallWinProcCheckWow+0x4e3 [clientcore\windows\core\ntuser\client\clmsg.cxx @ 279] 
14 00000095`845ffa20 00007ffd`ac9b4543 USER32!DispatchClientMessage+0x9c [clientcore\windows\core\ntuser\client\daytona\objfre\amd64\client.cxx @ 3444] 
15 00000095`845ffa80 00007ffd`add30664 USER32!__fnDWORD+0x33 [onecoreuap\internal\windows\inc\ntuser\inc\ntcb.h @ 1214] 
16 00000095`845ffae0 00007ffd`abc01104 ntdll!KiUserCallbackDispatcherContinue [minkernel\ntos\rtl\amd64\trampoln.asm @ 601] 
17 00000095`845ffb68 00007ffd`ac9b54ee win32u!ZwUserGetMessage+0x14 [onecoreuap\windows\core\umode\moderncore\objfre\amd64\usrstubs.asm @ 190] 
18 00000095`845ffb70 00007ff7`3bbe46c6 USER32!GetMessageW+0x2e [onecoreuap\internal\windows\inc\private\core\ntuser\client\ntcftxt.h @ 538] 
19 00000095`845ffbd0 00007ff7`3bbecc42 WindowsTerminal!wWinMain+0x1c6 [E:\BA\35\s\src\cascadia\WindowsTerminal\main.cpp @ 150] 
1a (Inline Function) --------`-------- WindowsTerminal!invoke_main+0x21 [d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 118] 
1b 00000095`845ffce0 00007ffd`aced7034 WindowsTerminal!__scrt_common_main_seh+0x106 [d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 288] 
1c 00000095`845ffd20 00007ffd`adcfb1b1 KERNEL32!BaseThreadInitThunk+0x14 [clientcore\base\win32\client\thread.c @ 64] 
1d 00000095`845ffd50 00000000`00000000 ntdll!RtlUserThreadStart+0x21 [minkernel\ntdll\rtlstrt.c @ 1153] 
```

### PR DESCRIPTION
**Pull request by mkitzan**
## Summary of the Pull Request
An asynchronous event handler capturing raw `this` in `TermControl` was causing an exception to be thrown when a scroll update event occurred after closing the active tab. This PR replaces all non-auto_revoke lambda captures in `TermControl` to capture (and validate) a `winrt::weak_ref` instead of using raw `this`.

 
## PR Checklist
* [x] Closes #2947
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Requires documentation to be updated
* [x] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #2947

## Detailed Description of the Pull Request / Additional comments
`TermControl` is already a WinRT type so no changes were required to enable the `winrt::weak_ref` functionality. There was only one strange change I had to make. In the destructor's helper function `Close`, I had to remove two calls to [`Stop`](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.dispatchertimer.stop#Windows_UI_Xaml_DispatcherTimer_Stop) which were throwing under [some circumstances](https://github.com/microsoft/terminal/issues/2947#issuecomment-562914135). Fortunately, these calls don't appear to be critical, but definitely a spot to look into when reviewing this PR.

Beyond scrolling, any anomalous crash related to the following functionality while closing a tab or WT may be fixed by this PR:
- Settings updating
- Changing background color

## Validation Steps Performed
Before these changes I was able to consistently repro the issue in #2947. Now, I can no longer repro the issue.

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
Thanks! For this one, actually, I’m wondering if we should use C++/WinRT’s auto_revoke machinery. Since we are largely dealing with other WinRT objects and not manually bound std::functions, we can probably use more of the cool platform accordances.

These auto_revokers get torn down during destruction, which ensures that a destructed TermControl has all of its handlers unbound before it becomes invalid.

**Comment by DHowett-MSFT** [comment]
(There are a couple where we explicitly specify the tear down order, but those shouldn’t need to be weak.)

**Comment by mkitzan** [comment]
I'll start by rolling back the auto_revoke handlers that I changed to use weak_ref (didn't realize auto_revoke made the event safe), and if I see some easy wins for the others I'll rework them to.

**Comment by DHowett-MSFT** [comment]
Thanks :smile:

**Comment by mkitzan** [comment]
Was able to make one extra event auto_revoke, so all events `TermControl` owns are auto_revoke. The only real blocker to making the rest auto_revoke is that the XAML Controls in `TermControl` are using [`CoreDispatcher.RunAsync`](https://docs.microsoft.com/en-us/uwp/api/windows.ui.core.coredispatcher.runasync) for their handler binding.

**Comment by mkitzan** [comment]
Azp unit testing got caught up again.
homer

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 1]
```diff
@@ -173,37 +171,41 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
...
         // Dispatch a call to the UI thread to apply the new settings to the
         // terminal.
-        _root.Dispatcher().RunAsync(CoreDispatcherPriority::Normal, [this]() {
-            // Update our control settings
-            _ApplyUISettings();
+        _root.Dispatcher().RunAsync(CoreDispatcherPriority::Normal, [weakThis]() {
+            if (auto control{ weakThis.get() })
+            {
+                // Update our control settings
+                control->_ApplyUISettings();
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalControl/TermControl.cpp]: not 100% sure on how i feel about indirecting through `control->` every time; in debug builds each one will be a call to `winrt::com_ptr::operator->()`...
but i do not know how much, if at all, I care. Thoughts?

Comment (DHowett-MSFT) [reply src/cascadia/TerminalControl/TermControl.cpp]: (we could capture `weakThis,this` and then only _use_ `this` implicitly if the weak got locked. @zadjii-msft?)

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 2]
```diff
@@ -173,37 +171,41 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
...
     {
         _settings = newSettings;
+        auto weakThis{ get_weak() };
 
         // Dispatch a call to the UI thread to apply the new settings to the
         // terminal.
-        _root.Dispatcher().RunAsync(CoreDispatcherPriority::Normal, [this]() {
-            // Update our control settings
-            _ApplyUISettings();
+        _root.Dispatcher().RunAsync(CoreDispatcherPriority::Normal, [weakThis]() {
```
[the remark this answers is not in the document]
Comment (mkitzan) [reply src/cascadia/TerminalControl/TermControl.cpp]: That form reads better. I'll include it in the next commit.

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 3]
```diff
@@ -156,11 +157,8 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
...
         // Subscribe to the connection's disconnected event and call our connection closed handlers.
-        _connectionStateChangedRevoker = _connection.StateChanged(winrt::auto_revoke, [weakThis = get_weak()](auto&& /*s*/, auto&& /*v*/) {
-            if (auto strongThis{ weakThis.get() })
-            {
-                strongThis->_ConnectionStateChangedHandlers(*strongThis, nullptr);
-            }
+        _connectionStateChangedRevoker = _connection.StateChanged(winrt::auto_revoke, [this](auto&& /*s*/, auto&& /*v*/) {
+            _ConnectionStateChangedHandlers(*this, nullptr);
         });
     }
```
[the remark this answers is not in the document]
Comment (DHowett-MSFT) [reply src/cascadia/TerminalControl/TermControl.cpp]: If we _cannot_ do this because the argument types don't match up, we should 100% just make the member function's arguments match :smile:

[the remark this answers is not in the document]
Comment (mkitzan) [reply src/cascadia/TerminalControl/TermControl.cpp]: This one isn't working, because `_ConnectionStateChangedHandlers` wants a `TermControl` object but WinRT is trying to provide something implementing `ITerminalConnection` to it. This is probably because the `{ this, pointer-to-member }` form is only using `this` in conjunction with accessing the member function and not using `this` as a function argument. Instead WinRT is wanting to pass the object owning the event, in this case a `ITerminalConnection`, as the sender argument to the member function.
It's such a clean form, but sadly it only applies to events following a very specific format.

[the remark this answers is not in the document]
Comment (DHowett-MSFT) [reply src/cascadia/TerminalControl/TermControl.cpp]: Oh, I see -- this isn't a local handler, it is an event _forwarder_. Okay, yeah, no, i retract my whole comment. Thank you. :)

[the remark this answers is not in the document]
Comment (DHowett-MSFT) [reply src/cascadia/TerminalControl/TermControl.cpp]: ("forward the connection's event _as my event_")

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 1 above)
Comment (mkitzan) [reply src/cascadia/TerminalControl/TermControl.cpp]: I prefer the way the `weakThis,this` lambdas read. All the `control->` just clutters things, not mention your comment about `winrt::com_ptr::operator->()`. WinRT could almost use a class to support this form of lambda. It would be extensible to all the places where we're having trouble with the `{ this, pointer-to-member }` event format. Anyways, I'll include the fix to these in the next revision commit.

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 4]
```diff
@@ -1576,19 +1596,6 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
...
-                localCursorTimer->Stop();
-                // cursorTimer timer, now stopped, is destroyed.
-            }
-
-            if (auto localAutoScrollTimer{ std::exchange(_autoScrollTimer, nullptr) })
-            {
-                localAutoScrollTimer.Stop();
-                // _autoScrollTimer timer, now stopped, is destroyed.
-            }
-
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalControl/TermControl.cpp]: i'm surprised tearing down the timers isn't necessary anymore, but I'm willing to believe it :smile:

Comment (mkitzan) [reply src/cascadia/TerminalControl/TermControl.cpp]: Those `Stop` calls were only throwing in the event that `TermControl` was being destructed at the end of an event handler, which was strange. Could just wrap them in try-catch blocks if the `Stop` calls really should be there 🤔

**Comment by mkitzan** [comment]
Thanks for the reviews. I've pushed some changes.

**Comment by DHowett-MSFT** [comment]
I'm closing and reopening to convince the CLA bot.

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 4 above)
Comment (zadjii-msft) [reply src/cascadia/TerminalControl/TermControl.cpp]: The most correct solution might be to make both the timers `Tick` events take a `get_weak()` as opposed to `this`, right? If we had done that from the start, we probably wouldn't have ever needed these lines...

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 1 above)
Comment (zadjii-msft) [reply src/cascadia/TerminalControl/TermControl.cpp]: I think I prefer it like this - not capturing `this` at all makes it harder for us to accidentally do the wrong thing.

Comment (DHowett-MSFT) [reply src/cascadia/TerminalControl/TermControl.cpp]: I guess there's a "convenient" middle ground...

```
if (auto strongThis{ weakThis.get() })
{
    auto& that{ *strongThis };
    that->x;
    that->y;
}
```

I _am_ worried about the constant indirection through `operator->`... but at the same time, `WRL::ComPtr` _literally is that for all com calls_, sooooooooo maybe i should not be worried?

Comment (DHowett-MSFT) [reply src/cascadia/TerminalControl/TermControl.cpp]: It's just that this is a member function, but we have to write it in a weird way that makes it not look like a member function.

**Comment by mkitzan** [comment]
Yeah, `get_weak` for `Tick` makes sense. I wasn't originally planning on making changes to the existing `{ this, &TermControl::EventHandler }`. However, it would be an easy fix to convert these to `{ get_weak(), &TermControl::EventHandler }`.

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 1 above)
Comment (mkitzan) [reply src/cascadia/TerminalControl/TermControl.cpp]: Let me know which form to go with, and I'll include it in the next commit.
