### PR TITLE
Fix a crash on settings reload

### LINKED ISSUE #13543: [1.16] JSON converter error during hot reload causes crash
Instead of displaying the error, we crash. This only applies to conversion errors (such as "unknown enum value" or "you put an int where we expected a boolean"), not syntax errors.

### PR DESCRIPTION
**Pull request by lhecker**
07d58a8 contains a regression where the settings' `Themes()` property is
accessed without checking whether it's a `nullptr`. This can happen because
the invalid settings modal is shown with a empty settings model object.

This commit fixes the issue by deferring the update of `_settings` until
after we ensured that the `_settings` object is valid (besides warnings).

Closes #13543

## Validation Steps Performed
* Replace any string value with `123`
* Application doesn't crash ✅

### CODE REVIEW

**Review by zadjii-msft — APPROVED** [review]
Huh. This is clever

File: src/cascadia/LocalTests_SettingsModel/DeserializationTests.cpp [hunk 1]
```diff
@@ -1900,15 +1899,6 @@ namespace SettingsModelLocalTests
...
     }
 
-    void DeserializationTests::TestValidDefaults()
-    {
-        // GH#8146: A LoadDefaults call should populate the list of active profiles
-
-        const auto settings{ CascadiaSettings::LoadDefaults() };
-        VERIFY_ARE_EQUAL(settings.ActiveProfiles().Size(), settings.AllProfiles().Size());
-        VERIFY_ARE_EQUAL(settings.AllProfiles().Size(), 2u);
-    }
```
Comment (carlos-zamora) [inline src/cascadia/LocalTests_SettingsModel/DeserializationTests.cpp:1910]: Would it be valuable to still have a test that just straight-up deserializes the defaults.json? On one hand, I like the idea of ensuring that defaults.json is valid. On the other hand, we've had a bad track record of looking at our local tests. But I'm concerned that we could somehow break defaults.json and never notice? Is that even possible tbh? haha

File: src/cascadia/TerminalApp/AppLogic.cpp [hunk 2]
```diff
@@ -866,11 +866,6 @@ namespace winrt::TerminalApp::implementation
         //      UI yet. We'll display the error in _OnLoaded.
         _settingsLoadedResult = _TryLoadSettings();
 
-        if (FAILED(_settingsLoadedResult))
-        {
-            _settings = CascadiaSettings::LoadDefaults();
-        }
```
Comment (carlos-zamora) [inline src/cascadia/TerminalApp/AppLogic.cpp:872]: Obviously, we can't call `LoadDefaults()` anymore so it makes sense to remove this branch. That said, can't we still hit these two `catch` branches in `_TryLoadSettings()` where we would've `FAILED(HR)`?

https://github.com/microsoft/terminal/blob/9a59b094680fe804e49d5bc995e011984c610e74/src/cascadia/TerminalApp/AppLogic.cpp#L827-L837

I see that the first branch also sets `_settingsLoadExceptionText` and I'm also concerned that now we're losing that.

**Review by carlos-zamora — CHANGES_REQUESTED** [review]
Mainly blocking over the question on the removed `FAILED` check. Just wanna make sure we have our bases covered.

**Comment by lhecker** [comment]
@zadjii-msft @carlos-zamora With the issue Carlos found, I've chosen a new approach which should also work. This slightly changes the behavior of WT however: From now on we'll not reload any settings until after the settings.json could be successfully parsed.

**Comment by carlos-zamora** [comment]
> @zadjii-msft @carlos-zamora With the issue Carlos found, I've chosen a new approach which should also work. This slightly changes the behavior of WT however: From now on we'll not reload any settings until after the settings.json could be successfully parsed.

Hmm... That's not noticeable right? A user generally experiences the following behavior after updating the settings.json...
- no errors in the JSON --> hot reload
- lingering comma --> we're smart and we ignore the comma --> hot reload
- valid JSON, but wrong type for a setting --> ignore the setting
- JSON cannot be read --> fall back to defaults.json

**Review by carlos-zamora — APPROVED** [review]
Yeah, I think this works just fine. Thanks!

**Review by zadjii-msft — APPROVED** [review]
huh. Another clever solution. Neato, thanks!

**Comment by lhecker** [comment]
> Hmm... That's not noticeable right? [...]
> * valid JSON, but wrong type for a setting --> ignore the setting
> * JSON cannot be read --> fall back to defaults.json

I think the only reason it's _generally_ not very noticeable is because we call `_root->SetSettings(_settings, true)` only if the settings reload was successful.

But if you check `AppLogic.cpp` you can see how `_settings` is used in a lot of other places as well. I get the feeling that this PR might fix a number of subtle bugs and not just #13543. For instance `AppLogic::FindTargetWindow` depends on `_settings`, but before this PR `_settings` might have been invalid.

**Review by DHowett — COMMENTED** [review]
Thanks!
