### PR TITLE
AtlasEngine: Scale glyphs to better fit the cell size

### LINKED ISSUE #12512: experimental.useAtlasEngine breaks draw-box rendering
### Windows Terminal version

1.13.10336.0

### Windows build number

10.0.22000.0

### Other Software

Any application which uses pseudo graphics.

### Steps to reproduce

Enable this feature and restart Terminal. Open any program which uses pseudo graphics. Far, Musikcube etc.

### Expected Behavior

There should be no distortion

### Actual Behavior

ss-1

ss-2

### PR DESCRIPTION
**Pull request by lhecker**
This commit contains 3 improvements for glyph rendering:
* Scale block element and box drawing characters to fit the cell size
  "perfectly" without leaving pixel gaps between cells.
* Use `IDWriteTextLayout::GetOverhangMetrics` to determine whether glyphs
  are outside the given layout box and if they are, offset their position
  to fit them back in. If that still fails to fit, we downscale them.
* Always scale up glyphs that are more than 2 cells wide
  This ensures that long ligatures that mimic box drawing characters like
  "===" under Cascadia Code are upscaled just like regular box drawings.
  Unfortunately this results in ligature-heavy text (like Myanmar) to get an
  "uneven" appearance because some ligatures can suddenly appear too large.
  It's difficult to come up with a good heuristic here.

Closes #12512

## Validation Steps Performed
* Print UTF-8-demo.txt
* Block characters don't leave gaps ✅
* Print a lorem-ipsum in Myanmar
* Glyphs aren't cut off anymore ✅
* Print a long "===" ligature under Cascadia Code
* The ligature is as wide as the number of cells used ✅

### CODE REVIEW

File: src/renderer/atlas/AtlasEngine.cpp [hunk 1]
```diff
@@ -1046,9 +1047,11 @@ void AtlasEngine::_recreateFontDependentResources()
                 // We want that. Otherwise fallback fonts might be rendered with an incorrect baseline and get cut off vertically.
                 THROW_IF_FAILED(textFormat->SetLineSpacing(DWRITE_LINE_SPACING_METHOD_UNIFORM, _r.cellSizeDIP.y, _api.fontMetrics.baselineInDIP));
 
-                if (!_api.fontAxisValues.empty())
+                if (const auto textFormat3 = textFormat.try_query<IDWriteTextFormat3>())
                 {
-                    if (const auto textFormat3 = textFormat.try_query<IDWriteTextFormat3>())
+                    textFormat3->SetAutomaticFontAxes(DWRITE_AUTOMATIC_FONT_AXES_OPTICAL_SIZE);
```
Comment (lhecker) [inline src/renderer/atlas/AtlasEngine.cpp:1052]: This change might be unrelated, but I felt like that this still fits in the theme of the PR.
It ensures that a good "optical size" is chosen for variable width fonts which I feel like might impact overhangs.

File: src/renderer/atlas/AtlasEngine.r.cpp [hunk 2]
```diff
@@ -266,23 +267,177 @@ void AtlasEngine::_drawGlyph(const AtlasQueueItem& item) const
...
+    f32x2 offset{ 0, 0 };
+    f32x2 scale{ 1, 1 };
+
+    // Block Element and Box Drawing characters need to be handled separately from
+    // others, because unlike them they're supposed to fill the entire layout box.
+    // Or in other words: If they overflow the layout box, that's actually great!
+    // Inversely we need to scale them up (not down) if they don't fill the box.
+    if (charsLength == 1 && key->chars[0] >= 0x2500 && key->chars[0] <= 0x259F)
+    {
+        // TODO: This code doesn't quite work yet unfortunately.
```
Comment (lhecker) [inline src/renderer/atlas/AtlasEngine.r.cpp:339]: The TODO-issue is #12512.

**Comment by lhecker** [comment]
Does this look correct to you? Because I can't replicate the exact same look you get given that config. For instance your second row of text is thin, but you specified that you set the font to extra-bold. 🤔
```json
{
    "antialiasingMode": "aliased",
    "experimental.useAtlasEngine": true,
    "font": 
    {
        "face": "Cascadia Code",
        "size": 17,
        "weight": "extra-bold"
    }
}
```

But I believe the fix is to:
* Add 0.5px of "margin" on each side when downscaling glyphs. That way we ensure that when DirectWrite/D2D snap glyph outlines to pixels, that those pixels actually end up within the layout box.
* `AtlasEngine::_resolveFontMetrics` seems to not respect font weight. When I change Cascadia Code from Regular to Bold the cell size doesn't change at all. But it should - the bold "M" character is a few pixels fatter after all.

**Comment by lhecker** [comment]
> 1. font size does not match between two modes. Sorry, this may not be related, but maybe it is. In the following table I listed sizes which visually match with each other in the respective modes.

Yeah I did this intentionally. The current text renderer (DxEngine) draws glyphs with fractional font sizes so that they fit perfectly into their glyph cells. This solves some issues (glyphs like "========" in Cascadia Code not having the correct size in AtlasEngine) but brings other issues (glyphs being blurry as you noted). It's a trade-off and there's unfortunately no correct decision. 🙁 I went with the "pixel-perfect" approach which makes ASCII and CJK text look nicer.

The latest commit should make your arrows look a bit nicer. Unfortunately they're sometimes still slightly cut off but at least for me it's tolerable now... We'll have to see how it goes! 🙂

File: src/renderer/atlas/AtlasEngine.r.cpp [hunk 3]
```diff
@@ -266,23 +275,207 @@ void AtlasEngine::_drawGlyph(const AtlasQueueItem& item) const
...
+        // Long glyphs should be drawn with their proper design size, even if that makes them a bit blurry,
+        // because otherwise we fail to support "pseudo" block characters like the "===" ligature in Cascadia Code.
+        // If we didn't force upscale that ligatures it would seemingly shrink shorter and shorter, as its
+        // glyph advance is often slightly shorter by a fractional pixel or two compared to our terminal's cells.
+        // It's a trade off that keeps most glyphs "crisp" while retaining support for things like "===".
+        // At least I can't think of any better heuristic for this at the moment...
+        if (cellCount > 2)
+        {
+            scalingRequired = true;
+            scale = _r.fontMetrics.scale;
```
Comment (lhecker) [inline src/renderer/atlas/AtlasEngine.r.cpp:368]: I just realized that this approach is slightly incorrect.
TODO (for myself): Set `scale` to the `max(.x, .y)` so that the glyph is resized while preserving the aspect ratio.

File: src/renderer/atlas/DWriteTextAnalysis.cpp [hunk 4]
```diff
@@ -0,0 +1,172 @@
+#include "pch.h"
```
Comment (zadjii-msft) [inline src/renderer/atlas/DWriteTextAnalysis.cpp:1]: note to reviewers: this whole file is just code that was deleted from the `TextAnalyzer` in `AtlasEngine.cpp`

File: src/renderer/atlas/AtlasEngine.r.cpp [hunk 5]
```diff
@@ -271,23 +271,219 @@ void AtlasEngine::_drawGlyph(const AtlasQueueItem& item) const
...
-        origin.x = rect.left - i * _r.cellSizeDIP.x;
-        origin.y = rect.top;
+        origin.x = rect.left - i * _r.cellSizeDIP.x + offset.x;
+        origin.y = rect.top + offset.y;
 
         _r.d2dRenderTarget->PushAxisAlignedClip(&rect, D2D1_ANTIALIAS_MODE_ALIASED);
         _r.d2dRenderTarget->Clear();
+        if (scalingRequired)
+        {
+            // TODO: dx/dy should technically be pixel snapped
```
Comment (zadjii-msft) [inline src/renderer/atlas/AtlasEngine.r.cpp:467]: Is this TODO now or TODO later?

File: src/renderer/atlas/AtlasEngine.r.cpp [hunk 6]
```diff
@@ -245,19 +244,20 @@ void AtlasEngine::_drawGlyph(const AtlasQueueItem& item) const
...
     wil::com_ptr<IDWriteTextLayout> textLayout;
-    THROW_IF_FAILED(_sr.dwriteFactory->CreateTextLayout(&key->chars[0], charsLength, textFormat, cells * _r.cellSizeDIP.x, _r.cellSizeDIP.y, textLayout.addressof()));
+    THROW_IF_FAILED(_sr.dwriteFactory->CreateTextLayout(&key->chars[0], charsLength, textFormat, layoutBox.x, layoutBox.y, textLayout.addressof()));
     if (_r.typography)
     {
         textLayout->SetTypography(_r.typography.get(), { 0, charsLength });
     }
 
-    auto options = D2D1_DRAW_TEXT_OPTIONS_CLIP;
+    auto options = D2D1_DRAW_TEXT_OPTIONS_NONE;
```
Comment (zadjii-msft) [inline src/renderer/atlas/AtlasEngine.r.cpp:260]: no more `_CLIP`?

**Review by zadjii-msft — COMMENTED** [review]
All in all, the code looks good to me, just a couple questions before I give the ✅

File: src/renderer/atlas/AtlasEngine.r.cpp (hunk 6 above)
Comment (lhecker) [reply src/renderer/atlas/AtlasEngine.r.cpp:260]: Yeah it doesn't work with scaling.

File: src/renderer/atlas/AtlasEngine.r.cpp (hunk 5 above)
Comment (lhecker) [reply src/renderer/atlas/AtlasEngine.r.cpp:467]: I wrote that comment for future-someone and not specifically for us.
I'll try to figure out the correct approach for this before it gets merged, but if I don't it's not that important anyways - the scaled glyphs are pretty crisp either way.

File: src/renderer/atlas/AtlasEngine.cpp [hunk 7]
```diff
@@ -966,9 +838,12 @@ void AtlasEngine::_recreateFontDependentResources()
 
         _r.cellSizeDIP.x = static_cast<float>(_api.fontMetrics.cellSize.x) / scaling;
         _r.cellSizeDIP.y = static_cast<float>(_api.fontMetrics.cellSize.y) / scaling;
+        _r.fontMetrics = _api.fontMetrics;
```
Comment (DHowett) [inline src/renderer/atlas/AtlasEngine.cpp:841]: duplicate line with R844

File: src/renderer/atlas/AtlasEngine.h [hunk 8]
```diff
@@ -992,7 +998,7 @@ namespace Microsoft::Console::Render
             Buffer<DWRITE_GLYPH_OFFSET> glyphOffsets;
             std::vector<DWRITE_FONT_FEATURE> fontFeatures; // changes are flagged as ApiInvalidations::Font|Size
             std::vector<DWRITE_FONT_AXIS_VALUE> fontAxisValues; // changes are flagged as ApiInvalidations::Font|Size
-            FontMetrics fontMetrics; // changes are flagged as ApiInvalidations::Font|Size
+            FontMetrics fontMetrics; // changes are flagged as ApiInvalidations::Font
```
Comment (DHowett) [inline src/renderer/atlas/AtlasEngine.h:1001]: not Size?

**Review by DHowett — APPROVED** [review]
I'm cool with this, let's get it into selfhosting!

File: src/renderer/atlas/AtlasEngine.r.cpp [hunk 9]
```diff
@@ -408,28 +405,34 @@ void AtlasEngine::_drawGlyph(const AtlasQueueItem& item) const
...
 
-        // Due to D2D1_DRAW_TEXT_OPTIONS_NO_SNAP our baseline won't get
-        // pixel aligned anymore and so we have to do it ourselves here.
-        offset.x = roundf(offset.x * _r.pixelPerDIP) * _r.dipPerPixel;
-        offset.y = roundf(offset.y * _r.pixelPerDIP) * _r.dipPerPixel;
+        // As explained below, we use D2D1_DRAW_TEXT_OPTIONS_NO_SNAP to prevent a weird issue with baseline snapping.
+        // But we do want it technically, so this re-implements baseline snapping... I think?
+        // It calculates the new `baseline` height after transformation by `scale.y` relative to the center point `halfSize.y`.
+        //
+        // This works even if `scale.y == 1`, because then `baseline == baselineInDIP + offset.y` and `baselineInDIP`
```
Comment (DHowett) [inline src/renderer/atlas/AtlasEngine.r.cpp:430]: to some extent i just have to, like... trust your math lol

**Review by DHowett — APPROVED** [review]

**Comment by lhecker** [comment]
@zadjii-msft FYI I just pushed some commits. It addresses these issues:
* I (hopefully correctly) fixed support for baseline snapping - CJK looks a better now!
* Fixed centering of glyphs - the `offset` was applied to the `origin` _before_ the transformation was applied, which meant that the `offset` was applied twice: Once to center the origin of `DrawTextLayout` and once to offset the scaling center (= after scaling the glyph isn't centered anymore).
* The use `targetSize` was entirely incorrect - glyphs like "W" are just as wide as "M" (= cell width), but since `targetSize` is 1px smaller than the cell size, it accidentally downsized all W by a factor of like 0.999995.

File: src/renderer/atlas/AtlasEngine.r.cpp (hunk 9 above)
Comment (lhecker) [reply src/renderer/atlas/AtlasEngine.r.cpp:427]: Yeah, this is really hard to read:
```
baseline = halfSize.y + (_r.fontMetrics.baselineInDIP + offset.y - halfSize.y) * scale.y
```

If it helps here's an image explanation:
image

`offset.y` shifts the glyph (and thus the baseline) up and down as needed to fit the glyph into the cell. So it's a simple `+ offset.y` and you arrive at my complex line of code there.

**Review by zadjii-msft — APPROVED** [review]
