### PR TITLE
Fix leak in buffering text for UIA when unfocused

### LINKED ISSUE #16217: Memory Leak
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.19045.0

### Other Software

Powershell 5.1.19041.3570

### Steps to reproduce

This has occurred a couple times, mostly when I leave docker logs open overnight.

I do have a memory dump - 300MB compressed. I cannot upload the dump publicly though.

### Expected Behavior

_No response_

### Actual Behavior

Memory usage continues to climb and Windows starts paging like crazy.

image

I suspect something is off with the buffer limit (I'm assuming there's a limit somewhere).

### PR DESCRIPTION
**Pull request by zadjii-msft**
Notes in #16217 have the investigation.

TL;DR: we'd always buffer text. Even if we're disabled (unfocused). When we're
disabled, we'd _never_ clear the buffered text. Oops.

Closes #16217

### CODE REVIEW

File: src/renderer/uia/UiaRenderer.cpp [hunk 1]
```diff
@@ -47,6 +47,12 @@ UiaEngine::UiaEngine(IUiaEventDispatcher* dispatcher) :
 [[nodiscard]] HRESULT UiaEngine::Disable() noexcept
 {
     _isEnabled = false;
+
+    // If we had buffered any text from NotifyNewText, dump it. When we do come
+    // back around to actually paint, we will just no-op. No sense in keeping
+    // the data buffered.
+    _newOutput.clear();
```
Comment (lhecker) [inline src/renderer/uia/UiaRenderer.cpp:54]: This will not release any memory however. Additionally, it also doesn't clear `_queuedOutput`. Do we need to do that?

This comment contains one approach to clear the memory in the `EndPaint()` method: https://github.com/microsoft/terminal/issues/16209#issuecomment-1773902806
In the `Disable()` case I'd release the memory whenever, let's say, `_newOutput.capacity() >= 4096` or something.

Comment (zadjii-msft) [reply src/renderer/uia/UiaRenderer.cpp:54]: Derp yea, we can resize it too. 

I didn't think we needed to clear out `_queuedOutput`, since we might technically be after `EndPaint`, but in the middle of a `Present`.

Comment (lhecker) [reply src/renderer/uia/UiaRenderer.cpp:54]: Ah right, good point.

**Review by DHowett — APPROVED** [review]

**Review by lhecker — APPROVED** [review]
