### PR TITLE
Fix the ConPTY extended attributes optimization

### LINKED ISSUE #13229: Terminal can omit backgrounds, links and underlines on empty cells
**Original Title**: Hyperlink on spaces over-optimization breaks rendering and usability

### Windows Terminal version

1.14.1452.0

### Windows build number

10.0.22000.708

### Other Software

My ActiveScript Shell, just to use JScript to easily script the console, but problem is with VT optimization.

### Steps to reproduce

When a hyperlink contains trailing spaces, they are shown or trimmed depending on the number of trailing spaces.
Starting at 9 spaces or more, they get used as spacing, but are not considered part of the hyperlink, while 8 or less are properly rendered and clickable as part of the hyperlink.

### Expected Behavior

Hyperlinks extending on space characters can be a design decision for consistency and usability, the Terminal should not decide to shorten the number of columns the hyperlink is effectively available on.
Note non-preview build 1.12.10983.0 does not trim the spaces, so this is a new bug introduced in the Preview version 1.14.1452.0.

### Actual Behavior

Current Preview build seems over-agressive in optimizing the spaces, and swallows spaces without abiding by the original VT output of apps.

image
See how the spaces above the red underlines are different between 8 and 9 spaces.

### PR DESCRIPTION
**Pull request by zadjii-msft**
... which should have never worked in the first place

Quick filing a PR for review. This is the bulk of the actual code changes. Figured it was best to review the conpty changes sooner than later and I can add tests in the morning.

Test cases:
```
printf "\e[7m         test         \e[m\n"
```

```
printf "\e[7m"; printf ' %.0s' $(seq 1 $COLUMNS); printf "\e[m\n"
```

After:
image

Closes #13229

Definitely fixes:
* [x] #13643
* [x] https://github.com/PowerShell/PowerShell/issues/17812

### CODE REVIEW

**Comment by zadjii-msft** [comment]
Whoops, I might want to revert e476682. I started from there, but that might not actually be relevant to this bug.

File: src/buffer/out/TextAttribute.hpp [hunk 1]
```diff
@@ -161,6 +164,13 @@ class TextAttribute final
     {
         return WI_IsAnyFlagSet(_wAttrLegacy, COMMON_LVB_GRID_HORIZONTAL | COMMON_LVB_GRID_LVERTICAL | COMMON_LVB_GRID_RVERTICAL | COMMON_LVB_UNDERSCORE);
     }
+    constexpr bool HasAnyExtendedAttributes() const noexcept
+    {
+        return GetExtendedAttributes() != ExtendedAttributes::Normal ||
+               !IsAnyGridLineEnabled() ||
+               GetHyperlinkId() != 0 ||
+               IsReverseVideo();
```
Comment (lhecker) [inline src/buffer/out/TextAttribute.hpp:172]: BTW `!IsAnyGridLineEnabled() || IsReverseVideo()` is the same as `_wAttrLegacy != 0`, _if_ you fix the constructor to not use `META_ATTRS`. Coincidentally it shouldn't use that anyways, but rather:
```cpp
COMMON_LVB_GRID_HORIZONTAL | COMMON_LVB_GRID_LVERTICAL | COMMON_LVB_GRID_RVERTICAL | COMMON_LVB_REVERSE_VIDEO | COMMON_LVB_UNDERSCORE
```
(This is because `TextAttribute` doesn't store DBCS attributes anymore.)

**Review by lhecker — APPROVED** [review]

**Review by carlos-zamora — APPROVED** [review]

File: src/buffer/out/TextAttribute.hpp [hunk 2]
```diff
@@ -161,6 +164,13 @@ class TextAttribute final
     {
         return WI_IsAnyFlagSet(_wAttrLegacy, COMMON_LVB_GRID_HORIZONTAL | COMMON_LVB_GRID_LVERTICAL | COMMON_LVB_GRID_RVERTICAL | COMMON_LVB_UNDERSCORE);
     }
+    constexpr bool HasAnyExtendedAttributes() const noexcept
+    {
+        return GetExtendedAttributes() != ExtendedAttributes::Normal ||
```
Comment (DHowett) [inline src/buffer/out/TextAttribute.hpp:169]: (fwiw: since `GetExtendedAttributes` doesn't do any translation or synthesis on its own, why should we use it instead of just using `_extendedAttrs` directly?)

File: src/renderer/vt/paint.cpp [hunk 3]
```diff
@@ -424,10 +424,15 @@ using namespace Microsoft::Console::Types;
     // the inbox telnet client doesn't understand the Erase Character sequence,
     // and it uses xterm-ascii. This ensures that xterm and -256color consumers
     // get the enhancements, and telnet isn't broken.
+    //
+    // GH#13229: ECH and EL don't fill the space with "meta" attributes like
```
Comment (DHowett) [inline src/renderer/vt/paint.cpp:428]: I mean, don't we still have the "background" version of this problem? `\e[40m                               x                \e[m` doesn't require any extended attributes.

Comment (zadjii-msft) [reply src/renderer/vt/paint.cpp:428]: more tests you got it
