### PR TITLE
Replace the UWP file export with the shell32 one

### LINKED ISSUE #11356: [1.12] Exporting text fails when running elevated (presumably we can't open the file picker elevated)
_discovered in the 1.12 bug bash on 9/28_

See title.

I think this is the same thing as the File picker dialog for the SUI

I could have swore this came up on the review, we may have yolo'd it anyways.

introduced in #11062, megathread: #9700

### LINKED ISSUE #11358: [1.12] We can probably just ditch the confirmation dialog when exporting text
_discovered in the 1.12 bug bash on 9/28_
image

Team discussion was "meh, just remove it"

### PR DESCRIPTION
**Pull request by zadjii-msft**
Just like in #9760, we can't actually use the UWP file picker API, because it will absolutely not work at all when the Terminal is running elevated. That would prevent the picker from appearing at all. So instead, we'll just use the shell32 one manually. 

This also gets rid of the confirmation dialog, since the team felt we didn't really need that. We could maybe replace it with a Toast (#8592), but _meh_

* [x] closes #11356
* [x] closes #11358
* This is a lot like #9760
* introduced in #11062
* megathread: #9700

### CODE REVIEW

**Review by carlos-zamora — APPROVED** [review]
I think the only thing that feels weird to me is that we export a file using `CascadiaSettings::ExportFile()`. I get that we're doing it so that we can leverage `FileUtils.h`, but would it be better for us to move `FileUtils` into the `inc` folder and just have it shared between projects? The only thing I think we would have to move out would be `GetBaseSettingsPath`.

That said, that's probably better as a CodeHealth follow-up, so I don't mind this for now.

File: src/cascadia/TerminalApp/TabManagement.cpp [hunk 1]
```diff
@@ -410,33 +413,45 @@ namespace winrt::TerminalApp::implementation
...
-                        _ShowControlNoticeDialog(RS_(L"NoticeInfo"), RS_(L"ExportSuccess"));
-                        break;
-                    default:
-                        _ShowControlNoticeDialog(RS_(L"NoticeError"), RS_(L"ExportFailure"));
+                        // Default to the Downloads folder
+                        auto folderShellItem{ winrt::capture<IShellItem>(&SHGetKnownFolderItem, FOLDERID_Downloads, KF_FLAG_DEFAULT, nullptr) };
+                        dialog->SetDefaultFolder(folderShellItem.get());
                     }
+                    CATCH_LOG(); // non-fatal
+                    THROW_IF_FAILED(dialog->SetFileTypes(ARRAYSIZE(supportedFileTypes), supportedFileTypes));
```
Comment (lhecker) [inline src/cascadia/TerminalApp/TabManagement.cpp:443]: `std::size` is the modern `ARRAYSIZE`.

**Review by lhecker — APPROVED** [review]
