### PR TITLE
Manually pre-evaluate the starting directory when calling elevate-shim

### LINKED ISSUE #15173: After updating Windows Terminal, pressing Ctrl+Profile will not inherit the working directory
### Windows Terminal version

1.16.10262.0

### Windows build number

10.0.22621.1537

### Other Software

_No response_

### Steps to reproduce

1. Set the startup directory in Windows Terminal settings to ".".
2. Go to a folder in File Explorer (for example: `D:\SomeDir`).
3. Right-click and select "Open with Terminal" from the context menu.
4. Hold down the Ctrl key on the title bar of the new Windows Terminal and create any tab (to create as an administrator).`

### Expected Behavior

In the new Windows Terminal that runs as an administrator, the working directory is inherited as `D:\SomeDir`

### Actual Behavior

In the new Windows Terminal that runs as an administrator, the working directory is reset to `C:\Windows\System32`

### PR DESCRIPTION
**Pull request by zadjii-msft**
_targets #15280_

When ctrl+clicking on a profile, pre-evaluate the starting directory of that profile, and stash that in the commandline we pass to elevate shim.

So in the case of something like "use parent process directory", we'll run `elevate-shim new-tab -p {guid} -d "C:\\the path\\of\\terminal\\."`

Closes #15173

### CODE REVIEW

**Comment by zadjii-msft** [comment]
examples of running the terminal, and where it got elevated to:

image

This is wrong for the second one! The profile doesn't have a `startingDirectory`, which means it should be `%userprofile%`, but got evaluated as the linux path anyways. Butts.

**Comment by zadjii-msft** [comment]
230be3e fixed the earlier issue I saw, where a profile that _wasn't_ a relative path would actually just open in the vcwd. Now this branch works too.

File: src/cascadia/TerminalApp/TerminalPage.cpp [hunk 1]
```diff
@@ -1166,13 +1166,9 @@ namespace winrt::TerminalApp::implementation
...
-    winrt::hstring TerminalPage::_evaluatePathForCwd(const winrt::hstring& path)
+    std::wstring TerminalPage::_evaluatePathForCwd(const std::wstring_view path)
     {
-        const auto currentVirtualDir{ _WindowProperties.VirtualWorkingDirectory() };
-        const auto cwdString{ std::wstring_view{ currentVirtualDir } };
-        return winrt::hstring{
-            Utils::EvaluateStartingDirectory(cwdString, std::wstring_view{ path })
-        };
+        return Utils::EvaluateStartingDirectory(_WindowProperties.VirtualWorkingDirectory(), path);
     }
```
Comment (lhecker) [inline src/cascadia/TerminalApp/TerminalPage.cpp:1172]: `winrt::hstring` is implicitly convertible to `std::wstring_view`, so there's no need for explicit casts like this most of the time. It just doesn't work for something like `std::filesystem::path::operator/=`, because C++ wouldn't know which of the 31 overloads to call, given a `hstring`.

Also, when cppwinrt generates `String` parameters for functions, it'll not use `winrt::hstring` but `winrt::param::hstring` which binds to almost any string type, include `std::wstring`, without making any extra copies on the heap. We can thus just return a `std::wstring` from this function and it'll work without any additional modifications.

**Review by lhecker — APPROVED** [review]

**Review by DHowett — APPROVED** [review]
