### PR TITLE
Fix tab row acrylic material in unfocused windows

### LINKED ISSUE #19544: Tab row loses acrylic material when window is unfocused
### Windows Terminal version

1.23.12811.0

### Windows build number

10.0.26200.0

### Other Software

_No response_

### Steps to reproduce

"Use acrylic material in the tab row": Enabled
"Allow acrylic material in unfocused windows": Enabled

1. Click on terminal window to give it focus
2. Observe tab row has an acrylic material
3. Click on another window so terminal window loses focus
4. Observe tab row no longer has an acrylic material

### Expected Behavior

"Use acrylic material in the tab row": Enabled
"Allow acrylic material in unfocused windows": Enabled

With the above two settings enabled, I would expect the tab row to always have an acrylic material whether focused or unfocused.

### Actual Behavior

The tab row only has an acrylic material when the window has focus. Once focus changes to a different window, the tab row becomes a solid colour again.

### PR DESCRIPTION
**Pull request by AbhishekGiri04**
## Summary
Fixes tab row losing acrylic material when window is unfocused, even when "Allow acrylic material in unfocused windows" is enabled.

## References
Fixes #19544

## Changes
Modified `_updateThemeColors()` in `TerminalPage.cpp` to check both window focus state and `EnableUnfocusedAcrylic` setting.

## Testing
- Verified acrylic persists when window loses focus (with setting enabled)
- Verified acrylic removed when setting disabled (expected behavior)

### CODE REVIEW

File: src/cascadia/TerminalApp/TerminalPage.cpp [hunk 1]
```diff
@@ -4865,7 +4865,14 @@ namespace winrt::TerminalApp::implementation
...
 
-        if (_settings.GlobalSettings().UseAcrylicInTabRow())
+        // Check if we should use acrylic in the tab row
+        // Use acrylic if:
+        // 1. UseAcrylicInTabRow is enabled, AND
+        // 2. Either the window is focused OR EnableUnfocusedAcrylic is enabled
+        const bool shouldUseAcrylic = _settings.GlobalSettings().UseAcrylicInTabRow() &&
+                                      (_activated || _settings.GlobalSettings().EnableUnfocusedAcrylic());
+
+        if (shouldUseAcrylic)
```
Comment (carlos-zamora) [inline src/cascadia/TerminalApp/TerminalPage.cpp]:
```suggestion
        if (_settings.GlobalSettings().UseAcrylicInTabRow() && (_activated || _settings.GlobalSettings().EnableUnfocusedAcrylic()))
```
nit: we don't use `shouldUseAcrylic` anywhere so we can just put the check directly in the if-statement

**Review by carlos-zamora — APPROVED** [review]
✅ Verified it works

Change is pretty straightforward. Thanks for doing it 😊

File: src/cascadia/TerminalApp/TerminalPage.cpp [hunk 2]
```diff
@@ -4865,7 +4865,14 @@ namespace winrt::TerminalApp::implementation
...
 
-        if (_settings.GlobalSettings().UseAcrylicInTabRow())
+        // Check if we should use acrylic in the tab row
+        // Use acrylic if:
+        // 1. UseAcrylicInTabRow is enabled, AND
+        // 2. Either the window is focused OR EnableUnfocusedAcrylic is enabled
+        const bool shouldUseAcrylic = _settings.GlobalSettings().UseAcrylicInTabRow() &&
+                                      (_activated || _settings.GlobalSettings().EnableUnfocusedAcrylic());
+
+        if (_settings.GlobalSettings().UseAcrylicInTabRow() && (_activated || _settings.GlobalSettings().EnableUnfocusedAcrylic()))
```
Comment (PankajBhojwani) [inline src/cascadia/TerminalApp/TerminalPage.cpp:4887]: `if (shouldUseAcrylic)`?

**Review by PankajBhojwani — CHANGES_REQUESTED** [review]

File: src/cascadia/TerminalApp/TerminalPage.cpp [hunk 3]
```diff
@@ -4865,7 +4865,14 @@ namespace winrt::TerminalApp::implementation
...
         }
 
-        if (_settings.GlobalSettings().UseAcrylicInTabRow())
+        // Check if we should use acrylic in the tab row
+        // Use acrylic if:
+        // 1. UseAcrylicInTabRow is enabled, AND
+        // 2. Either the window is focused OR EnableUnfocusedAcrylic is enabled
+        const bool shouldUseAcrylic = _settings.GlobalSettings().UseAcrylicInTabRow() &&
+                                      (_activated || _settings.GlobalSettings().EnableUnfocusedAcrylic());
+
```
Comment (carlos-zamora) [inline src/cascadia/TerminalApp/TerminalPage.cpp]:
```suggestion
```

File: src/cascadia/TerminalApp/TerminalPage.cpp (hunk 2 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalApp/TerminalPage.cpp:4887]: @PankajBhojwani sorry, I did a bad job patching it. Fixed in [3abee35](https://github.com/microsoft/terminal/pull/19647/commits/3abee3510225a7c022b71934419f1417788b2ab6)

**Review by DHowett — APPROVED** [review]

**Comment by willjgit** [comment]
Hi - sorry to reopen this issue but I am still having the exact same problem - tab row's acrylic disappears if the window is out of focus. On Windows Terminal Version 1.24.10621.0. Looks like this was not fixed in v 1.24?
