### PR TITLE
Revoke old event handlers correctly on pane close

### LINKED ISSUE #1278: Crash on `exit` after previously closing a pane with non-leaf sibling
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.175]
Windows Terminal version (if applicable): master
```

# Steps to reproduce

Open terminal and split the main pane vertically. Then split the left-hand pane horizontally. You should now have 3 panes, named A, B, C shown in the configuration and tree structure below:

```none
+---+---+   1: parent
| A |   |   ├── 2: parent
+---+ B |   |   ├── 3: A
| C |   |   |   └── 4: C
+---+---+   └── 5: B
```

Now `exit` pane B, then `exit` either of panes A or C.

# Expected behavior

The second exited pane will close, leaving one pane open.

# Actual behavior

Terminal crashes.

# More information

I believe this is due to a bug in Pane::_CloseChild where close event handlers are not correctly revoked when the remaining child pane is non-leaf. Proposed fix: #1279

### PR DESCRIPTION
**Pull request by peterdn**
## Summary of the Pull Request

Fixes revoking of old close event handlers after a pane is closed (issue #1278).

 
## PR Checklist
* [x] Closes #1278 
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Requires documentation to be updated
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Detailed Description of the Pull Request / Additional comments

Currently, when a pane with non-leaf sibling is closed, various close event handlers are incorrectly revoked leading to dangling references. These are dereferenced next time another close event occurs (i.e. closing a 2nd pane) and causes Terminal to crash.

Additionally it revokes event handlers on old panes and controls (as occurs when a leaf pane is closed).

## Validation Steps Performed

Tested manually. If I understand correctly, an automated test could be written after the framework in #1164 lands.

### CODE REVIEW

File: src/cascadia/TerminalApp/Pane.cpp [hunk 1]
```diff
@@ -342,9 +342,14 @@ void Pane::_CloseChild(const bool closeFirst)
...
-        _firstChild->Closed(_firstClosedToken);
-        _secondChild->Closed(_secondClosedToken);
+        // Revoke the old event handlers on our new children
+        _firstChild->Closed(remainingChild->_firstClosedToken);
+        _secondChild->Closed(remainingChild->_secondClosedToken);
+
+        // Revoke event handlers on old panes and controls
+        oldFirst->Closed(oldFirstToken);
+        oldSecond->Closed(oldSecondToken);
+        closedChild->_control.ConnectionClosed(closedChild->_connectionClosedToken);
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalApp/Pane.cpp]: I'm concerned about the mixing of ownership here. Should the child know well enough what it's doing to make its own revocation?

Comment (zadjii-msft) [reply src/cascadia/TerminalApp/Pane.cpp]: That's a good point - it seems like this is the kinda thing that _should_ be handled by the dtor, or maybe the event should be marked `auto_revoke` or something (though I'm not totally sure how that works).

I'd maybe just add a destructor with just
```c++
_control.ConnectionClosed(_connectionClosedToken);
```
<hr>

Though, now that I'm saying that, there is *previous art* on L296-297 where I'm having tha parent manually revoke its children's event handlers on their behalf, so I think I'm fine with this the way it is.

Comment (peterdn) [reply src/cascadia/TerminalApp/Pane.cpp]: Thanks both @DHowett-MSFT @zadjii-msft. Makes sense that this revocation would ideally be done in a destructor. My first aim was simply to prevent the crashing issue, then I attempted to make both branches of the conditional consistent. Only lines 346+347 are actually required to directly resolve the linked issue.

If you like, I can proceed to either:

1. Remove lines 350-352 to strip the changes back to the minimum necessary to fix the crashing issue, then raise a new issue for the ownership question. Or;
2. Move the revocations to a destructor as part of this PR.

Comment (DHowett-MSFT) [reply src/cascadia/TerminalApp/Pane.cpp]: I'm alright with this, actually. Thank you!
