### PR TITLE
Fix `closeOnExit: always`

### LINKED ISSUE #16068: Terminal ignores Profile termination behavior setting
### Windows Terminal version

1.19.2682.0

### Windows build number

10.0.22621.0

### Other Software

WSL

### Steps to reproduce

Set Profile termination behavior to "Close when process exits, fails, or crashes". Make profile exit with non-zero exit code. I can reproduce this in WSL, for example, by listing a non-existing file `ls 123`, then `exit`.

### Expected Behavior

Tab closes silently. (Terminal 1.18 closes tab silently in this case).

### Actual Behavior

This message is displayed:

```
[process exited with code 2 (0x00000002)]
You can now close this terminal with Ctrl+D, or press Enter to restart.
```

### PR DESCRIPTION
**Pull request by zadjii-msft**
Well, Pane doesn't _only_ care if the connection isn't entering a terminal state. It does need to update its own state first.

Regressed in #15335

Closes #16068

### CODE REVIEW

File: src/cascadia/TerminalApp/Pane.cpp [hunk 1]
```diff
@@ -1040,6 +1040,7 @@ winrt::fire_and_forget Pane::_ControlConnectionStateChangedHandler(const winrt::
         newConnectionState = coreState.ConnectionState();
     }
 
+    const auto previousConnectionState = std::exchange(_connectionState, newConnectionState);
```
Comment (zadjii-msft) [inline src/cascadia/TerminalApp/Pane.cpp:1043]: /cc @lhecker to make sure I didn't royally blow up some locking / co_await / other threading issue, which I am prone to do

**Review by carlos-zamora — APPROVED** [review]

File: src/cascadia/TerminalApp/Pane.cpp (hunk 1 above)
Comment (lhecker) [reply src/cascadia/TerminalApp/Pane.cpp:1043]: Not that I can tell at least!

**Review by lhecker — APPROVED** [review]

**Review by DHowett — APPROVED** [review]
