### PR TITLE
Ensure PowerShell Core profile commandline is quoted

### LINKED ISSUE #11717: error 0x800700c1 when launching pwsh.exe
### Windows Terminal version (or Windows build number)

1.11.2921.0

### Other Software

pwsh.exe 7.2.0

### Steps to reproduce

my terminal has **C:\Users\Kevin Kostrzewa\AppData\Local\Microsoft\WindowsApps\Microsoft.PowerShell_8wekyb3d8bbwe\pwsh.exe** in the Powershell profile (note the space between **Kevin** and **Kostrzewa*() 

Installing Visual Studio 2022 created a file called **c:\users\Kevin** to be created, containing some installation logs.

Terminal failed to launch pwsh.exe after, presumably because of the space in the terminal profile around powershell. I think this is related to https://github.com/microsoft/terminal/issues/7195

### Expected Behavior

pwsh.exe to launch

NOTE: I think Terminal could be more resilient around pathing and launching the .exe so a file can't be injected ahead of it with clever space filled pathing. This *may* be a security issue, if c:\users\Kevin was attempted to be CreateProcess'ed.

### Actual Behavior

[error 0x800700c1 when launching `C:\Users\Kevin Kostrzewa\AppData\Local\Microsoft\WindowsApps\Microsoft.PowerShell_8wekyb3d8bbwe\pwsh.exe']

### PR DESCRIPTION
**Pull request by ianjoneill**
Ensures the PowerShell Core profile's commandline is quoted. This allows
the profile to work correctly if there are files in place on the machine
(e.g. one called `C:\Program`) that prevent `CreateProcess()` from
invoking the un-quoted commandline.

## Validation Steps Performed
Created a file called `C:\Program` and opened the PowerShell profile in
terminal.

Closes #11717

### CODE REVIEW

**Comment by DHowett** [comment]
uuuuuuuuuugh thank you

File: src/cascadia/TerminalSettingsModel/PowershellCoreProfileGenerator.cpp [hunk 1]
```diff
@@ -309,7 +309,15 @@ void PowershellCoreProfileGenerator::GenerateProfiles(std::vector<winrt::com_ptr
...
         auto profile{ CreateDynamicProfile(name) };
-        profile->Commandline(winrt::hstring{ psI.executablePath.native() });
+
+        const auto& unquotedCommandline = psI.executablePath.native();
+        std::wstring quotedCommandline;
+        quotedCommandline.reserve(unquotedCommandline.size() + 2);
+        quotedCommandline.push_back(L'"');
+        quotedCommandline.append(unquotedCommandline);
+        quotedCommandline.push_back(L'"');
+        profile->Commandline(winrt::hstring{ quotedCommandline });
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsModel/PowershellCoreProfileGenerator.cpp:319]: for cheap tricks, we could also...

```
auto quotedCommandline = fmt::format(FMT_COMPILE(L"\"{}\""), psI.executablePath.native());
```

which _should_ (?????) compile down to effectively optimal code (!)

**Review by DHowett — APPROVED** [review]

File: src/cascadia/TerminalSettingsModel/PowershellCoreProfileGenerator.cpp (hunk 1 above)
Comment (ianjoneill) [reply src/cascadia/TerminalSettingsModel/PowershellCoreProfileGenerator.cpp:319]: A micro-benchmark on my machine shows my code to be faster :)

```cpp
        auto start = std::chrono::steady_clock::now();
        for (int i = 0; i < 100000; i++)
        {
            const auto& unquotedCommandline = psI.executablePath.native();
            std::wstring quotedCommandline;
            quotedCommandline.reserve(unquotedCommandline.size() + 2);
            quotedCommandline.push_back(L'"');
            quotedCommandline.append(unquotedCommandline);
            quotedCommandline.push_back(L'"');
        }
        auto end = std::chrono::steady_clock::now();
        std::wstringstream stream;
        stream << "Elapsed microseconds for native code " << std::chrono::duration_cast<std::chrono::microseconds>(end - start).count() << std::endl;
        OutputDebugString(stream.str().c_str());

        start = std::chrono::steady_clock::now();
        for (int i = 0; i < 100000; i++)
        {
            auto quotedCommandline = fmt::format(FMT_COMPILE(L"\"{}\""), psI.executablePath.native());
        }
        end = std::chrono::steady_clock::now();
        std::wstringstream stream2;
        stream2 << "Elapsed microseconds for fmt code " << std::chrono::duration_cast<std::chrono::microseconds>(end - start).count() << std::endl;
        OutputDebugString(stream2.str().c_str());
```

Output:
```
Elapsed microseconds for native code 11221
Elapsed microseconds for fmt code 15288
```

Comment (miniksa) [reply src/cascadia/TerminalSettingsModel/PowershellCoreProfileGenerator.cpp:319]: > A micro-benchmark on my machine shows my code to be faster :)

Well, you'll make @lhecker 's day. And I chuckled. Good enough.

**Review by miniksa — APPROVED** [review]

File: src/cascadia/TerminalSettingsModel/PowershellCoreProfileGenerator.cpp (hunk 1 above)
Comment (DHowett) [reply src/cascadia/TerminalSettingsModel/PowershellCoreProfileGenerator.cpp:319]: LOL. Fair enough 😁
