### PR TITLE
Fix conhost UseDx mode

### LINKED ISSUE #5455: Conhost output is invisible when UseDx is set
# Environment

Windows build number: Version 10.0.18362.657
Windows Terminal version (if applicable): Commit f6f0731eae61f24e6777e5cf98aaf7e746f1b2bd

# Steps to reproduce

1. Set the DWORD registry value `HKCU\Console\UseDx` to `1` to enable the DirectX renderer.
2. Build the latest source (or at least commit 79684bf82177dfa52bd1eca84476a2950d765bb9).
3. Start a cmd shell in conhost (the problem isn't exclusive to the cmd shell though).

# Expected behavior

I'd expect to see the copyright message and command prompt.

# Actual behavior

The screen is blank. I can still see the cursor, but any text output is invisible. It's like it's rendering everything in black on black.

This was working for me in commit ffbdfe32ac972ecf76ead140a2ae5bad59cf6f91, but broke after commit 79684bf82177dfa52bd1eca84476a2950d765bb9. It still seems to be broken in the latest commit (f6f0731eae61f24e6777e5cf98aaf7e746f1b2bd).

### PR DESCRIPTION
**Pull request by lhecker**
This commit fixes the UseDx mode for conhost.
In order to add support for UseDx without calling `SetWindowSize`,
responsibility for resizing `_invalidMap` has been moved to occur
only when the renderer itself recognizes a new size. Furthermore
`InvalidateAll` is now the central point to invalidate `_invalidMap`.

## Validation Steps Performed

* Enabling `UseDx` enables the DxEngine for conhost ✔️
* Resizing windows in conhost works ✔️
* Resizing windows in WT works ✔️

Closes #5455

### CODE REVIEW

File: src/renderer/dx/DxRenderer.cpp [hunk 1]
```diff
@@ -1047,14 +1047,10 @@ HANDLE DxEngine::GetSwapChainHandle()
...
-    if (_invalidateFullRows)
-    {
-        invalidate = til::rectangle{ til::point{ static_cast<ptrdiff_t>(0), rc.top() }, til::size{ _invalidMap.size().width(), rc.height() } };
-    }
-
-    _invalidMap.set(invalidate);
+    const auto size = _invalidMap.size();
+    const auto topLeft = til::point{ 0, std::min(size.height(), rc.top()) };
+    const auto bottomRight = til::point{ size.width(), std::min(size.height(), rc.bottom()) };
+    _invalidMap.set({ topLeft, bottomRight });
```
Comment (lhecker) [inline src/renderer/dx/DxRenderer.cpp:1053]: Due to the missing `std::min`, but the delayed `_invalidMap` resize, this was blowing up with exceptions. Now it isn't anymore.

File: src/renderer/dx/DxRenderer.cpp [hunk 2]
```diff
@@ -1322,8 +1318,8 @@ try
             // And persist the new size.
             _displaySizePixels = clientSize;
 
-            // Mark this as the first frame on the new target. We can't use incremental drawing on the first frame.
-            _firstFrame = true;
+            _invalidMap.resize(clientSize / _fontRenderData->GlyphCell());
```
Comment (DHowett) [inline src/renderer/dx/DxRenderer.cpp:1321]: I'm confused -- the body of the PR says "responsibility for resizing `_invalidMap` has been moved entirely into `InvalidateAll`", but both places we have InvalidateAll calls we resize the map _before_ calling it?

File: src/renderer/dx/DxRenderer.cpp [hunk 3]
```diff
@@ -1047,14 +1047,10 @@ HANDLE DxEngine::GetSwapChainHandle()
...
-
-    if (_invalidateFullRows)
-    {
-        invalidate = til::rectangle{ til::point{ static_cast<ptrdiff_t>(0), rc.top() }, til::size{ _invalidMap.size().width(), rc.height() } };
-    }
-
-    _invalidMap.set(invalidate);
+    const auto size = _invalidMap.size();
+    const auto topLeft = til::point{ 0, std::min(size.height(), rc.top()) };
+    const auto bottomRight = til::point{ size.width(), std::min(size.height(), rc.bottom()) };
```
Comment (DHowett) [inline src/renderer/dx/DxRenderer.cpp:1052]: I'm sure @miniksa will agree:

i am surprised we do not have `til::rectangle::clamp`

**Review by DHowett — CHANGES_REQUESTED** [review]
Open question about the divergence between the description and the implementation?

File: src/renderer/dx/DxRenderer.cpp (hunk 2 above)
Comment (lhecker) [reply src/renderer/dx/DxRenderer.cpp:1321]: Woops I mixed things up. I'm fixing my PR body to say that responsibility for full invalidation was moved there.

**Comment by DHowett** [comment]
Make sure you test unusual scenarios too, like doing a *lot*  of resizing in WT, with multiple panes, and moving between displays of different DPIs (or changing your active DPI)

File: src/renderer/dx/DxRenderer.cpp (hunk 3 above)
Comment (lhecker) [reply src/renderer/dx/DxRenderer.cpp:1052]: I mean we do technically have an `operator&`, but I found it cumbersome to first construct a rectangle (which is rather verbose) just to do `& rc`.

Comment (DHowett) [reply src/renderer/dx/DxRenderer.cpp:1052]: Only somewhat verbose :smile:

```
const auto size = _invalidMap.size();
_invalidMap.set(til::rectangle{ 0, rc.top(), size.width(), rc.bottom() } & til::rectangle{ size });
```

okay I admit, it does look somewhat cumbersome.

**Comment by lhecker** [comment]
> Make sure you test unusual scenarios too, like doing a lot of resizing in WT, with multiple panes, and moving between displays of different DPIs (or changing your active DPI)

I can't spot anything unusual. 👍

File: src/renderer/dx/DxRenderer.cpp (hunk 3 above)
Comment (miniksa) [reply src/renderer/dx/DxRenderer.cpp:1052]: I personally prefer Dustin's, but I'll take either. The structures and operators are tools to make life easier... not a strict requirement.

File: src/renderer/dx/DxRenderer.cpp [hunk 4]
```diff
@@ -61,7 +61,6 @@ using namespace Microsoft::Console::Types;
 // TODO GH 2683: The default constructor should not throw.
 DxEngine::DxEngine() :
     RenderEngineBase(),
-    _invalidateFullRows{ true },
```
Comment (miniksa) [inline src/renderer/dx/DxRenderer.cpp:64]: Why did you pull this? I presume the answer is:
1. No one ever set this so we'll always just invalidate a full row.
2. We determined that we likely won't even need to do differential drawing with a better render strategy anyway so there's no reason to try to tighten down the differential drawing any further in the future by doing partial rows.
If that's the answer... maybe leave some of that in a comment in `InvalidateRectangle` so we don't forget.

**Review by miniksa — APPROVED** [review]

File: src/renderer/dx/DxRenderer.cpp (hunk 4 above)
Comment (lhecker) [reply src/renderer/dx/DxRenderer.cpp:64]: Yeah basically that. I was touching the only function that uses this field and I doubt this field will ever be useful again, as it's slower to figure out what contains ligatures, compared to just redrawing the entire row. The difference between drawing no text and a full row of text is only 5-10μs after all. (Also: YAGNI. 😄)

File: src/renderer/dx/DxRenderer.cpp (hunk 3 above)
Comment (lhecker) [reply src/renderer/dx/DxRenderer.cpp:1052]: If I'm reading this correctly, there isn't a strong opinion... as I'd like to keep it the way I did it for now, if you don't mind. 😅

**Review by DHowett — APPROVED** [review]

File: src/renderer/dx/DxRenderer.cpp (hunk 4 above)
Comment (miniksa) [reply src/renderer/dx/DxRenderer.cpp:64]: Fair enough.
