### PR TITLE
Lookup WSL distros in the registry

### LINKED ISSUE #7199: WSL terminal not available sometimes in "New Tab" dropdown on start-up
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.959]
Windows Terminal version (if applicable): 1.1.2021.0

Any other software? Yes
Ubuntu-20.04
```

# Steps to reproduce

Start-up Windows Terminal normally, i.e. Click on the pinned Task-Bar icon

# Expected behavior

The "New Tab" dropdown should list "Ubuntu-20.04"

# Actual behavior

The "New Tab" dropdown doesn't list "Ubuntu-20.04". To get it listed I need to perform the following:
1. Open Settings, i.e. from the dropdown menu.
    Visual Studio opens with the settings.json file.
2. Make a benign change, i.e. add a space and delete it, and save.
3. Now Windows Terminal lists "Ubuntu-20.04" under the "New Tab" dropdown (no closing reopening necessary).

### LINKED ISSUE #9905: Slow loading time on first use
Windows Terminal Version: 1.7.1033.0
Windows Version 20H2 (OS Build 19042.928)

I use Windows Terminal with Ubuntu WSL2 and Windows Command Prompt profile.
In some previous version it would load quickly, but for some time when I first load a terminal it takes several seconds before the window loads. During this time there does appear an icon in the system tray with the title "DesktopWindowXamlSource" which eventually is replaced with the profile name when the window finally appears.

This occurs regardless if which profile I'm initially loading. 

After the terminal has loaded, if I close the window and load it again, it opens quickly. I can still see the original DesktopWindowXamlSource icon but it's only there for a split second. I can continue loading terminal windows, even after they are all closed, with no delay.

However, if I don't open a terminal window for some time (several minutes), there is a delay on loading the first instance again.

There was a previous issue Slow startup time #4886 reporting a similar problem in a previous version, which has been closed. I'm not sure if this is the same issue or not, but it hasn't been resolved.

I also experience this on both my desktop and laptop computers.

### PR DESCRIPTION
**Pull request by zadjii-msft**
This PR converts the WSL distro generator to use the registry to lookup
WSL distros instead of trying to parse the results of `wsl.exe`.
`wsl.exe` sometimes takes a very long time to launch the WSL service,
which means that on the first launch of the Terminal, WSL distros can
sometimes be missing entirely!

## References
* Also related is #6160, but I feel that deserves a separate PR for
  warning when the default profile is a dynamic profile who's source
  indicated it was gone. 

## PR Checklist
* [x] Closes #9905
* [x] Closes #7199
* [x] I work here
* [ ] Tests added/passed
* [ ] Requires documentation to be updated

## Detailed Description of the Pull Request / Additional comments

This is maybe a little BODGY, but hey we get tons of reports of this
root cause.

## Validation Steps Performed

Ran it locally, it did well. Ran a `wsl --shutdown`, then booted the
terminal - seemed to do well. I never was able to repro the slowness
myself, but I'd suspect this'll fix it.

### CODE REVIEW

File: src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp [hunk 1]
```diff
@@ -35,7 +35,7 @@ std::wstring_view WslDistroGenerator::GetNamespace()
 // - <none>
 // Return Value:
 // - a vector with all distros for all the installed WSL distros
-std::vector<Profile> WslDistroGenerator::GenerateProfiles()
+std::vector<Profile> _legacyGenerate()
```
Comment (lhecker) [inline src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp:38]: Identifiers in the global scope starting with underscore are reserved identifiers.
I think we shouldn't introduce new identifiers like that anymore at this point. `legacyGenerate()`, `namesToProfiles()`, etc. are just fine IMO.

File: src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp [hunk 2]
```diff
@@ -136,3 +136,206 @@ std::vector<Profile> WslDistroGenerator::GenerateProfiles()
...
+        profiles.emplace_back(WSLDistro);
+    }
+    return profiles;
+}
+
+// The WSL entries are structured as such:
+// HKCU\Software\Microsoft\Windows\CurrentVersion\Lxss
+//   ⌞ {distroGuid}
+//     ⌞ DistributionName: {the name}
+const wchar_t RegKeyLxss[] = L"Software\\Microsoft\\Windows\\CurrentVersion\\Lxss";
```
Comment (lhecker) [inline src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp:174]: You can use `constexpr auto`.

File: src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp [hunk 3]
```diff
@@ -136,3 +136,206 @@ std::vector<Profile> WslDistroGenerator::GenerateProfiles()
...
+    {
+        return false;
+    }
+
+    // lpcbMaxSubKeyLen does not include trailing space
+    std::unique_ptr<wchar_t[]> buffer = std::make_unique<wchar_t[]>(maxSubKeyLen + 1);
+
+    // reserve enough space for all the GUIDs we're about to enumerate
+    guidStrings.reserve(dwNumSubKeys);
+    for (DWORD i = 0; i < dwNumSubKeys; i++)
```
Comment (lhecker) [inline src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp:252]: I believe you should iterate until `ERROR_NO_MORE_ITEMS` instead.

File: src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp [hunk 4]
```diff
@@ -136,3 +136,206 @@ std::vector<Profile> WslDistroGenerator::GenerateProfiles()
...
+    {
+        auto cbName = maxSubKeyLen + 1;
+        const auto result = RegEnumKeyEx(wslRootKey.get(), i, buffer.get(), &cbName, nullptr, nullptr, nullptr, nullptr);
+        if (result == ERROR_SUCCESS)
```
Comment (lhecker) [inline src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp:256]: Since you know you want to extract GUIDs and nothing else a sanity check might be useful. If the Lxss key ever changes to something different it might be better to fail early and reliably instead of accidentally working. Additionally this allows you to simplify the buffer a bit:

```cpp
HRESULT hr;
wchar_t buffer[39]; // a {GUID} is 38 chars long

for (;;) {
	DWORD length;
	const auto result = RegEnumKeyEx(wslRootKey.get(), i, &buffer[0], &length, nullptr, nullptr, nullptr, nullptr);
	if (result == ERROR_NO_MORE_ITEMS) {
		break;
	}

	if (result == ERROR_SUCCESS && length == 38 && buffer[0] == L'{' && buffer[37] == L'}') {
		guidStrings.emplace_back(&buffer[0], length);
	}
}
```

File: src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp [hunk 5]
```diff
@@ -136,3 +136,206 @@ std::vector<Profile> WslDistroGenerator::GenerateProfiles()
...
+        auto result = RegQueryValueEx(distroKey.get(), RegKeyDistroName, 0, nullptr, nullptr, &bufferCapacity);
+        // request regkey binary buffer capacity only
+        if (result != ERROR_SUCCESS)
+        {
+            // return false;
+            continue;
+        }
+        std::unique_ptr<wchar_t[]> buffer = std::make_unique<wchar_t[]>(bufferCapacity);
+        // request regkey binary content
+        result = RegQueryValueEx(distroKey.get(), RegKeyDistroName, 0, nullptr, reinterpret_cast<BYTE*>(buffer.get()), &bufferCapacity);
```
Comment (lhecker) [inline src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp:301]: You can write this and drop the extra size-check above:
```cpp
std::wstring buffer;
result = wil::AdaptFixedSizeToAllocatedResult<std::wstring, 256>(buffer, [&](PWSTR value, size_t valueLength, size_t* valueLengthNeededWithNull) -> HRESULT {
	auto length = static_cast<DWORD>(valueLength);
    const auto hr = RegQueryValueExW(distroKey.get(), RegKeyDistroName, 0, nullptr, value, &length);
	*valueLengthNeededWithNull = length + 1;
	return hr == ERROR_MORE_DATA ? S_OK : hr;
});
names.emplace_back(std::move(buffer));
```

File: src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp [hunk 6]
```diff
@@ -136,3 +136,206 @@ std::vector<Profile> WslDistroGenerator::GenerateProfiles()
...
+{
+    static wil::unique_hkey wslRootKey{ _openWslRegKey() };
+    if (wslRootKey)
+    {
+        std::vector<std::wstring> guidStrings{};
+        if (_getWslGuids(wslRootKey, guidStrings))
+        {
+            std::vector<std::wstring> names{};
+            names.reserve(guidStrings.size());
+            if (_getWslNames(wslRootKey, guidStrings, names))
```
Comment (lhecker) [inline src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp:333]: I believe it would be better to use exception handling as opposed to using booleans.

File: src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp (hunk 1 above)
Comment (DHowett) [inline src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp:38]: interesting -- introducing a full fallback mode that is just "do the old thing." clever.

File: src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp (hunk 2 above)
Comment (DHowett) [inline src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp:174]: static constexpr maybe?

File: src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp [hunk 7]
```diff
@@ -136,3 +136,206 @@ std::vector<Profile> WslDistroGenerator::GenerateProfiles()
...
+const wchar_t RegKeyLxss[] = L"Software\\Microsoft\\Windows\\CurrentVersion\\Lxss";
+const wchar_t RegKeyDistroName[] = L"DistributionName";
+
+// Function Description:
+// - Open the reg key the root of the WSL data, in HKCU\Software\Microsoft\Windows\CurrentVersion\Lxss
+// Arguments:
+// - <none>
+// Return Value:
+// - the HKEY if it exists and we can read it, else nullptr
+HKEY _openWslRegKey()
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp:183]: make these static :smile:

Comment (DHowett) [reply src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp:183]: also, we may want to use the `wil` helpers here. `wil::unique_hkey` etc

Comment (DHowett) [reply src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp:183]: oh my god there's a wil registry_watcher

_like, we could reload the settings if the lxss key changes_

not saying that we should do this now, but... whoa

**Review by DHowett — CHANGES_REQUESTED** [review]

File: src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp (hunk 5 above)
Comment (DHowett) [reply src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp:301]: LOVE this thing

**Comment by DHowett** [comment]
Notes from looking at the registry keys:

1. In the future (i will file) we can use the `PackageFamilyName` value to generate a better icon by default (!) for distros that came from packages
2. I was going to say "let's understand `State`, which is one of the values in the distro key" but then i decided _eh, it will be fine_

**Comment by vadimkantorov** [comment]
One very frequent case of wsl.exe being slow to respond is when the user opens terminal immediately after Windows logs in. At login, there may be thousand of processes hammering IO and RAM (think of simulataneously a few hundred Chrome tabs trying to recover themselves). This all gets worse if the hardware is old (HDD / only 8Gb or RAM)

I still propose to offer use a Retry / Wait / Cancel button even when wsl.exe response is needed. In the case above wsl.exe always fail to respond timely.

**Comment by zadjii-msft** [comment]
> I still propose to offer use a Retry / Wait / Cancel button even when wsl.exe response is needed. In the case above wsl.exe always fail to respond timely.

Honestly, at this point we only fall back to `wsl.exe` if we fail to read the reg keys at all. That's not really a valid configuration as far as I'm aware - I'd bet that even `wsl.exe` would bite it in that scenario. This should be strictly faster than trying to boot `wsl.exe`.

**Comment by vadimkantorov** [comment]
No doubt about that, but if WSL Ubuntu is already default profile, immediately after there would be wait for wsl.exe anyway. Currently, just a black screen is shown that seems hung (if one doesn't know about this background connecting to WSL booting up). Maybe it could temporarily print something like "Connecting to WSL service...".

**Comment by DHowett** [comment]
> No doubt about that, but if WSL Ubuntu is already default profile, immediately after there would be wait for wsl.exe anyway. Currently, just a black screen is shown that seems hung (if one doesn't know about this background connecting to WSL booting up). Maybe it could temporarily print something like "Connecting to WSL service..." (but I agree that black screen is less nasty than Profile Not Found messageboxes)

At least that happens after our UI is set up **and responsive**¹; the same would happen to any application that takes some time to launch. We can probably give a better indication that something's happening (though anything we do here is "extra" because it's the app's responsibility to emit something before a long wait), but at the very least the user can interact with the thing while they're waiting.

¹ (which is the point :smile:)

File: src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp [hunk 8]
```diff
@@ -136,3 +143,201 @@ std::vector<Profile> WslDistroGenerator::GenerateProfiles()
...
+//   we fail to open any regkey for the GUID of a distro, we'll just skip it.
+//   Places the names of all the distros into the "names" param.
+// Arguments:
+// - wslRootKey: the HKEY for the Lxss node.
+// - guidStrings: A list of all the GUIDs of the installed distros
+// - names: a vector that receives all the names of the installed distros.
+// Return Value:
+// - false if the root key was invalid, else true.
+static bool getWslNames(const wil::unique_hkey& wslRootKey,
+                        std::vector<std::wstring>& guidStrings,
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp:278]: We consume this one `const`ly, right?

```suggestion
                        const std::vector<std::wstring>& guidStrings,
```

File: src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp [hunk 9]
```diff
@@ -136,3 +143,201 @@ std::vector<Profile> WslDistroGenerator::GenerateProfiles()
...
+        auto result = wil::AdaptFixedSizeToAllocatedResult<std::wstring, 256>(buffer, [&](PWSTR value, size_t valueLength, size_t* valueLengthNeededWithNull) -> HRESULT {
+            auto length = static_cast<DWORD>(valueLength);
+            const auto status = RegQueryValueExW(distroKey.get(), RegKeyDistroName, 0, nullptr, reinterpret_cast<BYTE*>(value), &length);
+            // length will receive the number of bytes - convert to a number of
+            // wchar_t's. AdaptFixedSizeToAllocatedResult will resize buffer to
+            // valueLengthNeededWithNull
+            *valueLengthNeededWithNull = (length / sizeof(wchar_t));
+            // If you add one for another trailing null, then there'll actually
+            // be _two_ trailing nulls in the buffer.
+            return status == ERROR_MORE_DATA ? ERROR_SUCCESS : status;
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp:303]: I'm not sure these are HRESULTs

Comment (DHowett) [reply src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp:303]: (I am also not certain I understand how this function works/what it is expecting)

File: src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp [hunk 10]
```diff
@@ -136,3 +143,201 @@ std::vector<Profile> WslDistroGenerator::GenerateProfiles()
...
+//   fails, we'll fall back to the legacy way of launching WSL.exe to read the
+//   distros from the commandline. Reading the registry is slightly more stable
+//   (see GH#7199, GH#9905), but it is certainly BODGY
+// Arguments:
+// - <none>
+// Return Value:
+// - A list of WSL profiles.
+std::vector<Profile> WslDistroGenerator::GenerateProfiles()
+{
+    static wil::unique_hkey wslRootKey{ openWslRegKey() };
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp:327]: Interesting; this will be held for the lifetime of the application. That's intentional, I presume?

File: src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp (hunk 3 above)
Comment (DHowett) [reply src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp:246]: Yeah -- the remarks say that you can just start with 0 and enumerate forever until you get `ERROR_NO_MORE_ITEMS`; there may not be a need to QueryInfoKey first at all

**Comment by vadimkantorov** [comment]
> (though anything we do here is "extra" because it's the app's responsibility to emit something before a long wait),

Well, from the user's standpoint this app is Terminal :) Apriori, I don't know whether we are waiting for WSL driver, all those VM layers or Terminal hanging...

**Comment by DHowett** [comment]
Terminal can only know about the first one, which makes this somewhat fraught. That's the issue.

**Comment by vadimkantorov** [comment]
Well, I mean it would be good if at least one of these printed something quick, so that it's clear that it's normal to wait for longer :)

File: src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp (hunk 10 above)
Comment (zadjii-msft) [reply src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp:327]: Oh, uh, maybe not. I guess I thought it would be easier than looking it up each time, but you know, we _should_ close it when we're done with it.

**Review by DHowett — APPROVED** [review]

File: src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp [hunk 11]
```diff
@@ -136,3 +143,183 @@ std::vector<Profile> WslDistroGenerator::GenerateProfiles()
...
+// Function Description:
+// - Open the reg key the root of the WSL data, in HKCU\Software\Microsoft\Windows\CurrentVersion\Lxss
+// Arguments:
+// - <none>
+// Return Value:
+// - the HKEY if it exists and we can read it, else nullptr
+static HKEY openWslRegKey()
+{
+    HKEY hKey{ nullptr };
+    if (RegOpenKeyEx(HKEY_CURRENT_USER, RegKeyLxss, 0, KEY_ALL_ACCESS, &hKey) == ERROR_SUCCESS)
```
Comment (miniksa) [inline src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp:186]: Can't you get away with just `KEY_READ`?

Least privilege required to do the job...

File: src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp [hunk 12]
```diff
@@ -136,3 +143,183 @@ std::vector<Profile> WslDistroGenerator::GenerateProfiles()
...
+    return profiles;
+}
+
+// Function Description:
+// - Open the reg key the root of the WSL data, in HKCU\Software\Microsoft\Windows\CurrentVersion\Lxss
+// Arguments:
+// - <none>
+// Return Value:
+// - the HKEY if it exists and we can read it, else nullptr
+static HKEY openWslRegKey()
```
Comment (miniksa) [inline src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp:183]: You can't have these return the `wil::unique_hkey` straight up?

File: src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp [hunk 13]
```diff
@@ -136,3 +143,183 @@ std::vector<Profile> WslDistroGenerator::GenerateProfiles()
...
+    for (const auto& guid : guidStrings)
+    {
+        wil::unique_hkey distroKey{ openDistroKey(wslRootKey, guid) };
+        if (!distroKey)
+        {
+            continue;
+        }
+
+        std::wstring buffer;
+        auto result = wil::AdaptFixedSizeToAllocatedResult<std::wstring, 256>(buffer, [&](PWSTR value, size_t valueLength, size_t* valueLengthNeededWithNull) -> HRESULT {
```
Comment (miniksa) [inline src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp:276]: Well that's one I haven't seen before.

File: src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp [hunk 14]
```diff
@@ -136,3 +143,183 @@ std::vector<Profile> WslDistroGenerator::GenerateProfiles()
...
+        if (result == ERROR_NO_MORE_ITEMS)
+        {
+            break;
+        }
+
+        if (result == ERROR_SUCCESS &&
+            length == 38 &&
+            buffer[0] == L'{' &&
+            buffer[37] == L'}')
+        {
```
Comment (miniksa) [inline src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp:241]: I'm chuckling at this loose guessing that it looks like and smells like a GUID without using an actual GUID parsing function like `StringFromGUID2` because you're just going to turn around and shove the string back at another registry API and don't actually need the GUID as a GUID.

**Review by miniksa — APPROVED** [review]
Approve with comments. Unmark automerge so you can see them before it rockets off.

File: src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp (hunk 13 above)
Comment (DHowett) [reply src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp:276]: SO COOL.

File: src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp (hunk 14 above)
Comment (DHowett) [reply src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp:241]: _lmao_

File: src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp [hunk 15]
```diff
@@ -136,3 +143,183 @@ std::vector<Profile> WslDistroGenerator::GenerateProfiles()
...
+{
+    if (!wslRootKey)
+    {
+        return false;
+    }
+
+    wchar_t buffer[39]; // a {GUID} is 38 chars long
+    for (DWORD i = 0;; i++)
+    {
+        DWORD length;
```
Comment (lhecker) [inline src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp:230]: BTW I had a programming error. This value needs to be initialized to `std::size(buffer)` (or 39).
This code shouldn't work without it. 🤔

File: src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp (hunk 14 above)
Comment (lhecker) [reply src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp:241]: Pretty funny how there's no `GUIDFromString`...
`IIDFromString` however could be used here if we want to. I just don't think it's necessary, because a string that's exactly 38 chars long and begins/ends with curly braces, looks and smells pretty significantly like a valid parameter. I'd probably rather remove the additional begin/end checks. 😄

File: src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp [hunk 16]
```diff
@@ -136,3 +143,183 @@ std::vector<Profile> WslDistroGenerator::GenerateProfiles()
...
+// Arguments:
+// - names: a list of distro names to turn into profiles
+// Return Value:
+// - the list of profiles we've generated.
+static std::vector<Profile> namesToProfiles(const std::vector<std::wstring>& names)
+{
+    std::vector<Profile> profiles;
+    for (const auto& distName : names)
+    {
+        if (distName.substr(0, std::min(distName.size(), DockerDistributionPrefix.size())) == DockerDistributionPrefix)
```
Comment (lhecker) [inline src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp:159]:
```suggestion
		if (til::starts_with(distName, DockerDistributionPrefix))
```

File: src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp (hunk 12 above)
Comment (lhecker) [reply src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp:183]: +1 for returning RAII wrappers.

File: src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp (hunk 13 above)
Comment (lhecker) [reply src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp:276]: Does this actually work? I only wrote it in theory unfortunately. 😅

File: src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp (hunk 12 above)
Comment (DHowett) [reply src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp:183]: My preferred API surface when smart wrappers is involved -- and this extends to WRL::ComPtr and all similar variants -- is this:

```
smart_wrapper_thing GetAThing(); // produce shared wrapper
thing GetAThing(); // produce dumb thing, see note 1
void TakeAThingOptional(thing*); // consume only -- non-owning and non-shared -- optional
void TakeAThing(thing&); // consume only -- non-owning and non-shared -- required
```

_Of course, ref vs pointer is a decision you can make for the specific type. `HKEY` is by nature optional._

Putting the `smart_wrapper` into the consuming contract forces the caller to have that type (bad) and implies some ownership semantics (dependent on the type).

(1) In general, a function that returns a smart wrapper is subject to the same restrictions as one that returns the thing directly (like `HKEY openWslRegKey`): it must ensure that if an exception is encountered before the smart wrapper is populated, it does not leak the resource. Registry functions don't _throw_, so the need for returning a smart wrapper is reduced. That makes `HKEY open...` _okay_ in my book so long as we make sure to cover the error conditions.

**Review by DHowett — CHANGES_REQUESTED** [review]
I think I have to block because Leonard pointed out a logic error?

**Review by lhecker — CHANGES_REQUESTED** [review]
LBTM

**Review by DHowett — APPROVED** [review]
@zadjii-msft I asked Leonard to block it so I could approve, leaving you with two once you dismiss his. For timezone purposes, it's likely easier on you to dismiss his when you've fixed it :smile:

**Review by lhecker — APPROVED** [review]
