### PR TITLE
AtlasEngine: Improve RDP performance

### LINKED ISSUE #13079: Extreme sluggishness and CPU usage when using Atlas inside a VM
### Windows Terminal version

1.13.10983.0

### Windows build number

10.0.19044.1645

### Other Software

None

### Steps to reproduce

- Use Terminal inside a typical VM
- Switch to the experimental Atlas engine
- Observe CPU load
- Try to type and experience sluggishness and even higher CPU load etc.  There's a decent amount of lag and output from long commands tends to stutter into view; it's not very smooth

### Expected Behavior

Was expecting that Atlas, in default/easy cases, would perform better than the old engine.

Looking ahead: IF atlas becomes the default and IF Terminal replaces all old cmd windows, then using this inside VMs is going to be a non-starter.

### Actual Behavior

Extreme CPU usage and general sluggishness. Witness the firepower of this fully operational battle... I mean barely affordable Azure VM displaying nothing but the flashing cursor inside a blank Terminal window:

atlas-perf
atlas-dxdiag

### PR DESCRIPTION
**Pull request by lhecker**
Direct2D is able to detect remote connections and will switch to sending
draw commands across RDP instead of rendering the data on the server.
This reduces the amount of data that needs to be transmitted as well
as the CPU load of the server, if it has no GPU installed.
This commit changes `AtlasEngine` to render with just Direct2D if a software or
remote device was chosen by `D3D11CreateDevice`. Selecting the DXGI adapter the
window is on explicitly in the future would allow us to be more precise here.

This new rendering mode doesn't implement some of the more fancy features just
yet, like inverted cursors or coloring a single wide glyph in multiple colors.
It reuses most existing facilities and uses the existing tile hash map to cache
DirectWrite text layouts to improve performance. Unfortunately this does incur
a fairly high memory overhead of approximately 25MB for a 120x30 viewport.

Additional drive-by changes include:
* Treat the given font size exactly as its given without rounding
  Apparently we don't really need to round the font size to whole pixels
* Stop updating the const buffer on every frame
* Support window resizing if `debugGeneralPerformance` is enabled

Closes #13079

## Validation Steps Performed
* Tested fairly exhaustively over RDP ✅

### CODE REVIEW

**Comment by DHowett** [comment]
Does this engine automatically enable/disable this mode when you RDP in? Do we need something special to enable that?

**Comment by DHowett** [comment]
AKA: I don't want to compromise the experience for somebody who returns to their desk after being remote.

File: src/renderer/atlas/AtlasEngine.cpp [hunk 1]
```diff
@@ -319,7 +324,7 @@ void AtlasEngine::WaitUntilCanRender() noexcept
 {
     if constexpr (!debugGeneralPerformance)
     {
-        WaitForSingleObjectEx(_r.frameLatencyWaitableObject.get(), 100, true);
+        WaitForSingleObjectEx(_r.frameLatencyWaitableObject.get(), INFINITE, true);
```
Comment (DHowett) [inline src/renderer/atlas/AtlasEngine.cpp:327]: this change worries me; should it?

File: src/renderer/atlas/AtlasEngine.cpp [hunk 2]
```diff
@@ -754,43 +773,29 @@ void AtlasEngine::_recreateSizeDependentResources()
...
-    // In the future this should cover the entire _api.sizeInPixel.x/_api.sizeInPixel.y.
-    // The pixel shader should draw the remaining content in the configured background color.
-    {
-        D3D11_VIEWPORT viewport{};
-        viewport.Width = static_cast<float>(_api.sizeInPixel.x);
-        viewport.Height = static_cast<float>(_api.sizeInPixel.y);
-        _r.deviceContext->RSSetViewports(1, &viewport);
-    }
+    const auto totalCellCount = static_cast<size_t>(_api.cellCount.x) * static_cast<size_t>(_api.cellCount.y);
+    const auto resize = _api.cellCount != _r.cellCount;
```
Comment (DHowett) [inline src/renderer/atlas/AtlasEngine.cpp:790]: _whoa_. I just noticed this. What if you go from a `30x29` terminal to a `29x30` one??

File: src/renderer/atlas/AtlasEngine.cpp [hunk 3]
```diff
@@ -818,21 +823,47 @@ void AtlasEngine::_recreateSizeDependentResources()
...
+            wil::com_ptr<ID3D11Texture2D> buffer;
+            THROW_IF_FAILED(_r.swapChain->GetBuffer(0, __uuidof(ID3D11Texture2D), buffer.put_void()));
+            THROW_IF_FAILED(_r.device->CreateRenderTargetView(buffer.get(), nullptr, _r.renderTargetView.put()));
+        }
+
+        // Tell D3D which parts of the render target will be visible.
+        // Everything outside of the viewport will be black.
+        //
+        // In the future this should cover the entire _api.sizeInPixel.x/_api.sizeInPixel.y.
+        // The pixel shader should draw the remaining content in the configured background color.
```
Comment (DHowett) [inline src/renderer/atlas/AtlasEngine.cpp:842]: i know this is not a new comment, but should we promote any of these unmarked TODOs to issues?

File: src/renderer/atlas/AtlasEngine.h [hunk 4]
```diff
@@ -347,6 +349,7 @@ namespace Microsoft::Console::Render
 
             SmallObjectOptimizer& operator=(SmallObjectOptimizer&& other) noexcept
             {
+                this->~SmallObjectOptimizer();
```
Comment (DHowett) [inline src/renderer/atlas/AtlasEngine.h:352]: _yikes_

Comment (DHowett) [reply src/renderer/atlas/AtlasEngine.h:352]: wow is this a valid implementation of an assignment operator?

File: src/renderer/atlas/AtlasEngine.h [hunk 5]
```diff
@@ -530,6 +548,8 @@ namespace Microsoft::Console::Render
                 return _data.data();
             }
 
+            CachedGlyphLayout cachedLayout;
```
Comment (DHowett) [inline src/renderer/atlas/AtlasEngine.h:551]: `AtlasValue` isn't supposed to be POD, right

File: src/renderer/atlas/AtlasEngine.r.cpp [hunk 6]
```diff
@@ -53,15 +62,15 @@ using namespace Microsoft::Console::Render;
 [[nodiscard]] HRESULT AtlasEngine::Present() noexcept
 try
 {
-    _adjustAtlasSize();
-    _processGlyphQueue();
-
-    if (WI_IsFlagSet(_r.invalidations, RenderInvalidations::Cursor))
+    if (_r.d2dMode)
```
Comment (DHowett) [inline src/renderer/atlas/AtlasEngine.r.cpp:65]: nit: do we want `likely` `unlikely` annotations?

File: src/renderer/atlas/AtlasEngine.r.cpp [hunk 7]
```diff
@@ -53,15 +62,15 @@ using namespace Microsoft::Console::Render;
...
 {
-    _adjustAtlasSize();
-    _processGlyphQueue();
-
-    if (WI_IsFlagSet(_r.invalidations, RenderInvalidations::Cursor))
+    if (_r.d2dMode)
     {
-        _drawCursor();
-        WI_ClearFlag(_r.invalidations, RenderInvalidations::Cursor);
+        _d2dPresent();
```
Comment (DHowett) [inline src/renderer/atlas/AtlasEngine.r.cpp:67]: should we not return the return value of `_d2dPresent`? so we can detect failure?

File: src/renderer/atlas/AtlasEngine.r.cpp [hunk 8]
```diff
@@ -481,57 +518,17 @@ void AtlasEngine::_drawGlyph(const AtlasQueueItem& item) const
...
-        {
-            static constexpr D2D1_MATRIX_3X2_F identity{ 1, 0, 0, 1, 0, 0 };
-            _r.d2dRenderTarget->SetTransform(&identity);
-        }
-        {
-            _r.d2dRenderTarget->PopAxisAlignedClip();
-        }
-    }
+    return CachedGlyphLayout{
+        .textLayout = textLayout,
```
Comment (DHowett) [inline src/renderer/atlas/AtlasEngine.r.cpp:522]: YAY C++20

File: src/renderer/atlas/AtlasEngine.r.cpp [hunk 9]
```diff
@@ -481,57 +518,17 @@ void AtlasEngine::_drawGlyph(const AtlasQueueItem& item) const
...
-        if (scalingRequired)
-        {
-            static constexpr D2D1_MATRIX_3X2_F identity{ 1, 0, 0, 1, 0, 0 };
-            _r.d2dRenderTarget->SetTransform(&identity);
-        }
-        {
-            _r.d2dRenderTarget->PopAxisAlignedClip();
-        }
-    }
+    return CachedGlyphLayout{
```
Comment (DHowett) [inline src/renderer/atlas/AtlasEngine.r.cpp:521]: I can't see how this does a cache

File: src/renderer/atlas/AtlasEngine.r.cpp [hunk 10]
```diff
@@ -540,64 +537,436 @@ void AtlasEngine::_drawCursor()
...
+    _d2dDrawDirtyArea();
+
+    // See documentation for IDXGISwapChain2::GetFrameLatencyWaitableObject method:
+    // > For every frame it renders, the app should wait on this handle before starting any rendering operations.
+    // > Note that this requirement includes the first frame the app renders with the swap chain.
+    assert(debugGeneralPerformance || _r.frameLatencyWaitableObjectUsed);
+
+    if (dirtyRectInPx)
+    {
+        {
```
Comment (DHowett) [inline src/renderer/atlas/AtlasEngine.r.cpp:692]: this seems like an unnecessary level of indentation

Comment (DHowett) [reply src/renderer/atlas/AtlasEngine.r.cpp:692]: (it covers the entire `if` body)

File: src/renderer/atlas/AtlasEngine.r.cpp [hunk 11]
```diff
@@ -540,64 +537,436 @@ void AtlasEngine::_drawCursor()
...
+            {
+                scrollRect = {
+                    0,
+                    std::max<til::CoordType>(0, _r.scrollOffset),
+                    _r.cellCount.x,
+                    _r.cellCount.y + std::min<til::CoordType>(0, _r.scrollOffset),
+                };
+                scrollOffset = {
+                    0,
+                    _r.scrollOffset,
```
Comment (DHowett) [inline src/renderer/atlas/AtlasEngine.r.cpp:710]: we change `previousDirtyRectInPx`, but we don't clear `scrollOffset`. Is this OK?

File: src/renderer/atlas/AtlasEngine.r.cpp [hunk 12]
```diff
@@ -540,64 +537,436 @@ void AtlasEngine::_drawCursor()
...
+        _r.brushColor = 0xffffffff;
+    }
+}
+
+void AtlasEngine::_d2dDrawDirtyArea()
+{
+    struct CellFlagHandler
+    {
+        CellFlags filter;
+        decltype(&AtlasEngine::_d2dCellFlagRendererCursor) func;
```
Comment (DHowett) [inline src/renderer/atlas/AtlasEngine.r.cpp:770]: _wow, clever_. I love this function.

File: src/renderer/atlas/AtlasEngine.r.cpp [hunk 13]
```diff
@@ -540,64 +537,436 @@ void AtlasEngine::_drawCursor()
...
+AtlasEngine::u16 AtlasEngine::_d2dDrawGlyph(const TileHashMap::iterator& it, const u16x2 coord, const u32 color)
+{
+    const auto key = it->first.data();
+    const auto value = it->second.data();
+    const auto charsLength = key->charCount;
+    const auto cellCount = key->attributes.cellCount;
+    const auto textFormat = _getTextFormat(key->attributes.bold, key->attributes.italic);
+    const auto coloredGlyph = WI_IsFlagSet(value->flags, CellFlags::ColoredGlyph);
+
+    auto& cachedLayout = it->second.cachedLayout;
```
Comment (DHowett) [inline src/renderer/atlas/AtlasEngine.r.cpp:883]: nevermind i see where "it does a cache"

**Review by DHowett — APPROVED** [review]
Fifteen comments and I am still throwing it a sign-off. This is brilliant.

File: src/renderer/atlas/AtlasEngine.cpp (hunk 2 above)
Comment (zadjii-msft) [reply src/renderer/atlas/AtlasEngine.cpp:790]: I think it's okay cause we just need a render target that's big enough for `cellCount` glyphs - it doesn't care if it's NxM or MxN or (2M)x(N/2), right?

File: src/renderer/atlas/AtlasEngine.r.cpp [hunk 14]
```diff
@@ -540,64 +537,436 @@ void AtlasEngine::_drawCursor()
...
+    __assume(d2dRenderTarget != nullptr);
+
+    if (scalingRequired)
+    {
+        static constexpr D2D1_MATRIX_3X2_F identity{ 1, 0, 0, 1, 0, 0 };
+        d2dRenderTarget->SetTransform(&identity);
+    }
+}
+
+void AtlasEngine::_d2dPresent()
```
Comment (zadjii-msft) [inline src/renderer/atlas/AtlasEngine.r.cpp:657]: aside - does it almost make sense to just have `AtlasD2D.r.cpp` or something for all these `AtlasEngine::_d2d*` methods?

**Comment by lhecker** [comment]
> Does this engine automatically enable/disable this mode when you RDP in? Do we need something special to enable that?
> AKA: I don't want to compromise the experience for somebody who returns to their desk after being remote.

This won't switch automatically. We'd have to run this test every time the display the application is on changes. Coincidentally I have an open task left to create the D3D device for the GPU the window is on instead of using the default/primary GPU. We can then add the check there and we'd get the automatic switching for free.

Until then I'd not overcomplicate this too much. PCs/workstations usually have GPUs and on those devices we should use the proper AtlasEngine no matter what.

In fact, now that I'm saying that, I'd like to propose an improved `d2dMode` check: We should simply test whether the D3D device is a WARP/Hyper-V adapter and then always use D2D. This would probably be a more robust check.

File: src/renderer/atlas/AtlasEngine.cpp (hunk 1 above)
Comment (lhecker) [reply src/renderer/atlas/AtlasEngine.cpp:327]: image

✨ No worries. ✨

File: src/renderer/atlas/AtlasEngine.h (hunk 4 above)
Comment (zadjii-msft) [reply src/renderer/atlas/AtlasEngine.h:352]: _double yikes_

**Review by zadjii-msft — COMMENTED** [review]
I'm only 2/3 RN but here are comments from those before the EOD

File: src/renderer/atlas/AtlasEngine.cpp (hunk 1 above)
Comment (lhecker) [reply src/renderer/atlas/AtlasEngine.cpp:327]: I made this change because I noticed that this `WaitForSingleObjectEx` returns within 1 V-Sync even if the window is minimized, which is weird - nothing got shown after all. In other words: OpenConsole renders even if the window is minimized, which is fairly wasteful.

...so I put `INFINITE` there, which is what the D3D demo code uses, but it didn't help either. But it surely won't hurt if we ever figure out why `frameLatencyWaitableObject` gets signaled.

If this does cause issues (e.g. because this blocks us from destroying the render thread) then we shouldn't change this `INFINITE` but rather any other potential cause, because I'm planning to add this check which might also block indefinitely: https://docs.microsoft.com/en-us/windows/win32/direct3ddxgi/waiting-when-occluded

File: src/renderer/atlas/AtlasEngine.cpp (hunk 2 above)
Comment (lhecker) [reply src/renderer/atlas/AtlasEngine.cpp:790]: `cellCount` is actually a `u16x2` - or in other words a x/y pair of `uint16_t`.
This comparison will return `true` if you pass it `30x29` vs. `29x30`. 🙂

File: src/renderer/atlas/AtlasEngine.cpp (hunk 3 above)
Comment (lhecker) [reply src/renderer/atlas/AtlasEngine.cpp:842]: Good point, because this comment is certainly outdated. We now support margins for the renderer (see the `backgroundColor` variable in `shader_ps.hlsl`).

File: src/renderer/atlas/AtlasEngine.h (hunk 4 above)
Comment (lhecker) [reply src/renderer/atlas/AtlasEngine.h:352]: I believe so. If it makes yourself more comfortable I can use `std::destruct_at` and `std::construct_at` (which is valid to do), but they basically do the exact same thing. 😅

The current code leaks memory however so this fix is somewhat important.

File: src/renderer/atlas/AtlasEngine.h (hunk 5 above)
Comment (lhecker) [reply src/renderer/atlas/AtlasEngine.h:551]: Yes only `AtlasValueData` needs to be POD.

File: src/renderer/atlas/AtlasEngine.r.cpp (hunk 7 above)
Comment (lhecker) [reply src/renderer/atlas/AtlasEngine.r.cpp:67]: `_d2dPresent` throws on error. I don't really use status codes in this class.

File: src/renderer/atlas/AtlasEngine.r.cpp (hunk 14 above)
Comment (lhecker) [reply src/renderer/atlas/AtlasEngine.r.cpp:657]: I'm planning a larger reorganization of the code at a later point. I'm not 100% sure whether such a split will be helpful, since the `_d2d*` function do use a lot of common logic of the regular AtlasEngine code, but if we want to split it I'd do it then.

File: src/renderer/atlas/AtlasEngine.r.cpp (hunk 13 above)
Comment (lhecker) [reply src/renderer/atlas/AtlasEngine.r.cpp:883]: Naming is hard. 🥲

File: src/renderer/atlas/AtlasEngine.r.cpp (hunk 11 above)
Comment (lhecker) [reply src/renderer/atlas/AtlasEngine.r.cpp:710]: I believe so. `previousDirtyRectInPx` is the only thing that should carry over to the next frame.

File: src/renderer/atlas/AtlasEngine.cpp (hunk 1 above)
Comment (lhecker) [reply src/renderer/atlas/AtlasEngine.cpp:327]: You know what, I'll revert this. No point in making unnecessary changes if they don't improve anything.

**Review by DHowett — APPROVED** [review]

File: src/renderer/atlas/AtlasEngine.cpp [hunk 15]
```diff
@@ -641,12 +633,15 @@ void AtlasEngine::_createResources()
...
 
-    // > You should not use GetSystemMetrics(SM_REMOTESESSION) to determine if your application is running
-    // > in a remote session in Windows 8 and later or Windows Server 2012 and later if the remote session
-    // > may also be using the RemoteFX vGPU improvements to the Microsoft Remote Display Protocol (RDP).
-    // > In this case, GetSystemMetrics(SM_REMOTESESSION) will identify the remote session as a local session.
-    // This actually sounds great for us. The non-d2dMode of AtlasEngine has more features, but requires a GPU.
-    _r.d2dMode = debugForceD2DMode || GetSystemMetrics(SM_REMOTESESSION);
+    {
+        wil::com_ptr<IDXGIAdapter1> dxgiAdapter;
+        THROW_IF_FAILED(_r.device.query<IDXGIObject>()->GetParent(__uuidof(dxgiAdapter), dxgiAdapter.put_void()));
```
Comment (DHowett) [inline src/renderer/atlas/AtlasEngine.cpp:638]: nit: i'm surprised `IID_PPV_ARGS` didn't work here.. or would it?

File: src/renderer/atlas/AtlasEngine.r.cpp [hunk 16]
```diff
@@ -62,45 +62,53 @@ using namespace Microsoft::Console::Render;
...
 try
 {
+    // See documentation for IDXGISwapChain2::GetFrameLatencyWaitableObject method:
+    // > For every frame it renders, the app should wait on this handle before starting any rendering operations.
+    // > Note that this requirement includes the first frame the app renders with the swap chain.
+    assert(debugGeneralPerformance || _r.frameLatencyWaitableObjectUsed);
+
     if (_r.d2dMode) [[unlikely]]
     {
+        // TODO gutters
```
Comment (DHowett) [inline src/renderer/atlas/AtlasEngine.r.cpp:72]: This commit says "paint the gutters"; is this still a to-do?

File: src/renderer/atlas/AtlasEngine.cpp (hunk 15 above)
Comment (lhecker) [reply src/renderer/atlas/AtlasEngine.cpp:638]: It would but most code in this class doesn't use it so I kept the pattern.

Comment (lhecker) [reply src/renderer/atlas/AtlasEngine.cpp:638]: (The reason I did this is because I wanted more (and more obvious) control over whether `.put()`, `.addressof()`, etc. are used.)

**Comment by DHowett** [comment]
@msftbot make sure @winobjc-bot signs off

**Comment by DHowett** [comment]
This is a stacked PR, so it can no longer be automerged.

File: src/renderer/atlas/AtlasEngine.r.cpp [hunk 17]
```diff
@@ -234,55 +234,53 @@ void AtlasEngine::_adjustAtlasSize()
...
-    if (_r.glyphQueue.empty())
+    if (_r.glyphQueue.empty() && WI_IsFlagClear(_r.invalidations, RenderInvalidations::Cursor))
     {
         return;
     }
 
     _r.d2dRenderTarget->BeginDraw();
-    for (const auto& pair : _r.glyphQueue)
+
+    if (WI_IsFlagSet(_r.invalidations, RenderInvalidations::Cursor))
```
Comment (zadjii-msft) [inline src/renderer/atlas/AtlasEngine.r.cpp:259]: note: cursor drawing moved here

**Review by zadjii-msft — APPROVED** [review]
okay this is friggin amazing. Especially `AtlasEngine::_d2dDrawDirtyArea`. Absolutely nuts.

File: src/renderer/atlas/AtlasEngine.r.cpp (hunk 17 above)
Comment (lhecker) [reply src/renderer/atlas/AtlasEngine.r.cpp:259]: This is so that I avoid calling `BeginDraw()` twice and allow D2D to batch up cursor and glyph drawing in a single render pass.
