### PR TITLE
Reduce instances of font fallback dialog

### LINKED ISSUE #9375: Unable to find the selected font "Cascadia Mono".
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.19042.0
Windows Terminal version: 1.6.10571.0
```

# Steps to reproduce
This 'happens on my machine', not sure if easily reproducible.
- Start Microsoft Terminal

# Expected behavior
Microsoft terminal opens on the default terminal

# Actual behavior
A pop-up is shown with the following error message:
screenshot of the error message
Transcript:  
```none
Warning

Unable to find the selected font "Cascadia Mono".

"Consolas" has been selected instead.

Please either install the missing font or choose another one.
```

# Additional information
Other applications, Microsoft Word, Paint.NET, show the `Cascadia Mono` font and allow usage without any issues.

### PR DESCRIPTION
**Pull request by miniksa**
Reduce instances of font fallback dialog through package font loading,
basic name trimming, and revised fallback test

- Adjusts the font dialog to only show when we attempt last-chance
  resolution from our hardcoded list of font names with a flag instead
  of with a string comparison by name
- Adds a resolution step to trim the font name by word from the end and
  retry to attempt to resolve a proper font that just has a weight
  suffix
- Adds a second font collection to font loading that will attempt to
  locate all TTF files sitting next to our binary, like in our package

- [x] Wrote my font preference in the JSON as `Cascadia Code Heavy` and
  watched it quietly resolve to just `Cascadia Code` without the dialog.
- [x] Put a font that isn't registered with the system into the layout
  directory for the package, set it as my desired font in Terminal, and
  watched it load just fine.
- [x] Try a font name with different casing and see if dialog doesn't
  pop anymore
- [x] Try a font with different (localized) names like ＭＳ ゴシック and
  see if dialog doesn't pop anymore
- [x] Check Win7 with WPF target

Closes #9375

### CODE REVIEW

File: src/renderer/dx/DxFontRenderData.cpp [hunk 1]
```diff
@@ -36,6 +36,50 @@ DxFontRenderData::DxFontRenderData(::Microsoft::WRL::ComPtr<IDWriteFactory1> dwr
     return _systemFontFallback;
 }
 
+[[nodiscard]] Microsoft::WRL::ComPtr<IDWriteFontCollection1> DxFontRenderData::PackageCollection() const
```
Comment (DHowett) [inline src/renderer/dx/DxFontRenderData.cpp:39]: I'm sad that we have to do this _once per font render data_(!) or even once per renderer, because the package is entirely read-only and we shouldn't need to hit the disk this many times per new terminal page :/

I get that we do because of the factory, but is there really no way?

Comment (miniksa) [reply src/renderer/dx/DxFontRenderData.cpp:39]: I mean I could hit the disk to lookup the paths outside the render instantiation and pass that in so the collection is made off of precached paths instead of one lookup per.

Comment (miniksa) [reply src/renderer/dx/DxFontRenderData.cpp:39]: Or per our chat... magic static the path grovel and cache in a vector to stay relatively contained.

File: src/renderer/dx/DxFontRenderData.h [hunk 2]
```diff
@@ -87,6 +92,7 @@ namespace Microsoft::Console::Render
         ::Microsoft::WRL::ComPtr<IBoxDrawingEffect> _boxDrawingEffect;
 
         ::Microsoft::WRL::ComPtr<IDWriteFontFallback> _systemFontFallback;
+        mutable ::Microsoft::WRL::ComPtr<IDWriteFontCollection1> _nearbyCollection;
```
Comment (zadjii-msft) [inline src/renderer/dx/DxFontRenderData.h:95]: > `mutable`

ew, but I get it. Almost feels like this should be static too, but idgaf

**Review by zadjii-msft — APPROVED** [review]

**Comment by zadjii-msft** [comment]
Thanks for making it a magic static - that's way better

File: src/renderer/dx/DxFontRenderData.cpp [hunk 3]
```diff
@@ -753,3 +848,37 @@ CATCH_RETURN()
...
+    const auto folder = module.parent_path();
+
+    for (auto& p : std::filesystem::directory_iterator(folder))
+    {
+        if (p.is_regular_file())
+        {
+            auto extension = p.path().extension().wstring();
+            std::transform(extension.begin(), extension.end(), extension.begin(), std::towlower);
+
+            const std::wstring_view ttfExtension{ L".ttf" };
```
Comment (DHowett) [inline src/renderer/dx/DxFontRenderData.cpp:875]:
```suggestion
            static constexpr std::wstring_view ttfExtension{ L".ttf" };
```

Comment (DHowett) [reply src/renderer/dx/DxFontRenderData.cpp:875]: otherwise it gets initialized as from pointer+length pair every iteration of the loop (worst case)

File: src/renderer/dx/DxFontRenderData.cpp [hunk 4]
```diff
@@ -753,3 +848,37 @@ CATCH_RETURN()
...
+// Return Value:
+// - Iterable collection of filesystem paths, one per font file that was found
+[[nodiscard]] std::vector<std::filesystem::path> DxFontRenderData::s_GetNearbyFonts()
+{
+    std::vector<std::filesystem::path> paths;
+
+    // Find the directory we're running from then enumerate all the TTF files
+    // sitting next to us.
+    const std::filesystem::path module{ wil::GetModuleFileNameW<std::wstring>(nullptr) };
+    const auto folder = module.parent_path();
```
Comment (DHowett) [inline src/renderer/dx/DxFontRenderData.cpp:866]: nit: mixed `=` and `{}` initialization syntax across lines

File: src/renderer/dx/DxFontRenderData.cpp [hunk 5]
```diff
@@ -36,6 +36,51 @@ DxFontRenderData::DxFontRenderData(::Microsoft::WRL::ComPtr<IDWriteFactory1> dwr
...
 }
 
+// Routine Description:
+// - Creates a DirectWrite font collection of font files that are sitting next to the running
+//   binary (in the same directory as the EXE).
+// Arguments:
+// - <none>
+// Return Value:
+// - DirectWrite font collection
+[[nodiscard]] Microsoft::WRL::ComPtr<IDWriteFontCollection1> DxFontRenderData::NearbyCollection() const
```
Comment (DHowett) [inline src/renderer/dx/DxFontRenderData.cpp:46]: nit: the return signature for this function ensures that everybody gets an AddRef and Release. You could instead use `const &` on the return to save a single addref/release in places like `NearbyCollection().Thing()`

File: src/renderer/dx/DxFontRenderData.cpp [hunk 6]
```diff
@@ -36,6 +36,51 @@ DxFontRenderData::DxFontRenderData(::Microsoft::WRL::ComPtr<IDWriteFactory1> dwr
...
+        THROW_IF_FAILED(factory3->CreateFontSetBuilder(&fontSetBuilder));
+
+        // Builder2 has a convenience to just feed in paths to font files.
+        ::Microsoft::WRL::ComPtr<IDWriteFontSetBuilder2> fontSetBuilder2;
+        THROW_IF_FAILED(fontSetBuilder.As(&fontSetBuilder2));
+
+        // Find the directory we're running from then enumerate all the TTF files
+        // sitting next to us.
+        const std::filesystem::path module{ wil::GetModuleFileNameW<std::wstring>(nullptr) };
+        const auto folder = module.parent_path();
```
Comment (DHowett) [inline src/renderer/dx/DxFontRenderData.cpp:68]: suspect you don't need this any more..

File: src/renderer/dx/DxFontRenderData.cpp [hunk 7]
```diff
@@ -578,37 +627,76 @@ CATCH_RETURN()
...
+        // an unexpected error dialog. We theoretically could detect the weight words and convert them, but this
+        // is the quick fix for the majority scenario.
+        // The long/full fix is backlogged to GH#xxxx
+        // Also this doesn't count as a fallback because we don't want to annoy folks with the warning dialog over
+        // this resolution.
+        while (!face && !familyName.empty())
         {
-            familyName = fallbackFace;
-            face = _FindFontFace(familyName, weight, stretch, style, localeName);
+            const auto lastSpace = familyName.find_last_of(L'\x20');
```
Comment (DHowett) [inline src/renderer/dx/DxFontRenderData.cpp:656]: yo we have a `UNICODE_SPACE` def don't we

File: src/renderer/dx/DxFontRenderData.cpp [hunk 8]
```diff
@@ -578,37 +627,76 @@ CATCH_RETURN()
...
     auto face = _FindFontFace(familyName, weight, stretch, style, localeName);
 
     if (!face)
     {
-        for (const auto fallbackFace : FALLBACK_FONT_FACES)
+        // If we missed, try looking a little more by trimming the last word off the requested family name a few times.
+        // Quite often, folks are specifying weights or something in the familyName and it causes failed resolution and
+        // an unexpected error dialog. We theoretically could detect the weight words and convert them, but this
+        // is the quick fix for the majority scenario.
+        // The long/full fix is backlogged to GH#xxxx
```
Comment (DHowett) [inline src/renderer/dx/DxFontRenderData.cpp:651]: XXXX

**Review by DHowett — CHANGES_REQUESTED** [review]

**Comment by DHowett** [comment]
"let me do my work," he says!

Windows 7 is now that work

File: src/renderer/dx/DxFontRenderData.h (hunk 2 above)
Comment (miniksa) [reply src/renderer/dx/DxFontRenderData.h:95]: its non static because it's tied to the factory which is a construction parameter and could theoretically change per instance so we're gonna close with no f given

**Comment by miniksa** [comment]
> "let me do my work," he says!
> 
> Windows 7 is now that work

[`89e9870` (#9734)](https://github.com/microsoft/terminal/pull/9734/commits/89e9870125efaacfdc18f7f41e0226414785e4b3) should cover it but I'll probably ask you to help triple check.

**Comment by skyline75489** [comment]
Maybe this isn't a good time...but this will conflict with #9201. I think we might want to merge #9201 first which will simplify this PR, too.

**Comment by DHowett** [comment]
@skyline75489 I appreciate that, and thanks for your work in #9201! I'm inclined to merge this one first just so that we can be ready for the 1.7 release (next week; hit me up on Teams for why this is important :)) and then get reviews in 9201. I know that it complicates your life because you have some merging to do 😦 and I am sorry about that.

File: src/renderer/dx/DxFontRenderData.cpp [hunk 9]
```diff
@@ -642,6 +734,19 @@ CATCH_RETURN()
     BOOL familyExists;
     THROW_IF_FAILED(fontCollection->FindFamilyName(familyName.data(), &familyIndex, &familyExists));
 
+    // If the system collection missed, try the files sitting next to our binary.
+    if (!familyExists)
+    {
+        const auto nearbyCollection = NearbyCollection();
```
Comment (DHowett) [inline src/renderer/dx/DxFontRenderData.cpp:740]: it's the tiniest nit, but this will reintroduce the addref/release. I also don't _really_ care at this point because it's not on every single font lookup or call to NearbyCollection.

I *think* the correct resolution is `auto&& nearbyCollection = NearbyCollection()`, whiich should derive a const reference automatically? Let me.. test that in godbolt

Comment (DHowett) [reply src/renderer/dx/DxFontRenderData.cpp:740]: auto&& or const auto& works for this.

Comment (DHowett) [reply src/renderer/dx/DxFontRenderData.cpp:740]:
```suggestion
        auto&& nearbyCollection = NearbyCollection();
```

**Comment by DHowett** [comment]
I tested ＭＳ ゴシック using WPF; it did not trigger the fallback code path.

**Review by DHowett — APPROVED** [review]
I forgot that I didn't sign off.
