### PR TITLE
Only use Mica in the SUI if Mica is available

### LINKED ISSUE #14667: Mica in the SUI BG doesn't work on Win10
This build appears to have resolved it for me in initial testing, with a completely unrelated side effect of the dark mode for settings having the light mode color background rendering it completely unreadable (but it at least appears to resolve this actual issue from what I can see so far)

image

_Originally posted by @spootle in https://github.com/microsoft/terminal/issues/13388#issuecomment-1379527904_

### PR DESCRIPTION
**Pull request by zadjii-msft**
This should make sure we only use Mica for the BG of the SUI when we're on a Windows build that supports it. Otherwise, we're just gonna get the emergency backstop / full transparency under it. 

Confirmed this fixes it on my win10 VM.

Closes #14667

### CODE REVIEW

**Comment by zadjii-msft** [comment]
Hmm. This didn't fix it. Weird.

**Review by carlos-zamora — APPROVED** [review]

File: src/cascadia/TerminalSettingsEditor/MainPage.cpp [hunk 1]
```diff
@@ -645,8 +645,23 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
...
+            osver.dwBuildNumber = 22621;
+            DWORDLONG dwlConditionMask = 0;
+            VER_SET_CONDITION(dwlConditionMask, VER_BUILDNUMBER, VER_GREATER_EQUAL);
+            return VerifyVersionInfoW(&osver, VER_BUILDNUMBER, dwlConditionMask) != FALSE;
+        }();
+
+        if (!isMicaAvailable)
+        {
+            return;
+        }
```
Comment (lhecker) [inline src/cascadia/TerminalSettingsEditor/MainPage.cpp:663]: I believe it'd be better long-term to come up with a way how we can get to the return value of `DwmSetWindowAttribute` in `IslandWindow::UseMica` instead.

Comment (zadjii-msft) [reply src/cascadia/TerminalSettingsEditor/MainPage.cpp:663]: I don't disagree, but that starts to be a little tricky from a layering perspective. The SUI dll doesn't link against anything at the window level, so it can't check that itself.

So instead we'd have to plumb the result back down from the window->app->SUI, to say "yes, you requested mica _and you got it_". That's doable, I suppose

Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/MainPage.cpp:663]: Consider using, ah, well...

We pass the HWND down into the settings UI so that we can parent the file dialogs appropriately.

You could use `DwmGetWindowAttribute` on that HWND to see whether Mica is, in fact, enabled...

File: src/cascadia/TerminalSettingsEditor/MainPage.cpp [hunk 2]
```diff
@@ -645,8 +649,30 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
...
+            const auto hr = DwmGetWindowAttribute(*_hostingHwnd, DWMWA_SYSTEMBACKDROP_TYPE, &attribute, sizeof(attribute));
+            if (SUCCEEDED(hr))
+            {
+                isMicaAvailable = attribute == DWMSBT_MAINWINDOW;
+            }
+        }
+
+        if (!isMicaAvailable)
+        {
+            return;
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/MainPage.cpp:673]: now, does this hot reload if you turn mica off? ;)

**Review by DHowett — APPROVED** [review]

File: src/cascadia/TerminalSettingsEditor/MainPage.cpp (hunk 2 above)
Comment (zadjii-msft) [reply src/cascadia/TerminalSettingsEditor/MainPage.cpp:673]: Sure seemed like it did
