### PR TITLE
Fix multiple regressions since #18215

### LINKED ISSUE #18331: Alt and F7 don't work in 1.23.3481.0
### Windows Terminal version

1.23.3481.0

### Windows build number

10.0.19045.5247

### Other Software

FAR Manager 3.0.6401.0 x64

when migrate from canary build terminal-1.23.3461.0 to next canary build terminal-1.23.3481.0
i have trouble with keys: Alt/RAlt and F7

### Steps to reproduce

run utility KeyEvents.exe and press Alt and F7

### Expected Behavior

result when press Alt:

terminal-1.23.3461.0 - good behavior
02:56:37 KEY_EVENT_RECORD: Dn, 1, Vk="VK_MENU" [18/0x0012], Scan=0x0038 uChar=[U=' ' (0x0000): A=' ' (0x00)]
         Ctrl=0x00000002 (cAsac - ecns) (Windowed)
02:56:37 KEY_EVENT_RECORD: Up, 1, Vk="VK_MENU" [18/0x0012], Scan=0x0038 uChar=[U=' ' (0x0000): A=' ' (0x00)]
         Ctrl=0x00000000 (casac - ecns) (Windowed)

result when press f7:

terminal-1.23.3461.0 - good behavior

03:08:36 KEY_EVENT_RECORD: Dn, 1, Vk="VK_F7" [118/0x0076], Scan=0x0041 uChar=[U=' ' (0x0000): A=' ' (0x00)]
         Ctrl=0x00000000 (casac - ecns) (Windowed)
03:08:36 KEY_EVENT_RECORD: Up, 1, Vk="VK_F7" [118/0x0076], Scan=0x0041 uChar=[U=' ' (0x0000): A=' ' (0x00)]
         Ctrl=0x00000000 (casac - ecns) (Windowed)

### Actual Behavior

result when press Alt:

terminal-1.23.3481.0 - bad behavior
02:54:44 KEY_EVENT_RECORD: Up, 1, Vk="VK_MENU" [18/0x0012], Scan=0x0038 uChar=[U=' ' (0x0000): A=' ' (0x00)]
         Ctrl=0x00000002 (cAsac - ecns) (Windowed)

result when press f7:

terminal-1.23.3481.0 - bad behavior
03:02:27 KEY_EVENT_RECORD: Dn, 1, Vk="VK_F7" [118/0x0076], Scan=0x0041 uChar=[U=' ' (0x0000): A=' ' (0x00)]
         Ctrl=0x00000000 (casac - ecns) (Windowed)
03:02:27 KEY_EVENT_RECORD: Dn, 1, Vk="VK_F7" [118/0x0076], Scan=0x0041 uChar=[U=' ' (0x0000): A=' ' (0x00)]
         Ctrl=0x00000000 (casac - ecns) (Windowed)

### LINKED ISSUE #18335: Mouse pointer "vanishes" when moved over Terminal Window
📝where'd this go

_Originally posted by @zadjii-msft in https://github.com/microsoft/terminal/pull/18215#discussion_r1880139859_
            
Probably this

### PR DESCRIPTION
**Pull request by lhecker**
Fixes
* Cursor vanishing, because
  ```cpp
  CoreWindow::GetForCurrentThread().PointerCursor()
  ```
  returned a non-null, but still invisible cursor.
* Alt/F7 not dispatching to newly created windows, because the
  `WM_ACTIVATE` message now arrives before the `AppHost` is initialized.
  This caused the messages to be delivered to old windows.
* Windows Terminal blocking expedited shutdown,
  because we return `FALSE` on non-`ENDSESSION_CLOSEAPP` messages.

Closes #18331
Closes #18335

## Validation Steps Performed
* Cursor still doesn't really vanish for me in the first place ✅
* Alt/F7 work in new windows without triggering old ones ✅

### CODE REVIEW

File: src/cascadia/WindowsTerminal/WindowEmperor.cpp [hunk 1]
```diff
@@ -442,6 +437,40 @@ void WindowEmperor::HandleCommandlineArgs(int nCmdShow)
     __assume(false);
 }
 
+void WindowEmperor::_dispatchSpecialKey(MSG& msg) const
+{
+    const auto hwnd = msg.hwnd;
+    AppHost* window = nullptr;
+
+    // Just in case someone has targed a specific HWND,
```
Comment (DHowett) [inline src/cascadia/WindowsTerminal/WindowEmperor.cpp:445]: targeted

```suggestion
    // Just in case someone has targeted a specific HWND,
```

**Review by DHowett — APPROVED** [review]

File: src/cascadia/WindowsTerminal/WindowEmperor.cpp [hunk 2]
```diff
@@ -826,14 +855,10 @@ LRESULT WindowEmperor::_messageHandler(HWND window, UINT const message, WPARAM c
...
-                // ENDSESSION_CLOSEAPP: The application is using a file that must be replaced,
-                // the system is being serviced, or system resources are exhausted.
-                RegisterApplicationRestart(nullptr, RESTART_NO_CRASH | RESTART_NO_HANG);
-                return TRUE;
-            }
-            return FALSE;
+            // ENDSESSION_CLOSEAPP: The application is using a file that must be replaced,
+            // the system is being serviced, or system resources are exhausted.
+            RegisterApplicationRestart(nullptr, RESTART_NO_CRASH | RESTART_NO_HANG);
+            return TRUE;
```
Comment (k-jeznach) [inline src/cascadia/WindowsTerminal/WindowEmperor.cpp:861]: Wouldn't it be better for code consistency to write `return 1`, or possibly adjust the rest of the method code to use `return FALSE` instead?

Comment (lhecker) [reply src/cascadia/WindowsTerminal/WindowEmperor.cpp:861]: FWIW I did it this way because the documentation for this message uses `TRUE` and `FALSE`.
