### PR TITLE
Re-add the keychords to the new tab flyout

### LINKED ISSUE #3896: Dropdown menu no longer displays bound keys again (after #3825)
This no longer works. Possible regression from #3825?

image

### PR DESCRIPTION
**Pull request by zadjii-msft**
## Summary of the Pull Request

On this month's episode of "Mike accidentally breaks this": 
  Mike forgets that `==` is defined on a pair of winrt objects as "do these point to the _SAME_ object", not "do they have the same values". 

This just slipped right through code review.

## References

Broken in #3825

## PR Checklist
* [x] Closes #3896
* [x] I work here
* [ ] Tests added/passed
* [n/a] Requires documentation to be updated

## Validation Steps Performed

Manually checked that these are still there

### CODE REVIEW

File: src/cascadia/TerminalApp/ActionArgs.h [hunk 1]
```diff
@@ -132,7 +127,7 @@ namespace winrt::TerminalApp::implementation
             auto otherAsUs = other.try_as<NewTabArgs>();
             if (otherAsUs)
             {
-                return otherAsUs->_TerminalArgs == _TerminalArgs;
+                return otherAsUs->_TerminalArgs.Equals(_TerminalArgs);
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalApp/ActionArgs.h]: I think we actually need a less strict check than this, right? like: if I bind a profile guid, name OR index to newTab, should it show up in the list?
