### PR TITLE
AtlasEngine: Fix uneven baselines when scaling glyphs

### LINKED ISSUE #13987: Some fonts' italic text has wavy baselines
### Windows Terminal version

1.16.2523.0

### Windows build number

10.0.19043.0

### Other Software

neovim 0.7.2 (WSL2)
FiraCode NF, 12pt as Terminal Font
colorscheme github_dark

### Steps to reproduce

Open a java source code file and comments are wavy, non-comment code lines are as expected
WavyCommentLines

### Expected Behavior

Open a java source code file and comments look the same way as other code lines

### Actual Behavior

comment lines are wavy

### PR DESCRIPTION
**Pull request by lhecker**
This commit changes the glyph scale algorithm to prefer aligning glyphs to
their baseline. This improves the visual appearance of simulated italic glyphs.
However wide Emojis in narrow cells now look slightly worse without centering.

Closes #13987

## Validation Steps Performed
* Use FiraCode which has no italic variant and instead uses simulated italics
* Write italic text
* Baseline is consistent ✅

### CODE REVIEW

**Comment by lhecker** [comment]
atlas_engine_baseline

**Comment by DHowett** [comment]
in "new" the vertical stems of letters (primarily `r`) become more blurry.

**Comment by lhecker** [comment]
Ah woops... The old one is using ClearType and the new one had it disabled and that makes "Old" to appear more crisp. If you open the image in a new tab and zoom in, you can see that the stems are practically identical.

**Comment by DHowett** [comment]
Well, it looks _less_ weird... !

**Comment by lhecker** [comment]
Yep, agreed. I'll try to make it work properly and as expected without downsizing in a follow-up PR.

File: src/renderer/atlas/AtlasEngine.r.cpp [hunk 1]
```diff
@@ -627,34 +623,27 @@ AtlasEngine::CachedGlyphLayout AtlasEngine::_getCachedGlyphLayout(const wchar_t*
         //   --> offsetY = 0
         //   --> scale   = layoutBox.y / (layoutBox.y + left + right)
         //               = 0.69f
-        offset.x = clampedOverhang.left - clampedOverhang.right;
-        offset.y = clampedOverhang.top - clampedOverhang.bottom;
+        offset.x = std::max(0.0f, overhang.left) - std::max(0.0f, overhang.right);
```
Comment (DHowett) [inline src/renderer/atlas/AtlasEngine.r.cpp:626]: This changes how overhangs are dealt with; do we need to update the explanatory comment above? Specifically I notice that the "bar diacritic" part has a negative left value...

File: src/renderer/atlas/AtlasEngine.r.cpp [hunk 2]
```diff
@@ -627,34 +623,27 @@ AtlasEngine::CachedGlyphLayout AtlasEngine::_getCachedGlyphLayout(const wchar_t*
...
         {
             scalingRequired = true;
             offset.x = (overhang.left - overhang.right) * 0.5f;
-            scale.x = layoutBox.x / actualSize.x;
+            scale.x = layoutBox.x / actualSizeX;
             scale.y = scale.x;
+            scaleCenter.x = layoutBox.x * 0.5f;
         }
-        if ((actualSize.y - layoutBox.y) > _r.dipPerPixel)
+        if (overhang.top > _r.dipPerPixel || overhang.bottom > _r.dipPerPixel)
```
Comment (DHowett) [inline src/renderer/atlas/AtlasEngine.r.cpp:638]: this is after the overhangs have been sign-adjusted, right?

File: src/renderer/atlas/AtlasEngine.r.cpp [hunk 3]
```diff
@@ -672,11 +661,19 @@ AtlasEngine::CachedGlyphLayout AtlasEngine::_getCachedGlyphLayout(const wchar_t*
     // where every single "=" might be blatantly misaligned vertically (same for any box drawings).
     WI_SetFlagIf(options, D2D1_DRAW_TEXT_OPTIONS_NO_SNAP, scalingRequired);
 
+    // ClearType basically has a 3x higher horizontal resolution. To make our glyphs render the same everywhere,
+    // it's probably for the best to ensure we initially rasterize them on a whole pixel boundary.
+    // (https://en.wikipedia.org/wiki/ClearType#How_ClearType_works)
+    offset.x = roundf(offset.x * _r.pixelPerDIP) * _r.dipPerPixel;
+    // As explained below, we use D2D1_DRAW_TEXT_OPTIONS_NO_SNAP to prevent a weird issue with baseline snapping.
+    // But we do want it technically, so this re-implements baseline snapping... I think?
```
Comment (DHowett) [inline src/renderer/atlas/AtlasEngine.r.cpp:669]: reviewer note: comment is not new, don't think too hard about the `... I think?"

File: src/renderer/atlas/AtlasEngine.r.cpp (hunk 1 above)
Comment (lhecker) [reply src/renderer/atlas/AtlasEngine.r.cpp:626]: No the big comment is still up to date. This particular change (for `offset.x`) is equivalent to the old code. `clampedOverhang` used to be computed as:
```cpp
const DWRITE_OVERHANG_METRICS clampedOverhang{
    std::max(0.0f, overhang.left),
    std::max(0.0f, overhang.top),
    std::max(0.0f, overhang.right),
    std::max(0.0f, overhang.bottom),
};
```

File: src/renderer/atlas/AtlasEngine.r.cpp (hunk 2 above)
Comment (lhecker) [reply src/renderer/atlas/AtlasEngine.r.cpp:638]: You mean clamped? In that case: No, these are the raw overhangs and a positive value indicates that the glyph clips outside of the layout box we've given it.

**Review by DHowett — APPROVED** [review]

**Review by carlos-zamora — APPROVED** [review]
