### PR TITLE
Reintroduce a color compatibility hack, but only for PowerShells

### LINKED ISSUE #6767: Black background in PowerShell commands
Since commit ddbe370 (#6506) a black background appears after space in commands while using PowerShell.

# Environment

```none
Windows build number: 10.0.19041.329
Windows Terminal versions: all since commit ddbe370
```

# Steps to reproduce

1. Open PowerShell (tested in 5.1 and 7.0.2)
2. Do either of these:
   - press space,
   - write anything and press space,
   - use the arrow up to display a command from history that contains a space character.

# Expected behavior

The background colour does not change and the acrylic effect is visible.
terminal_PS_older

# Actual behavior

A weird black background appears after the space character.
terminal_PS_black_bg

### PR DESCRIPTION
**Pull request by DHowett**
There is going to be a very long tail of applications that will
explicitly request VT SGR 40/37 when what they really want is to
SetConsoleTextAttribute() with a black background/white foreground.
Instead of making those applications look bad (and therefore making us
look bad, because we're releasing this as an update to something that
"looks good" already), we're introducing this compatibility quirk.
Before the color reckoning in #6698 + #6506, *every* color was subject
to being spontaneously and erroneously turned into the default color.
Now, only the 16-color palette value that matches the active console
background/foreground color will be destroyed, and only when received
from specific applications.

Removal will be tracked by #6807.

Michael and I discussed what layer this quirk really belonged in. I
originally believed it would be sufficient to detect a background color
that matched the legacy default background, but @j4james provided an
example of where that wouldn't work out (powershell setting the
foreground color to white/gray). In addition, it was too heavyhanded: it
re-broke black backgrounds for every application.

Michael thought that it should live in the server, as a small VT parser
that righted the wrongs coming directly out of the application. On
further investigation, however, I realized that we'd need to push more
information up into the server (so that it could make the decision about
which VT was wrong and which was right) than should be strictly
necessary.

The host knows which colors are right and wrong, and it gets final say
in what ends up in the buffer.

Because of that, I chose to push the quirk state down through
WriteConsole to DoWriteConsole and toggle state on the
SCREEN_INFORMATION that indicates whether the colors coming out of the
application are to be distrusted. This quirk _only applies to pwsh.exe
and powershell.exe._

**NOTE**: This doesn't work for PowerShell the .NET Global tool,
because it is run as an assembly through dotnet.exe. I have no opinion
on how to fix this, or whether it is worth fixing.

## PR Checklist
* [x] Closes #6767 
* [x] CLA signed
* [x] Tests added/passed
* [x] Documentation updated
* [x] Schema updated.
* [x] I've discussed this with core contributors already

## Validation

I've configured my terminals to have an incredibly garish color scheme
to show exactly what's going to happen as a result of this. The _default
terminal background_ is purple or red, and the foreground green. I've
printed out a heap of test colors to see how black interacts with them.

One the left, Terminal Preview without this fix. On the right, Terminal
Dev _with_ this fix.

* `DEFAULT` = `39` or `49`
* `WHITE` = `37` or `47`
* `BLACK` = `30` or `40`
* `AIX WHT` = `97` or `107`
* `AIX BLK` = `90` or `100`
* `INT` = `1`

image

The only color lines that change are the ones where black as a
background or white as a foreground is selected out of the 16-color
palette explicitly. Reverse video still works fine (because black is in
the foreground!), and it's even possible to represent "black on default"
and reverse it into "default on black", despite the black in question
having been `40`.

### CODE REVIEW

**Comment by DHowett** [comment]
/cc @j4james, as I can't request a review from him right now.

With apologies.

**Comment by j4james** [comment]
Obviously I hate this, but I understand the reasons for needing it. I'd have been happy to block #6506 for the same reasons. But definitely only as a temporary solution. The mention of "defer the hard work until later -- if ever" sounds scary to me. Because with this solution we're just trading one set of bug reports for another. And it's the apps that are doing the right thing that are going to get buggy results, while the buggy apps get what they want. That just doesn't seem right.

So +1 on doing whatever we have to do to keep PowerShell happy for now. But I'd definitely want us to make this a PowerShell-only mode ASAP. I don't think it really needs to be anything fancy - just exactly what you're doing now, but tied to a flag that is only set for PowerShell. Possibly a profile option that's default true for the PowerShell profiles, so that way users can still turn it off if PowerShell ever gets fixed.

**Comment by DHowett** [comment]
So, my motivation behind saying “if ever” is less because we might keep it forever and more because I’m hoping to get PowerShell (Core) serviced with the fix. If we fail to identify any other applications that need a workaround like this, we can move it into a shim that only applies to PowerShell Inbox or simply throw up our hands and say “no, we aren’t going to make a concession for this one.” If we never have to do the shim work because all our reproducers disappear, that’s better than having to carry around a better version of the fix forever.

**Comment by DHowett** [comment]
And with regards to blocking the original PR, I’m really glad we didn’t. I wanted this improvement, and its already paying dividends in how easily you could implement overline and fix DECSCNM. We would have had merge conflicts for months while we shook it all out.

At least this way we have the architectural fix _and_ a place to document our known failings and foibles. I much prefer that over a beautiful architecture that never lands. :smile:

**Comment by j4james** [comment]
To throw another spanner in the works, I've just realised that this patch actually makes things worse with light color schemes. For example, here's the before and after of `dir ohno.txt` in PowerShell with the _One Half Light_ scheme. It may have been ugly before, but now it's invisible. You can't win. 😞

image

**Comment by DHowett** [comment]
Alright, wow, ouch. The hack pretty much has to move into host (it can’t live in server because server doesn’t know the state of the global “legacy defaults” and it can’t live in the renderer because I absolutely don’t want to break 37 for anyone but powershell).

@zadjii-msft the only real way we truly ferret out all the broken applications is to ship with the visual regression, but I have so far failed to convince @cinnamon-msft that it’s worth our reputation to do so.

**Comment by cinnamon-msft** [comment]
I know this isn't an ideal situation. Considering majority of people use PowerShell in Terminal, I'd be okay with having the hack only for PowerShell and the other broken applications will surface eventually.

**Comment by j4james** [comment]
Have you considered maybe hacking this on the Terminal side as just a simple color scheme patch? For example, if the command line is powershell.exe or pwsh.exe, then automatically patch the initial scheme so _black_ is the same color as _background_, and _white_ is the same color as _foreground_. Doesn't require any run-time overhead, and people could still override the palette with an escape sequence if they really wanted to.

**Comment by DHowett** [comment]
I'm not sure that's feasible, for a couple reasons.

* For backgrounds; we don't support individual transparency for paletted colors, so acrylic/background image wouldn't show through even if we set black to background
* It would damage black foregrounds/white backgrounds
* It wouldn't help workflows where the user launches powershell/pwsh from another shell, and might do more harm (compared to a server/host quick for powershell directly) to workflows where the user launches something _from_ pwsh

**Comment by DHowett** [comment]
image

**Comment by DHowett** [comment]
And a money shot for acrylic:

image

**Comment by DHowett** [comment]
The tests will fail to compile. Don't be daft, Dustin, fix them!

**Comment by DHowett** [comment]
I'll have you all know that _i hate this so much_. :smile:

**Comment by DHowett** [comment]
Okay, this check needs to be smarter about `INTENSITY` and whether the things it's suppressing match in intensity. :smile:

**Comment by j4james** [comment]
I've just been trying out this branch, and my initial impression with `powershell.exe` looked promising, but then I found that it didn't work with `pwsh.exe` (my version is 6.2.3). If I erased something on the command line, it redrew the line with a black background rather than the default.

I don't know if this has got anything to do with it, but when starting a conhost session in the debugger with `pwsh.exe`, I noticed that `ConsoleShimPolicy::s_CreateInstance` was actually called twice - the first time with _processName_ being `pwsh.exe`, and the second time with `dotnet.exe`. Obviously the latter process isn't detected as powershell, so the quirk isn't enabled.

I don't have time to dig more tonight, but just wanted to let you know that there may be a problem somewhere.

**Comment by DHowett** [comment]
Huh, that's actually really interesting. Thanks for testing!
There should be one shim policy per connected process, and we should be checking the process that's actually emitting the output ... but if something in process handling is busted, that could explain this behavior.

**Comment by DHowett** [comment]
So, wow, okay. When PowerShell's been installed as a dotnet global tool it's spawned via `dotnet pwsh.dll`. The connection packet doesn't include the full commandline _and_ we can't necessarily determine the identity of this dotnet.exe instance by its parentage ...

File: src/server/ConsoleShimPolicy.h [hunk 1]
```diff
@@ -25,6 +25,7 @@ class ConsoleShimPolicy
 
     bool IsCmdExe() const noexcept;
     bool IsPowershellExe() const noexcept;
+    bool ApplicationMishandlesVTColors() const noexcept;
```
Comment (miniksa) [inline src/server/ConsoleShimPolicy.h:28]: The title of this function feels presumptuous and applies intent to the client application's programming. We didn't have a firm and well-developed story to introducing VT in the first place. 

I think we should choose a more neutral naming. Simply doubling down on the quirkiness of the situation like `IsVtColorQuirkRequired()` might be better.

**Comment by DHowett** [comment]
@cinnamon-msft I need your approval -- in spirit, not on the PR itself -- of the reality that this workaround **does not work** for "dotnet global tool" powershell. We have had other issues with that version, not limited to color representation, that have historically made it a poor fit for running in Terminal. If it represents a comparatively small subset of all powershell users, and we understand that it can be updated a lot faster than the inbox Windows PowerShell which we are using as our default profile, is it acceptable to you that we ship with a potential color regression?

Impacted population is small, and remediation is easy.

**Comment by DHowett** [comment]
Just to be clear: powershell/pwsh and powershell inbox work perfectly fine; one of the installation methods pwsh ships has been historically troublesome.

**Comment by j4james** [comment]
For the record I'm "happy" with this. I just want to note that black-on-black and white-on-white are no longer invisible if your defaults aren't white-on-black, which might trigger some bug reports. But I still think it's an improvement on the current situation, and hopefully this quirk won't have to last forever.

**Comment by jantari** [comment]
Am I correct in my understanding that:

- This compatibility hack fixes the vast vast majority of PowerShell/PSReadline background color troubles
- Is mostly being introduced because the inbox Windows PowerShell 5.1 and its PSReadLine version aren't going to get updated soon if ever ( mrw: 🙄)
- The underlying issue is fixed by [PSReadLine#1626](https://github.com/PowerShell/PSReadLine/pull/1626)
- Once I update my PSReadLine manually to a version that includes PR 1626, everything will be perfect and this lingering compatibility fix, although still active for all my powershell tabs, won't re-break anything with the new PSReadLine version?
- This compatibility hack also covers me if I run `powershell.exe` from within a `cmd` tab because it taps into the commandlines of the whole child process tree of a tab and not just the initial program the tabs profile started?

**Comment by DHowett** [comment]
@jantari very close.

Since the workaround is happening in conhost, which receives a "console connection packet" for every commandline application that starts up, it's not doing any process tree inspection. But, yes, on all your other points:

1. This compatibility hack fixes the majority of PowerShell/PSReadline-related background color issues **introduced by the changes in #6506** or seen when using the "experimental terminal features" conhost option we added in Windows 1903.
   * It disables the use of two colors from the ANSI 16-color palette
2. The update for PSReadline shipped with Windows PowerShell will come out in an insider's build of Windows eventually.
3. Yes, PowerShell/PSReadline#1626 fixed this
4. The fixed version of PSRL will not introduce further issues (it moves the decision we made in conhost down into PSRL), but it will NOT bring back the two colors removed from the 16-color palette.
5. Right, or any other means of spawning something named `powershell.exe` or `pwsh.exe` :smile:

**Comment by DHowett** [comment]
(@jantari: why do you ask? I love talking about this stuff, so am happy to dig through a bunch of questions about it :))

**Comment by Johbii** [comment]
@DHowett so the issue stands that in order to fix we would need to push a fix to the included Windows PowerShell 5.1 or PSReadLine included in Windows 10?

**Comment by DHowett** [comment]
> @DHowett so the issue stands that in order to fix we would need to push a fix to the included Windows PowerShell 5.1 or PSReadLine included in Windows 10?

This is fixed in PSReadline in Insider builds of Windows. Problem is, though, that this is a bug with a very limited impact and an easy workaround... so there’s no reason to service it to earlier versions. 🤷🏻
