### PR TITLE
Fix `repositionCursorWithMouse` after the viewport starts scrolling

### LINKED ISSUE #16423: `repositionCursorWithMouse` doesn't work once the viewport starts scrolling
version 1.20.whatever. Probably in 1.19 too. 

`"experimental.repositionCursorWithMouse": true` in the json. 

enable shell integration. 

do a `dir` or two, then try to move the cursor with the mouse.

### PR DESCRIPTION
**Pull request by zadjii-msft**
Yea, I used a viewport-relative mouse position, rather than the buffer-relative position. Pretty obvious in retrospect.

Closes #16423

### CODE REVIEW

File: src/cascadia/TerminalControl/ControlCore.cpp [hunk 1]
```diff
@@ -1904,17 +1904,26 @@ namespace winrt::Microsoft::Terminal::Control::implementation
...
+                if (clampedClick.y > lastNonSpace.y)
+                {
+                    // Clicked under the prompt. Bail.
+                    return;
+                }
+                else if (clampedClick > lastNonSpace)
                 {
                     clampedClick = lastNonSpace + til::point{ 1, 0 };
-                    _terminal->GetTextBuffer().GetSize().Clamp(clampedClick);
+                    bufferSize.Clamp(clampedClick);
```
Comment (lhecker) [inline src/cascadia/TerminalControl/ControlCore.cpp:1921]: `lastNonSpace` cannot be larger than `bufferSize` (unless there's a bug in `GetLastNonSpaceCharacter`, but I think it'd be fine if we assume there isn't). As such we can simplify this code quite a bit. We just need to the `if a > b` idea into a `if a >= b + 1` one and we get:
```cpp
const auto bufferPos = _terminal->GetViewport().Origin() + terminalPosition;
if (bufferPos.y > lastNonSpace.y)
{
    // Clicked under the prompt. Bail.
    return;
}

// Limit the click to 1 past the last character on the last line.
const auto clampedClick = std::min(bufferPos, lastNonSpace + til::point{ 1, 0 });
if (clampedClick >= end)
// ...
```

However, `+ til::point` doesn't do line wrapping. This breaks the `if (bufferPos.y > lastNonSpace.y)` check at a minimum. As such it may be necessary to do
```cpp
bufferSize.IncrementInBounds(lastNonSpace, true);

const auto bufferPos = _terminal->GetViewport().Origin() + terminalPosition;
if (bufferPos.y > lastNonSpace.y)
{
    // Clicked under the prompt. Bail.
    return;
}

// Limit the click to 1 past the last character on the last line.
const auto clampedClick = std::min(bufferPos, lastNonSpace);
if (clampedClick >= end)
// ...
```

**Review by lhecker — APPROVED** [review]

**Review by DHowett — APPROVED** [review]
