### PR TITLE
Fix refresh-related crashes in Settings UI

### LINKED ISSUE #8747: Crash when deleting a profile you just added
# Steps to reproduce
1. Create a new profile - apply.  
2. Delete the profile without changing the selected profile 
  - Here, the terminal you deleted the profile in hangs, before you even have a chance to apply the changes 
  - The crash seems like its in XAML so not sure what happened 

# Expected behavior

The selected profile is deleted and another profile is selected.

# Actual behavior

Crash

### LINKED ISSUE #8748: Crash when deleting a profile you just (un)hid
# Steps to reproduce

1. go to the tab of any delete-able profile you have
2. Check/uncheck 'hide profile from dropdown'
3. Hit 'apply'
4. Hit 'delete profile'

# Expected behavior

the profile is deleted and another profile is selected

# Actual behavior

Crash

### PR DESCRIPTION
**Pull request by carlos-zamora**
Removes the visibility hack in `UpdateSettings` where we were hiding
Profile menu items instead of removing them. This hack was removed using
`ReplaceAll`. For an unknown reason, calling `Remove()` would result in
an out-of-bounds error in XAML code.

The "Discard" button would improperly refresh the Settings UI. Both of
the bugs were caused by holding a reference to a hidden menu item then
trying to set the `SelectedItem` to that menu item. 

Additionally, 9283375 adds a check for the selected item in
`SettingsNav_ItemInvoked()`. This prevents navigation to an already
selected item. This was the heuristic used by the XAML Controls Gallery.

References #6800 - Settings UI Epic

## Validation Steps Performed
(Repeated for each menu item)
1. Select the menu item
2. click "Discard changes"
3. Verify navigated to same page

Also performed repro steps for #8747 and #8748.

Closes #8747
Closes #8748

### CODE REVIEW

File: src/cascadia/TerminalSettingsEditor/MainPage.cpp [hunk 1]
```diff
@@ -64,69 +64,95 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
 
         co_await winrt::resume_foreground(Dispatcher());
 
-        // "remove" all profile-related NavViewItems
-        // LOAD-BEARING: use Visibility here, instead of menuItems.Remove().
-        //               Remove() works fine on NavViewItems with an hstring tag,
-        //               but causes an out-of-bounds error with Profile tagged items.
-        //               The cause of this error is unknown.
+        // Deduce information about the currently selected item
+        std::optional<IInspectable> selectedItemTag{ std::nullopt };
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/MainPage.cpp:68]: iinspectable is already nullable, it doesn't need to be made optional on top of that

File: src/cascadia/TerminalSettingsEditor/MainPage.cpp [hunk 2]
```diff
@@ -64,69 +64,95 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
...
                         {
-                            // hide NavViewItem pointing to "Add Profile"
-                            navViewItem.Visibility(Visibility::Collapsed);
+                            // don't add the "Add Profile" item
+                            continue;
                         }
                     }
                 }
             }
+            menuItemsSTL.push_back(item);
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/MainPage.cpp:107]: `emplace_back(std::move(item))` to conserve the ref count so you don't need to keep incrementing and decrementing it. remove the `const` on item to make it work.

File: src/cascadia/TerminalSettingsEditor/MainPage.cpp [hunk 3]
```diff
@@ -64,69 +64,95 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
...
+        // now that the menuItems are repopulated,
+        // refresh the current page using the SelectedItem data we collected before the refresh
+        if (selectedItemTag)
         {
-            if (const auto tag{ selectedItem.as<MUX::Controls::NavigationViewItem>().Tag() })
+            if (const auto tag{ selectedItemTag->try_as<hstring>() })
             {
-                if (const auto oldProfile{ tag.try_as<Editor::ProfileViewModel>() })
+                // SelectedItem is a menu item we didn't remove
+                SettingsNav().SelectedItem(menuItems.GetAt(*selectedItemIndex));
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/MainPage.cpp:121]: Seems like we should just be able to find the one with a matching tag. No need to keep the index -- what does it do for us?

Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/MainPage.cpp:121]: In fact, if the order _does_ ever change, we will navigate to one tag but select the index for a _different_ tag.

File: src/cascadia/TerminalSettingsEditor/MainPage.cpp [hunk 4]
```diff
@@ -64,69 +64,95 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
...
+            }
+            menuItems.IndexOf(selectedItem, *selectedItemIndex);
+        }
+
+        // remove all profile-related NavViewItems by populating a std::vector
+        // with the ones we want to keep.
+        // NOTE: menuItems.Remove() causes an out-of-bounds crash. Using ReplaceAll()
+        //       gets around this crash.
+        std::vector<IInspectable> menuItemsSTL;
+        for (uint32_t i = 0; i < menuItems.Size(); ++i)
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/MainPage.cpp:85]: you're not using `i` here, so simplify this into a range-based for loop.

then, make it a `const auto&` (note the &) and use emplace_back without std::move.

File: src/cascadia/TerminalSettingsEditor/MainPage.cpp [hunk 5]
```diff
@@ -64,69 +64,95 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
...
+                // SelectedItem is a menu item we didn't remove
+                SettingsNav().SelectedItem(menuItems.GetAt(*selectedItemIndex));
+                _Navigate(*tag);
+                co_return;
+            }
+            else if (const auto selectedItemProfileTag{ selectedItemTag->try_as<ProfileViewModel>() })
+            {
+                // SelectedItem was pointing to a profile
+                // Iterate over all menu items to find the one we were pointing at before
+                for (const auto item : menuItems)
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/MainPage.cpp:129]: you're not manipulating item, so use `const auto&`.

**Review by DHowett — CHANGES_REQUESTED** [review]

File: src/cascadia/TerminalSettingsEditor/MainPage.cpp (hunk 4 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/MainPage.cpp:85]: Feedback on this comment slightly contradicts the [one below](https://github.com/microsoft/terminal/pull/8773/files#r556217683). I'm assuming you want this one though.

File: src/cascadia/TerminalSettingsEditor/MainPage.cpp [hunk 6]
```diff
@@ -150,9 +147,9 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
 
         // couldn't find the selected item,
         // fallback to first menu item
-        const auto firstItem{ menuItems.GetAt(0) };
+        const auto& firstItem{ menuItems.GetAt(0) };
         SettingsNav().SelectedItem(firstItem);
-        if (const auto tag{ SettingsNav().SelectedItem().as<MUX::Controls::NavigationViewItem>().Tag() })
+        if (const auto& tag{ SettingsNav().SelectedItem().try_as<MUX::Controls::NavigationViewItem>().Tag() })
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/MainPage.cpp]: don't go too crazy with this -- some of these things generate temporaries and we don't want to capture references to those. Those should not have the & if we can help it.

Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/MainPage.cpp]: The ones you create from try_as, and the ones you create from GetAt, probably aren't safe to take references to. The ones you create from iteration over an iterator, however, are safe to take a reference to.

Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/MainPage.cpp]: I apologize - i know i asked you to flip it one way and then the other, but... some nuance :smile:

**Review by DHowett — CHANGES_REQUESTED** [review]

File: src/cascadia/TerminalSettingsEditor/MainPage.cpp (hunk 6 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/MainPage.cpp]: Ok. So just to get this straight, `try_as` and `GetAt` aren't safe to take refs of because `MenuItems` might change from underneath us (especially when looking at the selected item stuff). So it's safer to take a copy so that we can use it later. Right?

Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/MainPage.cpp]: > Ok. So just to get this straight, `try_as` and `GetAt` aren't safe to take refs of because `MenuItems` might change from underneath us (especially when looking at the selected item stuff). So it's safer to take a copy so that we can use it later. Right?

So, it's a little more complicated than that.

If this were _just plain C++_, that would be why. For a vector, `at` returns a reference to the memory location inside the vector's storage, which is durable until the vector changes.

For C++/WinRT, the story is a little different. Sorta. I still don't totally know the C++ reasons for why this works the way it does.

`GetAt()` returns a new object that was constructed to hold the internal WinRT object pointer. `try_as` does the same thing. Those objects are _projected type wrappers_, and they are constructed on return from the function. You _can't_ take a reference to them, because they are not referenceable. They don't exist.

Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/MainPage.cpp]: **HOWEVER**, I think I led you astray. I did some reading on Stack Overflow, and I finally understand it. What you had written before was completely legal, and now I understand why. You can safely revert the code that removed all the `&`s.

[Here's the skinny, on Herb Sutter's blog](https://herbsutter.com/2008/01/01/gotw-88-a-candidate-for-the-most-important-const/).

> C++ deliberately specifies that binding a temporary object to a reference to const on the stack lengthens the lifetime of the temporary to the lifetime of the reference itself, and thus avoids what would otherwise be a common dangling-reference error.

**Review by DHowett — APPROVED** [review]
love it love it

File: src/cascadia/TerminalSettingsEditor/MainPage.cpp [hunk 7]
```diff
@@ -64,69 +64,92 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
...
+                        else if (const auto& profileTag{ tag.try_as<ProfileViewModel>() })
+                        {
+                            if (profileTag->Guid() == selectedItemProfileTag->Guid())
+                            {
+                                // found the one that was selected before the refresh
+                                SettingsNav().SelectedItem(item);
+                                _Navigate(*selectedItemProfileTag);
+                                co_return;
+                            }
+                        }
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/MainPage.cpp:142]: hey how will this work when you have BASE LAYER selected?

Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/MainPage.cpp:142]: Base Layer is unique in that it has a string tag. So that's covered in the other if-statement.

File: src/cascadia/TerminalSettingsEditor/MainPage.cpp [hunk 8]
```diff
@@ -180,6 +203,13 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
     {
         if (const auto clickedItemContainer = args.InvokedItemContainer())
         {
+            if (clickedItemContainer.IsSelected())
```
Comment (zadjii-msft) [inline src/cascadia/TerminalSettingsEditor/MainPage.cpp:206]: clever

File: src/cascadia/TerminalSettingsEditor/MainPage.cpp [hunk 9]
```diff
@@ -64,69 +64,92 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
...
-        const auto firstItem{ navigationMenu.MenuItems().GetAt(0) };
-        navigationMenu.SelectedItem(firstItem);
-        if (const auto tag{ navigationMenu.SelectedItem().as<MUX::Controls::NavigationViewItem>().Tag() })
+        // couldn't find the selected item,
+        // fallback to first menu item
+        const auto& firstItem{ menuItems.GetAt(0) };
+        SettingsNav().SelectedItem(firstItem);
+        if (const auto& tag{ SettingsNav().SelectedItem().try_as<MUX::Controls::NavigationViewItem>().Tag() })
         {
             _Navigate(unbox_value<hstring>(tag));
```
Comment (zadjii-msft) [inline src/cascadia/TerminalSettingsEditor/MainPage.cpp:154]: oh I see, yea this works because the first one is always a string. gotcha.

File: src/cascadia/TerminalSettingsEditor/MainPage.cpp [hunk 10]
```diff
@@ -64,69 +64,92 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
...
+            if (const auto& navViewItem{ selectedItem.try_as<MUX::Controls::NavigationViewItem>() })
             {
-                if (const auto tag{ navViewItem.Tag() })
+                selectedItemTag = navViewItem.Tag();
+            }
+        }
+
+        // remove all profile-related NavViewItems by populating a std::vector
+        // with the ones we want to keep.
+        // NOTE: menuItems.Remove() causes an out-of-bounds crash. Using ReplaceAll()
```
Comment (zadjii-msft) [inline src/cascadia/TerminalSettingsEditor/MainPage.cpp:80]: OF COURSE IT DOES.

Is there an upstream bug for the `Remove` crash?

**Review by zadjii-msft — APPROVED** [review]

File: src/cascadia/TerminalSettingsEditor/MainPage.cpp (hunk 10 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/MainPage.cpp:80]: No. I couldn't get a repro in a custom XAML app last month. The crash doesn't happen when you removed hstring tagged items, only `Profile` tagged items. Not exactly sure how to report that. Maybe it's XAML Islands related? 🤷‍♂️

Comment (zadjii-msft) [reply src/cascadia/TerminalSettingsEditor/MainPage.cpp:80]: GAH. Okay. Well, eff it then.
