### PR TITLE
Fixed #5205: Ctrl+Alt+2 doesn't send ^[^@

### LINKED ISSUE #5205: Ctrl+Alt+Shift+2 doesn't send NUL in VT input mode
@zadjii-msft:
> Okay so <kbd>Ctrl+Alt+Space</kbd> was fixed for conhost, but it looks like it's still broken in the Terminal 😢 Now it's just generating a `^@`, a single NUL.
> 
> I think the Terminal is synthesizing the right sequence, but maybe conpty is generating the wrong input for it now, or maybe the input that's generated by conpty doesn't get re-translated back to `^[^@` correctly. I can try to keep investigating to figure out where the miscommunication is, if you need help.

@lhecker:
> @zadjii-msft Yeah I was just about to say that as well.
>
> As I wrote above the most puzzling thing for me though is if you change [this if condition (line 510)](https://github.com/microsoft/terminal/pull/4192/files#diff-3895074b0184ca0d36ef271db540a282R510) to a simple `ch != 0` - which _should_ be correct as well.
> If you attach a debugger you'll see that `TerminalInput` _definitely_ invokes `_pfnWriteEvents` with a `\x1b\x00` sequence.
> But then showkey shows a `^[^R` sequence instead. How can this happen? > I don't understand how such a benign change to the if condition can cause this. :disappointed: 

Okay I maybe saw what happened here.

1. On a en-us keyboard, '@' is <kbd>shift+2</kbd>. 
2. When conpty sees a `\x1b\x0`, it converts it to [Shift_down, Ctrl_down, Alt_down, 2_down, 2_up, Alt_up, Ctrl_up, Shift_up].
    - I did not pay a ton of attention to the keys that got synthesized here. I need to re-investigate the [2_down, 2_up]
3. When we get back to `TerminalInput::HandleKey`, we end up skipping that branch, because the `ch` was `0n50`, which is `0x32`, which is `'2'`.

I'm not sure what's exactly the right behavior here. I'd think we probably should send a different key, but I'll need to investigate more. It's possible that the `ch != 0` change would work just fine, but I want to make sure that the upstream input from conpty is _actually_ correct.
I've got a [braindead fix](https://github.com/microsoft/terminal/commit/77eee7066e5606f32359ec5ea8b291e42aa86ca9) that would fix `showkey -a`, but that doesn't really resolve the issue here for Win32 applications unfortunately, so I'm gonna file a separate issue to track this investigation.

_Originally posted by @zadjii-msft in https://github.com/microsoft/terminal/pull/4192#issuecomment-607326733_

### PR DESCRIPTION
**Pull request by lhecker**
## Summary of the Pull Request

Fixes #5205, by replacing another use of `MapVirtualKeyW` with `ToUnicodeEx`.
The latter just seems to be much more consistent at translating key combinations in general.
In this particular case though it fixes the issue, because there's no differentiation in `MapVirtualKeyW` for whether it failed to return a character (`'\0'`) or succeeded in turning `^@` into `'\0'`.
`ToUnicodeEx` on the other hand returns the success state separately from the translated character.

## PR Checklist
* [x] Closes #5205
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [x] Tests added/passed
* [ ] Requires documentation to be updated
* [x] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #5205

## Detailed Description of the Pull Request / Additional comments

This PR changes the behavior of the `Ctrl+Alt+Key` handling slightly:
⚠️ `ToUnicodeEx` returns unshifted characters. ⚠️
For instance `Ctrl+Alt+a` is now turned into `^[^a`. Due to how ASCII works this is essentially the same though because `'A' & 0b11111` and `'a' & 0b11111` are the same.

## Validation Steps Performed

* Run `showkey -a`
* Ensured `Ctrl+Alt+Space` as well as `Ctrl+Alt+Shift+2` are turned into `^[^@`
* Ensured other, random `Ctrl+Alt+Key` combination behave identical to the current master

### CODE REVIEW

**Comment by lhecker** [comment]
BTW I couldn't run tests locally, because I'm faced with the following error:
```
".\terminal\OpenConsole.sln" (Clean;Build target) (1) ->
".\terminal\src\cascadia\TerminalAzBridge\TerminalAzBridge.vcxproj" (Clean;Build target) (50) ->
  .\terminal\packages\Microsoft.Windows.CppWinRT.2.0.200316.3\build\native\Microsoft.Windows.CppWinRT.targets(164,13):
error MSB4006: There is a circular dependency in the target dependency graph involving target "ComputeGetResolvedWinMD".
[.\terminal\src\cascadia\TerminalAzBridge\TerminalAzBridge.vcxproj]
```

**Comment by zadjii-msft** [comment]
I'm not sure what exactly is causing that error you're seeing, but there are definitely some unit test breaks 😆 Sometimes just cleaning out the project it complains about will fix it. 

From CI:
```
Summary of Non-passing Tests:
    Microsoft::Console::VirtualTerminal::InputTest::TerminalInputModifierKeyTests#metadataSet4 [Failed]
    Microsoft::Console::VirtualTerminal::InputTest::TerminalInputModifierKeyTests#metadataSet5 [Failed]
    Microsoft::Console::VirtualTerminal::InputTest::TerminalInputModifierKeyTests#metadataSet6 [Failed]
    Microsoft::Console::VirtualTerminal::InputTest::TerminalInputModifierKeyTests#metadataSet8 [Failed]
    Microsoft::Console::VirtualTerminal::InputTest::TerminalInputModifierKeyTests#metadataSet10 [Failed]
    Microsoft::Console::VirtualTerminal::InputTest::DifferentModifiersTest [Failed]
    Microsoft::Console::VirtualTerminal::InputEngineTest::RoundTripTest [Skipped]

Summary: Total=2136, Passed=2129, Failed=6, Blocked=0, Not Run=0, Skipped=1

```

TBH I rarely build the entire solution anymore, usually I just build only the projects I'm interested in by right clicking on them in VS:
image

your mileage may vary, but that's what works for me. You might be able to at least get the `VirtualTerminal::InputTest`s building that way.

File: src/terminal/input/terminalInput.cpp [hunk 1]
```diff
@@ -494,21 +494,18 @@ bool TerminalInput::HandleKey(const IInputEvent* const pInEvent)
...
-        auto ch = keyEvent.GetCharData();
-        if (ch == UNICODE_NULL)
-        {
-            // For Alt+Ctrl+Key messages GetCharData() returns 0.
-            // -> Get the char from the virtual key.
-            ch = LOWORD(MapVirtualKeyW(keyEvent.GetVirtualKeyCode(), MAPVK_VK_TO_CHAR));
-        }
-        if (ch == UNICODE_SPACE)
+        auto character = _CharacterFromAltCtrlKeyEvent(keyEvent);
+        if (character)
```
Comment (zadjii-msft) [inline src/terminal/input/terminalInput.cpp:498]:
```suggestion
        if (character.has_value())
```

I _know_ that these do the same thing, but I find the second version much more readable, because I initially thought the error case was `UNICODE_NULL`

File: src/terminal/input/terminalInput.cpp [hunk 2]
```diff
@@ -576,6 +573,49 @@ bool TerminalInput::HandleKey(const IInputEvent* const pInEvent)
...
+// Method Description:
+// - Returns the keyboard's scan code for the given virtual key code.
+// Arguments:
+// - vkey: The virtual key code.
+// Return Value:
+// - The keyboard's scan code.
+WORD TerminalInput::_ScanCodeFromVirtualKey(const WORD vkey) noexcept
+{
+    return LOWORD(MapVirtualKeyW(vkey, MAPVK_VK_TO_VSC));
+}
```
Comment (zadjii-msft) [inline src/terminal/input/terminalInput.cpp:585]: Part of me thinks we should move these helpers to some shared space, since this isn't the first time this has been written, but that's probably a better follow-up codehealth task.

File: src/terminal/adapter/ut_adapter/inputTest.cpp [hunk 3]
```diff
@@ -482,8 +482,16 @@ void InputTest::TerminalInputModifierKeyTests()
...
-            if (AltPressed(uiKeystate) && ControlPressed(uiKeystate) && ch >= 0x40 && ch < 0x7F)
+            if (AltPressed(uiKeystate) && ControlPressed(uiKeystate))
             {
+                if (ch == 0)
+                {
+                    // There are a few vkeys that MapVirtualKeyW() above turns into 0,
+                    // while TerminalInput is still capable of processing them.
+                    // The important ones are tested in DifferentModifiersTest/TerminalInputNullKeyTests.
+                    continue;
+                }
```
Comment (lhecker) [inline src/terminal/adapter/ut_adapter/inputTest.cpp:493]: @zadjii-msft In order for the tests to work again I disabled tests for certain Ctrl+Alt combinations as you can see here.
We could make the tests work if we pull in the `ToUnicodeEx()` logic into this file as well. If we do that though we should probably really create a helper file that contains this function separately. 😄

On the other hand I personally kinda doubt that this if condition makes this unit test any worse, because to fix this unit test we have to basically add a identical copy of the `TerminalInput::_CharacterFromAltCtrlKeyEvent` method.
And IMHO that way we'd just test for the current state of affairs of which OS methods we use instead for the actual results that we'd like to see for each character, you know? 🤔

**Comment by lhecker** [comment]
@zadjii-msft Now the build bot is facing the same issue I had earlier:
```
packages\Microsoft.Windows.CppWinRT.2.0.200316.3\build\native\Microsoft.Windows.CppWinRT.targets(164,13): Error MSB4006: There is a circular dependency in the target dependency graph involving target "ComputeGetResolvedWinMD".
```

What do? 😱

**Comment by DHowett-MSFT** [comment]
maybe re-queueing it will help. maybe there was a VS update. :/

File: src/terminal/input/terminalInput.cpp [hunk 4]
```diff
@@ -485,6 +485,17 @@ bool TerminalInput::HandleKey(const IInputEvent* const pInEvent)
...
+    const auto senderFunc = [this](const std::wstring_view seq) noexcept
+    {
+        _SendInputSequence(seq);
+    };
+
+    // If a modifier key was pressed, then we need to try and send the modified sequence.
+    if (keyEvent.IsModifierPressed() && _searchWithModifier(keyEvent, senderFunc))
+    {
+        return true;
+    }
```
Comment (zadjii-msft) [inline src/terminal/input/terminalInput.cpp:497]: Yea moving this seems fine to me, it's not like the code that _was_ before it was having any effect on this block, so it can life here just fine.

File: src/terminal/adapter/ut_adapter/inputTest.cpp (hunk 3 above)
Comment (zadjii-msft) [reply src/terminal/adapter/ut_adapter/inputTest.cpp:493]: Yea this is fine with me

**Comment by lhecker** [comment]
@zadjii-msft I believe I made a mistake in this PR. I tested it again just now and `Ctrl+Alt+@` doesn't work as intended anymore. I'm not sure when this started to be broken...

Also there's the fact that `ToUnicodeEx` returns unshifted, lowercase characters by default, unlike the current code. I'm a bit concerned that this might break some Alt+Ctrl combinations.

**Comment by lhecker** [comment]
@zadjii-msft I guess I can't figure out anymore how I originally fixed the issue. 😐
Due to that I'll now add a special handling for `^@` using the old test for `VkKeyScanW(0)`.

One quick question regarding this PR though: Should I revert my addition of `ToUnicodeEx`?
It's benefit is that it can properly handle shift keys. For instance this PR can differentiate between:
* <kbd>Ctrl+Alt+.</kbd> which yields `^[^.` and
* <kbd>Ctrl+Alt+Shift+.</kbd> which yields `^[^:`

The current solution with `MapVirtualKeyW` only supports the unshifted character `.`.
Another benefit is that after merging this PR we can remove _all_ of [this special handling altogether](https://github.com/microsoft/terminal/blob/ea1bb2ed9359fcc6ded32ad11a8cab544b91ae0e/src/terminal/input/terminalInput.cpp#L347-L416).
Since `ToUnicodeEx` supports Shift we can now use this to easily differentiate between `Ctrl+Alt+/` and `Ctrl+Alt+?` as well. All of the `VkKeyScanW` based code can thus be removed.

But the downside to the `ToUnicodeEx` based solution is that it changes the current behavior slightly:
When you now press <kbd>Ctrl+Alt+A</kbd> it'll technically generate `^[^a` (i.e. lowercase "a").
Due to [the way Ctrl masking works](https://garbagecollected.org/2017/01/31/four-column-ascii/) I _believe_ that all currently supported Ctrl+Alt combinations should produce the same output as they did before though.

What are your thoughts about this?
I'd personally go ahead with `ToUnicodeEx` because it supports the Shift key and it allows us to clean up `_searchWithModifier` later on. But I cannot yet properly estimate what the risk potential for getting something wrong and changing existing behavior is.

**Comment by lhecker** [comment]
I kinda forgot about this PR. 😅 I‘ll try to tackle this again soon.
Due to the changes in master this will require a slightly different approach.

**Review by zadjii-msft — APPROVED** [review]
why did we never merge this before...?
