### PR TITLE
AtlasEngine: Make Direct2D/3D and Present1 configurable

### LINKED ISSUE #14254: Windows Terminal crashing when resizing panes
### Windows Terminal version

1.16.2642.0 ( and tested also on 1.15.2875.0)

### Windows build number

Windows 11 22H2 22621.674  (Windows Feature Experience Pack 1000.22634.1000.0)

### Other Software

Powershell not required, the same occur with command line

### Steps to reproduce

- Open Windows Terminal
- Maximize window to have more space for resizing (optional but makes it easier to reproduce)
- Split the terminal horizontally (2 pans is enough)
- Resize right and left pane repeatedly using keyboard shortcuts Alt + Shift + Left and Alt + Shift + Right holding down the right and left keys sometimes.
- Crash of the app and lost all pans

### Expected Behavior

The panes should resize without issues

### Actual Behavior

Windows Terminal crashes
We lost all pans at once

### LINKED ISSUE #16747: Unable to open Windows Terminal any more
### Windows Terminal version

 1.19.10302.0

### Windows build number

10.0.22631.3155

### Other Software

_No response_

### Steps to reproduce

I'm getting a similar issue as #16730 .  I don't have macType.  I just click on terminal from the start menu and nothing happens.  The dialog doesn't even flash up,  and nothing in the event log.

### Expected Behavior

Should open

### Actual Behavior

The odd thing is that if I open Powershell (x64) it will open.  But if I try to open a new tab, it crashes with this:

Faulting application name: WindowsTerminal.exe, version: 1.19.2401.30002, time stamp: 0x65b9ada4
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.22621.3155, time stamp: 0xa0b6eeba
Exception code: 0xc000027b
Fault offset: 0x0000000000873530
Faulting process id: 0x0x71E8
Faulting application start time: 0x0x1DA65063E2CFEFC
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.19.10302.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: 49a8f447-eb8c-4473-94b1-5c94f3088e53
Faulting package full name: Microsoft.WindowsTerminal_1.19.10302.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

### PR DESCRIPTION
**Pull request by lhecker**
This implements `SetForceFullRepaintRendering` and adds a new
`SetGraphicsAPI` function. The former toggles `Present1` on and off
and the latter allows users to explicitly request Direct2D/3D.

On top of these changes I did a minor cleanup of the interface,
because now that DxRenderer is gone we don't need all that anymore.

Closes #14254
Closes #16747

## Validation Steps Performed
* Toggling Direct2D on/off changes colored ligature support ✅
* Toggling Present1 on/off can be observed in a debugger ✅
* Toggling WARP on/off changes GPU metrics ✅

### CODE REVIEW

**Comment by lhecker** [comment]
This is what the Rendering page now looks like:
image

File: src/cascadia/TerminalControl/ControlCore.cpp [hunk 1]
```diff
@@ -397,8 +397,6 @@ namespace winrt::Microsoft::Terminal::Control::implementation
             // GH#11315: Always do this, even if they don't have acrylic on.
             _renderEngine->EnableTransparentBackground(_isBackgroundTransparent());
 
-            THROW_IF_FAILED(_renderEngine->Enable());
```
Comment (DHowett) [inline src/cascadia/TerminalControl/ControlCore.cpp:400]: this seemed important

File: src/cascadia/TerminalSettingsModel/GlobalAppSettings.cpp [hunk 2]
```diff
@@ -220,8 +220,21 @@ const std::vector<winrt::Microsoft::Terminal::Settings::Model::SettingsLoadWarni
 // - <none>
 // Return Value:
 // - the JsonObject representing this instance
-Json::Value GlobalAppSettings::ToJson() const
+Json::Value GlobalAppSettings::ToJson()
 {
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsModel/GlobalAppSettings.cpp:224]: a comment may help explain why

File: src/cascadia/TerminalSettingsModel/GlobalAppSettings.h [hunk 3]
```diff
@@ -52,7 +52,7 @@ namespace winrt::Microsoft::Terminal::Settings::Model::implementation
         void LayerJson(const Json::Value& json, const OriginTag origin);
         void LayerActionsFrom(const Json::Value& json, const OriginTag origin, const bool withKeybindings = true);
 
-        Json::Value ToJson() const;
+        Json::Value ToJson();
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsModel/GlobalAppSettings.h:55]: oof

File: src/cascadia/TerminalSettingsModel/MTSMSettings.h [hunk 4]
```diff
@@ -24,6 +24,7 @@ Author(s):
     X(hstring, WordDelimiters, "wordDelimiters", DEFAULT_WORD_DELIMITERS)                                                                                                                             \
     X(bool, CopyOnSelect, "copyOnSelect", false)                                                                                                                                                      \
     X(bool, FocusFollowMouse, "focusFollowMouse", false)                                                                                                                                              \
+    X(winrt::Microsoft::Terminal::Control::GraphicsAPI, GraphicsAPI, "experimental.rendering.graphicsAPI")                                                                                            \
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsModel/MTSMSettings.h:27]: we may also remove `experimental.` from these, if you want - if we're gonna keep them for a while...

File: src/cppwinrt.build.pre.props [hunk 5]
```diff
@@ -9,7 +9,6 @@
   <Import Project="..\common.openconsole.props" Condition="'$(OpenConsoleDir)'==''" />
 
   <PropertyGroup Label="Globals">
-    <CppWinRTHeapEnforcement>AnyValueHereWillDisableTheOptOut</CppWinRTHeapEnforcement>
```
Comment (DHowett) [inline src/cppwinrt.build.pre.props:12]: whooooooooooaaa what

File: src/renderer/atlas/AtlasEngine.r.cpp [hunk 6]
```diff
@@ -252,37 +258,45 @@ void AtlasEngine::_recreateBackend()
...
-        std::ignore = device->CheckFeatureSupport(D3D11_FEATURE_D3D10_X_HARDWARE_OPTIONS, &options, sizeof(options));
-        d2dMode |= !options.ComputeShaders_Plus_RawAndStructuredBuffers_Via_Shader_4_x;
+        if (featureLevel < D3D_FEATURE_LEVEL_10_0)
+        {
+            graphicsAPI = GraphicsAPI::Direct2D;
+        }
+        else if (featureLevel < D3D_FEATURE_LEVEL_11_0)
+        {
+            D3D11_FEATURE_DATA_D3D10_X_HARDWARE_OPTIONS options{};
+            // I'm assuming if `CheckFeatureSupport` fails, it'll leave `options` untouched which will result in `d2dMode |= true`.
```
Comment (DHowett) [inline src/renderer/atlas/AtlasEngine.r.cpp:270]: comment out of date a bit

File: src/renderer/atlas/AtlasEngine.r.cpp [hunk 7]
```diff
@@ -458,44 +472,36 @@ void AtlasEngine::_present()
...
+            scrollOffset = { 0, offsetInPx };
+
+            params.pScrollRect = &scrollRect;
+            params.pScrollOffset = &scrollOffset;
         }
     }
-    else
+
+    auto hr = _p.swapChain.swapChain->Present1(1, 0, &params);
+    if (Feature_AtlasEnginePresentFallback::IsEnabled() && FAILED(hr) && params.DirtyRectsCount != 0)
```
Comment (DHowett) [inline src/renderer/atlas/AtlasEngine.r.cpp:500]: FWIW, Velocity checks are (by Windows style) usually in their own conditionals, even if it makes the code more annoying to read. However, eh.

File: src/renderer/atlas/AtlasEngine.r.cpp [hunk 8]
```diff
@@ -458,44 +472,36 @@ void AtlasEngine::_present()
...
+            scrollRect = { 0, top, width, bottom };
+            scrollOffset = { 0, offsetInPx };
+
+            params.pScrollRect = &scrollRect;
+            params.pScrollOffset = &scrollOffset;
         }
     }
-    else
+
+    auto hr = _p.swapChain.swapChain->Present1(1, 0, &params);
```
Comment (DHowett) [inline src/renderer/atlas/AtlasEngine.r.cpp:499]: so wait, how does this disable present1?

**Review by DHowett — APPROVED** [review]

File: src/cascadia/TerminalControl/ControlCore.cpp (hunk 1 above)
Comment (lhecker) [reply src/cascadia/TerminalControl/ControlCore.cpp:400]: It wasn't implemented by AtlasEngine! It initializes itself lazily.

File: src/cppwinrt.build.pre.props (hunk 5 above)
Comment (lhecker) [reply src/cppwinrt.build.pre.props:12]: Oh I wanted to commit this in a separate PR but forgot to split it off first.

I believe we added this to work around a bug in the XAML compiler (no surprises there I'm sure) because it used `std::shared_ptr` instead of `winrt::com_ptr` on a WinRT object. This bug seems to have been fixed a while ago so there doesn't seem to be any reason for us to still opt out of these safety checks.

Comment (DHowett) [reply src/cppwinrt.build.pre.props:12]: YESSS

File: src/renderer/atlas/AtlasEngine.r.cpp (hunk 8 above)
Comment (lhecker) [reply src/renderer/atlas/AtlasEngine.r.cpp:499]: By leaving `params.DirtyRectsCount` at 0. That way the `Present1` call is identical to a `Present` call. In fact calling `Present` nowadays simply calls `Present1` with an empty `DXGI_PRESENT_PARAMETERS`.

File: doc/cascadia/profiles.schema.json [hunk 9]
```diff
@@ -2332,12 +2332,20 @@
           },
           "type": "array"
         },
-        "experimental.rendering.forceFullRepaint": {
-          "description": "When set to true, we will redraw the entire screen each frame. When set to false, we will render only the updates to the screen between frames.",
+        "rendering.graphicsAPI": {
+          "description": "Direct3D 11 provides a more performant and feature-rich experience, whereas Direct2D is more stable. The default option "Automatic" will pick the API that best fits your graphics hardware. If you experience significant issues, consider using Direct2D.",
```
Comment (DHowett) [inline doc/cascadia/profiles.schema.json:2336]: oop this is broken json!

```suggestion
          "description": "Direct3D 11 provides a more performant and feature-rich experience, whereas Direct2D is more stable. The default option \"Automatic\" will pick the API that best fits your graphics hardware. If you experience significant issues, consider using Direct2D.",
```

File: src/cascadia/TerminalSettingsEditor/Resources/de-DE/Resources.resw [hunk 10]
```diff
@@ -311,13 +311,13 @@
     <value>Die Terminalanwendung, die gestartet wird, wenn eine Befehlszeilenanwendung ohne vorhandene Sitzung gestartet wird, beispielsweise vom Startmenü oder über das Dialogfeld "Ausführen".</value>
     <comment>A description to clarify that the dropdown choice for default terminal will tell the operating system which Terminal application (Windows Terminal, the preview build, the legacy inbox window, or a 3rd party one) to use when starting a command line tool like CMD or Powershell that does not already have a window.</comment>
   </data>
-  <data name="Globals_ForceFullRepaint.Header" xml:space="preserve">
+  <data name="Globals_DisablePartialInvalidation.Header" xml:space="preserve">
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/Resources/de-DE/Resources.resw:314]: unfortunately, this is well-meaning but will not do much. localization will see Globals_DisablePartialInvalidation as a completely new key, and relocalize it. it'll overwrite these either way :)

Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/Resources/de-DE/Resources.resw:314]: you could reduce the loc burden by keeping the Uid the same (alas)

File: src/cascadia/TerminalSettingsEditor/Resources/qps-plocm/Resources.resw [hunk 11]
```diff
@@ -311,13 +311,13 @@
     <value>Ťђě ţэřмīηãĺ ǻφφℓï¢ǻтΐбň ŧђáт łáůйčĥēś ẅĥэп ā сöмmǻńđ-ľіŉэ ăρρĺįċāτΐôⁿ ϊš яųñ шíţћöυţ ªņ ĕхϊŝŧĭñğ şěŝѕïŏπ, ŀĩĸė ƒѓом ţћĕ Ŝτáґт Μęπü бг Яųņ ďīäℓöğ. !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !!! !</value>
     <comment>A description to clarify that the dropdown choice for default terminal will tell the operating system which Terminal application (Windows Terminal, the preview build, the legacy inbox window, or a 3rd party one) to use when starting a command line tool like CMD or Powershell that does not already have a window.</comment>
   </data>
-  <data name="Globals_ForceFullRepaint.Header" xml:space="preserve">
+  <data name="Globals_DisablePartialInvalidation.Header" xml:space="preserve">
     <value>Ŗёδѓªŵ еñţιŗę šĉřέëŋ шн℮й đĩşρℓâў υρďάţëš !!! !!! !!! !!!</value>
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/Resources/qps-plocm/Resources.resw:315]: funny enough, your ploc tool will actually change the content of these strings! :grin:

File: src/cascadia/TerminalSettingsEditor/Resources/de-DE/Resources.resw (hunk 10 above)
Comment (lhecker) [reply src/cascadia/TerminalSettingsEditor/Resources/de-DE/Resources.resw:314]: > you could reduce the loc burden by keeping the Uid the same (alas)

Since I rewrote the text I felt like this will be fine. After all, we'll be getting a new translation anyway.

File: src/cascadia/TerminalSettingsEditor/Resources/qps-plocm/Resources.resw (hunk 11 above)
Comment (lhecker) [reply src/cascadia/TerminalSettingsEditor/Resources/qps-plocm/Resources.resw:315]: Do you think I should revert these? The benefit of my change is that the compiler warnings go away (resource mismatch detected).

Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/Resources/qps-plocm/Resources.resw:315]: This is totally fine, just run your qps script! :D

File: src/cascadia/TerminalSettingsEditor/Resources/de-DE/Resources.resw (hunk 10 above)
Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/Resources/de-DE/Resources.resw:314]: fine with me!

File: src/cascadia/TerminalSettingsEditor/Resources/qps-plocm/Resources.resw (hunk 11 above)
Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/Resources/qps-plocm/Resources.resw:315]: actually the ci will do that for you, ignore me

**Comment by zadjii-msft** [comment]
image

File: src/cascadia/TerminalSettingsModel/MTSMSettings.h [hunk 12]
```diff
@@ -24,8 +24,9 @@ Author(s):
     X(hstring, WordDelimiters, "wordDelimiters", DEFAULT_WORD_DELIMITERS)                                                                                                                             \
     X(bool, CopyOnSelect, "copyOnSelect", false)                                                                                                                                                      \
     X(bool, FocusFollowMouse, "focusFollowMouse", false)                                                                                                                                              \
-    X(bool, ForceFullRepaintRendering, "experimental.rendering.forceFullRepaint", false)                                                                                                              \
-    X(bool, SoftwareRendering, "experimental.rendering.software", false)                                                                                                                              \
```
Comment (zadjii-msft) [inline src/cascadia/TerminalSettingsModel/MTSMSettings.h:28]: i think there are some folks that were using these in the past. Should we be migrating them to the roughly equivalent new settings?

File: src/renderer/atlas/AtlasEngine.api.cpp [hunk 13]
```diff
@@ -316,33 +316,18 @@ CATCH_RETURN()
...
-    return S_OK;
-}
+#pragma region getter
 
 [[nodiscard]] std::wstring_view AtlasEngine::GetPixelShaderPath() noexcept
 {
     return _api.s->misc->customPixelShaderPath;
 }
 
-[[nodiscard]] std::wstring_view AtlasEngine::GetPixelShaderImagePath() noexcept
```
Comment (zadjii-msft) [inline src/renderer/atlas/AtlasEngine.api.cpp:331]: Did this just entirely disappear?

Comment (zadjii-msft) [reply src/renderer/atlas/AtlasEngine.api.cpp:331]: oh I see, it did. But no one was using it. gotcha.

**Review by zadjii-msft — COMMENTED** [review]
just commenting cause automerge is set up but I'm pretty much a ✅

I don't think I _really_ care about migrating the old settings if you think it's fine.

File: src/cascadia/TerminalSettingsModel/MTSMSettings.h [hunk 14]
```diff
@@ -24,8 +24,9 @@ Author(s):
...
     X(bool, FocusFollowMouse, "focusFollowMouse", false)                                                                                                                                              \
-    X(bool, ForceFullRepaintRendering, "experimental.rendering.forceFullRepaint", false)                                                                                                              \
-    X(bool, SoftwareRendering, "experimental.rendering.software", false)                                                                                                                              \
+    X(winrt::Microsoft::Terminal::Control::GraphicsAPI, GraphicsAPI, "rendering.graphicsAPI")                                                                                                         \
+    X(bool, DisablePartialInvalidation, "rendering.disablePartialInvalidation", false)                                                                                                                \
```
[the remark this answers is not in the document]
Comment (lhecker) [reply src/cascadia/TerminalSettingsModel/MTSMSettings.h:28]: "Partial invalidation" is a more common technical term for `Present1` and so I felt it's more fitting. Another one is "dirty rectangles", i.e. `disableDirtyRectangles` but I wasn't sure whether that's better.

File: src/cascadia/TerminalSettingsModel/MTSMSettings.h (hunk 12 above)
Comment (lhecker) [reply src/cascadia/TerminalSettingsModel/MTSMSettings.h:28]: People who have been using `ForceFullRepaintRendering` likely have been doing something wrong or accidentally clicked it. `SoftwareRendering` did have its uses, but I believe that everyone who used it should try the new AtlasEngine again or migrate to using Direct2D. The exact choice here depends on their exact issues.

File: src/renderer/atlas/AtlasEngine.api.cpp (hunk 13 above)
Comment (lhecker) [reply src/renderer/atlas/AtlasEngine.api.cpp:331]: Yup there's another one, related to DPI, which was used but only in a single place so I just inlined it there.

**Review by zadjii-msft — APPROVED** [review]
mmk yea I'm cool with that.
