### PR TITLE
Use the tab's active title for `Export Text`

### LINKED ISSUE #13909: If you rename the tab and then click on Export Text, the filename is the previous title of the tab
### Windows Terminal version

1.14.2281.0

### Windows build number

10.0.19044.0

### Other Software

_No response_

### Steps to reproduce

Title of a tab is _Administrator: PowerShell_
- rename it to _asd_
- click on Export Text
- (default) filename is _Administrator: PowerShell.txt_

### Expected Behavior

The (default) filename exported is the tab name (so, in this example _asd.txt_)

### Actual Behavior

The filename is not aligned to the tab title

### PR DESCRIPTION
**Pull request by serd2011**
Takes title from the tab instead of the TermControl

Closes #13909

### CODE REVIEW

File: src/cascadia/TerminalApp/TabManagement.cpp [hunk 1]
```diff
@@ -420,7 +420,7 @@ namespace winrt::TerminalApp::implementation
                     // GH#11356 - we can't use the UWP apis for writing the file,
                     // because they don't work elevated (shocker) So just use the
                     // shell32 file picker manually.
-                    path = co_await SaveFilePicker(*_hostingHwnd, [control](auto&& dialog) {
+                    path = co_await SaveFilePicker(*_hostingHwnd, [&tab](auto&& dialog) {
```
Comment (DHowett) [inline src/cascadia/TerminalApp/TabManagement.cpp:423]: We may actually want to capture `tab` by copy, if we can. It will increment a reference to the underlying smart pointer.

Capturing a reference with `&` during a coroutine handoff can in some cases result in the function blowing up later when it refers to the old coroutine's stack location. It can be messy.

**Review by DHowett — CHANGES_REQUESTED** [review]
(noted)

**Comment by DHowett** [comment]
As always, thanks for tackling these things! :)

File: src/cascadia/TerminalApp/TabManagement.cpp (hunk 1 above)
Comment (serd2011) [reply src/cascadia/TerminalApp/TabManagement.cpp:423]: Copy constructor for `TerminalTab` is implicitly deleted cuz deep down `winrt::impl::root_implements` has `std::atomic` in it which is not CopyConstructible.

Comment (DHowett) [reply src/cascadia/TerminalApp/TabManagement.cpp:423]: *Oh*, I didn't realize it was a type from the `implementation` namespace. Sorry!

Comment (serd2011) [reply src/cascadia/TerminalApp/TabManagement.cpp:423]: Well, since all we need from tab is it's title we can get it outside of coroutine and just pass `wstring` by value.
```
std::wstring filename{ tab.Title() };
filename = til::clean_filename(filename);
path = co_await SaveFilePicker(*_hostingHwnd, [filename](auto&& dialog) {
```
Will this be fine?

Comment (DHowett) [reply src/cascadia/TerminalApp/TabManagement.cpp:423]: Ah, I love it! You can move the filename into the lambda as well!

File: src/cascadia/TerminalApp/TabManagement.cpp [hunk 2]
```diff
@@ -420,7 +420,9 @@ namespace winrt::TerminalApp::implementation
                     // GH#11356 - we can't use the UWP apis for writing the file,
                     // because they don't work elevated (shocker) So just use the
                     // shell32 file picker manually.
-                    path = co_await SaveFilePicker(*_hostingHwnd, [control](auto&& dialog) {
+                    std::wstring filename{ tab.Title() };
+                    filename = til::clean_filename(filename);
+                    path = co_await SaveFilePicker(*_hostingHwnd, [filename](auto&& dialog) {
```
Comment (DHowett) [inline src/cascadia/TerminalApp/TabManagement.cpp:425]:
```suggestion
                    path = co_await SaveFilePicker(*_hostingHwnd, [filename = std::move(filename)](auto&& dialog) {
```

This should compile as of C++14 and will remove an extra/unnecessary copy. However, it also doesn't matter since this is a very rarely-exercised codepath in a user interactive scenario.

**Review by DHowett — APPROVED** [review]
Thanks so much for doing this! I appreciate your response to our feedback, even (or especially!) when it is wrong. 😁

**Review by zadjii-msft — APPROVED** [review]
