### PR TITLE
When we delete a profile, focus the delete button automatically

### LINKED ISSUE #11971: [Settings>Color schemes] : Keyboard focus jumps to first tab, when user activates 'Yes, delete color scheme' button.
### Windows Terminal version

1.12.3472.0

### Windows build number

22509.1011

### Other Software

**Test Environment: **
OS: Windows 11 Version Dev (OS Build 22509.1011)
App: Windows Terminal Preview

### Steps to reproduce

**Repro Steps: **

1.Open Windows Terminal.
2.Open Settings page using 'Ctr+,'
3.Navigate to 'Color schemes' list-item present in left pane via tab ley & press enter.
4.Naviagte to 'Delete color scheme' button via tab key & press enter.
5.A pop-up will gets open.
6.Navigate to 'Yes, delete color scheme' button via tab key & press enter.
7.Observe the issue.

**User Experience: **
Users who rely on keyboard will get impacted here & will have to navigate again from top of the page un-necessarily, if Keyboard focus jumps to first tab on activating 'Yes, delete color scheme' button.

Guideline reference
https://www.w3.org/TR/WCAG21/#focus-order

Attachment : 
[Keyboard focus jumps to first tab, when user activates 'Yes, delete color scheme' button..zip](https://github.com/microsoft/terminal/files/7728455/Keyboard.focus.jumps.to.first.tab.when.user.activates.Yes.delete.color.scheme.button.zip)

### Expected Behavior

Focus should land on next interactive control i.e (Discard changes button), on activating 'Yes, delete color scheme' button.

### Actual Behavior

Keyboard focus jumps to first tab, when user activates 'Yes, delete color scheme' button.

**Note :** 
1.Same issue repro on 'Deleting' profiles also.

### PR DESCRIPTION
**Pull request by zadjii-msft**
This sure is bodgy, but it makes sense. Right now, when we delete a profile, we load in a totally new content for the new profile's settings. That one resets the scroll view and the focus, and now the "delete" button is obviously not focused.

Instead, this PR will manually re-focus the delete button of a profile page when the page is navigated to _because we deleted another profile_.

* [x] This will take care of #11971
* [x] I work here
* [x] tested manually

### CODE REVIEW

File: src/cascadia/TerminalSettingsEditor/Profiles_Base.cpp [hunk 1]
```diff
@@ -37,6 +37,25 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
...
+            // Any earlier than the last layout update and we may not know the terminal's starting size.
+
+            // Only let this succeed once.
+            _layoutUpdatedRevoker.revoke();
+
+            if (state.FocusDeleteButton())
+            {
+                DeleteButton().Focus(FocusState::Programmatic);
+                state.FocusDeleteButton(false);
+                ProfilesBase_ScrollView().ChangeView(nullptr, ProfilesBase_ScrollView().ScrollableHeight(), nullptr);
```
Comment (lhecker) [inline src/cascadia/TerminalSettingsEditor/Profiles_Base.cpp:56]: Instead of passing a boolean I'd pass the `VerticalOffset` of the ScrollView and restore the scroll offset accurately.

Alternatively, why don't we just set `BringIntoViewOnFocusChange="true"`? Does this not work?

Comment (zadjii-msft) [reply src/cascadia/TerminalSettingsEditor/Profiles_Base.cpp:56]: > Instead of passing a boolean I'd pass the `VerticalOffset` of the ScrollView and restore the scroll offset accurately.

Because the bug is specifically about making sure to focus the delete button, so KB users don't have to tab through all the settings



> Alternatively, why don't we just set `BringIntoViewOnFocusChange="true"`? Does this not work?

I did not know about that, lemme try that one

Comment (zadjii-msft) [reply src/cascadia/TerminalSettingsEditor/Profiles_Base.cpp:56]: Just double checked - that didn't work in this case 🤷

**Review by lhecker — APPROVED** [review]

**Review by miniksa — APPROVED** [review]

File: src/cascadia/TerminalSettingsEditor/Profiles_Base.cpp [hunk 2]
```diff
@@ -37,6 +37,25 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
         {
             StartingDirectoryUseParentCheckbox().IsChecked(true);
         }
+
+        // Initialize the terminal only once the swapchainpanel is loaded - that
+        //      way, we'll be able to query the real pixel size it got on layout
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/Profiles_Base.cpp:42]: this comment seems spurious

Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/Profiles_Base.cpp:42]:
```suggestion
```

**Review by DHowett — APPROVED** [review]

**Comment by DHowett** [comment]
Admin merging once the format check passes (previous commit passed build test)
