### PR TITLE
Fix RTL regression (fixes #4779)

### LINKED ISSUE #4779: RTL is worse after #4747
Before: 
image

After:
image

See utf82.txt within https://github.com/microsoft/terminal/issues/4375.

This is probably just not accounting for RTL stuff when dividing glyphs for scaling.
Also, I'm not sure that any of the RTL was correct before 4747, but it was at least displaying something. Now it's blank spaces.

We don't really state we support RTL at all yet (#538)...

### PR DESCRIPTION
**Pull request by schorrm**
## Summary of the Pull Request
This fixes the RTL regression caused in #4747. We create the rectangle taking the direction (through the BiDi Level) into account, and then the rendering works again. The GlyphRun shaping could still probably use some work to be a polished thingy, and there are still issues with RTL getting chopped up a lot when there's font fallback going on, but this fixes the regression, and it's now functional again.

 
## References
#4779 #4747 

## PR Checklist
* [x] Closes #4779
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Requires documentation to be updated
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Detailed Description of the Pull Request / Additional comments
The baseline is actually direction dependent. So when it was being initialized, the unconditional baseline as left broke it, setting the box off to right of the text. We just check if the `GlyphRun->bidiLevel` is set, and if so, we adjust it so that the baseline lines up with the right, not with the left.

## Validation Steps Performed
image

### CODE REVIEW

File: src/renderer/dx/CustomTextRenderer.cpp [hunk 1]
```diff
@@ -404,8 +409,7 @@ using namespace Microsoft::Console::Render;
                 }
                 break;
 
-                case DWRITE_GLYPH_IMAGE_FORMATS_SVG:
-                {
+                case DWRITE_GLYPH_IMAGE_FORMATS_SVG: {
```
Comment (zadjii-msft) [inline src/renderer/dx/CustomTextRenderer.cpp:412]:
```suggestion
                case DWRITE_GLYPH_IMAGE_FORMATS_SVG: 
                {
```

File: src/renderer/dx/CustomTextRenderer.cpp [hunk 2]
```diff
@@ -394,8 +400,7 @@ using namespace Microsoft::Console::Render;
                 case DWRITE_GLYPH_IMAGE_FORMATS_PNG:
                 case DWRITE_GLYPH_IMAGE_FORMATS_JPEG:
                 case DWRITE_GLYPH_IMAGE_FORMATS_TIFF:
-                case DWRITE_GLYPH_IMAGE_FORMATS_PREMULTIPLIED_B8G8R8A8:
-                {
+                case DWRITE_GLYPH_IMAGE_FORMATS_PREMULTIPLIED_B8G8R8A8: {
```
Comment (zadjii-msft) [inline src/renderer/dx/CustomTextRenderer.cpp:403]: These braces are breaking the formatting check:

```suggestion
                case DWRITE_GLYPH_IMAGE_FORMATS_PREMULTIPLIED_B8G8R8A8: 
                {
```

**Comment by zadjii-msft** [comment]
@msftbot make sure @miniksa signs off on this

File: src/renderer/dx/CustomTextRenderer.cpp [hunk 3]
```diff
@@ -404,7 +410,7 @@ using namespace Microsoft::Console::Render;
                 }
                 break;
 
-                case DWRITE_GLYPH_IMAGE_FORMATS_SVG:
+                case DWRITE_GLYPH_IMAGE_FORMATS_SVG:
```
Comment (zadjii-msft) [inline src/renderer/dx/CustomTextRenderer.cpp:413]:
```suggestion
                case DWRITE_GLYPH_IMAGE_FORMATS_SVG:
```

File: src/renderer/dx/CustomTextRenderer.cpp [hunk 4]
```diff
@@ -394,7 +400,7 @@ using namespace Microsoft::Console::Render;
                 case DWRITE_GLYPH_IMAGE_FORMATS_PNG:
                 case DWRITE_GLYPH_IMAGE_FORMATS_JPEG:
                 case DWRITE_GLYPH_IMAGE_FORMATS_TIFF:
-                case DWRITE_GLYPH_IMAGE_FORMATS_PREMULTIPLIED_B8G8R8A8:
+                case DWRITE_GLYPH_IMAGE_FORMATS_PREMULTIPLIED_B8G8R8A8:
```
Comment (zadjii-msft) [inline src/renderer/dx/CustomTextRenderer.cpp:403]:
```suggestion
                case DWRITE_GLYPH_IMAGE_FORMATS_PREMULTIPLIED_B8G8R8A8:
```

File: src/renderer/dx/CustomTextRenderer.cpp (hunk 2 above)
Comment (schorrm) [reply src/renderer/dx/CustomTextRenderer.cpp]: Sorry about those, I don't why running Clang-Format made things against your formatting rules

**Comment by DHowett-MSFT** [comment]
@msftbot merge this in 3 minutes

**Comment by DHowett-MSFT** [comment]
Thank you, @schorrm!

**Comment by DHowett** [comment]
:tada: Once again, thanks for the contribution!

This pull request was included in a set of conhost changes that was just
released with [Windows Insider Build 20161](https://blogs.windows.com/windowsexperience/2020/07/01/announcing-windows-10-insider-preview-build-20161/).
