### PR TITLE
Fix overflow in Viewport::FromDimensions

### LINKED ISSUE #5271: Crash in ScrollConsoleScreenBuffer when destination coordinates overflow
# Environment

Windows build number: Version 10.0.18362.657

# Steps to reproduce

Compile and run the following C++ code in a conhost cmd shell:
```cpp
#include <windows.h>

void main() {
    SMALL_RECT rect = {0, 0, 40, 0};
    COORD dest = {32767, 0};
    CHAR_INFO fill = {L'X', 0x07};
    HANDLE output = GetStdHandle(STD_OUTPUT_HANDLE);
    ScrollConsoleScreenBufferW(output, &rect, NULL, dest, &fill);
}
```

# Expected behavior

The first 40 characters of the first line should fill with X's.

# Actual behavior

The console crashes. 

When the `ScrollRegion` function is copying the area that is being scrolled, the `_CopyRectangle` function makes use of the `Viewport::WalkInBoundsCircular` method, and that fails when the target position goes out of bounds. See here:

https://github.com/microsoft/terminal/blob/5de9fa9cf375e9b5bdc582d8d166604eeb519844/src/types/viewport.cpp#L411

### PR DESCRIPTION
**Pull request by lhecker**
This removes one source of potential integer overflows from the Viewport class.
Other parts were left untouched, as this entire class of overflow issues gets
 fixed all at once, as soon as we replace COORD with til::coord (etc.).

## PR Checklist
* [x] Closes #5271
* [x] I work here
* [x] Tests added/passed

## Validation Steps Performed
* Call `ScrollConsoleScreenBufferW` with out of bounds coordinates
* Doesn't crash ✅

### CODE REVIEW

**Review by miniksa — APPROVED** [review]
Man this `Viewport` class needs to go, doesn't it?

**Comment by lhecker** [comment]
> Man this `Viewport` class needs to go, doesn't it?

This and `SMALL_RECT`. I hope we can get my til::coord/size/rect PR merged for the next WT version, even if it's a grand total of around 9000 LOC diff. It removes like 99% of the `SMALL_RECT` use and practically 100% of all int -> short narrowing bugs like this one.

File: src/renderer/base/renderer.cpp [hunk 1]
```diff
@@ -677,8 +677,7 @@ void Renderer::_PaintBufferOutput(_In_ IRenderEngine* const pEngine)
 
     for (const auto& dirtyRect : dirtyAreas)
     {
-        // Shortcut: don't bother redrawing if the width is 0.
-        if (dirtyRect.left == dirtyRect.right)
+        if (!dirtyRect)
```
Comment (lhecker) [inline src/renderer/base/renderer.cpp:680]: BTW This is a bug. Some engines return dirty rects where `top == bottom`, and I don't think any engine returns `left == right` actually. This causes an invalid `Viewport` to be created a few lines below. In either case though, this now checks both dimensions.

Comment (miniksa) [reply src/renderer/base/renderer.cpp:680]: wuh oh. good catch then.

**Review by DHowett — APPROVED** [review]

**Comment by DHowett** [comment]
@msftbot merge this in 1 minute
