### PR TITLE
Unify UTF-8 handling using til::u8u16 & revise WriteConsoleAImpl

### LINKED ISSUE #3378: Reconcile UTF-8 behavior in `utf8ToWideCharParser.cpp`
Outcomes from #3320... (this is all related to `utf8ToWideCharParser.cpp`)

1. When we encounter obviously invalid UTF-8 (wrong number of continuation bytes for a lead, lead without continuations, etc.), we straight up discard them from the stream in `_InvolvedParse`.
- We need to consider replacing them with U+FFFD or having the option to do so.
2. When we get not-obviously invalid UTF-8 (non-minimal forms like 0xC0 0x80 for null), we didn't detect and remove those.
- We now (as of #3320) replace them with U+FFFD, though that's inconsistent with eating them above. This was chosen as a quick fix to be easy to port into the Windows 20H1 cycle during our bug fixing phase.
- We should reconcile this difference with part 1 above (being able to toggle both of them on or off)
3. We seem to need to walk though this entire sequence multiple to many times inside our code and then again inside the kernel as the `MultiByteToWideChar` call eventually thunks to `RtlUTF8ToUnicodeN`.
- The reason we have to walk through it ourselves is to attempt to preserve partial sequences that just happen to fall across a call boundary. If the client application emits one UTF-8 character at a time, we still want to aggregate them and turn it into the correct result if they properly gave us "3-sequence-lead, continuation, continuation" in 3 separate calls. `MultiByteToWideChar` will not do this. It will either error (MB_ERR_INVALID_CHARS) or replace (U+FFFD).
- The call to `RtlUTF8ToUnicodeN` is a kernel syscall on a hot path in our codebase that is quite probably slowing us down. 

Given that we're already doing almost everything required to understand the UTF-8 sequence such that we can store partials across calls, perhaps we just add the final two steps of:
1. Detecting non-minimal forms of UTF-8 as invalid
2. Just doing the conversion to UTF-8 ourselves in user mode as it's just an algorithmic translation and we're already most of the way there bit twiddling to identify sequence length and continuations

This issue represents investigating:
1. Is there a serious performance detriment to the kernel syscall for UTF-8 conversion that will start biting us especially hard as more and more things need UTF-8 <--> UTF-16?
2. How hard is it for us to detect the non-minimal forms?
3. Can we just finish the algorithm on our side in user mode relatively simply?
4. Can we decide on a replacement strategy and make it consistent between clearly invalid sequences and non-minimal forms?

### LINKED ISSUE #4086: Certain invalid UTF-8 sequences can cause the output to fail
# Environment

Windows build number: Version 10.0.18362.418
Windows Terminal version (if applicable): 0.7.3451.0

# Steps to reproduce

1. Open a bash shell.
2. Execute the command `printf "\xA3"`

# Expected behavior

I'd expect to see something like the U+FFFD error character, or worst case nothing at all.

# Actual behavior

The output is aborted with an error:

    -bash: printf: write error: Input/output error

This looks similar to issue #3320, but PR #3380 doesn't fix it, and a recent build from master still produces the problem.

I did a bit of experimenting, and if you replace the `MB_ERR_INVALID_CHARS` with 0 in the [`_ParseFullRange`](https://github.com/microsoft/terminal/blob/126d489af97fdafbb3194c0cd32f9f99b031f376/src/host/utf8ToWideCharParser.cpp#L296) method, that seems to help, although I don't know whether that's the right solution.

I know there was a follow up task created which may end up fixing this  (#3378), but I thought it best to have the issue filed as an actual bug. If you don't think that's necessary, though, you can always close this as a dup.

### PR DESCRIPTION
**Pull request by german-one**
## Summary of the Pull Request

Replace  `utf8Parser` with `til::u8u16` in order to have the same conversion algorithms used in terminal and conhost.

 
## References

This PR is a follow up of #4093 

## PR Checklist
* [x] Closes #4086 , Closes #3378
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [x] Tests added/passed
* [ ] Requires documentation to be updated
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Detailed Description of the Pull Request / Additional comments

This PR addresses item 2 in this list:
1. ✉ Implement `til::u8u16` and `til::u16u8` (done in PR #4093)
   
   
2. ✔ **Unify UTF-8 handling using `til::u8u16` (this PR)**
    2.1. ✔ **Update VtInputThread::_HandleRunInput()**
    2.2. ✔ **Update ApiRoutines::WriteConsoleAImpl()**
    2.3. ❌ (optional / ask the core team) Remove Utf8ToWideCharParser from the code base to avoid further use

3. ❌ Enable BOM discarding (follow up)
    3.1. ❌ extend `til::u8u16` and `til::u16u8` with a 3rd parameter to enable discarding the BOM
    3.2. ❌ Make use of the 3rd parameter to discard the BOM in all current function callers, or (optional / ask the core team) make it the default for  `til::u8u16` and `til::u16u8` 

4. ❌ Find UTF-16 to UTF-8 conversions and examine if they can be unified, too (follow up)

@miniksa @DHowett-MSFT 
- Please check if this PR, along with the investigations done in #4093, does really close #3378
- Please advice if I should remove `Utf8ToWideCharParser` now that it isn't used anymore

## Validation Steps Performed

- long UTF-8 files outputted to the console
- `printf` tested as shown in #4086

### CODE REVIEW

File: src/host/_stream.cpp [hunk 1]
```diff
@@ -1053,36 +1052,25 @@ constexpr unsigned int LOCAL_BUFFER_SIZE = 100;
         const auto codepage = gci.OutputCP;
 
         // Convert our input parameters to Unicode
-        std::unique_ptr<wchar_t[]> wideCharBuffer{ nullptr };
-        static Utf8ToWideCharParser parser{ gci.OutputCP };
```
Comment (DHowett-MSFT) [inline src/host/_stream.cpp]: **IGNORE, SEE BELOW** 
this one unfortunately cannot change just yet. `gci.OutputCP` _must_ be the user's console output codepage for now and the forseeable future.

This poses an interesting conundrum for u8u16: should we have "ASCII" versions that take a codepage? au16 and u16a? I'm not sure :smile:

Comment (DHowett-MSFT) [reply src/host/_stream.cpp]: maybe it's actually part of the `u*state` itself...

Comment (DHowett-MSFT) [reply src/host/_stream.cpp]: **OH**, I understand. You can almost entirely ignore this comment. I was confused because this was created outside the `CP_UTF8` block.
I also understand that writing in another codepage means we need to kill the u8 state -- so we can't move it inside this block.

Comment (german-one) [reply src/host/_stream.cpp]: @DHowett-MSFT Your understanding is correct. The `reset()` method is called in the `else` branch where codepages other than UTF-8 are processed. I knew I would need the `reset` here, that's why I implemented it from the beginning.

> This poses an interesting conundrum for u8u16: should we have "ASCII" versions that take a codepage? au16 and u16a? I'm not sure 😄

Interesting indeed. Well, we already have function `ConvertToW` (and `ConvertToA`). But that's not applicable in `WriteConsoleAImpl()` due to the fact that we may receive DBCS-encoded text where caching of partials is required, too. @miniksa briefly mentioned that in https://github.com/Microsoft/terminal/issues/386#issuecomment-507823218
I only have a poor understanding of how DBCS has to be processed though. The manpage of `IsDBCSLeadByte` states that even if you validated a lead byte you may not rely on `MultiByteToWideChar` being able to process the substring correctly. So, unfortunately I don't know enough to revise the DBCS handling. And I don't know if there is any other function in the code base where DBCS has to be converted. Hence it might not worth the effort to bring it into a separate function.
However, I offer to do my best to get rid of `new` and `delete` in `WriteConsoleAImpl()` and instead use the wstring that we already have for the UTF-8 conversion.

**Comment by german-one** [comment]
Removed `new` and `delete` in `WriteConsoleAImpl` and on this occasion cleaned it up a little.

**Comment by german-one** [comment]
The latest commit is intended to improve the readability of `WriteConsoleAImpl`, not to change its behavior in any kind.
This can be taken to be _somehow_ related to the update of the UTF-8 conversion in this function. However, I changed the topic to make it visible for everyone.

File: src/host/_stream.cpp (hunk 1 above)
Comment (miniksa) [reply src/host/_stream.cpp]: @german-one, if we theoretically made a `au16` and a `u16a` to supercede `ConvertToW` and `ConvertToA`, there would probably be some sort of `astate` variable required. That variable could be stored on the assorted input handles to ensure that the problem briefly discussed in #386 is rectified.

Off hand, I believe there are probably several points in the code base that could be unified behind such a convergence function in a similar way to converging the u8/u16 problem. But I haven't enumerated them recently, so I may be incorrect.

I believe that the only circumstance where we'd really pay attention to `IsDBCSLeadByte` and hold onto it until the next call is if a string ends in a lead byte (then it would take the lead byte off the end and cache it for the next call in the `astate` or equivalent.) If it's in the middle of a run, we wouldn't care and just pass it into `MultiByteToWideChar` probably with the replacement character flag on so it would remove invalid DBCS representations. The next write would have the stored DBCS lead prefixed to whatever comes next, even if it's not valid together, and we'd let MB2WC sort it out and replace it. 

The last provision to consider is that I believe the state would be discarded anytime the code page changed.

Comment (german-one) [reply src/host/_stream.cpp]: @miniksa  `u16a` would be easy. We only need to take care of split surrogates, and that's what `u16state` already does.
As to `au16` - [`IsDBCSLeadByteEx`](https://docs.microsoft.com/en-us/windows/win32/api/winnls/nf-winnls-isdbcsleadbyteex) isn't used in the current implementation of `CheckBisectStringA`. It would be my attempt to implement an `astate` though. The remarks found on the manpage still make me wonder if it would be bulletproof for DBCS.
But even if it was that simple, we would still only have conversions for SBCS, DBCS (the few mentioned on the manpage), and UTF-8. Guess what happens if we receive UTF-7 that was split inside of a base64 sequence 🤕

File: src/host/_stream.cpp [hunk 2]
```diff
@@ -1034,199 +1033,148 @@ constexpr unsigned int LOCAL_BUFFER_SIZE = 100;
...
-                                          charCount,
-                                          charsConsumed,
-                                          wideCharBuffer,
-                                          charsGenerated));
-
-            pwchBuffer = reinterpret_cast<wchar_t*>(wideCharBuffer.get());
-            cchBuffer = charsGenerated;
-            read = charsConsumed;
+            RETURN_IF_FAILED(til::u8u16(buffer, wstr, u8State));
+            read = buffer.size();
```
[the remark this answers is not in the document]
Comment (german-one) [reply src/host/_stream.cpp]: @DHowett-MSFT I was struggling with the same concern like you. We may decrease the effective number of bytes used by putting some in the cache and we also may increase the number by prepending the cached to the string. But for the records, the `utf8Parser::Parse()` method behaves the same. If it succeeds, it populates the incoming length as the length consumed. Since I'm not aware of any issues with this (and I didn't want to cause issues) I left this behavior unchanged.

**Comment by DHowett-MSFT** [comment]
:tada: Once again, thanks for the contribution!

This pull request was included in a set of conhost changes that was just
released with [Windows Insider Build 19603](https://blogs.windows.com/windowsexperience/2020/04/08/announcing-windows-10-insider-preview-build-19603/).
