### PR TITLE
AtlasEngine: Fix bugs introduced in 66f4f9d and d74b66a

### LINKED ISSUE #13490: Wrong terminal content redrawing after some time of inactivity...
### Windows Terminal version

Bulded from source... Last commit fd74d59c6c87a1ac49ffea11142ce273e07f95f0

### Windows build number

10.0.25151.0

### Other Software

PowerShell
Far Manager

### Steps to reproduce

After some time of inactivity we lost content redrawing... some parts still visible, links still exists and works as expected (click works and url under link is still right, underlined on hoover), background also seems ok for example... we can copy content of terminal and copy is fine. All tabs in same (wrong) state after some time... new ones is ok.

clear in powershell for example make some differences... but not solve problem: 3rd attached screenshot

On attached screenshots first tab with PowerShell after some time of inactivity and second tab in same terminal - new - with PowerShell in same scroll position.

### Expected Behavior

image

### Actual Behavior

image
image

### PR DESCRIPTION
**Pull request by lhecker**
### Disappearing glyphs

We only process glyphs within the dirtyRect, but glyphs outside of the dirtyRect
are still in use and shouldn't be discarded. This is critical if someone uses
a tool like tmux to split the terminal horizontally. If they then print a lot
of Unicode text on just one side, we have to ensure that the (for example)
plain ASCII glyphs on the other half of the viewport are still retained.

### Black viewport after font changes

The cursor was drawn without a clip rect, causing the entire atlas
texture to be filled with black. This just so happened to work fine 
in Windows Terminal but relied on a race condition.

Closes #13490

## Validation Steps Performed
* Disappearing glyphs
  * Start `tmux` in `wsl`
  * Split horizontally with `Ctrl+B`, `"`
  * `cat` a huge Unicode text file on the bottom
  * Ensure ASCII glyphs in the top half don't disappear ✅
* Black viewport after font changes
  * Start `OpenConsole` with `AtlasEngine`
  * Open Properties dialog and click "Ok"
  * Viewport content doesn't disappear ✅

### CODE REVIEW

File: src/renderer/atlas/AtlasEngine.h [hunk 1]
```diff
@@ -288,6 +288,12 @@ namespace Microsoft::Console::Render
             }
 #pragma warning(pop)
 
+            void destroy() noexcept
+            {
+                std::destroy_n(_data, _size);
+                deallocate(_data);
+            }
```
Comment (lhecker) [inline src/renderer/atlas/AtlasEngine.h:295]: These 3 `Buffer` changes should've been here all along. The 3 corresponding STL functions already do exactly the optimal thing: nothing for trivial types (i.e. leave the memory uninitialized) and properly construct/destruct the types if they're proper classes. And in case of `std::uninitialized_copy_n` in particular it already uses `memmove` for trivial types internally. Perfect!
This change allows us to construct a `Buffer<iterator>` which is an array of non-trivial types.

BTW/FYI: I didn't use `std::vector` and wrote `Buffer` instead, because I want to convey that these things explicitly _don't_ hold resizeable contents (in general). For instance I didn't want a `push_back` method on my viewport arrays - that wouldn't make sense so that always felt a bit wrong to me. It also doesn't initialize contents to zero, allowing rapid creation/destruction and you can specify a custom alignment (improves rendering perf by about 20% over `std::vector` IIRC).

File: src/renderer/atlas/AtlasEngine.r.cpp [hunk 2]
```diff
@@ -328,6 +331,7 @@ void AtlasEngine::_drawCursor()
     }
 
     _r.d2dRenderTarget->BeginDraw();
+    _r.d2dRenderTarget->PushAxisAlignedClip(&clip, D2D1_ANTIALIAS_MODE_ALIASED);
```
Comment (lhecker) [inline src/renderer/atlas/AtlasEngine.r.cpp:334]: Took me hours to figure this one out. 🥲

File: src/renderer/atlas/AtlasEngine.cpp [hunk 3]
```diff
@@ -360,6 +360,36 @@ try
...
     }
 
+    // This is an important block of code for our TileHashMap.
+    // We only process glyphs within the dirtyRect, but glyphs outside of the
+    // dirtyRect are still in use and shouldn't be discarded. This is critical
+    // if someone uses a tool like tmux to split the terminal horizontally.
+    // If they then print a lot of Unicode text on just one side, we have to
+    // ensure that the (for example) plain ASCII glyphs on the other half of the
+    // viewport are still retained. This bit of code "refreshes" those glyphs and
+    // brings them to the front of the LRU queue to prevent them from being reused.
```
Comment (DHowett) [inline src/renderer/atlas/AtlasEngine.cpp:370]: how expensive is this refresh?

Comment (DHowett) [reply src/renderer/atlas/AtlasEngine.cpp:370]: would this be easier if we did not track dirty rects at all, and just did the whole screen every time?

File: src/renderer/atlas/AtlasEngine.r.cpp (hunk 2 above)
Comment (DHowett) [reply src/renderer/atlas/AtlasEngine.r.cpp:334]: what _is_ it?

Comment (DHowett) [reply src/renderer/atlas/AtlasEngine.r.cpp:334]: oh the cursor!

File: src/renderer/atlas/AtlasEngine.cpp [hunk 4]
```diff
@@ -360,6 +360,36 @@ try
...
+    {
+        std::array<til::point, 2> ranges{ {
+            { 0, _api.dirtyRect.top },
+            { _api.dirtyRect.bottom, _api.cellCount.y },
+        } };
+        const auto stride = static_cast<size_t>(_r.cellCount.x);
+        for (const auto& p : ranges)
+        {
+            const auto from = p.x;
+            const auto to = p.y;
```
Comment (carlos-zamora) [inline src/renderer/atlas/AtlasEngine.cpp:380]: Sorry, I'm just really confused about this. Why are we iterating from the x-coord to the y-coord? The inner loop makes sense because we're looping over each y value. Shouldn't this be looping over the x values then?

File: src/renderer/atlas/AtlasEngine.h [hunk 5]
```diff
@@ -553,21 +564,28 @@ namespace Microsoft::Console::Render
...
+
             TileHashMap() noexcept = default;
 
-            AtlasValue* find(const AtlasKey& key)
+            iterator end() noexcept
+            {
+                return _lru.end();
+            }
+
+            iterator find(const AtlasKey& key)
```
[the remark this answers is not in the document]
Comment (carlos-zamora) [reply src/renderer/atlas/AtlasEngine.h:576]: Oh I see it now. This is better too because now you can just get the `AtlasValue` when you want it.

File: src/renderer/atlas/AtlasEngine.r.cpp [hunk 6]
```diff
@@ -293,11 +293,14 @@ void AtlasEngine::_drawCursor()
...
-    rect.right = _r.cellSizeDIP.x;
-    rect.bottom = _r.cellSizeDIP.y;
+
+    D2D1_RECT_F clip;
+    clip.left = 0.0f;
+    clip.top = 0.0f;
+    clip.right = _r.cellSizeDIP.x;
+    clip.bottom = _r.cellSizeDIP.y;
+
+    auto rect = clip;
```
Comment (carlos-zamora) [inline src/renderer/atlas/AtlasEngine.r.cpp:303]: Why do we need clip? I mean, I see that we call `PushAxisAlignedClip()` down below, but it would be nice to add a comment here explaining the purpose of clip and what it fixes, exactly. More just so that anybody that comes along understands this code better.

File: src/renderer/atlas/AtlasEngine.cpp (hunk 3 above)
Comment (lhecker) [reply src/renderer/atlas/AtlasEngine.cpp:370]: We need to avoid measuring glyphs with DirectWrite as much as possible, due to its insufficient font fallback performance. While not tracking dirty rects improves performance for ASCII ¹, it would make eastern scripts very unpleasant to use.

Brahmi script as used in India for instance runs at approx. 100k-150k code points per second on my fairly powerful workstation, compared to approx. 9M code points per second for Latin scripts. While 100k code points per second _sounds_ much, that's only ~30 FPS at 120x30 with my CPU running at 5 GHz. This means we have to cache DirectWrite results as much as possible and thus requires this workaround.

¹ Approx. 1.5x with DirectWrite, approx. 2-3x with Uniscribe.

File: src/renderer/atlas/AtlasEngine.h [hunk 7]
```diff
@@ -175,19 +175,24 @@ namespace Microsoft::Console::Render
...
             Buffer(const T* data, size_t size) :
                 _data{ allocate(size) },
                 _size{ size }
             {
-                static_assert(std::is_trivially_copyable_v<T>);
-                memcpy(_data, data, size * sizeof(T));
+                // Changing the constructor arguments to accept std::span might
+                // be a good future extension, but not to improve security here.
+                // You can trivially construct std::span's from invalid ranges.
+                // Until then the raw-pointer style is more practical.
```
[the remark this answers is not in the document]
Comment (lhecker) [reply src/renderer/atlas/AtlasEngine.h:188]: I intended the comment more of an "excuse" why following the C++ guidelines there is impractical and wouldn't help with security either.

I was about to write that I'll add it anyways, but just realized that it would require us to include `<span>` everywhere. 🤔 I'd rather replace `<gsl/span>` with `<span>` everywhere first.

File: src/renderer/atlas/AtlasEngine.h (hunk 5 above)
[the remark this answers is not in the document]
Comment (lhecker) [reply src/renderer/atlas/AtlasEngine.h:576]: Yeah and we need to stuff the iterator into the new `Buffer`.

File: src/renderer/atlas/AtlasEngine.cpp (hunk 4 above)
Comment (lhecker) [reply src/renderer/atlas/AtlasEngine.cpp:383]: I've added a brief comment explaining this peculiar code.

File: src/renderer/atlas/AtlasEngine.r.cpp (hunk 6 above)
Comment (lhecker) [reply src/renderer/atlas/AtlasEngine.r.cpp:305]: Let me know if the comment I just added is sufficient. 🙂

File: src/renderer/atlas/AtlasEngine.cpp [hunk 8]
```diff
@@ -369,15 +369,19 @@ try
...
+        const std::array<til::point, 2> ranges{ {
             { 0, _api.dirtyRect.top },
             { _api.dirtyRect.bottom, _api.cellCount.y },
         } };
         const auto stride = static_cast<size_t>(_r.cellCount.x);
+
         for (const auto& p : ranges)
         {
+            // We (ab)use the .x/.y members of the til::point as the
+            // respective [from,to) range of rows we need to makeNewest().
```
Comment (carlos-zamora) [inline src/renderer/atlas/AtlasEngine.cpp:381]: hahahaha, ok that makes me feel _much better_ about this

File: src/renderer/atlas/AtlasEngine.h (hunk 1 above)
Comment (DHowett) [reply src/renderer/atlas/AtlasEngine.h:300]: When you pull these classes out to their own files, explain that ^^ in a comment!

File: src/renderer/atlas/AtlasEngine.r.cpp [hunk 9]
```diff
@@ -328,6 +333,9 @@ void AtlasEngine::_drawCursor()
     }
 
     _r.d2dRenderTarget->BeginDraw();
+    // We need to clip the area we draw in to ensure we don't
+    // accidentally draw into any neighboring texture atlas tiles.
+    _r.d2dRenderTarget->PushAxisAlignedClip(&clip, D2D1_ANTIALIAS_MODE_ALIASED);
```
Comment (DHowett) [inline src/renderer/atlas/AtlasEngine.r.cpp:338]: I don't actually understand why we need this clip! We are only filling or stroking within `0,0 .. cellSizeDIP` _already_; were we measurably "accidentally" drawing into the neighboring tiles? When? How?

**Review by DHowett — APPROVED** [review]

File: src/renderer/atlas/AtlasEngine.r.cpp (hunk 9 above)
Comment (lhecker) [reply src/renderer/atlas/AtlasEngine.r.cpp:338]: I'm a bit concerned that D2D might draw lines/rectangles outside of the coordinates I specify, be it due to off-by-fractional-1 bugs or due to AA. I think using a clip rect is more robust and doesn't hurt performance since we only seldomly draw a cursor.
