### PR TITLE
Ensure TermControl is not closing when firing UIA events

### LINKED ISSUE #13978: The SignalTextChanged crash isn't actually fixed
FYI I just got a crash in `RaiseAutomationEventImpl` passing through `SignalTextChanged`, which seems similar to the one shown in https://github.com/microsoft/terminal/issues/13357#issuecomment-1163015484. This occurred while shutting down the terminal, so I'm assuming I wouldn't have noticed usually, but I happened to be in the debugger at the time.

I'm branched off of 3e6abd37df192d969088188ce836edbf645b13b4, which includes PR #13876, so that doesn't appear to have helped. I do have some local changes, so it's possible that may be a factor, but I don't think that's likely.

The exception was:
```
Unhandled exception at 0x00007FFE52AADA82 (Windows.UI.Xaml.dll) in WindowsTerminal.exe: 0xC0000005: Access violation reading location 0x0000000000000010.
```

And this was the stack trace:
```
>	Windows.UI.Xaml.dll!DirectUI::AutomationPeer::RaiseAutomationEventImpl(Windows::UI::Xaml::Automation::Peers::AutomationEvents eventId) Line 813	C++
 	Windows.UI.Xaml.dll!DirectUI::AutomationPeerGenerated::RaiseAutomationEvent(Windows::UI::Xaml::Automation::Peers::AutomationEvents eventId) Line 1980	C++
 	Microsoft.Terminal.Control.dll!winrt::Microsoft::Terminal::Control::implementation::TermControlAutomationPeer::SignalTextChanged::__l2::<lambda_1>::operator()() Line 166	C++
 	Microsoft.Terminal.Control.dll!winrt::impl::delegate<winrt::Windows::UI::Core::DispatchedHandler,`winrt::Microsoft::Terminal::Control::implementation::TermControlAutomationPeer::SignalTextChanged'::`2'::<lambda_1>>::Invoke() Line 1136	C++
 	[External Code]	
 	[Inline Frame] WindowsTerminal.exe!winrt::impl::consume_Windows_Foundation_IClosable<winrt::TerminalApp::App>::Close() Line 121	C++
 	WindowsTerminal.exe!AppHost::~AppHost() Line 149	C++
 	WindowsTerminal.exe!wWinMain(HINSTANCE__ * __formal, HINSTANCE__ * __formal, wchar_t * __formal, int __formal) Line 193	C++
 	[External Code]	
```

I poked about in the local variables for a bit to see if I could spot anything obviously wrong, but I'm afraid I don't understand the code well enough to make a meaningful assessment. A lot of fields said "Object uninitialized or information unavailable", but I suspect that may just be a release build thing.

_Originally posted by @j4james in https://github.com/microsoft/terminal/issues/13357#issuecomment-1242812664_

### PR DESCRIPTION
**Pull request by carlos-zamora**
The `SignalTextChanged` crash seems to be occurring due to the `TermControlAutomationPeer` being destructed by the time the UIA event is actually dispatched. Even though we're already checking if TCAP and TermControl still exist, it could be that the TermControl is being closed as text is being output.

The proposed fix here is to record when the closing process starts and exposing that information directly to the TCAP. If TCAP sees that we're in the process of closing, don't bother sending a UIA event.

Closes #13978

### CODE REVIEW

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 1]
```diff
@@ -1990,6 +1990,11 @@ namespace winrt::Microsoft::Terminal::Control::implementation
         if (!_IsClosing())
         {
             _closing = true;
+            if (_automationPeer)
+            {
+                auto autoPeerImpl{ winrt::get_self<implementation::TermControlAutomationPeer>(_automationPeer) };
+                autoPeerImpl->IsClosing(true);
+            }
```
Comment (carlos-zamora) [inline src/cascadia/TerminalControl/TermControl.cpp:1997]: I don't like this too too much, but I don't know if there's a better way to do this. `IsClosing()` is a public function off the impl type, so that helps ensure it isn't abused.

I'm mildly annoyed that we only use it _once_, but `_closing` is only set in one spot so I'll take what I can get haha.

File: src/cascadia/TerminalControl/TermControlAutomationPeer.h [hunk 2]
```diff
@@ -81,5 +82,6 @@ namespace winrt::Microsoft::Terminal::Control::implementation
         winrt::weak_ref<Microsoft::Terminal::Control::implementation::TermControl> _termControl;
         Control::InteractivityAutomationPeer _contentAutomationPeer;
         til::shared_mutex<std::deque<wchar_t>> _keyEvents;
+        bool _closing;
```
Comment (DHowett) [inline src/cascadia/TerminalControl/TermControlAutomationPeer.h:85]: big whoa! make sure you initialize this - it will otherwise contain random data and some subset of users will report that they never get text notifications any more!

File: src/cascadia/TerminalControl/TermControlAutomationPeer.cpp [hunk 3]
```diff
@@ -248,7 +253,7 @@ namespace winrt::Microsoft::Terminal::Control::implementation
         dispatcher.RunAsync(Windows::UI::Core::CoreDispatcherPriority::Normal, [weakThis{ get_weak() }, sanitizedCopy{ hstring{ sanitized } }]() {
             if (auto strongThis{ weakThis.get() })
             {
-                if (auto control{ strongThis->_termControl.get() })
+                if (auto control{ strongThis->_termControl.get() }; control && !strongThis->_closing)
```
Comment (DHowett) [inline src/cascadia/TerminalControl/TermControlAutomationPeer.cpp:256]: @lhecker do we need some sort of atomic for `_closing` here? We're guaranteed multiple threads will contend for it.

**Review by DHowett — CHANGES_REQUESTED** [review]
Only the big whoa

**Review by DHowett — APPROVED** [review]

File: src/cascadia/TerminalControl/TermControlAutomationPeer.cpp (hunk 3 above)
Comment (lhecker) [reply src/cascadia/TerminalControl/TermControlAutomationPeer.cpp:257]: The `_closing` check is ineffective even if it was atomic, because TermControl might close on the main thread while this background thread is running the code inside the if condition. In other words, the if condition would be about as effective if the `_closing` condition wouldn't exist at all.

...but why does the `_closing` check exist at all? The PR message implies that all we need to do is to keep TermControl and TCAP alive. But the old code already did that, so is the PR message incomplete?

Solving both problems may be done by using a semaphore (= unblock when the count is 0). Unfortunately `std::semaphore` doesn't work for this purpose (it blocks when the count is 0), but an alternative may be built with `std::condition_variable` or similar.

**Review by lhecker — CHANGES_REQUESTED** [review]
Let's figure this `_closing` race out. :)

File: src/cascadia/TerminalControl/TermControlAutomationPeer.cpp (hunk 3 above)
Comment (DHowett) [reply src/cascadia/TerminalControl/TermControlAutomationPeer.cpp:257]: The problem is, the UIA machinery in XAML doesn't care whether our object is still alive. We need an external signal that we should stop attempting to produce notifications... we don't want to wait for them to finish

**Review by lhecker — APPROVED** [review]
Dustin pointed out to me that the callbacks occur on the main thread and not a background thread. No atomics or anything needed then. 😊

File: src/cascadia/TerminalControl/TermControlAutomationPeer.h [hunk 4]
```diff
@@ -49,6 +49,7 @@ namespace winrt::Microsoft::Terminal::Control::implementation
         void UpdateControlBounds();
         void SetControlPadding(const Core::Padding padding);
         void RecordKeyEvent(const WORD vkey);
+        void IsClosing(bool closing);
```
Comment (lhecker) [inline src/cascadia/TerminalControl/TermControlAutomationPeer.h:52]: BTW it might be more readable if you name this function `NotifyControlClosed()` or something, since the boolean parameter will always be `true`.

Comment (DHowett) [reply src/cascadia/TerminalControl/TermControlAutomationPeer.h:52]: agreed. Or just `Close()` like the one in TermControl

Comment (lhecker) [reply src/cascadia/TerminalControl/TermControlAutomationPeer.h:52]: Yeah I like `Close()`. And I just realized that you can actually drop the `bool _closing` member and instead just `.reset()` the `_termControl` member!

**Review by DHowett — APPROVED** [review]
