### PR TITLE
Remove the rowsToScroll setting and just always use the system setting

### LINKED ISSUE #5610: Mouse wheel scrolls backwards when set to "one screen at a time"
# Environment
```
Microsoft Windows [Version 10.0.18363.720]
Windows Terminal 0.11.1121.0
Lenovo X1 Yoga
Logitech Mouse (M185)
```

# Steps to reproduce
- Open Windows Terminal
- Open a shell (cmd, Powershell, ...)
- Issue commands leading to the display of vertical scrollbar 
- Use the mouse wheel

# Expected behavior
- Mouse wheel should behave in Windows Terminal as it does in other system apps 

# Actual behavior
- Mouse wheel scrolls in the other direction (rolling the mouse wheel upward scrolls down)

Suspecting potential conflicts with the Laptop touchscreen or trackpad i disabled them, but still observe the same behavior. I tried to look for parameters allowing to control the mouse wheel but did not find any.

### PR DESCRIPTION
**Pull request by DHowett**
This parameter was added as a workaround for our fast trackpad
scrolling. Since that was fixed before 1.0 shipped, in #4554, it has
been largely vestigial. There is no reason for us to keep it around any
longer.

It was also the only "logic" in TerminalSettings, which is otherwise a
library that only transits data between two other libraries.

I have not removed it from the schema, as I do not want to mark folks'
settings files invalid to a strict schema parser.

While I was in the area, I added support for "scroll one screen at a
time" (which is represented by the API returning WHEEL_PAGESCROLL),
fixing #5610. We were also storing it in an int (whoops) instead of a
uint.

Fixes #5610

### CODE REVIEW

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 1]
```diff
@@ -1697,7 +1696,18 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
...
+        _UpdateSystemParameterSettings();
+    }
+
+    // Method Description
+    // - Updates internal params based on system parameters
+    void TermControl::_UpdateSystemParameterSettings() noexcept
+    {
+        if (!SystemParametersInfoW(SPI_GETWHEELSCROLLLINES, 0, &_rowsToScroll, 0))
+        {
+            _rowsToScroll = 3;
```
Comment (zadjii-msft) [inline src/cascadia/TerminalControl/TermControl.cpp:1709]: what the heck, why 3?

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 2]
```diff
@@ -1495,8 +1494,8 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
 
         // With one of the precision mouses, one click is always a multiple of 120,
         // but the "smooth scrolling" mode results in non-int values
-
-        double newValue = (_rowsToScroll * rowDelta) + (currentOffset);
+        const auto rowsToScroll{ _rowsToScroll == WHEEL_PAGESCROLL ? GetViewHeight() : _rowsToScroll };
```
Comment (zadjii-msft) [inline src/cascadia/TerminalControl/TermControl.cpp:1497]: please add a comment explaining what `WHEEL_PAGESCROLL` does, and/or where it comes from

File: doc/cascadia/profiles.schema.json [hunk 3]
```diff
@@ -396,7 +396,7 @@
         },
         "rowsToScroll": {
           "default": "system",
-          "description": "The number of rows to scroll at a time with the mouse wheel. This will override the system setting if the value is not zero or \"system\".",
+          "description": "This parameter has been deprecated.",
```
Comment (carlos-zamora) [inline doc/cascadia/profiles.schema.json:399]: Is there a built-in way to deprecate things through the JSON schema? I tried looking into it but I got a bit lost.

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 2 above)
Comment (DHowett) [reply src/cascadia/TerminalControl/TermControl.cpp:1497]: Im like 50/50 on this; it’s a quick Ctrl-click away, and it’s a documented Win32 API, but also it’s weird and probably worth commenting

File: doc/cascadia/profiles.schema.json (hunk 3 above)
Comment (DHowett) [reply doc/cascadia/profiles.schema.json:399]: Not that I’m aware of.

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 1 above)
Comment (DHowett) [reply src/cascadia/TerminalControl/TermControl.cpp:1709]: 3 appears to be the default value configured for this feature on Windows

Comment (DHowett) [reply src/cascadia/TerminalControl/TermControl.cpp:1709]: I believe SystemParamInfoW will never fail, but it _can_ fail, so why not protecc

File: doc/cascadia/profiles.schema.json (hunk 3 above)
Comment (DHowett) [reply doc/cascadia/profiles.schema.json:399]: Maybe, but I don’t know if we’re using a new-enough version of the json-schema format

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 1 above)
Comment (zadjii-msft) [reply src/cascadia/TerminalControl/TermControl.cpp:1709]: excuse-me

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 2 above)
Comment (DHowett) [reply src/cascadia/TerminalControl/TermControl.cpp:1500]: addressed.

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 1 above)
Comment (DHowett) [reply src/cascadia/TerminalControl/TermControl.cpp:1715]: documented, but yeah i know

**Comment by DHowett** [comment]
@carlos-zamora doc discussion ongoing in https://github.com/MicrosoftDocs/terminal/pull/87
