### PR TITLE
Stop leaking CPR sequences

### LINKED ISSUE #19575: Any shortcut prints random signs (even when window is not active)
### Windows Terminal version

1.25.3251.0

### Windows build number

26100.7171

### Other Software

_No response_

### Steps to reproduce

Press any shortcut key (e.g., Ctrl+I, Ctrl+K, Alt+key)
Prints random signs on the terminal: "2R4R4R0R0R4R4R"
Repeat inside SSH or tmux — same behaviour
Press shortcuts while the  WT window is not active — still reproduces

### Expected Behavior

No output in the terminal

### Actual Behavior

Unexpected terminal output: 2R4R4R0R0R4R4R or ;3R;6R;9R.

### LINKED ISSUE #19609: Escape sequences appearing on new Ubuntu panes
### Windows Terminal version

1.25.3351.0

### Windows build number

25H2 26220.7070

### Other Software

_No response_

### Steps to reproduce

Use Windows Terminal Canary
Open a new Ubuntu pane
Toggle pane zoom on the Ubuntu pane

### Expected Behavior

No weird escape sequences appearing in the prompt :)

### Actual Behavior

Upon opening a new pane:
Image

After toggling pane zoom, new characters appear in the prompt:

Image

Image

### PR DESCRIPTION
**Pull request by lhecker**
Due to the `IsVtInputEnabled` early return, we'd skip
the `_captureNextCursorPositionReport` by accident.

Closes #19575
Closes #19609

### CODE REVIEW

File: src/terminal/parser/InputStateMachineEngine.cpp [hunk 1]
```diff
@@ -391,19 +391,18 @@ bool InputStateMachineEngine::ActionCsiDispatch(const VTID id, const VTParameter
...
 
     switch (id)
     {
     case CsiActionCodes::MouseDown:
     case CsiActionCodes::MouseUp:
     {
+        if (vtInputEnabled)
+        {
+            return false;
+        }
```
Comment (lhecker) [inline src/terminal/parser/InputStateMachineEngine.cpp:404]: This is more verbose than before, but also easier to understand IMO and only 2 more checks than before (3 `id` comparisons VS 5 if conditions).

**Review by DHowett — APPROVED** [review]
