### PR TITLE
Attempt to fix the _refreshSizeUnderLock crash

### LINKED ISSUE #12176: `ControlCore::_refreshSizeUnderLock` crash
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.22523.0

### Other Software

````
wsl --list -v

  NAME                   STATE           VERSION
* docker-desktop-data    Running         2
  Ubuntu                 Running         2
  docker-desktop         Running         2
````

Typically I'm using multiple panes, one or more tabs, with both Windows 11 Powershell and Ubuntu. For ubuntu:

````
cat /etc/lsb-release

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
````

### Steps to reproduce

Day-to-day use of the terminal. Sometimes WSL *and* Windows Powershell tabs/panes, sometimes just one or the other. Somtimes using software like k9s, other times just sitting at a prompt.

### Expected Behavior

Everything to remain responsive.

### Actual Behavior

After some nondescript amount of time, the window hangs, Terminal is unresponsive and must be quit. Windows crash reporting pops up.

If I leave it long enough (say a few hours), it's more likely to have occurred. Sometimes it's during active use though. If I'm using `k9s` (kubernetes tool) on a Windows powershell and press `e` to open Notepad to edit some yaml, recently that pane has then stopped responding to input (but output still updates). Unsure if related.

Feedback Hub link: https://aka.ms/AAfh1tt

### PR DESCRIPTION
**Pull request by zadjii-msft**
See https://github.com/microsoft/terminal/issues/12176#issuecomment-1199488906, and MSFT:39723014.

I have literally no idea how to repro this one, or debug it. The dump I looked at looked like there was a `SwapChainScaleChanged` that was being dispatched as the app was tearing down. The `ControlCore` had started closing, but the `TermControl` hadn't yet. Apparently, just none of the `_refreshSizeUnderLock` callers checked if we were already closing.

All the callers appear to be on the main thread.

Closes #12176

Since there's no real way for me to repro this manually, I'm thinking we fire this fix off to the OS terminal build, where we'll pretty quickly be able to see if this fixed it or not.

### CODE REVIEW

**Review by lhecker — APPROVED** [review]

File: src/cascadia/TerminalControl/ControlCore.cpp [hunk 1]
```diff
@@ -911,6 +911,11 @@ namespace winrt::Microsoft::Terminal::Control::implementation
     // - <none>
     void ControlCore::_refreshSizeUnderLock()
     {
+        if (_IsClosing())
```
Comment (DHowett) [inline src/cascadia/TerminalControl/ControlCore.cpp:914]: IsClosing only works on main thread. This is guaranteed to be on the main thread right?

**Review by DHowett — APPROVED** [review]

File: src/cascadia/TerminalControl/ControlCore.cpp (hunk 1 above)
Comment (lhecker) [reply src/cascadia/TerminalControl/ControlCore.cpp:914]: All callers appear to be WinUI related callbacks/functions.
