### PR TITLE
Wait for clients to exit on ConPTY shutdown

### LINKED ISSUE #14132: OpenConsole.exe will not quit if start with `msys2` profile and click `close window button`
### Windows Terminal version

1.16.22...

### Windows build number

_No response_

### Other Software

_No response_

### Steps to reproduce

 start WT  with `msys2` profile and click `close window button`.

### Expected Behavior

OpenConsole.exe should quit after click close button even if WT start with msys2 profile.

### Actual Behavior

 I have to type `exit` to make OpenConsole.exe quit everytime or it will become a zombie process.

### PR DESCRIPTION
**Pull request by lhecker**
#14160 didn't fix #14132 entirely. There seems to be a race condition left
where (on my system) 9 out of 10 times everything works correctly,
but sometimes OpenConsole exits, while pwsh and bash keep running.

My leading theory is that the new code is exiting OpenConsole faster than the
old code. This prevents clients from calling console APIs, etc. causing them
to get stuck. The old code (and new code) calls `ExitProcess` when the ConPTY
pipes break and I think this is wrong: In conhost when you close the window we
only call `CloseConsoleProcessState` via the `WM_CLOSE` event and that's it.
Solution: Remove the call to `RundownAndExit` for ConPTY.

During testing I found that continuously printing text inside msys2 will cause
child processes to only exit slowly one by one every 5 seconds.
This happens because `CloseConsoleProcessState` calls `HandleCtrlEvent` without
holding the console lock. This creates a race condition where most of the time
the console IO thread is the one picking up the `CTRL_CLOSE_EVENT`. But that's
problematic because the `CTRL_CLOSE_EVENT` leads to a `ConsoleControl` call of
type `ConsoleEndTask` which calls back into conhost's IO thread and
so you got the IO thread waiting on itself to respond.
Solution: Don't race conditions.

## Validation Steps Performed
* `Enter-VsDevShell` and close the tab
  Everything exits after 5s ✅
* Run msys2 bash from within pwsh and close the tab
  Everything exits instantly ✅
* Run `cat bigfile.txt` and close the tab
  Everything exits instantly ✅
* Patch `conhost.exe` with `sfpcopy`, as well as `KernelBase.dll`
  with the recent changes to `winconpty`, then launch and exit
  shells and applications via VS Code's terminal ✅
* On the main branch without this modification remove the call to
  `TriggerTeardown` in `RundownAndExit` (this speeds up the shutdown).
  Run (msys2's) `bash.exe --login` and hold enter and then press Ctrl+Shift+W
  simultaneously. The tab should close and randomly OpenConsole should exit
  early while pwsh/bash keep running. Then retry this with this branch and
  observe how the child processes don't stick around forever anymore. ✅

### CODE REVIEW

**Comment by DHowett** [comment]
Notes from chat on Saturday: pseudoconsole teardown should have the same effect as clicking the `X` in a conhost window. If that means a process takes a while to release its last console handle after it gets the `CTRL_CLOSE_EVENT` (or similar), at least we can make Terminal not block on it.

**Comment by lhecker** [comment]
> Please check all prior criteria, including VSCode. :)

I think only VS Code was missing. Seems to work great.

File: src/host/PtySignalInputThread.cpp [hunk 1]
```diff
@@ -106,7 +110,10 @@ void PtySignalInputThread::CreatePseudoWindow()
         case PtySignal::ShowHideWindow:
         {
             ShowHideData msg = { 0 };
-            _GetData(&msg, sizeof(msg));
+            if (!_GetData(&msg, sizeof(msg)))
+            {
+                break;
+            }
```
Comment (lhecker) [inline src/host/PtySignalInputThread.cpp:116]: All of these were missing. `_GetData` returns a `bool` after all.

File: src/host/PtySignalInputThread.cpp [hunk 2]
```diff
@@ -191,9 +204,7 @@ void PtySignalInputThread::CreatePseudoWindow()
             break;
         }
         default:
-        {
-            THROW_HR(E_UNEXPECTED);
-        }
+            break;
```
Comment (lhecker) [inline src/host/PtySignalInputThread.cpp:207]: We can't throw an exception here - no one is catching it and it would cross an ABI boundary otherwise.

File: src/host/PtySignalInputThread.cpp [hunk 3]
```diff
@@ -273,25 +284,14 @@ bool PtySignalInputThread::_GetData(_Out_writes_bytes_(cbBuffer) void* const pBu
...
-            THROW_WIN32(lastError);
-        }
+        return false;
     }
-    else if (dwRead != cbBuffer)
+
+    if (dwRead != cbBuffer)
     {
-        _Shutdown();
+        return false;
```
Comment (lhecker) [inline src/host/PtySignalInputThread.cpp:294]: Now that `RundownAndExit` is missing, we aren't `[[noreturn]]` anymore and need to return something. Almost didn't catch this due to the disabled linter checks.

File: src/host/VtInputThread.cpp [hunk 4]
```diff
@@ -110,10 +110,6 @@ void VtInputThread::DoReadInput(const bool throwOnFail)
     DWORD dwRead = 0;
     auto fSuccess = !!ReadFile(_hFile.get(), buffer, ARRAYSIZE(buffer), &dwRead, nullptr);
 
-    // If we failed to read because the terminal broke our pipe (usually due
-    //      to dying itself), close gracefully with ERROR_BROKEN_PIPE.
-    // Otherwise throw an exception. ERROR_BROKEN_PIPE is the only case that
-    //       we want to gracefully close in.
```
Comment (lhecker) [inline src/host/VtInputThread.cpp:116]: This comment is a copy/paste from `PtySignalInputThread`, but it doesn't actually apply to this code. Also there's only 4 uses of `_exitRequested` in total which makes this code easy to follow anyways IMO.

File: src/host/PtySignalInputThread.cpp [hunk 5]
```diff
@@ -191,12 +209,9 @@ void PtySignalInputThread::CreatePseudoWindow()
             break;
         }
         default:
-        {
-            THROW_HR(E_UNEXPECTED);
-        }
+            return S_OK;
```
Comment (lhecker) [inline src/host/PtySignalInputThread.cpp:212]: We can't throw an exception here - no one is catching it and it would cross an ABI boundary otherwise. This is also why this function is now `noexcept` - it should've always been.

File: src/host/PtySignalInputThread.cpp [hunk 6]
```diff
@@ -96,17 +96,29 @@ void PtySignalInputThread::CreatePseudoWindow()
...
+        _Shutdown();
+    });
+
+    for (;;)
     {
+        PtySignal signalId;
+        if (!_GetData(&signalId, sizeof(signalId)))
+        {
+            return S_OK;
+        }
```
Comment (lhecker) [inline src/host/PtySignalInputThread.cpp:111]: I changed this in the end, so that the `_GetData` calls are all uniform and consistent. I just felt that this looks better...

File: src/winconpty/ft_pty/ConPtyTests.cpp [hunk 7]
```diff
@@ -218,63 +221,6 @@ void ConPtyTests::SurvivesOnBreakOutput()
...
-    VERIFY_SUCCEEDED(WriteFile(inPipeOurSide.get(), L"a", sizeof(wchar_t), nullptr, nullptr));
-
-    // Close the other pipe, and make sure conhost dies
-    VERIFY_IS_TRUE(CloseHandle(inPipeOurSide.get()));
-
-    VERIFY_ARE_EQUAL(WaitForSingleObject(pty.hConPtyProcess, 10000), (DWORD)WAIT_OBJECT_0);
-    VERIFY_IS_TRUE(GetExitCodeProcess(pty.hConPtyProcess, &dwExit));
-    VERIFY_ARE_NOT_EQUAL(dwExit, (DWORD)STILL_ACTIVE);
-}
-
```
Comment (lhecker) [inline src/winconpty/ft_pty/ConPtyTests.cpp:277]: This test doesn't work anymore because now conhost won't exit when you close the pipes. This is because winconpty holds a console client handle inside `hPtyReference`. Only once you call `ClosePseudoConsole` that handle will be closed, but this is already being tracked in the `DiesOnClose()` test.

File: src/host/output.cpp [hunk 8]
```diff
@@ -499,7 +499,11 @@ void SetActiveScreenBuffer(SCREEN_INFORMATION& screenInfo)
 // TODO: MSFT 9450717 This should join the ProcessList class when CtrlEvents become moved into the server. https://osgvsowi/9450717
 void CloseConsoleProcessState()
 {
+    LockConsole();
+    const auto unlock = wil::scope_exit([] { UnlockConsole(); });
```
Comment (lhecker) [inline src/host/output.cpp:503]: To quote myself from the PR:
> During testing I found that continuously printing text inside msys2 will cause child processes to only exit slowly one by one every 5 seconds.
> This happens because `CloseConsoleProcessState` calls `HandleCtrlEvent` without holding the console lock. This creates a race condition where most of the time the console IO thread is the one picking up the `CTRL_CLOSE_EVENT`. But that's problematic because the `CTRL_CLOSE_EVENT` leads to a `ConsoleControl` call of type `ConsoleEndTask` which calls back into conhost's IO thread and so you got the IO thread waiting on itself to respond.
> Solution: Don't race conditions.

File: src/interactivity/base/ServiceLocator.cpp [hunk 9]
```diff
@@ -50,6 +50,14 @@ void ServiceLocator::RundownAndExit(const HRESULT hr)
     //   because doing so would prevent the render thread from progressing.
     if (locked.exchange(true, std::memory_order_relaxed))
     {
+        // Don't sleep forever with the console lock being held or otherwise
+        // no one can acquire it while we shut down.
+        const auto& gci = s_globals.getConsoleInformation();
+        while (gci.IsConsoleLocked())
+        {
+            gci.UnlockConsole();
+        }
```
Comment (lhecker) [inline src/interactivity/base/ServiceLocator.cpp:59]: I put this in a safety measure so that `CloseConsoleProcessState()` works correctly even if the console lock was acquired. Do you think I should call the global `UnlockConsole()` instead so that this optionally calls `ProcessCtrlEvents`? I was hoping that this wouldn't be important given that this would be at least the second thread to enter `RundownAndExit`...

File: src/host/output.cpp (hunk 8 above)
Comment (DHowett) [reply src/host/output.cpp:503]: So wait, calling `RundownAndExit` is _safe_ to do while holding the console lock? Isn't it another recipe for a deadlock?

File: src/interactivity/base/ServiceLocator.cpp (hunk 9 above)
Comment (DHowett) [reply src/interactivity/base/ServiceLocator.cpp:59]: Ah, I see. This is... i'm honestly not sure.
While we're running down and exiting _in response to a process exiting,_ I don't think we need to deliver it any more signals.

File: src/host/output.cpp (hunk 8 above)
Comment (lhecker) [reply src/host/output.cpp:503]: I don't think it's safe at all, but the conhost code did exactly that. `Window::ConsoleWindowProc` acquires the console lock and then calls `Window::_CloseWindow` which calls `CloseConsoleProcessState` which calls `ServiceLocator::RundownAndExit`.
In the past without ConPTY `RundownAndExit` was trivial since it only did `ProcessExit` but now with the render flush it has been a disaster recipe for quite a while unfortunately...

File: src/host/output.cpp [hunk 10]
```diff
@@ -513,14 +517,4 @@ void CloseConsoleProcessState()
...
-
-    // Jiggle the handle: (see MSFT:19419231)
-    // When we call this function, we'll only actually close the console once
-    //      we're totally unlocked. If our caller has the console locked, great,
-    //      we'll dispatch the ctrl event once they unlock. However, if they're
-    //      not running under lock (eg PtySignalInputThread::_GetData), then the
-    //      ctrl event will never actually get dispatched.
-    // So, lock and unlock here, to make sure the ctrl event gets handled.
-    LockConsole();
-    UnlockConsole();
```
Comment (DHowett) [inline src/host/output.cpp:525]: okay just so I understand... the Unlock happening after the scope_exit will have the same effect of making sure the CTRL event gets handled? Can you look up the repro for MSFT-19419231?

**Review by DHowett — APPROVED** [review]
I think I have to trust this. We've gotten it wrong a number of times, but this _must be better_?

File: src/host/PtySignalInputThread.cpp [hunk 11]
```diff
@@ -272,26 +287,21 @@ void PtySignalInputThread::_DoSetWindowParent(const SetParentData& data)
...
     if (FALSE == ReadFile(_hFile.get(), pBuffer, cbBuffer, &dwRead, nullptr))
     {
-        auto lastError = GetLastError();
-        if (lastError == ERROR_BROKEN_PIPE)
-        {
-            _Shutdown();
-        }
-        else
-        {
-            THROW_WIN32(lastError);
```
Comment (carlos-zamora) [inline src/host/PtySignalInputThread.cpp:289]: Regarding...
```cpp
        auto lastError = GetLastError();
        if (lastError == ERROR_BROKEN_PIPE)
        {
            _Shutdown();
        }
        else
        {
            THROW_WIN32(lastError);
        }
```
Looks like we never really handled the thrown error, right? So I guess it's fine that we removed it. But should we at least collect and log it?

File: src/host/PtySignalInputThread.hpp [hunk 12]
```diff
@@ -60,7 +60,7 @@ namespace Microsoft::Console
             uint64_t handle;
         };
 
-        [[nodiscard]] HRESULT _InputThread();
+        [[nodiscard]] HRESULT _InputThread() noexcept;
         bool _GetData(_Out_writes_bytes_(cbBuffer) void* const pBuffer, const DWORD cbBuffer);
```
Comment (carlos-zamora) [inline src/host/PtySignalInputThread.hpp:64]:
```suggestion
        [[nodiscard]] bool _GetData(_Out_writes_bytes_(cbBuffer) void* const pBuffer, const DWORD cbBuffer);
```
Looks like everybody explicitly handles `_GetData()`'s return val (which imo is much better). You could add the `nodiscard` attribute if you want.

File: src/host/PtySignalInputThread.cpp (hunk 5 above)
Comment (carlos-zamora) [reply src/host/PtySignalInputThread.cpp:212]: You could wrap the whole function in a `try` block and add a `CATCH_LOG_RETURN_HR(S_OK);` at the end. Then just keep the `default` case as a `THROW_HR(E_UNEXPECTED)`.

Looks a bit ugly, but it's true, the `default:` case is definitely unexpected.

**Review by carlos-zamora — APPROVED** [review]
The changes to each file make sense to me. Full disclosure, I don't get how the functions flow into each other though (like, the overall code flow). If you feel uncomfortable with that, definitely have @zadjii-msft take a look, I won't mind 😊.

Changes look good though and I agree it's an improvement. I added a few comments to add more logging, but that's up to you if you want to follow them.

**Review by DHowett — CHANGES_REQUESTED** [review]
aaa

**Comment by lhecker** [comment]
With @DHowett supplying me with a patched `KernelBase.dll` that includes the most recent `winconpty` changes to `ClosePseudoConsole` this PR has now underwent quite some testing rounds inside a Windows 11 VM.

The most recent commits contain a fix (fb14982) that caused Ctrl+C to not work in VS Code. This happened because `CloseConsoleProcessState()` now holds the console lock while calling `RundownAndExit`. That's problematic, because when `RundownAndExit` calls `TriggerTeardown()` on the `Renderer` it expects it to render the last frame of VT output on another thread, but it can't do that if the `RundownAndExit` thread is currently holding the console lock.

Furthermore I found a bug in WSL's usage of the pseudoconsole API, which is unpatchable on our side and is also reproducible on vanilla conhost/kernelbase build 25247:
* Run `wsl` inside conhost.
* Inside that run any Windows CLI application that prints 100MB or more of text in a single `WriteFile(stdout)` call. conhost will take multiple seconds to process that amount of data.
* While it prints the text, close the conhost window.
* --> both the Windows CLI application and the pseudoconsole conhost that WSL has spawned will deadlock until wsl shuts down.

From what I can tell, WSL is neither reading from, nor closing the output pipe conhost is writing VT/text to, while being stuck waiting on `ClosePseudoConsole`. `ClosePseudoConsole` won't ever return because it's waiting on `conhost` which is waiting to write into the output pipe that isn't being read from. This deadlock can only reliably be resolved on WSL's side, because while we could add timeouts to our writes, they'd be just a worst-case fallback if anything and the issue would still fundamentally exist. The correct solution is to either continue reading from the output pipe or closing it before calling `ClosePseudoConsole`. I'll get in touch with the WSL folks.

File: src/winconpty/winconpty.cpp [hunk 13]
```diff
@@ -230,6 +230,8 @@ HRESULT _CreatePseudoConsole(const HANDLE hToken,
     pPty->hConPtyProcess = pi.hProcess;
     pi.hProcess = nullptr;
 
+    // The hPtyReference we create here is used when the PROC_THREAD_ATTRIBUTE_PSEUDOCONSOLE attribute is processed.
```
Comment (DHowett) [inline src/winconpty/winconpty.cpp:233]: did we ever solve the issue where conpty looks like a client to conhost?

**Review by DHowett — APPROVED** [review]
