### PR TITLE
Fix VT mouse capture issues in Terminal and conhost

### LINKED ISSUE #6401: [VT Mouse Mode] Release is not fired when a drag begins inside and exits the terminal window
# Environment

```none
Windows build number: 10.0.18363.836
WSL profile
```

# Steps to reproduce

Use WSL profile, enable the mouse tracking mode `SGR (1006)`: 
```cmd
echo -e '\e[?1003;1006h'
```

If you press the mouse button in the terminal window and move the cursor outside the window and release the button there, the application running in the terminal does not receive a message that the button has been released.

When the mouse tracking mode is on, while holding any mouse button and moving the cursor outside the window, the mouse tracking should not stop.

# Expected behavior

If the mouse button was pressed inside the terminal, then the message about releasing the mouse button should come even if the mouse cursor has moved outside the window.

# Actual behavior

А message about releasing the mouse button (and any tracking messages) does not come if the mouse cursor has moved outside the window.

### PR DESCRIPTION
**Pull request by DHowett**
This pull request fixes capture and event generation in VT mouse mode
for both conhost and terminal.

Fixes #6401.

[1/3] Terminal: clamp mouse events to the viewport, don't throw them away

 gnome-terminal (at least) sends mouse events whose x/y are at the
 extreme ends of the buffer when a drag starts inside the terminal and
 then exits it.

 We would previously discard any mouse events that exited the borders of
 the viewport. Now we will keep emitting events where X/Y=0/w/h.

[2/3] conhost: clamp VT mouse to viewport, capture pointer

 This is the same as (1), but for conhost. conhost wasn't already
 capturing the pointer when VT mouse mode was in use. By capturing, we
 ensure that events that happen outside the screen still result in events
 sent to an application (like a release after a drag)

[3/3] wpf: capture the pointer when VT mouse is enabled

 This is the same as (2), but for the WPF control. Clamping is handled
 in TerminalCore in (1), so we didn't need to do it in WPF.

### CODE REVIEW

**Comment by DHowett** [comment]
wiffed it with the name. fixed.

**Comment by DHowett** [comment]
Tagged @miniksa in because it touches the conhost wndproc

File: src/cascadia/TerminalCore/Terminal.cpp [hunk 1]
```diff
@@ -486,14 +486,11 @@ bool Terminal::SendKeyEvent(const WORD vkey,
...
 {
-    // viewportPos must be within the dimensions of the viewport
-    const auto viewportDimensions = _mutableViewport.Dimensions();
-    if (viewportPos.X < 0 || viewportPos.X >= viewportDimensions.X || viewportPos.Y < 0 || viewportPos.Y >= viewportDimensions.Y)
-    {
-        return false;
-    }
-
-    return _terminalInput->HandleMouse(viewportPos, uiButton, GET_KEYSTATE_WPARAM(states.Value()), wheelDelta);
+    // viewportPos must be clamped to the dimensions of the viewport
```
Comment (miniksa) [inline src/cascadia/TerminalCore/Terminal.cpp:489]: Why. Why clamped? Would be nice for a future editor to know the brief reason why clamping is goodness.

File: src/interactivity/win32/windowio.cpp [hunk 2]
```diff
@@ -635,6 +638,20 @@ BOOL HandleMouseEvent(const SCREEN_INFORMATION& ScreenInfo,
 
         if (HandleTerminalMouseEvent(MousePosition, Message, GET_KEYSTATE_WPARAM(wParam), sDelta))
         {
```
Comment (DHowett) [inline src/interactivity/win32/windowio.cpp:640]:
```suggestion
        {
			// Capturing the mouse here ensures that we get events (drag/release)
			// even if the user drags outside the window.
```

File: src/interactivity/win32/windowio.cpp [hunk 3]
```diff
@@ -123,7 +123,10 @@ bool HandleTerminalMouseEvent(const COORD cMousePosition,
     // Virtual terminal input mode
     if (IsInVirtualTerminalInputMode())
     {
-        fWasHandled = gci.GetActiveInputBuffer()->GetTerminalInput().HandleMouse(cMousePosition, uiButton, sModifierKeystate, sWheelDelta);
+        auto clampedPosition{ cMousePosition };
```
Comment (miniksa) [inline src/interactivity/win32/windowio.cpp:126]: Same here. What's the reason to clamp before a future maintainer get the bright idea to change it again.

Comment (DHowett) [inline src/interactivity/win32/windowio.cpp:126]:
```suggestion
		// Events outside the viewport should be clamped to within the viewport
		// to match other terminal emulators.
        auto clampedPosition{ cMousePosition };
```

File: src/interactivity/win32/windowio.cpp [hunk 4]
```diff
@@ -635,6 +638,20 @@ BOOL HandleMouseEvent(const SCREEN_INFORMATION& ScreenInfo,
 
         if (HandleTerminalMouseEvent(MousePosition, Message, GET_KEYSTATE_WPARAM(wParam), sDelta))
         {
+            switch (Message)
```
Comment (miniksa) [inline src/interactivity/win32/windowio.cpp:641]: I'd be inclined also to leave a quick comment here about why capturing is great in VT mode like what sorts of applications it enables or what broken behaviors result if we don't do it. (And maybe that it only happens in VT mode BECAUSE the `HandleTerminalMouseEvent` call should return `false` outside VT mode... codifying the assumption here.)

File: src/cascadia/TerminalCore/Terminal.cpp (hunk 1 above)
Comment (DHowett) [inline src/cascadia/TerminalCore/Terminal.cpp:489]:
```suggestion
    // GH#6401: VT applications should be able to receive mouse events from outside the
    // terminal buffer. This is likely to happen when the user drags the cursor offscreen.
    // We shouldn't throw away perfectly good events when they're offscreen, so we just
    // clamp them to be within the range [(0, 0), (W, H)].
```

File: src/interactivity/win32/windowio.cpp [hunk 5]
```diff
@@ -123,7 +123,12 @@ bool HandleTerminalMouseEvent(const COORD cMousePosition,
     // Virtual terminal input mode
     if (IsInVirtualTerminalInputMode())
     {
-        fWasHandled = gci.GetActiveInputBuffer()->GetTerminalInput().HandleMouse(cMousePosition, uiButton, sModifierKeystate, sWheelDelta);
+        // Events outside the viewport should be clamped to within the viewport
+        // to match other terminal emulators (GH#6401)
```
Comment (DHowett) [inline src/interactivity/win32/windowio.cpp:127]:
```suggestion
        // GH#6401: VT applications should be able to receive mouse events from outside the
        // terminal buffer. This is likely to happen when the user drags the cursor offscreen.
        // We shouldn't throw away perfectly good events when they're offscreen, so we just
        // clamp them to be within the range [(0, 0), (W, H)].
```

File: src/interactivity/win32/windowio.cpp [hunk 6]
```diff
@@ -635,6 +640,22 @@ BOOL HandleMouseEvent(const SCREEN_INFORMATION& ScreenInfo,
 
         if (HandleTerminalMouseEvent(MousePosition, Message, GET_KEYSTATE_WPARAM(wParam), sDelta))
         {
+            // Capturing the mouse here ensures that we get events (drag/release)
+            // even if the user drags outside the window (GH#6401)
```
Comment (DHowett) [inline src/interactivity/win32/windowio.cpp:644]:
```suggestion
            // GH#6401: Capturing the mouse ensures that we get drag/release events
            // even if the user moves outside the window.
            // HandleTerminalMouseEvent returns false if the terminal's not in VT mode,
            // so capturing/releasing here should not impact other console mouse event
            // consumers.
```

**Comment by DHowett** [comment]
@msftbot merge this in 9 minutes

**Comment by miniksa** [comment]
Looks good to me with wpf control and comments.

**Comment by DHowett** [comment]
@msftbot merge this in 1 minutes
