### PR TITLE
Escape HTML entities

### LINKED ISSUE #2738: copied text does not include sufficient/correct HTML entity escaping
# Environment

```none
Windows build number: 10.0.18362.356
Windows Terminal version (if applicable): 0.4.2382.0
Copy-on-select is enabled (I doubt it matters)
```

# Steps to reproduce
Select some text in the terminal containing a `<` character. Right-click to copy it if needed.

For example:
image

# Expected behavior
Text is copied to the clipboard as both plain text and valid HTML.

# Actual behavior
Pasting into notepad pastes the full selected plain text.
Pasting into an HTML-capable app (in this case the mail client) shows that entity-escaping hasn't been done correctly:
image

### PR DESCRIPTION
**Pull request by mcpiroman**
## Summary of the Pull Request

Since MS Word apparently just got support for HTML entities, we can now properly escape them.

 
## References
I omitted this in #2038 since Word didn't support them

## PR Checklist
* [X] Closes #2738
* [X] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Requires documentation to be updated
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

### CODE REVIEW

File: src/buffer/out/textBuffer.cpp [hunk 1]
```diff
@@ -1150,9 +1150,25 @@ std::string TextBuffer::GenHTML(const TextAndColor& rows, const int fontHeightPo
...
+                                htmlBuilder << "&lt;";
+                                break;
+                            case '>':
+                                htmlBuilder << "&gt;";
+                                break;
+                            case '&':
+                                htmlBuilder << "&amp;";
+                                break;
+                            default:
+                                htmlBuilder << ConvertToA(CP_UTF8, std::wstring_view(&c, 1));
```
Comment (DHowett-MSFT) [inline src/buffer/out/textBuffer.cpp]: This seems like it might split up surrogate pairs. Is there a version of this algorithm that could be used on spans of text up-to-but-excluding-`<>&` instead of going wchar_t by wchar_t?

Comment (mcpiroman) [reply src/buffer/out/textBuffer.cpp]: Ah yes, you're right. Imma rework that

File: src/buffer/out/textBuffer.cpp [hunk 2]
```diff
@@ -1165,7 +1165,7 @@ std::string TextBuffer::GenHTML(const TextAndColor& rows, const int fontHeightPo
                                 htmlBuilder << "&amp;";
                                 break;
                             default:
-                                htmlBuilder << ConvertToA(CP_UTF8, std::wstring_view(&c, 1));
+                                htmlBuilder << c;
```
Comment (DHowett-MSFT) [inline src/buffer/out/textBuffer.cpp]: I'm still concerned about the cost of doing this character-by-character. I'd let everyone else on the team override me, though :smile:

Comment (zadjii-msft) [reply src/buffer/out/textBuffer.cpp]: If I'm putting my Austin hat on, I'd say that there's certainly a `std` function that could be used here to just replace all these somehow. Maybe `std::replace` or `std::transform`?

That being said, I'm also a [third tribe](https://josephg.com/blog/3-tribes/) kinda guy and I think this is good enough. Someone else can choose to block this though, because yes we _should_ do things better. I just don't think this is a hot enough path to care ATM

**Comment by mcpiroman** [comment]
@zadjii-msft 
Actually the only function from std that would make this code shorter is `regex_replace`, but I measured it to be about 10 times slower than this approach.

@DHowett-MSFT 
The cumulative (non char-by-char) approach is about 10% faster (for strings, see below) but somewhat more complicated. Choose your tradeoff :)

So actually, it looks like `std::ostringstream` doesn't perform preallocation, so frequent  writes are slower than with `std::string` and `append()`, up to 10 times for char-by-char append. Would you know? 
So I quess we could leave it as is for now and eventually replace `std::ostringstream` (everywhere) with some wrapper that does preallocation, when we get into optimization stage.

**Comment by DHowett-MSFT** [comment]
I'm alright with this as-is, honestly. :smile: Thanks

File: src/buffer/out/textBuffer.cpp (hunk 2 above)
Comment (miniksa) [reply src/buffer/out/textBuffer.cpp]: Honestly I think using std::replace or something like that is likely to introduce more intermediates and be of worse performance given that a single character is expanding into multiple in most of these situations.

Also, I do agree. This is a user-generated infrequent action, so I don't really care about premature optimization here. This makes sense as is and is easy to understand. I'm OK with it until a perf trace proves otherwise.
