### PR TITLE
Represent inheritance in Settings UI

### LINKED ISSUE #8804: Represent Inheritance in Settings UI
**Original issues name**: Base layer is ignored when profile setting is deleted in SUI

The following bug report is a particular example of inheritance not being represented properly in the Settings UI. In order to fix this, #8269 needs to be implemented.

# Environment

```none
Windows build number: 10.0.21286.0
Windows Terminal version (if applicable): 1.6.10101.0

Any other software?
```

# Steps to reproduce

Apply a setting in Base layer, then remove the same setting from a specific profile. For example, set the Base layer font face to Cascadia Code and remove Cascadia Code PL from the font face section of PowerShell.

Note that I didn't test other settings with Base layer, so this may be the only one I'm not entirely sure.

# Expected behavior

PowerShell should use Cascadia Code because it's defined in Base layer.

# Actual behavior

Terminal shows an error saying `"" is not a font face, using Consolas instead.` and Cascadia Code is ignored from the Base layer.

image

### PR DESCRIPTION
**Pull request by carlos-zamora**
## Summary of the Pull Request
Introduces the `SettingContainer`. `SettingContainer` is used to wrap a setting in the settings UI and provide the following functionality:
- a reset button next to the header
- tooltips and automation properties for the setting being wrapped
- a comment stating if you are currently overriding a setting

## References
[Spec - Inheritance in Settings UI](https://github.com/microsoft/terminal/blob/main/doc/specs/%231564%20-%20Settings%20UI/cascading-settings.md)
#8804 - removes the ambiguity of leaving a setting blank
#6800 - Settings UI Epic
#8899 - Automation properties for Settings UI
#8768 - Keyboard Navigation

## PR Checklist
* [X] Closes #8804

## Detailed Description of the Pull Request / Additional comments
A few highlights in this PR:
- CommonResources.xaml:
  - we need to merge the SettingContainerStyle.xaml in there. Otherwise, XAML doesn't merge these files properly and can't apply the template.
- Profiles.cpp:
  - view model checks if the starting directory and background image were reset, to determine which value to show when unchecking the special value
  - `Profiles::OnNavigatedTo()` needs a property changed handler to update its own "Current<Setting>" and update the UI properly
- Profiles.xaml:
  - basically wrapped all of the settings we want to be inheritable in there
  - `Binding` is used instead of `x:Bind` in some places because `x:Bind` can't find the parent `SettingContainer` and gives you a compiler error.
- Resources.resw:
  - had to set the "HeaderText" and "HelpText" on each setting container. Does a decent localization burden, unfortunately.
- `SettingContainer` files
  - This operates by creating a template and applying that template over other settings. This allows you to inject the existing controls inside of this. This means that we need to provide our UIElements names and access/modify them via `OnApplyTemplate`
  - We had to remove the header from each individual control, and have `SettingContainer` be in charge of it. This allows us to add the reset button in there.
  - Due to the problem mentioned earlier about CommonResources.xaml, we can't reference anything from CommonResources.xaml.
  - Using `DependencyProperty` to let us set a few properties in the XML files. Particularly, `Has<Setting>` and `Clear<Setting>` are what do all the heavy lifting of interacting with the inheritance model.

## Demo
Inheritance Demo

## Validation Steps Performed
- Verified correct binding behavior with the following generic setting controls:
  - radio buttons
  - toggle switch
  - text block
  - slider
  - settings with browse buttons
  - the background image alignment control
  - controls with special check boxes (starting directory and background image)

## Next Steps
- The automation properties have been verified using NVDA. This is a part of resolving #8899.
- The override text is currently "Overrides a setting". According to #8269, we actually want to add a hyperlink in there that navigates to the parent profile object. This will be a follow-up task as it requires settings model changes.

### CODE REVIEW

File: src/cascadia/TerminalSettingsEditor/Profiles.cpp [hunk 1]
```diff
@@ -248,6 +245,59 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
             StartingDirectoryUseParentCheckbox().IsChecked(true);
         }
 
+        // Subscribe to some changes in the view model
+        // These changes should force us to update our own set of "Current<Setting>" members,
+        // and propagate those changes to the UI
+        _State.Profile().PropertyChanged([&](auto&&, const PropertyChangedEventArgs& args) {
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/Profiles.cpp:251]: **NEVER CAPTURE `this` BY REFERENCE** you will absolutely crash :smile:

Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/Profiles.cpp:251]: you will want a revoker, otherwise the profile will get more and more and more event handlers for PropertyChanged accumulating on it as you navigate to and away from the page.

File: src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw [hunk 2]
```diff
@@ -329,25 +329,25 @@
...
   </data>
-  <data name="Profile_AcrylicOpacity.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip" xml:space="preserve">
+  <data name="Profile_AcrylicOpacity.HelpText" xml:space="preserve">
     <value>Sets the transparency of the window.</value>
   </data>
   <data name="Profile_Advanced.Header" xml:space="preserve">
     <value>Advanced</value>
   </data>
-  <data name="Profile_AltGrAliasing.Header" xml:space="preserve">
+  <data name="Profile_AltGrAliasing.HeaderText" xml:space="preserve">
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw:341]: It seems like you could save a HUGE loc burden by just making the dependencyproperty `Header`, right? Just... same key, same resource, bind it into the template.

File: src/cascadia/TerminalSettingsEditor/SettingContainer.cpp [hunk 3]
```diff
@@ -0,0 +1,111 @@
...
+            xaml_typename<hstring>(),
+            xaml_typename<Editor::SettingContainer>(),
+            PropertyMetadata{ nullptr });
+
+    DependencyProperty SettingContainer::_HelpTextProperty =
+        DependencyProperty::Register(
+            L"HelpText",
+            xaml_typename<hstring>(),
+            xaml_typename<Editor::SettingContainer>(),
+            PropertyMetadata{ box_value(L"") });
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/SettingContainer.cpp:25]: technically these are static initializers, and I am loathe to allow them. Can we find a way to not initialize them on library load?

File: src/cascadia/TerminalSettingsEditor/SettingContainer.cpp [hunk 4]
```diff
@@ -0,0 +1,111 @@
...
+                elem.Visibility(newVal ? Visibility::Visible : Visibility::Collapsed);
+            }
+        }
+
+        // update visibility for override message
+        if (auto overrideMsg{ obj.GetTemplateChild(L"OverrideMessage") })
+        {
+            if (auto elem{ overrideMsg.try_as<UIElement>() })
+            {
+                elem.Visibility(newVal ? Visibility::Visible : Visibility::Collapsed);
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/SettingContainer.cpp:53]: can you not bind these to `{TemplateBinding HasSettingValue}` inside the template?

File: src/cascadia/TerminalSettingsEditor/SettingContainer.cpp [hunk 5]
```diff
@@ -0,0 +1,111 @@
...
+    {
+        if (auto child{ GetTemplateChild(L"ResetButton") })
+        {
+            if (auto button{ child.try_as<Controls::Button>() })
+            {
+                // Apply click handler for the reset button.
+                // When clicked, we dispatch the bound ClearSettingValue event,
+                // resulting in inheriting the setting value from the parent.
+                button.Click([weakThis{ get_weak() }](auto&&, auto&&) {
+                    if (auto container{ weakThis.get() })
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/SettingContainer.cpp:68]: no need for weak references here. this control will exist and receive button clicks, or it will not exist _and_ not receive button clicks.

File: src/cascadia/TerminalSettingsEditor/SettingContainerStyle.xaml [hunk 6]
```diff
@@ -0,0 +1,72 @@
...
+                                    Style="{StaticResource SettingContainerResetButtonStyle}">
+
+                                <Button.Content>
+                                    <FontIcon Glyph="&#xE845;"
+                                              Style="{StaticResource SettingContainerFontIconStyle}"/>
+                                </Button.Content>
+
+                                <Button.Background>
+                                    <SolidColorBrush Opacity="0"/>
+                                </Button.Background>
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/SettingContainerStyle.xaml:53]: this seems more complicated than `Background="Transparent"`. Does it have to be?

**Review by DHowett — CHANGES_REQUESTED** [review]
did a first pass, will come back again

File: src/cascadia/TerminalSettingsEditor/Profiles.xaml [hunk 7]
```diff
@@ -206,384 +221,399 @@ the MIT License. See LICENSE in the project root for license information. -->
...
+                            </local:SettingContainer>
 
                             <!--Cursor Height-->
-                            <ContentPresenter Style="{StaticResource SettingContainerStyle}"
-                                              Visibility="{x:Bind IsVintageCursor, Mode=OneWay}">
-                                <muxc:NumberBox x:Uid="Profile_CursorHeight"
-                                                Value="{x:Bind State.Profile.CursorHeight, Mode=TwoWay}"
+                            <local:SettingContainer x:Uid="Profile_CursorHeight"
+                                                    HasSettingValue="{x:Bind State.Profile.HasCursorShape, Mode=OneWay}"
+                                                    ClearSettingValue="{x:Bind State.Profile.ClearCursorShape}"
```
Comment (carlos-zamora) [inline src/cascadia/TerminalSettingsEditor/Profiles.xaml:323]:
```suggestion
                                                    HasSettingValue="{x:Bind State.Profile.HasCursorHeight, Mode=OneWay}"
                                                    ClearSettingValue="{x:Bind State.Profile.ClearCursorHeight}"
```

File: src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw (hunk 2 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw:341]: Yeah. So this is dumb and annoying. The "Header" dependency property is apparently already in use (see below).
```
1>D:\Terminal\src\cascadia\TerminalSettingsEditor\Generated Files\XamlTypeInfo.g.cpp(493,44): error C2995: 'winrt::Windows::Foundation::IInspectable winrt::Microsoft::Terminal::Settings::Editor::implementation::GetReferenceTypeMember_Header(const winrt::Windows::Foundation::IInspectable &)': function template has already been defined
1>D:\Terminal\src\cascadia\TerminalSettingsEditor\Generated Files\XamlTypeInfo.g.cpp(463): message : see declaration of 'winrt::Microsoft::Terminal::Settings::Editor::implementation::GetReferenceTypeMember_Header'
1>D:\Terminal\src\cascadia\TerminalSettingsEditor\Generated Files\XamlTypeInfo.g.cpp(1387,6): error C2995: 'void winrt::Microsoft::Terminal::Settings::Editor::implementation::SetReferenceTypeMember_Header(const winrt::Windows::Foundation::IInspectable &,const winrt::Windows::Foundation::IInspectable &)': function template has already been defined
```
_But_ if we try and use "Header", we fail catastrophically:
- adding `TabTitle.Header` to the resw --> `'Unable to resolve property 'Header' while processing properties for Uid 'Profile_TabTitle'. [Line: 138 Position: 69]'`
- `Header()` does not exist in SettingContainer.cpp

File: src/cascadia/TerminalSettingsEditor/SettingContainerStyle.xaml (hunk 6 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/SettingContainerStyle.xaml:53]: Nice catch! Didn't even know that was an option!

File: src/cascadia/TerminalSettingsEditor/SettingContainer.cpp (hunk 4 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/SettingContainer.cpp:53]: This is another one that doesn't make sense to me. I tried just that, but the visibility is initialized to `Visible` regardless of `HasSettingValue` (even setting `HasSettingValue`'s default value to false results in no different behavior). Figured this might be an `OnApplyTemplate` thing that's getting in the way of initializing the value properly?

File: src/cascadia/TerminalSettingsEditor/Profiles.cpp (hunk 1 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/Profiles.cpp:251]: I'm really new to revokers so I'm leaving this as unresolved just to confirm that I did it right.
- Introduced `INotifyPropertyChanged::PropertyChanged_revoker _ViewModelChangedRevoker;`
- updated this line to be...
```cpp
_ViewModelChangedRevoker = _State.Profile().PropertyChanged(winrt::auto_revoke, [weakThis{ get_weak() }](auto&&, const PropertyChangedEventArgs& args) {
```
- Added this:
```cpp
void Profiles::OnNavigatedFrom(const NavigationEventArgs& e)
{
    _ViewModelChangedRevoker.revoke();
}
```

My thought process is, we don't actually construct a new page on navigation. So the `auto_revoke` is really only useful when we close SUI. On navigation, we update the revoker and set the property changed handler. When we navigate away, we should stop listening to these because they're now outdated.

Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/Profiles.cpp:251]: The revoke triggers when you close SUI (the page gets destructed) or when it gets overwritten in OnNvaigatedTo. It's a bonus to put it in OnNavigatedFrom. If you do that, please add the other revokers for other event handlers established on OnNavTo :wink:

File: src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw (hunk 2 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw:341]: Aha! Issue was that `Header` is an `IInspectable`. Fixed!

File: src/cascadia/TerminalSettingsEditor/Profiles.cpp (hunk 1 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/Profiles.cpp]: We just listen to the view model's property changed event so I think that's it?

File: src/cascadia/TerminalSettingsEditor/Profiles.cpp [hunk 8]
```diff
@@ -248,51 +248,54 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
         // Subscribe to some changes in the view model
         // These changes should force us to update our own set of "Current<Setting>" members,
         // and propagate those changes to the UI
-        _State.Profile().PropertyChanged([&](auto&&, const PropertyChangedEventArgs& args) {
-            if (args.PropertyName() == L"CursorShape")
+        _ViewModelChangedRevoker = _State.Profile().PropertyChanged(winrt::auto_revoke, [weakThis{ get_weak() }](auto&&, const PropertyChangedEventArgs& args) {
+            if (auto page{ weakThis.get() })
             {
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/Profiles.cpp]: no need for a weak capture here. the revoker ensures that either events are delivered to a living instance, or the registration is revoked

File: src/cascadia/TerminalSettingsEditor/Profiles.cpp [hunk 9]
```diff
@@ -248,10 +245,71 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
             StartingDirectoryUseParentCheckbox().IsChecked(true);
         }
 
+        // Subscribe to some changes in the view model
+        // These changes should force us to update our own set of "Current<Setting>" members,
+        // and propagate those changes to the UI
+        _ViewModelChangedRevoker = _State.Profile().PropertyChanged(winrt::auto_revoke, [weakThis{ get_weak() }](auto&&, const PropertyChangedEventArgs& args) {
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/Profiles.cpp:251]: Not sure if I was pointing at the right PR/commit, but: no need for the weak ref here. Revoker guarantees we'll be alive or that it will be unregistered.

Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/Profiles.cpp:251]: then you can drop `page->` off everything inside.

Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/Profiles.cpp:251]: just capture `this` by value

File: src/cascadia/TerminalSettingsEditor/Profiles.cpp [hunk 10]
```diff
@@ -248,10 +245,71 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
...
+                    page->_PropertyChangedHandlers(*page, PropertyChangedEventArgs{ L"CurrentScrollState" });
+                }
+                else if (args.PropertyName() == L"FontWeight")
+                {
+                    page->_PropertyChangedHandlers(*page, PropertyChangedEventArgs{ L"CurrentFontWeight" });
+                    page->_PropertyChangedHandlers(*page, PropertyChangedEventArgs{ L"IsCustomFontWeight" });
+                }
+                else if (args.PropertyName() == L"ColorSchemeName")
+                {
+                    page->_PropertyChangedHandlers(*page, PropertyChangedEventArgs{ L"CurrentColorScheme" });
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/Profiles.cpp:286]: oops, good catch on all of these `Current` guys

File: src/cascadia/TerminalSettingsEditor/Profiles.cpp [hunk 11]
```diff
@@ -248,10 +245,71 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
...
+                    // reset all of the buttons to unchecked.
+                    // set the one for the value we actually have.
+                    const auto alignment{ static_cast<int32_t>(page->_State.Profile().BackgroundImageAlignment()) };
+                    for (const auto& biButton : page->_BIAlignmentButtons)
+                    {
+                        if (const auto& biButtonAlignment{ biButton.Tag().try_as<int32_t>() })
+                        {
+                            biButton.IsChecked(biButtonAlignment == alignment);
+                        }
+                    }
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/Profiles.cpp:299]: is there a helper function for this? we do it in 2 places i think

File: src/cascadia/TerminalSettingsEditor/Profiles.cpp [hunk 12]
```diff
@@ -406,7 +464,7 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
 
     void Profiles::CursorShape_Changed(IInspectable const& /*sender*/, RoutedEventArgs const& /*e*/)
     {
-        _PropertyChangedHandlers(*this, Windows::UI::Xaml::Data::PropertyChangedEventArgs{ L"IsVintageCursor" });
+        _PropertyChangedHandlers(*this, PropertyChangedEventArgs{ L"IsVintageCursor" });
     }
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/Profiles.cpp:468]: ideally this would be hooked up to the CursorShape changing, _NOT_ the checkbox/optionbutton changing (!)

File: src/cascadia/TerminalSettingsEditor/Profiles.xaml [hunk 13]
```diff
@@ -59,41 +59,51 @@ the MIT License. See LICENSE in the project root for license information. -->
...
+                                                Visibility="{x:Bind State.Profile.IsBaseLayer, Mode=OneWay, Converter={StaticResource InvertedBooleanToVisibilityConverter}}"
+                                                Margin="0,0,0,24">
                             <StackPanel Orientation="Horizontal">
-                                <TextBox x:Uid="Profile_Commandline"
-                                         x:Name="Commandline"
+                                <TextBox x:Name="Commandline"
                                          Text="{x:Bind State.Profile.Commandline, Mode=TwoWay}"
+                                         AutomationProperties.Name="{Binding CommandlineContainer.Header}"
+                                         AutomationProperties.HelpText="{Binding CommandlineContainer.HelpText}"
                                          Style="{StaticResource TextBoxSettingStyle}"/>
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/Profiles.xaml:86]: This will be made unnecessary by the fixes in the SettingsContainer, right?

File: src/cascadia/TerminalSettingsEditor/SettingContainer.cpp (hunk 4 above)
Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/SettingContainer.cpp:53]: _hmm_.

File: src/cascadia/TerminalSettingsEditor/Profiles.cpp (hunk 11 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/Profiles.cpp:299]: We do a very similar thing in the other one (there we do `button == biButton` instead). I'll pull this out into a helper function though, you're right.

File: src/cascadia/TerminalSettingsEditor/Profiles.cpp (hunk 12 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/Profiles.cpp:468]: Actually... I'm glad you mentioned this. Now that we're subscribed to the cursor shape in the view model, we completely don't need this function. Removed.

File: src/cascadia/TerminalSettingsEditor/Profiles.xaml (hunk 13 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/Profiles.xaml:86]: Yup! Verified that it's no longer needed

**Comment by carlos-zamora** [comment]
Base layer is still a bit wonky. Polish in that area is coming up next.

**Comment by carlos-zamora** [comment]
> Base layer is still a bit wonky. Polish in that area is coming up next.

Base layer is treated no differently. Long-term, the idea is that "Overrides a setting" will be replaced with a link to the source. Base layer will say something like "Overrides default setting" and we'll link to a view of defaults.json in SUI.

File: src/cascadia/TerminalSettingsEditor/ViewModelHelpers.h [hunk 14]
```diff
@@ -48,7 +48,7 @@ public:                                                   \
         if (name() != value)                              \
         {                                                 \
             target.name(value);                           \
-            _NotifyChanges(L"Has" #name, L#name);         \
+            _NotifyChanges(L"Has" L#name, L#name);        \
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/ViewModelHelpers.h:51]: due to how the compiler stitches strings together, this is not a problem.

File: src/cascadia/TerminalSettingsEditor/ViewModelHelpers.h [hunk 15]
```diff
@@ -59,11 +59,11 @@ public:                                                   \
     _BASE_OBSERVABLE_PROJECTED_SETTING(target, name) \
     void Clear##name()                               \
     {                                                \
-        const auto hadValue{ target.Has##Name() };   \
+        const auto hadValue{ target.Has##name() };   \
         target.Clear##name();                        \
         if (hadValue)                                \
         {                                            \
-            _NotifyChanges(L"Has" #name, L#name);    \
+            _NotifyChanges(L"Has" L#name, L#name);   \
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/ViewModelHelpers.h:66]: as above

File: src/cascadia/TerminalSettingsEditor/ViewModelHelpers.h (hunk 14 above)
Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/ViewModelHelpers.h:51]: (why did this need to change?)

Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/ViewModelHelpers.h:51]: For whatever reason, Base Layer was not updating the UI when the SettingContainer reset button was clicked. I tracked the bug down to the macros (which was surprising, because the non-base layer profile pages worked just fine). Worked with @miniksa to figure out what was wrong with the macros and these changes fixed it. 🤷‍♂️

We think the missing 'L' might've improperly concatenated "Has" and \<name\>, and the notification that gets fired is silently ignored because nothing matches the garbled up "Has\<Name\>".

Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/ViewModelHelpers.h:51]: Hmm. That's definitely not it -- `L"X" "Y"` is identical to `L"XY"` and `L"X" L"Y"`

Comment (miniksa) [reply src/cascadia/TerminalSettingsEditor/ViewModelHelpers.h:51]: well then it was probably the other thing where you had a `#Name`, Carlos, that wasn't getting substituted properly and it got fixed changing it to `#name`?

Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/ViewModelHelpers.h:51]: Yeah I bet _that_ got substituted as `"Name"` (not expanding the macro!)

Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/ViewModelHelpers.h:51]: Why didn't that result in a compiler error though? That's where I'm confused.

Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/ViewModelHelpers.h:51]: In the C preprocessor's language, `#X` means "turn X into a string" (=> `"X"`). If X is a macro parameter, it is expanded. If it's not, the literal word just gets turned into a string.

Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/ViewModelHelpers.h:51]: OH. OH. IT WORKS BECAUSE profile _HAS_ a `HasName`. I was thinking about `#`, not `##`.

Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/ViewModelHelpers.h:51]: Omg, that makes so much sense! Alright, I'll revert the 'L' changes then.

Comment (miniksa) [reply src/cascadia/TerminalSettingsEditor/ViewModelHelpers.h:51]: To be clear, I had no idea why it wasn't working. I was literally just playing spot the difference between the macro you said was broken and the code you said was working.... :P

File: src/cascadia/TerminalControl/TermControl.xaml [hunk 16]
```diff
@@ -1,4 +1,6 @@
-﻿<UserControl
+﻿<!-- Copyright (c) Microsoft Corporation. All rights reserved. Licensed under
+the MIT License. See LICENSE in the project root for license information. -->
```
Comment (DHowett) [inline src/cascadia/TerminalControl/TermControl.xaml:2]: *nit*: unrelated changes make git blame annoying. I'm not asking you to change this now, but try to make sure your changesets are constrained (within reason. Obviously I also say "while you're here, fix this" sometimes. It's a blurry line.)

File: src/cascadia/TerminalSettingsEditor/Profiles.cpp [hunk 17]
```diff
@@ -248,10 +245,59 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
             StartingDirectoryUseParentCheckbox().IsChecked(true);
         }
 
+        // Subscribe to some changes in the view model
+        // These changes should force us to update our own set of "Current<Setting>" members,
+        // and propagate those changes to the UI
+        _ViewModelChangedRevoker = _State.Profile().PropertyChanged(winrt::auto_revoke, [=](auto&&, const PropertyChangedEventArgs& args) {
+            if (args.PropertyName() == L"CursorShape")
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/Profiles.cpp:252]: minor opportunity for optimization: pull the property name out into an auto-typed local. You can avoid making more and more calls through the projected interface to get it.

File: src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw [hunk 18]
```diff
@@ -838,4 +814,10 @@
   <data name="ColorScheme_RenameErrorTip.Title" xml:space="preserve">
     <value>This color scheme name is already in use.</value>
   </data>
-</root>
\ No newline at end of file
+  <data name="SettingContainer_OverrideIntro.Text" xml:space="preserve">
+    <value>Overrides a setting</value>
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw:818]:
```suggestion
    <value>This more-specific setting overrides a value from another profile.</value>
```

"Overrides a setting" is engineer-speak vagueness. Can we brainstorm something better?

You'll want to be careful. When we make this into a hyperlink, we are going to need to support the translator changing the location of the link (because it is the object of the sentence, or indirect object, or qualifier, or something (@miniksa will be able to tell me what part of speech "profile name" is in the sentence "This overrides a value in [profile name]").) within the sentence.

File: src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw [hunk 19]
```diff
@@ -838,4 +814,10 @@
   <data name="ColorScheme_RenameErrorTip.Title" xml:space="preserve">
     <value>This color scheme name is already in use.</value>
   </data>
-</root>
\ No newline at end of file
+  <data name="SettingContainer_OverrideIntro.Text" xml:space="preserve">
+    <value>Overrides a setting</value>
+  </data>
+  <data name="SettingContainer_ResetButtonHelpText" xml:space="preserve">
+    <value>Reset</value>
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw:821]: why is this a HelpText and not a `[using:blah blah blah]tooltip`?

File: src/cascadia/TerminalSettingsEditor/SettingContainerStyle.xaml [hunk 20]
```diff
@@ -0,0 +1,65 @@
...
+    <Style TargetType="local:SettingContainer">
+        <Setter Property="Margin" Value="0,24,0,0"/>
+        <Setter Property="Template">
+            <Setter.Value>
+                <ControlTemplate TargetType="local:SettingContainer">
+                    <StackPanel>
+
+                        <!--Header space-->
+                        <StackPanel Style="{StaticResource SettingContainerHeaderStyle}">
+                            <TextBlock Text="{TemplateBinding Header}"/>
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/SettingContainerStyle.xaml:43]: do we need to style this or set automation properties on it such that it reads as a header?

File: src/cascadia/TerminalSettingsEditor/SettingContainerStyle.xaml [hunk 21]
```diff
@@ -0,0 +1,65 @@
...
+                            <Button x:Name="ResetButton"
+                                    Style="{StaticResource SettingContainerResetButtonStyle}">
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/SettingContainerStyle.xaml:45]: oh I see, was it not possible to use an `x:Uid` here?

Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/SettingContainerStyle.xaml:45]: (re: the comment about `HelpText`)

File: src/cascadia/TerminalSettingsEditor/SettingContainerStyle.xaml (hunk 20 above)
Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/SettingContainerStyle.xaml:43]: actually yes how does this whole thing read to a screen reader?

File: src/cascadia/TerminalSettingsEditor/SettingContainer.cpp [hunk 22]
```diff
@@ -0,0 +1,114 @@
...
+            xaml_typename<hstring>(),
+            xaml_typename<Editor::SettingContainer>(),
+            PropertyMetadata{ box_value(L"") });
+
+    DependencyProperty SettingContainer::_HasSettingValueProperty =
+        DependencyProperty::Register(
+            L"HasSettingValue",
+            xaml_typename<bool>(),
+            xaml_typename<Editor::SettingContainer>(),
+            PropertyMetadata{ box_value(true), PropertyChangedCallback{ &SettingContainer::_OnHasSettingValueChanged } });
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/SettingContainer.cpp:32]: remember to somehow make these only initialize on the first construction of one of your objects. A It's expensive to run all this winrt code the moment the TSE library is loaded (which is when Terminal boots up :|)

File: src/cascadia/TerminalSettingsEditor/SettingContainer.cpp (hunk 4 above)
Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/SettingContainer.cpp:53]: Still surprised by this. I'm gonna check out your branch and have a look-see. :smile:

File: src/cascadia/TerminalSettingsEditor/SettingContainer.cpp [hunk 23]
```diff
@@ -0,0 +1,114 @@
...
+                    }
+                }
+
+                // apply help text as tooltip and help text (automation property)
+                const auto& helpText{ HelpText() };
+                if (!helpText.empty())
+                {
+                    Controls::ToolTipService::SetToolTip(obj, box_value(helpText));
+                    Automation::AutomationProperties::SetHelpText(obj, helpText);
+                }
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/SettingContainer.cpp:110]: surprised you couldn't do some binding work to make this happen actually. You should be able to `{TemplateBinding HelpText}` inside the xaml file. Don't block on this. Just curious.

Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/SettingContainer.cpp:110]: Same for `{TemplateBinding Header}` on automation property

File: src/cascadia/TerminalSettingsEditor/Profiles.xaml [hunk 24]
```diff
@@ -59,41 +59,47 @@ the MIT License. See LICENSE in the project root for license information. -->
...
                 <ScrollViewer>
                     <StackPanel Style="{StaticResource PivotStackStyle}">
-                        
+
                         <!--Name-->
                         <ContentPresenter Visibility="{x:Bind State.Profile.IsBaseLayer, Mode=OneWay, Converter={StaticResource InvertedBooleanToVisibilityConverter}}"
                                           Style="{StaticResource SettingContainerStyle}"
                                           Margin="0,0,0,24">
                             <TextBox x:Uid="Profile_Name"
+                                     x:Name="ProfileName"
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/Profiles.xaml:68]: why?

Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/Profiles.xaml:68]: oh, it's bound below. I don't like this.

You're working around the helptext not working by adding a binding to the special magical tooltip that's injected by SettingContainer. That feels _all sorts of weird_ (because nobody sets tooltip, so you just kinda depend on invisible behavior)

File: src/cascadia/TerminalSettingsEditor/Profiles.xaml [hunk 25]
```diff
@@ -104,28 +110,31 @@ the MIT License. See LICENSE in the project root for license information. -->
                                       x:Name="StartingDirectoryUseParentCheckbox"
                                       IsChecked="{x:Bind State.Profile.UseParentProcessDirectory, Mode=TwoWay}"/>
                             </StackPanel>
-                        </ContentPresenter>
+                        </local:SettingContainer>
 
                         <!--Icon-->
-                        <ContentPresenter Style="{StaticResource SettingContainerStyle}">
+                        <local:SettingContainer x:Uid="Profile_Icon"
+                                                x:Name="IconContainer"
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/Profiles.xaml:117]: IconContainer doesn't seem to be used

File: src/cascadia/TerminalSettingsEditor/Profiles.xaml [hunk 26]
```diff
@@ -104,28 +110,31 @@ the MIT License. See LICENSE in the project root for license information. -->
...
                         <!--Icon-->
-                        <ContentPresenter Style="{StaticResource SettingContainerStyle}">
+                        <local:SettingContainer x:Uid="Profile_Icon"
+                                                x:Name="IconContainer"
+                                                HasSettingValue="{x:Bind State.Profile.HasIcon, Mode=OneWay}"
+                                                ClearSettingValue="{x:Bind State.Profile.ClearIcon}">
                             <StackPanel Orientation="Horizontal">
-                                <TextBox x:Uid="Profile_Icon"
-                                         x:Name="Icon"
+                                <TextBox x:Name="Icon"
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/Profiles.xaml:121]: does this need to be named any more?

Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/Profiles.xaml:121]: oh, no, we got rid of the need to name things w/ browse buttons by having a good viewmodel

File: src/cascadia/TerminalSettingsEditor/Profiles.cpp [hunk 27]
```diff
@@ -248,10 +245,59 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
...
+                _PropertyChangedHandlers(*this, PropertyChangedEventArgs{ L"CurrentFontWeight" });
+                _PropertyChangedHandlers(*this, PropertyChangedEventArgs{ L"IsCustomFontWeight" });
+            }
+            else if (args.PropertyName() == L"ColorSchemeName")
+            {
+                _PropertyChangedHandlers(*this, PropertyChangedEventArgs{ L"CurrentColorScheme" });
+            }
+            else if (args.PropertyName() == L"BackgroundImageAlignment")
+            {
+                _UpdateBIAlignmentControl(static_cast<int32_t>(_State.Profile().BackgroundImageAlignment()));
```
Comment (zadjii-msft) [inline src/cascadia/TerminalSettingsEditor/Profiles.cpp:288]: This one's weird that it's not a `_PropertyChangedHandlers`, but okay

File: src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw (hunk 19 above)
Comment (zadjii-msft) [reply src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw:821]: Does this need to be a `.HelpText`?

File: src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw [hunk 28]
```diff
@@ -578,19 +560,13 @@
   <data name="Profile_ScrollbarVisibilityVisible.Content" xml:space="preserve">
     <value>Visible</value>
   </data>
-  <data name="Profile_SelectionBackgroundColor.Header" xml:space="preserve">
-    <value>Selection background color</value>
-  </data>
-  <data name="Profile_SelectionBackgroundColorToolTip.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip" xml:space="preserve">
-    <value>Sets the background color of selected text. Overrides the selection background set in the color scheme.</value>
-  </data>
```
Comment (zadjii-msft) [inline src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw:586]: Oh, were these three just not used at all (hence removing them?)

**Review by zadjii-msft — COMMENTED** [review]
Okay, I think I can wrap my head around this. I don't have anything that wasn't already called out, but there's enough other comments that I'll hold off approving till they're fixed.

File: src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw (hunk 28 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw:586]: Yeah, I wanted to ask about that actually. We weren't using them (because we cut a few settings) so I removed them. Found them while I was updating the resw file. But, we do plan on adding them back in at some point. I feel like the right move is to remove them but just want to double check.

File: src/cascadia/TerminalControl/TermControl.xaml (hunk 16 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalControl/TermControl.xaml:2]: Ok, I'll at least try to keep these within the same file in the future. Would that work?

File: src/cascadia/TerminalSettingsEditor/Profiles.cpp (hunk 17 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/Profiles.cpp:252]: Done. Did it in `ProfileViewModel`'s `PropertyChanged` handler too. Should I also pull out the strings into `static constexpr std::wstring_view`s? Like this:
```c++
static constexpr std::wstring_view CursorShapeKey{ L"CursorShape" };
static constexpr std::wstring_view CurrentCursorShapeKey{ L"CurrentCursorShape" };
static constexpr std::wstring_view IsVintageCursorKey{ L"IsVintageCursor" };
...
```

Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/Profiles.cpp:252]: Doing that is additional clutter for no real benefit :)

File: src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw (hunk 28 above)
Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw:586]: Since we have to break the loc keys, let's remove them. We _will_ probably want to bring them back eventually... but we can do it when we get there.

File: src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw (hunk 19 above)
Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw:821]: nah HelpText is a magic thing we made up.

File: src/cascadia/TerminalControl/TermControl.xaml (hunk 16 above)
Comment (DHowett) [reply src/cascadia/TerminalControl/TermControl.xaml:2]: I'd say... if you don't need to change files in a project, leave that project alone. When I generate changelogs for individual components, I will often do a `git log src/cascadia/WhateverComponent`, right? This would show me, when I do "git log TerminalCOntrol", that it changed to "represent inheritance in the settings UI". The cognitive load is higher for that, since I need to figure out why the TC had to change. Oh, it was just a copyright. _hrm._

File: src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw (hunk 19 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw:821]: "HelpText" was just the name I happened to use here. No relationship to the `HelpText` property.

Going back to today's episode of "Carlos' issues with data binding", this is another case of that. I want to create one resw entry that can be used as the tooltip and the automation property for this button simultaneously.

I tried this (after setting the resw entry to `SettingContainer_ResetButton.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip`):
```xml
<Button x:Uid="SettingContainer_ResetButton"
		x:Name="ResetButton"
        Style="{StaticResource SettingContainerResetButtonStyle}"
        AutomationProperties.Name="{Binding RelativeSource={RelativeSource Self}, Path=ToolTip, Mode=OneWay}">
```

The tooltip is set properly, but the automation property is not.

Figured it'd be more straightforward to do this in the code like this:
```cpp
// SettingContainer.cpp --> OnApplyTemplate()

if (auto child{ GetTemplateChild(L"ResetButton") })
{
	// apply tooltip and name (automation property)
	const auto& helpText{ RS_(L"SettingContainer_ResetButtonHelpText") };
	Controls::ToolTipService::SetToolTip(child, box_value(helpText));
	Automation::AutomationProperties::SetName(child, helpText);
}
```

File: src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw (hunk 18 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw:818]: > "Overrides a setting" is engineer-speak vagueness. Can we brainstorm something better?
Summoning @cinnamon-msft for word-smithing.
The spec says "Overrides Base Layer" and I think we still would want this to be a fairly short string.

> You'll want to be careful. When we make this into a hyperlink, we are going to need to support the translator changing the location of the link

Good call. I'll have to use `fmt` and make it something like `Overrides {}` (comment: "{}" is the object being overridden (possibly a sentence)). Then for now, I'll just replace `{}` with "a setting" (localized) until hyperlinks come in.

File: src/cascadia/TerminalSettingsEditor/SettingContainerStyle.xaml (hunk 20 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/SettingContainerStyle.xaml:43]: For something like commandline, it reads:
"commandline grouping. Executable used in the profile. Edit. powershell.exe"
-->
"<Header> grouping. <HelpText>. Edit. <current setting value>."

I've verified this behavior across all of the profile settings. The only ones that don't work are the ones for radio buttons :(. Screen reader just reads the checked value.

File: src/cascadia/TerminalSettingsEditor/SettingContainerStyle.xaml (hunk 21 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/SettingContainerStyle.xaml:45]: Closing this thread in favor of the other one.

File: src/cascadia/TerminalSettingsEditor/Profiles.xaml (hunk 24 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/Profiles.xaml:68]: I'm gonna try and do this without adding an x:Name.

It's not too bad, though, right? Like, we're just making the automation properties bind to what we already have. And if we don't have anything, we don't set it to anything. This is a side effect of how tooltips are not accessible, unfortunately.

Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/Profiles.xaml:68]: Oh lovely, the current method doesn't work...
this doesn't work either:
```
AutomationProperties.HelpText="{Binding RelativeSource={RelativeSource Self}, Path=ToolTipService.ToolTip, Mode=OneWay}"
```

Why does this have to be unreasonably difficult? I can't find any documentation on binding one of my properties to another one of my own.

File: src/cascadia/TerminalSettingsEditor/Profiles.xaml (hunk 26 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/Profiles.xaml:121]: Huh, good catch. I'll take a look at the other browse button settings too.

File: src/cascadia/TerminalSettingsEditor/Profiles.xaml (hunk 24 above)
Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/Profiles.xaml:68]: I'd rather figure out the root cause. Why does SettingContainer _correctly_ set the tooltip, but it can't successfully set the automation help text? SettingContainer does both... so you shouldn't need to tell the textbox to set its own HelpText based on the ToolTip set by SettingContainer _because SettingContainer also sets the HelpText_

File: src/cascadia/TerminalSettingsEditor/SettingContainerStyle.xaml (hunk 20 above)
Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/SettingContainerStyle.xaml:43]: OK what does it say when there's an override in effect??

File: src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw (hunk 18 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw:818]: Discussed offline with @cinnamon-msft. Going with:
```
This overrides the value in {}.
```
Temporarily replacing {} with "another layer" until the hyperlink functionality goes in.

Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw:818]: demo

Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw:818]: Make sure `another layer` is a separate string. Understand that if you want to make it an actual hyperlink, you will _need_ to parse the string at runtime to know where to break it to insert the link.

Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw:818]: It would be very fun to write a `fmt` adapter for `TextBlock` (!), but... not today

File: src/cascadia/TerminalSettingsEditor/SettingContainerStyle.xaml (hunk 20 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/SettingContainerStyle.xaml:43]: Oh, that didn't read it. Hmm...

File: src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw (hunk 18 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw:818]: demo 2

last minute change: "another layer" --> "a lower layer"

File: src/cascadia/TerminalSettingsEditor/Profiles.xaml (hunk 24 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/Profiles.xaml:68]: wait... I think your comment may be a bit in the wrong place here. `Name` isn't wrapped in a SettingContainer. SettingContainer is working properly in a separate discussion thread.

Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/Profiles.xaml:68]: You have a `Name`d textblock inside a settingcontainer, and it is `Name`d so that you can bind its `helptext` to its `tooltip`. I am asking you to figure out why you need to bind the `HelpText`, **which is otherwise set by `SettingContainer`**, to the `Tooltip` (**which is successfully set by the `SettingContainer`**). They're all connected. :smile:

Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/Profiles.xaml:68]: (So that you can delete the Name, without introducing a new binding)

Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/Profiles.xaml:68]: Offline discussion notes: Name wasn't wrapped in a `SettingContainer`. But, why not? So now I wrapped every setting in a `SettingContainer` but I don't pass in a value for `HasSetting`. This allows us to remove the stray `SettingContainerStyle` and clean up CommonResources.xaml a bit.

File: src/cascadia/TerminalSettingsEditor/SettingContainerStyle.xaml (hunk 20 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/SettingContainerStyle.xaml:43]: I'm checking with an a11y contact to see what the proper design here should be. If we can fix this, this would let us close out #8899.

File: src/cascadia/TerminalSettingsEditor/SettingContainer.cpp [hunk 29]
```diff
@@ -82,6 +104,11 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
         {
             if (auto tb{ child.try_as<Controls::TextBlock>() })
             {
+                // TODO GH#6800: 'OverrideTarget' will be replaced with hyperlink/text directing the user to another profile.
+                // Create the override message
+                const auto overrideMsg{ fmt::format(std::wstring{ RS_(L"SettingContainer_OverrideIntro") }, RS_(L"SettingContainer_OverrideTarget")) };
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/SettingContainer.cpp:109]:
```suggestion
                const auto overrideMsg{ fmt::format(std::wstring_view{ RS_(L"SettingContainer_OverrideIntro") }, RS_(L"SettingContainer_OverrideTarget")) };
```

no need to copy the string just as a format input

File: src/cascadia/TerminalSettingsEditor/Profiles.xaml [hunk 30]
```diff
@@ -137,17 +133,16 @@ the MIT License. See LICENSE in the project root for license information. -->
...
-                        <ContentPresenter Style="{StaticResource SettingContainerStyle}">
-                            <StackPanel Visibility="{x:Bind State.Profile.IsBaseLayer, Mode=OneWay, Converter={StaticResource InvertedBooleanToVisibilityConverter}}">
+                        <local:SettingContainer Visibility="{x:Bind State.Profile.IsBaseLayer, Mode=OneWay, Converter={StaticResource InvertedBooleanToVisibilityConverter}}">
+                            <StackPanel>
                                 <Button IsEnabled="{x:Bind State.Profile.CanDeleteProfile}"
-                                    Style="{StaticResource DeleteButtonStyle}">
+                                        Style="{StaticResource DeleteButtonStyle}">
                                     <Button.Resources>
                                         <ResourceDictionary>
                                             <ResourceDictionary.ThemeDictionaries>
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/Profiles.xaml:148]: this part is weird to me -- it's _not_ a setting.

Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/Profiles.xaml:148]: even if it were inheritable, it cannot be overridden or reset

File: src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw (hunk 19 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw:822]: Spoke with somebody from the accessibility team. Decided on this solution:
- Header (name of the setting) --> AutomationProperty::Name
- Override Message (overriddes what?) --> AutomationProperty::HelpText
- ToolTip (extra description to setting) --> AutomationProperty::DescriptionText

File: src/cascadia/TerminalSettingsEditor/SettingContainerStyle.xaml (hunk 20 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/SettingContainerStyle.xaml:43]: Spoke with somebody from the accessibility team. Decided on this solution:
- Header (name of the setting) --> AutomationProperty::Name
- Override Message (overriddes what?) --> AutomationProperty::HelpText
- ToolTip (extra description to setting) --> AutomationProperty::DescriptionText

File: src/cascadia/TerminalSettingsEditor/Profiles.xaml (hunk 30 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/Profiles.xaml:148]: Fair enough. Looks like we were just using this for the `StandardControlMargin`, so I added that in.

**Comment by carlos-zamora** [comment]
A large contribution to #8899 has happened (mostly automatically) in this PR. `SettingContainer` handles most of the setting of automation properties. I went ahead and added the ones for the background image alignment control and the checkboxes for starting directory and background image. They're a bit out of scope, so I stopped there. But this puts us in a position where all settings now have reasonable automation properties.

#8899 cannot be closed, however, because there's still some work to be done on non-setting ui elements (i.e. discard changes & save buttons, open json button, etc...). I _could_ do that here, but I feel that that's too out of scope for this PR.

**Comment by DHowett** [comment]
Leaving assigned to Carlos because of the discussion we had on Teams.

Summarized here:

1. I think that the if check for setting the automation help text will ensure that it _never gets cleared_ when override goes from off to on to off again.
2. use hstrings for GenerateOverrideThing

**Comment by carlos-zamora** [comment]
> 1. I think that the if check for setting the automation help text will ensure that it _never gets cleared_ when override goes from off to on to off again.

This is really annoying. I've tried various methods and the `AutomationProperty::HelpText` _does not_ update when I set it in `_OnHasSettingValueChanged`. I've tried...
- `AutomationProperties::SetHelpText` to the new value
- `peer.RaisePropertyChangedEvent(Automation::AutomationElementIdentifiers::HelpTextProperty(), box_value(oldVal), box_value(newVal));`

The code runs properly in both cases, but the automation client (i.e. screen reader) _refuses_ to acknowledge that the value changed (so frustrating!). I've decided to do the following approach instead:
- `Header` --> `Content.AP.Name`
- `HelpText` --> `Content.ToolTip` & `Content.AP.FullDescription`
- `OverrideMsg` --> `ResetButton.AP.HelpText`

I've also investigated a bit of what's going to happen when we add a hyperlink in the override message. For whatever reason, hyperlinks do not provide any automation properties automatically. So the user would tab to the hyperlink, and not be read anything. I think the right move there would be to keep the proposed design above, and add the following auto props to the hyperlink:
- `AP.Name` --> \<the text that is hyperlinked (e.g. "base layer")\>
- `AP.HelpText` --> "Navigate to \<AP.Name (e.g. "base layer")\>"

I feel like that'll still be somewhat intuitive. And the reset button is described such that the user is in the context of overriding a setting.

File: src/cascadia/TerminalSettingsEditor/SettingContainer.cpp [hunk 31]
```diff
@@ -98,12 +91,35 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
...
+                            {
+                                if (auto panelControl{ panelChild.try_as<Controls::Control>() })
+                                {
+                                    panelControl.Focus(FocusState::Programmatic);
+                                    return;
+                                }
+                            }
+                        }
+                        // if we get here, we didn't find something to reasonably focus to.
+                    }
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/SettingContainer.cpp:115]: `const auto&` all this stuff

Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/SettingContainer.cpp:115]: Should I do it on the `GetTemplateChild` calls too?

Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/SettingContainer.cpp:115]: might as well

File: src/cascadia/TerminalSettingsEditor/SettingContainer.cpp [hunk 32]
```diff
@@ -0,0 +1,184 @@
...
+                // initialize visibility for reset button
+                button.Visibility(HasSettingValue() ? Visibility::Visible : Visibility::Collapsed);
+            }
+        }
+
+        if (const auto& child{ GetTemplateChild(L"OverrideMessage") })
+        {
+            if (const auto& tb{ child.try_as<Controls::TextBlock>() })
+            {
+                const auto overrideMsg{ _GenerateOverrideMessageText() };
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/SettingContainer.cpp:133]: you already have one of these above (L83)

```suggestion
```

**Review by DHowett — APPROVED** [review]
This is an excellent piece of work. Well done. Just the one nit, then we can GO GO GO.

**Review by zadjii-msft — APPROVED** [review]
Sure lets do it
