### PR TITLE
Correct improper usage of THROW_IF_NULL_ALLOC

### LINKED ISSUE #4099: Convert THROW_IF_NULL_ALLOC for input parameters to return E_INVALIDARG not E_OUTOFMEMORY.
This isn't exactly correct, it'll result in a hresult exception `E_OUTOFMEMORY` or whatever. It's really more of an invalid parameter, but also it's more of a "we could avoid the throwing constructor completely" case?

_Originally posted by @DHowett-MSFT in https://github.com/microsoft/terminal/pull/4005_

I had said we should bulk do this all over the codebase.

### PR DESCRIPTION
**Pull request by skyline75489**
## Summary of the Pull Request

FIx incorrect usage of THROW_IF_NULL_ALLOC which will throw E_OUTOFMEMORY unintentionally.

 
## PR Checklist
* [X] Closes #4099
* [X] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA

## Validation Steps Performed

Build and run it.

### CODE REVIEW

File: src/host/screenInfo.cpp [hunk 1]
```diff
@@ -103,10 +103,10 @@ SCREEN_INFORMATION::~SCREEN_INFORMATION()
     try
     {
         IWindowMetrics* pMetrics = ServiceLocator::LocateWindowMetrics();
-        THROW_IF_NULL_ALLOC(pMetrics);
+        THROW_HR_IF_NULL(E_FAIL, pMetrics);
```
Comment (skyline75489) [inline src/host/screenInfo.cpp]: I don't think this should throw `E_INVALIDARG`. So I choose `E_FAIL`. Any advice?

File: src/renderer/dx/DxRenderer.cpp [hunk 2]
```diff
@@ -1735,7 +1735,7 @@ float DxEngine::GetScaling() const noexcept
         }
     }
 
-    THROW_IF_NULL_ALLOC(face);
+    THROW_HR_IF_NULL(E_FAIL, face);
```
Comment (skyline75489) [inline src/renderer/dx/DxRenderer.cpp]: Another `E_FAIL` here.

File: src/host/screenInfo.cpp (hunk 1 above)
Comment (zadjii-msft) [reply src/host/screenInfo.cpp]: That seems right to me

**Comment by DHowett-MSFT** [comment]
Thanks!

**Comment by DHowett-MSFT** [comment]
:tada: Once again, thanks for the contribution!

This pull request was included in a set of conhost changes that was just
released with [Windows Insider Build 19603](https://blogs.windows.com/windowsexperience/2020/04/08/announcing-windows-10-insider-preview-build-19603/).
