### PR TITLE
[a11y] Make CommandPalette announce selected item

### LINKED ISSUE #12065: [Terminal> Command palette]: Screen Reader is not announcing Suggestion name when user navigate to Command Palette suggestions using up/down arrow keys.
### Windows Terminal version

1.12.3472.0

### Windows build number

10.0.22504.1010

### Other Software

**Test Environment:**
OS: Windows 11 Version Dev (OS Build 22504.1010)
App: Windows Terminal Preview
Screen Reader: Narrator

### Steps to reproduce

**Repro Steps:**
1. Open Windows Terminal.
2. Open Settings page using 'Ctr+ Shift + p'.
3. Open Narrator using 'Win + Ctrl + Enter' keys.
4. Now press up/down arrow keys and observe the issues.

**User Experience:**
Screen Reader users UX will not be good as screen reader is not announcing suggestion while navigate to them.

**Guideline Reference:**
https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships

**Attachments:**
[Screen Reader is not announcing Suggestion name when user navigate to Command Palette suggestions using updown arrow keys..zip](https://github.com/microsoft/terminal/files/7787291/Screen.Reader.is.not.announcing.Suggestion.name.when.user.navigate.to.Command.Palette.suggestions.using.updown.arrow.keys.zip)

### Expected Behavior

Screen Reader should announce Suggestion name when user navigate to Command Palette suggestions using up/down arrow keys.

### Actual Behavior

Screen Reader is not announcing Suggestion name when user navigate to Command Palette suggestions using up/down arrow keys.

**Observation:** NVDA announce 'blank' and JAWS remain silent.

### PR DESCRIPTION
**Pull request by carlos-zamora**
## Summary of the Pull Request
The command palette (and tab search by extension) doesn't ever tell screen readers what is selected. Here, we simply hook up the selection changed event to a function that tells the screen reader what is selected. With this, the user no longer has to tab into the list view to know what is selected!

Will resolve the following bug upon validation from a11y team: #12065 

## Validation Steps Performed
Performed repro steps from #12065.

NOTE: we do NOT read the selected item when the command palette is first opened. I think that's ok.

### CODE REVIEW

**Comment by DHowett** [comment]
I'm a little concerned. How did we regress this? It was working, and I thought that a list view was supposed to automatically handle accessibility notifications when its selected item changed. Is that not true? Has this never worked?

Mini-RCA?

**Comment by carlos-zamora** [comment]
> I'm a little concerned. How did we regress this? It was working, and I thought that a list view was supposed to automatically handle accessibility notifications when its selected item changed. Is that not true? Has this never worked?
> 
> Mini-RCA?

Nah, this isn't a regression. It's just slightly different. The implementation we had was that we added `AutomationProperties` to the `ListViewItem` and that worked (and continues to work) correctly. A screen reader can point to the item and extract the text from it.

The difference here is _when_ that information gets extracted. The `AutomationProperties` made it so that you had to tab to the item to get the name/keys. So the workflow would look like this:
1. open cmd palette
2. tab to list of results
3. use up/down to move focus/selection to the desired item

But the command palette has an additional way to change the selection _without moving the focus_:
1. open cmd palette
2. use up/down to move selection to the desired item (but maintain focus in text box)

This PR enables support for that second scenario.

NOTE: since the experience is still accessible, the bug is marked as a Sev3 as opposed to a higher one.

**Review by zadjii-msft — APPROVED** [review]

**Comment by DHowett** [comment]
I don't know how I feel about this. Are we certain that the content that Narrator reads is identical to the one when you select a list item? What about "drilling in" for details -- can you get Narrator to read the Name and the Key Binding separately? What happens today in _keyboard focus_ if you do that? What about this new thing?

**Comment by DHowett** [comment]
Is there a better way to do this than say "narrator speak these words?" Is it possible to say, "narrator, speak this _control_"?

**Review by DHowett — CHANGES_REQUESTED** [review]
Red for questions

**Comment by carlos-zamora** [comment]
> I don't know how I feel about this. Are we certain that the content that Narrator reads is identical to the one when you select a list item?

Tested with Narrator/NVDA/JAWS: identical behavior to when you move focus onto a list item

> What about "drilling in" for details -- can you get Narrator to read the Name and the Key Binding separately? What happens today in _keyboard focus_ if you do that? What about this new thing?

After a bit of digging, I can't figure out a way to do this with Narrator or NVDA. I reached out to Bill and he said that NVDA just reads accelerator keys automatically; there's no way to do it on request, but he could write up a plug-in for it. It seems to be a common standard to just read the accelerator keys.

> Is there a better way to do this than say "narrator speak these words?" Is it possible to say, "narrator, speak this _control_"?

Hmm... I don't think there's a way to just hand over the control to Narrator. I don't think that's necessarily desired either though? The user has the ability to tab to the selected item then "drill in" if so desired. This notification is more intended to let the user know what the "enter" button will do if it's invoked.

**Comment by codeofdusk** [comment]
> I reached out to Bill and he said that NVDA just reads accelerator keys automatically; there's no way to do it on request

There is now, see PR nvaccess/nvda#13960 (available from 2022.4).

File: src/cascadia/TerminalApp/CommandPalette.cpp [hunk 1]
```diff
@@ -524,6 +524,34 @@ namespace winrt::TerminalApp::implementation
...
+            if (auto automationPeer{ Automation::Peers::FrameworkElementAutomationPeer::FromElement(_searchBox()) })
+            {
+                if (const auto selectedList = e.AddedItems(); selectedList.Size() > 0)
+                {
+                    const auto selectedCommand = selectedList.GetAt(0);
+                    if (const auto filteredCmd = selectedCommand.try_as<TerminalApp::FilteredCommand>())
+                    {
+                        if (const auto paletteItem = filteredCmd.Item().try_as<TerminalApp::PaletteItem>())
+                        {
+                            automationPeer.RaiseNotificationEvent(
```
Comment (DHowett) [inline src/cascadia/TerminalApp/CommandPalette.cpp:543]: okay, here's another annoying question!

How do we tell the user that the command they selected has nested commands? What is the audible version of the `>` symbol?

**Review by DHowett — APPROVED** [review]
This is an improvement for now!

File: src/cascadia/TerminalApp/CommandPalette.cpp (hunk 1 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalApp/CommandPalette.cpp:543]: Ah, you've stumbled upon #12041 haha.

The short version is that we have help text saying "More options", but depending on the screen reader, that may or may not be read automatically. Rahul seems to have commented on the thread with a way to fix the issue, so that's nice.

**Comment by carlos-zamora** [comment]
@msftbot merge this in 10 minutes
