### PR TITLE
Remove unneeded VT-specific control character handling

### LINKED ISSUE #3971: Backspacing a tab character in conpty causes visual corruption
# Environment

```none
Windows build number: 18362.476
Windows Terminal version (if applicable): 0.7.3451.0

Python 3.5>>> 3.8
```

# Steps to reproduce
Add to config file:
```none
{
            // Make changes here to the python.exe profile
            "guid": "{0cab0dad-35be-5f56-a8ff-afceeeaa6101}",
            "name": "Python",
            "commandline": "C:\\Program Files\\Python35\\python.exe",
            "hidden": false,
	    "backgroundImage": "C:\\Users\\noncyrilicusername\\Documents\\DDLC\\extract\\src\\images.rpa\\images\\cg\\credits\\1.png",
            "backgroundImageOpacity": 0.5,
	    "icon": "C:\\Program Files\\Python35\\icon.png"
        }
```

Launch new tab, try to write text, press Enter, press Up Arrow, try to edit
# Expected behavior
Normal text

# Actual behavior
image

### PR DESCRIPTION
**Pull request by j4james**
## Summary of the Pull Request

This PR removes all of the VT-specific functionality from the `WriteCharsLegacy` function that dealt with control characters, since those controls are now handled in the state machine when in VT mode. It also removes most of the control character handling from the `Terminal::_WriteBuffer` method for the same reason.

## References

This is a followup to PR #4171

## PR Checklist
* [x] Closes #3971
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Requires documentation to be updated
* [x] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: https://github.com/microsoft/terminal/issues/780#issuecomment-570287435

## Detailed Description of the Pull Request / Additional comments

There are four changes to the `WriteCharsLegacy` implementation:

1. The `TAB` character had special case handling in VT mode which is now no longer required. This fixes a bug in the Python REPL editor (when run from a cmd shell in Windows Terminal), which would prevent you tabbing past the end of the line. It also fixes #3971.

2. Following on from point 1, the `WC_NONDESTRUCTIVE_TAB` flag could also now be removed. It only ever applied in VT mode, in which case the `TAB` character isn't handled in `WriteCharsLegacy`, so there isn't a need for a non-destructive version.

3. There used to be special case handling for a `BS` character at the beginning of the line when in VT mode, and that is also no longer required. This fixes an edge-case bug which would prevent a glyph being output for code point 8 when `ENABLE_PROCESSED_OUTPUT` was disabled. 

4. There was quite a lot of special case handling for control characters in the "end-of-line wrap" implementation, which is no longer required. This fixes a bug which would prevent "low ASCII" characters from wrapping when output at the end of a line.

Then in the `Terminal::_WriteBuffer` implementation, I've simply removed all control character handling, except for `LF`. The Terminal is always in VT mode, so the control characters are always handled by the state machine. The exception for the `LF` character is simply because it doesn't have a proper implementation yet, so it still passes the character through to `_WriteBuffer`. That will get cleaned up eventually, but I thought that could wait for a later PR.

Finally, with the removal of the VT mode handling in `WriteCharsLegacy`, there was no longer a need for the `SCREEN_INFORMATION::InVTMode` method to be publicly accessible. That has now been made private.

## Validation Steps Performed

I've only tested manually, making sure the conhost and Windows Terminal still basically work, and confirming that the above-mentioned bugs are fixed by these changes.

### CODE REVIEW

**Comment by zadjii-msft** [comment]
@msftbot make sure @miniksa signs off on this

**Comment by miniksa** [comment]
I'll get to this on Tuesday probably. We have Monday off and I'm watching the NFC game right now like @zadjii-msft should be given the Packers are still in it. :P

**Comment by zadjii-msft** [comment]
Ahaha yea, I was just filling the time between the games 😝 

༼ つ ◕_◕ ༽つ TAKE MY ENERGY PACKERS ༼ つ ◕_◕ ༽つ

**Comment by miniksa** [comment]
@zadjii-msft, oof indeed.

Also, sorry, Tuesday turned out to be Performance Review day, so I spent all day procrastinating on and writing it.

Looking now. I intend to double check the changes against the historical versions of `WriteCharsLegacy` from conhostv1 to make sure we're only tampering with things that I've added in the course of the last several years for VT reasons.

**Comment by j4james** [comment]
> Looking now. I intend to double check the changes against the historical versions of `WriteCharsLegacy` from conhostv1 to make sure we're only tampering with things that I've added in the course of the last several years for VT reasons.

I was hoping you'd be able to do that! Ideally we could eventually get this back to exactly how it was in the v1 conhost, once we've got a dedicated stream writer for VT mode (i.e. #780). 

But if you have any concerns about these changes, I was going to suggest maybe splitting it up into separates PRs? The most important change is probably the first commit, because that fixes #3971. The rest are really edge-case bugs that are unlikely to be encountered in practice.

**Comment by miniksa** [comment]
> But if you have any concerns about these changes, I was going to suggest maybe splitting it up into separates PRs? The most important change is probably the first commit, because that fixes #3971. The rest are really edge-case bugs that are unlikely to be encountered in practice.

I'm not concerned about splitting them up. @zadjii-msft and @DHowett-MSFT are probably rightfully afraid of this area, but making a big mess all at once was my signature thing in this space a few years ago. So just give me a bit to walk through. I'd rather work the whole problem at once instead of chasing 5 PRs.

**Comment by miniksa** [comment]
> These are mostly notes to myself. I'm still reviewing and I don't want GH to choke and lose them somehow.

Also I will likely finish in the morning because I have to go pick up the kiddo from daycare soon.

File: src/host/_stream.cpp [hunk 1]
```diff
@@ -449,28 +402,23 @@ constexpr unsigned int LOCAL_BUFFER_SIZE = 100;
...
-                        }
+                    for (ULONG j = 0; j < TabSize && i < LOCAL_BUFFER_SIZE; j++, i++)
+                    {
+                        *LocalBufPtr = UNICODE_SPACE;
+                        LocalBufPtr++;
                     }
 
                     pwchBuffer++;
                     break;
+                }
```
Comment (miniksa) [inline src/host/_stream.cpp]: This section matches the v1 code except for `LocalBufPtrA` which used to exist and I still need to find where it went (but am relatively confident it's unimportant.)

File: src/host/_stream.cpp [hunk 2]
```diff
@@ -753,52 +701,40 @@ constexpr unsigned int LOCAL_BUFFER_SIZE = 100;
...
-                    textBuffer.GetRowByOffset(cursor.GetPosition().Y).GetCharRow().SetWrapForced(true);
-                }
-                else
-                {
-                    NumChars = gsl::narrow<size_t>(CursorPosition.X - cursor.GetPosition().X);
-                    CursorPosition.Y = cursor.GetPosition().Y;
-                }
+                NumChars = gsl::narrow<size_t>(CursorPosition.X - cursor.GetPosition().X);
+                CursorPosition.Y = cursor.GetPosition().Y;
+            }
```
Comment (miniksa) [inline src/host/_stream.cpp]: Confirming this now matches the v1 block except the `SetWrapForced` line which I added in early in TH1 for the resize with reflow feature.

File: src/host/_stream.cpp [hunk 3]
```diff
@@ -753,52 +701,40 @@ constexpr unsigned int LOCAL_BUFFER_SIZE = 100;
...
-                    CATCH_LOG();
-                }
+            try
+            {
+                const OutputCellIterator it(UNICODE_SPACE, Attributes, NumChars);
+                const auto done = screenInfo.Write(it, cursor.GetPosition());
+                NumChars = done.GetCellDistance(it);
             }
+            CATCH_LOG();
+
```
Comment (miniksa) [inline src/host/_stream.cpp]: This spiritually matches the original v1 code now which called the bifurcated SB/FE `WriteOutputString` followed by the bifurcated SB/FE `FillOutput` unconditionally and did not check for error codes at the time. `NumChars` used to be returned as well out of each of the two calls, were never checked to be the same (the fill operation overwrote the string write result without looking at it first, I think)... but philosophically they were how many cell units of the buffer got filled up by the operations.

(I don't expect outsiders to understand the old bifurcated nature of these functions or the SB/FE thing, but consider them notes to myselfish that I could explain later. It's not really a secret.)

File: src/cascadia/TerminalCore/Terminal.cpp [hunk 4]
```diff
@@ -431,27 +431,6 @@ void Terminal::_WriteBuffer(const std::wstring_view& stringView)
         {
             proposedCursorPosition.Y++;
         }
```
[the remark this answers is not in the document]
Comment (j4james) [reply src/cascadia/TerminalCore/Terminal.cpp]: Yep. I believe the only reason it's still needed is for the `TerminalDispatch::LineFeed` implementation here:

https://github.com/microsoft/terminal/blob/94f4db32cdbc41fc9f3234f5c35554f230aab7fc/src/cascadia/TerminalCore/TerminalDispatch.cpp#L85-L91

Ideally I think it would be replaced with a call to something in the `ITerminalApi` interface, similar to the way the `AdaptDispatch` implementation calls `ConGetSet::PrivateLineFeed`. But I was hoping that would eventually work itself out as part of the `TerminalDispatch`/`AdaptDispatch` unification in #3849.

If it's holding up your #780 stream writer, though, it may be worth doing something about this sooner rather than later, even if it is a temporary hack.

File: src/host/_stream.cpp (hunk 1 above)
Comment (miniksa) [reply src/host/_stream.cpp]: `LocalBufPtrA` is no longer needed. It was tracking column width. We figure out the column width elsewhere, not immediately here while entering tabs.

File: src/host/_stream.cpp [hunk 5]
```diff
@@ -330,59 +330,12 @@ constexpr unsigned int LOCAL_BUFFER_SIZE = 100;
...
-                    // forward to the next line as if we had done it earlier, then let everything else play out normally.
-                    fDoEolWrap = true;
-                }
-
-                if (fDoEolWrap)
-                {
-                    CursorPosition.X = 0;
-                    CursorPosition.Y++;
+                CursorPosition.X = 0;
+                CursorPosition.Y++;
```
[the remark this answers is not in the document]
Comment (miniksa) [reply src/host/_stream.cpp]: OK, so the delayed EOL as a whole was not a part of the original WriteChars from v1 either.

I added that to ensure that VT writers could successfully write into the bottom right corner of the display without causing an automatic advance to the next row.

It's quite likely that we should end up removing this entire block, the `WC_DELAY_EOL_WRAP` flag, and the setter block down at the bottom of this function on lines 564-575 too.

We may or may not also remove the state and methods off the `Cursor` class itself. I can see reusing them inside `TextBuffer` to keep track of this while stream-writing or eliminating them and implementing it a different way. (I'm not a huge fan of all the stuff hanging off of `Cursor` anyway.)

File: src/host/_stream.cpp [hunk 6]
```diff
@@ -330,59 +330,12 @@ constexpr unsigned int LOCAL_BUFFER_SIZE = 100;
...
 
-                    Status = AdjustCursorPosition(screenInfo, CursorPosition, WI_IsFlagSet(dwFlags, WC_KEEP_CURSOR_VISIBLE), psScrollY);
+                Status = AdjustCursorPosition(screenInfo, CursorPosition, WI_IsFlagSet(dwFlags, WC_KEEP_CURSOR_VISIBLE), psScrollY);
 
-                    CursorPosition = cursor.GetPosition();
-                }
-            }
-        }
-
-        if (screenInfo.InVTMode())
```
Comment (miniksa) [inline src/host/_stream.cpp]: With the elimination of all references to `SCREEN_INFORMATION::InVtMode` from this function, I believe that the method can now be made private on `SCREEN_INFORMATION` such that no one else takes a dependency on it going forward.

Comment (j4james) [reply src/host/_stream.cpp]: Is this something you'd like me to do now or is it just a note for a followup PR? One of my longer term plans was to see if we could move more of the VT-specific code into the `AdaptDispatch` class, where it could be more easily shared with the Terminal implementation. That would include the current tabstop management, which I think is now the only reason `InVTMode` is required, so we could eventually get rid of that completely.

Comment (miniksa) [reply src/host/_stream.cpp]: Changing it to private to symbolize that it's no longer accessible I'd like in this PR if possible just to shut the door on other consumers if the longer term plan takes longer than we want.

It should just be moving it down to the private section and then rename/replacing it with _InVTMode or something in the 3-4 locations it is remaining.

I know I'm being a bit confusing in this PR by making some comments, researching them, then resolving them myself. But this one is a legit change request. :)

Comment (j4james) [reply src/host/_stream.cpp]: OK. I've now made it private, and moved it down to where the other private boolean getters were declared. Also made a couple of cosmetic changes at the same time. I added an `Is` prefix to the name just to be consistent with the other methods, and slightly restructured the doc comments to match the surrounding code. (550a68587984448210c60bf6298cadb9f0afd94a)

File: src/cascadia/TerminalCore/Terminal.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (miniksa) [reply src/cascadia/TerminalCore/Terminal.cpp]: I keep changing my mind on what I want the stream writer to be because `TextBuffer::Write` doesn't seem far off from it right now, especially with all the C0 stuff coming out.

I think for consistency sake, we should probably take \n out too into a temporary thing. Then all this method will have left is the cursor handling and viewport scrolling.

File: src/host/_stream.cpp (hunk 6 above)
Comment (miniksa) [reply src/host/_stream.cpp]: Alright, thank you.

File: src/host/outputStream.cpp [hunk 7]
```diff
@@ -85,7 +85,7 @@ void WriteBuffer::_DefaultStringCase(const std::wstring_view string)
                                  &dwNumBytes,
                                  nullptr,
                                  _io.GetActiveOutputBuffer().GetTextBuffer().GetCursor().GetPosition().X,
-                                 WC_LIMIT_BACKSPACE | WC_NONDESTRUCTIVE_TAB | WC_DELAY_EOL_WRAP,
+                                 WC_LIMIT_BACKSPACE | WC_DELAY_EOL_WRAP,
```
[the remark this answers is not in the document]
Comment (miniksa) [reply src/host/outputStream.cpp]: I was researching this a few days ago. And then we had Day of Learning on Friday so I spent the day learning, not correlating. Then I spent the weekend weekending. So I'm back to this today.

**Comment by miniksa** [comment]
Yes, yes, @zadjii-msft, I hear you.

**Comment by miniksa** [comment]
OK, just looking through `WriteCharsLegacy` callers.... I've taken some notes.

It looks like:

## Usages of WriteCharsLegacy

The API is only used in 2 ways, flags wise:
- 1. `WC_LIMIT_BACKSPACE | WC_NONDESTRUCTIVE_TAB | WC_DELAY_EOL_WRAP` - 1 use
- 2. `WC_DESTRUCTIVE_BACKSPACE | WC_KEEP_CURSOR_VISIBLE | WC_ECHO` - all the other uses
- ** NOTE on 2: One of them has a slight variance, `readDataCooked:724`. This one optionally sets `WC_KEEP_CURSOR_VISIBLE`. But I'm 95% sure that is pointless and it could just set it all the time to no ill effect or be worked around otherwise.

And the usages only fall into two categories:
- A. Supporting stream writing operations - 2 uses
- B. Supporting cooked input lines - all other uses

#### Inventory of callers:
Callsite | Flags | Use Type
--- | --- | ---
_outputstream.cpp:81 | 1 | A
_stream.cpp:939 | 2 | A
readDataCooked:844 | 2 | B
readDataCooked:782 | 2 | B
readDataCooked:724 | 2 | B
readDataCooked:611 | 2 | B
readDataCooked:529 | 2 | B
commandNumberPopup.cpp:69 | 2 | B
commandNumberPopup.cpp:38 | 2 | B
Cmdline.cpp:984 | 2 | B
Cmdline.cpp:934 | 2 | B
Cmdline.cpp:891 | 2 | B
Cmdline.cpp:310 | 2 | B
Cmdline.cpp:474 | 2 | B
Cmdline.cpp:509 | 2 | B
Cmdline.cpp:545 | 2 | B
Cmdline.cpp:1031 | 2 | B
Cmdline.cpp:269 | 2 | B
Cmdline.cpp:572 | 2 | B
Cmdline.cpp:599 | 2 | B
Cmdline.cpp:1086 | 2 | B

#### Commentary
- If the type 2 flags calls become all that's left, there's really no point in passing the flags at all, testing the flags for these, or having any variation at all left in `WriteCharsLegacy` around them because the behavior won't vary.
- All type B usages are probably due for some kind of refactor anyway at some point because the way they manipulate the buffer is always weird and mostly unsafe. We tried to protect it slightly with the `readDataCooked` class but that work never finished.

## Actions
### Part 1
- Finish this PR (+/- the move of the final `\n` operation into a function)
- Move terminus of `conhost.exe` parser (`_outputstream.cpp:81`) from calling `WriteCharsLegacy` into calling `TextBuffer::Write` since that's where it will end up getting to anyway after running through metric tons of code to realize it has no C0s anymore and just needs to call `TextBuffer::Write` anyway.
- Clean up terminus of `wt.exe` parser (`Terminal::_WriteBuffer`) before the `TextBuffer::Write` operation.
- Evaluate the following things and ensure they're either implemented in `TextBuffer::Write` or into a new function/options on that function to handle the needs of both `conhost.exe` and `wt.exe` uniformly:
1. Notifying the accessibility framework of what changed
2. Moving the cursor on their behalf instead of making them manage it
3. Updating the way they scroll to either notify them or have them look up the final cursor (if they care) and adjust their viewport over the buffer
- Stop accepting flags on `WriteCharsLegacy` and just make it always use those three flags and take out any switches on those to simplify it so we can better understand how to finally get rid of it entirely when getting around to improving the cooked read lines.

### Part 2
This focuses on the 2A item, `_stream.cpp:939`. That's the method `WriteChars`.
- After Part 1, `WriteChars` is the last non-input-line-related caller of `WriteCharsLegacy`
- The only caller of `WriteChars` is `DoWriteConsole`, a method that used to have a bunch of other `Do*` friends that I've killed over the years in favor of more organized `ApiDispatchers` and friends.
- The only remaining caller of `DoWriteConsole` is `WriteConsoleWImplHelper`*
(The * is because there's actually a second caller, `WriteData::Notify`, but that's simply the wait-routine servicer of `WriteConsoleWImplHelper`... a.k.a. it's the one who dispatches that call "later" if it turns out that the buffer was blocked at the time the call was first dispatched and will be called later when the block is released. This is the "click on the screen to make a selection stops the clients from writing" thing.)
- `WriteConsoleWImplHelper` is responsible for the three public APIs: 
1. `WriteConsoleW`
2. `WriteConsoleA`
3. `WriteFile` (when the `HANDLE` is a console handle).
- My theory on these is that what the public operations want here is similar enough to what the VT ones want that once we have the C0 commands implemented here and have beefed up `TextBuffer::Write` (or another function that looks very close to it, the stream writer), that we could feed them directly into a VT parser in a mode that only pulls out the relevant C0s and dispatches them to an Adapter implementation that performs things like a destructive backspace and then feeds the final result into the `TextBuffer::Write`.

## Conclusion
- Doing `Part 1` is what we need to satisfy the "Credible stream writing" for the Terminal product `wt.exe`.
- Doing `Part 2` is all `conhost.exe` work and would be great for maintainability as we'd be platforming everything on the same things.
- Making a less crappy cooked read suite could be a `Part 3`, is `conhost.exe`-centric, and I'm not sure how much real value it has besides letting us kill `WriteCharsLegacy` once and for all. I might try to justify it on the buffer insecurity of the `cmdline.cpp` and `cookedReadData.cpp` accesses to memory locations.

cc: #780

File: src/cascadia/TerminalCore/Terminal.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (j4james) [reply src/cascadia/TerminalCore/Terminal.cpp]: I'm not sure this is what you had in mind, but I had to split the cursor movement code out of `Terminal::_WriteBuffer` into a separate method so it could be reused in the linefeed implementation (see [`7f0bcad`](https://github.com/microsoft/terminal/commit/7f0bcad72bba5e131ba94aab84efdc6a911247e5?w=1)  without whitespace diffs), otherwise there'd be a lot of code duplication.

I then added a `CursorLineFeed` method in `TerminalApi` which calls the above method to handle the actual cursor movement, and got rid of the linefeed handling in `_WriteBuffer`  (see [`da0924b`](https://github.com/microsoft/terminal/commit/da0924b43df07f2d5831f38090f83949575659fb?w=1), again easier to follow without whitespace diffs).

I'm not positive this is the best long-term interface, but for now at least it's more in line with the `AdaptDispatch` implementation.

[the remark this answers is not in the document]
Comment (miniksa) [reply src/cascadia/TerminalCore/Terminal.cpp]: OK, I'll look. Thank you for bearing with me.

**Comment by j4james** [comment]
@miniksa: Regarding the notes above, I think there are couple of things you may be overlooking in part 1, which we'd need to address before we could replace `WriteCharsLegacy` with `TextBuffer::Write`.

1. Delayed EOL wrap
2. The option to not wrap at all when `DECAWM` is reset
3. The wrapping/scrolling margins (initially `DECSTBM`, but we'll eventually want to support `DECSLRM` too)

The first two are probably not that big a deal, but I can see the margin handling becoming a bit of a nightmare again.

**Comment by miniksa** [comment]
> @miniksa Michael Niksa FTE: Regarding the notes above, I think there are couple of things you may be overlooking in part 1, which we'd need to address before we could replace `WriteCharsLegacy` with `TextBuffer::Write`.
> 
> 1. Delayed EOL wrap
> 2. The option to not wrap at all when `DECAWM` is reset
> 3. The wrapping/scrolling margins (initially `DECSTBM`, but we'll eventually want to support `DECSLRM` too)
> 
> The first two are probably not that big a deal, but I can see the margin handling becoming a bit of a nightmare again.

I wrote it out hoping you would spot considerations I missed like that and we could discuss further. Thanks! Here's my thoughts on each:

For 1, I think delayed EOL wrap should maybe be the default behavior there and the true legacy ways (the ones coming in through the API) should force-advance and then backspace once to get the non-delayed behavior.

For 2, there's an alternate function of `TextBuffer::WriteLine` that always stops when it reaches the right bounds. `TextBuffer::Write` calls that in a loop. I'd think things like `DECAWM` could use that conditionally.

For 3, One of the parameters to `TextBuffer::Write`, in one of its incarnations, is a bounding rectangle that defaults to the whole buffer. Perhaps when `DECSTBM` or `DECSLRM` are set, the `Write` caller passes in a bounding rectangle with those to the optional parameter?

Any of that sound reasonable? Am I still blind to something?

**Comment by j4james** [comment]
> For 1, I think delayed EOL wrap should maybe be the default behavior there and the true legacy ways (the ones coming in through the API) should force-advance and then backspace once to get the non-delayed behavior.

I'm not sure about this. How would you force-advance? You couldn't write out something like a space, because you need it to be non-destructive. And you couldn't just use CR/LF to move to the next line because you assumedly want the line to be marked as "wrapped" for resizing purposes.

I suspect it might be easier in the end to have a flag for this. Although maybe that's not necessary if  the legacy code never goes this route. Maybe it's fine if the delayed wrap is always applied here?

> For 2, there's an alternate function of `TextBuffer::WriteLine` that always stops when it reaches the right bounds. `TextBuffer::Write` calls that in a loop. I'd think things like `DECAWM` could use that conditionally.

Conceptually I like this, but I'm not certain it's the right approach. As I understand it, `WriteLine` stops writing when it reaches the end of the line, but it then leaves the "unused" content unwritten. For `DECAWM`, we actually need it to consume all of the content, just overwriting the last character every time. I suppose that could be achieved by calling `WriteLine` repeatedly until everything is consumed, but that feels a bit messy.

> For 3, One of the parameters to `TextBuffer::Write`, in one of its incarnations, is a bounding rectangle that defaults to the whole buffer. Perhaps when `DECSTBM` or `DECSLRM` are set, the `Write` caller passes in a bounding rectangle with those to the optional parameter?

An optional bounding rectangle sounds good. However, bear in mind that it's not really equivalent to the default buffer boundaries. If you're constrained by the margin boundaries, then a scroll event requires that you shift part of the buffer content, whereas a regular scroll would move the viewport origin or cycle the buffer.

Also, if you've started off outside the margin boundaries, then you're not constrained by them, but you are constrained by the viewport boundary. Only in that case, you don't scroll when you reach the bottom of the viewport, but I think you do still wrap at the right viewport boundary. It's complicated.

Also, I expect we'll want to keep at least some of this functionality in a separate method so it can be reused by other operations. In particular linefeeds need to implement the exact same margin/scrolling behaviour as wrapped text.

That said, as long as you're aware of all the issues, I don't think it's necessary we figure out the perfect plan in advance. It often helps to just dive in and start writing something, and if you don't like how it turns out, you can always start again. Eventually you'll settle on the solution you find least offensive. At least, that's what I do. ;)

**Comment by miniksa** [comment]
> > For 1, I think delayed EOL wrap should maybe be the default behavior there and the true legacy ways (the ones coming in through the API) should force-advance and then backspace once to get the non-delayed behavior.
> 
> I'm not sure about this. How would you force-advance? You couldn't write out something like a space, because you need it to be non-destructive. And you couldn't just use CR/LF to move to the next line because you assumedly want the line to be marked as "wrapped" for resizing purposes.

Hm, I was thinking that it might not need to be non-destructive. For instance, the case where we're writing to the bottom right corner of the buffer, the next operation once it leaves the right edge is to go down a line and "rotate the circular buffer" which destroys the contents of the line that's about to swap in.

But I suppose if we're NOT in the absolute bottom-right corner of the buffer, only the right edge of a viewport, that we wouldn't necessarily want to destroy the value in the 0th column of the next line. So everywhere except X=Max,Y=Max it would have to be non-destructive.

> I suspect it might be easier in the end to have a flag for this. Although maybe that's not necessary if the legacy code never goes this route. Maybe it's fine if the delayed wrap is always applied here?

Yeah perhaps it's best that it's either a flag or something then.

> > For 2, there's an alternate function of `TextBuffer::WriteLine` that always stops when it reaches the right bounds. `TextBuffer::Write` calls that in a loop. I'd think things like `DECAWM` could use that conditionally.
> 
> Conceptually I like this, but I'm not certain it's the right approach. As I understand it, `WriteLine` stops writing when it reaches the end of the line, but it then leaves the "unused" content unwritten. For `DECAWM`, we actually need it to consume all of the content, just overwriting the last character every time. I suppose that could be achieved by calling `WriteLine` repeatedly until everything is consumed, but that feels a bit messy.

Nnnnn. More flags. Or something. I don't like the idea of adding more and more and more flags and would hope we could just find a systematic way out of this. Perhaps the initial naive implementation just calls it repeatedly until everything is consumed. Then we optimize later. The assorted `TextBuffer::Write*` methods already leave a bit to be desired in terms of optimization. They could be performing look-aheads to bulk insert data when it matches certain common patterns that they aren't (and that the original legacy algorithms did to some degree). But it doesn't seem to be that painful right now, performance wise... or at least not that I'm aware of.

> > For 3, One of the parameters to `TextBuffer::Write`, in one of its incarnations, is a bounding rectangle that defaults to the whole buffer. Perhaps when `DECSTBM` or `DECSLRM` are set, the `Write` caller passes in a bounding rectangle with those to the optional parameter?
> 
> An optional bounding rectangle sounds good. However, bear in mind that it's not really equivalent to the default buffer boundaries. If you're constrained by the margin boundaries, then a scroll event requires that you shift part of the buffer content, whereas a regular scroll would move the viewport origin or cycle the buffer.
> 
> Also, if you've started off outside the margin boundaries, then you're not constrained by them, but you are constrained by the viewport boundary. Only in that case, you don't scroll when you reach the bottom of the viewport, but I think you do still wrap at the right viewport boundary. It's complicated.

Ah, yes. Perhaps the passed bounding rectangle for writing is also the range that is used for the `TextBuffer::ScrollRows` operation. If we're writing in a mode where we "Write to the end of the iterator content" not a mode where "we write until we run out of space", then the `TextBuffer::Write*` entrypoint would just call `ScrollRows` on itself with the parameters of the bounding rectangle until it ran out of space.

> Also, I expect we'll want to keep at least some of this functionality in a separate method so it can be reused by other operations. In particular linefeeds need to implement the exact same margin/scrolling behaviour as wrapped text.
> 
> That said, as long as you're aware of all the issues, I don't think it's necessary we figure out the perfect plan in advance. It often helps to just dive in and start writing something, and if you don't like how it turns out, you can always start again. Eventually you'll settle on the solution you find least offensive. At least, that's what I do. ;)

Yes. Yes. Generally I've had the most success just mucking about with it piece by piece and evolving it over time. Let's just make progress here. If you're OK without 100% pre-planning, so am I.

File: src/cascadia/TerminalCore/Terminal.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (miniksa) [reply src/cascadia/TerminalCore/Terminal.cpp]: Nah, that's good enough for now. Thanks. Let's go with what you said further below and just keep progressively mushing on it until we deem it minimally offensive.

**Comment by miniksa** [comment]
I'm going to try a re-run on the thing hoping that it remerges against master. But if not, we need to merge master in to see if the flakiness subsides.

I'd click the button, but I royally screwed up your branch last time, @j4james.

**Comment by miniksa** [comment]
Quick. I'm merging it before the system looks at it funny and fails again.

**Comment by DHowett-MSFT** [comment]
:tada: Once again, thanks for the contribution!

This pull request was included in a set of conhost changes that was just
released with [Windows Insider Build 19603](https://blogs.windows.com/windowsexperience/2020/04/08/announcing-windows-10-insider-preview-build-19603/).
