### PR TITLE
Fix Reverse Walking in AttrRowIterator

### LINKED ISSUE #3409: Crash: Chunk Selection over ubuntu prompt working directory
# Environment

```none
Windows build number: [run `[Environment]::10.0.19016.1000
Windows Terminal version (if applicable): v0.6.2951.0
```

Other prereqs:
- double click delimiters must include "\\/"
- have a way of printing CJK characters and emoji
- Ubuntu
- must be "Windows Terminal (Dev Build)". Doesn't repro on version downloaded from the store. Doesn't matter if debugger is attached.

NOTE: not entirely sure which of these are relevant but we can cut down on it as we investigate

# Steps to reproduce

1. open tab with ubuntu in it
2. output CJK characters
3. double click a portion of the command that is in English
4. chunk select (drag while holding mouse button) to the right or down (should work fine. Even if you highlight CJK characters)
5. chunk select back past starting anchor into file path

(Optional) if it doesn't crash when you go into the file path, just keep trying to chunk select the file path, it should occur.

# Expected behavior

Chunk selection continues to happen just fine.

# Actual behavior

Crash. Here's the stack:
```
>	ucrtbased.dll!_VCrtDbgReportA(int nRptType, void * returnAddress, const char * szFile, int nLine, const char * szModule, const char * szFormat, char * arglist) Line 284	C++
 	ucrtbased.dll!_CrtDbgReport(int report_type, const char * file_name, int line_number, const char * module_name, const char * format, ...) Line 263	C++
 	TerminalControl.dll!std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<TextAttributeRun> > >::operator--() Line 82	C++
 	TerminalControl.dll!AttrRowIterator::_decrement(unsigned __int64 count) Line 135	C++
 	TerminalControl.dll!AttrRowIterator::operator+=(const __int64 & movement) Line 64	C++
 	TerminalControl.dll!TextBufferCellIterator::_SetPos(const _COORD newPos) Line 219	C++
 	TerminalControl.dll!TextBufferCellIterator::operator+=(const __int64 & movement) Line 110	C++
 	TerminalControl.dll!TextBufferCellIterator::operator-=(const __int64 & movement) Line 122	C++
 	TerminalControl.dll!TextBufferCellIterator::operator--() Line 140	C++
 	TerminalControl.dll!TextBufferCellIterator::operator--(int __formal) Line 161	C++
 	TerminalControl.dll!Microsoft::Terminal::Core::Terminal::_ExpandDoubleClickSelectionLeft(const _COORD position) Line 369	C++
```

I'm particularly confused because it's hitting a `_CrtDbgBreak()` in the last frame.

### PR DESCRIPTION
**Pull request by carlos-zamora**
## Summary of the Pull Request
The `count -= _currentAttributeIndex` caused `_run` to go out of bounds. Removing the minor optimization fixes this potential crash.

## References
#3409 

## PR Checklist
* [x] Closes #3409 
* [x] CLA signed
* [ ] Tests added/passed
* [x] Requires documentation to be updated
* [x] I am a core contributor

## Detailed Description of the Pull Request / Additional comments
@miniksa knows much more about this. He's the real MVP.

## Validation Steps Performed
1. Open ubuntu shell
2. double click the : or ~ in cazamor@PC-cazamor:~$

This used to crash. Not anymore!

### CODE REVIEW

**Comment by zadjii-msft** [comment]
Hey so can we add a unit test in SelectionTests for this case? It seems obscure enough of a case that it should have one

**Comment by DHowett-MSFT** [comment]
Can you indicate where the optimization got added, and why it's bad, and why it's okay to go without it, and if this is a full revert of another commit or a partial one, etc.?

**Comment by DHowett-MSFT** [comment]
We need to make sure that these two cases work properly as well:

```
  AAAA BBBB CCCC
         ^
         decrement(5)

should be:

  AAAA BBBB CCCC
   ^

with this change, I think it's:

x AAAA BBBB CCCC
^ off the end of the run
```

```
  AAAA BBBB CCCC
             ^
             decrement(7)

should be:

  AAAA BBBB CCCC
    ^

with this change, I think it's:

x AAAA BBBB CCCC
^ off the end of the run
```

**Comment by carlos-zamora** [comment]
> We need to make sure that these two cases work properly as well:
> 
> ```
>   AAAA BBBB CCCC
>          ^
>          decrement(5)
> 
> should be:
> 
>   AAAA BBBB CCCC
>    ^
> 
> with this change, I think it's:
> 
> x AAAA BBBB CCCC
> ^ off the end of the run
> ```
> 
> ```
>   AAAA BBBB CCCC
>              ^
>              decrement(7)
> 
> should be:
> 
>   AAAA BBBB CCCC
>     ^
> 
> with this change, I think it's:
> 
> x AAAA BBBB CCCC
> ^ off the end of the run
> ```

Added the two tests above except that the runs are of length one. This makes verification easier because now I just have to check the text attribute (@DHowett-MSFT 's idea)

File: src/buffer/out/AttrRowIterator.cpp [hunk 1]
```diff
@@ -123,14 +130,23 @@ void AttrRowIterator::_decrement(size_t count)
...
     while (count > 0)
     {
+        // If there's still space within this color attribute to move left, do so.
         if (count <= _currentAttributeIndex)
         {
             _currentAttributeIndex -= count;
             return;
         }
+        // If there's not space, move the whole color attribute left by one
+        // and just take one away from the remaining movement.
```
Comment (DHowett-MSFT) [inline src/buffer/out/AttrRowIterator.cpp]: this comment doesn't match the math below -- it's no longer just subtracting one

File: src/host/ut_host/AttrRowTests.cpp [hunk 2]
```diff
@@ -498,6 +498,128 @@ class AttrRowTests
...
+            VERIFY_ARE_EQUAL(chain->_cchRowWidth, chain->_list[0]._cchLength + chain->_list[1]._cchLength + chain->_list[2]._cchLength);
+
+            auto index = 1;
+            auto stepSize = 1;
+            verifyStep(chain.get(), index, stepSize, TextAttribute(0xB));
+        }
+
+        Log::Comment(L"Reverse iterate past one boundary");
+        {
+            // Create attr row representing a buffer that's 12 wide.
```
Comment (DHowett-MSFT) [inline src/host/ut_host/AttrRowTests.cpp]: not 12

File: src/host/ut_host/AttrRowTests.cpp [hunk 3]
```diff
@@ -498,6 +498,128 @@ class AttrRowTests
...
+            VERIFY_ARE_EQUAL(chain->_cchRowWidth, chain->_list[0]._cchLength + chain->_list[1]._cchLength + chain->_list[2]._cchLength + chain->_list[3]._cchLength);
+
+            auto index = chain->_list[0].GetLength();
+            auto stepSize = 1;
+            testWalk(chain.get(), index, stepSize);
+        }
+
+        Log::Comment(L"Reverse iterate past one boundary");
+        {
+            // Create attr row representing a buffer that's 12 wide.
```
Comment (DHowett-MSFT) [inline src/host/ut_host/AttrRowTests.cpp]: not 12

File: src/buffer/out/AttrRowIterator.cpp [hunk 4]
```diff
@@ -84,11 +89,13 @@ AttrRowIterator AttrRowIterator::operator--(int)
 
 const TextAttribute* AttrRowIterator::operator->() const
 {
+    THROW_HR_IF(E_BOUNDS, _exceeded);
```
Comment (miniksa) [inline src/buffer/out/AttrRowIterator.cpp]:
```suggestion
    // This should be technically impossible as the movement stops this condition.
    FAIL_FAST_IF(_exceeded);
```

File: src/buffer/out/AttrRowIterator.cpp [hunk 5]
```diff
@@ -84,11 +89,13 @@ AttrRowIterator AttrRowIterator::operator--(int)
 
 const TextAttribute* AttrRowIterator::operator->() const
 {
+    THROW_HR_IF(E_BOUNDS, _exceeded);
     return &_run->GetAttributes();
 }
 
 const TextAttribute& AttrRowIterator::operator*() const
 {
+    THROW_HR_IF(E_BOUNDS, _exceeded);
```
Comment (miniksa) [inline src/buffer/out/AttrRowIterator.cpp]:
```suggestion
    // This should be technically impossible as the movement stops this condition.
    FAIL_FAST_IF(_exceeded);
```

**Comment by DHowett-MSFT** [comment]
"movement stops this condition"

I disagree a little bit with this.

`iter -= 100` will result in an exceeded iterator; movement doesn't prevent this state.
Checking the validity of the iterator with `if(iter)` _helps_ prevent it, but.. i dunno.

File: src/buffer/out/AttrRowIterator.cpp (hunk 4 above)
Comment (carlos-zamora) [reply src/buffer/out/AttrRowIterator.cpp]: Resolving because it makes more sense to have it be flexible and let the `E_BOUNDS` be caught/handled elsewhere.

File: src/buffer/out/AttrRowIterator.cpp (hunk 5 above)
Comment (carlos-zamora) [reply src/buffer/out/AttrRowIterator.cpp]: Resolving because it makes more sense to have it be flexible and let the `E_BOUNDS` be caught/handled elsewhere.

File: src/host/ut_host/AttrRowTests.cpp [hunk 6]
```diff
@@ -498,6 +498,128 @@ class AttrRowTests
...
+
+            // The sum of the lengths should be 3.
+            VERIFY_ARE_EQUAL(chain->_cchRowWidth, chain->_list[0]._cchLength + chain->_list[1]._cchLength + chain->_list[2]._cchLength);
+
+            auto index = 1;
+            auto stepSize = 1;
+            verifyStep(chain.get(), index, stepSize, TextAttribute(0xB));
+        }
+
+        Log::Comment(L"Reverse iterate past one boundary");
```
Comment (DHowett-MSFT) [inline src/host/ut_host/AttrRowTests.cpp]: 566 and 594 both say "past one boundary". Is one incorrect?
