### PR TITLE
Pass the scancode in our tunneled DirectKey event

### LINKED ISSUE #7297: F7 tunneling broken
F7 tunneling introduced by #4807 seem to be broken in 1.2.2234.0 preview, but still works in 1.1.2233.0 release

# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.450]
Windows Terminal version (if applicable): Version: 1.2.2234.0
```

# Steps to reproduce

Press F7

# Expected behavior

F7 key is passed to application

# Actual behavior

Nothing happens

### PR DESCRIPTION
**Pull request by DHowett**
#7145 introduced a check so that we wouldn't dispatch keys unless they
actually had a scancode. Our synthetic events actually _didn't_ have
scancodes. Not because they couldn't--just because they didn't.

Fixes #7297

### CODE REVIEW

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 1]
```diff
@@ -763,7 +763,7 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
     //   normally. Namely, the keys we're concerned with are F7 down and Alt up.
     // Return value:
     // - Whether the key was handled.
-    bool TermControl::OnDirectKeyEvent(const uint32_t vkey, const bool down)
+    bool TermControl::OnDirectKeyEvent(const uint32_t vkey, const uint8_t scanCode, const bool down)
     {
         const auto modifiers{ _GetPressedModifierKeys() };
         auto handled = false;
```
Comment (DHowett) [inline src/cascadia/TerminalControl/TermControl.cpp:769]: we actually _fake the scancode for ALT_ so uh why not just fix this too

File: src/cascadia/TerminalApp/IDirectKeyListener.idl [hunk 2]
```diff
@@ -8,7 +8,7 @@ namespace TerminalApp
     // If you update this one, please update the one in TerminalControl\TermControl.idl
     // If you change this interface, please update the guid.
     // If you press F7 or Alt and get a runtime error, go make sure both copies are the same.
-    [uuid("339e1a87-5315-4da6-96f0-565549b6472b")] interface IDirectKeyListener {
-        Boolean OnDirectKeyEvent(UInt32 vkey, Boolean down);
+    [uuid("0ddf4edc-3fda-4dee-97ca-a417ee3dd510")] interface IDirectKeyListener {
```
Comment (zadjii-msft) [inline src/cascadia/TerminalApp/IDirectKeyListener.idl:11]: why bump the uuid?

Comment (DHowett) [reply src/cascadia/TerminalApp/IDirectKeyListener.idl:11]: you're supposed to do this on every change to an existing interface, technically. The interface is really supposed to unique the vtable layout that allows for a conformant class to be called by an unknown caller -- the chief feature of COM :smile:

Also because it says it in the rules on line 9

Comment (DHowett) [reply src/cascadia/TerminalApp/IDirectKeyListener.idl:11]: It's not applicable here but it's good to get in the habit. If somebody had taken a dependency on this interface solely by layout and old UUID, new consumers are no longer compatible with it. If we didn't change the uuid, consumers of the new layout would _report as compatible_ but get the parameter layout wrong (unpacking the first 8 bits of the Boolean as the scancode (!!))

**Comment by lhecker** [comment]
Aww ****. 🙈 Thanks for fixing this!

File: src/cascadia/TerminalApp/IDirectKeyListener.idl (hunk 2 above)
Comment (zadjii-msft) [reply src/cascadia/TerminalApp/IDirectKeyListener.idl:11]: that's what I thought, but I'm glad to have this typed out for posterity 😄

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 3]
```diff
@@ -763,17 +763,15 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
     //   normally. Namely, the keys we're concerned with are F7 down and Alt up.
     // Return value:
     // - Whether the key was handled.
-    bool TermControl::OnDirectKeyEvent(const uint32_t vkey, const bool down)
+    bool TermControl::OnDirectKeyEvent(const uint32_t vkey, const uint8_t scanCode, const bool down)
```
Comment (lhecker) [inline src/cascadia/TerminalControl/TermControl.cpp:766]: BTW The `vkey` parameter could technically be an `uint8_t` as well.

Comment (DHowett) [reply src/cascadia/TerminalControl/TermControl.cpp:766]: Totally. Didn't want to make too many changes in this PR for a hotfix :smile:

**Comment by DHowett** [comment]
@msftbot merge this in 2 minutes
