### PR TITLE
Fix a deadlock during ConPTY shutdown

### LINKED ISSUE #14132: OpenConsole.exe will not quit if start with `msys2` profile and click `close window button`
### Windows Terminal version

1.16.22...

### Windows build number

_No response_

### Other Software

_No response_

### Steps to reproduce

 start WT  with `msys2` profile and click `close window button`.

### Expected Behavior

OpenConsole.exe should quit after click close button even if WT start with msys2 profile.

### Actual Behavior

 I have to type `exit` to make OpenConsole.exe quit everytime or it will become a zombie process.

### PR DESCRIPTION
**Pull request by lhecker**
Problem:
* Calling `RundownAndExit` tries to flush out the last frame from `VtEngine`
* `VtEngine` indirectly calls `RundownAndExit` if the pipe is gone via `VtIo`
* `RundownAndExit` is called by other parts of OpenConsole
* `RundownAndExit` must be `[[noreturn]]` for most parts of OpenConsole
* `VtIo` itself has a mutex ensuring orderly shutdown
* In short, doing a thread safe orderly shutdown requires us to hold both,
  a lock in `RundownAndExit` and `VtIo` at the same time, but while other parts
  need a blocking `RundownAndExit`, `VtIo` needs a non-blocking one
* Refactoring the code to use optionally non-blocking `RundownAndExit`
  requires refactoring and might prove to be just as buggy

Solution:
* Simply don't call `RundownAndExit` in `VtEngine` at all
* In case the write pipe breaks:
  * `VtEngine` will close the handle
  * The client should notice that their read pipe is broken and
    close their write pipe sooner or later
  * Once we notice that our read pipe is broken, we call `RundownAndExit`
  * `RundownAndExit` might call back into `VtEngine` but
    without a pipe it won't do anything
* In case the read pipe breaks or any other part calls `RundownAndExit`:
  * We call `RundownAndExit`
  * `RundownAndExit` might call back into `VtEngine` and depending on whether
    the write pipe is broken or not it will simply write into it or ignore it

Closes #14132
Pretty sure this also applies to #1810

## Validation Steps Performed
* Open 5 tabs and run MSYS2's `bash --login` in each of them
* `Enter-VsDevShell` in another tab
* Close window
* 5 tab processes are killed instantly, 1 after ~3s ✅
* Replace conhost with OpenConsole via sfpcopy
* Launch Dozens of Git Bash tabs in VS Code
* Close them randomly
* Remaining ones still work, processes are gone ✅

### CODE REVIEW

File: src/host/VtIo.cpp [hunk 1]
```diff
@@ -444,56 +443,36 @@ void VtIo::SetWindowVisibility(bool showOrHide) noexcept
...
-        //      happens if this method is called outside of lock, but if we're
-        //      currently locked, we want to make sure ctrl events are handled
-        //      _before_ we RundownAndExit.
-        LockConsole();
-        ProcessCtrlEvents();
-
-        // Make sure we terminate.
-        ServiceLocator::RundownAndExit(ERROR_BROKEN_PIPE);
-    }
+    // At this point, we no longer have a renderer or inthread. So we've
```
Comment (DHowett) [inline src/host/VtIo.cpp:458]: I bet `inthread` doesn't pass spell check

Comment (DHowett) [reply src/host/VtIo.cpp:458]: nevermind it didn't change from the earlier code, just got indented. wow

File: src/host/VtIo.cpp [hunk 2]
```diff
@@ -444,56 +443,36 @@ void VtIo::SetWindowVisibility(bool showOrHide) noexcept
...
+    //      effectively been disconnected from the terminal.
```
Comment (DHowett) [inline src/host/VtIo.cpp:459]: there's no chance we'll call `CloseConsoleProcessState` twice?

Comment (DHowett) [reply src/host/VtIo.cpp:459]: I guess even if we do, we will then call LockConsole and one thread will stall here

File: src/host/VtIo.cpp [hunk 3]
```diff
@@ -337,11 +337,10 @@ void VtIo::CreatePseudoWindow()
...
 {
-    // MSFT:40853556 Grab the shutdown lock here, so that another
-    // thread can't trigger a CloseOutput and release the
-    // _pVtRenderEngine out from underneath us.
-    std::lock_guard<std::mutex> lk(_shutdownLock);
-
+    // ConsoleInputThreadProcWin32 calls VtIo::CreatePseudoWindow,
+    // which calls CreateWindowExW, which causes a WM_SIZE message.
+    // In short, this function might be called before _pVtRenderEngine exists.
+    // See PtySignalInputThread::CreatePseudoWindow().
```
Comment (DHowett) [inline src/host/VtIo.cpp:343]: since the window message loop happens on a different thread, what happens if we get a window message for visibility while we are shutting down? we will come in here, lock console, and stall... right?

**Review by DHowett — CHANGES_REQUESTED** [review]
> [2:20 PM] Dustin Howett
> did you `git blame` the line that introduced the shutdown mutex to see if it fixed a bug?
> [2:20 PM] Dustin Howett
> if so, can you test against _that_ bug?

Requesting changes during due diligence :)

File: src/host/VtIo.cpp (hunk 2 above)
Comment (lhecker) [reply src/host/VtIo.cpp:459]: Yeah, and the only caller is `CloseInput()` which is only called in a single place (`VtInputThread`, after `DoReadInput` fails).

File: src/host/VtIo.cpp (hunk 3 above)
Comment (lhecker) [reply src/host/VtIo.cpp:343]: The only function that blocks is `LockConsole`. If it does, that's fine since `RundownAndExit()` will hold the console lock during shutdown until the process exits. No code depends on the window thread to proceed during the shutdown so there's no "circular dependency" as is the case with `VtEngine`.

**Comment by lhecker** [comment]
> Requesting changes during due diligence :)

When I suggested that lock, my concern was that the caller of `SetWindowVisibility()` runs on a different thread than the code that calls `CloseOutput()`. Accessing `_pVtRenderEngine` without mutex would then lead to a race condition.

But now that I've read the code a bit closer, I've realized that all we do is `.release()` the object and not close it. So we might as well not reset _or_ release it at all, thus avoid needing another mutex.

**Review by DHowett — COMMENTED** [review]
I didn't submit a single annoying nit comment from a week ago lol

File: src/host/VtIo.cpp [hunk 4]
```diff
@@ -337,21 +339,20 @@ void VtIo::CreatePseudoWindow()
 
 void VtIo::SetWindowVisibility(bool showOrHide) noexcept
 {
-    // MSFT:40853556 Grab the shutdown lock here, so that another
-    // thread can't trigger a CloseOutput and release the
-    // _pVtRenderEngine out from underneath us.
-    std::lock_guard<std::mutex> lk(_shutdownLock);
+    auto& gci = ::Microsoft::Console::Interactivity::ServiceLocator::LocateGlobals().getConsoleInformation();
```
Comment (DHowett) [inline src/host/VtIo.cpp:342]: Actually, i am suddenly worried this is a deadlock factory. We call `SetWindowVisibility` off the I/O thread when Terminal says "I got focus." The PseudoWindow itself may also take the console lock to send Terminal messages. Is there a condition that will result in Terminal receiving and processing a message while the console lock is held, and then trying to dump a focus message back into the VtIo pipe?

**Review by DHowett — APPROVED** [review]
Let's give it a shot then!

File: src/host/VtIo.cpp (hunk 4 above)
Comment (lhecker) [reply src/host/VtIo.cpp:342]: The previous code already acquired the console lock here. All I did was move the if condition inside the locked area. If we have such a bug then we should have had it before this PR is/was merged.

File: src/host/VtInputThread.cpp [hunk 5]
```diff
@@ -94,7 +93,7 @@ VtInputThread::VtInputThread(_In_ wil::unique_hfile hPipe,
 DWORD WINAPI VtInputThread::StaticVtInputThreadProc(_In_ LPVOID lpParameter)
 {
     const auto pInstance = reinterpret_cast<VtInputThread*>(lpParameter);
-    return pInstance->_InputThread();
+    pInstance->_InputThread();
```
Comment (lhecker) [inline src/host/VtInputThread.cpp:96]: FYI `_InputThread` is now `[[noreturn]]` because `CloseInput` is `[[noreturn]]`. Hence, no `return` is needed, despite this function "returning" a `DWORD`.

**Comment by miniksa** [comment]
Test with WSL calling out to this to run a Windows executable (ensure you receive all output from the Windows binary back to the Linux half and that the process exits correctly).
Also test with VScode's integrated terminal.

If both are "fine" then this should be "fine".

**Comment by miniksa** [comment]
Hate that I'm saying this, but you should probably check this change on a OneCore edition as well :|

**Review by miniksa — APPROVED** [review]
Code looks fine to me. It's just a matter of the effects. You will want to test the various integrations I listed if you didn't already (building this as conhost.exe and subbing into the various Windows OS images) before merging.

**Comment by DHowett** [comment]
> Test with WSL calling out to this to run a Windows executable (ensure you receive all output from the Windows binary back to the Linux half and that the process exits correctly).

A good way would be to run, like, `bc` or something... using WSL interop.

I'll help L with a onecore build. It can be.. let's say tedious. :D

**Comment by lhecker** [comment]
I've tested two scenarios now:
* Opening a `pwsh` tab running `wsl` inside, running `pwsh` inside that and then running `bc.exe`.
  Then close the tab.
* Running an .exe that exits really quickly.

In both cases both the old code as well as the new code caused OpenConsole to exit immediately. However one time I had a leftover/hung conhost.exe in headless mode hanging around out of nowhere. The good news is that this is the OS' conhost and not the one I patched via `sfpcopy`, so whatever this does: This doesn't make it worse. (I ran my OpenConsole as conhost via `sfpcopy` already to test VS Code and that worked fine as well.)

**Comment by DHowett** [comment]
I can't get sirep working, but it does tear down properly in onecore (not tested onecoreuap yet); I can't get WSL to exhibit an output truncation bug either.
