### PR TITLE
Bugfix: vertical selection out of bounds

### LINKED ISSUE #1312: Crashes on console text selection from bottom to top if mouse reaches window's titlebar
# Environment

```none
Windows build number: Microsoft Windows [Versión 10.0.18362.175]
Windows Terminal version (if applicable): 0.0.1.0

Any other software?
```

# Steps to reproduce

Select text from bottom to top and reach to the window title while still holding the mouse.

# Expected behavior

Not to crash.

# Actual behavior

Crashes and closes the terminal.

### PR DESCRIPTION
**Pull request by carlos-zamora**
## Summary of the Pull Request
This was a side effect of #905. But applies the same logic #1254. We were trying to get buffer data at a location that doesn't exist for the buffer. Removed the `noexcept`s from the expand selection functions.

The fix is simple enough. Just clamp the Y value of the selection to be between 0 and the mutable viewport's height. I tried using the Viewport's Clamp method but we're doing some weird transforms so I found that it's just easiest to do it manually (and slightly differently).

As an extra benefit, now if you're all the way at the top of the buffer and you try making a selection past the top, the x-value still updates as you move. The same thing applies to the bottom when you're at the bottom of the buffer.

 
## PR Checklist
* [x] Closes #1312 
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Requires documentation to be updated
* [x] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan.

## Validation Steps Performed
- create a selection expanding past the top of the window
- do same selection as above but right-click to copy (this tests extracting the data from the buffer is still done properly)
- do both tests above, but for the bottom (this wasn't an issue before, and shouldn't be one now)
- repeat mentioned tests when you create a scrollable region and you are NOT at the boundaries

NOTE: for that last one, the selection should actually expand to outside of the viewport. That's actually intended as we need that for #1247 .

### CODE REVIEW

File: src/cascadia/TerminalCore/Terminal.hpp [hunk 1]
```diff
@@ -192,7 +192,7 @@ class Microsoft::Terminal::Core::Terminal final :
 #pragma region TextSelection
     // These methods are defined in TerminalSelection.cpp
     std::vector<SMALL_RECT> _GetSelectionRects() const;
-    const SHORT _ExpandWideGlyphSelectionLeft(const SHORT xPos, const SHORT yPos) const noexcept;
```
Comment (zadjii-msft) [inline src/cascadia/TerminalCore/Terminal.hpp]: Wait why do these have to be _not_ `noexcept`? (I think I'm missing it)

Comment (carlos-zamora) [reply src/cascadia/TerminalCore/Terminal.hpp]: That's what I thought. BUT, `const auto attr = _buffer->GetCellDataAt(position)->DbcsAttr();` (speciffically the `_buffer->GetCellDataAt(position)` part) isn't always safe to use. If you're outside of the buffer, you crash.

The exact same thing happened with copying after a resize event. You'd point to a place that doesn't exist.

**Comment by carlos-zamora** [comment]
> Could we file a follow-up task to create a test for this? I don't want to block 0.2 on missing a test for this case, but since it's all in TerminalCore, I think it should have one

#1327
