### PR TITLE
Configure CLI11 to stuff all unknown positionals into the cmdline

### LINKED ISSUE #4277: Error message when trying to provide a `--startingDirectory` to a WSL `wt.exe` command
(Follow-up from #4023)

Say you wanted to open a `Debian` WSL instance in `C:\Users`. According to the docs, you might try:

```
wt -d c:\Users wsl -d Debian
```

Unfortunately, this _won't_ work, and will give you an error about "expected exactly 1 argument to `--startingDirectory`, got 2". This is because we'll erroneously try to parse the `-d Debian` parameter as a second `--startingDirectory` value. This is unexpected.

### PR DESCRIPTION
**Pull request by DHowett-MSFT**
This commit fixes an issue where "wt -d C: wsl -d Alpine" would be
parsed as "wt -d C: -d Alpine wsl" and rejected as invalid due to the
repeated -d. It also fixes support for the option parsing terminator,
--, in all command lines.

Fixes #4277.

## References

https://github.com/CLIUtils/CLI11/issues/417

## PR Checklist
* [x] Closes #4277
* [x] cla
* [x] Tests added/passed
* [x] docs fixed
* [x] The core one cometh

## Validation Steps

Tests, manual wailing.

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
The new test passes, but the `split-pane` tests are broken because we yeeted automatic in at the last second.

**Comment by zadjii-msft** [comment]
> the `split-pane` tests are broken because we yeeted automatic in at the last second.

what? no, I would _never_ not run the tests like that O_o

File: src/cascadia/LocalTests_TerminalApp/CommandlineTest.cpp [hunk 1]
```diff
@@ -971,21 +971,69 @@ namespace TerminalAppLocalTests
                 L"Pass a flag that would be accepted by split-pane, but isn't accepted by new-tab"));
             AppCommandlineArgs appArgs{};
             std::vector<const wchar_t*> rawCommands{ L"wt.exe", L"slpit-pane", L"-H" };
```
Comment (miniksa) [inline src/cascadia/LocalTests_TerminalApp/CommandlineTest.cpp]: Is "slpit-pane" an intentional typo in this whole file?

Comment (DHowett-MSFT) [reply src/cascadia/LocalTests_TerminalApp/CommandlineTest.cpp]: You’re reading the TypoTests so yes

Comment (miniksa) [reply src/cascadia/LocalTests_TerminalApp/CommandlineTest.cpp]: Derp ok.

**Comment by DHowett-MSFT** [comment]
I learned from the CLI11 folks that we don't actually need the string+vector version
