### PR TITLE
Fix Ctrl+Alt not being treated as a substitute for AltGr anymore

### LINKED ISSUE #5525: Ctrl+Alt+'char' generates other chars then 'AltGr' (Germany Layout) v0.11.1121.0
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.19041.0
Windows Terminal version (if applicable): v0.11.1121.0
```

# Steps to reproduce
In german keyboard layout type `Ctrl+Alt+<` (or any other key that has a 3rd char on it).

# Expected behavior
Shows the same as `AltGr+<`
the pipe char: `|` 

# Actual behavior
Shows the `#` hash sign.

# Additional remarks
This started on v0.11 till the fixing of AltGr months ago, this didn't happen till today.
On german keyboard layout at least, AltGr+key and Ctrl+Alt+key always return the same char.

some other examples on pwsh:
| Key  | AltGr  | Ctrl+Alt  |
|---|---|---|
| <  | Pipe  | # |
| q | @ | " |
| e | € | € |
| 7 | { | ^[ |
| 8 | [ | ^[ |
| 9 | ] | + |
| + | ~ | & |

cmd in terminal returns also different chars but other (mostly `^]` or `^\`)
wsl doesn't support Ctrl+Alt at all, but I don't need it there and I'm not sure, if it worked there till v0.11,

I mostly recognized this problem while typing PowerShell, cause its way faster to create the `|` (pipe) using `Ctrl+Alt+<` on the left side of the keyboard then `AltGr+<` cause this would require two hands.

### PR DESCRIPTION
**Pull request by lhecker**
## Summary of the Pull Request

This PR fixes #5525 by re-adding range checks that where erroneously removed in a9c9714.

## PR Checklist
* [x] Closes #5525
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [x] Tests added/passed
* [ ] Requires documentation to be updated
* [x] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #5525

## Validation Steps Performed

* Enabled a German keyboard layout
* Entered `<`, `+`, `7`, `8`, `9`, `0` while holding either Alt+Ctrl or AltGr and...
* Ensuring that both produce `|`, `~`, `{`, `[`, `]`, `}`

### CODE REVIEW

File: src/terminal/input/terminalInput.cpp [hunk 1]
```diff
@@ -498,16 +498,16 @@ bool TerminalInput::HandleKey(const IInputEvent* const pInEvent)
         if (ch == UNICODE_NULL)
         {
             // For Alt+Ctrl+Key messages GetCharData() returns 0.
+            // The values of the ASCII characters and virtual key codes
+            // of <Space>, A-Z (as used below) are numerically identical.
             // -> Get the char from the virtual key.
-            ch = LOWORD(MapVirtualKeyW(keyEvent.GetVirtualKeyCode(), MAPVK_VK_TO_CHAR));
+            ch = keyEvent.GetVirtualKeyCode();
```
Comment (lhecker) [inline src/terminal/input/terminalInput.cpp:504]: I've taken the liberty to remove this call to `MapVirtualKeyW`.
As far as I now understood virtual key codes in Windows, the numeric values of the vkeys for Space and A-Z are identical with their respective ASCII value. As such a call to `MapVirtualKeyW` is IMO unnecessary.
Am I seing this correctly?

File: src/terminal/input/terminalInput.cpp [hunk 2]
```diff
@@ -530,7 +530,7 @@ bool TerminalInput::HandleKey(const IInputEvent* const pInEvent)
 
     // This section is similar to the Alt modifier section above,
     // but handles cases without Ctrl modifiers.
-    if (keyEvent.IsAltPressed() && keyEvent.GetCharData() != 0)
+    if (keyEvent.IsAltPressed() && !keyEvent.IsCtrlPressed() && keyEvent.GetCharData() != 0)
```
Comment (lhecker) [inline src/terminal/input/terminalInput.cpp:533]: I've had to add these two additional checks, because `Alt+Ctrl` combinations actually sometimes do carry character data!
For instance `Ctrl+Alt+<` will send an `KeyEvent` with the CharData being `|`. 😲
The old condition here (`keyEvent.IsAltPressed() && keyEvent.GetCharData() != 0`) would thus incorrectly match and `Ctrl+Alt+<` would send `^[|` instead of `|`.

**Comment by lhecker** [comment]
BTW did something change recently?
My Dev build feels ***crazy*** snappy nowadays, even if I got a debugger attached. 🤯
That definitely wasn't the case a month ago or so. Is this because of the new `til::bitmap` rendering?

**Comment by DHowett-MSFT** [comment]
I hope that's it 😁

File: src/terminal/input/terminalInput.cpp (hunk 1 above)
Comment (DHowett-MSFT) [reply src/terminal/input/terminalInput.cpp:504]: I believe you are correct.

File: src/terminal/input/terminalInput.cpp [hunk 3]
```diff
@@ -498,16 +498,16 @@ bool TerminalInput::HandleKey(const IInputEvent* const pInEvent)
...
-            // Ctrl+@ and Ctrl+Space are supposed to send null bytes.
-            // -> Change Ctrl+Space to Ctrl+@ for compatibility reasons.
-            ch = 0x40;
-        }
-        if (ch >= 0x40 && ch < 0x7F)
+        // Alt+Ctrl acts as a substitute for AltGr on Windows.
+        // For instance using a German keyboard both AltGr+< and Alt+Ctrl+< produce a | (pipe) character.
+        // The below condition primitively ensures that we allow all common Alt+Ctrl combinations
+        // while preserving most of the functionality of Alt+Ctrl as a substitute for AltGr.
+        if (ch == UNICODE_SPACE || (ch > 0x40 && ch <= 0x5A))
```
Comment (DHowett-MSFT) [inline src/terminal/input/terminalInput.cpp:510]: Oh, I see: this change is safe because `0x20 & 0b11111` is 0 (we didn't need to set it to 0x40 just to strip off the top few bits). Clever.

Comment (lhecker) [reply src/terminal/input/terminalInput.cpp:510]: @DHowett-MSFT Did you ever see this article? https://garbagecollected.org/2017/01/31/four-column-ascii/
You probably know everything about this already, but for me it was pretty eye opening regardless...
It quickly shows you _why_ `^␣` is actually the same as `^@` and why `^[` is the same as the ESC character. It's a much better representation of ASCII as the square one you can find everywhere else (including Wikipedia). 🙂

Comment (zadjii-msft) [reply src/terminal/input/terminalInput.cpp:510]: I actually used to have a giant version of [this table](http://www.asciitable.com/) printed in my office, which has been immensely helpful

**Comment by mintty** [comment]
I think this is a misguided change and should be reverted, see my comment at
https://github.com/microsoft/terminal/issues/5525#issuecomment-627868323

**Comment by DHowett** [comment]
:tada: Once again, thanks for the contribution!

This pull request was included in a set of conhost changes that was just
released with [Windows Insider Build 20161](https://blogs.windows.com/windowsexperience/2020/07/01/announcing-windows-10-insider-preview-build-20161/).
