### PR TITLE
Send an updated cursor position at the end of writing a run

### LINKED ISSUE #11170: TermControl does not receive enough `_CursorPositionChanged` events
### Windows Terminal version (or Windows build number)

1.12

### Other Software

_No response_

### Steps to reproduce

1. Start Terminal in debug mode
2. Set a breakpoint at `TermControl::_CursorPositionChanged`
3. Enter some input (without any newlines)

### Expected Behavior

The breakpoint at `TermControl::_CursorPositionChanged` should get hit

### Actual Behavior

The breakpoint does not get hit, it only gets hit when the input contains a newline

### PR DESCRIPTION
**Pull request by zadjii-msft**
I can find the commit where this regressed tomorrow if needed. In #10685 we stopped emitting these notifications while we were deferring cursor drawing. We however forgot to send the notification at the end of the defer.

This likely has a small perf impact. We however do need these cursor position events for IMEs to be able to track the cursor position (and low key for #10821)

* [x] regressed in #10685
* [x] Closes #11170
* [x] I work here
* [x] Tests added

### CODE REVIEW

**Comment by DHowett** [comment]
Can you confirm that this fixes IME tracking when the cursor moves within a line?

File: src/cascadia/TerminalCore/Terminal.cpp [hunk 1]
```diff
@@ -989,6 +989,7 @@ void Terminal::_WriteBuffer(const std::wstring_view& stringView)
     }
 
     cursor.EndDeferDrawing();
+    _NotifyTerminalCursorPositionChanged();
```
Comment (lhecker) [inline src/cascadia/TerminalCore/Terminal.cpp:992]: If we do it like that, I believe it's easier to understand if you remove the call to `_NotifyTerminalCursorPositionChanged` from `_AdjustCursorPosition` entirely and instead add it at the end of `CursorLineFeed`.

That way both functions have the exact same "code structure" of calling `_NotifyTerminalCursorPositionChanged` at the end. This would feel more consistent and logical to me.

Comment (zadjii-msft) [reply src/cascadia/TerminalCore/Terminal.cpp:992]: Alternatively, we might be able to get away with once _per `Write`_...

**Comment by zadjii-msft** [comment]
> Can you confirm that this fixes IME tracking when the cursor moves within a line?

Any idea which IME this applied to? I'm trying Chinese with this branch and Preview and the behave the same, but I'm not sure they ever moved the cursor as the user typed. I'll try and chase down a build before this regressed

**Comment by zadjii-msft** [comment]
Actually, did this ever work? tried out 1.10 (before #10685 landed) and for both the Chinese and Japanese IMEs the cursor would stay affixed to the start of the proposed text, then move to the end when the text was accepted. Korean is a little different, it seems to compose and move glyph by glyph, but that still seemed fine and unchanged between 1.10 and 1.13 selfhost.

**Comment by zadjii-msft** [comment]
https://github.com/microsoft/terminal/pull/5135

Okay, now I see it. It's in Korean composition, where the next glyph would draw on top of the previous one. Yes, this fixes that ☺️

**Review by lhecker — APPROVED** [review]
Uh neat!

**Review by DHowett — APPROVED** [review]
