### PR TITLE
Fix focus issue when profile selected from nested menu entry

### LINKED ISSUE #15049: Focus starts on titlebar when opening a profile from a nested dropdown entry
### Windows Terminal version

1.17.1023

### Windows build number

10.0.19045.0

### Other Software

_No response_

### Steps to reproduce

Adding a profile like this in wt 1.16.10261.0 starts the profile with keyboard focus on the command shell

When I use the preview version, focus is on the titlebar, so I have to tab 2x to switch to the command shell

```json
            {
                "commandline": "ssh -i \"%USERPROFILE%\\.ssh\\my-super-secret-key.pem\" ec2-user@10.161.0.101",
                "experimental.retroTerminalEffect": true,
                "guid": "{8e690e45-db6d-47c5-919a-68a86077f9dd}",
                "hidden": false,
                "name": "ec2:kpk-my-super-awesome-ec2-name",
                "suppressApplicationTitle": true
            }
```

I am using the fabulous new folders feature
```json
        {
            "type": "folder",
            "name": "ssh",
            "entries": [
                {
                    "profile": "ec2:kpk-my-super-awesome-ec2-name",
                    "type": "profile"
                }
            ]
        }
```

### Expected Behavior

focus in command shell

### Actual Behavior

focus in titlebar

### PR DESCRIPTION
**Pull request by kkostrzewa**
Original bug report #15049
Relates to feature #1571 

MenuFlyoutSubItem, when collapsing from profile selection, move focus back to the titlebar. 
An extra Closing event handler is needed to keep focus on the command shell.

Closes #15049

### CODE REVIEW

File: src/cascadia/TerminalApp/TerminalPage.cpp [hunk 1]
```diff
@@ -855,6 +855,10 @@ namespace winrt::TerminalApp::implementation
         newTabFlyout.Opening([this](auto&&, auto&&) {
             _FocusCurrentTab(true);
         });
+        // Necessary for fly-out sub items to get focus on a tab before collapsing. Related to #15049
+        newTabFlyout.Closing([this](auto&&, auto&&) {
+            _FocusCurrentTab(true);
```
Comment (DHowett) [inline src/cascadia/TerminalApp/TerminalPage.cpp:860]: @carlos-zamora, can you do an accessibility pass over this?

**Review by DHowett — CHANGES_REQUESTED** [review]
Oh, dang, that's a small fix! Thanks!

I'm blocking only until Carlos (or someone else!) gets a chance to see how this works for accessibility/assistive tech tools like screen readers. I don't want to unduly damage the keyboarding experience :smile:

**Review by lhecker — APPROVED** [review]

**Comment by zadjii-msft** [comment]
Shhhhhh bot, this is something @carlos-zamora has to do a pass on, not OP

File: src/cascadia/TerminalApp/TerminalPage.cpp (hunk 1 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalApp/TerminalPage.cpp:860]: Works great!

**Review by carlos-zamora — APPROVED** [review]

**Review by DHowett — APPROVED** [review]

**Comment by DHowett** [comment]
@carlos-zamora  did you test it with Narrator

**Comment by carlos-zamora** [comment]
> @carlos-zamora did you test it with Narrator

Yup! Works fine too.
