### PR TITLE
Fix misalignment of Sixel image slices

### LINKED ISSUE #17711: Issue with sixel rendering: stretched bands
### Windows Terminal version

Canary 1.22.2261.0

### Windows build number

10.0.22631.4037 x64

### Description of the problem

I believe I may have found an issue with sixels images rendering.

When displaying sixels images with a transparent background (by using `P0;1` and not drawing some pixels in any of the colors), it renders perfectly when displayed on its own.
image

But when it gets close to another sixel image, added either on the previous line, or on the second line of the multi-line image with transparency, its width gets weird.

image

When the other sixel image is added above, the first band/line of the multi-line image gets slightly stretched.
image

When the other sixel image is appended after the second line of the multi-line image, that band gets stretched.
image

Note this also seems to happen in conhost, but with less visible stretching (only noticeable at some font sizes).

### Steps to reproduce

Here is the repro text file: [test.txt](https://github.com/user-attachments/files/16611729/test.txt)

### Expected Behavior

The sixel images to keep their dimensions regardless of other contents displayed in the terminal.

### Actual Behavior

Sixel images sometimes get distorted with some bands stretched when other contents is displayed near them.

### PR DESCRIPTION
**Pull request by j4james**
## Summary of the Pull Request

When we have a series of image slices of differing widths, which also
don't align with the cell boundaries, we can get rounding errors in the
scaling which makes the different slices appear misaligned.

This PR fixes the issue by removing the 4 pixel width alignment that was
enforced in the `ImageSlice` class, since that's not actually necessary
when the pixels themselves are already 4 bytes in size. And without
that, the widths should be correctly aligned with the cell boundaries.

## References and Relevant Issues

The initial Sixel implementation was added in PR #17421.

## Validation Steps Performed

I've confirmed that this fixes the rendering glitches reported in
#17711, and all my existing Sixel tests still work as expected.

## PR Checklist
- [x] Closes #17711

### CODE REVIEW

File: src/renderer/gdi/paint.cpp [hunk 1]
```diff
@@ -685,7 +685,7 @@ try
     const auto srcWidth = imageSlice.PixelWidth();
     const auto srcHeight = srcCellSize.height;
     const auto dstWidth = srcWidth * dstCellSize.width / srcCellSize.width;
-    const auto dstHeight = srcHeight * dstCellSize.height / srcCellSize.height;
+    const auto dstHeight = dstCellSize.height;
```
Comment (j4james) [inline src/renderer/gdi/paint.cpp:688]: This is just a little optimization that I noticed when investigating the rounding problems. The `srcHeight` is always `srcCellSize.height`, so the `dstHeight` should always be `dstCellSize.height`.

**Comment by j4james** [comment]
I'm assuming the audit failure is because the build server has a new version of the compiler.

**Review by DHowett — APPROVED** [review]
Wow, that's subtle. Thanks!

**Comment by DHowett** [comment]
Don't worry about audit mode - #17723

**Review by lhecker — APPROVED** [review]

**Comment by PhMajerus** [comment]
Thanks for this fix!
I can confirm it fixed my test file, as well as my original observation that made me investigate the issue:
image

Being able to display icons in the terminal is so nice, so many new possibilities, I have to write a Sixel conversion component.
