### PR TITLE
Fix text selection while new lines are being printed when history buffer is full

### LINKED ISSUE #10319: Unable to select text correctly while new lines are printed and history buffer is full
### Windows Terminal version (or Windows build number)

10.0.19043.0, 1.8.1444.0

### Other Software

_No response_

### Steps to reproduce

1. Set `"historySize": 100,` for the profile.
2. Run a script that echoes new lines
3. Try to select text

Example script to test the issue:
```powershell
Do {
	echo $(Get-Random)
	sleep 0.1
}
while ($true)
```

The history buffer must be full for this to trigger.

See attached video:

https://user-images.githubusercontent.com/613331/120690411-d9f48880-c4ad-11eb-8f84-e930b5783dfc.mp4

### Expected Behavior

Correctly select text. It works when the history buffer is full.

### Actual Behavior

The selection scrolls away from you, selecting different text.

### PR DESCRIPTION
**Pull request by PankajBhojwani**
When our text buffer is full, newlines cause the buffer to scroll underneath the viewport (rather than the viewport moving down). This was causing selections made during text output to scroll down. To solve this, when we increment the circular buffer, we decrement the y-coordinates of the current selections by 1. We also invalidate the previous selection rects.

Closes #10319

### CODE REVIEW

File: src/renderer/base/renderer.cpp [hunk 1]
```diff
@@ -466,17 +466,22 @@ void Renderer::TriggerScroll(const COORD* const pcoordDelta)
...
         LOG_IF_FAILED(hr);
 
+        LOG_IF_FAILED(pEngine->InvalidateSelection(rects));
+
         if (SUCCEEDED(hr) && fEngineRequestsRepaint)
         {
             LOG_IF_FAILED(_PaintFrameForEngine(pEngine));
         }
     }
+    _pData->CircleSelections();
```
Comment (DHowett) [inline src/renderer/base/renderer.cpp:484]: I'm a bit concerned about this, actually. I think this is the **first** instance where the renderer can _change data in the terminal_. I don't think we should ever allow that; rather, we should handle this before it even gets to the renderer.

(Aside: the renderer telling us about circling so that we can do something about it is a very long game of telephone. Terminal -> Buffer -> Renderer -> Terminal again.)

**Review by DHowett — CHANGES_REQUESTED** [review]

File: src/renderer/base/renderer.cpp (hunk 1 above)
Comment (PankajBhojwani) [reply src/renderer/base/renderer.cpp]: *facepalm* yes that makes much more sense

Comment (PankajBhojwani) [reply src/renderer/base/renderer.cpp]: fixed

File: src/cascadia/TerminalCore/Terminal.cpp [hunk 2]
```diff
@@ -1004,6 +1004,13 @@ void Terminal::_AdjustCursorPosition(const COORD proposedPosition)
             _buffer->IncrementCircularBuffer();
             proposedCursorPosition.Y--;
             rowsPushedOffTopOfBuffer++;
+
+            // Update our selection too, so it doesn't move as the buffer is cycled
+            if (_selection)
+            {
+                _selection->start.Y -= 1;
```
Comment (DHowett) [inline src/cascadia/TerminalCore/Terminal.cpp:1011]: What if the selection starts to go off the top of the screen (Y=0)?

Comment (PankajBhojwani) [reply src/cascadia/TerminalCore/Terminal.cpp]: Updated, if start.Y is at 0, we only reduce end.Y (if end.Y is greater than 0). If both are at 0, we clear the selection

Comment (PankajBhojwani) [reply src/cascadia/TerminalCore/Terminal.cpp]: Update: if we're only reducing end.Y, then we also set start.X = 0 to keep the block selection

**Review by carlos-zamora — APPROVED** [review]

File: src/cascadia/UnitTests_Control/ControlInteractivityTests.cpp [hunk 3]
```diff
@@ -634,4 +635,74 @@ namespace ControlUnitTests
...
+    void ControlInteractivityTests::IncrementCircularBufferWithSelection()
+    {
+        // This is a test for GH#10749
+        WEX::TestExecution::DisableVerifyExceptions disableVerifyExceptions{};
+
+        auto [settings, conn] = _createSettingsAndConnection();
+        auto [core, interactivity] = _createCoreAndInteractivity(*settings, *conn);
+        _standardInit(core, interactivity);
+
+        interactivity->_rowsToScroll = 1;
```
[the remark this answers is not in the document]
Comment (PankajBhojwani) [reply src/cascadia/UnitTests_Control/ControlInteractivityTests.cpp:648]: Thanks for the catch!

File: src/cascadia/UnitTests_Control/ControlInteractivityTests.cpp [hunk 4]
```diff
@@ -634,4 +635,74 @@ namespace ControlUnitTests
...
+        VERIFY_ARE_EQUAL(expectedAnchor, core->_terminal->GetSelectionEnd());
+
+        Log::Comment(L"Output a line of text");
+        conn->WriteInput(L"foo\r\n");
+
+        Log::Comment(L"Verify the location of the selection");
+        // The selection should now be 1 row lower
+        expectedAnchor.Y -= 1;
+        VERIFY_ARE_EQUAL(expectedAnchor, core->_terminal->GetSelectionAnchor());
+        VERIFY_ARE_EQUAL(expectedAnchor, core->_terminal->GetSelectionEnd());
```
[the remark this answers is not in the document]
Comment (PankajBhojwani) [reply src/cascadia/UnitTests_Control/ControlInteractivityTests.cpp:706]: Done!

**Comment by zadjii-msft** [comment]
Any chance this also fixes #7524?

**Comment by PankajBhojwani** [comment]
> Any chance this also fixes #7524?

I'm leaning towards no because this fix only touches what happens when we `IncrementCircularBuffer` and #7524 doesn't mention anything about the buffer needing to be full (tho it doesn't mention any other repro steps either so idk maybe?)

**Review by zadjii-msft — APPROVED** [review]

**Review by DHowett — APPROVED** [review]
Thanks!
