### PR TITLE
Make opening the settings file more robust

### LINKED ISSUE #1789: Settings do not open if json files are assigned to gvim
# Environment

```none
Windows build number: Version 10.0.18362.207
Windows Terminal version (if applicable): master

Any other software?
gvim
```

# Steps to reproduce

Install gvim
Assign json files to gvim
Try to open the settings in terminal

# Expected behavior

Gvim opens the settings file
# Actual behavior

Nothing happens

More information:
I have visual studio installed as well. If I change the settings so visual studio is the default handler for json file it works, also notepad. If select gvim from the selection list I can open json files in explorer just fine but trying to open the settings in terminal does not work.
To be honest I am not sure if this is a terminal or vim issue but since terminal is the first application I see this behaviour I filled the bug here.

### PR DESCRIPTION
**Pull request by maru-sama**
This fixes two issues.

 * Opens the assigned default application regardless of its configuration.
   Gvim for example only reacts to the "edit" verb so when selected as default application won't open.
   Using nullptr results in using the first specified application.
   This fixes #1789
 * If no application is assigned for json files fall back to notepad

 See https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shellexecutea for more details
 especially why the result code checking is so horrific.

## PR Checklist
* [x] Closes #1789 
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Requires documentation to be updated
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Validation Steps Performed
* Set a default application and make sure it opens
* Remove the default application and make sure that notepad gets opened

### CODE REVIEW

File: src/cascadia/TerminalApp/App.cpp [hunk 1]
```diff
@@ -445,7 +445,12 @@ namespace winrt::TerminalApp::implementation
         co_await winrt::resume_background();
 
         const auto settingsPath = CascadiaSettings::GetSettingsPath();
-        ShellExecute(nullptr, L"open", settingsPath.c_str(), nullptr, nullptr, SW_SHOW);
+
+        HINSTANCE res = ShellExecute(nullptr, nullptr, settingsPath.c_str(), nullptr, nullptr, SW_SHOW);
```
Comment (miniksa) [inline src/cascadia/TerminalApp/App.cpp]: I get the "try something else when the first one fails," but why did you drop the "open" verb?

Also can you leave a comment back to this page https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shellexecutea that explains why the result code checking is so horrific for this API?

Comment (DHowett-MSFT) [reply src/cascadia/TerminalApp/App.cpp]: I think dropping the open verb is also documented there:

>**NULL**
> The default verb is used, if available. If not, the "open" verb is used. If neither verb is available, the system uses the first verb listed in the registry.

That seems strictly better. GVim registers the _edit_ verb (which we learned in #1789!)

Comment (maru-sama) [reply src/cascadia/TerminalApp/App.cpp]: I tried to explain this in the commit message. Gvim only sets up the registry for the "edit" verb so it does not work with the "open" verb. Setting this to NULL solves the issue as well.

> NULL
> The default verb is used, if available. If not, the "open" verb is used. If neither verb is available, > the system uses the first verb listed in the registry.

File: src/cascadia/TerminalApp/App.cpp [hunk 2]
```diff
@@ -445,7 +445,12 @@ namespace winrt::TerminalApp::implementation
         co_await winrt::resume_background();
 
         const auto settingsPath = CascadiaSettings::GetSettingsPath();
-        ShellExecute(nullptr, L"open", settingsPath.c_str(), nullptr, nullptr, SW_SHOW);
+
+        HINSTANCE res = ShellExecute(nullptr, nullptr, settingsPath.c_str(), nullptr, nullptr, SW_SHOW);
+        if ((INT_PTR)res <= 32)
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalApp/App.cpp]: In additional to Michael's comment, I'd prefer a `static_cast<intptr_t>()` versus a C cast, but I'm otherwise totally willing to approve this.

Comment (maru-sama) [reply src/cascadia/TerminalApp/App.cpp]: Let me change this and push again.

Comment (maru-sama) [reply src/cascadia/TerminalApp/App.cpp]: Well apparently only 

> (reinterpret_cast<intptr_t>(res)

works, which I think does the same

Comment (maru-sama) [reply src/cascadia/TerminalApp/App.cpp]: Looking at this some more I think that reinterpret_cast just works since it does not check anything and the static cast fails, hence I will keep it as it is. Feel free to change it.

File: src/cascadia/TerminalApp/App.cpp (hunk 1 above)
Comment (metathinker) [reply src/cascadia/TerminalApp/App.cpp]: @MiNiksa if you're concerned about the oddities of the ShellExecute return value, it might make sense to use ShellExecuteEx instead because that returns true or false.

As to why it's so odd, [it made more sense in 16 bits.](https://devblogs.microsoft.com/oldnewthing/20060505-08/?p=31293)

**Comment by maru-sama** [comment]
> I agree with fixing the c-style cast, but otherwise this is a great fix, thanks!

I tried that before and could not get static_cast to work at all. reinterpre_cast was working but I do not feel comfortable using it here.

**Comment by maru-sama** [comment]
I did find a "fix" for that. but it does not look at nice.

static_cast<int>(reinterpret_cast<uintptr_t>.....

This should get rid if the compiler warnings I get otherwise. Should I add this or leave it like it is right now?

**Comment by maru-sama** [comment]
Hi anything else that I can do to get this merged?
