### PR TITLE
Make all console output modes more strictly buffer state

### LINKED ISSUE #14690: wslsys in alt buffer toggles DISABLE_NEWLINE_AUTO_RETURN
### Windows Terminal version

1.16.2641.0

### Windows build number

10.0.19044.2364

### Other Software

_No response_

### Steps to reproduce

1. Open a WSL bash shell in conhost or Windows Terminal.
2. Switch to the alt buffer with `printf "\e[?1049h"`
3. Test the formfeed behavior with `printf "\e[10CX\b\fY\n"`
4. Run `wslsys`
5. Run the formfeed test again with `printf "\e[10CX\b\fY\n"`

### Expected Behavior

The test case above moves the cursor right 10 columns, outputs an `X`, a `BS` control (moving the cursor back a column), and a `FF` control (moving the cursor down a row), then finally outputs a `Y`.

In both cases the `Y` should be directly below the `X`.

image

### Actual Behavior

After `wslsys` has been run, the `DISABLE_NEWLINE_AUTO_RETURN` mode is turned off, so the `FF` control also triggers a carriage return, and the `Y` is output in the first column.

image

The problem is that the auto-return mode is tracked in two separates places. It's one of the modes of the `OutputMode` field in the `SCREEN_INFORMATION` class, but it's also stored in the `_fAutoReturnOnNewline` flag in the global `Settings`. These two places have different scope!

By default `_fAutoReturnOnNewline` is true, and the `DISABLE_NEWLINE_AUTO_RETURN` mode isn't set. But WSL toggles that state on startup, so in WSL the mode is set, and `_fAutoReturnOnNewline` flag is false. When you switch to the alt buffer, though, you get a new `SCREEN_INFORMATION` instance with the defaults again, so the mode is again not set, but the global `_fAutoReturnOnNewline` is still false!

This isn't immediately a problem, because the line feed operations rely on the `_fAutoReturnOnNewline` flag which still has the correct value. But once you run `wslsys`, it makes a call set `SetConsoleMode` which forces the `_fAutoReturnOnNewline` flag to be refreshed. And although it doesn't change the mode, the mode was already wrong at this point, so that incorrect state is now transferred to the `_fAutoReturnOnNewline` flag.

From then, all the line feed controls will trigger a carriage return, which can be problematic for apps that weren't expecting that behavior. One case in particular is `tmux`, which relies on line feed controls to move down without a carriage return when redrawing the screen. If that isn't correct, the entire display gets messed up. This is at least one of the causes of #6987.

### PR DESCRIPTION
**Pull request by j4james**
The original console output modes were considered attributes of the
buffer, while later additions were treated as global state, and yet both
were accessed via the same buffer-based API. This could result in the
reported modes being out of sync with the way the system was actually
behaving, and a call to `SetConsoleMode` without updating anything could
still trigger unpredictable changes in behavior.

This PR attempts to address that problem by making all modes part of the
buffer state, and giving them predictable default values.

While this won't solve all the tmux layout-breaking issues in #6987, it
does at least fix one case which was the result of an unexpected change
in the `DISABLE_NEWLINE_AUTO_RETURN` mode.

All access to the output modes is now done via the `OutputMode` field in
`SCREEN_INFORMATION`. The fields that were tracking global state in the
`Settings` class (`_fAutoReturnOnNewline` and  `_fRenderGridWorldwide`)
have now been removed.

We still have a global `_dwVirtTermLevel` field, though, but that now
serves as a default value for the `ENABLE_VIRTUAL_TERMINAL_PROCESSING`
mode when creating a new buffer. It's enabled for conpty mode, and when
the VT level in the registry is not 0. That default doesn't change.

For the VT alternate buffer, things works slightly differently, since
there is an expectation that VT modes are global. So when creating an
alt buffer, we copy the current modes from the main buffer, and when
it's closed, we copy them back again.

## Validation Steps Performed

I've manually confirmed that this fixes the problem described in issue
#14690. I've also added a basic feature test that confirms the modes are
initialized as expected when creating new buffers, and changes to the
modes in one buffer do not impact any other buffers.

Closes #14690

### CODE REVIEW

**Comment by j4james** [comment]
I think this is logically the right approach to take, in that the "rules" are straightforward, so the behavior is easily predictable. However, my one concern is with the `ENABLE_VIRTUAL_TERMINAL_PROCESSING` flag - it's possible that there are apps creating multiple console buffers that are also setting the VT mode, and they may expect that they can set it once and have that change "inherited" when creating additional buffers. I don't know if that's a likely scenario though.

**Review by sophacola — APPROVED** [review]

**Review by sophacola — APPROVED** [review]

**Comment by DHowett** [comment]
> So when creating an alt buffer, we copy the current modes from the main buffer, and when it's closed, we copy them back again.

Totally cool with this. Alt buffer being a `SCREEN_INFORMATION` is an implementation detail, not a contract, and doing this simply pays down a debt we incurred by _using_ that implementation detail.

Thanks for doing this.

File: src/host/settings.cpp [hunk 1]
```diff
@@ -376,33 +374,6 @@ void Settings::SetAltF4CloseAllowed(const bool fAllowAltF4Close)
...
-void Settings::SetGridRenderingAllowedWorldwide(const bool fGridRenderingAllowed)
-{
-    // Only trigger a notification and update the status if something has changed.
-    if (_fRenderGridWorldwide != fGridRenderingAllowed)
-    {
-        _fRenderGridWorldwide = fGridRenderingAllowed;
-
-        if (ServiceLocator::LocateGlobals().pRender != nullptr)
-        {
-            ServiceLocator::LocateGlobals().pRender->TriggerRedrawAll();
```
Comment (DHowett) [inline src/host/settings.cpp:401]: Do we need to retain this logic? We might miss a global repaint if we don't, and grid lines that had been written will not appear on demand.

**Review by DHowett — COMMENTED** [review]
Approved with comment - I expect that I've missed something, and there's a second reviewer yet required. :smile:

**Review by DHowett — APPROVED** [review]

**Review by lhecker — APPROVED** [review]
Love the changeset. But @DHowett makes a valid point about the renderer invalidation. I don't know what `ENABLE_LVB_GRID_WORLDWIDE` does (I've never tried it), but I imagine that it requires an invalidation when the setting changes.

File: src/host/settings.cpp (hunk 1 above)
Comment (j4james) [reply src/host/settings.cpp:401]: This redraw was also being done in the `SetConsoleOutputModeImpl` method, so this code was never really necessary. See here:

https://github.com/microsoft/terminal/blob/0eff8c06e32bff6c1e8d39e6505ef8a4c6d8ecbf/src/host/getset.cpp#L443-L454

I should also mention that I wrote some little test apps similar to the functional tests, but which render output to visually confirm the modes are working as expected. And when the `ENABLE_LVB_GRID_WORLDWIDE` mode is toggled, the screen was definitely being refreshed, with the grid line disappearing and reappearing.

**Comment by DHowett** [comment]
That's all I need. Thank you!

**Comment by j4james** [comment]
I know it's a bit late now, since we're merged, but just to be clear, my concern regarding the `ENABLE_VIRTUAL_TERMINAL_PROCESSING` mode is not with the alt buffer, but with people that are using `CreateConsoleScreenBuffer` to create additional buffers. There was a comment in the Console-Docs issue tracker (see https://github.com/MicrosoftDocs/Console-Docs/issues/276#issuecomment-1217248088) which made me realise that some people might be expecting that mode to be inherited.

Technically the current behavior isn't really inheritance anyway, but it's probably close enough for most use cases that are expecting that. But after this PR, you'll need to explicitly set the mode in every buffer you create (not counting the alt buffer). That's assuming you want it changed from the default, i.e. you want to turn it on in cohost, or turn it off in Windows Terminal.

Now I wouldn't have thought there were a lot of apps using `CreateConsoleScreenBuffer` that were also messing with the VT mode, and for those that are, I would hope they're setting the mode explicitly in every buffer anyway (you would already have had to do that for the original modes). But for anyone that isn't doing that, this is potentially a breaking change.

**Comment by DHowett** [comment]
> potentially breaking change

Two weeks ago, I took a note to document this breaking change somewhere. I finally did that here: https://github.com/microsoft/terminal/wiki/Console:-Potential-Breaking-Changes

I'm going to try to make sure we track this stuff a little better, because the Windows release cycle has gotten somewhat longer and it means we accumulate more things like this before people _see_ them.
