### PR TITLE
Set Cascadia Code as default font

### LINKED ISSUE #4943: Make Cascadia Code the default font
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

The default font should be Cascadia Code :)

# Actual behavior

The default font is Consolas

### PR DESCRIPTION
**Pull request by cinnamon-msft**
## Summary of the Pull Request
Changes default font from Consolas to Cascadia Code.

## PR Checklist
* [x] Closes #4943 
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Requires documentation to be updated
* [x] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Validation Steps Performed
I deleted my profiles.json and built from source. All profiles appeared in Cascadia Code.

### CODE REVIEW

File: src/inc/DefaultSettings.h [hunk 1]
```diff
@@ -30,7 +30,7 @@ constexpr short DEFAULT_HISTORY_SIZE = 9001;
 #pragma warning(push)
 #pragma warning(disable : 26426)
 // TODO GH 2674, don't disable this warning, move to std::wstring_view or something like that.
-const std::wstring DEFAULT_FONT_FACE{ L"Consolas" };
+const std::wstring DEFAULT_FONT_FACE{ L"Cascadia Code" };
```
Comment (zadjii-msft) [inline src/inc/DefaultSettings.h]: Oh danger here - this might break the WpfTerminal that VS is using, unless they're also shipping Cascadia Code or Cascadia Code is present in the package - we might have to leave this one

**Comment by cinnamon-msft** [comment]
The font package is up-to-date now, but when we make changes to the font we'll have to update it.

**Comment by DHowett-MSFT** [comment]
@msftbot merge this in 1 minute

**Comment by djee-ms** [comment]
So... neither the commit descriptions nor any linked issue nor the description of this PR describe why this change was done. I personally find this new font utterly ugly, and I have a hard time understanding why the change was made. Can you please document the change @cinnamon-msft?
