### PR TITLE
[deadlock fix] Remove lock for SIUP::GetSelectionRange()

### LINKED ISSUE #11385: Open narrator, select some text in the Terminal ---> experience a hang
as in title. 1.12.whatever-the-selfhost-build-is

no repro on 1.10.2383.0
Repro on 1.12.2712.0

Other than the like 80 nvidia threads:

```
0:209> ~*k

   0  Id: c528.7b5c Suspend: 1 Teb: 000000b4`cbaa8000 Unfrozen
 # Child-SP          RetAddr               Call Site
00 000000b4`cb97d988 00007ffe`43ece753     ntdll!ZwWaitForAlertByThreadId+0x14 [minkernel\ntdll\daytona\objfre\amd64\usrstubs.asm @ 4051] 
01 000000b4`cb97d990 00007ffe`43ece8a0     ntdll!RtlpWaitOnAddressWithTimeout+0x9f [minkernel\ntos\rtl\waitaddr.c @ 851] 
02 000000b4`cb97d9c0 00007ffe`43ecd733     ntdll!RtlpWaitOnAddress+0xd8 [minkernel\ntos\rtl\waitaddr.c @ 1094] 
03 000000b4`cb97da30 00007ffe`4137503f     ntdll!RtlWaitOnAddress+0x13 [minkernel\ntos\rtl\waitaddr.c @ 946] 
04 000000b4`cb97da70 00007ffd`7a49d12a     KERNELBASE!WaitOnAddress+0x2f [minkernel\kernelbase\synch.c @ 2258] 
05 000000b4`cb97dab0 00007ffd`7a4a35a0     Microsoft_Terminal_Control!til::atomic_wait<unsigned int>+0x3a [D:\dev\public\terminal\src\inc\til\atomic.h @ 14] 
06 000000b4`cb97dae0 00007ffd`7a4a40d9     Microsoft_Terminal_Control!til::ticket_lock::lock+0xb0 [D:\dev\public\terminal\src\inc\til\ticket_lock.h @ 35] 
07 000000b4`cb97db60 00007ffd`7a377804     Microsoft_Terminal_Control!Microsoft::Terminal::Core::Terminal::LockConsole+0x29 [D:\dev\public\terminal\src\cascadia\TerminalCore\TerminalRenderData.cpp @ 236] 
08 000000b4`cb97db90 00007ffd`7a371da0     Microsoft_Terminal_Control!Microsoft::Terminal::TermControlUiaProvider::GetSelectionRange+0x104 [D:\dev\public\terminal\src\types\TermControlUiaProvider.cpp @ 118] 
09 000000b4`cb97dd30 00007ffd`7a299bed     Microsoft_Terminal_Control!Microsoft::Console::Types::ScreenInfoUiaProviderBase::GetSelection+0x540 [D:\dev\public\terminal\src\types\ScreenInfoUiaProviderBase.cpp @ 247] 
0a 000000b4`cb97df30 00007ffd`7a2aaf25     Microsoft_Terminal_Control!winrt::Microsoft::Terminal::Control::implementation::InteractivityAutomationPeer::GetSelection+0x9d [D:\dev\public\terminal\src\cascadia\TerminalControl\InteractivityAutomationPeer.cpp @ 96] 
0b 000000b4`cb97dfc0 00007ffd`7a2e57d0     Microsoft_Terminal_Control!winrt::impl::produce<winrt::Microsoft::Terminal::Control::implementation::InteractivityAutomationPeer,winrt::Windows::UI::Xaml::Automation::Provider::ITextProvider>::GetSelection+0xa5 [D:\dev\public\terminal\src\cascadia\TerminalControl\Generated Files\winrt\Windows.UI.Xaml.Automation.Provider.h @ 1471] 
0c 000000b4`cb97e080 00007ffd`7a2dd540     Microsoft_Terminal_Control!winrt::impl::consume_Windows_UI_Xaml_Automation_Provider_ITextProvider<winrt::Microsoft::Terminal::Control::InteractivityAutomationPeer>::GetSelection+0xc0 [D:\dev\public\terminal\src\cascadia\TerminalControl\Generated Files\winrt\Windows.UI.Xaml.Automation.Provider.h @ 486] 
0d 000000b4`cb97e130 00007ffd`7a2e5905     Microsoft_Terminal_Control!winrt::Microsoft::Terminal::Control::implementation::TermControlAutomationPeer::GetSelection+0x40 [D:\dev\public\terminal\src\cascadia\TerminalControl\TermControlAutomationPeer.cpp @ 200] 
0e 000000b4`cb97e170 00007ffe`155b563e     Microsoft_Terminal_Control!winrt::impl::produce<winrt::Microsoft::Terminal::Control::implementation::TermControlAutomationPeer,winrt::Windows::UI::Xaml::Automation::Provider::ITextProvider>::GetSelection+0xa5 [D:\dev\public\terminal\src\cascadia\TerminalControl\Generated Files\winrt\Windows.UI.Xaml.Automation.Provider.h @ 1471] 
0f 000000b4`cb97e230 00007ffe`15b65658     Windows_UI_Xaml!DirectUI::AutomationPeer::UIAPatternInvoke+0x2942 [onecoreuap\windows\dxaml\xcp\dxaml\lib\automationpeer_partial.cpp @ 3102] 
10 (Inline Function) --------`--------     Windows_UI_Xaml!CFxCallbacks::AutomationPeer_UIAPatternInvoke+0x33 [onecoreuap\windows\dxaml\xcp\dxaml\lib\fxcallbacks.cpp @ 1250] 
11 000000b4`cb97e4e0 00007ffe`15c9b570     Windows_UI_Xaml!CManagedTextProvider::GetSelection+0x58 [onecoreuap\windows\dxaml\xcp\core\core\elements\uiapatternprovider.cpp @ 1251] 
12 000000b4`cb97e560 00007ffe`15c9b297     Windows_UI_Xaml!CUIATextProviderWrapper::GetSelectionImpl+0x58 [onecoreuap\windows\dxaml\xcp\win\shared\uiapatternproviderwrapper.cpp @ 3846] 
13 000000b4`cb97e590 00007ffe`13f84d0d     Windows_UI_Xaml!CUIATextProviderWrapper::GetSelection+0x57 [onecoreuap\windows\dxaml\xcp\win\shared\uiapatternproviderwrapper.cpp @ 3793] 
14 000000b4`cb97e610 00007ffe`13f51027     uiautomationcore!ProviderCallouts::GetSelection+0x49 [onecore\windows\accessibletech\uiautomationcore\ProviderCallouts.h @ 1236] 
15 000000b4`cb97e650 00007ffe`13ef6ab6     uiautomationcore!RemotePatternStub::Text_GetSelection+0x67 [onecore\windows\accessibletech\uiautomationcore\remotepatternstub.cpp @ 836] 
16 000000b4`cb97e690 00007ffe`13ef5563     uiautomationcore!RemotePatternStub::OnMessage+0x66 [onecore\windows\accessibletech\uiautomationcore\remotepatternstub.cpp @ 125] 
17 000000b4`cb97e6e0 00007ffe`2bd3144a     uiautomationcore!InvokePatternMethodOnCorrectContext_Callback+0xe3 [onecore\windows\accessibletech\uiautomationcore\serverconnection.cpp @ 1762] 
18 (Inline Function) --------`--------     OneCoreCommonProxyStub!IServiceProvider_QueryService_Stub+0x1e [onecore\merged\commonproxystub\dll\call_as.c @ 25] 
19 000000b4`cb97e760 00007ffe`41eea68e     OneCoreCommonProxyStub!IServiceProvider_RemoteQueryService_Thunk+0x3a [onecore\inetcore\published\sdk\inc\objfre\amd64\servprov_p.c @ 175] 
1a 000000b4`cb97e7a0 00007ffe`41e29192     RPCRT4!Ndr64StubWorker+0xd0e [minio\rpc\ndr64\srvcall.cxx @ 353] 
1b 000000b4`cb97ee50 00007ffe`433df47a     RPCRT4!NdrStubCall3+0xd2 [minio\rpc\ndr64\srvwrap.cxx @ 166] 
1c 000000b4`cb97eeb0 00007ffe`41e66d55     combase!CStdStubBuffer_Invoke+0xca [onecore\com\combase\ndr\ndrole\stub.cxx @ 1583] 
1d 000000b4`cb97eef0 00007ffe`433aa27d     RPCRT4!CStdStubBuffer_Invoke+0x45 [minio\rpc\ndr20\ndrfwds.cxx @ 182] 
1e (Inline Function) --------`--------     combase!InvokeStubWithExceptionPolicyAndTracing::__l6::<lambda_c9f3956a20c9da92a64affc24fdd69ec>::operator()+0x22 [onecore\com\combase\dcomrem\channelb.cxx @ 1160] 
1f 000000b4`cb97ef20 00007ffe`433aa017     combase!ObjectMethodExceptionHandlingAction<<lambda_c9f3956a20c9da92a64affc24fdd69ec> >+0x4d [onecore\com\combase\dcomrem\excepn.hxx @ 94] 
20 (Inline Function) --------`--------     combase!InvokeStubWithExceptionPolicyAndTracing+0xda [onecore\com\combase\dcomrem\channelb.cxx @ 1158] 
21 000000b4`cb97ef80 00007ffe`433e1978     combase!DefaultStubInvoke+0x257 [onecore\com\combase\dcomrem\channelb.cxx @ 1227] 
22 000000b4`cb97f0d0 00007ffe`4337877b     combase!SyncServerCall::StubInvoke+0x38 [onecore\com\combase\dcomrem\ServerCall.hpp @ 799] 
23 (Inline Function) --------`--------     combase!StubInvoke+0x2d8 [onecore\com\combase\dcomrem\channelb.cxx @ 1509] 
24 000000b4`cb97f110 00007ffe`4339c3bf     combase!ServerCall::ContextInvoke+0x46b [onecore\com\combase\dcomrem\ctxchnl.cxx @ 1425] 
25 (Inline Function) --------`--------     combase!CServerChannel::ContextInvoke+0x16b [onecore\com\combase\dcomrem\ctxchnl.cxx @ 1332] 
26 (Inline Function) --------`--------     combase!DefaultInvokeInApartment+0x16b [onecore\com\combase\dcomrem\callctrl.cxx @ 3297] 
27 000000b4`cb97f3f0 00007ffe`4336e114     combase!ReentrantSTAInvokeInApartment+0x1df [onecore\com\combase\dcomrem\reentrantsta.cpp @ 113] 
28 000000b4`cb97f470 00007ffe`4334634c     combase!ComInvokeWithLockAndIPID+0xa14 [onecore\com\combase\dcomrem\channelb.cxx @ 2246] 
29 000000b4`cb97f750 00007ffe`43344be9     combase!ThreadDispatch+0x43c [onecore\com\combase\dcomrem\channelb.cxx @ 1668] 
2a 000000b4`cb97f870 00007ffe`437e9b48     combase!ThreadWndProc+0x109 [onecore\com\combase\dcomrem\chancont.cxx @ 720] 
2b 000000b4`cb97f8e0 00007ffe`437e8299     user32!UserCallWinProcCheckWow+0x338 [clientcore\windows\core\ntuser\client\clmsg.cxx @ 282] 
2c 000000b4`cb97fa50 00007ff6`f652fb9f     user32!DispatchMessageWorker+0x1c9 [clientcore\windows\core\ntuser\client\clmsg.cxx @ 3167] 
2d 000000b4`cb97fad0 00007ff6`f6633d72     WindowsTerminal!wWinMain+0x25f [D:\dev\public\terminal\src\cascadia\WindowsTerminal\main.cpp @ 198] 
2e 000000b4`cb97fc90 00007ff6`f6633c9e     WindowsTerminal!invoke_main+0x32 [d:\a01\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 123] 
2f 000000b4`cb97fcd0 00007ff6`f6633b5e     WindowsTerminal!__scrt_common_main_seh+0x12e [d:\a01\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 288] 
30 000000b4`cb97fd40 00007ff6`f6633dee     WindowsTerminal!__scrt_common_main+0xe [d:\a01\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 331] 
31 000000b4`cb97fd70 00007ffe`42e86ab0     WindowsTerminal!wWinMainCRTStartup+0xe [d:\a01\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_wwinmain.cpp @ 17] 
32 000000b4`cb97fda0 00007ffe`43edc44b     KERNEL32!BaseThreadInitThunk+0x10 [clientcore\base\win32\client\thread.c @ 75] 
33 000000b4`cb97fdd0 00000000`00000000     ntdll!RtlUserThreadStart+0x2b [minkernel\ntdll\rtlstrt.c @ 1152] 

   1  Id: c528.922c Suspend: 1 Teb: 000000b4`cbaac000 Unfrozen
 # Child-SP          RetAddr               Call Site
00 000000b4`cbdffb28 00007ffe`43ed79ef     ntdll!ZwWaitForWorkViaWorkerFactory+0x14 [minkernel\ntdll\daytona\objfre\amd64\usrstubs.asm @ 4075] 
01 000000b4`cbdffb30 00007ffe`42e86ab0     ntdll!TppWorkerThread+0x2df [minkernel\threadpool\ntdll\worker.c @ 910] 
02 000000b4`cbdffe20 00007ffe`43edc44b     KERNEL32!BaseThreadInitThunk+0x10 [clientcore\base\win32\client\thread.c @ 75] 
03 000000b4`cbdffe50 00000000`00000000     ntdll!RtlUserThreadStart+0x2b [minkernel\ntdll\rtlstrt.c @ 1152] 

   2  Id: c528.97a8 Suspend: 1 Teb: 000000b4`cbab0000 Unfrozen
 # Child-SP          RetAddr               Call Site
00 000000b4`cbffe6e8 00007ffe`4133590e     ntdll!ZwWaitForSingleObject+0x14 [minkernel\ntdll\daytona\objfre\amd64\usrstubs.asm @ 251] 
01 000000b4`cbffe6f0 00007ffd`a053408d     KERNELBASE!WaitForSingleObjectEx+0x8e [minkernel\kernelbase\synch.c @ 1328] 
02 000000b4`cbffe790 00007ffd`a053412c     Microsoft_Terminal_Remoting!winrt::impl::wait_for_completed<winrt::Windows::Foundation::IAsyncOperation<winrt::hstring> >+0xed [d:\dev\public\terminal\src\cascadia\Remoting\Generated Files\winrt\Windows.Foundation.h @ 3294] 
03 000000b4`cbffe820 00007ffd`a053fa32     Microsoft_Terminal_Remoting!winrt::impl::wait_get<winrt::Windows::Foundation::IAsyncOperation<winrt::hstring> >+0x4c [d:\dev\public\terminal\src\cascadia\Remoting\Generated Files\winrt\Windows.Foundation.h @ 3322] 
04 000000b4`cbffe860 00007ffd`a052dff5     Microsoft_Terminal_Remoting!winrt::impl::consume_Windows_Foundation_IAsyncOperation<winrt::Windows::Foundation::IAsyncOperation<winrt::hstring>,winrt::hstring>::get+0x32 [d:\dev\public\terminal\src\cascadia\Remoting\Generated Files\winrt\Windows.Foundation.h @ 3425] 
05 000000b4`cbffe8a0 00007ffd`a0539fb4     Microsoft_Terminal_Remoting!winrt::Microsoft::Terminal::Remoting::implementation::Peasant::GetWindowLayout+0xf5 [d:\dev\public\terminal\src\cascadia\Remoting\Peasant.cpp @ 309] 
06 000000b4`cbffe970 00007ffd`a0508fba     Microsoft_Terminal_Remoting!winrt::impl::produce<winrt::Microsoft::Terminal::Remoting::implementation::Peasant,winrt::Microsoft::Terminal::Remoting::IPeasant>::GetWindowLayout+0x94 [d:\dev\public\terminal\src\cascadia\Remoting\Generated Files\winrt\Microsoft.Terminal.Remoting.h @ 1247] 
07 000000b4`cbffea00 00007ffd`a04df5fc     Microsoft_Terminal_Remoting!winrt::impl::consume_Microsoft_Terminal_Remoting_IPeasant<winrt::Microsoft::Terminal::Remoting::IPeasant>::GetWindowLayout+0xaa [d:\dev\public\terminal\src\cascadia\Remoting\Generated Files\winrt\Microsoft.Terminal.Remoting.h @ 310] 
08 000000b4`cbffea90 00007ffd`a04e6034     Microsoft_Terminal_Remoting!<lambda_fc1a410c0531896355b3e1a4af608fe1>::operator()<unsigned __int64,winrt::Microsoft::Terminal::Remoting::IPeasant>+0x3c [d:\dev\public\terminal\src\cascadia\Remoting\Monarch.cpp @ 1015] 
09 000000b4`cbffeaf0 00007ffd`a04d8c7b     Microsoft_Terminal_Remoting!winrt::Microsoft::Terminal::Remoting::implementation::Monarch::_forEachPeasant<<lambda_fc1a410c0531896355b3e1a4af608fe1> &,<lambda_f304ae241c39a80e0e0fe73a1c609478> &>+0x184 [d:\dev\public\terminal\src\cascadia\Remoting\Monarch.h @ 142] 
0a 000000b4`cbffed10 00007ffd`a0505154     Microsoft_Terminal_Remoting!winrt::Microsoft::Terminal::Remoting::implementation::Monarch::GetAllWindowLayouts+0xab [d:\dev\public\terminal\src\cascadia\Remoting\Monarch.cpp @ 1026] 
0b 000000b4`cbffedd0 00007ffd`a055fe0a     Microsoft_Terminal_Remoting!winrt::impl::produce<winrt::Microsoft::Terminal::Remoting::implementation::Monarch,winrt::Microsoft::Terminal::Remoting::IMonarch>::GetAllWindowLayouts+0x94 [d:\dev\public\terminal\src\cascadia\Remoting\Generated Files\winrt\Microsoft.Terminal.Remoting.h @ 1028] 
0c 000000b4`cbffee60 00007ffd`a055525c     Microsoft_Terminal_Remoting!winrt::impl::consume_Microsoft_Terminal_Remoting_IMonarch<winrt::Microsoft::Terminal::Remoting::IMonarch>::GetAllWindowLayouts+0xaa [d:\dev\public\terminal\src\cascadia\Remoting\Generated Files\winrt\Microsoft.Terminal.Remoting.h @ 138] 
0d 000000b4`cbffeef0 00007ffd`a055ff14     Microsoft_Terminal_Remoting!winrt::Microsoft::Terminal::Remoting::implementation::WindowManager::GetAllWindowLayouts+0x5c [d:\dev\public\terminal\src\cascadia\Remoting\WindowManager.cpp @ 622] 
0e 000000b4`cbffef40 00007ff6`f65986c7     Microsoft_Terminal_Remoting!winrt::impl::produce<winrt::Microsoft::Terminal::Remoting::implementation::WindowManager,winrt::Microsoft::Terminal::Remoting::IWindowManager>::GetAllWindowLayouts+0x94 [d:\dev\public\terminal\src\cascadia\Remoting\Generated Files\winrt\Microsoft.Terminal.Remoting.h @ 1767] 
0f 000000b4`cbffefd0 00007ff6`f65446e1     WindowsTerminal!winrt::impl::consume_Microsoft_Terminal_Remoting_IWindowManager<winrt::Microsoft::Terminal::Remoting::IWindowManager>::GetAllWindowLayouts+0xa7 [D:\dev\public\terminal\src\cascadia\WindowsTerminal\Generated Files\winrt\Microsoft.Terminal.Remoting.h @ 694] 
10 000000b4`cbfff060 00007ff6`f65b6e6d     WindowsTerminal!AppHost::_SaveWindowLayouts$_ResumeCoro$1+0x5b1 [D:\dev\public\terminal\src\cascadia\WindowsTerminal\AppHost.cpp @ 829] 
11 000000b4`cbfff490 00007ff6`f6591b70     WindowsTerminal!std::experimental::coroutine_handle<void>::resume+0x4d [C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.30.30528\include\experimental\coroutine @ 106] 
12 000000b4`cbfff4e0 00007ff6`f65b7302     WindowsTerminal!std::experimental::coroutine_handle<void>::operator()+0x20 [C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.30.30528\include\experimental\coroutine @ 98] 
13 000000b4`cbfff510 00007ffe`43ed1873     WindowsTerminal!winrt::impl::resume_background_callback+0x32 [D:\dev\public\terminal\src\cascadia\WindowsTerminal\Generated Files\winrt\base.h @ 8622] 
14 000000b4`cbfff550 00007ffe`43ed7d96     ntdll!TppSimplepExecuteCallback+0xa3 [minkernel\threadpool\ntdll\simple.c @ 376] 
15 000000b4`cbfff5a0 00007ffe`42e86ab0     ntdll!TppWorkerThread+0x686 [minkernel\threadpool\ntdll\worker.c @ 1109] 
16 000000b4`cbfff890 00007ffe`43edc44b     KERNEL32!BaseThreadInitThunk+0x10 [clientcore\base\win32\client\thread.c @ 75] 
17 000000b4`cbfff8c0 00000000`00000000     ntdll!RtlUserThreadStart+0x2b [minkernel\ntdll\rtlstrt.c @ 1152] 

   3  Id: c528.5010 Suspend: 1 Teb: 000000b4`cbab2000 Unfrozen
 # Child-SP          RetAddr               Call Site
00 000000b4`cc0ff538 00007ffe`4134f0b0     ntdll!ZwWaitForMultipleObjects+0x14 [minkernel\ntdll\daytona\objfre\amd64\usrstubs.asm @ 947] 
01 000000b4`cc0ff540 00007ffe`433b7bec     KERNELBASE!WaitForMultipleObjectsEx+0xf0 [minkernel\kernelbase\synch.c @ 1551] 
02 000000b4`cc0ff830 00007ffe`433b7a4a     combase!WaitCoalesced+0xb8 [onecore\com\published\comutils\coalescedwait.cxx @ 72] 
03 000000b4`cc0ffac0 00007ffe`433b784c     combase!CROIDTable::WorkerThreadLoop+0x5a [onecore\com\combase\dcomrem\refcache.cxx @ 1682] 
04 000000b4`cc0ffb10 00007ffe`433b77c9     combase!CRpcThread::WorkerLoop+0x58 [onecore\com\combase\dcomrem\threads.cxx @ 283] 
05 000000b4`cc0ffb80 00007ffe`42e86ab0     combase!CRpcThreadCache::RpcWorkerThreadEntry+0x29 [onecore\com\combase\dcomrem\threads.cxx @ 77] 
06 000000b4`cc0ffbb0 00007ffe`43edc44b     KERNEL32!BaseThreadInitThunk+0x10 [clientcore\base\win32\client\thread.c @ 75] 
07 000000b4`cc0ffbe0 00000000`00000000     ntdll!RtlUserThreadStart+0x2b [minkernel\ntdll\rtlstrt.c @ 1152] 

   4  Id: c528.1cb8 Suspend: 1 Teb: 000000b4`cbab4000 Unfrozen
 # Child-SP          RetAddr               Call Site
00 000000b4`cc1fe4c8 00007ffe`4134f0b0     ntdll!ZwWaitForMultipleObjects+0x14 [minkernel\ntdll\daytona\objfre\amd64\usrstubs.asm @ 947] 
01 000000b4`cc1fe4d0 00007ffe`433466d2     KERNELBASE!WaitForMultipleObjectsEx+0xf0 [minkernel\kernelbase\synch.c @ 1551] 
02 000000b4`cc1fe7c0 00007ffe`43345db5     combase!MTAThreadWaitForCall+0x102 [onecore\com\combase\dcomrem\channelb.cxx @ 7398] 
03 000000b4`cc1fe870 00007ffe`4339d2f6     combase!MTAThreadDispatchCrossApartmentCall+0x1e5 [onecore\com\combase\dcomrem\chancont.cxx @ 232] 
04 (Inline Function) --------`--------     combase!CSyncClientCall::SwitchAptAndDispatchCall+0x69f [onecore\com\combase\dcomrem\channelb.cxx @ 5934] 
05 000000b4`cc1fe8b0 00007ffe`4334319e     combase!CSyncClientCall::SendReceive2+0x786 [onecore\com\combase\dcomrem\channelb.cxx @ 5537] 
06 (Inline Function) --------`--------     combase!SyncClientCallRetryContext::SendReceiveWithRetry+0x2f [onecore\com\combase\dcomrem\callctrl.cxx @ 1542] 
07 (Inline Function) --------`--------     combase!CSyncClientCall::SendReceiveInRetryContext+0x2f [onecore\com\combase\dcomrem\callctrl.cxx @ 565] 
08 000000b4`cc1feb80 00007ffe`4339f69e     combase!DefaultSendReceive+0x6e [onecore\com\combase\dcomrem\callctrl.cxx @ 523] 
09 000000b4`cc1febe0 00007ffe`433459e8     combase!CSyncClientCall::SendReceive+0x30e [onecore\com\combase\dcomrem\ctxchnl.cxx @ 726] 
0a 000000b4`cc1fede0 00007ffe`433df578     combase!CClientChannel::SendReceive+0x98 [onecore\com\combase\dcomrem\ctxchnl.cxx @ 655] 
0b 000000b4`cc1fee50 00007ffe`41eeb12c     combase!NdrExtpProxySendReceive+0x58 [onecore\com\combase\ndr\ndrole\proxy.cxx @ 1989] 
0c (Inline Function) --------`--------     RPCRT4!Ndr64pSendReceive+0x39 [minio\rpc\ndr64\cltcall.cxx @ 184] 
0d 000000b4`cc1fee80 00007ffe`433dd87d     RPCRT4!NdrpClientCall3+0x3fc [minio\rpc\ndr64\cltcall.cxx @ 328] 
0e 000000b4`cc1ff200 00007ffe`43455d72     combase!ObjectStublessClient+0x1bd [onecore\com\combase\ndr\ndrole\amd64\stblsclt.cxx @ 297] 
0f 000000b4`cc1ff590 00007ffe`4337e797     combase!ObjectStubless+0x42 [onecore\com\combase\ndr\ndrole\amd64\stubless.asm @ 176] 
10 000000b4`cc1ff5e0 00007ffe`4336b388     combase!CObjectContext::InternalContextCallback+0x207 [onecore\com\combase\dcomrem\context.cxx @ 4329] 
11 000000b4`cc1ff6f0 00007ffe`13f07bf3     combase!CGIPTable::GetInterfaceFromGlobal+0x4b8 [onecore\com\combase\dcomrem\giptbl.cxx @ 1693] 
12 000000b4`cc1ff7b0 00007ffe`13f079c0     uiautomationcore!EventMap::ReleaseOneEntry+0xdb [onecore\windows\accessibletech\uiautomationcore\proxies\msaa_eventmanager.cpp @ 354] 
13 000000b4`cc1ff7f0 00007ffe`43ed0e63     uiautomationcore!EventMap::ReleaseOldEntries+0x150 [onecore\windows\accessibletech\uiautomationcore\proxies\msaa_eventmanager.cpp @ 613] 
14 000000b4`cc1ff860 00007ffe`43ed1793     ntdll!RtlpTpTimerCallback+0x83 [minkernel\threadpool\compat\timer.c @ 418] 
15 000000b4`cc1ff8a0 00007ffe`43ed7d96     ntdll!TppTimerpExecuteCallback+0xb3 [minkernel\threadpool\ntdll\timer.c @ 2293] 
16 000000b4`cc1ff8f0 00007ffe`42e86ab0     ntdll!TppWorkerThread+0x686 [minkernel\threadpool\ntdll\worker.c @ 1109] 
17 000000b4`cc1ffbe0 00007ffe`43edc44b     KERNEL32!BaseThreadInitThunk+0x10 [clientcore\base\win32\client\thread.c @ 75] 
18 000000b4`cc1ffc10 00000000`00000000     ntdll!RtlUserThreadStart+0x2b [minkernel\ntdll\rtlstrt.c @ 1152] 

```

### PR DESCRIPTION
**Pull request by carlos-zamora**
## Summary of the Pull Request
The deadlock was caused by `ScreenInfoUiaProviderBase::GetSelection()` calling `TermControlUiaProvider::GetSelectionRange` (both of which attempted to lock the console). This PR removes the lock and initialization check from `TermControlUiaProvider`. It is no longer necessary because the only one that calls it is `SIUPB::GetSelection()`.

Additionally, this adds some code that was useful in debugging this race condition. That should help us figure out any locking issues that may come up in the future.

## References
#11312
Closes #11385 

## Validation Steps Performed
✅ Repro steps don't cause hang

### CODE REVIEW

File: src/cascadia/TerminalCore/Terminal.cpp [hunk 1]
```diff
@@ -849,7 +849,13 @@ WORD Terminal::_TakeVirtualKeyFromLastKeyEvent(const WORD scanCode) noexcept
 //      will release this lock when it's destructed.
 [[nodiscard]] std::unique_lock<til::ticket_lock> Terminal::LockForReading()
 {
+#ifdef NDEBUG
```
Comment (miniksa) [inline src/cascadia/TerminalCore/Terminal.cpp:852]: I've always done ifdef DBG and done it the other way. @lhecker would know if this is fine.

**Review by miniksa — APPROVED** [review]

**Review by lhecker — APPROVED** [review]

**Comment by carlos-zamora** [comment]
@msftbot merge this in 1 minute
