### PR TITLE
Parse UTF-16 surrogates pairs for calculating pattern's position

### LINKED ISSUE #8709: Links/URLs get offset when certain unicode characters are printed
# Environment

```none
Windows build number: Windows 10 version 2004 (10.0.19041.0)
Windows Terminal version: Preview 1.5.3242.0
```

# Steps to reproduce

Print certain unicode characters like this one: `𝓐`

# Expected behavior

Links/URLs should be valid.

# Actual behavior

Links/URLs get offset and break with the presence of certain unicode characters.
For example, if the following text is printed:
```none
𝓐𝓐𝓐
https://microsoft.com/
```
image

The hoverable link, clickable link and opened link is `ps://microsoft.com/   `
If those unicode characters are not printed (if you scroll for example), the links work again.

https://user-images.githubusercontent.com/1197915/103703479-e54b9280-4fa7-11eb-9394-4d6bd81e952d.mp4

Note that the emoji doesn't cause the issue.
The code used in the video is:
```js
console.log(`𝓐𝓐𝓐𝓐𝓐𝓐 123 https://microsoft.com/

✨ https://google.com/
https://google.fr/
https://youtube.com/
https://aka.ms/`)
```

### PR DESCRIPTION
**Pull request by comzyh**
## Summary of the Pull Request

Properly handle UTF-16 surrogates when calculating the position of matched pattern.

Fix #8709

 
## References
https://github.com/microsoft/terminal/blob/b88ffb21b0725331877ba76bac5a79a4c21eaa03/src/buffer/out/search.cpp#L335-L339

## PR Checklist
* [ ] Closes #8709
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Documentation updated. If checked, please file a pull request on [our docs repo](https://github.com/MicrosoftDocs/terminal) and link it here: #xxx
* [ ] Schema updated.
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Detailed Description of the Pull Request / Additional comments
use `Utf16Parser::Parse` to handle code points from U+010000 to U+10FFFF in UTF-16.

## Validation Steps Performed

image

also the case by @mas90  https://github.com/microsoft/terminal/issues/8709#issuecomment-884915485:

image

### CODE REVIEW

**Review by zadjii-msft — APPROVED** [review]
Good catch, thanks!

**Comment by zadjii-msft** [comment]
@msftbot make sure @PankajBhojwani signs off on this one

File: src/buffer/out/textBuffer.cpp [hunk 1]
```diff
@@ -2585,16 +2586,17 @@ PointTree TextBuffer::GetPatterns(const size_t firstRow, const size_t lastRow) c
             // match and the previous match, so we use the size of the prefix
             // along with the size of the match to determine the locations
             size_t prefixSize = 0;
-
-            for (const auto ch : i->prefix().str())
+            for (const std::vector<wchar_t> parsedGlyph : Utf16Parser::Parse(i->prefix().str()))
```
Comment (miniksa) [inline src/buffer/out/textBuffer.cpp:2589]: I would have left `auto` for the left side here and below... but I'm not going to block over it.

**Review by miniksa — APPROVED** [review]

**Review by PankajBhojwani — APPROVED** [review]

**Comment by zadjii-msft** [comment]
@msftbot merge this in 1 minute
