### PR TITLE
Fix drag and drop on '+' button for drive letters

### LINKED ISSUE #10723: D&D on the '+' button: Dragging a drive letter (`c:\`) behaves weird
Follow up to #10160.

### PR DESCRIPTION
**Pull request by ianjoneill**
Fixes dragging and dropping drive letters onto the '+' button.

Manually tested - dragging and dropping the `C:\` drive onto the '+' button works when creating a new tab, splitting or creating a new window. Dragging and dropping a regular directory still works.

Closes #10723

### CODE REVIEW

File: src/cascadia/TerminalApp/TerminalPage.cpp [hunk 1]
```diff
@@ -255,10 +255,10 @@ namespace winrt::TerminalApp::implementation
 
             std::wstring pathText = path.wstring();
 
-            // Handle edge case of "C:\\", seems like the "StartingDirectory" doesn't like path which ends with '\'
```
Comment (DHowett) [inline src/cascadia/TerminalApp/TerminalPage.cpp:258]: I'm actually quite surprised by this premise. The reason we have issues with StartingDirectory when passed through the commandline are ones of _escaping_.

Does it really beef it if we don't do this trick at all? *huh.*

Comment (DHowett) [reply src/cascadia/TerminalApp/TerminalPage.cpp:258]: (because the commandline escaping for `wt` resaults in `"C:\"` being parsed as `C:\"` (terminating quote captured in path))

Comment (DHowett) [reply src/cascadia/TerminalApp/TerminalPage.cpp:258]: image

Comment (ianjoneill) [reply src/cascadia/TerminalApp/TerminalPage.cpp:258]: Yes - this is purely for the "Open in new window" case

If I comment out the `pathText.push_back(L'.')` and drop on `C:\` with shift pressed, the new window fails to parse the command line:

image

image

Comment (ianjoneill) [reply src/cascadia/TerminalApp/TerminalPage.cpp:258]: Drag and dropping `C:\` to get a new tab or split the current window works fine, it's just the new window case that fails.

Comment (DHowett) [reply src/cascadia/TerminalApp/TerminalPage.cpp:258]: *OH*. Okay.

We should fix this in the New Window commandline generator, honestly. That would also fix it for shift-clicking the `cmd2` profile I created to test this. :smile:

I suspect that this code lives in `NewTerminalArgs::ToCommandline`.

Comment (ianjoneill) [reply src/cascadia/TerminalApp/TerminalPage.cpp:258]: Done - with the added bonus that this now has a test 🙂

**Review by zadjii-msft — APPROVED** [review]
I love that you added a test, thanks!

File: src/cascadia/TerminalApp/TerminalPage.cpp (hunk 1 above)
Comment (DHowett) [reply src/cascadia/TerminalApp/TerminalPage.cpp:258]: Love it! Thank you!

**Review by DHowett — APPROVED** [review]
