### PR TITLE
ConPTY: Raise the MAX_PATH limit

### LINKED ISSUE #16860: `CreatePseudoConsole` crashes due to long path to conpty.dll
### Windows Terminal version

1.19.10573.0

### Windows build number

10.0.22631.0

### Other Software

_No response_

### Steps to reproduce

1. Install [Windows Terminal v1.19.10573.0](https://github.com/microsoft/terminal/releases/tag/v1.19.10573.0) to a directory with long full path: the parent directory of `WindowsTerminal.exe` should have length 167 chars or higher.
2. Run `WindowsTerminal.exe`

Please see https://github.com/segrey/CreatePseudoConsole-crash-with-long-path, it automates the reproduction of this issue.

### Expected Behavior

Windows Terminal runs normally.

### Actual Behavior

Windows Terminal crashes at startup and finishes with exit code -1073740791 (hex: c0000409)

Event Viewer (Windows Log | Application) contains the following error:
```text
Faulting application name: WindowsTerminal.exe, version: 1.19.2402.26003, time stamp: 0x65dce3ea
Faulting module name: ucrtbase.dll, version: 10.0.22621.2506, time stamp: 0x097c794c
Exception code: 0xc0000409
Fault offset: 0x000000000007df28
Faulting process id: 0x0x4424
Faulting application start time: 0x0x1DA739C0BB31B88
Faulting application path: D:\CreatePseudoConsole-crash-with-long-path\tmp\aaaaaaaa\aaaaaaaa\aaaaaaaa\aaaaaaaa\aaaaaaaa\aaaaaaaa\aaaaaaaa\aaaaaaaa\aaaaaaaa\aaaaaaaa\aaaaaaa\terminal-1.19.10573.0\WindowsTerminal.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: 201c4d23-ff42-474b-8764-703686bc06cc
Faulting package full name: 
Faulting package-relative application ID: 
```

Running the `WindowsTerminal.exe` with WinDbg shows that the problem is in `CreatePseudoConsole` function:

image

Looks like it's caused by crashing [`swprintf_s`](https://github.com/microsoft/terminal/blob/a38388615e299658072f906578acd60e976fe787/src/winconpty/winconpty.cpp#L142), because `MAX_PATH` (260) is too small to accomodate the full path. This is indirectly confirmed by the following: `WindowsTerminal.exe` doesn't crash when it's located in a directory with full path length 162 chars -- in this case the command line of OpenConsole.exe is 259 chars and everything works correctly:

`"D:\CreatePseudoConsole-crash-with-long-path\tmp\aaaaaaaa\aaaaaaaa\aaaaaaaa\aaaaaaaa\aaaaaaaa\aaaaaaaa\aaaaaaaa\aaaaaaaa\aaaaaaaa\aaaaaaaa\aa\terminal-1.19.10573.0\OpenConsole.exe" --headless --resizeQuirk --width 120 --height 30 --signal 0xd28 --server 0xd20`

It'd be great to fix this issue, because sometimes conpty.dll / OpenConsole.exe are located deep inside the file system.

### PR DESCRIPTION
**Pull request by lhecker**
Swapped the `swprintf_s` with no failure checks against a
`str_printf_nothrow` with checks. I also deduplicated the
`CreateProcess` calls since they're mostly identical.

Closes #16860

### CODE REVIEW

File: src/winconpty/winconpty.cpp [hunk 1]
```diff
@@ -93,7 +93,7 @@ static bool _HandleIsValid(HANDLE h) noexcept
     return (h != INVALID_HANDLE_VALUE) && (h != nullptr);
 }
 
-HRESULT _CreatePseudoConsole(const HANDLE hToken,
+HRESULT _CreatePseudoConsole(HANDLE hToken,
```
Comment (lhecker) [inline src/winconpty/winconpty.cpp:96]: No whitespace: https://github.com/microsoft/terminal/pull/17768/files?w=1

**Review by zadjii-msft — APPROVED** [review]
