### PR TITLE
Persist inbox conhost; delegate control activities to it via a pipe

### LINKED ISSUE #10134: [DefApp] launching WSL inside DefTerm yields “the parameter is incorrect”
As in title

### LINKED ISSUE #10194: Windows terminal as default terminal application breaks WSL2 launch when WSL2 debugConsole is enabled
### Windows Terminal version (or Windows build number)

1.9.1445.0

### Other Software

1. WSL2
2. Windows 10 build 21387 or later, for the WSL2 `debugConsole` functionality

### Steps to reproduce

1. Install WSL2 + a distro and create the `%USERPROFILE%\.wslconfig` file with the following contents:

```
[wsl2]
debugConsole=true
```
2. Make sure that Terminal v1.9.1445.0 is installed, and that it's a) set as the default terminal b) has a profile for your WSL2 distro
3. Attempt to launch terminal in the WSL2 profile, either via the jump list or terminal's own profile menu

### Expected Behavior

1. WSL2 profile opens normally

### Actual Behavior

1. Windows terminal locks up and goes into a "not responding" state, with high system CPU usage from VM compute service
2. After the windows terminal process is killed, a legacy console window spawns with the expected WSL2 VM debug output
3. After the VM boots, another Windows terminal spawns without any tabs open, lacking any WSL profile, and doesn't respond to window close events
4. When the terminal instance from 3 is killed, and another one is spawned, this one will work normally

### LINKED ISSUE #10413: [DefApp] Ctrl+C doesn't work to cancel ping from cmd
Open cmd
Ping something
Try to cancel with Ctrl+C.

It no worky.

### LINKED ISSUE #10414: [DefApp] Assorted leftover processes when abruptly terminating portions of app chain
Depending on how and where things are terminated, sometimes there are leftover processes when things are crashing.

This bug represents ensuring that we can kill any of the following in the chain and have the remainder of them clean themselves up.
- client application like `cmd.exe`
- inbox `conhost.exe`
- packaged `openconsole.exe`
- terminal `windowsterminaal.exe`

We seem to have this pretty reliable already for things started from the Terminal side... but it's not as robust for things coming in from the DefApp inbound connection side.

### PR DESCRIPTION
**Pull request by miniksa**
Persist inbox conhost; delegate control activities to it via a pipe

## PR Checklist
* [x] Closes #10194 - WSL Debug Tap doesn't work
* [x] Closes #10134 - WSL Parameter is Incorrect
* [x] Closes #10413 - Ctrl+C not passed to client
* [x] Closes #10414 - Leftover processes on abrupt termination
* [x] Might help #10251 - Win+X Powershell sometimes fails to attach
* [x] I work here
* [x] Manually tested with assorted launch scenarios

## Detailed Description of the Pull Request / Additional comments
It turns out that there's a bit of ownership that goes on with the original inbox `conhost.exe` and the operating system/driver. The PID of that original `conhost.exe` is stowed when the initial connection is established and it is verified for several activities. This means that the plan of letting it go completely away and having the `OpenConsole.exe` take over all of its activities must be slightly revised. 

I have tested the following two alternatives to keeping `conhost.exe` around and they do not work:
1. Replacing the original owner `conhost.exe` with `OpenConsole.exe` - A.) The driver does not allow this. Once the owner is registered, it cannot be replaced. B.) There's no way of updating this information inside the client process space and it is kept there too in the `kernelbase`/`conclnt` data from its initial connection.
2. Attempting to pick up the first packet (to determine headed/headless and other initial connection information that we use to determine whether handoff is appropriate or not) prior to registering any owner at all. - The driver doesn't allow this either. The owner must be registered prior to a packet coming through.

Put this mental model in your head:
CMD --> Conhost (inbox) --> OpenConsole (WT Package) --> Terminal (WT Package)

So since the `conhost.exe` needs to stick around, here's what I'm doing in this PR:
- `conhost.exe` in the OS will receive back the `OpenConsole.exe` process handle on a successful handoff and is expected to remain alive until the `OpenConsole.exe` exits. It's now waiting on that before it terminates itself.
- `conhost.exe` in the OS will establish a signal channel pipe and listen for control commands from `OpenConsole.exe` in a very similar fashion to how the `ConPTY` signal pipe operates between the Terminal and the PTY (provided by `OpenConsole.exe` in this particular example.) When `OpenConsole.exe` needs to do something that would be verified by the OS and rejected... it will instead signal the original `conhost.exe` to do that thing and it will go through.
- `conhost.exe` will give its own handle through to `OpenConsole.exe` so it can monitor its lifetime and cleanup. If the owner is gone, the session should end.
- Assorted handle cleanup that was leading to improper exits. I was confused between `.reset()` and `.release()` for some of the `wil::unique_any<T>` handling and it lead to leaked handles. The leaked handles meant that threads weren't aware of the other sides collapsing and wouldn't cleanup/terminate appropriately.

How does this fix things?
- For the WSL cases... WSL was specifically looking up the owner PID of the console session from the driver. That was the `conhost.exe` PID. If it exits, that PID isn't valid and is recycled. Thus the parameter is incorrect or other inappropriate WSL setup behaviors.
- Ctrl+C not passed... this is a signal the operating system rejects from a PID that is not the owner. This is now relayed through the original owner and it works.
- Leftover processes... I believe I explained this was both not-enough-monitoring of each others' process lifetimes coupled with mishandling of release/resetting handles and leaking them.
- Powershell sometimes fails to attach... my theory on this one is that it's a race that became upset when the `conhost.exe` disappeared while something about Powershell/.NET was still starting, much like the WSL one. I believe now that it is sticking around, it will be fine.

Also, this WILL require an OS update to complete improvement of functionality and I have revised the interface ID. This is considered an acceptable breaking change with no mitigation because we said this feature was an alpha preview.  

## Validation Steps Performed
- Launched WSL with defapp set, it works
- Launched WSL with defapp set and the debug tap on, it works and opens in two tabs
- Launched CMD, ran ping, did Ctrl+C, it now receives it
- Launched Win+X powershell a ton of times. It seems fine now
- Launched cmd, powershell, wsl, etc. Killed assorted processes in the chain (client/conhost/openconsole/windowsterminal) and observed in Process Explorer (with a long delta timer so I could see it) that they all successfully tear down now without leftovers.

### CODE REVIEW

**Comment by miniksa** [comment]
I just realized I likely need to send a few more parameters over the IConsoleHandoff interface while I'm here for #9458. So setting to Draft until I figure that out so I don't have to rev the IID again.

**Comment by miniksa** [comment]
> I just realized I likely need to send a few more parameters over the IConsoleHandoff interface while I'm here for #9458. So setting to Draft until I figure that out so I don't have to rev the IID again.

`ConsoleInitializeConnectInfo` looks like it can pick up any of this information in the `OpenConsole.exe` so it doesn't need to be passed. So nevermind on the #9458 business. That's between `OpenConsole.exe` and `WindowsTerminal.exe`... not the OS copy.

File: src/host/srvinit.cpp [hunk 1]
```diff
@@ -388,6 +391,22 @@ try
...
+
+    // Set up a threadpool waiter to shutdown everything if the inbox process disappears.
+    g.handoffInboxConsoleExitWait.reset(CreateThreadpoolWait(
+        [](PTP_CALLBACK_INSTANCE /*callbackInstance*/, PVOID /*context*/, PTP_WAIT /*wait*/, TP_WAIT_RESULT /*waitResult*/) noexcept {
+            ServiceLocator::RundownAndExit(E_APPLICATION_MANAGER_NOT_RUNNING);
+        },
+        nullptr,
+        nullptr));
+
+    SetThreadpoolWait(g.handoffInboxConsoleExitWait.get(), g.handoffInboxConsoleHandle.get(), nullptr);
```
Comment (lhecker) [inline src/host/srvinit.cpp:405]: I've read the documentation, but I don't quite get how it works...
Is this functionally the same as `RegisterWaitForSingleObject`?

**Comment by o-sdn-o** [comment]
Could this be related to #10400?

**Comment by DHowett** [comment]
> Could this be related to #10400?

Unlikely; this code is only used when conhost (inside windows) spawns a _secondary conhost_, not when you call `CreatePseudoConsole`.

File: src/host/srvinit.cpp (hunk 1 above)
Comment (miniksa) [reply src/host/srvinit.cpp:405]: I think you're right. I think it's similar functionality to that function, just perhaps with different configuration options available.

File: src/interactivity/base/ServiceLocator.cpp [hunk 2]
```diff
@@ -104,6 +104,27 @@ void ServiceLocator::RundownAndExit(const HRESULT hr)
 
 #pragma region Set Methods
 
+[[nodiscard]] NTSTATUS ServiceLocator::SetConsoleControlInstance(_In_ std::unique_ptr<IConsoleControl>& control)
```
Comment (DHowett) [inline src/interactivity/base/ServiceLocator.cpp:107]: Augh, forcing ownership transfer like this is nonidiomatic.

If you want to codify it _in a C++ way_ you should take `std::unique_ptr<IConsoleControl> control` and pass it in with `std::move` and _move it out into `s_consoleControl` with `std::move` as well_.

Comment (DHowett) [reply src/interactivity/base/ServiceLocator.cpp:107]: Even better:

```suggestion
[[nodiscard]] NTSTATUS ServiceLocator::SetConsoleControlInstance(_In_ std::unique_ptr<IConsoleControl>&& control)
```

this forces the caller to 🎵 `move` it `move` it

File: src/host/srvinit.cpp [hunk 3]
```diff
@@ -364,6 +365,8 @@ HRESULT ConsoleCreateIoThread(_In_ HANDLE Server,
 //   from the driver... or an S_OK success.
 [[nodiscard]] HRESULT ConsoleEstablishHandoff([[maybe_unused]] _In_ HANDLE Server,
                                               [[maybe_unused]] HANDLE driverInputEvent,
+                                              [[maybe_unused]] HANDLE hostSignalPipe,
+                                              [[maybe_unused]] HANDLE hostProcessHandle,
                                               [[maybe_unused]] PCONSOLE_API_MSG connectMessage)
 try
 {
```
Comment (DHowett) [inline src/host/srvinit.cpp:372]: you'll probably merge conflict near here because of til::feature

File: src/inc/HostSignals.hpp [hunk 4]
```diff
@@ -0,0 +1,26 @@
+// These values match the enumeration values of `ControlType` for the `ConsoleControl` class
+// but are defined here similarly to not pollute other projects.zs
```
Comment (DHowett) [inline src/inc/HostSignals.hpp:2]:
```suggestion
// but are defined here similarly to not pollute other projects.
```

File: src/inc/HostSignals.hpp [hunk 5]
```diff
@@ -0,0 +1,26 @@
...
+};
+
+#define HOST_SIGNAL_END_TASK 7u
+struct HOST_SIGNAL_END_TASK_DATA
+{
+    DWORD cbSize;
+    ULONG dwProcessId;
+    DWORD dwEventType;
+    ULONG ulCtrlFlags;
+};
```
Comment (DHowett) [inline src/inc/HostSignals.hpp:26]: for "wire types", it might be better to prefer the known sized types from stdint, `uint8_t` `uint32_t` `uint16_t` etc.

Also: we don't have to be weird -- we can just use enums like civilized folks instead of defines like.. define-users :)

Comment (DHowett) [reply src/inc/HostSignals.hpp:26]: especially because enum classes make it possible to enforce the enum type size on the wire

File: src/interactivity/base/HostSignalInputThread.cpp [hunk 6]
```diff
@@ -0,0 +1,255 @@
...
+#include "../interactivity/inc/ServiceLocator.hpp"
+
+using namespace Microsoft::Console;
+using namespace Microsoft::Console::Interactivity;
+
+// Constructor Description:
+// - Creates the PTY Signal Input Thread.
+// Arguments:
+// - hPipe - a handle to the file representing the read end of the Host Signal pipe.
+HostSignalInputThread::HostSignalInputThread(_In_ wil::unique_hfile hPipe) :
```
Comment (DHowett) [inline src/interactivity/base/HostSignalInputThread.cpp:18]: you can enforce an ownership transfer requirement with `wil::unique_hfile&& hPipe`, if you so desire.

File: src/interactivity/base/HostSignalInputThread.cpp [hunk 7]
```diff
@@ -0,0 +1,255 @@
...
+void HostSignalInputThread::ConnectConsole() noexcept
+{
+    _consoleConnected = true;
+}
+
+// Method Description:
+// - The ThreadProc for the Host Signal Input Thread.
+// Return Value:
+// - S_OK if the thread runs to completion.
+// - Otherwise it may cause an application termination another route and never return.
```
Comment (DHowett) [inline src/interactivity/base/HostSignalInputThread.cpp:66]: grammar

File: src/interactivity/base/HostSignalInputThread.cpp [hunk 8]
```diff
@@ -0,0 +1,255 @@
...
+[[nodiscard]] HRESULT HostSignalInputThread::_InputThread()
+{
+    unsigned short signalId;
```
Comment (DHowett) [inline src/interactivity/base/HostSignalInputThread.cpp:69]: same comments as above about using the sized types

File: src/interactivity/base/HostSignalInputThread.cpp [hunk 9]
```diff
@@ -0,0 +1,255 @@
...
+        {
+        case HOST_SIGNAL_NOTIFY_APP:
+        {
+            HOST_SIGNAL_NOTIFY_APP_DATA msg = { 0 };
+            if (_GetData(&msg, sizeof(msg)))
+            {
+                if (msg.cbSize >= sizeof(msg))
+                {
+                    _AdvanceReader(msg.cbSize - sizeof(msg));
+                }
```
Comment (DHowett) [inline src/interactivity/base/HostSignalInputThread.cpp:82]: this (and the exception) seems like shared code between the three cases; is there an opportunity for templatization here? It can easily figure out the size of the struct and advance the correct distance.

File: src/interactivity/base/HostSignalInputThread.cpp [hunk 10]
```diff
@@ -0,0 +1,255 @@
...
+                {
+                    THROW_HR(E_ILLEGAL_METHOD_CALL);
+                }
+
+                LOG_IF_NTSTATUS_FAILED(ServiceLocator::LocateConsoleControl()->NotifyConsoleApplication(msg.dwProcessId));
+            }
+            else
+            {
+                return E_ABORT;
+            }
```
Comment (DHowett) [inline src/interactivity/base/HostSignalInputThread.cpp:93]: nit: you can outdent the body a level if you use `if(!_GetData()) { ... abort ... }`

File: src/interactivity/base/HostSignalInputThread.cpp [hunk 11]
```diff
@@ -0,0 +1,255 @@
...
+            THROW_HR(E_UNEXPECTED);
+            break;
+        }
+        }
+    }
+    return S_OK;
+}
+
+// Method Description:
+// - Skips the file stream forward by the specified number of bytes.zs
```
Comment (DHowett) [inline src/interactivity/base/HostSignalInputThread.cpp:152]: a bunch of `.zs` appeared. interesting.

```suggestion
// - Skips the file stream forward by the specified number of bytes.
```

File: src/interactivity/base/HostSignalInputThread.cpp [hunk 12]
```diff
@@ -0,0 +1,255 @@
...
+
+    hThread = CreateThread(nullptr,
+                           0,
+                           HostSignalInputThread::StaticThreadProc,
+                           this,
+                           0,
+                           &dwThreadId);
+
+    RETURN_LAST_ERROR_IF_NULL(hThread);
+    _hThread.reset(hThread);
```
Comment (DHowett) [inline src/interactivity/base/HostSignalInputThread.cpp:233]: You can probably just store the output of CreateThread directly into `_hThread`, no?

Comment (DHowett) [reply src/interactivity/base/HostSignalInputThread.cpp:233]: Same for `_dwThreadId`.

It's safe from torn state because you're torching the house if it fails.

File: src/interactivity/base/RemoteConsoleControl.cpp [hunk 13]
```diff
@@ -0,0 +1,88 @@
...
+    HOST_SIGNAL_NOTIFY_APP_DATA data;
+    data.cbSize = sizeof(data);
+    data.dwProcessId = dwProcessId;
+
+    if (!WriteFile(_pipe.get(), &data, sizeof(data), &dwWritten, nullptr))
+    {
+        return NTSTATUS_FROM_WIN32(::GetLastError());
+    }
+
+    return STATUS_SUCCESS;
```
Comment (DHowett) [inline src/interactivity/base/RemoteConsoleControl.cpp:38]: nit: Can these be consolidated into a single buffer write somehow? I know this isn't a high-bandwidth channel, but I have to ask

File: src/interactivity/base/RemoteConsoleControl.cpp [hunk 14]
```diff
@@ -0,0 +1,88 @@
...
+{
+    DWORD dwWritten = 0;
+
+    unsigned short code = HOST_SIGNAL_NOTIFY_APP;
+    if (!WriteFile(_pipe.get(), &code, sizeof(code), &dwWritten, nullptr))
+    {
+        return NTSTATUS_FROM_WIN32(::GetLastError());
+    }
+
+    HOST_SIGNAL_NOTIFY_APP_DATA data;
```
Comment (DHowett) [inline src/interactivity/base/RemoteConsoleControl.cpp:29]:
```suggestion
    HOST_SIGNAL_NOTIFY_APP_DATA data{};
```

even though you're going to initialize every member, it doesn't hurt to zero-initialize it too

**Review by DHowett — CHANGES_REQUESTED** [review]

File: src/interactivity/base/HostSignalInputThread.cpp (hunk 11 above)
Comment (miniksa) [reply src/interactivity/base/HostSignalInputThread.cpp:152]: That's a keyboard thing. I'm trying to hit Ctrl+S to save but I'm not waiting long enough for the Ctrl to roll over out of the Z key. Oops.

File: src/interactivity/base/RemoteConsoleControl.cpp [hunk 15]
```diff
@@ -0,0 +1,71 @@
...
+#pragma region IConsoleControl Members
+
+template<typename T>
+[[nodiscard]] NTSTATUS _SendTypedPacket(HANDLE pipe, ::Microsoft::Console::HostSignals signalCode, T& payload)
+{
+    struct HostSignalPacket
+    {
+        ::Microsoft::Console::HostSignals code;
+        T data;
+    };
```
Comment (DHowett) [inline src/interactivity/base/RemoteConsoleControl.cpp:26]: This may not work the way you'd like, unfortunately. Intra-member padding will be introduced for alignment purposes s.t. you'll get `[code 0 0 0 data1 data2 data3]` on the wire

Comment (miniksa) [reply src/interactivity/base/RemoteConsoleControl.cpp:28]: pack should do it.

**Review by DHowett — APPROVED** [review]

File: src/host/srvinit.cpp [hunk 16]
```diff
@@ -434,9 +444,9 @@ try
                                                   serverProcess,
                                                   clientProcess.get()));
 
-    inPipeTheirSide.release();
-    outPipeTheirSide.release();
-    signalPipeTheirSide.release();
+    inPipeTheirSide.reset();
+    outPipeTheirSide.reset();
+    signalPipeTheirSide.reset();
```
Comment (lhecker) [inline src/host/srvinit.cpp:449]: Do you even have to drop those manually when you're exiting the scope a few lines later?

File: src/interactivity/base/HostSignalInputThread.cpp [hunk 17]
```diff
@@ -0,0 +1,240 @@
...
+#include "../interactivity/inc/ServiceLocator.hpp"
+
+using namespace Microsoft::Console;
+using namespace Microsoft::Console::Interactivity;
+
+// Constructor Description:
+// - Creates the PTY Signal Input Thread.
+// Arguments:
+// - hPipe - a handle to the file representing the read end of the Host Signal pipe.
+HostSignalInputThread::HostSignalInputThread(_In_ wil::unique_hfile&& hPipe) :
```
Comment (lhecker) [inline src/interactivity/base/HostSignalInputThread.cpp:18]: We don't need `_In_` in modern C++ anymore, do we?
Also I think I need to change my opinion: I previously agreed with Dustin that `&&` makes the intent of ownership transfer clear, but now that I read the code I feel like a version without any references at all is cleaner. It properly works even with prvalues, like when you want to write `new HostSignalInputThread(wil::make_unique<>(...))` (if that existed), etc.
I'm not sure if it can be argued in this particular case that the `&&` variant helps confer any additional meaning to future readers, what a handle called "unique" doesn't already.

File: src/interactivity/base/HostSignalInputThread.hpp [hunk 18]
```diff
@@ -0,0 +1,51 @@
...
+        T _ReceiveTypedPacket();
+        [[nodiscard]] HRESULT _InputThread();
+
+        bool _GetData(_Out_writes_bytes_(cbBuffer) void* const pBuffer, const DWORD cbBuffer);
+        bool _AdvanceReader(const DWORD cbBytes);
+        void _Shutdown();
+
+        wil::unique_hfile _hFile;
+        wil::unique_handle _hThread;
+        DWORD _dwThreadId;
```
Comment (lhecker) [inline src/interactivity/base/HostSignalInputThread.hpp:48]: You don't actually read `_dwThreadId` anywhere. Is that a mistake, or is this just unneeded code now?

File: src/interactivity/base/HostSignalInputThread.cpp [hunk 19]
```diff
@@ -0,0 +1,240 @@
...
+    }
+
+    return true;
+}
+
+// Method Description:
+// - Starts the PTY Signal input thread.
+[[nodiscard]] HRESULT HostSignalInputThread::Start() noexcept
+{
+    RETURN_LAST_ERROR_IF(!_hFile);
```
Comment (lhecker) [inline src/interactivity/base/HostSignalInputThread.cpp:207]: I'd move this into the constructor and make the class member `const`.

File: src/interactivity/base/HostSignalInputThread.cpp [hunk 20]
```diff
@@ -0,0 +1,240 @@
...
+
+    // 0 is the right value, https://devblogs.microsoft.com/oldnewthing/20040223-00/?p=40503
+    _dwThreadId = 0;
+
+    _hThread.reset(CreateThread(nullptr,
+                                0,
+                                HostSignalInputThread::StaticThreadProc,
+                                this,
+                                0,
+                                &_dwThreadId));
```
Comment (lhecker) [inline src/interactivity/base/HostSignalInputThread.cpp:217]: We should consider using `std::thread` in newer code. It allows access to the underlying thread handle just like `wil::unique_handle` does, but is more ergonomic.

File: src/interactivity/base/HostSignalInputThread.cpp [hunk 21]
```diff
@@ -0,0 +1,240 @@
...
+// Method Description:
+// - Retrieves bytes from the file stream and exits or throws errors should the pipe state
+//   be compromised.
+// Arguments:
+// - pBuffer - Buffer to fill with data.
+// - cbBuffer - Count of bytes in the given buffer.
+// Return Value:
+// - True if data was retrieved successfully. False otherwise.
+bool HostSignalInputThread::_GetData(_Out_writes_bytes_(cbBuffer) void* const pBuffer,
+                                     const DWORD cbBuffer)
```
Comment (lhecker) [inline src/interactivity/base/HostSignalInputThread.cpp:174]: You can use a `gsl::span<std::byte>` or `gsl::span<BYTE>`!

File: src/interactivity/base/HostSignalInputThread.cpp [hunk 22]
```diff
@@ -0,0 +1,240 @@
...
+        {
+            _Shutdown();
+            return false;
+        }
+        else
+        {
+            THROW_WIN32(lastError);
+        }
+    }
+    else if (dwRead != cbBuffer)
```
Comment (lhecker) [inline src/interactivity/base/HostSignalInputThread.cpp:194]: You don't need the `else`. This condition isn't related to the "ReadFile failed"-handling code anymore anyways. (You could also remove the else above.)

File: src/interactivity/base/HostSignalInputThread.cpp [hunk 23]
```diff
@@ -0,0 +1,240 @@
...
+
+// Function Description:
+// - Static function used for initializing an instance's ThreadProc.
+// Arguments:
+// - lpParameter - A pointer to the HostSignalInputThread instance that should be called.
+// Return Value:
+// - The return value of the underlying instance's _InputThread
+DWORD WINAPI HostSignalInputThread::StaticThreadProc(_In_ LPVOID lpParameter)
+{
+    HostSignalInputThread* const pInstance = reinterpret_cast<HostSignalInputThread*>(lpParameter);
```
Comment (lhecker) [inline src/interactivity/base/HostSignalInputThread.cpp:44]: This can be a `static_cast`.

File: src/interactivity/base/HostSignalInputThread.cpp [hunk 24]
```diff
@@ -0,0 +1,240 @@
...
+    // do nothing.
+    if (msg.sizeInBytes >= sizeof(msg))
+    {
+        _AdvanceReader(msg.sizeInBytes - sizeof(msg));
+    }
+    // If the message is smaller than what we expected
+    // then it was malformed and we need to throw.
+    else
+    {
+        THROW_HR(E_ILLEGAL_METHOD_CALL);
```
Comment (lhecker) [inline src/interactivity/base/HostSignalInputThread.cpp:87]: If you swap the if condition around you can unnest the `_AdvanceReader` and make the code flow more linear / less nested.

File: src/interactivity/base/HostSignalInputThread.cpp [hunk 25]
```diff
@@ -0,0 +1,240 @@
...
+// Method Description:
+// - Skips the file stream forward by the specified number of bytes.
+// Arguments:
+// - cbBytes - Count of bytes to skip forward
+// Return Value:
+// - True if we could skip forward successfully. False otherwise.
+bool HostSignalInputThread::_AdvanceReader(const DWORD cbBytes)
+{
+    std::array<BYTE, 8> buffer;
+    auto bytesRemaining = cbBytes;
```
Comment (lhecker) [inline src/interactivity/base/HostSignalInputThread.cpp:148]: Why not make the parameter non-const instead?

File: src/interactivity/base/HostSignalInputThread.cpp [hunk 26]
```diff
@@ -0,0 +1,240 @@
...
+
+// Method Description:
+// - Skips the file stream forward by the specified number of bytes.
+// Arguments:
+// - cbBytes - Count of bytes to skip forward
+// Return Value:
+// - True if we could skip forward successfully. False otherwise.
+bool HostSignalInputThread::_AdvanceReader(const DWORD cbBytes)
+{
+    std::array<BYTE, 8> buffer;
```
Comment (lhecker) [inline src/interactivity/base/HostSignalInputThread.cpp:147]: It can't hurt making this larger. A cache line is at least 64 Bytes nowadays, which can be the minimum for any buffer like that. A weak min-spec CPU usually has about 2-4MB L3 cache at least.
If you make this 256-1024 bytes it's just 5-17 cache lines at most - of which only those are swapped into CPU cache, that are actually touched by this function. And finally: Stack memory is cheap after all...

File: src/interactivity/base/RemoteConsoleControl.cpp [hunk 27]
```diff
@@ -0,0 +1,74 @@
...
+#pragma pack(pop)
+
+    HostSignalPacket packet;
+    packet.code = signalCode;
+    packet.data = payload;
+
+    DWORD dwWritten = 0;
+    if (!WriteFile(pipe, &packet, sizeof(packet), &dwWritten, nullptr))
```
Comment (lhecker) [inline src/interactivity/base/RemoteConsoleControl.cpp:36]: `RETURN_IF_WIN32_BOOL_FALSE`?

And should `dwWritten` be checked afterwards?
The pipe should be considered broken if a write failed, because if it happened to still work on the next call the receiver code would fail to read the correct amount of `msg.sizeInBytes` and get stuck, being out of sync with the sender logic.

File: src/interactivity/base/RemoteConsoleControl.cpp [hunk 28]
```diff
@@ -0,0 +1,74 @@
...
+    {
+        return NTSTATUS_FROM_WIN32(::GetLastError());
+    }
+
+    return STATUS_SUCCESS;
+}
+
+[[nodiscard]] NTSTATUS RemoteConsoleControl::NotifyConsoleApplication(_In_ DWORD dwProcessId)
+{
+    HostSignalNotifyAppData data = { 0 };
```
Comment (lhecker) [inline src/interactivity/base/RemoteConsoleControl.cpp:46]: In C this was necessary, but in C++ you can just write `data{}`.
The implicitly declared default constructor for any class or struct performs zero initialization since C++11.

File: src/interactivity/base/ServiceLocator.cpp [hunk 29]
```diff
@@ -104,6 +104,26 @@ void ServiceLocator::RundownAndExit(const HRESULT hr)
...
+{
+    NTSTATUS status = STATUS_SUCCESS;
+
+    if (s_consoleControl)
+    {
+        status = STATUS_INVALID_HANDLE;
+    }
+    else if (!control)
+    {
+        status = STATUS_INVALID_PARAMETER;
```
Comment (lhecker) [inline src/interactivity/base/ServiceLocator.cpp:117]: I wish these were return statements.

File: src/server/IoDispatchers.cpp [hunk 30]
```diff
@@ -296,16 +297,50 @@ PCONSOLE_API_MSG IoDispatchers::ConsoleHandleConnectionRequest(_In_ PCONSOLE_API
...
+            wil::unique_hfile signalPipeOurSide;
+
+            THROW_IF_WIN32_BOOL_FALSE(CreatePipe(signalPipeOurSide.addressof(), signalPipeTheirSide.addressof(), nullptr, 0));
+
+            // Give a copy of our own process handle to be tracked.
+            wil::unique_process_handle ourProcess;
+            THROW_IF_WIN32_BOOL_FALSE(DuplicateHandle(GetCurrentProcess(),
+                                                      GetCurrentProcess(),
+                                                      GetCurrentProcess(),
+                                                      &ourProcess,
```
Comment (lhecker) [inline src/server/IoDispatchers.cpp:310]: For the sake of consistency this should probably be `ourProcess.addressof()`.
The `operator&` is an alias for `.put()` and performs a `.reset()` (deallocation) and returns the same as `.addressof()`. And right above this you use `.addressof()` already.

Personally I don't understand the existence of `.addressof()` in wil - it seems like a macro-optimization to me.

**Review by lhecker — APPROVED** [review]
Lotta comments... But no actual mistakes.

File: src/host/srvinit.cpp [hunk 31]
```diff
@@ -388,6 +391,22 @@ try
...
+    g.handoffInboxConsoleHandle.reset(hostProcessHandle);
+
+    // Set up a threadpool waiter to shutdown everything if the inbox process disappears.
+    g.handoffInboxConsoleExitWait.reset(CreateThreadpoolWait(
+        [](PTP_CALLBACK_INSTANCE /*callbackInstance*/, PVOID /*context*/, PTP_WAIT /*wait*/, TP_WAIT_RESULT /*waitResult*/) noexcept {
+            ServiceLocator::RundownAndExit(E_APPLICATION_MANAGER_NOT_RUNNING);
+        },
+        nullptr,
+        nullptr));
+
```
[the remark this answers is not in the document]
Comment (miniksa) [reply src/host/srvinit.cpp:404]: I put the return check on this one. No idea on why it works for `__stdcall` but it does so.......

File: src/host/srvinit.cpp (hunk 16 above)
Comment (miniksa) [reply src/host/srvinit.cpp:449]: I'm just doing it for good measure for the next time someone edits this code and gets the idea to insert more stuff between this code and the bottom.

File: src/interactivity/base/HostSignalInputThread.cpp (hunk 17 above)
Comment (miniksa) [reply src/interactivity/base/HostSignalInputThread.cpp:18]: This is between you and @DHowett then. && already confuses me and you two understand it better than me. I just want whatever works.

File: src/interactivity/base/HostSignalInputThread.hpp (hunk 18 above)
Comment (miniksa) [reply src/interactivity/base/HostSignalInputThread.hpp:48]: I'll drop it. It's because I copied this from PtySignalInputThread.

Comment (miniksa) [reply src/interactivity/base/HostSignalInputThread.hpp:48]: And the connected var too...

File: src/interactivity/base/HostSignalInputThread.cpp (hunk 17 above)
Comment (miniksa) [reply src/interactivity/base/HostSignalInputThread.cpp:18]: (I did drop SAL tho...)

File: src/interactivity/base/HostSignalInputThread.cpp (hunk 25 above)
Comment (miniksa) [reply src/interactivity/base/HostSignalInputThread.cpp:148]: brain fart

File: src/interactivity/base/HostSignalInputThread.cpp (hunk 26 above)
Comment (miniksa) [reply src/interactivity/base/HostSignalInputThread.cpp:147]: 256 it is.

File: src/server/IoDispatchers.cpp (hunk 30 above)
Comment (miniksa) [reply src/server/IoDispatchers.cpp:310]: It's probably a COM reason. It just feels like one. I dunno. Made it line up.

File: src/interactivity/base/ServiceLocator.cpp (hunk 29 above)
Comment (miniksa) [reply src/interactivity/base/ServiceLocator.cpp:117]: Wish granted. I was just matching the style of the file but sure.

File: src/interactivity/base/RemoteConsoleControl.cpp (hunk 28 above)
Comment (miniksa) [reply src/interactivity/base/RemoteConsoleControl.cpp:46]: Huh. OK.

File: src/interactivity/base/RemoteConsoleControl.cpp (hunk 27 above)
Comment (miniksa) [reply src/interactivity/base/RemoteConsoleControl.cpp:36]: unfortunately this set of APIs is returning `NTSTATUS` so my only wil options seem to be the `RETURN_NTSTATUS` and `RETURN_NTSTATUS_MSG` functions without any of the nice flow shorthand. but I've updated to use the wil ones for debuggability and added a test for write length.

Comment (miniksa) [reply src/interactivity/base/RemoteConsoleControl.cpp:36]: No on further look... all the wil ones transform...

File: src/interactivity/base/HostSignalInputThread.cpp (hunk 20 above)
Comment (miniksa) [reply src/interactivity/base/HostSignalInputThread.cpp:217]: not right now because of the annoying join on destruct behavior, std::thread has bit me in the butt there before.

File: src/interactivity/base/HostSignalInputThread.cpp (hunk 19 above)
Comment (miniksa) [reply src/interactivity/base/HostSignalInputThread.cpp:207]: I'm going to keep dwthreadid with the loose thread so I'm going to leave this alone.

**Comment by miniksa** [comment]
Don't merge yet. I need to do a final e2e test after all the style feedback to make sure I didn't bungle a byte buffer.

**Comment by miniksa** [comment]
Built against OS and fixed. Patched OS and tried it and confirmed the issues are still resolved. Setting automerge.

File: src/interactivity/base/HostSignalInputThread.cpp [hunk 32]
```diff
@@ -15,13 +15,13 @@ using namespace Microsoft::Console::Interactivity;
...
-HostSignalInputThread::HostSignalInputThread(_In_ wil::unique_hfile&& hPipe) :
+HostSignalInputThread::HostSignalInputThread(wil::unique_hfile&& hPipe) :
     _hFile{ std::move(hPipe) },
     _hThread{},
-    _dwThreadId{ 0 },
-    _consoleConnected{ false }
+    _dwThreadId{}
 {
     THROW_HR_IF(E_HANDLE, _hFile.get() == INVALID_HANDLE_VALUE);
+    THROW_HR_IF(E_HANDLE, _hFile.get() == nullptr);
```
Comment (DHowett) [inline src/interactivity/base/HostSignalInputThread.cpp]: huh, i thought that these were the same

moreover, however: `!_hFile` is the valid way to check for presence in a wil handle

File: src/interactivity/base/RemoteConsoleControl.cpp [hunk 33]
```diff
@@ -32,18 +32,23 @@ template<typename T>
     packet.code = signalCode;
     packet.data = payload;
 
-    DWORD dwWritten = 0;
-    if (!WriteFile(pipe, &packet, sizeof(packet), &dwWritten, nullptr))
+    DWORD bytesWritten = 0;
+    if (!WriteFile(pipe, &packet, sizeof(packet), &bytesWritten, nullptr))
     {
-        return NTSTATUS_FROM_WIN32(::GetLastError());
+        NT_RETURN_NTSTATUS(static_cast<NTSTATUS>(NTSTATUS_FROM_WIN32(::GetLastError())));
```
Comment (DHowett) [inline src/interactivity/base/RemoteConsoleControl.cpp:38]: i... thought we moved to wil because there was a macro that made this less ugly, not a macro that made it **more** ugly 😉

Comment (lhecker) [reply src/interactivity/base/RemoteConsoleControl.cpp:38]: For the glory of error tracing! 🥲
It's really weird that the `static_cast` is necessary...

Comment (miniksa) [reply src/interactivity/base/RemoteConsoleControl.cpp:38]: the only plus side to this mess is that it is more debuggable with the wil tracelog. You're right... wil was supposed to solve this but then on further inspection... someone implemented like 4 of the functions and not the ones I needed (`NT_RETURN_NTSTATUS_IF` and `NT_RETURN_NTSTATUS_IF_WIN32_BOOL_FALSE` etc.)
