### PR TITLE
Ignore KeyDown events during Alt-Numpad Input

### LINKED ISSUE #1401: TerminalControl handles ALT+NUMPAD input poorly
When the user enters <kbd>Alt-123</kbd> it looks like we're doing this:

* Sending `ESC` `1`
* Sending `2`
* Sending `3`
* Sending whichever character <kbd>Alt-123</kbd> corresponds to.

Powershell and bash (readline) interpret alt-number as "enter digit-argument mode." Digit argument mode usually means "repeat the first character N times" ... so this results in character `123` being added to the buffer 123 times.

We should definitely fix that.

# original content

## Environment

```
Windows build number: 10.0.18922.1000 and 10.0.18362.175
Windows Terminal version (if applicable): 0.2.1715.0

Any other software?
Powershell Core 7.0.0-preview.1
Powershell Core 6.2.1
Windows Powershell 5.1
```

## Steps to reproduce
 - Open Powershell (whatever version listed above) session in the Terminal
 - try to insert an ascii char by:
   - press and hold  `ALT` key
   - digit whatever number (for example 126 corresponding to `~`)

## Expected behavior
a tilde (`~`) is inserted
WinTerPS7ok

## Actual behavior

127 tildes are inserted
WinTerPS7

The same thing happens for all the versions of Powershell listed above

### PR DESCRIPTION
**Pull request by leonMSFT**
## Summary of the Pull Request
Alt-Numpad# input would be escaping each numkey before sending it through. This would result in some weird behavior, for example, in powershell, where the first alt-numpad# would start digit argument and once the user releases alt, a character is sent through and digit argument would repeat that character X times. To resolve this, we simply need to ignore KeyDowns where Alt is held and a Numpad# is pressed. 

Once Alt is released, we'll receive a character through `TSFInputControl`, not `TermControl::CharacterHandler`. It seems that the `CoreTextEditContext` in `TSFInputControl` intercepts the character before it gets to `TermControl`. TSF will then send the received character through as normal.

## PR Checklist
* [x] Closes #1401 
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [x] Tests added/passed

## Validation Steps Performed
Testing various combinations of Alt-Numpad# consistently sends through only one instance of the expected symbols.

### CODE REVIEW

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 1]
```diff
@@ -724,6 +724,14 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
         const auto scanCode = gsl::narrow_cast<WORD>(e.KeyStatus().ScanCode);
         bool handled = false;
 
+        // Alt-Numpad# input will send us a character once the user releases Alt, so we should be ignoring the individual keydowns.
+        // The character will be sent through the TSFInputControl.
+        if (modifiers.IsAltPressed() && (e.OriginalKey() >= VirtualKey::NumberPad0 && e.OriginalKey() <= VirtualKey::NumberPad9))
```
Comment (zadjii-msft) [inline src/cascadia/TerminalControl/TermControl.cpp]:
```suggestion
        // See GH#1401 for more details
        if (modifiers.IsAltPressed() && (e.OriginalKey() >= VirtualKey::NumberPad0 && e.OriginalKey() <= VirtualKey::NumberPad9))

```

Always handy to link back to the issue for weird code snippets like this
