### PR TITLE
Fix garbling when copying multibyte text via OSC 52

### LINKED ISSUE #7819: OSC52 does not handle UTF-8 correctly ("copying content using tmux copy mode doesn't paste properly")
# Environment

Windows build number: `Microsoft Windows [Version 10.0.19041.508]`
Windows Terminal version: 1.3.2651.0

Other software:

Tmux version: `tmux 3.0a`
Running Ubuntu 20.04.1 LTS inside of WSL2

# Steps to reproduce

All the steps to reproduce this issue are stated in this [issue](https://github.com/tmux/tmux/issues/2407) that I created.
Please read that issue as it contains some more information about my environment and some relevant comments.

It seems like this issue doesn't relate to a problem with tmux but rather a problem with the Windows Terminal or the windows clipboard.

# Expected behavior
When I copy content using tmux copy mode I would like to have the ability to paste it outside of tmux containing the exact same characters which can be seen here in a browser search bar:
image

# Actual behavior
The content is not pasted properly as [this character](https://www.fileformat.info/info/unicode/char/2019/index.htm) shows up as cryptic characters:
image

### PR DESCRIPTION
**Pull request by amaya382**
This commit adds a missing conversion utf8 to utf16 in decoding base64
for handling multibyte text in copying via OSC 52.

## Validation Steps Performed
* automatically
    * Tests w/ multibyte characters
* manually
    * case1
        * Executed `printf "\x1b]52;;%s\x1b\\" "$(printf '👍👍🏻👍🏼👍🏽👍🏾👍🏿' | base64)"`
        * Verified `👍👍🏻👍🏼👍🏽👍🏾👍🏿` in my clipboard
    * case2
        * Copied `👍👍🏻👍🏼👍🏽👍🏾👍🏿` by tmux 2.6 default copy function (OSC 52)
        * Verified `👍👍🏻👍🏼👍🏽👍🏾👍🏿` in my clipboard

Closes #7819

### CODE REVIEW

File: src/terminal/parser/ut_parser/Base64Test.cpp [hunk 1]
```diff
@@ -84,5 +84,18 @@ class Microsoft::Console::VirtualTerminal::Base64Test
...
+        success = Base64::s_Decode(L"44Gr44G744KT44GU5rGJ6K+t7ZWc6rWt", result);
+        VERIFY_ARE_EQUAL(true, success);
+        VERIFY_ARE_EQUAL(L"にほんご汉语한국", result);
+
+        // U+d83d U+dc4d U+d83d U+dc4d U+d83c U+dffb U+d83d U+dc4d U+d83c U+dffc U+d83d
+        // U+dc4d U+d83c U+dffd U+d83d U+dc4d U+d83c U+dffe U+d83d U+dc4d U+d83c U+dfff
+        result = L"";
+        success = Base64::s_Decode(L"8J+RjfCfkY3wn4+78J+RjfCfj7zwn5GN8J+PvfCfkY3wn4++8J+RjfCfj78=", result);
+        VERIFY_ARE_EQUAL(true, success);
+        VERIFY_ARE_EQUAL(L"👍👍🏻👍🏼👍🏽👍🏾👍🏿", result);
```
Comment (zadjii-msft) [inline src/terminal/parser/ut_parser/Base64Test.cpp:99]: I'm _mildly_ worried about putting the emoji in the file as literals like this - I know in the past we've had issues where someone's text editor saves a file with emoji as the wrong encoding which then end up breaking the tests later. I could be mistaken though, I'll let @DHowett or @miniksa refresh my memory if this is a bad idea or not.

**Review by zadjii-msft — APPROVED** [review]
Looks good to me! As far as the spellcheck is concerned, I'd update the `L"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789\+/"
` line in `patterns.txt` to not have an `L` at the start of it, and I'd add `strchr` to `apis.txt`

File: src/terminal/parser/base64.cpp [hunk 2]
```diff
@@ -176,7 +177,11 @@ bool Base64::s_Decode(const std::wstring_view src, std::wstring& dst) noexcept
         return false;
     }
 
-    return true;
+    const auto wstrLen = MultiByteToWideChar(CP_UTF8, 0, mbStr.c_str(), (int)mbStr.length(), nullptr, 0);
+    dst.resize(wstrLen);
+    const auto err = MultiByteToWideChar(CP_UTF8, 0, mbStr.c_str(), (int)mbStr.length(), dst.data(), wstrLen);
```
Comment (DHowett) [inline src/terminal/parser/base64.cpp:182]: Would you mind switching this to `til::u8u16`? We can safely replace this with ...

```suggestion
    dst = std::move(til::u8u16(mbStr));
```

It wraps up MultiByteToWideChar but also supports collecting partials and deals w/ the double-call interface (by estimating the required length.)

Comment (DHowett) [reply src/terminal/parser/base64.cpp:182]: you can probably use the HRESULT version actually.

```
return SUCCEEDED(til::u8u16(mbStr, dst));
```

:smile:

**Review by DHowett — CHANGES_REQUESTED** [review]

File: src/terminal/parser/base64.cpp (hunk 2 above)
Comment (amaya382) [reply src/terminal/parser/base64.cpp]: It works as expected, thanks!

File: src/terminal/parser/ut_parser/Base64Test.cpp (hunk 1 above)
Comment (DHowett) [reply src/terminal/parser/ut_parser/Base64Test.cpp:99]: Naw, we've done this before. We'll survive!

**Review by DHowett — APPROVED** [review]
Thanks so much for fixing this. I really appreciate it!
