### PR TITLE
Fix a memory leak in onecore interactivity

### LINKED ISSUE #6759: ConIoSrvComm::Connect memory leak
The ConIoSrvComm::Connect function has a memory leak from using the RtlCreateUnicodeString function incorrectly:

https://github.com/microsoft/terminal/blob/396cbbb151ccd6fc9ae0356771ce1a5af5623e48/src/interactivity/onecore/ConIoSrvComm.cpp#L101-L106

RtlCreateUnicodeString creates a copy of the string on the process heap and the PortName variable has local-scope. The string doesn't get freed with RtlFreeUnicodeString before the function returns creating a memory leak.

CIS_ALPC_PORT_NAME is a constant string and the PortName variable should instead be initialized using the RTL_CONSTANT_STRING macro:

`static UNICODE_STRING PortName = RTL_CONSTANT_STRING(CIS_ALPC_PORT_NAME);`

It could alternatively use RtlInitUnicodeString but since the string is hard-coded it should be using the macro.

### PR DESCRIPTION
**Pull request by zadjii-msft**
As noted in #6759:

> `RtlCreateUnicodeString` creates a copy of the string on the process heap and the `PortName` variable has local-scope. The string doesn't get freed with `RtlFreeUnicodeString` before the function returns creating a memory leak.
> `CIS_ALPC_PORT_NAME` is a constant string and the `PortName` variable should instead be initialized using the `RTL_CONSTANT_STRING` macro:
>
> ```c++
> static UNICODE_STRING PortName = RTL_CONSTANT_STRING(CIS_ALPC_PORT_NAME);
> ```

I actually built this in the OS repo to make sure it'll still build, because this code doesn't even build outside Windows.

* [x] Closes #6759
* I work here.

### CODE REVIEW

File: src/interactivity/onecore/ConIoSrvComm.cpp [hunk 1]
```diff
@@ -71,12 +71,11 @@ ConIoSrvComm::~ConIoSrvComm()
 
 [[nodiscard]] NTSTATUS ConIoSrvComm::Connect()
 {
-    BOOL Ret = TRUE;
     NTSTATUS Status = STATUS_SUCCESS;
 
     // Port handle and name.
     HANDLE PortHandle;
-    UNICODE_STRING PortName;
+    static UNICODE_STRING PortName = RTL_CONSTANT_STRING(CIS_ALPC_PORT_NAME);
```
Comment (lhecker) [inline src/interactivity/onecore/ConIoSrvComm.cpp:78]: `static constexpr`? If not then `static const`.

**Review by lhecker — APPROVED** [review]

File: src/interactivity/onecore/ConIoSrvComm.cpp (hunk 1 above)
Comment (DHowett) [reply src/interactivity/onecore/ConIoSrvComm.cpp:78]: This requires a deadly const_cast -- if that is okay, let's do constexpr!

```diff
diff --git a/onecore/windows/core/console/open/src/interactivity/onecore/ConIoSrvComm.cpp b/onecore/windows/core/console/open/src/interactivity/onecore/ConIoSrvComm.cpp
index cdeebed38c365..6c1b4ffc465b0 100644
--- a/onecore/windows/core/console/open/src/interactivity/onecore/ConIoSrvComm.cpp
+++ b/onecore/windows/core/console/open/src/interactivity/onecore/ConIoSrvComm.cpp
@@ -153,7 +145,7 @@ ConIoSrvComm::~ConIoSrvComm()
     // Request to connect to the server.
     ConnectionMessageLength = sizeof(CIS_MSG);
     Status = NtAlpcConnectPort(&PortHandle,
-                               &PortName,
+                               const_cast<PUNICODE_STRING>(&PortName),^M
                                NULL,
                                &PortAttributes,
                                ALPC_MSGFLG_SYNC_REQUEST,
```

Comment (lhecker) [reply src/interactivity/onecore/ConIoSrvComm.cpp:78]: In that case I'd personally use a regular static... Better safe than sorry, since it's possible it might do reference counting on it, right?

**Review by miniksa — APPROVED** [review]
I'd rather it just stay the static at this point too.
