### PR TITLE
When the renderer fails, try to fall back to D2D + WARP

### LINKED ISSUE #15601: Brand new Windows 10 install: This terminal has encountered an issue with the graphics driver and it could not recover in time.
### Windows Terminal version

1.17.11461.0

### Windows build number

10.0.19045.0

### Other Software

N/A

### Steps to reproduce

- New computer, fresh install of Windows 10
- Run all updates for Windows 10
- Ensure all drivers (graphics card, etc.) are up-to-date
- Enable WSL
- Install Terminal (or Terminal Preview, both versions behave identically)
- Open Terminal (or Terminal Preview) and receive the error message, "This terminal has encountered an issue with the graphics driver and it could not recover in time.  It has been suspended."
- Terminal is completely unusable, there is no place to type anything or use the terminal

image

### Expected Behavior

- New computer, fresh install of Windows 10
- Run all updates for Windows 10
- Ensure all drivers (graphics card, etc.) are up-to-date
- Enable WSL
- Install Terminal (or Terminal Preview, both versions behave identically)
- Open Terminal (or Terminal Preview) and be able to use it

### Actual Behavior

- Open Terminal (or Terminal Preview) and receive the error message, "This terminal has encountered an issue with the graphics driver and it could not recover in time.  It has been suspended."
- Terminal is completely unusable, there is no place to type anything or use the terminal

image

### LINKED ISSUE #18198: Renderer encountered an unexpected error: 0x887a0001
### Windows Terminal version

1.22.2912.0

### Windows build number

10.0.26100.2314

### Other Software

I use terminal with WSL, ssh and tmux.

### Steps to reproduce

No particular steps, I get this error at random and must restart the app.

### Expected Behavior

That I don't have to restart Windows Terminal unless I reboot Windows.

### Actual Behavior

I get this error at random and must restart the app.
This can happen after 15 minutes or after two weeks of running. It happens a few times per month. I use the windows terminal constantly.

Image

### PR DESCRIPTION
**Pull request by DHowett**
This commit also ups the number of render failures that are permissible to 6 (one try plus 5 retries), and moves us to use an exponential backoff rather than a simple geometric one.

It also suppresses the dialog box in case of present failures for Stable users. I feel like the warning dialog should be used for something that the user can actually do something about...

Closes #15601
Closes #18198

### CODE REVIEW

File: src/renderer/atlas/AtlasEngine.r.cpp [hunk 1]
```diff
@@ -61,6 +61,9 @@ catch (const wil::ResultException& exception)
         return E_PENDING;
     }
 
+#ifndef NDEBUG
```
Comment (DHowett) [inline src/renderer/atlas/AtlasEngine.r.cpp]: Leonard this may be controversial, but I think that the warning prompt is only useful for shader and font and etc problems the user may stand a chance of fixing

Comment (DHowett) [reply src/renderer/atlas/AtlasEngine.r.cpp]: otherwise, it displays five dialogs in quick succession and then still restarts rendering now after turning on d2d/warp

File: src/renderer/base/renderer.cpp [hunk 2]
```diff
@@ -355,8 +356,8 @@ DWORD Renderer::_timerToMillis(TimerRepr t) noexcept
         }
 
         // Add a bit of backoff.
-        // Sleep 150ms, 300ms, 450ms before failing out and disabling the renderer.
-        Sleep(renderBackoffBaseTimeMilliseconds * (maxRetriesForRenderEngine - tries));
+        // Sleep 100, 200, 400, 600, 800, 1600ms before failing out and disabling the renderer.
+        Sleep(renderBackoffBaseTimeMilliseconds * (1 << (maxRetriesForRenderEngine - tries - 1)));
```
Comment (lhecker) [inline src/renderer/base/renderer.cpp]: We could take this opportunity to swap the loop around to "for i from 0 to maxRetries". It'd be more readable IMO, particularly down here.

**Review by lhecker — APPROVED** [review]

File: src/renderer/atlas/AtlasEngine.r.cpp (hunk 1 above)
Comment (lhecker) [reply src/renderer/atlas/AtlasEngine.r.cpp]: The warning callback has been very helpful to me to diagnose some of the reported issues we received. Particularly just recently it showed that DWrite failed because the font file was locked. I wasn't even aware we had a distinct error type for that, but we do, and it meant that we can boldly assert that this isn't an us-issue.

Comment (lhecker) [reply src/renderer/atlas/AtlasEngine.r.cpp]: ...Perhaps we should instead check if the dialog is already being shown and then ignore a 2nd and following error/warning?

Comment (DHowett) [reply src/renderer/atlas/AtlasEngine.r.cpp]: I don't hate that, but like... also, we lack the capacity to _dismiss_ that warning when we retry and it works. Right now I am prioritizing the user experience, where something happens and they don't need to dismiss 1..N dialogs _per terminal control_ per render try

Comment (lhecker) [reply src/renderer/atlas/AtlasEngine.r.cpp]: I thought dialogs were per page? It's a good point though that it may spam too much.
But without the dialog I'm afraid that we may be missing out on useful signal to our users. Given that on a stable system we should never see the warning in the first place, and _certainly_ not on the regular, I'm a bit dismayed by this complete removal.

Comment (DHowett) [reply src/renderer/atlas/AtlasEngine.r.cpp]: Unfortunately, most of our few hundred million users interact with terminal because they have to, not because they want to.

How would you feel about keeping the dialog for preview/canary/dev and disabling it for stable?

Comment (lhecker) [reply src/renderer/atlas/AtlasEngine.r.cpp]: Yeah, I think that's a good middle ground because we can tell them to use a different version for a while and we'll get informed when they hit a warning.

File: src/renderer/base/renderer.cpp (hunk 2 above)
Comment (DHowett) [reply src/renderer/base/renderer.cpp]: I did. I moved the sleep earlier, as well, so that it doesn't sleep after it fails but before it presents the error message.

The backoff steps are only 100 200 400 800 now.

Should I shift them to be 200 400 800 1600?

File: src/renderer/base/renderer.cpp [hunk 3]
```diff
@@ -326,40 +327,43 @@ DWORD Renderer::_timerToMillis(TimerRepr t) noexcept
 // - HRESULT S_OK, GDI error, Safe Math error, or state/argument errors.
 [[nodiscard]] HRESULT Renderer::PaintFrame()
 {
-    auto tries = maxRetriesForRenderEngine;
-    while (tries > 0)
+    HRESULT hr{ S_FALSE };
+    for (auto attempt = 0; attempt < maxRetriesForRenderEngine; ++attempt)
```
Comment (lhecker) [inline src/renderer/base/renderer.cpp]: This probably complains in x86 because attempt is int and maxRetriesForRenderEngine is unsigned int.

File: src/renderer/base/renderer.cpp [hunk 4]
```diff
@@ -326,40 +327,43 @@ DWORD Renderer::_timerToMillis(TimerRepr t) noexcept
...
 {
-    auto tries = maxRetriesForRenderEngine;
-    while (tries > 0)
+    HRESULT hr{ S_FALSE };
+    for (auto attempt = 0; attempt < maxRetriesForRenderEngine; ++attempt)
     {
+        if (attempt > 0) [[unlikely]]
+        {
+            // Add a bit of backoff.
+            // Sleep 100, 200, 400, 600, 800ms before failing out and disabling the renderer.
```
Comment (lhecker) [inline src/renderer/base/renderer.cpp]: This should be 100, 200, 400, 800, 1600, no? That's 3.1s which seems fine to me (re: your other question).

**Comment by DHowett** [comment]
I added some tracepoints to the rewritten render loop,

```
DH: Renderer returned E_PENDING The data necessary to complete this operation is not yet available.
DH: Sleeping for 100
DH: Renderer returned E_PENDING The data necessary to complete this operation is not yet available.
DH: Sleeping for 200
DH: Renderer returned E_PENDING The data necessary to complete this operation is not yet available.
DH: Sleeping for 400
DH: Renderer returned E_PENDING The data necessary to complete this operation is not yet available.
DH: Sleeping for 800
DH: Renderer returned E_PENDING The data necessary to complete this operation is not yet available.
DH: RENDERER FINALLY FAILED WITH E_PENDING The data necessary to complete this operation is not yet available.
```

File: src/renderer/base/renderer.cpp (hunk 3 above)
Comment (DHowett) [reply src/renderer/base/renderer.cpp]: ALWAYS

File: src/renderer/base/renderer.cpp (hunk 4 above)
Comment (DHowett) [reply src/renderer/base/renderer.cpp]: well, so, no. after the fifth failure we don't retry agian. it's actually max TRIES, not max RETRIES. We can change that to be retries though

Comment (lhecker) [reply src/renderer/base/renderer.cpp]: 1.5s also seems fine to me. It probably doesn't matter too much. I think "max tries" may be better than retries... 🤔
