### PR TITLE
Fix #8458: Handle all Ctrl-key combinations

### LINKED ISSUE #8458: Unable to use any mapping containing 'CTRL+\' in apps
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): Windows Terminal Preview v1.5.3242.0
```

# Steps to reproduce
1. Try to use a mapping containing `CTRL+\`: for instance `CTRL+\ CTRL+n` in Neovim to quit the built-in terminal or by adding a new mapping in `tmux`.

# Expected behavior
Nothing happens. It seems the `CTRL+\` sequence is completely ignored by Windows Terminal. I've tried it in Powershell and in WSL and same issue. I've also tried with another terminal emulator (kitty) and `CTRL+\` works fine there.

I found related issues: #1288, #521 but they are marked resolved and I'm still getting the bug. Any idea why?

# Actual behavior
The `CTRL+\` sequence should work.

### PR DESCRIPTION
**Pull request by lhecker**
Pressing Ctrl+\ produces `^\` using the US keyboard layout, thanks to Ctrl-key mappings inside the keyboard layout, whereas some layouts, like the UK extended layout, don't contain those. This causes the character value to be zero and previously caused no VT sequence to be generated under these situations. This PR employs `MapVirtualKeyW` to infer the missing characters.
As a side effect this PR effectively causes _all_ major keys on the keyboard to produce Ctrl+combinations now.

## PR Checklist
* [x] Closes #8458
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [x] Tests passed

## Validation Steps Performed

Compared all major keys in combination with Ctrl with the app store version of Terminal using `showkey` in WSL. All keys that previously worked still appear to continue to work.

### CODE REVIEW

File: src/terminal/input/terminalInput.cpp [hunk 1]
```diff
@@ -598,6 +598,13 @@ bool TerminalInput::HandleKey(const IInputEvent* const pInEvent)
         return true;
     }
 
+    // Check any other key mappings (like those for the F1-F12 keys).
+    const auto mapping = _getKeyMapping(keyEvent, _ansiMode, _cursorApplicationMode, _keypadApplicationMode);
+    if (_translateDefaultMapping(keyEvent, mapping, senderFunc))
+    {
+        return true;
+    }
+
```
Comment (lhecker) [inline src/terminal/input/terminalInput.cpp:607]: Since the Ctrl-key handling block below now handles many more combinations I decided to move this block of code upwards. This should prevent any accidental key mapping conflicts.

**Review by zadjii-msft — APPROVED** [review]
God why is input such a disaster 🙃

Thanks for looking into this and fixing it

**Comment by lhecker** [comment]
It might take me until next weekend to fix the failing unit tests by the way.

**Comment by lhecker** [comment]
Turns out there was a reason why `_translateDefaultMapping` happens at the very end of that method. Unit tests catched it and I added an appropriate comment.

**Review by miniksa — APPROVED** [review]
Wonderful. Thanks.
