### PR TITLE
Limit Concept of TextBuffer's Size in UIA

### LINKED ISSUE #4485: Terminal hangs when navigating (back?) by word in Narrator
# Environment

```none
Windows build number: Vb
Windows Terminal version (if applicable): 0.9.362.0
```

# Steps to reproduce

Navigate by word.

# Expected behavior

It does not hang.

# Actual behavior

It hangs rather a lot.

We may have a long (very long) loop in...

```
00 (Inline Function) --------`-------- TerminalControl!Microsoft::Console::Types::Viewport::{ctor}+0x5 [E:\BA\19\s\src\types\Viewport.cpp @ 10] 
01 (Inline Function) --------`-------- TerminalControl!Microsoft::Console::Types::Viewport::FromInclusive+0x5 [E:\BA\19\s\src\types\Viewport.cpp @ 26] 
02 (Inline Function) --------`-------- TerminalControl!Microsoft::Console::Types::Viewport::FromExclusive+0x20 [E:\BA\19\s\src\types\Viewport.cpp @ 34] 
03 (Inline Function) --------`-------- TerminalControl!Microsoft::Console::Types::Viewport::FromDimensions+0x33 [E:\BA\19\s\src\types\Viewport.cpp @ 63] 
04 000000e7`190fdab0 00007fff`15a954ee TerminalControl!TextBuffer::GetSize+0xc1 [E:\BA\19\s\src\buffer\out\textBuffer.cpp @ 663] 
05 000000e7`190fdb00 00007fff`15a8dfd2 TerminalControl!TextBufferCellIterator::TextBufferCellIterator+0xee [E:\BA\19\s\src\buffer\out\textBufferCellIterator.cpp @ 43] 
06 (Inline Function) --------`-------- TerminalControl!TextBufferCellIterator::{ctor}+0x1e [E:\BA\19\s\src\buffer\out\textBufferCellIterator.cpp @ 23] 
07 (Inline Function) --------`-------- TerminalControl!TextBuffer::GetCellDataAt+0x1e [E:\BA\19\s\src\buffer\out\textBuffer.cpp @ 119] 
08 (Inline Function) --------`-------- TerminalControl!TextBuffer::GetTextDataAt+0x1e [E:\BA\19\s\src\buffer\out\textBuffer.cpp @ 108] 
09 000000e7`190fdb80 00007fff`15a89fe1 TerminalControl!TextBuffer::MoveToNextWord+0x122 [E:\BA\19\s\src\buffer\out\textBuffer.cpp @ 1219] 
0a 000000e7`190fdc90 00007fff`15a8926b TerminalControl!Microsoft::Console::Types::UiaTextRangeBase::_moveEndpointByUnitWord+0x1d1 [E:\BA\19\s\src\types\UiaTextRangeBase.cpp @ 1129] 
0b 000000e7`190fdd60 00007fff`15a7d127 TerminalControl!Microsoft::Console::Types::UiaTextRangeBase::Move+0xbb [E:\BA\19\s\src\types\UiaTextRangeBase.cpp @ 680] 
```

### PR DESCRIPTION
**Pull request by carlos-zamora**
## Summary of the Pull Request
In UIA Providers, update the concept of the size of the text buffer to just go down to the virtual bottom. This significantly increases performance to the point that it can even be used in the Debug build.

## PR Checklist
* [x] Closes #4485 
* [x] CLA signed.

## Detailed Description of the Pull Request / Additional comments
We already actually have this concept exposed to us via the IUiaData. So we're just leveraging that and putting it in a helper function `_getBufferSize()`.

## Validation Steps Performed
Tested word nav on Narrator (previously hung). Now it works on the Debug build. Previously, using the release build was necessary to be able to test this feature.

### CODE REVIEW

File: src/types/UiaTextRangeBase.cpp [hunk 1]
```diff
@@ -313,7 +313,12 @@ IFACEMETHODIMP UiaTextRangeBase::ExpandToEnclosingUnit(_In_ TextUnit unit) noexc
         {
             // expand to word
             _start = buffer.GetWordStart(_start, _wordDelimiters, true);
+
+            // GetWordEnd may return the end of the TextBuffer we need to clamp
+            // this value to our bufferSize (which may be different from the
+            // actual size of the text buffer)
             _end = buffer.GetWordEnd(_start, _wordDelimiters, true);
+            bufferSize.Clamp(_end);
```
Comment (DHowett-MSFT) [inline src/types/UiaTextRangeBase.cpp]: I think this will damage the coordinate's exclusiveness.

**Comment by carlos-zamora** [comment]
@msftbot merge this in 2 minutes
