### PR TITLE
[DefApp] Move from Monarch multi instance servers to Peasant single instance servers

### LINKED ISSUE #10358: Defterm launches into quake window
### Windows Terminal version (or Windows build number)

1.9.1445.0

### Other Software

_No response_

### Steps to reproduce

* Launch Windows Terminal Preview and ensure Terminal Preview is set as your default terminal
* Open a quake window
* Dismiss quake window with `Win+\``
* Close initial terminal window
* Launch a ps1 file from file explorer

Since the quake window is the only open Terminal window, defterm launches into that instead of creating a new terminal instance.

### Expected Behavior

A new terminal instance is created.

### Actual Behavior

The quake window is opened and attempts to run the selected file.

### PR DESCRIPTION
**Pull request by leonMSFT**
- Monarch no longer sets itself up as a `CTerminalHandoff` multi instance server by default
- In fact, `CTerminalHandoff` will only ever be a single instance server 
- When COM needs a `CTerminalHandoff`, it launches `wt.exe -embedding`, which gets picked up by the Monarch and then gets handed off to itself/peasant depending on user settings.
- Peasant now recognizes the `-embedding` commandline and will start a `CTerminalHandoff` single instance listener, and receives the connection into a new tab.

Closes #10358

### CODE REVIEW

**Comment by DHowett** [comment]
LOVE IT. IT MAKES SO MUCH SENSE

**Comment by zadjii-msft** [comment]
@msftbot make sure @miniksa signs off on this

File: src/cascadia/TerminalConnection/CTerminalHandoff.cpp [hunk 1]
```diff
@@ -93,8 +93,15 @@ static HRESULT _duplicateHandle(const HANDLE in, HANDLE& out) noexcept
...
+    // Stash a local copy of _pfnHandoff before we stop listening.
+    auto localPfnHandoff = _pfnHandoff;
+
+    // Because we are REGCLS_SINGLEUSE... we need to `CoRevokeClassObject` after we handle this ONE call.
+    // COM does not automatically clean that up for us. We must do it.
+    s_StopListening();
+
     // Report an error if no one registered a handoff function before calling this.
-    RETURN_HR_IF_NULL(E_NOT_VALID_STATE, _pfnHandoff);
+    RETURN_HR_IF_NULL(E_NOT_VALID_STATE, localPfnHandoff);
```
Comment (zadjii-msft) [inline src/cascadia/TerminalConnection/CTerminalHandoff.cpp:104]: Should this line be _above_ the `s_StopListening` call? Or should we always stop listening, even if this is null. 


I suppose, if this is null, then we do want to stop being the server for inbound connections first, otherwise we'll leave ourself polluted. 

okay this makes sense

**Review by zadjii-msft — APPROVED** [review]
Hokay so lemme get this straight:
1. COM creates a `wt -embedding` process to try and host the incoming connection
2. that wt automatically tosses the commandline to the Monarch to have it deal with it. 
3. The monarch will then either
 * Toss the commandline `wt -embedding` to the appropriate peasant, who then 
   * starts the COM server
   * accepts the connection
   * stops the server
   * opens the tab
 * Or the monarch decides that this connection should be a new peasant (a new window)
   * the new window opens
   * starts the server, accepts the connection, ... opens the tab

all based on what we already had. 

That's fricken amazing.

File: src/cascadia/TerminalApp/TerminalPage.cpp [hunk 2]
```diff
@@ -2363,13 +2341,43 @@ namespace winrt::TerminalApp::implementation
...
+            std::condition_variable cv;
+
+            std::unique_lock<std::mutex> lock{ mtx };
+
+            Dispatcher().RunAsync(CoreDispatcherPriority::Normal, [&]() {
+                auto hr = _OpenNewTab(nullptr, connection);
+
+                _SummonWindowRequestedHandlers(*this, nullptr);
+
+                std::unique_lock<std::mutex> lock{ mtx };
```
Comment (miniksa) [inline src/cascadia/TerminalApp/TerminalPage.cpp:2373]: Something is up here and I'm not certain what it is.

It worries me that you covered one definition of lock (since the lambda captured everything) with another more local definition of the same thing.

The inside of this lambda isn't even using the lock. Is it? Am I missing an implicit piece of the construction here?

File: src/cascadia/TerminalConnection/CTerminalHandoff.cpp [hunk 3]
```diff
@@ -93,8 +93,15 @@ static HRESULT _duplicateHandle(const HANDLE in, HANDLE& out) noexcept
 //   from the registered handler event function.
 HRESULT CTerminalHandoff::EstablishPtyHandoff(HANDLE in, HANDLE out, HANDLE signal, HANDLE ref, HANDLE server, HANDLE client) noexcept
 {
+    // Stash a local copy of _pfnHandoff before we stop listening.
```
Comment (miniksa) [inline src/cascadia/TerminalConnection/CTerminalHandoff.cpp:96]: I wonder if there is a race here between the monarch turning on a listener at the same time on another thread as a previous request is being served out of the mta Com pool and turning it off. Maybe we should make methods on this class like startlistening, stoplistening, and/or this establishptyhandoff one use a synchronization primitive so multiple things can't happen to it at once...

**Review by miniksa — COMMENTED** [review]
It's pretty close. Just a few questions. I don't feel it is fair for me to block or sign though because I helped you debug and coauthor some of this. Hopefully @DHowett or @lhecker will do the second after we can look at these comments.

(it's otherwise fine from my pov)

File: src/cascadia/TerminalApp/TerminalPage.cpp (hunk 2 above)
Comment (leonMSFT) [reply src/cascadia/TerminalApp/TerminalPage.cpp:2373]: I should probably change the name of the lock inside of the lambda, that's a good point.
As for whether the inside of the lambda is using the lock, we should technically be acquiring the lock before modifying `finalVal` since that's the shared resource right?

Comment (miniksa) [reply src/cascadia/TerminalApp/TerminalPage.cpp:2373]: I need an adult to answer that. I just copied this pattern from somewhere else. @lhecker halp.

Comment (miniksa) [reply src/cascadia/TerminalApp/TerminalPage.cpp:2373]: (This is where I stole the idea from: https://github.com/microsoft/terminal/blob/d57fb84557e993017a2fecc346ae62cef1803962/src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp#L57-L78)

Comment (lhecker) [reply src/cascadia/TerminalApp/TerminalPage.cpp:2373]: You can use [`til::latch`](https://github.com/microsoft/terminal/blob/e7108332f72a3c14c72a65484d091c4e79ab28b2/src/inc/til/latch.h) for this now. Less overhead & easier to use. 🙂
* You need to import it yourself as `<til/latch.h>` (just like a stdlib header - no need to put it into `pch.h`)
* Instantiate it as `til::latch latch(1);`
* Replace the mutex/condition_variable code inside the lambda with `lath.count_down()`
* Replace the mutex/condition_variable code outside the lambda with `latch.wait()`
* Just make sure to write the data before counting down and only read from it after wait() has returned.

**Review by miniksa — APPROVED** [review]

**Review by lhecker — APPROVED** [review]
