### PR TITLE
Make the alt buffer inherit cursor state from the main buffer

### LINKED ISSUE #3545: Alt buffer should share more state with main buffer
# Environment

Windows build number: Version 10.0.18362.356

# Steps to reproduce

Open a WSL shell in conhost and execute the following command:

    printf "\ec\e[1;15r\e[3g\e[1;20H\eH\e[?25l\e[9;20H\e[?1049hstart\r\e[99Bmargin\e[H\ttab\n"

This initialises a number of terminal properties.

- The scrolling margins are set to 1:15 (`DECSTBM`).
- The tabstops are cleared and then a single tabstop is set at column 20 (`TBC`/`HTS`).
- The cursor blinking is disabled (`DECTCEM`).
- The cursor position is set to line 9 column 20 (`CUP`).

It then switches to the alternate screen buffer (private mode 1049) and "tests" the state.

- The text "start" is output to indicate the starting position.
- The cursor is moved down 99 lines (`CUD`), and the text "margin" is output to indicate the bottom margin position.
- The cursor is moved to the home position (`CUP`) and a tab is output, followed by the text "tab" to indicate the position of the tab stop.

# Expected behavior

I would expect all of the initial state to be inherited by the alt buffer, producing the following results:

- The "start" text should be on line 9, column 20, i.e. the position before the switch to the alt buffer.
- The "margin" text should be on line 15, the bottom margin.
- The "tab" text should be in column 20, the position of the tab stop that was set.
- The cursor should be invisible.

Here's what the output looks like in XTerm:

image

# Actual behavior

When switching to the alt buffer in conhost, we reset all those properties, producing the following results:

- The "start" text is in the top left corner.
- The "margin" text is at the bottom of the screen.
- The "tab" text is in column 9.
- The cursor is visible.

Here's what our output looks like:

image

The reason for this behaviour is because these properties are part of the `SCREEN_INFORMATION` class, and the alternate buffer is implemented as a separate instance of that class, when it should really be sharing much of that state with the main buffer.

The scroll margins are a little more complicated, since those properties are also duplicated in the `AdaptDispatch` class. And this can result in some weirdness when switching to the alt buffer since the two sets of values can end up out of sync.

### PR DESCRIPTION
**Pull request by j4james**
When switching to the alt buffer, the starting cursor position, style,
and visibility is meant to be inherited from the main buffer. Similarly,
when returning to the main buffer, any changes made to those attributes
should be copied back (with the exception of the cursor position, which
is restored to its original state). This PR makes sure we handle that
cursor state correctly.

At some point I'd like to move the cursor state out of the
`SCREEN_INFORMATION` class, which would make this inheritance problem a
non-issue. For now, though, I've just made it copy the state from the
main buffer when creating the alt buffer, and copy it back when
returning to the main buffer.

## Validation Steps Performed

I've added some unit tests to verify the cursor state is inherited
correctly when switching to the alt buffer and back again. I also had to
make a small change to one of the existing alt buffer test that relied
on the initial cursor position being at 0;0, which is no longer the
case.

I've verified that the test case in issue #3545 is now working
correctly. I've also confirmed that this fixes a problem in the
_notcurses_ demo, where the cursor was showing when it should have been
hidden.

Closes #3545

### CODE REVIEW

**Review by DHowett — APPROVED** [review]
I'm cool with this. I appreciate that you'll want to refactor Cursor to live elsewhere eventually, and this sounds like an excellent stopgap to me.

**Comment by DHowett** [comment]
As always, _thank you._ We're ever more compliant thanks to your continued efforts :smile:

**Review by zadjii-msft — APPROVED** [review]

**Comment by zadjii-msft** [comment]
@j4james are the other elements of #3545 already fixed? That issue also mentions things about the tab stops, the margins, etc. I wouldn't want to pre-emptively close that issue if there's still actionable work it's tracking 😝

**Comment by j4james** [comment]
> @j4james are the other elements of #3545 already fixed? That issue also mentions things about the tab stops, the margins, etc. I wouldn't want to pre-emptively close that issue if there's still actionable work it's tracking 😝

Sorry, I mean to address that. The tab stops were fixed in PR #5173 and I think the margin issue was probably fixed by PR #3628. All aspects of the #3545 test case are definitely passing now.

**Comment by zadjii-msft** [comment]
Awesome, thanks for following up!

**Comment by lhecker** [comment]
I've rebased one of my branches on top of main and this PR seems to have a flaw unfortunately.
If you run `cmatrix` or `cacafire` (which I assume use the alt buffer?) and press Ctrl+C it'll crash conhost.

File: src/host/screenInfo.cpp [hunk 1]
```diff
@@ -1998,6 +2005,13 @@ void SCREEN_INFORMATION::UseMainScreenBuffer()
         s_RemoveScreenBuffer(psiAlt); // this will also delete the alt buffer
```
Comment (DHowett) [inline src/host/screenInfo.cpp:1998]: I suspect the issue @lhecker found stems from the deletion of psiAlt here before we establish a reference to its cursor :)

Comment (j4james) [reply src/host/screenInfo.cpp:1998]: Yikes. Sorry guys. I don't know why I thought it was a good idea to add that code _after_ the line that clearly says it deletes the alt buffer. Will try and fix ASAP.

Funnily enough I can't actually reproduce the crash with `cmatrix` or `cacafire`, but maybe it only crashes in a debug build?
