### PR TITLE
Expose 'Default' tag to Screen Readers in Color Schemes page

### LINKED ISSUE #14401: [Color Schemes]: Screen reader does not announce the 'default' visible text defined with the 'Campbell' color scheme on the page.
### Windows Terminal version

1.17.3052.0

### Windows build number

Windows 11 Version 22H2 (OS Build 25206.1000)

### Other Software

_No response_

### Steps to reproduce

1. Open Windows Terminal.
2. Open 'Settings > Startup' window with 'Ctrl+,' keys.
3. Turn on Narrator by 'Ctrl+Win+Enter' keys.
4. Navigate to 'Color schemes' list item by down arrow key and select it.
5. Navigate to 'Campbel' by the tab key.
6. Observe the Narrator's announcement here.

**User Experience: -**
Screen reader users will have to navigate in scan mode to get this value information defined with the color control.

**Guideline Reference:**
(https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html)

**Attachments:**
[Screen reader does not announce the 'default' visible text defined with the 'Campbell' color scheme on the page..zip](https://github.com/microsoft/terminal/files/10028996/Screen.reader.does.not.announce.the.default.visible.text.defined.with.the.Campbell.color.scheme.on.the.page.zip)

### Expected Behavior

Screen reader should announce the 'default' visible text defined with the 'Campbell' color scheme on the page. It should announce as '_Campbell, default, 1 of 11 selected_'.

### Actual Behavior

Screen reader does not announce the 'default' visible text defined with the 'Campbell' color scheme on the page. It announces as '_Campbell, 1 of 11 selected_'.

**Observation:**

Issue also reproes with the NVDA screen reader.

### PR DESCRIPTION
**Pull request by carlos-zamora**
## Summary of the Pull Request
This removes the "default" text box from the UI Automation tree, thus preventing screen readers from navigating to it. This was a confusing scenario for users because the "default" tag was unclear if it was a part of the previous or next color scheme (i.e. consider hearing "Campbell, default, Campbell PowerShell"; it's unclear which one is default).

This also appends the "default" string to the `ToString` function of the color scheme view model. This makes it so that the combo box and list view visually appear the same, but can be quick searched or read out by the screen reader with the 'default' tag.

## Validation Steps Performed
- [x] Verified this works on Windows 11
- [x] Verified this works on Windows 10
- Scenarios tested:
   - [x] saving settings after changing the default scheme
   - [x] saving settings.json to force a refresh in SUI

Closes #14401

### CODE REVIEW

**Comment by carlos-zamora** [comment]
### Why is this a draft?
We're having trouble remembering what exactly caused the crash last time. I'm looking into this. Once we're sure it won't crash, I'll bring it out of draft.

File: src/cascadia/TerminalSettingsEditor/ColorSchemes.cpp [hunk 1]
```diff
@@ -43,6 +43,16 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
             _layoutUpdatedRevoker.revoke();
 
             ColorSchemeListView().Focus(FocusState::Programmatic);
+
+            for (const auto scheme : _ViewModel.AllColorSchemes())
+            {
+                if (scheme.IsDefaultScheme())
+                {
+                    winrt::hstring newName{ fmt::format(L"{} ({})", scheme.Name(), RS_(L"ColorScheme_DefaultTag/Text")) };
```
Comment (lhecker) [inline src/cascadia/TerminalSettingsEditor/ColorSchemes.cpp:51]:
```suggestion
                    const auto newName = fmt::format(L"{} ({})", scheme.Name(), RS_(L"ColorScheme_DefaultTag/Text"));
```

You can also use `{}` instead of `=` if you prefer. This file seems to use a mix of both styles.

WinRT generated functions accept a `winrt::param::hstring` instead of a `winrt::hstring`, the former of which are "borrowed" strings. It allows you to pass a non-hstring string without making any additional copies and is very convenient to use, because any null-terminated string implicitly (!) converts to it. = No casting needed.

**Review by lhecker — APPROVED** [review]

**Review by DHowett — CHANGES_REQUESTED** [review]
I determined the reason we had to revert it!

image

FYI.

Overriding the accessibility text content of one item in a listview seems like the wrong way to fix this bug in general. Especially because we can't tell when that item is invisible.

FYI adding a check that the item _has a Container_ is only going to make it so that the accessibility bug disappears until the user opens the SUI with a window too small to have assigned a container to the item.

We need to fix it comprehensively :)

**Review by DHowett — APPROVED** [review]

**Comment by DHowett** [comment]
Make sure the description is up to date!

**Comment by carlos-zamora** [comment]
@msftbot merge this in 10 minutes
