### PR TITLE
Patch fix for #1360 until WriteStream (#780) can be implemented.

### LINKED ISSUE #1360: Windows terminal hangs after running ripgrep in a loop
# Environment
Windows version 1903 OS build 18899.1000
Windows Terminal (Preview) version 0.2.1703.0

Any other software?
ripgrep 11.0.0

# Steps to reproduce
Install [ripgrep](https://github.com/BurntSushi/ripgrep)
Open wt (Windows Terminal), running PowerShell.
Run the following from the root of a large drive
`while ($true) { rg -i "foo" }`

# Expected behavior
The terminal continually runs ripgrep against all files on the drive

# Actual behavior
The terminal eventually hangs and is completely unresponsive.

The call stack for the main thread when the window hangs is attached.

[HungTerminal1.callstack.txt](https://github.com/microsoft/terminal/files/3312675/HungTerminal1.callstack.txt)

A minidump of the hung process is available here:
[HungWindowsTerminal](https://1drv.ms/u/s!Alav93a0o3vchOg0nCVjwUPjFn0DYw?e=Ue4AP5)

### PR DESCRIPTION
**Pull request by miniksa**
## Summary of the Pull Request
Writing can enter an infinite loop with full-width characters being inserted into the last column of the buffer.

 
## References
#780

## PR Checklist
* [X] Closes #1360
* [X] I work here
* [ ] Draft because I'm going to try to turn the code @treit gave me for repro into a test
* [X] Documented by comments at the hack and noted for #780
* [X] I'm a core contributor

## Detailed Description of the Pull Request / Additional comments
This is because the "WriteCharsLegacy2ElectricBoogaloo" implementation in the Terminal (`Terminal::_WriteBuffer`) is a hacky thing that we put together knowing full well that we'd have to do #780 but we had to get this working enough for now. Turns out, it's not super complete and fragile. Surprise.

## Validation Steps Performed

- Manual run of @treit's sample against the Terminal.
- Attempting to author automated test with @treit's sample
- I need to run it against conhost and make sure it's not failing too (and fix it there too if it is)

### CODE REVIEW

**Comment by miniksa** [comment]
Same code snippet against conhost doesn't crash, so I don't believe there's anything to fix there right now. This makes sense since it should hit the OG `WriteCharsLegacy` which has provisions to auto-newline when we pass the right side and not bisect characters.

**Comment by DHowett-MSFT** [comment]
image

File: src/cascadia/TerminalCore/Terminal.cpp [hunk 1]
```diff
@@ -381,6 +381,18 @@ void Terminal::_WriteBuffer(const std::wstring_view& stringView)
             }
         }
 
+        // If we're about to try to place the cursor past the right edge of the buffer, move it down a row
+        // This is another patch that GH#780 should supercede. This is really correcting for other bad situations
```
Comment (HBelusca) [inline src/cascadia/TerminalCore/Terminal.cpp]: supersede*

Comment (DHowett-MSFT) [inline src/cascadia/TerminalCore/Terminal.cpp]:
```suggestion
        // This is another patch that GH#780 should supersede. This is really correcting for other bad situations
```
