### PR TITLE
Fix the feature tests with a retry

### LINKED ISSUE #8495: The feature tests fail in CI often
Hey maybe we should have an issue tracking this, because it's kinda getting worse.

Builds with this issue:
* [124997](https://dev.azure.com/ms/terminal/_build/results?buildId=124997&view=logs&j=fe5d217b-357f-5a83-11fa-ea15ba02c406&t=94a67b48-79ec-5be5-f887-ae3875b74c8b&l=20057) `FileTests::TestWriteFileWrapEOL#metadataSet0 [Failed]`
* [126069](https://dev.azure.com/ms/20953fb4-d427-4ad6-b78c-13142d0c5462/_build/results?buildId=126069): `    FileTests::TestWriteFileDisableNewlineAutoReturn#metadataSet1 [Failed]`
* [126880](https://dev.azure.com/ms/terminal/_build/results?buildId=126880&view=logs&j=fe5d217b-357f-5a83-11fa-ea15ba02c406&t=94a67b48-79ec-5be5-f887-ae3875b74c8b) `FileTests::TestWriteFileRaw [Failed]` and `FileTests::TestWriteFileProcessed [Failed]` 
  - `Error: Verify: Win32BoolSucceeded(GetConsoleScreenBufferInfoEx(`
  - `Error: Verify: Win32BoolSucceeded(GetConsoleScreenBufferInfoEx(`

Feels free to add more as they come. Maybe just disable all of them?

### PR DESCRIPTION
**Pull request by zadjii-msft**
A bunch of our feature tests don't work reliably in CI. They rely on creating a new `OpenConsole.exe` window, then running the test _in that console_. As a part of that test setup, the test runner used to wait a second to attach to the newly created console. Then the test goes on it's merry way, assuming the console is ready to go. However, in CI, that might take more than a second. If it does, then the test would fail pretty immediately, as soon as it tries to get at the buffer of the new console.

This PR introduces a little retry loop to the test init. After attaching to the new console, we'll try and get at the screen buffer. If that fails, we'll wait a second and try again. We'll try 5 times total, before bailing entirely. Hopefully, this should mitigate most of the random CI failures we get in the feature tests.

* [x] Closes #8495

### CODE REVIEW

**Comment by zadjii-msft** [comment]
Hey look, this works!

```
Attempt #1 to confirm we've attached
Verify: AreEqual(0, err)
Verify: AreEqual(0, err)
Verify: AreNotEqual(hConsole, INVALID_HANDLE_VALUE): Ensure we got a valid console handle
Verify: IsNotNull(hConsole): Ensure we got a non-null console handle
Verify: IsNotNull(hOut): Verify we have the standard output handle.
Verify: AreEqual(6u, gle): If we fail to set up the console, GetLastError should return 6 here.
Attempt #2 to confirm we've attached
Verify: AreEqual(0, err)
Verify: AreEqual(0, err)
Verify: AreNotEqual(hConsole, INVALID_HANDLE_VALUE): Ensure we got a valid console handle
Verify: IsNotNull(hConsole): Ensure we got a non-null console handle
Verify: IsNotNull(hOut): Verify we have the standard output handle.

```

It's silly, but it gets the job done, right?

**Review by miniksa — APPROVED** [review]
Yeah this is a good call. Thanks.

File: src/host/ft_host/InitTests.cpp [hunk 1]
```diff
@@ -236,19 +237,47 @@ MODULE_SETUP(ModuleSetup)
...
+        BOOL succeeded = GetConsoleScreenBufferInfoEx(hOut, &csbiexBefore);
+        if (!succeeded)
+        {
+            auto gle = GetLastError();
+            VERIFY_ARE_EQUAL(6u, gle, L"If we fail to set up the console, GetLastError should return 6 here.");
+            Sleep(1000);
+        }
+        else
+        {
+            setupConsole = true;
```
Comment (DHowett) [inline src/host/ft_host/InitTests.cpp:276]: you could also dispense with the boolean and just `break` here!

**Review by DHowett — APPROVED** [review]
