### PR TITLE
When Conpty encounters an unknown string, flush immediately

### LINKED ISSUE #2011: Bug Report: What is reordering VT escape sequences in my string?
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.239]
Windows Terminal version (if applicable): (built from latest source as of July 17th, 2019, morning)
```

I am working on implementing some new VT escape sequences (PR [here](https://github.com/microsoft/terminal/pull/1978)), but I've run into a strange problem. What the sequences do (or are supposed to do) is not important here. The problem is that in certain circumstances, something is *reordering* VT escape sequences in my content (which is very surprising to me).

The control sequences in question are XTPUSHSGR and XTPOPSGR: `[CSI]#p` and `[CSI]#q`, respectively. Note in the string below, how there is an XTPUSHSGR sequence, then a normal SGR sequence to set the color to red, then an XTPOPSGR sequence (and then a normal SGR sequence to reset the color).

When I open OpenConsole.sln in Visual Studio 2019, with the CascadiaPackage set as the default project to debug, and then <kbd>F5</kbd> to start debugging it, it launches a terminal running Windows PowerShell. When I send my string to the console, something is *moving* the XTPUSHSGR and XTPOPSGR sequences to the very beginning of the string!

# Steps to reproduce

1. Start OpenConsole.sln in Visual Studio 2019. Make sure CascadiaPackage is the default project, and platform is set to x64, and build the solution if necessary.
1. <kbd>F5</kbd> to start debugging a new instance. You should now have a PowerShell instance in the terminal.
1. In the PowerShell instance in the terminal, run the following commands:

```powershell
 $esc = [char] 0x1b
 $s = "Hello. Push:${esc}[#p ${esc}[91m this text is RED Pop:${esc}[#q FG should " +
      "no longer be red (unless it was red before) courtesy reset: ${esc}[0m"
```
4. Set a breakpoint at `TerminalControl.dll!Microsoft::Console::VirtualTerminal::StateMachine::ProcessString` (the two-parameter one).
1. In the PowerShell instance in the terminal, run the command `$s` to output the string.
1. When you hit the breakpoint, observe the value of `rgwch`.

# Expected behavior

The content of the string should be just as it was set in PowerShell.

# Actual behavior

The XTPUSHSGR and XTPOPSGR sequences have been moved to the beginning of the string!

My first thought was that PowerShell must be doing something funny, but I attached windbg to the PowerShell and set a breakpoint on kernel32!WriteConsoleW, and the string passed in there is correct. So something is happening after the string has left PowerShell's hands.

### LINKED ISSUE #4106: When changing cursor shape using DECSCUSR escape sequences, the cursor shape doesn't change until the cursor is moved
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): 0.7.3451.0

Any other software?
`pwsh + PSReadLine`
```

# Steps to reproduce

I tried to fix https://github.com/PowerShell/PSReadLine/issues/1233 in PSReadLine by always applying the standard escape sequences, so the cursor shape can be changed when switching between Insert and Command modes in the VI edit mode.

A quick fix looks like this: https://github.com/daxian-dbw/PSReadLine/commit/d29dad98426992c2d9f3b92cebedd7d85c4a0fac
It works fine in the terminals on Linux and macOS.
However, in Windows Terminal and VS Code terminal, the cursor shape doesn't changed immediately after writing out the escape sequences. The change happens only after the cursor is moved.

# Expected behavior

The behavior should be the same as on Linux.
1. type <kbd>Esc</kbd> to switch from insert mode to command mode. Cursor shape is changed to steady block.
2. type <kbd>i</kbd> to switch from command mode to insert mode. Cursor shape is changed to blinking bar.
3. type <kbd>a</kbd> to insert the character `a`.

linux

# Actual behavior

This is what happens in Windows Terminal.
1. type <kbd>Esc</kbd> to switch from insert mode to command mode. Cursor shape is changed to steady block.
2. type <kbd>i</kbd> to switch from command mode to insert mode. Cursor shape doesn't change.
3. type <kbd>a</kbd> to insert the character `a`. Cursor shape is changed to blinking bar. Moving the cursor with <kbd>LeftArrow</kbd> or <kbd>RightArrow</kbd> will also trigger the cursor shape change.

winterminal

### PR DESCRIPTION
**Pull request by zadjii-msft**
When ConPTY encounters a string we don't understand, immediately flush the frame.

## References

This PR supersedes #2665. This solution is much simpler than what was proposed in that PR. 
As mentioned in #2665: "This might have some long-term consequences for #1173."

## PR Checklist
* [x] Closes #2011
* [x] Closes #4106
* [x] I work here
* [x] Tests added/passed

### CODE REVIEW

File: src/terminal/adapter/adaptDispatch.cpp [hunk 1]
```diff
@@ -1894,6 +1887,15 @@ bool AdaptDispatch::SetCursorStyle(const DispatchTypes::CursorStyle cursorStyle)
         success = _pConApi->PrivateAllowCursorBlinking(fEnableBlinking);
     }
 
+    // If we're a conpty, always return false, so that this cursor state will be
```
Comment (DHowett-MSFT) [inline src/terminal/adapter/adaptDispatch.cpp]: Why after not before?

**Comment by DHowett-MSFT** [comment]
And finally: this will work okay, but not amazing, for things that manipulate how text is displayed — because it will happen in between the frames that render text?

File: src/terminal/adapter/adaptDispatch.cpp (hunk 1 above)
Comment (zadjii-msft) [reply src/terminal/adapter/adaptDispatch.cpp]: I moved this after to make the test work tbh. Doing this after means the conpty will still have this state in it the same as the Terminal, even if there's no way to query or use that information.

**Comment by zadjii-msft** [comment]
> And finally: this will work okay, but not amazing, for things that manipulate how text is displayed — because it will happen in between the frames that render text?

Pretty much exactly.

File: src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp [hunk 2]
```diff
@@ -673,6 +675,36 @@ void ConptyRoundtripTests::MoveCursorAtEOL()
...
+void ConptyRoundtripTests::PassthroughCursorShapeImmediately()
+{
+    // This is a test for GH#4106, and more indirectly, GH #2011.
+
+    Log::Comment(NoThrowString().Format(
+        L"Change the cursor shape with VT. This should immediately be flushed to the Terminal."));
+    VERIFY_IS_NOT_NULL(_pVtRenderEngine.get());
+
+    auto& g = ServiceLocator::LocateGlobals();
+    // auto& renderer = *g.pRender;
```
Comment (carlos-zamora) [inline src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp]: stray comment

Comment (DHowett-MSFT) [inline src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp]:
```suggestion
```

**Comment by DHowett-MSFT** [comment]
Admin merge: I removed a comment, but our CI is in deep
