### PR TITLE
Use nearby fonts for font fallback

### LINKED ISSUE #11032: Weird fonts on Windows Server 2022
### Windows Terminal version (or Windows build number)

1.10.1933.0

### Other Software

Fresh install of Windows Server 2022 Evaluation, straight from https://www.microsoft.com/en-us/evalcenter/. Did not yet check for updates.

### Steps to reproduce

Install latest preview appxbundle using Add-AppxPackage.
Running Windows Server on VMWare Workstation 16.1.2 build-17966106.

### Expected Behavior

Capture

This is how cascadia code normally looks.

### Actual Behavior

This is what I got. Doesn't quite seem right.

Capture-bad

### LINKED ISSUE #11648: Terminal suddenly can't find the font Cascadia Mono
### Windows Terminal version (or Windows build number)

10.0.19043.1288

### Other Software

_No response_

### Steps to reproduce

Just starting the Terminal on Windows 10. Not running as admin.

### Expected Behavior

A new terminal window

### Actual Behavior

Got this error

`Unable to find the selected font "Cascadia Mono".

"Consolas" has been selected instead.

Please either install the missing font or choose another one.`

### PR DESCRIPTION
**Pull request by lhecker**
This commit is a minimal fix in order to pass the
`IDWriteFontCollection` we create out of .ttf files residing next to our
binaries to the `IDWriteFontFallback::MapCharacters` call. The
`IDWriteTextFormat` is used in order to carry the font collection over
into `CustomTextLayout`.

## Validation
* Put `JetBrainsMono-Regular.ttf` into the binary output directory
* Modify `HKCU:\Console\*\FaceName`  to `JetBrains Mono`
* Launch OpenConsole.exe
* OpenConsole uses JetBrains Mono ✔️

Closes #11032
Closes #11648

### CODE REVIEW

**Comment by lhecker** [comment]
With this PR finally open I'll go back into ~suspension~ vacation.

I have a branch that fixes this issue much more thoroughly, by getting rid of the entire DxFontInfo class as well as most of the font features and axes code and some other bits altogether (removes about 10-15% of DxEngine).
But I felt like that's pure overkill so I'm saving that one for later. 😈

I realize I didn't test it with WT under Windows Server 2022, but I had to uninstall Hyper-V in order to test Windows 7 rendering stuff, so... Yeah let me know if you think my testing methodology is enough. Otherwise I'll reinstall Hyper-V soon and test it again.
IMO it's enough, since I didn't touch `DxFontInfo::s_GetNearbyFonts` at all. As such the only way my change can work, is by fixing it not just for OpenConsole locally but also in all other cases, such as in an app package on Windows Server 2022.

**Comment by ianjoneill** [comment]
This does address the underlying problem on Server 2022.

Windows2022

However, it doesn't make any changes to the settings UI. As I noted in #11032 the SUI uses the system font collection, so the font isn't displayed in the dropdown. This leads to a bit of a weird UI - the dropdown looks like it's empty. If you click on it, you can select a font, but not Cascadia. If you select e.g. Courier New, then decide you want to switch back, you need to use the reset button. Under the debugger clicking it causes an exception to be raised, but without the debugger attached, the button just disappears. Clicking save does revert the font successfully.

Demo:

https://user-images.githubusercontent.com/5821575/141846473-b2055b38-ee48-4f2a-b49f-0f57df3e115b.mp4

**Comment by lhecker** [comment]
@ianjoneill I pushed the code for the settings UI just now.

File: src/cascadia/TerminalSettingsEditor/Profiles.cpp [hunk 1]
```diff
@@ -3,13 +3,62 @@
 
 #include "pch.h"
 #include "Profiles.h"
+
```
Comment (miniksa) [inline src/cascadia/TerminalSettingsEditor/Profiles.cpp:6]: ?

File: src/cascadia/TerminalSettingsEditor/Profiles.cpp [hunk 2]
```diff
@@ -3,13 +3,62 @@
...
 
+// This function is a copy of DxFontInfo::_NearbyCollection() with
+// * the call to DxFontInfo::s_GetNearbyFonts() inlined
+// * checkForUpdates for GetSystemFontCollection() set to true
+static wil::com_ptr<IDWriteFontCollection1> NearbyCollection(IDWriteFactory* dwriteFactory)
+{
+    // The convenience interfaces for loading fonts from files
+    // are only available on Windows 10+.
+    wil::com_ptr<IDWriteFactory6> factory6;
+    // wil's query() facilities don't work inside WinRT land at the moment.
```
Comment (miniksa) [inline src/cascadia/TerminalSettingsEditor/Profiles.cpp:22]: Is this filed against microsoft/wil and/or are we just behind on updating our copy of wil?

File: src/cascadia/TerminalSettingsEditor/Profiles.cpp [hunk 3]
```diff
@@ -107,8 +156,7 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
             reinterpret_cast<::IUnknown**>(factory.put())));
 
         // get the font collection; subscribe to updates
-        com_ptr<IDWriteFontCollection> fontCollection;
-        THROW_IF_FAILED(factory->GetSystemFontCollection(fontCollection.put(), TRUE));
+        const auto fontCollection = NearbyCollection(factory.get());
```
Comment (miniksa) [inline src/cascadia/TerminalSettingsEditor/Profiles.cpp:159]: So this will recreate it every time the page reloads the view model? Not a perf issue?

**Review by miniksa — APPROVED** [review]

File: src/cascadia/TerminalSettingsEditor/Profiles.cpp (hunk 1 above)
Comment (lhecker) [reply src/cascadia/TerminalSettingsEditor/Profiles.cpp:6]: Ah this is just me following the most common C++ style guide for imports... It breaks them up into the following order:
* "pch.h"
* "class.h"
* _blank line_
* \<system headers\>
* _blank line_
* \<stdlib headers\>
* _blank line_
* \<other global headers\>
* _blank line_
* "local headers.h"

(Google has a good explanation [here](https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes).)

This ordering helps with clarity as you know immediately where some file resides at. This is especially helpful with MSVC, which for whatever reason has decided to not actually implement C++ and treats `#include "foo"` and `#include <foo>` synonymous. 😐 With the above order such imports cannot be confused anymore under msvc, which is nice.
You'll find that most projects follow this style and in fact even in this project most code follows this style already.

But in short: Considering that our project already does this for most files, I feel like it's alright to modify files that don't do this yet.

File: src/cascadia/TerminalSettingsEditor/Profiles.cpp (hunk 2 above)
Comment (lhecker) [reply src/cascadia/TerminalSettingsEditor/Profiles.cpp:22]: I got a TODO item to open a PR for that when I'm back at work. Since it's an easy fix that seemed better to me than opening an issue. 🙂

File: src/cascadia/TerminalSettingsEditor/Profiles.cpp (hunk 3 above)
Comment (lhecker) [reply src/cascadia/TerminalSettingsEditor/Profiles.cpp:159]: From what I could tell this only loads once when the settings page is opened. Navigating back and forth between views didn't call this function again.

File: src/cascadia/TerminalSettingsEditor/Profiles.cpp (hunk 2 above)
Comment (zadjii-msft) [reply src/cascadia/TerminalSettingsEditor/Profiles.cpp:22]: IIRC that's an ordering issue - something about including wil _before_ winrt, or vice-versa, or something like that. My memory's hazy on this...

File: src/renderer/dx/DxFontInfo.cpp [hunk 4]
```diff
@@ -332,42 +335,48 @@ void DxFontInfo::SetFromEngine(const std::wstring_view familyName,
...
-    static const auto knownPaths = s_GetNearbyFonts();
+    if (_nearbyCollection)
+    {
+        return _nearbyCollection.Get();
+    }
 
     // The convenience interfaces for loading fonts from files
     // are only available on Windows 10+.
-    // Don't try to look up if below that OS version.
-    static const bool s_isWindows10OrGreater = IsWindows10OrGreater();
```
Comment (zadjii-msft) [inline src/renderer/dx/DxFontInfo.cpp:344]: What happened to this check? Are these available on Win7 now? (If so, we should get rid of the comment, or update to say that it doesn't matter)

**Review by zadjii-msft — COMMENTED** [review]
I'm only worried about the Win10 comment there. Otherwise this is a ✅ from me

File: src/renderer/dx/DxFontInfo.cpp (hunk 4 above)
Comment (DHowett) [reply src/renderer/dx/DxFontInfo.cpp:344]: If I had to guess, it's because we switched to using `QueryInterface` to determine whether the factory supported the requisite interface.

Comment (DHowett) [reply src/renderer/dx/DxFontInfo.cpp:344]: It is always better to do live detection of features (think backports!) instead of version number checks.

Comment (lhecker) [reply src/renderer/dx/DxFontInfo.cpp:344]: Yeah, version checks (including the entirety of `IsWindowsXOrGreater()` functions) are basically deprecated. We're supposed to do feature checks nowadays instead.

This is especially so since the current code has a bug. Can you spot it? 😄
It's this line:
```cpp
        // Builder2 has a convenience to just feed in paths to font files.
        ::Microsoft::WRL::ComPtr<IDWriteFontSetBuilder2> fontSetBuilder2;
        THROW_IF_FAILED(fontSetBuilder.As(&fontSetBuilder2));
```

This will throw if you don't have Windows 10 Build 20348 or newer installed, which lead to #10211 and got solved "by accident" in a way, since the problem wasn't just corrupted fonts per se.

**Review by zadjii-msft — APPROVED** [review]

File: src/renderer/dx/DxFontInfo.cpp (hunk 4 above)
Comment (lhecker) [reply src/renderer/dx/DxFontInfo.cpp:344]: Oh btw: Let's not store results from `VersionHelpers.h` into statics. The data it uses comes from the PEB (process environment block) and while the version check isn't trival (since you can set a ton of fields and flags when calling `VerifyVersionInfoW`), it's not a syscall and can read the version straight from process-local memory (the PEB is local to each process).

**Review by DHowett — APPROVED** [review]
Do you know who "wins" in this font collection? Ideally, if a user installs a newer version of Cascadia on their system the nearby version would be ignored.

**Comment by lhecker** [comment]
I suspect that the font set builder is an ordered list. @miniksa mentioned that it always prefers the system font collection if the code is written this way.

**Comment by miniksa** [comment]
> I suspect that the font set builder is an ordered list. @miniksa mentioned that it always prefers the system font collection if the code is written this way.

I believe that's what @fdwr told me.
