### PR TITLE
Fix failing TestHostApp unit tests

### LINKED ISSUE #11339: Multiple failing unit tests
### Windows Terminal version (or Windows build number)

10.0.18363.1500, Commit 2be394f421b9b23a15e5573fb02b9c7a25768941

### Other Software

_No response_

### Steps to reproduce

1. Checkout a recent version of the Terminal.
2. Build the code.
3. Execute `runut` in the tools directory.

### Expected Behavior

The unit tests should all pass.

### Actual Behavior

I'm getting quite a lot of failures.

    TerminalAppLocalTests::CommandlineTest::ParseFocusTabArgs#metadataSet0 [Failed]
    TerminalAppLocalTests::CommandlineTest::ParseFocusTabArgs#metadataSet1 [Failed]
    TerminalAppLocalTests::SettingsTests::TestIterateCommands [Failed]
    TerminalAppLocalTests::SettingsTests::TestIterateOnGeneratedNamedCommands [Failed]
    TerminalAppLocalTests::SettingsTests::TestIterateOnBadJson [Failed]
    TerminalAppLocalTests::SettingsTests::TestNestedCommands [Failed]
    TerminalAppLocalTests::SettingsTests::TestNestedInNestedCommand [Failed]
    TerminalAppLocalTests::SettingsTests::TestNestedInIterableCommand [Failed]
    TerminalAppLocalTests::SettingsTests::TestIterableInNestedCommand [Failed]
    TerminalAppLocalTests::SettingsTests::TestMixedNestedAndIterableCommand [Failed]
    TerminalAppLocalTests::SettingsTests::TestIterableColorSchemeCommands [Failed]
    TerminalAppLocalTests::TabTests::MoveFocusFromZoomedPane [Failed]
    SettingsModelLocalTests::ProfileTests::TestGenGuidsForProfiles [Failed]
    SettingsModelLocalTests::DeserializationTests::TestLayerUserDefaultsOnDynamics [Failed]
    SettingsModelLocalTests::SerializationTests::Profile [Failed]

I haven't actually looked to see what's going wrong, so it's possible it's just me.

### PR DESCRIPTION
**Pull request by lhecker**
This commit fixes various failing TestHostApp unit tests.
Most of these broke as part of 168d28b (#11184).

## PR Checklist
* [x] Closes #11339
* [x] I work here
* [x] Tests added/passed

### CODE REVIEW

File: src/cascadia/LocalTests_TerminalApp/CommandlineTest.cpp [hunk 1]
```diff
@@ -1047,7 +1049,9 @@ namespace TerminalAppLocalTests
 
             auto actionAndArgs = appArgs._startupActions.at(1);
             VERIFY_ARE_EQUAL(ShortcutAction::PrevTab, actionAndArgs.Action());
-            VERIFY_IS_NULL(actionAndArgs.Args());
+            VERIFY_IS_NOT_NULL(actionAndArgs.Args());
+            const auto myArgs = actionAndArgs.Args().as<PrevTabArgs>();
+            VERIFY_ARE_EQUAL(TabSwitcherMode::Disabled, myArgs.SwitcherMode().Value());
```
Comment (lhecker) [inline src/cascadia/LocalTests_TerminalApp/CommandlineTest.cpp:1054]: Well at least 2 out of 14 failing tests weren't broken by me. That's something. 😄

File: src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp [hunk 2]
```diff
@@ -16,6 +16,31 @@ using namespace winrt::Microsoft::Terminal::Control;
...
+            "brightBlack": "#767676",
+            "brightRed": "#E74856",
+            "brightGreen": "#16C60C",
+            "brightYellow": "#F9F1A5",
+            "brightBlue": "#3B78FF",
+            "brightPurple": "#B4009E",
+            "brightCyan": "#61D6D6",
+            "brightWhite": "#F2F2F2"
+        }]
+    })" };
```
Comment (lhecker) [inline src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp:42]: Nowadays `CascadiaSettings` enforces strict ColorScheme tests as part of its constructor.

**Review by zadjii-msft — APPROVED** [review]

**Review by carlos-zamora — APPROVED** [review]

**Review by DHowett — APPROVED** [review]
