### PR TITLE
During Alt+Numpad composition, stash keys in case we bail out

### LINKED ISSUE #17762: CANARY: ALT+NUMPAD ADD is Broken
### Windows Terminal version

1.22.2334.0

### Windows build number

10.0.19045.4780

### Other Software

_No response_

### Steps to reproduce

Alt+NumpadAdd pressing combination is broken since Canary build terminal-1.22.2201.0
terminal-1.22.2191.0 - latest good
terminal-1.22.2201.0 - broken
...
terminal-1.22.2334.0 - broken

run utilities for getting codes DOWN/UP VK_CODES etc
press Alt key after press NumpadAdd and release NumpadAdd, press NumpadAdd and release NumpadAdd, press NumpadAdd and release NumpadAdd

### Expected Behavior

terminal-1.22.2191.0 - latest good:
21:42:56 KEY_EVENT_RECORD: Dn, 1, Vk="VK_ADD" [107/0x006B], Scan=0x004E uChar=[U='+' (0x002B): A='+' (0x2B)]
         Ctrl=0x00000002 (cAsac - ecns) (Windowed)
21:42:56 KEY_EVENT_RECORD: Dn, 1, Vk="VK_ADD" [107/0x006B], Scan=0x004E uChar=[U='+' (0x002B): A='+' (0x2B)]
         Ctrl=0x00000002 (cAsac - ecns) (Windowed)
21:42:57 KEY_EVENT_RECORD: Up, 1, Vk="VK_ADD" [107/0x006B], Scan=0x004E uChar=[U='+' (0x002B): A='+' (0x2B)]
         Ctrl=0x00000002 (cAsac - ecns) (Windowed)

### Actual Behavior

since terminal-1.22.2201.0  to latest canary build terminal-1.22.2334.0  is broken:

21:44:18 KEY_EVENT_RECORD: Up, 1, Vk="VK_ADD" [107/0x006B], Scan=0x004E uChar=[U='+' (0x002B): A='+' (0x2B)]
         Ctrl=0x00000002 (cAsac - ecns) (Windowed)
21:44:18 KEY_EVENT_RECORD: Up, 1, Vk="VK_ADD" [107/0x006B], Scan=0x004E uChar=[U='+' (0x002B): A='+' (0x2B)]
         Ctrl=0x00000002 (cAsac - ecns) (Windowed)
21:44:18 KEY_EVENT_RECORD: Up, 1, Vk="VK_ADD" [107/0x006B], Scan=0x004E uChar=[U='+' (0x002B): A='+' (0x2B)]
         Ctrl=0x00000002 (cAsac - ecns) (Windowed)

### PR DESCRIPTION
**Pull request by DHowett**
We were erroneously eating Alt followed by VK_ADD. This change makes sure we cache key presses and releases that happen once a numpad composition is active so that we can send them when you release Alt.

Right now, we only send them when you release Alt after composing Alt and VK_ADD (entering hex mode) and only if you haven't inserted an actual hex numpad code. This does mean that `Alt VK_ADD 0 0 H I` will result in an input of "+hi". That... seems like a small price to pay for Alt VK_ADD working again.

Closes #17762

### CODE REVIEW

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 1]
```diff
@@ -1601,53 +1614,64 @@ namespace winrt::Microsoft::Terminal::Control::implementation
...
 
                 if (vkey == VK_ADD)
                 {
-                    // Alt '+' <number> is used to input Unicode code points.
-                    // Every time you press + it resets the entire state
-                    // in the original OS implementation as well.
-                    s.encoding = AltNumpadEncoding::Unicode;
-                    s.accumulator = 0;
-                    s.active = true;
+                    if (keyDown)
```
Comment (DHowett) [inline src/cascadia/TerminalControl/TermControl.cpp:1623]: I had to move keyDown into these places so we could stash the keyUp event in case composition was active.

This makes `ALTdown KP+down KP+up ALTup` work.

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 2]
```diff
@@ -1543,7 +1543,20 @@ namespace winrt::Microsoft::Terminal::Control::implementation
...
+                    // If the user pressed Alt + VK_ADD, then released Alt, they probably didn't intend to insert a numpad character at all.
+                    // Send any accumulated key events instead.
+                    bool h = true;
+                    for (auto&& e : _altNumpadState.cachedKeyEvents)
+                    {
+                        h = h && _TrySendKeyEvent(std::get<0>(e), std::get<1>(e), std::get<2>(e), std::get<3>(e));
+                    }
+                    // Send the alt keyup we are currently processing
+                    h = h && _TrySendKeyEvent(vkey, scanCode, modifiers, keyDown);
+                    // do not accumulate into the buffer
```
Comment (DHowett) [inline src/cascadia/TerminalControl/TermControl.cpp:1557]: oh we should probably return h somewhere...

**Review by zadjii-msft — COMMENTED** [review]
I don't have time to read this, but I think this is fine with one sign-off

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 3]
```diff
@@ -1543,7 +1543,20 @@ namespace winrt::Microsoft::Terminal::Control::implementation
             if (encoding == AltNumpadEncoding::Unicode)
             {
                 // UTF-32 -> UTF-16
-                if (s.accumulator <= 0xffff)
+                if (s.accumulator == 0)
+                {
+                    // If the user pressed Alt + VK_ADD, then released Alt, they probably didn't intend to insert a numpad character at all.
+                    // Send any accumulated key events instead.
```
Comment (lhecker) [inline src/cascadia/TerminalControl/TermControl.cpp:1549]: We could potentially also get by, by passing through Alt/+ presses immediately without constraints and only switch to `s.active == true` once we encounter the first number/character. This requires us to add a 2nd `.active` member, because one of them will be required to track the state of the `_altNumpadState` (`.active` is already used in the if condition above and below).

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 1 above)
Comment (lhecker) [reply src/cascadia/TerminalControl/TermControl.cpp:1623]: This may be easier to read if the `if (keyDown)` was outside the if/else chain instead of inside it.

**Review by lhecker — APPROVED** [review]

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 3 above)
Comment (lhecker) [reply src/cascadia/TerminalControl/TermControl.cpp:1549]: As it turns out, numpad+ is the same as +. 🤦

**Review by lhecker — APPROVED** [review]
