### PR TITLE
Propagate window style changes to the titlebar and minmax

### LINKED ISSUE #1780: Double clicking on the drag bar to maximize does not update the maximize button icon
Double clicking on the drag bar to maximize does not update the maximize button icon, the icon remains the same, by contrast, if you click the maximize button the icon does update.

# Environment

```none
Windows 10 19H1
Windows Terminal version (if applicable): master

Any other software?
```

# Steps to reproduce
1. Start Windows Terminal in normal state
2. Double click the drag bar to maximize the window.

# Expected behavior
The maximize button icon is updated

# Actual behavior
The maximize button icon does not update.

We are not listening from window state change events from the top level window into the mixmaxclose user control.

### PR DESCRIPTION
**Pull request by DHowett-MSFT**
## PR Checklist
* [x] Fixes #1780
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [x] I've discussed this with core contributors already.

## Detailed Description of the Pull Request / Additional comments

This also sets us up for a bit more robustness down the line.

## Validation Steps Performed
Really went ham on ways to minmax the window.

### CODE REVIEW

File: src/cascadia/TerminalApp/MinMaxCloseControl.cpp [hunk 1]
```diff
@@ -48,6 +38,21 @@ namespace winrt::TerminalApp::implementation
         _closeClickHandlers(*this, e);
     }
 
+    void MinMaxCloseControl::SetWindowVisualState(WindowVisualState visualState)
+    {
+        switch (visualState)
+        {
+        case WindowVisualState::WindowVisualStateMaximized:
+            winrt::Windows::UI::Xaml::VisualStateManager::GoToState(MaximizeButton(), L"WindowStateMaximized", false);
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalApp/MinMaxCloseControl.cpp]: i do not yet intend to unify these string names. sorry.

File: src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp [hunk 2]
```diff
@@ -679,6 +679,17 @@ bool NonClientIslandWindow::_HandleWindowPosChanging(WINDOWPOS* const windowPos)
         return false;
     }
 
+    const auto windowStyle = GetWindowStyle(_window.get());
+    const auto isMaximized = WI_IsFlagSet(windowStyle, WS_MAXIMIZE);
+    const auto isIconified = WI_IsFlagSet(windowStyle, WS_ICONIC);
+
+    if (_titlebar)
+    {
+        _titlebar.SetWindowVisualState(isMaximized ? winrt::TerminalApp::WindowVisualState::WindowVisualStateMaximized :
```
Comment (zadjii-msft) [inline src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp]: my only complaint is that these lines are _too damn long_. But that's a stylistic choice for someone with split panes in their editor :)
