### PR TITLE
Fix setting `wght` axis font bugs

### LINKED ISSUE #10852: Setting `wght` axis results in weight flickering when text is/is not "Simple"
### Windows Terminal version (or Windows build number)

1.11

### Other Software

_No response_

### Steps to reproduce

```json
"font": 
{
    "face": "Cascadia Code PL",
    "axes": {
        "wght": 300,
    },
    "size": 14,
}
```

### Expected Behavior

_No response_

### Actual Behavior

image

### LINKED ISSUE #10853: Setting `wght` axis breaks bold fonts
### Windows Terminal version (or Windows build number)

1.11

### Other Software

_No response_

### Steps to reproduce

```json
"font": 
{
    "face": "Cascadia Code PL",
    "axes": {
        "wght": 300,
    },
    "size": 14,
}
```

### Expected Behavior

Bold text from SGR 1 should be bold (weight 700).

This sample was made by setting `weight` instead of `axes.wght`:

image

### Actual Behavior

It is not bold.

image

This is impacted by #10852. If the run is considered "simple" (I added `j` to make it complex), bold works fine (but note that the base weight of 300 is lost due to #10852.)

image

### PR DESCRIPTION
**Pull request by PankajBhojwani**
- When deciding whether to call `_AnalyzeFontFallback`, also check if the user set any font axes
- Do not use the user set weight if we are setting the weight due to the bold attribute
- When calling `FontFaceWithAttribute`, check if the user set the italic axis as well as the text attribute

* [x] Closes #10852
* [x] Closes #10853

### CODE REVIEW

File: src/renderer/dx/DxFontRenderData.cpp [hunk 1]
```diff
@@ -612,7 +623,7 @@ std::vector<DWRITE_FONT_AXIS_VALUE> DxFontRenderData::GetAxisVector(const DWRITE
         }
     }
 
-    if (WI_IsFlagClear(axisTagPresence, AxisTagPresence::Weight))
+    if (WI_IsFlagClear(axisTagPresence, AxisTagPresence::Weight) || fontWeight != DWRITE_FONT_WEIGHT::DWRITE_FONT_WEIGHT_NORMAL)
```
Comment (PankajBhojwani) [inline src/renderer/dx/DxFontRenderData.cpp:626]: This is almost certainly wrong, anyone have a better idea for how we can distinguish between 'the user set bold/something else' and 'this is the weight value to use when the font is normal'?

**Comment by DHowett** [comment]
Does this mean that we are technically constructing a font fallback *every time there's a `j` or `i` in the input?* That seems crazy. Can you verify if that's the case?

**Comment by PankajBhojwani** [comment]
> Does this mean that we are technically constructing a font fallback every time there's a j or i in the input?

[Yes we do](https://github.com/microsoft/terminal/blob/2eb659717c0941626610faa4f3326f7f6a309a94/src/renderer/dx/CustomTextLayout.cpp#L239)

**Comment by DHowett** [comment]
gdi. Sounds like Chester's #10858

**Comment by skyline75489** [comment]
#10858 is very much inspired by the recent font features change. With the recent changes, the flag `isEntireTextSimple` is becoming less and less effective. If `isEntireTextSimple` is causing too much trouble, I'm quite OK with just removing it and investigate other ways like #9156 and #10858 .

Additionally, with the future atlas based renderer work, I assume the shaping & layout overhead will also be reduced. This one needs confirmation from @lhecker .

File: src/renderer/dx/CustomTextLayout.cpp [hunk 2]
```diff
@@ -145,6 +145,13 @@ try
     {
         // TODO: "relative" bold?
         weight = DWRITE_FONT_WEIGHT_BOLD;
+        // Since we are setting the font weight according to the text attribute,
+        // make sure to tell the text format to ignore the user set font weight
+        _fontRenderData->UseUserWeight(false);
```
Comment (lhecker) [inline src/renderer/dx/CustomTextLayout.cpp:150]: So this is basically `_fontRenderData->UseUserWeight(!drawingContext->useBoldFont);`?

Would it be less confusing if we flipped the meaning of either of the two booleans?

**Review by lhecker — COMMENTED** [review]
Doesn't this same problem occur with `DWRITE_FONT_AXIS_TAG_ITALIC`?

**Comment by lhecker** [comment]
Why does the bold text attribute override the user specified font axes, but if the axes contain italic then they override the text attribute? Shouldn't either both lead to font axes to be overriden or both forcing text attributes to be overriden?

**Comment by PankajBhojwani** [comment]
> Shouldn't either both lead to font axes to be overridden or both forcing text attributes to be overridden?

So it turns out that the italic axis and the italic text attribute actually _mean different things_.

Setting the italic text attribute tells dwrite to find the font with italic in its header, whereas setting the italic axis tells dwrite to find the font which has an italic axis of variation and then set that axis' value. Setting the axis can be thought of as setting a restriction on the fonts dwrite will consider. As an example of how this works with Cascadia Code:

Set "ital": 1 - Dwrite gets Cascadia Curve
Text attribute is italic - Dwrite gets Cascadia Curve
Set "ital": 0, text attribute is italic - Dwrite gets Cascadia Code and slants it 

This is the intended way it should work. So in short, the italic axis/attribute should not override each other even though bold does.

File: src/renderer/dx/CustomTextLayout.cpp (hunk 2 above)
Comment (PankajBhojwani) [reply src/renderer/dx/CustomTextLayout.cpp:150]: > So this is basically `_fontRenderData->UseUserWeight(!drawingContext->useBoldFont);`?

Yes, but I did not want to access `drawingContext->useBoldFont` again since we did that in the `if` statement to get in this block in the first place

File: src/renderer/dx/CustomTextLayout.cpp [hunk 3]
```diff
@@ -145,9 +145,16 @@ try
...
+        // make sure to tell the text format to ignore the user set font weight
+        _fontRenderData->UseUserWeight(false);
+    }
+    else
+    {
+        _fontRenderData->UseUserWeight(true);
     }
 
-    if (drawingContext->useItalicFont)
+    if (drawingContext->useItalicFont || _fontRenderData->DidUserSetItalic())
```
Comment (DHowett) [inline src/renderer/dx/CustomTextLayout.cpp:157]: sorry, what's this check do? does this promote the `ital` axis back into `STYLE_ITALIC`?

File: src/renderer/dx/DxFontRenderData.cpp [hunk 4]
```diff
@@ -509,14 +547,18 @@ void DxFontRenderData::_SetAxes(const std::unordered_map<std::wstring_view, floa
...
         {
-            const auto dwriteTag = DWRITE_MAKE_FONT_AXIS_TAG(til::at(axis, 0), til::at(axis, 1), til::at(axis, 2), til::at(axis, 3));
-            _axesVector.emplace_back(DWRITE_FONT_AXIS_VALUE{ dwriteTag, value });
+            if (axis.length() == TAG_LENGTH)
+            {
+                const auto dwriteTag = DWRITE_MAKE_FONT_AXIS_TAG(til::at(axis, 0), til::at(axis, 1), til::at(axis, 2), til::at(axis, 3));
+                _axesVector.emplace_back(DWRITE_FONT_AXIS_VALUE{ dwriteTag, value });
+            }
         }
+        _didUserSetAxes = true;
```
Comment (DHowett) [inline src/renderer/dx/DxFontRenderData.cpp:561]: We never set this to false.. even if a hot reload deletes the axes.

File: src/renderer/dx/DxFontRenderData.cpp [hunk 5]
```diff
@@ -845,8 +887,29 @@ Microsoft::WRL::ComPtr<IDWriteTextFormat> DxFontRenderData::_BuildTextFormat(con
...
+                }
+            }
+        }
         DWRITE_FONT_AXIS_VALUE const* axesList = _axesVector.data();
         format3->SetFontAxisValues(axesList, gsl::narrow<uint32_t>(_axesVector.size()));
+        // If we removed the user weight, make sure to put it back
+        if (oldWeight)
+        {
+            _axesVector.emplace_back(DWRITE_FONT_AXIS_VALUE{ DWRITE_FONT_AXIS_TAG_WEIGHT, oldWeight.value() });
+        }
```
Comment (DHowett) [inline src/renderer/dx/DxFontRenderData.cpp:912]: I'm generally quite against any code that takes the format, "Delete something from global state, then re-add it after the patrols have passed by". There is a better way to do this, and I suspect that we should do that instead.

**Review by DHowett — CHANGES_REQUESTED** [review]

**Comment by DHowett** [comment]
Since you changed how italic is handled, please make sure you mention that in the PR body. That body becomes the body of the commit, and it's important that we be able to look at history and learn both the what and the why.

Right now the title/body only mention `wght`.

File: src/renderer/dx/CustomTextLayout.cpp (hunk 3 above)
Comment (PankajBhojwani) [reply src/renderer/dx/CustomTextLayout.cpp:157]: This is so `FontFaceWithAttribute` gets called with `DWRITE_FONT_STYLE_ITALIC` if the `"ital"` axis is set, otherwise this happens:

ital

File: src/renderer/dx/DxFontRenderData.cpp (hunk 5 above)
Comment (PankajBhojwani) [reply src/renderer/dx/DxFontRenderData.cpp]: Changed!

File: src/renderer/dx/CustomTextLayout.cpp (hunk 2 above)
Comment (lhecker) [reply src/renderer/dx/CustomTextLayout.cpp:150]: Yeah that makes sense.

But regarding my other point: Would it help the code clarity if we kept both booleans in sync?
If we had something like `InhibitUserWeight()` we'd knew that it's always true if `drawingContext->useBoldFont` is true. I don't know about others, but I'd personally would find it easier to understand the state-logic of the renderer that way.

File: src/renderer/dx/DxFontRenderData.cpp [hunk 6]
```diff
@@ -457,6 +457,44 @@ bool DxFontRenderData::DidUserSetFeatures() const noexcept
...
+{
+    for (const auto& axisVal : _axesVector)
+    {
+        if (axisVal.axisTag == DWRITE_FONT_AXIS_TAG_ITALIC && axisVal.value == 1)
+        {
+            return true;
+        }
+    }
+    return false;
+}
```
Comment (lhecker) [inline src/renderer/dx/DxFontRenderData.cpp:496]: Consider eagerly computing and then caching this when the `_axesVector` is changed.

File: src/renderer/dx/DxFontRenderData.cpp [hunk 7]
```diff
@@ -845,8 +888,25 @@ Microsoft::WRL::ComPtr<IDWriteTextFormat> DxFontRenderData::_BuildTextFormat(con
...
+            //  don't delete it from our internal axes vector)
+            std::vector<DWRITE_FONT_AXIS_VALUE> axesWithoutWeight;
+            for (const auto axis : _axesVector)
+            {
+                if (axis.axisTag != DWRITE_FONT_AXIS_TAG_WEIGHT)
+                {
+                    axesWithoutWeight.emplace_back(axis);
+                }
+            }
+            format3->SetFontAxisValues(axesWithoutWeight.data(), gsl::narrow<uint32_t>(axesWithoutWeight.size()));
```
Comment (lhecker) [inline src/renderer/dx/DxFontRenderData.cpp:904]: We know the approximate size of `axesWithoutWeight`, so it'd be easy to add a quick `axesWithoutWeight.reserve(_axesVector.size())` call in there.

But you could prevent this temporary allocation entirely by modifying `DxFontRenderData::_SetAxes` similar to this (pseudo-code - I added a early return so it's flatter):
```cpp
struct DxFontRenderData {
	// ...
    std::vector<DWRITE_FONT_AXIS_VALUE> _axesVectorWithBold;
    gsl::span<DWRITE_FONT_AXIS_VALUE> _axesVector;
}

// ...

void DxFontRenderData::_SetAxes(const std::unordered_map<std::wstring_view, float>& axes)
{
    _axesVectorWithBold.clear();
    _didUserSetAxes = false;

    // Update our axis map with the provided axes
    if (!axes.empty())
    {
        bool hasBold = false;

#pragma warning(suppress : 26445) // the analyzer doesn't like reference to string_view
        for (const auto& [axis, value] : axes)
        {
            if (axis.length() == TAG_LENGTH)
            {
                const auto dwriteTag = DWRITE_MAKE_FONT_AXIS_TAG(til::at(axis, 0), til::at(axis, 1), til::at(axis, 2), til::at(axis, 3));
                hasBold |= dwriteTag == DWRITE_FONT_AXIS_TAG_WEIGHT;
                _axesVectorWithBold.emplace_back(DWRITE_FONT_AXIS_VALUE{ dwriteTag, value });
            }
        }

        _didUserSetAxes = true;
        _axesVector = gsl::make_span(_axesVectorWithBold);

        if (!hasBold) {
            _axesVectorWithBold.emplace_back(DWRITE_FONT_AXIS_TAG_WEIGHT);
        }
    }
}
```

Afterwards you can remove the loop from `_BuildTextFormat` and just use the two members as you need.

Axes are only modified extremely seldom, whereas something like `DxFontRenderData::_BuildTextFormat` is run thousands of times per second, which makes aggressive caching a good idea under all circumstances as far as I can see.

Comment (PankajBhojwani) [reply src/renderer/dx/DxFontRenderData.cpp]: Oh that's a fantastic idea, thanks! Latest commit does it very slightly differently but the idea is the same

File: src/renderer/dx/DxFontRenderData.cpp (hunk 6 above)
Comment (PankajBhojwani) [reply src/renderer/dx/DxFontRenderData.cpp]: That's probably better yeah, thanks!

File: src/renderer/dx/CustomTextLayout.cpp (hunk 2 above)
Comment (PankajBhojwani) [reply src/renderer/dx/CustomTextLayout.cpp]: I don't feel strongly either way but its a small enough fix, made the change!

**Comment by DHowett** [comment]
@PankajBhojwani so, the value in Leonard's implementation is that you *only* have one vector. The other one is a span pointing to the subset of the vector that doesn't contain bold. Right now you just seem to have two vectors...

File: src/renderer/dx/DxFontRenderData.cpp [hunk 8]
```diff
@@ -507,16 +538,30 @@ void DxFontRenderData::_SetFeatures(const std::unordered_map<std::wstring_view,
...
+                const auto dwriteFontAxis = DWRITE_FONT_AXIS_VALUE{ DWRITE_MAKE_FONT_AXIS_TAG(til::at(axis, 0), til::at(axis, 1), til::at(axis, 2), til::at(axis, 3)), value };
+                _axesVector.emplace_back(dwriteFontAxis);
+                if (dwriteFontAxis.axisTag != DWRITE_FONT_AXIS_TAG_WEIGHT)
+                {
+                    _axesVectorWithoutWeight.emplace_back(dwriteFontAxis);
+                }
+                if (dwriteFontAxis.axisTag == DWRITE_FONT_AXIS_TAG_ITALIC && value == 1)
+                {
+                    _didUserSetItalic = true;
+                }
```
Comment (lhecker) [inline src/renderer/dx/DxFontRenderData.cpp:561]: Personally I'd shorten these things to
```cpp
_didUserSetItalic |= dwriteFontAxis.axisTag == DWRITE_FONT_AXIS_TAG_ITALIC && value == 1;
```

The benefits as I personally, subjectivelly perceive them:
* Easier to read.
* It compiles to what GCC/Clang would produce. MSVC always needs a bit of handholding when it comes to booleans.
* And a longer one...

CPUs appear to be really fast nowadays, but they're actually often just as dumb as they used to be. One of the problems is that the "predictor" for branches has a limited size. While an important branch like this has literally 0 performance impact on this code and is absolutely fine, it might displace actually important branches out of the limited branch predictor cache.

For instance I have a PR open which simply removes `std::deque` and improves performance by ~5% on my CPU. This is really weird actually, because if you benchmark `std::deque` in a small benchmark project you'll find that it's super fast. And it's only iterated about ~100/sec! Still... it's mere presence has a negative impact, despite being fast itself. CPUs are dumb.

That said I wouldn't mind merging it as is. 😄

**Comment by PankajBhojwani** [comment]
> so, the value in Leonard's implementation is that you only have one vector. The other one is a span pointing to the subset of the vector that doesn't contain bold. Right now you just seem to have two vectors...

Ah, I get the difference now. Fixed

File: src/renderer/dx/DxFontRenderData.cpp [hunk 9]
```diff
@@ -506,17 +537,56 @@ void DxFontRenderData::_SetFeatures(const std::unordered_map<std::wstring_view,
...
-#pragma warning(suppress : 26445) // the analyzer doesn't like reference to string_view
-    for (const auto& [axis, value] : axes)
+    if (!axes.empty())
     {
-        if (axis.length() == TAG_LENGTH)
+        // Store the weight aside: we will be creating a span of all the axes in the vector except the weight,
+        // and then we will add the weight to the vector
+        // We are doing this so that when the text attribute is bold, we can apply all the axes except the weight
+        bool hasWeight{ false };
+        DWRITE_FONT_AXIS_VALUE weightAxis;
```
Comment (lhecker) [inline src/renderer/dx/DxFontRenderData.cpp:552]: We could make this a `std::optional`.

**Review by lhecker — APPROVED** [review]

**Review by DHowett — APPROVED** [review]
