### PR TITLE
Fix a handoff deadlock if layout completes synchronously

### LINKED ISSUE #18634: Windows Terminal deadlock/lockleak after startup.
### Windows Terminal version

1.23.10353

### Windows build number

27788

### Steps to reproduce

My computer pops up a Windows Terminal window upon startup, which becomes unresponsive and freezes. This has happened twice now, with the previous occurrence happening a few days ago. I attached to the process in VS, paused the program to check where it was blocked, and found that a lock is waiting and has never been notified within TerminalConnection.dll.

Image

Image

Image

### PR DESCRIPTION
**Pull request by lhecker**
I've received a dump from an affected user, and it showed that the layout event in TerminalPage was raised synchronously. This meant that during page initialization, the handoff listener was started while still being stuck inside the handoff listener. This resulted in a deadlock.

This PR fixes the issue by not holding the lock across handoff callback calls.

Closes #18634

## Validation Steps Performed
* Can't repro ❌

### CODE REVIEW

File: src/cascadia/TerminalConnection/ConptyConnection.cpp [hunk 1]
```diff
@@ -780,12 +780,12 @@ namespace winrt::Microsoft::Terminal::TerminalConnection::implementation
...
     void ConptyConnection::StartInboundListener()
     {
-        THROW_IF_FAILED(CTerminalHandoff::s_StartListening(&ConptyConnection::NewHandoff));
-    }
+        static const auto init = []() noexcept {
+            CTerminalHandoff::s_setCallback(&ConptyConnection::NewHandoff);
+            return true;
+        }();
 
-    void ConptyConnection::StopInboundListener()
```
Comment (DHowett) [inline src/cascadia/TerminalConnection/ConptyConnection.cpp:786]: never called?

**Review by DHowett — APPROVED** [review]

**Review by zadjii-msft — APPROVED** [review]

File: src/cascadia/TerminalConnection/ConptyConnection.cpp (hunk 1 above)
Comment (lhecker) [reply src/cascadia/TerminalConnection/ConptyConnection.cpp:786]: I missed your comment. Yeah it's never called and removing it allows us to ensure it remains safe (the registration gets removed directly in the callback routine).
