### PR TITLE
Fix a11y crash in alt buffer apps

### LINKED ISSUE #13183: Terminal crashes when starting nano in bash when screen reader is enabled
### Windows Terminal version

1.14.1433.0 preview

### Windows build number

22621.1

### Other Software

* Nano in either WSL or ssh
* Narrator or NVDA 2022.1

### Steps to reproduce

1. Start wsl from the terminal
2. Type `nano test`

### Expected Behavior

Nano opens as expected

### Actual Behavior

WT crashes

### PR DESCRIPTION
**Pull request by carlos-zamora**
## Summary of the Pull Request
This fixes the crashes caused by using a screen reader when in an app that uses the alt buffer via two changes:
1. Fix `Terminal::ViewEndIndex()`
   - `UiaTextRangeBase` receives a coordinate that is outside of the bounds of the text buffer via the following chain of functions... `_getDocumentEnd()` --> `GetLastNonSpaceCharacter()` --> `_getOptimizedBufferSize()` --> `GetTextBufferEndPoisition()` --> `ViewEndIndex()`
   - Since support for the alt buffer was added recently, `ViewEndIndex()` was recently changed, so that explains why this issue came up recently. We were accidentally setting the view end index to `height` instead of `height-1`. Thanks @j4james for finding this!
   - The UIA code would get the "exclusive end" of the alt buffer. Since it was using `ViewEndIndex()` to calculate that, it was one more than it should be. The UIA code has explicit allowance for "one past the end of the viewport" in its `IsInBounds()` check. Since the `ViewEndIndex()` is way beyond that, it's not allowed, hitting the fail fast.
2. Replace `FAIL_FAST_IF` with `assert`
   - These fail fast calls have caused so many issues with our UIA code. Those checks still provide value, but they shouldn't take the whole app down. This change replaces the `Viewport` and `UiaTextRangeBase` fail fasts with asserts to still perform those checks, but not take down the entire app in release builds.

Closes #13183 

## Validation Steps Performed
While using Narrator...
- opened nano in bash
- generated text and scrolled in nano
- generated text and scrolled in PowerShell

### CODE REVIEW

**Review by zadjii-msft — APPROVED** [review]
Sure. When I was originally testing this, I found another crash after "moving the cursor down some rows" (presumably, in vim).

Did we ever figure out why that caused the out of bounds? or are we just leaning on the FAIL_FAST -> assert to silently ignore?

**Comment by carlos-zamora** [comment]
> Sure. When I was originally testing this, I found another crash after "moving the cursor down some rows" (presumably, in vim).
Just tested it in vim as well, and I can't repro the crash. Not sure how you got it to crash in the past :/.

> Did we ever figure out why that caused the out of bounds? or are we just leaning on the FAIL_FAST -> assert to silently ignore?

oh geez, I meant to include that in the PR body. Adding it now. But here's what I'm adding for quick reference:

> The UIA code would get the "exclusive end" of the alt buffer. Since it was using `ViewEndIndex()` to calculate that, it was one more than it should be. The UIA code has explicit allowance for "one past the end of the viewport" in its `IsInBounds()` check. Since the `ViewEndIndex()` is way beyond that, it's not allowed, hitting the fail fast.

Also relevant, this is really just a backport-able solution for 1.14. The better solution is #13244, but since Leonard's sweeping til::point PR isn't in 1.14, we need to make it not crash. #13244 straight up removes uses of `CompareInBounds` which is responsible for most of our UIA-related crashes. Leveraging til::point's < and > gives us the same benefit but none of the crashing!

File: src/types/UiaTextRangeBase.cpp [hunk 1]
```diff
@@ -1289,9 +1289,9 @@ try
         }
     }
 
-    FAIL_FAST_IF(!(newViewport.Top >= topRow));
-    FAIL_FAST_IF(!(newViewport.Bottom <= bottomRow));
-    FAIL_FAST_IF(!(_getViewportHeight(oldViewport) == _getViewportHeight(newViewport)));
+    assert(newViewport.Top >= topRow);
```
Comment (DHowett) [inline src/types/UiaTextRangeBase.cpp:1292]: @lhecker, can you suggest something better than just assert? If there is anything better. Otherwise, let's just do this.

File: src/cascadia/TerminalCore/Terminal.cpp [hunk 2]
```diff
@@ -992,7 +992,7 @@ int Terminal::ViewStartIndex() const noexcept
 
 int Terminal::ViewEndIndex() const noexcept
 {
-    return _inAltBuffer() ? _altBufferSize.height : _mutableViewport.BottomInclusive();
+    return _inAltBuffer() ? _altBufferSize.height - 1 : _mutableViewport.BottomInclusive();
```
Comment (DHowett) [inline src/cascadia/TerminalCore/Terminal.cpp:995]: @zadjii-msft are there any alt buffer conformance scenarios you'd like us to check before committing to this change?

File: src/types/viewport.cpp [hunk 3]
```diff
@@ -432,7 +433,7 @@ bool Viewport::WalkInBounds(til::point& pos, const WalkDir dir, bool allowEndExc
 bool Viewport::WalkInBoundsCircular(til::point& pos, const WalkDir dir, bool allowEndExclusive) const noexcept
 {
     // Assert that the position given fits inside this viewport.
-    FAIL_FAST_IF(!IsInBounds(pos, allowEndExclusive));
+    assert(IsInBounds(pos, allowEndExclusive));
```
Comment (DHowett) [inline src/types/viewport.cpp:436]: What happens down the line when UIA _tries to use this new coordinate_ that is provably out of bounds? What happens when we Walk it in bounds circular?

File: src/types/viewport.cpp [hunk 4]
```diff
@@ -365,11 +365,12 @@ bool Viewport::DecrementInBoundsCircular(til::point& pos) const noexcept
 // -  This is so you can do s_CompareCoords(first, second) <= 0 for "first is left or the same as second".
 //    (the < looks like a left arrow :D)
 // -  The magnitude of the result is the distance between the two coordinates when typing characters into the buffer (left to right, top to bottom)
+#pragma warning(suppress : 4100)
```
Comment (DHowett) [inline src/types/viewport.cpp:368]: ???

File: src/types/UiaTextRangeBase.cpp (hunk 1 above)
Comment (carlos-zamora) [reply src/types/UiaTextRangeBase.cpp:1292]: The thread I dug up from like 3 years ago had Michael suggesting telemetry asserts. Unfortunately, that requires a decent amount of work to set up.

File: src/types/viewport.cpp (hunk 4 above)
Comment (carlos-zamora) [reply src/types/viewport.cpp:368]: It's dumb. `allowEndExclusive` is now a param that's not referenced anywhere... but like, it is, it's just hidden behind an `assert`.

File: src/cascadia/TerminalCore/Terminal.cpp (hunk 2 above)
Comment (zadjii-msft) [reply src/cascadia/TerminalCore/Terminal.cpp:995]: This I checked myself before I left last week, and seemed like it was just a typo tbh. Like, there's no reason to not have the -1

File: src/types/viewport.cpp (hunk 3 above)
Comment (DHowett) [reply src/types/viewport.cpp:436]: Hmmmmmmm.

I guess the problem with `MyClamp` is that _if we knew when to use it,_` we wouldn't have had this problem in the first place. Right?

File: src/types/UiaTextRangeBase.cpp (hunk 1 above)
Comment (lhecker) [reply src/types/UiaTextRangeBase.cpp:1292]: The only alternative to telemetry asserts that come to my mind is `WI_ASSERT`.

**Review by lhecker — APPROVED** [review]

File: src/types/viewport.cpp (hunk 3 above)
Comment (lhecker) [reply src/types/viewport.cpp:436]: I personally would say that we should use fail-fasts or exceptions for security or safety relevant checks (e.g. boundary checks for array access). For anything else I'd use debug assertions + clamping/truncation/etc. in release on a "lazy" best-effort basis.

The suggested code above would be overkill already for that purpose IMO. It's not just stopping incorrect behavior, but also tries to correct the position in a smart manner. But how do we know that this improves the behavior? It shouldn't pass incorrect positions in the first place after all!

As such I'd just use `std::clamp` 4 times for numeric parameters like that.

**Review by DHowett — COMMENTED** [review]
FWIW we automerged this without addressing exactly _what_ happens when an out of bounds coordinate escapes through the assert since it's not built in Release
