### PR TITLE
Fix a hang when writing wide glyphs into a 1 column terminal

### LINKED ISSUE #7416: Windows terminal hangs under stress after resizing vertical pane to the minimum width
# Environment

```none
Windows build number: 10.0.20197.0
Windows Terminal version: 1.2.2381.0
```
# Steps to reproduce
1. Open Windows Terminal
2. Press alt+shift+= to open a second vertical pane
3. Build and run this [TerminalStress](https://github.com/Treit/TerminalStress) application in the left-hand pane.
4. While the stress test is running, press `alt+shift+left arrow key` to reduce the size of the pane. Repeat until the pane is reduced to the smallest possible width.

# Expected behavior
The terminal does not hang.

# Actual behavior
The terminal becomes unresponsive and hangs.

### PR DESCRIPTION
**Pull request by lhecker**
The code changes are mostly self-explanatory: Just skip glyphs
that can never be inserted. I implemented it slightly incorrectly
(a newline will be inserted every time you write such a wide glyph),
but it's a niche issue and I think the simplicity of the fix is
more important than its exact correctness.

It also contains a fix for some severe log spam due to
`_PrepareForDoubleByteSequence` complaining in this situation.
The spam is so bad that it freezes the app for a few seconds
during text buffer reflow.

Closes #7416

## Validation Steps Performed
* Open an extra pane and run `TerminalStress.exe` in there
* Resize to 1 column
* Doesn't hang ✅

### CODE REVIEW

File: src/terminal/adapter/adaptDispatch.cpp [hunk 1]
```diff
@@ -139,17 +139,22 @@ void AdaptDispatch::_WriteToBuffer(const std::wstring_view string)
 
         if (isWrapping)
         {
-            if (wrapAtEOL)
+            // We want to wrap, but we're not allowed to and we failed to write
+            // even a single character into the row. This can mean two things:
+            // * The glyph is wider than the buffer and can never be inserted.
```
Comment (DHowett) [inline src/terminal/adapter/adaptDispatch.cpp:144]:
```suggestion
            // * The glyph is wider than the buffer and can never be inserted (which is indicated by the start column being 0)
```

Hey, what happens if you set a DECLRMM (@j4james PR #14876) that is 1 column wide and try to put a wide char in it?

Comment (j4james) [reply src/terminal/adapter/adaptDispatch.cpp:144]: The left margin has to be less than the right margin, which guarantees a margin area at least two columns wide. Unless the screen itself is only wide column wide, but then it should behave as if no margins are set at all, which would assumedly be covered by the fix in this PR.

Comment (lhecker) [reply src/terminal/adapter/adaptDispatch.cpp:144]: I think I would feel a little more comfortable if it was hardened against this anyways. I think this can be achieved by replacing the condition with `state.columnBegin == leftMargin`.

Comment (j4james) [reply src/terminal/adapter/adaptDispatch.cpp]: I don't think that's technically correct, though, because the left margin isn't necessarily where the cursor will end up when it wraps. That won't matter if the only time this can occur is when the left margin is 0 anyway, but then it's just making the code more confusing. Because either it's not needed, or it's wrong.

Comment (lhecker) [reply src/terminal/adapter/adaptDispatch.cpp]: Hmm I haven't read your PR yet, so I'm not sure I understand that. The reason I'm worried about this is because I'm playing around with the idea of introducing cells that are wider than 2 columns for the purpose of improved Unicode correctness during reflow on resize. I'm not sure yet whether it'll work out since most (all?) other terminals don't do that, but I would like to avoid issues like this one, even if it's a hypothetical 3 column wide glyph that fails to insert into a 2 column wide buffer. This PR would work in this situation, because without margins, on line wrap, the cursor will end up on column 0 and my assumption is that if a glyph fails to insert at column 0, it'll also fail to insert at any other column, so it needs to be dropped. I'm not sure how this would work with margins, because I don't quite understand how DECLRMM works yet (especially since I would've assumed that the cursor remains inside the margins during line wrap).

Comment (j4james) [reply src/terminal/adapter/adaptDispatch.cpp]: Although, now that I think about it, if we're ever going to get to a point where we're writing out characters that occupy _more_ than two columns, this could be a problem. I think that might be more complicated to handle correctly though. I'm curious now how other terminals deal with that.

Comment (lhecker) [reply src/terminal/adapter/adaptDispatch.cpp]: To make a somewhat contrived, but still quite valid example, a category of characters that is combining but still considered to occupy a column are the characters from the "Spacing Mark" (Mc) category. One example is 온〮 (100 in middle Korean; U+C628 U+302E) which is a single grapheme and thus should optimally never be broken apart by us, but according to the asian width spec this grapheme is supposed to occupy 4 columns[^1].

[^1]: it's somewhat puzzling why they assigned 2 columns to U+302E - probably a typo on their end. This makes it a perfect example however.

Comment (j4james) [reply src/terminal/adapter/adaptDispatch.cpp]: The complication is that the horizontal margins only apply to wrapping when you're also within the boundaries of the vertical margins. For example, consider these parameters:

* screen width is 80 columns
* horizontal margins are 79 to 80 (inclusive)
* vertical margins are 10 to 20
* cursor position is column 79, row 5

If you try to write out your 4-column character at that point, it's not going to fit. However, the cursor should wrap to column 1 on row 6, where a 4-column character _will_ fit, despite the fact that your starting point happened to be aligned with the left margin.

There may be other edge cases I haven't thought of, but that's the first one that springs to mind.

File: src/buffer/out/textBuffer.cpp [hunk 2]
```diff
@@ -272,10 +272,6 @@ bool TextBuffer::_AssertValidDoubleByteSequence(const DbcsAttribute dbcsAttribut
 // - false otherwise (out of memory)
 bool TextBuffer::_PrepareForDoubleByteSequence(const DbcsAttribute dbcsAttribute)
 {
-    // This function corrects most errors. If this is false, we had an uncorrectable one which
-    // older versions of conhost simply let pass by unflinching.
-    LOG_HR_IF(E_NOT_VALID_STATE, !(_AssertValidDoubleByteSequence(dbcsAttribute))); // Shouldn't be uncorrectable sequences unless something is very wrong.
```
Comment (DHowett) [inline src/buffer/out/textBuffer.cpp:277]: ha we stopped even logging it.

**Review by DHowett — APPROVED** [review]
I trust

**Comment by DHowett** [comment]
Now here's a fun question!

Will this return a failure to the user application by way of `WriteConsole` or `WriteFile` returning false?

**Review by zadjii-msft — APPROVED** [review]
