### PR TITLE
Fix a pair of TermControl dragging bugs

### LINKED ISSUE #4603: Quickly dragging a tab into the terminal area that has text selected modifies that selection
# Environment

```none
Windows build number:  10.0.18362.0
Windows Terminal version (if applicable): master (941a44a46491e1a018419eb24c9d92d3b2640e55)

Any other software?
```

# Steps to reproduce

1. Make a selection.
2. Quickly drag a tab onto the terminal area.

# Expected behavior

The selection is not modified.

# Actual behavior

The selection is modified.

### LINKED ISSUE #9109: Dragging a tab makes the window slowly scroll up for a while even after not dragging the tab anymore
# Environment

```none
Windows build number: 10.0.19042.0
Windows Terminal version (if applicable): 1.5.10271.0
```

# Steps to reproduce

1. Have a single tab open
2. Drag that tab downward a little (starting your drag at the bottom of the tab, sometimes text in the terminal gets selected this way, but that's not necessary for this to happen)

# Expected behavior

It shouldn't scroll up forever when you do that

# Actual behavior

If the terminal can scroll up it will scroll up slowly and go on until you click in the terminal
video: https://www.youtube.com/watch?v=o0T1jeFemvQ

### PR DESCRIPTION
**Pull request by zadjii-msft**
## Summary of the Pull Request

This fixes two bugs related to dragging into the bounds of the `TermControl`. Although the fixes are fairly small, I'm batching them up, because I don't want to stack 2 more PRs on top of #10051.

* #9109 
  - This is fixed by only starting an autoscroll if the click&drag actually started within the bounds of the control. 
* #4603
  - Building on the above change, only modify the selection when the drag started in the control. 
 
## References
* srsly go read #10051.

## PR Checklist
* [x] Closes #9109
* [x] Closes #4603
* [x] I work here
* [x] Test added
* [n/a] Requires documentation to be updated

## Detailed Description of the Pull Request / Additional comments

This is kind of annoying that the auto-scrolling is handled by the TermControl, but it uses a timer that's still a WinUI construct.

We only want to start the auto-scrolling behavior when the drag started _inside_ the control. Otherwise, in the tab drag scenario, dragging into the bounds of the TermControl will trick it into thinking it should start a scroll.

### CODE REVIEW

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 1]
```diff
@@ -1154,6 +1167,8 @@ namespace winrt::Microsoft::Terminal::Control::implementation
             return;
         }
 
+        _pointerPressedInBounds = false;
```
Comment (DHowett) [inline src/cascadia/TerminalControl/TermControl.cpp:1170]: And because we use _capture_... if the cursor is pressed inside and released outside, we still get this message and clear the flag yes?

**Review by DHowett — APPROVED** [review]

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 1 above)
Comment (zadjii-msft) [reply src/cascadia/TerminalControl/TermControl.cpp:1170]: 🤔

Comment (zadjii-msft) [reply src/cascadia/TerminalControl/TermControl.cpp:1170]: Checked out the branch and confirmed - yes we do

**Review by miniksa — APPROVED** [review]
Yeah. Looks good.

**Comment by miniksa** [comment]
Oop. Gotta fix that merge conflict. Assigning Mike.
