### PR TITLE
Fix use-after-free when disabling the ASB

### LINKED ISSUE #17515: Switching between buffers while a cooked read is active crashes conhost
### Windows Terminal version

_No response_

### Windows build number

10.0.26120.0

### Other Software

_No response_

### Steps to reproduce

Run the following code:
```cpp
#include <Windows.h>

int main() {
    SetConsoleOutputCP(CP_UTF8);
    SetConsoleMode(GetStdHandle(STD_INPUT_HANDLE), ENABLE_PROCESSED_INPUT | ENABLE_LINE_INPUT | ENABLE_ECHO_INPUT);
    SetConsoleMode(GetStdHandle(STD_OUTPUT_HANDLE), ENABLE_PROCESSED_OUTPUT | ENABLE_WRAP_AT_EOL_OUTPUT | ENABLE_VIRTUAL_TERMINAL_PROCESSING | DISABLE_NEWLINE_AUTO_RETURN);

    // Disabled the alternate screen buffer while a cooked read is ongoing.
    CreateThread(
        nullptr,
        0,
        [](void*) -> DWORD {
            Sleep(1000);
            WriteFile(GetStdHandle(STD_OUTPUT_HANDLE), "\x1b[?1049l", 8, nullptr, nullptr);
            return 0;
        },
        nullptr,
        0,
        nullptr
    );

    char buf[128];
    WriteFile(GetStdHandle(STD_OUTPUT_HANDLE), "\x1b[?1049h", 8, nullptr, nullptr);
    ReadFile(GetStdHandle(STD_INPUT_HANDLE), &buf[0], 128, nullptr, nullptr);
    return 0;
}
```

and press any (visible character) key.

### Expected Behavior

_No response_

### Actual Behavior

The crash occurs because we don't cancel (or update) the pending cooked read in `SCREEN_INFORMATION::UseAlternateScreenBuffer` / `UseMainScreenBuffer`. Any version of conhost that supports alt buffers crashes with the above repro. Since support for ASB has existed for a while I'd not give this a P0, even if it's a stale pointer read (= bad, because unpredictable).

### PR DESCRIPTION
**Pull request by lhecker**
Closes #17515

## Validation Steps Performed
* Disable the ASB while there's a pending cooked read
* Type some text
* No crash ✅

### CODE REVIEW

File: src/server/WaitQueue.cpp [hunk 1]
```diff
@@ -103,6 +103,22 @@ bool ConsoleWaitQueue::NotifyWaiters(const bool fNotifyAll,
     return fResult;
 }
 
+void ConsoleWaitQueue::CancelWaitersForScreenBuffer(const SCREEN_INFORMATION* pScreenInfo)
+{
+    for (auto it = _blocks.begin(); it != _blocks.end();)
```
Comment (DHowett) [inline src/server/WaitQueue.cpp:108]: if it can be erased, doesn't that make iterating this list during modification into UB?

Comment (DHowett) [reply src/server/WaitQueue.cpp:108]: it's an `std::list`, this is fine
