### PR TITLE
Set working directory when invoked from shell extension

### LINKED ISSUE #8933: "Open Windows Terminal here" does not continue to work for subsequent tabs, panes
# Environment

```none
Windows build number: 10.0.19042.0
Windows Terminal version (if applicable): 1.5.10271.0

Any other software?
```

# Steps to reproduce
1. Click "Open Windows Terminal here" in directory
2. Click WSL or CMD (anything that different than the default tab)
image

Else, I have been add `startingDirectory` in setting:
```
"profiles":
    {
        "defaults":
        {
            "startingDirectory" : "."
            // Put settings here that you want to apply to all profiles.
        },
```

# Expected behavior
For example, I click "Open Windows Terminal here" in `D:\Games`.
What I think it should be:
image
image
image

# Actual behavior

My default tab is Powershell7, it works well:
image
But if I switch to WSL or CMD:
image
image

the path goes to `C:\Windows\system32`.

# Other
I now use this for me:
```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\Directory\Background\shell\wt]
@="Open in Windows Terminal here"
"Icon"="%USERPROFILE%\\AppData\\Local\\terminal\\wt_32.ico"

[HKEY_CLASSES_ROOT\Directory\Background\shell\wt\command]
@="C:\\Users\\hjthjthjt\\AppData\\Local\\Microsoft\\WindowsApps\\wt.exe"
```
It works as my expect. But the new feature "Open Windows Terminal here" does not.

### PR DESCRIPTION
**Pull request by ianjoneill**
Sets the working directory of the terminal when invoked from the shell extension. This ensures that new tabs opened with a starting directory of `.` open in the directory that the terminal was invoked from.

Closes #8933

## Validation Steps Performed
Manually tested - default PowerShell profile set to use home directory, Windows PowerShell profile set to use current directory. Launched via the shell extension and the default profile opened in the explorer directory, as did a new Windows PowerShell tab.

### CODE REVIEW

File: src/cascadia/ShellExtension/OpenTerminalHere.cpp [hunk 1]
```diff
@@ -56,16 +56,17 @@ HRESULT OpenTerminalHere::Invoke(IShellItemArray* psiItemArray,
         siEx.StartupInfo.cb = sizeof(STARTUPINFOEX);
 
         // Append a "\." to the given path, so that this will work in "C:\"
-        auto cmdline{ wil::str_printf<std::wstring>(LR"-("%s" -d "%s\.")-", GetWtExePath().c_str(), pszName.get()) };
+        auto path{ wil::str_printf<std::wstring>(LR"-(%s\.)-", pszName.get()) };
+        auto cmdline{ wil::str_printf<std::wstring>(LR"-("%s" -d "%s")-", GetWtExePath().c_str(), path.c_str()) };
```
Comment (lhecker) [inline src/cascadia/ShellExtension/OpenTerminalHere.cpp:60]: We should consider migrating this old code to use the newer `fmt`. It would be:
```cpp
auto path = fmt::format(LR"-({}\.)-", pszName.get());
auto cmdline = fmt::format(LR"-("{}" -d "{}")-", GetWtExePath(), path);
```

Comment (lhecker) [reply src/cascadia/ShellExtension/OpenTerminalHere.cpp:60]: The man has just informed that `fmt` increases binary size by _a lot_ and `wil` was specifically chosen to drastically cut it down.

**Review by lhecker — APPROVED** [review]
The code is correct, but I hope someone else can review the logical correctness.

**Review by zadjii-msft — CHANGES_REQUESTED** [review]
>  I hope someone else can review the logical correctness.

blocking for aforementioned logical correctness discussion

**Comment by ianjoneill** [comment]
So my thinking behind this was that it would make it similar to you running `wt -d .` from the address bar in explorer.

The screenshot below shows the current directory for different launch types:
1. Launch from shell extension without this change
2. Launch from shell extension with this change
3. Launch from `wt -d .` from the address bar in explorer

Current Directory

**Comment by DHowett** [comment]
So, this will definitely work... but only for the default configuration of Terminal. It starts to get a little dicey when you use the "New windows open in ... existing instance of terminal" option. Then again, this doesn't make it **worse** for anyone else; it is just as ambiguous for reused instances as it ever was. 😁

**Review by DHowett — APPROVED** [review]
On account of the thing I said, I'm cool with this. It's not worse than it was, and it is better for our default configuration. We'll have to figure out what to do **in general** with the cwd when Remoting is on.

**Comment by DHowett** [comment]
Thanks for the contribution!

**Comment by ianjoneill** [comment]
Yeah I see what you mean.

The current behaviour (new tabs get the working directory that was used to launch the "parent" terminal window) makes sense from a process hierarchy perspective, but I could understand people wanting something else. If it were to be made configurable I get the impression could be a bit tricky to describe in a clear way!

**Comment by adrianghc** [comment]
This feature does not work for me. I'm using WT Preview 1.10.1933.0.

**Comment by ianjoneill** [comment]
> This feature does not work for me. I'm using WT Preview 1.10.1933.0. New tabs don't launch in the directory of the first tab when launching WT from the shell extension.

Hi @adrianghc, could you open a new issue and provide a copy of your `settings.json`?

**Comment by adrianghc** [comment]
> > This feature does not work for me. I'm using WT Preview 1.10.1933.0. New tabs don't launch in the directory of the first tab when launching WT from the shell extension.
> 
> Hi @adrianghc, could you open a new issue and provide a copy of your `settings.json`?

Done at #10789.
