### PR TITLE
Fix WriteUTF8FileAtomic to preserve symlinks

### LINKED ISSUE #10787: Settings editor erases the symbolic link rather than following it
### Windows Terminal version (or Windows build number)

Windows Terminal Preview 1.10.1933.0

### Other Software

Symbolic link created from my configuration repository with this command:

```powershell
New-Item `
 -ItemType SymbolicLink `
 -Force `
 -Path "$env:LOCALAPPDATA\Packages\Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe\LocalState\settings.json" `
 -Target ./terminal/settings.json
```

### Steps to reproduce

1. Create a symlink to the settings file;
2. open the settings in the terminal and hit the save button.

State after 1.:

image

State after 2.:

image

### Expected Behavior

The settings editor follows the symbolic link and saves the file in my configuration repository.

### Actual Behavior

The settings editor erases the symbolic link.

### PR DESCRIPTION
**Pull request by Don-Vito**
WriteUTF8FileAtomic  overrides the content of the file "atomically"
by creating a temp file and then renaming it to the original path.
The problem arises when the original path is symbolic link,
as the link itself gets overridden by a file (rather than the link target).
This PR introduces a special handling of the symlinks:
if the path as a symlink we resolve the path and use:
1. target's directory to create a temp-file in
2. target itself to be replaced with the tempfile.

Symlink resolution is problematic when the target path does not exist,
as there is no good utility that resolves such link (canonical() fails).
In this corner case we skip the "atomic" approach of renaming the file
and write the link target directly.

Closes #10787

### CODE REVIEW

File: src/cascadia/TerminalSettingsModel/FileUtils.cpp [hunk 1]
```diff
@@ -123,7 +123,11 @@ namespace Microsoft::Terminal::Settings::Model
 
     void WriteUTF8FileAtomic(const std::filesystem::path& path, const std::string_view content)
     {
-        auto tmpPath = path;
+        // GH#10787: In the case of symbolic link, ensure that we modify the target rather than the link itself.
+        // We append the paths manually rather than using "canonical" method to support scenario in which link target doesn't exist
+        const auto resolvedPath = std::filesystem::is_symlink(path) ? path.parent_path() / std::filesystem::read_symlink(path) : path;
```
Comment (eryksun) [inline src/cascadia/TerminalSettingsModel/FileUtils.cpp:128]: What if the target of the symlink is another symlink? Consider using [`std::filesystem::canonical()`](https://docs.microsoft.com/en-us/cpp/standard-library/filesystem-functions?view=msvc-160#canonical), which is implemented in Windows via `GetFinalPathNameByHandleW()`.

Comment (Don-Vito) [reply src/cascadia/TerminalSettingsModel/FileUtils.cpp:128]: Yeah. This is how I started. The problem with canonical is that it requires the target to exist. I am not sure which is more a corner case: a link to a link or link to non- existing file.

Comment (eryksun) [reply src/cascadia/TerminalSettingsModel/FileUtils.cpp:128]: You could handle the exception / error by manually resolving the target path.

Comment (Don-Vito) [reply src/cascadia/TerminalSettingsModel/FileUtils.cpp:128]: > You could handle the exception / error by manually resolving the target path.

So if there is a link to a link to non-existing file, the canonical will throw / return error. And in this case we will need to resolve path manually, by appending within a loop. In this case the question is why not to resolve manually in a loop in the first place. 

So, IMHO, the options are:
1. resolve manually by replacing if with while
2. use canonical, with disclaimer the path needs to exist

WDYT?

Comment (zadjii-msft) [reply src/cascadia/TerminalSettingsModel/FileUtils.cpp:128]: It seems to me like we should be redundant enough to be able to handle both smylinks that point to symlinks and paths that don't exist. Like, what about when the file is first written? That's a case where the path won't exist yet.

Comment (Don-Vito) [reply src/cascadia/TerminalSettingsModel/FileUtils.cpp]: So I continued with the first option of manual resolution in while loop. Tested the following paths:
* no file
* file
* a link to a file
* a link to a link to a file
* a link to a non-existing file

File: src/cascadia/TerminalSettingsModel/FileUtils.cpp [hunk 2]
```diff
@@ -123,7 +123,15 @@ namespace Microsoft::Terminal::Settings::Model
 
     void WriteUTF8FileAtomic(const std::filesystem::path& path, const std::string_view content)
```
Comment (lhecker) [inline src/cascadia/TerminalSettingsModel/FileUtils.cpp:124]: nit: You could modify this function to take `path` as a by-value argument.
That way you don't have to create the local `resolvedPath` copy.

**Review by lhecker — APPROVED** [review]

File: src/cascadia/TerminalSettingsModel/FileUtils.cpp (hunk 2 above)
Comment (Don-Vito) [reply src/cascadia/TerminalSettingsModel/FileUtils.cpp:124]: Thanks for the review!

This could simplify the code for sure. On the other hand it would probably make the interface with the clients less clean: i.e., tomorrow we might decide to implement the function completely differently, and then we will need to revert the interface to the current signature.

File: src/cascadia/TerminalSettingsModel/FileUtils.cpp [hunk 3]
```diff
@@ -125,7 +125,11 @@ namespace Microsoft::Terminal::Settings::Model
     {
         // GH#10787: In the case of symbolic link, ensure that we modify the target rather than the link itself.
         // We append the paths manually rather than using "canonical" method to support scenario in which link target doesn't exist
-        const auto resolvedPath = std::filesystem::is_symlink(path) ? path.parent_path() / std::filesystem::read_symlink(path) : path;
+        auto resolvedPath = path;
+        while (std::filesystem::is_symlink(resolvedPath))
+        {
+            resolvedPath = resolvedPath.parent_path() / std::filesystem::read_symlink(resolvedPath);
+        }
```
Comment (eryksun) [inline src/cascadia/TerminalSettingsModel/FileUtils.cpp:132]: One concern with manual symlink resolution is that it opens a can of worms regarding the symlink evaluation policy for L2L (local to local), L2R (local to remote), R2R, and R2L symlink types. (Check, for example, `fsutil.exe  behavior query symlinkEvaluation`.) I don't personally care about the first 3 types, but the last one is disturbing, and I think it should always be disabled. Symlinks are evaluated on the client side, so an R2L symlink is probably a mistake (e.g. "\\\\server\\share\\link" -> "C:\\local\\target\\path"). If a symlink type is disabled, then trying to follow it should fail with an `error_code` `value()` equal to `ERROR_SYMLINK_CLASS_DISABLED` (1463). This is the case for the `exists()` and `canonical()` methods, but `is_symlink()` and `read_symlink()` never ask the system to actually follow the link.

File: src/cascadia/TerminalSettingsModel/FileUtils.cpp (hunk 2 above)
Comment (lhecker) [reply src/cascadia/TerminalSettingsModel/FileUtils.cpp:124]: You don't have to change it. 🙂

But in general: Since we aren't writing a library, we can still change almost any code `src/cascadia` however we want to. This file in particular is an internal implementation detail.

File: src/cascadia/TerminalSettingsModel/FileUtils.cpp (hunk 3 above)
Comment (Don-Vito) [reply src/cascadia/TerminalSettingsModel/FileUtils.cpp:132]: @eryksun - these are great points: I didn't consider the remote links at all 🤦 But I am still not certain how to avoid manual resolution, if we want to support cases that the final target file doesn't exist, which I believe might be a common scenario (someone might remove the file to let the sessions be recreated)

File: src/cascadia/TerminalSettingsModel/FileUtils.cpp (hunk 2 above)
Comment (Don-Vito) [reply src/cascadia/TerminalSettingsModel/FileUtils.cpp:124]: > But in general: Since we aren't writing a library, we can still change almost any code `src/cascadia` however we want to. This file in particular is an internal implementation detail.

Yeah I know - and in general you are right! My point is that every class (especially like this util) might become a library some day, so I usually prefer not to pass by value even in such cases. But this more of a habit I guess :blush:

File: src/cascadia/TerminalSettingsModel/FileUtils.cpp (hunk 3 above)
Comment (lhecker) [reply src/cascadia/TerminalSettingsModel/FileUtils.cpp:132]: We could also try to resolve the file with `std::filesystem::canonical` and if the target doesn't exist (aka `canonical()` throws), fall back to writing the file directly, without the tmp file.
It allows atomic file operations for most users in most cases, but avoids the can of worms @eryksun has described.

Comment (Don-Vito) [reply src/cascadia/TerminalSettingsModel/FileUtils.cpp:132]: > 
> 
> We could also try to resolve the file with `std::filesystem::canonical` and if the target doesn't exist (aka `canonical()` throws), fall back to writing the file directly, without the tmp file.
> It allows atomic file operations for most users in most cases, but avoids the can of worms @eryksun has described.

My problem with this approach is the case when we have a link to a non-existing file.
In such case the canonical will fail and we will fallback to writing the file directly, rather than writing to the file that the link points to.
I believe that such scenario might be common: let's say I have a link to a settings folder (like in the original ticket) and I decided to delete the settings from this configuration folder, so they will be recreated. The suggested approach will destroy my file structure.

Comment (eryksun) [reply src/cascadia/TerminalSettingsModel/FileUtils.cpp:132]: I was thinking to use `canonical()`, and handle `ERROR_FILE_NOT_FOUND` (2), and only that error code, with manual symlink resolution. If the symlink type is disabled, the error will be `ERROR_SYMLINK_CLASS_DISABLED` (1463), which shouldn't be handled.

Comment (Don-Vito) [reply src/cascadia/TerminalSettingsModel/FileUtils.cpp:132]: Get it. I will do it. Thanks.

Comment (lhecker) [reply src/cascadia/TerminalSettingsModel/FileUtils.cpp:132]: > In such case the canonical will fail and we will fallback to writing the file directly, rather than writing to the file that the link points to.

I thought that if you `OpenFile()` a symlink on Windows it resolves that symlink. Do you mean to say that `OpenFile()` would overwrite the symlink? I thought that the rename operation is the problem here...

Comment (Don-Vito) [reply src/cascadia/TerminalSettingsModel/FileUtils.cpp:132]: @lhecker  - Oh.. Now I see what you mean. The question regarding the OpenFile and writing to it is whether the operation will be atomic enough (at least at the level this function tries to achieve).

Comment (Don-Vito) [reply src/cascadia/TerminalSettingsModel/FileUtils.cpp:132]: I mean, in your implementation:
```
        // GH#10787: In the case of symbolic link, ensure that we modify the target rather than the link itself.
        // If the link target does not exist, "canonical" will fail. In this case however we can simply write the file
        if (std::filesystem::exists(path))
        {
            const auto resolvedPath = std::filesystem::canonical(path);
            auto tmpPath = resolvedPath;
            tmpPath += L".tmp";

            // Writing to a file isn't atomic, but...
            WriteUTF8File(tmpPath, content);

            // renaming one is (supposed to be) atomic.
            // Wait... "supposed to be"!? Well it's technically not always atomic,
            // but it's pretty darn close to it, so... better than nothing.
            std::filesystem::rename(tmpPath, resolvedPath);
        }
        else
        {
            // Is this gooed enough? It is not atomic.
            WriteUTF8File(path, content);
        }
```

Comment (eryksun) [reply src/cascadia/TerminalSettingsModel/FileUtils.cpp:132]: > I thought that if you `OpenFile()` a symlink on Windows it resolves that symlink. Do you mean to say that `OpenFile()` would overwrite the symlink? I thought that the rename operation is the problem here...

By default, [`CreateFileW()`](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilew) follows all types of reparse points, unless it's passed the flag `FILE_FLAG_OPEN_REPARSE_POINT`. But the apparent goal here for the case of a symlink is to modify the symlink target in an atomic manner. So the new file has to be created beside the target, and then `rename()` is called to replace the target file.

Comment (Don-Vito) [reply src/cascadia/TerminalSettingsModel/FileUtils.cpp:132]: @eryksun, @lhecker  - what do you think about this:
```
        // GH#10787: In the case of symbolic link, ensure that we modify the target rather than the link itself.
        // If the link target does not exist, "canonical" will fail. In that case we resolve the link manually.
        auto resolvedPath = path;
        if (std::filesystem::exists(path))
        {
            resolvedPath = std::filesystem::canonical(path);
        }
        else
        {
            while (std::filesystem::is_symlink(resolvedPath))
            {
                resolvedPath = resolvedPath.parent_path() / std::filesystem::read_symlink(resolvedPath);
            }
        }

        auto tmpPath = resolvedPath;
        tmpPath += L".tmp";

        // Writing to a file isn't atomic, but...
        WriteUTF8File(tmpPath, content);

        // renaming one is (supposed to be) atomic.
        // Wait... "supposed to be"!? Well it's technically not always atomic,
        // but it's pretty darn close to it, so... better than nothing.
        std::filesystem::rename(tmpPath, resolvedPath);
```

Comment (lhecker) [reply src/cascadia/TerminalSettingsModel/FileUtils.cpp:132]: Personally I'd do:
```cpp
void WriteUTF8FileAtomic(const std::filesystem::path& path, const std::string_view content)
{
    // GH#10787: rename() will replace symlinks themselves and not the path they point at.
    // It's thus important that we first resolve them before generating tmpPath.
    std::error_code ec;
    const auto resolvedPath = std::filesystem::canonical(path, ec);

    if (ec)
    {
        // If path is a link and the target does not exist, "canonical" will fail.
        // Considering that our "atomic" writes are only on a best-effort base anyways,
        // the best fallback with highest compatibility is to just write the file.
        WriteUTF8File(path, content);
    }
    else
    {
        auto tmpPath = resolvedPath;
        tmpPath += L".tmp";

        // Writing to a file isn't atomic, but...
        WriteUTF8File(tmpPath, content);
        // renaming one is (supposed to be) atomic.
        // Wait... "supposed to be"!? Well it's technically not always atomic,
        // but it's pretty darn close to it, so... better than nothing.
        std::filesystem::rename(tmpPath, resolvedPath);
    }
}
```

Comment (eryksun) [reply src/cascadia/TerminalSettingsModel/FileUtils.cpp:132]: I'd manually resolve the path in the loop if `canonical(path)` raises a `filesystem_error` with a `code().value()` of `ERROR_FILE_NOT_FOUND`. Else `throw` the exception to let the caller handle the problem.

Comment (Don-Vito) [reply src/cascadia/TerminalSettingsModel/FileUtils.cpp:132]: @lhecker, @eryksun - you are both suggesting improved variations of two approaches attached earlier. Which is great, but we need to decide on one of them, and then we can improve it even further (e.g., by throwing if ec!=error_file_not_found). So the options are:
* @lhecker: if the file doesn't exist - create it
* @eryksun: if the file doesn't exist - resolve the path manually

The pro of @lhecker's approach is that path resolution will be more accurate. The pro of @eryksun's approach is that we preserve better atomicity when the file doesn't exist. What I am missing is how much this atomicity important when the file doesn't exist.

Comment (eryksun) [reply src/cascadia/TerminalSettingsModel/FileUtils.cpp:132]: > What I am missing is how much this atomicity important when the file doesn't exist.

The intent is to avoid having an accessible file that's in the process of being written, so one uses a temporary name until the file is completely written. (Usually the name is a relatively long random name, rather than just appending ".tmp" to the  target name.) The alternative in Windows is to to open without sharing any data access (not generally possible in POSIX), in which case other threads that try to open the file will fail with `ERROR_SHARING_VIOLATION` (32), but that's more complicated for everyone.

Comment (Don-Vito) [reply src/cascadia/TerminalSettingsModel/FileUtils.cpp:132]: @eryksun - I understand a concept of atomic update and the use of renaming as a way to simulate it. 
My question was: what is the impact of this function not being atomic in the case that the file doesn't exist. E..g.: does it mean that every 3rd fresh run will fail, or does it mean that hypothetically in some weird case there will be some message.

Comment (lhecker) [reply src/cascadia/TerminalSettingsModel/FileUtils.cpp:132]: Ever since @eryksun brought up the topic of symlink evaluation policies I'm convinced that we should avoid manually resolving symlinks. Because if the resolve-loop is fine as a fallback I don't see why we should use `canonical()` in the first place - the "vulnerability" would still be there as a fallback.
In either case, an imperfect solution is fine for now in my opinion. If possible I'd err on the side of security wherever we can though.

Comment (eryksun) [reply src/cascadia/TerminalSettingsModel/FileUtils.cpp:132]: I'm only looking at from the POV of implementing the intent of the function. The implementation of `rename()` in Windows calls `MoveFileExW()` with the flags `MOVEFILE_COPY_ALLOWED` and `MOVEFILE_REPLACE_EXISTING`. It won't be atomic if it has to copy the file across filesystems and delete the original, but renaming a file within a filesystem is atomic.

Comment (eryksun) [reply src/cascadia/TerminalSettingsModel/FileUtils.cpp:132]: > Because if the resolve-loop is fine as a fallback I don't see why we should use `canonical()` in the first place - the "vulnerability" would still be there as a fallback.

The only error I'd handle from `canonical()` is a missing target file, in which case the symlink type was supported -- at the time of the `canonical()` call. However, there is some concern that another thread can meddle with the symlink(s) in between calls (e.g. replace a link with one that targets another path) while resolving the path manually.

Comment (Don-Vito) [reply src/cascadia/TerminalSettingsModel/FileUtils.cpp:132]: @eryksun - I am not sure we need to preserve the intent of the function at any price, as it is used in 2 places only in the code. I also agree with @lhecker that manual resolution of the symlinks is risky. My major concern with @lhecker's approach is when will this lack of atomicity screw us? For instance we have a watchdog on the folder - will it get triggered in the middle of the writing the new file, will it crash the terminal?

Comment (Don-Vito) [reply src/cascadia/TerminalSettingsModel/FileUtils.cpp]: @eryksun, @lhecker - I pushed the version that:
1. Uses canonical by default
2. Throws if canonical fails not due to file not found
3. Has a single clause that handles the corner case when the path points to a link and the target doesn't exist
4. I have chosen @lhecker's suggestion of implementing this fallback clause by simply writing to a file

File: src/cascadia/TerminalSettingsModel/FileUtils.cpp [hunk 4]
```diff
@@ -123,15 +123,41 @@ namespace Microsoft::Terminal::Settings::Model
...
+        auto resolvedPath = std::filesystem::canonical(path, ec);
+        if (ec)
+        {
+            if (ec.value() != ERROR_FILE_NOT_FOUND)
+            {
+                THROW_WIN32_MSG(ec.value(), "failed to compute canonical path");
+            }
+
+            // We were not able to compute the canonical path as the target does not exist.
+            if (std::filesystem::is_symlink(path))
```
Comment (lhecker) [inline src/cascadia/TerminalSettingsModel/FileUtils.cpp:138]: As I said, IMO this check is unnecessary. We have various other fallbacks in place, in case a prior write corrupted the settings, so the most basic solution is IMO acceptable.
On the other hand this code is fine as it is. --> ✔️

**Review by lhecker — APPROVED** [review]

File: src/cascadia/TerminalSettingsModel/FileUtils.cpp [hunk 5]
```diff
@@ -123,15 +123,41 @@ namespace Microsoft::Terminal::Settings::Model
...
+            {
+                // In the case the original file is a link (but the target doesn't exist), we still need to resolve it.
+                // We considered two fall-backs:
+                // * resolving the link manually (by invoking read_symlink()) which might be less accurate
+                // * writing the file directly, which ensures more accurate link resolution, but leaves the write not atomic.
+                // We have chosen the latter, as this is an edge case and our "atomic" writes are only best-effort anyways.
+                WriteUTF8File(path, content);
+                return;
+            }
```
Comment (eryksun) [inline src/cascadia/TerminalSettingsModel/FileUtils.cpp:147]: It doesn't need the expensive `canonical()` call if the final component isn't a symlink, which is how you structured it in the first code that I saw. For example:
```c++
    std::error_code ec;
    auto resolvedPath = std::filesystem::is_symlink(path) ?
                          std::filesystem::canonical(path, ec) : path;
    if (ec)
    {
        if (ec.value() != ERROR_FILE_NOT_FOUND)
        {
            THROW_WIN32_MSG(ec.value(), "failed to compute canonical path");
        }
        
        // The original file is a symlink, but the target doesn't exist. 
        // Consider two fall-backs:
        //   * resolve the link manually, which might be less accurate and
        //     more prone to race conditions
        //   * write to the file directly, which lets the system resolve the
        //     the symlink but leaves the write non-atomic
        // The latter is chosen, as this is an edge case and our 'atomic'
        // writes are only best-effort.
        
        WriteUTF8File(path, content);
        return;
    }
```

**Comment by lhecker** [comment]
@eryksun What's the default value of `std::error_code`?
Doesn't this mean `if (ec)` is always true if it's not a symlink, forcing non-atomic writes for non-symlink targets?

**Comment by Don-Vito** [comment]
> 
> 
> @eryksun What's the default value of `std::error_code`?
> Doesn't this mean `if (ec)` is always true if it's not a symlink, forcing non-atomic writes for non-symlink targets?

The default for error code is 0 (success). Which means that if (ec) is always false for non-symlinks.

File: src/cascadia/TerminalSettingsModel/FileUtils.cpp (hunk 5 above)
Comment (eryksun) [reply src/cascadia/TerminalSettingsModel/FileUtils.cpp]: > I was less concerned of the performance of canonical vs is_symlink (both of which require system calls)

That's reasonable. To clarify my "expensive" comment, they both have to open a file, but the open in `is_symlink()` doesn't have to reparse the symlink target.  Once opened it's a single system call to check for a symlink. In contrast, `canonical()` uses the API function `GetFinalPathNameByHandleW()`, which is implemented with multiple system calls. It uses `NtQueryObject()` and `NtQueryInformationFile()` to split the final path into the device part and filesystem part -- e.g. "\\Device\\HarddiskVolume2\\Windows\\explorer.exe" -> ( "\\Device\\HarddiskVolume2",  "\\Windows\\explorer.exe" ). Another `NtQueryInformationFile()` call gets the normalized path in the filesystem -- e.g. get the actual name casing and long filenames for every component in the final path. It opens a handle to "\\\\.\\MountPointManager" via `NtCreateFile()` and queries the mountpoint manager for the canonical DOS name of the opened device via `NtDeviceIoControlFile()` -- e.g. "\\Device\\HarddiskVolume2" -> "\\\\?\\C:".

**Comment by lhecker** [comment]
@Don-Vito `std::error_code` defines an `operator bool` which returns true if the value is 0.

**Comment by eryksun** [comment]
> @Don-Vito `std::error_code` defines an `operator bool` which returns true if the value is 0.

It's the other way around. It's true when there's a non-zero error value and otherwise false: `std::error_code` [`operator bool`](https://docs.microsoft.com/en-us/cpp/standard-library/error-code-class?view=msvc-160#op_bool) "returns a value convertible to `true` only if `value()` is not equal to zero".

**Comment by lhecker** [comment]
Ah thanks!

**Comment by Don-Vito** [comment]
You are right :smile: and this is exactly what I meant when saying that initial error code is 0 (success). Which means that if the symlink was not invoked then the value remains success, and thus if(ec) returns false. I just didn't mention is that this conversion done by bool() operator. And of course I also tested all these scenarios after each code change.

**Review by DHowett — APPROVED** [review]
I'm v. cool with this; thanks for doing it! :smile:

**Comment by DHowett** [comment]
Also? Welcome back! 👏🏻

**Comment by Don-Vito** [comment]
> I'm v. cool with this; thanks for doing it! :smile:

All the credit goes to @lhecker and @eryksun :)

**Comment by Don-Vito** [comment]
> Also? Welcome back! 👏🏻 

Thanks! :) Hope to finally get some vacation soon (aka best time for coding), so I am warming up :)
