### PR TITLE
Ignore right-click copy when copy on select is enabled

### LINKED ISSUE #4740: Duplicate copyOnSelect actions part 2
# Environment

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

Windows Terminal Version 0.9.433.0

# Steps to reproduce

Please note, this isn't a duplicate of issue #4255 which I reported previously, it's a variation of the same issue which is still present in the latest version where as 4255 is now fixed.

1.  Open WSL Ubuntu terminal
2.  Split pane in two: pane_1 and pane_2
3.  Select a block on text with copyOnSelect enabled (for example "TEST1") on pane_1
4.  Ensure block of text remains highlighted
5.  Make pane_2 the active pane
6.  Switch to notepad instance
7.  Paste selected text into Notepad
8.  Make some change to text, (for example change string to "TEST999")
9.  Copy string inside Notepad
10. Highlight Windows Terminal, clicking into the last active pane (pane_2)
11. Paste string into Windows Terminal
12. Now highlight the other pane (pane_1) that still has the original string highlighted
13. Paste again

# Expected behavior

In both steps 11 and 13, the last copied string, "TEST999", is pasted

# Actual behavior

In step 11, TEST999 is pasted
In step 13, TEST1 is pasted

### PR DESCRIPTION
**Pull request by leonMSFT**
## Summary of the Pull Request
Right clicking on a focused tab while Copy On Select is active currently copies any active selection. This is because `PointerReleasedHandler` doesn't check for the mouse button that was released. 
During a mouse button release, only the left mouse button release should be doing anything.

## PR Checklist
* [x] Closes #4740
* [x] CLA signed.
* [x] Tests added/passed

## Validation Steps Performed
These are the scenarios I've tested. They're a combination of in focus/out of focus, Copy On Select on/off, left/right click pressed and their move and release variants.

From Out of Focus:
- Left Click = Focus
- Left Click Move = Focus + Selection
- Left Click Release
  - CoS on = Copy
  - CoS off = Nothing
- Shift Left Click = Focus
- Right Click 
  - Focus 
  - CoS on = Paste
  - CoS off = Copy if Active Selection, Paste if not.
- Right Click Move = Nothing
- Right Click Release = Nothing

From In Focus
- Left Click = Selection if CoS off
- Left Click Move = Selection
- Left Click Release
  - CoS on = Copy
  - CoS off = Nothing
- Shift Left Click = Set Selection Anchor
- Right Click 
  - CoS on = Paste
  - CoS off = Copy if Active Selection, Paste if not.
- Right Click Move = Nothing
- Right Click Release = Nothing

### CODE REVIEW

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 1]
```diff
@@ -65,11 +65,11 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
         _actualFont{ DEFAULT_FONT_FACE, 0, 10, { 0, DEFAULT_FONT_SIZE }, CP_UTF8, false },
         _touchAnchor{ std::nullopt },
         _cursorTimer{},
-        _lastMouseClick{},
+        _lastMouseClickTS{},
```
Comment (miniksa) [inline src/cascadia/TerminalControl/TermControl.cpp]: I don't recognize what a "TS" is straight off the bat. Rename it? (I had to search down to find it was a "timestamp".)

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 2]
```diff
@@ -974,22 +964,24 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
...
 
         if (ptr.PointerDeviceType() == Windows::Devices::Input::PointerDeviceType::Mouse || ptr.PointerDeviceType() == Windows::Devices::Input::PointerDeviceType::Pen)
         {
-            const auto modifiers = static_cast<uint32_t>(args.KeyModifiers());
-            // static_cast to a uint32_t because we can't use the WI_IsFlagSet
-            // macro directly with a VirtualKeyModifiers
-            const auto shiftEnabled = WI_IsFlagSet(modifiers, static_cast<uint32_t>(VirtualKeyModifiers::Shift));
-
-            if (_terminal->IsCopyOnSelectActive())
+            if (_terminal->IsCopyOnSelectActive() && point.Properties().PointerUpdateKind() == Windows::UI::Input::PointerUpdateKind::LeftButtonReleased)
```
Comment (miniksa) [inline src/cascadia/TerminalControl/TermControl.cpp]: Add comment above this if statement explaining the situation and why we do this (a.k.a. some of the flavor from your PR summary should go here.)
