### PR TITLE
Fix a shutdown race condition in ControlCore

### LINKED ISSUE #18598: Microsoft::Console::VirtualTerminal::StateMachine::ProcessString Crash
Internal ADO link: https://microsoft.visualstudio.com/OS/_workitems/edit/54447014?src=WorkItemMention&src-action=artifact_link

Getting a good amount of crashes for Germanium on v1.21/22/23

### PR DESCRIPTION
**Pull request by lhecker**
I found multiple issues while investigating this:
* Render thread shutdown is racy, because it doesn't actually stop the render thread.
* Lifetime management in `ControlCore` failed to account for the circular dependency of render thread --> renderer --> render data --> terminal --> renderer --> render thread. Fixed by reordering the `ControlCore` members to ensure their correct destruction.
* Ensured that the connection setter calls close on the previous connection.

(Hopefully) Closes #18598

## Validation Steps Performed
* Can't repro the original failure ❌
* Opening and closing tabs as fast as possible doesn't crash anymore ✅
* Detaching and reattaching a tab producing continuous output ✅

### CODE REVIEW

File: src/cascadia/TerminalControl/ControlCore.cpp [hunk 1]
```diff
@@ -142,23 +142,13 @@ namespace winrt::Microsoft::Terminal::Control::implementation
         // If we wait, a screen reader may try to get the AutomationPeer (aka the UIA Engine), and we won't be able to attach
         // the UIA Engine to the renderer. This prevents us from signaling changes to the cursor or buffer.
         {
-            // First create the render thread.
-            // Then stash a local pointer to the render thread so we can initialize it and enable it
-            // to paint itself *after* we hand off its ownership to the renderer.
-            // We split up construction and initialization of the render thread object this way
-            // because the renderer and render thread have circular references to each other.
-            auto renderThread = std::make_unique<::Microsoft::Console::Render::RenderThread>();
-            auto* const localPointerToThread = renderThread.get();
```
Comment (lhecker) [inline src/cascadia/TerminalControl/ControlCore.cpp:151]: This has always been a thorn in my eye, so I fixed it in this PR by moving the `RenderThread` into the Renderer. No more ownership issues.

File: src/cascadia/TerminalControl/ControlCore.cpp [hunk 2]
```diff
@@ -227,9 +218,6 @@ namespace winrt::Microsoft::Terminal::Control::implementation
     ControlCore::~ControlCore()
     {
         Close();
-
-        _renderer.reset();
-        _renderEngine.reset();
```
Comment (lhecker) [inline src/cascadia/TerminalControl/ControlCore.cpp:232]: I removed this, because I fixed the member order of the class.

File: src/cascadia/TerminalApp/DebugTapConnection.cpp [hunk 3]
```diff
@@ -60,9 +60,12 @@ namespace winrt::Microsoft::TerminalApp::implementation
 
     DebugTapConnection::DebugTapConnection(ITerminalConnection wrappedConnection)
     {
-        _outputRevoker = wrappedConnection.TerminalOutput(winrt::auto_revoke, { this, &DebugTapConnection::_OutputHandler });
-        _stateChangedRevoker = wrappedConnection.StateChanged(winrt::auto_revoke, [this](auto&& /*s*/, auto&& /*e*/) {
-            StateChanged.raise(*this, nullptr);
+        _outputRevoker = wrappedConnection.TerminalOutput(winrt::auto_revoke, { get_weak(), &DebugTapConnection::_OutputHandler });
```
[the remark this answers is not in the document]
Comment (DHowett) [reply src/cascadia/TerminalApp/DebugTapConnection.cpp:63]: does this by chance fix the issue where closing a connection while the debug tap is on it crashes terminal

**Comment by DHowett** [comment]
I know the tests probably interact with RenderThread in weird ways.

File: src/cascadia/TerminalApp/DebugTapConnection.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (lhecker) [reply src/cascadia/TerminalApp/DebugTapConnection.cpp:63]: I wasn't aware we had such an issue. It's quite likely that this fixes it.

File: src/cascadia/TerminalControl/ControlCore.cpp [hunk 4]
```diff
@@ -186,30 +176,31 @@ namespace winrt::Microsoft::Terminal::Control::implementation
...
                 });
 
-                if (const auto t = weakTerminal.lock())
-                {
-                    const auto lock = t->LockForWriting();
-                    t->UpdatePatternsUnderLock();
-                }
+                // We can't use a `weak_ptr` to `_terminal` here, because it takes significant
+                // dependency on the lifetime of `this` (primarily on our `_renderer`).
+                // and a `weak_ptr` would allow it to outlive `this`.
```
Comment (DHowett) [inline src/cascadia/TerminalControl/ControlCore.cpp:189]: don't we need to lock `weakThis`? otherwise it's guaranteed that at SOME POINT the debounced function will call into this lambda with a dead weak reference but dereference `this` anyway...

Comment (DHowett) [reply src/cascadia/TerminalControl/ControlCore.cpp:189]: NEVERMIND I CANNOT READ

File: src/cascadia/TerminalControl/ControlCore.h [hunk 5]
```diff
@@ -443,6 +383,70 @@ namespace winrt::Microsoft::Terminal::Control::implementation
...
+
+        // ----------------------------------------------------------------------------------------
+        // These are ordered last to ensure they're destroyed first.
+        // This ensures that their respective contents stops taking dependency on the above.
+        // I recommend reading the following paragraphs in reverse order.
+        // ----------------------------------------------------------------------------------------
+
+        // ↑ This one is tricky - all of these are raw pointers:
+        //   1. _terminal depends on _renderer (for invalidations)
+        //   2. _renderer depends on _terminal (for IRenderData)
```
Comment (DHowett) [inline src/cascadia/TerminalControl/ControlCore.h:430]: the comments below say 3 3 and 1. there is no 2.

File: src/renderer/base/renderer.cpp [hunk 6]
```diff
@@ -91,7 +63,6 @@ IRenderData* Renderer::GetRenderData() const noexcept
         if (--tries == 0)
         {
             // Stop trying.
-            _pThread->DisablePainting();
```
Comment (DHowett) [inline src/renderer/base/renderer.cpp:94]: wha?

**Review by DHowett — APPROVED** [review]
Okay. I think I need you to explain how moving from the current architecture where we have "is the thread allowed to spin" and "does the thread need to actually produce a frame" is OK, and what implications all of this simplification should have on the application. I can see that there's _real issues fixed here,_ but it is a big change in a touchy area.

File: src/cascadia/TerminalControl/ControlCore.cpp [hunk 7]
```diff
@@ -434,7 +445,10 @@ namespace winrt::Microsoft::Terminal::Control::implementation
     // - <none>
     void ControlCore::_sendInputToConnection(std::wstring_view wstr)
     {
-        _connection.WriteInput(winrt_wstring_to_array_view(wstr));
+        if (_connection)
```
[the remark this answers is not in the document]
Comment (lhecker) [reply src/cascadia/TerminalControl/ControlCore.cpp:448]: No, it won't. likely/unlikely rarely make a difference, but if they do it's primarily in tight code.

File: src/renderer/base/renderer.cpp (hunk 6 above)
Comment (lhecker) [reply src/renderer/base/renderer.cpp:94]: It's way safer if this function simply signals the end of painting to the renderer. This reminds me that I didn't test this, shame on me.

**Comment by lhecker** [comment]
I have good news: this PR fixes another bug where restarting a connection would fail to terminate the previous one. (It would leak the connection by not calling Close on it, since it is unfortunately self-referential.)

Regarding why all this is necessary: I realized during development that the entire logic around `_hPaintCompletedEvent` in the RenderThread is flawed as it doesn't actually reliably protect against another frame being scheduled. This rewrite fixes the issue which prevents random AVs during shutdown.
…hopefully without any regressions though.

**Review by DHowett — APPROVED** [review]
