### PR TITLE
Fix `focusFollowMouse`

### LINKED ISSUE #15412: Application crashes when focusFollowMouse is enabled
### Windows Terminal version

1.18.1421.0

### Windows build number

22621.1344

### Other Software

WSL
FarManager

### Steps to reproduce

Open profile entry.

### Expected Behavior

Open screen of application.

### Actual Behavior

WindowsTermninal application aborted with error:

Faulting application name: WindowsTerminal.exe, version: 1.18.2305.22001, time stamp: 0x646c16cf
Faulting module name: ucrtbase.dll, version: 10.0.22621.608, time stamp: 0xf5fc15a3
Exception code: 0xc0000409
Fault offset: 0x000000000007f61e
Faulting process id: 0x0xEB4
Faulting application start time: 0x0x1D98DEF4ED2D0CD
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.18.1421.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: d5f35825-bb26-459f-91ef-20e1e8e5c9cc
Faulting package full name: Microsoft.WindowsTerminalPreview_1.18.1421.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

--------------------------------------

Fault bucket , type 0
Event Name: MoBEX
Response: Not available
Cab Id: 0

Problem signature:
P1: Microsoft.WindowsTerminalPreview_1.18.1421.0_x64__8wekyb3d8bbwe
P2: praid:App
P3: 1.18.2305.22001
P4: 646c16cf
P5: ucrtbase.dll
P6: 10.0.22621.608
P7: f5fc15a3
P8: 000000000007f61e
P9: c0000409
P10: 0000000000000007

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Microsoft.Window_c2d345a83ebd4f63f65431ce4b20f769d6644d_03f0cf04_e1e6e590-85ca-4740-a653-a1e60ec30e78

Analysis symbol: 
Rechecking for solution: 0
Report Id: d5f35825-bb26-459f-91ef-20e1e8e5c9cc
Report Status: 4100
Hashed bucket: 
Cab Guid: 0

---------------------------

Fault bucket 1525387907268971424, type 5
Event Name: MoBEX
Response: Not available
Cab Id: 0

Problem signature:
P1: Microsoft.WindowsTerminalPreview_1.18.1421.0_x64__8wekyb3d8bbwe
P2: praid:App
P3: 1.18.2305.22001
P4: 646c16cf
P5: ucrtbase.dll
P6: 10.0.22621.608
P7: f5fc15a3
P8: 000000000007f61e
P9: c0000409
P10: 0000000000000007

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.86404f2d-8a99-494e-9315-eeb0acc11a2a.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Microsoft.Window_c2d345a83ebd4f63f65431ce4b20f769d6644d_03f0cf04_e1e6e590-85ca-4740-a653-a1e60ec30e78

Analysis symbol: 
Rechecking for solution: 0
Report Id: d5f35825-bb26-459f-91ef-20e1e8e5c9cc
Report Status: 268439552
Hashed bucket: 48cb60da2fa68c80e52b443845718ba0
Cab Guid: 0

### PR DESCRIPTION
**Pull request by zadjii-msft**
Because this looks like it's entirely broken in `main`, and possibly in 1.17(?)

We didn't take a strong ref to the coroutine parameter. As to be expected, that explodes. 

Closes #15412

### CODE REVIEW

File: src/cascadia/TerminalApp/TerminalTab.cpp [hunk 1]
```diff
@@ -907,64 +907,77 @@ namespace winrt::TerminalApp::implementation
...
-        });
+        _controlEvents[paneId] = events;
+    }
 
-        events.focusToken = control.FocusFollowMouseRequested([dispatcher, weakThis](auto&& sender, auto&&) -> winrt::fire_and_forget {
-            co_await wil::resume_foreground(dispatcher);
-            if (const auto tab{ weakThis.get() })
+    winrt::fire_and_forget TerminalTab::_controlTitleChanged(Windows::Foundation::IInspectable sender, Microsoft::Terminal::Control::TitleChangedEventArgs e)
+    {
+        auto weakThis{ get_weak() };
```
Comment (zadjii-msft) [inline src/cascadia/TerminalApp/TerminalTab.cpp:923]: @lhecker you have any clever ideas on how to like, do this with some sort of smart template? Like, I want to just say 

```
events.titleToken = control.TitleChanged(til::OnForeground{ get_weak(), TabViewItem().Dispatcher(), &TerminalTab::_controlTitleChanged });
```

But methinks that wouldn't work, cause I'd have to keep the `til::OnForeground` somewhere to keep the inner function pointer alive.

Comment (lhecker) [reply src/cascadia/TerminalApp/TerminalTab.cpp:923]: A `til::OnForeground` struct would look very similar btw. Like this basically (pseudocode):
```cpp
template<typename Weak, typename Func>
struct OnForeground {
    OnForeground(Weak weak, CoreDispatcher dispatcher, Func func) :
        _weak{ std::move(weak) },
        _dispatcher{ std::move(dispatcher) },
        _func{ std::move(func) }
    {}

    void operator()(auto sender, auto&&) const -> winrt::fire_and_forget
    {
        co_await wil::resume_foreground(dispatcher);

        if (const auto strong = _weak.get())
        {
            if constexpr (std::is_invocable_v<decltype(func), decltype(strong), decltype(sender)>)
            {
                (strong.get()->*_func)(sender);
            }
            else
            {
                (strong.get()->*_func)();
            }
        }
    }

private:
    Weak _weak;
    CoreDispatcher _dispatcher;
    Func _func;
};
```

This is basically identical to what the compiler generators for the "generator" lambdas. It has the same downsides too. It's a bit like a `std::mem_fn`, whose use is equally discouraged, because all these wrappers use dynamic dispatch for `func`, whereas the lambdas use static dispatch.

**Comment by DHowett** [comment]
I don't understand totally - what state is this change in? I would love to merge in a very surgical fix for 1.17.

**Comment by DHowett** [comment]
(I am also cool with this fix if it isn't exactly _surgical_ and just pulls things out into member functions. As long as it can be backported cleanly.)

**Review by DHowett — APPROVED** [review]
YIKES THAT IS SUBTLE

To be clear: i am 100% okay with your bigger fix, I just wanted to make sure it didn't have any unintended side effects that would be hard to review.

Do you want to bring that one in to main in a different PR?

**Review by lhecker — APPROVED** [review]
