### PR TITLE
Pass the window root to the profile page views, instead of the view model

### LINKED ISSUE #14808: SUI "Browse..." button crashes
### Windows Terminal version

1.17.1023

### Windows build number

25294.1001

### Other Software

_No response_

### Steps to reproduce

1. open WT
2. Open SUI
3. Click PowerShell profile
4. Open "Starting directory"
5. Click "Browse..."

### Expected Behavior

Not a crash

### Actual Behavior

Crash

### PR DESCRIPTION
**Pull request by PankajBhojwani**
## Summary of the Pull Request
Let the profile pages' views have access to the window root, rather than the `ProfileViewModel`. The window root is passed along when the page is navigated to.

## Validation Steps Performed
Clicking `Browse` no longer crashes.

## PR Checklist
- [x] Closes #14808

### CODE REVIEW

File: src/cascadia/TerminalSettingsEditor/ProfileViewModel.cpp [hunk 1]
```diff
@@ -352,6 +352,7 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
 
     void ProfileViewModel::SetupAppearances(Windows::Foundation::Collections::IObservableVector<Editor::ColorSchemeViewModel> schemesList, Editor::IHostedInWindow windowRoot)
```
Comment (PankajBhojwani) [inline src/cascadia/TerminalSettingsEditor/ProfileViewModel.cpp:353]: Do we want to rename this to something like `SetupHelper` or something since it technically isn't _just_ setting up the appearances anymore? I don't feel too strongly about it

Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/ProfileViewModel.cpp:353]: If you're going to call it from outside the class, `Helper` is not a good name.

For consideration: a hosting window might reasonably be considered part of the _view_ moreso than part of the view model. Can we just pass it in when the view is created? It doesn't change over time, and does not have any xaml bound to it.

Comment (PankajBhojwani) [reply src/cascadia/TerminalSettingsEditor/ProfileViewModel.cpp]: Makes sense! Made the changes

File: src/cascadia/TerminalSettingsEditor/ProfileViewModel.idl [hunk 2]
```diff
@@ -14,6 +14,12 @@ import "ColorSchemesPageViewModel.idl";
 
 namespace Microsoft.Terminal.Settings.Editor
 {
+	runtimeclass NavigateToProfileArgs
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/ProfileViewModel.idl:17]: nit: spacing

**Review by carlos-zamora — APPROVED** [review]

**Review by DHowett — APPROVED** [review]
