### PR TITLE
[wpf] Add UIA events

### LINKED ISSUE #12642: Terminal WPF control doesn't support screen readers
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.19043.0

### Other Software

Microsoft Visual Studio 2019 and 2022

### Steps to reproduce

1. Turn on Narrator or any other screen reader
2. Open the WPF Control Test project under the Terminal repo
3. Write any command and press enter

### Expected Behavior

Screen readers read the console output

### Actual Behavior

Screen readers ignore the output and only read the written letters

### PR DESCRIPTION
**Pull request by carlos-zamora**
Adds UIA events to the WPF control for the following items:
- selection changed
- text changed (and output)
- cursor changed

### Automation Peer
Similar to the architecture of the UWP TermControl, we added a
`HwndTerminalAutomationPeer` which acts as the
`TermControlAutomationPeer` in UWP. However, we don't need a XAML
wrapper here, so really we just need it to inherit from
`TermControlUiaProvider` (the `ITextProvider` implementation shared
across conhost and WT) and `IUiaEventDispatcher` (the event dispatching
interface that is responsible for signaling the screen reader that
something has changed).

### Removing the local echo
As with WT, we need to record key events to remove the local echo. These
recorded events are matched up with the output text. Each sequential
match is removed in the output text so that it's not read by the screen
reader.

### Detecting what to send events for
As with WT, a `UiaEngine` was added to the renderer and it is set up
when a UIA client is detected. WT would normally stop sending events
when focus was lost from the control. We do the same here.

### Automation properties
`TermControlUiaProvider` was upgraded to support property values. Such
properties include class name and control type. These align with those
set in `TermControlAutomationPeer`. Realistically, those should point to
these, but that requires a lot more work and a localization burden
(because we need to move the localized word "terminal").

`HwndTerminalAutomationPeer` takes this a step further and overrides the
class name to be `WPFTermControl`. This allows screen readers to provide
special handling for the `WPFTermControl` vs the UWP term control since
they will be updating at different speeds.

### Build fixes
To build the WPF test app, I had to mess with the dependencies a little
bit. Really just add the atlas engine and uia renderer to the build
steps.

### HwndTerminal initialization
The initialization order with `WM_NCCREATE` was changed to match that of
Windows Terminal (BaseWindow/IslandWindow). This is safer now. I also
removed the `static` window because it was unnecessary.

### Handling `WM_GETOBJECT`
WPF's HwndHost likes to mark the `WM_GETOBJECT` message as handled to
force the usage of the WPF automation peer. We now explicitly mark it as
not handled and don't return an automation peer. This forces the message
to go down to the HwndTerminal where we return terminal's UiaProvider.

### Remove TermControl layer from UIA tree
TermContol (the top-most layer in the UIA tree) would pop up and not do
anything. This PR also overrides the automation peer at that layer and
marks IsContentElement/IsControlElement=false (the equivalent to
AccessibilityView=Raw). This makes the layer only appear in the UIA tree
if you are using the raw view (i.e. you know what you're doing and you
want to see each individual layer even if you can't directly interact
with it).

## Validation Steps Performed
Tested with Narrator/NVDA using WpfTerminalTestNetCore project in our
repo.
- [X] New output is read out (not just key events, but also other output
  text)
- [X] Local echo does not occur (i.e. pressing 'A' should only read 'A'
  once, not twice [key event and rendered letter]).
- [X] selection events are read out properly
- [X] cursor change events are read out properly (tested with text
  cursor indicator preview in Settings App > Accessibility > Text
  Cursor)

NOTE: test this with Release builds. Debug builds may be too slow and
not read out properly

Closes #12642

### CODE REVIEW

File: src/cascadia/PublicTerminalCore/HwndTerminalAutomationPeer.cpp [hunk 1]
```diff
@@ -0,0 +1,133 @@
...
+void HwndTerminalAutomationPeer::RecordKeyEvent(const WORD vkey)
+{
+    if (const auto charCode{ MapVirtualKey(vkey, MAPVK_VK_TO_CHAR) })
+    {
+        if (const auto keyEventChar{ gsl::narrow_cast<wchar_t>(charCode) }; IsReadable({ &keyEventChar, 1 }))
+        {
+            _keyEvents.emplace_back(keyEventChar);
+        }
+    }
+}
```
Comment (carlos-zamora) [inline src/cascadia/PublicTerminalCore/HwndTerminalAutomationPeer.cpp:60]: This is duplicated in the TermControlAutomationPeer. I think I'll move it over to the IUiaEventDispatcher so that it doesn't have to be duplicated

File: src/cascadia/PublicTerminalCore/HwndTerminalAutomationPeer.cpp [hunk 2]
```diff
@@ -0,0 +1,133 @@
...
+    }
+
+    // Suppress event if the remaining text is not readable
+    if (!IsReadable(sanitized))
+    {
+        return;
+    }
+
+    const auto sanitizedBstr = SysAllocString(sanitized.c_str());
+    static auto activityId = SysAllocString(L"TerminalTextOutput");
```
Comment (carlos-zamora) [inline src/cascadia/PublicTerminalCore/HwndTerminalAutomationPeer.cpp:131]: This is all copied over too, so I'll probably add a helper function that does just this.

File: src/cascadia/PublicTerminalCore/HwndTerminalAutomationPeer.hpp [hunk 3]
```diff
@@ -0,0 +1,46 @@
...
+  to support both automation tests and accessibility (screen
+  reading) applications. This mainly interacts with ScreenInfoUiaProvider
+  to allow for shared code between ConHost and Windows Terminal
+  accessibility providers.
+- Based on the Custom Automation Peers guide on msdn
+  (https://docs.microsoft.com/en-us/windows/uwp/design/accessibility/custom-automation-peers)
+- Wraps the UIAutomationCore ITextProvider
+  (https://docs.microsoft.com/en-us/windows/win32/api/uiautomationcore/nn-uiautomationcore-itextprovider)
+  with a XAML ITextProvider
+  (https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.automation.provider.itextprovider)
```
Comment (carlos-zamora) [inline src/cascadia/PublicTerminalCore/HwndTerminalAutomationPeer.hpp:19]: Nope. Delete

File: src/cascadia/PublicTerminalCore/HwndTerminalAutomationPeer.hpp [hunk 4]
```diff
@@ -0,0 +1,46 @@
+/*++
+Copyright (c) Microsoft Corporation
+Licensed under the MIT license.
+
+Module Name:
+- HwndTerminalAutomationPeer.hpp
+
+Abstract:
+- This module provides UI Automation access to the TermControl
```
Comment (carlos-zamora) [inline src/cascadia/PublicTerminalCore/HwndTerminalAutomationPeer.hpp:9]: nit: TermControl --> HwndTerminal

File: src/cascadia/PublicTerminalCore/HwndTerminalAutomationPeer.hpp [hunk 5]
```diff
@@ -0,0 +1,46 @@
...
+#include "../types/TermControlUiaProvider.hpp"
+#include "../types/IUiaEventDispatcher.h"
+#include "../types/IControlAccessibilityInfo.h"
+
+class HwndTerminalAutomationPeer :
+    public ::Microsoft::Console::Types::IUiaEventDispatcher,
+    public ::Microsoft::Terminal::TermControlUiaProvider
+{
+public:
+    void RecordKeyEvent(const WORD vkey);
```
Comment (carlos-zamora) [inline src/cascadia/PublicTerminalCore/HwndTerminalAutomationPeer.hpp:36]: similar to the cpp feedback, I should move this to the IUiaEventDispatcher so that we don't have it duplicated

File: src/cascadia/PublicTerminalCore/HwndTerminal.cpp [hunk 6]
```diff
@@ -725,6 +724,10 @@ try
     {
         modifiers |= ControlKeyStates::EnhancedKey;
     }
+    if (vkey && keyDown && _uiaProviderInitialized)
```
Comment (carlos-zamora) [inline src/cascadia/PublicTerminalCore/HwndTerminal.cpp:727]: Considering doing a quick replacement of `_uiaProviderInitialized` --> `_uiaProvider` null check. Should accomplish the same thing.

File: src/cascadia/PublicTerminalCore/HwndTerminalAutomationPeer.cpp (hunk 1 above)
Comment (DHowett) [reply src/cascadia/PublicTerminalCore/HwndTerminalAutomationPeer.cpp:60]: But that's an interface. I don't think we should do that. Duplicate the code for now, fix later.

File: src/cascadia/PublicTerminalCore/HwndTerminalAutomationPeer.cpp (hunk 2 above)
Comment (DHowett) [reply src/cascadia/PublicTerminalCore/HwndTerminalAutomationPeer.cpp:131]: Just duplicate it for now. :)

File: src/cascadia/PublicTerminalCore/HwndTerminalAutomationPeer.hpp (hunk 5 above)
Comment (DHowett) [reply src/cascadia/PublicTerminalCore/HwndTerminalAutomationPeer.hpp:36]: Don't bother

**Comment by codeofdusk** [comment]
Does this new control use the same UIA class name? How can I test it?

File: src/types/TermControlUiaProvider.cpp [hunk 7]
```diff
@@ -19,6 +19,56 @@ HRESULT TermControlUiaProvider::RuntimeClassInitialize(_In_ ::Microsoft::Console
...
+IFACEMETHODIMP TermControlUiaProvider::GetPropertyValue(_In_ PROPERTYID propertyId,
+                                                        _Out_ VARIANT* pVariant) noexcept
+{
+    pVariant->vt = VT_EMPTY;
+
+    // Returning the default will leave the property as the default
+    // so we only really need to touch it for the properties we want to implement
+    if (propertyId == UIA_ClassNamePropertyId)
+    {
+        pVariant->bstrVal = SysAllocString(L"TermControl");
```
Comment (codeofdusk) [inline src/types/TermControlUiaProvider.cpp:33]:
```suggestion
        pVariant->bstrVal = SysAllocString(L"WPFTermControl");

```

Comment (carlos-zamora) [reply src/types/TermControlUiaProvider.cpp:33]: Applied the fix to the right place

File: src/cascadia/PublicTerminalCore/HwndTerminal.cpp [hunk 8]
```diff
@@ -725,6 +711,10 @@ try
     {
         modifiers |= ControlKeyStates::EnhancedKey;
     }
+    if (vkey && keyDown && _uiaProvider)
```
Comment (lhecker) [inline src/cascadia/PublicTerminalCore/HwndTerminal.cpp:714]: Can there be `_SendKeyEvent`s without `vkey`?

File: src/cascadia/PublicTerminalCore/HwndTerminal.cpp [hunk 9]
```diff
@@ -54,6 +50,17 @@ LRESULT CALLBACK HwndTerminal::HwndTerminalWndProc(
     LPARAM lParam) noexcept
 try
 {
+    if (WM_NCCREATE == uMsg)
+    {
+#pragma warning(suppress : 26490) // Win32 APIs can only store void*, have to use reinterpret_cast
+        auto cs = reinterpret_cast<CREATESTRUCT*>(lParam);
```
Comment (lhecker) [inline src/cascadia/PublicTerminalCore/HwndTerminal.cpp:56]: BTW you can now use `std::bit_cast` for this. But it's not particularly important.

File: src/cascadia/PublicTerminalCore/HwndTerminalAutomationPeer.cpp [hunk 10]
```diff
@@ -0,0 +1,159 @@
...
+    // that is just the keypress the user made
+    auto sanitized{ Sanitize(newOutput) };
+    while (!_keyEvents.empty() && IsReadable(sanitized))
+    {
+        if (til::toupper_ascii(sanitized.front()) == _keyEvents.front())
+        {
+            // the key event's character (i.e. the "A" key) matches
+            // the output character (i.e. "a" or "A" text).
+            // We can assume that the output character resulted from
+            // the pressed key, so we can ignore it.
```
Comment (lhecker) [inline src/cascadia/PublicTerminalCore/HwndTerminalAutomationPeer.cpp:136]: There's no way this works with Unicode, right? ._.

File: src/types/TermControlUiaProvider.cpp [hunk 11]
```diff
@@ -19,6 +19,56 @@ HRESULT TermControlUiaProvider::RuntimeClassInitialize(_In_ ::Microsoft::Console
...
+// Implementation of IRawElementProviderSimple::get_PropertyValue.
+// Gets custom properties.
+IFACEMETHODIMP TermControlUiaProvider::GetPropertyValue(_In_ PROPERTYID propertyId,
+                                                        _Out_ VARIANT* pVariant) noexcept
+{
+    pVariant->vt = VT_EMPTY;
+
+    // Returning the default will leave the property as the default
+    // so we only really need to touch it for the properties we want to implement
+    if (propertyId == UIA_ClassNamePropertyId)
```
Comment (lhecker) [inline src/types/TermControlUiaProvider.cpp:31]: You could make this a switch statement for better readability.

**Review by lhecker — APPROVED** [review]

File: src/cascadia/PublicTerminalCore/HwndTerminal.cpp [hunk 12]
```diff
@@ -324,14 +328,15 @@ IRawElementProviderSimple* HwndTerminal::_GetUiaProvider() noexcept
...
-    if (!_uiaProviderInitialized)
+    if (!_uiaProvider)
     {
         try
         {
             auto lock = _terminal->LockForWriting();
-            LOG_IF_FAILED(::Microsoft::WRL::MakeAndInitialize<::Microsoft::Terminal::TermControlUiaProvider>(&_uiaProvider, this->GetUiaData(), this));
-            _uiaProviderInitialized = true;
+            LOG_IF_FAILED(::Microsoft::WRL::MakeAndInitialize<HwndTerminalAutomationPeer>(&_uiaProvider, this->GetUiaData(), this));
+            _uiaEngine = std::make_unique<::Microsoft::Console::Render::UiaEngine>(_uiaProvider.Get()); // TODO CARLOS: fix circular ref
```
Comment (DHowett) [inline src/cascadia/PublicTerminalCore/HwndTerminal.cpp:337]: circular ref -- OK? memory leak?

File: src/cascadia/PublicTerminalCore/HwndTerminal.cpp [hunk 13]
```diff
@@ -380,29 +385,10 @@ void HwndTerminal::SendOutput(std::wstring_view data)
...
-        0,
-        0,
-        0,
-        0,
-        parentHwnd,
-        nullptr,
-        nullptr,
-        nullptr);
-    auto _terminal = std::make_unique<HwndTerminal>(_hostWindow);
+    auto _terminal = std::make_unique<HwndTerminal>(/*_hostWindow*/ parentHwnd);
```
Comment (DHowett) [inline src/cascadia/PublicTerminalCore/HwndTerminal.cpp:388]: comment not required

File: src/cascadia/PublicTerminalCore/HwndTerminal.cpp (hunk 8 above)
Comment (carlos-zamora) [reply src/cascadia/PublicTerminalCore/HwndTerminal.cpp:714]: Traced all the way to `TerminalContainer.cs`:
`private IntPtr TerminalContainer_MessageHook(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)`

`wParam` gets converted to the vkey. I assume vkey can't be null? But I guess it doesn't hurt

File: src/cascadia/PublicTerminalCore/HwndTerminalAutomationPeer.cpp (hunk 10 above)
Comment (carlos-zamora) [reply src/cascadia/PublicTerminalCore/HwndTerminalAutomationPeer.cpp:136]: Probably not, but that should be fine. We're really just using this to suppress key events. So, when you press the <kbd>A</kbd> key, normally you'd hear "A" from pressing the key and "A" from rendering the key. If we suppress that second event, it sounds/feels more natural.

File: src/cascadia/PublicTerminalCore/HwndTerminalAutomationPeer.cpp [hunk 14]
```diff
@@ -0,0 +1,159 @@
...
+        pVariant->bstrVal = SysAllocString(L"WPFTermControl");
+        if (pVariant->bstrVal != nullptr)
+        {
+            pVariant->vt = VT_BSTR;
+        }
+    }
+    else
+    {
+        // fall back to shared implementation
+        TermControlUiaProvider::GetPropertyValue(propertyId, pVariant);
```
Comment (DHowett) [inline src/cascadia/PublicTerminalCore/HwndTerminalAutomationPeer.cpp:83]: we may need to `return` the parent's GetPropertyValue, right?

File: src/cascadia/PublicTerminalCore/HwndTerminalAutomationPeer.cpp [hunk 15]
```diff
@@ -0,0 +1,159 @@
...
+    }
+
+    // Suppress event if the remaining text is not readable
+    if (!IsReadable(sanitized))
+    {
+        return;
+    }
+
+    const auto sanitizedBstr = SysAllocString(sanitized.c_str());
+    static auto activityId = SysAllocString(L"TerminalTextOutput");
```
Comment (DHowett) [inline src/cascadia/PublicTerminalCore/HwndTerminalAutomationPeer.cpp:157]: we might be leaking these -- can you confirm whether UiaRaise takes ownership? I bet it doesn't.

Should use `wil::unique_bstr`

File: src/cascadia/WpfTerminalControl/TerminalContainer.cs [hunk 16]
```diff
@@ -52,6 +53,24 @@ public TerminalContainer()
             }
         }
 
+        /// <inheritdoc/>
+        protected override IntPtr WndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
```
Comment (DHowett) [inline src/cascadia/WpfTerminalControl/TerminalContainer.cs:57]: worth copying your comment from the PR body in here

File: src/cascadia/PublicTerminalCore/HwndTerminalAutomationPeer.cpp (hunk 15 above)
Comment (DHowett) [reply src/cascadia/PublicTerminalCore/HwndTerminalAutomationPeer.cpp:157]: i believe the ones in the Variants ARE accounted for, and you do not need to delete them or use unique_bstr on them.

**Review by DHowett — CHANGES_REQUESTED** [review]
memory questions!

File: src/cascadia/PublicTerminalCore/HwndTerminalAutomationPeer.cpp (hunk 14 above)
Comment (carlos-zamora) [reply src/cascadia/PublicTerminalCore/HwndTerminalAutomationPeer.cpp:83]: Fair enough. It's always S_OK though haha.

File: src/cascadia/PublicTerminalCore/HwndTerminal.cpp (hunk 12 above)
Comment (carlos-zamora) [reply src/cascadia/PublicTerminalCore/HwndTerminal.cpp:337]: I think this was left over from an earlier iteration. Should be good. We have a `unique_ptr<UiaEngine>` pointing to a `ComPtr<HwndTerminalAP>`. But that `HwndTerminalAP` doesn't point back.

File: src/cascadia/PublicTerminalCore/HwndTerminalAutomationPeer.cpp [hunk 17]
```diff
@@ -153,7 +153,7 @@ void HwndTerminalAutomationPeer::NotifyNewOutput(std::wstring_view newOutput)
         return;
     }
 
-    const auto sanitizedBstr = SysAllocString(sanitized.c_str());
-    static auto activityId = SysAllocString(L"TerminalTextOutput");
-    LOG_IF_FAILED(UiaRaiseNotificationEvent(this, NotificationKind_ActionCompleted, NotificationProcessing_All, sanitizedBstr, activityId));
+    const auto sanitizedBstr = wil::unique_bstr(sanitized.c_str());
+    static auto activityId = wil::unique_bstr(L"TerminalTextOutput");
```
Comment (DHowett) [inline src/cascadia/PublicTerminalCore/HwndTerminalAutomationPeer.cpp:157]: ah, this is a bit of a weirdness.

I don't know if this is a legal way to create a unique_bstr.

Try using `wil::make_bstr_nothrow()` instead!

**Review by DHowett — APPROVED** [review]
