### PR TITLE
Fix unbinding keys in v0.10

### LINKED ISSUE #3729: Alt arrow keys do nothing; key unbinding broken?
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version:  0.7.3291.0

Any other software?
- Ubuntu 16.04.3 LTS
- byobu version 5.106
- tmux 2.1
```
# Note

This issue is a follow-on to #3101.  In that issue superfluous keys were being generated.  Now it appears no keys are being generated.  Alt arrows are dead to me.

# Steps to reproduce

- Start Byobu:  byobu
- Create a new Byobu tab:  F2
- Press alt left or alt right to switch between the tabs

# Expected behavior

Byobu switches between the two tabs.

# Actual behavior

Nothing happens.

### PR DESCRIPTION
**Pull request by zadjii-msft**
## Summary of the Pull Request

We (the royal "we") broke key unbinding in #4746. We didn't run the local tests after this, which actually would have caught this. The comment even suggests what we should have done here. We need to make sure that when we bail, it's because there's a parsing function that returned nothing. `null`, `"unbound"`, etc actually don't even have a parsing function at all, so they should just keep on keepin' on.

## References

Source of this regression: #4746

## PR Checklist
* [x] Closes #3729
* [x] I work here
* [x] Tests added/passed
* [n/a] Requires documentation to be updated

## Detailed Description of the Pull Request / Additional comments

This is a great example of why your unittests should run in CI always

## Validation Steps Performed
* **ran the tests**
* tested the following unbindings:

```json
        { "command": null, "keys": [ "ctrl+shift+t" ] },
        { "command": "unbound", "keys": [ "ctrl+shift+t" ] },
        { "command": "null", "keys": [ "ctrl+shift+t" ] },

```
and they each individually worked.

### CODE REVIEW

**Comment by int3l** [comment]
I am looking in the code and I can't find a workaround for the issue. I just updated and all my unbound bindings are broken. Is there a temp solution for this until the this PR lands in future build?

**Comment by zadjii-msft** [comment]
I don't think there's a workaround for the moment unfortunately. I'd bet good money that this PR gets merged and hotfix build pushed out ASAP (when the rest of the team wakes up 😜)

**Comment by int3l** [comment]
Welp, I guess I will wait for the next update then :) Thanks for the quick response.

**Comment by DHowett-MSFT** [comment]
When you merge this one please do it manually: the bot has trouble with the title when there’s only a single commit in the pull request. It uses the commit title instead of the pr

File: src/cascadia/TerminalApp/AppKeyBindingsSerialization.cpp [hunk 1]
```diff
@@ -516,7 +516,7 @@ std::vector<::TerminalApp::SettingsLoadWarnings> winrt::TerminalApp::implementat
                 warnings.insert(warnings.end(), parseWarnings.begin(), parseWarnings.end());
 
                 // if an arg parser was registered, but failed, bail
-                if (args == nullptr)
+                if (pfn && args == nullptr)
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalApp/AppKeyBindingsSerialization.cpp]: I’m surprised we are getting in here, though. Don’t we drop out because there isn’t a deserializer registered for null or unbound?

Comment (DHowett-MSFT) [reply src/cascadia/TerminalApp/AppKeyBindingsSerialization.cpp]: Should we just put this _all_ under “if pfn” and move on? After all, there are no warnings if there’s no pfn..

Comment (zadjii-msft) [reply src/cascadia/TerminalApp/AppKeyBindingsSerialization.cpp]: there's actually an explicit `nullptr` deserializer registered for "unbound"

**Comment by ondras** [comment]
Is there an ETA for a release of this particular fix? Terminal is kinda unusable for me since 0.10 ...

**Comment by Zenexer** [comment]
This is probably a good time to mention that many of the default keybindings interfere with popular Linux applications, which I find odd given the emphasis on support of WSL.  This regression probably wouldn't be such an impediment if key combinations that send unique ANSI codes were avoided in keybindings.

Is this an area where you'd be open to feedback in a new issue?  I may be able to provide some advice as to what's safe and what isn't.  I don't think there's really any authoritative or complete documentation floating around on the internet, unfortunately.

**Comment by zadjii-msft** [comment]
@ondras It should be coming out soon<sup>tm</sup>, whenever the store gets around to pushing packages out.

<hr> 

@Zenexer I'd say _this pull request_ is not the place for that discussion. I'd recommend filing a new issue for that discussion.

**Comment by Zenexer** [comment]
@zadjii-msft Thanks; I was just asking whether it'd even be worth filing an issue.  I'll do some research and open one.

@ondras If you don't want to wait for the store, an installer that includes this was just released on GitHub: https://github.com/microsoft/terminal/releases

**Comment by DHowett-MSFT** [comment]
That build is also available in the store as of 8:00 PDT. :)
