### PR TITLE
Also remember to persist window positions

### LINKED ISSUE #17010: [1.21 canary] Session restore is restoring to the wrong screen coordinates and window size
Seems like we're off by a DPI scaling factor somewhere?

image

`settings`

```json
    "firstWindowPreference": "persistedWindowLayout",
    "initialCols": 80,
    "initialPosition": "-128,383",
    "initialRows": 24,
    "launchMode": "default",
```

`state`:

```json
	"persistedWindowLayouts" : 
	[
		{
			"initialSize" : 
			{
				"height" : 896.0,
				"width" : 1407.0
			},
			"launchMode" : "default",
			"tabLayout" : 
```

oops no `initialPosition`

### PR DESCRIPTION
**Pull request by zadjii-msft**
This got lost in #16598. `TerminalPage` needs to ask the window where the it actually is, so it can persist it. More details in https://github.com/microsoft/terminal/pull/16598#discussion_r1511519304

Closes #17010

### CODE REVIEW

File: src/cascadia/TerminalApp/TerminalPage.cpp [hunk 1]
```diff
@@ -1952,6 +1953,12 @@ namespace winrt::TerminalApp::implementation
 
         layout.InitialSize(windowSize);
 
+        // We don't actually know our own position. So we have to ask the window
+        // layer for that.
+        const auto launchPosRequest{ winrt::make<LaunchPositionRequest>() };
+        RequestLaunchPosition.raise(*this, launchPosRequest);
+        layout.InitialPosition(launchPosRequest.Position());
```
Comment (lhecker) [inline src/cascadia/TerminalApp/TerminalPage.cpp:1960]: BTW as I mentioned briefly in #12633 we should probably use `GetWindowPlacement` here. It only needs the `HWND` which the `TerminalPage` already knows about. The struct could then be serialized to a JSON object. It even got `WPF_ASYNCWINDOWPLACEMENT` which may be useful for us: https://learn.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-windowplacement

**Review by lhecker — APPROVED** [review]

File: src/cascadia/TerminalApp/TerminalPage.cpp (hunk 1 above)
Comment (zadjii-msft) [reply src/cascadia/TerminalApp/TerminalPage.cpp:1960]: Yes, though, we may also want to be careful about how that plays with focus mode too. Since forever, session restore + fomo has restored at the wrong size, I think wrongly including the size of the tab row. (I cannot for the life of me find that issue though)

**Comment by DHowett** [comment]
Hey, does this apply to #17049 as well?

**Review by carlos-zamora — APPROVED** [review]
