### PR TITLE
Fix conpty not emitting colored spaces on the VERY FIRST frame

### LINKED ISSUE #8341: Spaces added to prompt on shell launch (PowerShell/pwsh)
# Environment

```none
Win32NT 10.0.19042.0 Microsoft Windows NT 10.0.19042.0
Windows Terminal Version: 1.4.3141.0

https://github.com/justjanne/powerline-go

```

# Steps to reproduce

Add the following to your PowerShell $PROFILE (adjust the path to the powerline-go exectuable to your local environment)

```PowerShell
Function global:prompt {
    $pwd = $ExecutionContext.SessionState.Path.CurrentLocation
    $startInfo = New-Object System.Diagnostics.ProcessStartInfo
    $startInfo.FileName = "$ENV:OneDriveConsumer\Util\powerline-go.exe"
    $startInfo.Arguments = "-shell bare"
    $startInfo.Environment["TERM"] = "xterm-256color"
    $startInfo.CreateNoWindow = $true
    $startInfo.StandardOutputEncoding = [System.Text.Encoding]::UTF8
    $startInfo.RedirectStandardOutput = $true
    $startInfo.UseShellExecute = $false
    $startInfo.WorkingDirectory = $pwd
    $process = New-Object System.Diagnostics.Process
    $process.StartInfo = $startInfo
    $process.Start() | Out-Null
    $standardOut = $process.StandardOutput.ReadToEnd()
    $process.WaitForExit()
    $standardOut
}
```

Start a PowerShell (classic) or PowerShell terminal window via Windows Terminal. The first time the prompt function is called there are spaces inserted between the different prompt parts. Pressing `Enter` makes these disappear and the prompt works fine.

If I use the same profile without Windows Terminal launching PowerShell.exe directly it works fine. So I suspect this is related to Windows Terminal.

Here's an animated GIF that shows what is going on:

powerline-spaces

# Expected behavior

I expect to see the prompt formatted correctly as follows:
powerline-go-expected

# Actual behavior

This is what the prompt looks like when the PowerShell is first started:

powerline-go-actual

### PR DESCRIPTION
**Pull request by zadjii-msft**
This bug arose from a "race condition" in the first frame handling of conpty. We'd try to optimize out spaces if we've cleared the entire frame (which always happens on the first frame). However, doing that even for colored spaces meant that things like powerline prompts could be emitted to conhost during the first frame, and we'd optimize the spaces out. That's silly. 

This is hard to repro naturally, but this comment has another repro I used
https://github.com/microsoft/terminal/issues/8341#issuecomment-731310022

Modified to facilitate simpler testing, it looks like:

#### Before
image

#### After
image

* [x] Closes #8341
* [x] Tests added

Co-authored by @DHowett

### CODE REVIEW

**Review by carlos-zamora — APPROVED** [review]

File: src/renderer/vt/paint.cpp [hunk 1]
```diff
@@ -448,10 +448,13 @@ using namespace Microsoft::Console::Types;
     // the lines _wrapped_. It doesn't care to manually break the lines, but if
     // we trimmed the spaces off here, we'd print all the "~"s one after another
     // on the same line.
-    const auto removeSpaces = !lineWrapped && (useEraseChar ||
-                                               _clearedAllThisFrame ||
-                                               (_newBottomLine && printingBottomLine && bgMatched));
-    const auto cchActual = removeSpaces ? nonSpaceLength : cchLine;
+    static const TextAttribute defaultAttrs{};
```
Comment (DHowett) [inline src/renderer/vt/paint.cpp:451]: It has been so long that I can't recall whether I wrote this

File: src/renderer/vt/paint.cpp [hunk 2]
```diff
@@ -448,10 +448,13 @@ using namespace Microsoft::Console::Types;
     // the lines _wrapped_. It doesn't care to manually break the lines, but if
     // we trimmed the spaces off here, we'd print all the "~"s one after another
     // on the same line.
-    const auto removeSpaces = !lineWrapped && (useEraseChar ||
-                                               _clearedAllThisFrame ||
-                                               (_newBottomLine && printingBottomLine && bgMatched));
-    const auto cchActual = removeSpaces ? nonSpaceLength : cchLine;
+    static const TextAttribute defaultAttrs{};
+    const bool removeSpaces = !lineWrapped && (useEraseChar // we determined earlier that ECH is optimal
+                                               || (_clearedAllThisFrame && _lastTextAttributes == defaultAttrs) // OR we cleared the last frame to the default attributes (specifically)
```
Comment (DHowett) [inline src/renderer/vt/paint.cpp:453]: I don't think I ever recommended this on account of its fragility, and I meant to ask @j4james if this seemed ... uh, reasonable?

Sorry, I'm still a bit brain-fogged

**Review by DHowett — APPROVED** [review]

File: src/renderer/vt/paint.cpp (hunk 1 above)
Comment (zadjii-msft) [reply src/renderer/vt/paint.cpp:451]: you had it inline:

* you: aba6caf
* my delta: 1fdd632

File: src/renderer/vt/paint.cpp (hunk 2 above)
Comment (zadjii-msft) [reply src/renderer/vt/paint.cpp:453]: HONESTLY I'm just opening the pr because I was in the area. I tried it for #13229, and it didn't work for that. However, it seemed overall reasonable, so filed this for discussion to get some feedback, mostly from @j4james.

Comment (j4james) [reply src/renderer/vt/paint.cpp:453]: I don't know know the conpty code very well, so I'm unsure if it's guaranteed that `_clearedAllThisFrame` would mean the screen was cleared with the default attributes. Is that correct? It's not possible for conpty to inherit colors from somewhere in the first frame, like maybe when nesting conpty sessions?

But if you're sure the screen was cleared with default attributes, and we're now writing out text with default attributes, then I think that would imply it's safe to remove spaces.

Comment (zadjii-msft) [reply src/renderer/vt/paint.cpp:453]: Looks like the only place `_clearedAllThisFrame = true` is set is in the first paint of `StartPaint`, when yea, the screen was cleared with the defaults. I don't think nesting conpty would change that - even if you did `color 46`, `wsl`, `cmd.exe` in a Terminal cmd instance, that second conpty would spawn with default attrs. 

That sounds good enough to me!

**Comment by DHowett** [comment]
awesome. now just spellbot it!

**Comment by danieldusharm** [comment]
Should the test case include a frame with white space characters? For example a terminal prompt containing a /n
