### PR TITLE
Rebuild the profile nav via MenuItemsSource; mitigate a crash

### LINKED ISSUE #13673: Windows Terminal crashes when emptying settings.json with settings window open
### Windows Terminal version

1.14.1962.0

### Windows build number

10.0.19043.0

### Other Software

N/A

### Steps to reproduce

1. Open Terminal
2. Open Settings
3. Open JSON file
4. In external editor, CTRL+A to select the contents of the settings.json and press delete
5. Save

### Expected Behavior

No crash.

### Actual Behavior

Windows Terminal repopulates the settings.json file with defaults and then crashes with:

```
Unhandled exception at 0x00007FFCE568FB62 (KernelBase.dll) in WindowsTerminal.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x000002CDCB9A0970, 0x000000000000000A).
```

Which is being triggered from `TerminalApp.dll!winrt::TerminalApp::implementation::AppLogic::_ApplyStartupTaskStateChange$_ResumeCoro$1() Line 1004`.

Edit: Feedback Hub URL: https://aka.ms/AAhm2q3

### PR DESCRIPTION
**Pull request by zadjii-msft**
Directly manipulating the `NavigationView::MenuItems` vector is bad. If you do that, you're gonna get crashes, in WinUI code for `Measure`. However, a WinUI PR (below) gave me an idea: Changing `NavigationView::MenuItemsSource` will wholly invalidate the entirety of the nav view items, and that will avoid the crash. 

This code does that. It's a wee bit janky, but it works. 

Closes #13673

_might_ affect #12333, need to try and repro. 

See also:
* #9273
* #10390
* https://github.com/microsoft/microsoft-ui-xaml/issues/6302
* https://github.com/microsoft/microsoft-ui-xaml/pull/3138, which was the fix for https://github.com/microsoft/microsoft-ui-xaml/issues/2818

### CODE REVIEW

File: src/cascadia/TerminalSettingsEditor/MainPage.cpp [hunk 1]
```diff
@@ -555,6 +567,30 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
         menuItems.Append(addProfileItem);
     }
 
+    void MainPage::_SetupNavViewItems()
+    {
+        if (SettingsNav().MenuItemsSource())
+        {
+            // We've already copied over the origina items to a source. Wek can
```
Comment (carlos-zamora) [inline src/cascadia/TerminalSettingsEditor/MainPage.cpp:574]:
```suggestion
            // We've already copied over the original items to a source. We can
```

File: src/cascadia/TerminalSettingsEditor/MainPage.cpp [hunk 2]
```diff
@@ -555,6 +567,30 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
...
+            // just skip this now.
+            return;
+        }
+
+        auto menuItems{ SettingsNav().MenuItems() };
+        // Remove all the existing items, and move them to a separate vector
+        // that we'll use as a MenuItemsSource. By doing this, we avoid a WinUI
+        // bug (MUX#6302) where modifying the NavView.Items() directly causes a
+        // crash. By leaving these static entries in XAML, we maintain the
+        // benefit of istantiating them from the XBF, rather than at runtime.
```
Comment (carlos-zamora) [inline src/cascadia/TerminalSettingsEditor/MainPage.cpp:584]:
```suggestion
        // benefit of instantiating them from the XBF, rather than at runtime.
```

File: src/cascadia/TerminalSettingsEditor/MainPage.cpp [hunk 3]
```diff
@@ -204,7 +213,8 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
         // Couldn't find the selected item, fallback to first menu item
         // This happens when the selected item was a profile which doesn't exist in the new configuration
         // We can use menuItemsSTL here because the only things they miss are profile entries.
-        const auto& firstItem{ menuItemsSTL.at(0).as<MUX::Controls::NavigationViewItem>() };
+        // const auto& firstItem{ menuItemsSTL.at(0).as<MUX::Controls::NavigationViewItem>() };
```
Comment (carlos-zamora) [inline src/cascadia/TerminalSettingsEditor/MainPage.cpp:216]:
```suggestion
```

File: src/cascadia/TerminalSettingsEditor/MainPage.cpp [hunk 4]
```diff
@@ -527,7 +537,9 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
 
     void MainPage::_InitializeProfilesList()
     {
-        const auto menuItems = SettingsNav().MenuItems();
+        const auto menuItems = SettingsNav().MenuItemsSource().try_as<Windows::Foundation::Collections::IVector<IInspectable>>();
+        // if (!menuItems)
+        //     return;
```
Comment (carlos-zamora) [inline src/cascadia/TerminalSettingsEditor/MainPage.cpp:542]:
```suggestion
```

**Review by carlos-zamora — APPROVED** [review]
Sure, if it works, it works haha. The `ReplaceAll()` we were doing was _also_ a workaround so at this point I'll take what I can get :P

File: src/cascadia/TerminalSettingsEditor/MainPage.cpp [hunk 5]
```diff
@@ -527,7 +536,7 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
 
     void MainPage::_InitializeProfilesList()
     {
-        const auto menuItems = SettingsNav().MenuItems();
+        const auto menuItems = SettingsNav().MenuItemsSource().try_as<Windows::Foundation::Collections::IVector<IInspectable>>();
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/MainPage.cpp:539]: This introduces an ordering dependency, right? It seems like there is code that _can_ run before `MenuItemsSource` is set and code that can only run after. Are we clear on what happens here if somehow it's not been set?

File: src/cascadia/TerminalSettingsEditor/MainPage.cpp [hunk 6]
```diff
@@ -555,6 +564,30 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
         menuItems.Append(addProfileItem);
     }
 
+    void MainPage::_SetupNavViewItems()
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/MainPage.cpp:567]: For clarity, I might recommend we be _very specific_ about what this does.

`_moveXAMLParsedNavItemsIntoItemSource`

**Review by DHowett — CHANGES_REQUESTED** [review]

File: src/cascadia/TerminalSettingsEditor/MainPage.cpp (hunk 6 above)
Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/MainPage.cpp:567]: In fact, we should make it a debug assert that it never fires twice

**Review by lhecker — APPROVED** [review]

File: src/cascadia/TerminalSettingsEditor/MainPage.cpp [hunk 7]
```diff
@@ -557,6 +575,36 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
         menuItems.Append(addProfileItem);
     }
 
+    // Does the very wacky business of moving all our MenuItems that we
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/MainPage.cpp:578]:
```suggestion
    // BODGY
    // Does the very wacky business of moving all our MenuItems that we
```

?

File: src/cascadia/TerminalSettingsEditor/MainPage.cpp [hunk 8]
```diff
@@ -557,6 +575,36 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
         menuItems.Append(addProfileItem);
     }
 
+    // Does the very wacky business of moving all our MenuItems that we
+    // hardcoded in XAML into a runtime MenuItemsSource. We'll then use _that_
+    // MenuItemsSource as the source for our nave view entries instead. This
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/MainPage.cpp:580]:
```suggestion
    // MenuItemsSource as the source for our nav view entries instead. This
```

**Review by DHowett — APPROVED** [review]
