### PR TITLE
Manually replace unqualified cmd, powershell paths for the default profiles

### LINKED ISSUE #12126: When default profile is set to Command Prompt, "Open in Windows Terminal" uses cmd.exe in current folder
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.22526.1000

### Other Software

_No response_

### Steps to reproduce

1. Ensure that cmd.exe from another version of Windows is in the current folder
2. Right-click a black space in Explorer and then click Open in Windows Terminal

### Expected Behavior

Ideally, the system's command prompt should be used as opposed to the one in the current 

### Actual Behavior

The command prompt in the folder is used as opposed to the one from the system

https://user-images.githubusercontent.com/81916167/148704076-bc05a3e8-f018-47e7-bab8-38fceacecd5b.mp4

### PR DESCRIPTION
**Pull request by zadjii-msft**
In previous releases, we had the commandlines for the Command Prompt and PowerShell profiles unqualified, as `cmd.exe` and `powershell.exe`. This was bad - theoretically, that would have preferred the cmd that was in the CWD over the one in System32. Or, something could insert itself into the path, and you'd end up with a malicious `cmd.exe` before the real one.

In #11437, we made sure that the `userDefaults` are initiated with the fully qualified paths. However, that didn't fix the issue for folks who already had settings files.

In an effort to better prevent this kind of badness, if we see a profile _with a default profile guid_, AND the unqualified version of the path, then we'll stealth replace it with the fully qualified one.

* Related to #11437
* [x] fixes #12126
* [x] Tests added

### CODE REVIEW

**Comment by miniksa** [comment]
> if we see a profile with a default profile guid, AND the unqualified version of the path, then we'll stealth replace it with the fully qualified one

Got instantly translated in my head to ["IF YOU SEE SOMETHING, SAY SOMETHING®"](https://www.dhs.gov/see-something-say-something)

**Review by miniksa — APPROVED** [review]

File: src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp [hunk 1]
```diff
@@ -977,3 +977,20 @@ void CascadiaSettings::_resolveDefaultProfile() const
...
 }
+
+void CascadiaSettings::_validateCorrectDefaultShellPaths() const
+{
+    for (auto profile : _allProfiles)
+    {
+        if (profile.Guid() == DEFAULT_COMMAND_PROMPT_GUID &&
+            profile.Commandline() == L"cmd.exe")
+        {
+            profile.Commandline(L"%SystemRoot%\\System32\\cmd.exe");
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp:988]: should we call `ClearCommandline` instead, to reset it to the inherited value? this would be somewhat more ergonomic in the settings UI and somewhat less ergonomic in the JSON, but it won't require us to repeat ourselves in three places with the new commandlines

**Review by DHowett — CHANGES_REQUESTED** [review]
noted

**Review by DHowett — APPROVED** [review]

**Comment by DHowett** [comment]
@msftbot merge this in 18 minutes
