### PR TITLE
Properly manage teardown state in TermControl

### LINKED ISSUE #1198: Tab teardown crashing resulting from renewed renderer destruction order issues
I can reliably crash a release build of WT by just closing tabs.

```
>	TerminalControl.dll!Microsoft::Console::Render::DxEngine::_CreateDeviceResources(const bool) Line 170	C++
 	TerminalControl.dll!Microsoft::Console::Render::DxEngine::StartPaint() Line 692	C++
 	TerminalControl.dll!Microsoft::Console::Render::Renderer::_PaintFrameForEngine(Microsoft::Console::Render::IRenderEngine * const pEngine) Line 90	C++
 	TerminalControl.dll!Microsoft::Console::Render::Renderer::PaintFrame() Line 68	C++
 	[Inline Frame] TerminalControl.dll!Microsoft::Console::Render::RenderThread::_ThreadProc()	C++
 	TerminalControl.dll!Microsoft::Console::Render::RenderThread::s_ThreadProc(void * lpParameter) Line 151	C++
```

Various things under `RenderThread::s_ThreadProc`.

If you ask the `Renderer` what it thinks, it says this:

```
this->_destructing
true
```

However, we're here:

https://github.com/microsoft/terminal/blob/b9d83baaeb149410dc8e520ec829eb891b2087a7/src/renderer/base/renderer.cpp#L59-L71

We passed the `_destructing` check and . . . now we're very sad.

### PR DESCRIPTION
**Pull request by DHowett-MSFT**
## Summary of the Pull Request
This commit introduces a few automatic event revokers and implements staged Close for TermControl's constituent components. It also fixes an issue in reading the title from a tab with no focused control.

Fixes #1198, #1188.

## PR Checklist
* [x] Closes #1198, #1188
* [x] CLA signed
* [x] Tests added/passed/manually tested

## Validation Steps Performed
I've opened and closed a number of tabs at a number of speeds, I can neither get it to crash _nor_ get it to leak console hosts and shells and a bunch of memory.

### CODE REVIEW

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 1]
```diff
@@ -355,30 +355,7 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
...
-
-        if (_renderer)
-        {
-            _renderer->TriggerTeardown();
-        }
-
-        _swapChainPanel = nullptr;
-        _root = nullptr;
-        _connection = nullptr;
+        Close();
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalControl/TermControl.cpp]: I flipped this because _calling the destructor maunally is terrible._

File: src/cascadia/TerminalApp/App.cpp [hunk 2]
```diff
@@ -1036,7 +1036,10 @@ namespace winrt::TerminalApp::implementation
             {
                 try
                 {
-                    return _GetFocusedControl().Title();
+                    if (auto focusedControl{ _GetFocusedControl() })
```
Comment (zadjii-msft) [inline src/cascadia/TerminalApp/App.cpp]: There's a chance there's a similar bug with scrolling using the keyboard, if you want to fold that into this PR

Comment (DHowett-MSFT) [reply src/cascadia/TerminalApp/App.cpp]: I think there are some issues in tying "active control" to "control currently focused in the XAML stack".. what do you think? Should we just holistically fix this all up by making active/focused not the same?

Comment (zadjii-msft) [reply src/cascadia/TerminalApp/App.cpp]: oh that's a great idea

Comment (DHowett-MSFT) [reply src/cascadia/TerminalApp/App.cpp]: Moved to #1205.
