### PR TITLE
Validate cursor position in UIA UTR ctor

### LINKED ISSUE #8730: Windows Terminal (Preview) crashes with wrapped text
❗ N.B. This issue has also been reported via **Feedback Hub link** https://aka.ms/AAa8g4n (video/screenshots have been uploaded; posted 2 months ago, but still no resolution)

# Environment

```none
Windows build number: 10.0.19042.0
Windows Terminal version: 1.5.3242.0

Any other software?
Windows Terminal version: 1.4.3243.0
```

# Steps to reproduce

1. Open new Windows Terminal tab or window (using Windows Powershell in this case)
2. Paste a long text string WITHOUT pressing ENTER. 
    
    For example, this  string (H/T http://powershell-guru.com/): `Get-ChildItem -Path C:\Demo -Filter *.cs | Rename-Item -NewName {[System.IO.Path]::ChangeExtension($_.Name, ".kt")}`

    Any long string of ASCII characters should also reproduce issue: `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX- `

    The text will soft wrap in a standard Windows Terminal configuration (12pt text)

3. Press backspace and begin deleting the text. 

# Expected behavior

The cursor should move up a line. Windows Terminal should not crash.

# Actual behavior

Windows Terminal crashes just before the cursor moves up a line, or in other words, just before the character where the text is wrapped.

_NOTE: This only appears to happen when there is one tab open._

### PR DESCRIPTION
**Pull request by carlos-zamora**
## Summary of the Pull Request
This adds some validation in the `UiaTextRange` ctor for the cursor position.

#8730 was caused by creating a `UiaTextRange` at the cursor position when it was in a delayed state (meaning it's purposefully hanging off of the right edge of the buffer). Normally, `Cursor` maintains a flag to keep track of when that occurs, but Windows Terminal isn't maintaining that properly in `Terminal::WriteBuffer`.

The _correct_ approach would be to fix `WriteBuffer` then leverage that flag for validation in `UiaTextRange`. However, messing with `WriteBuffer` is a little too risky for our comfort right now. So we'll do the second half of that by checking if the cursor position is valid. Since the cursor is really only expected to be out of bounds when it's in that delayed state, we get the same result (just maybe a tad slower than simply checking a flag).

Closes #8730 

Filed #12440 to track changes in `Terminal::_WriteBuffer` for delayed EOL wrap.

## Validation Steps Performed
While using magnifier, input/delete wrapped text in input buffer.

### CODE REVIEW

**Comment by codeofdusk** [comment]
Are there plans to remove the `FailFast` logic in this PR as well?

File: src/types/UiaTextRangeBase.cpp [hunk 1]
```diff
@@ -44,7 +44,15 @@ try
...
     RETURN_IF_FAILED(RuntimeClassInitialize(pData, pProvider, wordDelimiters));
 
+    // GH#8730: The cursor position may be in a delayed state, resulting in it being out of bounds.
+    // If that's the case, clamp it to be within bounds.
+    // TODO GH#XXXX: We should be able to just check some fields off of the Cursor object,
+    // but Windows Terminal isn't updating those flags properly.
     _start = cursor.GetPosition();
+    if (const auto bufferSize{ pData->GetTextBuffer().GetSize() }; !bufferSize.IsInBounds(_start))
+    {
+        bufferSize.Clamp(_start);
```
Comment (lhecker) [inline src/types/UiaTextRangeBase.cpp:54]: Just call Clamp() always. There's no point in testing whether it's in-bounds twice, since `IsInBounds` is basically `Clamp`, but immutable.

Additionally I'd suggest removing the fail-fasts in this PR.

**Comment by carlos-zamora** [comment]
> Are there plans to remove the `FailFast` logic in this PR as well?

Nope. That's a huge undertaking. @miniksa and I were talking about the possibility of switching them over to `asserts`, but we'll have to do some research before committing to that.

File: src/types/UiaTextRangeBase.cpp [hunk 2]
```diff
@@ -44,7 +44,12 @@ try
 {
     RETURN_IF_FAILED(RuntimeClassInitialize(pData, pProvider, wordDelimiters));
 
+    // GH#8730: The cursor position may be in a delayed state, resulting in it being out of bounds.
+    // If that's the case, clamp it to be within bounds.
+    // TODO GH#XXXX: We should be able to just check some fields off of the Cursor object,
```
Comment (zadjii-msft) [inline src/types/UiaTextRangeBase.cpp:49]: Meh probably update this

**Review by zadjii-msft — APPROVED** [review]
But like, builds are hosed so you got time

**Comment by zadjii-msft** [comment]
I FOUND IT

OpenConsole!1794053. 

> Since we don't really do chk and have a ton of different types of asserts, we're going to reduce this all down to one pattern.
> 
> Either it's important enough to check and fast fail on to generate a bucket all the time, or it should be recovered and keep going.
> 
> Many of the asserts we have are indicative of programming failures on our part, so they should crash when we are building/testing them. Others are indicative of stuff that should "never happen". So either they never happen and we won't crash, or they do happen, will crash, and we can identify what sorts of reliability enhancements to make in these areas by their hit level.
> 
> I've removed assert(), ASSERT(), NT_ASSERT(), Assert(), and ASSERT_FRE() from the code and replaced things with either a FAIL_FAST_* wil macro or removed it, especially if it's a thing we've never really utilized.

**Comment by miniksa** [comment]
> I FOUND IT
> 
> OpenConsole!1794053.
> 
> > Since we don't really do chk and have a ton of different types of asserts, we're going to reduce this all down to one pattern.
> > Either it's important enough to check and fast fail on to generate a bucket all the time, or it should be recovered and keep going.
> > Many of the asserts we have are indicative of programming failures on our part, so they should crash when we are building/testing them. Others are indicative of stuff that should "never happen". So either they never happen and we won't crash, or they do happen, will crash, and we can identify what sorts of reliability enhancements to make in these areas by their hit level.
> > I've removed assert(), ASSERT(), NT_ASSERT(), Assert(), and ASSERT_FRE() from the code and replaced things with either a FAIL_FAST_* wil macro or removed it, especially if it's a thing we've never really utilized.

When I talked about this verbally to @carlos-zamora, I had suggested using a telemetry-based assert so we could collect the stack of the failure but not crash the application. Like whatever that engineering system thing is we have that lets you effectively make a "crash report" but keep running. I thought it was telemetry asserts. I did not mean those classic ones that I converted from in that old OpenConsole PR.

**Review by DHowett — APPROVED** [review]

**Comment by DHowett** [comment]
you do still need to fix the SA build!

**Comment by carlos-zamora** [comment]
> you do still need to fix the SA build!

oh yeah. Idk why that's happening. `_pData` is checked for nullness in the `RuntimeClassInitialize()` call -.-.

I'll just check it again, I guess.

**Comment by DHowett** [comment]
the static analyzer is not capable of telling that RuntimeClassInitialize does a null check INSIDE itself and propagating that out to callers

**Comment by carlos-zamora** [comment]
> the static analyzer is not capable of telling that RuntimeClassInitialize does a null check INSIDE itself and propagating that out to callers

That's fair. But out of curiosity, why is it complaining _now_? I didn't touch the method signature.

**Comment by DHowett** [comment]
you are *using* `pData` on the body now where you were not before
