### PR TITLE
Initialize the text buffer with the default attributes on a resize

### LINKED ISSUE #3848: Weird blue selection after closing neovim (WSL)
# Environment

```none
Windows build number: Microsoft Windows Version 10.0.18362.476
Windows Terminal version: microsoft-windows-terminal 0.7.3291.0
```

# Steps to reproduce

1. Open terminal in wsl mode
2. Open neovim
3. Resize the window
4. Quit neovim 

# Actual behavior

A weird blue "selection" appears
`clear` gets rid of it

blue

### PR DESCRIPTION
**Pull request by zadjii-msft**
When we resize the text buffer, initialize the buffer with the
_default_¹ attributes, not the _current_ ones. If we use the current
attributes, then we can get into scenarios where something like `vim` is
running, and left the attributes set to something other than the
defaults, and when we resized the buffer, we'd fill it up with color, as
opposed to whatever the default would be.

This PR instead initializes the buffers with the default colors. It also
makes sure to set the active attributes of the newly created buffers
back to whatever the current attributes of the old buffer were.

[1]: For the Terminal, the default attributes are "default on default".
For conhost, the default attributes are whatever the result of
`Settings::GetDefaultAttributes` is, which could be any combo of the
legacy indices and the default color.

## PR Checklist
* [x] Closes #3848
* [x] I work here
* [x] Tests added/passed
* [n/a] Requires documentation to be updated

## Validation Steps Performed
* ran tests

### CODE REVIEW

**Comment by zadjii-msft** [comment]
I honestly don't know. I'm not sure it's well defined behavior. 

`gnome-terminal` definitely doesn't let you "reveal new lines" when you increase the height of the buffer - the buffer's always at the bottom, resizing just moves lines from scrollback into the buffer, so that's not really an issue for them.

IMO we should act like those lines _don't_ exist until text gets to them. Then whenever text is output and we eventually do get to that line, we'll initialize it with whatever the new attributes should _currently_ be for those lines. (IIRC, we already do that).

Maybe selfhost this (after 1.0) so we can see how it feels?

File: src/cascadia/TerminalCore/Terminal.cpp [hunk 1]
```diff
@@ -199,8 +199,14 @@ void Terminal::UpdateSettings(winrt::Microsoft::Terminal::Settings::ICoreSetting
...
     {
+        // GH#3848 - Stash away the current attributes the old text buffer is
+        // using. We'll initialize the new buffer with the default attributes,
+        // but after the resize, we'll want to make sure that the new buffer's
+        // current attributes (the ones used for printing new text) match the
+        // old buffer's.
+        const auto oldBufferAttributes = _buffer->GetCurrentAttributes();
         newTextBuffer = std::make_unique<TextBuffer>(bufferSize,
-                                                     _buffer->GetCurrentAttributes(),
+                                                     TextAttribute(),
```
Comment (DHowett) [inline src/cascadia/TerminalCore/Terminal.cpp:209]: nit: prefer `{}` initialization if possible

**Review by DHowett — APPROVED** [review]
Okay. I'm a little scared, but this is probably correct. Resize should initialize to the default _and then be filled up with the current attributes_. Yes.

This isn't going to bother cmd's `color` command (in conhost), right?

File: src/host/screenInfo.cpp [hunk 2]
```diff
@@ -1422,7 +1421,7 @@ bool SCREEN_INFORMATION::IsMaximizedY() const
     try
     {
         newTextBuffer = std::make_unique<TextBuffer>(coordNewScreenSize,
-                                                     gci.GetDefaultAttributes(),
+                                                     TextAttribute{},
```
Comment (DHowett) [inline src/host/screenInfo.cpp:1424]: **whoa**. this one scares me!! the session default attributes are more important in conhost than terminal. why the change?

**Review by DHowett — CHANGES_REQUESTED** [review]
disc

File: src/host/screenInfo.cpp (hunk 2 above)
Comment (DHowett) [reply src/host/screenInfo.cpp:1424]: oh but it defaults to `{Default, Default}` doesn't it

Comment (zadjii-msft) [reply src/host/screenInfo.cpp:1424]: Oh I thought this was the way to do it post-#6506

Comment (DHowett) [reply src/host/screenInfo.cpp:1424]: ohhhhhhhhh okay

**Review by DHowett — APPROVED** [review]

**Comment by DHowett** [comment]
@msftbot make sure @miniksa signs

**Review by miniksa — APPROVED** [review]
Yeah. OK. It seems fair.
