### PR TITLE
Keep degenerate UIA text ranges degenerate after movement

### LINKED ISSUE #7342: UIA: degenerate text ranges not degenerate after move
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd] Latest master of OpenConsole
Windows Terminal version (if applicable):

Any other software? NVDA
```

# Steps to reproduce

```Python console
>>> # In the NVDA Python console (NVDA+control+z)
>>> # In a Microsoft Word document (using UIA for access, enable in advanced settings), caret positioned on the first "C" in "Cactus".
>>> start = nav.makeTextInfo("caret")
>>> end = start.copy()
>>> end.move("character", 2) # move to the second "c".
2
>>> marker=start.copy()
>>> marker.setEndPoint(start, "startToStart") # Calls MoveEndpointByRange for UIA controls.
>>> marker.setEndPoint(end, "endToEnd")
>>> marker.text
'Ca' # GOOD

>>> # Now, in conhost with UIA enabled
>>> start = nav.makeTextInfo("caret")
>>> end = start.copy()
>>> end.move("character", 2)
2
>>> marker=start.copy()
>>> marker.setEndPoint(start, "startToStart")
>>> marker.setEndPoint(end, "endToEnd")
>>> marker.text
'Cac' # BAD
```

# Expected behaviour
Conhost matches Microsoft Word when calling `MoveEndpointByRange`.

# Actual behaviour
See above.

### PR DESCRIPTION
**Pull request by codeofdusk**
Conhost expands UIA text ranges when moved. This means that degenerate
ranges become non-degenerate after movement, leading to odd behaviour
from UIA clients. This PR doesn't expand degenerate ranges, but rather
keeps them degenerate by moving `_end` to the newly-changed `_start`.

Tested in the NVDA Python console (cases with `setEndPoint` and
`compareEndPoints` described in #7342). Also ran the logic by
@michaeldcurran.

Closes #7342

Almost definitely addresses nvaccess/nvda#11288 (although I'll need to
test with my Braille display). Also fixes an issue privately reported to
me by @simon818 with copy/paste from review cursor which originally lead
me to believe the issue was with `moveEndPointByRange`.

### CODE REVIEW

File: src/types/UiaTextRangeBase.cpp [hunk 1]
```diff
@@ -603,8 +604,17 @@ IFACEMETHODIMP UiaTextRangeBase::Move(_In_ TextUnit unit,
     // If we actually moved...
     if (*pRetVal != 0)
     {
-        // then just expand to get our _end
-        ExpandToEnclosingUnit(unit);
+        if (wasDegenerate)
+        {
+            // The range was degenerate before the move.
```
Comment (carlos-zamora) [inline src/types/UiaTextRangeBase.cpp:609]:
```suggestion
            // GH#7342: The range was degenerate before the move.
```
We generally mark which bug this fixed as a paper trail.

**Review by carlos-zamora — CHANGES_REQUESTED** [review]
This test is failing: https://github.com/microsoft/terminal/blob/9279b7a73d3d6e0783ef38fa9cf2ad4406c14824/src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp#L578

Not too bad though. Just change [this line](https://github.com/microsoft/terminal/blob/9279b7a73d3d6e0783ef38fa9cf2ad4406c14824/src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp#L586) to:
```
{4, 0+1}
```

Bonus points if you add a similar test to `CanMoveByLine` tests here: https://github.com/microsoft/terminal/blob/9279b7a73d3d6e0783ef38fa9cf2ad4406c14824/src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp#L619

File: src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp [hunk 2]
```diff
@@ -695,6 +695,30 @@ class UiaTextRangeTests
...
+                    5,
+                    {lastColumnIndex , 0 + 5},
+                    {lastColumnIndex , 0 + 5}
+                }
+            },
+
+            MoveTest{
+                L"can move to a new row when necessary when moving backward",
+                { 0, 0 + 1 },
+                { lastColumnIndex, 0 + 1 },
```
Comment (carlos-zamora) [inline src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp:714]: 2 things:
1. you're going to want these two coordinates to be the same value. That way we have a degenerate range.
2. Since we're moving backwards 5 times, you'll want this to have a y-value greater than 5. That way we don't hit the buffer boundary and stop moving.

File: src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp [hunk 3]
```diff
@@ -695,6 +695,30 @@ class UiaTextRangeTests
...
+                -5,
+                {
+                    -5,
+                    {lastColumnIndex - 5, 0},
+                    {lastColumnIndex - 5, 0}
```
Comment (carlos-zamora) [inline src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp:719]: Subtracted the 5 to the x-value instead of the y-value.
Also, keep in mind for when you address the last comment, you'll be starting at a new y-value. So instead of `0-5` it'll be `7-5` (if you choose to make start/end begin on the 7th line, for example).

**Review by carlos-zamora — CHANGES_REQUESTED** [review]
We're close 😊

Also, we have a code formatter. To run it, do this in your terminal:
```sh
# in pwsh, go to the repo's directory
Import-Module .\tools\OpenConsole.psm1
Invoke-CodeFormat
```

File: src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp [hunk 4]
```diff
@@ -694,6 +694,30 @@ class UiaTextRangeTests
...
+
+            MoveTest{
+                L"can move to a new row when necessary when moving forward",
+                { lastColumnIndex, 0 },
+                { lastColumnIndex, 0 },
+                5,
+                {
+                    5,
+                    {lastColumnIndex , 0 + 5},
+                    {lastColumnIndex , 0 + 5}
```
Comment (carlos-zamora) [inline src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp:707]:
```suggestion
                    {0, 0 + 5},
                    {0, 0 + 5}
```
This'll fix the failing test. This is the expected behavior too so that's good.

**Review by carlos-zamora — CHANGES_REQUESTED** [review]

**Review by DHowett — APPROVED** [review]
This is excellent, and a very good catch. Thank you :smile:L

**Comment by DHowett** [comment]
@carlos-zamora double-tap plz

**Review by carlos-zamora — APPROVED** [review]

**Comment by codeofdusk** [comment]
Any rough timeline for when this will make it to insider inbox?

**Comment by DHowett** [comment]
This is merging to Windows today; it will be a couple weeks before it goes out to Insiders. :smile: Thanks again for the contribution.

I'll let you know when it's out.
