### PR TITLE
Fix `//wsl$` paths not working in `MangleStartingDirectoryForWSL`

### LINKED ISSUE #11994: After upgrade to 1.12.3472.0 startingDirectory with forward slashes does not work for WSL any more
### Windows Terminal version

1.12.3472.0

### Windows build number

10.0.19043.0

### Other Software

I have both WSL2 and WSL1 with Ubuntu 20.04 images. For both of them after Windows Terminal upgraded form 1.11 preview to 1.12 preview my session starts in the Ubuntu's root directory instead of the directory set in the Terminal's profile:
``` JSON
            {
                "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
                "hidden": false,
                "name": "Ubuntu",
                "source": "Windows.Terminal.Wsl",
                "startingDirectory": "//wsl$/Ubuntu/home/vbrozik/"
            },
            {
                "guid": "{07b52e3e-de2c-5db4-bd2d-ba144ed6c273}",
                "hidden": false,
                "name": "Ubuntu-20.04",
                "source": "Windows.Terminal.Wsl",
                "startingDirectory": "//wsl$/Ubuntu-20.04/home/vbrozik/"
            },
```
The directories exist:
``` terminal
PS C:\Users\vaclav.brozik> cd //wsl$/Ubuntu/home/vbrozik/
PS Microsoft.PowerShell.Core\FileSystem::\\wsl$\Ubuntu\home\vbrozik> cd //wsl$/Ubuntu-20.04/home/vbrozik/
PS Microsoft.PowerShell.Core\FileSystem::\\wsl$\Ubuntu-20.04\home\vbrozik>
```
The same bug is in the `wsl` utility itself as I noticed that the `--cd` switch fails to process the path with forward slashes while backslashes work fine:
```
PS C:\Users\vaclav.brozik> wsl --cd //wsl$/Ubuntu/home/vbrozik/
vbrozik@EUCZPC6DRGJM2:/$ pwd
/
vbrozik@EUCZPC6DRGJM2:/$ logout
PS C:\Users\vaclav.brozik> wsl --cd \\wsl$\Ubuntu\home\vbrozik\
vbrozik@EUCZPC6DRGJM2:~$ pwd
/home/vbrozik
```
So if Windows Terminal uses this buggy functionality of the `wsl` tool the bug propagates to Windows Terminal.

### Workaround
After I replaced the slashes with backslashes everything works as expected:
``` JSON
            {
                "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
                "hidden": false,
                "name": "Ubuntu",
                "source": "Windows.Terminal.Wsl",
                "startingDirectory": "\\\\wsl$\\Ubuntu\\home\\vbrozik\\"
            },
            {
                "guid": "{07b52e3e-de2c-5db4-bd2d-ba144ed6c273}",
                "hidden": false,
                "name": "Ubuntu-20.04",
                "source": "Windows.Terminal.Wsl",
                "startingDirectory": "\\\\wsl$\\Ubuntu-20.04\\home\\vbrozik\\"
            },
```

### Steps to reproduce

Use forward slashes in the `startingDirectory` property of a WSL profile in Windows Terminal - for example `//wsl$/Ubuntu/home/username/`.

### Expected Behavior

The interactive shell running in WSL should have the working directory as configured in the `startingDirectory` property.

### Actual Behavior

The interactive shell running in WSL has the root directory as the working directory.

### PR DESCRIPTION
**Pull request by zadjii-msft**
This PR does two things, which are best viewed as atomic commits:
* e64ae7d: Move the `MangleStartingDirectoryForWSL` to `types/utils`. It doesn't _really_ make sense in `types`, since it's only really being used in a single place in TerminalConnection. However, TerminalConnection doesn't have tests, and types does. So this commit move the function there, and adds tests from #9223 to the types tests. 
* 42036c5: This actually fixes the bug in #11994. Unfortunately, `wsl --cd` will try to treat paths starting with `//wsl$` as a linux-relative path, when the user almost certainly wanted a windows-relative one. So we'll mangle that back into a path that looks like `\\wsl$\foo\bar`.
* [x] closes #11994
* [x] I work here
* [x] tests added 🎉

### CODE REVIEW

File: src/types/utils.cpp [hunk 1]
```diff
@@ -647,8 +647,23 @@ std::tuple<std::wstring, std::wstring> Utils::MangleStartingDirectoryForWSL(std:
                     // Tilde followed by non-space should be okay (like, wsl -d Debian ~/blah.sh)
                 }
 
+                // GH#11994 - If the path starts with //wsl$, then the user is
```
Comment (DHowett) [inline src/types/utils.cpp:650]: careful -- there's also a `//wsl.localhost` version. we may want `//wsl` plus either a `$` or a `.`

**Review by DHowett — CHANGES_REQUESTED** [review]
as noted

File: src/types/utils.cpp (hunk 1 above)
Comment (zadjii-msft) [reply src/types/utils.cpp:650]: frick good point.

**Review by DHowett — APPROVED** [review]

**Review by miniksa — APPROVED** [review]
