### PR TITLE
Use the til::enumset type for the SgrSaveRestoreStackOptions enum

### LINKED ISSUE #11879: Use the til::enumset type in place of std::bitset in the SgrStack implementation
# Description of the new feature/enhancement

The `SgrStack` implementation currently uses a `std::bitset` type to track which of the attribute values are saved in each stack entry. Since the set index is an enum type, this requires a lot of casting when testing and setting the `bitset`. Replacing that `bitset` with a `til::enumset` should make the code a little bit cleaner.

Here's a sample of the kind of code I'm talking about:
https://github.com/microsoft/terminal/blob/fb597ed304ec6eef245405c9652e9b8a029b821f/src/types/sgrStack.cpp#L143-L153

# Proposed technical implementation details (optional)

Replace the `std::bitset` with a `til::enumset` and eliminate all the unnecessary casts.

I should add that I'm happy to put together a PR for this if there are no objections.

### LINKED ISSUE #11883: XTPUSHSGR doesn't handle default and zero parameters correctly
### Windows Terminal version

1.12.2931.0

### Windows build number

10.0.19041.1348

### Other Software

_No response_

### Steps to reproduce

1. Open a bash shell.
2. Execute the following statements:
```
printf "\033[0;4;7m\033[#p\033[m\033[#qREVERSE UNDERLINE\033[m\n"
printf "\033[0;4;7m\033[;4#p\033[m\033[#qUNDERLINE ONLY\033[m\n"
printf "\033[0;4;7m\033[0#p\033[m\033[#qNEITHER REVERSE NOR UNDERLINE\033[m\n"
```

### Expected Behavior

The first line should be both reversed and underlined.
The second line should be underlined only.
The last line should be neither reversed nor underlined.

This is a screenshot from XTerm:
image

### Actual Behavior

All three lines are displayed as reversed and underlined.

image

The problem is that we're interpreting zero parameters and default parameters to mean that all attributes should be saved. However, the documentation states that we should only be saving all attributes when _no parameters_ have been specified at all.

### PR DESCRIPTION
**Pull request by j4james**
## Summary of the Pull Request

This replaces the `std::bitset` for the `SgrSaveRestoreStackOptions` enum with a `til::enumset` type, thus avoiding the need to cast the `enum` to a `size_t` every time a value is set or tested.

This also fixes an issue with the handling of omitted and zero parameters in the `XTPUSHSGR` sequence, which are meant to be ignored, and not interpreted as "all".

## PR Checklist
* [x] Closes #11879
* [x] Closes #11883
* [x] CLA signed.
* [ ] Tests added/passed
* [ ] Documentation updated.
* [ ] Schema updated.
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Detailed Description of the Pull Request / Additional comments

In addition to dropping all the `static_cast` operations, the use of the `til::enumset` also allowed us to get rid of the `try`/`catch` handling that was previously required in a couple of places, since the `til::enumset` operations don't throw. 

And to fix the zero parameter handling, we just needed to add an additional lower bound when validating that options are in range - if an option is 0 (`All`), it will now just be ignored.

## Validation Steps Performed

The updated code still passes the existing unit tests, and I've manually confirmed that it fixes the test case for omitted and zero parameters from issue #11883.

### CODE REVIEW

**Comment by j4james** [comment]
Btw, I included the #11883 fix in this PR because it's such a trivial change (https://github.com/microsoft/terminal/pull/11888/commits/15514c98a9483a1e42729704b45dbd20c5957345), but if you prefer to keep the issues separate, I can pull that out into another PR.

**Review by zadjii-msft — APPROVED** [review]

File: src/types/sgrStack.cpp [hunk 1]
```diff
@@ -19,42 +19,31 @@ namespace Microsoft::Console::VirtualTerminal
...
-                // encoded; options that aren't supported are ignored when read back (popped).
-                // So if you try to save only unsupported aspects of the current text
-                // attributes, you'll do what is effectively an "empty" push (the subsequent
-                // pop will not change the current attributes), which is the correct behavior.
+                const auto option = static_cast<SgrSaveRestoreStackOptions>(options.at(i).value_or(0));
 
-                for (size_t i = 0; i < options.size(); i++)
+                // Options must be specified singly; not in combination. Values that are
+                // out of range will be ignored.
+                if (option > SgrSaveRestoreStackOptions::All && option <= SgrSaveRestoreStackOptions::Max)
```
Comment (lhecker) [inline src/types/sgrStack.cpp:41]: Shouldn't this be `option >= All && option < Max`?

File: src/types/inc/sgrStack.hpp [hunk 2]
```diff
@@ -14,8 +14,8 @@ Module Name:
 #pragma once
 
 #include "..\..\buffer\out\TextAttribute.hpp"
+#include "..\..\inc\til\enumset.h"
```
Comment (lhecker) [inline src/types/inc/sgrStack.hpp:17]: Oh and I think this should be `#include <til/enumset.h>` for consistency...

File: src/types/sgrStack.cpp (hunk 1 above)
Comment (lhecker) [reply src/types/sgrStack.cpp:41]: Oh `Max` is actually inclusive... I thought it's like the typical exclusive "Count" enum member that's 1 past the highest element. But what about `All`? You can't set the option to 0 (aka `All`) via VT?

Comment (lhecker) [reply src/types/sgrStack.cpp:41]: > if an option is 0 (All), it will now just be ignored.

Fuck. 😄 I need to learn to read. 😄

**Review by lhecker — APPROVED** [review]

File: src/types/inc/sgrStack.hpp (hunk 2 above)
Comment (j4james) [reply src/types/inc/sgrStack.hpp:17]: Cool. I didn't realise that would work. I'll do that now.

**Comment by DHowett** [comment]
I love this. Thanks @j4james!
