### PR TITLE
Fix session restoration of full buffers

### LINKED ISSUE #17639: Restoring a session as tall as the buffer breaks *everything*
### Windows Terminal version

1.22

### Steps to reproduce

Somehow, it puts the viewport below the buffer. Permanently!
CNR on 1.21 Preview.

### PR DESCRIPTION
**Pull request by lhecker**
This removes the `Terminal::SetViewportPosition` call from session
restoration which was responsible for putting the viewport below
the buffer height and caused the renderer to fail.

In order to prevent such issues in the future, `SetViewportPosition`
now protects itself against out of bounds requests.

Closes #17639

## Validation Steps Performed
* Enable persistence
* Print `big.txt`
* Restart
* Looks good ✅

### CODE REVIEW

**Review by DHowett — COMMENTED** [review]
IMO the outcome should be that H-4 lines of the reloaded buffer get pushed off the top of scrollback and lost; what does this change result in?

**Comment by lhecker** [comment]
Oh good point. I should not move the viewport but rather print newlines and then CUP up.

**Review by DHowett — CHANGES_REQUESTED** [review]
(Lodging my review)

**Comment by lhecker** [comment]
We talked about it and decided to just show as much scrollback as possible, since the popups in cmd now use VT.

File: src/cascadia/TerminalControl/ControlCore.cpp [hunk 1]
```diff
@@ -1850,33 +1850,15 @@ namespace winrt::Microsoft::Terminal::Control::implementation
 
             if (read < sizeof(buffer))
             {
+                // Normally the cursor should already be at the start of the line, but let's be absolutely sure it is.
+                if (_terminal->GetCursorPosition().x != 0)
+                {
+                    _terminal->Write(L"\r\n");
+                }
+                _terminal->Write(message);
```
Comment (lhecker) [inline src/cascadia/TerminalControl/ControlCore.cpp:1858]: Moving it into the loop allows us to reuse the console lock that we've already acquired.

**Review by DHowett — APPROVED** [review]

**Review by carlos-zamora — APPROVED** [review]
