### PR TITLE
Don't auto-dismiss the warning dialog on launch

### LINKED ISSUE #15170: Settings error/warning dialog seems to self-dismiss on startup
### Windows Terminal version

56d451ded7cf9ca64abc511740221b963c98ded3

### Windows build number

10.0.22621.1555

### Other Software

_No response_

### Steps to reproduce

1. Checkout the main branch at 56d451ded7cf9ca64abc511740221b963c98ded3
2. Make your settings file invalid
3. Start Terminal

### Expected Behavior

The settings error dialog should be displayed.

### Actual Behavior

The settings error dialog displays for a fraction of a second and then disappears. See video below - you can just see a glimpse of the dialog. This also happens if you've got warnings (which is how I found it originally). This didn't happen whilst I was developing #15082 (which was merged with main at 0105807be22571c8470fc3be6b660da64683528e) - as I tested the duplicate environment variables warning numerous times, so I'd guess this is caused by #15078.

https://user-images.githubusercontent.com/5821575/231422935-3313c80b-3d64-4233-9bce-b63482c1fd28.mp4

### PR DESCRIPTION
**Pull request by zadjii-msft**
Apparently, `ShowWindow` also sends a `WM_MOVE`, which we then turn around and use to dismiss open dialogs. 

Closes #15170

Regressed in #13811

### CODE REVIEW

**Review by DHowett — COMMENTED** [review]
This seems like us working around implicit magic. Is there no way to suppress the WM_MOVE?

**Comment by zadjii-msft** [comment]
> This seems like us working around implicit magic. Is there no way to suppress the WM_MOVE?

Didn't seem like it. I _might_ be able to filter based off if the old window rect and the new one are the same, but that might not work for the initial show

File: src/cascadia/WindowsTerminal/AppHost.cpp [hunk 1]
```diff
@@ -1252,6 +1257,16 @@ winrt::fire_and_forget AppHost::_WindowInitializedHandler(const winrt::Windows::
...
     }
+
+    // Don't set our state to Initialized until after the call to ShowWindow.
+    // When we call ShowWindow, the OS will also send us a WM_MOVE, which we'll
+    // then use to try and dismiss an open dialog. This creates the unintended
+    // side effect of immediately dismissing the initial warning dialog, if
+    // there were settings load warnings.
+    //
+    // In AppHost::_WindowMoved, we'll make sure we're at least initialized
+    // before dismissing open dialogs.
```
Comment (carlos-zamora) [inline src/cascadia/WindowsTerminal/AppHost.cpp:1268]: BODGY?

**Review by carlos-zamora — APPROVED** [review]

File: src/cascadia/WindowsTerminal/AppHost.cpp (hunk 1 above)
Comment (zadjii-msft) [reply src/cascadia/WindowsTerminal/AppHost.cpp:1268]: i mean, at this point: 

> // BODGY
>

**Review by lhecker — APPROVED** [review]
