### PR TITLE
Fix Opacity in Windows 10, again

### LINKED ISSUE #11743: How can I prevent Windows Terminal Preview getting brighter when I click on it?
Currently:

- when I click OFF Windows Terminal Preview, it gets darker  
- when I click ON Windows Terminal Preview, it gets brighter

I like the darker color.  

How can I prevent Windows Terminal Preview getting brighter when I click on it?  

I use Git Bash for all my panes.  

I have tried playing around with setting at:

Settings > Git Bash > Appearance > 'Unfocused Appearance'

But that doesn't seem to get me where I want to go.  

I suppose because I want to control the 'Focussed' appearance, and not the 'Unfocussed' appearance.

### PR DESCRIPTION
**Pull request by zadjii-msft**
More fallout from the settings refactor. Probably because testing on a Windows
10 device is hard, because you actually need a physical machine to get acrylic
to behave correctly.

Basically, the code is simpler now, but we missed the windows 10 only edge case
where acrylic can get turned on, but we forget to enable the acrylic brush, so
it just stays off.

Refer to #11619 where this regressed, and #11643, #12229, because this is just a
hard problem apparently

* [x] Closes #11743. Technically OP is complaining about behavior that's
  by-design, but it made me realize this regressed in 1.12.
* [ ] No tests on this part of the `TermControl` unfortunately.
* [x] Hauled out my old Win10 laptop to verify that opacity works right:
  - [x] A fresh profile isn't created with any opacity
  - [x] Mouse wheeling turns on acrylic
  - [x] Using `opacity` only in the settings still stealthily enables acrylic

### CODE REVIEW

**Comment by DHowett** [comment]
backport desired?

**Review by DHowett — APPROVED** [review]

**Comment by zadjii-msft** [comment]
@DHowett Yes? Not sure how easy this is to get into 1.12.

**Comment by zadjii-msft** [comment]
wait but if the refactor isn't in 1.12, then this should work fine on 1.12. Yea wait ignore me. This ACTUALLY regressed in 1.13, not 1.12. So no need to backport

**Comment by DHowett** [comment]
OK great!

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 1]
```diff
@@ -451,7 +451,9 @@ namespace winrt::Microsoft::Terminal::Control::implementation
     {
         auto settings{ _core.Settings() };
         auto bgColor = til::color{ _core.FocusedAppearance().DefaultBackground() };
-        if (settings.UseAcrylic())
+        // GH#11743: Make sure to use the Core's current UseAcrylic value, not
+        // the one from the settings.
```
Comment (lhecker) [inline src/cascadia/TerminalControl/TermControl.cpp:455]: nit: It's clear from the code that it's using the core and not the settings UseAcrylic value. This comment can be improved by summarizing why this is important.

**Review by lhecker — APPROVED** [review]
