### PR TITLE
Prevent splitting panes into 0 width/height #2401

### LINKED ISSUE #2401: Crash when attempting to split pane with insufficient space available
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.175]
Windows Terminal version (if applicable):0.3.2171.0
```

# Steps to reproduce

1. Map a key binding to `splitHorizontal`
2. Invoke the `splitHorizontal` key binding beyond the point where space is available for the split (~6-7 times)

NOTE: It also happens when splitting vertically but it appears to allow more before crashing.

# Expected behavior

Worth discussing, but I'm guessing it would simply reject the command and perform a system beep (or some other indication of the failure)

# Actual behavior

Application crash

### PR DESCRIPTION
**Pull request by richardszalay**
Fixes a crash that can occur when splitting pane that was so small that the target panes would have a width/height of 0, causing DxRenderer to fail when creating the device resources.

This PR prevents both the call to `App::AddHorizontal/VerticalSplit` and the creation of the `TermControl` if the split would fail.

## PR Checklist
* [x] Closes #2401
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed (_there are no tests for this part of WT_)
* [ ] Requires documentation to be updated
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #2401

## Detailed Description of the Pull Request / Additional comments

`App::_SplitPane` calls `focusedTab->CanAddHorizontalSplit/CanAddHorizontalSplit` before it initializes the `TermControl` to avoid having to deal with the cleanup. If a split cannot occur, it will simply return. 

**Question: Should we beep or something here?**

It then follows the same naming/flow style as the split operation, so: `Tab::CanAddHorizontalSplit -> Pane::CanSplitHorizontal ->Pane::_CanSplit`. The public pane methods will handle leaf/child the same as the current Split methods.

`_CanSplit` reuses existing logic like `_root.GetActualWidth/Height`, `Pane::_GetMinSize`, and the `Half` constant.

## Validation Steps Performed

1. Open a new tab
2. Attempt to split horizontally/vertically more than 6-8 times

Success: Pane will will eventually stop splitting rather than crashing the process.

### CODE REVIEW

File: src/cascadia/TerminalApp/Pane.cpp [hunk 1]
```diff
@@ -834,6 +884,38 @@ void Pane::SplitHorizontal(const GUID& profile, const TermControl& control)
...
+// - splitType: what type of split we want to create.
+// Return Value:
+// - True if the pane can be split. False otherwise.
+bool Pane::_CanSplit(SplitState splitType)
+{
+    const bool changeWidth = _splitState == SplitState::Vertical;
+
+    const Size actualSize{ gsl::narrow_cast<float>(_root.ActualWidth()),
+                           gsl::narrow_cast<float>(_root.ActualHeight()) };
+
```
Comment (zadjii-msft) [inline src/cascadia/TerminalApp/Pane.cpp]: This might need to account for the separator size - when we split the pane, each child is not going to half the parent, it's going to have (half the parent - the size of the separator)

**Comment by richardszalay** [comment]
Ah yes - I was originally planning on using `_GetPaneSizes` as it already contained the separator logic, but couldn't in the end because it relied on the `_firstPercent/_secondPercent` private members and then forgot to include it in my own implementation.

I've amended the commit to include the separator.

(To be honest, I think a lot of Pane.cpp could be refactored to avoid duplicating logic but since this is my first PR I wanted to keep things simple)

**Comment by wolf99** [comment]
If a user cannot open a pane, can they make it larger? Or are they stuck without panes at the moment?

**Comment by zadjii-msft** [comment]
> (To be honest, I think a lot of Pane.cpp could be refactored to avoid duplicating logic but since this is my first PR I wanted to keep things simple)

I would so very happily review that PR 😄

**Comment by richardszalay** [comment]
@zadjii-msft Are those updates ok? The issue is still marked as requiring changes.

**Comment by zadjii-msft** [comment]
Oh, yea I'm happy with that. Sorry I missed the new commit!

File: src/cascadia/TerminalApp/Pane.cpp [hunk 2]
```diff
@@ -834,6 +884,40 @@ void Pane::SplitHorizontal(const GUID& profile, const TermControl& control)
...
+// - Determines whether the pane can be split.
+// Arguments:
+// - splitType: what type of split we want to create.
+// Return Value:
+// - True if the pane can be split. False otherwise.
+bool Pane::_CanSplit(SplitState splitType)
+{
+    const bool changeWidth = _splitState == SplitState::Vertical;
+
+    const Size actualSize{ gsl::narrow_cast<float>(_root.ActualWidth()),
```
Comment (carlos-zamora) [inline src/cascadia/TerminalApp/Pane.cpp]: Should this be `gsl::narrow_cast` or `gsl::narrow`? I honestly don't know, but I know `gsl::narrow_cast` can throw an exception and `gsl::narrow` doesn't.

Comment (miniksa) [reply src/cascadia/TerminalApp/Pane.cpp]: The other way around. `gsl::narrow_cast` means shrink it and I don't care if it doesn't fit exactly.

`gsl::narrow` means if it didn't fit, throw an exception.

**Comment by richardszalay** [comment]
@carlos-zamora Both the naming and the use of `narrow_cast` were used to remain consistent with the existing conventions of the class.

I plan on doing a refactor PR as per my comments above, but I didn't want to include it in this PR since it would detract from the fix being made (not to mention that this is my first terminal PR)

If you're happy to merge this as-is, I can follow up with the refactor PR.

**Comment by DHowett-MSFT** [comment]
Thanks a bunch!

File: src/cascadia/TerminalApp/Pane.cpp (hunk 2 above)
Comment (richardszalay) [reply src/cascadia/TerminalApp/Pane.cpp]: @carlos-zamora Since `double`->`float` is only going to cause a precision loss, I'm assuming that's preferable to keep using `gsl::narrow_cast`?
