### PR TITLE
Make sure background color is opaque when attrs are reversed

### LINKED ISSUE #5498: SGR 7 (reverse video) makes text invisible in Windows Terminal
# Environment

Windows build number: Version 10.0.18362.657
Windows Terminal version (if applicable): 0.11.1121.0

# Steps to reproduce

1. Open a bash shell in Windows Terminal.
2. Execute `printf "\e[mNORMAL \e[7;38m REVERSE \e[m\n"`

# Expected behavior

This is a weird test case, because conpty wouldn't usually forward `SGR 7`, so it's relying on a "feature" in conhost that forces it to pass-through any sequence that the dispatcher doesn't understand. In this case I'm relying on `SGR 38` with a missing type parameter to trigger this pass-through. What this means is that the sequences that actually get sent down the conpty pipe look more like this:

    \e[7;38mNORMAL \e[30;47m REVERSE \e[m\n

So ignoring the fact that the "pass through" feature is generally a bad idea, and this sequence is wrong to start with, I'd expect it to be interpreted as black on white (i.e. reversed), followed by white on black (colors changed to black on white, but still reversed).

# Actual behavior

`SGR 7` somehow seems to make the text invisible, so the first part of the line is blank, and the second half is white on black. Even stranger, it makes the first part of the shell prompt on the following line invisible too.

image

This may seem like an unimportant edge case, but I actually discovered this bug while experimenting with a fix for #2661 (which ended up causing more problems than it solved). Until we can get Windows Terminal to handle all the SGR sequences correctly, I don't think we'll be able to fix issues like #2661.

### PR DESCRIPTION
**Pull request by j4james**
## Summary of the Pull Request

In order to support a transparent background for the acrylic effect, the renderer sets the alpha value to zero for the default background color. However, when the _reversed video_ attribute is set, the background is actually filled with the foreground color, and will not be displayed correctly if it is made transparent. This PR addresses that issue by making sure the rendered background color is opaque if the reversed video attribute is set.

## References

* This is not a major issue at the moment, since the _reverse video_ attribute is not typically forwarded though conpty, but that will change once #2661 is fixed.

## PR Checklist
* [x] Closes #5498
* [x] CLA signed.
* [ ] Tests added/passed
* [ ] Requires documentation to be updated
* [x] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #5498

## Detailed Description of the Pull Request / Additional comments

This simply adds an additional check in `Terminal::GetBackgroundColor` to make sure the returned color is opaque if the _reverse video_ attribute is set. At some point in the future this check may need to be extended to support the `DECSCNM` reverse screen mode, but for now that's not an issue.

## Validation Steps Performed

I've run the test case from issue #5498, and confirmed that it now works as expected. I've also got an experimental fix for #2661 that I've tested with this patch, and that now displays _reverse video_ attributes correctly too.

### CODE REVIEW

File: src/cascadia/TerminalCore/terminalrenderdata.cpp [hunk 1]
```diff
@@ -59,8 +59,8 @@ const COLORREF Terminal::GetBackgroundColor(const TextAttribute& attr) const noe
 {
     const auto bgColor = attr.CalculateRgbBackground({ _colorTable.data(), _colorTable.size() }, _defaultFg, _defaultBg);
     // We only care about alpha for the default BG (which enables acrylic)
-    // If the bg isn't the default bg color, then make it fully opaque.
-    if (!attr.BackgroundIsDefault())
+    // If the bg isn't the default bg color, or reverse video is enabled, make it fully opaque.
+    if (!attr.BackgroundIsDefault() || WI_IsFlagSet(attr.GetMetaAttributes(), COMMON_LVB_REVERSE_VIDEO))
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalCore/terminalrenderdata.cpp:63]: I may file a followup TODO: the _foreground_ should become transparent in this case, which would just be wild. Also, it simply wouldn't work, because we would need to push it on as a clipping layer when we draw the background ;P

Comment (j4james) [reply src/cascadia/TerminalCore/terminalrenderdata.cpp:63]: On a related note, we may also want to consider whether a background color that simply matches the default background should also be made transparent. Right now, if I set my background to `\e[40m` or `\e[48;5;0m` those colors will also be treated as transparent. Once #2661 is fixed, though, that wouldn't be the case - only an explicit default background would be transparent. Maybe that's the way it should be - I don't what most people expect from this feature. We just need to be aware that the current behaviour _is_ going to change after #2661 if we leave things as they are.

Comment (DHowett-MSFT) [reply src/cascadia/TerminalCore/terminalrenderdata.cpp:63]: I think it's the _right_ thing to do (separate 40/48 and 37/38), but we may need to make it opt-in or opt-out for the ConPTY consumer. Per https://github.com/microsoft/terminal/issues/293#issuecomment-458239831, this is one of those sad compatibility hacks.

Because legacy console applications could never emit colors that weren't in the default 16, we chose to make their explicit requests for backgrounds that matched the "default" buffer background (in the legacy 4-bit sense) and foreground into requests for the "default" when they came out of the PTY. 😕

Comment (DHowett-MSFT) [reply src/cascadia/TerminalCore/terminalrenderdata.cpp:63]: If there weren't so many apps with a dependency on the layout of a console text attribute or the `SetConsoleTextAttributes` API, I'd be gung-ho for it. After all, conhost itself has a mode that lets us differentiate them. It does look rather garish, however:

(from Rich's blog post about that)
image
