### PR TITLE
az: Don't fail when a tenant doesn't have a knowable name

### LINKED ISSUE #2249: Azure Cloud Shell Connector Not Working
# Environment

```none
Windows build number: 10.0.18950.1000
Windows Terminal version (if applicable): 0.3.2142.0 (from Microsoft Store)

Any other software?
Not a software, but I'm using GitHub authentication with Microsoft Account.
```

# Steps to reproduce

I tried to use Azure CloudShell Connector, but the connector shows an error message like below.

issue

# Expected behavior

I think it should work normally.

# Actual behavior

I captured traffic with Fiddler4. The OAUTH API returns 400 error code like below. The API says `AADSTS70016: Pending end-user authorization.`. I don't know what causes the error after authentication is complete, but authentication fails as shown in the attached screenshot. 

If there are any conditions or circumstances that prevent the device from logging in, it may be necessary to provide guidance on how to respond appropriately.

Request

```
POST https://login.microsoftonline.com/common/oauth2/token HTTP/1.1
Connection: Keep-Alive
Content-Type: application/x-www-form-urlencoded; charset=utf-8
User-Agent: cpprestsdk/2.10.13
Content-Length: 328
Host: login.microsoftonline.com
Cookie: stsservicecookie=ests; x-ms-gateway-slice=prod; fpc=...

grant_type=device_code&resource=https://management.core.windows.net/&client_id=...&code=...
```

Response:

```
{"error":"authorization_pending","error_description":"AADSTS70016: Pending end-user authorization.\r\nTrace ID: 020679d0-f785-40be-b55c-b6dfa9029500\r\nCorrelation ID: 2de85d18-59f3-44b5-8e91-aa9ada0412b8\r\nTimestamp: 2019-08-05 04:19:27Z","error_codes":[70016],"timestamp":"2019-08-05 04:19:27Z","trace_id":"020679d0-f785-40be-b55c-b6dfa9029500","correlation_id":"2de85d18-59f3-44b5-8e91-aa9ada0412b8"}
```

### PR DESCRIPTION
**Pull request by DHowett-MSFT**
On occasion, in certain delegated access scenarios, we'll fail to read
the name of one or more of the user's Azure tenants. We would summarily
explode (because we're being strict about our incoming JSON, and we
didn't know that this was possible.)

Now we'll substitute in an alternate name and present the ID.

Fixes #2249.

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
h/t to @revpixel for the local repro :smile:

File: src/cascadia/TerminalConnection/AzureConnection.cpp [hunk 1]
```diff
@@ -272,6 +272,20 @@ namespace winrt::Microsoft::Terminal::TerminalConnection::implementation
         }
     }
 
+    // Method description:
+    // - This method returns a tenant's ID and display name (if one if available).
```
Comment (carlos-zamora) [inline src/cascadia/TerminalConnection/AzureConnection.cpp]:
```suggestion
    // - This method returns a tenant's ID and display name (if one is available).
```
