### PR TITLE
vt: make sure to Flush the entire parsed sequence

### LINKED ISSUE #3080: Weird parsing and behavior when an unrecognized OSC's ST is split
# Environment

```none
Windows build number: Win32NT 10.0.18362.0
Windows Terminal version (if applicable): 0.5.2762.0
```

# Steps to reproduce

    echo -ne '\e]10;foo\e'; sleep 1; echo -ne '\\'; sleep 5; echo; sleep 1; echo; sleep 10

# Expected behavior

Two linefeeds eventually, nothing more.

OSC 10 sets the default foreground, it's not yet supported by WT. You can replace it with any other number that's not yet supported.

The terminating sequence of `OSC` should be `ST` accoding to the standard (`BEL` is a commonly used but nonstandard choice instead). `ST` in the `C0` set is `ESC` followed by `\`.

Now we insert a bit of delay in the middle of `ST`. Such difference in timing should never make a difference in the final outcome, not even when the sequence is unsupported.

# Actual behavior

The following weirdnesses occur:

- A literal `\` gets printed. It shouldn't.

- That `\` gets printed 6 seconds after starting the command line, rather than 1 second after. That is, not immediately when received, but when the next character (whether that's a newline or not) is received.

- Subsequent newlines don't move the cursor to the beginning of the line as expected, but walk downwards in the second column.

So it seems the parser might be stuck in some weird mode??

The bug does not occur if the delay is eliminated and the unsupported escape sequence is printed in a single step. It is completely ignored then, as expected.

The bug does not occur with supported escape sequences either, such as setting the title with OSC 0. It's immune to injected delays, as expected.

### LINKED ISSUE #3081: Unsupported CSI, OSC or DEC private mode parsing is interrupted on a delay
# Environment

```none
Windows build number: Win32NT 10.0.18362.0
Windows Terminal version (if applicable): 0.5.2762.0
```

# Steps to reproduce

Sibling issue of #3080. Execute this:

    echo -ne '\e[?12'; sleep 1; echo -ne '34h'

# Expected behavior

As if the delay wasn't there, this should attempt to enable DEC private mode 1234, which is unsupported by WT (actually undefined), so no action should be taken.

# Actual behavior

`34h` is printed, suggesting that parsing the sequence got interrupted.

Note that if the given number is supported (e.g. 1049 to switch to the alternate screen) then the sequence is parsed and executed correctly even when a delay is injected.

---

Update:

The same goes for unsupported CSI modes too, e.g. `\e[22;0;0t` (save title on stack) or `\e[4l` (replace mode).

### PR DESCRIPTION
**Pull request by DHowett-MSFT**
When we had to flush unknown sequences to the terminal, we were only
taking the _most recent run_ with us; therefore, if we received `\e[?12`
and `34h` in separate packets we would _only_ send out `34h`.

This change fixes that issue by ensuring that we cache partial bits of
sequences we haven't yet completed, just in case we need to flush them.

Fixes #3080.
Fixes #3081.

## PR Checklist
* [x] Closes #3080, Closes #3081
* [x] CLA signed
* [x] Tests added/passed
* [ ] Requires documentation to be updated
* [x] Core contributor

## Validation Steps Performed
Ran new tests!

### CODE REVIEW

**Comment by oising** [comment]
You should test that this correctly flushes/ignores SIXEL data too...

**Comment by DHowett-MSFT** [comment]
Chatted offline; since SIXEL data isn't encoded in an escape but rather as a separate "mode" the terminal needs to be put into, this doesn't change how it's handled/passed through/ignored.

File: src/terminal/parser/stateMachine.cpp [hunk 1]
```diff
@@ -1230,7 +1232,13 @@ bool StateMachine::FlushToTerminal()
...
     // However, if we're here, then the processing of pwchChar triggered the
     //      engine to request the entire sequence get passed through, including pwchCurr.
-    return _engine->ActionPassThroughString(_run);
+    bool succeeded = true;
+    if (succeeded && _cachedSequence.has_value())
+    {
+        succeeded = _engine->ActionPassThroughString(*_cachedSequence);
+        _cachedSequence.reset();
+    }
+    return succeeded && _engine->ActionPassThroughString(_run);
```
Comment (miniksa) [inline src/terminal/parser/stateMachine.cpp]: You're being tricky here and it's taking more than instantaneous to figure out what you're doing. Can you please add more comments to explain your trickery?

(Also that first `succeeded` test is weird given it's always true...)

Comment (DHowett-MSFT) [reply src/terminal/parser/stateMachine.cpp]: the first `succeeded` test is in case anybody ever adds another thing that might fail in this flow ;P but yeah, fair. I'll comment it
