### PR TITLE
Make sure RIS re-enables win32 input and focus events

### LINKED ISSUE #15461: Hard reset disables win32-input-mode
### Windows Terminal version

1.18.1421.0

### Windows build number

10.0.19045.2913

### Other Software

_No response_

### Steps to reproduce

1. Start Windows Terminal.
2. Open up a WSL bash shell with the debug tap enabled.
3. Press some keys and note the escape sequences that are generated in the debug pane.
4. Execute `reset`.
5. Press some more keys and note what is generated in the debug pane now.

### Expected Behavior

I'd expected to see win32-input-mode escape sequences for every key press.

### Actual Behavior

After the reset, win32-input-mode is disabled, and the key presses are just passed through as ASCII, or basic VT100 escape for things like arrow keys.

I think this was a regression introduced in PR #14444 when I made the `RIS` operation fully reset all input modes. Technically that was the right thing to do, but for conpty to work correctly, it would now also need to re-request any non-default modes it needs from the conpty client.

I'm not sure how best to fix this. The `HardReset` implementation can't just return false to pass through the `RIS` sequence anymore. It would probably need to call a new "reset" method in the renderer that the VT engine would pass on as an `RIS` with additional mode requests. It must also then return true to prevent the state machine trying to pass through the `RIS` a second time.

I don't know if anyone has any better ideas.

### PR DESCRIPTION
**Pull request by j4james**
When an `RIS` (hard reset) sequence is executed, ConHost will pass that
through to the connected conpty terminal, which results in all modes
being reset to their initial state. To work best, though, conpty needs
to have the win32 input mode enabled, as well as the focus event mode.
This PR addresses that by explicitly requesting the required modes after
an `RIS` is passed through.

Originally these modes were only set if the `--win32input` option was
given, but there is really no need for that, since terminals that don't
support them should simply ignore the request. To avoid that additional
complication, I've now removed the option (i.e. ConHost will now always
attempt to set the modes it needs).

I've manually confirmed that keypresses are still passed through with
win32 input sequences after a hard reset, and that focus events are
still being generated. I've also updated the existing conpty round-trip
test for `RIS` to confirm that it's now also passing through the mode
requests that it needs.

Closes #15461

### CODE REVIEW

File: src/host/ConsoleArguments.cpp [hunk 1]
```diff
@@ -515,9 +514,10 @@ void ConsoleArguments::s_ConsumeArg(_Inout_ std::vector<std::wstring>& args, _In
...
         }
-        else if (arg == WIN32_INPUT_MODE)
+        else if (std::regex_match(arg, std::wregex(L"--[A-Za-z0-9]+")))
         {
-            _win32InputMode = true;
+            // Any other alphanumeric sequence starting with -- is likely
+            // an unrecognized argument that we need to ignore.
             s_ConsumeArg(args, i);
             hr = S_OK;
         }
```
Comment (j4james) [inline src/host/ConsoleArguments.cpp:523]: I'm not sure if you'll be happy with using a regex here, if that's going to add bloat to conhost. It looks to me like we're already using regex searches in the `TextBuffer`, but I'm not sure if that actually gets linked into conhost.

Worst case, we could make this only ignore the defunct `--win32input` option, but I thought it would be nice to have it dropping all the unsupported args, since there was already a TODO for that a few lines down from here.

**Comment by j4james** [comment]
I should also note that I haven't removed the code that _sets_ the `--win32input` command line option when starting up a conpty connection, because I wasn't sure if that needed to remain for backwards compatibility, e.g. if connecting to an older version of conhost. If that's not something we need to worry about, then there's probably a bit more code we could get rid of.

File: src/host/ConsoleArguments.cpp (hunk 1 above)
Comment (lhecker) [reply src/host/ConsoleArguments.cpp:523]: It's not linked into conhost as far as I know. I personally would like to replace it with ICU in the future so that we can get proper Unicode aware regex queries. ICU is also _significantly_ faster, like in the order >100x. It can go through the entire 120x9001 text buffer full of enwik8 in <3ms with a worst-case query like `e` (or some other common ASCII character).

Is there any reason to not just check if the `arg` starts with `--` and then ignore it? What other arguments could start with `--` and not be followed by a-z0-9?

**Review by lhecker — APPROVED** [review]

File: src/host/ConsoleArguments.cpp (hunk 1 above)
Comment (DHowett) [reply src/host/ConsoleArguments.cpp:523]: This, I am somewhat worried about. We go from explicitly rejecting unknowns to explicitly accepting them...

Since conpty.dll and openconsole.exe ship in lock-step, I would be comfortable just yanking all support for the argument and the special flag and everything. :)

After all . . . it never made it up to our public API surface on Windows!

Comment (DHowett) [reply src/host/ConsoleArguments.cpp:523]: This got me thinking, and I'd be interested in what you and Leonard and @zadjii-msft think.

_This is speculative and not for this PR._

"In the future", we might want to add more types of conpty flags. Maybe. I don't love it, but maybe we will.

Mike and Michael used to prefer `--real --arguments` that set flags, rather than `--flags 0xABCD` to bulk enable all of `0xABCD`. The argument was that it was easier spot in a debugger or a process list.

I still think there's value in having `--flags 0xABCD`, but this PR made me realize that maybe what we actually want is `--flags.required 0x0001 --flags.optional 0x0002`. Conforming versions of conhost can say, "I don't support flag 0x0001" if `0x0001` is too new for their blood... but they can ignore `0x0002` if they don't know what it is.

Is that YAGNI?

Comment (j4james) [reply src/host/ConsoleArguments.cpp:523]: > Is there any reason to not just check if the `arg` starts with `--` and then ignore it? What other arguments could start with `--` and not be followed by a-z0-9?

That was actually my first attempt, but it caused this test case to fail:
https://github.com/microsoft/terminal/blob/c9e993a38ec04833e15edac230300948a0fab83b/src/host/ut_host/ConsoleArgumentsTests.cpp#L113

So then I thought I should maybe also check that the arg contained no spaces, but that still caused this test to fail:
https://github.com/microsoft/terminal/blob/c9e993a38ec04833e15edac230300948a0fab83b/src/host/ut_host/ConsoleArgumentsTests.cpp#L182

And that's when I figured I'd need to go with a regex.

But maybe those test cases aren't really something we need to support. I don't know.

Comment (j4james) [reply src/host/ConsoleArguments.cpp:523]: > Since conpty.dll and openconsole.exe ship in lock-step, I would be comfortable just yanking all support for the argument and the special flag and everything. :)

Won't this potentially break third-party terminals though? If this update eventually ships as the inbox conhost, and there are third-party terminals launching it with the `--win32input` parameter, then that's surely going to kill them.

I was also concerned by the wording of the comments regarding defterm here:
https://github.com/microsoft/terminal/blob/c9e993a38ec04833e15edac230300948a0fab83b/src/host/srvinit.cpp#L606-L609

That made me think with defterm you might have an old version of conhost being started that would hand off to a newer version of Windows Terminal. Or does it not work like that?

Comment (DHowett) [reply src/host/ConsoleArguments.cpp:523]: Ah, that! That one doesn't actually matter, and is an example of one of my least favorite types of code[^1]. That code runs in the _receiving_ conhost (the one that's built out of this repo) and it's actually just using that string to tell another part of the same process how to act.

We can safely remove it, so long as win32 input mode really does default to always-requested.

[^1]: using strings and serialization to communicate state _in the same address space, between two components that could exchange objects or POD types_

Comment (j4james) [reply src/host/ConsoleArguments.cpp:523]: OK, so the plan then is to remove all the `--win32input` parameters when starting the conpty connection, and drop the regex check for invalid args - we can figure out how best to handle that at some point in the future.

But I need to ask again, are we sure this won't break any third-party terminals?

Comment (DHowett) [reply src/host/ConsoleArguments.cpp:523]: > But I need to ask again, are we sure this won't break any third-party terminals?

Fffffair, and sorry I didn't answer it at first. My official stance is, _"we haven't built the conpty API for use without conpty.dll"_; if somebody is invoking it directly and passing their own pipes, they are allowed to keep the pieces when it breaks.

The command line args are effectively an internal interface. Technically. I know somebody's caught us out for breaking them before, but that's because they were setting "`conhost --pty`" as their _debugger_ to stop certain Windows processes from starting . . .

Comment (j4james) [reply src/host/ConsoleArguments.cpp:523]: OK, that's just me not understanding how it works - that seems reasonable. But do I keep the `PSEUDOCONSOLE_WIN32_INPUT_MODE` flag, and just not do anything with it, or should that be nuked as well?

Comment (DHowett) [reply src/host/ConsoleArguments.cpp:523]: Ah, it would be fine for you to remove that flag in its entirety. :)

Comment (DHowett) [reply src/host/ConsoleArguments.cpp:523]: That's the other half of the equation. We haven't made a publicly supported API-stable release of ConPTY's new undocked interface, so anybody using it is taking on `0.x` version level support. I'm happy to be the one with whom the buck stops if they come to ask!

Comment (j4james) [reply src/host/ConsoleArguments.cpp]: I think this is done now. I've dropped the regex test for the invalid args, and removed all the `--win32input` command line parameters as well as the `PSEUDOCONSOLE` flag. Everything still appears to work.

**Review by DHowett — APPROVED** [review]
Outstanding. Thanks so much for tearing out all the vestiges of this thing :smile:
