### PR TITLE
Use standard 1px window borders on NC Island Window

### LINKED ISSUE #1307: Thick white border around window when showTabsInTitlebar enabled
# Environment

```none
Windows build number: 10.0.18362.145
Windows Terminal version (if applicable):
```

# Steps to reproduce

Set `showTabsInTitlebar` to true in the settings file, and then start up Windows Terminal.

# Expected behavior

The window should be surrounded with a thin grey border:

image

# Actual behavior

A thick, non-Windowsy white border is shown instead.

image

### LINKED ISSUE #1859: Window border width does not respect system theme
# Environment

```none
Windows build number: 10.0.18362.207
Windows Terminal version (if applicable): 0.2.1831.0
```

# Steps to reproduce

1. Install the [third-party Aerolite.theme ](https://www.deviantart.com/win7tbar/art/Aerolite-Theme-for-Windows-10-658196061) to get window borders back to being usable (i.e. not zero-width).
2. Note that Command Prompt, Windows PowerShell, and Ubuntu for Windows 10 command shell windows all respect the nice new border width.
3. Launch Windows Terminal.

# Expected behavior

Windows Terminal should also respect the theme's window border width.

# Actual behavior

Windows Terminal has a zero-width window border in defiance of the system theme, making it nearly impossible to resize.

### LINKED ISSUE #1897: Lots of work is duplicated when NonClientIslandWindow is resized and the drag bar size changes
This is work that's following on from work that's being done for #1625. 

I'm pulling the code for updating the drag region out of `NonClientIslandWindow::OnSize` into its own method. Unfortunately, both these methods need to do the following block of work:
```c++

        const auto windowRect = GetWindowRect();
        const auto width = windowRect.right - windowRect.left;
        const auto height = windowRect.bottom - windowRect.top;

        const auto scale = GetCurrentDpiScale();
        const auto dpi = ::GetDpiForWindow(_window.get());

        const auto dragY = ::GetSystemMetricsForDpi(SM_CYDRAG, dpi);
        const auto dragX = ::GetSystemMetricsForDpi(SM_CXDRAG, dpi);

        // If we're maximized, we don't want to use the frame as our margins,
        // instead we want to use the margins from the maximization. If we included
        // the left&right sides of the frame in this calculation while maximized,
        // you' have a few pixels of the window border on the sides while maximized,
        // which most apps do not have.
        const auto bordersWidth = _isMaximized ?
                                      (_maximizedMargins.cxLeftWidth + _maximizedMargins.cxRightWidth) :
                                      (dragX * 2);
        const auto bordersHeight = _isMaximized ?
                                       (_maximizedMargins.cyBottomHeight + _maximizedMargins.cyTopHeight) :
                                       (dragY * 2);

        const auto windowsWidth = width - bordersWidth;
        const auto windowsHeight = height - bordersHeight;
        const auto xPos = _isMaximized ? _maximizedMargins.cxLeftWidth : dragX;
        const auto yPos = _isMaximized ? _maximizedMargins.cyTopHeight : dragY;

        const auto dragBarRect = GetDragAreaRect();
        const auto nonClientHeight = dragBarRect.bottom - dragBarRect.top;
```

Doing this twice is clearly ridiculous, and more likely than not, _wrong_.

I'm thinking that on the resize, we could _probably_ just cache some of these values. I think this will also important for dealing with maximizing, cause I ~~think~~ know the maximize borders are wrong on non-primary displays.

### LINKED ISSUE #3064: White border at the bottom of the window.
# Environment

```none
Windows build number: 10.0.18995.0
Windows Terminal version (if applicable): 0.5.2762.0
```

# Steps to reproduce

Open Terminal app.

# Expected behavior

Should not show a white border on the bottom of the window.

# Actual behavior

Shows a 1 pixel thin white border on the bottom of the window.
grafik

### LINKED ISSUE #3136: Window Border expands when showTabsInTitlebar is enabled
I originally opened #2333 which was supposed to be resolved by #2150 but I am still seeing the issue in 0.5

# Environment

```none
Windows build number: Microsoft Windows NT 10.0.18362.0
Windows Terminal version (if applicable): 0.5.2762.0


```

# Steps to reproduce
Set showTabsInTitlebar to true.

# Expected behavior

working

# Actual behavior
true

When showTabsInTitlebar is false

false

### LINKED ISSUE #3222: Suspicious remains of previous window borders flash up when closing the window
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version (if applicable): 0.5.2762.0
```

# Steps to reproduce

Resize the window to smaller, then back to about its original size or even bigger.

Close the window.

# Expected behavior

The window should simply disappear.

# Actual behavior

For a fraction of a second, tons of horizontal and vertical lines, which look like the border of the window at its previous sizes, are painted inside the window area.

This suspiciously looks like some leftover widgets that don't get properly cleaned up during a resize, potentially consuming various resources (and maybe causing who knows what other problems).

(Could be related to #3207?)

WT-closing

### PR DESCRIPTION
**Pull request by greg904**
## Summary of the Pull Request

I put the standard Windows window borders on the Windows Terminal window (can you read that?).
(It's only on the left, bottom and right though, on the top I had to use a hack because of the title bar)

Light mode, color in title bar disabled:
frame

Light mode, color in title bar enabled:
frame color

Dark mode, color in title bar disabled:
frame dark

Dark mode, color in title bar enabled:
frame dark color

High contrast mode (with Settings app on right to compare):
high contrast

Note: the title bar should probably be purple like in Win32 apps but it isn't either in the UWP apps (Settings, classic Edge, …) so I don't really know.

 
## PR Checklist
* [x] Closes #3064, closes #1307, closes #3136, closes #1897, closes #3222, closes #1859 and maybe more?
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Requires documentation to be updated
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Detailed Description of the Pull Request / Additional comments

We take the standard window frame except that we remove the top part (see `NonClientIslandWindow::_OnNcCalcSize`), then we put little 1 pixel wide top border back in the client area using `DwmExtendFrameIntoClientArea` and then we put the XAML island and the drag bar on top.

Most of this PR is comments to explain how the code works and also removing complex code that was needed to handle the weird cases when the borders were custom.

I've also refactored a little bit the `NonClientIslandWindow` class.

### CODE REVIEW

File: src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp [hunk 1]
```diff
@@ -531,53 +519,38 @@ RECT NonClientIslandWindow::GetMaxWindowRectInPixels(const RECT* const prcSugges
...
+                _backgroundBrush = wil::unique_hbrush(CreateSolidBrush(color));
+
+                RECT rcRest = ps.rcPaint;
+                rcRest.top = topBorderHeight;
+
+                // To paint on top of the original title bar, we have to set
+                // alpha channel to 255. This is a hack to do it with GDI.
+                HDC opaqueDc;
+                BP_PAINTPARAMS params = { sizeof(params), BPPF_NOCLIP | BPPF_ERASE };
+                HPAINTBUFFER buf = BeginBufferedPaint(hdc.get(), &rcRest, BPBF_TOPDOWNDIB, &params, &opaqueDc);
```
Comment (greg904) [inline src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp]: I don't really know how GDI works so I found the first solution on Google to do this but maybe there is a better solution.

File: src/types/lib/types.vcxproj.filters [hunk 2]
```diff
@@ -60,9 +60,6 @@
     <ClCompile Include="..\UTF8OutPipeReader.cpp">
       <Filter>Source Files</Filter>
     </ClCompile>
-    <ClCompile Include="..\WindowUiaProvider.cpp">
```
Comment (greg904) [inline src/types/lib/types.vcxproj.filters]: I don't know what this is, there is no `WindowUiaProvider.cpp` file in `src/types`. The file is in `src/interactivity/win32`. I think Visual Studio removed it automatically? Should I remove this?

**Comment by greg904** [comment]
For now there is no resize handle directly on top of the tab row.

File: src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp [hunk 3]
```diff
@@ -457,47 +445,6 @@ void NonClientIslandWindow::_UpdateDragRegion()
 
         return 0;
     }
-
-    case WM_NCLBUTTONDOWN:
```
Comment (greg904) [inline src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp]: This is already done in `IslandWindow::MessageHandler`.

File: src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp [hunk 4]
```diff
@@ -457,47 +445,6 @@ void NonClientIslandWindow::_UpdateDragRegion()
...
-        if (_HandleWindowPosChanging(lpwpos))
-        {
-            return 0;
-        }
-        else
-        {
-            break;
-        }
-    }
-    case WM_DPICHANGED:
```
Comment (greg904) [inline src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp]: This is already done in `BaseWindow::MessageHandler`.

**Comment by miniksa** [comment]
I don't know enough about the non-client area and XAML stuff to go through this. @DHowett-MSFT is the non-client expert and @zadjii-msft is the current UI king. So I'll let them stab first.

File: src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp [hunk 5]
```diff
@@ -461,342 +428,120 @@ RECT NonClientIslandWindow::GetMaxWindowRectInPixels(const RECT* const prcSugges
...
+            _backgroundBrush = wil::unique_hbrush(CreateSolidBrush(color));
         }
-        else
+
+        // To hide the original title bar, we have to paint on top of it with
+        // the alpha component set to 255. This is a hack to do it with GDI.
+        // See NonClientIslandWindow::_UpdateFrameMargins for more information.
+        HDC opaqueDc;
+        BP_PAINTPARAMS params = { sizeof(params), BPPF_NOCLIP | BPPF_ERASE };
+        HPAINTBUFFER buf = BeginBufferedPaint(hdc.get(), &rcRest, BPBF_TOPDOWNDIB, &params, &opaqueDc);
```
Comment (greg904) [inline src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp]: I don't really know how GDI works so I found the first solution that worked on Google to do this but maybe there is a better solution.

**Comment by greg904** [comment]
Note: the big purple top border is missing when high contrast is activated on Windows because I hardcoded its size as 1 pixel * DPI scale. But it's also missing on UWP apps so I guess the people at Microsoft who did the UWP apps had the same problem but couldn't fix it so maybe there is no easy solution?

high contrast

**Comment by greg904** [comment]
Please 😢

image

**Comment by DHowett-MSFT** [comment]
This is a lot to digest, but I think I like where it's going. It definitely cleans up the reponsibilities of a bunch of the crap in NonClientIslandWindow. I'll need to give it a closer review, but it seems like a more refined version of the work I was doing to achieve the same goal. :smile:

File: src/cascadia/WindowsTerminal/AppHost.cpp [hunk 6]
```diff
@@ -188,54 +188,40 @@ void AppHost::_HandleCreateWindow(const HWND hwnd, RECT proposedRect, winrt::Ter
...
 
-        // Create a RECT from our requested client size
-        auto nonClient = Viewport::FromDimensions({ _currentWidth,
-                                                    _currentHeight })
-                             .ToRect();
+        long nonClientWidth = currentWidth;
+        long nonClientHeight = currentHeight;
+
+        RECT frame = {};
+        bool succeeded = AdjustWindowRectExForDpi(&frame, WS_OVERLAPPEDWINDOW, false, 0, dpix);
```
Comment (DHowett-MSFT) [inline src/cascadia/WindowsTerminal/AppHost.cpp]: (this can be a `LOG_LAST_ERROR_IF(!...`)

File: src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp [hunk 7]
```diff
@@ -461,342 +424,120 @@ RECT NonClientIslandWindow::GetMaxWindowRectInPixels(const RECT* const prcSugges
...
-            _maximizedMargins.cyTopHeight = frame.top * -1;
-            _maximizedMargins.cxRightWidth = frame.right;
-            _maximizedMargins.cyBottomHeight = frame.bottom;
-
-            _isMaximized = true;
-            THROW_IF_FAILED(_UpdateFrameMargins());
-        }
-    }
-    else
+    if (FAILED(ThemeUtils::SetDwmImmersiveDarkMode(_window.get(), isDarkMode)))
```
Comment (DHowett-MSFT) [inline src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp]: this one should just be `LOG_IF_FAILED(...)` -- not because it's fewer lines of code, but because this function returns an HRESULT, and DWM returns an HRESULT, but `LOG_LAST_ERROR` uses `GetLastError()` to get the _win32 error state_ (which isn't used by any of the downstream callees here)

LOG_IF_FAILED() just takes the HRESULT return and logs that. :smile:

Comment (DHowett-MSFT) [reply src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp]: It actually will shout at you if you use it wrong, but that would require us to hit a failure:

```
                WI_USAGE_ERROR_FORWARD("CALLER BUG: Macro usage error detected.  GetLastError() does not have an error.");
```

**Comment by greg904** [comment]
Ok so in the before last commit I fixed a bug where the theme is taken from the system settings and not the settings.json. But because the theme was not originally passed to NonClientIslandWindow, I had to change a few files like App.h, App.cpp, AppHost.cpp, etc. Please check this.

> I'd be most comfortable merging this without the dark theme fix (which I know will cause there to be white borders around the entire window instead of just at the bottom) and then bringing in the dark theme changes when the other fix has flowed back down from Windows.

I'm not sure if I understand this correctly. I rolled back `src/interactivity/win32/windowtheme.cpp` to `master` and removed the code in the function to set dark mode in ThemeUtils (now it doesn't do anything). Also I renamed the function to be more generic because apparently it's no longer a DWM window attribute to set the frame to dark theme.

> (which I know will cause there to be white borders around the entire window instead of just at the bottom)

There was no white border at the bottom, I removed the hack with `DwmExtendFrameIntoClientArea`.

**Comment by Elttob** [comment]
One thing I've noticed - the behaviour for when title bar colours are disabled doesn't actually line up with the current/expected behaviour seen with other apps.

As an example, here's Settings while inactive and with title bar colours disabled.
Zooming in on the left border here, you can see the border is actually a transparent shade;

image

When I focus the Settings window, the border remains transparent;

image

As far as I can see, your borders are solid colour. It's a small thing, but might be best fixed before merging 🙂 ✨

File: src/types/ThemeUtils.cpp [hunk 8]
```diff
@@ -0,0 +1,19 @@
...
+    // Arguments:
+    // - hwnd: handle to the window to change
+    // - enabled: whether to enable or not the dark mode on the window's frame
+    // Return Value:
+    // - S_OK or suitable HRESULT from DWM engines.
+    [[nodiscard]] HRESULT SetWindowFrameDarkMode(HWND /* hwnd */, bool /* enabled */) noexcept
+    {
+        // TODO:GH #3425 implement the new DWM API and change
+        //  src/interactivity/win32/windowtheme.cpp to use it.
+        return S_OK;
```
Comment (DHowett-MSFT) [inline src/types/ThemeUtils.cpp]: Thanks for this. :smile:

File: src/types/lib/types.vcxproj.filters (hunk 2 above)
Comment (DHowett-MSFT) [reply src/types/lib/types.vcxproj.filters]: This is fine to remove. We occasionally miss updates to the `filters` files, and VS is more than happy to change them where necessary.

File: src/types/precomp.h [hunk 9]
```diff
@@ -29,6 +29,7 @@ Module Name:
 
 // Windows Header Files:
 #include <windows.h>
+#include <dwmapi.h>
```
Comment (DHowett-MSFT) [inline src/types/precomp.h]: We probably don't need this one for the moment now that ThemeUtils is stripped, right?

**Comment by greg904** [comment]
It looks like it depends on the app. On my system, explorer.exe has this white border too.
image

Paint has it too:
image

But conhost.exe doesn't:
image

Neither does regedit:
image

Explorer and Paint are two apps that modify their title bar to add additional buttons in it (explorer to open file properties and create a new folder; paint to save or go back/forward). So maybe the window border turns white automatically for some reason when you remove the title bar? Then I don't know how the Settings app does it because it has a dark border on my system but it ALSO has a custom its title bar.

image

**Comment by Elttob** [comment]
Interesting, it's probably something to do with UWP vs non UWP apps?

File: src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp [hunk 10]
```diff
@@ -202,142 +254,125 @@ void NonClientIslandWindow::OnSize(const UINT width, const UINT height)
...
-// https://docs.microsoft.com/en-us/windows/desktop/dwm/customframe
-[[nodiscard]] LRESULT NonClientIslandWindow::HitTestNCA(POINT ptMouse) const noexcept
+// - the height of the window's top resize handle
+int NonClientIslandWindow::_GetResizeHandleHeight() const noexcept
 {
-    // Get the window rectangle.
-    RECT rcWindow = BaseWindow::GetWindowRect();
+    // there isn't a SM_CYPADDEDBORDER for the Y axis
+    return ::GetSystemMetricsForDpi(SM_CXPADDEDBORDER, _currentDpi) +
+           ::GetSystemMetricsForDpi(SM_CYFRAME, _currentDpi);
```
[the remark this answers is not in the document]
Comment (greg904) [reply src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp]: The issue was about not using CYDRAG, not CYFRAME.

According to https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getsystemmetrics CYDRAG is:
> The number of pixels above and below a mouse-down point that the mouse pointer can move before a drag operation begins. This allows the user to click and release the mouse button easily without unintentionally starting a drag operation. If this value is negative, it is subtracted from above the mouse-down point and added below it. 

I think CYDRAG was the wrong metric. It has nothing to do with the window frame. What we want is probably CYSIZEFRAME (at least according to the doc):
>The thickness of the sizing border around the perimeter of a window that can be resized, in pixels. SM_CXSIZEFRAME is the width of the horizontal border, and SM_CYSIZEFRAME is the height of the vertical border. 
This value is the same as SM_CYFRAME.

CYSIZEFRAME is the same as CYFRAME. Maybe I should change CYFRAME to CYSIZEFRAME for more clarity?

**Comment by greg904** [comment]
Ok so I found a bug where the title bar is not included in the initial height when `showTabsInTitlebar` is on so if you set `initialCols` to 10 for example it ends up being less than that (and it can even crash if you set it to 1 because the size is too small). The bug was there before the PR but I've updated a TODO in 48cd3801c3b1df22bf809314ad4696eb0441ad03 to tell what needs to be done to fix bug (because it should probably be done in another PR). Should I make a GitHub issue for it? Because the TODO says MSFT so it's not on GitHub.

@DHowett-MSFT I initially assumed that DWM would scale the borders based on the DPI but I tried changing my DPI and the top border stays 1 pixel exactly on apps like explorer.exe so I've removed the code to scale the top border according to the DPI. It will probably fix the bug with the thick borders.

File: src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp [hunk 11]
```diff
@@ -202,142 +254,125 @@ void NonClientIslandWindow::OnSize(const UINT width, const UINT height)
...
+    LPARAM lParam = MAKELONG(ptMouse.x, ptMouse.y);
+    const auto originalRet = DefWindowProc(_window.get(), WM_NCHITTEST, 0, lParam);
+    if (originalRet != HTCLIENT)
+    {
+        return originalRet;
+    }
 
-    const auto dragBarRect = GetDragAreaRect();
-    const auto nonClientHeight = dragBarRect.bottom - dragBarRect.top;
+    // At this point, we know that the cursor is inside the client area so it
```
[the remark this answers is not in the document]
Comment (greg904) [reply src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp]: I love deleting code 😈.

**Comment by zadjii-msft** [comment]
@greg904 That might actually be #2061, if not it's definitely related. I'd probably just leave it as-is, and fix it as a part of #2061.

File: src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp (hunk 10 above)
[the remark this answers is not in the document]
Comment (zadjii-msft) [reply src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp]: Oh good catch, I missed that. This looks like the right answer, thanks!

**Comment by greg904** [comment]
Ok, I've reverted the TODO change to leave it as-is.

File: src/cascadia/WindowsTerminal/AppHost.cpp [hunk 12]
```diff
@@ -188,54 +188,25 @@ void AppHost::_HandleCreateWindow(const HWND hwnd, RECT proposedRect, winrt::Ter
...
-            // coincides with the screen
-            const auto pCWindow = static_cast<IslandWindow*>(_window.get());
-            const RECT frame = pCWindow->GetFrameBorderMargins(dpix);
-            proposedRect.left += frame.left;
+            islandFrame.top = -NonClientIslandWindow::topBorderVisibleHeight;
         }
 
-        adjustedHeight = nonClient.bottom - nonClient.top;
-        adjustedWidth = nonClient.right - nonClient.left;
+        adjustedWidth = -islandFrame.left + islandWidth + islandFrame.right;
```
Comment (zadjii-msft) [inline src/cascadia/WindowsTerminal/AppHost.cpp]: I'd maybe add a comment on why we don't need to do anything for the `!_useNonClientArea` case here

File: src/cascadia/WindowsTerminal/NonClientIslandWindow.h [hunk 13]
```diff
@@ -21,48 +21,58 @@ Author(s):
...
 #include <dwmapi.h>
-#include <wil\resource.h>
+#include <wil/resource.h>
 
 class NonClientIslandWindow : public IslandWindow
 {
 public:
-    NonClientIslandWindow() noexcept;
+    // this is the same for all DPIs
+    static constexpr const int topBorderVisibleHeight = 1;
```
[the remark this answers is not in the document]
Comment (zadjii-msft) [reply src/cascadia/WindowsTerminal/NonClientIslandWindow.h]: Though probably don't just commit this suggestion, that'd break things D:

**Comment by musm** [comment]
bravo!

**Comment by Stanzilla** [comment]
So...any way to color this new 1px border? I don't think there is a setting in Windows to color inactive window borders differently anymore, is there?

**Comment by adrianghc** [comment]
> I'd be most comfortable merging this without the dark theme fix (which I know will cause there to be white borders around the entire window instead of just at the bottom) and then bringing in the dark theme changes when the other fix has flowed back down from Windows.

I couldn't find more details about this here, so does this mean the white border will be fixed with a new release or does the fix need to come from Windows, i.e. we would have to get 20H1 for the fix?

**Comment by greg904** [comment]
@Stanzilla The border behaves the same way as other windows. When it is active it will be either the accent color that you chose in Windows Settings if "Show accent color on the following surfaces -> Title bars and windows borders" is checked or a gray color otherwise. When it is inactive, it will always be gray. I don't think that there is a setting to color inactive window borders in Windows.

@adrianghc 20H1 changed the way to make the border dark. I think it is possible to detect if 20H1 is running and use the new way and if it's older than 20H1, use the old way to make the border dark so it could be fixed without waiting for 20H1 if this is done.

**Comment by Stanzilla** [comment]
Well yeah, I don't really want to use my accent color on every window, was just wondering if there is a way to overwrite. But if that is black in 20H1 I'm okay with that

**Comment by Borkason** [comment]
In addition to the bottom white border, I now have 3 more borders, making the issue officially 4 times worse 😂

grafik

**Comment by linux-overuser** [comment]
Yes indeed, the border in dark mode is still white I've noticed, which is quite bothersome to look at. 
image

**Comment by Bebotron** [comment]
Version 0.9 has rolled out and my Windows Terminal still has this problem. Any ideas as to what the status of this issue is?
WT white borders
WT version

**Comment by greg904** [comment]
Yes, see #3425 and maybe PR #4577.

**Comment by Bebotron** [comment]
Thanks @greg904, so it sounds like its not a stable solution yet correct? Wondering if it might be best to sit tight a little longer until a new version of WT fixes this, or if it's worthwhile to attempt your solution in #4577

**Comment by greg904** [comment]
If you run the fix:
- you are running the dev or `master` version which is not stable and can have bugs
- on top of it you are running my fix which is not very tested (I made it quickly because I, too, want that bright border to go away :))

If you wait:
- [last release](https://github.com/microsoft/terminal/releases) was 2 days ago so I'm guessing the new release won't come in a few days
- maybe more stable

BTW, just to be clear:

With the fix, if you disable:
setting

You get this:
image

And if you enable it, you will have a border but now it will be blue:
image

So there still is a blue border but it is just like other apps:
image
