### PR TITLE
Shift the island up by 1px when maximized

### LINKED ISSUE #7422: 1 pixel gap around window prevents mouse from interacting with control buttons (minimize, maximize, close)
# Environment

```none
Windows build number: Win32NT, 10.0.19042.0 Microsoft Windows NT 10.0.19042.0
Windows Terminal version (if applicable): 1.1.2233.0
```

# Steps to reproduce

1. Maximize the window.
2. Move the mouse to the very top right corner of the screen and click to close the window.

# Expected behavior

Correct/typical behavior (e.g. for File Explorer, Edge, UWP apps, etc...) is that the mouse interacts with the window control buttons (minimize, maximize, close) when touching the top edge of the screen, or the top right corner. Meaning, the mouse can be put into the very top right corner of the screen, and when clicking, the close button is engaged and the window closes. For the Windows Terminal, there seems to be a 1pixel "gap" along the top/sides of the window that prevents this from working.

# Actual behavior

The close button does not go into a hover state with the mouse located there and the window does not close.

See example where mouse cursor is at top right corner of the screen but the close button is not "lit up" red:

mouse-cursor-in-top-right-corner

I see this on some apps here and there -- Nitro PDF is another example.

### PR DESCRIPTION
**Pull request by zadjii-msft**
For inexplicable reasons, the top row of pixels on our tabs, new tab
button, and caption buttons is totally unclickable. The mouse simply
refuses to interact with them. So when we're maximized, on certain
monitor configurations, this results in the top row of pixels not
reacting to clicks at all.

To obey Fitt's Law, we're gonna hackily shift the entire island up one
pixel. That will result in the top row of pixels in the window actually
being the _second_ row of pixels for those buttons, which will make them
clickable. It's perhaps not the right fix, but it works.

After discussion, we think this is a fine fix for this. We don't think
anyone's going to miss the top row of pixels on the TabView. The original
bug is painful enough for the subset of users it impacts that this is an
acceptable trade. Should a better fix be found, we can absolutely do that
instead.

Closes #7422

### CODE REVIEW

File: src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp [hunk 1]
```diff
@@ -360,7 +360,21 @@ void NonClientIslandWindow::_OnMaximizeChange() noexcept
 //   sizes of our child XAML Islands to match our new sizing.
 void NonClientIslandWindow::_UpdateIslandPosition(const UINT windowWidth, const UINT windowHeight)
 {
-    const auto topBorderHeight = Utils::ClampToShortMax(_GetTopBorderHeight(), 0);
+    const auto originalTopHeight = _GetTopBorderHeight();
+    // GH#7422
+    // !! BODGY !!
```
Comment (miniksa) [inline src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp:365]: I was about to say "did you include my magic keyword of `BODGY`"? 

Yes. Yes you did.

**Review by miniksa — APPROVED** [review]
I'll take it.

**Review by lhecker — APPROVED** [review]
