### PR TITLE
Bugfix: crash on copying resized selection

### LINKED ISSUE #1165: Crash on copy after selection goes offscreen because of resizing
# Environment

```none
Windows build number: [run "ver" at a command prompt]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce
1. Start terminal
2. Maximize terminal
3. Select something that will eventually go offscreen (i.e. top right corner)
4. Unmaximize terminal
5. Try pressing copy or right click

### PR DESCRIPTION
**Pull request by carlos-zamora**
## Summary of the Pull Request
The selection anchors would become outside of the new size. They didn't matter for rendering the selection, but they would crash on the copy because we would actually try to read the buffer in a non-existent space.

Solution: clamp the anchors at RENDER TIME
That way, if we have the window resize again AND the anchors are valid, draw them appropriately.
I think this is better than just clearing a selection after a resize event, BUT if you disagree, I guess we can add that in pretty easily.

 
## References
#1165 specifically mentions resizing so I'll close that one. Just be aware that there is a chance #1246  could be what's happening too.

## PR Checklist
* [x] Closes #1165 
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [x] Tests added/passed
* [x] Requires documentation to be updated
* [x] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Detailed Description of the Pull Request / Additional comments
- clamp when you're extracting data from buffer
- also moved the `_buffer->GetSize().RightInclusive()` out of the for loop so I guess it's more performant? 

## Validation Steps Performed
1. Maximize window
2. Create a scroll region (just do "dir" or "ls" a bunch)
3. Scroll to somewhere in the middle
4. Select top-left corner, then right-most side 3 lines down (so select 3 full lines)
5. Unmaximize window
6. Right-click to copy

Used to crash, now you should get all three lines in your clipboard.

NOTE: if you copy the same selection in a maximized state vs unmaximized state, it will be slightly different BECAUSE the right side of the buffer is now cropped.

### CODE REVIEW

File: src/cascadia/TerminalCore/Terminal.cpp [hunk 1]
```diff
@@ -515,13 +515,19 @@ std::vector<SMALL_RECT> Terminal::_GetSelectionRects() const
...
-    THROW_IF_FAILED(ShortAdd(_endSelectionPosition.Y, _endSelectionPosition_YOffset, &temp2));
+    SHORT y1;
+    SHORT y2;
+    THROW_IF_FAILED(ShortAdd(_selectionAnchor.Y, _selectionAnchor_YOffset, &y1));
+    THROW_IF_FAILED(ShortAdd(_endSelectionPosition.Y, _endSelectionPosition_YOffset, &y2));
+
+    // clamp X values to be within buffer bounds
+    const auto bufferWidth = _buffer->GetSize().RightInclusive();
+    SHORT x1 = std::clamp(_selectionAnchor.X, static_cast<SHORT>(0), bufferWidth);
+    SHORT x2 = std::clamp(_endSelectionPosition.X, static_cast<SHORT>(0), bufferWidth);
```
Comment (zadjii-msft) [inline src/cascadia/TerminalCore/Terminal.cpp]: So out of curiosity, if you maximize, then make a selection, then restore down, then re-maximize, the entire selection remains selected, correct?

Is this something we want?

File: src/cascadia/TerminalCore/Terminal.cpp [hunk 2]
```diff
@@ -515,13 +515,19 @@ std::vector<SMALL_RECT> Terminal::_GetSelectionRects() const
     }
 
     // Add anchor offset here to update properly on new buffer output
-    SHORT temp1, temp2;
-    THROW_IF_FAILED(ShortAdd(_selectionAnchor.Y, _selectionAnchor_YOffset, &temp1));
-    THROW_IF_FAILED(ShortAdd(_endSelectionPosition.Y, _endSelectionPosition_YOffset, &temp2));
+    SHORT y1;
+    SHORT y2;
```
Comment (zadjii-msft) [inline src/cascadia/TerminalCore/Terminal.cpp]: I'd probably prefer more descriptive names for `y1`, `y2`, `x1`, and `x2`

File: src/cascadia/TerminalCore/Terminal.cpp (hunk 1 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalCore/Terminal.cpp]: 1. **Yes**: The clamping happens at render time. So, the same selection would be in effect when you re-maximize it (assuming it's the same dimensions as before).

2. **Yes?**: We definitely want this PR because it fixes a crash that's really easy to get. (if you make a selection of the entire screen, it crashes w/out this change)

Where it gets weird is with wrapping text. Then, I think you won't really know what you've selected because the (x,y) position of the anchors stay the same, but the text changed locations. 

With regards to THAT issue I just mentioned, we have a few options I can think of:
(1) clear selection on resize - I think this is the easy way out but, I guess it works?
(2) update selection anchors on resize - we'd have to identify when text is (not) wrapping and update appropriately

Comment (zadjii-msft) [reply src/cascadia/TerminalCore/Terminal.cpp]: We could theoretically reflow the selection anchors the same way we attempt to reflow the cursor position when we handle a resize-with-reflow in conhost. (This is not code we have in Terminal today). I will add, that code is a bug factory, always has been, and I believe it always will be.

Though, conhost also just dismisses the selection so it doesn't have to deal with this problem. That's almost certainly not something would complain about, _right_?

File: src/cascadia/TerminalCore/Terminal.cpp (hunk 2 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalCore/Terminal.cpp]: Refactored so now we don't even need these temp variables :)
