### PR TITLE
Make sure to update the maximize button's visual state on launch

### LINKED ISSUE #3440: Windows Terminal does not open with button displaying "maximized" state
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.418]
Windows Terminal version (if applicable): 0.6.2951.0

```

# Steps to reproduce

Set `"launchMode": "maximized"` within `profiles.json`

# Expected behavior

Windows Terminal opens maximized.

# Actual behavior

Windows Terminal opens with maximum screen size, but not maximized (see screenshots).
wrong (actual implementation): wrong
correct: correct

### PR DESCRIPTION
**Pull request by zadjii-msft**
## Summary of the Pull Request
This is an enormously trivial nit - when we launch maximized, we don't draw the maximize button in the "restore" state.

This PR changes the terminal to manually update the Maximize button on launch, once the titlebar is added to the UI tree.

## PR Checklist
* [x] Closes #3440
* [x] I work here
* [ ] Tests added/passed
* [n/a] Requires documentation to be updated

### CODE REVIEW

File: src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp [hunk 1]
```diff
@@ -205,6 +205,11 @@ void NonClientIslandWindow::Initialize()
     _rootGrid.Children().Append(_titlebar);
 
     Controls::Grid::SetRow(_titlebar, 0);
+
+    // GH#3440 - When the titlebar is loaded (officially added to our UI tree),
+    // then make sure to update it's visual state to reflect if we're in the
+    // maximized state on launch.
+    _titlebar.Loaded([this](auto&&, auto&&) { _OnMaximizeChange(); });
```
Comment (DHowett) [inline src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp:212]: Scary that Loaded hasn't happened yet! Guess it makes sense tho.
