### PR TITLE
Check EnableHexNumpad before enabling it

### LINKED ISSUE #17762: CANARY: ALT+NUMPAD ADD is Broken
### Windows Terminal version

1.22.2334.0

### Windows build number

10.0.19045.4780

### Other Software

_No response_

### Steps to reproduce

Alt+NumpadAdd pressing combination is broken since Canary build terminal-1.22.2201.0
terminal-1.22.2191.0 - latest good
terminal-1.22.2201.0 - broken
...
terminal-1.22.2334.0 - broken

run utilities for getting codes DOWN/UP VK_CODES etc
press Alt key after press NumpadAdd and release NumpadAdd, press NumpadAdd and release NumpadAdd, press NumpadAdd and release NumpadAdd

### Expected Behavior

terminal-1.22.2191.0 - latest good:
21:42:56 KEY_EVENT_RECORD: Dn, 1, Vk="VK_ADD" [107/0x006B], Scan=0x004E uChar=[U='+' (0x002B): A='+' (0x2B)]
         Ctrl=0x00000002 (cAsac - ecns) (Windowed)
21:42:56 KEY_EVENT_RECORD: Dn, 1, Vk="VK_ADD" [107/0x006B], Scan=0x004E uChar=[U='+' (0x002B): A='+' (0x2B)]
         Ctrl=0x00000002 (cAsac - ecns) (Windowed)
21:42:57 KEY_EVENT_RECORD: Up, 1, Vk="VK_ADD" [107/0x006B], Scan=0x004E uChar=[U='+' (0x002B): A='+' (0x2B)]
         Ctrl=0x00000002 (cAsac - ecns) (Windowed)

### Actual Behavior

since terminal-1.22.2201.0  to latest canary build terminal-1.22.2334.0  is broken:

21:44:18 KEY_EVENT_RECORD: Up, 1, Vk="VK_ADD" [107/0x006B], Scan=0x004E uChar=[U='+' (0x002B): A='+' (0x2B)]
         Ctrl=0x00000002 (cAsac - ecns) (Windowed)
21:44:18 KEY_EVENT_RECORD: Up, 1, Vk="VK_ADD" [107/0x006B], Scan=0x004E uChar=[U='+' (0x002B): A='+' (0x2B)]
         Ctrl=0x00000002 (cAsac - ecns) (Windowed)
21:44:18 KEY_EVENT_RECORD: Up, 1, Vk="VK_ADD" [107/0x006B], Scan=0x004E uChar=[U='+' (0x002B): A='+' (0x2B)]
         Ctrl=0x00000002 (cAsac - ecns) (Windowed)

### PR DESCRIPTION
**Pull request by lhecker**
This just adds a quick registry check for `EnableHexNumpad`.

Depends on #17774
Closes #17762 (again)

## Validation Steps Performed
* Alt + NumpadAdd + 221E doesn't do anything ✅
* Set the `EnableHexNumpad` registry key
* Restart
* Alt + NumpadAdd + 221E inserts ∞ ✅

### CODE REVIEW

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 1]
```diff
@@ -1631,12 +1631,29 @@ namespace winrt::Microsoft::Terminal::Control::implementation
...
+                            DWORD size = sizeof(buffer);
+                            RegGetValueW(
+                                HKEY_CURRENT_USER,
+                                L"Control Panel\\Input Method",
+                                L"EnableHexNumpad",
+                                RRF_RT_REG_SZ,
+                                nullptr,
+                                &buffer[0],
+                                &size);
+                            return size == 4 && memcmp(&buffer[0], L"1", 4) == 0;
```
Comment (DHowett) [inline src/cascadia/TerminalControl/TermControl.cpp:1645]: my gosh, it's actually a string? wild

**Review by DHowett — APPROVED** [review]

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 1 above)
Comment (DHowett) [reply src/cascadia/TerminalControl/TermControl.cpp:1645]: Should we use any of the `wil` registry helpers here? or is that just overhead.

things like `wil::reg::try_get_value<string>` and co

Comment (lhecker) [reply src/cascadia/TerminalControl/TermControl.cpp:1645]: I wouldn't. It's trivial code like this. I could replace the check with a `wcsnlen` though...

**Review by carlos-zamora — APPROVED** [review]
