### PR TITLE
Fix RTF generation for Unicode characters

### LINKED ISSUE #12379: RTF formatted copy doesn't work for Unicode characters
### Windows Terminal version

_No response_

### Windows build number

_No response_

### Other Software

_No response_

### Steps to reproduce

Emit some fun Unicode stuff! Copy/paste it in RTF format. Notice that it is _destroyed._

### Expected Behavior

_No response_

### Actual Behavior

We may need to update the RTF generator per this [O'Reilly pocket guide on RTF](https://www.oreilly.com/library/view/rtf-pocket-guide/9781449302047/ch01.html#unicode_in_rtf).

### PR DESCRIPTION
**Pull request by ianjoneill**
## Summary of the Pull Request
Fixes RTF generation for text with Unicode characters.

## PR Checklist
* [x] Closes #12379
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [x] Tests added/passed
* [ ] Documentation updated. If checked, please file a pull request on [our docs repo](https://github.com/MicrosoftDocs/terminal) and link it here: #xxx
* [ ] Schema updated.
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Validation Steps Performed
Added some unit tests.

Ran the following in PowerShell and copied the emitted text into WordPad.
```pwsh
echo "This is some Ascii \ {}`nLow code units: á é í ó ú `u{2b81} `u{2b82}`nHigh code units: `u{a7b5} `u{a7b7}`nSurrogates: `u{1f366} `u{1f47e} `u{1f440}"
```

### CODE REVIEW

**Comment by ianjoneill** [comment]
Video of the validation:

https://user-images.githubusercontent.com/5821575/155839988-ab000af2-80ed-4881-b8ee-f33f9815699c.mp4

**Review by zadjii-msft — APPROVED** [review]

File: src/buffer/out/textBuffer.cpp [hunk 1]
```diff
@@ -2146,6 +2134,34 @@ std::string TextBuffer::GenRTF(const TextAndColor& rows, const int fontHeightPoi
...
+            }
+        }
+        else if (codeUnit <= 32767)
+        {
+            contentBuilder << "\\u" << std::to_string(codeUnit) << "?";
+        }
+        else
+        {
+            contentBuilder << "\\u" << std::to_string(codeUnit - 65536) << "?";
+        }
```
Comment (lhecker) [inline src/buffer/out/textBuffer.cpp:2161]: Since C++20, signed integers are defined to use two's complement just like unsigned integers (P0907R4).
You can rewrite this code as:
```cpp
else
{
    // Windows uses unsigned wchar_t - RTF uses signed ones.
    contentBuilder << "\\u" << std::to_string(til::bit_cast<int16_t>(codeUnit)) << "?";
}
```

**Review by lhecker — APPROVED** [review]

File: src/buffer/out/textBuffer.cpp (hunk 1 above)
Comment (ianjoneill) [reply src/buffer/out/textBuffer.cpp]: Done

**Comment by lhecker** [comment]
You can also remove the extra `else if (codeUnit <= 32767)` branch now that you use the bit-cast.
But this is really more like an "interesting nit" than anything. Since I approved it, you don't have to address my feedback, unless you feel the same way. 🙂

**Comment by ianjoneill** [comment]
Good point - I didn't engage brain - done (again)
