### PR TITLE
Manually pass mouse wheel messages to TermControls

### LINKED ISSUE #979: Touchpad scrolling not possible
# Environment

Windows build number: Microsoft Windows [Version 10.0.18898.1000]
Windows Terminal version (if applicable): pulled and built today (WindowsTerminalDev_0.0.1.0_x64__8wekyb3d8bbwe)

# Steps to reproduce

Not entirely sure if this is intended behaviour or an issue to other users but I am not able to scroll through the new terminal with my touchpad on my Notebook (Alienware).

It works with my mouse but not with the touchpad. I can scroll through the native console/ poweshell though. Can somebody reproduce this?

# Expected behavior

That I can scroll through the curren window-history using two-finger-touch on the touchpad.

# Actual behavior

It wont scroll.

### PR DESCRIPTION
**Pull request by zadjii-msft**
## Summary of the Pull Request

As we've learned in #979, not all touchpads are created equal. Some of them have bad drivers that makes scrolling inactive windows not work. For whatever reason, these devices think the Terminal is all one giant inactive window, so we don't get the mouse wheel events through the XAML stack. We do however get the event as a `WM_MOUSEWHEEL` on those devices (a message we don't get on devices with normally functioning trackpads).

This PR attempts to take that `WM_MOUSEWHEEL` and manually dispatch it to the `TermControl`, so we can at least scroll the terminal content.

Unfortunately, this solution is not very general purpose. This only works to scroll controls that manually implement our own `IMouseWheelListener` interface. As we add more controls, we'll need to continue manually implementing this interface, until the underlying XAML Islands bug is fixed. **I don't love this**. I'd rather have a better solution, but it seems that we can't synthesize a more general-purpose `PointerWheeled` event that could get routed through the XAML tree as normal. 

## References

* #2606 and microsoft/microsoft-ui-xaml#2101 - these bugs are also tracking a similar "inactive windows" / "scaled mouse events" issue in XAML

## PR Checklist
* [x] Closes #979
* [x] I work here
* [ ] Tests added/passed
* [n/a] Requires documentation to be updated

## Detailed Description of the Pull Request / Additional comments

I've also added a `til::point` conversion _to_ `winrt::Windows::Foundation::Point`, and some scaling operators for `point`

## Validation Steps Performed

* It works on my HP Spectre 2017 with a synaptics trackpad
  - I also made sure to test that `tmux` works in panes on this laptop
* It works on my slaptop, and DOESN'T follow this hack codepath on this machine.

### CODE REVIEW

File: src/inc/til/point.h [hunk 1]
```diff
@@ -140,6 +140,50 @@ namespace til // Terminal Implementation Library. Also: "Today I Learned"
             return point{ x, y };
         }
 
+        point operator*(const int& scale) const
```
Comment (miniksa) [inline src/inc/til/point.h]: Nnnnn should this be a template the same way that `CheckMul` is a template so it can accept any basic type?

Comment (zadjii-msft) [reply src/inc/til/point.h]: I was seriously just thinking about that. I'm not positive I'm skilled enough in template-fu but I'll give it a shot

File: src/cascadia/TerminalControl/IMouseWheelListener.idl [hunk 2]
```diff
@@ -0,0 +1,16 @@
+// Copyright (c) Microsoft Corporation.
+// Licensed under the MIT license.
+
+namespace Microsoft.Terminal.TerminalControl
+{
+
+    // This interface is a hack for GH#979. Controls should implement this
+    // interface to be able to be notified of mousewheel events even on devices
+    // who's trackpads won't scroll inactive windows.
```
[the remark this answers is not in the document]
Comment (zadjii-msft) [reply src/cascadia/TerminalControl/IMouseWheelListener.idl]: Sure, I just filed https://github.com/microsoft/microsoft-ui-xaml/issues/2172 upstream to track them, I'll add another on us.

File: src/cascadia/TerminalControl/IMouseWheelListener.idl [hunk 3]
```diff
@@ -0,0 +1,16 @@
...
+
+    // This interface is a hack for GH#979. Controls should implement this
+    // interface to be able to be notified of mousewheel events even on devices
+    // who's trackpads won't scroll inactive windows.
+
+    [uuid("65b8b8c5-988f-43ff-aba9-e89368da1598")]
+    interface IMouseWheelListener
+    {
+        Boolean OnMouseWheel(Windows.Foundation.Point coord, Int32 delta);
+    }
```
[the remark this answers is not in the document]
Comment (zadjii-msft) [reply src/cascadia/TerminalControl/IMouseWheelListener.idl]: Eh, they're handled differently. The IF7Listener tries to tunnel the F7 down to the leaf-most focused control, then bubble it up till someone handles it. This on is just handled by whichever control is physically underneath the mouse. I could imagine something like the Command Palette not caring about F7, but _does_ care about scrolling.

File: src/inc/til/point.h (hunk 1 above)
Comment (miniksa) [reply src/inc/til/point.h]: I'm usually not **that** skilled in template-fu. In this case, you could probably steal some of the template declaration from `CheckMul` itself by looking how it is defined.

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 4]
```diff
@@ -892,6 +892,18 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
...
+    //     _value(0)
+    // {
+    //     // static_cast to a uint32_t because we can't use the WI_IsFlagSet
+    //     // macro directly with a VirtualKeyModifiers
+    //     const auto m = static_cast<uint32_t>(modifiers);
+    //     _value |= WI_IsFlagSet(m, static_cast<uint32_t>(VirtualKeyModifiers::Shift)) ? SHIFT_PRESSED : 0;
+    //     // Since we can't differentiate between the left & right versions of Ctrl & Alt in a VirtualKeyModifiers
+    //     _value |= WI_IsFlagSet(m, static_cast<uint32_t>(VirtualKeyModifiers::Menu)) ? LEFT_ALT_PRESSED : 0;
+    //     _value |= WI_IsFlagSet(m, static_cast<uint32_t>(VirtualKeyModifiers::Ctrl)) ? LEFT_CTRL_PRESSED : 0;
+    // }
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalControl/TermControl.cpp]: big comment

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 5]
```diff
@@ -1155,28 +1167,56 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
...
         {
-            _TrySendMouseEvent(point);
             args.Handled(true);
-            return;
         }
+    }
 
-        const auto delta = point.Properties().MouseWheelDelta();
+    // Method Description:
+    // - Actually handle a scrolling event, with from a mouse wheel or a
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalControl/TermControl.cpp]:
```suggestion
    // - Actually handle a scrolling event, whether from a mouse wheel or a

```

File: src/cascadia/WindowsTerminal/IslandWindow.cpp [hunk 6]
```diff
@@ -326,6 +326,38 @@ void IslandWindow::OnSize(const UINT width, const UINT height)
         _windowCloseButtonClickedHandler();
         return 0;
     }
+    case WM_MOUSEWHEEL:
```
Comment (DHowett-MSFT) [inline src/cascadia/WindowsTerminal/IslandWindow.cpp]: so this doesn't break with surface devices, but _does it change with a wired mouse with a wheel?_

File: src/cascadia/WindowsTerminal/AppHost.cpp [hunk 7]
```diff
@@ -338,3 +338,43 @@ void AppHost::_ToggleFullscreen(const winrt::Windows::Foundation::IInspectable&,
...
+        for (const auto& e : elems)
+        {
+            // If that element has implemented IMouseWheelListener, call OnMouseWheel on that element.
+            if (auto control{ e.try_as<winrt::Microsoft::Terminal::TerminalControl::IMouseWheelListener>() })
+            {
+                // Translate the event to the coordinate space of the control
+                // we're attempting to dispatch it to
+                const auto transform = e.TransformToVisual(nullptr);
+                const auto controlOrigin = transform.TransformPoint(til::point{ 0, 0 });
+                const til::point offsetPoint{ ::base::ClampSub(coord.x(), controlOrigin.X), ::base::ClampSub(coord.y(), controlOrigin.Y) };
```
Comment (miniksa) [inline src/cascadia/WindowsTerminal/AppHost.cpp]: Add a clamped sub method to til::point instead of doing it on the outside? I feel like this line should read

```
const auto offsetPoint = coord.ClampSub(controlOrigin);
```

File: src/cascadia/WindowsTerminal/IslandWindow.cpp [hunk 8]
```diff
@@ -326,6 +326,38 @@ void IslandWindow::OnSize(const UINT width, const UINT height)
...
+        // Important! Do not use the LOWORD or HIWORD macros to extract the x-
+        // and y- coordinates of the cursor position because these macros return
+        // incorrect results on systems with multiple monitors. Systems with
+        // multiple monitors can have negative x- and y- coordinates, and LOWORD
+        // and HIWORD treat the coordinates as unsigned quantities.
+        const til::point eventPoint{ GET_X_LPARAM(lparam), GET_Y_LPARAM(lparam) };
+        // This mouse event is relative to the display origin, not the window. Convert here.
+        const til::rectangle windowRect{ GetWindowRect() };
+        const auto origin = windowRect.origin();
+        const auto relative = eventPoint - origin;
```
Comment (miniksa) [inline src/cascadia/WindowsTerminal/IslandWindow.cpp]: This can throw. Does the outer message loop catch exceptions or will this bubble out the top?

File: src/cascadia/WindowsTerminal/pch.h [hunk 9]
```diff
@@ -30,6 +30,8 @@ Module Name:
 #include <shellscalingapi.h>
 #include <windowsx.h>
 
+// Manually include til after we include Windows.Foundation to give it winrt superpowers
+#define BLOCK_TIL
```
Comment (miniksa) [inline src/cascadia/WindowsTerminal/pch.h]: Can you file a follow-on task to perhaps make a second `LibraryIncludes.h` that includes WIL and TIL and have it at the bottom of every `precomp.h`?

I feel like you've done this to like 6 more projects as of this PR and I bet it will just keep coming.

We should probably put all super-powered headers at the bottom of every `precomp.h`.

File: src/inc/til/point.h [hunk 10]
```diff
@@ -140,6 +140,32 @@ namespace til // Terminal Implementation Library. Also: "Today I Learned"
             return point{ x, y };
         }
 
+        template<typename T>
+        point operator*(const T& scale) const
+        {
+            static_assert(std::is_arithmetic<T>::value, "Type must be arithmetic");
```
Comment (miniksa) [inline src/inc/til/point.h]: Excellent.

File: src/cascadia/WindowsTerminal/pch.h (hunk 9 above)
Comment (zadjii-msft) [reply src/cascadia/WindowsTerminal/pch.h]: Ask and you shall receive: #5182

File: src/cascadia/WindowsTerminal/AppHost.cpp (hunk 7 above)
Comment (zadjii-msft) [reply src/cascadia/WindowsTerminal/AppHost.cpp]: Okay so the real reason I was doing this _wasn't_ for clamped math but more because I couldn't use the `float`s from the `Windows::Foundation::Point`. Now that I _can_, I'll try/catch this appropriately.

File: src/cascadia/WindowsTerminal/IslandWindow.cpp (hunk 6 above)
Comment (zadjii-msft) [reply src/cascadia/WindowsTerminal/IslandWindow.cpp]: I can't explain it, but yea this isn't hit for a normal mouse wheel either. Maybe this is what `MouseInPointer` does? Maybe when XAML _does_ handle it, it handles it via the `WM_POINTERWHEEL`, but then if it doesn't, it arrives to us as a `WM_MOUSEWHEEL`? Maybe that's the reason these devices are broken in the first place? I have no idea. 

Regardless, this is working as expected.

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 11]
```diff
@@ -1193,7 +1193,7 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
     }
 
     // Method Description:
-    // - Actually handle a scrolling event, with from a mouse wheel or a
+    // - Actually handle a scrolling event, wether from a mouse wheel or a
```
Comment (miniksa) [inline src/cascadia/TerminalControl/TermControl.cpp:1196]:
```suggestion
    // - Actually handle a scrolling event, whether from a mouse wheel or a

```

And I don't know how spellcheck bot didn't catch this. Should figure that out too.

Comment (zadjii-msft) [reply src/cascadia/TerminalControl/TermControl.cpp:1196]: Oh boy this and a VTE thing I just automerged over in #5200, that's weird. Well `master` is busted now, so I'll go fix that up.

**Comment by msbrunoalves** [comment]
Just tried the release, it's fixed on my HP laptop with Synaptics drivers, thank you!
