### PR TITLE
Restore off-the-top behavior for VT mouse mode

### LINKED ISSUE #17744: Mouse events are not sent when the mouse is outside the top of the WT
### Windows Terminal version

Versão: 1.20.11781.0

### Windows build number

10.0.22631.0

### Other Software

_No response_

### Steps to reproduce

Please clone this GitHub repository [MouseTests](https://github.com/BDisp/MouseTests.git) and run. Keep pressing the mouse inside the console and move around it, as the gif show.

### Expected Behavior

The mouse events should be sent while the mouse button is pressed and moving inside or outside the console until it's released.

### Actual Behavior

The mouse events are sent as expected except from outside of the console on top.

MouseTests

With the `conhost` the mouse events are always sent from anywhere while the mouse isn't released.

### PR DESCRIPTION
**Pull request by DHowett**
PR #10642 and #11290 introduced an adjustment for the cursor position used to generate VT mouse mode events.

One of the decisions made in those PRs was to only send coordinates where Y was >= 0, so if you were off the top of the screen you wouldn't get any events. However, terminal emulators are expected to send _clamped_ events when the mouse is off the screen. This decision broke clamping Y to 0 when the mouse was above the screen.

The other decision was to only adjust the Y coordinate if the core's `ScrollOffset` was greater than 0. It turns out that `ScrollOffset` _is 0_ when you are scrolled all the way back in teh buffer. With this check, we would clamp coordinates properly _until the top line of the scrollback was visible_, at which point we would send those coordinates over directly. This resulted in the same weird behavior as observed in #10190.

I've fixed both of those things. Core is expected to receive negative coordinates and clamp them to the viewport. ScrollOffset should never be below 0, as it refers to the top visible buffer line.

In addition to that, #17744 uncovered that we were allowing autoscrolling to happen even when VT mouse events were being generated. I added a way for `ControlInteractivity` to halt further event processing. It's crude.

Refs #10190
Closes #17744

### CODE REVIEW

**Review by zadjii-msft — APPROVED** [review]

File: src/cascadia/TerminalControl/ControlInteractivity.cpp [hunk 1]
```diff
@@ -334,14 +334,17 @@ namespace winrt::Microsoft::Terminal::Control::implementation
                                             const ::Microsoft::Terminal::Core::ControlKeyStates modifiers,
                                             const bool focused,
                                             const Core::Point pixelPosition,
-                                            const bool pointerPressedInBounds)
+                                            const bool pointerPressedInBounds,
+                                            bool& suppressFurtherHandling)
```
Comment (lhecker) [inline src/cascadia/TerminalControl/ControlInteractivity.cpp:338]: If we change this to a return value it'd probably be worth adding a comment that "return true" means "suppress further handlings" just in case this helps someone in the future.

**Review by lhecker — APPROVED** [review]

**Review by PankajBhojwani — APPROVED** [review]

**Review by lhecker — APPROVED** [review]

**Comment by DHowett** [comment]
Honestly the 100% correct behavior is to accept *drag and move* events off the top of the buffer but not click or button events.

**Comment by DHowett** [comment]
Specifically, drags that start in the viewport and move outside it.

**Comment by BDisp** [comment]
> Honestly the 100% correct behavior is to accept _drag and move_ events off the top of the buffer but not click or button events.

The main reason to caught mouse events above the top is for example to get button released event to take some action. I hope the mouse button events are available. Thanks.
