### PR TITLE
Replace the HRGN-based titlebar cutout with an overlay window

### LINKED ISSUE #2100: When a dialog is open, the titlebar is the wrong color
related to #1625.

image

This one's tricky - the Background of the TabRow doesn't actually change here, it's just being combined with the overlay of the ContentDialog. We'd have to compose that color ourselves in the NonClientWindow class.

### LINKED ISSUE #4744: Investigate Acrylic in titlebar / not using a `HRGN` for the titlebar
# Description of the new feature/enhancement

The title says it all.
This is another really good thing that Windows Terminal could borrow from [felixse/FluentTerminal](https://github.com/felixse/FluentTerminal).
This would basically expand the current terminal's background (including all the modifications done to it, for example a custom background image or opacity level) over to the titlebar (including the minimize, maximize and close icons). 
This would make it consistent with other Windows apps following Fluent Design (think of the Settings app and its titlebar), apart from making it look really cool.
Attached here is a screenshot of Fluent Terminal (with acrylic blur and without any background image):

Screenshot (145)

# Proposed technical implementation details (optional)

While digging for similar requests (I couldn't find an issue that addressed this specifically), I read somewhere that such a thing isn't possible given the architecture. Well, if that's the case, too bad. But I'm still opening the issue so that this remains documented somewhere separately.

### PR DESCRIPTION
**Pull request by DHowett-MSFT**
Copying the description from the inimitable @greg904 in #4778.

## Summary of the Pull Request

My understanding is that the XAML framework uses another way of getting mouse input that doesn't work with `WM_SYSCOMMAND` with `SC_MOVE`. It looks like it "steals" our mouse messages like `WM_LBUTTONDOWN`.

Before, we were cutting (with `HRGN`s) the drag bar part of the XAML islands window in order to catch mouse messages and be able to implement the drag bar that can move the window. However this "cut" doesn't only apply to input (mouse messages) but also to the graphics so we had to paint behind with the same color as the drag bar using GDI to hide the fact that we were cutting the window.

The main issue with this is that we have to replicate exactly the rendering on the XAML drag bar using GDI and this is bad because:
1. it's hard to keep track of the right color: if a dialog is open, it will cover the whole window including the drag bar with a transparent white layer and it's hard to keep track of those things.
2. we can't do acrylic with GDI

So I found another method, which is to instead put a "drag window" exactly where the drag bar is, but on top of the XAML islands window (in Z order). I've found that this lets us receive the `WM_LBUTTONDOWN` messages.

## PR Checklist
* [x] Closes #4744. Closes #2100. Closes #4778 (superseded.)
* [x] CLA signed
* [x] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #4744

## Detailed Description of the Pull Request / Additional comments

Picture's worth a thousand words.

Available with this PR:
image

Available after version 1, _if we so desire_:

image

## Validation Steps Performed
DH: Tested manually in all configurations (debug, release) with snap, drag, move, double-click and double-click on the resize handle. Tested at 200% scale.

* [x] Need to test DPI transitions still.

### CODE REVIEW

File: src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp [hunk 1]
```diff
@@ -475,6 +532,48 @@ int NonClientIslandWindow::_GetResizeHandleHeight() const noexcept
...
+[[nodiscard]] LRESULT NonClientIslandWindow::_OnSetCursor(WPARAM wParam, LPARAM lParam) const noexcept
+{
+    if (LOWORD(lParam) == HTCLIENT)
+    {
+        // Get the cursor position from the _last message_ and not from
+        // `GetCursorPos` (which returns the cursor position _at the
+        // moment_) because if we're lagging behind the cursor's position,
+        // we still want to get the cursor position that was associated
+        // with that message at the time it was sent to handle the message
+        // correctly.
```
Comment (zadjii-msft) [inline src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp:547]: this is mental

File: src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp [hunk 2]
```diff
@@ -32,6 +30,117 @@ NonClientIslandWindow::~NonClientIslandWindow()
...
+    }
+
+    if (nonClientMessage.has_value())
+    {
+        POINT clientPt = { GET_X_LPARAM(lparam), GET_Y_LPARAM(lparam) };
+
+        POINT screenPt = clientPt;
+        if (ClientToScreen(window, &screenPt))
+        {
+            const auto parentWindow{ GetAncestor(window, GA_PARENT) };
```
Comment (zadjii-msft) [inline src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp:106]: This is just a formality, right? Like, we _know_ this is going to just return `GetWindowsHandle()` right?

File: src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp [hunk 3]
```diff
@@ -32,6 +30,117 @@ NonClientIslandWindow::~NonClientIslandWindow()
...
+    if (_IsTitlebarVisible() && rect.size().area() > 0)
+    {
+        SetWindowPos(_dragBarWindow.get(),
+                     HWND_TOP,
+                     rect.left<int>(),
+                     rect.top<int>() + _GetTopBorderHeight(),
+                     rect.width<int>(),
+                     rect.height<int>(),
+                     SWP_NOACTIVATE | SWP_SHOWWINDOW);
+        SetLayeredWindowAttributes(_dragBarWindow.get(), 0, 255, LWA_ALPHA);
```
Comment (zadjii-msft) [inline src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp:136]: Do we need this call on every resize? or once when it's created?

File: src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp (hunk 2 above)
Comment (DHowett-MSFT) [reply src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp:106]: So the trick here is this isn’t a member function and doesn’t have access to `this`

File: src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp (hunk 3 above)
Comment (DHowett-MSFT) [reply src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp:136]: ApplicationFrameHost does it on resize, weird enough.

**Comment by DHowett-MSFT** [comment]
I tested fullscreen, but not from maximized. I’ll add it to the list.

File: src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp (hunk 3 above)
Comment (zadjii-msft) [reply src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp:136]: Oh if you're using their code as reference then yea, I'll trust that as the word of god

File: src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp (hunk 2 above)
Comment (zadjii-msft) [reply src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp:106]: Oh derp, thanks for clearing that up ☺️

Comment (jsoref) [reply src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp:106]: Is it worth commenting to that effect?

Comment (DHowett-MSFT) [reply src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp:106]: You know, given our plans for this it might be better to just make this a member and do the window data pointer thing anyway.

**Comment by DHowett-MSFT** [comment]
@zadjii-msft tested, passed:

* [x] DPI switch
* [x] fullscreen from maximize
* [x] really leaning hard on the f11 button to try to break it

File: src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp [hunk 4]
```diff
@@ -475,6 +551,48 @@ int NonClientIslandWindow::_GetResizeHandleHeight() const noexcept
...
+        // Get the cursor position from the _last message_ and not from
+        // `GetCursorPos` (which returns the cursor position _at the
+        // moment_) because if we're lagging behind the cursor's position,
+        // we still want to get the cursor position that was associated
+        // with that message at the time it was sent to handle the message
+        // correctly.
+        const auto screenPtDword = GetMessagePos();
+        POINT screenPt = { GET_X_LPARAM(screenPtDword), GET_Y_LPARAM(screenPtDword) };
+
+        LRESULT hitTest = SendMessage(GetWindowHandle(), WM_NCHITTEST, 0, MAKELPARAM(screenPt.x, screenPt.y));
```
Comment (miniksa) [inline src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp:570]: Why isn't the pos just forwarded straight into the `lParam` of the `SendMessage` call? It doesn't look like it's used for anything else and this is just pulling it apart to put it back together again, as far as I can read.

Comment (DHowett-MSFT) [reply src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp:570]: Great question; I stole this from Greg. It made me want to write a til<->LPARAM conversion but I didn’t realize I’d just be wasting cycles going back and forth.

Comment (DHowett-MSFT) [reply src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp:570]: Probably a vestige from when he was doing manual management of the hit testing

Comment (greg904) [reply src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp]: I don't see any reason why I wrote it like that either. You're probably right, maybe I wanted to see the value in my debugger or I wrote the code differently and I refactored something.

**Comment by yoshiask** [comment]
How does this work with Tablet Mode? Does it still use acrylic in the titlebar?

**Comment by DHowett** [comment]
This changes nothing about tablet mode.

**Comment by rovecode** [comment]
Did these changes make it into the release? 

Do they exist at the moment? I do not see acrylic in versions 1.4+

Best regards,
Roman S

**Comment by DHowett** [comment]
@rovecode this change did not add acrylic to the title bar. This change removed a technical roadblock to having acrylic in the title bar.

**Comment by rovecode** [comment]
@DHowett. OK. But acrylic in the title bar is not planned?

**Comment by zadjii-msft** [comment]
@rovecode We're planning for acrylic in the titlebar as a part of a broader "theming" feature set, see #3327 and #5772 for more details
