### PR TITLE
XtermEngine: Explicitly emit cursor state on the first frame

### LINKED ISSUE #12401: Blinking cursor shows up in TUI programs (where it shouldn't) in 1.13
### Windows Terminal version

1.13.10336.0

### Windows build number

10.0.19044.1348

### Other Software

scoop install [vifm](https://vifm.info)

_and_

scoop install [ncspot](https://github.com/hrkfdn/ncspot)

### Steps to reproduce

Just launch the programs. See below.

cursor

cursor1c

### Expected Behavior

The cursor wasn't showing up (at all) in 1.12 Preview. It shouldn't appear.

### Actual Behavior

The cursor appears.

Possibly related - https://github.com/microsoft/terminal/issues/12372 ?

### PR DESCRIPTION
**Pull request by lhecker**
This commit fixes an issue, where we failed to emit a DECTCEM sequence to hide
the cursor if it was hidden before XtermEngine's first frame was finalized.
Even in such cases we need to emit a DECTCEM sequence
in order to ensure we're in a consistent state.

## PR Checklist
* [x] Closes #12401
* [x] I work here
* [x] Tests added/passed

## Validation Steps Performed
* Added test✅
* Run #12401's repro steps around 30 times✅

### CODE REVIEW

File: src/renderer/vt/XtermEngine.hpp [hunk 1]
```diff
@@ -54,9 +54,18 @@ namespace Microsoft::Console::Render
         [[nodiscard]] HRESULT WriteTerminalW(const std::wstring_view str) noexcept override;
 
     protected:
+        // I'm using a non-class enum here, so that the values
+        // are trivially convertible and comparable to bool.
+        enum Tribool : uint8_t
+        {
+            Tribool_False = 0,
+            Tribool_True,
+            Tribool_Invalid,
```
Comment (DHowett) [inline src/renderer/vt/XtermEngine.hpp:63]: invalid is truthy! that makes sense for this case, but it is different from an `optional<bool>` and SQL's nullable bool

should we rename it to `CursorState` and be very specific on the inner constant names?

**Review by DHowett — COMMENTED** [review]
This is still valid even if the cursor visibility is changed DURING the first frame, right? Should we test that case too?

File: src/renderer/vt/XtermEngine.hpp (hunk 1 above)
Comment (zadjii-msft) [reply src/renderer/vt/XtermEngine.hpp:63]: Yea that's kinda my takeaway as well - Either this should be just a plain old optional or an enum, right?

Comment (lhecker) [reply src/renderer/vt/XtermEngine.hpp:63]: I mean it is an enum, I just wanted to reduce the amount of code I'm refactoring for... reasons. Ya know.
I'll make it an `enum class` then.

Comment (lhecker) [reply src/renderer/vt/XtermEngine.hpp]: Turns out that this was really simple... I removed the assertions from the unit test, since we can already observe the correctness of the algorithm by the way it emits escape sequences to us.

**Review by DHowett — COMMENTED** [review]
i think i understand

**Review by DHowett — APPROVED** [review]

**Review by zadjii-msft — APPROVED** [review]
