### PR TITLE
Manually initialize the warnings vector to prevent a crash on launch

### LINKED ISSUE #8986: Terminal v1.5.10271.0 crashes on startup due to settings.json load bug
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): 1.5.10271.0
```

# Steps to reproduce

Add an empty object to the `schemes` option list

As an example I've picked the default configuration and only changed `"schemes": []` into `"schemes": [{}]"`
```
// This file was initially generated by Windows Terminal 1.1.2021.0
// It should still be usable in newer versions, but newer versions might have additional
// settings, help text, or changes that you will not see unless you clear this file
// and let us generate a new one for you.

// To view the default settings, hold "alt" while clicking on the "Settings" button.
// For documentation on these settings, see: https://aka.ms/terminal-documentation
{
    "$schema": "https://aka.ms/terminal-profiles-schema",

    "defaultProfile": "{07b52e3e-de2c-5db4-bd2d-ba144ed6c273}",

    // You can add more global application settings here.
    // To learn more about global settings, visit https://aka.ms/terminal-global-settings

    // If enabled, selections are automatically copied to your clipboard.
    "copyOnSelect": false,

    // If enabled, formatted data is also copied to your clipboard
    "copyFormatting": false,

    "theme": "dark",

    // A profile specifies a command to execute paired with information about how it should look and feel.
    // Each one of them will appear in the 'New Tab' dropdown,
    //   and can be invoked from the commandline with `wt.exe -p xxx`
    // To learn more about profiles, visit https://aka.ms/terminal-profile-settings
    "profiles":
    {
        "defaults":
        {
            // Put settings here that you want to apply to all profiles.
        },
        "list":
        [
            {
                "guid": "{07b52e3e-de2c-5db4-bd2d-ba144ed6c273}",
                "hidden": false,
                "name": "Ubuntu-20.04",
                "source": "Windows.Terminal.Wsl",
                "colorScheme": "Solarized Dark",
                "fontFace": "Droid Sans Mono for Powerline",
                "fontSize": 11,
                "fontWeight": "light",
                "antialiasingMode": "cleartype",
                "startingDirectory": "//wsl$/Ubuntu-20.04/home/baskiers/",
                "historySize": 99001
            },
            {
                // Make changes here to the powershell.exe profile.
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "name": "Windows PowerShell",
                "commandline": "powershell.exe",
                "hidden": false
            },
            {
                // Make changes here to the cmd.exe profile.
                "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
                "name": "Command Prompt",
                "commandline": "cmd.exe",
                "hidden": false
            },
            {
                "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
                "hidden": false,
                "name": "Azure Cloud Shell",
                "source": "Windows.Terminal.Azure"
            }
        ]
    },

    // Add custom color schemes to this array.
    // To learn more about color schemes, visit https://aka.ms/terminal-color-schemes
    "schemes": [{}],

    // Add custom keybindings to this array.
    // To unbind a key combination from your defaults.json, set the command to "unbound".
    // To learn more about keybindings, visit https://aka.ms/terminal-keybindings
    "keybindings":
    [
        // Copy and paste are bound to Ctrl+Shift+C and Ctrl+Shift+V in your defaults.json.
        // These two lines additionally bind them to Ctrl+C and Ctrl+V.
        // To learn more about selection, visit https://aka.ms/terminal-selection
        { "command": {"action": "copy", "singleLine": false }, "keys": "ctrl+c" },
        { "command": "paste", "keys": "ctrl+v" },

        // Press Ctrl+F to open the search box
        { "command": "find", "keys": "ctrl+f" },

        { "command": { "action": "newTab", "index": 0 }, "keys": "ctrl+t" },
        // Press Alt+Shift+D to open a new pane.
        // - "split": "auto" makes this pane open in the direction that provides the most surface area.
        // - "splitMode": "duplicate" makes the new pane use the focused pane's profile.
        // To learn more about panes, visit https://aka.ms/terminal-panes
        { "command": { "action": "splitPane", "split": "auto", "splitMode": "duplicate" }, "keys": "ctrl+shift+d" },

        // Unbound
        { "command": "unbound", "keys": "alt+shift+esc" }
    ]
}
```

# Expected behavior

Terminal starts up.

The schema does validate on the JSON Schema definition (https://aka.ms/terminal-profiles-schema). If this configuration is invalid the schema definition should reflect that.

# Actual behavior

The terminal instantly crashes on startup.

I've used this configuration for around half a year without issues.
This issue could be a subset of #8358, although I started experiencing this bug only in the latest version of the Terminal.

### PR DESCRIPTION
**Pull request by zadjii-msft**
## Summary of the Pull Request

Oops, winrt `IVector`s need to be manually initialized, when default-constructed `std::vector`s didn't. Simple oversight.

## PR Checklist
* [x] Closes #8986
* [x] I work here
* [x] A test would be great but ain't nobody got time for that.
* [n/a] Requires documentation to be updated

## Validation Steps Performed
Ran the terminal with 
```json

    "schemes" :
    [ {} ]
```
First the crash repro'd, now it doesn't.

### CODE REVIEW

**Comment by zadjii-msft** [comment]
@DHowett INTERESTING, the bot did _not_ transfer the z*Service-Consider labels, headsup

**Comment by DHowett** [comment]
Thanks for the h/u. What the _heck_ did spellbot drink?

File: src/cascadia/TerminalApp/TerminalPage.cpp [hunk 1]
```diff
@@ -2410,7 +2410,7 @@ namespace winrt::TerminalApp::implementation
                                                                 IVectorView<Profile> profiles,
                                                                 IMapView<winrt::hstring, ColorScheme> schemes)
     {
-        IVector<SettingsLoadWarnings> warnings;
+        IVector<SettingsLoadWarnings> warnings{ winrt::single_threaded_vector<SettingsLoadWarnings>() };
```
Comment (DHowett) [inline src/cascadia/TerminalApp/TerminalPage.cpp:2413]: I hate that we're heap allocating a thing that in most instances will not be used at all, but it fixes a bug and I cannot die on the hill of purity.

**Review by DHowett — APPROVED** [review]

**Review by carlos-zamora — APPROVED** [review]
Wow, this is the only place we did this. Good to know haha.
