### PR TITLE
Make the Pane inactive border respect the `theme.window.applicationTheme`

### LINKED ISSUE #3917: Panel split background ignores `requestedTheme`, follows system app mode
# Environment

```none
Windows build number: 10.0.18362.476
Windows Terminal version (if applicable): 0.7.3382.0
```

# Steps to reproduce

Have Windows configured in "light mode", and configure Terminal with `requestedTheme` set to `dark`. Split a tab in two or more panels.

# Expected behavior

The split background should be dark, matching the tabs. The current panel is highlighted with the accent colour.

# Actual behavior

The split background is light, matching the system theme (in particular the "app mode" setting), and ignores the `requestedTheme` Terminal setting. Next to a light grey line, the accent colour is less visible.

The opposite is also true: set windows to "dark mode", Terminal to "light mode", and the splits will follow the system settings.

image

### PR DESCRIPTION
**Pull request by zadjii-msft**
We couldn't do this before, because `App::Current().Resources().Lookup()` would always return the OS theme version of a resource. That thread has lengthy details on why.

FORTUNATELY FOR US, this isn't the first time we've dealt with this. We've come up with a workaround in the past, and we can just use it again here. 

Closes #3917

This will also make #3061 easy 😉

### CODE REVIEW

File: src/cascadia/TerminalApp/TerminalPage.cpp [hunk 1]
```diff
@@ -4175,6 +4175,22 @@ namespace winrt::TerminalApp::implementation
         const auto theme = _settings.GlobalSettings().CurrentTheme();
         auto requestedTheme{ theme.RequestedTheme() };
 
+        {
+            // Update the brushes that Pane's use...
+            Pane::SetupResources(requestedTheme);
+            // ... then trigger a visual update for all the bane borders to
```
Comment (carlos-zamora) [inline src/cascadia/TerminalApp/TerminalPage.cpp:4181]:
```suggestion
            // ... then trigger a visual update for all the pane borders to
```
BaneBatmanGIF

**Review by carlos-zamora — APPROVED** [review]
Nice-n-easy

File: src/cascadia/TerminalApp/TerminalPage.cpp [hunk 2]
```diff
@@ -4175,6 +4175,22 @@ namespace winrt::TerminalApp::implementation
         const auto theme = _settings.GlobalSettings().CurrentTheme();
         auto requestedTheme{ theme.RequestedTheme() };
 
+        {
+            // Update the brushes that Pane's use...
+            Pane::SetupResources(requestedTheme);
```
Comment (DHowett) [inline src/cascadia/TerminalApp/TerminalPage.cpp:4180]: Scary, updating globals like that, but I think I get how it is safe!

**Review by DHowett — APPROVED** [review]
