### PR TITLE
Bugfix: sync color scheme rename with profile reference

### LINKED ISSUE #8756: Renaming a color scheme used by a profile should properly update the profile
# Steps to reproduce

1. Open Settings UI
2. Have a profile ("Profile A") refer to a custom color scheme ("Color Scheme A")
3. Go to the Color Schemes page
4. Select "Color Scheme A"
5. Rename it to something else ("Color Scheme B")
6. Navigate back to the profile that referred to this color scheme ("Profile A")

# Expected behavior

"Profile A" should now reference "Color Scheme B".

# Actual behavior

"Profile A" refers to "Campbell"

# Additional details
The TerminalSettingsModel stores Profile.ColorScheme as a string reference to the name of the ColorScheme.
In TerminalSettingsEditor ([Profiles.cpp](https://github.com/microsoft/terminal/blob/7235996b4d83b340a9cfa7227381922e5ad7baf8/src/cascadia/TerminalSettingsEditor/Profiles.cpp#L130)), if a ColorScheme with that name isn't found, we fallback to "Campbell".

Perhaps a better architecture would be to reference a `ColorScheme` object in the TerminalSettingsModel? Or at least reference a `ColorScheme` object in the ViewModel in TerminalSettingsEditor.

### PR DESCRIPTION
**Pull request by carlos-zamora**
## Summary of the Pull Request
This fixes a bug where renaming/deleting a color scheme would not update profiles that referenced it.

This also adds detection for renaming a color scheme to a name that is already in use, and adds appropriate UI for that.

## References
#6800 - Settings UI Epic

## PR Checklist
* [X] Closes #8756 

## Detailed Description of the Pull Request / Additional comments
`Model::CascadiaSettings` was updated to have a `UpdateColorSchemeReferences()` function that updates all profiles referencing the newly renamed color scheme.

`Editor::ColorSchemesPageNavigationState` now takes and exposes a `Model::CascadiaSettings`.

When a color scheme is renamed or deleted, we use `CascadiaSettings` to update our list of color schemes appropriately, then call `UpdateColorSchemeReferences()` to update the profiles.

The tricky part is that `Profile` does not store a direct reference to `ColorScheme`, but rather the name of the color scheme. See [this tread](https://github.com/microsoft/terminal/issues/8756#issuecomment-760375027) for a discussion on this topic.

## Validation Steps Performed
Repro steps from #8756 when renaming/deleting a referenced color scheme.

## Demo
Scheme Name Already In Use Demo

### CODE REVIEW

**Comment by carlos-zamora** [comment]
This PR is in draft because it doesn't work. It _should_ work, but it doesn't and I don't understand why. Here's my findings so far:
- `ModifyColorSchemeNameEventArgs` verified to contain correct data and be sent at proper time
- `MainPage::_ModifyColorSchemeName()` called appropriately. It detects the profiles with the outdated name and updates the profile
- \<navigate to profile page of relevant profile\>
- `Profiles::CurrentColorScheme()`:
  - `schemeName` is retrieved correctly (contains updated color scheme name)
  - Surprisingly, the failure comes in the line after that `if (const auto scheme{ _State.Schemes().TryLookup(schemeName) })`. The updated color scheme name is _not_ in the map of schemes in `_State.Schemes()` (aka `Globals().ColorSchemes()`)!

I was suspicious that the `IMapView` may be causing some problems where we _think_ we're updating our storage of color schemes, but we're modifying a temporary, immutable map of them. So I went into the settings model and made `Globals().ColorSchemes()` return an `IMap` instead of an `IMapView`, but that resulted in the same behavior as above. (This change is not committed, but it's stashed and readily available if requested).

File: src/cascadia/TerminalSettingsEditor/ColorSchemes.cpp [hunk 1]
```diff
@@ -51,6 +51,17 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
...
 
+    void ColorSchemesPageNavigationState::RenameColorScheme(hstring oldName, hstring newName)
+    {
+        _Settings.RenameColorScheme(oldName, newName);
+    }
+
+    void ColorSchemesPageNavigationState::DeleteColorScheme(hstring name)
+    {
+        // This ensures that the JSON is updated with "Campbell", because the color scheme was deleted
+        _Settings.RenameColorScheme(name, L"Campbell");
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/ColorSchemes.cpp:62]: * * * NOT COMFORTABLE WITH THIS * * *
even momentarily, the settings model will think that _this color scheme_ that we're about to delete is campbell.

File: src/cascadia/TerminalSettingsEditor/ColorSchemes.h [hunk 2]
```diff
@@ -13,11 +13,18 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
...
     {
     public:
-        ColorSchemesPageNavigationState(const Model::GlobalAppSettings& settings) :
-            _Globals{ settings } {}
+        ColorSchemesPageNavigationState(const Model::CascadiaSettings& settings) :
+            _Globals{ settings.GlobalSettings() },
+            _Settings{ settings } {}
+
+        void RenameColorScheme(hstring oldName, hstring newName);
+        void DeleteColorScheme(hstring name);
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/ColorSchemes.h:22]: This is an inappropriate responsibility for the navigation state. It's supposed to be a handoff object that gets information from MainPage into ColorSchemesPage, nothing more.

Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/ColorSchemes.h:22]: (This one still applies under the new design)
I could do all of this in the color schemes page. The navigation state would have to expose `CascadiaSettings` though. Or is there a way that I could _only_ expose `UpdateColorSchemeReferences()` without having to make an interface for that one thing?

File: src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp [hunk 3]
```diff
@@ -865,6 +865,25 @@ winrt::Microsoft::Terminal::Settings::Model::ColorScheme CascadiaSettings::GetCo
...
+// - updates all references to that color scheme with the new name
+// Arguments:
+// - oldName: the original name for the color scheme
+// - newName: the new name for the color scheme
+// Return Value:
+// - <none>
+void CascadiaSettings::UpdateColorSchemeReferences(const hstring oldName, const hstring newName)
+{
+    // update all profiles referencing this color scheme
+    for (auto profile : _allProfiles)
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp:878]: `const auto&` :smile:

File: src/cascadia/TerminalSettingsEditor/ColorSchemes.h (hunk 2 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/ColorSchemes.h]: Ended up exposing `CascadiaSettings` entirely instead of just `GlobalAppSettings`.

File: src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp (hunk 3 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp]: Fixed. So, here's what's confusing to me about this though. `const auto&` means we're taking an "immutable reference to the variable", but a few lines down, we're modifying that variable. So then is `const auto&` have the sole purpose of not incrementing the ref-count?

Comment (DHowett) [reply src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp]: Oh. Right. It's _complicated_. WinRT objects _do not have constness_. It isn't part of WinRT.

Therefore, we're just using the C++ rules of constness: the projection object isn't gonna change, but the thing inside it absolutely is.

Comment (DHowett) [reply src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp]: If it builds this way. Maybe it wont'?

File: src/cascadia/TerminalSettingsEditor/ColorSchemes.cpp [hunk 4]
```diff
@@ -275,9 +263,16 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
             NameBox().SelectAll();
             return;
         }
-        RenameErrorTip().IsOpen(false);
 
-        winrt::get_self<ColorSchemesPageNavigationState>(_State)->RenameColorScheme(CurrentColorScheme().Name(), newName);
+        // update the settings model
+        auto scheme{ _State.Settings().GlobalSettings().ColorSchemes().Lookup(oldName) };
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/ColorSchemes.cpp:268]: y u do lookup when you have `CurrentColorScheme`?

**Review by DHowett — CHANGES_REQUESTED** [review]
-

**Review by DHowett — APPROVED** [review]
love it. thank you. EXCELLENT addition w/ the new teaching tip.

**Review by zadjii-msft — APPROVED** [review]
This is very clever, I like it

**Comment by DHowett** [comment]
Before you merge this, please update the PR body. It describes the old implementation.
