### PR TITLE
Disable the VT color quirk for pwsh and modern inbox powershell

### LINKED ISSUE #6807: It bad
# Environment

```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

# Expected behavior

# Actual behavior

### PR DESCRIPTION
**Pull request by DHowett**
In #6810, we introduced a "quirk" for all known versions of PowerShell
that suppressed their requests for black background/gray foreground.
This was done to avoid an [issue in PSReadline] where it would paint
black bars all over the screen if the default background color wasn't
the same as the ANSI black color.

Years have passed since that quirk was introduced. The underlying bug
was fixed, and the fix was released broadly long ago. It's time for us
to remove the quirk... almost.

Terminal still runs on versions of Windows that ship a broken version of
PSReadline. We must maintain the quirk there -- the user can't do
anything about it, and we would make their experience worse if we
removed the quirk entirely.

PowerShell 7.0 also ships a broken version of PSReadline. It is still in
support for another 6 months, but updates have been available for some
time. We can encourage users to update.

Therefore, we only need the quirk for Windows PowerShell, and then only
for specific versions of Windows.

_Inside Windows_, we don't even need that: we're guaranteed to be built
alongside a fixed version of PowerShell!

Closes #6807

[issue in PSReadline]: https://github.com/PowerShell/PSReadLine/issues/830#issuecomment-650508857

### CODE REVIEW

File: src/server/ConsoleShimPolicy.cpp [hunk 1]
```diff
@@ -41,19 +22,36 @@ ConsoleShimPolicy ConsoleShimPolicy::s_CreateInstance(const HANDLE hProcess)
...
-        isPowershell = (clientName.compare(L"powershell.exe") == 0) ||
-                       (clientName.compare(L"pwsh.exe") == 0);
+        const auto isInboxPowershell = clientName.compare(L"powershell.exe") == 0;
+        const auto isPwsh = clientName.compare(L"pwsh.exe") == 0;
+        _isPowershell = isInboxPowershell || isPwsh;
+
+        // Inside Windows, we are guaranteed that we're building alongside a new (good) inbox PowerShell.
+        // Therefore, we can default _requiresVtColorQuirk to false.
+#ifndef __INSIDE_WINDOWS
+        // Outside of Windows, we need to check the OS version: PowerShell eas fixed in early Iron builds.
```
Comment (DHowett) [inline src/server/ConsoleShimPolicy.cpp:39]:
```suggestion
        // Outside of Windows, we need to check the OS version: PowerShell was fixed in early Iron builds.
```

**Comment by DHowett** [comment]
I also changed how `ConsoleShimPolicy` works because the way it was written was _strange_. A static in-class constructor that doesn't poke at its private boolean members, but calls a private constructor anyway? That just seems like too many steps. Instead of adding a third parameter, it seemed easier to just make the ctor exception-safe and move to accessing the members directly.

File: src/server/ConsoleShimPolicy.cpp [hunk 2]
```diff
@@ -41,19 +22,36 @@ ConsoleShimPolicy ConsoleShimPolicy::s_CreateInstance(const HANDLE hProcess)
         // Convert to lower case, just in case
         std::transform(clientName.begin(), clientName.end(), clientName.begin(), std::towlower);
 
-        isCmd = clientName.compare(L"cmd.exe") == 0;
+        _isCmd = clientName.compare(L"cmd.exe") == 0;
```
Comment (DHowett) [inline src/server/ConsoleShimPolicy.cpp:25]: fwiw it seems like it would be reasonable to not check if it's pwsh _if it's cmd_, but... eh. whatever. it was always this way.

File: src/server/ConsoleShimPolicy.cpp [hunk 3]
```diff
@@ -41,19 +22,36 @@ ConsoleShimPolicy ConsoleShimPolicy::s_CreateInstance(const HANDLE hProcess)
...
-                       (clientName.compare(L"pwsh.exe") == 0);
+        const auto isInboxPowershell = clientName.compare(L"powershell.exe") == 0;
+        const auto isPwsh = clientName.compare(L"pwsh.exe") == 0;
+        _isPowershell = isInboxPowershell || isPwsh;
+
+        // Inside Windows, we are guaranteed that we're building alongside a new (good) inbox PowerShell.
+        // Therefore, we can default _requiresVtColorQuirk to false.
+#ifndef __INSIDE_WINDOWS
+        // Outside of Windows, we need to check the OS version: PowerShell was fixed in early Iron builds.
+        static auto _doesInboxPowershellVersionRequireQuirk = [] {
```
Comment (DHowett) [inline src/server/ConsoleShimPolicy.cpp:40]:
```suggestion
        static auto doesInboxPowershellVersionRequireQuirk = [] {
```

File: src/server/ConsoleShimPolicy.cpp [hunk 4]
```diff
@@ -41,19 +22,36 @@ ConsoleShimPolicy ConsoleShimPolicy::s_CreateInstance(const HANDLE hProcess)
...
+            OSVERSIONINFOEXW osver{};
+            osver.dwOSVersionInfoSize = sizeof(osver);
+            osver.dwBuildNumber = 20348; // Windows Server 2022 RTM
+
+            DWORDLONG dwlConditionMask = 0;
+            VER_SET_CONDITION(dwlConditionMask, VER_BUILDNUMBER, VER_LESS);
+
+            return VerifyVersionInfoW(&osver, VER_BUILDNUMBER, dwlConditionMask) != FALSE;
+        }();
+        _requiresVtColorQuirk = isInboxPowershell && _doesInboxPowershellVersionRequireQuirk;
```
Comment (DHowett) [inline src/server/ConsoleShimPolicy.cpp:50]:
```suggestion
        _requiresVtColorQuirk = isInboxPowershell && doesInboxPowershellVersionRequireQuirk;
```

File: src/server/ConsoleShimPolicy.cpp [hunk 5]
```diff
@@ -41,19 +22,36 @@ ConsoleShimPolicy ConsoleShimPolicy::s_CreateInstance(const HANDLE hProcess)
...
 
         // For powershell, we need both Windows PowersShell (powershell.exe) and
         // PowerShell Core (pwsh.exe). If PowerShell Core is ever updated to use
         // ^[[3J for Clear-Host, then it won't ever hit the shim code path, but
         // we're keeping this for the long tail of pwsh versions that still
         // _don't_ use that sequence.
-        isPowershell = (clientName.compare(L"powershell.exe") == 0) ||
-                       (clientName.compare(L"pwsh.exe") == 0);
+        const auto isInboxPowershell = clientName.compare(L"powershell.exe") == 0;
+        const auto isPwsh = clientName.compare(L"pwsh.exe") == 0;
```
[the remark this answers is not in the document]
Comment (DHowett) [reply src/server/ConsoleShimPolicy.cpp:33]: might as well do it, right? would you prefer equals_insensitive_ascii or CompareStringOrdinal?

[the remark this answers is not in the document]
Comment (lhecker) [reply src/server/ConsoleShimPolicy.cpp:33]: Both are fine, but `til::equals_insensitive_ascii` might be easier to use since it accepts string views and is sufficient in this case.

[the remark this answers is not in the document]
Comment (DHowett) [reply src/server/ConsoleShimPolicy.cpp]: how would you say you feel about the changes here?

**Comment by lhecker** [comment]
LGTM. _If_ you don't mind you could also remove this line:
```cpp
clientName.erase(std::find(clientName.begin(), clientName.end(), '\0'), clientName.end());
```

It got fixed a while ago in https://github.com/microsoft/wil/pull/165

**Comment by DHowett** [comment]
OH DANG I HAD NO IDEA IT WAS FIXED

**Review by zadjii-msft — APPROVED** [review]
