### PR TITLE
Fix profile commandlines being overwritten by profile.defaults

### LINKED ISSUE #12842: profiles.defaults should be default values, not override values, or make a new section for overridable defaults
The current implementation of Terminal applies the settings found in profiles.default to all profiles, regardless of whether the individual profile has its own value for any of those settings.  Unfortunately, this behavior is unexpected and confusing.  The only reasoning I can come up with is that profiles.default was meant to override settings from automatic profiles that aren't defined in settings.json at all.  For profiles defined in settings.json, the expectation for profiles.default would be that any setting not defined in an individual profile would get its value from profiles.default, but if a setting *is* provided in the individual profile the corresponding setting in profiles.default would be ignored.

Please change Terminal so profiles.default behaves in an expected way, providing default values and not override values.  If an overriding section is really needed, then create a new profiles.overrides section for this.  With the current implementation, it is not possible to define several profiles and have most of them use a common value for some settings, while one or two exception profiles do something different without copying that setting to every individual profile.  profiles.default has very little value when it forces itself onto every profile.
If profiles.default can't change for some reason, then consider creating a new section (maybe profiles.fallback) for overridable defaults or fallback values that individual profiles can override if they provide a value for that setting in the profile.

### PR DESCRIPTION
**Pull request by lhecker**
#12149 introduced a bug where `ClearCommandline()` is called on any user
profile containing the non-canonical strings "cmd.exe" or "powershell.exe"
in the "commandline" field. If you happen to have set the "commandline"
field in your `profiles.defaults`, this will cause these user profiles
to adopt the base layer command-line instead of the defaults layer one.

This commit fixes the issue, by checking the command-line after the call
to `ClearCommandline()` and ensuring it's the expected string.

Additionally this moves the migration logic to `SettingsLoader` as this allows
us to write the fixed settings to disk, if any fixed had to be applied.

## PR Checklist
* [x] Closes #12842
* [x] I work here
* [x] Tests added/passed

## Validation Steps Performed
* The modified unit test fails without these changes ✅
* The modified unit test succeeds with these changes ✅
* Setting `profiles.defaults.commandline` to "pwsh.exe" and setting
  my "...\\powershell.exe" profile to use just "powershell.exe" as
  the `commandline`, doesn't cause it to use "pwsh.exe" ✅
  The fixed settings are written to settings.json ✅

### CODE REVIEW

**Comment by lhecker** [comment]
The modified unit test fails with this (rather lengthy) message, without the `CascadiaSettings` changes:
> `Error: Verify: AreEqual(L"%SystemRoot%\\System32\\WindowsPowerShell\\v1.0\\powershell.exe", allProfiles.GetAt(0).Commandline()) - Values (%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe, pwsh.exe) [File: C:\Users\lhecker\projects\terminal\src\cascadia\LocalTests_SettingsModel\ProfileTests.cpp, Function: SettingsModelLocalTests::ProfileTests::TestCorrectOldDefaultShellPaths, Line: 413]`

File: src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp [hunk 1]
```diff
@@ -361,6 +364,58 @@ bool SettingsLoader::DisableDeletedProfiles()
...
+    struct CommandlinePatch
+    {
+        winrt::guid guid;
+        std::wstring_view before;
+        std::wstring_view after;
+    };
+
+    static constexpr std::array commandlinePatches{
+        CommandlinePatch{ DEFAULT_COMMAND_PROMPT_GUID, L"cmd.exe", L"%SystemRoot%\\System32\\cmd.exe" },
+        CommandlinePatch{ DEFAULT_WINDOWS_POWERSHELL_GUID, L"powershell.exe", L"%SystemRoot%\\System32\\WindowsPowerShell\\v1.0\\powershell.exe" },
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp:383]: thank you for restricting this to only the original profiles

File: src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp [hunk 2]
```diff
@@ -361,6 +364,58 @@ bool SettingsLoader::DisableDeletedProfiles()
     return newGeneratedProfiles;
 }
 
+// Runs migrations and fixups on user settings.
+// Returns true if something got changed and
+// the settings need to be saved to disk.
+bool SettingsLoader::FixupUserSettings()
+{
+    using namespace std::string_view_literals;
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp:372]: you didn't end up using the literals tho right?

**Review by DHowett — APPROVED** [review]

**Review by zadjii-msft — APPROVED** [review]
