### PR TITLE
Fix the cursor blink VT sequence being ignored

### LINKED ISSUE #10543: ConPTY does not pass cursor blinking VT sequence (`DECSET/DECRST 12`)
### Windows Terminal version (or Windows build number)

1.8

### Other Software

_No response_

### Steps to reproduce

In powershell, enter:

"`e[?12l"

### Expected Behavior

Cursor should stop blinking

### Actual Behavior

Cursor continues to blink

### PR DESCRIPTION
**Pull request by PankajBhojwani**
Ensure that the cursor blink VT sequence gets flushed to terminal when conhost is attached to a pty

Closes #10543

### CODE REVIEW

**Review by zadjii-msft — APPROVED** [review]

File: src/host/outputStream.cpp [hunk 1]
```diff
@@ -344,7 +344,12 @@ bool ConhostInternalGetSet::PrivateShowCursor(const bool show) noexcept
 bool ConhostInternalGetSet::PrivateAllowCursorBlinking(const bool fEnable)
 {
     DoSrvPrivateAllowCursorBlinking(_io.GetActiveOutputBuffer(), fEnable);
-    return true;
+
+    bool isPty;
+    DoSrvIsConsolePty(isPty);
+    // If we are connected to a pty, return that we could not handle this
```
Comment (miniksa) [inline src/host/outputStream.cpp:350]: Confusing. We did handle it by turning on our own blinking... didn't we with `DoSrvPrivateAllowCursorBlinking` above?

Comment (DHowett) [reply src/host/outputStream.cpp:350]: Returning `false` in an event handler for the VT Parser's OutputStateMachineEngine has been overloaded to mean, "Pass this through to the connected terminal."

This is not the first, and will likely not be the last, case in which we do this.

Comment (miniksa) [reply src/host/outputStream.cpp:350]: So we are saying that we need to process it AND the connected terminal needs to process it too... right?

Comment (PankajBhojwani) [reply src/host/outputStream.cpp:350]: So technically we don't _need_ to process it ourselves, only the connected terminal needs to. I've done it this way just so there's consistency between the two, just in case.

Comment (miniksa) [reply src/host/outputStream.cpp:350]: Just leave that as a comment then to inform a future reader, please, and I'm good then.

Comment (PankajBhojwani) [reply src/host/outputStream.cpp:350]: Okay, added!

**Review by DHowett — APPROVED** [review]

**Comment by polluks** [comment]
Maybe there should be a warning like https://unix.stackexchange.com/a/3769/277889.
