### PR TITLE
[DefApp] Teach connection and tab to negotiate initial size

### LINKED ISSUE #9811: [DefApp] TerminalHandoff does not communicate first new size to client
### Windows Terminal version (or Windows build number)

1.9

### Other Software

_No response_

### Steps to reproduce

Launch a console application in Terminal via def. app.

### Expected Behavior

The new application is sized appropriately for the terminal window hosting it (or we use the STARTUPINFO data to size terminal (!))

### Actual Behavior

image

It is definitely not 120x9001!

### PR DESCRIPTION
**Pull request by miniksa**
- For tabs started from the Terminal, the initial sizing information is
  passed into the connection and used to establish the PTY. Those
  parameters are given over to the `OpenConsole.exe` acting as PTY to
  establish the initial buffer/window size.
- However, for tabs started from outside, the PTY is created with some
  default buffer information FIRST as the Terminal hasn't even been
  involved yet. As such, when the Terminal gets that connection, it must
  tell the PTY to resize just as it connects to match the window size
  it's about to use.
- Ongoing resize operations in the Terminal did and still work fine
  because they transmitted the updated size with the
  `ResizePseudoConsole` API.

## Validation Steps Performed
- [x] Confirmed existing tabs opening have correct initial size in PTY
  (like with CMD `mode con` command)
- [x] Confirmed inbound cmd tabs have correct initial size in PTY via
  `mode con` command per bug repro

Closes #9811

### CODE REVIEW

File: src/cascadia/TerminalConnection/ConptyConnection.cpp [hunk 1]
```diff
@@ -423,11 +432,14 @@ namespace winrt::Microsoft::Terminal::TerminalConnection::implementation
 
     void ConptyConnection::Resize(uint32_t rows, uint32_t columns)
     {
-        if (!_hPC)
+        // If we haven't started connecting at all, it's still fair to update
+        // the initial rows and columns before we set things up.
+        if (!_isStateAtOrBeyond(ConnectionState::Connecting))
```
Comment (DHowett) [inline src/cascadia/TerminalConnection/ConptyConnection.cpp:437]: yay you used my fun template garbage

**Review by DHowett — APPROVED** [review]

**Review by zadjii-msft — APPROVED** [review]

**Review by carlos-zamora — APPROVED** [review]
