### PR TITLE
Hide the window from DWM until we're finished with initialization

### LINKED ISSUE #9053: START /MIN WT?
# Environment
Microsoft Windows 10 Pro for Workstations
10.0.19042.746 (2009, 20H2)
WindowsTerminalPreview_1.6.10272.0_x64
```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):

Any other software?
```

# Steps to reproduce

In CMD.EXE, issue `START /MIN WT`

# Expected behavior
WT starts minimized and can be restored.

# Actual behavior
WT starts minimized and can't be restored.  The taskbar icon is rather lame.

I couldn't get good pics of the taskbar icon's popup thumbnails because they close when I activate the screen clipper.

### LINKED ISSUE #11561: Starting WT momentarily shows a black titlebar
### Windows Terminal version (or Windows build number)

10.0.19043.1288 1.12.2922.0

### Other Software

_No response_

### Steps to reproduce

Start WT.

### Expected Behavior

The GUI should start without showing a glitched black title bar, just as it did in v1.11.

### Actual Behavior

It shows a black title bar for a few milliseconds. See below:

My [settings.json](https://github.com/rashil2000/dotfiles/blob/master/wt/settings.json) is the same as before I upgraded (through Store).

### PR DESCRIPTION
**Pull request by zadjii-msft**
When we start up, our window is initially just a frame with a transparent content area. We're gonna do all this startup init on the UI thread, so the UI won't actually paint till it's all done. This results in a few frames where the frame is visible, before the page paints for the first time, before any tabs appears, etc. 

To mitigate this, we're gonna wait for the UI thread to finish everything it's gotta do for the initial init, and _then_ fire our Initialized event. By waiting for everything else to finish (`CoreDispatcherPriority::Low`), we let all the tabs and panes actually get created. In the window layer, we're gonna ~cloak~ just not show the window till this event is fired, so we don't actually see this frame until we're actually all ready to go. **This will result in the window seemingly not loading as fast**, but it will actually take exactly the same amount of time before it's usable. 

I also experimented with drawing a solid BG color before the initialization is finished. However, there are still a few frames after the frame is displayed before the XAML content first draws, so that didn't actually resolve any issues.

* [x] Closes #11561
* [x] Tested manually
* [x] I work here.
* [x] Accidentally also closes #9053. By switching the initial call from `ShowWindow(SW_SHOW)` to `ShowWindow(SW_SHOWDEFAULT)`, we actually obey the startup info now.

### CODE REVIEW

File: src/cascadia/TerminalApp/TerminalPage.cpp [hunk 1]
```diff
@@ -678,10 +678,48 @@ namespace winrt::TerminalApp::implementation
...
+            // it will actually take exactly the same amount of time before it's
+            // usable.
+            //
+            // We also experimented with drawing a solid BG color before the
+            // initialization is finished. However, there are still a few frames
+            // after the frame is displayed before the XAML content first draws,
+            // so that didn't actually resolve any issues.
+
+            // Capture calling context.
+            winrt::apartment_context ui_thread;
```
Comment (lhecker) [inline src/cascadia/TerminalApp/TerminalPage.cpp:710]: Unused?

File: src/cascadia/TerminalApp/TerminalPage.cpp [hunk 2]
```diff
@@ -678,10 +678,48 @@ namespace winrt::TerminalApp::implementation
...
+            auto weak{ get_weak() };
+
+            // Switch to the BG thread -
+            co_await winrt::resume_background();
+
+            // Then enqueue the rest of this function for after the UI thread settles.
+            co_await wil::resume_foreground(Dispatcher(), CoreDispatcherPriority::Low);
```
Comment (lhecker) [inline src/cascadia/TerminalApp/TerminalPage.cpp:717]: `Dispatcher()` depends on `this` so you could capture it at the start of the function (instead of `ui_thread`).

**Comment by zadjii-msft** [comment]
Okay, after discussing in team sync - we totally can just defer the actual first call to `ShowWindow`, and it'll just do the right thing:

now-with-less-cloaking

and now we get the little **shwoop** animation back too. Thanks for the idea @lhecker!

File: src/cascadia/TerminalApp/TerminalPage.cpp (hunk 1 above)
Comment (zadjii-msft) [reply src/cascadia/TerminalApp/TerminalPage.cpp:710]: yea - I wanted to just `co_await ui_thread`, but that doesn't let me await it with low priority 🤷

File: src/cascadia/TerminalApp/TerminalPage.cpp [hunk 3]
```diff
@@ -713,12 +713,21 @@ namespace winrt::TerminalApp::implementation
             // Switch to the BG thread -
             co_await winrt::resume_background();
 
-            // Then enqueue the rest of this function for after the UI thread settles.
-            co_await wil::resume_foreground(Dispatcher(), CoreDispatcherPriority::Low);
+            if (auto self{ weak.get() })
+            {
+                // Then enqueue the rest of this function for after the UI thread settles.
+                co_await wil::resume_foreground(self->Dispatcher(), CoreDispatcherPriority::Low);
```
Comment (lhecker) [inline src/cascadia/TerminalApp/TerminalPage.cpp:719]: I'd suggest just storing the dispatcher in the beginning as
```cpp
const auto dispatcher = Dispatcher();
```

Seems like a more hassle free solution to me.
Also: Do you mind removing the `winrt::apartment_context` instantiation?

Finally there's the option to drop all of the coroutine stuff and write this:
```cpp
Dispatcher().RunAsync(CoreDispatcherPriority::Low, [weak = get_weak()]() {
    if (auto self = weak.get())
    {
        self->_InitializedHandlers(*self, nullptr);
    }
});
```

File: src/cascadia/TerminalApp/TerminalPage.cpp (hunk 1 above)
Comment (lhecker) [reply src/cascadia/TerminalApp/TerminalPage.cpp:710]: We should try to avoid using `winrt::apartment_context` as it's inherently flawed unfortunately. 😥
As Raymond Chen wrote:
> Unfortunately, it's true. co_await'ing an `apartment_context` is blocking [the background thread]. That's because it's built out of COM's `IContextCallback`, [which supports only synchronous transfer](https://devblogs.microsoft.com/oldnewthing/20191128-00/?p=103157).
> [...]
> Note that it's even worse: Even after you get to the other side, the side you came **\*from\*** is still blocked until you finish doing your other-side work (which could take the form of another co_await).
> [...]
> If the UI thread is hung, this will lead to threadpool starvation and eventually a deadlock.

File: src/cascadia/WindowsTerminal/AppHost.cpp [hunk 4]
```diff
@@ -1547,3 +1566,22 @@ void AppHost::_CloseRequested(const winrt::Windows::Foundation::IInspectable& /*
...
+                                     const winrt::Windows::Foundation::IInspectable& /*arg*/)
+{
+    // GH#11561: We're totally done being initialized. Resize the window to
+    // match the initial settings, and then call ShowWindow to finally make us
+    // visible.
+
+    LaunchMode launchMode{};
+    _initialResizeAndRepositionWindow(_window->GetHandle(), _proposedRect, launchMode);
+
+    int nCmdShow = SW_SHOW;
```
Comment (lhecker) [inline src/cascadia/WindowsTerminal/AppHost.cpp:1580]: You can use `SW_SHOWDEFAULT` here to respect the wishes of the OS.
> Sets the show state based on the SW_ value specified in the [STARTUPINFO](https://docs.microsoft.com/en-us/windows/desktop/api/processthreadsapi/ns-processthreadsapi-startupinfoa) structure passed to the [CreateProcess](https://docs.microsoft.com/en-us/windows/desktop/api/processthreadsapi/nf-processthreadsapi-createprocessa) function by the program that started the application.

Comment (zadjii-msft) [reply src/cascadia/WindowsTerminal/AppHost.cpp:1580]: Huh. Interesting. Might be related to the weirdness in #9053

Comment (lhecker) [reply src/cascadia/WindowsTerminal/AppHost.cpp:1580]: Yeah I think so.

Comment (zadjii-msft) [reply src/cascadia/WindowsTerminal/AppHost.cpp:1580]: HOLY SHIT that totally fixes it.

**Review by lhecker — APPROVED** [review]

File: src/cascadia/WindowsTerminal/AppHost.cpp [hunk 5]
```diff
@@ -1556,3 +1575,22 @@ void AppHost::_CloseRequested(const winrt::Windows::Foundation::IInspectable& /*
...
+
+void AppHost::_AppInitializedHandler(const winrt::Windows::Foundation::IInspectable& /*sender*/,
+                                     const winrt::Windows::Foundation::IInspectable& /*arg*/)
+{
+    // GH#11561: We're totally done being initialized. Resize the window to
+    // match the initial settings, and then call ShowWindow to finally make us
+    // visible.
+
+    LaunchMode launchMode{};
+    _initialResizeAndRepositionWindow(_window->GetHandle(), _proposedRect, launchMode);
```
Comment (DHowett) [inline src/cascadia/WindowsTerminal/AppHost.cpp:1587]: Worried a bit about the resize - how often will we start up at the *wrong* size?

File: src/cascadia/WindowsTerminal/IslandWindow.cpp [hunk 6]
```diff
@@ -154,19 +154,13 @@ void IslandWindow::_HandleCreateWindow(const WPARAM, const LPARAM lParam) noexce
...
 
-    auto nCmdShow = SW_SHOW;
-    if (WI_IsFlagSet(launchMode, LaunchMode::MaximizedMode))
-    {
-        nCmdShow = SW_MAXIMIZE;
-    }
-
-    ShowWindow(_window.get(), nCmdShow);
+    // GH#11561: DO NOT call ShowWindow here. The AppHost will call ShowWindow
+    // once the app has completed it's initialization.
```
Comment (DHowett) [inline src/cascadia/WindowsTerminal/IslandWindow.cpp:163]:
```suggestion
    // once the app has completed its initialization.
```

File: src/cascadia/WindowsTerminal/AppHost.cpp (hunk 5 above)
Comment (zadjii-msft) [reply src/cascadia/WindowsTerminal/AppHost.cpp:1587]: I never saw it?

**Review by DHowett — COMMENTED** [review]
Does this work well enough with session restoration?

What happens if the hosted application exits cleanly before finishing startup?

`wt -w -1 -- cmd /c exit 0`

How does it work for DefTerm?

How about DefTerm when the command exits instantly?

**Comment by zadjii-msft** [comment]
> Does this work well enough with session restoration?

Yep, pretty slick honestly

> What happens if the hosted application exits cleanly before finishing startup?

The foreground window changes for a second, but the new Terminal window never actually gets drawn.

> How does it work for DefTerm?

Seems to work well enough

> How about DefTerm when the command exits instantly?

You got me, in that specific case, a frame flashes and immediately goes away.

**Review by DHowett — APPROVED** [review]

**Comment by zadjii-msft** [comment]
we definitely need to back this one out, I _think_ it's causing my persisted windows (on my secondary monitor) to shrink a little each time.

**Review by Rooman95 — APPROVED** [review]
.

File: src/cascadia/WindowsTerminal/AppHost.cpp (hunk 5 above)
Comment (zadjii-msft) [reply src/cascadia/WindowsTerminal/AppHost.cpp:1587]: lmao well this was the issue now 😑
