### PR TITLE
Fix engine size not being changed on DPI changes

### LINKED ISSUE #11317: Text display area does not scale correctly
### Windows Terminal version (or Windows build number)

Windows Terminal version 1.10.2383.0

### Other Software

_No response_

### Steps to reproduce

1. Open Windows terminal (spawns on primary/1080p monitor)
2. Execute commands till text reaches the bottom of the window
3. Move window to secondary monitor (4k, 125% scaling)
4. Text at bottom and right is cut off, and scrolling does not update the bottom of the window
5. Input is also cut off at the bottom, so I can't see what I'm typing

### Expected Behavior

The text display area should scale correctly 

### Actual Behavior

Window on 1080p monitor:
image

Window on 4k monitor:
image

Scrolling also seems to only affect the top 3 lines while on the 4k display?
image

And there's also something about cutting off the output of commands above the fold, which seems to apply regardless of monitor:
image

I also just accidentally discovered that resizing the window fixes both the text display area and the scrolling issue on the 4k monitor

### PR DESCRIPTION
**Pull request by lhecker**
Previously we would only call `SetWindowSize` and `TriggerRedrawAll` if the
viewport size in characters changed. This commit removes the limitation.
Since the if-condition limiting full redraws is now gone, this commit
moves the responsibility of limiting the calls up the call chain.
With `_refreshSizeUnderLock` now being a heavier function call
than before, some surrounding code was thus refactored.

## PR Checklist
* [x] Closes #11317
* [x] I work here
* [x] Tests added/passed

## Validation Steps Performed

Test relevant for #11317:
* Print text, filling the entire window
* Move the window from a 150% scale to a 300% scale monitor
* The application works as expected ✅

Regression tests:
* Text zoom with Ctrl+Plus/Minus/0 works as before ✅
* Resizing a window works as before ✅
* No deadlocks, etc. during settings updates ✅

### CODE REVIEW

File: src/cascadia/TerminalControl/ControlCore.cpp [hunk 1]
```diff
@@ -809,69 +790,46 @@ namespace winrt::Microsoft::Terminal::Control::implementation
...
-                                                           { static_cast<short>(size.cx), static_cast<short>(size.cy) });
+        const auto viewInPixels = Viewport::FromDimensions({ 0, 0 }, { cx, cy });
         const auto vp = _renderEngine->GetViewportInCharacters(viewInPixels);
         const auto currentVP = _terminal->GetViewport();
 
-        // Don't actually resize if viewport dimensions didn't change
-        if (vp.Height() == currentVP.Height() && vp.Width() == currentVP.Width())
-        {
-            return;
-        }
```
Comment (lhecker) [inline src/cascadia/TerminalControl/ControlCore.cpp:869]: This is the bug fix. The rest are "performance-restoration-refactorizations" to limit calls to `_refreshSizeUnderLock`.

**Comment by lhecker** [comment]
@DHowett A minimal change for 1.12: https://github.com/microsoft/terminal/compare/release-1.12...dev/lhecker/11317-dpi-change-fix-1.12
(I'll test this later today and update this comment accordingly.)

**Review by Gido97081214 — CHANGES_REQUESTED** [review]
Rewrite in C for Linux

**Review by Gido97081214 — APPROVED** [review]

File: src/cascadia/TerminalControl/ControlCore.cpp [hunk 2]
```diff
@@ -768,30 +752,22 @@ namespace winrt::Microsoft::Terminal::Control::implementation
     // - Set the font size of the terminal control.
     // Arguments:
     // - fontSize: The size of the font.
-    void ControlCore::_setFontSize(int fontSize)
+    // Return Value:
+    // - Returns true if you need to call _refreshSizeUnderLock().
+    bool ControlCore::_setFontSizeUnderLock(int fontSize)
```
Comment (miniksa) [inline src/cascadia/TerminalControl/ControlCore.cpp:757]: Oh. So it's not doing it "under lock". It's saying that you should call this only if you're under a lock.

**Review by miniksa — APPROVED** [review]

File: src/cascadia/TerminalControl/ControlCore.cpp (hunk 2 above)
Comment (lhecker) [reply src/cascadia/TerminalControl/ControlCore.cpp:757]: Yeah, there's another function with a similar name pattern.

**Review by DHowett — APPROVED** [review]
