### PR TITLE
Prevent the v1 propsheet from zeroing colors, causing black text on black background.

### LINKED ISSUE #2319: Toggling Legacy console on and off enables Terminal colors but sets them to all black
# Environment

Microsoft Windows [Version 10.0.18362.239]

# Steps to reproduce

1.Open a CMD
2.Settings > Options > Check Legacy 
3.Restart CMD
4.Settings > Options > Uncheck Legacy 
5.Restart CMD
6.Get a full black screen.

# Actual behavior

Anmerkung 2019-08-07 110052

Screenshot from Settings after the steps to reproduce.

 # What's actually happening?

The problem is that i run a script on shutting down my computer which is for backup and ask me in a CMD if i want to backup my files.
Since the new update, this CMD is all black. So i just know what there is written, but i can't see it actually.
I think this causes from this bug.

### PR DESCRIPTION
**Pull request by zadjii-msft**
## Summary of the Pull Request
The v1 console doesn't know anything about "default foreground" or "default background" colors. So when the v1 console starts up, it leaves those members of the `CONSOLE_STATE_INFO` zero'd. However, both the v1 and v2 console's share the same `console.dll`, the propsheet. When the user unchecks the "use legacy settings" checkbox and saves the settings, the propsheet tries to save the v2 settings that are totally inaccessible to the "v1" propsheet, and were zero'd to match the state of the console.

This change makes is so that the propsheet only saves the "Terminal" settings when the propsheet was launched from a v2 console.

## PR Checklist
* [x] Closes #2319 
* [x] I work here
* [n/a] Tests added/passed
* [n/a] Requires documentation to be updated

## Detailed Description of the Pull Request / Additional comments

This PR fixes the bug for both loading the settings from the registry _and_ loading from the shortcut.

## Validation Steps Performed
1. Copied my modified console.dll into system32.
2. Opened a v2 conhost from win+r, `cmd` (using the registry settings)
3. opened the propsheet, confirmed it had a default FG/BG.
4. Used the propsheet to switch to legacy mode
5. Opened a v1 conhost with win+r
6. Opened the propsheet, confirmed there was no "Terminal" propsheet
7. unchecked the "legacy" checkbox
8. Opened a new win+r conhost
9. It re-opened with the original default colors

and then repeat steps 2-9 using the Win+X, C conhost, which uses a shortcut instead of the registry.

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
One last validation step: right-click a shortcut from explorer, launch propsheet that way. The "no console host" path.

File: src/propsheet/registry.cpp [hunk 1]
```diff
@@ -169,6 +169,7 @@ DWORD GetRegistryValues(
 
     // initial values for global v2 settings
     g_fForceV2 = GetConsoleBoolValue(CONSOLE_REGISTRY_FORCEV2, TRUE);
+    g_fLaunchedAsV2 = g_fForceV2;
```
Comment (DHowett-MSFT) [inline src/propsheet/registry.cpp]: wait, is this always set even for the shortcut case? I'm alarmed that it's set here but used in SaveConsoleSettingsIfNeeded's _link_ path

Comment (zadjii-msft) [reply src/propsheet/registry.cpp]: Yea, because the ForceV2 setting isn't per-registry or per-shortcut, it's _always_ in the registry root, as a global-only setting.

(I'm leaving this open to ensure that it works for the "launch straight into the shortcut, no conhost" path)

**Comment by DHowett-MSFT** [comment]
@zadjii-msft did it end up working in the shortcut-only case?

File: src/propsheet/registry.cpp (hunk 1 above)
Comment (zadjii-msft) [reply src/propsheet/registry.cpp]: This does in fact work φ(*￣0￣)

File: src/propslib/ShortcutSerialization.cpp [hunk 2]
```diff
@@ -488,12 +489,21 @@ Return Value:
                     s_SetLinkPropertyBoolValue(pps, PKEY_Console_CtrlKeyShortcutsDisabled, pStateInfo->fCtrlKeyShortcutsDisabled);
                     s_SetLinkPropertyBoolValue(pps, PKEY_Console_LineSelection, pStateInfo->fLineSelection);
                     s_SetLinkPropertyByteValue(pps, PKEY_Console_WindowTransparency, pStateInfo->bWindowTransparency);
-                    s_SetLinkPropertyDwordValue(pps, PKEY_Console_CursorType, pStateInfo->CursorType);
-                    s_SetLinkPropertyDwordValue(pps, PKEY_Console_CursorColor, pStateInfo->CursorColor);
                     s_SetLinkPropertyBoolValue(pps, PKEY_Console_InterceptCopyPaste, pStateInfo->InterceptCopyPaste);
```
Comment (carlos-zamora) [inline src/propslib/ShortcutSerialization.cpp]: Should this one be moved too? You touched it in `registry.cpp`.

File: src/propsheet/globals.h [hunk 3]
```diff
@@ -35,6 +35,7 @@ extern BOOL gbEnumerateFaces;
 extern LONG gcxScreen;
 extern LONG gcyScreen;
 extern BOOL g_fForceV2;
+extern BOOL g_fLaunchedAsV2;
```
Comment (miniksa) [inline src/propsheet/globals.h]: You don't need this. The v2 console will declare itself as such in the structure passed in when the Property Sheet is created so you can key off of it.

Check `gpStateInfo->fIsV2Console` and see this for a sample where something is already keying to only show when launched from the V2 console: https://github.com/microsoft/terminal/blob/bac69f7cabec6068868034345e2aea22a9533696/src/propsheet/console.cpp#L579-L582

File: tools/bx.ps1 [hunk 4]
```diff
@@ -21,6 +21,13 @@ $targets = $Metaproj.Project.Target
 #   [Conhost\Server, Conhost\Server:Clean, Conhost\Server:Rebuild, Conhost\Server:Publish]
 $matchingTargets = $targets | Where-Object { $_.MSBuild.Condition -eq $msBuildCondition }
 
+# If we didn't find a target, it's possible that the project doesn't have a metaproj
```
Comment (miniksa) [inline tools/bx.ps1]: Sorry, what's this about? It's not even clear from the comment.

File: src/propsheet/globals.h (hunk 3 above)
Comment (DHowett-MSFT) [reply src/propsheet/globals.h]: How does this work for explorer-only invocation?

Comment (DHowett-MSFT) [reply src/propsheet/globals.h]: I just attached to explorer and checked. `fIsV2Console` is false when we're in the standalone propsheet.

Comment (miniksa) [reply src/propsheet/globals.h]: My argument is then basically that either the old test was wrong or the new test is superfluous. 

I follow what you're saying and it's probably bad that explorer launch is detected as v1. So maybe change fIsV2Console to be the registry state, stop passing it from conhost v2, and key everything off of that one?
