### PR TITLE
AtlasEngine: Fix support for font features

### LINKED ISSUE #15896: Atlas engine does not render stylistic sets
### Windows Terminal version

1.18.1462.0

### Windows build number

10.0.22621.0

### Other Software

None

### Steps to reproduce

- Set the font to "Cascadia Mono"
- Open the JSON settings and add in the appropriate place `features: { "ss19": 1 }` (see Cascadia Code repo)
- This should choose the slashed zero variant of Cascadia Code
- In the Rendering settings, turn off use Atlas engine
- Slashed 0 is shown in terminal text
- Now turn on Atlas engine
- Slashed 0 is not shown

### Expected Behavior

Atlas engine should render stylistic sets

### Actual Behavior

Atlas engine does not render stylistic sets

### PR DESCRIPTION
**Pull request by lhecker**
Font features require us to skip the fast path via `GetTextComplexity`.
`IDWriteTextLayout` handles it the same way internally.

Closes #15896

## Validation Steps Performed
* Use Cascadia Code
* Set `features: { "ss19": 1 }`
* "0" has a dash in it instead of a dot ✅

### CODE REVIEW

File: src/renderer/atlas/AtlasEngine.cpp [hunk 1]
```diff
@@ -648,6 +648,9 @@ void AtlasEngine::_flushBufferLine()
 
         const auto initialIndicesCount = row.glyphIndices.size();
 
+        // GetTextComplexity() returns as many glyph indices as its textLength parameter (here: mappedLength).
+        // This block ensures that the buffer has sufficient capacity. It also initializes the glyphProps buffer because it and
+        // glyphIndices sort of form a "pair" in the _mapComplex() code and are always simultaneously resized there as well.
```
Comment (lhecker) [inline src/renderer/atlas/AtlasEngine.cpp:653]: -> Suppress whitespace changes: https://github.com/microsoft/terminal/pull/15912/files?w=1

**Review by zadjii-msft — APPROVED** [review]
