### PR TITLE
Fix a crash when opening a new tab with args

### LINKED ISSUE #3897: A `{"action": "newTab", "profile": "NameOfProfile"}` binding causes a crash
https://github.com/microsoft/terminal/blob/402b7ff0e055a56baa5e9b4ee127b9ed75658191/src/cascadia/TerminalApp/TerminalPage.cpp#L420-L429

```
00 (Inline Function) --------`-------- TerminalApp!winrt::impl::consume_Windows_Foundation_IReference<winrt::Windows::Foundation::IReference<int>,int>::Value+0x4 [E:\BA\22\s\src\cascadia\TerminalApp\lib\Generated Files\winrt\Windows.Foundation.h @ 627] 
01 0000006b`126fda10 00007ffa`9189fc7e TerminalApp!winrt::TerminalApp::implementation::TerminalPage::_OpenNewTab+0xef [E:\BA\22\s\src\cascadia\TerminalApp\TerminalPage.cpp @ 420] 
02 0000006b`126fdb70 00007ffa`91852338 TerminalApp!winrt::TerminalApp::implementation::TerminalPage::_HandleNewTab+0x13e [E:\BA\22\s\src\cascadia\TerminalApp\AppActionHandlers.cpp @ 145] 
```

It is in the ETL generator ☹️

### PR DESCRIPTION
**Pull request by zadjii-msft**
## Summary of the Pull Request

I accidentally did the wrong check here to see if the value exists. For an `IReference`, you need to do `variable != nullptr`. I did `variable.Value()`. 

## References
Introduced in #3825

## PR Checklist
* [x] Closes #3897
* [x] I work here
* [ ] Tests added/passed - wow this was a lot harder than I expected
* [n/a] Requires documentation to be updated

## Detailed Description of the Pull Request / Additional comments

This includes a maybe unrelated fix to make `TerminalPage`'s `ShortcutActionDispatch` a `com_ptr`. While I was messing with the tests for this, I caught that we're not supposed to direct allocate winrt types like that. Ofc, the `TerminalAppLib` project doesn't catch this.

## Validation Steps Performed
Ran the terminal manually, instead of just running the tests

### CODE REVIEW

File: src/cascadia/TerminalApp/TerminalPage.h [hunk 1]
```diff
@@ -60,7 +60,7 @@ namespace winrt::TerminalApp::implementation
         std::optional<int> _rearrangeFrom;
         std::optional<int> _rearrangeTo;
 
-        ShortcutActionDispatch _actionDispatch{};
+        winrt::com_ptr<ShortcutActionDispatch> _actionDispatch{ winrt::make_self<ShortcutActionDispatch>() };
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalApp/TerminalPage.h]: this perturbs me a bit. something about the complex initializer statement in the header, idk
