### PR TITLE
Fix The conhost command line is not properly escaped

### LINKED ISSUE #1090: Bug Report: The conhost command line is not properly escaped
# Environment

```none
Windows build number: [run "ver" at a command prompt]
Windows Terminal version (if applicable):

Any other software?
```

Today I modified the Windows Terminal configuration file and wanted to create a Pwsh with the emoji title. However, I encountered some confusion in this process. I checked the task manager and found that conhost did not escape when the process was started, causing the command line to parse the exception.

# Steps to reproduce

# Expected behavior

I need to start pwsh by the following command line (note that the following command line is in cmd, or you can start pwsh normally using CreateProcessW.) 
```
"C:\Program Files\PowerShell\7-preview\pwsh.exe" -NoExit -Command "$Host.UI.RawUI.WindowTitle=\"Windows Pwsh 💙 (7 Preview)\""
```

Here is the Windows Terminal configuration file (the command line has been properly escaped):
```json
        {
            "startingDirectory": "C:\\Users\\CharlieInc",
            "guid": "{08a0be98-ff68-4e3a-a054-0fbd3969d3bb}",
            "name": "Windows Pwsh 💙 (7 Preview)",
            "colorscheme": "Campbell",
            "historySize": 9001,
            "snapOnInput": true,
            "cursorColor": "#FFFFFF",
            "cursorShape": "bar",
            "commandline": "\"C:\\Program Files\\PowerShell\\7-preview\\pwsh.exe\" -NoExit -Command \"$Host.UI.RawUI.WindowTitle=\\\"Windows Pwsh 💙 (7 Preview)\\\"\"",
            "fontFace": "Consolas",
            "fontSize": 12,
            "acrylicOpacity": 0.75,
            "useAcrylic": true,
            "closeOnExit": false,
            "padding": "0, 0, 0, 0",
            "icon": "ms-appdata:///roaming/pwsh-32.png"
        }
```

# Actual behavior

As expected, Pwsh should set the title correctly, but pwsh reported the error:
image

Let's take a look at the command line:

image

image

When you see the red line, the command line that pwsh starts is incorrect, and when you start conhost, the command line is still correct!

Currently I have found a suspicious code, most likely this code caused an error:

https://github.com/microsoft/terminal/blob/71e19cd82528d66a0a7867cbed85990cfc1685f1/src/host/ConsoleArguments.cpp#L263-L288

In this code, command line composition is simply a simple connection rather than a concatenated string. If the string contains spaces, this will result in an incorrect command line.

Below is a code for the command line escaping, which may be useful：

```cpp
inline std::wstring escape_argument(std::wstring_view ac) {
  if (ac.empty()) {
    return L"\"\"";
  }
  bool hasspace = false;
  auto n = ac.size();
  for (auto c : ac) {
    switch (c) {
    case L'"':
    case L'\\':
      n++;
      break;
    case ' ':
    case '\t':
      hasspace = true;
      break;
    default:
      break;
    }
  }
  if (hasspace) {
    n += 2;
  }
  if (n == ac.size()) {
    return std::wstring(ac.data(), ac.size());
  }
  std::wstring buf;
  if (hasspace) {
    buf.push_back(L'"');
  }
  size_t slashes = 0;
  for (auto c : ac) {
    switch (c) {
    case L'\\':
      slashes++;
      buf.push_back(L'\\');
      break;
    case L'"': {
      for (; slashes > 0; slashes--) {
        buf.push_back(L'\\');
      }
      buf.push_back(L'\\');
      buf.push_back(c);
    } break;
    default:
      slashes = 0;
      buf.push_back(c);
      break;
    }
  }
  if (hasspace) {
    for (; slashes > 0; slashes--) {
      buf.push_back(L'\\');
    }
    buf.push_back(L'"');
  }
  return buf;
}
```

### PR DESCRIPTION
**Pull request by fcharlie**
## Summary of the Pull Request

This PR is used to fix conhost when the process is started, and the command line is not properly escaped causing an error. For details, please see Issues: #1090 

 
## PR Checklist
* [x] Closes #1090
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [x] Tests added/passed
* [ ] Requires documentation to be updated
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

### CODE REVIEW

**Comment by fcharlie** [comment]
`ConsoleArgumentsTests::ArgSplittingTests` is bad..

File: src/host/ConsoleArguments.cpp [hunk 1]
```diff
@@ -21,6 +21,79 @@ const std::wstring_view ConsoleArguments::INHERIT_CURSOR_ARG = L"--inheritcursor
 const std::wstring_view ConsoleArguments::FEATURE_ARG = L"--feature";
 const std::wstring_view ConsoleArguments::FEATURE_PTY_ARG = L"pty";
 
+std::wstring escape_argument(std::wstring_view ac)
+{
+    if (ac.empty())
+    {
+        return L"\"\"";
+    }
+    bool hasspace = false;
```
Comment (miniksa) [inline src/host/ConsoleArguments.cpp]:
```suggestion
    bool hasSpace = false;
```

Please camel case. This looked like "hass pace" to me.

File: src/host/ConsoleArguments.cpp [hunk 2]
```diff
@@ -21,6 +21,79 @@ const std::wstring_view ConsoleArguments::INHERIT_CURSOR_ARG = L"--inheritcursor
 const std::wstring_view ConsoleArguments::FEATURE_ARG = L"--feature";
 const std::wstring_view ConsoleArguments::FEATURE_PTY_ARG = L"pty";
 
+std::wstring escape_argument(std::wstring_view ac)
```
Comment (miniksa) [inline src/host/ConsoleArguments.cpp]:
```suggestion
std::wstring EscapeArgument(std::wstring_view ac)
```

It doesn't have to be this naming exactly, but I don't think we have any functions in our codebase that we defined with all lowercase names with an underscore pattern.

File: src/host/ut_host/ConsoleArgumentsTests.cpp [hunk 3]
```diff
@@ -90,7 +90,7 @@ void ConsoleArgumentsTests::ArgSplittingTests()
                    INVALID_HANDLE_VALUE,
                    INVALID_HANDLE_VALUE,
                    ConsoleArguments(commandline,
-                                    L"this is the commandline", // clientCommandLine
+                                    L"\"this is the commandline\"", // clientCommandLine
```
Comment (miniksa) [inline src/host/ut_host/ConsoleArgumentsTests.cpp]: We should still maintain a test variant that does it without the quotes in it so we can ensure that the non-quoted string is doing the appropriate thing too.

**Comment by DHowett-MSFT** [comment]
The core issue is that we are relying on the command line arguments coming in pre-mangled by the CRT’s argument parser.

It should be possible to, when we detect that we should switch to “client command line” parsing, just call GetCommandLineW and take the _raw_ unmangled argument string back through CreateProcess.

Would that be a cleaner design that doesn’t require us to re-escape un-escaped strings?

**Comment by DHowett-MSFT** [comment]
Oh, it looks like we aren’t relying on the CRT. Shouldn’t this be easier, then? We should just not mangle the arguments _only to have to unmangle  them later._

**Comment by fcharlie** [comment]
@DHowett-MSFT Using the original command line arguments is possible in this project (but the Windows SDK UCRT still needs to be escaped to fix `spawnv` ), but using the original command line to calculate the offset position of the parameters that conhost can handle will be cumbersome.

In addition, this escaping design refers to golang and is a mature solution.

[https://github.com/golang/go/blob/master/src/syscall/exec_windows.go#L26-L95](https://github.com/golang/go/blob/master/src/syscall/exec_windows.go#L26-L95)

File: src/host/ut_host/ConsoleArgumentsTests.cpp (hunk 3 above)
Comment (fcharlie) [reply src/host/ut_host/ConsoleArgumentsTests.cpp]: I added a test without quotes.

**Comment by fcharlie** [comment]
@miniksa The PR has been updated, but the CI is not responding.

**Comment by fcharlie** [comment]
@DHowett-MSFT  Thanks.

**Comment by fcharlie** [comment]
@DHowett-MSFT  Thanks. Windows Terminal makes me happy
