### PR TITLE
Work around a (likely) optimizer issue with SetPixelShaderPath

### LINKED ISSUE #8723: Crash in `DxEngine::SetPixelShaderPath`
Version: 1.6.3521.0

Unsure of exact repro steps. I edited the settings file and saved it. Presumably that forced an `UpdateSettings`, which is what triggered this?

```c++
void DxEngine::SetPixelShaderPath(std::wstring_view value) noexcept
try
{
    if (_pixelShaderPath != value)
    {
        // Enable shader effects if the path isn't empty. Otherwise leave it untouched.
        _terminalEffectsEnabled = value.empty() ? _terminalEffectsEnabled : true;
        _pixelShaderPath = { value }; // <---- This line right here
        _recreateDeviceRequested = true;
        LOG_IF_FAILED(InvalidateAll());
    }
}
CATCH_LOG()

```

I think making a wstring from an empty string is _bad_.

Relevant stack frames:
```

07 00000082`d4afed30 00007ffe`e8eecb17     TerminalControl!Microsoft::Console::Render::DxEngine::SetPixelShaderPath+0xd4 [E:\BA\184\s\src\renderer\dx\DxRenderer.cpp @ 978] 
08 (Inline Function) --------`--------     TerminalControl!winrt::hstring::operator class std::basic_string_view<wchar_t,struct std::char_traits<wchar_t> >+0x8e [E:\BA\184\s\src\cascadia\TerminalControl\Generated Files\winrt\base.h @ 2788] 
09 00000082`d4afed80 00007ffe`e8e73aa1     TerminalControl!winrt::Microsoft::Terminal::TerminalControl::implementation::TermControl::UpdateSettings$_ResumeCoro$1+0x5b7 [E:\BA\184\s\src\cascadia\TerminalControl\TermControl.cpp @ 313] 
0a (Inline Function) --------`--------     TerminalControl!std::experimental::coroutine_handle<void>::resume+0x9 [C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\include\experimental\coroutine @ 107] 
0b (Inline Function) --------`--------     TerminalControl!std::experimental::coroutine_handle<void>::operator()+0x9 [C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\include\experimental\coroutine @ 99] 
0c 00000082`d4afeec0 00007fff`15424684     TerminalControl!winrt::impl::resume_apartment_callback+0x11 [E:\BA\184\s\src\cascadia\TerminalControl\Generated Files\winrt\windows.ui.core.h @ 1277] 
0d 00000082`d4afeef0 00007fff`153dec9f     Windows_UI!<lambda_59517943c03487243f9bea31c6c1a784>::operator()+0x84 [onecoreuap\windows\advcore\winrt\onecoreiwindow\corewindow\common\dispatcher.cpp @ 908] 

```

### LINKED ISSUE #9064: Unable to find the provided shader "".
Microsoft Windows NT 10.0.19042.0
Windows Terminal Preview Version: 1.6.10272.0

# Steps to reproduce

Open a new tab, with following profile;

-----
      {
        "guid": "{a232ec02-ced9-4160-a72d-16cbc00786c6}",
        "name": "SomeServer",
        "commandline": "c:/profile/someserver.cmd",
        "tabTitle": "SomeServer",
        "backgroundImage": "C:/profile/backdrops/somebackground.jpg",
        "backgroundImageStretchMode": "uniformToFill",
        "backgroundImageOpacity": 0.5,
        "closeOnExit": "always",
        "bellStyle": "none",
        "fontWeight": "light",
        "colorScheme": "Solarized Dark Higher Contrast"
      },
-----

c:/profile/someserver.cmd contains;

-----
set display=localhost:0.0
ssh -Y -C -c aes128-ctr myserver
-----

And myserver is ofc configured in .~/ssh/config as follows

-----
Host *
    ForwardAgent yes
    ForwardX11 yes
    ForwardX11Trusted yes
    IdentityFile ~/.ssh/mykey
    ServerAliveInterval 60
    ServerAliveCountMax 2
    User myusername

Host myserver 
	Hostname <SOMEIP>
	LocalForward 3306 localhost:3306
	IdentityFile ~/.ssh/otherkey
------

# Expected behavior

Open the session without popups, being notified about missing shaders, 
And WT remaining active. I noticed it sometimes completely dissappears, but have not been able to pinpoint exactly if that coincides with the "Unable to find the provided shader ""." message

# Actual behavior

Almost always pops up saying "Warning: Unable to find the provided shader ""."

Below animation shows me opening several tabs with pwsh, powershell, cmd
Before opening the sshserver.cmd profile.
I made a copy of the profile pointing to a different background image, this did not change the behaviour

At the end, we see 1 succesful open, then an open with warning message, then another open with warning message before WT just complete closes (all gone)

ShaderGifSki2

### PR DESCRIPTION
**Pull request by DHowett**
It appears as though the optimizer is generating a sequence of
instructions on x64 that results in a nonsense std::wstring_view being
passed to SetPixelShaderPath when it's converted from a winrt::hstring.

Initially, I suspected that the issue was in us caching `_settings`
before we broke off the coroutine to update settings on the UI thread. I
implemented a quick fix for this (applying values off the new settings
object while also storing it in the control instance), but it didn't
actually lead anywhere. I do think it's the right thing to do for code
health's sake. Pankaj already changed how this works in 1.7: we no
longer (ever) re-seat the `_settings` reference... we only ever change
its parentage. Whether this is right or wrong is not for this paragraph
to discuss.

Eventually, I started looking more closely at the time travel traces. It
seriously looks like the wstring_view is generated wrong to begin with.
The debugger points directly at `return { L"", 0 };` (which is correct),
but the values we get immediately on the other side of the call are
something like `{ 0x7FFFFFFF, 0 }` or `{ 0x0, 0x48454C4C }`.

I moved _just_ the call to SetPixelShaderPath into a separate function.
The bug miraculously disappeared when I marked it **noinline**. It
reappeared when the function was fully inlined.

To avoid any future issues, I moved the whole UI thread body of
UpdateSettings out into its own function, to be called only while on the
UI thread. This fixes the bug.

Closes #8723.
Closes #9064.

## Validation Steps Performed

I found a repro (update the settings file every 0.5 seconds and resize
the terminal wildly while it's doing so) that would trigger the bug
within ~10 seconds. It stopped doing so.

### CODE REVIEW

**Comment by DHowett** [comment]
I have subtly changed the locking here. It is possible for UpdateSettings to take the lock before Initialize does (!), so we need to check a couple more conditions. This is **NOT A NEW ISSUE**.

**Comment by DHowett** [comment]
This pull request targets `release-1.6`. A different fix will need to be made on `main`.

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 1]
```diff
@@ -276,65 +276,89 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
 
     // Method Description:
     // - Given new settings for this profile, applies the settings to the current terminal.
+    // - This method is separate from UpdateSettings because there is an apparent optimizer
+    //   issue that causes one of our hstring -> wstring_view conversions to result in garbage,
+    //   but only from a coroutine context.
```
Comment (zadjii-msft) [inline src/cascadia/TerminalControl/TermControl.cpp:281]:
```suggestion
    //   but only from a coroutine context. See GH#8723.
```

**Review by zadjii-msft — DISMISSED** [review]
This is _mental_ yo. 

Are we doing this targeting 1.6 because `main` has sufficiently different enough code in this area with the appearance settings changes? That makes sense to me - just have to make sure we don't lose this 😉

**Comment by DHowett** [comment]
> This is _mental_ yo.
> 
> Are we doing this targeting 1.6 because `main` has sufficiently different enough code in this area with the appearance settings changes? That makes sense to me - just have to make sure we don't lose this 😉

I'll be targeting main with a different version of this fix.

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 2]
```diff
@@ -276,65 +276,89 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
...
-            _UpdateFont();
-            const auto actualFontNewSize = _actualFont.GetSize();
-            if (actualFontNewSize != actualFontOldSize)
-            {
-                _RefreshSizeUnderLock();
-            }
+        // If 'weakThis' is locked, then we can safely work with 'this'
+        if (auto control{ weakThis.get() })
+        {
+            _UpdateSettingsOnUIThread(newSettings);
```
Comment (miniksa) [inline src/cascadia/TerminalControl/TermControl.cpp:361]: I highly recommend the
```
// LOAD BEARING CODE
// If this is not a call to another function, the optimizer has been shown to completely sack some of the variables due to tripping over the coroutine.
// Please call out to another method here.
```

**Review by miniksa — APPROVED** [review]
