### PR TITLE
Fix a crash when resizing conhost in Debug

### LINKED ISSUE #12917: "invalid bounds arguments passed to std::clamp" when resizing window to zero height
### Windows Terminal version

1.12.10733.0

### Windows build number

10.0.22000

### Other Software

_No response_

### Steps to reproduce

Launch OpenConsole.exe compiled in debug mode, drag bottom of the window to the very top.

### Expected Behavior

No assertion

### Actual Behavior

Assertion from from STL `"invalid bounds arguments passed to std::clamp"` on the line
```cpp
clampMe.Top = std::clamp(clampMe.Top, Top(), BottomInclusive());
```
in `Viewport Viewport::Clamp`
<details>
<summary>Call stack</summary>
<pre>
 	ucrtbased.dll!00007ff9248a7fbc()	Unknown
 	ucrtbased.dll!00007ff9248a7ef4()	Unknown
 	ucrtbased.dll!00007ff9248a7d90()	Unknown
>	OpenConsole.exe!std::clamp<short,std::less<void>>(const short & _Val, const short & _Min_val, const short & _Max_val, std::less<void> _Pred) Line 10188	C++
 	OpenConsole.exe!std::clamp<short>(const short & _Val, const short & _Min_val, const short & _Max_val) Line 10208	C++
 	OpenConsole.exe!Microsoft::Console::Types::Viewport::Clamp(const Microsoft::Console::Types::Viewport & other) Line 245	C++
 	OpenConsole.exe!Microsoft::Console::Render::Renderer::TriggerRedrawCursor(const _COORD * const pcoord) Line 284	C++
 	OpenConsole.exe!TextBuffer::TriggerRedrawCursor(const _COORD position) Line 992	C++
 	OpenConsole.exe!Cursor::_RedrawCursorAlways() Line 190	C++
 	OpenConsole.exe!Cursor::SetIsOn(const bool fIsOn) Line 103	C++
 	OpenConsole.exe!Microsoft::Console::CursorBlinker::TimerRoutine(SCREEN_INFORMATION & ScreenInfo) Line 153	C++
 	OpenConsole.exe!CursorTimerRoutineWrapper(_TP_CALLBACK_INSTANCE * __formal, void * __formal, _TP_TIMER * __formal) Line 24	C++
 	ntdll.dll!TppTimerpExecuteCallback()	Unknown
 	ntdll.dll!TppWorkerThread()	Unknown
 	kernel32.dll!00007ff9feee54e0()	Unknown
 	ntdll.dll!RtlUserThreadStart()	Unknown
</pre>
</details>

Looks like it happens because `SCREEN_INFORMATION::_InternalSetViewportSize` increases viewport's `Top` in `srNewViewport.Top -= DeltaY;` (`DeltaY` is negative) line without any check to prevent `Top` becoming more than `Bottom` which sadly can happen. Clamp cannot work when `Top` is more than `Bottom`

### PR DESCRIPTION
**Pull request by zadjii-msft**
Don't clamp here, it's unnecessary. See notes in https://github.com/microsoft/terminal/issues/12917#issuecomment-1101423091

Closes #12917

### CODE REVIEW

File: src/renderer/base/renderer.cpp [hunk 1]
```diff
@@ -281,9 +281,7 @@ void Renderer::TriggerRedrawCursor(const COORD* const pcoord)
         // The region is clamped within the viewport boundaries and we only
         // trigger a redraw if the region is not empty.
         auto view = _pData->GetViewport();
-        cursorView = view.Clamp(cursorView);
-
-        if (cursorView.IsValid())
+        if (view.IsInBounds(cursorView))
```
Comment (DHowett) [inline src/renderer/base/renderer.cpp:284]: What a strange way for us to do this. And `IsInBounds` doesn't beef? Neat!

Comment (DHowett) [reply src/renderer/base/renderer.cpp:284]: I mean the old way was strange.

**Review by DHowett — APPROVED** [review]

File: src/renderer/base/renderer.cpp (hunk 1 above)
Comment (j4james) [reply src/renderer/base/renderer.cpp:284]: I guess it's a bit late to tell you now, but I don't think this is right. I haven't had a chance to check, but I think `IsInBounds` is testing whether the whole `cursorView` is inside the `view`, but that means a cursor that is partially off screen is probably not going to be refreshed.

Comment (DHowett) [reply src/renderer/base/renderer.cpp:284]: Hmmmmm..

Would this come up when the cursor is on a double-width glyph and the viewport is scrolled such that it cuts that glyph in half?

Comment (j4james) [reply src/renderer/base/renderer.cpp:284]: Yeah. Also on a double-width line, or even a double-width glyph on a double-width line, which can be four characters wide.
