### PR TITLE
Fix racy access to _tsfTryRedrawCanvas in TermControl

### LINKED ISSUE #10302: Exiting a tab sometimes closes the entire window
### Windows Terminal version (or Windows build number)

1.8.1444.0

### Other Software

- GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu) (in WSL)
- Windows PowerShell 7.1.3

### Steps to reproduce

This is a very intermittent bug, but the consequences are rather catastrophic when the bug does occur. Very rarely, when I type `exit` inside either a WSL bash session or in PowerShell, the entire Windows Terminal window exits, rather than just individual tab.

### Expected Behavior

I would expect just the individual tab to close when I exit a WSL bash or Windows PowerShell session.

### Actual Behavior

All tabs close, terminating other terminals that have long-running jobs in them.

### LINKED ISSUE #10479: Entire Terminal app is randomly crashing while closing tabs
### Windows Terminal version (or Windows build number)

1.8.1521.0

### Other Software

_No response_

### Steps to reproduce

1. Set WSL profile as default one
2. Open a lot of tabs with Ctrl+Shift+T
3. Start closing them with Ctrl+D

### Expected Behavior

Tabs should either close, or tab contents should end with `Process exited with code XXXXXX`

### Actual Behavior

Whole Terminal app is crashing, with all sessions that were running inside it. I'm seeing this behavior on two separate machines.

It is happening randomly, most of the time it works correctly, but I had a couple of situations where entire Terminal crashed while I was doing more important things :(

This is WSL profile I have on my laptop, the other one has no theme or font settings.
```
           {
                "bellStyle": "none",
                "closeOnExit": "graceful",
                "colorScheme": "One Half Dark",
                "cursorShape": "filledBox",
                "fontFace": "Terminus (TTF) for Windows",
                "fontSize": 9,
                "guid": "{07b52e3e-de2c-5db4-bd2d-ba144ed6c273}",
                "hidden": false,
                "historySize": 50000,
                "name": "Ubuntu-20.04",
                "source": "Windows.Terminal.Wsl",
                "startingDirectory": "\\\\wsl$\\Ubuntu-20.04\\home\\patryk",
                "useAcrylic": false
            }
```

### PR DESCRIPTION
**Pull request by lhecker**
Previously `TermControl::Close` destroyed all `ThrottledFunc`s to ensure they're not scheduling any callbacks on the UI thread, as the call to `Close` signals the point at which the `TermControl` isn't part of the UI thread anymore. `_CursorPositionChanged` tried to prevent access to the potentially deallocated `_tsfTryRedrawCanvas` by checking the `std::shared_ptr` for nullability, but since the deallocation happens on the UI thread and the nullability check on a background thread, this check introduced a race condition.

This commit solves the issue by not deallocating any `ThrottledFunc`s anymore and instead checking the `_closing` flag inside the `ThrottledFunc` callback on the UI thread.

Additionally this commit cleans up some antipatterns around the use of `std::optional`.

## PR Checklist
* [x] Closes #10479
* [x] Closes #10302

## Validation Steps Performed

* Opening and closing tabs doesn't crash ✔️
* Printing long text doesn't crash ✔️
* Manual scrolling doesn't crash ✔️
* ^G / the audible bell doesn't crash ✔️

### CODE REVIEW

File: src/cascadia/TerminalControl/TermControl.h [hunk 1]
```diff
@@ -183,6 +183,12 @@ namespace winrt::Microsoft::Terminal::Control::implementation
 
         winrt::Windows::UI::Xaml::Controls::SwapChainPanel::LayoutUpdated_revoker _layoutUpdatedRevoker;
 
+        inline bool _IsClosing() const noexcept {
+            // _closing isn't atomic and may only be accessed from the main thread.
+            assert(Dispatcher().HasThreadAccess());
```
Comment (lhecker) [inline src/cascadia/TerminalControl/TermControl.h:188]: I previously wanted to introduce a cool macro for this in WinRTUtils, but I realized, that global state would only work properly if it's shared using a .dll. A .lib like that wouldn't do that for us. 😟

**Comment by lhecker** [comment]
A branch with a minimalistic set of changes for 1.8 is ready for backporting.

This PR in particular needs to be evaluated very carefully and theoretically as the interaction with `_closing` is basically a "logical race condition". Despite that I forgot to set the `_closing` variable to `true` prior to my latest commit, the code worked fine on my PC through many rounds of testing, which just further proves how much of a race condition this really is.

**Comment by DHowett** [comment]
note: i edited your PR body to make sure the `Closes` verb was repeated for each closed issue. GitHub will not close two issues if you say `Closes X, Y`.

File: src/cascadia/TerminalControl/TermControl.h (hunk 1 above)
Comment (DHowett) [reply src/cascadia/TerminalControl/TermControl.h:189]: This assert is compiled out in debug builds, correct?

Comment (DHowett) [reply src/cascadia/TerminalControl/TermControl.h:189]: Sorry, compiled out in release builds./

**Review by DHowett — APPROVED** [review]

**Review by carlos-zamora — APPROVED** [review]
