### PR TITLE
Fix for some profiles.defaults settings not working

### LINKED ISSUE #9761: New Tab does not Display the Background Image
### Windows Terminal version (or Windows build number)

Windows Build: 10.0.19042.906, Windows Terminal commit b310b1c built using Visual Studio 2019 16.9.3

### Other Software

oh-my-posh 3.133.1
posh-git 1.0.0 (Latest)
PSReadLine 2.1.0

Ubuntu WSL 20.04

### Steps to reproduce

Build Windows Terminal using visual studio. Release, x64, CascadiaPackage

1) Configure a profile to use a background.
image

2) Exit Terminal
3) Run Terminal and the background will be solid gray and not the image selected in step 1
image

5) Open Settings
6) Save Settings
7) The open tab background will show the background specified in settings
image

8) Start a new tab, and the background will be solid gray
image

The kind of shell doesn't seem to affect this. I've tried Powershell 7.1.3, Ubuntu 20.04, git bash using MINGW64.

### Expected Behavior

Opening a new Windows Terminal tab shows the background image specified in the profile. 

### Actual Behavior

Opening a new Windows Terminal tab does not show the background image specified in the profile. 

### Included Settings.json
[settings.zip](https://github.com/microsoft/terminal/files/6287896/settings.zip)

### PR DESCRIPTION
**Pull request by PankajBhojwani**
Fix for profiles.defaults.colorScheme not working 
Fix for background image only showing up after a settings reload

Closes #9761

### CODE REVIEW

**Review by zadjii-msft — APPROVED** [review]

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 1]
```diff
@@ -910,6 +910,9 @@ namespace winrt::Microsoft::Terminal::Control::implementation
             //      becomes a no-op.
             this->Focus(FocusState::Programmatic);
 
+            // Now that the renderer is set up, update the appearance for initialization
+            UpdateAppearance(_settings);
```
Comment (DHowett) [inline src/cascadia/TerminalControl/TermControl.cpp:914]: I am *still* deeply uncomfortable with us going from the main thread (initializing), under lock, and pushing another block onto the main thread queue that takes the lock and updates the appearance.

This is all stuff that could be done directly on the main thread without the intermediate step-off-step-back-onto-the-main-thread business.

Is the only problem that UpdateAppearance->UpdateAppearanceOnMainThread _takes the lock_ that is held in this function? If so, make it `_UpdateAppearanceOnMainThreadUnderLock` and make sure that all callers take the correct lock before calling it.

**Review by DHowett — CHANGES_REQUESTED** [review]

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 1 above)
Comment (DHowett) [reply src/cascadia/TerminalControl/TermControl.cpp:914]: I'm uncomfortable with it because we're introducing a point in the middle, during initialization, where somebody else could get code running on the main thread and manipulate the state of the terminal. Imagine us losing focus between Initialize and when UpdateAppearance finally runs -- we'll flicker to unfocused appearance and then THIS UpdateAppearance will finally trigger and flip it back to focused¹


¹ assuming that the focus change is scheduled in between [Init] and [UpdateAppearance(settings)]
² unless the focus handler itself dispatches BACK to the main thread (even though it started there), then the queue becomes... `Init ; Handle Focus ; UpdateAppearance(settings) ; UpdateAppearance(unfocusedSettings)` (which _works_, but... why)

Comment (PankajBhojwani) [reply src/cascadia/TerminalControl/TermControl.cpp]: Thank you for the explanation! Changed to `_UpdateAppearanceOnUIThreadUnderLock` and `_UpdateSettingsOnUIThreadUnderLock`, and the callers take the lock before calling it

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 2]
```diff
@@ -820,8 +823,6 @@ namespace winrt::Microsoft::Terminal::Control::implementation
             // the first paint will be ignored!
             dxEngine->SetWarningCallback(std::bind(&TermControl::_RendererWarning, this, std::placeholders::_1));
 
-            dxEngine->SetRetroTerminalEffect(_settings.RetroTerminalEffect());
```
Comment (DHowett) [inline src/cascadia/TerminalControl/TermControl.cpp:823]: why did these get nuked?

Comment (DHowett) [reply src/cascadia/TerminalControl/TermControl.cpp:823]: oh, they're in the appearance setup aren't they!

**Comment by DHowett** [comment]
Requested some "hardiness" tests over Teams

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 2 above)
Comment (PankajBhojwani) [reply src/cascadia/TerminalControl/TermControl.cpp:823]: Yep, they're in the `_UpdateAppearanceFromUIThreadUnderLock` call below (really should have been nuked in the original PR tbh)

**Review by DHowett — APPROVED** [review]

**Comment by DHowett** [comment]
@msftbot merge this in 1 minute
