### PR TITLE
Make Mark Mode keybindings precede custom keybindings

### LINKED ISSUE #13533: Mark Mode should preempt key bindings, and work with anything that causes scrolling...
### Windows Terminal version

1.15.1862.0

### Windows build number

10.0.19042.0

### Other Software

_No response_

### Steps to reproduce

I know the mark mode keyboard selection is still very early days. I just wanted to make sure the expected behaviors are all covered, and I didn't see this called out.

Any hotkey that pre-exists the mark mode currently interfere with selection. That is, currently:

- Mark mode seems to only works with the default windows text navigation keys: the arrows, PgUp/PgDn, home/end.
- **Selecting** requires turning on mark mode and then holding shift while pressing those keys.

If the user has an "Action" configured for `Ctrl+Shift+Home` or `Ctrl+Shift+PgUp` or whatever, that action will trigger **instead of** the selection.

Additionally, nothing else that scrolls the buffer causes the mark to move or select:

- Scrolling with the mouse
- Scrolling with scrollToMark
- Scrolling via the command palette (Ctrl+Shift+P)

On top of that, we can't **usefully** turn on mark mode _after_ scrolling, because it always appears at the bottom.

### Expected Behavior

Mark mode should probably be called "selection" mode, to disambiguate with the new "marks" ...

Mark mode should disregard actions that consume Arrows/PgUp/PgDn/Home/End  -- or possibly, should ignore all actions except selection-specific actions or Esc to cancel, changing all the hotkeys like a `vi` mode does.

The "mark" should follow the scroll buffer if the buffer is scrolled via other actions. Ideally, it should select when that happens with SHIFT pressed. 

The mark should always appear _within the visible buffer_ when it's invoked, **not** only at the bottom/prompt.

### Actual Behavior

The mark only ever appears at the prompt, and can only be used if you haven't configured actions over the default text selection keys.

### PR DESCRIPTION
**Pull request by carlos-zamora**
## Summary of the Pull Request
This PR moves the key handling for mark mode into a helper method that is then called before an action/key binding is attempted. 

## References
Epic: #4993 
Closes #13533

## Validation Steps Performed
- Add custom keybinding to "down" arrow key
- in mark mode --> selection updates appropriately
- out of mark mode --> keybinding executed

### CODE REVIEW

**Comment by carlos-zamora** [comment]
Hmm... I'm marking this as a service-able bugfix. But if anybody disagrees, let me know.

File: src/cascadia/TerminalControl/ControlCore.cpp [hunk 1]
```diff
@@ -389,6 +389,60 @@ namespace winrt::Microsoft::Terminal::Control::implementation
         return _terminal->SendCharEvent(ch, scanCode, modifiers);
     }
 
+    bool ControlCore::TryMarkModeKeybinding(const WORD vkey,
+                                            const ::Microsoft::Terminal::Core::ControlKeyStates modifiers)
+    {
+        if (HasSelection() &&
```
Comment (zadjii-msft) [inline src/cascadia/TerminalControl/ControlCore.cpp:395]: Methinks

```c++
            HasSelection() &&
            !KeyEvent::IsModifierKey(vkey) &&
            vkey != VK_SNAPSHOT &&
```

should probably also be pulled into a helper, so that we don't only alter one of `TryMarkModeKeybinding` and `TrySendKeyEvent`

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 2]
```diff
@@ -1085,7 +1085,10 @@ namespace winrt::Microsoft::Terminal::Control::implementation
         // keybindings on the keyUp, then we'll still send the keydown to the
         // connected terminal application, and something like ctrl+shift+T will
         // emit a ^T to the pipe.
-        if (!modifiers.IsAltGrPressed() && keyDown && _TryHandleKeyBinding(vkey, scanCode, modifiers))
+        if (!modifiers.IsAltGrPressed() &&
+            keyDown &&
+            (_core.TryMarkModeKeybinding(vkey, modifiers) ||
+             _TryHandleKeyBinding(vkey, scanCode, modifiers)))
```
Comment (lhecker) [inline src/cascadia/TerminalControl/TermControl.cpp:1091]: What about `if (_core.IsInReadOnlyMode())`?
Shouldn't we call `_core.TryMarkModeKeybinding(vkey, modifiers)` inside `_TryHandleKeyBinding`?

**Review by lhecker — APPROVED** [review]

**Review by zadjii-msft — APPROVED** [review]
