### PR TITLE
Fixed #521 - AltGr combinations not working

### LINKED ISSUE #521: AltGR SEQUENCES DO NOT WORK -- Can't type any AltGr combinations in Windows Terminal
**Your Windows build number:**
 10.0.18362.86

**What you're doing and what's happening:**
Trying to enter the `@` sign on a Swedish keyboard in a PowerShell console using `Alt Gr` + `2`.  
See animated gif:

terminal

**What's wrong / what should be happening instead:**
Windows terminal shows `digit-argument` instead of outputting the `@` sign as expected.

It's possible this is a PEBKAC error somehow but the problem doesn't show up in the normal PowerShell console... 😓

### PR DESCRIPTION
**Pull request by lhecker**
## Summary of the Pull Request

Let's start fixing #521 and the currently broken state of AltGr combinations, as it heavily affects many non-US users of this project.

## PR Checklist
* [ ] Closes #521
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [x] Tests added/passed
* [ ] Requires documentation to be updated
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #521

## Detailed Description of the Pull Request / Additional comments

I'm about 100% sure that this PR is not going to fix #521 by itself, but it's a start. 🙂
If others wan't to contribute to this PR, please feel free to do so. I'll gladly grant push permissions to my fork.

If you want to view the diff here on GitHub I recommend enabling "Hide whitespace changes" in the diff viewer.

## Validation Steps Performed

This PR fixes all immediate/obvious issues in regards to AltGr for me in all types of shells I know.
I think it's fairly easy to see why it works, since I simply delegate the handling to `WM_CHAR` instead.

### CODE REVIEW

**Comment by lhecker** [comment]
Alright... I've spent 5 hours on this thing today. Dammit. I hope it was worth it. 😄

This PR should now be far more robust than my basic solution in #521.
I've changed the `Terminal` class to actually propagate the left/right states of Alt/Ctrl separately down into the `TerminalInput` class. That way we can continue (or... technically start...) using `keyEvent.IsAltGrPressed()` in the `HandleKey` method.

This also has the nice side effect of this PR allowing others to continue pressing Ctrl+Alt without it being confused for a AltGr key press.
For instance if I press AltGr+@ on my german keyboard it will now insert a @ character, **BUT** if I press Alt+Ctrl+Q it will properly send an escape sequence instead, just like it used to.

I've also fixed the input tests I believe, which now...
* Reflect the changes to AltGr being handled by WM_CHAR instead
* Added the missing Ctrl+/ sequence check - without it the tests are failing on systems with non-US keyboards

**Comment by DHowett-MSFT** [comment]
This is exciting. Thanks so much for looking at it! We’ll probably get to reviewing this after the weekend. 😄

File: src/terminal/input/terminalInput.cpp [hunk 1]
```diff
@@ -374,25 +374,16 @@ bool TerminalInput::HandleKey(const IInputEvent* const pInEvent) const
...
+            // E.g. on a German keyboard AltGr+Q should result in the "@" character,
+            // but actually results in "Q" with Alt and Ctrl modifier states.
+            // By returning false though, we can abort handling this WM_KEYDOWN
+            // event and let the WM_CHAR handler kick in, which will be
+            // provided with an appropriate unicode character.
             if (keyEvent.IsAltGrPressed())
             {
-                keyEvent.DeactivateModifierKey(ModifierKeyState::LeftCtrl);
-                keyEvent.DeactivateModifierKey(ModifierKeyState::RightAlt);
+                return false;
```
Comment (lhecker) [inline src/terminal/input/terminalInput.cpp]: Regarding the upcoming review:
I'm particularly concerned about this part of the code, as I'm uncertain which non-Cascadia parts of this project might be negatively affected.
Do you think I should rather move this check into Cascadia (e.g. into `Terminal::SendKeyEvent` above)?

Comment (lhecker) [reply src/terminal/input/terminalInput.cpp]: Honestly I kinda feel like `terminalInput.cpp` should actually remain untouched and the following should be changed to properly "pretranslate the UnicodeChar to the proper alternative value" instead (like the original comment claims):
https://github.com/microsoft/terminal/blob/bc236c7c59b3b19765e20e361b0039c2d12b81f8/src/cascadia/TerminalCore/Terminal.cpp#L221-L237

Comment (lhecker) [reply src/terminal/input/terminalInput.cpp]: In fact it seems like the "old" Terminal version did just that if I'm not mistaken:
https://github.com/microsoft/terminal/blob/b9e66fee6d6e131b6711b8e44607d16584d05c98/src/interactivity/win32/windowio.cpp#L201-L205

Comment (miniksa) [reply src/terminal/input/terminalInput.cpp]: Let me look into this.

Comment (miniksa) [reply src/terminal/input/terminalInput.cpp]: Yes, correct. Please do move this concern into the `TerminalCore/Terminal.cpp` method of `Terminal::SendKeyEvent` if possible to resolve this issue.

Modifying the `terminal/input/terminalInput.cpp` will influence the behavior of client applications hosted in the ConPTY that are submitting input information with the `WriteConsoleInput` method.

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 2]
```diff
@@ -1428,17 +1428,35 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
...
+            { VirtualKey::LeftControl, LEFT_CTRL_PRESSED },
+            { VirtualKey::Shift, SHIFT_PRESSED },
+        } };
+
+        DWORD flags = 0;
+
+        for (const auto& mod : modifiers)
+        {
+            const auto state = window.GetKeyState(mod.vkey);
+            const auto isDown = WI_IsFlagSet(state, CoreVirtualKeyStates::Down);
```
[the remark this answers is not in the document]
Comment (lhecker) [reply src/cascadia/TerminalControl/TermControl.cpp]: `WI_SetFlagIf` only works for compile time constants. I could make the `modifiers` a constexpr, but that won't help with the loop and everything past that might not be worth the effort IMO.
What do you think?

File: src/terminal/adapter/ut_adapter/inputTest.cpp [hunk 3]
```diff
@@ -356,165 +362,171 @@ void InputTest::TerminalInputModifierKeyTests()
...
+                    if (ControlPressed(uiKeystate))
+                    {
+                        // Generally the control key is key-0x40
+                        wchShifted = vkey - 0x40;
+                    }
+                    s_pwsInputBuffer[1] = wchShifted;
+                }
+                else
+                {
+                    fExpectedKeyHandled = (vkey >= '0' && vkey <= 'Z') || vkey == VK_CANCEL;
```
[the remark this answers is not in the document]
Comment (lhecker) [reply src/terminal/adapter/ut_adapter/inputTest.cpp]: I've reverted this part of the code and left it unchanged. 🙂

File: src/terminal/input/terminalInput.cpp (hunk 1 above)
Comment (lhecker) [reply src/terminal/input/terminalInput.cpp]: I've reverted the entire file. 🙂

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (miniksa) [reply src/cascadia/TerminalControl/TermControl.cpp]: Nah, leave it as is then. Sorry, my mental compiler didn't realize it was compile-time only flags.

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 4]
```diff
@@ -1417,8 +1417,8 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
     //   find out which modifiers (ctrl, alt, shift) are pressed in events that
     //   don't necessarily include that state.
     // Return Value:
-    // - a KeyModifiers value with flags set for each key that's pressed.
-    Settings::KeyModifiers TermControl::_GetPressedModifierKeys() const
+    // - The combined ControlKeyState flags as a bitfield.
+    DWORD TermControl::_GetPressedModifierKeys() const
```
[the remark this answers is not in the document]
Comment (miniksa) [reply src/cascadia/TerminalControl/TermControl.cpp]: To be fair, I don't mind it this way.

**Comment by lhecker** [comment]
@miniksa Thank you for your kind review! I've reverted most parts of the changeset and tried to be as minimalistic as possible this time. You'll find that the diff should be easier to read now.

I _could_ optimize the code structure here and there to use e.g. switches (like I did originally), but I feel like I might not be following any plans you guys might already have in mind for this project. For now I'd like make this PR simple and leave any larger refactorings to you. 🙂

Except of course... Regarding the `modifiers` bitfield... I also don't think my current approach is acceptable either.
I'm slightly unsure what you mean with "expand it [the `Settings::KeyModifiers` structure] to have a preference" though.
What I'd like to suggest is to write a class that abstracts over the exact same bitfield used by the TerminalInput module, but provides a simplified API to query for Alt/Ctrl/AltGr states, similar to how `KeyEvent` does it already. That way this class would stay compatible with the DWORD based APIs. 🙂
Since the diff is relatively minimalistic such changes can be done at any point in time though IMO.
Either way is fine for me (i.e. me writing this class or not as part of this PR).

**Comment by yveslange** [comment]
Please, can you review this issue ? For most people in Sweden, Germany and Switzerland the terminal with WSL is unusable at the moment without this patch.

**Comment by utybo** [comment]
Also relatively unusable for French users, given that this prevents using all sorts of keys. `#{[|\^@]}` all require pressing AltGr for French AZERTY keyboards.

**Comment by pekkah** [comment]
Same for Finnish users. Cannot navigate paths as cannot type path separators.

**Comment by miniksa** [comment]
> @miniksa Michael Niksa FTE Thank you for your kind review! I've reverted most parts of the changeset and tried to be as minimalistic as possible this time. You'll find that the diff should be easier to read now.
> 
> I _could_ optimize the code structure here and there to use e.g. switches (like I did originally), but I feel like I might not be following any plans you guys might already have in mind for this project. For now I'd like make this PR simple and leave any larger refactorings to you. 🙂
> 
> Except of course... Regarding the `modifiers` bitfield... I also don't think my current approach is acceptable either.
> I'm slightly unsure what you mean with "expand it [the `Settings::KeyModifiers` structure] to have a preference" though.
> What I'd like to suggest is to write a class that abstracts over the exact same bitfield used by the TerminalInput module, but provides a simplified API to query for Alt/Ctrl/AltGr states, similar to how `KeyEvent` does it already. That way this class would stay compatible with the DWORD based APIs. 🙂
> Since the diff is relatively minimalistic such changes can be done at any point in time though IMO.
> Either way is fine for me (i.e. me writing this class or not as part of this PR).
> 
> _Edit_: Ah you're already done reviewing. 😅

If you could write a follow on issue or PR to make it into a nice class that does what you say... that would be ideal.



For everyone else, I'll try to get someone else to 2nd this and we can correct anything that @zadjii-msft finds disagreeable later when he gets back.

**Comment by lhecker** [comment]
@miniksa Do you believe it might be possible to get this PR through until the weekend? Coincidentally I'm going to have some free time then and could work on that. But don't worry if it's not possible. We'll find the necessary time/solution either way, right? 🙂

**Comment by miniksa** [comment]
@lhecker, I think we could merge it today if I can find someone with 15 minutes to read it. Let me keep trying. We have had meetings this afternoon.

**Comment by patriksvensson** [comment]
@lhecker Just noticed this was merged. Thank you so much for submitting a PR and fixing this issue!
