### PR TITLE
Fix IME/CoreTextEditContext not being reset properly

### LINKED ISSUE #3645: TSFInputControl NotifyFocusLeave causes IME to no longer show
from #1919 

Code TODO, if the IME is notified that Focus has left it causes the IME to no longer show.  It's unclear if the IME needs to know Focus is leaving.  Investigate if the call is required. and re-enable the call in the code:

```
    void TSFInputControl::NotifyFocusLeave()
    {
        if (_editContext != nullptr)
        {
            // _editContext.NotifyFocusLeave();
        }
    }
```

### LINKED ISSUE #3706: When entering a Chinese punctuation, it acts like keeping hitting the key
# Environment

```none
Windows build number: 10.0.19030.1
Windows Terminal version: 0.7.3291.0
```

# Steps to reproduce

Hit the key "，" (or other punctuation) in windows terminal with Chinese input method 

# Expected behavior

Output a "，" (I delete the extra "，" in the following picture manually)

image

# Actual behavior

keeps outputting "，" just like I keep hitting the "，"

image

# Some other information

1. I have reproduced it in Windows Terminal using wsl, cmd and powershell7-preview on my two PCs.
2. Another phenomenon is that Windows Terminal add space behind Chinese character automatically after my inputting one character.

### LINKED ISSUE #3745: Needs to input twice to insert a single Chinese symbol
# Environment

```none
Windows build number: 18363.476
Windows Terminal version (if applicable): 0.7.3291.0
```

# Steps to reproduce
1. switch to Microsoft Chinese Input Method
2. press `shift` + `/` to insert a Chinese `？`

# Expected behavior
`？` successfully inserted

# Actual behavior
I have to press `shift` + `/` twice to insert a single `？`

Same problem with other Chinese symbols, such as `《`, `》`, `【`, `】` and etc.

### PR DESCRIPTION
**Pull request by lhecker**
The first argument to `NotifyTextChanged` incorrectly was `[0,0]`
instead of the length of the text to be removed from the
`CoreTextEditContext`.

Best source of documentation for `NotifyTextChanged`:
https://docs.microsoft.com/en-us/windows/uwp/design/input/custom-text-input#overriding-text-updates

FYI @DHowett-MSFT (just in case): C++/WinRT uses `winrt::param::hstring`
for string parameters which intelligently borrows strings. As such you
can simply pass a `std::wstring` to most WinRT methods without the need
of having to allocate an intermediate `hstring`. 🙂

## Validation Steps Performed

I followed the reproduction instructions of #3706 and #3745 and ensured
the issue doesn't happen anymore.

Closes #3645
Closes #3706
Closes #3745

### CODE REVIEW

**Comment by lhecker** [comment]
BTW the IME integration is still not quite perfect yet. It's truly the easiest to reproduce if you install the chinese language and play around with the editor. For instance if you switch to chinese and press <kbd>Win</kbd><kbd>.</kbd> you'll notice that it fails to insert most of the symbols on the "Symbols" tab most of the time, unless you also type some regular words without the use of <kbd>Win</kbd><kbd>.</kbd>.

File: src/cascadia/TerminalControl/TSFInputControl.cpp [hunk 1]
```diff
@@ -104,7 +104,7 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
     {
         if (_editContext != nullptr)
         {
-            // _editContext.NotifyFocusLeave(); TODO GitHub #3645: Enabling causes IME to no longer show up, need to determine if required
+            _editContext.NotifyFocusLeave();
```
Comment (philnach) [inline src/cascadia/TerminalControl/TSFInputControl.cpp]: Can you double check that the IME with multiple tabs still works as expected and after closing tabs?  I seem to recall the IME would get into a state where it would not longer appear.

File: src/cascadia/TerminalControl/TSFInputControl.cpp [hunk 2]
```diff
@@ -209,23 +209,16 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
...
 
-            // tell the input server that we've cleared the buffer
-            CoreTextRange emptyTextRange;
-            emptyTextRange.StartCaretPosition = 0;
-            emptyTextRange.EndCaretPosition = 0;
-
             // indicate text is now 0
-            _editContext.NotifyTextChanged(emptyTextRange, 0, emptyTextRange);
-            _editContext.NotifySelectionChanged(emptyTextRange);
+            _editContext.NotifyTextChanged({ 0, bufferLength }, 0, { 0, 0 });
```
Comment (philnach) [inline src/cascadia/TerminalControl/TSFInputControl.cpp]: @lhecker, great catch! I struggled with this call for a while.

File: src/cascadia/TerminalControl/TSFInputControl.cpp (hunk 1 above)
Comment (lhecker) [reply src/cascadia/TerminalControl/TSFInputControl.cpp]: Do you mean this Window?
image

If yes, then I believe it works correctly, albeit slightly different compared to `origin/master`:
The current Windows Store version closes the IME after inserting a character. The version I built myself from this branch behaves like other software (like Firefox) on the other hand and doesn't close the Window unless you defocus it.
If you do have the time I would of course be very happy if you (or maybe someone else) could verify my changes. 🙂

BTW This PR doesn't fix the above "Emoji-Window" for the Chinese language though: Neither the Store nor my Dev version inserts any characters if I click any buttons in the Window.

Comment (lhecker) [reply src/cascadia/TerminalControl/TSFInputControl.cpp]: P.S.: Oh and the Unicode support is incomplete of course as can be seen in the above screenshot, but that's another story I suppose.

Comment (philnach) [reply src/cascadia/TerminalControl/TSFInputControl.cpp]: Definently sounds like a big improvement.  I'll pull down your branch and double check.

Comment (philnach) [reply src/cascadia/TerminalControl/TSFInputControl.cpp]: I took a look, I built both debug and release versions of your change and am still seeing #3745 , I can't reproduce #3706 .  

#3745 doesn't reproduce on the initial character, but consecutive characters (shift+/) get eaten and then eventually displayed.  I'm in Chinese (Simplfied, China) Microsoft Pinyin input method mode.

I also didn't run into any issues with my original concerns around IME not rendering.

Overall, I think we are good with this change as it definently fixes #3645 and #3706.  I'm just not sure about #3745.  @zadjii-msft any chance you can double check what I'm seeing with #3745?

Comment (zadjii-msft) [reply src/cascadia/TerminalControl/TSFInputControl.cpp]: If I can't get to it tonight (3pm PST), then I'll give it a shot in the morning

Comment (lhecker) [reply src/cascadia/TerminalControl/TSFInputControl.cpp]: I did a clean build of this branch (`bcz dbg`) and tried to reproduce #3745 again.
Just to ensure I'm doing the same as you, @philnach, and others:

When the Terminal App is focused, your taskbar looks like this right?
image

And pressing the lone shift key (which is to the left of the right shift key), causes a `、` character to be printed?

In that case I'm not sure what I'm doing differently.
If I start a fresh instance of the App and press <kbd>Shift</kbd><kbd>/</kbd> 3 times, it prints ` ？？？` for me. 😕

Apart from that the following could make a difference:
* I'm using a German keyboard (instead of <kbd>/</kbd> it's a <kbd>-</kbd> for me), but if a Chinese input mode is used it should use the same virtual key code to a US one either way
* Fully updated Visual Studio 16.4.2
* I'm a Windows Insider on 19041.1

Comment (zadjii-msft) [reply src/cascadia/TerminalControl/TSFInputControl.cpp]: Okay, I don't know if I'm doing it right, but I _maybe_ got #3745 to repro locally. I was changing input modes frequently and honestly I'm not sure I was doing it right at all. I'm still trying to make it happen again and I can't seem to. Maybe it has something to do with the shell? @philnach were you using `bash`, `cmd`, `pwsh`?

Comment (lhecker) [reply src/cascadia/TerminalControl/TSFInputControl.cpp]: Oh and btw @philnach: [This](https://drive.google.com/file/d/1xh-Y7j4l2Ns1oudhNoGu_3ESSFN4NhPj/view) is what I meant earlier when I said that the "Emoji-Window" doesn't insert anything when I use the Chinese input method. It seems to be slightly similar to the overarching "consecutive characters get eaten and then eventually displayed" issue.

Comment (philnach) [reply src/cascadia/TerminalControl/TSFInputControl.cpp]: @zadjii-msft , I'm using cmd as the shell.

@lhecker , thanks for sharing the video and see the same behavior in the "Emoji-Window".  

Here's my setup:

- Fully updated VS 16.4.2

- Windows 10 19H1 (18363.535) 

Input method is the same as you sent in the picture:
image

I'm on a US keyboard.

**What I'm seeing:**
- Launch Release/x64 version of your branch.
- Set input method to Simplified Chinese.
- The first time I hit 'left shift + /' I get a ? 
- Second time I hit 'left shift + /' I get nothing new.  
- The third time I hit 'left shift + /', I finally get my second ?.

Here's what my prompt shows after each press of 'left shift + /'
1. ?
2. ?
3. ? ?
4. ? ?
5. ? ? ?

If I do the same thing with the same input method in Notpad, I have 5 questions marks after entering 'left shift + /' 5 times.

I double checked that the master branch behaves the same way as well 3 ? after 5 have been typed in.

Comment (zadjii-msft) [reply src/cascadia/TerminalControl/TSFInputControl.cpp]: yikes, I'm on `10.0.19541.1001` and I can't get that to repro with the same steps. I'd say we leave #3745 open temporarily, just until we can make sure it goes away. @lhecker, do we have an issue tracking the Chinese IME + Emoji Picker issue？ If not, let's file one for a follow-up

Comment (philnach) [reply src/cascadia/TerminalControl/TSFInputControl.cpp]: @zadjii-msft , thanks for double checking and odd that it doesn't repro.  I agree with leaving it temporarily open.

Comment (lhecker) [reply src/cascadia/TerminalControl/TSFInputControl.cpp]: @zadjii-msft --> https://github.com/microsoft/terminal/issues/4148
Please feel free to adjust the issue to your liking. 🙂

**Comment by DHowett-MSFT** [comment]
The winrt::param::hstring thing actually infuriates me a little bit. You cannot generally _write_ code that accepts anything automatically convertible to an hstring because `winrt::param` is a private namespace. So, if you add an hstring parameter to a function, you must always pass an hstring to it. :smile:
