### PR TITLE
Remove TranslateUnicodeToOem and all related code

### LINKED ISSUE #4551: COOKED_READ doesn't return UTF-8 on *A APIs in CP_UTF8
# Environment
```
Microsoft Windows [Version 10.0.18363.592]
```

# Impact
This issue is affecting reading console input via the Universal C Runtime as well - `_read`, `getchar`, `fread`, `scanf`, etc. Using `_cgets_s` only works around this issue because it uses `ReadConsoleW` instead of `ReadFile`. This is also reported against the UCRT on Developer Community here: [_read() cannot read UTF-8 but _cgets_s() can](https://developercommunity.visualstudio.com/content/problem/910961/-read-cannot-read-utf-8-but-cgets-s-can.html).

# Steps to reproduce
When using `ReadFile` to read from a console handle, UTF-8 input is not correctly returned. Using `ReadFile` on other types of handles (files, pipes) can read UTF-8 without issue. `SetConsoleCP` and `SetConsoleOutputCP` do not appear to affect this behavior.

``` 
C:\Users\stwish\source\read_utf8>type win32_test.cpp
#include <Windows.h>
#include <stdio.h>

int main()
{
    SetConsoleCP(65001);
    SetConsoleOutputCP(65001);
    const HANDLE console_stdin = GetStdHandle(STD_INPUT_HANDLE);

    const size_t buf_count = 20;
    char buffer[buf_count]{};

    DWORD num_read;

    BOOL result = ReadFile(
        console_stdin,
        buffer,
        buf_count,
        &num_read,
        nullptr
        );

    printf("ReadFile returned '%d'\n", result);
    for (int i = 0; i < 20; i++)
    {
        printf("%02x ", (unsigned char)buffer[i]);
    }

    return 0;
}
```

```
C:\Users\stwish\source\read_utf8>cl /nologo /EHsc /MT win32_test.cpp /Zi
win32_test.cpp
```
```
C:\Users\stwish\source\read_utf8>win32_test.exe
我是中文字符
ReadFile returned '1'
00 00 00 00 00 00 0d 0a 00 00 00 00 00 00 00 00 00 00 00 00
```
```
C:\Users\stwish\source\read_utf8>echo 我是中文字符 | win32_test.exe
ReadFile returned '1'
e6 88 91 e6 98 af e4 b8 ad e6 96 87 e5 ad 97 e7 ac a6 20 0d
```
```
C:\Users\stwish\source\read_utf8>type input.txt
我是中文字符

C:\Users\stwish\source\read_utf8>type input.txt | win32_test.exe
ReadFile returned '1'
e6 88 91 e6 98 af e4 b8 ad e6 96 87 e5 ad 97 e7 ac a6 00 00
```

# Expected behavior
Running `win32_test.exe` and entering '我是中文字符' input on the console should return `e6 88 91 e6 98 af e4 b8 ad e6 96 87 e5 ad 97 e7 ac a6 0d 0a` as this is the UTF-8 representation of that string, plus CR LF.

# Actual behavior
Running `win32_test.exe` and entering '我是中文字符' input on the console will return 6 null characters and CR LF, but still returns that the read operation was successful.

### LINKED ISSUE #7589: Some multibyte chars, e.g. 'α', cannot be read by ReadFile() under codepage 932 (Japanese).
# Environment
```none
Windows build number: Microsoft Windows [Version 10.0.18363.1082]
Windows Terminal version (if applicable): 1.2.2381.0
```

# Steps to reproduce

1) Compile the code below.
```
/* test-prog.c */
#include <windows.h>
#include <stdio.h>

int main()
{
        unsigned char buf[256];
        DWORD len;
        int i;
        ReadFile(GetStdHandle(STD_INPUT_HANDLE), buf, sizeof(buf), &len, NULL);
        for (i=0; i<len; i++) printf("%02x ", buf[i]);
        printf("\n");
        return 0;
}
```
2) Open Windows Terminal with cmd.exe or powershell.exe.
3) Run chcp 932.
4) Run the test-prog above.
5) Enter 'α' + [enter key].

# Expected behavior

If the test-prog above is executed in command prompt, the multibyte char 'α' can be read correctly as follows.
```
C:\Test>test-prog
α
83 bf 0d 0a
```
# Actual behavior

If the test-prog above is executed in Windows Terminal, the multibyte char 'α' cannot be read correctly as follows.
```
C:\Test>test-prog
α
00 0d 0a
```
This also happens with getchar(), getwchar(), gets(), ReadConsoleA(), etc.
As far as I tested, only ReadConsoleW() can read 'α' correctly.

Most of Japanese multibyte chars can be read correctly with the code above as follows
```
C:\Test>test-prog
あ
82 a0 0d 0a
```
even in Windows Terminal.

# Supplement
Similar happens under CP936 (Simplified Chinese) and CP949 (Korean).

### LINKED ISSUE #8663: OpenConsole crash when pasting emoji
# Environment

```none
Windows build number:  10.0.19041.630]
Windows Terminal version (if applicable):

Any other software?
tcsh (native Windows version)

# Steps to reproduce

download tcsh-x64.exe from https://github.com/amoldeshpande/tcsh/releases/tag/20210103.10 

Launch tcsh.  Doesn't have to be in terminal.  Paste any emoji into it.  It will crash conhost.exe on Windows 10 2004 and OpenConsole.exe if you launch within Windows Terminal

# Expected behavior

Should paste an emoji

# Actual behavior


Edited: repro steps with tcsh. Cannnot repro it with my test program anymore

### PR DESCRIPTION
**Pull request by lhecker**
The overarching intention of this PR is to improve our Unicode support. Most
of our APIs still don't support anything beyond UCS-2 and DBCS sequences.
This commit doesn't fix the UTF-16 support (by supporting surrogate pairs),
but it does improve support for UTF-8 by allowing longer `char` sequences.

It does so by removing `TranslateUnicodeToOem` which seems to have had an almost
viral effect on code quality wherever it was used. It made the assumption that
_all_ narrow glyphs encode to 1 `char` and most wide glyphs to 2 `char`s.
It also didn't bother to check whether `WideCharToMultiByte` failed or returned
a different amount of `char`s. So up until now it was easily possible to read
uninitialized stack memory from conhost. Any code that used this function was
forced to do the same "measurement" of narrow/wide glyphs, because _of course_
it didn't had any way to indicate to the caller how much memory it needs to
store the result. Instead all callers were forced to sorta replicate how it
worked to calculate the required storage ahead of time.
Unsurprisingly, none of the callers used the same algorithm...

Without it the code is much leaner and easier to understand now. The best
example is `COOKED_READ_DATA::_handlePostCharInputLoop` which used to contain 3
blocks of _almost_ identical code, but with ever so subtle differences. After
reading the old code for hours I still don't know if they were relevant or not.
It used to be 200 lines of code lacking any documentation and it's now 50 lines
with descriptive function names. I hope this doesn't break anything, but to
be honest I can't imagine anyone having relied on this mess in the first place.

I needed some helpers to handle byte slices (`std::span<char>`), which is why
a new `til/bytes.h` header was added. Initially I wrote a `buf_writer` class
but felt like such a wrapper around a slice/span was annoying to use.
As such I've opted for freestanding functions which take slices as mutable
references and "advance" them (offset the start) whenever they're read from
or written to. I'm not particularly happy with the design but they do the job.

Related to #8000
Fixes #4551
Fixes #7589
Fixes #8663

## Validation Steps Performed
* Unit and feature tests ✅
* Far Manager ✅
* Fixes test cases in #4551, #7589 and #8663 ✅

### CODE REVIEW

File: src/host/misc.h [hunk 1]
```diff
@@ -44,6 +44,38 @@ int ConvertToOem(const UINT uiCodePage,
...
+void InputEventsToString(std::deque<std::unique_ptr<IInputEvent>>& events, std::basic_string<CharT, Traits>& str)
+{
+    for (const auto& event : events)
+    {
+        if (event->EventType() == InputEventType::KeyEvent)
+        {
+            const auto keyEvent = static_cast<const KeyEvent*>(event.get());
+            // This keydown check prevents us from serializing ABC keypresses
+            // into AABBCC because each key-down is followed by a key-up.
+            if (keyEvent->IsKeyDown())
```
Comment (DHowett) [inline src/host/misc.h:70]: Did you move this from some other place? We've had some trouble with only checking `IsKeyDown` in the past

Comment (DHowett) [reply src/host/misc.h:70]: (So if it's net new code, 50% chance it's wrong; if it is old code, 95% chance it's wrong ;))

File: src/host/misc.h [hunk 2]
```diff
@@ -44,6 +44,38 @@ int ConvertToOem(const UINT uiCodePage,
...
+        auto event = std::make_unique<KeyEvent>();
+        event->SetKeyDown(true);
+        event->SetRepeatCount(1);
+        event->SetCharData(ch);
+        events.push_back(std::move(event));
+    }
+}
+
+template<typename CharT, typename Traits>
+void InputEventsToString(std::deque<std::unique_ptr<IInputEvent>>& events, std::basic_string<CharT, Traits>& str)
```
Comment (DHowett) [inline src/host/misc.h:61]: Is there any reason for us to need to know how many input events have been consumed?

File: src/host/misc.h [hunk 3]
```diff
@@ -44,6 +44,38 @@ int ConvertToOem(const UINT uiCodePage,
                  _Out_writes_(cchTarget) CHAR* const pchTarget,
                  const UINT cchTarget) noexcept;
 
+template<typename CharT, typename Traits>
+void StringToInputEvents(std::basic_string_view<CharT, Traits> str, std::deque<std::unique_ptr<IInputEvent>>& events)
```
Comment (DHowett) [inline src/host/misc.h:48]: We should make sure that this is named more clearly. It doesn't create fully formed input events that are safe for everyone to consume - it only creates keydown events.

File: src/inc/til/at.h [hunk 4]
```diff
@@ -37,16 +18,14 @@ namespace til
     template<typename T, typename I>
     constexpr auto at(T&& cont, const I i) noexcept -> decltype(auto)
     {
-#ifdef GSL_SPAN_H
-        if constexpr (details::is_span<T>::value)
+        if constexpr (ContiguousView<T>)
```
Comment (DHowett) [inline src/inc/til/at.h:21]: love it

File: src/server/ApiDispatchers.cpp [hunk 5]
```diff
@@ -270,13 +270,8 @@
...
     ULONG cbBufferSize;
-    // TODO: This is dumb. We should find out how much we need, not guess.
-    // If the request is not in Unicode mode, we must allocate an output buffer that is twice as big as the actual caller buffer.
-    RETURN_IF_FAILED(m->GetAugmentedOutputBuffer((a->Unicode != FALSE) ? 1 : 2,
-                                                 &pvBuffer,
-                                                 &cbBufferSize));
+    RETURN_IF_FAILED(m->GetOutputBuffer(&pvBuffer, &cbBufferSize));
 
-    // TODO: This is also rather strange and will also probably make more sense if we stop guessing that we need 2x buffer to convert.
     // This might need to go on the other side of the fence (inside host) because the server doesn't know what we're going to do with initial num bytes.
```
Comment (DHowett) [inline src/server/ApiDispatchers.cpp:275]: Do we still need to figure out whether this "might"?

File: src/host/stream.h [hunk 6]
```diff
@@ -29,6 +29,12 @@ Revision History:
                                _Out_opt_ bool* const pPopupKeys,
                                _Out_opt_ DWORD* const pdwKeyState) noexcept;
 
+[[nodiscard]] NTSTATUS _ReadCharacterInput(InputBuffer& inputBuffer,
```
Comment (DHowett) [inline src/host/stream.h:32]: nit: if this is going in the "public API" component of `stream.h`, it should not begin with a `_`

**Review by DHowett — COMMENTED** [review]
9/16 i've skipped the hard stuff for now

**Comment by DHowett** [comment]
Also related to #4551?

File: src/inc/til/type_traits.h [hunk 7]
```diff
@@ -0,0 +1,55 @@
...
+{
+    namespace details
+    {
+        template<typename T>
+        struct is_contiguous_view : std::false_type
+        {
+        };
+        // std::span remains largely unused in this code base so far.
+        //template<typename U, std::size_t E>
+        //struct is_contiguous_view<std::span<U, E>> : std::true_type
```
[the remark this answers is not in the document]
Comment (lhecker) [reply src/inc/til/type_traits.h:16]: We don't import the `<span>` anywhere yet, so the type usually isn't defined. I'm planning to simply replace all `gsl::span` usage with `std::span` in the future. Matter of fact, I might just be doing it right now.

File: src/host/misc.h (hunk 1 above)
Comment (lhecker) [reply src/host/misc.h:70]: It's likely 95% wrong then. 🥲

File: src/host/misc.h (hunk 2 above)
Comment (lhecker) [reply src/host/misc.h:61]: Oh you mean because it's a mutable reference? That's an oversight - It can be made `const`.

File: src/server/ApiDispatchers.cpp (hunk 5 above)
Comment (lhecker) [reply src/server/ApiDispatchers.cpp:275]: To be entirely honest I don't quite get what this comment means and what `InitialNumBytes` is supposed to do. I can try to figure it out, but it can probably also be left as is for the time being.

File: src/host/misc.h (hunk 2 above)
Comment (DHowett) [reply src/host/misc.h:61]: What i mean is... won't the consumer want to know how many events were used? That's the only way they can adequately track what is remaining...

**Comment by lhecker** [comment]
Also fixes #7589.

File: src/inc/til/type_traits.h (hunk 7 above)
[the remark this answers is not in the document]
Comment (carlos-zamora) [reply src/inc/til/type_traits.h:16]: #14763 just merged so you're good to go now haha

**Comment by lhecker** [comment]
Now after rewriting half of `InputBuffer::Read` I think that this is pretty solid. I've chosen not to implement support for surrogate pairs, because it was quite frankly a major pain in the ass to stitch `KeyEvent`s back together. Instead, it'd be much better to simply add support for surrogate pairs to `KeyEvent` itself (i.e. have it store up to 2 `wchar_t`), so that we don't have to do any stitching in the first place. Or if that's not possible, I'll add support for the stitching some time in the future. For this particular case it was just too much.

File: src/host/misc.h (hunk 2 above)
Comment (lhecker) [reply src/host/misc.h]: I've removed the two functions now.

File: src/host/inputBuffer.cpp [hunk 8]
```diff
@@ -36,59 +37,199 @@ InputBuffer::InputBuffer() :
...
+            const auto length = WideCharToMultiByte(cp, 0, source.data(), wideLength, target.data(), narrowLength, nullptr, nullptr);
+            if (length > 0)
+            {
+                source = {};
+                til::bytes_advance(target, gsl::narrow_cast<size_t>(length));
+                return;
+            }
+
+            const auto error = GetLastError();
+            THROW_HR_IF(HRESULT_FROM_WIN32(error), error != ERROR_INSUFFICIENT_BUFFER);
```
Comment (zadjii-msft) [inline src/host/inputBuffer.cpp:88]: throwing seems... aggressive, but I reckon that this already threw didn't it...

Comment (zadjii-msft) [reply src/host/inputBuffer.cpp:88]: Oh wait only throw if it's not a `ERROR_INSUFFICIENT_BUFFER`? Okay yea that _would_ be unexpected

**Review by zadjii-msft — APPROVED** [review]
I follow this which is much more than I can say about how the code was before.

File: src/host/readDataDirect.cpp [hunk 9]
```diff
@@ -88,105 +78,59 @@ bool DirectReadData::Notify(const WaitTerminationReason TerminationReason,
...
+    // move events to pOutputData
+    const auto pOutputDeque = static_cast<std::deque<std::unique_ptr<IInputEvent>>* const>(pOutputData);
+    *pNumBytes = _outEvents.size() * sizeof(INPUT_RECORD);
+    *pOutputDeque = std::move(_outEvents);
+
+    return true;
+}
+catch (...)
+{
+    // There doesn't seem to be a way to just get the NT exception code with WIL.
```
Comment (DHowett) [inline src/host/readDataDirect.cpp:131]: you might benefit from `NT_CATCH_RETURN()`! It's in `wil/nt_result_macros.h`

File: src/host/readDataRaw.cpp [hunk 10]
```diff
@@ -82,146 +81,50 @@ bool RAW_READ_DATA::Notify(const WaitTerminationReason TerminationReason,
...
-
-        memmove(lpBuffer, tempBuffer.get(), *pNumBytes);
-        if (fAddDbcsLead)
-        {
-            (*pNumBytes)++;
-        }
-    }
-    return RetVal;
+    std::span buffer{ reinterpret_cast<char*>(_BufPtr), _BufferSize };
+    *pReplyStatus = ReadCharacterInput(*_pInputBuffer, buffer, *pNumBytes, *_pInputReadHandleData, fIsUnicode);
```
Comment (DHowett) [inline src/host/readDataRaw.cpp:119]: I sure do love how much simpler this is lol

File: src/host/stream.cpp [hunk 11]
```diff
@@ -285,151 +284,38 @@ til::CoordType RetrieveNumberOfSpaces(_In_ til::CoordType sOriginalCursorPositio
...
-            NumToWrite++;
-        }
+        readHandleState.UpdatePending(pending);
     }
 
-    bytesRead = NumToWrite;
+    bytesRead = buffer.size() - writer.size();
     return STATUS_SUCCESS;
 }
+NT_CATCH_RETURN()
```
Comment (DHowett) [inline src/host/stream.cpp:318]: wait, now i'm confused. did i misread the earlier one

File: src/host/stream.cpp [hunk 12]
```diff
@@ -521,140 +407,51 @@ til::CoordType RetrieveNumberOfSpaces(_In_ til::CoordType sOriginalCursorPositio
 // populated.
 // - STATUS_SUCCESS on success
 // - Other NTSTATUS codes as necessary
-[[nodiscard]] static NTSTATUS _ReadCharacterInput(InputBuffer& inputBuffer,
-                                                  std::span<char> buffer,
-                                                  size_t& bytesRead,
-                                                  INPUT_READ_HANDLE_DATA& readHandleState,
-                                                  const bool unicode,
-                                                  std::unique_ptr<IWaitRoutine>& waiter)
+[[nodiscard]] NTSTATUS ReadCharacterInput(InputBuffer& inputBuffer,
```
Comment (DHowett) [inline src/host/stream.cpp:410]: should this be a member on InputBuffer, or stay relegated to stream.cpp?

File: src/host/stream.cpp [hunk 13]
```diff
@@ -521,140 +407,51 @@ til::CoordType RetrieveNumberOfSpaces(_In_ til::CoordType sOriginalCursorPositio
...
+                                          INPUT_READ_HANDLE_DATA& readHandleState,
+                                          const bool unicode)
+try
 {
-    size_t NumToWrite = 0;
-    auto addDbcsLead = false;
-    auto Status = STATUS_SUCCESS;
-    auto pBuffer = reinterpret_cast<wchar_t*>(buffer.data());
-    auto bufferRemaining = buffer.size_bytes();
+    UNREFERENCED_PARAMETER(readHandleState);
```
Comment (DHowett) [inline src/host/stream.cpp:417]: why keep it? we got rid of some params.

File: src/host/ut_host/Host.UnitTests.vcxproj [hunk 14]
```diff
@@ -35,7 +35,6 @@
     <ClCompile Include="UtilsTests.cpp" />
     <ClCompile Include="Utf8ToWideCharParserTests.cpp" />
     <ClCompile Include="InputBufferTests.cpp" />
-    <ClCompile Include="ReadWaitTests.cpp" />
```
Comment (DHowett) [inline src/host/ut_host/Host.UnitTests.vcxproj:38]: remove from sources

File: src/host/ut_host/ReadWaitTests.cpp [hunk 15]
```diff
@@ -1,129 +0,0 @@
-// Copyright (c) Microsoft Corporation.
```
Comment (DHowett) [inline src/host/ut_host/ReadWaitTests.cpp:1]: What happened? Why can we get rid of this?

File: src/inc/til/type_traits.h (hunk 7 above)
[the remark this answers is not in the document]
Comment (DHowett) [reply src/inc/til/type_traits.h:16]: agree!

File: src/host/inputBuffer.cpp [hunk 16]
```diff
@@ -36,59 +37,199 @@ InputBuffer::InputBuffer() :
...
+
+        // Slow path: Character-wise conversion otherwise. We do this in order to only
+        // consume as many characters from `source` as necessary to fill `target`.
+        {
+            size_t read = 0;
+
+            for (const auto& wch : source)
+            {
+                char buffer[8];
+                const auto length = WideCharToMultiByte(cp, 0, &wch, 1, &buffer[0], sizeof(buffer), nullptr, nullptr);
```
Comment (DHowett) [inline src/host/inputBuffer.cpp:99]: this will break on surrogate pairs, won't it?

should we be using utf16parser's iterator here?

File: src/host/inputBuffer.cpp [hunk 17]
```diff
@@ -261,47 +402,105 @@ void InputBuffer::PassThroughWin32MouseRequest(bool enable)
...
+            {
+                do
+                {
+                    OutEvents.push_back(std::make_unique<KeyEvent>(*keyEvent));
+                    repeat--;
+                } while (repeat > 0 && OutEvents.size() < AmountToRead);
+            }
+            else
+            {
+                const auto wch = keyEvent->GetCharData();
```
Comment (DHowett) [inline src/host/inputBuffer.cpp:449]: same Q about surrogate pairs, but they're split up over multiple input records

File: src/host/inputBuffer.cpp [hunk 18]
```diff
@@ -261,47 +402,105 @@ void InputBuffer::PassThroughWin32MouseRequest(bool enable)
...
+        ++it;
     }
-    catch (...)
+
+    if (!Peek)
+    {
+        _storage.erase(_storage.begin(), it);
+    }
+
+    Cache(Unicode, OutEvents, AmountToRead);
```
Comment (DHowett) [inline src/host/inputBuffer.cpp:489]: if cache is only ever used internally, move it into private?

File: src/host/inputBuffer.cpp [hunk 19]
```diff
@@ -261,47 +402,105 @@ void InputBuffer::PassThroughWin32MouseRequest(bool enable)
...
+
+    if (OutEvents.empty())
+    {
+        return WaitForData ? CONSOLE_STATUS_WAIT : STATUS_SUCCESS;
+    }
+    if (_storage.empty())
```
Comment (DHowett) [inline src/host/inputBuffer.cpp:495]: are we sure we want to reset the event when we are mptied out?

are we totally certain that the original boolean wasn't _useful_?

**Review by DHowett — CHANGES_REQUESTED** [review]
open questions - i'm ready to sign off though w/ answers

File: src/host/readDataCooked.cpp [hunk 20]
```diff
@@ -1003,211 +1003,55 @@ void COOKED_READ_DATA::SavePendingInput(const size_t index, const bool multiline
...
+    GetInputBuffer()->Consume(isUnicode, input, writer);
 
-        const auto pInputReadHandleData = GetInputReadHandleData();
-        const std::wstring_view pending{ _backupLimit + (numBytes / sizeof(wchar_t)), (_bytesRead - numBytes) / sizeof(wchar_t) };
+    if (!input.empty())
+    {
         if (LineCount > 1)
         {
-            pInputReadHandleData->SaveMultilinePendingInput(pending);
+            GetInputReadHandleData()->SaveMultilinePendingInput(input);
```
[the remark this answers is not in the document]
Comment (lhecker) [reply src/host/readDataCooked.cpp:1037]: I'm not quite seeing what you mean, when looking at the current code: https://github.com/microsoft/terminal/blob/814e44bf45762ee878b41553c7048c6ffbf1e63e/src/host/readDataCooked.cpp#L1116-L1123

If you remove all the unrelated code and simplify it a bit you arrive at:
```cpp
DWORD LineCount = 1;

if (_echoInput)
{
    ProcessAliases(LineCount);
}

// `_bytesRead > _userBufferSize` is true when there's more data than the user requested.
if (_bytesRead > _userBufferSize || LineCount > 1)
{
    if (LineCount > 1)
    {
        pInputReadHandleData->SaveMultilinePendingInput(pending);
    }
    else
    {
        pInputReadHandleData->SavePendingInput(pending);
    }
}
else
{
}
```

File: src/host/ut_host/ReadWaitTests.cpp (hunk 15 above)
Comment (lhecker) [reply src/host/ut_host/ReadWaitTests.cpp:1]: Despite the name of the file, it only tested `SplitToOem`, which doesn't exist anymore. We could replace it with unit tests for the new `InputBuffer` code I added, but given that this is already covered by our DBCS feature tests and that further large changes to our input stack are required to allow for full Unicode support in both Windows Terminal and conhost (which will break such unit tests), I don't think that's worth the effort.

File: src/host/readDataDirect.cpp (hunk 9 above)
Comment (lhecker) [reply src/host/readDataDirect.cpp:131]: That doesn't quite work, since it uses an out parameter. But I just found `wil::StatusFromCaughtException()`!

File: src/host/stream.cpp (hunk 12 above)
Comment (lhecker) [reply src/host/stream.cpp:410]: I'd like this to stay here to minimize the changes a little bit. There are many further changes required anyways to fix our text handling.

File: src/host/stream.cpp (hunk 13 above)
Comment (lhecker) [reply src/host/stream.cpp:417]: I was thinking it might be helpful for when we move the the partially read events from the global `InputBuffer` over to the per-connection `INPUT_READ_HANDLE_DATA`.

File: src/host/ut_host/Host.UnitTests.vcxproj (hunk 14 above)
Comment (lhecker) [reply src/host/ut_host/Host.UnitTests.vcxproj:38]: Seems like it never was part of any sources file?

File: src/host/inputBuffer.cpp (hunk 16 above)
Comment (lhecker) [reply src/host/inputBuffer.cpp:99]: I wasn't confident in making such a change just yet. Thinking about it for a while, I realized that both clients and our internal code base expect to read text if just a single character of input is available. For instance if just 1 leading surrogate half is available and I don't send at least 1 character as output, will clients deadlock, because we thought we sent data, but the client never received any? Will anything get out of sync on our end?
So I personally decided to defer making such a change until I either fixed the system or got a better grasp of what can happen when.

File: src/host/inputBuffer.cpp (hunk 18 above)
Comment (lhecker) [reply src/host/inputBuffer.cpp:489]: Originally I needed to call these functions externally as well and it's entirely possible I need to do it again in the future. I don't think them being public is hurting the code.

File: src/host/inputBuffer.cpp (hunk 19 above)
Comment (lhecker) [reply src/host/inputBuffer.cpp:495]: It comforts me that you got confused by this code as well. Holy moly.
`resetWaitEvent` used to be an out parameter of the `_ReadBuffer` function, which had only 1 caller: this function (`Read`). `resetWaitEvent` was set like this by `_ReadBuffer`:
```cpp
resetWaitEvent = true;

// ...

// signal if we emptied the buffer
if (_storage.empty())
{
    resetWaitEvent = true;
}
```

`Read` in turn did this:
```cpp
if (resetWaitEvent)
{
    ServiceLocator::LocateGlobals().hInputEvent.ResetEvent();
}
```

By merging `_ReadBuffer` into `Read` the `resetWaitEvent` is gone and got replaced with `_storage.empty()`.

File: src/host/inputBuffer.cpp (hunk 17 above)
Comment (lhecker) [reply src/host/inputBuffer.cpp:449]: (Same as above.)

File: src/inc/til/type_traits.h [hunk 21]
```diff
@@ -11,21 +11,14 @@ namespace til
...
-        //struct is_contiguous_view<std::span<U, E>> : std::true_type
-        //{
-        //};
-        template<typename U, typename V>
-        struct is_contiguous_view<std::basic_string_view<U, V>> : std::true_type
-        {
-        };
-#ifdef GSL_SPAN_H
         template<typename U, std::size_t E>
         struct is_contiguous_view<std::span<U, E>> : std::true_type
```
Comment (DHowett) [inline src/inc/til/type_traits.h:15]: rofl, oops

Comment (lhecker) [reply src/inc/til/type_traits.h:15]: Ah woops. 😅 Well, problem fixed!

**Review by DHowett — APPROVED** [review]

**Comment by alexrp** [comment]
Just wanted to check: With this PR merged, is the `ReadFile` w/ UTF-8 code page situation supposed to be improved?

**Comment by lhecker** [comment]
Yes, the test case as described in #4551 is now fixed. However, I believe that "improved" is just the right choice of words: There's still no consistent internal support for surrogate pairs for instance, but this is something that I'm actively working on.

**Comment by methane** [comment]
Has this fix shipped in Windows 11 conhost already?

**Comment by lhecker** [comment]
[This will not ship for quite a while unfortunately.](https://winaero.com/microsoft-cancels-windows-11-23h2-switches-to-three-year-release-cycle-for-major-versions/) 10000s of lines of other changes are also waiting to be shipped, including massive correctness and performance improvements, and I'm quite excited to see when it does.

**Comment by zadjii-msft** [comment]
(It will ship in the _Terminal_ in 1.18 Soon<sup>TM</sup> though)

**Comment by methane** [comment]
Thank you!

**Comment by SainoNamkho** [comment]
Is this related to #12626?
