### PR TITLE
Fix all fragments not loading when one is badly formed

### LINKED ISSUE #10590: [BLOCKING] 1.10 breaks fragment extensions
### Windows Terminal version (or Windows build number)

1.10.18x

### Other Software

Julia, Ubuntu Community Preview

### Steps to reproduce

Install any fragment extension-bearing application.

### Expected Behavior

_No response_

### Actual Behavior

The fragments are not loaded.

### PR DESCRIPTION
**Pull request by PankajBhojwani**
Adds try-catch blocks to the parts where we layer a fragment onto a profile and create a new profile from a fragment. This allows us to continue looping over the remaining fragments after failing to use a badly-formed one, instead of aborting prematurely.

## PR Checklist
* [x] Closes #10590 

## Validation Steps Performed
Non-badly formed fragments get loaded even if there is a badly formed one somewhere

### CODE REVIEW

File: src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp [hunk 1]
```diff
@@ -530,14 +530,20 @@ void CascadiaSettings::_ParseAndLayerFragmentFiles(const std::unordered_set<std:
...
+                            auto childImpl{ matchingProfile->CreateChild() };
+                            childImpl->LayerJson(profileStub);
+                            childImpl->Origin(OriginTag::Fragment);
+
+                            // replace parent in _profiles with child
+                            _allProfiles.SetAt(_FindMatchingProfileIndex(matchingProfile->ToJson()).value(), *childImpl);
+                        }
+                        catch (...)
+                        {
+                        }
```
Comment (PankajBhojwani) [inline src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp:546]: Note, we are deliberately choosing _not_ to append a warning here because this is an issue with the fragment, which is unlikely to be the fault of the user

**Review by DHowett — APPROVED** [review]
suspect you could put this around the body of the `for` loop, but this works just as well.

**Review by miniksa — COMMENTED** [review]
Yeah I'm good with this.

**Review by miniksa — APPROVED** [review]

**Review by carlos-zamora — APPROVED** [review]

**Comment by DHowett** [comment]
@msftbot merge this in 1 minutes
