### PR TITLE
Reimplement the VT tab stop functionality

### LINKED ISSUE #4669: Issue with line-wrapped tabstops after resizing the window
# Environment

```none
Windows build number: 10.0.18362.0
Windows Terminal version (if applicable): 0.9.433.0
```

# Steps to reproduce

1. From WSL, echo a line of text containing a literal tab character, long enough to cause the tab character to render AFTER Terminal line-wraps the line (e.g. on a second line).
2. Resize Terminal, increasing its width enough so that the whole line of text now fits on a single line
3. Print the same line of text again.

# Expected behavior

The second printing of the text is printed in a single line, with the tab producing the expected amount of horizontal whitespace.

# Actual behavior

The line of text is corrupted, with the tab consuming too much horizontal whitespace (= the full remaining width of the window - 1), causing the line to sill be wrapped across multiple lines as well.

I would assume this is related to the various problems listed in #4200, but I don't see this specifically mentioned (though some of the issues listed there are beyond my ability to grok).

Fully fleshed-out example:

Assuming an initial window width of approximately 80 characters, here's an example command that will print a suitable line:

```bash
echo -e "123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 Hardtab:\t123456789 123456789 123456789 123456789"
```

On a smallish window, that renders something like this:

image

If you then resize the window wide enough that the output line is reflowed onto a single line...

image

... and then re-run the echo you get something clearly quite wrong:

image

### PR DESCRIPTION
**Pull request by j4james**
## Summary of the Pull Request

This is essentially a rewrite of the VT tab stop functionality, implemented entirely within the `AdaptDispatch` class. This significantly simplifies the `ConGetSet` interface, and should hopefully make it easier to share the functionality with the Windows Terminal VT implementation in the future.

By removing the dependence on the `SCREEN_INFORMATION` class, it fixes the problem of the the tab state not being preserved when switching between the main and alternate buffers. And the new architecture also fixes problems with the tabs not being correctly initialized when the screen is resized.

## References

This fixes one aspect of issue #3545.
It also supersedes the fix for #411 (PR #2816).
I'm hoping the simplification of `ConGetSet` will help with #3849.

## PR Checklist
* [x] Closes #4669
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [x] Tests added/passed
* [ ] Requires documentation to be updated
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Detailed Description of the Pull Request / Additional comments

In the new tab architecture, there is now a `vector<bool>` (__tabStopColumns_), which tracks whether any particular column is a tab stop or not. There is also a __initDefaultTabStops_ flag indicating whether the default tab stop positions need to be initialised when the screen is resized.

The way this works, the vector is initially empty, and only initialized (to the current width of the screen) when it needs to be used. When the vector grows in size, the __initDefaultTabStops_ flag determines whether the new columns are set to false, or if every 8th column is set to true.

By default we want the latter behaviour - newly revealed columns should have default tab stops assigned to them - so __initDefaultTabStops_ is set to true. However, after a `TBC 3` operation (i.e. we've cleared all tab stops), there should be no tab stops in any newly revealed columns, so __initDefaultTabStops_ is set to false.

Note that the __tabStopColumns_ vector is never made smaller when the window is shrunk, and that way it can preserve the state of tab stops that are off screen, but which may come into range if the window is made bigger again.

However, we can can still reset the vector completely after an `RIS` or `TBC 3` operation, since the state can then be reconstructed automatically based on just the __initDefaultTabStops_ flag.

## Validation Steps Performed

The original screen buffer tests had to be rewritten to set and query the tab stop state using escape sequences rather than interacting with the `SCREEN_INFORMATION` class directly, but otherwise the structure of most tests remained largely the same.

However, the alt buffer test was significantly rewritten, since the original behaviour was incorrect, and the initialization test was dropped completely, since it was no longer applicable. The adapter tests were also dropped, since they were testing the `ConGetSet` interface which has now been removed.

I also had to make an addition to the method setup of the screen buffer tests (making sure the viewport was appropriately initialized), since there were some tests (unrelated to tab stops) that were previously dependent on the state being set in the tab initialization test which has now been removed.

I've manually tested the issue described in #4669 and confirmed that the tabs now produce the correct spacing after a resize.

### CODE REVIEW

File: src/terminal/adapter/adaptDispatch.cpp [hunk 1]
```diff
@@ -1388,7 +1421,29 @@ bool AdaptDispatch::ForwardTab(const size_t numTabs)
...
+        const auto width = csbiex.dwSize.X;
+        const auto row = csbiex.dwCursorPosition.Y;
+        auto column = csbiex.dwCursorPosition.X;
+        auto tabsPerformed = 0u;
+
+        _InitTabStopsForWidth(width);
+        while (column > 0 && tabsPerformed < numTabs)
+        {
+            column--;
+            if (til::at(_tabStopColumns, column))
```
Comment (DHowett-MSFT) [inline src/terminal/adapter/adaptDispatch.cpp]: we ended up bringing in a `dynamic_bitset`, which looks like `std::vector<bool>` but is somewhat more ergonomic. Is there a clever trick we can use with `dynamic_bitset`'s `find_first()` and `find_next(size_t)` operations here? Perhaps not, because we're walking it in reverse...

Comment (DHowett-MSFT) [reply src/terminal/adapter/adaptDispatch.cpp]: perhaps for ForwardTab though

File: src/terminal/adapter/adaptDispatch.cpp [hunk 2]
```diff
@@ -1376,7 +1387,29 @@ bool AdaptDispatch::HorizontalTabSet()
...
+
+        _InitTabStopsForWidth(width);
+        while (column + 1 < width && tabsPerformed < numTabs)
+        {
+            column++;
+            if (til::at(_tabStopColumns, column))
+            {
+                tabsPerformed++;
+            }
+        }
```
Comment (DHowett-MSFT) [inline src/terminal/adapter/adaptDispatch.cpp]: just for my own edification: `SPC SPC TAB`

If the tabstops set are:

```
0       8      10
|       |       |
```

then

```
0       8      10
|       |       |
XX<TAB>
  ^ cursor
```

will result in

```
0       8      10
|       |       |
XX        |
          ^ cursor
```

right? Where we'll overshoot the tab by the number of columns we were off the previous tab?

File: src/terminal/adapter/adaptDispatch.cpp (hunk 1 above)
Comment (j4james) [reply src/terminal/adapter/adaptDispatch.cpp]: I've just had a go at using `dynamic_bitset`, and I don't think it's an improvement. The fact that the width boundary has to be special cased makes the code slightly messier, and it introduces the need for narrow cast which is annoying. Also the use of `find_next` triggers an "unreachable code" warning in the header that has to be disabled - I'm not sure why that is.

And after all that, the generated assembly actually looks way worse than the simple `vector` approach. It's possible someone else could make better use of the bitset functionality than I have, but my initial impression is that it doesn't help.

File: src/terminal/adapter/adaptDispatch.cpp (hunk 2 above)
Comment (j4james) [reply src/terminal/adapter/adaptDispatch.cpp]: No. The algorithm doesn't care where it started from. It just keeps incrementing the column number until it reaches a tab stop - the `til::at(_tabStopColumns, column)` test will tell us if any given column is a tab stop or not.

In case the `tabsPerformed++` is confusing the matter, you can think of that as just being a `break` when all you need is a single tab. But because we're potentially performing multiple tabs, we have to keep track of the count, and only break once we've repeated the operation _numTabs_ times.

File: src/terminal/adapter/adaptDispatch.cpp [hunk 3]
```diff
@@ -1405,15 +1460,60 @@ bool AdaptDispatch::TabClear(const size_t clearType)
...
         break;
     case DispatchTypes::TabClearType::ClearAllColumns:
-        success = _pConApi->PrivateTabClear(true);
+        success = _ClearAllTabStops();
         break;
     }
     return success;
 }
 
+bool AdaptDispatch::_ClearSingleTabStop()
```
Comment (zadjii-msft) [inline src/terminal/adapter/adaptDispatch.cpp]: nit: these guys should have doc comments

File: src/terminal/adapter/adaptDispatch.cpp [hunk 4]
```diff
@@ -1405,15 +1460,60 @@ bool AdaptDispatch::TabClear(const size_t clearType)
...
+
+void AdaptDispatch::_InitTabStopsForWidth(const size_t width)
+{
+    const auto initialWidth = _tabStopColumns.size();
+    if (width > initialWidth)
+    {
+        _tabStopColumns.resize(width);
+        for (auto column = 8u; column < _tabStopColumns.size(); column += 8)
+        {
+            if (_initDefaultTabStops && column >= initialWidth)
```
Comment (zadjii-msft) [inline src/terminal/adapter/adaptDispatch.cpp]: should we move the `if (_initDefaultTabStops` bit earlier, since that's not about to change during the course of this method?

File: src/terminal/adapter/adaptDispatch.cpp (hunk 2 above)
Comment (DHowett-MSFT) [reply src/terminal/adapter/adaptDispatch.cpp]: D’oh, of course we break out after we hit the number of tabs requested without further incrementing `column`. Thanks for the reality check :)

**Comment by j4james** [comment]
> So wait, just to be clear, the main and alt buffer are supposed to share one set of tab stops?

Yep. There's a test case in #3545 which demonstrates this issue and a screenshot of the XTerm behaviour. VTE and Mintty work the same way.

File: src/terminal/adapter/adaptDispatch.cpp (hunk 3 above)
Comment (j4james) [reply src/terminal/adapter/adaptDispatch.cpp]: Right. I'll do that.

File: src/terminal/adapter/adaptDispatch.cpp (hunk 4 above)
Comment (j4james) [reply src/terminal/adapter/adaptDispatch.cpp]: Yeah. I was trying to be clever and avoid an extra condition, thinking the compiler would be smart enough to move the check out of the loop. It seems it doesn't do that, though, and it's probably clearer having the condition up front anyway. Will fix this now.

File: src/terminal/adapter/adaptDispatch.cpp (hunk 3 above)
Comment (j4james) [reply src/terminal/adapter/adaptDispatch.cpp]: Done in commit a0a4780bf0adff3a7829cd2467ce37a9adfd7860.

File: src/terminal/adapter/adaptDispatch.cpp (hunk 4 above)
Comment (j4james) [reply src/terminal/adapter/adaptDispatch.cpp]: Done in commit a0a4780bf0adff3a7829cd2467ce37a9adfd7860.

**Comment by j4james** [comment]
Note that build failure is just a timeout in the unit tests. The second last commit was fine, and the one that followed was just a comment fix, so no reason it should make any difference.

**Comment by DHowett-MSFT** [comment]
Kicked the failed test.

**Comment by DHowett-MSFT** [comment]
The two Mikes, who would otherwise be reviewing and/or signing off, aren't available today -- this might take a little bit to get merged, but I'll tag it for Auto and Second.

**Comment by DHowett-MSFT** [comment]
@msftbot make sure @zadjii-msft signs off

**Comment by j4james** [comment]
> The two Mikes, who would otherwise be reviewing and/or signing off, aren't available today -- this might take a little bit to get merged, but I'll tag it for Auto and Second.

That's cool. I wasn't expecting you'd even look at it before the v1 release. I'm not in any rush to get anything merged.
