### PR TITLE
Fix and test TextBuffer::MoveToPreviousWord()

### LINKED ISSUE #7742: UIA: incorrect move to previous word
Since #7677 was merged:

In the NVDA Python console (NVDA+control+z):

### Word

```python console
>>> # In a Word document (accessed VIA UIA, positioned on the start of the text "My name is Carlos"):
>>> ti=nav.makeTextInfo("caret")
>>> ti.expand("word")
>>> ti.text
'My '
>>> ti.collapse() # Make a degenerate range (move end to start)
>>> ti.move("word", 1)
1
>>> ti.expand("word")
>>> ti.text
'name '
>>> ti.collapse()
>>> ti.move("word", -1)
-1
>>> ti.expand("character")
>>> ti.text
'M' # GOOD
```

### conhost

```python console
>>> # Now, in Conhost
>>> ti=nav.makeTextInfo("caret")
>>> ti.expand("word")
>>> ti.text
'C:\\Users\\codeofdusk>My '
>>> ti.collapse() # Make a degenerate range (move end to start)
>>> ti.move("word", 1)
1
>>> ti.expand("word")
>>> ti.text
'name '
>>> ti.collapse()
>>> ti.move("word", -1)
-1
>>> ti.expand("character")
>>> ti.text
' ' # BAD
```

Cc @carlos-zamora.

### PR DESCRIPTION
**Pull request by carlos-zamora**
This fixes a bug when moving backwards by word that resulted in #7742.

This also includes...
- a minor refactor that leverages `GetWordStart` in `MoveToPreviousWord`
- additional unit tests for movement by word
- a feature test comprised of the referenced bug report

`MoveToPreviousWord()` would...
- move backwards for each whitespace character
- then, move backwards for each regular character

This would actually result in moving to the beginning of the current "word" (as defined by a11y).

We actually need to do this process twice:
- the first time gets you to the beginning of the current word
- attempt to move back by one character
- the second time gets you to the beginning of the previous word

Rather than implementing 4 while loops, we leverage `GetWordStart()` to
attempt to move to the beginning of the previous word. We call it twice
(as described above). The logic is unchanged, but we instead reuse a
function that has already undergone more testing.

To make sure this works as expected, additional unit tests were
introduced covering "MoveByWord" in the TextBuffer.

## Validation Steps Performed
Added test for repro steps.
Added unit tests for movement by word.

Closes #7742

### CODE REVIEW

**Comment by DHowett** [comment]
Carlos, did this break further with #7677?

**Comment by DHowett** [comment]
Since this change has to make its way back into windows, I would prefer if you do not make unrelated performance changes at the same time **unless** they double or triple the performance during a11y. If it's so bad that it's noticeable, let's chat.

**Comment by DHowett** [comment]
This would also benefit from an explanation as to what the bug ius.

**Comment by codeofdusk** [comment]
> If it's so bad that it's noticeable, let's chat.

There *are* performance issues with word nav, see #5243 (which might be fixed by this PR as the NVDA review cursor does expand by word).

**Comment by codeofdusk** [comment]
> Carlos, did this break further with #7677?

Not Carlos, but #7677 did introduce this bug.

**Comment by carlos-zamora** [comment]
> Carlos, did this break further with #7677?

No it did not. #7677 had to do with working with a degenerate range at `EndExclusive`. This one has to do with moving by word.

> Since this change has to make its way back into windows, I would prefer if you do not make unrelated performance changes at the same time **unless** they double or triple the performance during a11y. If it's so bad that it's noticeable, let's chat.

I feel that. I could leave `MoveToNextWord()` untouched since the bug only had an issue with `MoveToPreviousWord()`? I think the test I wrote failed in that state though (I'll double check if you want).

I did add extra tests to try and alleviate that concern though. And the code looks much cleaner this way. My earlier version of `MoveToPreviousWord()` required 4 while loops
- move back through all whitespace of current word
- move back through all text of current word
- move back through all whitespace of previous word
- move back through all text of previous word

**Review by DHowett — CHANGES_REQUESTED** [review]
NAK for restructuring.

Since the last edits here introduced a regression and we're close to a Windows bug bar date, I'd like to get this in two separate PRs (bug fix, performance).

**Comment by carlos-zamora** [comment]
> > Carlos, did this break further with #7677?
> 
> Not Carlos, but I'm pretty sure that #7677 did introduce this bug.

Slapped the feature test on 9539ec3 (just before #7677). It failed then too.

**Review by codeofdusk — APPROVED** [review]
This PR does seem to fix #7742 with minor performance improvement to word nav (although could just be placebo)! There are still some noticeable performance issues though at the end of the output. I'll leave code comments to others.

File: src/buffer/out/textBuffer.hpp [hunk 1]
```diff
@@ -131,7 +131,7 @@ class TextBuffer final
 
     const COORD GetWordStart(const COORD target, const std::wstring_view wordDelimiters, bool accessibilityMode = false) const;
     const COORD GetWordEnd(const COORD target, const std::wstring_view wordDelimiters, bool accessibilityMode = false) const;
-    bool MoveToNextWord(COORD& pos, const std::wstring_view wordDelimiters, COORD lastCharPos) const;
+    bool MoveToNextWord(COORD& pos, const std::wstring_view wordDelimiters, const COORD lastCharPos) const;
```
Comment (DHowett) [inline src/buffer/out/textBuffer.hpp:134]: surprised this compiles

File: src/host/ut_host/TextBufferTests.cpp [hunk 2]
```diff
@@ -2132,6 +2133,87 @@ void TextBufferTests::GetWordBoundaries()
...
+    };
+
+    // Set testData for GetWordStart tests
+    // clang-format off
+    std::vector<Test> testData = {
+        // tests for first line of text
+        { {  0, 0 },    {{  5, 0 },      { 0, 0 }} },
+        { {  1, 0 },    {{  5, 0 },      { 1, 0 }} },
+        { {  3, 0 },    {{  5, 0 },      { 3, 0 }} },
+        { {  4, 0 },    {{  5, 0 },      { 4, 0 }} },
```
Comment (DHowett) [inline src/host/ut_host/TextBufferTests.cpp:2171]: It doesn't seem right that `expected.moveBackwards` is the same as `startPos`. Why does moving backwards off the current word, when it is the first word, not end up at 0,0?

**Review by DHowett — APPROVED** [review]
I believe I understand -- you cannot move back a word, so you do not change the coordinates.

File: src/buffer/out/textBuffer.hpp (hunk 1 above)
Comment (carlos-zamora) [reply src/buffer/out/textBuffer.hpp:134]: derp. Just added it to the cpp too.

Comment (DHowett) [reply src/buffer/out/textBuffer.hpp:134]: The correct way to fix this would be to back out _all changes to `MoveToNextWord`_

**Review by DHowett — CHANGES_REQUESTED** [review]
as noted

**Review by DHowett — APPROVED** [review]

**Comment by DHowett** [comment]
@msftbot merge this in  5 minutes

**Comment by codeofdusk** [comment]
@DHowett I think this PR requires a second review from someone with write access.

**Comment by codeofdusk** [comment]
Oh and pipelines are failing.

**Comment by DHowett** [comment]
> @DHowett I think this PR requires a second review from someone with write access.

Yes, indeed. The team has been notified.

**Review by miniksa — APPROVED** [review]
Alright. I had to go dig into what `GetWordStart` did because you didn't change it in this PR. But this looks fine to get this fixed. And I'm glad to see the increased test coverage. I'll jump over to the perf one next.

**Comment by DHowett** [comment]
This fix was just released as part of Windows in [Insider Build 20236](https://blogs.windows.com/windows-insider/2020/10/14/announcing-windows-10-insider-preview-build-20236/)!
