### PR TITLE
Fix duplicate copyOnSelect when clicking on an unfocused terminal

### LINKED ISSUE #4255: Duplicate copyOnSelect actions
# Environment

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0

Windows Terminal Version 0.8.10091.0

# Steps to reproduce

Open WSL Ubuntu terminal
Select a block on text with copyOnSelect enabled (for example "TEST1")
  Ensure block of text remains highlighted
Switch to notepad instance
Paste selected text into Notepad
Make some change to text, (for example change string to "TEST999")
Copy string inside Notepad
Highlight Windows Terminal
Paste string into Windows Terminal

# Expected behavior

TEST999 is pasted into Windows Terminal window

# Actual behavior

TEST1 is pasted into Windows Terminal window

# Notes

It appears that each time the window is made active, a new copyOnSelect action is performed if there is some text previously highlighted. I would expect the Terminal to only perform the copy operation the very first time the text is highlighted.

### PR DESCRIPTION
**Pull request by leonMSFT**
## Summary of the Pull Request
Currently, clicking on an unfocused terminal with a selection active will trigger `copyOnSelect`. This is because the check for `copyOnSelect` and copying to the clipboard is bound to when the Pointer is released. This works fine for when a user performs a click-drag selection, but it inadvertently also triggers when the user performs a single click on an unfocused terminal. We expect `copyOnSelect` to trigger only on the first time a selection is completed. 

This PR will allow the user to single click on an unfocused terminal that has a selection active without triggering a copyOnSelect. It also ensures that any click-drag selection, whether it's on an unfocused or focused terminal, will trigger copyOnSelect.

## PR Checklist
* [x] Closes #4255

## Validation Steps Performed
Performed manual testing involving permutations of multiple panes, tabs, in focus, and out of focus.

### CODE REVIEW

File: src/cascadia/TerminalControl/TermControl.h [hunk 1]
```diff
@@ -162,7 +162,8 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
         Timestamp _lastMouseClick;
         unsigned int _multiClickCounter;
         std::optional<winrt::Windows::Foundation::Point> _lastMouseClickPos;
-        std::optional<winrt::Windows::Foundation::Point> _clickDragStartPos{ std::nullopt };
+        std::optional<winrt::Windows::Foundation::Point> _unfocusedClickPos{ std::nullopt };
+        bool _isClickDragSelection{ false };
```
Comment (carlos-zamora) [inline src/cascadia/TerminalControl/TermControl.h]: We should initialize these in the constructor or `_InitializeTerminal()` along with the others that are already there.
