### PR TITLE
Skip whitespace removal for multiline pastes

### LINKED ISSUE #12387: Pasting multiple lines doesn't execute the last line
### Windows Terminal version

1.13.10336.0

### Windows build number

10.0.19042.0

### Other Software

_No response_

### Steps to reproduce

Copy multiple powershell commands from any text editor.
Paste them into the powershell core tab of Windows Terminal.
All lines execute except the last line. (even though i've included one or 2 blanks lines after the last line of code - to ensure getting a new line or enter)

### Expected Behavior

All pasted lines of code should execute as expected.

### Actual Behavior

You must manually press the enter key to get the last command to execute.

### PR DESCRIPTION
**Pull request by serd2011**
## Summary of the Pull Request
Skips whitespace removal if pasted string is multiline

## PR Checklist
* [x] Closes #12387
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [x] Tests added/passed
* [ ] Documentation updated. If checked, please file a pull request on [our docs repo](https://github.com/MicrosoftDocs/terminal) and link it here: #xxx
* [ ] Schema updated.
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Validation Steps Performed
Tests passed
The last command in multiline paste now executes

### CODE REVIEW

**Comment by serd2011** [comment]
I don't really see why tabs should be treated differently. Am I missing something?

File: src/types/utils.cpp [hunk 1]
```diff
@@ -772,3 +772,33 @@ std::tuple<std::wstring, std::wstring> Utils::MangleStartingDirectoryForWSL(std:
...
+        // DON'T trim it in this case.
+        return textView;
+    }
+
+    if (const auto toRemove = textView.size() - 1 - lastNonSpace; toRemove > 0)
+    {
+        textView.remove_suffix(toRemove);
+    }
+
+    return textView;
```
Comment (lhecker) [inline src/types/utils.cpp:803]: The if condition isn't really needed... I'd suggest either of:
```suggestion
    textView.remove_suffix(textView.size() - 1 - lastNonSpace);
    return textView;
```

```suggestion
    return textView.substr(0, lastNonSpace + 1);
```

**Review by lhecker — APPROVED** [review]

**Comment by lhecker** [comment]
(I've fixed a small grammatical error in the PR title.)

**Review by zadjii-msft — APPROVED** [review]
LGTM. Makes more sense when you don't try to do weird games with tabs 😅
