### PR TITLE
Properly handle and test a11y movement at end of buffer

### LINKED ISSUE #7771: UIA: crash at very end of buffer
In the NVDA Python console (NVDA+control+z):

``` python console
>>> from NVDAObjects.UIA import UIATextInfo
>>> ti=UIATextInfo(nav, "last")
>>> ti.move("character", 1)  # conhost crashes
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "NVDAObjects\UIA\__init__.pyc", line 752, in move
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))
```

Note: fixing this bug may result in strange behaviour from NVDA (see [here](https://github.com/nvaccess/nvda/blob/master/source/NVDAObjects/UIA/winConsoleUIA.py#L53), around line 53). I'll remove the offending workaround once a fix is merged to master.

I suspect #6986 would fix this bug, but I think the root cause of this crash should be investigated before then. Cc @carlos-zamora.

### PR DESCRIPTION
**Pull request by carlos-zamora**
## Summary of the Pull Request
The `MovementAtExclusiveEnd` test was improperly authored for the
following reasons:
- it should have used `TEST_METHOD_PROPERTY` to cover all of the
  TextUnits
- TextUnit::Document (arguably one of the most important) was ommitted
  accidentally (`!= TextUnit_Document` was used instead of `<=`)
- The created range was not `EndExclusive`, but rather, the last cell in
  the buffer (`EndInclusive`)

The first half of this PR fixes the test.

The second half of this PR expands the test and fixes any related issues
to make the test pass (i.e. #7771):
- `TEST_METHOD_PROPERTY` was added for it to be degenerate (start/end at
  `EndExclusive`) or not (last cell of buffer)
- `utr->_start` is now also validated after moving backwards

NOTE: `utr->_start` was not validated when moving forwards because
moving forwards should always fail when at/past the last chell in the
buffer.

Closes #7771

### CODE REVIEW

File: src/buffer/out/textBuffer.cpp [hunk 1]
```diff
@@ -1359,9 +1359,15 @@ const til::point TextBuffer::GetGlyphEnd(const til::point pos) const
 bool TextBuffer::MoveToNextGlyph(til::point& pos, bool allowBottomExclusive) const
 {
     COORD resultPos = pos;
+    const auto bufferSize = GetSize();
```
Comment (DHowett) [inline src/buffer/out/textBuffer.cpp:1362]: is this the fix for the crash?

File: src/types/UiaTextRangeBase.cpp [hunk 2]
```diff
@@ -953,7 +953,7 @@ void UiaTextRangeBase::_moveEndpointByUnitCharacter(_In_ const int moveCount,
             }
             break;
         case MovementDirection::Backward:
-            success = buffer.MoveToPreviousGlyph(target, allowBottomExclusive);
+            success = buffer.MoveToPreviousGlyph(target);
```
Comment (DHowett) [inline src/types/UiaTextRangeBase.cpp:956]: this is because it is safe to move backwards off the exclusive end, and you're checking before loading the glyph data that it _is_ a valid position?

File: src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp [hunk 3]
```diff
@@ -1136,57 +1136,82 @@ class UiaTextRangeTests
...
+        const COORD endExclusive{ bufferSize.EndExclusive() };
 
-        // Iterate over each TextUnit. If the we don't support
+        // Iterate over each TextUnit. If we don't support
         // the given TextUnit, we're supposed to fallback
         // to the last one that was defined anyways.
+        BEGIN_TEST_METHOD_PROPERTIES()
+            TEST_METHOD_PROPERTY(L"Data:textUnit", L"{0, 1, 2, 3, 4, 5, 6}")
+            TEST_METHOD_PROPERTY(L"Data:degenerate", L"{false, true}")
+        END_TEST_METHOD_PROPERTIES();
```
Comment (DHowett) [inline src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp:1151]: great catch!

File: src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp [hunk 4]
```diff
@@ -1136,57 +1136,82 @@ class UiaTextRangeTests
...
-            case TextUnit::TextUnit_Document:
-                expectedEnd = bufferSize.Origin();
-                break;
-            default:
-                continue;
-            }
 
-            Log::Comment(NoThrowString().Format(L"Backwards by %s", toString(static_cast<TextUnit>(unit))));
+        //if (textUnit == TextUnit::TextUnit_Character && !degenerate)
+        //    DebugBreak();
```
Comment (DHowett) [inline src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp:1184]: commented

File: src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp [hunk 5]
```diff
@@ -1136,57 +1136,82 @@ class UiaTextRangeTests
...
 
-            // Create a degenerate UTR at EndExclusive
-            THROW_IF_FAILED(Microsoft::WRL::MakeAndInitialize<UiaTextRange>(&utr, _pUiaData, &_dummyProvider, endInclusive, endExclusive));
-            THROW_IF_FAILED(utr->Move(static_cast<TextUnit>(unit), -1, &moveAmt));
+        Log::Comment(NoThrowString().Format(L"Backwards by %s", toString(textUnit)));
+        THROW_IF_FAILED(utr->Move(textUnit, -1, &moveAmt));
```
Comment (DHowett) [inline src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp:1187]: so this test is different from before. instead of making a new UTR, it assumes that the existing one was ... unchanged? or it builds off the existing one?

This could use a comment explaining why we're recycling the UTR and what its expected state is!

File: src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp [hunk 6]
```diff
@@ -1136,57 +1136,82 @@ class UiaTextRangeTests
...
+        {
             THROW_IF_FAILED(Microsoft::WRL::MakeAndInitialize<UiaTextRange>(&utr, _pUiaData, &_dummyProvider, endInclusive, endExclusive));
-            THROW_IF_FAILED(utr->Move(static_cast<TextUnit>(unit), 1, &moveAmt));
-
-            VERIFY_ARE_EQUAL(endExclusive, utr->_end);
-            VERIFY_ARE_EQUAL(0, moveAmt);
         }
+        THROW_IF_FAILED(utr->Move(textUnit, 1, &moveAmt));
+
+        VERIFY_ARE_EQUAL(endExclusive, utr->_end);
```
Comment (DHowett) [inline src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp:1174]: so moving forward from a degenerate _or_ non-degenerate range results in a degenerate range? great

File: src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp (hunk 5 above)
Comment (DHowett) [reply src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp:1187]: nevermind -- now I understand. You're ensuring that the range _goes degenerate off the end_ no matter what.

File: src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp [hunk 7]
```diff
@@ -1136,57 +1136,82 @@ class UiaTextRangeTests
...
+        else if (textUnit <= TextUnit::TextUnit_Line)
+        {
+            VERIFY_ARE_EQUAL(lastLineStart, utr->_start);
+            VERIFY_ARE_EQUAL(degenerate ? lastLineStart : endExclusive, utr->_end);
+            VERIFY_ARE_EQUAL(-1, moveAmt);
+        }
+        else // textUnit <= TextUnit::TextUnit_Document:
+        {
+            VERIFY_ARE_EQUAL(origin, utr->_start);
+            VERIFY_ARE_EQUAL(degenerate ? origin : endExclusive, utr->_end);
```
Comment (DHowett) [inline src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp:1214]: i know it might be a chore, but having @codeofdusk review this test case for sanity would be helpful

Comment (DHowett) [reply src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp:1214]: (a chore for him, not a chore for you. since this is a bunch of dense WEX C++)

**Review by DHowett — APPROVED** [review]
Thanks so much for doing this. I like the look of this, and just had some process questions!

**Comment by zadjii-msft** [comment]
In general, this seems fine to me, but I can't really say I understand the problem space well enough to give an official ✔️. Maybe if you came through and answered some of Dustin's comments, then I could make better sense of what's going on? Or if @codeofdusk thinks the tests are good, then I'd probably defer to his expertise in the area

File: src/buffer/out/textBuffer.cpp (hunk 1 above)
Comment (carlos-zamora) [reply src/buffer/out/textBuffer.cpp:1362]: Yup. In general, I thought it was only possible for `_end` to be at `EndExclusive()`, so `allowBottomExclusive` is used to track if we are working with `_end`. That definitely wasn't the case because you can end up with `_start` at `EndExclusive()` by doing the repro steps.

So this check for `EndExclusive()` is basically thrown around everywhere to ensure we don't crash on an `IncrementInBounds` or `DecrementInBounds` check (which checks if the COORD is in the buffer, and `EndExclusive` isn't)

File: src/types/UiaTextRangeBase.cpp (hunk 2 above)
Comment (carlos-zamora) [reply src/types/UiaTextRangeBase.cpp:956]: Correct. It's safe to move backwards off the exclusive end. So let's not bother passing in `allowBottomExclusive` and _always_ allow it.

File: src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp (hunk 3 above)
Comment (carlos-zamora) [reply src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp:1151]: Thanks! Makes the tests so much more legible too haha.

File: src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp (hunk 5 above)
Comment (carlos-zamora) [reply src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp:1187]: Correct. We already verified that the UTR failed to move in the first place. So rather than creating another UTR at the same spot, we can save a bit of time.

File: src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp (hunk 6 above)
Comment (carlos-zamora) [reply src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp:1174]: Yup. That functionality was caught and introduced by #7530. So this does more testing on that for free!

**Comment by carlos-zamora** [comment]
@codeofdusk found that there was a crash when expanding at the end. So I added testing for that and fixed any failing tests.

**Comment by DHowett** [comment]
is there any way at all whatsoever that we can automatically do the things a human might do

**Comment by codeofdusk** [comment]
> is there any way at all whatsoever that we can automatically do the things a human might do

Maybe, by adapting NVDA's system test framework? Cc @feerrenrut, @michaelDCurran.

**Review by codeofdusk — APPROVED** [review]
While I don't feel comfortable commenting on the robustness of the unit tests, this PR definitely fixes my reported UIA bugs!

**Review by zadjii-msft — APPROVED** [review]
Good enough for me!

**Review by miniksa — APPROVED** [review]
This looks fine to me. I appreciate all the extra tests thrown in to be more comprehensive than before.

**Comment by DHowett** [comment]
This fix was just released as part of Windows in [Insider Build 20236](https://blogs.windows.com/windows-insider/2020/10/14/announcing-windows-10-insider-preview-build-20236/)!
