### PR TITLE
Delegate all character input to the character event handler

### LINKED ISSUE #3516: Terminal does not handle custom keyboard layouts with dead-keys mapping to themselves
The Microsoft Terminal does not seem to correctly handle dead-keys for a custom keyboard layout made with Microsoft Keyboard Layout Creator.

In fact, it does not correctly handle dead-keys which have a mapping for themselves in the keyboard layout.

# Environment

|Platform|ServicePack|Version|VersionString|
|---|---|---|---|
|Win32NT||10.0.19018.0|Microsoft Windows NT 10.0.19018.0|

Additionnal software:

 - [Custom AZERTY-NF Keyboard Layout](https://github.com/springcomp/optimized-azerty-win/releases/tag/v1.3.0.0)
 - [Microsoft Keyboard Layout Creator 1.4](https://www.microsoft.com/en-us/download/details.aspx?id=22339)

# Steps to reproduce

This issue happens with many dead-keys. For the purpose of this discussion, let us focus on one particular dead-key.

On a French AZERTY keyboard, the <kbd>AltGr</kbd>+<kbd>2</kbd> combination is a dead-key used to input the `~` (TILDE, U+007E) diacritical mark. By itself, this sequence does not produce any output to the Terminal.

Obviously, when this sequence if followed by a supported character, for instance <kbd>o</kbd>, the corresponding `õ` character is typed into the Terminal. A spacing version of the `~` character can be typed into the Terminal by following the dead-key sequence with a <kbd>Space</kbd>.

However, when using a custom AZERTY-NF keyboard layout, the corresponding sequence does not work.

In order to reproduce this issue:

 - Install the referred to AZERY-NF keyboard layout.
 - Select this layout as the currently active layout with <kbd>Win</kbd>+<kbd>Space</kbd>
 - In the Microsoft Terminal, type the following sequence: <kbd>AltGr</kbd>+<kbd>n</kbd>.
 - Observe that a character `~` (COMBINING TILDE, U+0303) has been typed into the Terminal.
 - Proceed to type the following key: <kbd>o</kbd>.
 - Observe that the character `õ` has been typed into the Terminal.

image

Alternatively, you can reproduce this issue by following this other set of steps:

 - Install MSKLC 1.4. 
 - Install the French AZERTY keyboard layout. 
 - With MSKLC, using the `File|Open Existing Keyboard…` menu command, open the French AZERTY keyboard layout (named _Français_ in the list)
 - Add an additionnal mapping for the <kbd>AltGr</kbd>+<kbd>2</kbd> dead key like so:

    - Click on the `é` key (VK_2) and push the `All…` button in the corresponding dialog.
    - In the lower part of this extended dialog, locate the mapping for the `ctrl-alt-<key>` dead key whose value is `0x007e` and push the `…` button.
    - Add a mapping for the base `U+007e` (TILDE) to the composite `U+0303` (COMBINING TILDE) as illustrated by the following screenshot.

    image

    - Using the `Project|Build DLL and Setup Package` menu command, compile the resulting layout. It should be generated in your `%USERPROFILE%\Documents\layout01` folder.
    
 - Install the custom layout by running `Setup.exe`.
 - Close your Windows session and login again.
 - Select this layout as the currently active layout with <kbd>Win</kbd>+<kbd>Space</kbd>
 - In the Microsoft Terminal, type the following sequence: <kbd>AltGr</kbd>+<kbd>2</kbd>.
 - Like previously described, observe that a character `~` (COMBINING TILDE, U+0303) has been typed into the Terminal.
 - Proceed to type the following key: <kbd>o</kbd>.
 - Observe that the character `õ` has been typed into the Terminal.

# Expected behavior

Similarly to what happens with the regular French keyboard, the <kbd>AltGr</kbd>+<kbd>n</kbd> combination on an AZERTY-NF keyboard layout is a dead-key and should not produce any output to the Terminal.

Followed by a supported character, for instance <kbd>o</kbd>, this dead-key sequence corresponds to the `~` diacritical mark and should type the character `õ` by itself on the terminal. 

# Actual behavior

When typing <kbd>AltGr</kbd>+<kbd>n</kbd>, <kbd>o</kbd>, the string `~õ` is typed into the Terminal, whereas the string `õ` was expected instead.

# Analysis summary

The heart of the problem lies in the following conditions:

- Microsoft Terminal handles `WM_CHAR` message that ultimately calls the `ToUnicodeEx` function. 
- Most keyboard layouts do not have a mapping for a double dead-key (a mapping for a dead-key to itself)

I believe calling `ToUnicodeEx` as part of the `WM_CHAR` handler is incorrect, because the effect of this function depends on the previous internal keyboard state.

# Extended analysis

Obviously, the expected behaviour is correctly observed in the builtin CMD, PowerShell and WSL terminals on Windows.

By compiling the latest version of the source code for Microsoft Terminal, I can see that the expected behaviour is also correctly observed when running the `OpenConsole.exe` program. The faulty behaviour only happens in the `WindowsTerminal` application launched from the `CascadiaPackage`.

I was able to pinpoint a troublesome behaviour at [this location](https://github.com/microsoft/terminal/blob/3e8a1a78bc456afc58686fa8ce818da0f03edbb3/src/cascadia/TerminalCore/Terminal.cpp#L303) in the source code.

There, the `ToUnicodeEx`[^](https://docs.microsoft.com/fr-fr/windows/win32/api/winuser/nf-winuser-tounicodeex) function does not return the correct result.

The reason for that is that this function is called inside a `WM_CHAR` handler where the keyboard internal state already contains the current character. However, the `ToUnicodeEx` function changes its behaviour depending on the current keyboard state.

For instance, consider the following table, that summarizes the parameters supplied to the `ToUnicodeEx` function:

|Layout|Sequence|Virtual Key Code|Scan Code|States|
|---|---|---|---|---|
|French AZERTY|<kbd>AltGr</kbd>+<kbd>2</kbd>|VK_2 (0x32)|0x03|CONTROL+MENU|
|French AZERTY-NF|<kbd>AltGr</kbd>+<kbd>n</kbd>|VK _N (0x4e)|0x31|CONTROL+MENU|

When called by itself in a [a simple program](https://gist.github.com/springcomp/f07157d1a50d18dcca84985752f10e33#file-program-cs), the `ToUnicodeEx` returns the correct result for both layouts, which is:

- The result of the function is `-1` indicating a dead key.
- The supplied buffer is set to a string containing `"~"` (TILDE, U+007E).

However, when called from within the `WM_CHAR` handler, the keyboard state contains the current (dead key character), the `ToUnicodeEx` function tries to combine the character corresponding to the supplied virtual key code, scan code and key states with the current internal keyboard state for the process.

- The result of the function is `2` indicating that a two-character string is returned.
- The supplied buffer is set to a string containing `"~~"` (TILDE, U+007E; TILDE, U+007E)

In fact, the `ToUnicodeEx` function _combines_ the supplied character with the previous keyboard state. In the case of virtually all keyboard layouts on the planet, there is no such valid combination. Therefore, the `ToUnicodeEx` function emits a string where the corresponding dead key character is emitted twice. That is what happens on Windows in all applications when typing the sequence <kbd>AltGr</kbd>+<kbd>2</kbd> twice on a French AZERTY keyboard.

Microsoft Terminal takes advantage of this fact, and when the `ToUnicodeEx` function returns anything other than `1` (a single character) or `-1` (a dead key character), it does not produce any output.

As for the AZERTY-NF layout of the customized layout described in the section for how to reproduce this issue, the `ToUnicodeEx` function behaves like so:

- The result is `1` indicating that a single character string is returned.
- The supplied buffer is set to a string containing `"~"` (COMBINING TILDE, U+0303).

This is consistent because the internal keyboard state already contains the dead key character and when combined with itself again, the keyboard layout is instructed to emit this particular character.

Because this results in a single character string, Microsoft Terminal writes this character to the output.

# Conclusion

I understand that this is a freak issue but I believe virtually all other Windows terminal-like apps handle the custom keyboard layout correctly, which seem to indicate that this is a bug in Microsoft Terminal only.

### LINKED ISSUE #3554: Further refine ToUnicodeEx calls in CharacterFromKeyEvent
> To fix the latter tangential issue, I'd like to propose that we simply return the first character of the output buffer, if the return value of `ToUnicodeEx` is >1. What do you think? (I'd open a seperate PR for this.)

That sounds reasonable based on the analysis above.

_Originally posted by @miniksa in https://github.com/microsoft/terminal/pull/3117#issuecomment-543234440_

This represents fixing the issue described in #3117 where other forms of multiple copies can occur based on the responses from ToUnicodeEx.

### PR DESCRIPTION
**Pull request by lhecker**
My basic idea was that `WM_CHAR` is just the better `WM_KEYDOWN`.
The latter fails to properly support common dead key sequences like in
#3516.

As such I added some logic to `Terminal::SendKeyEvent` to make it return
false if the pressed key represents a printable character.
This causes us to receive a character event with a (hopefully) correctly
composed code unit, which then gets sent to `Terminal::SendCharEvent`.
`Terminal::SendCharEvent` in turn had to be modified to support
potentially pressed modifier keys, since `Terminal::SendKeyEvent` isn't
doing that for us anymore.
Lastly `TerminalInput` had to be modified heavily to support character
events with modifier key states. In order to do so I merged its
`HandleKey` and `HandleChar` methods into a single one, that now handles
both cases.
Since key events will now contain character data and character events
key codes the decision logic in `TerminalInput::HandleKey` had to be
rewritten.

## PR Checklist
* [x] CLA signed
* [x] Tests added/passed
* [x] I've discussed this with core contributors already.

## Validation Steps Performed

* See #3516.
* I don't have any keyboard that generates surrogate characters. Due to
  this I modified `TermControl::_SendPastedTextToConnection` to send the
  data to `_terminal->SendCharEvent()` instead. I then pasted the test
  string ""𐐌𐐜𐐬" and ensured that the new `TerminalInput::_SendChar`
  method still correctly assembles surrogate pairs.

Closes #3516
Closes #3554 (obsoleted by this PR)
Potentially impacts #391, which sounds like a duplicate of #3516

### CODE REVIEW

**Comment by lhecker** [comment]
I'm almost done fixing all tests. Only `InputTest::TerminalInputModifierKeyTests` is still giving me troubles.
(...because `HandleKey()` is now capable of handling all characters, which this test doesn't know about yet.)

**Comment by lhecker** [comment]
OMG! All checks have passed?! I almost can't even believe it anymore. 😄
This PR was _seriously_ hard to create. Sheesh. I hope we can merge at least parts of it tbh. 😅

**Comment by zadjii-msft** [comment]
I've owed you a review for far too long on this particular PR. My schedule just became much more available, so I'm going to try and get to this today or Monday. Sorry for the delay!

**Comment by lhecker** [comment]
@zadjii-msft You don’t owe me anything. 🙂
I believe this PR is rather tricky as I decided to completely rewrite the entire input handling logic.
As such please feel free to "rip and tear" my PR apart. 😄

**Comment by zadjii-msft** [comment]
I absolutely do - IMO, it's our responsibility as project maintainers to reply to good contributions like this in a reasonably prompt timeframe. If the community is going to be generous enough to contribute to us, then the least we owe is the time to review the contribution. That's at least my opinion on that matter.

Besides, I wrote all this code originally like 3 years ago, so it's probably my _specific_ responsibility to review you ripping and tearing this apart 😜

**Comment by lhecker** [comment]
FYI I rebased this PR to resolve merge conflicts that have popped up.

**Comment by lhecker** [comment]
@zadjii-msft Do you happen to have time for some unicode love? 🙈🙈🙈
The last build failed due to a timeout. Can you restart it?

File: src/terminal/input/terminalInput.cpp [hunk 1]
```diff
@@ -440,120 +440,138 @@ static bool _translateDefaultMapping(const KeyEvent& keyEvent,
...
+
+    // Many keyboard layouts have an AltGr key, which makes widely used characters accessible.
+    // For instance on a German keyboard layout "[" is written by pressing AltGr+8.
+    // Furthermore Ctrl+Alt is traditionally treated as an alternative way to AltGr by Windows.
+    // When AltGr is pressed, the caller needs to make sure to send us a pretranslated character in GetCharData().
+    // We'll handle this case first, in order for us to not step into the Alt/Ctrl conditions below.
+    if (keyEvent.IsAltGrPressed() && keyEvent.GetCharData() != 0)
     {
-        const auto senderFunc = [this](const std::wstring_view seq) noexcept { _SendInputSequence(seq); };
+        _SendChar(keyEvent.GetCharData());
```
[the remark this answers is not in the document]
Comment (lhecker) [reply src/terminal/input/terminalInput.cpp]: Hmm... I never actually thought about this!
I'll try to revert this particular condition and see whether everything still works. 🙂

File: src/terminal/input/terminalInput.cpp [hunk 2]
```diff
@@ -440,120 +440,138 @@ static bool _translateDefaultMapping(const KeyEvent& keyEvent,
...
+//   modifiers, like the characters given by the WM_CHAR event.
+// - The caller doesn't need to fill in any char data for:
+//   - Tab key
+//   - Alt+key combinations
+// - This method will alias Ctrl+Space as a synonym for Ctrl+@ - the null byte.
+// Arguments:
+// - keyEvent - Key event to translate
+// Return Value:
+// - True if the event was handled.
+bool TerminalInput::HandleKey(const IInputEvent* const pInEvent)
```
[the remark this answers is not in the document]
Comment (lhecker) [reply src/terminal/input/terminalInput.cpp]: I'm sorry. 🙈
Most changes to this function where necessary to ensure everything still works when you funnel character events into `HandleKey()` instead of `HandleChar()` (which doesn't exist anymore).

At some point I got so confused by the code that I just decided to rewrite this function _from scratch_.
This also means though that it actually might be best if you review changes to this function by pulling up [the current code](https://github.com/microsoft/terminal/blob/1ae4252a7bc07eb08511c837e572ae0ffa58694c/src/terminal/input/terminalInput.cpp#L443-L548) and comparing it side-by-side with the one in my PR, without viewing the diff.
While the structure is entirely different, you should quickly notice that the logic flow itself is the same as before.
I added comments to each section explaining how I understood the code and why it's necessary.

**Comment by lhecker** [comment]
@zadjii-msft Honestly I wouldn't be mad at all if you didn't merge this before 1.0.
In fact as you pointed out yourself this PR introduced a bug. 😄
I'll try to swiftly fix all bugs that I can find though and make sure this PR at least works just as well as the current master.

**Comment by lhecker** [comment]
@zadjii-msft I feel like I'm loosing my mind. 😐
The issue regarding <kbd>Ctrl+Alt+Space</kbd> resulting in `^[^R` is fixed if you change [this condition](https://github.com/microsoft/terminal/blob/1805f792f619450f6aa6a099195d1a9f58666342/src/terminal/input/terminalInput.cpp#L518) to be `ch >= 0x40` instead.
If you attach a debugger with a breakpoint condition of `ch < 0x40` you'll notice that this breakpoint is apparently never hit.
Do you know what's going on here? Is the `TerminalInput` class being used outside of the debugger's context?

In the meantime I'll change the if condition to reflect the current master branch, because that fixes the issue for whatever reason.

**Comment by lhecker** [comment]
@zadjii-msft I've force-pushed a new version that reduces the amount of changes in this PR by about a quarter. 🙂
It also fixes the <kbd>Ctrl+Alt+Space</kbd> issue as mentioned above.
I tested all key combinations that I could think of and made sure that the showkey output is the same between the current master and my version.

**Comment by lhecker** [comment]
F*** Now I remember why I rebuilt the entire `inputTest.cpp`. 😄
I changed the code to use a `std::wstring` because there's now a new situation where the buffer can contain e.g. `\x1b\x00` and the test should definitely cover that situation.
The current approach with the `s_pwsInputBuffer` doesn't support this though, because it's C-string based (i.e. null-terminated).

**Comment by lhecker** [comment]
Since the last time you reviewed, @zadjii-msft, [this has happened](https://github.com/microsoft/terminal/compare/1805f792f619450f6aa6a099195d1a9f58666342..a8e86ac3c02b0f5590fad1b367a937e1d695e1ca).
I'm extremely sorry for me rebasing this PR. I thought I could get rid of a huge chunk of unnecessary changes, but it turns out I actually made them for a reason. I could've just pushed the changes as separate commits. Sorry. 🙈

If you dislike the size of this PR I could find a way to integrate the changes necessary for #3516 without modifying `TerminalInput::HandleKey` too much btw. I believe that should be possible.

**Comment by zadjii-msft** [comment]
> sorry for me rebasing this PR

Don't worry about it, happens all the time! Providing that delta link is much appreciated :)

> If you dislike the size of this PR

lol no, it's perfectly fine. It's just one of those types of changes that github has a particularly hard time with. I couldn't care less about the actual size, looking through the code I'm not terribly scared of it. You're version of `TerminalInput::HandleKey` looks infinitely better and I'd hate to lose that goodness ❤️

**Comment by lhecker** [comment]
@zadjii-msft Yeah I was just about to say that as well.

As I wrote above the most puzzling thing for me though is if you change [this if condition (line 510)](https://github.com/microsoft/terminal/pull/4192/files#diff-3895074b0184ca0d36ef271db540a282R510) to a simple `ch != 0` - which _should_ be correct as well.
If you attach a debugger you'll see that `TerminalInput` _definitely_ invokes `_pfnWriteEvents` with a `\x1b\x00` sequence.
But then showkey shows a `^[^R` sequence instead. How can this happen? I don't understand how such a benign change to the if condition can cause this. :disappointed:

**Comment by zadjii-msft** [comment]
Okay I maybe saw what happened here.

1. On a en-us keyboard, '@' is <kbd>shift+2</kbd>. 
2. When conpty sees a `\x1b\x0`, it converts it to [Shift_down, Ctrl_down, Alt_down, 2_down, 2_up, Alt_up, Ctrl_up, Shift_up].
    - I did not pay a ton of attention to the keys that got synthesized here. I need to re-investigate the [2_down, 2_up]
3. When we get back to `TerminalInput::HandleKey`, we end up skipping that branch, because the `ch` was `0n50`, which is `0x32`, which is `'2'`.

I'm not sure what's exactly the right behavior here. I'd think we probably should send a different key, but I'll need to investigate more. It's possible that the `ch != 0` change would work just fine, but I want to make sure that the upstream input from conpty is _actually_ correct.
I've got a [braindead fix](https://github.com/microsoft/terminal/commit/77eee7066e5606f32359ec5ea8b291e42aa86ca9) that would fix `showkey -a`, but that doesn't really resolve the issue here for Win32 applications unfortunately, so I'm gonna file a separate issue to track this investigation.

File: src/cascadia/TerminalCore/Terminal.cpp [hunk 3]
```diff
@@ -471,9 +463,39 @@ bool Terminal::SendMouseEvent(const COORD viewportPos, const unsigned int uiButt
...
+    // the system menu for restore, min/maximize, size, move, close.
+    if (ch == L' ' && states.IsAltPressed() && !states.IsCtrlPressed())
+    {
+        return false;
+    }
+
+    auto vkey = _TakeVirtualKeyFromLastKeyEvent(scanCode);
+    if (vkey == 0 && scanCode != 0)
+    {
+        vkey = _ScanCodeFromVirtualKey(scanCode);
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalCore/Terminal.cpp:490]: this name worries me. Below, we have `VirtualKeyFromCharacter`, but here we're _assigning_ `vkey` but the function name implies it returns a ScanCode

File: src/terminal/input/terminalInput.cpp [hunk 4]
```diff
@@ -440,120 +440,150 @@ static bool _translateDefaultMapping(const KeyEvent& keyEvent,
...
+    if (keyEvent.IsModifierPressed() && _searchWithModifier(keyEvent, senderFunc))
+    {
+        return true;
+    }
 
-            if (!keyHandled)
-            {
-                // For perf optimization, filter out any typically printable Virtual Keys (e.g. A-Z)
-                // This is in lieu of an O(1) sparse table or other such less-maintainable methods.
-                // VK_CANCEL is an exception and we want to send the associated uChar as is.
```
Comment (DHowett-MSFT) [inline src/terminal/input/terminalInput.cpp:529]: Is this a worthwhile optimization to keep? I'd be interested in seeing the real-world performance impact.

File: src/cascadia/TerminalCore/Terminal.cpp (hunk 3 above)
Comment (lhecker) [reply src/cascadia/TerminalCore/Terminal.cpp:490]: You‘re right: This should be `_VirtualKeyFromScanCode`. 👍

File: src/terminal/input/terminalInput.cpp (hunk 4 above)
Comment (lhecker) [reply src/terminal/input/terminalInput.cpp:529]: `_translateDefaultMapping` is an extremely simple and fast method (<1us I‘m sure) and I suppose it‘s not necessary to retain such an optimization.
On the other hand the intention of the previous code is easy to understand and doesn’t add much complexity.
I‘ll gladly add it back in. 👍

(Our of curiosity I‘ll make sure to post the performance impact of that function tomorrow. 🙂)

Comment (DHowett-MSFT) [reply src/terminal/input/terminalInput.cpp:529]: I believe you that it's incredibly minor, so I am okay leaving out the optimization. It used to be a std::map, but then it was replaced with an std::array and not revisited. No need to share performance traces as a requirement for landing this :smile:

**Comment by DHowett-MSFT** [comment]
(You'll probably need to merge master to get the spell checking bot going again, but I bet it's going to complain about `ecma` (instead of `ECMA`)

File: src/terminal/input/terminalInput.cpp [hunk 5]
```diff
@@ -440,120 +440,150 @@ static bool _translateDefaultMapping(const KeyEvent& keyEvent,
...
-            // pressed...
-            // ... and if they are both pressed, strip them out of the control key state.
-            if (keyEvent.IsAltGrPressed())
-            {
-                keyEvent.DeactivateModifierKey(ModifierKeyState::LeftCtrl);
-                keyEvent.DeactivateModifierKey(ModifierKeyState::RightAlt);
-            }
+            // For Alt+Ctrl+Key messages GetCharData() returns 0.
+            // -> Get the char from the virtual key.
+            ch = LOWORD(MapVirtualKeyW(keyEvent.GetVirtualKeyCode(), MAPVK_VK_TO_CHAR));
```
Comment (DJm00n) [inline src/terminal/input/terminalInput.cpp:502]: @lhecker this may be broken for non-US layouts.
See https://stackoverflow.com/q/72464583/1795050
