### PR TITLE
Move commandline->title promotion into TerminalSettings

### LINKED ISSUE #6776: Windows/tabs created with "wt new-tab COMMAND" start with the title of the default Terminal profile, not the COMMAND name
### Environment

**Windows build number:** Windows 10 ver. 2004 build 19041.329
**Windows Terminal version (if applicable):** 1.1.1812.0

### Steps to reproduce

1. While Terminal is closed, delete or rename your `settings.json` file, causing Terminal to revert to the default settings under which the built-in Windows PowerShell profile for Terminal `{61c54bbd-c2c6-5271-96e7-009a87ff44bf}` is the default one.
1. Run this command: `wt.exe C:\Windows\System32\robocopy.exe`

### Expected behavior

The title of the Terminal tab created is "C:\Windows\System32\robocopy.exe" or similar.

### Actual behavior

The title of the Terminal tab created is "Windows PowerShell".
(If you watch Task Manager or another process listing, you can see that no PowerShell process was ever started.)

### PR DESCRIPTION
**Pull request by DHowett**
It was insufficient to only promote commandline components to titles
during commandline parsing, because we also have a whole complement of
actions that contain NewTerminalArgs. The tests caught me out a little
too late (sorry!). I decided it was better move promotion down to
TerminalSettings.

Fixes #6776
Re-implements #10998

### CODE REVIEW

File: src/cascadia/TerminalSettingsModel/TerminalSettings.cpp [hunk 1]
```diff
@@ -124,6 +124,21 @@ namespace winrt::Microsoft::Terminal::Settings::Model::implementation
...
+            {
+                // There was no title, and no profile from which to infer the title.
+                // Per GH#6776, promote the first component of the command line to the title.
+                // This will ensure that the tab we spawn has a name (since it didn't get one from its profile!)
+                if (newTerminalArgs.Profile().empty() && !newTerminalArgs.Commandline().empty())
+                {
+                    const std::wstring_view commandLine{ newTerminalArgs.Commandline() };
+                    const auto start{ til::at(commandLine, 0) == L'"' ? 1 : 0 };
+                    const auto terminator{ commandLine.find_first_of(start ? L'"' : L' ', start) }; // look past the first character if it starts with "
+                    // We have to take a copy here; winrt::param::hstring requires a null-terminated string
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsModel/TerminalSettings.cpp:137]: this is rough but it works. doing a substr with `npos-x` later is safe (confirmed by docs)

Comment (DHowett) [reply src/cascadia/TerminalSettingsModel/TerminalSettings.cpp:137]: if it yields a title of _nothing_, we already have a weird commandline. If the title is too long, _oh well_

**Review by zadjii-msft — APPROVED** [review]

File: src/cascadia/TerminalSettingsModel/TerminalSettings.cpp (hunk 1 above)
Comment (lhecker) [reply src/cascadia/TerminalSettingsModel/TerminalSettings.cpp:137]: Are you sure about this? `winrt::param::hstring` has an explicit `std::wstring_view` constructor and appears to work just fine with it.

Comment (DHowett) [reply src/cascadia/TerminalSettingsModel/TerminalSettings.cpp:137]: Dead sure. This blog post just came out today to reinforce: https://devblogs.microsoft.com/oldnewthing/20210823-00/?p=105598

**Comment by lhecker** [comment]
Also, while it's less efficient, I think we should introduce `til::trim_prefix/suffix` functions...
It's easy to implement with existing functions:
```cpp
template<typename T, typename Traits>
constexpr std::basic_string_view<T, Traits> trim_prefix(const std::basic_string_view<T, Traits>& str, const std::basic_string_view<T, Traits>& prefix) noexcept
{
#pragma warning(suppress : 26481) // Don't use pointer arithmetic. Use span instead
	return starts_with(str, prefix) ? std::basic_string_view<T, Traits>{ str.data() + prefix.size(), str.size() - prefix.size() } : str;
}

constexpr std::string_view trim_prefix(const std::string_view& str, const std::string_view& prefix) noexcept
{
	return trim_prefix<>(str, prefix);
}

constexpr std::wstring_view trim_prefix(const std::wstring_view& str, const std::wstring_view& prefix) noexcept
{
	return trim_prefix<>(str, prefix);
}

template<typename T, typename Traits>
constexpr std::basic_string_view<T, Traits> trim_suffix(const std::basic_string_view<T, Traits>& str, const std::basic_string_view<T, Traits>& suffix) noexcept
{
#pragma warning(suppress : 26481) // Don't use pointer arithmetic. Use span instead
	return ends_with(str, suffix) ? std::basic_string_view<T, Traits>{ str.data(), str.size() - prefix.size() } : str;
}

constexpr std::string_view trim_suffix(const std::string_view& str, const std::string_view& suffix) noexcept
{
	return trim_prefix<>(str, suffix);
}

constexpr std::wstring_view trim_suffix(const std::wstring_view& str, const std::wstring_view& suffix) noexcept
{
	return trim_prefix<>(str, suffix);
}

// ...

const auto firstComponent = til::trim_suffix(til::trim_prefix(commandLine, L'"'), L'"');
```

**Comment by DHowett** [comment]
That doesn't do the same thing as this, though. This converts `"foo" bar` into _just_ `foo` 😄

File: src/cascadia/TerminalSettingsModel/TerminalSettings.cpp (hunk 1 above)
Comment (lhecker) [reply src/cascadia/TerminalSettingsModel/TerminalSettings.cpp:137]: shocked

Comment (lhecker) [reply src/cascadia/TerminalSettingsModel/TerminalSettings.cpp:137]: Uh oh.

**Review by lhecker — APPROVED** [review]

**Comment by DHowett** [comment]
@msftbot merge this in 2 minutes
