### PR TITLE
Make Terminal look great in High Contrast

### LINKED ISSUE #5360: UI is broken in system high contrast mode
# Environment

```
Windows build number: 10.0.19603.1000
Windows Terminal version (if applicable): 0.10.781.0
```

# Steps to reproduce

Turn on high contrast mode.

# Expected behavior

UI elements should become easier to distinguish.

# Actual behavior

Terminal UI elements are hard to identify. It took me some time to find the `+` button because it looks like the Windows logo or the start menu button and not like a `+`. Dropdown button looks more like a checkbox than a dropdown button or arrow pointing down.

Screenshot_win10_2020-04-15_17:10:46

### PR DESCRIPTION
**Pull request by jtippet**
## Summary of the Pull Request
This PR enables `ApplicationHighContrastAdjustment::None`.  Doing this disables a set of mitigations in XAML designed to band-aid apps that were never explicitly designed for High Contrast (HC) modes.  Terminal now has full control of and responsibility for its appearance in HC mode.  This allows Terminal to look a lot better.

## PR Checklist
* [X] Closes #5360 
* [X] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Documentation updated. If checked, please file a pull request on [our docs repo](https://github.com/MicrosoftDocs/terminal) and link it here: #xxx
* [ ] Schema updated.
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Detailed Description of the Pull Request / Additional comments
On paper, we should be able to set `HighContrastAdjustment="None"` on the `<Application>` element.  But that doesn't have any effect.  I don't know if this is a bug in `<Toolkit:XamlApplication>` or somewhere else.  So instead I set the property in codebehind, which is not as ideal, but does at least work.  I'd love to a way to move this into App.xaml.

The Find box had a couple stray styles to override the ToggleButton's foreground color.  With backplating removed, these styles became actively harmful (white foreground on highlight color background), so I just removed them.  The built-in style for ToggleButton is perfect as-is.

## Validation Steps Performed
Vicariously validate via viewing various vivid videos.

High Contrast White:
finalwhite

High Contrast Dark:
finalblack

The previous appearance, prior to this PR, for comparison purposes:
finalold

@mimi89999 _this_ is the PR you've been waiting for ;)  Thanks for reporting the HC bugs, and please do keep leaning on apps to make them look great in HC mode.

### CODE REVIEW

**Comment by mimi89999** [comment]
Thanks a lot for your work on this. I'm waiting for this to land in master for the pipeline not being a PR one to test the artifacts :smile:

File: src/cascadia/TerminalApp/App.cpp [hunk 1]
```diff
@@ -26,6 +26,7 @@ namespace winrt::TerminalApp::implementation
         }
 
         Initialize();
+        HighContrastAdjustment(::winrt::Windows::UI::Xaml::ApplicationHighContrastAdjustment::None);
```
Comment (miniksa) [inline src/cascadia/TerminalApp/App.cpp:29]: A comment leaving a bit of explanation and the effects of this above the call would be appreciated. (As well as perhaps a reference to what it influences in the XAML files for future cross-referencing when we add more UI or update what we have.) Someone *could* go look up this PR with `git blame` and the docs page on `HighContrastAdjustment`, but I feel like it's a thing that should be explained in-line.

**Comment by jtippet** [comment]
> In general, I am neither surprised nor horrified to learn that there is a global magic flag that is set to "do weird stuff to my application" mode by default.

Console defaults to CP_OEM streams or something equally vile ��

**Comment by DHowett** [comment]
I feel very seen right now
😁

**Comment by DHowett** [comment]
@msftbot merge this in 5 minutes
