### PR TITLE
Make sure to copy `connectionType` for the azure shell

### LINKED ISSUE #12120: Unable to duplicate Azure Cloud Shell Profile
### Windows Terminal version

1.11.3471.0

### Windows build number

10.0.19044.1415

### Other Software

_No response_

### Steps to reproduce

Start Windows Terminal
Go to settings
Add a new profile
Duplicate Azure Cloud Shell Profile & Save

### Expected Behavior

I expect this to work in the same way as it works for PowerShell or Ubuntu. 

### Actual Behavior

It doesn't work and fails with the error below.

[error 0x80070002 when launching `Azure']
windowsterminal-3
windowsterminal-2
windowsterminal-1

### PR DESCRIPTION
**Pull request by zadjii-msft**
This was a simple oversight. No user profile ever has `connectionType` set, because why would they. So even for the Azure Shell, which needed this, the check would fail and we'd forget to duplicate the connectionType to the new profile.

* [x] I work here
* [x] Closes #12120
* [x] Tested manually

### CODE REVIEW

**Review by miniksa — APPROVED** [review]

File: src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp [hunk 1]
```diff
@@ -345,7 +345,13 @@ Model::Profile CascadiaSettings::DuplicateProfile(const Model::Profile& source)
...
+    // GH#12120: Check if the connection type isn't just the default value. If
+    // it is, then we should copy it. The only case this applies right now is
+    // for the Azure Cloud Shell, which is the only thing that has a non-{}
+    // guid. The user's version of this profile won't have connectionType set,
+    // because it inherits the setting from the parent. If we fail to copy it
+    // here, they won't actually get a Azure shell profile.
+    if (source.ConnectionType() != winrt::guid{})
     {
         duplicated->ConnectionType(source.ConnectionType());
     }
```
Comment (lhecker) [inline src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp:357]: In Go you have this idiom where you write:
```go
if foo := bar(); foo != 123 {
    baz(foo);
}
```

You can write the same in C++:
```cpp
 if (const auto type = source.ConnectionType(); type != winrt::guid{})
{
    duplicated->ConnectionType(type);
}
```

I personally find this idiom quite fitting for such situations.

**Review by lhecker — APPROVED** [review]

**Review by carlos-zamora — APPROVED** [review]

**Comment by DHowett** [comment]
@msftbot merge this in 5 minutes
