### PR TITLE
Make Conpty emit wrapped lines as actually wrapped lines

### LINKED ISSUE #405: Text Wrapping with ConPTY
It seems to me that output is line-wrapped by conhost before being sent through the ConPTY stdout pipe. This makes sense, though it has the unfortunate downside that in [Alacritty](https://github.com/jwilm/alacritty) we can't do the line-wrapping ourselves.

This wouldn't matter that much, but when selecting and copying text in Alacritty which has been line-wrapped by conhost, Alacritty isn't aware that the text was originally a single line and inserts a newline into the content placed on the clipboard.

Is it possible to disable the line wrapping by conhost?

(Perhaps this would be something that would naturally be in the "passthrough" mode I've seen mentioned elsewhere in this issue tracker?)

### LINKED ISSUE #3088: WSL Terminal Line Endings (the "exact wrap" bug)
Put into terminal and then increase the window size:
`printf "%*s\n" "$(tput cols)" "" | tr " " "X"`

Line endings acts like they disappeared if the string length matches exactly the window columns.
The terminal has different behavior for columns +- 1.
The behavior does not depend on the type of shell.

### LINKED ISSUE #3367: Make sure WT can copy wrapped lines as a single line
I created this profile (since WT 0.5),

```
{
            "guid": "{9c173dff-f524-43df-b40e-29953998c744}",
            "name": "MSYS2 Terminal",
            "commandline": "cmd.exe /c \"set MSYSTEM=MSYS&& set MSYS=winsymlinks:nativestrict&& C:/msys64/usr/bin/bash.exe --login\"",
            "hidden": false,
            "startingDirectory": "C:/msys64/home/user",
            "closeOnExit": true,
            "colorScheme": "MSYS2-Theme",
            "cursorColor": "#FD9D4F",
            "cursorShape": "filledBox",
            "fontFace": "Cascadia Code",
            "fontSize": 11,
            "historySize": 9001,
            "icon": "C:/msys64/msys2.ico",
            "padding": "8, 8, 8, 8",
            "snapOnInput": true// ,
            // "useAcrylic": true,
            // "acrylicOpacity": 0.75
        }
```

and noticed that when I paste a long line as in 
long_line it works wrong

```
$ ls -lrt /usr/lib/gcc/ /usr/lib/gcc/ /usr/lib/gcc/ /usr/lib/gcc/ /usr/lib/gcc/ /usr/lib/gcc/ /usr/lib/gcc/ /usr/lib/gc
ls: impossibile accedere a '/usr/lib/gc': No such file or directory
[...]
$ c/ /usr/lib/gcc/ /usr/lib/gcc/
```

This does not occur in Ubuntu or DOS or PoweShell profiles.

In short, it does not like the end of line when using MSYS2 profile. Maybe you have some suggestions...

(BTW, I copied that line dragging the mouse and pasting with right click, as usually one have to do in WT)

The system is W10 Pro 64 10.0.18362.449.

### PR DESCRIPTION
**Pull request by zadjii-msft**
## Summary of the Pull Request

Changes how conpty emits text to preserve line-wrap state, and additionally adds rudimentary support to the Windows Terminal for wrapped lines.

## References

* Does _not_ fix (!) #3088, but that might be lower down in conhost. This makes wt behave like conhost, so at least there's that
* Still needs a proper deferred EOL wrap implementation in #780, which is left as a todo
* #4200 is the mega bucket with all this work
* MSFT:16485846 was the first attempt at this task, which caused the regression MSFT:18123777 so we backed it out.
* #4403 - I made sure this worked with that PR before I even sent #4403

## PR Checklist
* [x] Closes #405
* [x] Closes #3367 
* [x] I work here
* [x] Tests added/passed
* [n/a] Requires documentation to be updated

## Detailed Description of the Pull Request / Additional comments

I started with the following implementation:
When conpty is about to write the last column, note that we wrapped this line here. If the next character the vt renderer is told to paint get is supposed to be at the start of the following line, then we know that the previous line had wrapped, so we _won't_ emit the usual `\r\n` here, and we'll just continue emitting text.

However, this isn't _exactly_ right - if someone fills the row _exactly_ with text, the information that's available to the vt renderer isn't enough to know for sure if this line broke or not. It is possible for the client to write a full line of text, with a `\n` at the end, to manually break the line. So, I had to also add the `lineWrapped` param to the `IRenderEngine` interface, which is about half the files in this changelist.

## Validation Steps Performed
* Ran tests
* Checked how the Windows Terminal behaves with these changes
* Made sure that conhost/inception and gnome-terminal both act as you'd expect with wrapped lines from conpty

### CODE REVIEW

File: src/renderer/vt/paint.cpp [hunk 1]
```diff
@@ -445,10 +450,36 @@ using namespace Microsoft::Console::Types;
...
 
+    // If we've written text to the last column of the viewport, then mark
+    // that we've wrapped this line. The next time we attempt to move the
+    // cursor, if we're trying to move it to the start of the next line,
+    // we'll remember that this line was wrapped, and not manually break the
+    // line.
+    // Don't do this is the last character we're writing is a space - The last
+    // char will always be a space, but if we see that, we shouldn't wrap.
+    if (lineWrapped &&
+        (_lastText.X + (totalWidth - numSpaces)) > _lastViewport.RightInclusive())
```
Comment (zadjii-msft) [inline src/renderer/vt/paint.cpp]: @miniksa What's the correct new-safemath way of doing this?

Comment (miniksa) [reply src/renderer/vt/paint.cpp]: Depends if you want an error out of bounds or if you want it to clamp. In most cases, we just want to clamp, so far.

You can either turn some of these variables into `base::ClampedNumeric<T>` or `base::CheckedNumeric<T>` and then use the usual operators on them to do the math normally and extract the result at the end. Clamped will auto-extract on assignment to a normal type. Checked requires you to choose one of the three extractions (ValueOrDie, ValueOrDefault, or AssignIfValid) to determine how you want to handle it.

Alternatively, you can just do the work with the bare types using `base::ClampAdd()` or `base::CheckAdd()` in a similar fashion to the old safe math way. Your choice. Whichever looks least ugly.

Finally, there's also `base::saturating_cast<T>` and `base::checked_cast<T>` if you want to do everything some other way in a larger datatype and then cast to check at the end.

It'll be completely contextual so I'm leaving it to you to decide which way works best here as I didn't read the whole function context, just your diffs.

**Comment by DHowett-MSFT** [comment]
I edited the description from `does not fix x` to `does not fix (!) x` because `fix x` is a magic github keyword and it doesn't read your sentence to figure out that you were deceiving it

**Comment by zadjii-msft** [comment]
> 
> 
> I edited the description from `does not fix x` to `does not fix (!) x` because `fix x` is a magic github keyword and it doesn't read your sentence to figure out that you were deceiving it

thanks :)

File: src/host/ut_host/VtRendererTests.cpp [hunk 2]
```diff
@@ -1315,8 +1315,8 @@ void VtRendererTest::TestWrapping()
             clusters2.emplace_back(std::wstring_view{ &line2[i], 1 }, static_cast<size_t>(rgWidths[i]));
         }
 
-        VERIFY_SUCCEEDED(engine->PaintBufferLine({ clusters1.data(), clusters1.size() }, { 0, 0 }, false));
-        VERIFY_SUCCEEDED(engine->PaintBufferLine({ clusters2.data(), clusters2.size() }, { 0, 1 }, false));
+        VERIFY_SUCCEEDED(engine->PaintBufferLine({ clusters1.data(), clusters1.size() }, { 0, 0 }, false, false));
+        VERIFY_SUCCEEDED(engine->PaintBufferLine({ clusters2.data(), clusters2.size() }, { 0, 1 }, false, false));
```
Comment (carlos-zamora) [inline src/host/ut_host/VtRendererTests.cpp]: If we're making that last param `false` for all of these tests, should it be a default param with a value of false unless stated otherwise?

**Comment by DHowett-MSFT** [comment]
@miniksa had comments on this -- I'd like to know whether he's cool before merging.

**Comment by DHowett-MSFT** [comment]
@msftbot make sure @miniksa signs off on this

**Comment by zadjii-msft** [comment]
@miniksa this is the one
