### PR TITLE
Manually copy trailing attributes on a resize

### LINKED ISSUE #32: Console doesn't handle colored regions when reflowed
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
FCU

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)

1. Open Ubuntu session in Console
1. Execute the following:

```bash
$ cd ~/
$ mkdir temp
$ cd temp
$ mkdir hello
$ mkdir world
$ clear 
$ ls
```

3. Grab & drag right-hand Console window edge to resize window width

## Expected:
Folders' colored background should only extend to the end of the folder name:

image

## Actual:
Lines with folders that are last item on line extend folder background coloring to right hand end of line:

image

See the following for an example of where it goes very wrong:
image

And it gets worse when lines wrap!
image

# References
Thanks to @jmorrill for reporting here: https://twitter.com/jmorrill/status/915982968094580736

### LINKED ISSUE #12567: Full-screen COLOR command no longer works right when resizing conhost and Terminal
> Open cmd window, set the color to 2f (green background, white text); observe the color change
> Resize the window, the color changes back to black, with the "text" portion of the window still left in 2f.
> This behavior can be repeated every time a resize happens.

This is the external half of MSFT:34761400

> Yep, okay this is weird in conhost now. I bet this was caused by fixing #3848.

Since this one's a partner bug, we've gotta get this sorted out in this OS release.

### PR DESCRIPTION
**Pull request by zadjii-msft**
## THE WHITE WHALE

This is a fairly naive fix for this bug. It's not terribly performant,
but neither is resize in the first place.

When the buffer gets resized, typically we only copy the text up to the
`MeasureRight` point, the last printable char in the row. Then we'd just
use the last char's attributes to fill the remainder of the row. 

Instead, this PR changes how reflow behaves when it gets to the end of
the row. After we finish copying text, then manually walk through the
attributes at the end of the row, and copy them over. This ensures that
cells that just have a colored space in them get copied into the new
buffer as well, and we don't just blat the last character's attributes
into the rest of the row. We'll do a similar thing once we get to the
last printable char in the buffer, copying the remaining attributes.

This could DEFINITELY be more performant. I think this current
implementation walks the attrs _on every cell_, then appends the new
attrs to the new ATTR_ROW. That could be optimized by just using the
actual iterator. The copy after the last printable char bit is also
especially bad in this regard. That could likely be a blind copy - I
just wanted to get this into the world.

Finally, we now copy the final attributes to the correct buffer: the new
one.  We used to copy them to the _old_ buffer, which we were about to
destroy.

## Validation

I'll add more gifs in the morning, not enough time to finish spinning a
release Terminal build with this tonight. 

Closes #32 🎉🎉🎉🎉🎉🎉🎉🎉🎉
Closes #12567

### CODE REVIEW

**Review by lhecker — APPROVED** [review]

**Comment by DHowett** [comment]
What if we resize down to the righthand edge of a color and then back to the left. Does it expand that color to the edge forever?

**Comment by zadjii-msft** [comment]
> What if we resize down to the righthand edge of a color and then back to the left. Does it expand that color to the edge forever?

Yea, that does. So that's the same as it was before:
gh-32-last-color-expands-000

That could probably be fixed by the proposed "'bookend' with default attrs at the end of the attrs from the pre-resize buffer" idea, which I haven't tested. In that case, resizing down to the white `w` above would work as expected, then resizing back out would have _default_ attrs.

**Comment by j4james** [comment]
I think I quite like it the way you have it now actually. This way if you've cleared the screen with a different background color, it should retain that color for the full width when you resize (or so I assume). But I don't think the default bookend idea would be bad either - both have their pros and cons.

It's also worth noting that Gnome Terminal seems to treat cells with non-default attributes as wrappable content (even when they're just spaces). But that behaves quite weirdly when you've cleared the screen with a non-default color. I'm not a fan of that approach myself, but I don't think it's unreasonable either.

**Comment by lhecker** [comment]
BTW regarding performance: This PR increases the CPU cost of `TextBuffer::Reflow` by about 18% if my 120x9001 buffer is full with enwik8. About half of the cost is due to `InsertCharacter` however, which is a bit silly anyways and can be improved by doing batch-insertions. I'm not concerned about this change from that POV.

**Review by DHowett — APPROVED** [review]

**Comment by DHowett** [comment]
@msftbot make sure @miniksa signs off

**Comment by DHowett** [comment]
> That could be optimized by just using the actual iterator.

How expensive would you estimate doing it this way would be? Code-time-wise?

**Comment by zadjii-msft** [comment]
> How expensive would you estimate doing it this way would be? Code-time-wise?

I could probably spend half a day sanity checking if that would take half a day or _many days_ and bail if it's too hard. After {the esb bug, the nav view one, the win11 backports, the ppt} in the queue.

File: src/buffer/out/textBuffer.cpp [hunk 1]
```diff
@@ -2265,6 +2267,48 @@ HRESULT TextBuffer::Reflow(TextBuffer& oldBuffer,
...
+        // remaining attributes.
+        // - if the old buffer is smaller than the new buffer, then just copy
+        //   what we have. as it was. The last attr in the row will be extended
+        //   to the end of the row in the new buffer.
+        // - if the old buffer is BIGGER, than we might have wrapped onto a new
+        //   line. Use the cursor's position's Y so that we know where the new
+        //   row is, and start writing st the cursor position. Again, the attr
+        //   in the last column of the old row will be extended to the end of the
+        //   row that the text was flowed onto.
+        //   - if we the text in the old buffer didn't actually fill the whole
```
Comment (miniksa) [inline src/buffer/out/textBuffer.cpp:2281]: "we the text"? like "we the people"?

File: src/buffer/out/textBuffer.cpp [hunk 2]
```diff
@@ -2265,6 +2267,48 @@ HRESULT TextBuffer::Reflow(TextBuffer& oldBuffer,
             CATCH_RETURN();
         }
 
+        // GH#32: Copy the attributes from the rest of the row into this new buffer.
+        // From where we are in the old buffer, to the end of the row, copy the
+        // remaining attributes.
+        // - if the old buffer is smaller than the new buffer, then just copy
```
Comment (miniksa) [inline src/buffer/out/textBuffer.cpp:2273]: Add a comment explaining "we already copied all text with the attribute color, but it's possible for someone to just put some color into the buffer to the right of that without any text. the buffer looks weird to the user when we resize and it starts losing those colors, so we need to copy them over too... as long as there is space."

Comment (miniksa) [reply src/buffer/out/textBuffer.cpp:2273]: aka some sort of "plain english" explanation without requiring someone to understand "attributes == colors"

File: src/buffer/out/textBuffer.cpp [hunk 3]
```diff
@@ -2265,6 +2267,48 @@ HRESULT TextBuffer::Reflow(TextBuffer& oldBuffer,
             CATCH_RETURN();
         }
 
+        // GH#32: Copy the attributes from the rest of the row into this new buffer.
+        // From where we are in the old buffer, to the end of the row, copy the
+        // remaining attributes.
+        // - if the old buffer is smaller than the new buffer, then just copy
+        //   what we have. as it was. The last attr in the row will be extended
+        //   to the end of the row in the new buffer.
+        // - if the old buffer is BIGGER, than we might have wrapped onto a new
```
Comment (miniksa) [inline src/buffer/out/textBuffer.cpp:2276]: specifically "WIDER" not bigger. Xold > Xnew. It could be "TALLER" and it doesn't apply.

File: src/buffer/out/textBuffer.cpp [hunk 4]
```diff
@@ -2265,6 +2267,48 @@ HRESULT TextBuffer::Reflow(TextBuffer& oldBuffer,
...
 
+        // GH#32: Copy the attributes from the rest of the row into this new buffer.
+        // From where we are in the old buffer, to the end of the row, copy the
+        // remaining attributes.
+        // - if the old buffer is smaller than the new buffer, then just copy
+        //   what we have. as it was. The last attr in the row will be extended
+        //   to the end of the row in the new buffer.
+        // - if the old buffer is BIGGER, than we might have wrapped onto a new
+        //   line. Use the cursor's position's Y so that we know where the new
+        //   row is, and start writing st the cursor position. Again, the attr
```
Comment (miniksa) [inline src/buffer/out/textBuffer.cpp:2278]: "st the cursor position?" at?

File: src/buffer/out/textBuffer.cpp [hunk 5]
```diff
@@ -2265,6 +2267,48 @@ HRESULT TextBuffer::Reflow(TextBuffer& oldBuffer,
...
+                    break;
+                }
+            }
+            CATCH_LOG(); // Not worth dying over.
+
+            newAttrColumn++;
+        }
+        // FOR DISCUSSION: Maybe also try to leave a
+        // default-attributes-to-the-end attr here, for the case where the line
+        // had color, then flowed onto the subsequent row.
```
Comment (miniksa) [inline src/buffer/out/textBuffer.cpp:2310]: This is obtuse. What exactly do you mean here?

File: src/buffer/out/textBuffer.cpp [hunk 6]
```diff
@@ -2241,7 +2242,8 @@ HRESULT TextBuffer::Reflow(TextBuffer& oldBuffer,
         // Loop through every character in the current row (up to
         // the "right" boundary, which is one past the final valid
         // character)
-        for (short iOldCol = 0; iOldCol < iRight; iOldCol++)
+        short iOldCol = 0;
+        for (; iOldCol < iRight; iOldCol++)
```
Comment (miniksa) [inline src/buffer/out/textBuffer.cpp:2246]: And we couldn't just set `iRight` to the std::min(oldBufferWidth, newBufferWidth) and let it dutifully copy the empty spaces with the color instead?

**Review by miniksa — CHANGES_REQUESTED** [review]
I like it but I have some questions outstanding.

File: src/buffer/out/textBuffer.cpp (hunk 6 above)
Comment (zadjii-msft) [reply src/buffer/out/textBuffer.cpp:2246]: .... maybe

Comment (zadjii-msft) [reply src/buffer/out/textBuffer.cpp:2300]: maybe not. If we do that, then we'll copy the blank spaces from the old buffer onto a new line the smaller new buffer........


but we could do 
```c++
std::min(oldBufferWidth, std::max(newBufferWidth, iRight))
```

copy all the chars up to the minimum of { the old buffer's width, ( the max of { the new buffers width or the old buffer's rightmost char } ) }. So if we resize narrower, the new buffer will be smaller. if the right 


* narrower, iRight > newBufferWidth: we want to copy all up to iRight  (or oldBufferWidth)
* narrower, iRight < newBufferWidth: we want to copy all up to newBufferWidth......................................




I couldn't get this right without copying extra spaces 🤷

**Comment by zadjii-msft** [comment]
I did the attr thing in `dev/migrie/b/32-attempt-3`, I wanna see the build fail here before I merge that branch into this PR

File: build/pipelines/templates/build-console-steps.yml [hunk 7]
```diff
@@ -110,6 +110,7 @@ steps:
      $(Build.SourcesDirectory)/bin/$(RationalizedBuildPlatform)/$(BuildConfiguration)/*.dll
      $(Build.SourcesDirectory)/bin/$(RationalizedBuildPlatform)/$(BuildConfiguration)/*.xml
      **/Microsoft.VCLibs.*.appx
+     **/*unit.test*.dll
```
Comment (zadjii-msft) [inline build/pipelines/templates/build-console-steps.yml:113]: Dustin and I discussed this: we weren't actually running any of 
```
UnitTests_TerminalCore\Terminal.Core.Unit.Tests.dll 
UnitTests_TerminalApp\Terminal.App.Unit.Tests.dll 
UnitTests_Remoting\Remoting.Unit.Tests.dll 
UnitTests_Control\Control.Unit.Tests.dll 
```

in CI, because they were never copied to the test output, because they were in subdirectories. Whoops!

Comment (zadjii-msft) [inline build/pipelines/templates/build-console-steps.yml:113]:
```suggestion
     **/*unit.test*.dll
     **/*unit.test*.manifest
```

File: src/buffer/out/textBuffer.cpp [hunk 8]
```diff
@@ -2306,9 +2311,9 @@ HRESULT TextBuffer::Reflow(TextBuffer& oldBuffer,
             try
             {
                 // TODO: MSFT: 19446208 - this should just use an iterator and the inserter...
-                const auto glyph = row.GetCharRow().GlyphAt(iOldCol);
-                const auto dbcsAttr = row.GetCharRow().DbcsAttrAt(iOldCol);
-                const auto textAttr = row.GetAttrRow().GetAttrByColumn(iOldCol);
+                const auto glyph = chars->Char();
```
Comment (DHowett) [inline src/buffer/out/textBuffer.cpp:2314]: Hopefully this doesn't cause any trouble with DBCS. It might be worth just smoke testing that -- fill a buffer with `U+30AB KATAKANA LETTER KA (カ)` and size it around to make sure it reflows properly.

File: src/buffer/out/textBuffer.cpp [hunk 9]
```diff
@@ -2352,7 +2405,7 @@ HRESULT TextBuffer::Reflow(TextBuffer& oldBuffer,
             // only because we ran out of space.
             if (iRight < cOldColsTotal && !row.WasWrapForced())
             {
-                if (iRight == cOldCursorPos.X && iOldRow == cOldCursorPos.Y)
+                if (!fFoundCursorPos && (iRight == cOldCursorPos.X && iOldRow == cOldCursorPos.Y))
```
Comment (DHowett) [inline src/buffer/out/textBuffer.cpp:2408]: Unrelated condition change -- scary? I guess as long as the reflow tests still pass...

File: src/buffer/out/textBuffer.cpp [hunk 10]
```diff
@@ -2403,6 +2456,34 @@ HRESULT TextBuffer::Reflow(TextBuffer& oldBuffer,
             }
         }
     }
+
+    // Finish copying buffer attributes to remaining rows below the last
+    // printable character. This is to fix the `color 2f` scenario, where you
+    // change the buffer colors then resize and everything below the past
```
Comment (DHowett) [inline src/buffer/out/textBuffer.cpp:2462]:
```suggestion
    // change the buffer colors then resize and everything below the last
```

Comment (DHowett) [reply src/buffer/out/textBuffer.cpp:2462]: this comment suggests we'll have to inbox this change to fix `COLOR`

File: src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp [hunk 11]
```diff
@@ -2964,7 +2964,7 @@ void ConptyRoundtripTests::ResizeInitializeBufferWithDefaultAttrs()
             else if (leaveTrailingChar && row == 3)
             {
                 auto iter = TestUtils::VerifyLineContains(tb, { 0, row }, L'#', greenAttrs, 1u);
-                TestUtils::VerifyLineContains(iter, L' ', (afterResize ? greenAttrs : actualDefaultAttrs), static_cast<size_t>(width - 1));
+                TestUtils::VerifyLineContains(iter, L' ', (actualDefaultAttrs), static_cast<size_t>(width - 1));
```
Comment (DHowett) [inline src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp:2967]: Confirming: this test was coded around the bad behavior, right?

File: src/host/screenInfo.cpp [hunk 12]
```diff
@@ -1472,7 +1472,7 @@ bool SCREEN_INFORMATION::IsMaximizedY() const
         coordCursorHeightDiff.Y = sCursorHeightInViewportAfter - sCursorHeightInViewportBefore;
         LOG_IF_FAILED(SetViewportOrigin(false, coordCursorHeightDiff, true));
 
-        _textBuffer->SetCurrentAttributes(oldPrimaryAttributes);
+        newTextBuffer->SetCurrentAttributes(oldPrimaryAttributes);
```
Comment (DHowett) [inline src/host/screenInfo.cpp:1475]: *HUH*. This seems like an unrelated but important bug fix

File: src/host/ut_host/ScreenBufferTests.cpp [hunk 13]
```diff
@@ -6269,3 +6276,239 @@ void ScreenBufferTests::TestWriteConsoleVTQuirkMode()
...
+    const til::point delta{ 15, 0 };
+    const til::point oldSize{ si.GetBufferSize().Dimensions() };
+    const til::point newSize{ oldSize + delta };
+    VERIFY_SUCCEEDED(si.ResizeWithReflow(newSize.to_win32_coord()));
+
+    // Buffer is now 95 wide. 85 A's that de-flowed onto the first row, where
+    // there are also 3 B's wrapped in spaces, and finally 5 trailing spaces.
+    Log::Comment(L"========== Checking the buffer state (after) ==========");
+    verifyBuffer(si.GetTextBuffer(), til::rect{ si.GetViewport().ToInclusive() }, false);
+}
```
Comment (DHowett) [inline src/host/ut_host/ScreenBufferTests.cpp:6514]: Do we need a test for the "copied the attributes after the last printable character" case?

**Review by DHowett — CHANGES_REQUESTED** [review]
I'll unmark after some questions :)

File: src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp (hunk 11 above)
Comment (zadjii-msft) [reply src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp:2967]: Yea.

File: src/buffer/out/textBuffer.cpp (hunk 9 above)
Comment (zadjii-msft) [reply src/buffer/out/textBuffer.cpp:2408]: It actually did end up being related. Because we're now also copying the trailing attrs, there was a case where we'd copy the attrs to the end of the row, but then set the new cursor position to the last column of the row the cursor was on. 


(it may not be relevant anymore, but it's not more wrong.)

File: src/host/ut_host/ScreenBufferTests.cpp (hunk 13 above)
Comment (zadjii-msft) [reply src/host/ut_host/ScreenBufferTests.cpp:6514]: meh, I could write one

File: src/buffer/out/textBuffer.cpp (hunk 8 above)
Comment (zadjii-msft) [reply src/buffer/out/textBuffer.cpp:2314]: gh-12637-dbcs

File: src/host/screenInfo.cpp (hunk 12 above)
Comment (zadjii-msft) [reply src/host/screenInfo.cpp:1475]: yea this was mentioned here: https://github.com/microsoft/terminal/issues/12567#issuecomment-1057980580 and in the previous reply

File: src/buffer/out/textBuffer.cpp (hunk 10 above)
Comment (zadjii-msft) [reply src/buffer/out/textBuffer.cpp:2462]: yea, we would.

**Comment by DHowett** [comment]
Test harness is crashing -- not sure if it is this PR's fault

    Error: TAEF: [HRESULT 0x800706BE] A failure occurred while running a test operation: 'SelectionInputTests::ClassSetup'. (The process hosting the test code was unexpectedly terminated with exit code 0x0000DEAD while invoking a test operation.)

File: src/host/ut_host/ScreenBufferTests.cpp (hunk 13 above)
Comment (DHowett) [reply src/host/ut_host/ScreenBufferTests.cpp:6514]: I'll sign, but I would like to see that ^

**Review by DHowett — APPROVED** [review]

**Comment by DHowett** [comment]
Test failure is not from this PR, and is addressed in #17274

File: src/buffer/out/textBuffer.cpp (hunk 6 above)
Comment (miniksa) [reply src/buffer/out/textBuffer.cpp]: Yeah that's fine. Thanks.

**Review by miniksa — APPROVED** [review]

**Comment by miniksa** [comment]
Fix the test, of course. But otherwise, I'm happy.

**Comment by DHowett** [comment]
Image from PR body


gh-32-did-I-do-it
