### PR TITLE
suppressApplicationTitle will suppress initial application title

### LINKED ISSUE #3743: suppressApplicationTitle doesn't seem to work in all cases
# Environment

```none
Windows build number: Version 10.0.18363.476
Windows Terminal version: Version: 0.7.3291.0
```

# Steps to reproduce

I created a profile like this:

```json
{
    "name": "VS2017 Developer CMD",
    "tabTitle": "VS2017 Developer CMD",
    "commandline": "cmd.exe /k \"C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/Common7/Tools/VsDevCmd.bat\"",
    "icon": "ms-appx:///ProfileIcons/{0caa0dad-35be-5f56-a8ff-afceeeaa6101}.png",
    "suppressApplicationTitle": true,
    "startingDirectory": "C:/Source"
},
```

# Expected behavior

The title of the tab should be `VS2017 Developer CMD`.

# Actual behavior

The title of the tab is `VS2017 Developer CMD - C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/Common7/Tools/VsDevCmd.bat`

Knipsel

### PR DESCRIPTION
**Pull request by cinnamon-msft**
## Summary of the Pull Request
Fixed bug where suppressApplicationTitle didn't suppress initial title from application

 
## PR Checklist
* [x] Closes #3743 
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Requires documentation to be updated
* [x] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

### CODE REVIEW

**Comment by cinnamon-msft** [comment]
> One last thing -- and this might actually fix the Azure Cloud Shell issue (!) -- is that you could set the _title to be _startingTitle if _suppressApplicationTitle is enabled in the Terminal::CreateFromSettings function. If you do that, it will get set to the correct value on creation!

Done!

File: src/cascadia/TerminalCore/Terminal.cpp [hunk 1]
```diff
@@ -87,6 +87,11 @@ void Terminal::CreateFromSettings(winrt::Microsoft::Terminal::Settings::ICoreSet
 {
     const COORD viewportSize{ Utils::ClampToShortMax(settings.InitialCols(), 1),
                               Utils::ClampToShortMax(settings.InitialRows(), 1) };
+
+    if (_suppressApplicationTitle)
+    {
+        _title = _startingTitle;
+    }
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalCore/Terminal.cpp]: er, this is not in the right place and will never trigger 😦 

It needs to be after line 98, `UpdateSettings`, because these values are never being set to anything otherwise..

Comment (carlos-zamora) [reply src/cascadia/TerminalCore/Terminal.cpp]: ...oops...I should not have merged that huh... Sorry!

Comment (DHowett-MSFT) [reply src/cascadia/TerminalCore/Terminal.cpp]: I shouldn't have Approved with pending "please write new code" comments :smile:
