### PR TITLE
Fix input corruption for high code points

### LINKED ISSUE #12977: Sending unicode character via KEYEVENTF_UNICODE/VK_PACKET in SendInput outputs the wrong characters
### Windows Terminal version

1.12.10982.0

### Windows build number

10.0.19043

### Other Software

Reproducible in:
- cmd.exe
- wsl ubuntu 20.04

powershell just displays `??   `, not sure which behaviour is more incorrect

Uses SendInput:
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-sendinput

### Steps to reproduce

Via SendInput, send the unicode character 🙁

E.g. in
https://github.com/jtroo/kanata/blob/master/src/oskbd/windows.rs#L168

### Expected Behavior

The correct unicode value gets typed in: 🙁

### Actual Behavior

The characters `翿翿` are typed in instead

### Additional info

When copy-pasting the unicode character, it's rendered correctly (in cmd/wsl). It's just not typed correctly via SendInput.

### PR DESCRIPTION
**Pull request by lhecker**
We must use 65535 as `MAX_PARAMETER_VALUE` in order for us to properly parse
win32-input-mode sequences, which transmit UTF-16 characters as parameters.

Closes #12977

## Validation Steps Performed
* Call `SendInput` with 🙁 (`L'\xD83D'`, `L'\xDE41'`)
* 🙁 appears on the input line ✅

### CODE REVIEW

File: src/terminal/parser/stateMachine.hpp [hunk 1]
```diff
@@ -21,11 +21,11 @@ Module Name:
...
 {
-    // The DEC STD 070 reference recommends supporting up to at least 16384 for
-    // parameter values, so 32767 should be more than enough. At most we might
-    // want to increase this to 65535, since that is what XTerm and VTE support,
-    // but for now 32767 is the safest limit for our existing code base.
-    constexpr VTInt MAX_PARAMETER_VALUE = 32767;
+    // The DEC STD 070 reference recommends supporting up to at least 16384
+    // for parameter values. 65535 is what XTerm and VTE support.
+    // GH#12977: We must use 65535 to properly parse win32-input-mode
+    // sequences, which transmit the UTF-16 character value as a parameter.
```
Comment (lhecker) [inline src/terminal/parser/stateMachine.hpp:27]: > [...] so 32767 should be more than enough.

Ah, the classic famous last words... "should be more than enough". lol
I'm a lot less concerned about this change since we mostly aren't using `short`s within the project anymore (for most parts).

**Review by DHowett — APPROVED** [review]

**Comment by DHowett** [comment]
@msftbot make sure @j4james signs off

**Review by zadjii-msft — APPROVED** [review]

**Review by j4james — APPROVED** [review]
As long as we don't go above the 65535 mark, I think we're good. I've done a brief scan of the code, and I can't see any obvious risky areas - the code has changed considerably from the days when parameter overflows were a real problem. I've also run a few test sequences with large parameter values to try and trigger a crash, and they all seemed OK (at least in the sense that nothing died).
