### PR TITLE
Redraw TSFInputControl when Terminal cursor updates

### LINKED ISSUE #4963: Character Overlap during Korean IME Composition
# Environment

**Windows version**

```
Microsoft Windows [Version 10.0.18362.720]
```

**Terminal version**

```
Version: 0.10.761.0
```

# Steps to reproduce

1. Open "Terminal" app
2. Type `"테스트"` (It means test in Korean)
3. You can probably see the letters overlapping

# Expected behavior

Rather than a long explanation, I'd rather attach the behavior of another operating system terminal.

macos_terminal

In the case of MacOS, the cursor is positioned under the letter being combined during the Korean language composition process, and there is no collision of letters.

linux_terminal

In the Ubuntu 18.04 X Window system environment, if the same operation is performed in the terminal, You can expect that Hangul characters are under the composition process in a cursor shape. And the Hangul characters do not overlap.

# Actual behavior

windows_terminal

In `Version: 0.10.761.0`, there is a problem that the Korean characters are overlapped as shown in the picture above.

If this problem is expected to be relatively minor by the core development team, please give a hint to the source code that is expected to be a problem so that I can give you a PR.

### PR DESCRIPTION
**Pull request by leonMSFT**
## Summary of the Pull Request
This PR will allow TSFInputControl to redraw its Canvas and TextBlock in response to when the Terminal cursor position updates. This will fix the issue where during Korean composition, the first symbol of the next composition will appear on top of the previous composed character. Since the Terminal Cursor updates a lot, I've added some checks to see if the TSFInputControl really needs to redraw. This will also decrease the number of actual redraws since we receive a bunch of `LayoutRequested` events when there's no difference between them.

## PR Checklist
* [x] Closes #4963
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [x] Tests added/passed

## Validation Steps Performed
Startup, teardown, CJK IME gibberish testing, making sure the IME block shows up in the right place.

### CODE REVIEW

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 1]
```diff
@@ -1774,6 +1777,31 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
...
+        if (_closing.load())
+        {
+            return;
+        }
+
+        auto weakThis{ get_weak() };
+
+        co_await winrt::resume_foreground(Dispatcher());
+
+        if (auto control{ weakThis.get() })
```
Comment (carlos-zamora) [inline src/cascadia/TerminalControl/TermControl.cpp]:
```suggestion
        if (weakThis.get())
```
Would something like this work? Since you don't actually use control?

Comment (carlos-zamora) [reply src/cascadia/TerminalControl/TermControl.cpp]: or even just `get_weak()` directly?

Comment (DHowett-MSFT) [reply src/cascadia/TerminalControl/TermControl.cpp]: whoa boy hold up

`get_weak` requires a strong `this` that's still alive

`weakThis.get()` _takes a weak pointer and makes it strong if possible_

you need to store it in a local variable, because the lifetime of that variable (controlled by its scope) determines how long the strong reference lives.
