### PR TITLE
Manually quit when the OS tells us to update

### LINKED ISSUE #13569: The MoAppHang thread
### Windows Terminal version

1.13.2205.23001

### Windows build number

10.0.19043.1766

### Other Software

_No response_

### Steps to reproduce

1. Open few cards in WindowsTerminal, including: cmd, powershell, ipython executed from cmd
2. Interact with those daily, but leave everything running

### Expected Behavior

WindowsTerminal executes smoothly.

### Actual Behavior

WindowsTerminal crashes. It's been crashing for months now. At various intervals. I couldn't determine any action to cause this. Today I switched off remote desktop and when logged in in few minutes, terminal was gone.
The only trace was in Event Viewer:
```Fault bucket 0, type 5
Event Name: MoAppHang
Response: Not available
Cab Id: 0

Problem signature:
P1: Microsoft.WindowsTerminal_1.13.11431.0_x64__8wekyb3d8bbwe
P2: praid:App
P3: 1.13.2205.23001
P4: 628bd6e7
P5: 0c21
P6: 2097152
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7AF0.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7B2F.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7B4D.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7BBC.tmp.txt
\\?\C:\Users\RGomulk\AppData\Local\Temp\WER7FA5.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppHang_Microsoft.Window_4bcfb2ab6ceed78368cad6844db4f7cf44eba4_3ff56f4b_cab_0c6eae25-ca99-44ed-ac03-564ef4cf04aa\minidump.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppHang_Microsoft.Window_4bcfb2ab6ceed78368cad6844db4f7cf44eba4_3ff56f4b_cab_0c6eae25-ca99-44ed-ac03-564ef4cf04aa\memory.hdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppHang_Microsoft.Window_4bcfb2ab6ceed78368cad6844db4f7cf44eba4_3ff56f4b_cab_0c6eae25-ca99-44ed-ac03-564ef4cf04aa\minidump.3f88.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppHang_Microsoft.Window_4bcfb2ab6ceed78368cad6844db4f7cf44eba4_3ff56f4b_cab_0c6eae25-ca99-44ed-ac03-564ef4cf04aa\minidump.5990.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppHang_Microsoft.Window_4bcfb2ab6ceed78368cad6844db4f7cf44eba4_3ff56f4b_cab_0c6eae25-ca99-44ed-ac03-564ef4cf04aa\minidump.3478.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppHang_Microsoft.Window_4bcfb2ab6ceed78368cad6844db4f7cf44eba4_3ff56f4b_cab_0c6eae25-ca99-44ed-ac03-564ef4cf04aa\minidump.46b0.mdmp

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppHang_Microsoft.Window_4bcfb2ab6ceed78368cad6844db4f7cf44eba4_3ff56f4b_0c6eae25-ca99-44ed-ac03-564ef4cf04aa

Analysis symbol: 
Rechecking for solution: 0
Report Id: 6ff345e4-bc39-4cf6-8a62-596843d57bd6
Report Status: 268435456
Hashed bucket: 86e421f1a50f55fde4a62f6775b8f8e5
Cab Guid: 0
```

Before which I got:
```
Fault bucket , type 0
Event Name: MoAppHang
Response: Not available
Cab Id: 0

Problem signature:
P1: Microsoft.WindowsTerminal_1.13.11431.0_x64__8wekyb3d8bbwe
P2: praid:App
P3: 1.13.2205.23001
P4: 628bd6e7
P5: 0c21
P6: 2097152
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7AF0.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7B2F.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7B4D.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7BBC.tmp.txt
\\?\C:\Users\RGomulk\AppData\Local\Temp\WER7FA5.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppHang_Microsoft.Window_4bcfb2ab6ceed78368cad6844db4f7cf44eba4_3ff56f4b_cab_0c6eae25-ca99-44ed-ac03-564ef4cf04aa\minidump.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppHang_Microsoft.Window_4bcfb2ab6ceed78368cad6844db4f7cf44eba4_3ff56f4b_cab_0c6eae25-ca99-44ed-ac03-564ef4cf04aa\memory.hdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppHang_Microsoft.Window_4bcfb2ab6ceed78368cad6844db4f7cf44eba4_3ff56f4b_cab_0c6eae25-ca99-44ed-ac03-564ef4cf04aa\minidump.3f88.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppHang_Microsoft.Window_4bcfb2ab6ceed78368cad6844db4f7cf44eba4_3ff56f4b_cab_0c6eae25-ca99-44ed-ac03-564ef4cf04aa\minidump.5990.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppHang_Microsoft.Window_4bcfb2ab6ceed78368cad6844db4f7cf44eba4_3ff56f4b_cab_0c6eae25-ca99-44ed-ac03-564ef4cf04aa\minidump.3478.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppHang_Microsoft.Window_4bcfb2ab6ceed78368cad6844db4f7cf44eba4_3ff56f4b_cab_0c6eae25-ca99-44ed-ac03-564ef4cf04aa\minidump.46b0.mdmp

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppHang_Microsoft.Window_4bcfb2ab6ceed78368cad6844db4f7cf44eba4_3ff56f4b_cab_0c6eae25-ca99-44ed-ac03-564ef4cf04aa

Analysis symbol: 
Rechecking for solution: 0
Report Id: 6ff345e4-bc39-4cf6-8a62-596843d57bd6
Report Status: 4
Hashed bucket: 
Cab Guid: 0
```

and
```
The program WindowsTerminal.exe version 1.13.2205.23001 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 2ff4
 Start Time: 01d8910361242def
 Termination Time: 4294967295
 Application Path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.13.11431.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
 Report Id: 6ff345e4-bc39-4cf6-8a62-596843d57bd6
 Faulting package full name: Microsoft.WindowsTerminal_1.13.11431.0_x64__8wekyb3d8bbwe
 Faulting package-relative application ID: App
 Hang type: Quiesce
```

I have both windows terminal and windows terminal preview installed. I'm not sure which exhibited the behaviour, but if remember correctly, both were crashing similarly.

### PR DESCRIPTION
**Pull request by zadjii-msft**
Refer to https://docs.microsoft.com/en-us/windows/win32/rstmgr/guidelines-for-applications

The OS will send us a WM_QUERYENDSESSION when it's preparing an
update for our app. It will then send us a WM_ENDSESSION, which gives
us a small timeout (~30s) to actually shut down gracefully. After
that timeout, it will send us a WM_CLOSE. If we still don't close
after the WM_CLOSE, it'll force-kill us (causing a crash which will be
bucketed to moapphang).

We will manually start a quit, so that we can persist the state. If we refuse to
gracefully shut down, the OS will crash us to focefully terminate us. We
choose to quit here, rather than just close, to skip over any warning dialogs
(e.g. "Are you sure you want to close all tabs?") which might prevent a WM_CLOSE
from cleanly closing the window.

This will cause a appHost._RequestQuitAll, which will notify the
monarch to collect up all the window state and save it.

This "crash" caused by the OS force killing us constitutes 80% of all our crashes. 80%. See MSFT:38947155, MSFT:38877540, MSFT:21058878, MSFT:31710054, MSFT:39764652, MSFT:26883776.

Closes #13569

It also fixes the issue where if you've got Terminal Dev running (outside VS), and you try to Deploy, you have to make sure to close the "Are you sure you want to close all tabs" dialog before the deployment can proceed. A deploy in VS sends the same sequence of messages as a real update.

### CODE REVIEW

File: src/cascadia/WindowsTerminal/IslandWindow.cpp [hunk 1]
```diff
@@ -658,6 +658,60 @@ long IslandWindow::_calculateTotalSize(const bool isWidth, const long clientSize
...
+        // The OS will send us a WM_QUERYENDSESSION when it's preparing an
+        // update for our app. It will then send us a WM_ENDSESSION, which gives
+        // us a small timeout (~30s) to actually shut down gracefully. After
+        // that timeout, it will send us a WM_CLOSE. If we still don't close
+        // after the WM_CLOSE, it'll force-kill us (causing a crash which will be
+        // bucketed to MoAppHang).
+        if (WI_IsFlagSet(lparam, ENDSESSION_CLOSEAPP))
+        {
+            // Log that we were told to shutdown by the OS.
+            //
```
Comment (carlos-zamora) [inline src/cascadia/WindowsTerminal/IslandWindow.cpp:677]: wait... is there supposed to be a `TraceLoggingWrite()` in this branch?

**Review by carlos-zamora — APPROVED** [review]

File: src/cascadia/WindowsTerminal/IslandWindow.cpp [hunk 2]
```diff
@@ -658,6 +658,56 @@ long IslandWindow::_calculateTotalSize(const bool isWidth, const long clientSize
...
+        // start it here.
+        //
+        // If (in the future) we need to prevent logoff, we can return false here.
+
+        TraceLoggingWrite(
+            g_hWindowsTerminalProvider,
+            "QueryEndSession",
+            TraceLoggingDescription("Emitted when the OS has begun the process of updating the Terminal"),
+            TraceLoggingLevel(WINEVENT_LEVEL_VERBOSE),
+            TraceLoggingKeyword(TIL_KEYWORD_TRACE));
```
Comment (lhecker) [inline src/cascadia/WindowsTerminal/IslandWindow.cpp:685]: Isn't this event redundant with the one for `WM_ENDSESSION`? If we return `true` here, then almost always we should also receive a `WM_ENDSESSION` event anyways right?
In that case you could remove this entire `case` because the `DefWindowProc` already returns `true`.

Comment (zadjii-msft) [reply src/cascadia/WindowsTerminal/IslandWindow.cpp:685]: Meh, yea probably. I was thinking originally that we would shove some logic in there, but turns out we really don't need it.

**Review by lhecker — APPROVED** [review]

**Comment by carlos-zamora** [comment]
Do we want to service this?

CC @DHowett

**Comment by zadjii-msft** [comment]
> Do we want to service this?

Talked to Dustin about this earlier, and the suggestion was _meh_. It's a large number of raw crashes, but ultimately it's one per user. Probably fine to just wait till it bubbles up the normal way.
