### PR TITLE
Clamp the terminal buffer to `SHRT_MAX` on resize

### LINKED ISSUE #2815: Bug Report: if historySize >= 32728 a maximize doesn't redraw the terminal
# Environment

```none
Windows build number: 10.0.18980.1
Windows Terminal version (if applicable): 0.4.2382.0

Any other software?
```

# Steps to reproduce

1. Set historySize of a profile to 32728 or bigger.
2. Open a tab for that profile.
3. Run commands so that there is a bunch of scroll space (running `nano` on Ubuntu is easier).
4. Maximize the window.

# Expected behavior

The terminal should redraw itself to occupy all the available space.

# Actual behavior

The terminal keeps using the previously available space, not occupying the extra one. Some screenshots:

1. After maximizing on Ubuntu:
maximized on ubuntu

2. After maximizing on cmd:
maximized on cmd
_(Note the last `dir` output kept going but it was cut midway)_

# Other relevant information

A manual resize of the window does correctly trigger a redraw on Ubuntu. Not on cmd, which just keeps using the window space it had when the tab was opened.

### LINKED ISSUE #4972: Resizing window causes app to crash in latest release (v0.10.761.0)
Updated to the latest preview release today (v0.10.761.0)

Immediately noticed that any attempts to resize the window either via mouse drag or keyboard shortcut causes the Terminal app to become unresponsive and crash. 

Same behavior for both normal and admin/elevated launches of Terminal app. 

# Environment
```none
Windows build number: 10.0.19582.0
Windows Terminal version (if applicable): 0.10.761.0

Any other software? No
```

# Steps to reproduce
Either:
- Use mouse to resize the Terminal app window
- Use keyboard shortcuts to maximize or split screen the window (via Win+Up/Right/Left)

# Expected behavior
Normal resizing which broke for me since latest build (v0.9 was resizing fine)

# Actual behavior
Application becomes unresponsive and crashes

### PR DESCRIPTION
**Pull request by zadjii-msft**
## Summary of the Pull Request

This is 100% on me. Even after mucking around in this function for the last 3
months, I missed that there was a single addition where we weren't doing a
clamped addition. This would lead to us creating a buffer with negative height,
and all sorts of badness.

Clamping this addition was enough to fix the bug.

## PR Checklist
* [x] Closes #2815
* [x] Closes #4972
* [x] I work here
* [x] Tests added/passed
* [n/a] Requires documentation to be updated

## Validation Steps Performed
* ran tests
* Created a profile with `"historySize" : 32728`, then filled the viewport with
  text, then maximized, and saw that the viewport indeed did resize to the new
  size of the window.

### CODE REVIEW

File: src/cascadia/TerminalCore/Terminal.cpp [hunk 1]
```diff
@@ -173,11 +173,12 @@ void Terminal::UpdateSettings(winrt::Microsoft::Terminal::Settings::ICoreSetting
     {
         return S_FALSE;
     }
-    const auto dx = viewportSize.X - oldDimensions.X;
+
+    const auto dx = ::base::saturated_cast<short>(viewportSize.X - oldDimensions.X);
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalCore/Terminal.cpp]: is casting after the fact acceptable or should we be using ClampedAdd/ClampedSub?

Comment (zadjii-msft) [reply src/cascadia/TerminalCore/Terminal.cpp]: @miniksa I actually don't know the answer to this. The way I'm doing it seems fine, right? It'll auto promote the result to an `int`, then cast down to a `short`?

Comment (zadjii-msft) [reply src/cascadia/TerminalCore/Terminal.cpp]: From chat, `::base::ClampedSub(viewportSize.X, oldDimensions.X)` is the way to do this correctly
