### PR TITLE
Don't scroll vertically on horizontal scroll motions

### LINKED ISSUE #10329: horizontal scroll gesture on trackpad scrolls viewport vertically
### Windows Terminal version (or Windows build number)

1.9.1523.0

### Other Software

_No response_

### Steps to reproduce

with some scroll back on the buffer do a horizontal 2-finger swipe on the trackpad

### Expected Behavior

do nothing

### Actual Behavior

vertical scroll is performed

very annoying if your vertical scroll gesture looks like this:
image

### PR DESCRIPTION
**Pull request by zadjii-msft**
## Summary of the Pull Request

Pretty straightforward. Check if the scroll event is a horizontal movement. If it is, ignore it. We don't have a horizontal scrollbar.

## References
* obviously, revisit this if we ever do #1860 

## PR Checklist
* [x] Closes #10329
* [x] I work here
* [ ] Tests added/passed
* [n/a] Requires documentation to be updated

## Validation Steps Performed
* scrolled ↑/↓ with slaptop trackpad: terminal scrolls.
* scrolled ←/→ with slaptop trackpad: terminal doesn't scroll.
* Scrolling _slightly more vertically than horizontally_ still scrolls.
* Scrolling _slightly more horizontally than vertically_ doesn't scroll.

### CODE REVIEW

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 1]
```diff
@@ -1209,7 +1209,13 @@ namespace winrt::Microsoft::Terminal::Control::implementation
         _RestorePointerCursorHandlers(*this, nullptr);
 
         const auto point = args.GetCurrentPoint(*this);
-
+        // GH#10329 - we don't need to handle horizontal scrolls. Only vertical ones.
+        // So filter out the horizontal ones.
+        if (point.Properties().IsHorizontalMouseWheel())
```
Comment (DHowett) [inline src/cascadia/TerminalControl/TermControl.cpp:1214]: thatwaseasy.gif

**Review by DHowett — APPROVED** [review]

**Review by carlos-zamora — APPROVED** [review]

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 1 above)
Comment (lhecker) [reply src/cascadia/TerminalControl/TermControl.cpp:1214]: Should it call `args.Handled()` though?

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 2]
```diff
@@ -1209,7 +1209,13 @@ namespace winrt::Microsoft::Terminal::Control::implementation
...
         const auto point = args.GetCurrentPoint(*this);
-
+        // GH#10329 - we don't need to handle horizontal scrolls. Only vertical ones.
+        // So filter out the horizontal ones.
+        if (point.Properties().IsHorizontalMouseWheel())
+        {
+            return;
+        }
+        
         auto result = _interactivity.MouseWheel(ControlKeyStates{ args.KeyModifiers() },
```
Comment (carlos-zamora) [inline src/cascadia/TerminalControl/TermControl.cpp:1219]: actually, quick question: it looks like this'll suppress the `_core->SendMouseEvent` in ControlInteractivity, is that ok? We don't want the VT mouse mode data anymore?

Comment (DHowett) [reply src/cascadia/TerminalControl/TermControl.cpp:1219]: not for horizontal wheel we don't.

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 1 above)
Comment (DHowett) [reply src/cascadia/TerminalControl/TermControl.cpp:1214]: I suspect that since we are not handling it, we should not mark it handled. Somebody else might want it :smile:
