### PR TITLE
Snap to character grid when resizing window

### LINKED ISSUE #2277: BUG: Crash on window resize
# Environment

```none
Windows build number: 
Microsoft Windows [Version 10.0.18362.267]

Windows Terminal version (if applicable):
Windows Terminal (Preview)
Version: 0.3.2142.0

Any other software?
None
```

# Steps to reproduce

Start terminal.  Resize.  I pretty consistently get a crash when I get to about the point of the single tab going to zero width.

Start terminal.  Add multiple tabs.  Resize.  I get crashes when the third tab starts to slide under the new tab UI.

Sometimes you can shrink all the way down and back.  Sometimes you can shrink all the way down, and it'll crash as it is being expanded.

# Expected behavior

Window resizes without crash

# Actual behavior

Here's one of the entries from my event log.

```none
Faulting application name: WindowsTerminal.exe, version: 1.0.1908.2002, time stamp: 0x5d448424
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.18362.267, time stamp: 0x3e916038
Exception code: 0xc000027b
Fault offset: 0x00000000007126f0
Faulting process id: 0x2fa8
Faulting application start time: 0x01d54c269fed96bb
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.3.2142.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: 985f1c17-14dc-45a2-9bf2-2e663574efa9
Faulting package full name: Microsoft.WindowsTerminal_0.3.2142.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

Here's the feedback hub entry, which should have dx attached to it:

https://aka.ms/AA5roli

### LINKED ISSUE #2834: Snap to character grid when resizing window
# Description of the new feature/enhancement

Snap to character grid when resizing window, like many terminals do (gnome-based, git terminal etc.). Questions:
- Make it a setting?
- If so. enable by default? (I'd say yes)

### PR DESCRIPTION
**Pull request by mcpiroman**
When user resizes window, snap the size to align with the character grid (like e.g. putty, mintty and most unix terminals). Properly resolves arbitrary pane configuration (even with different font sizes and padding) trying to align each pane as close as possible.

It also fixes terminal minimum size enforcement which was not quite well handled, especially with multiple panes.

This PR does not however try to keep the terminals aligned at other user actions (e.g. font change or pane split). That is to be tracked by some other activity.

term_snapping

## References
#3060 introduces some differences in size calculations by moving from separator to borders, but it should be easy to adopt to that.

## PR Checklist
* [X] Closes #2834, Closes #2277 
* [X] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed - do we have UI tests yet?
* [ ] Requires documentation to be updated
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Detailed Description of the Pull Request / Additional comments

Snapping is resolved in the pane tree, recursively, so it (hopefully) works for any possible layout.

Along the way I had to clean up some things as so to make the resulting code not so cumbersome:
1. `Pane.cpp`: Replaced `_firstPercent` and `_secondPercent` with single `_desiredSplitPosition` to reduce invariants - these had to be kept in sync so their sum always gives 1 (and were not really a percent). The `desired` part refers to fact that since panes are aligned, there is usually some deviation from that ratio.
2. `Pane.cpp`: Fixed `_GetMinSize()` - it was improperly accounting for split direction
3. `TerminalControl`: Made dedicated member for padding instead of reading it from a control itself. This is because the winrt property functions turned out to be slow and this algorithm needs to access it many times. I also cached scrollbar width for the same reason.
4. `AppHost`: Moved window to client size resolution to virtual method, where `IslandWinow` and `NonClientIslandWindow` have their own implementations (as opposite to pointer casting).

One problem with current implementation is I had to make a long call chain from the window that requests snapping to the (root) pane that implements it:
`IslandWindow` -> `AppHost`'s callback -> `App` -> `TerminalPage` -> `Tab` -> `Pane`
Idk if this can be done better.

## Validation Steps Performed
Spam split pane buttons, randomly change font sizes with ctrl+mouse wheel and drag the window back and forth.

### CODE REVIEW

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 1]
```diff
@@ -771,8 +775,8 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
                 const auto cursorPosition = point.Position();
                 _SetEndSelectionPointAtCursor(cursorPosition);
 
-                const double cursorBelowBottomDist = cursorPosition.Y - _swapChainPanel.Margin().Top - _swapChainPanel.ActualHeight();
-                const double cursorAboveTopDist = -1 * cursorPosition.Y + _swapChainPanel.Margin().Top;
+                const double cursorBelowBottomDist = cursorPosition.Y - _padding.Top - _swapChainPanel.ActualHeight();
```
Comment (carlos-zamora) [inline src/cascadia/TerminalControl/TermControl.cpp]: Is there ever a time that `_padding != _swapChainPanel.Margin()`?

File: src/cascadia/TerminalApp/Pane.cpp [hunk 2]
```diff
@@ -308,6 +294,14 @@ void Pane::_ControlClosedHandler()
     }
 }
 
+void Pane::_FontSizeChangedHandler(const int fontWidth, const int fontHeight, const bool isInitialChange)
```
Comment (carlos-zamora) [inline src/cascadia/TerminalApp/Pane.cpp]: nit: comment plz

File: src/cascadia/TerminalApp/Pane.h [hunk 3]
```diff
@@ -51,27 +51,31 @@ class Pane : public std::enable_shared_from_this<Pane>
...
-    std::optional<float> _firstPercent{ std::nullopt };
-    std::optional<float> _secondPercent{ std::nullopt };
+    float _desiredSplitPosition;
 
     bool _lastFocused{ false };
     std::optional<GUID> _profile{ std::nullopt };
     winrt::event_token _connectionClosedToken{ 0 };
     winrt::event_token _firstClosedToken{ 0 };
     winrt::event_token _secondClosedToken{ 0 };
+    winrt::event_token _fonstSizeChangedToken{ 0 };
```
Comment (carlos-zamora) [inline src/cascadia/TerminalApp/Pane.h]:
```suggestion
    winrt::event_token _fontSizeChangedToken{ 0 };
```

File: src/cascadia/TerminalApp/Pane.h [hunk 4]
```diff
@@ -33,7 +33,7 @@ class Pane : public std::enable_shared_from_this<Pane>
         Horizontal = 2
     };
 
-    Pane(const GUID& profile, const winrt::Microsoft::Terminal::TerminalControl::TermControl& control, const bool lastFocused = false);
+    Pane(const GUID& profile, const winrt::Microsoft::Terminal::TerminalControl::TermControl& control, Pane* const rootPane, const bool lastFocused = false);
```
Comment (carlos-zamora) [inline src/cascadia/TerminalApp/Pane.h]:
```suggestion
    Pane(const GUID& profile, const winrt::Microsoft::Terminal::TerminalControl::TermControl& control, Pane* const rootPane = nullptr, const bool lastFocused = false);
```
Thoughts?

**Comment by DHowett-MSFT** [comment]
(I am very excited about this and just need some time to give it a review.)

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 1 above)
Comment (mcpiroman) [reply src/cascadia/TerminalControl/TermControl.cpp]: No, there shouldn't be.

File: src/cascadia/TerminalApp/Pane.h (hunk 4 above)
Comment (mcpiroman) [reply src/cascadia/TerminalApp/Pane.h]: So it's rather a special case when create a root pane that we pass here a null (because we can't pass pointer to itself in constructor). Otherwise we should always pass the valid pointer, so that's we I left it not optional.

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 5]
```diff
@@ -179,20 +181,20 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
         _BackgroundColorChanged(bg);
 
         // Apply padding as swapChainPanel's margin
-        auto newMargin = _ParseThicknessFromPadding(_settings.Padding());
-        auto existingMargin = _swapChainPanel.Margin();
```
[the remark this answers is not in the document]
Comment (mcpiroman) [reply src/cascadia/TerminalControl/TermControl.cpp]: Yup, i got the lines swapped.

**Comment by oising** [comment]
Nice! Definitely needed.

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 1 above)
Comment (zadjii-msft) [reply src/cascadia/TerminalControl/TermControl.cpp]: If there's not, then I think I'd prefer if we kept it in `_swapChainPanel.Margin()`. We've been burned before by keeping "redundant" data around that ends up getting out of sync.

File: src/cascadia/TerminalApp/Pane.cpp [hunk 6]
```diff
@@ -308,6 +294,26 @@ void Pane::_ControlClosedHandler()
...
+//   On the latter event, we tell the root pane to resize itself so that its
+//   descendants (including ourself) can properly snap to character grids. In future,
+//   we may also want to do that on regular font changes.
+// Arguments:
+// - fontWidth - new font width in pixels
+// - fontHeight - new font height in pixels
+// - isInitialChange - whether terminal just got its proper font size.
+// Return Value:
+// - <none>
+void Pane::_FontSizeChangedHandler(const int /* fontWidth */, const int /* fontHeight */, const bool isInitialChange)
```
Comment (zadjii-msft) [inline src/cascadia/TerminalApp/Pane.cpp]: It looks like this is the only place where `_rootPane` is used - is there another way we can bubble this information up somehow? I'd prefer if we avoided adding a pointer to the root if at all possible. That feels like breaking the abstraction of the tree, you know?

Comment (mcpiroman) [reply src/cascadia/TerminalApp/Pane.cpp]: Of course I could store pointer to parent instead of root and bubble the information up to the root, but that then honestly feels like extra complexity (ep. with keeping track of parent) without practical benefit. Please decide though.

Comment (zadjii-msft) [reply src/cascadia/TerminalApp/Pane.cpp]: It might be terribly annoying, but would it be possible to do this as an event like `ConnectionClosed`, and have it bubble up to the Tab, which then calls `ResizeContent` on the root pane? I just really don't love the idea of having a pointer to somewhere higher on the tree.

Or __even better__, we could just have the `Tab` register a handler for each child control's `FontSizeChanged` event. Each `Split` goes through the Tab anyways, so the `Tab` has a chance to add event handlers then, and `Tab` is the layer that owns the `_root` Pane anyways.

File: src/cascadia/TerminalApp/Pane.cpp [hunk 7]
```diff
@@ -914,25 +924,253 @@ void Pane::_Split(SplitState splitType, const GUID& profile, const TermControl&
...
+
+// Method Description:
+// - Adjusts given dimension (width or height) so that all descendant terminals
+//   align with their character grids as close as possible. Also makes sure to
+//   fit in minimal sizes of the panes.
+// Arguments:
+// - widthOrHeight: if true operates on width, otherwise on height
+// - dimension: a dimension (width or height) to be snapped
+// Return Value:
+// - pair of floats, where first value is the size snapped downward (not greater then
```
[the remark this answers is not in the document]
Comment (mcpiroman) [reply src/cascadia/TerminalApp/Pane.cpp]: And that's why languages need to have named tuples. And sadly, they usually don't.

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 8]
```diff
@@ -1632,17 +1649,43 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
...
 
+    // Method Description:
+    // - Adjusts given dimension (width or height) so that it aligns to the character grid.
+    //   The snap is always downward.
+    // Arguments:
+    // - widthOrHeight: if true operates on width, otherwise on height
+    // - dimension: a dimension (width or height) to be snapped
+    // Return Value:
+    // - A dimension that would be aligned to the character grid.
+    float TermControl::SnapDimensionToGrid(const bool widthOrHeight, const float dimension) const
```
[the remark this answers is not in the document]
Comment (mcpiroman) [reply src/cascadia/TerminalControl/TermControl.cpp]: If so, this should be renamed everywhere (so in a lot of places). I went with `widthOrHeight` because I find it more readable. With some thing like `isWidth`, it is not so apparent what it means if it's false. Usually not-width means height, but not always.

**Comment by mcpiroman** [comment]
About performance:

Form my measurements it appears that the introduced layouting code takes usually about 1% CPU time of whole resize operation (and the thing to note is that it runs on every mouse move event, while the actual terminal resizes runs only at the 'snaps`). On the other hand the terminal resize takes way to long.

I've tried to make this O(1) instead of the current O(n) (where n is number of cells fitting given dimension) but failed to do so ~(and spent far too much time thinking about this. That actually gotta be on some math competition!)~. I'm fairly convicted that the current, iterative implementation is the a good compromise between optimization and sanity.

As of caching: the XAML prop reads really did slow down the algorithm by few times, even on release config. But since I measured it the algorithm changed quite drastically and now these properties are being read many less times (in favor of character size, which does not go through xaml) + I just discovered I can cache the padding locally instead of reading it for each edge. This makes it far less buttlenecking and in fact rather irrelevant so I can safely undo the cacheing.

File: src/cascadia/TerminalApp/Tab.h [hunk 9]
```diff
@@ -23,6 +23,8 @@ class Tab
     bool CanSplitPane(Pane::SplitState splitType);
     void SplitPane(Pane::SplitState splitType, const GUID& profile, winrt::Microsoft::Terminal::TerminalControl::TermControl& control);
 
+    float SnapDimension(const bool widthOrHeight, const float dimension) const;
```
[the remark this answers is not in the document]
Comment (mcpiroman) [reply src/cascadia/TerminalApp/Tab.h]: So I should rename this everywhere, right? Also I'm more for `GetSnappedDimension`, or maybe `CalcSnappedDimension` to indicate that it's actually doing some non-trivial computation.

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 10]
```diff
@@ -1211,15 +1220,23 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
...
-        // TODO: MSFT:20895307 If the font doesn't exist, this doesn't
-        //      actually fail. We need a way to gracefully fallback.
-        _renderer->TriggerFontChange(newDpi, _desiredFont, _actualFont);
+            // TODO: MSFT:20895307 If the font doesn't exist, this doesn't
+            //      actually fail. We need a way to gracefully fallback.
+            _renderer->TriggerFontChange(newDpi, _desiredFont, _actualFont);
+        }
+
+        const auto fontSize = _actualFont.GetSize();
+        _fontSizeChangedHandlers(fontSize.X, fontSize.Y, initialUpdate);
```
[the remark this answers is not in the document]
Comment (mcpiroman) [reply src/cascadia/TerminalControl/TermControl.cpp]: Yes, I did this because in future we may re-layout panes even on other events, like font/zoom change and so we don't make to much diff (see issue #xxx I haven't filled one yet). But it might be too future of a future to bother now.

File: src/cascadia/TerminalControl/TermControl.idl [hunk 11]
```diff
@@ -4,6 +4,7 @@
 namespace Microsoft.Terminal.TerminalControl
 {
     delegate void TitleChangedEventArgs(String newTitle);
+    delegate void FontSizeChangedEventArgs(Int32 width, Int32 height, Boolean isInitialChange);
```
[the remark this answers is not in the document]
Comment (mcpiroman) [reply src/cascadia/TerminalControl/TermControl.idl]: Ah yes, I could. But should it be floats or ints? Font size is actually integer but e.g. `TermControl::CharacterDimensions` returns `Windows.Foundation.Size`, so floats.

File: src/cascadia/TerminalControl/TermControl.idl [hunk 12]
```diff
@@ -40,6 +42,7 @@ namespace Microsoft.Terminal.TerminalControl
         Boolean ShouldCloseOnExit { get; };
         Windows.Foundation.Size CharacterDimensions { get; };
         Windows.Foundation.Size MinimumSize { get; };
+        Single SnapDimensionToGrid(Boolean widthOrHeight, Single dimension);
```
[the remark this answers is not in the document]
Comment (mcpiroman) [reply src/cascadia/TerminalControl/TermControl.idl]: Because in `Pane` we operate on floats. But really its only matter of where the conversion form doubles to floats is done, so it probably has sense to do it in `Pane` and have doubles in this interface. On the other hand this would be inconsistent with previous two properties of type `Windows.Foundation.Size` which has float values.

File: src/cascadia/TerminalApp/Pane.h [hunk 13]
```diff
@@ -130,4 +140,24 @@ class Pane : public std::enable_shared_from_this<Pane>
...
+
+    // Helper structure that builds a (roughly) binary tree corresponding
+    // to the pane tree. Used for layouting panes with snapped sizes.
+    struct LayoutSizeNode
+    {
+        float size;
+        bool isMinimumSize;
+        std::unique_ptr<LayoutSizeNode> firstChild;
+        std::unique_ptr<LayoutSizeNode> secondChild;
+        std::unique_ptr<LayoutSizeNode> nextFirstChild;
```
[the remark this answers is not in the document]
Comment (mcpiroman) [reply src/cascadia/TerminalApp/Pane.h]: I think that's mostly correct.
`firstChild` and `secondChild` are the `current`, snapped sizes (`current` in the progression of layouting algorithm). I'm not sure if "next smaller snap size" does describe that correctly.

`next*Child` are the next (higher) possible snapped sizes. In simplest case they represent the `*Child` with one more character. They serve mostly like a cache - we might calculate them each time `firstChild` and `secondChild` but this would be wasteful because  on each `AdvanceSnappedDimension` call we have to know them both but we choose only one. 

This also means that the bulk on 'advancing' say first child becomes `*firstChild = *nextFirstChild`, assuming `nextFirstChild` is already calculated (and then of course we have to adjust `nextFirstChild` itself).

File: src/cascadia/TerminalApp/Pane.cpp [hunk 14]
```diff
@@ -914,25 +924,253 @@ void Pane::_Split(SplitState splitType, const GUID& profile, const TermControl&
...
+            const auto secondSize = sizeNode.secondChild->size;
+
+            // Because we relay on equality check these calculations have to be
+            // immune to floating point errors.
+            const auto deviation1 = nextFirstSize - (nextFirstSize + secondSize) * _desiredSplitPosition;
+            const auto deviation2 = -1 * (firstSize - (firstSize + nextSecondSize) * _desiredSplitPosition);
+            advanceFirst = deviation1 <= deviation2;
+        }
+
+        if (advanceFirst)
```
[the remark this answers is not in the document]
Comment (mcpiroman) [reply src/cascadia/TerminalApp/Pane.cpp]: Each `_AdvanceSnappedDimension` call advances excellently one of the pane's children (unless it's a leaf) and here it decides which one will it be. And according to my convention `advanceFirst` should really be `advanceFirstOrSecond`.

If your talking about the general idea, then admittedly it's not the very simplest thing in the world. Do you think this would benefit from some further explanation?

File: src/cascadia/TerminalApp/Pane.h (hunk 13 above)
[the remark this answers is not in the document]
Comment (zadjii-msft) [reply src/cascadia/TerminalApp/Pane.h]: Okay, I think this should probably be added as a comment, because I certainly didn't feel like I understood that on my first read-through of the code.

File: src/cascadia/TerminalApp/TerminalPage.cpp [hunk 15]
```diff
@@ -1058,6 +1058,14 @@ namespace winrt::TerminalApp::implementation
         }
     }
 
+    // Method Description:
+    // - See Pane::SnapDimension
+    float TerminalPage::SnapDimension(const bool widthOrHeight, const float dimension) const
+    {
+        const auto focusedTabIndex = _GetFocusedTabIndex();
+        return _tabs[focusedTabIndex]->SnapDimension(widthOrHeight, dimension);
```
[the remark this answers is not in the document]
Comment (mcpiroman) [reply src/cascadia/TerminalApp/TerminalPage.cpp]: Rather than having method named `SnapDimension` that sometimes doesn't do its job, it might be cleaner just not to call it at all in `IslandWindow`.

Secondly, that would only disable the 'window' snapping but not 'pane' snapping (so if one splits terminal vertically and changes the window's width, the left pane will still snap, although the whole window would go smoothly). Should it be this way? Maybe make this 3-way setting that would also cover that (like `fullSnap`, `innerSnap`, `noSnap`).

File: src/cascadia/WindowsTerminal/IslandWindow.cpp [hunk 16]
```diff
@@ -285,6 +361,27 @@ void IslandWindow::SetContent(winrt::Windows::UI::Xaml::UIElement content)
     _rootGrid.Children().Append(content);
 }
 
+// Method Description:
+// - Gets the difference between window and client area size.
```
[the remark this answers is not in the document]
Comment (mcpiroman) [reply src/cascadia/WindowsTerminal/IslandWindow.cpp]: Or wouldn't it be better to name this function `GetClient2NonClientSizeDelta`? Because as I read it now it appears to be the size of whole window (with non client area) rather than just the non-client margins summed up. I thing I even named it once that way but changed it for some reason.

File: src/cascadia/TerminalApp/Pane.cpp [hunk 17]
```diff
@@ -35,6 +35,14 @@ Pane::Pane(const GUID& profile, const TermControl& control, const bool lastFocus
...
 
     _connectionStateChangedToken = _control.ConnectionStateChanged({ this, &Pane::_ControlConnectionStateChangedHandler });
+    _fontSizeChangedToken = _control.FontSizeChanged({ this, &Pane::_FontSizeChangedHandler });
+
+    if (isRoot)
+    {
+        ShouldRelayout([=] {
+            ResizeContent(_root.ActualSize());
+        });
+    }
```
Comment (zadjii-msft) [inline src/cascadia/TerminalApp/Pane.cpp]: I regards to all this `ShouldRelayout` bits:
I think it might be easiest if the `Tab` attached an event handler in `Tab::_AttachEventHandlersToControl` to the control's `FontSizeChanged` event. That way, each Pane wouldn't need to bubble that event up to the root, and none of them would need to know whether they were the root or not. 
```c++
    control.FontSizeChanged([this](const int /* fontWidth */,
                                   const int /* fontHeight */,
                                   const bool isInitialChange) {
        if (isInitialChange)
        {
            _rootPane->Relayout();
        }
    });
```
Where `Pane::Relayout` is just `ResizeContent(_root.ActualSize());`

Then, we wouldn't need the `ShouldRelayout` event at all

File: src/cascadia/TerminalApp/Pane.cpp [hunk 18]
```diff
@@ -1070,28 +1084,45 @@ std::pair<float, float> Pane::_GetPaneSizes(const float fullSize) const
...
+//   the fullSize, but are snapped. If the children can be snapped and also exactly match
+//   the fullSize, then both this fields have the same value that represent this situation.
 Pane::SnapChildrenSizeResult Pane::_CalcSnappedPaneDimensions(const bool widthOrHeight, const float fullSize) const
 {
     if (_IsLeaf())
     {
         THROW_HR(E_FAIL);
     }
 
+    //   First we build a tree of nodes corresponding to the tree of our descendant panes.
```
Comment (zadjii-msft) [inline src/cascadia/TerminalApp/Pane.cpp]: Now this is the kind of code commenting I like to see 😄 thanks!

File: src/cascadia/TerminalApp/Pane.cpp (hunk 17 above)
Comment (mcpiroman) [reply src/cascadia/TerminalApp/Pane.cpp]: Yes, that's simpler and cleaner, except only that it's rather a pane's and not tab's thing to care about that. But I'll go with it.

File: src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp [hunk 19]
```diff
@@ -405,6 +405,34 @@ int NonClientIslandWindow::_GetResizeHandleHeight() const noexcept
     return HTCAPTION;
 }
 
+// Method Description:
+// - Gets the difference between window and client area size.
+// Arguments:
+// - dpi: dpi of a monitor on which the window is placed
+// Return Value
+// - The size difference
+SIZE NonClientIslandWindow::GetClient2WindowSizeDelta(UINT dpi) const noexcept
```
Comment (zadjii-msft) [inline src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp]: Honestly I still don't _love_ the name of this, but I can't really think of a clear better name. `GetNonClientBorderDimensions`? `GetNonClientFrameSize`?

Maybe @DHowett-MSFT or @miniksa might have thoughts

**Comment by mcpiroman** [comment]
(Wasn't there a way not to merge this until I give a sign? I've found one minor thing I'd like to polish.)

**Comment by zadjii-msft** [comment]
@mcpiroman I'm sure there is, but I forget how that works. I can go ahead and block this on your behalf if you want. Considering there's another merge conflict with `Pane.h` (sorry) it still won't automerge, so we'll have to wait for another update _regardless_...

File: src/cascadia/TerminalApp/Pane.cpp [hunk 20]
```diff
@@ -1029,24 +1031,306 @@ std::pair<std::shared_ptr<Pane>, std::shared_ptr<Pane>> Pane::_Split(SplitState
...
+// - widthOrHeight: if true operates on width, otherwise on height
+// - dimension: a dimension (width or height) to snap
+// Return Value:
+// - A value corresponding to the next closest snap size for this Pane, either upward or downward
+float Pane::CalcSnappedDimension(const bool widthOrHeight, const float dimension) const
+{
+    const auto snapPossibilites = _CalcSnappedDimension(widthOrHeight, dimension);
+    const auto lower = snapPossibilites.lower;
+    const auto higher = snapPossibilites.higher;
+    return dimension - lower < higher - dimension ? lower : higher;
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalApp/Pane.cpp]: nit: this could use some parens, it definitely did my eyes in

File: src/cascadia/TerminalApp/lib/Pane.LayoutSizeNode.cpp [hunk 21]
```diff
@@ -0,0 +1,73 @@
...
+// Arguments:
+// - other: Node to take the values from.
+// Return Value:
+// - itself
+Pane::LayoutSizeNode& Pane::LayoutSizeNode::operator=(const LayoutSizeNode& other)
+{
+    size = other.size;
+    isMinimumSize = other.isMinimumSize;
+
+    _AssignChildNode(firstChild, other.firstChild.get());
```
[the remark this answers is not in the document]
Comment (mcpiroman) [reply src/cascadia/TerminalApp/lib/Pane.LayoutSizeNode.cpp]: Sorry, I don't understand what's wrong here. I only pop the underlying pointer to pass it to `_AssignChildNode`, which just reads the pointed object and copies it (copies object, not the pointer). It could receive it by reference as well, except it has to be nullable. Or it could receive reference to `unique_ptr` but that's anti pattern in such situations (not to force implementation). And I don't see any two `unique_ptr`s to hold the same value.

File: src/cascadia/TerminalApp/Pane.cpp (hunk 20 above)
Comment (mcpiroman) [reply src/cascadia/TerminalApp/Pane.cpp]: I had it but forgot to commit apparently.

**Comment by mcpiroman** [comment]
@zadjii-msft Ok, screw it. The problem is that since panes now have borders inside them and some panes have more borders than others (because e.g. some are on the edge of the window), thus some are bigger than others, although terminals are the same. This somewhat breaks the nice order of growth that was established earlier, because now panes that are in the middle are favored, since they are smaller. But that's not terribly bad, if noticeable, so I won't block on that. Fixing this would require differentiating between content and border size and that seems a little bit hard and messy. I might take a follow up on this.

Another problem I noticed is that `CanSplit` can yield wrong result, because it assumes that the other pane would have the same minimum size as the one to be spitted (which is not in case of different font scale, and now with #3825). But this isn't really related to this PR, so I guess I should file an issue about that.

**Comment by miniksa** [comment]
1. I'm still concerned this should be a setting that can be turned off given that `conhost` originally snapped to character cells, then we removed it. I don't recall 100% why that was, but I'm going to suspect there's at least some set of users who prefer it to smooth resize.
2. Did you test that this still works with maximizing the screen and fullscreening through F11/Alt+Enter? One of the weirdnesses in conhost.exe when it snapped to cells was that maximizing the window wouldn't... actually maximize because it was not ready nor willing to have a partial cell rendered at the bottom/right if necessary dependent on the pixel dimensions of the monitor.

**Comment by zadjii-msft** [comment]
@miniksa re: point 1 - I'm fully prepared with a PR to make this a disable-able setting once this merges 😄

**Comment by mcpiroman** [comment]
I can't get it built ATM for some reason but I'm pretty sure it fullscreening worked well. It's only on WM_SIZING that something happens, so only when user drags an edge of window.

Regarding the disabilisness, as I mentioned somewhere, apart from the on and off states, there could be an interesting option to only snap panes, but not window. Can there be a setting that is both boolean and enum? (Typescript can handle that). If not it could be named something like `fullSnap`, `innerSnap` and `noSnap`.

**Comment by zadjii-msft** [comment]
> Regarding the disabilisness, as I mentioned somewhere, apart from the on and off states, there could be an interesting option to only snap panes, but not window. Can there be a setting that is both boolean and enum? (Typescript can handle that). If not it could be named something like `fullSnap`, `innerSnap` and `noSnap`.

Yea that's how I planned on implementing it - we can differentiate between a `boolean` and a `string` at parse time, and assume that `false` == `"innerSnap"` (or something)

**Comment by miniksa** [comment]
@mcpiroman, I know I said in your other PR 4068 that I'd try to get to this one today because I duplicate commented everywhere. But I got tied up in other PRs this morning and early afternoon and now I have to go for the day. (I was overdue on a few for @j4james...) This is now on the top of my list for Thursday morning after the New Year holiday. Thanks for your patience.

**Comment by mcpiroman** [comment]
@miniksa No worries, I wouldn't look at that anyway - it's almost new year already at my timezone

File: src/cascadia/TerminalApp/Pane.cpp (hunk 20 above)
Comment (miniksa) [reply src/cascadia/TerminalApp/Pane.cpp]: This doesn't look resolved...

Comment (mcpiroman) [reply src/cascadia/TerminalApp/Pane.cpp]: But it is, I guess? And for some reason github doesn't show that? I went into file changes, selected "Changes from all commits" and I see it (now it's 2 lines instead of 4). Unless I have misunderstood the request and that's not what you wanted.

Comment (ZhaoMJ) [reply src/cascadia/TerminalApp/Pane.cpp]: Yeah github should mark it as outdated, but I think Dustin might also want something like
`return (dimension - lower) < (higher - dimension) ? lower : higher;`?

**Comment by DHowett-MSFT** [comment]
@mcpiroman thanks for your contribution :smile:
