### PR TITLE
Make the SearchBox announce if it found results or not

### LINKED ISSUE #11973: [Command prompt>Find] : Screen Reader users are not getting any information about 'Search results'.
### Windows Terminal version

1.12.3472.0

### Windows build number

22509.1011

### Other Software

**Test Environment: **
OS: Windows 11 Version Dev (OS Build 22509.1011)
App: Windows Terminal Preview
Screen Reader : Narrator

### Steps to reproduce

**Repro Steps: **

1.Open Windows Terminal.
2.Open 'Command prompt' using 'Ctrl + shift + 2'.
3.Now open 'Find' pop-up using 'Ctrl + Shift + F'.
4.Type any keyword in 'Find' edit field & press enter.
4.Verify whether screen reader is narrating any information regarding available 'Search results' or not.

**User Experience: **
Users who rely on screen readers will get impacted here & may not know any information regarding search results, if screen reader stays silent on typing any keyword.

Guideline reference
https://www.w3.org/TR/WCAG21/#info-and-relationships

Attachment : 
[Narrator not reading any information reg search results.zip](https://github.com/microsoft/terminal/files/7743234/Narrator.not.reading.any.information.reg.search.results.zip)

### Expected Behavior

Screen reader should narrate information of  available 'Search results', on typing any keyword on 'Find' edit field.

### Actual Behavior

Screen reader is staying silent & not narrating any information regarding 'Search results'.

### PR DESCRIPTION
**Pull request by zadjii-msft**
Basically, this is the same as #12266, but for the `SearchBoxControl`. Trickily, the ControlCore is the one that knows if there were search results, but the TermControl has to be the one to announce it.

* [x] Will take care of #11973 once a11y team confirms
* [x] Tested manually with Narrator
* [x] Resolves a part of #6319, which I'm repurposing just to displaying the number of results in general. 
* See also #3920

### CODE REVIEW

File: src/cascadia/TerminalControl/ControlCore.h [hunk 1]
```diff
@@ -191,6 +191,7 @@ namespace winrt::Microsoft::Terminal::Control::implementation
         TYPED_EVENT(RaiseNotice,               IInspectable, Control::NoticeEventArgs);
         TYPED_EVENT(TransparencyChanged,       IInspectable, Control::TransparencyChangedEventArgs);
         TYPED_EVENT(ReceivedOutput,            IInspectable, IInspectable);
+        TYPED_EVENT(FoundMatch,            IInspectable, Control::FoundResultsArgs);
```
Comment (DHowett) [inline src/cascadia/TerminalControl/ControlCore.h:194]: manual spacing is off here

File: src/cascadia/TerminalControl/Resources/en-US/Resources.resw [hunk 2]
```diff
@@ -200,4 +200,10 @@ Please either install the missing font or choose another one.</value>
   <data name="TermControlReadOnly" xml:space="preserve">
     <value>Read-only mode is enabled.</value>
   </data>
+  <data name="SearchBox_MatchesAvailable" xml:space="preserve">
+    <value>Results found</value>
```
Comment (DHowett) [inline src/cascadia/TerminalControl/Resources/en-US/Resources.resw:204]: should we add comments explaining that these are read aloud to users using screen readers?

**Review by DHowett — CHANGES_REQUESTED** [review]

File: src/cascadia/TerminalControl/ControlCore.h (hunk 1 above)
Comment (zadjii-msft) [reply src/cascadia/TerminalControl/ControlCore.h:194]: i-am-ashamed

File: src/cascadia/TerminalControl/EventArgs.idl [hunk 3]
```diff
@@ -68,4 +68,10 @@ namespace Microsoft.Terminal.Control
     {
         Double Opacity { get; };
     }
+
```
Comment (carlos-zamora) [inline src/cascadia/TerminalControl/EventArgs.idl:71]:
```suggestion
```
nit: extra newline

**Review by carlos-zamora — APPROVED** [review]
Thank you!

**Review by DHowett — APPROVED** [review]

**Comment by DHowett** [comment]
@msftbot merge this in 1 minute
