### PR TITLE
Prevent the virtual viewport bottom being moved up unintentionally

### LINKED ISSUE #9754: The virtual viewport bottom is not maintained correctly
### Windows Terminal version (or Windows build number)

10.0.18363.1379, 7f5a19b627037353fc988755ed25e6ecb5bf4675

### Other Software

_No response_

### Steps to reproduce

1. Start a bash shell in conhost.
2. Open the Properties page, and enable the _Disable Scroll-Forward_ option on the _Terminal_ tab.
3. Generate some output to get a few pages of content in the backscroll buffer.
4. Execute `printf "\e[H"` to move the cursor to the top of the current page.
5. Scroll back to the top of the buffer so the cursor is now out of view.
6. Type a printable character

### Expected Behavior

All of the buffer contents should be preserved.

### Actual Behavior

The line that the cursor was on becomes the bottom of the buffer, and everything below that point is truncated. Technically the data is still there - if you press enter a few times, it'll start scrolling into view. The problem is that the virtual viewport bottom is incorrectly set, so with _Scroll-Forward_ disabled, everything below that point is hidden.

There are a number of ways this bug can be triggered - even just resizing the window can do it - but the above described method is probably the easiest to reproduce consistently. Anything that calls `SCREEN_INFORMATION::UpdateBottom` can potentially trigger it, and there are a quite a few code paths leading to that.

### PR DESCRIPTION
**Pull request by j4james**
## Summary of the Pull Request

The "virtual bottom" marks the last line of the mutable viewport area, which is the part of the buffer that VT sequences can write to. This region should typically only move downwards, as new lines are added to the buffer, but there were a number of cases where it was incorrectly being moved up. This PR attempts to fix that.

## PR Checklist
* [x] Closes #9754
* [x] CLA signed.
* [x] Tests added/passed
* [ ] Documentation updated.
* [ ] Schema updated.
* [x] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #9754

## Detailed Description of the Pull Request / Additional comments

When a call is made to `UpdateBottom`, we now clamp the value so it's at least as low as the current viewport bottom (i.e. if the viewport has moved down, we want the virtual bottom to move down too), but no lower than the bottom of the buffer (we don't want it to be out of range).

There is one special case where we do actually want the virtual bottom to move up - when the scrollback has been cleared with an `ED3` escape sequence. So in that case we needed a new `ConGetSet` API (`ResetBottom`) to reset the virtual bottom to the top of the buffer (essentially one less than the viewport height, since the virtual bottom points to the last line of the viewport).

## Validation Steps Performed

I had to reset the virtual bottom manually in some parts of the `ScreenBufferTests`, since some of the tests were relying on the virtual bottom being automatically reset when the viewport was reset, which is no longer the case.

I've also added a new test to verify that the virtual bottom doesn't move upwards if an update is triggered while the visible viewport is scrolled up. This essentially reproduces the test case from issue #9754, which I've also manually confirmed is fixed.

### CODE REVIEW

File: src/host/screenInfo.cpp [hunk 1]
```diff
@@ -113,14 +113,15 @@ SCREEN_INFORMATION::~SCREEN_INFORMATION()
...
                                                       pScreen->_IsInPtyMode() ? coordScreenBufferSize : coordWindowSize);
-        pScreen->UpdateBottom();
 
         // Set up text buffer
         pScreen->_textBuffer = std::make_unique<TextBuffer>(coordScreenBufferSize,
                                                             defaultAttributes,
                                                             uiCursorSize,
                                                             pScreen->_renderTarget);
 
+        pScreen->UpdateBottom();
```
Comment (j4james) [inline src/host/screenInfo.cpp:123]: This had to move down, because `UpdateBottom` now depends on `_textBuffer` to verify that the bottom hasn't become out of range.

**Review by miniksa — APPROVED** [review]
This seems fair to me and looks fine.

**Review by DHowett — APPROVED** [review]
Yep, this seems fine to me too. Happy to reflect it back into windows. :smile:

**Comment by j4james** [comment]
The only reason I had this as a draft was because I wanted to use it for a while and make sure it was working as expected. Unfortunately my home computer has now reached a point where it's more dead than alive, which means I likely won't be able to work on WT for the foreseeable future. So I'm going to mark this as ready for review now - in the time I had been using it, it seemed fine to me.

**Comment by zadjii-msft** [comment]
(sorry to hear that your PC died - I will long await the days you can return in full ☺️)

**Review by zadjii-msft — APPROVED** [review]
Yep this looks smart to me.
