### PR TITLE
Bugfix: update color scheme references properly

### LINKED ISSUE #9094: Settings UI: Renaming default color scheme applies to each profile instead of defaults section
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19042.746]
Windows Terminal version (if applicable): Windows Terminal Preview Version: 1.6.10272.0
```

# Steps to reproduce

1. Create a custom color scheme named 'foo'
2. In the "Base Layer" settings page, select 'foo' as the color scheme
3. Rename the color scheme 'foo' to 'bar'

# Expected behavior

The color scheme in the "Base Layer" settings should be updated to be 'bar' and changing it should affect all profiles.

# Actual behavior

The color scheme in the "Base Layer" settings changes to "Campbell" and changing it has no effect on other profiles.  Looking at the settings file you will see that each profile has had the `colorScheme` attribute added with the new name, and the `colorScheme` attribute in the `defaults` section still has the old name.

### PR DESCRIPTION
**Pull request by carlos-zamora**
`CascadiaSettings::UpdateColorSchemeReferences` had two bugs in it:
1. we would never check/update the base layer
2. we would explicitly set the color scheme on a profile referencing the
   old name

This PR fixes both of those issues by checking/updating the base layer,
and ensuring that we check if a profile has an explicit reference before
updating it.

Since the affected code is in TSM, I also created an automated local
test.

## Validation Steps Performed
Bug repro steps.
Specifically tested [DHowett's scenario] too.
Test added.

Closes #9094 

[DHowett's scenario]: https://github.com/microsoft/terminal/issues/9094#issuecomment-776412781

### CODE REVIEW

File: src/cascadia/LocalTests_SettingsModel/ColorSchemeTests.cpp [hunk 1]
```diff
@@ -290,4 +291,81 @@ namespace SettingsModelLocalTests
...
+                                            })" };
+
+        auto settings{ winrt::make_self<CascadiaSettings>(false) };
+        settings->_ParseJsonString(settingsString, false);
+        settings->_ApplyDefaultsFromUserSettings();
+        settings->LayerJson(settings->_userSettings);
+        settings->_ValidateSettings();
+
+        // update all references from scheme 1 --> 3
+        const auto newName{ L"Scheme 1 (renamed) " };
```
Comment (DHowett) [inline src/cascadia/LocalTests_SettingsModel/ColorSchemeTests.cpp:336]:
```suggestion
        const auto newName{ L"Scheme 1 (renamed)" };
```

having this space at the end seems _strange_. It also doesn't go from `1` to `3` as in the comment.

**Review by DHowett — APPROVED** [review]

File: src/cascadia/LocalTests_SettingsModel/ColorSchemeTests.cpp [hunk 2]
```diff
@@ -290,4 +291,81 @@ namespace SettingsModelLocalTests
...
+                                                        {
+                                                            "name": "Different reference",
+                                                            "colorScheme": "Scheme 2"
+                                                        }
+                                                    ]
+                                                },
+                                                "schemes": [
+                                                    { "name": "Scheme 1" },
+                                                    { "name": "Scheme 2" },
+                                                    { "name": "Scheme 1 (renamed) " }
```
Comment (carlos-zamora) [inline src/cascadia/LocalTests_SettingsModel/ColorSchemeTests.cpp:325]: @DHowett dumb question:
```suggestion
                                                    { "name": "Scheme 1 (renamed)" }
```
this doesn't work because the syntax expects `)"` to be the end of the string. But I've tried doing `)/"` and `)\"` and both seem to be interpreted incorrectly. Any ideas how to get around this?

Comment (carlos-zamora) [reply src/cascadia/LocalTests_SettingsModel/ColorSchemeTests.cpp:325]: That's why I went with the extra space haha

Comment (DHowett) [reply src/cascadia/LocalTests_SettingsModel/ColorSchemeTests.cpp:325]: Use a different delimiter. The [raw string literal](https://en.cppreference.com/w/cpp/language/string_literal) syntax supports different delimiters... it doesn't just have to be `R"(...)"`, it can be `R"json(xxxxxxxxxxxxxx)json"`

**Comment by DHowett** [comment]
@msftbot merge this in 5 minutes

**Review by zadjii-msft — APPROVED** [review]
