### PR TITLE
Fetch the terminal cursor position after a resize

### LINKED ISSUE #18725: ConPTY: Ask for the cursor position after each resize
### Description of the new feature

ConPTY's reflow algorithm may differ from the hosting terminal and that may result in ConPTY returning wildly incorrect cursor positions via `GetConsoleCursorInfo`. This results in the cursor being inside the previous prompt when resizing PowerShell in VS Code.

### Proposed technical implementation details

Use the existing DSC CPR facilities in `VtIo` but make them more flexible so that they can be called more than once.

Complications:
* The request must block the console server
* ...but it must not block further incoming resizes (= debounce)

### PR DESCRIPTION
**Pull request by lhecker**
Closes #18725

## Validation Steps Performed
Functionality was observed under a
debugger while using PowerShell 5.

### CODE REVIEW

File: src/host/VtIo.cpp [hunk 1]
```diff
@@ -177,7 +177,7 @@ bool VtIo::IsUsingVt() const
             // wait for the DA1 response below and effectively wait for both.
             if (_lookingForCursorPosition)
             {
-                writer.WriteUTF8("\x1b[6n"); // Cursor Position Report (DSR CPR)
```
Comment (carlos-zamora) [inline src/host/VtIo.cpp:180]: 📝Moved to `WriteDSRCPR()`

**Review by carlos-zamora — APPROVED** [review]
Looks good to me! Thanks! 🙂

EDIT: aside from the build failure, of course. But that looks like it may be an easy fix.

**Review by carlos-zamora — APPROVED** [review]

**Comment by lhecker** [comment]
Market as `Inbox Servicing Pipeline` not for inbox, but for packaging as a nuget.
