### PR TITLE
Fix restore window position when exiting fullscreen

### LINKED ISSUE #9746: Exiting fullscreen positions window to unexpected place if monitor changed
### Windows Terminal version (or Windows build number)

issue is not a regression, but running Windows Terminal Version: 1.6.10571.0

### Other Software

The problem exists in Terminal and conhost, albeit with forked implementations.

### Steps to reproduce

With two monitors, f11 to enter fullscreen, win+shift+left/right, f11 to exit fullscreen. 

### Expected Behavior

Window restores somewhere on its current monitor, to its previous logical size (or maximize state) and relative position on the monitor. This should be true even if the window's monitor has changed or has been removed.

### Actual Behavior

If window was not maximized, will restore to previous position on previous monitor, potentially jumping to an unexpected size if the window has changed DPI since the restore position was stored. If the window's previous monitor was removed, it may now be off-screen. If window was maximized, window may disappear even without its previous monitor having been removed.

### PR DESCRIPTION
**Pull request by ekoschik**
## Summary of the Pull Request

This change cleans up the Fullscreen implementation for both conhost and Terminal, improving the restore position (where the window goes when exiting fullscreen).

Prior to this change the window wasn't guaranteed to restore somewhere on the window's current monitor when exiting fullscreen. With this change the window will restore always to its current monitor, at a reasonable location (and will 'double restore' (to fullscreen->maximize->restore) after monitor changes while fullscreen, which is the expected user behavior.

 
## PR Checklist
* [x] Closes #9746
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Documentation updated. If checked, please file a pull request on [our docs repo](https://github.com/MicrosoftDocs/terminal) and link it here: #xxx
* [ ] Schema updated.
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Detailed Description of the Pull Request / Additional comments

A fullscreen window's monitor can change.
 - Win+Shift+left/right migrates a window between monitors.
 - User could open settings, display, and move the monitor or change its DPI.
 - The monitor could be unplugged.
 - The session could be remote and be disconnected.

A fullscreen window stores a 'restore position' when entering fullscreen, used to move the window back 'where it was'. BUT, its unexpected for the window to exit fullscreen and jump to another monitor. This means its previous position must be migrated from the old monitor's work area to the new monitor's work area.

If a window is maximized, it is sized to the work area. Like with fullscreen, a maximized window has a 'restore position', though unlike with fullscreen the restore position for maximized is stored by the system itself. Migration in cases where a maximized (or fullscreen) window's monitor changes is also taken care of by the system. To restore 'safely' to maximized (after changing window styles) a window must only `SetWindowPos(SWP_FRAMECHANGED)`. While technically a maximized window that becomes fullscreen 'is still maximized' (from Win32's perspective), its prudent to also `ShowWindow(SW_MAXIMIZED)` prior to `SWP_FRAMECHANGED` (to explicitly make the window maximized).

If not restoring to maximized, the restore position is adjusted by the new/ old work area. Additionally, the new/ old window DPI is used to adjust the size of the window by the DPI change (keeping the window's logical size the same).
 - The work area origin is checked first (shifting window rect by the change in origin)
 - The DPI is checked next, changing right/ bottom (size only)
 - Each edge of the window is compared against the corresponding edge of the work area, nudging the window back on-screen if hanging offscreen. By shifting right before left, bottom before top, the top-left is guaranteed on-screen. 

## Validation Steps Performed

Tried it out. Seemed to work on my machine.
Jk, ran conhost/ terminal on mixed DPI system, max (or not), fullscreen, win+shift+left/ exit fullscreen/ maximize. Monitor unplug, etc.

### CODE REVIEW

**Comment by DHowett** [comment]
@ekoschik If you link up your account at the OSS portal (repos.opensource.microsoft.com, link tab) you won't have to accept the CLA.

File: src/interactivity/win32/windowproc.cpp [hunk 1]
```diff
@@ -226,18 +226,15 @@ using namespace Microsoft::Console::Types;
         _UpdateSystemMetrics();
         s_ReinitializeFontsForDPIChange();
 
-        if (IsInFullscreen())
-        {
-            // If we're a full screen window, completely ignore what the DPICHANGED says as it will be bigger than the monitor and
-            // instead just ensure that the window is still taking up the full screen.
-            SetIsFullscreen(true);
-        }
-        else
```
Comment (DHowett) [inline src/interactivity/win32/windowproc.cpp:235]: Will any of these changes regress our windowing downlevel from 21xxx? Or is this "more correct" everywhere?

Comment (ekoschik) [reply src/interactivity/win32/windowproc.cpp:235]: Fair concern. The short answer is 'yes', this change should work properly on all down-level releases.

Re the WM_DPICHANGED message, whenever this message is sent (from any release) anything other than calling SetWindowPos with the RECT from lParam simply isn't supported. If this was ever necessary, it was because of a bug that (I believe) has since been fixed.

I'd be happy to convince you further (either in the open or in a teams chat) :).

**Comment by DHowett** [comment]
(Sorry, we've been busy with the coming 1.8/1.7 pair of releases; We'll review this asap.)

**Review by zadjii-msft — APPROVED** [review]
Okay this all seems reasonable to me. It also makes the logic in those methods way easier to follow. Thanks!

**Comment by zadjii-msft** [comment]
@msftbot make sure either @DHowett or @miniksa signs off on this

File: src/cascadia/WindowsTerminal/IslandWindow.cpp [hunk 2]
```diff
@@ -758,6 +758,91 @@ void IslandWindow::_SetIsBorderless(const bool borderlessEnabled)
...
+        return;
+    }
+
+    // Start with the stored window position.
+    RECT rcRestore = _rcWindowBeforeFullscreen;
+
+    // If the window DPI has changed, re-size the stored position by the change in DPI. This
+    // ensures the window restores to the same logical size (even if to a monitor with a different
+    // DPI/ scale factor).
+    UINT dpiWindow = GetDpiForWindow(hWnd);
```
Comment (miniksa) [inline src/cascadia/WindowsTerminal/IslandWindow.cpp:808]:
```suggestion
    UINT const dpiWindow = GetDpiForWindow(hWnd);

```

**Review by miniksa — APPROVED** [review]
Looks good to me. Nothing like a `user32k` expert to fix up your window message handling, so I trust @ekoschik here.

Evan, if you're confused on fixing up the spell check bot that's blocking the merge, let me know.

**Comment by miniksa** [comment]
WELP OK SPELL CHECK DOES NOT BLOCK MERGE. Guess I'm fixing it now.

**Review by DHowett — COMMENTED** [review]
Signing off after the fact -- this is great. Thanks so much @ekoschik

**Comment by ekoschik** [comment]
Yayyy!!! Thanks so much, folks!
