### PR TITLE
Fix a crash on startup with a `folder` entry without `entries`

### LINKED ISSUE #14557: Empty "folder" entry in "newTabMenu" causes WT to be unable to start
### Windows Terminal version

1.17.3482.0

### Windows build number

_No response_

### Other Software

_No response_

### Steps to reproduce

1. In `settings.json`, update the `"newtabMenu"` setting to look like this:

```
    [
        {
            "type": "remainingProfiles"
        },
        {
            "type": "folder"
        }
    ],
```

2. Launch Terminal

### Expected Behavior

Either nothing happens, or Terminal gives me a warning

### Actual Behavior

I get an empty window and a system error dialog that says "Windows Terminal.exe has stopped working"

### PR DESCRIPTION
**Pull request by zadjii-msft**
`_Entries` was getting default constructed to `nullptr`. We should be careful about that. 

Adds a test too, and fixes a regression in the local tests introduced in #13763.

Closes #14557

### CODE REVIEW

**Comment by carlos-zamora** [comment]
If having an empty folder is invalid, shouldn't we throw a serialization error or warning?

File: src/cascadia/TerminalSettingsModel/FolderEntry.cpp [hunk 1]
```diff
@@ -48,7 +48,10 @@ winrt::com_ptr<NewTabMenuEntry> FolderEntry::FromJson(const Json::Value& json)
 
     JsonUtils::GetValueForKey(json, NameKey, entry->_Name);
     JsonUtils::GetValueForKey(json, IconKey, entry->_Icon);
-    JsonUtils::GetValueForKey(json, EntriesKey, entry->_Entries);
+    if (const auto& entries{ JsonUtils::GetValueForKey<decltype(entry->_Entries)>(json, EntriesKey) })
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsModel/FolderEntry.cpp:51]: Can you explain quick how this is different from `GetValueForKey(..., into)`? It seems largely the same, but more verbose and error-prone.

**Review by DHowett — CHANGES_REQUESTED** [review]
(only not signing off because of the `GetValueForKey<T>` thing)

File: src/cascadia/TerminalSettingsModel/FolderEntry.cpp (hunk 1 above)
Comment (zadjii-msft) [reply src/cascadia/TerminalSettingsModel/FolderEntry.cpp:51]: @DHowett IIRC, the issue was that `GetValueForKey(..., into)` would happily place `nullptr` into `into` if it didn't find `entries`. So the later attempt to query it would a/v. 

I think I started here, and then added the null check, and I probably should have just started there. I'll revert these lines.

**Comment by zadjii-msft** [comment]
> shouldn't we throw a serialization error or warning

A warning might be nice, sure, but it's not well hooked up for that right now, and we do need the crash fix NOW. I feel like this is one of those "you aint gonna fix it" things.
