### PR TITLE
Prevent resizing terminal to a lower-than-minimum width

### LINKED ISSUE #8026: possible to resize terminal to a lower width than minimum width
# Environment

```none
Windows build number: [10.0.19042.0]
Windows Terminal version (if applicable):1.4.2652.0

Any other software?
```

# Steps to reproduce

1. grab one of the upper corners of the terminal window
2. move the mouse to the top of the screen to trigger snap assist
3. move the mouse to a position above the other corner of the window while still maintaining it at the top of screen
4. release mouse button

# Expected behavior

minimum width is enforced properly

# Actual behavior

width is resized based on mouse position
resize

### PR DESCRIPTION
**Pull request by Don-Vito**
Until now, we relied on WM_SIZING to ensure that the island is not
downsized below minimal allowed dimensions. However, on some occasions
WM_WINDOWPOSCHANGED, e.g. when anchoring a window to the top/bottom of
the screen. This message will use dimensions obtained from
WM_GETMINMAXINFO. Until now we didn't override this value, falling back
to the defaults. As a result we got an inconsistent behavior (at least
when attaching the anchor).

I added logic very similar to the one we use in IslandWindow::_OnSizing
to the MINMAXINFO handler: snap the client area, add non client
exclusive are, consider DPI along the computation.

## Validation Steps Performed
* Manual testing of minimizing, maximizing, resizing, attaching
  different anchors, etc.

Closes #8026

### CODE REVIEW

**Comment by Don-Vito** [comment]
@DHowett - no more hacktoberfest labeling is needed - the tree is already planted. We did it 🌳

**Comment by Don-Vito** [comment]
@zadjii-msft - resolved conflicts and bumping 😊

**Review by zadjii-msft — COMMENTED** [review]
Played with this a bit this morning - this seems like it works well enough to me. Thanks for putting this together!

**Review by zadjii-msft — APPROVED** [review]
days since I pressed <kbd>ctrl+enter</kbd> thinking that it was "Approve": 0

File: src/cascadia/WindowsTerminal/IslandWindow.cpp [hunk 1]
```diff
@@ -2,6 +2,7 @@
 // Licensed under the MIT license.
 
 #include "pch.h"
+#include <WinUser.h>
```
Comment (DHowett) [inline src/cascadia/WindowsTerminal/IslandWindow.cpp:5]: this might belong in the `pch.h` in this project with the other platform includes. I'm very surprised it isn't already included!

File: src/cascadia/WindowsTerminal/IslandWindow.cpp [hunk 2]
```diff
@@ -276,10 +277,77 @@ void IslandWindow::OnSize(const UINT width, const UINT height)
...
 }
 
+// Method Description:
+// - Handles a WM_GETMINMAXINFO message, issued before the window sizing starts.
+//   This message allows to modify the minimal and maximal dimensions of the window.
+//   We focus on minimal dimensions here
+//   (the maximal dimension will be calculate upon maximizing)
+//   Our goal is to protect against to downsizing to less than minimal allowed dimensions,
+//   that might occur in the scenarios, where _OnSizing is bypassed.
+//   An example of such scenario, is anchoring the window to the top/bottom screen border
```
Comment (DHowett) [inline src/cascadia/WindowsTerminal/IslandWindow.cpp:287]:
```suggestion
//   that might occur in the scenarios where _OnSizing is bypassed.
//   An example of such scenario is anchoring the window to the top/bottom screen border
```

extraneous commas

File: src/cascadia/WindowsTerminal/IslandWindow.cpp [hunk 3]
```diff
@@ -276,10 +277,77 @@ void IslandWindow::OnSize(const UINT width, const UINT height)
...
+
+    UINT dpix = USER_DEFAULT_SCREEN_DPI;
+    UINT dpiy = USER_DEFAULT_SCREEN_DPI;
+    GetDpiForMonitor(hmon, MDT_EFFECTIVE_DPI, &dpix, &dpiy);
+
+    // From now we use dpix for all computations (same as in _OnSizing).
+    const auto nonClientSizeScaled = GetTotalNonClientExclusiveSize(dpix);
+    const auto scale = base::ClampedNumeric<float>(dpix) / USER_DEFAULT_SCREEN_DPI;
+
+    LPMINMAXINFO lpMinMaxInfo = reinterpret_cast<LPMINMAXINFO>(lParam);
```
Comment (DHowett) [inline src/cascadia/WindowsTerminal/IslandWindow.cpp:323]:
```suggestion
    auto lpMinMaxInfo = reinterpret_cast<LPMINMAXINFO>(lParam);
```

(repetitive w/ the cast type)

**Review by DHowett — COMMENTED** [review]
Looks good to me! Only minor nit-level comments

**Review by atherkhan — APPROVED** [review]

File: src/cascadia/WindowsTerminal/IslandWindow.cpp (hunk 2 above)
Comment (Don-Vito) [reply src/cascadia/WindowsTerminal/IslandWindow.cpp:287]: I will never learn this - in my mother tongue the comma is required.. while in English it is not.

**Review by DHowett — APPROVED** [review]
Thank you! This is great.
