### PR TITLE
Set actual background color in HTML copy

### LINKED ISSUE #2128: HTML copied text has invalid background after last char in row
## Environment
(note that HTML copy is not yet on master)

## Steps to reproduce
In terminal:
image

Pasted to Word:
## Expected behavior
image

## Actual behavior
image

The color is taken form the first copied cell, `X` in this example.

### PR DESCRIPTION
**Pull request by mcpiroman**
## Summary of the Pull Request

It just takes background color from terminal (or console) configured in settings, instead first copied 
character. Somewhat easier than I thought it would be.

## PR Checklist
* [X] Closes #2128
* [X] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Requires documentation to be updated
* [X] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #990

### CODE REVIEW

File: src/buffer/out/textBuffer.cpp [hunk 1]
```diff
@@ -1056,12 +1056,13 @@ const TextBuffer::TextAndColor TextBuffer::GetTextForClipboard(const bool lineSe
...
 // Arguments:
 // - rows - the text and color data we will format & encapsulate
+// - backgroundColor - default background color for characters, also used in padding
 // - fontHeightPoints - the unscaled font height
 // - fontFaceName - the name of the font used
 // - htmlTitle - value used in title tag of html header. Used to name the application
 // Return Value:
 // - string containing the generated HTML
-std::string TextBuffer::GenHTML(const TextAndColor& rows, const int fontHeightPoints, const PCWCHAR fontFaceName, const std::string& htmlTitle)
+std::string TextBuffer::GenHTML(const TextAndColor& rows, const int fontHeightPoints, const PCWCHAR fontFaceName, COLORREF backgroundColor, const std::string& htmlTitle)
```
Comment (zadjii-msft) [inline src/buffer/out/textBuffer.cpp]:
```suggestion
std::string TextBuffer::GenHTML(const TextAndColor& rows, const int fontHeightPoints, const PCWCHAR fontFaceName, const COLORREF backgroundColor, const std::string& htmlTitle)
```
