### PR TITLE
Ignore closeOnExit when a conn. moves from Connecting to Failed

### LINKED ISSUE #10225: startingDirectory being invalid shouldn't cause silent failures
### Windows Terminal version (or Windows build number)

1.8.1444.0

### Other Software

_No response_

### Steps to reproduce

Adjust the startingDirectory to the name of a directory that doesn't exist. Then launch Windows Terminal. That's it.

### Expected Behavior

I was expecting an error message saying that the directory doesn't exist. This could be printed to the console or it could be a dialog. Ideally Windows Terminal would still launch since otherwise there is no clear way for me to fix this broken setting.

### Actual Behavior

The Windows terminal window flashes and then closes. There is no indication of what the problem is and, unless you have memorized the path to the settings file, no way to fix the problem.

This issue can easily happen if you delete a directory or if you copy settings from one machine to another.

### PR DESCRIPTION
**Pull request by DHowett**
ConptyConnection has two different failure modes:

1. We failed to initialize the pseudoconsole or create the process
2. The process exited with an error code.

Until this commit, they were treated the same way: closeOnExit=always
would force the pane/tab to be destroyed. This was very bad in case 1,
where we would display a (possibly useful) error message and then
immediately close the window.

This was made even worse by the change in #10045. We removed
startingDirectory validation and promoted it to an error message (so
that we could eventually let the connection handle startingDirectory in
its own way.) This of course revealed that a number of users had set
invalid starting directories… and those users included some who set
closeOnExit to always. Boom: instant "terminal opens and crashes"¹

¹ It only looks like a crash; it's actually _technically_ functioning
properly.

Closes #10225.

### CODE REVIEW

**Review by zadjii-msft — APPROVED** [review]

File: src/cascadia/TerminalApp/Pane.cpp [hunk 1]
```diff
@@ -1476,6 +1486,7 @@ std::pair<std::shared_ptr<Pane>, std::shared_ptr<Pane>> Pane::_Split(SplitState
     //   Move our control, guid into the first one.
     //   Move the new guid, control into the second.
     _firstChild = std::make_shared<Pane>(_profile.value(), _control);
+    _firstChild->_connectionState = std::exchange(_connectionState, ConnectionState::NotConnected);
```
Comment (lhecker) [inline src/cascadia/TerminalApp/Pane.cpp:1489]: Is it just me or is it kinda hacky that this isn't part of the/a constructor?

**Review by lhecker — APPROVED** [review]

File: src/cascadia/TerminalApp/Pane.cpp (hunk 1 above)
Comment (DHowett) [reply src/cascadia/TerminalApp/Pane.cpp:1489]: I rather think the design of Pane leaves a lot to be desired; there are a lot of properties that "move" between parent and leaf panes. The ideal design is one that doesn't require us to move state at all. I'd rather not spend too much effort on an already-bad solution :smile:
