### PR TITLE
Fix cursor being hidden when pressing modifier keys

### LINKED ISSUE #19445: The mouse pointer has disappeared when press CTRL or SHIFT
### Windows Terminal version

v1.23.12811.0

### Windows build number

10.0.19045.0

### Other Software

_No response_

### Steps to reproduce

Sometimes I use the SHIFT key with the mouse to select text to copy, but when I hold down the SHIFT key, the mouse pointer disappears automatically, and it only reappears when I move the mouse.

### Expected Behavior

The mouse pointer does not disappear when I press SHIFT or CTRL

### Actual Behavior

The mouse pointer disappears when I press SHIFT or CTRL

### PR DESCRIPTION
**Pull request by angesie**
## Summary of the Pull Request

Added a check to ensure IslandWindow::HideCursor() is only called when a non-modifier key (e.g., not Shift, Control, Alt, or Windows keys) is pressed. This prevents unintended cursor hiding when only modifier keys are used.

## References and Relevant Issues

[19445](https://github.com/microsoft/terminal/issues/19445) - The mouse pointer has disappeared when press CTRL or SHIFT

## Validation Steps Performed

Built and deployed CascadiaPackage through VS, tested the deployed Terminal Dev app on local machine.

## PR Checklist
- [x] Closes #19445
- [x] Tests added/passed
- [ ] Documentation updated
   - If checked, please file a pull request on [our docs repo](https://github.com/MicrosoftDocs/terminal) and link it here: #xxx
- [ ] Schema updated (if necessary)

### CODE REVIEW

**Comment by Mayuri9356** [comment]
Thanks for the review. I'm excited to contribute to this project. I'm available to make any requested changes quickly!

File: src/cascadia/WindowsTerminal/WindowEmperor.cpp [hunk 1]
```diff
@@ -486,7 +486,17 @@ void WindowEmperor::HandleCommandlineArgs(int nCmdShow)
...
             {
-                IslandWindow::HideCursor();
+                const bool modifierKey = (msg.wParam == VK_SHIFT ||
+                                          msg.wParam == VK_CONTROL ||
+                                          msg.wParam == VK_MENU ||
+                                          msg.wParam == VK_LWIN ||
+                                          msg.wParam == VK_RWIN);
+
+                // Hide the cursor only when the key pressed is not a modifier key.
+                if (!modifierKey)
```
Comment (lhecker) [inline src/cascadia/WindowsTerminal/WindowEmperor.cpp]: Thank you for working on this. Elsewhere we have this function:

https://github.com/microsoft/terminal/blob/b8f35a31c26febbe153642488c88549f93e5980c/src/cascadia/TerminalCore/Terminal.hpp#L66-L80

Perhaps we should copy it verbatim here and use it?

Comment (angesie) [reply src/cascadia/WindowsTerminal/WindowEmperor.cpp]: Hi! Thanks for the feedback :) 
I've refactored the code following your advice, and re-tested it

**Comment by angesie** [comment]
@microsoft-github-policy-service agree

**Review by lhecker — APPROVED** [review]
Thank you for doing this!

At some point in the future we can think about how to unify the `IsInputKey` copies, but not today. :)
