### PR TITLE
Don't yeet focus to the control when the tab renamer is opened

### LINKED ISSUE #10112: Right-click on a tab... "Rename Tab" broken after #10048
I did something wrong in #10048 and now when we close the context menu, we immediately toss focus into the control, which means that the renamer immediately loses focus and dismisses itself. Oops.

See also #6680

### PR DESCRIPTION
**Pull request by zadjii-msft**
This is a hotfix to #10048. When the tab renamer is opened, we need to make sure to not immediately steal focus from it.

* [x] closes #10112
* [x] I work here
* [x] tested manually

### CODE REVIEW

File: src/cascadia/TerminalApp/TerminalTab.cpp [hunk 1]
```diff
@@ -899,7 +899,13 @@ namespace winrt::TerminalApp::implementation
         contextMenuFlyout.Closed([weakThis](auto&&, auto&&) {
             if (auto tab{ weakThis.get() })
             {
-                tab->_RequestFocusActiveControlHandlers();
+                // GH#10112 - if we're opening the tab renamer, don't
+                // immediately toss focus to the control. We don't want to steal
+                // focus from the tab renamer.
+                if (!tab->_headerControl.InRename())
```
Comment (DHowett) [inline src/cascadia/TerminalApp/TerminalTab.cpp:905]: are we gonna have to start slapping "BODGY" on our own code that is workaround for other code of ours being wrong

Comment (zadjii-msft) [reply src/cascadia/TerminalApp/TerminalTab.cpp:905]: That sure is possible

**Review by DHowett — APPROVED** [review]

File: src/cascadia/TerminalApp/TabHeaderControl.cpp [hunk 2]
```diff
@@ -55,6 +55,18 @@ namespace winrt::TerminalApp::implementation
...
     }
 
+    // Method Description:
+    // - Returns true if we're in the middle of a tab rename. This is used to
+    //   mitigate GH#10112.
+    // Arguments:
+    // - <none>
+    // Return Value:
+    // - true if the renamer is open.
+    bool TabHeaderControl::InRename()
```
Comment (carlos-zamora) [inline src/cascadia/TerminalApp/TabHeaderControl.cpp:65]:
```suggestion
    bool TabHeaderControl::InRename() const noexcept
```

**Review by carlos-zamora — APPROVED** [review]
