### PR TITLE
Gently rework icon and background image validation

### LINKED ISSUE #14143: We should block resources from web URLs
### Windows Terminal version

1.16.2641.0

### Windows build number

10.0.19044.2075

### Other Software

WSL1 ubuntu 22.04LTS

### Steps to reproduce

open windows terminal preview

### Expected Behavior

just show the terminal, not attempt to connect to the internet

### Actual Behavior

image

### LINKED ISSUE #18703: Found a profile with an invalid "icon" error
### Windows Terminal version

1.21.10351.0

### Windows build number

10.0.19045.0

### Other Software

_No response_

### Steps to reproduce

I tried uninstalling the program and reinstalling it, removing my current `settings.json` file.
And this error doesn't go away
Even tho i don't have any icon setting in my config file.

### Expected Behavior

To run normally

### Actual Behavior

Image

### PR DESCRIPTION
**Pull request by DHowett**
Right now, image validation accepts web-sourced icons (boo) and rejects images whose paths begin with `\\?\`. In addition, it will warn the user for things out of their control like images set by fragments.

This pull request adds a filesystem path validator (which accepts images with fully-qualified paths and UNC paths), makes the URI validator reject any web-origin URIs (only `file` and `ms-*` are allowable), and suppresses warnings for any images that were not _directly_ set by the user.

Since we want to avoid using fragment images that fail validation, we no longer `Clear` each image property but rather set it to the blank or fallback value.

This does **not** actually add support for images at absolute paths beginning with `\\?\`. Such images are still rejected by `Image` and the other XAML fixtures we use for images. It's better than a warning, though.

Closes #18703
Closes #14143
Refs #18710
Refs #5204
Related to #18922 (http-origin icons will be blank everywhere and not just the jump list :wink:)

### CODE REVIEW

File: src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp [hunk 1]
```diff
@@ -488,6 +488,40 @@ void CascadiaSettings::_validateAllSchemesExist()
...
+        winrt::Windows::Foundation::Uri resourceUri{ resource };
+        if (!resourceUri)
+        {
+            return false;
+        }
+
+        const auto scheme{ resourceUri.SchemeName() };
+        std::wstring_view schemeSv{ scheme };
+        // Only file: URIs and ms-* URIs are permissible. http, https, ftp, gopher, etc. are not.
+        return til::equals_insensitive_ascii(scheme, L"file") || (schemeSv.size() > 3 && til::equals_insensitive_ascii(schemeSv.substr(0, 3), L"ms-"));
```
Comment (lhecker) [inline src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp]: image

Comment (DHowett) [reply src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp]: LOL. apparently yes.

**Review by lhecker — APPROVED** [review]
