### PR TITLE
Fix SUI race conditions when reloading settings

### LINKED ISSUE #9273: Settings reload causes occasional crash in SUI
It looks like manipulating the Navigation View's menu still wigs it out a bit.

```
08 (Inline Function) --------`--------     Microsoft_Terminal_Settings_Editor!winrt::check_hresult+0xb [E:\BA\271\s\src\cascadia\TerminalSettingsEditor\Generated Files\winrt\base.h @ 4825] 
09 (Inline Function) --------`--------     Microsoft_Terminal_Settings_Editor!winrt::impl::consume_Windows_Foundation_Collections_IVector<winrt::Windows::Foundation::Collections::IVector<winrt::Windows::Foundation::IInspectable>,winrt::Windows::Foundation::IInspectable>::ReplaceAll+0x4f [E:\BA\271\s\src\cascadia\TerminalSettingsEditor\Generated Files\winrt\Windows.Foundation.Collections.h @ 247] 
0a 00000068`690fefd0 00007ff8`83d99611     Microsoft_Terminal_Settings_Editor!winrt::Microsoft::Terminal::Settings::Editor::implementation::MainPage::UpdateSettings$_ResumeCoro$1+0xafd [E:\BA\271\s\src\cascadia\TerminalSettingsEditor\MainPage.cpp @ 117] 
0b (Inline Function) --------`--------     Microsoft_Terminal_Settings_Editor!std::experimental::coroutine_handle<void>::resume+0xd [C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\include\experimental\coroutine @ 107] 
0c (Inline Function) --------`--------     Microsoft_Terminal_Settings_Editor!std::experimental::coroutine_handle<void>::operator()+0xd [C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\include\experimental\coroutine @ 99] 
0d (Inline Function) --------`--------     Microsoft_Terminal_Settings_Editor!winrt::resume_foreground::__l2::awaitable::await_suspend::__l2::<lambda_2ab9998b3c4eacdb9b89a7a0699bc21a>::operator()+0xd [E:\BA\271\s\src\cascadia\TerminalSettingsEditor\Generated Files\winrt\Windows.UI.Core.h @ 3326] 
0e 00000068`690ff390 00007ff8`acb454a8     Microsoft_Terminal_Settings_Editor!winrt::impl::delegate<winrt::Windows::UI::Core::DispatchedHandler,<lambda_2ab9998b3c4eacdb9b89a7a0699bc21a> >::Invoke+0x11 [E:\BA\271\s\src\cascadia\TerminalSettingsEditor\Generated Files\winrt\Windows.UI.Core.h @ 1277] 
0f 00000068`690ff3c0 00007ff8`acb0505f     Windows_UI!CreateControlInput+0x1a658
```

### PR DESCRIPTION
**Pull request by lhecker**
## Summary of the Pull Request

This commit fixes various race conditions regarding the settings UI. It's unsafe to write to class members from background threads without acquiring mutexes or yielding to the main thread first.
By changing the settings reload code path to yield to the main thread early, we're able to cut down on code complexity and unsafe member accesses.

## PR Checklist
* [x] Closes #9273
* [x] I work here
* [x] Tests added/passed

## Validation Steps Performed

* Settings UI reloads without crashing ✔️

### CODE REVIEW

**Comment by lhecker** [comment]
This PR looks a lot better with whitespace changes suppressed.

File: src/cascadia/TerminalApp/AppLogic.cpp [hunk 1]
```diff
@@ -895,36 +895,25 @@ namespace winrt::TerminalApp::implementation
...
+        auto weakSelf = get_weak();
 
-        const winrt::hstring titleKey = USES_RESOURCE(L"ReloadJsonParseErrorTitle");
-        const winrt::hstring textKey = USES_RESOURCE(L"ReloadJsonParseErrorText");
-        _ShowLoadErrorsDialog(titleKey, textKey, _settingsLoadedResult);
-    }
-
-    fire_and_forget AppLogic::_ShowLoadWarningsDialogRoutine()
-    {
+        co_await winrt::resume_after(std::chrono::milliseconds(100));
```
Comment (carlos-zamora) [inline src/cascadia/TerminalApp/AppLogic.cpp:905]:
```suggestion
        co_await winrt::resume_after(std::chrono::milliseconds(50));
```
Shouldn't this be 50? because `FileActivityQuiesceTime` was originally 50?

Comment (miniksa) [inline src/cascadia/TerminalApp/AppLogic.cpp:905]: Why 100 now over 50?

**Review by carlos-zamora — APPROVED** [review]
Does this also address #9273?

**Review by miniksa — APPROVED** [review]
If this indeed works better, I'm good with it. Definitely a lot more straightforward.

File: src/cascadia/TerminalApp/AppLogic.cpp (hunk 1 above)
Comment (lhecker) [reply src/cascadia/TerminalApp/AppLogic.cpp:905]: On my system 50ms wasn't always enough and the settings UI reloaded twice instead of just once.

Comment (lhecker) [reply src/cascadia/TerminalApp/AppLogic.cpp:905]: On my system 50ms wasn't always enough and the settings UI reloaded twice instead of just once.
