### PR TITLE
Initialize all members of Terminal

### LINKED ISSUE #14129: 🐛 Strange bug with pasting sudo password via SSH on Linux 🐧
### Windows Terminal version

1.15.2713.0

### Windows build number

10.0.22621.608

### Other Software

```bash
kmatuszak@ubuntu:~$ bash --version
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)

kmatuszak@ubuntu:~$ sudo -V
Sudo version 1.8.31
Sudoers policy plugin version 1.8.31
Sudoers file grammar version 46
Sudoers I/O plugin version 1.8.31

kmatuszak@ubuntu:~$ ssh -V
OpenSSH_8.2p1 Ubuntu-4ubuntu0.5, OpenSSL 1.1.1f  31 Mar 2020

kmatuszak@ubuntu:~$ uname -r
5.15.0-48-generic

kmatuszak@ubuntu:~$ lsb_release -sd
Ubuntu 20.04.5 LTS
```

### Steps to reproduce

1. Connect to an Ubuntu server with password set to `HtJy*&fPMS4@K84C$RJfFT9*$#SR4E52` via SSH using Windows Terminal
2. Authenticate using your username and password by pasting the password, this will work fine
3. Try to run any sudo command which will ask for your sudo password, for example: `sudo apt update && sudo apt upgrade -y`
4. Paste your sudo password either by `CTRL+V` or `CTRL+SHIFT+V`

### Expected Behavior

Password should be accepted, but it is not:
```bash
kmatuszak@ubuntu:~$ sudo apt update && sudo apt upgrade -y
[sudo] password for kmatuszak:
Sorry, try again.
[sudo] password for kmatuszak:
```

### Actual Behavior

Password is not accepted either if pasted by `CTRL+V` or `CTRL+SHIFT+V`, but it works fine when typed by hand. Also password is accepted just fine if pasted in PuTTY. Other passwords also work just fine if pasted in Windows Terminal. The same password works just fine for initial authentication when connecting to an SSH server, but not for authenticating when running sudo.

### PR DESCRIPTION
**Pull request by lhecker**
The following members were not initialized during construction:
* `CursorType _defaultCursorShape`
* `bool _suppressApplicationTitle`
* `bool _bracketedPasteMode`
* `size_t _hyperlinkPatternId`
* `SelectionExpansion _multiClickSelectionMode`
* `til::CoordType _scrollbackLines`

Unlike gcc and clang, MSVC is fairly tame when it comes to removing code
tainted by undefined behavior, so the most likely affect this had is that
we were reading uninitialized memory.

Related to #14129.

### CODE REVIEW

**Review by zadjii-msft — APPROVED** [review]

File: src/cascadia/TerminalCore/Terminal.cpp [hunk 1]
```diff
@@ -37,24 +37,7 @@ static std::wstring _KeyEventsToText(std::deque<std::unique_ptr<IInputEvent>>& i
 }
 
 #pragma warning(suppress : 26455) // default constructor is throwing, too much effort to rearrange at this time.
-Terminal::Terminal() :
-    _mutableViewport{ Viewport::Empty() },
```
Comment (carlos-zamora) [inline src/cascadia/TerminalCore/Terminal.cpp:41]: This one didn't get copied over to the header. Should we initialize it there too?

File: src/cascadia/TerminalCore/Terminal.hpp [hunk 2]
```diff
@@ -356,27 +352,27 @@ class Microsoft::Terminal::Core::Terminal final :
...
-    bool _anchorInactiveSelectionEndpoint;
+    SelectionExpansion _multiClickSelectionMode = SelectionExpansion::Char;
+    SelectionInteractionMode _selectionMode = SelectionInteractionMode::None;
+    bool _selectionIsTargetingUrl = false;
+    SelectionEndpoint _selectionEndpoint = SelectionEndpoint::None;
+    bool _anchorInactiveSelectionEndpoint = false;
 #pragma endregion
 
     std::unique_ptr<TextBuffer> _mainBuffer;
     std::unique_ptr<TextBuffer> _altBuffer;
```
Comment (carlos-zamora) [inline src/cascadia/TerminalCore/Terminal.hpp:365]:
```suggestion
    std::unique_ptr<TextBuffer> _mainBuffer = nullptr;
    std::unique_ptr<TextBuffer> _altBuffer = nullptr;
```
no benefit to initializing these too? At least for consistency.

File: src/cascadia/TerminalCore/Terminal.hpp [hunk 3]
```diff
@@ -356,27 +352,27 @@ class Microsoft::Terminal::Core::Terminal final :
         til::point pivot;
     };
     std::optional<SelectionAnchors> _selection;
```
Comment (carlos-zamora) [inline src/cascadia/TerminalCore/Terminal.hpp:354]:
```suggestion
    std::optional<SelectionAnchors> _selection = std::nullopt;
```
this one also didn't get carried over from the cpp.

**Review by carlos-zamora — APPROVED** [review]
discussed offline. We good.

File: src/cascadia/TerminalCore/Terminal.hpp (hunk 3 above)
Comment (DHowett) [reply src/cascadia/TerminalCore/Terminal.hpp:354]: optionals are technically .. ah you probably talked about this
