### PR TITLE
Don't copy if there's no selection

### LINKED ISSUE #2258: Terminal process remains on background after exiting it
# Environment

```none
Windows build number: [run "ver" at a command prompt] 10.0.18362.267
Windows Terminal version (if applicable): v0.3.2142.0

Any other software? No
```

# Steps to reproduce
## Error 1: CMD
1. Open Windows Terminal
2. Open CMD tab
3. Close Terminal

## Error 2: Ubuntu
1. Open Windows Terminal
2. Open Ubuntu tab
3. Input any command
4. Close Terminal

# Actual behavior
## Error 1: CMD
pic1

## Error 2: Ubuntu
pic3

Terminal process remains on background and especially it occupies CPU resources excessively when after exiting terminal used as CMD.

When I use only PowerShell, terminal process disappears from background process list immediately after exiting terminal.

### LINKED ISSUE #2285: Ctrl C, when text is highlighted, should copy not cancel
# Environment

WIndows 10.0.18362.0 Microsoft Windows NT 10.0.18362.0 
Windows Terminal Preview 3

# Steps to reproduce

Select text.
Press Ctrl C

# Expected behavior

Per Windows behavior, Ctrl C should copy the text.

# Actual behavior

Ctrl C cancels, potentially terminating foreground jobs. This makes sense from a terminal point of view, but Windows users are used to hitting Ctrl C to copy text. That there is some text selected is a good indication that the user wishes to copy, not to cancel.

### PR DESCRIPTION
**Pull request by zadjii-msft**
## Summary of the Pull Request

Converts every action we have to a TypedEventHandler. These are in accordance with #1349. This allows us to _not_ handle some events, like the Copy event.

 
## References

Really heavily inspired by #1349. @DHowett-MSFT thinks we should ship this fix this month an _I agree_. Hence the PR before the spec is finished.

## PR Checklist
* [x] Closes #2285
* [x] I work here
* [ ] Tests added/passed - ooh there's an idea

### CODE REVIEW

File: src/cascadia/TerminalApp/ActionArgs.h [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+
+#include "../../cascadia/inc/cppwinrt_utils.h"
+
+// Notes on defining ActionArgs and ActionEventArgs:
+// * All properties specific to an action should be defined as in the ActionArgs
+//   class.
+// * ActionEventArgs should extend from the ActionArgs class, and add an
+//   aditional `Handled` property. For EventArgs that require actual args (ex:
+//   NewTabWithProfileEventArgs)
+// * For ActionEventArgs:
```
Comment (zadjii-msft) [inline src/cascadia/TerminalApp/ActionArgs.h]: This is out-of-date

File: src/cascadia/TerminalApp/AppKeyBindings.h [hunk 2]
```diff
@@ -76,3 +77,16 @@ namespace winrt::TerminalApp::factory_implementation
     {
     };
 }
+
+// public:
```
Comment (zadjii-msft) [inline src/cascadia/TerminalApp/AppKeyBindings.h]: ded

File: src/cascadia/inc/cppwinrt_utils.h [hunk 3]
```diff
@@ -57,6 +57,53 @@ private:
...
+// Use this in a classes header if you have a Windows.Foundation.TypedEventHandler
+#define TYPED_EVENT(name, sender, args)                                                                                                     \
+public:                                                                                                                                     \
+    winrt::event_token name(Windows::Foundation::TypedEventHandler<sender, args> const& handler) { return _##name##Handlers.add(handler); } \
+    void name(winrt::event_token const& token) noexcept { _##name##Handlers.remove(token); }                                                \
+                                                                                                                                            \
+private:                                                                                                                                    \
+    winrt::event<Windows::Foundation::TypedEventHandler<sender, args>> _##name##Handlers;
+
+// // Use this macro to quick implement both the getter and setter for a property.
```
Comment (zadjii-msft) [inline src/cascadia/inc/cppwinrt_utils.h]: ded

File: src/cascadia/TerminalApp/ActionArgs.idl [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+    };
+
+    [default_interface] runtimeclass ActionEventArgs : IActionEventArgs
+    {
+        ActionEventArgs(IActionArgs args);
+    };
+
+    [default_interface] runtimeclass CopyTextArgs : IActionArgs
+    {
+        Boolean TrimWhitespace;
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalApp/ActionArgs.idl]: I wonder. Should these all be `{get;}`? I do not want a recipient of a static instance of one of these to be able to, even accidentally, change it.

Comment (DHowett-MSFT) [reply src/cascadia/TerminalApp/ActionArgs.idl]: this would mandate that they are _set_ only by a private impl

File: src/cascadia/TerminalApp/App.cpp [hunk 5]
```diff
@@ -1451,6 +1459,153 @@ namespace winrt::TerminalApp::implementation
...
+        }
+    }
+
+    void App::_HandleSwitchToTab(const IInspectable& /*sender*/,
+                                 const TerminalApp::ActionEventArgs& args)
+    {
+        if (const auto& realArgs = args.ActionArgs().try_as<TerminalApp::SwitchToTabArgs>())
+        {
+            _SelectTab({ realArgs.TabIndex() });
+            args.Handled(true);
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalApp/App.cpp]: should this send-through if you do not have a tab with that number?

File: src/cascadia/TerminalApp/App.cpp [hunk 6]
```diff
@@ -1451,6 +1459,153 @@ namespace winrt::TerminalApp::implementation
...
+        }
+    }
+
+    void App::_HandleCopyText(const IInspectable& /*sender*/,
+                              const TerminalApp::ActionEventArgs& args)
+    {
+        if (const auto& realArgs = args.ActionArgs().try_as<TerminalApp::CopyTextArgs>())
+        {
+            args.Handled(_CopyText(realArgs.TrimWhitespace()));
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalApp/App.cpp]: eh this is the only one that does a nested call like this; nit: break out for clarity?

File: src/cascadia/TerminalApp/AppKeyBindings.cpp [hunk 7]
```diff
@@ -47,143 +46,331 @@ namespace winrt::TerminalApp::implementation
         switch (action)
         {
         case ShortcutAction::CopyText:
-            _CopyTextHandlers(true);
-            return true;
+        {
+            auto args = CopyTextArgs();
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalApp/AppKeyBindings.cpp]: nit: prefer `CopyTextArgs args{}`; -- otherwise looks like a function call

Comment (DHowett-MSFT) [reply src/cascadia/TerminalApp/AppKeyBindings.cpp]: for all of these

File: src/cascadia/TerminalApp/AppKeyBindings.idl [hunk 8]
```diff
@@ -1,16 +1,9 @@
 // Copyright (c) Microsoft Corporation.
 // Licensed under the MIT license.
+import "../ActionArgs.idl";
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalApp/AppKeyBindings.idl]: is this bit necessary, or can midl figure it out?

File: src/cascadia/TerminalApp/KeyBindingArgs.idl [hunk 9]
```diff
@@ -0,0 +1,60 @@
...
+    [default_interface] runtimeclass PrevTabEventArgs : IKeyBindingArgs{};
+    [default_interface] runtimeclass SplitVerticalEventArgs : IKeyBindingArgs{};
+    [default_interface] runtimeclass SplitHorizontalEventArgs : IKeyBindingArgs{};
+    [default_interface] runtimeclass SwitchToTabEventArgs : IKeyBindingArgs
+    {
+        Int32 ProfileIndex;
+    };
+    [default_interface] runtimeclass IncreaseFontSizeEventArgs : IKeyBindingArgs{};
+    [default_interface] runtimeclass DecreaseFontSizeEventArgs : IKeyBindingArgs{};
+    [default_interface] runtimeclass ScrollUpEventArgs : IKeyBindingArgs{};
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalApp/KeyBindingArgs.idl]: ded

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 10]
```diff
@@ -1792,6 +1792,11 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
         return std::pow(cursorDistanceFromBorder, 2.0) / 25.0 + 2.0;
     }
 
+    bool TermControl::HasSelection() const
+    {
+        return _terminal != nullptr && _terminal->IsAreaSelected();
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalControl/TermControl.cpp]: there's also `isSelectionActive`. @carlos-zamora can you clarify which to use here?

File: src/cascadia/inc/cppwinrt_utils.h [hunk 11]
```diff
@@ -57,6 +57,53 @@ private:
     winrt::event_token className::name(Windows::Foundation::TypedEventHandler<sender, args> const& handler) { return eventHandler.add(handler); } \
     void className::name(winrt::event_token const& token) noexcept { eventHandler.remove(token); }
 
+// This is a helper macro for both declaring the signature of an event, and
+// defining the body. Winrt events need a method for adding a callback to the
+// event and removing the callback. This macro will both declare the method
+// signatures and define them both for you, because they don't really vary from
+// event to event.
+// Use this in a classes header if you have a Windows.Foundation.TypedEventHandler
+#define TYPED_EVENT(name, sender, args)                                                                                                     \
```
Comment (DHowett-MSFT) [inline src/cascadia/inc/cppwinrt_utils.h]: is this just a combined version of `DEFINE_..WITH_TYPED` and `DECLARE_..WITH_TYPED`?

Comment (DHowett-MSFT) [reply src/cascadia/inc/cppwinrt_utils.h]: if so please consider using the decltype magic in #1104 to remove the need for `sender`!

File: src/cascadia/inc/cppwinrt_utils.h [hunk 12]
```diff
@@ -57,6 +57,53 @@ private:
...
+//     type name() const { return _##name; }             \
+//     void name(const type& value) { _##name = value; } \
+//                                                       \
+// private:                                              \
+//     type _##name;
+
+// Use this macro to quick implement both the getter and setter for a property.
+// This should only be used for simple types where there's no logic in the
+// getter/setter beyond just accessing/updating the value.
+#define GETSET_PROPERTY(type, name, defaultValue)     \
```
Comment (DHowett-MSFT) [inline src/cascadia/inc/cppwinrt_utils.h]: consider using `...` instead of `defaultValue`, and then using the `__VA_ARGS__` expandion down on line 94. That way, you can say `GETSET_PROPERTY(type, name)` and it will fill in defaultValue with [nothing]

**Comment by dsafa** [comment]
The PR mentions closing 22**58** but it should be closing 22**85** instead right?

**Comment by DHowett-MSFT** [comment]
@dsafa good catch. thanks.

**Comment by DHowett-MSFT** [comment]
I'd prefer the name be a little more.. specific on what it does. Fixing copy eating `^C` is a side effect of better design more than anything, but .. hm

File: src/cascadia/inc/cppwinrt_utils.h (hunk 11 above)
Comment (zadjii-msft) [reply src/cascadia/inc/cppwinrt_utils.h]: You better believe it is. However, I'm a little cautious on doing that as much as I want to. There's some stuff in #2208 that explicitly has a `Object` sender, where the `Object` is not the current type. So for those situations we _explicitly_ need to say `IInspectable` - would the magic still work for that case?

File: src/cascadia/TerminalApp/AppKeyBindings.idl (hunk 8 above)
Comment (zadjii-msft) [reply src/cascadia/TerminalApp/AppKeyBindings.idl]: > can midl figure it out 
image

File: src/cascadia/TerminalApp/App.cpp [hunk 13]
```diff
@@ -1052,10 +1053,17 @@ namespace winrt::TerminalApp::implementation
...
     // - trimTrailingWhitespace: enable removing any whitespace from copied selection
     //    and get text to appear on separate lines.
-    void App::_CopyText(const bool trimTrailingWhitespace)
+    // Return Value:
+    // - true iff we we able to copy text (if a selection was active)
+    bool App::_CopyText(const bool trimTrailingWhitespace)
     {
         const auto control = _GetFocusedControl();
-        control.CopySelectionToClipboard(trimTrailingWhitespace);
+        if (control.HasSelection())
```
Comment (carlos-zamora) [inline src/cascadia/TerminalApp/App.cpp]: This just feels weird. Like, SHOULD the app be aware of whether the control has a selection or not? I feel like that responsibility falls on the control, and the control should tell the app what happened.

Won't this become a problem if the `TermControl` is split from the `TermApp`?

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 10 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalControl/TermControl.cpp]: OMG. THEY'RE BOTH THE SAME. Adding to #1327.

File: src/cascadia/inc/cppwinrt_utils.h [hunk 14]
```diff
@@ -57,6 +57,42 @@ private:
...
+private:                                              \
+    type _##name{ __VA_ARGS__ };
+
+// Use this macro for quickly defining the factory_implementation part of a
+// class. CppWinrt requires these for the compiler, but more often than not,
+// they require no customization. See
+// https://docs.microsoft.com/en-us/uwp/cpp-ref-for-winrt/implements#marker-types
+// and https://docs.microsoft.com/en-us/uwp/cpp-ref-for-winrt/static-lifetime
+// for examples of when you might _not_ want to use this.
+#define BASIC_FACTORY(typeName)                                       \
```
Comment (carlos-zamora) [inline src/cascadia/inc/cppwinrt_utils.h]: While you're here, is there anywhere else we can use these new macros? Could you go ahead and apply them.

File: src/cascadia/TerminalApp/AppKeyBindings.cpp [hunk 15]
```diff
@@ -47,143 +46,331 @@ namespace winrt::TerminalApp::implementation
...
         case ShortcutAction::OpenSettings:
-            _OpenSettingsHandlers();
-            return true;
+        {
+            ActionEventArgs eventArgs{};
+            _OpenSettingsHandlers(*this, eventArgs);
+            return eventArgs.Handled();
+        }
 
         case ShortcutAction::NewTabProfile0:
```
[the remark this answers is not in the document]
Comment (zadjii-msft) [reply src/cascadia/TerminalApp/AppKeyBindings.cpp]: So I don't think this will work in the general case - right now there's a few actions with a single arg, but the macro would quickly get M A D once there were multiple arguments to an action. PLus there's other work coming here with pt 2 of #1349, so I think I'm going to leave it like this _for now_ and keep that in mind for the upcoming feature work here

File: src/cascadia/TerminalApp/App.h [hunk 16]
```diff
@@ -145,6 +145,26 @@ namespace winrt::TerminalApp::implementation
         void _PasteFromClipboardHandler(const IInspectable& sender, const Microsoft::Terminal::TerminalControl::PasteFromClipboardEventArgs& eventArgs);
 
         static void _SetAcceleratorForMenuItem(Windows::UI::Xaml::Controls::MenuFlyoutItem& menuItem, const winrt::Microsoft::Terminal::Settings::KeyChord& keyChord);
+
+        void _HandleNewTab(const IInspectable& sender, const TerminalApp::ActionEventArgs& args);
```
[the remark this answers is not in the document]
Comment (zadjii-msft) [reply src/cascadia/TerminalApp/App.h]: I so badly wanted to, yea It's happening

File: src/cascadia/inc/cppwinrt_utils.h (hunk 14 above)
Comment (carlos-zamora) [reply src/cascadia/inc/cppwinrt_utils.h]: Resolving. Moved issue to #2456

Comment (zadjii-msft) [reply src/cascadia/inc/cppwinrt_utils.h]: Moved to #2456

File: src/cascadia/TerminalApp/AppKeyBindings.cpp [hunk 17]
```diff
@@ -47,327 +47,327 @@ namespace winrt::TerminalApp::implementation
         {
         case ShortcutAction::CopyText:
         {
-            auto args = CopyTextArgs();
+            CopyTextArgs args{};
             args.TrimWhitespace(true);
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalApp/AppKeyBindings.cpp]: I'm surprised this setter actually works/exists. How?? It's not in the idl, and you're using the projected type (instead of the internal one)

Comment (DHowett-MSFT) [reply src/cascadia/TerminalApp/AppKeyBindings.cpp]: Also, you _should_ consider using the impl type using `winrt::make_self<xxxx::CopyTextArgs::implementation>()`

Comment (zadjii-msft) [reply src/cascadia/TerminalApp/AppKeyBindings.cpp]: It's because we're in the `TerminalApp::implementation` namespace, not the `TerminalApp` namespace. So we're making a `TerminalApp::implementation::CopyTextArgs`, not a projected type

Comment (DHowett-MSFT) [reply src/cascadia/TerminalApp/AppKeyBindings.cpp]: In that case this is technically a very bad thing! We should never stack-allocate implementation types. They _must_ be heap allocated

Comment (zadjii-msft) [reply src/cascadia/TerminalApp/AppKeyBindings.cpp]: wait _really_? Why does this seem to work then?

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 18]
```diff
@@ -1391,15 +1391,20 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
     // Arguments:
     // - trimTrailingWhitespace: enable removing any whitespace from copied selection
     //    and get text to appear on separate lines.
-    void TermControl::CopySelectionToClipboard(bool trimTrailingWhitespace)
+    bool TermControl::CopySelectionToClipboard(bool trimTrailingWhitespace)
     {
-        // extract text from buffer
-        const auto copiedData = _terminal->RetrieveSelectedTextFromBuffer(trimTrailingWhitespace);
+        if (_terminal != nullptr && _terminal->IsAreaSelected())
```
Comment (carlos-zamora) [inline src/cascadia/TerminalControl/TermControl.cpp]:
```suggestion
        if (_terminal->IsAreaSelected())
```
Is this even possible? Can we have a `TermControl` with no `Terminal`?
