### PR TITLE
Make sure VT reports still work when DECARM is disabled

### LINKED ISSUE #14208: Terminal reports no longer work in Vttest
### Windows Terminal version

Commit cacf66860f6c175672b3d030dcd166e372b2a8cc

### Windows build number

10.0.19044.2006

### Other Software

Vttest

### Steps to reproduce

1. Open a WSL shell in conhost or Terminal
2. Run `vttest`.
2. Select the _Private Device Attributes_ test (menu 6.4).

### Expected Behavior

The report received from the terminal should be:
```
<27> [ ? 1 ; 0 c
```

### Actual Behavior

In conhost it only seems to receive the initial `ESC` character, while in Terminal it receives nothing at all. And it's not just `DA` - other reports fail in a similar way.

I think this regression was caused by the recent `DECARM` merge (PR #13981), but I have no idea why. I'm still investigating.

The weird thing is that it works correctly in all of my own tests and applications. There's just something about the way vttest is reading the input that is causing it to fail.

### PR DESCRIPTION
**Pull request by j4james**
The way `DECARM` was initially implemented, we checked for repeated key
presses by matching the last recorded virtual key code, and used a 0 key
code to indicate that no key was pressed. This caused the VT query
responses to fail, because they generated key events with a 0 key code,
and that would end up being detected as a repeated key that should be
suppressed.

This PR fixes that issue by using a `std::optional` to track the last
key code, so if no key has been pressed we can represent that with
`std::nullopt`, and there's no way that can be confused with a genuine
key press.

The `DECARM` mode was introduced in PR #13981.

## Validation Steps Performed
I've manually tested in Vttest to confirm that the query reports are now
working again, even when `DECARM` is disabled. I've also checked that
`DECARM` itself it still working as expected.

Closes #14208

### CODE REVIEW

File: src/terminal/input/terminalInput.cpp [hunk 1]
```diff
@@ -551,20 +551,23 @@ bool TerminalInput::HandleKey(const IInputEvent* const pInEvent)
         return true;
     }
 
+    // Check if this key matches the last recorded key code.
+    const auto matchingLastKeyPress = _lastVirtualKeyCode && _lastVirtualKeyCode.value() == keyEvent.GetVirtualKeyCode();
```
Comment (DHowett) [inline src/terminal/input/terminalInput.cpp:555]: cute `std::optional` trick: you don't need to check whether the optional is populated before doing a comparison; `nullopt == T{}` will always return `false`

**Review by DHowett — APPROVED** [review]

File: src/terminal/input/terminalInput.cpp (hunk 1 above)
Comment (j4james) [reply src/terminal/input/terminalInput.cpp]: Oh wow, that's neat! Thank you!

**Review by lhecker — APPROVED** [review]
