### PR TITLE
Properly escape constructed `wt` command-lines

### LINKED ISSUE #11273: Opening a folder from ctx menu which has ";" in it's file name fails to open
### Windows Terminal version (or Windows build number)

Windows Terminal 1.10.2383.0; Microsoft Windows 10.0.19043

### Other Software

_No response_

### Steps to reproduce

1. Have a folder which contains ";" in it's name
2. Right click the folder and click "Open in Windows Terminal"

### Expected Behavior

Windows Terminal to open at the specified directory 

### Actual Behavior

Two tabs open saying 
```
tab1
[error 0x8007010b when launching `cmd.exe']
Could not access starting directory "<directory up to ;>"

tab2
[error 0x80070002 when launching `<after;>\.']
```
this happens regardless if im using powershell or cmd as default start up.

### PR DESCRIPTION
**Pull request by ianjoneill**
Ensures that command-lines constructed to invoke `wt` are escaped properly.

## PR Checklist
* [x] Closes #11273
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [x] Tests added/passed

## Detailed Description of the Pull Request / Additional comments
This was broken in two places - when constructing the command-line in the shell extension and in `NewTerminalArgs::ToCommandline()`.

Both places now invoke a shared method to escape the command-line arguments that require it.

## Validation Steps Performed
Added a test and additionally:
* Invoked the shell extension from `D:\Downloads\With;Semicolon`.
* Added a `newWindow` action to `settings.json` as below and ensured the new window opened without erroring.
  ```json
  {
    "command": 
    {
      "action": "newWindow",
      "tabTitle": "\";foo\\"
    },
    "keys": "ctrl+shift+s"
  }
  ```

### CODE REVIEW

File: src/cascadia/WinRTUtils/WtExeUtils.cpp [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+
+// Method Description:
+// - Escapes the given string so that it can be used as a command-line arg within a quoted string.
+// - e.g. given `";foo\` will return `\"\;foo\\` so that the caller can construct a command-line
+//   using something such as `fmt::format(L"wt --title \"{}\"", EscapeCommandlineArg(TabTitle()))`.
+// Arguments:
+// - arg - the command-line argument to escape.
+// Return Value:
+// - the escaped command-line argument.
+std::wstring EscapeCommandlineArg(const std::wstring_view arg)
```
Comment (miniksa) [inline src/cascadia/WinRTUtils/WtExeUtils.cpp:15]: I'm pretty sure that the `_TIL_PREFIXINLINE` that is used for the other methods in the _WtExeUtils.h_ file is so they can be header-only and not run into ODR failures. If you follow that pattern and put this code in the header, I don't think you need the CPP or to change the VCXPROJ file.

Comment (ianjoneill) [reply src/cascadia/WinRTUtils/WtExeUtils.cpp:15]: Yep, that works - done.

**Comment by ianjoneill** [comment]
Gah test flake

**Review by miniksa — APPROVED** [review]

File: src/cascadia/WinRTUtils/inc/WtExeUtils.h [hunk 2]
```diff
@@ -104,3 +104,29 @@ _TIL_INLINEPREFIX const std::wstring& GetWtExePath()
...
+        if (*it == L';' || *it == L'"')
+        {
+            stream << L'\\';
+        }
+        stream << *it;
+    }
+    if (arg.back() == L'\\')
+    {
+        stream << L'\\';
+    }
```
Comment (lhecker) [inline src/cascadia/WinRTUtils/inc/WtExeUtils.h:130]: This function doesn't handle escaping of backslashes correctly. This should be correct:
```cpp
_TIL_INLINEPREFIX std::wstring EscapeCommandlineArg(const std::wstring_view& arg)
{
    std::wstring out;
    out.reserve(arg.size() + 2);
    out.push_back(L'"');

    size_t backslashes = 0;
    for (const auto ch : arg) {
        if (ch == L'\\') {
            backslashes++;
        } else {
            if (ch == L';' || ch == L'"') {
                out.append(backslashes + 1, L'\\');
            }
            backslashes = 0;
        }
        out.push_back(x);
    }

    out.append(backslashes, L'\\');
    out.push_back(L'"');
    return out;
}
```

I've included the addition of quotes to the function, because I felt this to be more consistent.
If you dislike that please remove the two occurrences of `out.push_back(L'"');` and the `+ 2`.

**Comment by lhecker** [comment]
To be entirely honest I don't quite understand why this issue occurs... Semicolons aren't a special character according to https://docs.microsoft.com/en-us/cpp/c-language/parsing-c-command-line-arguments
And I don't believe other libraries or programming languages escape `;` for their calls to `CreateProcess` either...

**Comment by ianjoneill** [comment]
Semicolon is used by terminal as it's new-tab delimiter. i.e. `wt -d "D:\Downloads\With\;Semicolon" ; nt -d "D:\Downloads"` will open a window with two tabs - one in `D:\Downloads\With;Semicolon` and another in `D:\Downloads`.

The code for parsing commands live in the `AppCommandlineArgs` class, which is where the delimiter is defined. I don't think you can go with the heuristic of only treating semicolons within quoted strings as new-tab delimiters, as for the above command PS strips the quotes when executing the command.

image

FYI I can't help noticing that the command doesn't work in PS! Semicolon is a command delimiter, so you need to escape it with quotes!

image

Both of these "quirks" (having to escape semicolons inside an arg and having to quote the semicolon in PS) should probably be added to the docs. I can do that if you like?

File: src/cascadia/WinRTUtils/inc/WtExeUtils.h (hunk 2 above)
Comment (ianjoneill) [reply src/cascadia/WinRTUtils/inc/WtExeUtils.h:130]: Do the back-slashes need escaping? Opening a folder `D:\Downloads\;SemicolonStart` works fine as-is.

image

image

Side-note: I didn't realise C++ had support for for-each loops like in Java. I see that came in C++11.

Comment (ianjoneill) [reply src/cascadia/WinRTUtils/inc/WtExeUtils.h:130]: Ah it's quotes that are the problem, not semicolons. Will add a test and fix.
```json
{
    "command": 
    {
        "action": "newWindow",
        "tabTitle": "\\\";foo\\"
    },
    "keys": "ctrl+shift+s"
}
```

image

Comment (ianjoneill) [reply src/cascadia/WinRTUtils/inc/WtExeUtils.h]: Done

**Comment by ianjoneill** [comment]
This is the third time I've hit this test flake now. I don't have credentials to fire-off the build again and there's no more changes in `main` to merge in 😢 

```
Summary of Errors Outside of Tests:
    Error: Verify: IsLessThan(tries, 5): Make sure we set up the new console in time - Values (5, 5) [File: C:\a\_work\1\s\src\host\ft_host\InitTests.cpp, Function: ModuleSetup, Line: 279]
    Error: TAEF: Setup fixture 'ModuleSetup' for the scope 'C:\a\_work\1\s\bin\x64\Release\ConHost.Feature.Tests.dll' failed.
```

https://dev.azure.com/ms/terminal/_build/results?buildId=224859&view=logs&j=fe5d217b-357f-5a83-11fa-ea15ba02c406&t=bf0e56c7-0cfd-5451-dd9a-625e0a64945c&l=19854

**Review by zadjii-msft — APPROVED** [review]

File: src/cascadia/WinRTUtils/inc/WtExeUtils.h (hunk 2 above)
Comment (lhecker) [reply src/cascadia/WinRTUtils/inc/WtExeUtils.h]: > Do the back-slashes need escaping?

Yeah the command lines rules on Windows are just outright weird, but the gist is that `a\\\b` literally contains 3 backslashes. This is utterly confusing of course, but it's the way it is...
This means you need to escape slashes _if_ the following character is a character that needs escaping.
So `\\\b` needs to be escaped as `\\\b` (no escaping), whereas `\\\"` needs to be escaped as `\\\\\\\"` (escaping for all backslashes + the quote).

**Comment by lhecker** [comment]
To be honest I don't like this approach. I feel like Windows Terminal does the wrong thing by splitting all arguments by semicolon unconditionally. As far as I can see this is no different than cmd.exe splitting everything by space unconditionally, which is equally confusing. If we were to only split the startup actions by semicolon, then we'd solve this issue as well as improve the UX, by removing a surprising behavior (as semicolons should only have a special meaning for actions).

But I don't mind this PR, as it solves the most obvious case of this issue already.

**Review by lhecker — APPROVED** [review]

**Comment by miniksa** [comment]
Thanks, @ianjoneill!
