### PR TITLE
Correct the boundaries of the scrolling commands

### LINKED ISSUE #2174: The ScrollRegion clip rect is almost always wrong
# Environment

Windows build number: Version 10.0.18362.175
Windows Terminal version (if applicable): Commit a08666b58eb65b85ddf94e69892fa3e0a084ba98

It has to be a build that includes PR #1807, otherwise the scrolling probably wouldn't work at all.

# Steps to reproduce

The issue manifests in a number of different ways, but one of the most obvious examples looks like this:

1. Start the conhost: Host.exe
2. In the properties, make sure that the _Screen Buffer Height_ is larger than the _Window Height_.
3. Open a WSL bash shell.
4. Get a directory listing, or something that fills the screen with content.
5. Execute the following escape sequence, which sets the background color to red, and deletes 4 lines from the top of the screen:

       printf "\e[41m\e[H\e[4M"

# Expected behavior

The contents of the window should scroll up by 4 lines, revealing 4 blank red lines at the bottom of the screen.

# Actual behavior

The blank lines are black rather than red. However, if you scroll down to the very end of the buffer, you'll see the 4 red lines there instead.

I believe the problem is that the call to `ScrollRegion` should have been passed a clip rect matching the window/viewport, but instead was given a rect encompassing the full buffer size.

In this case, the offending code is in the `DoSrvPrivateModifyLinesImpl` function, which calls the `ScrollRegion` function via the `ScrollConsoleScreenBufferWImpl` method:

https://github.com/microsoft/terminal/blob/0e6f290806ef066e8ef29c0a933c83a0007eac98/src/host/getset.cpp#L2055-L2063

The `screenEdges` rect (with which the `srClip` rect is initialised), is set here:

https://github.com/microsoft/terminal/blob/0e6f290806ef066e8ef29c0a933c83a0007eac98/src/host/getset.cpp#L2036

# Additional examples

The IL (insert lines) escape sequence is similarly affected. When you insert lines onto the screen, anything that scrolls off the bottom of the viewport should be lost, but it's actually just scrolled into the forward buffer, so if you scroll down you can still see it.

For example, execute the sequence below, and then scroll the viewport down to reveal the _LAST LINE_ text that was shifted off screen (it should have been erased):

    printf "\e[100BLAST LINE\e[H\e[4L"

The SU (scroll up) and SD (scroll down) escape sequences almost get it right. They're using the viewport as their clip rect, but they're using an exclusive range, where the `ScrollRegion` function expects an inclusive range, so they're off by one.

For example, if you fill the screen with content as with the first test case, then execute the following escape sequence, which scrolls up by 4 lines:

    printf "\e[41m\e[H\e[4S"

That should reveal 4 blank red lines at the bottom of the screen, but actually only 3 of them are red - the fourth red line is off screen.

So far the only command I've found that gets the clip rect correct is the RI (reverse index) sequence.

### PR DESCRIPTION
**Pull request by j4james**
## Summary of the Pull Request

There are a number of VT escape sequences that rely on the `ScrollRegion` function to scroll the viewport ([RI](https://vt100.net/docs/vt510-rm/chapter4.html#T4-2), [DL](https://www.vt100.net/docs/vt510-rm/DL), [IL](https://www.vt100.net/docs/vt510-rm/IL), [SU](https://www.vt100.net/docs/vt510-rm/SU), [SD](https://www.vt100.net/docs/vt510-rm/SD), [ICH](https://www.vt100.net/docs/vt510-rm/ICH), and [DCH](https://www.vt100.net/docs/vt510-rm/DCH)), and all of them have got the clipping rect or scroll boundaries wrong in some way, resulting in content being scrolled off the screen that should have been clipped, revealed areas not being correctly filled, or parts of the screen not being moved that should have been. This PR attempts to fix all of those issues.

## PR Checklist
* [x] Closes #2174
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [x] Tests added/passed
* [ ] Requires documentation to be updated
* [x] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #2174

## Detailed Description of the Pull Request / Additional comments
The `ScrollRegion` function is what ultimately handles the scrolling, but it's typically called via the `ApiRoutines::ScrollConsoleScreenBufferWImpl` method, and it's the callers of that method that have needed correcting.

One "mistake" that many of these operations made, was in setting a clipping rect that was different from the scrolling rect. This should never have been necessary, since the area being scrolled is also the boundary into which the content needs to be clipped, so the easiest thing to do is just use the same rect for both parameters.

Another common mistake was in clipping the horizontal boundaries to the width of the viewport. But it's really the buffer width that represents the active width of the screen - the viewport width and offset are merely a window on that active area. As such, the viewport should only be used to clip vertically - the horizontal extent should typically be the full buffer width.

On that note, there is really no need to actually calculate the buffer width when we want to set any of the scrolling parameters to that width. The `ScrollRegion` function already takes care of clipping everything within the buffer boundary, so we can simply set the `Left` of the rect to `0` and the `Right` to `SHORT_MAX`.

More details on individual commands:

* RI (the `DoSrvPrivateReverseLineFeed` function)
  This now uses a single rect for both the scroll region and clipping boundary, and the width is set to `SHORT_MAX` to cover the full buffer width. Also the bottom of the scrolling region is now the bottom of the viewport (rather than bottom-1), otherwise it would be off by one.

* DL and IL (the `DoSrvPrivateModifyLinesImpl` function)
  Again this uses a single rect for both the scroll region and clipping boundary, and the width is set to `SHORT_MAX` to cover the full width. The most significant change, though, is that the bottom boundary is now the viewport bottom rather than the buffer bottom. Using the buffer bottom prevented it clipping the content that scrolled off screen when inserting, and failed to fill the revealed area when deleting.

* SU and SD (the `AdaptDispatch::_ScrollMovement` method)
  This was already using a single rect for both the scroll region and clipping boundary, but it was previously constrained to the width of the viewport rather than the buffer width, so some areas of the screen weren't correctly scrolled. Also, the bottom boundary was off by 1, because it was using an exclusive rect while the `ScrollRegion` function expects inclusive rects.

* ICH and DCH (the `AdaptDispatch::_InsertDeleteHelper` method)
  This method has been considerably simplified, because it was reimplementing a lot of functionality that was already provided by the `ScrollRegion` function. And like many of the other cases, it has been updated to use a single rect for both the scroll region and clipping boundary, and clip to the full buffer width rather than the viewport width.

I should add that if we were following the specs exactly, then the SU and SD commands should technically be panning the viewport over the buffer instead of moving the buffer contents within the viewport boundary. So SU would be the equivalent of a newline at the bottom of the viewport (assuming no margins). And SD would assumedly do the opposite, scrolling the back buffer back into view (an RI at the top of the viewport should do the same).

This doesn't seem to be something that is consistently implemented, though. Some terminals do implement SU as a viewport pan, but I haven't seen anyone implement SD or RI as a pan. If we do want to do something about this, I think it's best addressed as a separate issue.

## Validation Steps Performed

There were already existing tests for the SU, SD, ICH, and DCH commands, but they were implemented as adapter tests, which weren't effectively testing anything - the `ScrollConsoleScreenBufferW` method used in those tests was just a mock (an incomplete reimplementation of the `ScrollRegion` function), so confirming that the mock produced the correct result told you nothing about the validity of the real code.

To address that, I've now reimplemented those adapter tests as screen buffer tests. For the most part I've tried to duplicate the functionality of the original tests, but there are significant differences to account for the fact that scrolling region now covers the full width of the buffer rather than just the viewport width.

I've also extended those tests with additional coverage for the RI, DL, and IL commands, which are really just a variation of the SU and SD functionality.

### CODE REVIEW

**Comment by j4james** [comment]
@DHowett-MSFT When you've got a moment, could you please take a look at this failing build log and let me know if it's something obvious I've done wrong, or just a transient build failure?

It seems that the build timed out while running the unit tests in the x86 build. And if I've understood the log correctly, the last test to complete was _TestResize_, and I'm assuming the one that follows is _ScreenWidthAndHeightAreClampedToBounds_ (based on the successful x64 build log).

I don't think either of those have anything to do with the changes I've made, but I thought I might have done something that effected the global state in a way that would break another test. Is that possible?

Neither of those tests fails when run locally - tested with both x86 and x64 builds.

**Comment by DHowett-MSFT** [comment]
It's more likely that you've hit one of our flaky tests. Let's see.

/azp run

File: src/host/ut_host/ScreenBufferTests.cpp [hunk 1]
```diff
@@ -3051,6 +3055,499 @@ void ScreenBufferTests::DontResetColorsAboveVirtualBottom()
...
+    auto& gci = ServiceLocator::LocateGlobals().getConsoleInformation();
+    auto& si = gci.GetActiveOutputBuffer().GetActiveBuffer();
+    auto& row = si.GetTextBuffer().GetRowByOffset(position.Y);
+    row.WriteCells({ fillContent, fillAttr }, position.X, false);
+}
+
+template<class T>
+void _FillLine(int line, T fillContent, TextAttribute fillAttr)
+{
+    _FillLine({ 0, SHORT(line) }, fillContent, fillAttr);
```
Comment (DHowett-MSFT) [inline src/host/ut_host/ScreenBufferTests.cpp]: nit: gsl narrow_cast this `SHORT`

File: src/host/ut_host/ScreenBufferTests.cpp [hunk 2]
```diff
@@ -3051,6 +3055,499 @@ void ScreenBufferTests::DontResetColorsAboveVirtualBottom()
...
+        ++actual;
+        ++expected;
+    }
+    return true;
+};
+
+template<class T>
+bool _ValidateLineContains(int line, T expectedContent, TextAttribute expectedAttr)
+{
+    return _ValidateLineContains({ 0, SHORT(line) }, expectedContent, expectedAttr);
```
Comment (DHowett-MSFT) [inline src/host/ut_host/ScreenBufferTests.cpp]: (as above)

File: src/host/getset.cpp [hunk 3]
```diff
@@ -1356,24 +1356,21 @@ void DoSrvPrivateAllowCursorBlinking(SCREEN_INFORMATION& screenInfo, const bool
         if (screenInfo.IsCursorInMargins(oldCursorPosition))
         {
             // Cursor is at the top of the viewport
-            const COORD bufferSize = screenInfo.GetBufferSize().Dimensions();
             // Rectangle to cut out of the existing buffer
             SMALL_RECT srScroll;
             srScroll.Left = 0;
-            srScroll.Right = bufferSize.X;
+            srScroll.Right = SHORT_MAX;
```
Comment (miniksa) [inline src/host/getset.cpp]: Please leave comment on why SHORT_MAX is acceptable.

File: src/host/getset.cpp [hunk 4]
```diff
@@ -1356,24 +1356,21 @@ void DoSrvPrivateAllowCursorBlinking(SCREEN_INFORMATION& screenInfo, const bool
...
             // Cursor is at the top of the viewport
-            const COORD bufferSize = screenInfo.GetBufferSize().Dimensions();
             // Rectangle to cut out of the existing buffer
             SMALL_RECT srScroll;
             srScroll.Left = 0;
-            srScroll.Right = bufferSize.X;
+            srScroll.Right = SHORT_MAX;
             srScroll.Top = viewport.Top;
-            srScroll.Bottom = viewport.Bottom - 1;
+            srScroll.Bottom = viewport.Bottom;
```
Comment (miniksa) [inline src/host/getset.cpp]: Please leave comment on inclusive/exclusiveness of the rectangles here so we understand why this -1 mistake was made and how to not make it again when someone revisits this in the future.

**Comment by miniksa** [comment]
I'm good with this. Thank you for identifying the testing gap and resolving it at the same time. I appreciate the detailed explanation and reasoning in the issues.

All I left was a comment or two to ask you to embed key pieces of the explanation inside the code for future maintainers.

File: src/host/ut_host/ScreenBufferTests.cpp (hunk 1 above)
Comment (j4james) [reply src/host/ut_host/ScreenBufferTests.cpp]: I think I've done this for all my casts now. Although I've used `gsl::narrow` rather than `narrow_cast`, since that seems to be the preference in these tests, and I'm assuming it's safer.

File: src/host/getset.cpp (hunk 4 above)
Comment (j4james) [reply src/host/getset.cpp]: This particular case wasn't really a mistake, but it was unnecessary, and forced the need for a separate clip rect. However, I have now documented the inclusiveness of the scroll rects everywhere, and also commented the place that did actually require a conversion from exclusive to inclusive.

File: src/host/getset.cpp (hunk 3 above)
Comment (j4james) [reply src/host/getset.cpp]: Done.

**Comment by j4james** [comment]
@DHowett-MSFT I rebased this yesterday so there are no merge conflicts now. Is there anything else I need to do? I'm hoping the force-push isn't a problem, because I don't really know what I'm doing with git half the time.

**Comment by DHowett-MSFT** [comment]
Perfect! Thanks so much.

**Comment by j4james** [comment]
I was bit worried for a moment there. Glad it's not a problem. Thanks for the merge.

**Comment by DHowett-MSFT** [comment]
This went out for conhost in insider build 19002! Thanks :smile:
