### PR TITLE
Stop writing optional theme fields

### LINKED ISSUE #13544: Writing settings includes all of Theme's optional keys
Including `useMica`, which might confuse users when they find it and set it to true and it doesn't work.

### PR DESCRIPTION
**Pull request by lhecker**
Other settings model classes call `JsonUtils::SetValueForKey` with the
private `_##value` member as the value. Since `_##value` is an optional,
this prevented writing out unset, optional fields. The new `Themes` class
deviated from this and this commit brings it back in line with the others.

Closes #13544

## Validation Steps Performed
* Create a `{ "name": "test" }` theme
* Save settings via the UI
* Optional/Defaulted fields aren't written ✅

### CODE REVIEW

File: src/cascadia/TerminalSettingsModel/Theme.cpp [hunk 1]
```diff
@@ -31,6 +31,35 @@ static constexpr std::string_view NameKey{ "name" };
 static constexpr wchar_t RegKeyDwm[] = L"Software\\Microsoft\\Windows\\DWM";
 static constexpr wchar_t RegKeyAccentColor[] = L"AccentColor";
 
+#define THEME_SETTINGS_COPY(type, name, jsonKey, ...) \
+    result->_##name = _##name;
+
+#define THEME_SETTINGS_TO_JSON(type, name, jsonKey, ...) \
+    JsonUtils::SetValueForKey(json, jsonKey, _##name);
```
Comment (lhecker) [inline src/cascadia/TerminalSettingsModel/Theme.cpp:38]: Primary fix. Fixes most fields from appearing.

File: src/cascadia/TerminalSettingsModel/Theme.cpp [hunk 2]
```diff
@@ -222,11 +244,6 @@ THEME_OBJECT_CONVERTER(winrt::Microsoft::Terminal::Settings::Model, TabTheme, MT
 #undef THEME_SETTINGS_TO_JSON
 #undef THEME_OBJECT_CONVERTER
 
-Theme::Theme() noexcept :
-    Theme{ winrt::WUX::ElementTheme::Default }
-{
-}
```
Comment (lhecker) [inline src/cascadia/TerminalSettingsModel/Theme.cpp:228]: Secondary fix. Prevents this from appearing:
```json
"window": 
{
    "applicationTheme": "system",
    "useMica": false
}
```

**Review by DHowett — APPROVED** [review]
Thanks for digging into this!

**Review by zadjii-msft — APPROVED** [review]
thanks for fixing all my bugs 😄
