### PR TITLE
[A11y] Initialize and copy _blockRange in UIA Clone

### LINKED ISSUE #7960: UIA: incorrect word boundary
### STR:
1. In a Linux directory with several files, run `ls | pr -2Tn`.
2. Navigate the output by word (with either NVDA or Narrator).

### Expected behaviour:
Each word is announced.

### Observed behaviour:
When navigating across a line boundary, strange things happen: it looks like the entire line (except the last character or two) are included in a word!

Cc @carlos-zamora.

### PR DESCRIPTION
**Pull request by carlos-zamora**
## Summary of the Pull Request
#7960 was caused by `UiaTextRangeBase::_blockRange` not being initialized, thus pointing to random memory. In most cases, we initialize it properly in `RuntimeClassInitialize`, however, the copying version of `RuntimeClassInitialize` doesn't actually copy it over, resulting in it still containing random memory.

NVDA (and other screen readers) occasionally use `Clone` (really just the copy initializer), resulting in this bug occurring randomly.

## PR Checklist
* [X] Closes #7960 
* [X] Tests added/passed

## Validation Steps Performed
Test failed before the change, but passes after the change.

### CODE REVIEW

File: src/types/UiaTextRangeBase.hpp [hunk 1]
```diff
@@ -135,9 +135,9 @@ namespace Microsoft::Console::Types
         // measure units in the form [_start, _end).
         // These are in the TextBuffer coordinate space.
         // NOTE: _start is inclusive, but _end is exclusive
-        COORD _start{};
-        COORD _end{};
-        bool _blockRange;
+        COORD _start{ 0, 0 };
+        COORD _end{ 0, 0 };
```
Comment (carlos-zamora) [inline src/types/UiaTextRangeBase.hpp:139]: No particular reason these are initialized to `{0,0}`. We should never actually hit this because, as mentioned in the PR description, all of the `RuntimeClassInitialize` set these to a value. I'm fine leaving this to `{}` but wanted to know what your thoughts are.

**Comment by DHowett** [comment]
Careful with the terminology. RuntimeClassInitialize isn't actually a "constructor" in the C++ sense specifically!

**Comment by carlos-zamora** [comment]
> Careful with the terminology. RuntimeClassInitialize isn't actually a "constructor" in the C++ sense specifically!

Fixed!

File: src/types/UiaTextRangeBase.hpp (hunk 1 above)
Comment (lhecker) [reply src/types/UiaTextRangeBase.hpp:139]: I prefer `{}` because it signals to me that a (if the given type is a primitive type) specifically a `memset(this, 0, sizeof(*this))` is being done here. Others might have other opinions though...

**Review by lhecker — APPROVED** [review]
When Resharper comes out for VS 2022, we should all buy it together.
It has a clang-tidy integration that actually works. 😐

File: src/types/UiaTextRangeBase.hpp [hunk 2]
```diff
@@ -125,7 +125,7 @@ namespace Microsoft::Console::Types
 
         IRawElementProviderSimple* _pProvider{ nullptr };
 
-        std::wstring _wordDelimiters{};
+        std::wstring _wordDelimiters{ L"" };
```
Comment (lhecker) [inline src/types/UiaTextRangeBase.hpp:128]: Oh and I'd suggest not doing this, if possible. 😅
That constructor is not `constexpr`!

File: src/types/UiaTextRangeBase.hpp (hunk 1 above)
Comment (miniksa) [reply src/types/UiaTextRangeBase.hpp:139]: I prefer the `{}` as well here.

File: src/types/UiaTextRangeBase.hpp [hunk 3]
```diff
@@ -135,9 +135,9 @@ namespace Microsoft::Console::Types
         // measure units in the form [_start, _end).
         // These are in the TextBuffer coordinate space.
         // NOTE: _start is inclusive, but _end is exclusive
-        COORD _start{};
-        COORD _end{};
-        bool _blockRange;
+        COORD _start{ 0, 0 };
+        COORD _end{ 0, 0 };
+        bool _blockRange{ false };
```
Comment (miniksa) [inline src/types/UiaTextRangeBase.hpp:140]: You can do `{}` here too as the default for bool is false.

**Review by miniksa — CHANGES_REQUESTED** [review]
Waiting for pending comments to be complete.

**Review by DHowett — APPROVED** [review]

**Review by miniksa — APPROVED** [review]
