### PR TITLE
Fix ShowHide for DefTerm

### LINKED ISSUE #13066: [1.14] `ShowWindow(SW_MINIMIZE)` doesn't work anymore
From bug bash. 

1. put in file: 
```pwsh
$Source=@"
using System;
using System.Runtime.InteropServices;
public class Native {
[DllImport("user32.dll")]
public static extern bool ShowWindow(IntPtr hWnd, int nCmdShow);
[DllImport("kernel32.dll", SetLastError = true)]
public static extern IntPtr GetConsoleWindow();
}
"@
Add-Type -TypeDefinition $Source
[Native]::ShowWindow([Native]::GetConsoleWindow(), 6)
```

2. Run `.\hide.ps1`

expect:
* See a dterm sequence for hiding the window

actual:
* Terminal still visible.

### PR DESCRIPTION
**Pull request by zadjii-msft**
Well this one feels dumb.

Make sure to also initially set the visibility of ConPTY windows created for DefTerm connections.

* [x] Closes #13066 for real.
* [x] tested manually.

### CODE REVIEW

**Review by DHowett — APPROVED** [review]

File: src/cascadia/TerminalConnection/ConptyConnection.cpp [hunk 1]
```diff
@@ -340,6 +340,11 @@ namespace winrt::Microsoft::Terminal::TerminalConnection::implementation
 
             THROW_IF_FAILED(ConptyResizePseudoConsole(_hPC.get(), dimensions));
             THROW_IF_FAILED(ConptyReparentPseudoConsole(_hPC.get(), reinterpret_cast<HWND>(_initialParentHwnd)));
+
+            if (_initialVisibility)
+            {
+                THROW_IF_FAILED(ConptyShowHidePseudoConsole(_hPC.get(), _initialVisibility));
+            }
```
Comment (lhecker) [inline src/cascadia/TerminalConnection/ConptyConnection.cpp:347]: I'm a sucker for perf, but I think it'd be more robust to always call that function.
IMO this code is currently similar to:
```cpp
if (dimensions != COORD{ 120, 30 })
{
    THROW_IF_FAILED(ConptyResizePseudoConsole(_hPC.get(), dimensions));
}
```

**Review by lhecker — APPROVED** [review]

**Comment by DHowett** [comment]
@msftbot merge this in 1 minutes
