### PR TITLE
Fix LocalTests that were working before

### LINKED ISSUE #3536: TerminalAppLocalTests failing when running unit tests locally
# Environment

Windows build number: Version 10.0.18362.356
Windows Terminal version (if applicable): commit e2994ff8908f5a8418f24f2e2954a6c163f910b6

Any other software?
Visual Studio Community 2019 Version 16.3.8

# Steps to reproduce

1. Checkout a recent version of the Terminal.
2. Build the code.
3. Execute `runut` in the tools directory.

# Expected behavior

I'm used to having a few failures in the `TerminalInputModifierKeyTests`, and I know a couple of `TabTests` are blocked, but the rest of the tests I would usually expected to pass.

# Actual behavior

Recently I've been getting failures in `TerminalAppLocalTests` that I've never had before:

    TerminalAppLocalTests::SettingsTests::TryCreateWinRTType [Failed]
    TerminalAppLocalTests::KeyBindingsTests::ManyKeysSameAction [Failed]
    TerminalAppLocalTests::KeyBindingsTests::LayerKeybindings [Failed]
    TerminalAppLocalTests::KeyBindingsTests::UnbindKeybindings [Failed]

The `TryCreateWinRTType` test is failing because it's throwing an unidentified C++ exception (I think in the `TerminalSettings` constructor):
```
StartGroup: TerminalAppLocalTests::SettingsTests::TryCreateWinRTType
Error: Caught an unidentified C++ exception
EndGroup: TerminalAppLocalTests::SettingsTests::TryCreateWinRTType [Failed]
```
The `KeyBindingsTests` are failing because the `KeyChordSerialization::FromString` method is throwing an exception for all of the key chords, so nothing gets added to the `appKeyBindings` in the `LayerJson` call. The test output isn't particularly informative, but here's an example of one of them:

```
StartGroup: TerminalAppLocalTests::KeyBindingsTests::ManyKeysSameAction
Verify: IsTrue(parseResult)
Verify: IsTrue(parseResult)
Verify: IsTrue(parseResult)
Verify: IsNotNull(appKeyBindings)
Verify: AreEqual(0u, appKeyBindings->_keyShortcuts.size())
Error: Verify: AreEqual(1u, appKeyBindings->_keyShortcuts.size()) - Values (1, 0) [File: C:\Users\James\CPP\terminal\src\cascadia\LocalTests_TerminalApp\KeyBindingsTests.cpp, Function: TerminalAppLocalTests::KeyBindingsTests::ManyKeysSameAction, Line: 63]
EndGroup: TerminalAppLocalTests::KeyBindingsTests::ManyKeysSameAction [Failed]
```

Are these failures expected when running the tests locally or is it just me?

### PR DESCRIPTION
**Pull request by zadjii-msft**
## Summary of the Pull Request

Fixes the LocalTests that should work. This does _not_ fix the TabTests.

## PR Checklist
* [x] Closes #3536
* [x] I work here
* [x] This is literally making the tests work
* [n/a] Requires documentation to be updated

## Detailed Description of the Pull Request / Additional comments

In a previous PR, we broke unpackaged activation. This had the unintended side-effect of breaking these tests. The solution here is to run these unittests _packaged_.

This also makes things a little bit better for the TabTests, but doesn't fix them (inexplicably). A mail thread internally is tracking the progress of fixing those tests.

### CODE REVIEW

File: src/cascadia/LocalTests_TerminalApp/ColorSchemeTests.cpp [hunk 1]
```diff
@@ -20,15 +20,14 @@ namespace TerminalAppLocalTests
...
-        // packaged context. See TabTests.cpp for more details on that.
+        // Use a custom AppxManifest to ensure that we can activate winrt types
+        // from our test. This property will tell taef to manually use this as
+        // the AppxManifest for this test class.
+        // This does not yet work for anything XAML-y. See TabTests.cpp for more
+        // details on that.
         BEGIN_TEST_CLASS(ColorSchemeTests)
-            TEST_CLASS_PROPERTY(L"ActivationContext", L"TerminalApp.LocalTests.manifest")
+            TEST_CLASS_PROPERTY(L"RunAs", L"UAP")
+            TEST_CLASS_PROPERTY(L"UAP:AppXManifest", L"TerminalApp.LocalTests.AppxManifest.xml")
```
Comment (DHowett-MSFT) [inline src/cascadia/LocalTests_TerminalApp/ColorSchemeTests.cpp]: Is it possible, i wonder, to set a `UAP:AppxManifest` at the _module_ level (`MODULE_PROPERTY`) so that it applies to all _classes_ marked `RunAs=UAP`?

Comment (miniksa) [reply src/cascadia/LocalTests_TerminalApp/ColorSchemeTests.cpp]: For the most part, what you're saying is exactly how it works. I would recommend that it be placed in a module property. I usually throw those in the "Init" file in every test module. It doesn't look like LocalTests_TerminalApp has one yet, but it's probably time that it does because there's always going to be more test configuration steps we add.

Comment (miniksa) [reply src/cascadia/LocalTests_TerminalApp/ColorSchemeTests.cpp]: Also if literally every test in this module is supposed to be a UAP test, you could move the RunAs declaration up there too.

File: src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.AppxManifest.prototype.xml [hunk 2]
```diff
@@ -3,49 +3,48 @@
...
+     MUX.dll. This is done in a custom build step that automatically adds each
+     of our types to this manifest.
 
   2. We also _NEED_ the two vclibs listed under the `PackageDependency` block.
 
-  If your test fails for whatever reason, it's likely possible you're testing a
-  type that's _not_ included in this file for some reason. So, here be dragons. -->
+  -->
 
   <Identity Name="TerminalApp.LocalTests.Package"
```
Comment (miniksa) [inline src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.AppxManifest.prototype.xml]: Does this work in the gates now? Do we still need to call it LocalTests?

Comment (zadjii-msft) [reply src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.AppxManifest.prototype.xml]: I honestly don't know yet. I was going to do that as a part of a follow-up PR. I wanted to just get the tests unblocked for now. I think as part of the whole "make the tab tests work" bit, I'll have a chance to loop back on that subject.
