### PR TITLE
Emit lines wrapped due to spaces at the end correctly

### LINKED ISSUE #5291: wsl vim is horribly broken after #5181
image

tap output:

```
~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K~␛[K
```

no cursor movement after the EL :/

### PR DESCRIPTION
**Pull request by zadjii-msft**
## Summary of the Pull Request

When WSL vim prints the initial empty buffer (the one that's just a bunch of '\~'s), it prints this by doing the following:
* Print '\~' followed by enough spaces to clear the line
* Use CUP (`^[[H`) to move the cursor to the start of the next line
* repeat until the buffer is full

When we'd get the line of "\~     "... in conhost, we'd mark that line as wrapped. 

Logically, it doesn't really make any sense that when we follow that up by moving the cursor, the line is wrapped. However, this is just how conhost is right now. 
This wasn't ever a problem in just conhost before, because we really didn't care if lines in the alt buffer were "wrapped" or not. Plus, when vim would get resized, it would just reprint it's own buffer anyways. Nor was this a problem in conpty before this year (2020). We've only just recently added logic to conpty to try and preserve wrapped lines. 

Initially, I tried fixing this by breaking the line manually when the cursor was moved. This seemed to work great, except for the win32 vim.exe. Vim.exe doesn't emit a newline or a CUP to get to the next line. It just _goes for it_ and keeps printing. So there's _no way_ for us to know the line broke, because they're essentially just printing one long line, assuming we'll automatically move the cursor.

So instead, I'm making sure to emit the proper number of spaces at the end of a line when the line is wrapped. We won't do any funny business in that scenario and try to optimize for them, we'll _just print the spaces_.

## References

* #5181 - This change regressed this
* #4415 - Actually implemented wrapped lines in conpty

## PR Checklist
* [x] Closes #5291
* [x] I work here
* [x] Tests added/passed
* [n/a] Requires documentation to be updated

## Validation Steps Performed
* Wrote a unittest first and foremost
* Checked vtpipeterm to make sure vim still works
* checked Terminal to make sure vim still works

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
Can we be _certain_ that this will only happen for a cursor move immediately after we deferred, and only from the line that deferred? Is there any other state transition that might set/unset deferred that we aren't aware of? Do we un-wrap when we get a `\n` during deferral?

File: src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp [hunk 1]
```diff
@@ -2186,3 +2188,98 @@ void ConptyRoundtripTests::OutputWrappedLineWithSpaceAtBottomOfBuffer()
...
+    hostSm.ProcessString(L"\x1b[?1049h");
+    auto restoreBuffer = wil::scope_exit([&] { hostSm.ProcessString(L"\x1b[?1049l"); });
+    auto& altBuffer = gci.GetActiveOutputBuffer();
+    auto& altTextBuffer = altBuffer.GetTextBuffer();
+
+    // Go home and clear the screen.
+    hostSm.ProcessString(L"\x1b[H");
+    hostSm.ProcessString(L"\x1b[2J");
+
+    // Write out lines of '~' followed by enough spaes to fill the line.
```
Comment (DHowett-MSFT) [inline src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp:2251]:
```suggestion
    // Write out lines of '~' followed by enough spaces to fill the line.
```

I'm surprised spellbot didn't catch this.

**Comment by DHowett-MSFT** [comment]
> spaes
> Third-person singular simple present indicative form of spae

> spae (third-person singular simple present spaes, present participle spaeing, simple past and past participle spaed)
> (Scotland) To divine; foretell

File: src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp (hunk 1 above)
Comment (zadjii-msft) [reply src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp:2251]: I'm yanking that, because I don't think that's going to be relevant _ever_

**Comment by zadjii-msft** [comment]
> Can we be certain that this will only happen for a cursor move immediately after we deferred, and only from the line that deferred? 
No idea.

> Is there any other state transition that might set/unset deferred that we aren't aware of? 
Almost certainly. I don't really know.

> Do we un-wrap when we get a \n during deferral?
I'd presume, but I don't _know_. Wouldn't be hard to modify this test to test that as well.

**Comment by DHowett-MSFT** [comment]
I think CRLF is the more common name for CRNL

**Comment by zadjii-msft** [comment]
@msftbot make sure @miniksa signs off on this

**Comment by miniksa** [comment]
Hmmmm. This is a conundrum. So the way I thought of wrap in the first place was from a stream write. If you had nothing special happen as you passed the end of the line, it got marked as wrap. If literally any other operation happened, it stayed unmarked and wasn't a wrap. 

Is what's currently implemented between PTY/Terminal that if you get into a deferred cursor newline (you've written enough that the cursor is just sitting there waiting off the right boundary for the next character) that you also set the wrap at the same time? Should we not be waiting to set the wrap status until one more character arrives and it comes off the deferred newline onto the next line?

My concern here is that if it is implemented the way I'm describing (entering the deferred newline state sets wrap) that there are an unknowable set of circumstances where it may still be broken. You probably caught the major ones here with the cursor movements, but you're right to fear a long tail. 

If there's a strong reason why wrap marking happens on ENTER defer newline instead of on EXIT defer newline with the follow up character.... then I'm fine with this as I think you've caught the major scenarios the best you can and we'll keep improving over time. Just like everything else with our PTY.

However, if there's not a good reason... perhaps investigate the alternative wrap marking scenario instead?

**Comment by DHowett-MSFT** [comment]
@zadjii-msft idly wondering if fixing Niksa's concerns _also_ helps exact-wrap?

**Comment by zadjii-msft** [comment]
> If there's a strong reason why wrap marking happens on ENTER defer newline instead of on EXIT defer newline with the follow up character.... then I'm fine with this as I think you've caught the major scenarios the best you can and we'll keep improving over time. Just like everything else with our PTY.
> 
> However, if there's not a good reason... perhaps investigate the alternative wrap marking scenario instead?


Okay I don't have a good reason, so I'll investigate this tomorrow. This is a tad bit scary, since that's a bit more mucking with `WriteCharsLegacy` than I'd like. I believe that `screenInfo.Write` is the one that ends up marking the line as wrapped when we write to the last cell of the row, but I suppose it could check it when it's writing the next char of the following row.

**Comment by DHowett-MSFT** [comment]
@miniksa is there a world where we merge this because it fixes the significant regression in PTY wrapping and continue the investigation tomorrow?

**Comment by miniksa** [comment]
> @miniksa is there a world where we merge this because it fixes the significant regression in PTY wrapping and continue the investigation tomorrow?

A world with a p0 follow on filed and linked, sure.

**Comment by DHowett-MSFT** [comment]
vim.exe still doesn't work with this change.

image


it's also picked up a status line bug

image


also, when it _exits_ (!) and reprints the entire screen, it reprints the entire screen wrapped now

image

same symptom in the debug tap: no newlines between ~[K ~[K ~[K lines

**Comment by DHowett-MSFT** [comment]
I managed to get a duplicate status line in vim over ssh:

image

```
9␛[K␍␊␣10␛[K␍␊␣11␛[K␍␊␣12␛[K␍␊␣13␛[K␍␊␣14␛[K␍␊␣15␛[K␍␊␣16␛[K␍␊␣17␛[K␍␊␣18␛[K␍␊␣
19␛[K␍␊␣20␛[K␍␊␣21␛[K␍␊␣22␛[K␍␊␣23␛[K␍␊␣24␛[K␍␊␣25␛[K␍␊␣26␛[K␍␊␣27␛[K␍␊␣28␛[K␍␊␣
29␛[K␍␊␣30␣␛[4m␛[m␛[K
␛[24m␛[1m␛[30m␛[107m[No␣Name][+]␣␣[unix/]␣[/home/dhowett]␣␣29,1␣␣␣␣␣␣␣␣␣␣␣100%
␛[97m␛[49m␍␊--␣INSERT␣--␛[m␛[K␛[46C␛[1m␛[30m␛[107m␛[29;40H30,␛[28;5H␛[?25h
```

**Comment by DHowett-MSFT** [comment]
Does the pull request description here need updating before merge?

@miniksa's concern no longer applies as we're not changing the wrap state in the host.

**Comment by zadjii-msft** [comment]
> Does the pull request description here need updating before merge?

Certainly does, on it.

File: src/renderer/vt/paint.cpp [hunk 2]
```diff
@@ -443,15 +443,23 @@ using namespace Microsoft::Console::Types;
...
     //
     // GH#5161: Only removeSpaces when we're in the _newBottomLine state and the
     // line we're trying to print right now _actually is the bottom line_
-    const bool removeSpaces = useEraseChar ||
-                              _clearedAllThisFrame ||
-                              (_newBottomLine && coord.Y == _lastViewport.BottomInclusive());
+    //
+    // GH#5291: DON'T remove spaces when the row wrapped. We might need those
+    // spaces to preserve the wrap state of this line, or the cursor position.
+    // For example, vim.exe uses "~    "... to clear the line, and then leaves
```
Comment (DHowett-MSFT) [inline src/renderer/vt/paint.cpp:456]: We used to used to do something like "`80X 80C` (delete 80, move 80 right)" or "`K 80C`", right? Would that still work here? After all, we want the spaces to appear on the output but the wrap state to be maintained

is the real problem that we're not putting the cursor at the end of the line, and the spaces make up for that? and suppressing the spaces would mean we move the cursor wrong?

Comment (DHowett-MSFT) [reply src/renderer/vt/paint.cpp:456]: (I'm worried about the accidental deoptimization in nor using ECH/EL, i guess.)

Comment (zadjii-msft) [reply src/renderer/vt/paint.cpp:456]: if we just did the `^[[80X^[[80C`, then the line won't actually get wrapped. We need to emit an actual space there. It's a combo of both needing the spaces to trigger the wrapping logic, and needing the spaces to move the cursor.

Theoretically we could do `^[[79X^[[79C ` (with a space at the end), but that seems dirtier.

Comment (DHowett-MSFT) [reply src/renderer/vt/paint.cpp:456]: Fair enough.

File: src/host/screenInfo.cpp [hunk 3]
```diff
@@ -1663,6 +1663,19 @@ void SCREEN_INFORMATION::SetCursorDBMode(const bool DoubleCursor)
         return STATUS_INVALID_PARAMETER;
     }
 
+    // In GH#5291, we experimented with manually breaking the line on all cursor
+    // movements here. As we print lines into the buffer, we mark lines as
+    // wrapped when we print the last cell of the row, not the first cell of the
+    // subsequent row (the row the first line wrapped onto).
+    //
```
Comment (miniksa) [inline src/host/screenInfo.cpp:1670]: Nice warning to future us.

File: src/renderer/vt/paint.cpp (hunk 2 above)
Comment (miniksa) [reply src/renderer/vt/paint.cpp:456]: I'm concerned about the efficiency of it, though. We realized a lot of gains recently simply by emitting fewer things between the PTY and the Terminal. It's a little dirtier, but it's 69 fewer bytes to send, parse, and react to. That doesn't sound like much for one line, but it could be easily magnified over multiple lines and redraws.

Comment (zadjii-msft) [reply src/renderer/vt/paint.cpp:456]: So here's my thought - the client app was already emitting all these spaces intentionally. This was actually an optimization that conpty was doing _for them_, and an optimization that we were doing wrong (in this scenario). 

We'll still be sending the optimized sequences if the app does something like "Y &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; X", or if the app uses `^[[K` to clear the line (like a sane application should)

Comment (miniksa) [reply src/renderer/vt/paint.cpp:456]: Alright, then I'm fine with it. Thanks.
