### PR TITLE
Fix a bunch of spelling errors across the project

### LINKED ISSUE #4294: Spelling errors w/in source
# Environment

none.

# Steps to reproduce

Run a spell checker on the corpus

# Expected behavior

Preferably 0 identifiable spelling mistakes.

# Actual behavior

tokens including: `Constucts` and `seperate`

### PR DESCRIPTION
**Pull request by jsoref**
Generated by https://github.com/jsoref/spelling `f`; to maintain your repo, please consider `fchurn`

I generally try to ignore upstream bits. I've accidentally included some items from the `deps/` directory. I expect someone will give me a list of items to drop, I'm happy to drop whole files/directories, or to split the PR into multiple items (E.g. comments/locals/public).

Closes #4294

### CODE REVIEW

File: dep/Console/condrv.h [hunk 1]
```diff
@@ -158,7 +158,7 @@ typedef struct _CD_IO_DISPLAY_SIZE {
 
 typedef struct _CD_IO_CHARACTER {
     WCHAR Character; 
-    USHORT Atribute;
+    USHORT Attribute;
```
Comment (jsoref) [inline dep/Console/condrv.h]: This file is in a directory `dep/` which probably means I shouldn't be touching it. Just let me know, and I'll drop it/all similar items.

If there's an upstream that I can reach, at some point I can provide a similar PR to it, if it's identified here, I'll probably get to it sooner.

File: dep/chromium/MAINTAINER_README.md [hunk 2]
```diff
@@ -4,7 +4,7 @@ This was originally imported by @miniksa in January 2020.
 
 The provenance information (where it came from and which commit) is stored in the file `cgmanifest.json` in the same directory as this readme.
 Please update the provenance information in that file when ingesting an updated version of the dependent library.
-That provenance file is automatically read and inventoried by Microsoft systems to ensure compliance with appropiate governance standards.
+That provenance file is automatically read and inventoried by Microsoft systems to ensure compliance with appropriate governance standards.
```
Comment (jsoref) [inline dep/chromium/MAINTAINER_README.md]: I really need to apply my tooling to chromium...

File: doc/ORGANIZATION.md [hunk 3]
```diff
@@ -28,10 +28,10 @@
...
 		* `/src/cascadia/TerminalApp` - This DLL represents the implementation of the Windows Terminal application. This includes parsing settings, hosting tabs & panes with Terminals in them, and displaying other UI elements. This DLL is almost entirely UWP-like code, and shouldn't be doing any Win32-like UI work.
 		* `/src/cascadia/WindowsTerminal` - This EXE provides Win32 hosting for the TerminalApp. It will set up XAML islands, and is responsible for drawing the window, either as a standard window or with content in the titlebar (non-client area).
-		* `/src/cascadia/CasadiaPackage` - This is a project for packaging the Windows Terminal and its dependencies into an .appx/.msix for deploying to the machine.
+		* `/src/cascadia/CascadiaPackage` - This is a project for packaging the Windows Terminal and its dependencies into an .appx/.msix for deploying to the machine.
```
Comment (jsoref) [inline doc/ORGANIZATION.md]: I checked, and the package name really was misspelled in this documentation.

File: doc/specs/#1235 - Azure cloud shell connector/spec.md [hunk 4]
```diff
@@ -53,7 +53,7 @@ This feature will not impact reliability of Windows Terminal.
 
 ### Compatibility
 
-With the implementation being mostly decoupled from the Windows Terminal app itself, no existing code/behaviours should break due to this feature. 
+With the implementation being mostly decoupled from the Windows Terminal app itself, no existing code/behaviors should break due to this feature.
```
Comment (jsoref) [inline doc/specs/#1235 - Azure cloud shell connector/spec.md]: This corpus is almost entirely en-US, and the en-US spelling is dominant. That said, I can split/drop this if requested.

File: src/cascadia/TerminalApp/AppLogic.h [hunk 5]
```diff
@@ -57,7 +57,7 @@ namespace winrt::TerminalApp::implementation
         // the ctor, you're going to have a bad time. It'll mysteriously fail to
         // activate the AppLogic.
         // ALSO: If you add any UIElements as roots here, make sure they're
-        // updated in _AppLogiclyTheme. The root currently is _root.
+        // updated in _ApplyTheme. The root currently is _root.
```
Comment (jsoref) [inline src/cascadia/TerminalApp/AppLogic.h]: I'm fairly certain this is a correct fix... There's no sign of the string I'm changing.

File: src/cascadia/TerminalApp/FixVisualStudioBug.targets [hunk 6]
```diff
@@ -8,7 +8,7 @@
     not try to read it.
 
     Upstream problem report:
-    https://developercommunity.visualstudio.com/content/problem/629524/static-library-reference-causes-there-was-a-proble.html
+    https://developercommunity.visualstudio.com/content/problem/629524/static-library-reference-causes-there-was-a-problem.html
```
Comment (jsoref) [inline src/cascadia/TerminalApp/FixVisualStudioBug.targets]: The webserver here only cares about the directory number not the filename.

File: src/cascadia/TerminalConnection/ConptyConnection.cpp [hunk 7]
```diff
@@ -370,20 +370,20 @@ namespace winrt::Microsoft::Terminal::TerminalConnection::implementation
...
+            if (!_receivedFirstByte)
             {
                 const auto now = std::chrono::high_resolution_clock::now();
                 const std::chrono::duration<double> delta = now - _startTime;
 
 #pragma warning(suppress : 26477 26485 26494 26482 26446) // We don't control TraceLoggingWrite
                 TraceLoggingWrite(g_hTerminalConnectionProvider,
-                                  "RecievedFirstByte",
-                                  TraceLoggingDescription("An event emitted when the connection recieves the first byte"),
+                                  "ReceivedFirstByte",
```
Comment (jsoref) [inline src/cascadia/TerminalConnection/ConptyConnection.cpp]: It's possible this is an API of sorts.

File: src/host/ut_host/TextBufferTests.cpp [hunk 8]
```diff
@@ -1859,13 +1859,13 @@ void TextBufferTests::ResizeTraditionalRotationPreservesHighUnicode()
     // Fill it up with a sequence that will have to hit the high unicode storage.
     // This is the negative squared latin capital letter B emoji: 🅱
     // It's encoded in UTF-16, as needed by the buffer.
-    const auto bbutton = L"\xD83C\xDD71";
-    position = bbutton;
+    const auto bButton = L"\xD83C\xDD71";
+    position = bButton;
```
Comment (jsoref) [inline src/host/ut_host/TextBufferTests.cpp]: Other variables in this file use camelCase (such as `readBack`).

File: doc/specs/#1235 - Azure cloud shell connector/spec.md (hunk 4 above)
Comment (j4james) [reply doc/specs/#1235 - Azure cloud shell connector/spec.md]: As a native en-UK speaker, I do make an effort to use en-US spelling on this project, but I'm sure I slip up from time to time. It's not my call to make, but I'd personally have no problem with having my spelling corrected (I know I'm to blame for at least one of the "behaviours" picked up in this PR).

**Comment by jsoref** [comment]
@j4james: most of the builds finished ✔️ , but one was marked as ❌ (it appears to have been canceled) and one with ❕ (it also appears to have been canceled). Is this my fault? Is there something I'm supposed to do about them? -- Also, why the discrepancy, if the cause is a timeout in both cases, shouldn't the status be the same for both cases?

-- It is possible for my spelling PRs to break things (I start by excluding files and only checking files I haven't excluded -- so, if I exclude half of a change, a break is easy; also, if I'm changing an api consumer from some public thing, that could easily fail). That said, this PR has relatively few code changes for its size, and I don't see anything obvious, so I'm not actually expecting it to fail.

-- I do expect some feedback requesting that I drop some changes...

**Comment by miniksa** [comment]
Wow I like it, but it's going to take me some time to review this. I'll get back around to it.

**Comment by j4james** [comment]
> @j4james: most of the builds finished ✔️ , but one was marked as ❌ (it appears to have been canceled) and one with ❕ (it also appears to have been canceled). Is this my fault? Is there something I'm supposed to do about them? -- Also, why the discrepancy, if the cause is a timeout in both cases, shouldn't the status be the same for both cases?

I suspect it's not your fault. I couldn't see an actual compile error anywhere. I know the CI build does fail from time to time for reasons unrelated to the code, and usually when that happens one of the MS devs will ask the bot to rebuild. But you can also force a rebuild just by committing again, which you're going to have to do now anyway to rebase (or merge) with the master branch.

File: dep/Console/condrv.h (hunk 1 above)
Comment (jsoref) [reply dep/Console/condrv.h]: I've dropped the `dep/` dirs

**Comment by jsoref** [comment]
@j4james: As you're happy w/ rebase, I'm quite happy to rebase; rebased. (This dropped the `dep/` directory -- I'll fix those repos eventually.)

**Comment by j4james** [comment]
@jsoref I see the build failed again, but I'm still fairly certain this is not your fault. It's just timed out while running the unit tests, which I've seen happen many times before (I had the same problem in a PR of my own last night). I think the build bot is just having a bad day. Sooner or later someone from MS will likely sort it out.

**Comment by jsoref** [comment]
I've been having a run of bad luck w/ CI systems recently.

File: doc/specs/#1235 - Azure cloud shell connector/spec.md (hunk 4 above)
Comment (miniksa) [reply doc/specs/#1235 - Azure cloud shell connector/spec.md]: > Generated by [jsoref/spelling](https://github.com/jsoref/spelling) `f`; to maintain your repo, please consider `fchurn`

@jsoref, is there a way we can run this as a part of our CI and make it fail on a typo like the clang-tidy style rules do?

**Comment by miniksa** [comment]
> Generated by [jsoref/spelling](https://github.com/jsoref/spelling) `f`; to maintain your repo, please consider `fchurn`

@jsoref, is there a way we can run this as a part of our CI and make it fail on a typo like the clang-tidy style rules do?

File: doc/ORGANIZATION.md (hunk 3 above)
Comment (miniksa) [reply doc/ORGANIZATION.md]: Whoops. Good catch.

File: doc/specs/#1235 - Azure cloud shell connector/spec.md (hunk 4 above)
Comment (miniksa) [reply doc/specs/#1235 - Azure cloud shell connector/spec.md]: We would prefer to do the `en-US` just to be consistent, generally speaking.

We've had our share of `en-UK` from @bitcrazed dropped into assorted things, though. He very insistently says that Americans were given a perfectly good language that we decided to not use. 

I don't mind the mix of them. But if you want to enforce one, lean toward `en-US`.

File: src/cascadia/TerminalApp/AppLogic.h (hunk 5 above)
Comment (miniksa) [reply src/cascadia/TerminalApp/AppLogic.h]: Ugh. This was my fault. It was App --> AppLogic in an overzealous find/replace. I thought I fixed them all. So yeah. `Apply` is the correct revert.

File: src/cascadia/TerminalApp/FixVisualStudioBug.targets (hunk 6 above)
Comment (miniksa) [reply src/cascadia/TerminalApp/FixVisualStudioBug.targets]: OK, good with me then.

File: src/cascadia/TerminalConnection/ConptyConnection.cpp (hunk 7 above)
Comment (miniksa) [reply src/cascadia/TerminalConnection/ConptyConnection.cpp]: Nnnnn. @amit-msft, does this mess up reporting if we correct the typo? Or can you glue the two together on the back-end?

File: src/host/ft_host/API_CursorTests.cpp [hunk 9]
```diff
@@ -154,6 +154,6 @@ void CursorTests::TestSetConsoleCursorPosition()
     // Try several cases
     TestSetConsoleCursorPositionImpl(0, 0, TRUE); // Top left corner of buffer
     TestSetConsoleCursorPositionImpl(sbiInitial.dwSize.X - 1, sbiInitial.dwSize.Y - 1, TRUE); // Bottom right corner of buffer
-    TestSetConsoleCursorPositionImpl(sbiInitial.dwSize.X, sbiInitial.dwSize.Y, FALSE); // 1 beyond bottom right corner (the size is 1 larger than the array indicies)
```
Comment (miniksa) [inline src/host/ft_host/API_CursorTests.cpp]: Man I really need to learn how to spell `indices`.

File: src/host/ut_host/TextBufferTests.cpp (hunk 8 above)
Comment (miniksa) [reply src/host/ut_host/TextBufferTests.cpp]: I think the author was trying to avoid it looking like the hungarian notation for "boolean Button" as `bButton`. But it's a test, so I don't mind either way.

File: src/inc/CppCoreCheck/warnings.h [hunk 10]
```diff
@@ -57,7 +57,7 @@ enum ECppCoreCheckWarningCodes
     WARNING_NO_CONST_CAST_UNNECESSARY = 26465,                          // Don't use const_cast to cast away const. const_cast is not required; constness or volatility is not being removed by this conversion (type.3: http://go.microsoft.com/fwlink/p/?LinkID=620419).
     WARNING_NO_STATIC_DOWNCAST_POLYMORPHIC = 26466,                     // Don't use static_cast downcasts. A cast from a polymorphic type should use dynamic_cast (type.2: http://go.microsoft.com/fwlink/p/?LinkID=620418).
     WARNING_NO_REINTERPRET_CAST_FROM_VOID_PTR = 26471,                  // Don't use reinterpret_cast. A cast from void* can use static_cast (type.1: http://go.microsoft.com/fwlink/p/?LinkID=620417).
-    WARNING_NO_CASTS_FOR_ARITHMETIC_CONVERSION = 26472,                 // Don't use a static_cast for arithmetic conversions. Use brace initialization, gsl::narrow_cast or gsl::narow (type.1: http://go.microsoft.com/fwlink/p/?LinkID=620417).
+    WARNING_NO_CASTS_FOR_ARITHMETIC_CONVERSION = 26472,                 // Don't use a static_cast for arithmetic conversions. Use brace initialization, gsl::narrow_cast or gsl::narrow (type.1: http://go.microsoft.com/fwlink/p/?LinkID=620417).
```
Comment (miniksa) [inline src/inc/CppCoreCheck/warnings.h]: This was imported from somewhere, but it's fine to fix the typo.

File: src/renderer/wddmcon/WddmConRenderer.cpp [hunk 11]
```diff
@@ -248,10 +248,10 @@ bool WddmConEngine::IsInitialized()
             NewChar = &_displayState[rowIndex]->New[colIndex];
 
             OldChar->Character = NewChar->Character;
-            OldChar->Atribute = NewChar->Atribute;
+            OldChar->Attribute = NewChar->Attribute;
```
Comment (miniksa) [inline src/renderer/wddmcon/WddmConRenderer.cpp]: Nnnn. This one goes upstream. Can you revert and file a separate issue for any `Atribute` to `Attribute` that is on `WddmCon*` or `Bgfx*` related files (that is, any of them that are off of a `CD_IO_CHARACTER` struct as I have to go fix that in the driver declaration inside Windows too.)

File: src/renderer/wddmcon/main.cxx [hunk 12]
```diff
@@ -617,7 +617,7 @@ WDDMConUpdateDisplay(
 
                 pCtx->pwszGlyphRunAccel[ColumnIndex] = pRowInformation->New[ColumnIndex].Character;
                 if (ColumnIndexReadAhead != pCtx->DisplaySize.Width) {
-                    while (pRowInformation->New[ColumnIndex].Atribute == pRowInformation->New[ColumnIndexReadAhead].Atribute) {
+                    while (pRowInformation->New[ColumnIndex].Attribute == pRowInformation->New[ColumnIndexReadAhead].Attribute) {
```
Comment (miniksa) [inline src/renderer/wddmcon/main.cxx]: This file too, revert and link it to the new issue per the other comment.

File: src/interactivity/onecore/BgfxEngine.cpp [hunk 13]
```diff
@@ -138,7 +138,7 @@ BgfxEngine::BgfxEngine(PVOID SharedViewBase, LONG DisplayHeight, LONG DisplayWid
         for (SHORT j = 0; j < _displayWidth; j++)
         {
             NewRun[j].Character = L' ';
-            NewRun[j].Atribute = 0;
+            NewRun[j].Attribute = 0;
```
Comment (miniksa) [inline src/interactivity/onecore/BgfxEngine.cpp]: Can't fix this one either without upstream fix of `condrv.h`.

File: src/inc/CppCoreCheck/warnings.h (hunk 10 above)
Comment (miniksa) [reply src/inc/CppCoreCheck/warnings.h]: Looks like it came out of `C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\VS\include\CppCoreCheck\warnings.h` but the typo looks fixed at least of VS 16.4.4 on my system.

**Comment by jsoref** [comment]
@miniksa : yes, for an example of this integration, see: https://github.com/checkstyle/checkstyle/blob/master/.ci/test-spelling-unknown-words.sh 

Note: You also need to pick a dictionary. (For licensing reasons, I don't host my own.)

Ideally you want some sort of bucket which stores your previous set of whitelisted words. For checkstyle, that's: https://github.com/checkstyle/checkstyle/blob/master/.ci/jsoref-spellchecker/whitelist.words

The right place to store the whitelist is probably a bucket (AWS S3/Azure Blob Storage/GCloud Bucket) -- You don't really want to version the whitelist in the repo as it's a large ever changing file that your users don't actually care about.

I haven't written that code yet (I need to do it for my employer's project).

**Comment by miniksa** [comment]
>  whole fies/directories, 

files

Heheheh...

Also

> I've accidentally included some items from the `deps/` directory.

Be sure you leave those out, for the most part. They come from somewhere else. If you want to make a list of the dependencies that have spelling errors, we can file issues to get them fixed upstream and in here at the same time.

**Comment by miniksa** [comment]
> @miniksa : yes, for an example of this integration, see: https://github.com/checkstyle/checkstyle/blob/master/.ci/test-spelling-unknown-words.sh [](/checkstyle/checkstyle/blob/HEAD@{2020-02-04T17:50:23Z}/.ci/test-spelling-unknown-words.sh)
> 
> Note: You also need to pick a dictionary. (For licensing reasons, I don't host my own.)
> 
> Ideally you want some sort of bucket which stores your previous set of whitelisted words. For checkstyle, that's: https://github.com/checkstyle/checkstyle/blob/master/.ci/jsoref-spellchecker/whitelist.words [](/checkstyle/checkstyle/blob/HEAD@{2020-02-04T17:50:23Z}/.ci/jsoref-spellchecker/whitelist.words)
> 
> The right place to store the whitelist is probably a bucket (AWS S3/Azure Blob Storage/GCloud Bucket) -- You don't really want to version the whitelist in the repo as it's a large ever changing file that your users don't actually care about.
> 
> I haven't written that code yet (I need to do it for my employer's project).

Hm, OK. 

We have a bucket in the form of the bucket we use to store our NuGet packages. We could keep a list there.

We would also need to adapt your BASH script to likely a PowerShell one as that's what we'd have to run in the Windows Server CI.

As for a dictionary, maybe we can use one that's installed with Visual Studio? I'd bet there's one in there somewhere and it'll already be on the build agents.

Let's capture this stuff into another work item.

**Comment by jsoref** [comment]
I think at this point I've successfully dropped `deps/` unless there are similar things hiding elsewhere.

I can resurrect older versions of my changes to identify the things that could use fixing later once this is merged.

I won't have any time to work on this until tonight. (It looks like it's dropping 
53f3966, rebasing, and resolving merge conflicts.)

**Comment by miniksa** [comment]
> I think at this point I've successfully dropped `deps/` unless there are similar things hiding elsewhere.
> 
> I can resurrect older versions of my changes to identify the things that could use fixing later once this is merged.
> 
> I won't have any time to work on this until tonight. (It looks like it's dropping
> [53f3966](https://github.com/microsoft/terminal/commit/53f39669dcf8061becb16240c4be6793eca538c8), rebasing, and resolving merge conflicts.)

No problem. No rush. We're slow about PRing when we get busy; take your time fixing it up. Thanks for your effort.

File: src/host/ft_host/API_CursorTests.cpp (hunk 9 above)
Comment (jsoref) [reply src/host/ft_host/API_CursorTests.cpp]: Fwiw, it is a commonly corrupted word. (Although I haven't seen it much recently, it's definitely something I correct often enough.)

File: src/renderer/wddmcon/WddmConRenderer.cpp (hunk 11 above)
Comment (jsoref) [reply src/renderer/wddmcon/WddmConRenderer.cpp]: This is now #4469

@miniksa: Are all renderers in this same boat? In trying to rebase I ended up w/ additional changes to files as part of 5cde86c

Comment (miniksa) [reply src/renderer/wddmcon/WddmConRenderer.cpp]: No, just those two (`WddmConEngine` and `BgfxEngine`) because they're special to bring-up editions of Windows that we don't ship. The other renderers don't run data through the driver in the `CD_IO_CHARACTER` interface.

**Comment by jsoref** [comment]
Well, I rebased, and I still haven't had a single successful run. It looks like they're still timing out :-( -- on the bright side, that's already covered by https://github.com/microsoft/terminal/pull/4295#ref-issue-554167447

File: dep/CLI11/CLI11.hpp [hunk 14]
```diff
@@ -913,11 +913,11 @@ public:
...
         CLI11_ERROR_DEF(ParseError, ArgumentMismatch)
         CLI11_ERROR_SIMPLE(ArgumentMismatch)
-        ArgumentMismatch(std::string name, int expected, size_t recieved) :
+        ArgumentMismatch(std::string name, int expected, size_t received) :
             ArgumentMismatch(expected > 0 ? ("Expected exactly " + std::to_string(expected) + " arguments to " + name +
-                                             ", got " + std::to_string(recieved)) :
+                                             ", got " + std::to_string(received)) :
                                             ("Expected at least " + std::to_string(-expected) + " arguments to " + name +
-                                             ", got " + std::to_string(recieved)),
+                                             ", got " + std::to_string(received)),
```
Comment (miniksa) [inline dep/CLI11/CLI11.hpp]: Don't touch things in the ./dep/ folder, please. We need to submit this to be fixed upstream at https://github.com/CLIUtils/CLI11

**Comment by miniksa** [comment]
> Well, I rebased, and I still haven't had a single successful run. It looks like they're still timing out :-( -- on the bright side, that's already covered by [#4295 (reference)](https://github.com/microsoft/terminal/pull/4295#ref-issue-554167447)

I'm working on fixing the test runs. I'll go look at the one you split out next. Thanks.

Just the one comment left that CLI11 is an upstream dependency. So we should fix the typo there and consume (not here).

File: dep/CLI11/CLI11.hpp (hunk 14 above)
Comment (jsoref) [reply dep/CLI11/CLI11.hpp]: Not sure I'll have time to run my tooling this week. Might look on Sunday.

Dropped. (and I cloned the upstream repo.)

**Comment by miniksa** [comment]
Presuming the CI is happy now (tests should be better in master), I think we're good to go. Thank you.

File: dep/CLI11/CLI11.hpp (hunk 14 above)
Comment (jsoref) [reply dep/CLI11/CLI11.hpp]: CLIUtils/CLI11#429

Comment (miniksa) [reply dep/CLI11/CLI11.hpp]: Wow they merged that fast. I've now made #4546 to update our copy of CLIUtils. Thanks!

Comment (jsoref) [reply dep/CLI11/CLI11.hpp]: Yeah, I was really impressed by that.

**Comment by DHowett-MSFT** [comment]
:tada: Once again, thanks for the contribution!

This pull request was included in a set of conhost changes that was just
released with [Windows Insider Build 19603](https://blogs.windows.com/windowsexperience/2020/04/08/announcing-windows-10-insider-preview-build-19603/).
