### PR TITLE
Always create a new environment block before we spawn a process

### LINKED ISSUE #7204: PATH in child process includes Windows Terminal Preview installation directory, if started via Win+R wt.exe
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.19041.388]
Windows Terminal version (if applicable): Windows Terminal Preview 1.2.2022.0
```

# Steps to reproduce

1. Enable the `wt.exe` app execution alias of Windows Terminal Preview.
2. Press <kbd>Windows</kbd>+<kbd>R</kbd> to open the <samp>Run</samp> dialog box.
3. Type `wt.exe` and press <kbd>Enter</kbd> to start Windows Terminal Preview.
4. In Windows Terminal Preview, start the Command Prompt profile.
5. In the Command Prompt session, type `PATH` and press <kbd>Enter</kbd>.

# Expected behavior

The displayed value of PATH does not include the directory where Windows Terminal Preview was installed.

# Actual behavior

`C:\Program Files\WindowsApps\Microsoft.WindowsTerminalPreview_1.2.2022.0_x64__8wekyb3d8bbwe` is the first directory in PATH.

# Notes

This is presumably caused by the Registry values that were created by AppXSvc when Windows Terminal Preview was installed:

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\wt.exe]
@="C:\\Program Files\\WindowsApps\\Microsoft.WindowsTerminalPreview_1.2.2022.0_x64__8wekyb3d8bbwe\\wt.exe"
"Path"="C:\\Program Files\\WindowsApps\\Microsoft.WindowsTerminalPreview_1.2.2022.0_x64__8wekyb3d8bbwe"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\wt.exe]
@="C:\\Program Files\\WindowsApps\\Microsoft.WindowsTerminalPreview_1.2.2022.0_x64__8wekyb3d8bbwe\\wt.exe"
"Path"="C:\\Program Files\\WindowsApps\\Microsoft.WindowsTerminalPreview_1.2.2022.0_x64__8wekyb3d8bbwe"
```

According to [Application Registration](<https://docs.microsoft.com/windows/win32/shell/app-registration#using-the-app-paths-subkey> "Application Registration - Win32 apps | Microsoft Docs"), ShellExecuteEx prepends the data of the "Path" Registry value to the PATH environment variable of the new process. That seems unnecessary here, as selecting Windows Terminal Preview from the Start menu does not add to PATH.

Because non-packaged processes of users have no access to the "C:\Program Files\WindowsApps" directory, this addition to PATH perhaps does not cause problems. However, if `wt.exe` is run as administrator, then the PATH addition could cause a process in the terminal session to load DLLs from the installation directory of Windows Terminal Preview. (If a packaged application is run within the terminal session, then that too would have access to the directory, but [Search Order for Windows Store apps](https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#search-order-for-windows-store-apps) looks like the PATH environment variable will not affect DLL loading in that case.)

Related to <https://github.com/microsoft/terminal/pull/6860>, <https://github.com/microsoft/terminal/issues/6748>, <https://github.com/microsoft/terminal/issues/7188>. Found while searching for possible causes of <https://github.com/microsoft/terminal/issues/7195>.

### LINKED ISSUE #7239: Environment changes are only picked up upon full restart
# Environment

```none
Windows build number: Microsoft Windows NT 10.0.18362.0
Windows Terminal version (if applicable): 1.1.2021.0
```

# Steps to reproduce

* Launch Windows terminal
* Modify environment (e.g. via `Win+Pause` -> Advanced System Settings -> Environment variables)
* Open a new tab in the existing instance

# Expected behavior

* Should see environment change in the new tab

# Actual behavior

* Environment change only becomes available if the entire Terminal instance is restarted completely

### PR DESCRIPTION
**Pull request by DHowett**
This commit ensures that we always furnish a new process with the
cleanest, most up-to-date environment variables we can. There is a minor
cost here in that WT will no longer pass environment variables that it
itself inherited to its child processes.

This could be considered a reasonable sacrifice. It will also remove
somebody else's TERM, TERM_PROGRAM and TERM_PROGRAM_VERSION from the
environment, which could be considered a win.

I validated  that GetCurrentProcessToken returns a token we're
_technically able_ to use with this API; it is roughly equivalent to
OpenProcessToken(GetCurrentProcess) in that it returns the current
active _access token_ (which is what CreateEnvironmentBlock wants.)

There's been discussion about doing a 3-way merge between WT's
environment and the new one. This will be complicated and I'd like to
scream test the 0-way merge first ;P

Related to #1125 (but it does not close it or resolve any of the other
issues it calls out.)

Fixes #7239
Fixes #7204 ("App Paths" value creeping into wt's environment)

### CODE REVIEW

File: src/types/Environment.cpp [hunk 1]
```diff
@@ -9,30 +9,42 @@ using namespace ::Microsoft::Console::Utils;
...
 // Function Description:
 // - Updates an EnvironmentVariableMapW with the current process's unicode
 //   environment variables ignoring ones already set in the provided map.
 // Arguments:
 // - map: The map to populate with the current processes's environment variables.
+// - environmentBlock: Optional environment block to use when filling map. If omitted,
+//   defaults to the current environment.
 // Return Value:
 // - S_OK if we succeeded, or an appropriate HRESULT for failing
-HRESULT Microsoft::Console::Utils::UpdateEnvironmentMapW(EnvironmentVariableMapW& map) noexcept
```
Comment (KalleOlaviNiemitalo) [inline src/types/Environment.cpp:19]: It seems a bit strange to take `std::optional<void*>` and then treat `nullptr` as equivalent to `std::nullopt`. I don't see `std::optional<T*>` anywhere else in the source tree. But perhaps it makes sense if you consider `nullptr` an invalid argument here.

Comment (zadjii-msft) [reply src/types/Environment.cpp:19]: I concur - why isn't the parameter just a `EnvironmentBlockPtr` that we compare to `nullptr` to check if it was provided?

**Comment by zadjii-msft** [comment]
I'm cool with this as-is, but I think I want to hear the `optional<void*>` discussion first

**Comment by DHowett** [comment]
So, that's a fair question and one for which I don't really have a good answer. `std::optional<void*>` was driven by my innate aversion to a raw `void*`. I would have passed an `EnvironmentBlockPtr` as @zadjii-msft suggested, but since that's a typedef over `wil::unique_any` it enforces ownership semantics at the function signature. It's generally incorrect for a function to require particular ownership semantics of its parameters.

I'm fine just dropping it to `void*`, but I somewhat wish that we had a better type to express that it's an environment block. I'd much rather not write more boilerplate just to do so, so I'm not interested in introducing another manual reference counting struct type. 🤷

**Comment by DHowett** [comment]
There, I switched it to a `std::optional<gsl::not_null<void*>>`.

**Comment by KalleOlaviNiemitalo** [comment]
I don't see any `gsl::not_null` in the diff….

**Comment by DHowett** [comment]
Well, I decided that an optional-not-null-void* was the same as a void* so I cut out the middle party 😉

**Comment by fcharlie** [comment]
This PR broke my [baulk](https://github.com/baulk/baulk), I implemented a package manager [baulk](https://github.com/baulk/baulk), baulk provides baulktermainl and baulk-dock After initializing specific environment variables, start Windows Terminal, and then perform the corresponding operations in the shell.
But this PR removed this possibility, which made me have to think of other ways to solve this problem.

**Comment by DHowett** [comment]
You know, I'm not surprised that we broke somebody ... but I _am_ surprised that we broke somebody **so instantly**. Thanks for letting us know.

It looks like you fixed it on your end, so we're not going to index too much on getting a fix in for 1.3... but we'll keep use cases like that in mind.

**Comment by DHowett** [comment]
Also, thanks for testing top-of-tree builds so much :smile:

**Comment by DHowett** [comment]
https://github.com/microsoft/terminal/issues/7399
It turns out that the _Volatile Environment_ isn't part of the new block. How silly.

File: src/types/Environment.cpp [hunk 2]
```diff
@@ -9,30 +9,42 @@ using namespace ::Microsoft::Console::Utils;
 // We cannot use spand or not_null because we're dealing with \0\0-terminated buffers of unknown length
 #pragma warning(disable : 26481 26429)
 
+// Function Description:
+// - Wraps win32's CreateEnvironmentBlock to return a smart pointer.
+EnvironmentBlockPtr Microsoft::Console::Utils::CreateEnvironmentBlock()
+{
+    void* newEnvironmentBlock{ nullptr };
+    if (!::CreateEnvironmentBlock(&newEnvironmentBlock, GetCurrentProcessToken(), FALSE))
```
Comment (DHowett) [inline src/types/Environment.cpp:17]: @nathpete can you test what happens if you replace `GetCurrentProcessToken` with..


```c++
auto processToken{ wil::open_current_access_token() };
CreateEnv(...processToken.get()...)
```

If that doesn't restore `USERNAME`, can you try passing `TOKEN_QUERY|TOKEN_DUPLICATE` as the first arg to open_current_acc?

Comment (DHowett) [reply src/types/Environment.cpp:17]: whoops - @nathpete-msft

Comment (nathpete-msft) [reply src/types/Environment.cpp:17]:
```
auto processToken{ wil::open_current_access_token(TOKEN_QUERY | TOKEN_DUPLICATE) };
```
That does it!

Comment (KalleOlaviNiemitalo) [reply src/types/Environment.cpp:17]: Ugh, I am surprised CreateEnvironmentBlock behaves that way. Tested:

- `NULL` => USERNAME=SYSTEM
- `GetCurrentProcessToken()` => no USERNAME
- `GetCurrentThreadEffectiveToken()` => no USERNAME
- `(HANDLE)0x123456` => error 6

Perhaps it is because GetCurrentProcessToken() lacks TOKEN_DUPLICATE access.

Comment (DHowett) [reply src/types/Environment.cpp:17]: You know, you're probably right about that last bit. That makes sense.

At least there's a nice WIL helper for us to get our current effective access token :smile:

**Comment by kpentaris** [comment]
@DHowett Hello. Has this issue regressed? I'm on WT version 1.11.2921.0 and I'm having the same problem albeit using the "setx /M" command to update the system wide env variable. Is this different?

**Comment by KalleOlaviNiemitalo** [comment]
@kpentaris, these changes have been repeatedly reverted from stable releases of Windows Terminal, e.g. in <https://github.com/microsoft/terminal/commit/616a71dd23e8fff717919c20c382edeaf59f433a> for Windows Terminal 1.11.2921.0. If you want this feature, use Windows Terminal Preview for now. I guess it will continue this way until the Windows PowerShell (x86) incompatibility <https://github.com/microsoft/terminal/issues/7418> is fixed somehow.

**Comment by zadjii-msft** [comment]
@kpentaris I believe we never ended up shipping this to stable, and it's only in the Preview builds of the Terminal

**Comment by kpentaris** [comment]
D'oh! It's actually mentioned in the latest commit... Very well, hopefully at some point this is fixed.
