### PR TITLE
Fix the terminal snapping across DPI boundaries strangely.

### LINKED ISSUE #2057: Dragging into corner for 1/4 view will result tab to be smaller than maximum
Dragged into corner of windows to snap into 1/4 view
image

Using WINDOWS KEY + Arrows will not produce same result (is good)
Expected result:
image

### PR DESCRIPTION
**Pull request by zadjii-msft**
## Summary of the Pull Request

When we snap across a DPI boundary, we'll get the DPI changed message _after_ the resize message. So when we try to calculate the new terminal position, we'll use the _old_ DPI to calculate the size. When snapping to a lower DPI, this means the terminal will be smaller, with "padding" all around the actual app. 

Instead, when we get a new DPI, force us to update out UI layout for the new DPI.

## PR Checklist
* [x] Closes #2057
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [N/A] Tests added/passed

## Validation Steps Performed

Snapped the terminal a bunch back and forth on my monitors.

Checked this works fine for `showTabsInTitlebar: false`.

Tried snapping into corners from high to low back to high DPI

### CODE REVIEW

File: src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp [hunk 1]
```diff
@@ -623,6 +623,12 @@ RECT NonClientIslandWindow::GetMaxWindowRectInPixels(const RECT* const prcSugges
             break;
         }
     }
+    case WM_DPICHANGED:
+    {
+        auto lprcNewScale = reinterpret_cast<RECT*>(lParam);
+        OnSize(RECT_WIDTH(lprcNewScale), RECT_HEIGHT(lprcNewScale));
```
Comment (DHowett-MSFT) [inline src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp]: should basewindow call this?

Comment (zadjii-msft) [reply src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp]: @DHowett-MSFT I honestly don't know. IslandWindow seems fine right now as it is. Do you want this for 0.3? If so, I won't have time to spin builds to verify before EOD. I'm fine making a follow up to investigate doing this. Thoughts?

Comment (DHowett-MSFT) [reply src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp]: this fix is fine
