### PR TITLE
Code to add WSLProfiles.

### LINKED ISSUE #441: Does not detect wsl distro
* Your Windows build number:  10.0.18890.1000

* What you're doing and what's happening: Open windows terminal and press the down arrow, it shows cmd and PowerShell but not wsl, I have wsl debian installed.

* What's wrong / what should be happening instead: It should let me select wsl debian

### PR DESCRIPTION
**Pull request by JBanks**
## Summary of the Pull Request
This code generates a list of WSL Distributions to be added to the drop down list.  It was tested manually with a setup holding a single WSL distribution.
 
## PR Checklist
* [x] Closes #441
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Requires documentation to be updated
* [x] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #441

## Detailed Description of the Pull Request / Additional comments
While implementing the stream I was getting stuck in a loop inside of the `wfstream `functions when I ran past the end of the output.  None of the `wfstream`'s health functions seemed to be working properly (`::rdstate()`, `::eof()`, etc) so I used `peeknamedpipe `to get the length and stopped reading from the pipe before this became an issue.  I'd like to find a more clean method

### CODE REVIEW

File: src/cascadia/TerminalApp/CascadiaSettings.cpp [hunk 1]
```diff
@@ -4,6 +4,9 @@
 #include "pch.h"
 #include <argb.h>
 #include <conattrs.hpp>
+#include <fstream>
```
Comment (miniksa) [inline src/cascadia/TerminalApp/CascadiaSettings.cpp]: This should likely go into `LibraryIncludes.h`

File: src/cascadia/TerminalApp/CascadiaSettings.cpp [hunk 2]
```diff
@@ -227,6 +230,53 @@ void CascadiaSettings::_CreateDefaultProfiles()
...
+    HANDLE writePipe;
+    SECURITY_ATTRIBUTES sa{ sizeof(sa), nullptr, true };
+    if (CreatePipe(&readPipe, &writePipe, &sa, 0)) {
+        STARTUPINFO si{};
+        si.cb = sizeof(si);
+        si.dwFlags = STARTF_USESTDHANDLES;
+        si.hStdOutput = writePipe;
+        si.hStdError = writePipe;
+
+        PROCESS_INFORMATION pi{};
```
Comment (miniksa) [inline src/cascadia/TerminalApp/CascadiaSettings.cpp]: Try `wil::unique_process_information` on for size to safely manage the handles that come back in a `PROCESS_INFORMATION` structure.

File: src/cascadia/TerminalApp/TerminalApp.vcxproj [hunk 3]
```diff
@@ -118,7 +110,7 @@
   </PropertyGroup>
   <ItemDefinitionGroup>
     <Link>
-      <AdditionalDependencies>WindowsApp.lib;shell32.lib;%(AdditionalDependencies)</AdditionalDependencies>
+      <AdditionalDependencies>Kernel32.lib;WindowsApp.lib;shell32.lib;%(AdditionalDependencies)</AdditionalDependencies>
```
Comment (miniksa) [inline src/cascadia/TerminalApp/TerminalApp.vcxproj]: The `kernel32.lib` reference makes me uncomfortable. The calls should already be accessible through one of the onecore umbrella libs, which I believe should be getting imported somewhere in here. (I thought I saw @DHowett-MSFT use those at one point...)

Which specific method is forcing you to add this reference?

File: src/cascadia/TerminalApp/CascadiaSettings.cpp [hunk 4]
```diff
@@ -227,6 +230,53 @@ void CascadiaSettings::_CreateDefaultProfiles()
 
     _profiles.emplace_back(powershellProfile);
     _profiles.emplace_back(cmdProfile);
+
+    HANDLE readPipe;
```
Comment (miniksa) [inline src/cascadia/TerminalApp/CascadiaSettings.cpp]: Consider `wil::unique_handle` here for lifetime management.

File: src/cascadia/TerminalApp/CascadiaSettings.cpp [hunk 5]
```diff
@@ -227,6 +230,53 @@ void CascadiaSettings::_CreateDefaultProfiles()
 
     _profiles.emplace_back(powershellProfile);
     _profiles.emplace_back(cmdProfile);
+
```
Comment (miniksa) [inline src/cascadia/TerminalApp/CascadiaSettings.cpp]: I would greatly prefer if you put this entire block of stuff into its own function that is something like `std::vector<TerminalApp::Profile> _CreateWslProfiles()` or `void _CreateWslProfiles(std::vector<TerminalApp::Profile>& profileStorage)`.

Then inside here, wrap the entire thing with 
```
try
{

}
CATCH_LOG();
```
since the failure to enumerate and add the WSL profiles is something that shouldn't stop the default profile creation, but should probably be logged in case someone wants to diagnose why it failed.

Finally, rework the contents of the method to follow the `wil/result.h` based style of running down the method and doing `THROW_IF_WIN32_BOOL_FALSE` on methods like `CreatePipe`, `CreateProcessW`, `PeekNamedPipe`, `GetExitCodeProcess` and checking the result code in your own way for `WaitForSingleObject` to verify it is returning according to the conditions you expect and not a failure case, throwing if it is unexpected.

e.g.
```
THROW_IF_WIN32_BOOL_FALSE(CreatePipe(&readPipe, &writePipe, &sa, 0));

STARTUPINFO si{};

....

THROW_IF_WIN32_BOOL_FALSE(CreateProcessW(...));

...
```

File: src/cascadia/TerminalApp/CascadiaSettings.cpp (hunk 2 above)
Comment (JBanks) [reply src/cascadia/TerminalApp/CascadiaSettings.cpp]: That's great, cleaned up all my handles at the bottom.

File: src/cascadia/TerminalApp/TerminalApp.vcxproj (hunk 3 above)
Comment (JBanks) [reply src/cascadia/TerminalApp/TerminalApp.vcxproj]: You're right, I just tried it and it wasn't required anymore.  I can't recall which function required it either.

File: src/cascadia/TerminalApp/CascadiaSettings.cpp (hunk 5 above)
Comment (JBanks) [reply src/cascadia/TerminalApp/CascadiaSettings.cpp]: I like the pass-by-reference version better, so I went with that one.

Everything is now in a try block, with a few exceptions thrown.

File: src/cascadia/TerminalApp/CascadiaSettings.cpp [hunk 6]
```diff
@@ -467,6 +472,61 @@ bool CascadiaSettings::_isPowerShellCoreInstalledInPath(const std::wstring_view
...
+// - Adds all of the WSL profiles to the provided container.
+// Arguments:
+// - A ref to the profiles container where the WSL profiles are to be added
+// Return Value:
+// - <none>
+void CascadiaSettings::_CreateWslProfiles(std::vector<TerminalApp::Profile>& profileStorage)
+{
+    try
+    {
+        DWORD bytesAvailable = 0;
```
Comment (mauve) [inline src/cascadia/TerminalApp/CascadiaSettings.cpp]: http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es21-dont-introduce-a-variable-or-constant-before-you-need-to-use-it

several variables can be moved closer to its first use

File: src/cascadia/TerminalApp/CascadiaSettings.cpp [hunk 7]
```diff
@@ -467,6 +472,61 @@ bool CascadiaSettings::_isPowerShellCoreInstalledInPath(const std::wstring_view
...
+            THROW_HR(E_INVALIDARG);
+        }
+        THROW_IF_WIN32_BOOL_FALSE(PeekNamedPipe(readPipe.get(), nullptr, NULL, nullptr, &bytesAvailable, nullptr));
+        FILE* hPipe = _wfdopen(_open_osfhandle((intptr_t)readPipe.get(), _O_WTEXT | _O_RDONLY), L"r");
+            //don't call fclose on hPipe because the readPipe handle is managed by wil and this will cause an error.
+        std::wfstream pipe{ hPipe };
+        std::getline(pipe, wline); //remove the header from the output.
+        while (pipe.tellp() < bytesAvailable) {
+            std::getline(pipe, wline);
+            std::wstringstream   wlinestream(wline);
```
Comment (mauve) [inline src/cascadia/TerminalApp/CascadiaSettings.cpp]: *nitpick*: double-space

File: src/cascadia/TerminalApp/CascadiaSettings.cpp [hunk 8]
```diff
@@ -467,6 +472,61 @@ bool CascadiaSettings::_isPowerShellCoreInstalledInPath(const std::wstring_view
...
+// Return Value:
+// - <none>
+void CascadiaSettings::_CreateWslProfiles(std::vector<TerminalApp::Profile>& profileStorage)
+{
+    try
+    {
+        DWORD bytesAvailable = 0;
+        DWORD exitCode = 0;
+        std::wstring command = L"wsl.exe --list";
+        std::wstring wline = L"";
```
Comment (mauve) [inline src/cascadia/TerminalApp/CascadiaSettings.cpp]: I don't think the explicit initializer is needed.

File: src/cascadia/TerminalApp/CascadiaSettings.cpp [hunk 9]
```diff
@@ -467,6 +472,61 @@ bool CascadiaSettings::_isPowerShellCoreInstalledInPath(const std::wstring_view
...
+        std::wstring distName = L"";
```
Comment (mauve) [inline src/cascadia/TerminalApp/CascadiaSettings.cpp]: I don't think the explicit initializer is needed.

File: src/cascadia/TerminalApp/CascadiaSettings.cpp (hunk 6 above)
Comment (JBanks) [reply src/cascadia/TerminalApp/CascadiaSettings.cpp]: Ah!  Thanks for the update!

File: src/cascadia/TerminalApp/CascadiaSettings.cpp (hunk 7 above)
Comment (JBanks) [reply src/cascadia/TerminalApp/CascadiaSettings.cpp]: Wow, it was actually a triple-space!  Fixed now, thanks.

File: src/cascadia/TerminalApp/CascadiaSettings.cpp (hunk 9 above)
Comment (JBanks) [reply src/cascadia/TerminalApp/CascadiaSettings.cpp]: Removed them all.  Cheers,

File: src/cascadia/TerminalApp/CascadiaSettings.cpp [hunk 10]
```diff
@@ -517,6 +472,61 @@ bool CascadiaSettings::_isPowerShellCoreInstalledInPath(const std::wstring_view
...
+            if (wlinestream) {
+                std::getline(wlinestream, distName, L' ');
+                auto WSLDistro{ _CreateDefaultProfile(distName) };
+                WSLDistro.SetCommandline(L"wsl.exe -d " + distName);
+                WSLDistro.SetColorScheme({ L"Campbell" });
+                profileStorage.emplace_back(WSLDistro);
+            }
+        }
+    }
+    CATCH_LOG()
```
Comment (miniksa) [inline src/cascadia/TerminalApp/CascadiaSettings.cpp]: Hm, I was specifically thinking about letting the exception leave this function and try/catch it on the caller side. Did you put it all in here for a specific reason?

File: src/cascadia/TerminalApp/CascadiaSettings.cpp [hunk 11]
```diff
@@ -517,6 +472,61 @@ bool CascadiaSettings::_isPowerShellCoreInstalledInPath(const std::wstring_view
...
+        si.dwFlags = STARTF_USESTDHANDLES;
+        si.hStdOutput = writePipe.get();
+        si.hStdError = writePipe.get();
+        wil::unique_process_information pi{};
+
+        THROW_IF_WIN32_BOOL_FALSE(CreateProcessW(nullptr, const_cast<LPWSTR>(command.c_str()), nullptr, nullptr,
+                                                    TRUE, CREATE_NO_WINDOW, nullptr, nullptr, &si, &pi));
+        if (WaitForSingleObject(pi.hProcess, INFINITE) != NULL)
+        {
+            throw;
```
Comment (miniksa) [inline src/cascadia/TerminalApp/CascadiaSettings.cpp]: Should probably throw *something* in particular like with `THROW_HR()`

File: src/cascadia/TerminalApp/CascadiaSettings.cpp (hunk 10 above)
Comment (JBanks) [reply src/cascadia/TerminalApp/CascadiaSettings.cpp]: I put it inside of the function so that it would keep the calling function clean, and I felt that for the sake of modularization (even though it's only one call) the function should handle the errors inside rather than outside.

I suppose having the try block outside allows the user to determine what to do based on different errors that could be thrown.

File: src/cascadia/TerminalApp/CascadiaSettings.cpp (hunk 11 above)
Comment (JBanks) [reply src/cascadia/TerminalApp/CascadiaSettings.cpp]: I went through part of the list (damn, there's a lot of these!)  I narrowed it down to the following:

```
ERROR_INVALID_DATA
ERROR_READ_FAULT
ERROR_SEM_TIMEOUT
ERROR_WAIT_NO_CHILDREN
ERROR_CHILD_NOT_COMPLETE
ERROR_UNHANDLED_EXCEPTION
```

and went with these:

```
ERROR_CHILD_NOT_COMPLETE
ERROR_UNHANDLED_EXCEPTION
```

File: src/cascadia/TerminalApp/CascadiaSettings.cpp (hunk 10 above)
Comment (miniksa) [reply src/cascadia/TerminalApp/CascadiaSettings.cpp]: I'm not going to push hard on this being either way. I don't have a massive preference. It's just I would have personally put it outside in this circumstance, so I toss out the suggestion. Internally, we'd say "I don't mind if you 'won't fix' this comment." :)

File: src/cascadia/TerminalApp/CascadiaSettings.cpp [hunk 12]
```diff
@@ -480,51 +483,54 @@ bool CascadiaSettings::_isPowerShellCoreInstalledInPath(const std::wstring_view
...
+    THROW_IF_WIN32_BOOL_FALSE(CreateProcessW(nullptr, const_cast<LPWSTR>(command.c_str()), nullptr, nullptr,
+                                                TRUE, CREATE_NO_WINDOW, nullptr, nullptr, &si, &pi));
+    switch (WaitForSingleObject(pi.hProcess, INFINITE)) {
+    case WAIT_OBJECT_0:
+        break;
+    case WAIT_ABANDONED:
+    case WAIT_TIMEOUT:
+        THROW_HR(ERROR_CHILD_NOT_COMPLETE);
+    case WAIT_FAILED:
+        //The function has failed. To get extended error information, call GetLastError.
```
Comment (miniksa) [inline src/cascadia/TerminalApp/CascadiaSettings.cpp]: I think there's THROW_LAST_ERROR()

File: src/cascadia/TerminalApp/CascadiaSettings.cpp (hunk 11 above)
Comment (miniksa) [reply src/cascadia/TerminalApp/CascadiaSettings.cpp]: Yeah that works.

File: src/cascadia/TerminalApp/CascadiaSettings.cpp (hunk 12 above)
Comment (JBanks) [reply src/cascadia/TerminalApp/CascadiaSettings.cpp]: There is.  Incoming commit.

File: src/cascadia/TerminalApp/CascadiaSettings.cpp (hunk 10 above)
Comment (JBanks) [reply src/cascadia/TerminalApp/CascadiaSettings.cpp]: Already done, no sweat from me.  I do like the look at the function more since it reigns in some of the excess indentation.

File: src/cascadia/TerminalApp/CascadiaSettings.cpp (hunk 1 above)
Comment (JBanks) [reply src/cascadia/TerminalApp/CascadiaSettings.cpp]: Should it only be `fstream `that goes in there, or should all 3?  Do you mind explaining what makes it/them special compared to `<argb.h>` and `<conattrs.hpp>`

Comment (miniksa) [reply src/cascadia/TerminalApp/CascadiaSettings.cpp]: Uh, <fstream> I believe is a platform library. Like I think it comes from STL, right?

The other two are headers from our own project, so not libraries.

Comment (JBanks) [reply src/cascadia/TerminalApp/CascadiaSettings.cpp]: Ok, I guess it's a nuance that's lost on me right now.  I see that STL, WIL, and a few other odds and ends have been included in there.  I'll just take it as it is and wait until someone who knows what they're doing tells me where to throw things :)

File: src/cascadia/TerminalApp/CascadiaSettings.cpp (hunk 5 above)
Comment (dlong11) [reply src/cascadia/TerminalApp/CascadiaSettings.cpp]: I know @miniksa suggested _CreateWslProfiles(std::vector<TerminalApp::Profile>& profileStorage) - but this doesn't jive with the CppCoreGuidelines.
[F.20: For “out” output values, prefer return values to output parameters](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#f20-for-out-output-values-prefer-return-values-to-output-parameters) 

@miniksa - Is this a recommendation that you guys aren't recommending/enforcing?  Just curious for future code reviews.

Comment (JBanks) [reply src/cascadia/TerminalApp/CascadiaSettings.cpp]: @dlong11 That is for values that are not "in-out", which is what we're treating the profiles list as. http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#f17-for-in-out-parameters-pass-by-reference-to-non-const

Comment (dlong11) [reply src/cascadia/TerminalApp/CascadiaSettings.cpp]: @JBanks Sorry about that I was looking at the modified function and the name.  I should have looked closer to the calling code.

Comment (JBanks) [reply src/cascadia/TerminalApp/CascadiaSettings.cpp]: @dlong11 No problem at all.  I appreciate you taking the time to look things over!

File: src/cascadia/TerminalApp/CascadiaSettings.cpp [hunk 13]
```diff
@@ -526,6 +526,7 @@ void CascadiaSettings::_AppendWslProfiles(std::vector<TerminalApp::Profile>& pro
             std::getline(wlinestream, distName, L' ');
             auto WSLDistro{ _CreateDefaultProfile(distName) };
             WSLDistro.SetCommandline(L"wsl.exe -d " + distName);
+            WSLDistro.SetStartingDirectory(L"~");
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalApp/CascadiaSettings.cpp]: alas, this will almost certainly not work properly. we'll pass it to `CreateProcess`, which doesn't understand linux paths.

Comment (JBanks) [reply src/cascadia/TerminalApp/CascadiaSettings.cpp]: Yeah, it has the workaround to set it to `DEFAULT_STARTINGDIRECTORY` right now, and I figured it would make it future proof once something happens with #592.  I can change it back if you like, but #592 also seems like some low hanging fruit that I could work on after this.

File: src/cascadia/TerminalApp/CascadiaSettings.cpp [hunk 14]
```diff
@@ -467,6 +474,65 @@ bool CascadiaSettings::_isPowerShellCoreInstalledInPath(const std::wstring_view
...
+    si.cb = sizeof(si);
+    si.dwFlags = STARTF_USESTDHANDLES;
+    si.hStdOutput = writePipe.get();
+    si.hStdError = writePipe.get();
+    wil::unique_process_information pi{};
+    std::wstring command = L"wsl.exe --list";
+
+    THROW_IF_WIN32_BOOL_FALSE(CreateProcessW(nullptr, const_cast<LPWSTR>(command.c_str()), nullptr, nullptr,
+                                                TRUE, CREATE_NO_WINDOW, nullptr, nullptr, &si, &pi));
+    switch (WaitForSingleObject(pi.hProcess, INFINITE)) {
```
Comment (zadjii-msft) [inline src/cascadia/TerminalApp/CascadiaSettings.cpp]: nit: here and elsewhere, opening braces should be on the following line

File: src/cascadia/TerminalApp/CascadiaSettings.cpp [hunk 15]
```diff
@@ -467,6 +474,65 @@ bool CascadiaSettings::_isPowerShellCoreInstalledInPath(const std::wstring_view
...
+    while (pipe.tellp() < bytesAvailable) {
+        std::getline(pipe, wline);
+        std::wstringstream wlinestream(wline);
+        if (wlinestream) {
+            std::wstring distName;
+            std::getline(wlinestream, distName, L' ');
+            auto WSLDistro{ _CreateDefaultProfile(distName) };
+            WSLDistro.SetCommandline(L"wsl.exe -d " + distName);
+            WSLDistro.SetStartingDirectory(L"~");
+            WSLDistro.SetColorScheme({ L"Campbell" });
```
Comment (zadjii-msft) [inline src/cascadia/TerminalApp/CascadiaSettings.cpp]: Do we want to set the icon for these distros to the [tux penguin](https://github.com/microsoft/terminal/blob/master/src/cascadia/CascadiaPackage/ProfileIcons/%7B9acb9455-ca41-5af7-950f-6bca1bc9722f%7D.scale-200.png) that we ship with the package?

@dhowett-msft can correct me if I'm wrong, but I think that path is:
`"ms-appx:///ProfileIcons/{9acb9455-ca41-5af7-950f-6bca1bc9722f}.png"`

File: src/cascadia/TerminalApp/CascadiaSettings.cpp (hunk 14 above)
Comment (JBanks) [reply src/cascadia/TerminalApp/CascadiaSettings.cpp]: Fixed.

File: src/cascadia/TerminalApp/CascadiaSettings.cpp (hunk 15 above)
Comment (JBanks) [reply src/cascadia/TerminalApp/CascadiaSettings.cpp]: I was hoping that we could determine the icon for each WSL profile, but I don't think we'll be able to using `WSL --list`.  I threw in some code to give us the penguin as a default until we figure out something better.

Comment (zadjii-msft) [reply src/cascadia/TerminalApp/CascadiaSettings.cpp]: I'm actually pretty sure that's not feasible at all, since some distros might be installed from the store, while others could be manually installed (and won't have an icon). So this is certainly a close enough compromise

File: src/cascadia/TerminalApp/CascadiaSettings.cpp [hunk 16]
```diff
@@ -467,6 +475,73 @@ bool CascadiaSettings::_isPowerShellCoreInstalledInPath(const std::wstring_view
...
+    wil::unique_handle writePipe;
+    SECURITY_ATTRIBUTES sa{ sizeof(sa), nullptr, true };
+    THROW_IF_WIN32_BOOL_FALSE(CreatePipe(&readPipe, &writePipe, &sa, 0));
+    STARTUPINFO si{};
+    si.cb = sizeof(si);
+    si.dwFlags = STARTF_USESTDHANDLES;
+    si.hStdOutput = writePipe.get();
+    si.hStdError = writePipe.get();
+    wil::unique_process_information pi{};
+    std::wstring command = L"wsl.exe --list";
```
Comment (benhillis) [inline src/cascadia/TerminalApp/CascadiaSettings.cpp]: Please use the full path to wsl.exe, something like this.

wil::unique_cotaskmem_string systemPath;
THROW_IF_FAILED(wil::GetSystemDirectoryW(systemPath));
std::wstring command(systemPath.get());
command += L"\\wsl.exe --list";

File: src/cascadia/TerminalApp/CascadiaSettings.cpp [hunk 17]
```diff
@@ -467,6 +475,73 @@ bool CascadiaSettings::_isPowerShellCoreInstalledInPath(const std::wstring_view
...
+        THROW_HR(ERROR_CHILD_NOT_COMPLETE);
+    case WAIT_FAILED:
+        THROW_LAST_ERROR();
+    default:
+        THROW_HR(ERROR_UNHANDLED_EXCEPTION);
+    }
+    DWORD exitCode;
+    if ((GetExitCodeProcess(pi.hProcess, &exitCode) == false) || (exitCode != 0))
+    {
+        THROW_HR(E_INVALIDARG);
```
Comment (benhillis) [inline src/cascadia/TerminalApp/CascadiaSettings.cpp]: A non-zero exit code will indicate that there are no distribuitons.  This is not an error.

File: src/cascadia/TerminalApp/CascadiaSettings.cpp [hunk 18]
```diff
@@ -467,6 +475,73 @@ bool CascadiaSettings::_isPowerShellCoreInstalledInPath(const std::wstring_view
...
+    }
+    DWORD bytesAvailable;
+    THROW_IF_WIN32_BOOL_FALSE(PeekNamedPipe(readPipe.get(), nullptr, NULL, nullptr, &bytesAvailable, nullptr));
+    FILE* hPipe = _wfdopen(_open_osfhandle((intptr_t)readPipe.get(), _O_WTEXT | _O_RDONLY), L"r");
+        //don't call fclose on hPipe because the readPipe handle is managed by wil and this will cause an error.
```
Comment (benhillis) [inline src/cascadia/TerminalApp/CascadiaSettings.cpp]: Then let's not use the hPipe local var, just construct the std::wfstream with the _wfdopen.

File: src/cascadia/TerminalApp/CascadiaSettings.cpp (hunk 16 above)
Comment (JBanks) [reply src/cascadia/TerminalApp/CascadiaSettings.cpp]: Fixed.

File: src/cascadia/TerminalApp/CascadiaSettings.cpp (hunk 17 above)
Comment (JBanks) [reply src/cascadia/TerminalApp/CascadiaSettings.cpp]: Would you rather have this throw something so that it gets logged `CATCHLOG()`?  I'm thinking `ERROR_NO_DATA` would be descriptive enough as to what's happening.

For the time being, I've changed it to return without error.

File: src/cascadia/TerminalApp/CascadiaSettings.cpp (hunk 18 above)
Comment (JBanks) [reply src/cascadia/TerminalApp/CascadiaSettings.cpp]: Fixed.

File: src/cascadia/TerminalApp/CascadiaSettings.cpp (hunk 13 above)
Comment (JBanks) [reply src/cascadia/TerminalApp/CascadiaSettings.cpp]: No comments on this for 2 days, so I'll remove that code.

**Comment by zadjii-msft** [comment]
I think we're all pretty happy with this change, so I'm going to merge it. If anyone has any remaining qualms, lets file follow-up issues
