### PR TITLE
AtlasEngine: Fix Present() of out of bounds glyphs

### LINKED ISSUE #15416: [1.18] Certain fonts will cause a renderer error (MesloLGM NF, Cascadia Code Nerd Font)
### Windows Terminal version

1.18.1421.0

### Windows build number

10.0.19045.2965

### Other Software

oh-my-posh v16.8.0
Ubuntu 22.04.02 LTS

### Steps to reproduce

- Make sure oh-my-posh is started automatically on startup
- Open a new tab
- Notice the render problems
- Press enters, type text
- Notice even more render problems
- Wait a while and see the renderer catch up

It seems impossible to create a screenshot with the snipping tool because when the focus on WT is lost, the renderer catches up immediately.

Tearing of a tab created an error the very first time, but couldn't reproduce it anymore.

### Expected Behavior

_No response_

### Actual Behavior

Various rendering issues

### PR DESCRIPTION
**Pull request by lhecker**
`til::rect`'s truthiness check (= rect is valid) returns `false` for
any rects that have negative coordinates. This makes sense for buffer
handling, but breaks AtlasEngine, where glyph coordinates can go out
of bounds and it's entirely valid for that to happen.

Closes #15416

## Validation Steps Performed
* Use MesloLGM NF and print NF glyphs in the first row
* Text rendering, selection, etc., still works ✅

### CODE REVIEW

File: src/renderer/atlas/BackendD2D.cpp [hunk 1]
```diff
@@ -627,7 +627,8 @@ void BackendD2D::_debugShowDirty(const RenderingPayload& p)
 
     for (size_t i = 0; i < std::size(_presentRects); ++i)
     {
-        if (const auto& rect = _presentRects[i])
+        const auto& rect = _presentRects[(_presentRectsPos + i) % std::size(_presentRects)];
+        if (rect.non_empty())
```
Comment (lhecker) [inline src/renderer/atlas/BackendD2D.cpp:631]: This makes debugging with `ATLAS_DEBUG_SHOW_DIRTY` a bit better. It's compiled out in release builds.

File: src/renderer/atlas/BackendD3D.cpp [hunk 2]
```diff
@@ -2042,10 +2042,11 @@ void BackendD3D::_debugShowDirty(const RenderingPayload& p)
 
     for (size_t i = 0; i < std::size(_presentRects); ++i)
     {
-        if (const auto& rect = _presentRects[i])
+        const auto& rect = _presentRects[(_presentRectsPos + i) % std::size(_presentRects)];
+        if (rect.non_empty())
```
Comment (lhecker) [inline src/renderer/atlas/BackendD3D.cpp:2046]: This makes debugging with `ATLAS_DEBUG_SHOW_DIRTY` a bit better. It's compiled out in release builds.

File: src/renderer/atlas/common.h [hunk 3]
```diff
@@ -531,8 +531,11 @@ namespace Microsoft::Console::Render::Atlas
         std::array<til::generation_t, 2> colorBitmapGenerations{ 1, 1 };
         // In columns/rows.
         til::rect cursorRect;
-        // In pixel.
-        til::rect dirtyRectInPx;
+        // The viewport/SwapChain area to be presented. In pixel.
+        // NOTE:
+        //   This can not use til::rect, because til::rect is constrained to
+        //   positive coordinates only, but this one can go out of bounds.
```
Comment (zadjii-msft) [inline src/renderer/atlas/common.h:537]: > because `til::rect` is constrained to positive coordinates only

wait, that's not true though, right? I thought it was 4 `int32_t`'s

File: src/renderer/atlas/AtlasEngine.r.cpp [hunk 4]
```diff
@@ -416,30 +416,31 @@ void AtlasEngine::_waitUntilCanRender() noexcept
 void AtlasEngine::_present()
 {
     // Present1() dislikes being called with an empty dirty rect.
-    if (!_p.dirtyRectInPx)
```
Comment (zadjii-msft) [inline src/renderer/atlas/AtlasEngine.r.cpp:419]: So, this is the LOAD BEARING change in this PR, the rest is incidental?

**Review by zadjii-msft — APPROVED** [review]

File: src/renderer/atlas/AtlasEngine.r.cpp (hunk 4 above)
Comment (lhecker) [reply src/renderer/atlas/AtlasEngine.r.cpp:419]: Yeah, sort of. Due to the type change a couple more changes are necessary unfortunately.

**Comment by DHowett** [comment]
UHHHHHHHHH we are 1.5 hours from the go-live time on Terminal Preview 1.18 - HOW IMPORTANT IS THIS?

File: src/renderer/atlas/common.h [hunk 5]
```diff
@@ -531,8 +531,12 @@ namespace Microsoft::Console::Render::Atlas
         std::array<til::generation_t, 2> colorBitmapGenerations{ 1, 1 };
         // In columns/rows.
         til::rect cursorRect;
-        // In pixel.
-        til::rect dirtyRectInPx;
+        // The viewport/SwapChain area to be presented. In pixel.
+        // NOTE:
+        //   This can not use til::rect, because til::rect generally expects positive coordinates only
```
Comment (DHowett) [inline src/renderer/atlas/common.h:536]:
```suggestion
        //   This cannot use til::rect, because til::rect generally expects positive coordinates only
```

**Review by DHowett — APPROVED** [review]
