### PR TITLE
Fix a ControlCore race condition on connection close

### LINKED ISSUE #13880: Terminal crashes when exiting a bash shell
### Windows Terminal version

1.15.1862.0

### Windows build number

10.0.19044.1889

### Other Software

WSL with Ubuntu 20.04.4 LTS

### Steps to reproduce

1. Start Windows Terminal
2. Open two tabs, one of which is a bash shell.
3. Exit the bash shell (with `exit`).

### Expected Behavior

The terminal should remain open after the bash shell exits, with the other tab still working.

### Actual Behavior

The terminal crashes.

I was able to reproduce this in the debugger with a build derived from commit c12987af415c5e0911d7a0a81b8494fbe6307328, and the stack trace for the crash looked like this:

	ntdll.dll!TppRaiseInvalidParameter()	Unknown
 	ntdll.dll!TppTimerpValidateTimer()	Unknown
 	ntdll.dll!TpSetTimerEx()	Unknown
 	Microsoft.Terminal.Control.dll!winrt::Microsoft::Terminal::Control::implementation::ControlCore::_terminalScrollPositionChanged(const int viewTop, const int viewHeight, const int bufferSize) Line 1308	C++
 	[External Code]	
 	Microsoft.Terminal.Control.dll!Microsoft::Terminal::Core::Terminal::_NotifyScrollEvent() Line 1305	C++
 	Microsoft.Terminal.Control.dll!Microsoft::Console::VirtualTerminal::AdaptDispatch::_EraseScrollback() Line 1952	C++
 	Microsoft.Terminal.Control.dll!Microsoft::Console::VirtualTerminal::AdaptDispatch::EraseInDisplay(const Microsoft::Console::VirtualTerminal::DispatchTypes::EraseType eraseType) Line 614	C++
 	Microsoft.Terminal.Control.dll!Microsoft::Console::VirtualTerminal::OutputStateMachineEngine::ActionCsiDispatch(const Microsoft::Console::VirtualTerminal::VTID id, const Microsoft::Console::VirtualTerminal::VTParameters parameters) Line 492	C++
 	Microsoft.Terminal.Control.dll!Microsoft::Console::VirtualTerminal::StateMachine::_SafeExecute<`Microsoft::Console::VirtualTerminal::StateMachine::_ActionCsiDispatch'::`2'::<lambda_1>>(Microsoft::Console::VirtualTerminal::StateMachine::_ActionCsiDispatch::__l2::<lambda_1> && lambda) Line 2039	C++
 	Microsoft.Terminal.Control.dll!Microsoft::Console::VirtualTerminal::StateMachine::_ActionCsiDispatch(const wchar_t wch) Line 480	C++
 	Microsoft.Terminal.Control.dll!Microsoft::Console::VirtualTerminal::StateMachine::ProcessCharacter(const wchar_t wch) Line 1778	C++
 	Microsoft.Terminal.Control.dll!Microsoft::Console::VirtualTerminal::StateMachine::ProcessString(const std::basic_string_view<wchar_t,std::char_traits<wchar_t>> string) Line 1853	C++
 	Microsoft.Terminal.Control.dll!winrt::Microsoft::Terminal::Control::implementation::ControlCore::_connectionOutputHandler(const winrt::hstring & hstr) Line 1706	C++
 	Microsoft.Terminal.Control.dll!winrt::impl::delegate<winrt::Microsoft::Terminal::TerminalConnection::TerminalOutputHandler,`winrt::Microsoft::Terminal::TerminalConnection::TerminalOutputHandler::implementation<winrt::Microsoft::Terminal::Control::implementation::ControlCore,void (__cdecl winrt::Microsoft::Terminal::Control::implementation::ControlCore::*)(winrt::hstring const &)>'::`1'::<lambda_218_>>::Invoke(void * output) Line 174	C++
 	[External Code]	

The problem, as far as I can make out, is that the `ControlCore` instance is deleted at this point in time. If you look at `ControlCore::Close` method, we're closing the connection asynchronously, which I think means we're still receiving VT sequences (in this case `\e[3J`) after `ControlCore` is gone. Assuming I've understood that correctly, that would probably explain the crash.

### PR DESCRIPTION
**Pull request by lhecker**
As noted by the `winrt::event` documentation:
> [...] But for asynchronous events, even after revoking [...], an in-flight
> event might reach your object after it has started destructing.

This is because while adding/removing/calling event handlers might be
thread-safe, there's no guarantee that they run mutually exclusive.

This commit fixes the issue by reverting 6f0f245. Since we never checked
the result of closing a terminal connection anyways, this commit simply drops
the wait on the connection being teared down to ensure #1996 doesn't regress.

Closes #13880

## Validation Steps Performed
* Open tab, close tab, open tab, close tab, open tab, close tab
  * ConPTY ✅
  * Azure ✅
* Closing a tab with a huge amount of panes ✅
* Opening a bunch of tabs and then closing the window ✅
* Closing a tab while it's busy with VT ✅
* `wtd -w 0 nt cmd /c exit` ✅
* `wtd -w -1 cmd /c exit`
  * No WerFault spawns ✅

### CODE REVIEW

**Comment by DHowett** [comment]
I've asked Leonard for more tests:

- closing a tab with a HUGE amount of panes in it?
- a tab whose connection exits before it even starts?
   - before terminal launches (`wt -w -1 cmd /c exit`)
- after terminal is running (`nt cmd /c exit` from the commandline palette)
- opening a bunch of tabs and then closing the entire terminal window?

**Review by zadjii-msft — COMMENTED** [review]
I'm not signing off so that we hold till 1.17, but treat this as a ✔️ if the baby arrives before the 1.16/1.17 fork

**Comment by zadjii-msft** [comment]
But also maybe test blatting `big.txt` and closing the pane

**Comment by lhecker** [comment]
Alright, I finished testing everything and updated the PR message.

**Comment by DHowett** [comment]
ONE FINAL TEST

**Comment by DHowett** [comment]
Nevermind I couldn't even get it to work normally.

**Comment by lhecker** [comment]
Could we get this into 1.16? I think this issue might be the cause for a crash on tab close I'm seeing quite often in debug builds...

**Review by zadjii-msft — APPROVED** [review]
Sure. I don't think there's any reason this would cause client exes to get leaked. I'm not sure there's any reason we need to wait on the client app before finishing `Connection::Close()`. Going back a while (#3461, #1340, I don't see evidence for needing it)

File: src/cascadia/TerminalConnection/ConptyConnection.cpp [hunk 1]
```diff
@@ -546,8 +546,9 @@ namespace winrt::Microsoft::Terminal::TerminalConnection::implementation
     {
         if (_transitionToState(ConnectionState::Closing))
         {
-            // EXIT POINT
-            _clientExitWait.reset(); // immediately stop waiting for the client to exit.
+            // _clientExitWait holds a CreateThreadpoolWait() which holds a weak reference to "this".
```
Comment (DHowett) [inline src/cascadia/TerminalConnection/ConptyConnection.cpp:549]:
```suggestion
            // EXIT POINT

            // _clientExitWait holds a CreateThreadpoolWait() which holds a weak reference to "this".
```

please keep this comment; it is an important landmark documented at the top of the file

**Review by DHowett — APPROVED** [review]
