### PR TITLE
Prevent horizontally scrolling wide chars erasing themselves

### LINKED ISSUE #14626: ICH no longer works correctly on lines containing wide characters
### Windows Terminal version

Commit 547349af77df16d0eed1c73ba3041c84f7b063da

### Windows build number

10.0.19044.2364

### Other Software

_No response_

### Steps to reproduce

1. Create a build from the latest commit.
2. Start Windows Terminal and open a WSL bash shell.
3. Execute the following command: `printf "\u3053\u3093\u306B\u3061\u306F World\r\e[@\n"`

### Expected Behavior

This should write out the text `こんにちは World`, and then insert a space at the start of the line via an `ICH` sequence. This is what it looks like in Preview version 1.16.2641.0:

image

### Actual Behavior

When using the latest commit, the Japanese characters are erased by the `ICH` sequence, so all that's left is `World`.

image

So this looks to me like a regression, although I'm not sure when exactly it stopped working.

And note that this fails in OpenConsole as well. It's just easier to confirm that it's a recent regression in Windows Terminals because I know 1.16 was working OK.

### PR DESCRIPTION
**Pull request by j4james**
When the buffer contains wide characters that occupy more than one cell,
and those cells are scrolled horizontally by exactly one column, that
operation can result in the wide characters being completely erased.
This PR attempts to fix that bug, although it's not an ideal long term
solution.

Although not really to blame, it was PR #13626 that exposed this issue.

The root of the problem is that scrolling operations copy cells one by
one, but wide characters are written to the buffer two cells at a time.
So when you move a wide character one position to the left or right, it
can overwrite itself before it's finished copying, and the end result is
the whole character gets erased.

I've attempt to solve this by getting the affected operations to read
two cells in advance before they start writing, so there's no risk of
losing the source data before it's fully output. This may not work in
the long term, with characters wider than two cells, but it should at
least be good enough for now.

I've also changed the `TextBuffer::Write` call to a `WriteLine` call to
improve the handling of a wide character on the end of the line, where
moving it right by one column would place it half off screen. It should
just be dropped, but with the `Write` method, it would end up pushed
onto the following line.

## Validation Steps Performed

I've manually confirmed this fixes all the test cases described in
#14626, and also added some unit tests that replicate those scenarios.

Closes #14626

### CODE REVIEW

**Review by carlos-zamora — APPROVED** [review]
Straightforward and tested. Thanks for doing this!

File: src/host/output.cpp [hunk 1]
```diff
@@ -102,12 +102,16 @@ static void _CopyRectangle(SCREEN_INFORMATION& screenInfo,
...
+        // itself when moving one cell horizontally.
+        auto next = OutputCell(*screenInfo.GetCellDataAt(sourcePos));
         do
         {
-            const auto data = OutputCell(*screenInfo.GetCellDataAt(sourcePos));
-            screenInfo.Write(OutputCellIterator({ &data, 1 }), targetPos);
-
+            const auto current = next;
             source.WalkInBounds(sourcePos, walkDirection);
+            next = OutputCell(*screenInfo.GetCellDataAt(sourcePos));
```
Comment (DHowett) [inline src/host/output.cpp:113]: Is it possible for this to result in `source` running out of space (somehow?) before target does? I guess we're doing it in the previous code as well, but maybe one fewer time.

Comment (j4james) [reply src/host/output.cpp:113]: If you look at the `WalkInBounds` implementation, it just doesn't update the position once it has reached the end of the range, so all we'll be doing is reading the final position twice.

https://github.com/microsoft/terminal/blob/0eff8c06e32bff6c1e8d39e6505ef8a4c6d8ecbf/src/types/viewport.cpp#L405-L417

**Comment by zadjii-msft** [comment]
> So when you move a wide character one position to the left or right, it can overwrite itself before it's finished copying, and the end result is the whole character gets erased.

for some reason this is hilarious to me. Like, _of course it does_, classic wide char code 🙃

**Review by zadjii-msft — APPROVED** [review]

**Review by DHowett — APPROVED** [review]
