### PR TITLE
Move rect expansion to textbuffer; refactor selection code

### LINKED ISSUE #4465: Selection Expansion should not be occurring during Rendering
This is a _major_ bug, not because of what it's doing _now_, but how it's affecting other things.

## How our selection model operates
Whenever we set a selection anchor (i.e.: pointer movements, search, etc), we are recording the COORD of the pointer or space that we want to select. If we encounter a wide glyph (i.e.: 😐) or are doing chunk selection for words/lines, the selection anchors are wrong and we expand to encompass them during `_GetSelectionRects()`.

## Issues this is causing
1) #2447 Signaling for selection: the selection anchors we're returning are not representative of what gets selected.
2) #3758 MoveSelectionAnchor: moving the selection anchors don't actually represent what is selected. So expanding by character on a double click selection really shows this.

Both of these issues are blocked until this gets resolved.

## Proposed Approach
- On click,
  - decide if this was a single/double/triple click
  - this establishes an expansion mode
  - set start/end at pointer
  - edit start/end based on expansion mode + glyphs
- On drag,
  - if moving to the "right" of start, set end. Otherwise, set start.
  - from current cursor position, expand appropriately and update target endpoint

### LINKED ISSUE #4547: Refactor TerminalSelection Anchors
# Summary

The selection anchors are recorded strangely. We keep track of their position on the viewport, and where the viewport is at that time. Whenever we want to know what text these anchors cover or need to do more processing, we need to convert to the TextBuffer space, do what we wanted to do, then re-convert back to this weird system.

Additionally, the names `_selectionAnchor` and `_endSelectionPosition` could probably be better.

# Technical Details

1. The selection anchors should be in the TextBuffer coordinate system
2. They should be renamed to something simpler and more cohesive (i.e.: `_selectionStart` and `_selectionEnd`)
3. (Bonus Points!) If we can keep track of which one is higher/lower, that would make some code a lot easier.

### PR DESCRIPTION
**Pull request by carlos-zamora**
- When performing chunk selection, the expansion now occurs at the time
  of the selection, not the rendering of the selection
- `GetSelectionRects()` was moved to the `TextBuffer` and is now shared
  between ConHost and Windows Terminal
- Some of the selection variables were renamed for clarity
- Selection COORDs are now in the Text Buffer coordinate space
- Fixes an issue with Shift+Click after performing a Multi-Click
  Selection

## References
This also contributes to...
- #4509: UIA Box Selection
- #2447: UIA Signaling for Selection
- #1354: UIA support for Wide Glyphs

Now that the expansion occurs at before render-time, the selection
anchors are an accurate representation of what is selected. We just need
to move `GetText` to the `TextBuffer`. Then we can have those three
issues just rely on code from the text buffer. This also means ConHost
gets some of this stuff for free 😀

### TextBuffer
- `GetTextRects` is the abstracted form of `GetSelectionRects`
- `_ExpandTextRow` is still needed to handle wide glyphs properly

### Terminal
- Rename...
    - `_boxSelection` --> `_blockSelection` for consistency with ConHost
    - `_selectionAnchor` --> `_selectionStart` for consistency with UIA
    - `_endSelectionPosition` --> `_selectionEnd` for consistency with
      UIA
- Selection anchors are in Text Buffer coordinates now
- Really rely on `SetSelectionEnd` to accomplish appropriate chunk
  selection and shift+click actions

## Validation Steps Performed
- Shift+Click
- Multi-Click --> Shift+Click
- Chunk Selection at...
    - top of buffer
    - bottom of buffer
    - random region in scrollback

Closes #4465
Closes #4547

### CODE REVIEW

File: src/cascadia/TerminalCore/Terminal.hpp [hunk 1]
```diff
@@ -156,12 +156,17 @@ class Microsoft::Terminal::Core::Terminal final :
...
+        Line
+    };
     const bool IsCopyOnSelectActive() const noexcept;
-    void DoubleClickSelection(const COORD position);
-    void TripleClickSelection(const COORD position);
+    void MultiClickSelection(const COORD viewportPos, SelectionExpansionMode expansionMode);
     void SetSelectionAnchor(const COORD position);
-    void SetEndSelectionPosition(const COORD position);
-    void SetBoxSelection(const bool isEnabled) noexcept;
+    void SetSelectionEnd(const COORD position, std::optional<SelectionExpansionMode> expansionMode = std::nullopt);
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalCore/Terminal.hpp]: is nullopt treated equivalently to Cell? If so, set cell as the default and ditch the optional

File: src/cascadia/TerminalCore/TerminalSelection.cpp [hunk 2]
```diff
@@ -235,92 +73,173 @@ const bool Terminal::IsCopyOnSelectActive() const noexcept
...
-    COORD positionWithOffsets = _ConvertToBufferCell(position);
-
-    // scan leftwards until delimiter is found and
-    // set selection anchor to one right of that spot
-    _selectionAnchor = _ExpandDoubleClickSelectionLeft(positionWithOffsets);
-    THROW_IF_FAILED(ShortSub(_selectionAnchor.Y, gsl::narrow<SHORT>(ViewStartIndex()), &_selectionAnchor.Y));
-    _selectionVerticalOffset = gsl::narrow<SHORT>(ViewStartIndex());
+    // set the selection pivot to expand the selection using SetSelectionEnd()
+    _selectionPivot = _ConvertToBufferCell(viewportPos);
+    _buffer->GetSize().Clamp(_selectionPivot);
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalCore/TerminalSelection.cpp]: why does ConvertToBufferCell not clamp on its own? Will this even be necessary with ConverToBufferCell?

File: src/cascadia/TerminalCore/TerminalSelection.cpp [hunk 3]
```diff
@@ -235,92 +73,173 @@ const bool Terminal::IsCopyOnSelectActive() const noexcept
...
+// - Record the position of the beginning of a selection
 // Arguments:
 // - position: the (x,y) coordinate on the visible viewport
-void Terminal::TripleClickSelection(const COORD position)
+void Terminal::SetSelectionAnchor(const COORD viewportPos)
 {
-    SetSelectionAnchor({ 0, position.Y });
-    SetEndSelectionPosition({ _buffer->GetSize().RightInclusive(), position.Y });
+    _selectionPivot = _ConvertToBufferCell(viewportPos);
+    _buffer->GetSize().Clamp(_selectionPivot);
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalCore/TerminalSelection.cpp]: same q as above

File: src/cascadia/TerminalCore/TerminalSelection.cpp [hunk 4]
```diff
@@ -235,92 +73,173 @@ const bool Terminal::IsCopyOnSelectActive() const noexcept
...
+
+    _multiClickSelectionMode = SelectionExpansionMode::Cell;
 
-    _multiClickSelectionMode = SelectionExpansionMode::Line;
+    // Unlike MultiClickSelection(), we need to set
+    // these vars BEFORE SetSelectionEnd()
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalCore/TerminalSelection.cpp]: comment clarity: why

File: src/cascadia/TerminalCore/TerminalSelection.cpp [hunk 5]
```diff
@@ -235,92 +73,173 @@ const bool Terminal::IsCopyOnSelectActive() const noexcept
...
 // Method Description:
-// - Record the position of the beginning of a selection
+// - Update selection anchors when dragging to a position
+// - based on the selection expansion mode
 // Arguments:
-// - position: the (x,y) coordinate on the visible viewport
-void Terminal::SetSelectionAnchor(const COORD position)
+// - viewportPos: the (x,y) coordinate on the visible viewport
+// - expansionModeOverwrite: overwrites the _multiClickSelectionMode for this function call. Used for ShiftClick
+void Terminal::SetSelectionEnd(const COORD viewportPos, std::optional<SelectionExpansionMode> expansionModeOverwrite)
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalCore/TerminalSelection.cpp]: oh i see. call it _override_ then instead of overwrite

Comment (DHowett-MSFT) [reply src/cascadia/TerminalCore/TerminalSelection.cpp]: or maybe `newExpansionMode`

File: src/cascadia/TerminalCore/TerminalSelection.cpp [hunk 6]
```diff
@@ -235,92 +73,173 @@ const bool Terminal::IsCopyOnSelectActive() const noexcept
...
 {
-    _selectionAnchor = position;
+    auto textBufferPos = _ConvertToBufferCell(viewportPos);
+    _buffer->GetSize().Clamp(textBufferPos);
 
-    // include _scrollOffset here to ensure this maps to the right spot of the original viewport
-    THROW_IF_FAILED(ShortSub(_selectionAnchor.Y, gsl::narrow<SHORT>(_scrollOffset), &_selectionAnchor.Y));
+    // if this is a shiftClick action, we need to overwrite the _multiClickSelectionMode value (even if it's the same)
+    // Otherwise, we may accidentally expand during other selection-based actions
+    const auto shiftClick = expansionModeOverwrite.has_value();
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalCore/TerminalSelection.cpp]: I don't love how the presence of this mcdude is used to determine _whether_ the user shift-clicked. is there a better name than `shiftClick` for this?

File: src/cascadia/TerminalCore/TerminalSelection.cpp [hunk 7]
```diff
@@ -235,92 +73,173 @@ const bool Terminal::IsCopyOnSelectActive() const noexcept
...
+    case SelectionExpansionMode::Word:
+        _ChunkSelectionByWord(textBufferPos, shiftClick);
+        break;
+    case SelectionExpansionMode::Cell:
+    default:
+        _ChunkSelectionByCell(textBufferPos, shiftClick);
+
+        if (_copyOnSelect && !_IsSingleCellSelection())
+        {
+            _allowSingleCharSelection = true;
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalCore/TerminalSelection.cpp]: comment note: "// moving the endpoint of what used to be a single cell selection allows the user to drag back and select just one cell"

File: src/cascadia/TerminalCore/TerminalSelection.cpp [hunk 8]
```diff
@@ -235,92 +73,173 @@ const bool Terminal::IsCopyOnSelectActive() const noexcept
...
     _selectionActive = true;
-    _allowSingleCharSelection = (_copyOnSelect) ? false : true;
-
-    SetEndSelectionPosition(position);
+}
 
-    _multiClickSelectionMode = SelectionExpansionMode::Cell;
+// Method Description:
+// - Update the selection anchors when dragging to a position
+// - Used for SelectionExpansionMode::Word
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalCore/TerminalSelection.cpp]: this comment is not true

File: src/cascadia/TerminalCore/TerminalSelection.cpp [hunk 9]
```diff
@@ -235,92 +73,173 @@ const bool Terminal::IsCopyOnSelectActive() const noexcept
...
+// Arguments:
+// - targetPos: the (x,y) coordinate we are dragging to on the text buffer
+// - shiftClick: when enabled, only update the _endSelectionPosition
+void Terminal::_ChunkSelectionByCell(const COORD targetPos, bool /*shiftClick*/)
+{
+    // TODO GH #4557: Shift+Multi-Click Expansion
+    //   shiftClick is reserved for that implementation
+    if (_buffer->GetSize().CompareInBounds(targetPos, _selectionPivot) <= 0)
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalCore/TerminalSelection.cpp]: all three of these functions do the same exact thing. How about this?

```
std::tuple<COORD, COORD> _AdjustStartAndEndAcrossPivot(const COORD targetPos, const COORD endpoint1, const COORD endpoint2);

...


std::tie(_selectionStart, _selectionEnd) = AdjustThingByThing(targetPos, Expand(targetPos), Expand(_selectionPivot))
```

but maybe the complexity of the args we're passing to AdjustThingByThing makes it reasonable to just copy the logic here for clarity...

File: src/cascadia/TerminalCore/TerminalSelection.cpp [hunk 10]
```diff
@@ -329,9 +248,8 @@ void Terminal::ClearSelection()
 {
     _selectionActive = false;
     _allowSingleCharSelection = false;
-    _selectionAnchor = { 0, 0 };
-    _endSelectionPosition = { 0, 0 };
-    _selectionVerticalOffset = 0;
+    _selectionStart = { 0, 0 };
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalCore/TerminalSelection.cpp]: I do not love how we have a boolean _and_ a coord.. that's just an std::optional in disguise lol

Comment (DHowett-MSFT) [reply src/cascadia/TerminalCore/TerminalSelection.cpp]: do not feel compelled to fix this for this pr

File: src/cascadia/TerminalCore/TerminalSelection.cpp [hunk 11]
```diff
@@ -395,15 +313,10 @@ COORD Terminal::_ExpandDoubleClickSelectionRight(const COORD position) const
...
+COORD Terminal::_ConvertToBufferCell(const COORD viewportPos) const noexcept
 {
-    // Force position to be valid
-    COORD positionWithOffsets = viewportPos;
-    _buffer->GetSize().Clamp(positionWithOffsets);
-
-    THROW_IF_FAILED(ShortSub(viewportPos.Y, gsl::narrow<SHORT>(_scrollOffset), &positionWithOffsets.Y));
-    THROW_IF_FAILED(ShortAdd(positionWithOffsets.Y, gsl::narrow<SHORT>(ViewStartIndex()), &positionWithOffsets.Y));
-    return positionWithOffsets;
+    const auto yPos = base::ClampedNumeric<short>(_VisibleStartIndex()) + viewportPos.Y;
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalCore/TerminalSelection.cpp]: what incited the change from ViewStartIdx to VisibleStartIdx? Are they different? Why do they both exist? Why would we use one vs the otehr?

File: src/host/ut_host/SelectionTests.cpp [hunk 12]
```diff
@@ -378,27 +383,27 @@ class SelectionTests
 
         // start from position 10 before end of row (80 length row)
         // row is 2
-        // selection is 10 characters long
+        // selection is 9 characters long
```
Comment (DHowett-MSFT) [inline src/host/ut_host/SelectionTests.cpp]: uh? wut

File: src/buffer/out/textBuffer.hpp [hunk 13]
```diff
@@ -135,6 +135,8 @@ class TextBuffer final
     bool MoveToNextWord(COORD& pos, const std::wstring_view wordDelimiters, COORD lastCharPos) const;
     bool MoveToPreviousWord(COORD& pos, const std::wstring_view wordDelimiters) const;
 
+    const std::vector<SMALL_RECT> GetTextRects(COORD start, COORD end, bool blockSelection = false) const;
```
Comment (miniksa) [inline src/buffer/out/textBuffer.hpp]: Please ensure this gets a unit test in the text buffer unit tests now that it lives over here.

File: src/cascadia/TerminalCore/Terminal.hpp [hunk 14]
```diff
@@ -186,19 +191,13 @@ class Microsoft::Terminal::Core::Terminal final :
...
-        Cell,
-        Word,
-        Line
-    };
-    COORD _selectionAnchor;
-    COORD _endSelectionPosition;
-    bool _boxSelection;
+    COORD _selectionStart;
+    COORD _selectionEnd;
+    COORD _selectionPivot;
```
Comment (miniksa) [inline src/cascadia/TerminalCore/Terminal.hpp]: What do you mean by pivot?

File: src/cascadia/TerminalCore/TerminalSelection.cpp (hunk 4 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalCore/TerminalSelection.cpp]: I was wrong

File: src/cascadia/TerminalCore/TerminalSelection.cpp (hunk 11 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalCore/TerminalSelection.cpp]: `VisibleStartIndex`: the first VISIBLE line of the buffer (updates as we scroll)
`ViewStartIndex`: the length of the scrollback (only updates as new output forces us to scroll)

Before, the scrollback at the time of selection was saved. Then we would have to convert from "viewport position at the time of selection" to "buffer position" whenever we wanted to know what it pointed at.

Now, we have no value in knowing what the scrollback was at the time of selection. Let's just save everything as buffer positions and save the headache.

Comment (DHowett-MSFT) [reply src/cascadia/TerminalCore/TerminalSelection.cpp]: Bingo. Thanks,

File: src/buffer/out/textBuffer.hpp (hunk 13 above)
Comment (carlos-zamora) [reply src/buffer/out/textBuffer.hpp]: Added. Note: I'm going a little light on them on purpose because this same stuff gets tested in selection tests and UIA tests.

File: src/cascadia/TerminalCore/Terminal.hpp (hunk 1 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalCore/Terminal.hpp]: Nope.
- `nullopt` --> use the current _multiClickSelectionMode
- `<new mode>` --> overwrite it, and use that

The overall plan is that this'll be even more useful for #4557. We can call `SetSelectionEnd(terminalPosition, ::Terminal::SelectionExpansionMode::Line);` to only expand one of the selection anchors to a line, as opposed to both anchors.

File: src/cascadia/TerminalCore/TerminalSelection.cpp (hunk 10 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalCore/TerminalSelection.cpp]: I made the change in the latest commit. Lemme know what you think. If you don't like it or wanna go a different direction, I can just revert that one 😀

Comment (carlos-zamora) [reply src/cascadia/TerminalCore/TerminalSelection.cpp]: Commit: https://github.com/microsoft/terminal/pull/4560/commits/12ba9eeb8f64c0f1cd6ee2eb07ae8c9200fd23c4

File: src/host/ut_host/SelectionTests.cpp (hunk 12 above)
Comment (carlos-zamora) [reply src/host/ut_host/SelectionTests.cpp]: This whole area was a bit weird to work with.
1. the test text has a Trailing byte at 0 (which should not be happening)
2. the code used to operate by identifying the starting point of a selection and expanding it by X _characters_. We moved away from this and, instead, just create a RECT that expands its left and right side by _cells_.

Since a wide glyph (presumably being one character) can hold two cells, we had to rewrite some of this a little bit.

Comment (carlos-zamora) [reply src/host/ut_host/SelectionTests.cpp]: I manually did some tests though (and added some for Michael below). So this should be working fine.

File: src/cascadia/TerminalCore/Terminal.hpp [hunk 15]
```diff
@@ -191,11 +192,17 @@ class Microsoft::Terminal::Core::Terminal final :
     bool _suppressApplicationTitle;
 
 #pragma region Text Selection
-    COORD _selectionStart;
-    COORD _selectionEnd;
-    COORD _selectionPivot;
+    // a selection is represented as a range between two COORDs (start and end)
+    // the pivot is the COORD that remains selected when you extend a selection in any direction
+    //   this is particularly useful when a selection is extended over its starting point
+    struct SelectionAnchors
```
Comment (miniksa) [inline src/cascadia/TerminalCore/Terminal.hpp]: Pivot only super makes sense in the context of a word or line selection.

Also, if you draw a big ASCII art diagram here of a few options, it could help someone.

File: src/cascadia/TerminalCore/TerminalSelection.cpp [hunk 16]
```diff
@@ -97,140 +140,93 @@ void Terminal::MultiClickSelection(const COORD viewportPos, SelectionExpansionMo
...
 
 // Method Description:
 // - Update selection anchors when dragging to a position
 // - based on the selection expansion mode
 // Arguments:
 // - viewportPos: the (x,y) coordinate on the visible viewport
-// - expansionModeOverwrite: overwrites the _multiClickSelectionMode for this function call. Used for ShiftClick
-void Terminal::SetSelectionEnd(const COORD viewportPos, std::optional<SelectionExpansionMode> expansionModeOverwrite)
+// - newExpansionMode: overwrites the _multiClickSelectionMode for this function call. Used for ShiftClick
+void Terminal::SetSelectionEnd(const COORD viewportPos, std::optional<SelectionExpansionMode> newExpansionMode)
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalCore/TerminalSelection.cpp]: this function will throw if SetSelectionStart has not been called. Presume that's okay?
