### PR TITLE
Fix unfocused appearance editor not appearing/disappearing correctly

### LINKED ISSUE #10673: Unfocused Appearance editor doesn't appear on +, disappear on Deletion
### Windows Terminal version (or Windows build number)

1.11

### Other Software

_No response_

### Steps to reproduce

Add or remove an unfocused appearance.

### Expected Behavior

_No response_

### Actual Behavior

On add, the + changes to a [trash] icon, but I cannot scroll to reveal an unfocused appearance. It appears if i navigate away and back.

On delete, the [trash] icon changes to a +, but the UI doesn't disappear.

### PR DESCRIPTION
**Pull request by PankajBhojwani**
## Summary of the Pull Request
Sends the additional xaml notification when the user presses the '+' or delete button for unfocused appearances

## PR Checklist
* [x] Closes #10673
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Documentation updated. If checked, please file a pull request on [our docs repo](https://github.com/MicrosoftDocs/terminal) and link it here: #xxx
* [ ] Schema updated.
* [x] I work here

## Validation Steps Performed
It works now

### CODE REVIEW

**Review by miniksa — APPROVED** [review]
Welp. That's an easy fix.

File: src/cascadia/TerminalSettingsEditor/Profiles.cpp [hunk 1]
```diff
@@ -275,7 +275,7 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
         _unfocusedAppearanceViewModel.Schemes(schemes);
         _unfocusedAppearanceViewModel.WindowRoot(windowRoot);
 
-        _NotifyChanges(L"UnfocusedAppearance", L"HasUnfocusedAppearance");
+        _NotifyChanges(L"UnfocusedAppearance", L"HasUnfocusedAppearance", L"ShowUnfocusedAppearance");
```
Comment (lhecker) [inline src/cascadia/TerminalSettingsEditor/Profiles.cpp:278]: Why does this one notify a change for "UnfocusedAppearance" but `DeleteUnfocusedAppearance()` doesn't? 🤔

**Review by lhecker — APPROVED** [review]

File: src/cascadia/TerminalSettingsEditor/Profiles.cpp (hunk 1 above)
Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/Profiles.cpp:278]: It's a fair question. If somebody were to be monitoring that object, it would have changed. We may want to notify on it just to be safe!

Comment (PankajBhojwani) [reply src/cascadia/TerminalSettingsEditor/Profiles.cpp:278]: Mostly because it just wasn't necessary since XAML hides the entire control once it gets the `HasUnfocusedAppearance`/`ShowUnfocusedAppearance` update, but yeah I've added it just in case!
