### PR TITLE
Restore support for pasting files

### LINKED ISSUE #16627: [1.19] Pasting a file from explorer into the Terminal no longer pastes the path (regression from 1.18)
### Windows Terminal version

1.19.240129002

### Windows build number

10.0.19045.3930

### Other Software

no

### Steps to reproduce

copy a file from the File Explorer (a file object, not text), and then paste it into Windows Terminal

### Expected Behavior

In version 1.18.240129001 of Windows Terminal, it can display the path of the pasted file.

### Actual Behavior

In 1.19, and 1.20 of Windows Terminal, nothing is shown.
(copy/paste normal text is OK)

### PR DESCRIPTION
**Pull request by lhecker**
TIL: You could Ctrl+V files into Windows Terminal and here I am,
always opening the context menu and selecting "Copy as path"... smh

This restores the support by adding a very rudimentary HDROP handler.
The flip side of the regression is that I learned about this and so
conhost also gets this now, because why not!

Closes #16627

## Validation Steps Performed
* Single files can be pasted in WT and conhost ✅

### CODE REVIEW

**Comment by DHowett** [comment]
Hey, the WinRT API _was_ doing something for us that we didn't have to worry too much about!

File: src/cascadia/TerminalApp/TerminalPage.cpp [hunk 1]
```diff
@@ -2628,6 +2628,75 @@ namespace winrt::TerminalApp::implementation
...
+        if (const auto handle = GetClipboardData(CF_UNICODETEXT))
+        {
+            const wil::unique_hglobal_locked lock{ handle };
+            const auto str = static_cast<const wchar_t*>(lock.get());
+            if (!str)
+            {
+                return {};
+            }
+
+            const auto maxLen = GlobalSize(handle) / sizeof(WCHAR);
```
Comment (DHowett) [inline src/cascadia/TerminalApp/TerminalPage.cpp:2666]: _technically,_ this doesn't matter. however: you're mixing `WCHAR` and `wchar_t` which _could_ be distinct types. It'll never happen in practice though...

**Comment by lhecker** [comment]
Ackchyually, we had to do it manually:
https://github.com/microsoft/terminal/blob/78de1147e910115f084638ba382675c7721c0fce/src/cascadia/TerminalApp/TerminalPage.cpp#L2620-L2629

That's effectively the `HDROP` handler but with WinRT APIs. I removed it because I never realized that you could simply Ctrl+V a file into WT. The author of that code might not have known either because look at the comment on top of it: It only refers to the whacky "Copy address" menu item, and _that one_ happens to actually contain a `CF_UNICODETEXT` and that's why I didn't port the `HDROP` handling into the Win32 code.

File: src/cascadia/TerminalApp/TerminalPage.cpp [hunk 2]
```diff
@@ -2628,6 +2628,75 @@ namespace winrt::TerminalApp::implementation
...
+                return {};
+            }
+
+            const auto cap = DragQueryFileW(drop, 0, nullptr, 0);
+            if (cap == 0)
+            {
+                return {};
+            }
+
+            auto buffer = winrt::impl::hstring_builder{ cap };
```
Comment (DHowett) [inline src/cascadia/TerminalApp/TerminalPage.cpp:2687]: we shouldn't use `winrt::impl` types directly. However, I don't love any of the other options. _heh_

File: src/interactivity/win32/Clipboard.cpp [hunk 3]
```diff
@@ -59,29 +59,60 @@ void Clipboard::Paste()
...
+        {
+            return;
+        }
 
-    // Clear any selection or scrolling that may be active.
-    Selection::Instance().ClearSelection();
-    Scrolling::s_ClearScroll();
+        // Clear any selection or scrolling that may be active.
+        Selection::Instance().ClearSelection();
+        Scrolling::s_ClearScroll();
```
Comment (DHowett) [inline src/interactivity/win32/Clipboard.cpp:74]: this is common with the other branch through `StringPaste` below; is there any need (value?) in deduplicating?

**Comment by DHowett** [comment]
> I removed it because I never realized that you could simply Ctrl+V a file into WT. The author of that code might not have known either because look at the comment on top of it: It only refers to the whacky "Copy address" menu item, and that one happens to actually contain a CF_UNICODETEXT and that's why I didn't port the HDROP handling into the Win32 code.

[Ah, I see.](https://en.wikipedia.org/wiki/G._K._Chesterton)

File: src/interactivity/win32/Clipboard.cpp (hunk 3 above)
Comment (lhecker) [reply src/interactivity/win32/Clipboard.cpp:74]: Hmm, let me try to restructure the code a little bit and try to unify it with the other HDROP handler in conhost.

**Review by DHowett — APPROVED** [review]

**Review by zadjii-msft — APPROVED** [review]
