### PR TITLE
Pass inbound handoff message via heap so it cannot race out of scope by the time it reaches the ConsoleIoThread

### LINKED ISSUE #10251: [DefApp] PowerShell opened via Win+X errors 50% of the time
### Windows Terminal version (or Windows build number)

10.0.21390.1, 1.9.1445.0

### Other Software

_No response_

### Steps to reproduce

1. Set Windows Terminal Preview to be the default terminal app
2. Use Win+X to open the system menu, then click Windows PowerShell

### Expected Behavior

Windows Terminal opens, with Windows PowerShell as the active shell.

### Actual Behavior

Around 50% of the time it works fine, the other 50% of the time I get the error below:

```
---------------------------
powershell.exe - Application Error
---------------------------
The application was unable to start correctly (0xc0000142). Click OK to close the application. 
---------------------------
OK   
---------------------------
```

Video showing this behaviour:

https://user-images.githubusercontent.com/5821575/119975767-26bbf900-bfae-11eb-9ee7-553a9373d76d.mp4

### PR DESCRIPTION
**Pull request by miniksa**
Pass inbound handoff message via heap so it cannot race out of scope by the time it reaches the ConsoleIoThread

## PR Checklist
* [x] Closes #10251
* [x] I work here.
* [x] Manually verified somewhat

## Detailed Description of the Pull Request / Additional comments
- `OpenConsole.exe` is started in response to the OS `conhost.exe` request for a handoff and prepares an Out Of Proc Multithreaded COM server.
- A COM thread from the pool inside `OpenConsole.exe` picks up the inbound message and allocates some stack space for the `CONSOLE_API_MSG` coming in
- That COM thread calls down to set up the I/O thread that will pump the console driver handle and passes a pointer to the stack-allocated `CONSOLE_API_MSG` as the `LPVOID` parameter for starting the thread.

Now one of two things happen:
1. The I/O thread is scheduled pretty much immediately (or soon enough that the COM thread hasn't messed with the stack space), picks up the pointer to the COM thread's stack with `CONSOLE_API_MSG`, and processes the initial message correctly.
2. The COM thread continues and finalizes the handoff message to `conhost.exe` declaring success. It then pops stack and "frees" the memory space. If it doesn't manage to overwrite it, we're still good. If it does, then things go crazy.

This fix changes it so that the `CONSOLE_API_MSG` is sent into the heap before being passed to the other thread so it's in a known location that won't be freed or overwritten unexpectedly.

## Validation Steps Performed
- [x] - Confirmed that many handoffs from the run box seem to work alright on my system after this change.
- [x] - Confirmed that many tab creations/splits seem to work alright on my system after this change.
- [x] - Would prefer if @ianjoneill could try to F5 this branch to build/deploy it, set it as default, and see if it makes it go away completely... but I'm pretty confident it is this based on the dumps provided either way.

### CODE REVIEW

File: src/host/srvinit.cpp [hunk 1]
```diff
@@ -871,7 +890,11 @@ DWORD WINAPI ConsoleIoThread(LPVOID lpParameter)
...
     {
-        ReceiveMsg = *(PCONSOLE_API_MSG)lpParameter;
+        // Capture the incoming lpParameter into a unique_ptr so we can appropriately
+        // free the heap memory when we're done getting the important bits out of it below.
+        std::unique_ptr<CONSOLE_API_MSG> capturedMessage{ static_cast<PCONSOLE_API_MSG>(lpParameter) };
+
+        ReceiveMsg = *capturedMessage.get();
         ReceiveMsg._pApiRoutines = &globals.api;
         ReceiveMsg._pDeviceComm = globals.pDeviceComm;
         IoSorter::ServiceIoOperation(&ReceiveMsg, &ReplyMsg);
```
Comment (DHowett) [inline src/host/srvinit.cpp:900]: Meh, can we just patch `capturedMessage` directly and hand it off as a pointer instead of copying it?

```suggestion
        IoSorter::ServiceIoOperation(capturedMessage.get(), &ReplyMsg);
```

Comment (miniksa) [reply src/host/srvinit.cpp:900]: Having the leftover stack state in `ReceiveMsg` and `ReplyMsg` when the dump I was given was hung later on at `HRESULT hr = ServiceLocator::LocateGlobals().pDeviceComm->ReadIo(ReplyMsg, &ReceiveMsg);` was what lead me to understand this bug to begin with.

As such, I tried to maintain keeping the "most recent message before hang" in the local variables. If I use the heap one directly, it'll disappear to space if I get another similar hang dump and I'll only have the reply to go on. Additionally, the api and devicecomm bits need to be patched up in `ReceiveMsg` anyway, no matter what, as they're reused message over message.

**Review by DHowett — APPROVED** [review]

**Review by ianjoneill — APPROVED** [review]
Looks good to me - tried about 20 times and it didn't fail 🎉

**Review by zadjii-msft — APPROVED** [review]
