### PR TITLE
Make RIS switch back to the main buffer

### LINKED ISSUE #3685: RIS in the alt buffer should switch to the main buffer
# Environment

Windows build number: Version 10.0.18362.356
Also tested with a recent build from source: 171f00c2656731e5ba0185dbbf337389fb7030bd

# Steps to reproduce

1. Start a WSL bash shell in conhost.
2. Do a directory listing or anything that produces some output.
3. Execute this command: `printf "\e[?1049h\ec\e[?1049l"`

That command switches to the alternate buffer (private mode 1049), executes the [`RIS`](https://vt100.net/docs/vt510-rm/RIS.html) escape sequence (reset to initial state), and then switches back to the main buffer.

# Expected behavior

The `RIS` command should automatically switch back to the main buffer, and then clear the main buffer's screen. The final 1049 sequence isn't relevent at that point, since we are already back in the main buffer. The end result should be a blank screen, other than the shell prompt.

I don't think this behaviour is actually documented anywhere, but that's the way it works in XTerm, and most of the other terminal emulators I've tested.

# Actual behavior

The `RIS` command clears the alternate buffer, and doesn't switch back to the main buffer. So when the final 1049 sequence does switch back, the main buffer contents are all still visible.

### PR DESCRIPTION
**Pull request by j4james**
## Summary of the Pull Request

If we receive a _Reset to Initial State_ (`RIS`) sequence while in the alternate screen buffer, we should be switching back to the main buffer. This PR fixes that behavior.

## PR Checklist
* [x] Closes #3685
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [x] Tests added/passed
* [ ] Requires documentation to be updated
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Detailed Description of the Pull Request / Additional comments

I've added a condition at the start of the `AdaptDispatch::HardReset` method to check whether we're using the alt buffer, and if so, call the `ConGetSet::PrivateUseMainScreenBuffer` API to switch back to the main buffer.

Calling `AdaptDispatch::UseMainScreenBuffer` would probably be neater for this, but it would also attempt to restore the cursor state, which seems pointless when we're in the process of resetting everything anyway.

## Validation Steps Performed

I've added a screen buffer test to confirm that the `RIS` sequence does actually switch back to the main buffer. I've also manually confirmed that the test case in issue #3685 does now behave as expected.

### CODE REVIEW

File: src/terminal/adapter/adaptDispatch.cpp [hunk 1]
```diff
@@ -1663,9 +1663,21 @@ bool AdaptDispatch::SoftReset()
 // True if handled successfully. False otherwise.
 bool AdaptDispatch::HardReset()
```
Comment (zadjii-msft) [inline src/terminal/adapter/adaptDispatch.cpp:1664]: Should we add this to the doc comment for this function?

Comment (j4james) [reply src/terminal/adapter/adaptDispatch.cpp:1666]: Yeah, that seems like a good idea. I've added something in commit 8003b5265d99c89323d3713b82c3075fc43c37cc. Sorry for the delay, but it's been a long day at work.

**Comment by DHowett-MSFT** [comment]
@msftbot merge this in 4 minutes

**Comment by DHowett-MSFT** [comment]
> Sorry for the delay, but it's been a long day at work.

You should never need to apologize for your contributions to our project, especially not right now when the entire world is chaos. :smile: We're happy to have you helping out.
