### PR TITLE
Fix UiaTextRange Misaligned Bounding Rects

### LINKED ISSUE #2551: Bug Report: Misaligned UIA text range bounding rectangles in displays that are not 100%-scale
# Environment
Not 100%-scale display (high DPI monitor)

```none
Windows build number: Microsoft Windows [Version 10.0.18853.1000]
Windows Terminal version (if applicable): v0.4

Any other software?
```

# Steps to reproduce

# Expected behavior
Rectangles should properly surround text inside the text buffer.

# Actual behavior
No alignment or sizing - displaying in the top left corner.

### PR DESCRIPTION
**Pull request by carlos-zamora**
## Summary of the Pull Request
Forgot to include the scaling factor. Also went ahead and used chromium math for this portion.

## PR Checklist
* [x] Closes #2551
* [x] CLA signed.

## Validation Steps Performed
Tested on 200% display and 100% display. Rects are aligned on both.

### CODE REVIEW

File: src/cascadia/TerminalControl/UiaTextRange.cpp [hunk 1]
```diff
@@ -4,10 +4,12 @@
 #include "pch.h"
 #include "UiaTextRange.hpp"
 #include "TermControlUiaProvider.hpp"
+#include <winrt/Windows.Graphics.Display.h>
```
Comment (zadjii-msft) [inline src/cascadia/TerminalControl/UiaTextRange.cpp]: should this go in `pch.h`?

Comment (carlos-zamora) [reply src/cascadia/TerminalControl/UiaTextRange.cpp]: huh.... apparently, it already is... removing.
