### PR TITLE
Disable duplicate button without selected profile

### LINKED ISSUE #12056: [Terminal]: 'Duplicate' button should remain in disabled state until user don't select a profile radio control.
### Windows Terminal version

1.12.3472.0

### Windows build number

10.0.22504.1010

### Other Software

**Test Environment:**
OS: Windows 11 Version Dev (OS Build 22504.1010)
App: Windows Terminal Preview
Screen Reader: Narrator

### Steps to reproduce

**Repro Steps:**
1. Open Windows Terminal.
2. Open Settings page using 'Ctr+,'.
3. Activate 'Add a new profile' tab and then navigate 'Duplicate' button.
4. Observe the issue.

**User Experience:**
Users UX will not be good especially Screen Reader as nothing will happen when they activate 'Duplicate' button. 

**Attachments:**
['Duplicate' button should remain in disabled state until user don't select a profile radio control..zip](https://github.com/microsoft/terminal/files/7783152/Duplicate.button.should.remain.in.disabled.state.until.user.don.t.select.a.profile.radio.control.zip)

### Expected Behavior

'Duplicate' button should remain in disabled state until user don't select a profile radio control.

### Actual Behavior

'Duplicate' button is in enabled state even when user don't select a profile radio control.

**Note Issue:** 'Save' and 'Discard' button should remain in disabled state until we don't make any changes.

### PR DESCRIPTION
**Pull request by davidegiacometti**
## Summary of the Pull Request

- Settings > Add a new profile
- Disable "Duplicate" button until a profile is selected

Duplicate

 
## PR Checklist
* [x] Should take care of #12056, once we can get a build to the a11y team (MAINTAINER EDIT: we unfortunately can't just say "closes #foo" for issues like this one, we need another team to validate the following build.)
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Documentation updated. If checked, please file a pull request on [our docs repo](https://github.com/MicrosoftDocs/terminal) and link it here: #xxx
* [ ] Schema updated.
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

### CODE REVIEW

**Review by zadjii-msft — APPROVED** [review]
Wow that was fast, thanks!

**Comment by zadjii-msft** [comment]
@msftbot make sure @carlos-zamora signs off on this

File: src/cascadia/TerminalSettingsEditor/AddProfile.cpp [hunk 1]
```diff
@@ -39,4 +39,13 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
             _State.RequestDuplicate(selected.try_as<Model::Profile>().Guid());
         }
     }
+
+    void AddProfile::ProfilesSelectionChanged(const IInspectable& /*sender*/,
+                                              const Windows::UI::Xaml::RoutedEventArgs& /*eventArgs*/)
+    {
+        if (!IsProfileSelected())
```
Comment (carlos-zamora) [inline src/cascadia/TerminalSettingsEditor/AddProfile.cpp:46]:
```suggestion
        if (!_IsProfileSelected)
```
nit: I think this'll be faster since we're not calling the function, technically

**Review by carlos-zamora — APPROVED** [review]

**Comment by carlos-zamora** [comment]
Thanks for doing this!

**Comment by htcfreek** [comment]
Small thought: I think it makes more sense to pre select the first profile by default or even better use a drop down menu.

**Comment by carlos-zamora** [comment]
> Small thought: I think it makes more sense to pre select the first profile by default or even better use a drop down menu.

Frankly, I'd prefer to replace all of our radio buttons with combo boxes simply because of the accessibility issues we've had with radio buttons (i.e.: can't update value using keyboard). Plus, combo boxes let you type a letter in and jump to the first relevant entry. But I think [guidance ](https://docs.microsoft.com/en-us/windows/apps/design/controls/radio-button) is to not to for most of our use cases.

For this particular case though, I could go either way. We want every profile to have "equal" value, so radio buttons make sense. Also, the page would look pretty empty without the radio buttons haha. But if we added more stuff like "import profile (JSON)", that would solve that problem. And the accessibility issues I mentioned earlier make me prefer combo boxes. So yeah, idk. 🤷
