### PR TITLE
Preprocess and convert C1 controls to their 7 bit equivalent 

### LINKED ISSUE #7032: VT SOS, APC & PM should be ignored until supported
# Environment

```none
Windows build number: 10.0.19041.388
Windows Terminal version (if applicable): 1.1.2021

Any other software? WSL
```

# Steps to reproduce

Run the following bash command:

```bash
printf '\e_123123\e\\'

printf '\e^123123\e\\'
```

# Expected behavior

Nothing is shown.

# Actual behavior

The data string is printed:

```plaintext
>printf '\e_123123\e\\'
123123%
```

# Detail

Coming from #120 and excellent comments of @j4james  on #6328 , it occurs to me that we should ignore APC and PM the same way as DCS.

Feel free to assign this issue to me as it's very likely to be the next thing in my plan.

### LINKED ISSUE #7317: Preprocess and convert C1 controls to their 7 bit equivalent
# Description of the new feature/enhancement

This is from a discussion in #6328:

> @j4james: I was actually wondering whether this was something we could handle as a sort of preprocessing step that converts all of the C1 controls into their two character 7-bit equivalent. That way we can drop all the extra code that's checking for 90 and 9B introducers, and 9C terminators, because those conditions would now be handled as regular 7-bit escapes.

### PR DESCRIPTION
**Pull request by skyline75489**
C1 control characters are now first converted to their 7 bit equivalent.
This allows us to unify the logic of C1 and C0 escape handling. This
also adds support for SOS/PM/APC string.

* Unify the logic for C1 and C0 escape handling by converting C1 to C0
  beforehand. This adds support for various C1 characters, including
  IND(8/4), NEL(8/5), HTS(8/8), RI(8/13), SS2(8/14), SS3(8/15),
  OSC(9/13), etc. 
* Add support for SOS/PM/APC escape sequences. Fixes #7032
* Use "Variable Length String" logic to unify the string termination
  handling of OSC, DCS and SOS/PM/APC. This fixes an issue where OSC
  action is successfully dispatched even when terminated with non-ST
  character. Introduced by #6328, the DCS PassThrough is spared from
  this issue. This PR puts them together and add test cases for them.

References:
https://vt100.net/docs/vt510-rm/chapter4.html
https://vt100.net/emu/dec_ansi_parser

Closes #7032
Closes #7317

### CODE REVIEW

File: src/terminal/parser/stateMachine.hpp [hunk 1]
```diff
@@ -129,7 +133,9 @@ namespace Microsoft::Console::VirtualTerminal
             DcsIntermediate,
             DcsParam,
             DcsPassThrough,
-            DcsTermination
+            DcsTermination,
+            SosPmApcString,
```
Comment (skyline75489) [inline src/terminal/parser/stateMachine.hpp:137]: OK this is like the very definition of developer-laziness. But in my defense, this is also what https://vt100.net/emu/dec_ansi_parser is using.

File: src/terminal/parser/stateMachine.cpp [hunk 2]
```diff
@@ -86,24 +86,14 @@ static constexpr bool _isC0Code(const wchar_t wch) noexcept
...
-//
-// Arguments:
-// - wch - Character to check.
-// Return Value:
-// - True if it is. False if it isn't.
-static constexpr bool _isC1Dcs(const wchar_t wch) noexcept
+static constexpr wchar_t _c1To7Bit(const wchar_t wch) noexcept
 {
-    return wch == L'\x90';
+    return wch - L'\x40';
```
Comment (skyline75489) [inline src/terminal/parser/stateMachine.cpp:96]: This *seems* correct but I can't find valid reference for this.

File: src/terminal/parser/stateMachine.cpp [hunk 3]
```diff
@@ -320,7 +299,7 @@ static constexpr bool _isOscInvalid(const wchar_t wch) noexcept
 // - True if it is. False if it isn't.
 static constexpr bool _isOscTerminator(const wchar_t wch) noexcept
 {
-    return wch == AsciiChars::BEL || _isStringTerminator(wch); // Bell character or C1 terminator
+    return wch == AsciiChars::BEL; // Bell character
```
Comment (skyline75489) [inline src/terminal/parser/stateMachine.cpp:302]: Should `BEL` also terminate DCS and SOS/PM/APC ?

File: src/terminal/parser/stateMachine.cpp (hunk 2 above)
Comment (j4james) [reply src/terminal/parser/stateMachine.cpp:96]: Yeah, I believe this is correct. Quoting the `DEC ST 070` manual:
> expansion escape sequence (Fe) - 2-character escape sequence in which the final character is in columns 4 and 5, and is used to extend the 7-bit code table by being the row equivalent to the corresponding C1 set of controls in columns 8 and 9 of an 8-bit code.

File: src/terminal/parser/stateMachine.cpp (hunk 3 above)
Comment (j4james) [reply src/terminal/parser/stateMachine.cpp:302]: I don't think so. My understanding is that it's just supported for legacy reasons in OSC, but is not actually part of the DEC or ANSI standards. Not all terminals handled this the same way, but I think the majority (including XTerm) will only recognise BEL as a terminator in OSC, so I'd recommend we follow that behaviour.

File: src/terminal/parser/stateMachine.cpp (hunk 2 above)
Comment (DHowett) [reply src/terminal/parser/stateMachine.cpp:96]: (Should we prefer `-0x40` or `&~0x40` here?)

Comment (skyline75489) [reply src/terminal/parser/stateMachine.cpp:96]: I choose `L'\x40'` cuz I want it have the same type as `wch`. Not that it mean anything, but hey, no implicit conversion.

File: src/terminal/parser/stateMachine.cpp [hunk 4]
```diff
@@ -1322,13 +1365,6 @@ void StateMachine::_EventOscString(const wchar_t wch)
 // - wch - Character that triggered the event
 // Return Value:
 // - <none>
-void StateMachine::_EventOscTermination(const wchar_t wch)
-{
-    _trace.TraceOnEvent(L"OscTermination");
-
-    _ActionOscDispatch(wch);
```
Comment (skyline75489) [inline src/terminal/parser/stateMachine.cpp:1329]: This behaviour is effectively changed. Now we only dispatch the OSC string when `\\` or `BEL` is seen. Is there any negative impact?

File: src/terminal/parser/stateMachine.cpp [hunk 5]
```diff
@@ -1634,21 +1656,43 @@ void StateMachine::_EventDcsPassThrough(const wchar_t wch)
...
+    {
+        _EnterSosPmApcTermination();
+    }
+    else
+    {
+        _ActionIgnore();
+    }
+}
 
+void StateMachine::_EventVariableLengthStringTermination(const wchar_t wch)
```
Comment (skyline75489) [inline src/terminal/parser/stateMachine.cpp:1680]: This ought to fix the ESC termination issue described here https://github.com/microsoft/terminal/pull/6328/files#r459167887

File: src/terminal/parser/stateMachine.cpp (hunk 4 above)
Comment (skyline75489) [reply src/terminal/parser/stateMachine.cpp:1329]: OK maybe I'm a little bit paranoid about changing the current code. It's a bugfix, right? It must change something to fix the bug. Would love someone to confirm this, though.

File: src/terminal/parser/stateMachine.cpp [hunk 6]
```diff
@@ -1952,3 +2016,16 @@ void StateMachine::_AccumulateTo(const wchar_t wch, size_t& value) noexcept
...
+// - Determines if the engine is in "Variable Length String" state, which is a combination
+//   of all states that are expecting a string that has a undetermined length.
+//
+// Arguments:
+// - <none>
+// Return Value:
+// - True if it is. False if it isn't.
+const bool StateMachine::_IsVariableLengthStringState() const noexcept
+{
+    return _state == VTStates::OscString || _state == VTStates::DcsPassThrough || _state == VTStates::SosPmApcString;
```
Comment (skyline75489) [inline src/terminal/parser/stateMachine.cpp:2030]: From the graph here https://vt100.net/emu/dec_ansi_parser, these are the only three cases. Not sure if there's more.

File: src/terminal/parser/stateMachine.hpp (hunk 1 above)
Comment (skyline75489) [reply src/terminal/parser/stateMachine.hpp:137]: I think when SOS/PM/APC actually do something on their own, it would still be easy to create new dedicated states for them.

File: src/terminal/parser/stateMachine.cpp [hunk 7]
```diff
@@ -367,7 +368,7 @@ static constexpr bool _isDcsPassThroughValid(const wchar_t wch) noexcept
 // - True if it is. False if it isn't.
 static constexpr bool _isActionableFromGround(const wchar_t wch) noexcept
 {
-    return (wch <= AsciiChars::US) || _isC1Csi(wch) || _isC1Dcs(wch) || _isDelete(wch);
+    return (wch <= AsciiChars::US) || _isC1ControlCharacter(wch) || _isDelete(wch);
```
Comment (skyline75489) [inline src/terminal/parser/stateMachine.cpp:371]: I just realized by doing C1 SS3(8/15) and C1 OSC(9/13) are also supported. And why are they not supported before? Is there anything special about them?

File: src/terminal/parser/stateMachine.cpp [hunk 8]
```diff
@@ -1497,24 +1517,16 @@ void StateMachine::_EventDcsEntry(const wchar_t wch)
...
-//   1. Enter ground on a String terminator
-//   2. Ignore everything else.
+//   In this state the entire DCS string is considered invalid and we will ignore everything.
+//   The termination state is handled outside when an ESC is seen.
 // Arguments:
 // - wch - Character that triggered the event
 // Return Value:
 // - <none>
-void StateMachine::_EventDcsIgnore(const wchar_t wch) noexcept
+void StateMachine::_EventDcsIgnore() noexcept
```
Comment (skyline75489) [inline src/terminal/parser/stateMachine.cpp:1526]: It’s a little weird to have just one case in this, isn’t it. But this is actually the correct way to do this.

File: src/terminal/parser/stateMachine.cpp [hunk 9]
```diff
@@ -1634,21 +1640,52 @@ void StateMachine::_EventDcsPassThrough(const wchar_t wch)
...
+void StateMachine::_EventVariableLengthStringTermination(const wchar_t wch)
+{
     if (_isStringTerminatorIndicator(wch))
     {
-        // TODO: The Dcs sequence has successfully terminated. This is where we'd be dispatching the DCS command.
+        if (_state == VTStates::OscTermination)
+        {
+            _ActionOscDispatch(wch);
+        }
+        if (_state == VTStates::DcsTermination)
```
Comment (zadjii-msft) [inline src/terminal/parser/stateMachine.cpp:1681]: should these be `else if`s? I get that `_Action*Dispatch` _shouldn't_ change the state, but still...

(this is a nit)

**Review by j4james — APPROVED** [review]
This looks good to me. I've run a few basic tests with it, and the C1 controls are now working as expected, and the APC/PM/SOS sequences are being appropriately ignored. I'm a little concerned about the input side of things, because I'm not how to test that, but I think the C1 mapping should still be OK for that.

File: src/terminal/parser/stateMachine.cpp (hunk 9 above)
Comment (skyline75489) [reply src/terminal/parser/stateMachine.cpp:1681]: I'll fix those nits in my next PR for #7316 if it's OK with you.  Thanks Mike, as always.

**Comment by skyline75489** [comment]
Thanks @j4james . I literally couldn't write any of these PRs without you . You know originally I just want those dazzling Sixel images. But who knows VT sequences are actually full of fun. Be prepared for my following unknown numbers of PRs that's VT related 😄 .

File: src/terminal/parser/stateMachine.cpp (hunk 9 above)
Comment (skyline75489) [reply src/terminal/parser/stateMachine.cpp]: I'm having some trouble with the fix for #7316 where the performance of DCS passthrough is not good enough. So I won't be able to file a new PR soon. I think we can ship this PR first and see where it takes us.

**Review by DHowett — APPROVED** [review]
Okay - I finally read over this, and I think I understand how this improves our state machine. I've got to trust Mike and James here, as well. Thanks @skyline75489!

**Comment by DHowett** [comment]
@msftbot merge this in 1 minute

**Comment by DHowett** [comment]
This fix was just released as part of Windows in [Insider Build 20236](https://blogs.windows.com/windows-insider/2020/10/14/announcing-windows-10-insider-preview-build-20236/)!
