### PR TITLE
Fix viewport moving when we've scrolled up and circled the buffer

### LINKED ISSUE #7222: Output should not keep scrolling down when manually scrolled up
# Description of the new feature/enhancement
For example, when tailing/following a log, and cursor is at the bottom. I expect the output to be scrolled down automatically.

However, if I manually scroll up to certain spot (e.g., looking at a test failure), I don't want my current view keep getting scrolled down. It should lock in place when user manually scrolls up. When user scrolls all the way to the bottom, then it should resume tailing.

### PR DESCRIPTION
**Pull request by zadjii-msft**
If you scroll up to view the scrollback, then we want the viewport to
"stay in place", as new output comes in (see #6062). This works fine up
until the buffer circles. In this case, the mutable viewport isn't
actually moving, so we never set `updatedViewport` to true. 

This regressed in #6062
Closes #7222

### CODE REVIEW

File: src/cascadia/TerminalCore/Terminal.cpp [hunk 1]
```diff
@@ -843,15 +843,31 @@ void Terminal::_AdjustCursorPosition(const COORD proposedPosition)
...
 
         _scrollOffset = scrollToOutput ? 0 : _scrollOffset + scrollAmount + newRows;
 
+        // Clamp the range to make sure that we don't scroll way off the top of the buffer
+        _scrollOffset = std::clamp(_scrollOffset,
+                                   0,
+                                   _buffer->GetSize().Height() - _mutableViewport.Height());
+
+        // If the new scroll offset is different, then we'll still want to raise a scroll event
+        updatedViewport |= oldScrollOffset != _scrollOffset;
```
Comment (DHowett) [inline src/cascadia/TerminalCore/Terminal.cpp:865]: augh binary or on a logical expression
technically works
is technically incorrect

Comment (DHowett) [reply src/cascadia/TerminalCore/Terminal.cpp:865]:
```suggestion
        updatedViewport = updatedViewport || (oldScrollOffset != _scrollOffset);
```

**Comment by DHowett** [comment]
@msftbot merge this in 1 minute
