### PR TITLE
Blink the cursor

### LINKED ISSUE #665: Cursor does not blink
* Your Windows build number: Microsoft Windows [Version 10.0.18362.86]
* What you're doing and what's happening:
Run Windows Terminal (Preview) and it started with cmd.exe. The cursor is not blink as in original console.
* What's wrong / what should be happening instead:
The cursor does not blink.

### PR DESCRIPTION
**Pull request by dkter**
Resolves #665. Behaviour was discussed a bit there:

- When the window is not in focus, the cursor is not shown.
- When the user is typing, the cursor is constantly shown.
- Otherwise, the cursor blinks.

### CODE REVIEW

**Comment by DHowett-MSFT** [comment]
I’ll defer to @miniksa on this, as he has some cursor-related battle scars

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 1]
```diff
@@ -410,6 +410,30 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
         auto pfnScrollPositionChanged = std::bind(&TermControl::_TerminalScrollPositionChanged, this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3);
         _terminal->SetScrollPositionChangedCallback(pfnScrollPositionChanged);
 
+        // Set up blinking cursor
+        DispatcherTimer cursorTimer;
```
Comment (zadjii-msft) [inline src/cascadia/TerminalControl/TermControl.cpp]: I'd prefer if `cursorTimer` was a private member variable on `TermControl`, and instead of setting up some lambdas here for each of `GotFocus`, and `LostFocus`, we had methods on `TermControl` instead. See the handler for `PreviewKeyDown`, set up on L404 as an example.

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 2]
```diff
@@ -410,6 +410,30 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
...
+        });
+
+        _controlRoot.LostFocus([this, cursorTimer](auto&, auto&) {
+            // Stop blinking the cursor when the window goes out of focus,
+            // and hide it.
+            cursorTimer.Stop();
+            _terminal->SetCursorVisible(false);
+        });
+
+        _controlRoot.KeyDown([this, cursorTimer](auto&, auto&) {
```
Comment (zadjii-msft) [inline src/cascadia/TerminalControl/TermControl.cpp]: Could we do this in the `TermControl::_KeyDownHandler` we already have registered?

File: src/cascadia/TerminalCore/terminalrenderdata.cpp [hunk 3]
```diff
@@ -70,6 +70,12 @@ bool Terminal::IsCursorOn() const noexcept
     return cursor.IsOn();
 }
 
+void Terminal::SetCursorVisible(const bool isVisible) noexcept
```
Comment (zadjii-msft) [inline src/cascadia/TerminalCore/terminalrenderdata.cpp]: I'd prefer if this was in `Terminal.cpp` instead - I think this file is specifically for methods defined in the `IRenderData` interface (though that's not called out anywhere so that's my bad :P)

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 1 above)
Comment (dkter) [reply src/cascadia/TerminalControl/TermControl.cpp]: Thanks for the feedback, I'll work on it!

**Comment by mdtauk** [comment]
I asked this in a related issue, Is the blink rate respecting the user's setting?

image

It was mentioned there is an API to get this...
https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-getcaretblinktime

**Comment by dkter** [comment]
@mdtauk Thanks, I'll look into that. I was going to ask if there should eventually be a setting for the blink rate but it looks like Windows already has that covered!

**Comment by mdtauk** [comment]
@dkter  The setting is buried in the Control Panel, and has not yet been moved over to the new Settings app.  Perhaps someone on the Windows team knows if/when this may be migrated.

I can't speak for how many people know of or adjust this setting, so there may be a case of handling this within the app alone.

I just thought I would bring attention to it.

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 4]
```diff
@@ -410,6 +412,24 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
...
         _terminal->SetScrollPositionChangedCallback(pfnScrollPositionChanged);
 
+        // Set up blinking cursor
+        int blinkTime = GetCaretBlinkTime();
+        if (blinkTime != INFINITE)
+        {
+            // Create a timer
+            _cursorTimer = std::make_optional(DispatcherTimer());
+            _cursorTimer.value().Interval(std::chrono::milliseconds(blinkTime));
+            auto registrationtoken = _cursorTimer.value().Tick({ this, &TermControl::_BlinkCursor });
```
Comment (zadjii-msft) [inline src/cascadia/TerminalControl/TermControl.cpp]: Looks like `registrationtoken` is unused after here, so I think you can go ahead and skip the assignment, and leave it as 
```
_cursorTimer.value().Tick({ this, &TermControl::_BlinkCursor });
```

File: src/cascadia/TerminalControl/TermControl.h [hunk 5]
```diff
@@ -100,7 +102,10 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
         void _PointerReleasedHandler(Windows::Foundation::IInspectable const& sender, Windows::UI::Xaml::Input::PointerRoutedEventArgs const& e);
         void _MouseWheelHandler(Windows::Foundation::IInspectable const& sender, Windows::UI::Xaml::Input::PointerRoutedEventArgs const& e);
         void _ScrollbarChangeHandler(Windows::Foundation::IInspectable const& sender, Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs const& e);
+        void _GotFocusHandler(Windows::Foundation::IInspectable const & sender, Windows::UI::Xaml::RoutedEventArgs const & e);
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalControl/TermControl.h]:
```suggestion
        void _GotFocusHandler(Windows::Foundation::IInspectable const& sender, Windows::UI::Xaml::RoutedEventArgs const& e);
```

File: src/cascadia/TerminalControl/TermControl.h [hunk 6]
```diff
@@ -100,7 +102,10 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
         void _PointerReleasedHandler(Windows::Foundation::IInspectable const& sender, Windows::UI::Xaml::Input::PointerRoutedEventArgs const& e);
         void _MouseWheelHandler(Windows::Foundation::IInspectable const& sender, Windows::UI::Xaml::Input::PointerRoutedEventArgs const& e);
         void _ScrollbarChangeHandler(Windows::Foundation::IInspectable const& sender, Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs const& e);
+        void _GotFocusHandler(Windows::Foundation::IInspectable const & sender, Windows::UI::Xaml::RoutedEventArgs const & e);
+        void _LostFocusHandler(Windows::Foundation::IInspectable const & sender, Windows::UI::Xaml::RoutedEventArgs const & e);
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalControl/TermControl.h]:
```suggestion
        void _LostFocusHandler(Windows::Foundation::IInspectable const& sender, Windows::UI::Xaml::RoutedEventArgs const& e);
```

File: src/cascadia/TerminalControl/TermControl.h (hunk 5 above)
Comment (dkter) [reply src/cascadia/TerminalControl/TermControl.h]: whoops, didn't even notice that! good catch

**Comment by DHowett-MSFT** [comment]
@dkter Thanks for the contribution!
