### PR TITLE
Captured pointer for SwapChainPanel and ScrollBar separately

### LINKED ISSUE #950: Terminal selects lines when scrolling down the scroll bar and crashes when right clicked afterwards
Windows terminal exits with code -1073741189 (0xc000027b). When clicking on a spot in the terminal, dragging down the scroll bar, then right clicking.

# Environment

```none
Windows build number: [Version 10.0.18898.1000]  
Using powershell
```

# Steps to reproduce

- Populate the terminal with ls until scroll bar is around 1/3 height of the terminal
- Scroll up top the top
- Left click within the terminal
Capture1

- Drag the scroll bar down
Capture2

- Right click within the terminal

# Expected behavior

Expected the terminal to do nothing.

# Actual behavior
Exited with code -1073741189.

### PR DESCRIPTION
**Pull request by carlos-zamora**
## Summary of the Pull Request
- capturing the SwapChainPanel and ScrollBar separately:
  - it used to be that the root would take pointer events. So both the scroll bar AND the terminal would respond to a mouse drag on the scroll bar. Yuck!
- Renamed MouseClickHandler and MouseMovedHandler to more generic names (since they handle touch events too).

 
## References
So, this fixes #950, but also doesn't. The reason #950 crashes is because the copy is waaaaaay too big. This will make it so that you can't make the selection that unreasonably big anymore. That said, there's still other ways to make massive copy selections so I think there's two relevant issues here:
- #1246 Copy large selection --> crash
- #1247 While selecting, dragging mouse over top/bottom border scrolls.

## PR Checklist
* [x] Closes #950
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [x] Tests added/passed
* [x] Requires documentation to be updated
* [x] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan.

### CODE REVIEW

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 1]
```diff
@@ -499,9 +501,9 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
         }
 
         _root.PointerWheelChanged({ this, &TermControl::_MouseWheelHandler });
-        _root.PointerPressed({ this, &TermControl::_MouseClickHandler });
-        _root.PointerMoved({ this, &TermControl::_MouseMovedHandler });
-        _root.PointerReleased({ this, &TermControl::_PointerReleasedHandler });
+        _swapChainPanel.PointerPressed({ this, &TermControl::_PointerPressedHandler });
```
Comment (zadjii-msft) [inline src/cascadia/TerminalControl/TermControl.cpp]: I'd maybe add a comment referring to this issue that calls out why these are on `_swapChainPanel` instead of `_root` like (most) everything else

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 2]
```diff
@@ -671,9 +673,11 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
     // Arguments:
     // - sender: not used
```
Comment (zadjii-msft) [inline src/cascadia/TerminalControl/TermControl.cpp]: nit: These args aren't unused anymore

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 3]
```diff
@@ -671,9 +673,11 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
     // Arguments:
     // - sender: not used
     // - args: event data
-    void TermControl::_MouseClickHandler(Windows::Foundation::IInspectable const& /*sender*/,
+    void TermControl::_PointerPressedHandler(Windows::Foundation::IInspectable const& sender,
                                          Input::PointerRoutedEventArgs const& args)
```
Comment (zadjii-msft) [inline src/cascadia/TerminalControl/TermControl.cpp]: nit: does clang-format really not care that these args aren't aligned anymore? I thought it would...

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 4]
```diff
@@ -949,6 +955,30 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
...
 
+    // Method Description:
+    // - captures the pointer so that none of the other XAML elements respond to pointer events
+    // Arguments:
+    // - sender: XAML element that is interacting with pointer
+    // - args: pointer data (i.e.: mouse, touch)
+    void TermControl::_CapturePointer(Windows::Foundation::IInspectable const& sender, Windows::UI::Xaml::Input::PointerRoutedEventArgs const& args)
+    {
+        IUIElement uielem;
+        sender.as(uielem);
```
Comment (zadjii-msft) [inline src/cascadia/TerminalControl/TermControl.cpp]: What happens if the sender isn't a `IUIElement`?

Comment (zadjii-msft) [reply src/cascadia/TerminalControl/TermControl.cpp]: (I mean, I know that in our cases, this is fine, but I'd rather be more safe than sorry)

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 3 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalControl/TermControl.cpp]: They're aligned. I think this might be a GitHub preview bug.

---
In reply to: [293539451](https://github.com/microsoft/terminal/pull/1248#discussion_r293539451) [](ancestors = 293539451)

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 4 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalControl/TermControl.cpp]: I changed it to return a bool. It doesn't crash now but I could still totally see somebody using it improperly. Is this fine, though? Might be overthinking it.

---
In reply to: [293540403](https://github.com/microsoft/terminal/pull/1248#discussion_r293540403) [](ancestors = 293540403)
