### PR TITLE
UIA: Fix GetVisibleRanges() and add Tracing

### LINKED ISSUE #1914: Task: Re-attach Tracing to UIA Tree
# Summary of the new feature/enhancement

I'm removing `Microsoft::Console::Interactivity::Win32::Tracing`s `s_TraceUia()` temporarilly in my Accessibility PR #1691 . I need to hook this back up. Filing this as a task.

### LINKED ISSUE #4507: ScreenInfoUiaProvider::GetVisibleRanges() returns an improper result
# Summary
Our TermControlUiaProvider (aka ScreenInfoUiaProvider) returns a list of `UiaTextRange` for our visible ranges (one per row in the buffer).

The docs for `GetVisibleRanges` state we should only return one range.

# Technical Details
We only have one continuous span of text visible at a time (within a given Terminal Control).

The documentation for [GetVisibleRanges](https://docs.microsoft.com/en-us/windows/win32/api/uiautomationcore/nf-uiautomationcore-itextprovider-getvisibleranges) states as follows:

>If the visible text consists of one contiguous span of text, the pRetVal array should contain a single text range that represents all of the visible text.
>
>
>ITextProvider::GetVisibleRanges should return a degenerate (empty) text range if no text is visible, if all text is scrolled out of view, or if the text-based control contains no text.

### PR DESCRIPTION
**Pull request by carlos-zamora**
## Summary of the Pull Request
Debugging our custom UIA providers has been a painful experience because outputting content to VS may result in UIA Clients getting impatient and giving up on extracting data.

Adding tracing allows us to debug these providers without getting in the way of reproducing a bug. This will help immensely with developing accessibility features on Windows Terminal and Console.

This pull request additionally contains payload from #4526:
* Make GetVisibleRanges() return one range (and add tracing for it).
`ScreenInfoUiaProvider::GetVisibleRanges()` used to return one range per line of visible text. The documentation for this function says that we should return one per contiguous span of text. Since all of the text in the TermControl will always be contiguous (at least by our standards), we should only ever be returning one range.

## PR Checklist
* [x] Closes #1914. Closes #4507.
* [x] CLA signed

## Detailed Description of the Pull Request / Additional comments
`UiaTracing` is a singleton class that is in charge of registration for trace logging. `TextRange` is used to trace `UiaTextRange`, whereas `TextProvider` is used to trace `ScreenInfoUiaProviderBase`.

`_getValue()` is overloaded to transform complex objects and enums into a string for logging.

`_getTextValue()` had to be added to be able to trace the text a UiaTextRange included. This makes following UiaTextRanges much simpler.

## Validation Steps Performed
Performed a few operations when under NVDA/Narrator and manually checked the results.

### CODE REVIEW

File: src/types/UiaTextRangeBase.cpp [hunk 1]
```diff
@@ -463,7 +463,7 @@ try
     *ppRetVal = nullptr;
 
 #pragma warning(suppress : 26447) // QueryInterface's exception should be caught by the try-CATCH_RETURN block to allow this to be noexcept
-    auto hr = _pProvider->QueryInterface(IID_PPV_ARGS(ppRetVal));
+    const auto hr = _pProvider->QueryInterface(IID_PPV_ARGS(ppRetVal));
```
Comment (DHowett-MSFT) [inline src/types/UiaTextRangeBase.cpp]: if `_pProvider` is a ComPtr here and you _are_ changing this line, please use `_pProvider.CopyTo(ppRetVal)`

File: src/types/UiaTextRangeBase.cpp [hunk 2]
```diff
@@ -1191,23 +1194,21 @@ std::wstring UiaTextRangeBase::_getTextValue() const noexcept
...
-        return {};
+        stream << buffer.GetTextDataAt(pos)->data();
+        bufferSize.IncrementInBounds(pos, true);
     }
+
+    return stream.str();
+}
+catch (...)
+{
+    return {};
```
Comment (DHowett-MSFT) [inline src/types/UiaTextRangeBase.cpp]: consider `LOG_CAUGHT_EXCEPTION()`

File: src/types/UiaTracing.cpp [hunk 3]
```diff
@@ -4,6 +4,16 @@
 #include "precomp.h"
 #include "UiaTracing.h"
 
+// we need to disable a few warnings because
+// the TraceLogging code is out of our control
+#pragma warning(push)
+#pragma warning(disable : 26447)
```
Comment (DHowett-MSFT) [inline src/types/UiaTracing.cpp]: jesus, is there no way to compress these to one line lol

Comment (DHowett-MSFT) [reply src/types/UiaTracing.cpp]: okay lokos like `warning(disable:1 2 3 4 5)`

Comment (DHowett-MSFT) [reply src/types/UiaTracing.cpp]: looks

**Comment by DHowett-MSFT** [comment]
sorry, i was just looking at one commit. re-reviewing.

File: src/types/ScreenInfoUiaProviderBase.cpp [hunk 4]
```diff
@@ -381,30 +347,26 @@ IFACEMETHODIMP ScreenInfoUiaProviderBase::GetVisibleRanges(_Outptr_result_mayben
             return hr;
         }
     }
+    UiaTracing::TextProvider::GetVisibleRanges(*this, *range.Get());
```
Comment (DHowett-MSFT) [inline src/types/ScreenInfoUiaProviderBase.cpp]: range might be null, which would make this explode _spectacularly_.. right/

Comment (DHowett-MSFT) [reply src/types/ScreenInfoUiaProviderBase.cpp]: oh i guess not... if you ever got out here with it being null..
hmm\
okay. but i don't love it. comment?

Comment (DHowett-MSFT) [reply src/types/ScreenInfoUiaProviderBase.cpp]: also, wait, no. you're calling `range.Detach()`. That is definitely not going to be an okay ComPtr to call `.Get` on later.

File: src/types/UiaTextRangeBase.cpp [hunk 5]
```diff
@@ -528,9 +462,11 @@ try
     RETURN_HR_IF(E_INVALIDARG, ppRetVal == nullptr);
     *ppRetVal = nullptr;
 
-    //Tracing::s_TraceUia(this, ApiCall::GetBoundingRectangles, nullptr);
 #pragma warning(suppress : 26447) // QueryInterface's exception should be caught by the try-CATCH_RETURN block to allow this to be noexcept
-    return _pProvider->QueryInterface(IID_PPV_ARGS(ppRetVal));
+    const auto hr = _pProvider->QueryInterface(IID_PPV_ARGS(ppRetVal));
+    // TODO CARLOS: fix tracing call
```
Comment (DHowett-MSFT) [inline src/types/UiaTextRangeBase.cpp]: why is this still a todo?

File: src/types/UiaTextRangeBase.cpp [hunk 6]
```diff
@@ -1330,3 +1178,37 @@ RECT UiaTextRangeBase::_getTerminalRect() const
         gsl::narrow<LONG>(result.top + result.height)
     };
 }
+
+#pragma warning(push)
+#pragma warning(disable : 26447) // compiler isn't filtering throws inside the try/catch
+std::wstring UiaTextRangeBase::_getTextValue() const noexcept
```
Comment (DHowett-MSFT) [inline src/types/UiaTextRangeBase.cpp]: what is this now?

File: src/types/UiaTextRangeBase.cpp (hunk 1 above)
Comment (carlos-zamora) [reply src/types/UiaTextRangeBase.cpp]: not a ComPtr :( just a weak pointer.

File: src/types/ScreenInfoUiaProviderBase.cpp (hunk 4 above)
Comment (carlos-zamora) [reply src/types/ScreenInfoUiaProviderBase.cpp]: You're absolutely right. Unfortunately, this entire function is just all sorts of wrong (see #4507).

Commenting the tracing off of this function and adding a TODO work item. 😡

File: src/types/UiaTextRangeBase.cpp (hunk 6 above)
Comment (carlos-zamora) [reply src/types/UiaTextRangeBase.cpp]: Discussed offline.

This is necessary because we need the `const` on that function header.

Decision: I'll make our current `GetText` use this as a helper function.

**Comment by DHowett-MSFT** [comment]
oop this one got another PR merged into it

File: src/types/UiaTracing.cpp [hunk 7]
```diff
@@ -0,0 +1,523 @@
...
+{
+    TraceLoggingUnregister(g_UiaProviderTraceProvider);
+}
+
+inline std::wstring UiaTracing::_getValue(const ScreenInfoUiaProviderBase& /*siup*/) noexcept
+try
+{
+    std::wstringstream stream;
+    stream << " NO IDENTIFYING DATA";
+    return stream.str();
```
Comment (miniksa) [inline src/types/UiaTracing.cpp]: Uh... can we just return the string until proven otherwise instead of making a whole string stream and coming back to the string?

**Comment by DHowett-MSFT** [comment]
I've updated the PR description to include the GetVisibleRanges change.

File: src/types/UiaTextRangeBase.hpp [hunk 8]
```diff
@@ -152,7 +152,7 @@ namespace Microsoft::Console::Types
         // This is used by tracing to extract the text value
         // that the UiaTextRange currently encompasses.
         // GetText() cannot be used as it's not const
-        std::wstring _getTextValue() const noexcept;
+        std::wstring _getTextValue(int maxLength = -1) const noexcept;
```
Comment (DHowett-MSFT) [inline src/types/UiaTextRangeBase.hpp]: this looks like a std::optional to me

File: src/types/UiaTracing.h [hunk 9]
```diff
@@ -88,9 +88,9 @@ namespace Microsoft::Console::Types
         UiaTracing& operator=(const UiaTracing&) = delete;
         UiaTracing& operator=(UiaTracing&&) = delete;
 
-        static std::wstring _getValue(const ScreenInfoUiaProviderBase& siup) noexcept;
-        static std::wstring _getValue(const UiaTextRangeBase& utr) noexcept;
-        static std::wstring _getValue(const TextPatternRangeEndpoint endpoint) noexcept;
-        static std::wstring _getValue(const TextUnit unit) noexcept;
+        static inline std::wstring _getValue(const ScreenInfoUiaProviderBase& siup) noexcept;
```
Comment (DHowett-MSFT) [inline src/types/UiaTracing.h]: if they're static _inline_ they don't even need to be in the header.. but also i don't care
