### PR TITLE
Don't just die if the user doesn't have the dx debugging tools

### LINKED ISSUE #14316: Renderer encountered an unexpected error
### Windows Terminal version

main b4d37d8c7

### Windows build number

10.0.22621.169 (aarch64)

### Other Software

_No response_

### Steps to reproduce

- build latest source on Windows `aarch64` (Windows DevKit 2023 used for testing)

### Expected Behavior

- terminal to launch

### Actual Behavior

Error message: `This terminal has encountered an issue with the graphics driver and it could not recover in time. It has been suspended.`

Upon pressing `Resume` an error is thrown:

Screenshot 2022-10-31 190138

### PR DESCRIPTION
**Pull request by zadjii-msft**
This PR gives the atlas engine an attempt to retry a couple operations where it asks for debug flags when we're in debug mode. If you don't have the Graphics debugger and GPU profiler for DirectX installed, then these calls will fail, and we end up blowing up the renderer. Instead, just try again. 

Originally, I actually thought I had hit #14082, but after sorting this out, it was just #14316.

closes #14316

### CODE REVIEW

File: src/renderer/atlas/AtlasEngine.r.cpp [hunk 1]
```diff
@@ -121,7 +121,18 @@ void AtlasEngine::_recreateAdapter()
 #endif
 
     // IID_PPV_ARGS doesn't work here for some reason.
-    THROW_IF_FAILED(CreateDXGIFactory2(flags, __uuidof(_p.dxgi.factory), _p.dxgi.factory.put_void()));
+    auto hr = (CreateDXGIFactory2(flags, __uuidof(_p.dxgi.factory), _p.dxgi.factory.put_void()));
```
Comment (lhecker) [inline src/renderer/atlas/AtlasEngine.r.cpp:124]: Redundant parentheses

File: src/renderer/atlas/AtlasEngine.r.cpp [hunk 2]
```diff
@@ -189,7 +200,7 @@ void AtlasEngine::_recreateBackend()
         D3D_FEATURE_LEVEL_9_1,
     };
 
-    THROW_IF_FAILED(D3D11CreateDevice(
+    auto hr = (D3D11CreateDevice(
```
Comment (lhecker) [inline src/renderer/atlas/AtlasEngine.r.cpp:203]: Redundant parentheses

File: src/renderer/atlas/AtlasEngine.r.cpp [hunk 3]
```diff
@@ -201,6 +212,29 @@ void AtlasEngine::_recreateBackend()
...
 
+#ifndef NDEBUG
+    if (hr == DXGI_ERROR_SDK_COMPONENT_MISSING)
+    {
+        // This might happen if you don't have "Graphics debugger and GPU
+        // profiler for DirectX" installed in VS. We shouln't just explode if
+        // you don't though - instead, disable debugging and try again.
+        WI_ClearFlag(deviceFlags, D3D11_CREATE_DEVICE_DEBUG);
+
+        hr = (D3D11CreateDevice(
```
Comment (lhecker) [inline src/renderer/atlas/AtlasEngine.r.cpp:223]: Redundant parentheses

**Review by lhecker — APPROVED** [review]
I marked the 3 spots that have leftover ().

**Review by DHowett — APPROVED** [review]
