### PR TITLE
Close tab context menu on titlebar click

### LINKED ISSUE #7988: Context menu on tabs doesn't close when clicking in the title bar
# Environment

```none
PS> [System.Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0

Windows Terminal
Version: 1.3.2651.0
```

# Steps to reproduce

1. Right click on a tab in Windows Terminal to open the context menu.
2. Click somewhere else to close it again.

# Expected behavior

The context menu closes, regardless of where the click in step 2 goes.

# Actual behavior

The context menu closes in pretty much all places, even different applications (presumably because losing focus also closes it), but doesn't close when clicking the title bar of WIndows Terminal. It does close when clicking controls in the title bar, though, even the default window buttons in the upper right.

### PR DESCRIPTION
**Pull request by mpela81**
Close the tab context menu when clicking on the title bar

## Detailed Description of the Pull Request / Additional comments
Following #2438, hide the tabs context menu on `TerminalPage::TitlebarClicked()`. 
We don't know which of the tabs is showing the context menu, do it on all tabs.

## Validation Steps Performed
Open the context menu from any tab, click on title bar and see the context menu disappear.

Closes #7988

### CODE REVIEW

**Review by zadjii-msft — APPROVED** [review]
Seems like it should work to me. Thanks!

**Review by DHowett — COMMENTED** [review]
I hate that we have to do this, but I totally understand.

File: src/cascadia/TerminalApp/TerminalPage.cpp [hunk 1]
```diff
@@ -2226,6 +2226,15 @@ namespace winrt::TerminalApp::implementation
         {
             _newTabButton.Flyout().Hide();
         }
+
+        for (auto tab : _tabs)
```
Comment (DHowett) [inline src/cascadia/TerminalApp/TerminalPage.cpp:2230]:
```suggestion
        for (const auto& tab : _tabs)
```

may save a few cycles doing AddRef/Release on each tab

**Review by DHowett — APPROVED** [review]
