### PR TITLE
Fix updating with fragments ignoring original profile settings

### LINKED ISSUE #9290: Proto-extensions ignore existing profile settings
If I use a proto-extension that `"updates"` an existing profile, all of the existing settings in my original profile are ignored.

Additionally, if I try to add a profile setting after a proto-extension is installed that `"updates"` that profile, the setting is instantly deleted.

Proto-extensions generate a new profile in settings.json using the same GUID, thus overriding all customizations to the original profile.

# Environment

```none
Windows build number: 10.0.21318.0
Windows Terminal version (if applicable): 1.7.543.0

Any other software?
```

# Steps to reproduce

Here's an example scenario:

My Ubuntu profile sets a background image:

```
{
    "backgroundImage": "C:\\Users\\cinnamon\\Pictures\\01 gettyimages-1129788053_resized.jpg",
    "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
    "hidden": false,
    "name": "Ubuntu",
    "source": "Windows.Terminal.Wsl",
    "fontFace": "Cascadia Code"
},
```

I install a proto-extension that updates Ubuntu's font weight and font size:

```
{
  // updates Ubuntu profile
  "updates": "{2c4de342-38b7-51cf-b940-2309a097f518}",
  "fontSize": 16,
  "fontWeight": "thin"
},
```

My settings.json is modified by the extension to look like this now:

```
{
    "backgroundImage": "C:\\Users\\cinnamon\\Pictures\\01 gettyimages-1129788053_resized.jpg",
    "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
    "hidden": false,
    "name": "Ubuntu",
    "source": "Windows.Terminal.Wsl",
    "fontFace": "Cascadia Code"
},
{
    "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
    "hidden": false,
    "name": "Ubuntu",
    "source": "demo-extension"
}
```

My font face and background image are now ignored.

image

I also can't update any setting after the fact.

proto-bug

Here's my settings.json after that settings application attempt:

```
{
    "colorScheme": "One Half Dark",
    "fontFace": "Cascadia Code"
},
{
    "backgroundImage": "C:\\Users\\cinnamon\\Pictures\\01 gettyimages-1129788053_resized.jpg"
},
{
    "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
    "hidden": false,
    "name": "Ubuntu",
    "source": "demo-extension"
}
```

My original Ubuntu profile is gone..?

# Expected behavior

The proto-extension should overlay its settings on top of my original settings, rather than ignoring all of them completely. I should also be able to customize a profile that has a proto-extension updating it.

# Actual behavior

See above.

### PR DESCRIPTION
**Pull request by PankajBhojwani**
Turns out we were adding the fragment source to profiles we update. This
PR fixes it so we keep the original source. 

## Validation Steps Performed
Existing profile settings are maintained

Closes #9290

### CODE REVIEW

File: src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp [hunk 1]
```diff
@@ -598,7 +598,6 @@ void CascadiaSettings::_ParseAndLayerFragmentFiles(const std::unordered_set<std:
                         auto childImpl{ matchingProfile->CreateChild() };
                         childImpl->LayerJson(profileStub);
                         childImpl->Origin(OriginTag::Fragment);
-                        childImpl->Source(source);
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp:601]: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Review by DHowett — APPROVED** [review]

File: src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp (hunk 1 above)
Comment (PankajBhojwani) [reply src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp:601]: same

**Review by carlos-zamora — CHANGES_REQUESTED** [review]
Wait. I'm pretty sure I introduced this for SUI Inheritance. So this'll probably break the tooltip there.

Blocking while I look into this a bit more.

**Comment by PankajBhojwani** [comment]
> Wait. I'm pretty sure I introduced this for SUI Inheritance. So this'll probably break the tooltip there.

Lol I just commented on that PR asking if we need this call

**Review by carlos-zamora — APPROVED** [review]
Tested with SUI Inheritance. Adding the source there wasn't necessary. My bet is that I was using the source to handle fragment-extensions like dynamic profiles, then I added `OriginTag::Fragment` to not have to do that (and look at the source), and just never removed that source call.

**Comment by DHowett** [comment]
@msftbot merge this in 1 minute
