### PR TITLE
Fix issues with Japanese & Vietnamese IME

### LINKED ISSUE #11479: Vietnamese IME word composition bug
### Windows Terminal version (or Windows build number)

Windows Terminal 1.10.2714.0

### Other Software

- Microsoft Windows [Version 10.0.22000.194] (though I believe this also occurs back to Windows 10 1903, which is the first version of Windows where Vietnamese Telex IME is first introduced)
- Powershell 7.1.4 (x64)

### Steps to reproduce

1. Add the Vietnamese language and 'Vietnamese Telex' keyboard layout
2. Open Windows Terminal, then switch to PowerShell
3. Switch to Vietnamese Telex keyboard layout
4. Type `'Xin chaof'` (including the apostrophe) then press Enter

### Expected Behavior

The sentence 'Xin chào' is written to the console, with normal word composition. (The screenshot is took in conhost)
conhost

(Note for non-Vietnamese: the 'f' denotes the grave on the main vowel, which, in this case, is the 'a')

### Actual Behavior

The IME composition works normally for the first syllable Xin. However, after pressing the 'c', the IME suddenly sticks the previous syllable at the beginning when composing, which breaks normal Vietnamese syllable structure. Therefore, when pressing the letter 'f', the IME then decides to append an 'f' instead of putting a grave on the 'a'. All of these result in the output of `'Xin Xinchaof'`.
wt

Somehow when composing the following words, the keystroke of the previous composition is retained. After typing Xin, then pressing Space and the 'f', the grave is put on the 'i' of the previous syllable 'Xin':
wt

The problem seems to come from the IME itself, since it is a relatively new piece of software. However, it would be nice to explain why the problem does not occur on conhost.

### LINKED ISSUE #13398: Japanese IME input mode switched back to Direct Input after pressing Enter key
### Windows Terminal version

1.14.1451.0

### Windows build number

10.0.19044.1766

### Other Software

_No response_

### Steps to reproduce

- Turn on Hiragana input mode
- Type something then press Enter to convert to japanese

### Expected Behavior

The input mode should not switch back to Direct Input

### Actual Behavior

The input mode switched to Direct Input automatically after conversion

terminal

### PR DESCRIPTION
**Pull request by lhecker**
This commit builds directly on the changes made in #13677 and fixes:
* TSF resetting to AlphaNumeric ("ASCII") input mode when pressing enter
* Vietnamese IME not composing a new word after pressing whitespace, etc.

Closes #11479
Closes #13398

## Validation Steps Performed
* Japanese IME (Full-Width Katakana)
  Typing "saitama" produces "サイタマ" ✅
* Korean IME
  Typing "gksrmf" produces "한글" ✅
* Vietnamese IME
  Typing "xin chaof" produces "xin chào" ✅
* Emoji Picker (Win+.)
  ✅

### CODE REVIEW

**Comment by lhecker** [comment]
I wasn't sure whether I should integrate these changes into the changes made in #13677.

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 1]
```diff
@@ -921,6 +921,19 @@ namespace winrt::Microsoft::Terminal::Control::implementation
...
         }
 
+        // GH#11479: TSF wants to be notified of any character input via ICoreTextEditContext::NotifyTextChanged().
+        // TSF is built and tested around the idea that you inform it of any text changes that happen
+        // when it doesn't currently compose characters. For instance writing "xin chaof" with the
+        // Vietnamese IME should produce "xin chào". After writing "xin" it'll emit a composition
+        // completion event and we'll write "xin" to the shell. It now has no input focus and won't know
+        // about the whitespace. If you then write "chaof", it'll emit another composition completion
+        // event for "xinchaof" and the resulting output in the shell will finally read "xinxinchaof".
+        // A composition completion event technically doesn't mean that the completed text is now
```
Comment (kiennq) [inline src/cascadia/TerminalControl/TermControl.cpp:931]: Wow, this one is correct. IME can change the text in the edit control as it sees fit, you can think of something like autocorrection.
So with the current implementation (before this PR), IME will see a big lump of text without any word delimitation (spaces, dot, comma ...) as they're not notified back to TSF, limiting the ability to provide more advanced text edit functionality that IME can provide.

I have a question regarding the text edit field, is the current command line where the user can input text is not considered a text edit field? And only the composition is considered as a text edit field and has text editing events notified back to TSF?

**Review by zadjii-msft — APPROVED** [review]

**Comment by DHowett** [comment]
This needs a merge or rebase

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 1 above)
Comment (DHowett) [reply src/cascadia/TerminalControl/TermControl.cpp:931]: > I have a question regarding the text edit field, is the current command line where the user can input text is not considered a text edit field?

This part is complicated. Right now, we are using an "overlay" text field because we have not connected the command line buffer to the TSF. This is because of how Terminal sees the screen:

|0|1|2|3|4|5|6|
|-|-|-|-|-|-|-|
|C|:|\\ |>|H|i|.|

All of the input _and output_ goes into the same character grid. Terminal does not know that `3` is part of the prompt, and `4` is part of the user input! If we naively sent all that data to TSF, it would look like the user could edit the `C:\>` part.

**Review by DHowett — APPROVED** [review]
To some extent, I have to trust this change -- both that it works right and that it _feels_ right. Thank you @kiennq for testing it and reviewing it as well!

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 1 above)
Comment (kiennq) [reply src/cascadia/TerminalControl/TermControl.cpp:931]: > All of the input _and output_ goes into the same character grid. Terminal does not know that `3` is part of the prompt, and `4` is part of the user input! If we naively sent all that data to TSF, it would look like the user could edit the `C:\>` part.

I see, thank you.
On another hand, I think that we can probably just pass that to the TSF, since the text modification should be depended on the text cursor position as well. And even if the TSF's input processors think it can change the text, if the application doesn't change the text then the input processors should follow.
