### PR TITLE
Fix VT sequences for Ctrl+Alt+? input

### LINKED ISSUE #3079: Powershell: Ctrl-Alt-? does not work in Windows Terminal
# Environment

```none
Windows build number: 10.0.18362.388
Windows Terminal version (if applicable): 0.5.2762.0

Powershell version:
PSVersion                      5.1.18362.145                                                                           
PSEdition                      Desktop                                                                                  PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}       
BuildVersion                   10.0.18362.145                                                                       
CLRVersion                     4.0.30319.42000                                                                          
WSManStackVersion              3.0                                                                                      
PSRemotingProtocolVersion      2.3                                                                                      
SerializationVersion           1.1.0.1              
```

# Steps to reproduce

- Open Powershell tab
- Press Ctrl-Alt-? (Ctrl-Alt-Shift-/)

# Expected behavior
it should display Powershell existing key binding 
Basic editing functions
```
=======================
Enter            AcceptLine         Accept the input or move to the next line if input is missing a closing token.
Shift+Enter      AddLine            Move the cursor to the next line without attempting to execute the input
Backspace        BackwardDeleteChar Delete the character before the cursor
Ctrl+h           BackwardDeleteChar Delete the character before the cursor
Ctrl+Home        BackwardDeleteLine Delete text from the cursor to the start of the line
Ctrl+Backspace   BackwardKillWord   Move the text from the start of the current or previous word to the cursor to th...
Ctrl+C           Copy               Copy selected region to the system clipboard.  If no region is selected, copy th...
Ctrl+c           CopyOrCancelLine   Either copy selected text to the clipboard, or if no text is selected, cancel ed...
Ctrl+x           Cut                Delete selected region placing deleted text in the system clipboard
```
# Actual behavior
it displays weird characters:
`^_  `

### PR DESCRIPTION
**Pull request by zadjii-msft**
## Summary of the Pull Request

Ctrl+/ and Ctrl-? are complicated in VT input.

* C-/ is supposed to be `^_` (the C0 character US)
* C-? is supposed to be `DEL`
* C-M-/ is supposed to be `^[^_` (ESC US)
* C-M-? is supposed to be `^[^?` (ESC DEL)

The astute reader will note that these characters also share the same key on a
standard en-us keyboard layout, which makes the problem even more complicated.
This PR does a better job of handling these weird cases.

# References
* #3079 - At first, I thought this PR would close this issue, but as I've learned below, this won't solve that one. This bug was merely found during that investigation.

## PR Checklist
* [x] Related to #3079
* [x] I work here
* [x] Tests added/passed
* [n/a] Requires documentation to be updated

## Validation Steps Performed

* ran tests
* checked `showkey -a` in gnome-terminal, which gives you the wrong results for C-M-/, C-M-?
* checked `showkey -a` in xterm, which gives you the _right_ results for C-M-/, C-M-?
* checked `showkey -a` in conhost
* checked `showkey -a` in Windows Terminal

### CODE REVIEW

File: src/terminal/input/terminalInput.cpp [hunk 1]
```diff
@@ -323,13 +326,61 @@ static bool _searchWithModifier(const KeyEvent& keyEvent, InputSender sender)
         }
         else
         {
-            // One last check: C-/ is supposed to be C-_
-            // But '/' is not the same VKEY on all keyboards. So we have to
-            //      figure out the vkey at runtime.
-            const BYTE slashVkey = LOBYTE(VkKeyScan(L'/'));
-            if (keyEvent.GetVirtualKeyCode() == slashVkey && keyEvent.IsCtrlPressed())
+            // One last check:
+            // * C-/ is supposed to be ^_ (the C0 charater US)
```
Comment (carlos-zamora) [inline src/terminal/input/terminalInput.cpp]:
```suggestion
            // * C-/ is supposed to be ^_ (the C0 character US)
```

File: src/terminal/input/terminalInput.cpp [hunk 2]
```diff
@@ -323,13 +326,61 @@ static bool _searchWithModifier(const KeyEvent& keyEvent, InputSender sender)
...
+            // this character.
+            const auto slashKeyScan = VkKeyScan(L'/'); // On USASCII: 0x00bf
+            const auto questionMarkKeyScan = VkKeyScan(L'?'); //On USASCII: 0x01bf
+
+            const auto ctrl = keyEvent.IsCtrlPressed();
+            const auto alt = keyEvent.IsAltPressed();
+            const bool shift = keyEvent.IsShiftPressed();
+
+            // From the KeyEvent we're translating, synthesize the equivalent VkKeyScan result
+            const short keyScanFromEvent = keyEvent.GetVirtualKeyCode() |
```
[the remark this answers is not in the document]
Comment (DHowett-MSFT) [reply src/terminal/input/terminalInput.cpp]: (i don't think it should be a member on keyevent because that's too win32-specific)

File: src/terminal/input/terminalInput.cpp [hunk 3]
```diff
@@ -323,13 +326,61 @@ static bool _searchWithModifier(const KeyEvent& keyEvent, InputSender sender)
...
+                                           (shift ? 0x100 : 0) |
+                                           (ctrl ? 0x200 : 0) |
+                                           (alt ? 0x400 : 0);
+
+            // If the key pressed was exactly the ? key, then try to send the
+            // appropriate sequence for a modified '?'. Otherwise, check if this
+            // was a modified '/' keypress. These mappings don't need to be
+            // changed at all.
+            if ((ctrl && alt) && WI_AreAllFlagsSet(keyScanFromEvent, questionMarkKeyScan))
```
Comment (DHowett-MSFT) [inline src/terminal/input/terminalInput.cpp]: I'm a little worried about this actually.

What if hypothetically we get a keyscan back that's like... ctrl+alt+some_random_VK. except, that VK has bits that are a superset of the bits set for question mark.

We might need to split and check the modifiers and the vk separately?

Comment (DHowett-MSFT) [reply src/terminal/input/terminalInput.cpp]: like i get we're using AreAllFlags for the _modifiers_ but for the VK part it may be incorrect

Comment (DHowett-MSFT) [reply src/terminal/input/terminalInput.cpp]: you will luck out here on US keyboards because /? is VK_OEM_2, 0xBF, `0b10111111`. The only other vk that could superset those bits would be 0xff, which is invalid.

We may not be so lucky for non-USASCII keyboards :)

**Comment by j4james** [comment]
> C-/ is supposed to be ^_ (the C0 charater US)
    C-? is supposed to be DEL
    C-M-/ is supposed to be ^[^/
    C-M-? is supposed to be ^[?

For the record, I think this is wrong. If you look at Mintty, or Xterm (with the _meta sends escape_ mode set), you'll get different results:

Ctl+/ is `^_` (US)
Ctl+? is `^?` (DEL)
Ctl+Atl+/ is `^[^_` (ESC US)
Ctl+Atl+? is `^[^?` (ESC DEL)
Alt+/ is `^[/` (ESC /)
Alt+? is `^[?` (ESC ?)

Notice how it all fits a pattern. Gnome-terminal doesn't distinguish between Ctl+Alt and Alt, which definitely seems like a bug to me.

**Comment by zadjii-msft** [comment]
@j4james great catch! I was using gnome-terminal to test, not xterm. That certainly does make more sense. I'll make sure that roundtrips as nicely through conpty as the other ones did

**Comment by zadjii-msft** [comment]
Gah okay. I concur that the fixed behavior is _more correct_, but now <kbd>ctrl+alt+?</kbd> falls into the #879 category of keys. We can't differentiate between that and <kbd>Alt+Bksp</kbd>, but that's probably okay.

**Comment by DHowett-MSFT** [comment]
In the future, I'd like to see if we can't just not special-case these keys.

File: src/terminal/adapter/ut_adapter/inputTest.cpp [hunk 4]
```diff
@@ -684,4 +684,33 @@ void InputTest::DifferentModifiersTest()
...
+    s_pwszInputExpected = L"\x7f";
+    TestKey(pInput, SHIFT_PRESSED | LEFT_CTRL_PRESSED, vkey, L'?');
+    TestKey(pInput, SHIFT_PRESSED | RIGHT_CTRL_PRESSED, vkey, L'?');
+
+    // C-M-/ -> 0x1b0x1f
+    Log::Comment(NoThrowString().Format(L"Checking C-M-/"));
+    uiKeystate = LEFT_CTRL_PRESSED | LEFT_ALT_PRESSED;
+    vkey = LOBYTE(VkKeyScan(L'/'));
+    s_pwszInputExpected = L"\x1b\x1f";
+    TestKey(pInput, LEFT_CTRL_PRESSED | LEFT_ALT_PRESSED, vkey, L'/');
```
Comment (lhecker) [inline src/terminal/adapter/ut_adapter/inputTest.cpp]: BTW This particular call fails if you've got a non-US keyboard attached. 🤔

Comment (DHowett-MSFT) [reply src/terminal/adapter/ut_adapter/inputTest.cpp]: Yeah, that bit is unfortunate. We've got a couple other tests that make assumptions about the environment they're running in (mostly around language and system codepage) ☹️
