### PR TITLE
Fix showing a dialog multiple times

### LINKED ISSUE #12622: Pasting multiple lines, multiple times is broken in main
After #12517 likely

copy a bunch of lines, like 

```
git cherry-pick 02135ed
git cherry-pick 27a1b9d
git cherry-pick f5f0712
git cherry-pick c0083ef
git cherry-pick 09e9915
git cherry-pick 0a15643
```

and paste em. You'll get the warning, fine. Allow the paste. Now copy some more lines like

```
git cherry-pick 5ba0d61
git cherry-pick c62705e
git cherry-pick 788d33c
```

and paste em. No warning, no paste. One at a time works fine. I'm betting the page is stuck thinking the dialog is open (it's not).

(I bet there are other ways of reproducing this too)

### PR DESCRIPTION
**Pull request by zadjii-msft**
After the dialog is displayed, always clear it out. If we don't, we won't be able to display another!

* regressed in #12517.
* [x] Fixes #12622.

### CODE REVIEW

File: src/cascadia/TerminalApp/AppLogic.cpp [hunk 1]
```diff
@@ -380,7 +380,11 @@ namespace winrt::TerminalApp::implementation
         auto loadedRevoker{ dialog.Loaded(winrt::auto_revoke, themingLambda) }; // if it's not yet in the tree
 
         // Display the dialog.
-        co_return co_await dialog.ShowAsync(Controls::ContentDialogPlacement::Popup);
+        const auto result = co_await dialog.ShowAsync(Controls::ContentDialogPlacement::Popup);
+        // GH#12622: After the dialog is displayed, always clear it out. If we
+        // don't, we won't be able to display another!
+        _dialog = nullptr;
```
Comment (lhecker) [inline src/cascadia/TerminalApp/AppLogic.cpp:386]: Above it says
```cpp
_dialog = dialog;
```

To make this code robust against exceptions and future early returns I'd suggest changing it to:
```cpp
_dialog = dialog;
const auto cleanup = wil::scope_exit([this]() {
    _dialog = nullptr;
});
```

**Review by DHowett — APPROVED** [review]

**Review by lhecker — APPROVED** [review]
