### PR TITLE
Hardcode the language list for the package manifest and settings dropdown

### LINKED ISSUE #12351: Localization gone since 1.13.10336.0
### Windows Terminal version

1.13.10336.0

### Windows build number

22000.469

### Other Software

_No response_

### Steps to reproduce

Install Windows Terminal Preview 1.13.10336.0.

### Expected Behavior

Previously available localizations remain.

### Actual Behavior

The entire UI has lost its localization and switched to English. I can also see under Settings -> Appearance -> Language that English is the only option available apart from the "system default" option. My system locale is de-DE.

### PR DESCRIPTION
**Pull request by miniksa**
The `x-generate` statement seems to have fallen apart somewhere and is no longer generating the valid list of languages for display. This hardcodes the list into the manifest to restore it, which is a valid option per the documentation.

We also hardcode the limited subset of languages into the Settings application because the main application supports fewer languages than we have been translated into for the shell extensions for Windows Explorer and Start Menu integration.

## PR Checklist
* [x] Closes #12351
* [x] I work here.
* [x] Manual tests below

## Validation Steps Performed
- [x] Clean built locally with `msbuild.exe openconsole.sln /p:Configuration=Release /p:Platform=x64 /p:WindowsTerminalBranding=Release /t:Terminal\CascadiaPackage /m /bl:log4.binlog` and checked that the `appxmanifest.xml` that popped out the other side contained the same languages that it used to contain.
- [x] Built in the release pipeline
- [x] Installed release and preview branded packages. Changed my machine language to Polish (pl-PL) which is not one of the fully localized languages, but is one of the limited ones. Checked the start menu and right-click menus and saw Polish text for Terminal and Terminal Preview. Checked the Settings page in our app and saw only the limited 14 language list for the application itself.

### CODE REVIEW

**Comment by miniksa** [comment]
https://dev.azure.com/microsoft/Dart/_build/results?buildId=44709402&view=results is the release build test.

**Review by lhecker — APPROVED** [review]
I'm sad that I tried this but did it incorrectly and wasted a bunch of time. :(
But I'm happy you did it correctly and saved us all a bunch more time. :)

the new king

**Comment by DHowett** [comment]
> We still need to figure out if the 80+ new languages for the OS integration menus will show up with this or if they won't (and if we need to hardcode all of those too

this is the part that worries me. 1.12 needs to be the version that fixes the context menu and start menu in all those languages :/

File: src/cascadia/CascadiaPackage/Package-Dev.appxmanifest [hunk 1]
```diff
@@ -30,7 +30,20 @@
   </Dependencies>
 
   <Resources>
-    <Resource Language="x-generate"/>
+    <Resource Language="EN-US" />
```
Comment (DHowett) [inline src/cascadia/CascadiaPackage/Package-Dev.appxmanifest:33]: does dev still work even if we don't have resources for these languages?

Comment (miniksa) [reply src/cascadia/CascadiaPackage/Package-Dev.appxmanifest:33]: woof, didn't test that. I will test the scenarios after lunch.

**Comment by miniksa** [comment]
We must declare all the languages for it to show in the Start Menu and the Context menu appropriately.

Unfortunately we don't have ALL the resources in those languages, so this now is going to force is to change the way the dropdown settings selector works probably to only show the limited list for which we have full translations.

We also won't have any control over what the store says we have in terms of language availability.

File: src/cascadia/TerminalSettingsEditor/GlobalAppearance.cpp [hunk 2]
```diff
@@ -88,43 +105,22 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
...
+            // dropdown to steer users towards the ones that we can display in the app.
 
             // As per the function definition, the first item
             // is always "Use system language" ("und").
-            auto data = tags.data();
-            *data++ = systemLanguageTag;
-
-            // Finally GetMany() all the tags from tagSources.
-            for (const auto& v : tagSources)
+            tags.push_back(systemLanguageTag.data());
```
Comment (lhecker) [inline src/cascadia/TerminalSettingsEditor/GlobalAppearance.cpp:118]: Should probably work with
```cpp
tags.emplace_back(systemLanguageTag);
```

File: src/cascadia/TerminalSettingsEditor/GlobalAppearance.cpp [hunk 3]
```diff
@@ -24,6 +24,23 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
...
+        L"fr-FR",
+        L"it-IT",
+        L"ja",
+        L"ko",
+        L"pt-BR",
+        L"qps-PLOC",
+        L"qps-PLOCA",
+        L"qps-PLOCM",
+        L"ru",
+        L"zh-Hans-CN",
```
Comment (lhecker) [inline src/cascadia/TerminalSettingsEditor/GlobalAppearance.cpp:40]: HANS GET ZE BUG FIX.

**Review by lhecker — APPROVED** [review]

**Comment by miniksa** [comment]
> We must declare all the languages for it to show in the Start Menu and the Context menu appropriately.
> 
> Unfortunately we don't have ALL the resources in those languages, so this now is going to force is to change the way the dropdown settings selector works probably to only show the limited list for which we have full translations.
> 
> We also won't have any control over what the store says we have in terms of language availability.

taken care of.

**Comment by miniksa** [comment]
Release branding: https://dev.azure.com/microsoft/Dart/_build/results?buildId=44725957&view=results
Preview branding: https://dev.azure.com/microsoft/Dart/_build/results?buildId=44725973&view=results

File: src/cascadia/TerminalSettingsEditor/GlobalAppearance.cpp [hunk 4]
```diff
@@ -88,43 +105,22 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
...
-            // Languages is a computed list that merges the ManifestLanguages with the
-            // user's ranked list of preferred languages taken from the system settings.
-            // As is tradition the API documentation is incomplete though, as it can also
-            // contain regional language variants. If our app supports en-US, but the user
-            // has en-GB or en-DE in their system's preferred language list, Languages will
-            // contain those as well, as they're variants from a supported language. We should
-            // allow a user to select those, as regional formattings can vary significantly.
-            const std::array tagSources{
-                winrt::Windows::Globalization::ApplicationLanguages::ManifestLanguages(),
-                winrt::Windows::Globalization::ApplicationLanguages::Languages()
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/GlobalAppearance.cpp:101]: So wait, the concern about regional variants either doesn't apply or doesn't matter how that we have to hardcode? Or, it would accidentally report too many language?

Comment (miniksa) [reply src/cascadia/TerminalSettingsEditor/GlobalAppearance.cpp:101]: @lhecker, you're the one who told me to take it out. Explain to Dustin?

Comment (lhecker) [reply src/cascadia/TerminalSettingsEditor/GlobalAppearance.cpp:101]: The latter. I was discussing this with @miniksa: `Languages()` returns regional variants - like `de-AT` - which can be important for number formatting and such. As such there's only two options here:
* filter the language list by reimplementing WinUI's language matcher (the one that says that `de-AT` and `de-DE` are compatible)
* hardcode the language list, ensuring only our languages are in there

The latter option seemed far more attractive since it's far simpler to implement. Additionally regional variants don't affect translated strings, but only generated strings. This means it's effect is limited to for instance the way we format numbers for the command palette. (Do we format numbers properly in a regional style anyways btw, or do we just use arabic numerals all the way?)

**Comment by lhecker** [comment]
Ah before I forget... Here's the Visual Studio feedback that brought the decisive cue:
https://developercommunity.visualstudio.com/t/the-new-version-probably-vs-makes-the-language-lis/1041637

> I now find that this problem should be caused by an optimization of VS. UWP will not bring all resource files by default, so the content I submitted above is not a bug but a feature. Please help me close this problem. Thank you

**Comment by miniksa** [comment]
> Release branding: [dev.azure.com/microsoft/Dart/_build/results?buildId=44725957&view=results](https://dev.azure.com/microsoft/Dart/_build/results?buildId=44725957&view=results) Preview branding: [dev.azure.com/microsoft/Dart/_build/results?buildId=44725973&view=results](https://dev.azure.com/microsoft/Dart/_build/results?buildId=44725973&view=results)

Both of these worked.

**Review by zadjii-msft — APPROVED** [review]

**Review by DHowett — APPROVED** [review]
