### PR TITLE
Shim the Azure connection through a conhost to stop VT bleeding

### LINKED ISSUE #2267: Bug Report: PowerShell Core launched by Azure Cloud Shell bash has positioning issues
# Environment

```none
Windows build number: 1903 OS build 18362.239
Windows Terminal version (if applicable): 0.3.2142.0

Any other software? N/A
```

# Steps to reproduce

1. Launch Azure Cloud Shell profile tab and connect/login to Azure
1. Launch PowerShell Core with command: `pwsh`
1. Execute any PowerShell Core commands

# Expected behavior

Cursor position should continue to advance down the console as commands are entered and output is produced by cmdlets.

# Actual behavior

Keyboard-entered input (cursor) is initially repositioned at row 0, column 0 regardless of where the prompt positions the cursor.

image

### LINKED ISSUE #4589: Arrow keys don't work in Vim in Azure Cloud Shell
# Environment

```none
Windows build number: 10.0.19041.0
Windows Terminal version (if applicable): 0.9.433.0
```

# Steps to reproduce

1. Open Azure Cloud Shell. 
2. Open Vim, such as `vim ./.bashrc`. 
3. Try to move the cursor with the arrow keys. It doesn't work and an error shows up with the left arrow key: `E388: Couldn't find definition`.

# Expected behavior

Should be able to move the cursor with the arrow keys. 

# Actual behavior

Cannot move the cursor with the arrow keys and an error shows up with the left arrow key: `E388: Couldn't find definition`.
`echo $TERM` shows xterm-256color

# Workaround 

In `~/.vimrc`, add `:set term=builtin_ansi` and then the arrow keys start working in Vim. 
This issue seems only happen with Azure Cloud Shell. It doesn't happen with wsl.

### PR DESCRIPTION
**Pull request by DHowett-MSFT**
This commit introduces a small console-subsystem application whose sole
job is to consume TerminalConnection.dll and hook it up to something
other than Terminal. It is 99% of the way to a generic solution.

I've introduced a stopgap in TerminalPage that makes sure we launch
TerminalAzBridge using ConptyConnection instead of AzureConnection.

As a bonus, this commit includes a class whose sole job it is to make
reading VT input off a console handle not terrible. It returns you a
string and dispatches window size change callbacks.

Fixes #2267.
Fixes #4589.
Related to #2266 (since pwsh needs better VT).

_NOTE: this application will only work if you put TerminalConnection.dll and resources.pri next to it. It is not yet intended for out-of-terminal-package use._

## Validation Steps Performed

image

### CODE REVIEW

File: src/cascadia/TerminalApp/TerminalPage.cpp [hunk 1]
```diff
@@ -602,8 +602,10 @@ namespace winrt::TerminalApp::implementation
             profile->GetConnectionType() == AzureConnectionType &&
             TerminalConnection::AzureConnection::IsAzureConnectionAvailable())
         {
-            connection = TerminalConnection::AzureConnection(settings.InitialRows(),
-                                                             settings.InitialCols());
+            // TODO GH#XXXX: Replace this with directly using the AzCon when our VT is better
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalApp/TerminalPage.cpp]: unguarded todo, i'll get to filing it tomorrow.

File: src/cascadia/TerminalAzBridge/main.cpp [hunk 2]
```diff
@@ -0,0 +1,101 @@
...
+
+    DWORD inputMode{}, outputMode{};
+    HANDLE conIn{ GetStdHandle(STD_INPUT_HANDLE) }, conOut{ GetStdHandle(STD_OUTPUT_HANDLE) };
+    UINT codepage{ GetConsoleCP() }, outputCodepage{ GetConsoleOutputCP() };
+
+    RETURN_IF_WIN32_BOOL_FALSE(GetConsoleMode(conIn, &inputMode));
+    RETURN_IF_WIN32_BOOL_FALSE(GetConsoleMode(conOut, &outputMode));
+
+    RETURN_IF_WIN32_BOOL_FALSE(SetConsoleMode(conIn, ENABLE_WINDOW_INPUT | ENABLE_VIRTUAL_TERMINAL_INPUT));
+    RETURN_IF_WIN32_BOOL_FALSE(SetConsoleMode(conOut, ENABLE_PROCESSED_OUTPUT | ENABLE_VIRTUAL_TERMINAL_PROCESSING | DISABLE_NEWLINE_AUTO_RETURN));
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalAzBridge/main.cpp]: I did not set ` ENABLE_WRAP_AT_EOL_OUTPUT `. This is incorrect.

Comment (DHowett-MSFT) [reply src/cascadia/TerminalAzBridge/main.cpp]:
```suggestion
    RETURN_IF_WIN32_BOOL_FALSE(SetConsoleMode(conOut, ENABLE_PROCESSED_OUTPUT | ENABLE_VIRTUAL_TERMINAL_PROCESSING | ENABLE_WRAP_AT_EOL_OUTPUT | DISABLE_NEWLINE_AUTO_RETURN));
```

File: src/cascadia/TerminalApp/TerminalPage.cpp (hunk 1 above)
Comment (DHowett-MSFT) [reply src/cascadia/TerminalApp/TerminalPage.cpp]:
```suggestion
            // TODO GH#4661: Replace this with directly using the AzCon when our VT is better
```

**Comment by carlos-zamora** [comment]
> _NOTE: this application will only work if you put TerminalConnection.dll and resources.pri next to it. It is not yet intended for out-of-terminal-package use._

Can we make it out-of-terminal-package useful? Is that a follow-up PR to this?

**Comment by DHowett-MSFT** [comment]
> can we

If a reason to do so arises, we can file it and track it.

File: src/cascadia/TerminalAzBridge/main.cpp [hunk 3]
```diff
@@ -0,0 +1,101 @@
...
+    RETURN_IF_WIN32_BOOL_FALSE(SetConsoleOutputCP(CP_UTF8));
+
+    auto restoreConsoleModes = wil::scope_exit([&]() {
+        SetConsoleMode(conIn, inputMode);
+        SetConsoleMode(conOut, outputMode);
+        SetConsoleCP(codepage);
+        SetConsoleOutputCP(outputCodepage);
+    });
+
+    auto size = GetConsoleScreenSize(conOut);
```
Comment (miniksa) [inline src/cascadia/TerminalAzBridge/main.cpp]:
```suggestion
    const auto size = GetConsoleScreenSize(conOut);

```

File: src/cascadia/TerminalAzBridge/main.cpp [hunk 4]
```diff
@@ -0,0 +1,101 @@
...
+    AzureConnection azureConn{ gsl::narrow_cast<uint32_t>(size.Y), gsl::narrow_cast<uint32_t>(size.X) };
+
+    auto state = RunConnectionToCompletion(azureConn, conOut, conIn);
```
Comment (miniksa) [inline src/cascadia/TerminalAzBridge/main.cpp]:
```suggestion
    const auto state = RunConnectionToCompletion(azureConn, conOut, conIn);

```

File: src/cascadia/TerminalAzBridge/main.cpp [hunk 5]
```diff
@@ -0,0 +1,101 @@
...
+        WriteConsoleW(outputHandle, output.data(), output.size(), nullptr, nullptr);
+    });
+
+    // Detach a thread to spin the console read indefinitely.
+    // This application exits when the connection is closed, so
+    // the connection's lifetime will outlast this thread.
+    std::thread([connection, outputHandle, inputHandle] {
+        ConsoleInputReader reader{ inputHandle };
+        reader.SetWindowSizeChangedCallback([&]() {
+            auto size = GetConsoleScreenSize(outputHandle);
```
Comment (miniksa) [inline src/cascadia/TerminalAzBridge/main.cpp]:
```suggestion
            const auto size = GetConsoleScreenSize(outputHandle);

```

File: src/cascadia/TerminalAzBridge/ConsoleInputReader.cpp [hunk 6]
```diff
@@ -0,0 +1,69 @@
...
+                    {
+                        _highSurrogate.emplace(keyEvent.uChar.UnicodeChar);
+                        continue; // we've consumed it -- only dispatch it if we get a low
+                    }
+
+                    if (IS_LOW_SURROGATE(keyEvent.uChar.UnicodeChar) && _highSurrogate)
+                    {
+                        _convertedString.push_back(*_highSurrogate);
+                        _highSurrogate.reset();
+                    }
```
Comment (miniksa) [inline src/cascadia/TerminalAzBridge/ConsoleInputReader.cpp]: if it is low and you don't have a `_highSurrogate`, won't you accidentally send it along?

File: src/cascadia/TerminalAzBridge/ConsoleInputReader.cpp [hunk 7]
```diff
@@ -0,0 +1,69 @@
...
+        _buffer.resize(BufferSize);
+        BOOL succeeded =
+            ReadConsoleInputW(_handle, _buffer.data(), gsl::narrow_cast<DWORD>(_buffer.size()), &readCount);
+        if (!succeeded)
+        {
+            return std::nullopt;
+        }
+
+        _buffer.resize(readCount);
+        for (auto it = _buffer.begin(); it != _buffer.end(); it++)
```
Comment (miniksa) [inline src/cascadia/TerminalAzBridge/ConsoleInputReader.cpp]:
```suggestion
        for (auto it = _buffer.begin(); it != _buffer.end(); ++it)
```

To avoid the copy.

Comment (DHowett-MSFT) [reply src/cascadia/TerminalAzBridge/ConsoleInputReader.cpp]: Right, thanks. I was troubleshooting a "lol it doesn't do `operator++`" that turned out to be because i had it  `const`

File: src/cascadia/TerminalAzBridge/ConsoleInputReader.cpp (hunk 6 above)
Comment (DHowett-MSFT) [reply src/cascadia/TerminalAzBridge/ConsoleInputReader.cpp]: Yep! I can instead send UNICODE_REPLACEMENT_CHAR?

File: src/cascadia/TerminalAzBridge/ConsoleInputReader.cpp [hunk 8]
```diff
@@ -50,15 +51,32 @@ std::optional<std::wstring_view> ConsoleInputReader::Read()
...
+                        // No matter what we do, we want to destructively consume the high surrogate
+                        if (const auto oldHighSurrogate{ std::exchange(_highSurrogate, std::nullopt) })
+                        {
+                            _convertedString.push_back(*_highSurrogate);
+                        }
+                        else
+                        {
+                            // If we get a low without a high surrogate, we've done everything we can.
+                            // This is an illegal state.
+                            _convertedString.push_back(UNICODE_REPLACEMENT);
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalAzBridge/ConsoleInputReader.cpp]: what i have written is the same as `optional.value_or(REPLACEMENT)`, but with the added `continue`.

I figured it was more clear this way, and we get the added benefit of exchanging the optional with nullopt

File: src/cascadia/TerminalAzBridge/ConsoleInputReader.cpp (hunk 6 above)
Comment (miniksa) [reply src/cascadia/TerminalAzBridge/ConsoleInputReader.cpp]: please.

File: src/cascadia/TerminalAzBridge/ConsoleInputReader.cpp (hunk 8 above)
Comment (miniksa) [reply src/cascadia/TerminalAzBridge/ConsoleInputReader.cpp]: works for me.

**Comment by DHowett-MSFT** [comment]
ty ty
