### PR TITLE
Make ActionMap compatible with ScanCode-only KeyChords

### LINKED ISSUE #10933: VKey assertion failure
### Windows Terminal version (or Windows build number)

dev origin/main

### Other Software

I use the colemak keyboard layout primarily, but it also seems to happen with regular qwerty too.

### Steps to reproduce

Launch the application, assert at line https://github.com/microsoft/terminal/pull/10917/files#diff-ac308dd6d23797c02f8be4591060500c2474856a7c3f483ac5cff219b3fc16a2R720 fails

### Expected Behavior

terminal actually loads

### Actual Behavior

exception thrown.

### PR DESCRIPTION
**Pull request by lhecker**
This commit partially reverts d465a47 and introduces an alternative approach by adding Hash and Equals methods to the KeyChords class. Those methods will now favor any existing Vkeys over ScanCodes.

## PR Checklist
* [x] Closes #10933
* [x] I work here
* [x] Tests added/passed

## Validation Steps Performed

* Added a new test, which is ✔️
* Various standard commands still work ✔️
* Hash() returns the same value for all KeyChords that are Equals() ✔️

### CODE REVIEW

File: src/cascadia/TerminalControl/KeyChord.cpp [hunk 1]
```diff
@@ -38,19 +38,68 @@ namespace winrt::Microsoft::Terminal::Control::implementation
...
+    uint64_t KeyChord::Hash() const noexcept
+    {
+        // Two KeyChords are equal if they have the same modifiers and either identical
+        // Vkey or ScanCode, with Vkey being preferred. See KeyChord::Equals().
+        // This forces us to _either_ hash _vkey or _scanCode.
+        //
+        // Additionally the hash value with _vkey==123 and _scanCode==123 must be different.
+        // --> Mark the hash of a KeyChord without _vkey with the highest bit set,
+        //     thus generating a different Hash() even if the Vkey/ScanCode are identical.
+        auto h = static_cast<uint64_t>(_modifiers) << 32;
```
Comment (DHowett) [inline src/cascadia/TerminalControl/KeyChord.cpp:54]: qq: since x86 has `4==sizeof(size_t)`, will this cause us to ignore modifiers when we cast off the top 32 bits and stuff these in the map? Do we need to collapse this down to 32 bits total?

File: src/cascadia/TerminalControl/KeyChord.cpp [hunk 2]
```diff
@@ -38,19 +38,68 @@ namespace winrt::Microsoft::Terminal::Control::implementation
...
+    }
+
+    uint64_t KeyChord::Hash() const noexcept
+    {
+        // Two KeyChords are equal if they have the same modifiers and either identical
+        // Vkey or ScanCode, with Vkey being preferred. See KeyChord::Equals().
+        // This forces us to _either_ hash _vkey or _scanCode.
+        //
+        // Additionally the hash value with _vkey==123 and _scanCode==123 must be different.
+        // --> Mark the hash of a KeyChord without _vkey with the highest bit set,
```
Comment (DHowett) [inline src/cascadia/TerminalControl/KeyChord.cpp:52]: technically not the highest bit, right? it's just one of the bits in the middle-ish

File: src/cascadia/TerminalSettingsModel/ActionMap.cpp [hunk 3]
```diff
@@ -300,24 +290,41 @@ namespace winrt::Microsoft::Terminal::Settings::Model::implementation
...
+            // ShortcutAction is GlobalSummon or QuakeMode
+            if (cmd.ActionAndArgs().Action() == ShortcutAction::GlobalSummon || cmd.ActionAndArgs().Action() == ShortcutAction::QuakeMode)
+            {
+                globalHotkeys.emplace(keys, cmd);
+            }
+        }
+
+        _KeyBindingMapCache = single_threaded_map<KeyChord, Model::Command>(std::move(keyBindingsMap));
+        _GlobalHotkeysCache = single_threaded_map<KeyChord, Model::Command>(std::move(globalHotkeys));
+    }
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsModel/ActionMap.cpp:318]: I'm actually shocked that this works -- does it just infer the template args for Hash and Equality? Whoa.

File: src/cascadia/ut_app/JsonTests.cpp [hunk 4]
```diff
@@ -36,26 +36,27 @@ namespace TerminalAppUnitTests
             return true;
         }
 
-        Json::Value VerifyParseSucceeded(std::string content);
```
Comment (DHowett) [inline src/cascadia/ut_app/JsonTests.cpp:39]: these changes seem unrelated

**Review by DHowett — CHANGES_REQUESTED** [review]
BigQ about hash

File: src/cascadia/TerminalControl/KeyChord.cpp (hunk 1 above)
Comment (lhecker) [reply src/cascadia/TerminalControl/KeyChord.cpp:54]: A hashmap would even work if the hash function returns the same value for all keys.
While this hash function is very primitive, it's still good enough that cutting off the top 32 bits will not loose too much meaningful information. The modifiers in particular won't be cut off since those are already mixed in and distributed using our hash function.

File: src/cascadia/TerminalControl/KeyChord.cpp (hunk 2 above)
Comment (lhecker) [reply src/cascadia/TerminalControl/KeyChord.cpp:52]: I've changed the mixin to `0xBABE0000` and changed the description.

File: src/cascadia/TerminalSettingsModel/ActionMap.cpp (hunk 3 above)
Comment (lhecker) [reply src/cascadia/TerminalSettingsModel/ActionMap.cpp:318]: Actually they're all inferred from the argument. I've removed the template arguments.

File: src/cascadia/ut_app/JsonTests.cpp (hunk 4 above)
Comment (lhecker) [reply src/cascadia/ut_app/JsonTests.cpp:39]: When I wrote the `KeyBindingsTests::KeybindingsWithoutVkey` and ran it in a debugger I noticed that it created temporary strings, so I improved this code. Would you like me to file this in a separate PR?

Comment (DHowett) [reply src/cascadia/ut_app/JsonTests.cpp:39]: Meh, no need. Tis is fine

**Review by DHowett — APPROVED** [review]

File: src/cascadia/TerminalControl/KeyChord.cpp (hunk 1 above)
Comment (DHowett) [reply src/cascadia/TerminalControl/KeyChord.cpp:53]: oh right. thanks!

**Review by carlos-zamora — APPROVED** [review]
