### PR TITLE
Fix acrylic brush flash/fade on new tab creation.

### LINKED ISSUE #1082: Bug Report - Terminal flashes significantly on New Tab and may trigger visual impairments
# Environment

```none
Windows build number: 18908.1000
Windows Terminal version (if applicable): 0.1.1502.0
```

# Steps to reproduce

Open a new tab, it flashes and fades

# Expected behavior

Fade is nice ,but a less aggressive flash.

# Actual behavior

See attached zip with VIDEO
[20190531_170117000_iOS.zip](https://github.com/microsoft/terminal/files/3242224/20190531_170117000_iOS.zip)

### PR DESCRIPTION
**Pull request by d-bingham**
## Summary of the Pull Request

Fixes #1082 -- #853's fix of the acrylic background's flash/fade on _any_ settings change managed to cause a flash/fade on new tab creation.  This change removed both flash/fades.

 
## PR Checklist
* [x] Closes #1082
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Requires documentation to be updated
* [x] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #1082

## Detailed Description of the Pull Request / Additional comments

#853 split background brush initialization from background color changes; due to the brush being constructed with a default color and then the color being initialized later, new tabs were getting the flash/fade that accompanies a re-focused fluent-style acrylic background.  This PR initializes the acrylic color at brush initialization to avoid the problem.

### CODE REVIEW

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 1]
```diff
@@ -223,6 +223,18 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
                 acrylic.BackgroundSource(Media::AcrylicBackgroundSource::HostBackdrop);
             }
 
+            // Initialize background color so we don't get a
```
Comment (zadjii-msft) [inline src/cascadia/TerminalControl/TermControl.cpp]:
```suggestion
            // see GH#1082: Initialize background color so we don't get a
```
This seems like a little bit less-obvious bug fix, so referring back to the original issue might help people get some context on why it was made originally.
