### PR TITLE
Fix various issues with useBackgroundImageForWindow

### LINKED ISSUE #13002: Issues with experimental.useBackgroundImageForWindow
* [x] When the background is set on `profiles.defaults`, it does not apply (the entire window is transparent and all backgrounds are dropped)
* [x] Closing/opening panes of the same type causes the background image to flicker
* [x] The settings preview control no longer displays a background; we might want to ensure that it _overrides_ the setting that drops out the background
* [x] `desktopWallpaper` doesn't work at all 
* [x] Switching between two profiles with the same bg image flashes at you

### PR DESCRIPTION
**Pull request by lhecker**
Fixes the following issues:
* `desktopWallpaper` not working
* switching tabs/panes causes the background to flicker
* settings preview having a transparent background

## PR Checklist
* [x] Closes #13002
* [x] I work here
* [x] Tests added/passed

## Validation Steps Performed
Tested the 3 cases above. ✅

### CODE REVIEW

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 1]
```diff
@@ -426,7 +426,7 @@ namespace winrt::Microsoft::Terminal::Control::implementation
 
         if (imageSource == nullptr ||
             imageSource.UriSource() == nullptr ||
-            imageSource.UriSource().RawUri() != imageUri.RawUri())
+            !imageSource.UriSource().Equals(imageUri))
```
Comment (lhecker) [inline src/cascadia/TerminalControl/TermControl.cpp:429]: `RawUri()` returns the string the URI was constructed with, not the normalized variant.
This can result in `imageSource.UriSource().RawUri()` being `file:///C:/...`, while `imageUri.RawUri()` is `C:\\...`.

File: src/cascadia/TerminalApp/TerminalPage.cpp [hunk 2]
```diff
@@ -2596,7 +2596,8 @@ namespace winrt::TerminalApp::implementation
     // - <none>
     void TerminalPage::_SetBackgroundImage(const winrt::Microsoft::Terminal::Settings::Model::IAppearanceConfig& newAppearance)
     {
-        if (newAppearance.BackgroundImagePath().empty())
+        const auto path = newAppearance.ExpandedBackgroundImagePath();
```
Comment (DHowett) [inline src/cascadia/TerminalApp/TerminalPage.cpp:2599]: ugh thanks

**Review by DHowett — APPROVED** [review]

**Review by carlos-zamora — APPROVED** [review]

**Comment by carlos-zamora** [comment]
@msftbot merge this in 5 minutes
