### PR TITLE
Make conhost history deduplication case-sensitive

### LINKED ISSUE #4186: Discard old duplicates needs to be case-sensitive
```none
Windows build number: [run `[Environment]::OSVersion` for powershell, or `ver` for cmd]
Windows Terminal version (if applicable):
Microsoft Windows [Version 10.0.18362.535]

Any other software? No, none required
```

# Steps to reproduce

Command Prompt Properties - check "Discard Old Duplicates" in history section
Enable the Experimental Console (UNcheck "Use Legacy Console..."

# Expected behavior

Run the two commands,
foo /v
foo /V

Then use up-arrow to view the history. You should see BOTH in the history. This is the case for the classic console.

# Actual behavior

In the experimental console, only the FIRST instance (foo /v) is preserved. That is, the new console acting case-insensitive, but 'V' and 'v' can have significance to "foo"!

### PR DESCRIPTION
**Pull request by lhecker**
The legacy console used to use case-sensitive history deduplication and
this change reverts the logic to restore ye olde history functionality.

This commit additionally changes the other remaining `std::equal` plus
`std::towlower` check into a `CompareStringOrdinal` call,
just because that's what MSDN suggests to use in such situations.

## PR Checklist
* [x] Closes #4186
* [x] I work here
* [x] Tests added/passed

## Validation Steps Performed
* Enter `test /v`
* Enter `test /V`
* Browsing through the history yields both items ✅

### CODE REVIEW

File: src/host/ut_host/CommandLineTests.cpp [hunk 1]
```diff
@@ -449,21 +449,21 @@ class CommandLineTests
 
         VERIFY_SUCCEEDED(m_pHistory->Add(L"I'm a little teapot", false));
         VERIFY_SUCCEEDED(m_pHistory->Add(L"short and stout", false));
-        VERIFY_SUCCEEDED(m_pHistory->Add(L"inflammable", false));
+        VERIFY_SUCCEEDED(m_pHistory->Add(L"Inflammable", false));
```
Comment (DHowett) [inline src/host/ut_host/CommandLineTests.cpp:452]: ideally this test would be updated to verify that it does *not* match `i` with `Inflammable`.. or something? Right?

Are users going to be surprised by this change? When did we make it case-insensitive?

**Comment by lhecker** [comment]
> In addition to what it says in the title, it changes history lookup. Conhostv1 uses case insensitive lookup on the up arrow.

Isn't that the same? From what I can tell, conhost stores commands already deduplicated in a buffer and the function I modified is used to ensure this deduplication. So basically "history deduplication" and "history lookup" should be the same I think...

Should I make it so that this change only affects "Conhostv2" / the non-legacy conhost?

**Comment by DHowett** [comment]
> Isn't that the same?

Sorry, I totally misinterpreted what history lookup was happening where. This is fine -- Conhostv1 uses case-sensitive lookup on <kbd>F8</kbd> (I thought it was <kbd>Up Arrow</kbd>), and Conhostv2 doesn't. This change makes it so that Conhostv2 **does** use case-sensitive lookup on <kbd>F8</kbd>

**Review by DHowett — APPROVED** [review]

**Review by miniksa — APPROVED** [review]
