### PR TITLE
Re-enable the setting to adjust the colors of indistinguishable text

### LINKED ISSUE #11917: SGR 1 and SGR 8 don't work when adjusting lightness of indistinguishable text
### Windows Terminal version

1.12.2931.0

### Windows build number

10.0.19041.1348

### Other Software

_No response_

### Steps to reproduce

1. In the Setting UI, go to the _Profiles Defaults_ page and select the _Appearance_ tab. 
2. Make sure the option _Automaticaly adjust lightness of indistinguishable text_ is enabled.
3. Open a bash shell.
4. Execute the following command: `printf "\e[m DEFAULT \e[1m BRIGHT \e[8m CONCEALED \e[m\n"`

### Expected Behavior

I'd expect the text with the `SGR 1` attribute to be brighter, and the text with `SGR 8` attribute to be invisible.

image

### Actual Behavior

All of the text looks exactly the same.

image

This wouldn't be that big a deal if it was an option that users specifically opted in to, but I realise now that it's actually on by default. Was that really intentional? Even ignoring these problems, I would have thought the performance overhead alone was enough of a reason to make it opt-in.

### PR DESCRIPTION
**Pull request by PankajBhojwani**
## Summary of the Pull Request
Re-enable the setting to adjust indistinguishable text, with some changes:

- We now pre-calculate the nudged values for 'default bright foreground' as well
- When a color table entry is manually set (i.e. via VT sequences) we re-calculate the nudged values

## References
#11095 #12160

## PR Checklist
* [x] Closes #11917
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Documentation updated. If checked, please file a pull request on [our docs repo](https://github.com/MicrosoftDocs/terminal) and link it here: #xxx
* [ ] Schema updated.

## Validation Steps Performed
Indistinguishable text gets adjusted again

### CODE REVIEW

**Comment by PankajBhojwani** [comment]
In a follow-up, we will change the setting from a boolean value to an enum with 3 possible values: 'Never' to never adjust the text, 'Indexed' to only adjust the text if both the foreground/background are part of the current color scheme's color table (this is today's behaviour when the setting is set to "true"), and "Always" to _always_ adjust the text if it is inditinguishable (this will be somewhat performance intensive since we will be calculating this at render time, but that is why it will be opt-in only)

**Review by lhecker — DISMISSED** [review]
I don't quite understand why we shouldn't nudge brightened colors. 🤔

**Comment by lhecker** [comment]
> this will be somewhat performance intensive since we will be calculating this at render time, but that is why it will be opt-in only

If performance turns out to be a problem we can use "redmean" still as I suggested offhand a while ago. I suspect it would work sufficiently well to determine a JND, since always nudging colors by 5 luminosity is in a way a lot less "scientific" than the DeltaE algorithm itself, defeating its purpose a bit. This is the entire algorithm btw (output range 0-765):
```cpp
double redmean(COLORREF c1, COLORREF c2) {
    int r1 = GetRValue(c1), g1 = GetGValue(c1), b1 = GetBValue(c1);
    int r2 = GetRValue(c2), g2 = GetGValue(c2), b2 = GetBValue(c2);
    int dr = r1 - r2;
    int dg = g1 - g2;
    int db = b1 - b2;
    int rmean = (r1 + r2) / 2;
    return sqrt((512 + rmean) * dr * dr / 256 + 4 * dg * dg + (767 - rmean) * db * db / 256);
}
```

**Comment by PankajBhojwani** [comment]
> I don't quite understand why we shouldn't nudge brightened colors. 🤔

The issue arises when the colors are reversed _and_ the foreground is bright - we will need to calculate what 'bright background' means but we don't have an easy way to do that

**Review by zadjii-msft — DISMISSED** [review]

File: src/renderer/base/RenderSettings.cpp [hunk 1]
```diff
@@ -192,22 +192,25 @@ std::pair<COLORREF, COLORREF> RenderSettings::GetAttributeColors(const TextAttri
     const auto swapFgAndBg = attr.IsReverseVideo() ^ GetRenderMode(Mode::ScreenReversed);
 
     // We want to nudge the foreground color to make it more perceivable only for the
-    // default color pairs within the color table
+    // default color pairs within the color table, and only if there's no additional text attributes
+
+    // The reason we don't want to nudge when there's additional attributes is because of certain
+    // interactions like "bright" + "reverse". We cannot nudge after reversing because we, as of now,
```
Comment (DHowett) [inline src/renderer/base/RenderSettings.cpp:198]: i do think we should nudge bright foregrounds that aren't the default foreground, but... that might just be me? hrm.

File: src/renderer/base/RenderSettings.cpp [hunk 2]
```diff
@@ -79,15 +80,19 @@ void RenderSettings::MakeAdjustedColorArray() noexcept
...
-    std::array<COLORREF, 18> colorTableWithDefaults;
+    std::array<COLORREF, 19> colorTableWithDefaults;
     std::copy_n(std::begin(_colorTable), 16, std::begin(colorTableWithDefaults));
     colorTableWithDefaults[AdjustedFgIndex] = GetColorAlias(ColorAlias::DefaultForeground);
     colorTableWithDefaults[AdjustedBgIndex] = GetColorAlias(ColorAlias::DefaultBackground);
 
-    for (auto fgIndex = 0; fgIndex < 18; ++fgIndex)
+    // We need to use TextColor to calculate the bright default fg
+    TextColor defaultFg;
+    colorTableWithDefaults[AdjustedBrightFgIndex] = defaultFg.GetColor(_colorTable, GetColorAliasIndex(ColorAlias::DefaultForeground), true);
```
Comment (lhecker) [inline src/renderer/base/RenderSettings.cpp:90]: So this should be a `static` function now right?

**Review by lhecker — APPROVED** [review]

File: src/renderer/base/RenderSettings.cpp (hunk 2 above)
Comment (DHowett) [reply src/renderer/base/RenderSettings.cpp:90]: realistically we should just do #11939 instead of solving `GetColor` having to recalculate the bright foreground every time.

**Comment by DHowett** [comment]
(Noting @j4james here, as he said "Finally, I think having bold in the color table is an essential prerequisite for getting the bold color to work when the option to _Automaticaly adjust lightness of indistinguishable text is enabled_ (see https://github.com/microsoft/terminal/issues/11917).". We did not end up choosing to fix 11939 beforehand, but may take the fix introduced here as a TODO on landing #11939. I would rather totally get rid of `GetColor`, given that 90% of its purpose is this weird brightness hack, which would necessitate breaking the workaround in this code. We could localize its implementation in RenderSettings.)

**Comment by j4james** [comment]
> I think having bold in the color table is an essential prerequisite for getting the bold color to work

LOL. Clearly I was wrong, since the bold seems to working fine in this PR as far as I can tell.

That said, I still think this functionality should probably not be enabled by default, because there are going to be edges cases that don't work, and that's kind of inevitable when we're deliberately choosing to alter the colors that were requested.

As one example, if you're using a "standard" color scheme, like Campbell, where the default background is identical to black, and the default foreground is identical to white, then both these sequences should be invisible, but they aren't:

    printf "\e[0;30mHIDDEN\e[m\n"
    printf "\e[0;47mHIDDEN\e[m\n"

That particular case may be fixable, but there'll always be something. Having the default behavior be technically incorrect feels like we're asking for bug reports.

File: src/terminal/adapter/adaptDispatch.cpp [hunk 3]
```diff
@@ -2221,6 +2221,11 @@ bool AdaptDispatch::SetClipboard(const std::wstring_view content)
 bool AdaptDispatch::SetColorTableEntry(const size_t tableIndex, const DWORD dwColor)
 {
     _renderSettings.SetColorTableEntry(tableIndex, dwColor);
+    if (_renderSettings.GetRenderMode(RenderSettings::Mode::DistinguishableColors))
+    {
+        // Re-calculate the adjusted colors now that one of the entries has been changed
+        _renderSettings.MakeAdjustedColorArray();
+    }
```
Comment (j4james) [inline src/terminal/adapter/adaptDispatch.cpp:2228]: I think this needs to be called in `AdaptDispatch::AssignColor` too - at least for the `NormalText` variant - otherwise that's not going to work.

**Comment by j4james** [comment]
I don't know how well this would work in practice, but one idea I had for improving the performance was to move the color remapping from the renderer to the `SetGraphicsRendition` method in `AdaptDispatch`. It wouldn't work in quite the same way, but I think it should still produce a similar effect. Not suggesting that for this PR, though - just a thought for a potential future enhancement.

**Comment by lhecker** [comment]
I've had a think about this over the weekend. 🧠🤔
Not because I want to rudely intrude on other people's work more than necessary, but rather because I personally find this topic (rendering and thus the color topic) fascinating.

If we picture RGB colors as a 3D space and simplify things a bit, then the area below the JND (just-noticeable-difference of color) forms a simple sphere around our reference color. Within this coordinate system grayscale is the unit vector `(1, 1, 1)`. Thus the question how much we need to brighten or darken the color of a point (= add or subtract such gray) so that it leaves the sphere of JND, becomes the calculation of a [line-sphere intersection](https://en.wikipedia.org/wiki/Line%E2%80%93sphere_intersection). This not just yields us immediately the 2 possible corrected colors, but also whether the line is within the sphere or not (= whether any adjustment needs to be done).

Of course the problem is that the [MacAdam ellipse](https://en.wikipedia.org/wiki/MacAdam_ellipse) (the range of colors within the JND) is an ellipse/ellipsoid and not a sphere, but as mentioned before [redmean](https://en.wikipedia.org/wiki/Color_difference#sRGB) is a simple algorithm that apparently [works sufficiently well](http://godsnotwheregodsnot.blogspot.com/2012/09/color-space-comparisons.html) and would allow us to scale the RGB axes to get an ellipsoid. The 3 scales would be, where `R_0` is the red coordinate of the reference point (sphere center):
```
r = (2 + R_0 / 256) / 9
g = 4 / 9
b = (3 - R_0 / 256) / 9
```
Scaling the coordinates down by these factors ("squishing" the coordinate space), doing the line-sphere intersection and then scaling it back up should yield us appropriate results I believe.

In either case, in my testing this calculation can be done without any caching at all in real time and (in a more limited testing) it seems to produce equally well adjusted colors. (Only the `sqrt` is a bit "problematic" but even that can be replaced with `FRSQRTE`/`FRSQRTS` on ARM64 and `RSQRTSS` on x86.)

**Comment by PankajBhojwani** [comment]
Had a chat with @lhecker, turns out the red-mean algorithm is not quite robust enough and just doesn't work as well as the delta e one. So we will stick to this algorithm for now and in the future come back to optimizing the delta e algorithm (Leonard has several ideas for how we can do this). 

I've also switched the setting back to default off as per James' suggestion

File: src/cascadia/TerminalSettingsModel/MTSMSettings.h [hunk 4]
```diff
@@ -109,7 +109,7 @@ Author(s):
     X(hstring, ColorSchemeName, "colorScheme", L"Campbell")                                                                                                        \
     X(hstring, BackgroundImagePath, "backgroundImage")                                                                                                             \
     X(Model::IntenseStyle, IntenseTextStyle, "intenseTextStyle", Model::IntenseStyle::Bright)                                                                      \
-    X(bool, AdjustIndistinguishableColors, "adjustIndistinguishableColors", false)
+    X(bool, AdjustIndistinguishableColors, "adjustIndistinguishableColors", true)
```
[the remark this answers is not in the document]
Comment (PankajBhojwani) [reply src/cascadia/TerminalSettingsModel/MTSMSettings.h]: switched it back as per James' suggestion

File: src/renderer/base/RenderSettings.cpp (hunk 2 above)
Comment (PankajBhojwani) [reply src/renderer/base/RenderSettings.cpp:90]: ^ what Dustin said, but we're leaving #11939 as a todo for now

File: src/terminal/adapter/adaptDispatch.cpp (hunk 3 above)
Comment (PankajBhojwani) [reply src/terminal/adapter/adaptDispatch.cpp:2228]: Thank you for the catch!

**Review by zadjii-msft — APPROVED** [review]
I'm cool with this, but I'm gonna leave automerge off to give Dustin a last chance at it.

**Comment by mailinglists35** [comment]
Hi, could you show an example of the relevant section of settings file where to enable this feature?
thanks
