### PR TITLE
fix: WpfTerminalControl allow Connection set to null

### LINKED ISSUE #15061: WPF Terminal Control crashes when set to a null Connection
### Windows Terminal version

n/a

### Windows build number

10.0.19044

### Other Software

WPF / .net control

### Steps to reproduce

The `Microsoft.Terminal.Wpf.TerminalControl` instance has a `ITerminalConnection Connection` interface that relates the backend connection.  While this starts as null, once it is set to not null setting it back to null throws an UE.  In fact probably just setting it to null when already null would do the same as the setter control tries to access the TerminalOutput function on the value.

### Expected Behavior

not to fault just to clear the old connection.

### Actual Behavior

unhandled exception

will submit PR to fix.

### PR DESCRIPTION
**Pull request by mitchcapper**
Hides the cursor when null, shows it when not.
Clear the screen any time the connection is changed.

## Summary of the Pull Request
Prevents the WPF Control from crashing when set back to null, clears the console and hides the mouse as well.
## References and Relevant Issues
#15061

## Detailed Description of the Pull Request / Additional comments

It say 3 ansi commands as well now:
1) When the Connection is set to null the cursor is hidden (reflects what the default state is)
2) When the Connection is set to a value and it was null before we show the cursor (not a breaking change as requires it to have been null which previously would cause a crash, except for for set)
3) When the Connection is changed the screen is cleared.  A breaking change officially although not sure if there are use cases where this behavior is not desired.  For added safety we could make sure we are not being set to the same value we currently are.

None of the ansi commands are needed, users could do it all themselves as well, the behavior largely seemed natural though.  I didn't see any ansi constants anywhere so they are just hard coded with comments, but not sure if there is an established better practice.

Closes #15061

### CODE REVIEW

**Comment by mitchcapper** [comment]
@microsoft-github-policy-service agree

**Comment by mitchcapper** [comment]
@microsoft-github-policy-service agree
I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.

**Review by zadjii-msft — APPROVED** [review]
Sure

**Review by DHowett — CHANGES_REQUESTED** [review]
Alright! I like the thrust behind this, but I'd like to put you on brief pause while we figure out what the public API for the Terminal Control is.

In general, I feel weird about using strings to have one part of an application tell another part what to do; this includes VT (the control telling itself!)

It strikes me as something that should be intrinsic to the internal native API bridging PublicTerminalCore <-> WpfTerminalControl.

In addition, we may want to surface the _hard reset_ operation rather than a simple clear screen one. A connection terminating can leave the terminal in a weird state, where it's sending encoded mouse events or scroll events or is using DECCKM for arrow keys or somesuch. Hard reset will bring it completely back into sanity. :)

**Comment by mitchcapper** [comment]
> In general, I feel weird about using strings to have one part of an application tell another part what to do; this includes VT (the control telling itself!)

Yeah certainly a bit odd but such is much of the ANSI api. 

If exposing the hard reset api is something to occur sooner rather than later happy to wait and update once it is.  If it might be a good bit further down the line, I can revise this to just allow setting it back to null for a temporary bandaid (if preferable).  There is nothing currently that stops you from assigning another it is just setting to null that breaks things (so the bugs mentioned do occur there).

**Comment by zadjii-msft** [comment]
Discussion: maybe it should be the `tput reset` string

File: src/cascadia/WpfTerminalControl/TerminalContainer.cs [hunk 1]
```diff
@@ -113,10 +113,23 @@ private get
                 {
                     this.connection.TerminalOutput -= this.Connection_TerminalOutput;
                 }
-
+                this.Connection_TerminalOutput(this, new TerminalOutputEventArgs("\u001b[2J")); //clear screen
```
Comment (lhecker) [inline src/cascadia/WpfTerminalControl/TerminalContainer.cs:116]: C# supports `\x1b` for strings btw, so there's no need for the rather verbose `\u001b`.

**Comment by lhecker** [comment]
I personally believe that the ANSI escape sequences are fine. Using an approach like `tput reset` is probably a good idea, because it's more robust at resetting the state. The output of `tput reset` for `xterm-256color` is:
```c#
"\x1bc\x1b]104\a\x1b[!p\x1b[?3;4l\x1b[4l\x1b>\x1b[?69l"
```

Translated this means:
* `\x1bc`: RIS - Reset to initial state
* `\x1b]104\a`: OSC 104 - color palette reset (not yet implemented though #3719)
* `\x1b[!p`: DECSTR - soft reset
* `\x1b[?3;4l`: DECRST - 80 columns (DECCOLM), fast scroll (DECSCLM)
* `\x1b[4l`: RM - reset mode to replace mode (IRM)
* `\x1b>`: DECKPNM - normal keypad
* `\x1b[?69l`: DECRST - disable left and right margins (DECLRMM)

Some of these don't seem to be useful for us, but I think that this string is generally fine. It's definitely more thorough than the current approach.

**Comment by DHowett** [comment]
Alright @mitchcapper, my team convinced me to see the light here. I'm not gonna let perfect be the enemy of good enough, and I think that using VT is _good enough._ We don't have immediate plans to give you a better API, anyway.

I was pretty curious about Leonard's recommended reset sequence, though.

> 
> ```cs
> "\x1bc\x1b]104\a\x1b[!p\x1b[?3;4l\x1b[4l\x1b>\x1b[?69l"
> ```
> 
> * `\x1bc`: RIS - Reset to initial state
> * `\x1b]104\a`: OSC 104 - color palette reset (not yet implemented though [Support resetting the colors via OSC 104, 110, 111... #3719](https://github.com/microsoft/terminal/issues/3719))
> * `\x1b[!p`: DECSTR - soft reset
> * `\x1b[?3;4l`: DECRST - 80 columns (DECCOLM), fast scroll (DECSCLM)
> * `\x1b[4l`: RM - reset mode to replace mode (IRM)
> * `\x1b>`: DECKPNM - normal keypad
> * `\x1b[?69l`: DECRST - disable left and right margins (DECLRMM)
> 

I don't know if we need to go full overboard with this, and I'm actually quite confused as to why `tput reset` emits all of these. Maybe @j4james has additional info there.

My understanding is that `\x1bc` `RIS` should reset the terminal to its startup state and blow away `DECCOLM` `DECSCLM` `IRM` `DECKPAM` and `DECLRMM` through standard operation. Looking at our own implementation . . .

https://github.com/microsoft/terminal/blob/f671f065bf313f1450c7e27e271856e4cf76989a/src/terminal/adapter/adaptDispatch.cpp#L2594-L2610

https://github.com/microsoft/terminal/blob/f671f065bf313f1450c7e27e271856e4cf76989a/src/terminal/adapter/adaptDispatch.cpp#L2535-L2556

. . . I believe that all we need is `\x1bc\x1b]104\x1b\\` because everything else is redundant or unsupported.

**Comment by j4james** [comment]
> My understanding is that `\x1bc` `RIS` should reset the terminal to its startup state and blow away `DECCOLM` `DECSCLM` `IRM` `DECKPAM` and `DECLRMM` through standard operation.

The issue here is that terminfo has a bunch of different reset strings (`rs1`, `rs2`, etc.). I don't know if their meaning is officially defined anywhere, but on XTerm, `rs1` is a hard reset, and `rs2` is a soft reset with a bunch of other things being manually reset.

I suspect one of the reasons for the split might be because some of the original hardware terminals would trigger a disconnect on a hard reset, so it would typically be preferable to use a soft reset if that option was available.

When you do a `tput reset`, though, it's just outputting all of the reset strings combined together, which kind of defeats the purpose. But maybe there's a good reason for that - I know very little about terminfo.

But the bottom line is, if you're going to send `RIS`, you really shouldn't need to send anything else. I believe that should even reset the palette, although I'll have to check how well that's supported. I know we don't do that, but it's on my TODO list.

**Comment by mitchcapper** [comment]
OK so I have updated the PR to match described.   @lhecker I mostly was using the intercept sequences between ConPty and Terminal. The `\x1b` does save you two characters but when doing tests with VT sequences more prone to error esp in chains (at least for me:)).  `0x1bG` completely fine but follow it with any of the valid hex chars, say `\x1bc`, and oops you did a "Ƽ".

**Review by DHowett — APPROVED** [review]

**Comment by DHowett** [comment]
Thanks James for the write-up :) and thanks Mitch for implementing
