### PR TITLE
Fix A11y EndExclusive Error for Move & Expand

### LINKED ISSUE #7663: conhost crash in narrator scan mode when jumping to heading 1
open conhost. enter scan mode. press `1` to navigate to the first heading

### LINKED ISSUE #7664: conhost crash (unknown cause) with UIA text range at {0, -1}
x |  x |  x | x  | x  | x  |  x |x  |  x| xz
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
8 | conhost!Microsoft::Console::Types::Viewport::WalkInBoundsCircular |   | 0x0000000000000031 |   |   |   | viewport.cpp |   | 411
9 | conhost!Microsoft::Console::Types::Viewport::WalkInBounds |   | 0x0000000000000019 |   |   |   | viewport.cpp |   | 383
10 | conhost!TextBuffer::_GetWordEndForAccessibility |   | 0x0000000000000092 |   |   |   | textbuffer.cpp |   | 1141
11 | conhost!Microsoft::Console::Types::UiaTextRangeBase::ExpandToEnclosingUnit |   | 0x00000000000001C0 |   |   |   | uiatextrangebase.cpp |   | 271
12 | uiautomationcore!ProviderCallouts::ExpandToEnclosingUnit |   | 0x0000000000000043 |   |   |   | ProviderCallouts.h |   | 1362
13 | uiautomationcore!RemotePatternStub::TextRange_ExpandToEnclosingUnit

### PR DESCRIPTION
**Pull request by carlos-zamora**
`EndExclusive` represents the end of the buffer. This is designed to not
point to any data on the buffer. UiaTextRange would point to this
`EndExclusive` and then attempt to move based on it. However, since it
does not point to any data, it could experience undefined behavior or
(inevitably) crash from running out of bounds.

This PR specifically checks for expansion and movement at that point,
and prevents us from moving beyond it. There are plans in the future to
define the "end" as the last character in the buffer. Until then, this
solution will suffice and provide correct behavior that doesn't crash.

## Validation Steps Performed
Performed the referenced bugs' repro steps and added test coverage.

Closes MSFT-20458595
Closes #7663
Closes #7664

### CODE REVIEW

**Comment by DHowett** [comment]
* did you figure out how we could end up with -1​​​​​​​ in a uia endpoint?
* it looks like this stops all movement at the end-degenerate. what about moving _backwards_?

**Comment by DHowett** [comment]
Build veyr mad

File: src/buffer/out/textBuffer.cpp [hunk 1]
```diff
@@ -1289,6 +1310,13 @@ bool TextBuffer::MoveToPreviousWord(COORD& pos, std::wstring_view wordDelimiters
     auto copy = pos;
     auto bufferSize = GetSize();
 
+    // GH#7663: Treat EndExclusive as EndInclusive so
+    // that it actually points to a space in the buffer
+    if (pos == bufferSize.EndExclusive())
+    {
+        copy = { bufferSize.RightExclusive(), bufferSize.BottomInclusive() };
```
Comment (DHowett) [inline src/buffer/out/textBuffer.cpp:1317]: I am worried that this is actually another version of "end exclusive" -- the invalid one. To be inclusive, it would need to be both right AND bottom inclusive, no?

Comment (DHowett) [reply src/buffer/out/textBuffer.cpp:1317]: it has the same comment as above (!!!!) but a different implementation (!!!!)

**Review by DHowett — CHANGES_REQUESTED** [review]

File: src/buffer/out/textBuffer.cpp (hunk 1 above)
Comment (carlos-zamora) [reply src/buffer/out/textBuffer.cpp:1318]: Good catch

**Comment by codeofdusk** [comment]
CC @simon818

File: src/host/ut_host/TextBufferTests.cpp [hunk 2]
```diff
@@ -2065,7 +2065,7 @@ void TextBufferTests::GetWordBoundaries()
         { { 79, 0 },    {{ 10, 0 },      { 5, 0 }} },
 
         // tests for second line of text
-        { {  0, 1 },     {{ 0, 1 },       { 0, 1 }} },
+        { {  0, 1 },     {{ 0, 1 },       { 5, 0 }} },
```
Comment (DHowett) [inline src/host/ut_host/TextBufferTests.cpp:2068]: I'm not sure which of the code changes made this change. Is this good and righteous? It _seems_ like it is because a11y defines the word to be the word + all the spaces after it, so you're inside the spaces at 0,1... so the word starts at 5,0... but why was this broken before?

Comment (carlos-zamora) [reply src/host/ut_host/TextBufferTests.cpp:2068]: This one was a mistake on my part back when I wrote these tests. You're right to be concerned but here's my reasoning:

You have the following text:
```
word other
  more   words
```

You're current position is where the X is (0,1):
```
word other
X more   words
```

When we get the previous word, we're supposed to wrap around to encompass "other". Before, on accident, we would hit the left boundary and _not_ wrap. So we would actually return the whitespace on the second line between the left boundary and "more".

Comment (DHowett) [reply src/host/ut_host/TextBufferTests.cpp:2068]: how did this test not _fail_ then? o_O

Comment (carlos-zamora) [reply src/host/ut_host/TextBufferTests.cpp:2068]: The test didn't fail because I wrote it incorrectly. It used to expect the whitespace. It _should_ have expected the word on the previous line.

Comment (carlos-zamora) [reply src/host/ut_host/TextBufferTests.cpp:2068]: I can't figure out how to permalink code, but you want to look at textbuffer.cpp line 1000
```c++
if (target.X == GetSize().Left())
```
We were treating "Left" as "Origin" and refusing to expand left.

**Review by DHowett — APPROVED** [review]

File: src/buffer/out/textBuffer.cpp [hunk 3]
```diff
@@ -996,19 +996,29 @@ const COORD TextBuffer::GetWordStart(const COORD target, const std::wstring_view
...
+    if (target == bufferSize.Origin())
+    {
+        // can't expand left
         return target;
     }
+    else if (target == bufferSize.EndExclusive())
+    {
+        // treat EndExclusive as EndInclusive
+        copy = { bufferSize.RightInclusive(), bufferSize.BottomInclusive() };
+    }
```
Comment (miniksa) [inline src/buffer/out/textBuffer.cpp:1013]: What if `target` is < `bufferSize.Origin()` or if `target` is > `bufferSize.EndExclusive()`?

Should we just be clamping this inside the bounds? Should we otherwise error out for those values?

Comment (DHowett) [reply src/buffer/out/textBuffer.cpp:1013]: @miniksa I'm not sure -- we only have `Compare` in Viewport for assessing relative location of points and it `THROW`s if you try to compare something that's actually out of bounds. It seems unsafe to use it here given we're fixing an a11y crash

Comment (miniksa) [reply src/buffer/out/textBuffer.cpp:1013]: Ick. Don't want that. If it's possible to do it with a `<=` and/or `>=` then fine. Otherwise, I withdraw my comment.

Comment (carlos-zamora) [reply src/buffer/out/textBuffer.cpp:1013]: Yeah. Gonna resolve this comment.
Side Note: Would it be possible/beneficial for us to create a non-crashing comparison operator for COORDs/points? It would look something like this:
```c++
bool operator<= (const COORD &c1, const COORD &c2)
{
    return c1.X <= c2.X && c1.Y <= c2.Y;
}
```
My main concern would be that it would cause some confusion with `CompareInBounds`, but this is just a thought.

Comment (miniksa) [reply src/buffer/out/textBuffer.cpp:1013]: Maybe. But not right now. We already have a lot of ways of doing this comparison. If we're going to make new operators, I'd want to sit down and evaluate the whole codebase so we stop having like 12 utilities that do similar things.

**Review by miniksa — APPROVED** [review]

**Comment by codeofdusk** [comment]
> Yeah. Gonna resolve this comment.

@carlos-zamora presumably in a follow-up PR?

**Comment by carlos-zamora** [comment]
> > Yeah. Gonna resolve this comment.
> 
> @carlos-zamora presumably in a follow-up PR?

Just a thought to play around with. This could be a part of #6453, since we'll hit that case often then.

**Comment by DHowett** [comment]
This fix was just released as part of Windows in [Insider Build 20236](https://blogs.windows.com/windows-insider/2020/10/14/announcing-windows-10-insider-preview-build-20236/)!
