### PR TITLE
Fix all fragments not loading when one is badly formed

### LINKED ISSUE #11330: One broken stub in a fragment file causes the whole file to not load
### Windows Terminal version (or Windows build number)

Current main build

### Other Software

_No response_

### Steps to reproduce

Put the following fragment file in `AppData\Local\Microsoft\Windows Terminal\Fragments\{any-name-here}`:

```
{
  "profiles": [
    {
      "name": "broken profile",
      "font": "thisFontDoesntExist"
    },
    {
      "name": "Cool Profile"
    }
  ]
}
```

Then start WT

### Expected Behavior

"Cool Profile" should show up in the dropdown

### Actual Behavior

"Cool Profile" does not show up, the presence of the broken profile causes the non-broken profile to not load

### PR DESCRIPTION
**Pull request by lhecker**
This commit introduces a number of poor abstractions to split
`SettingsLoader::_parse` into `_parse` for content in the format of the user's
settings.json and `_parseFragment` which is specialized for fragment files.
The latter suppresses exceptions and supports the "updates" key for profiles.

## PR Checklist
* [x] Closes #11330
* [x] I work here
* [x] Tests added/passed

## Validation Steps Performed

* Wrote the following to
  `%LOCALAPPDATA%\Microsoft\Windows Terminal\Fragments\test\test.json`:
  ```json
  {
    "profiles": [
      {
        "name": "bad",
        "unfocusedAppearance": ""
      },
      {
        "name": "good"
      },
      {
        "updates": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
        "background": "#333"
      }
    ]
  }
  ```
* Ensured that "bad" is ignored ✔️
* Ensured that "good" shows up and works ✔️
* Ensured that the pwsh profile has a gray background ✔️

### CODE REVIEW

**Review by PankajBhojwani — APPROVED** [review]
Thanks!

File: src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp [hunk 1]
```diff
@@ -432,92 +440,124 @@ gsl::span<const winrt::com_ptr<Profile>> SettingsLoader::_getNonUserOriginProfil
...
+    // The Guid() generation below depends on the value of Source().
+    // --> Provide one if we got one.
+    if (!source.empty())
+    {
+        profile->Source(source);
+    }
+
+    if (!profile->HasGuid() && profile->HasName())
+    {
+        profile->Guid(profile->Guid());
```
Comment (carlos-zamora) [inline src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp:555]: This looks really weird haha. I'd add a comment saying that we're generating a guid based on the name, and storing it.

File: src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp [hunk 2]
```diff
@@ -432,92 +440,124 @@ gsl::span<const winrt::com_ptr<Profile>> SettingsLoader::_getNonUserOriginProfil
...
-
-            // The Guid() generation below depends on the value of Source().
-            // --> Provide one if we got one.
-            if (!source.empty())
+            auto profile = _parseProfile(origin, source, profileJson);
+            if (profile->HasGuid())
             {
-                profile->Source(source);
+                _appendProfile(std::move(profile), settings);
             }
```
Comment (carlos-zamora) [inline src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp:481]: Won't this always be `true` because `_parseProfile` generates/saves a guid if there isn't one?

File: src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp [hunk 3]
```diff
@@ -432,92 +440,124 @@ gsl::span<const winrt::com_ptr<Profile>> SettingsLoader::_getNonUserOriginProfil
...
+        const auto size = json.profilesList.size();
+        settings.profiles.reserve(size);
+        settings.profilesByGuid.reserve(size);
+
+        for (const auto& profileJson : json.profilesList)
+        {
+            try
+            {
+                auto profile = _parseProfile(OriginTag::Fragment, source, profileJson);
+                if (profile->HasGuid() || profile->Updates() != winrt::guid{})
```
Comment (carlos-zamora) [inline src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp:520]: similar question as above (though this one might be ok).

Won't we always have a guid, so we'll always append the profile?

**Review by carlos-zamora — APPROVED** [review]

File: src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp (hunk 2 above)
Comment (lhecker) [reply src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp:481]: It'll only generate a Guid() if there was a Name().
Normally I'd just return a nullptr to communicate to the caller that no profile could be parsed, but fragments allow profiles without either Guid or Name. They also accept profiles with a valid Updates() value. That's why both callers check HasGuid(). I'll add comments.
