### PR TITLE
Grab the write lock before updating the font

### LINKED ISSUE #5479: Crashes if zoom font size up and down rapidly with ctrl + scroll wheel
# Environment

Win10 1909 x64

Windows Terminal version (if applicable): 0.11.1121.0

# Steps to reproduce

Increase and decrease the font size rapidly in the first tab using ctrl and mouse scroll wheel

# Expected behavior

Not to crash

# Actual behavior

Crashes

---

Crashes every time when I use Ctrl and the mouse wheel to increase and decrease the font rapidly. Only happens with the first tab and regardless of what is running in there. I have crash dumps. Doesn't crash when I try and record a video of it in Snagit.

image

### PR DESCRIPTION
**Pull request by leonMSFT**
## Summary of the Pull Request
Based on the discussion in #5479, it seems that the crash is caused by a race condition due to not obtaining the write lock before calling `TriggerFontChange`.

I'm not totally sure if my approach is the right one, but I've taken the lock out of `_RefreshSize` since it seems like all calls of `_RefreshSize` come after a `TriggerFontChange`/`UpdateFont`. Then I just 
made sure all calls of `TriggerFontChange`/`UpdateFont` are preceded with a `LockForWriting`.

## PR Checklist
* [x] Closes #5479
* [x] CLA signed.
* [x] Tests added/passed

## Validation Steps Performed
Scrolling to change my font size does not kill the Terminal anymore! 🙌

### CODE REVIEW

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 1]
```diff
@@ -1833,6 +1840,7 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
     //   swapchain size. This helper will call _DoResize with the current size
     //   of the swapchain, accounting for scaling due to DPI.
     // - Note that a DPI change will also trigger a font size change, and will call into here.
+    // - The write lock should be held when calling this method, we might be changing the buffer size in _DoResize.
```
Comment (zadjii-msft) [inline src/cascadia/TerminalControl/TermControl.cpp:1843]: Is there any way we can check if a lock is currently held? Like introduce some sort of `assert(terminal->IsLocked())`?

Comment (leonMSFT) [reply src/cascadia/TerminalControl/TermControl.cpp:1843]: hmm, I don't think you can ask if the mutex is held bc of the whole "oh it's not held @ time = 0? let me lock then! (but then somebody else swipes it away @ time = 0.001)", but there is a `std::shared_mutex::try_lock` that would return false if it can't lock otherwise it returns true and locks? 🤔

**Comment by DHowett-MSFT** [comment]
If you run `cmatrix -u0` inside WSL, do you get hitching when you try to mouse-wheel the font (when text output takes/releases the write lock)?

**Comment by zadjii-msft** [comment]
> I'd like to propose a name change to make this a bit clearer-

This is a very good idea

**Comment by leonMSFT** [comment]
@DHowett-MSFT What do you mean by hitching? Do you mean like getting stuck for a split second but continuing along its merry way with a smaller/bigger font size?

**Comment by DHowett-MSFT** [comment]
Yep. I guess I was worried about it being noticeably long and annoying but honestly that probably doesn’t matter

**Comment by leonMSFT** [comment]
cmatrixscrollcompare

Alright idk if this'll help but the left is 0.11.191.0 and the right is my branch, from what I can see it looks kinda similar??

**Comment by DHowett-MSFT** [comment]
lgtm!

**Comment by zadjii-msft** [comment]
those are some A+ gifs

**Comment by DHowett-MSFT** [comment]
@msftbot merge this in 1 minutes
