### PR TITLE
Fix selection render on paste

### LINKED ISSUE #11227: Pasting does not clear the rendered selection
### Windows Terminal version (or Windows build number)

1.10.2383.0

### Other Software

None

### Steps to reproduce

1. Create a selection
2. execute `paste` keybinding

### Expected Behavior

Paste should clear the selection and inject the pasted text.

### Actual Behavior

The text is pasted, but the selection is not cleared.

Interestingly, executing the copy action (with <kbd>ctrl+c</kbd>, for example) passes the keybinding through. This suggests that the selection was cleared, but we're not telling the renderer to `TriggerSelection()` on a paste operation.

### PR DESCRIPTION
**Pull request by serd2011**
## Summary of the Pull Request
Clears selection render on paste

## PR Checklist
* [x] Closes #11227
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA

## Detailed Description of the Pull Request / Additional comments
Added ```_renderer->TriggerSelection(); ``` similarly to the copy action few lines up in ```CopySelectionToClipboard``` function

## Validation Steps Performed
Manually tested

### CODE REVIEW

**Review by carlos-zamora — APPROVED** [review]
Thank you!

File: src/cascadia/TerminalControl/ControlCore.cpp [hunk 1]
```diff
@@ -979,6 +979,7 @@ namespace winrt::Microsoft::Terminal::Control::implementation
     {
         _terminal->WritePastedText(hstr);
         _terminal->ClearSelection();
```
Comment (zadjii-msft) [inline src/cascadia/TerminalControl/ControlCore.cpp:981]: aside: `Terminal::ClearSelection` should probably just trigger selection, right?

**Review by zadjii-msft — APPROVED** [review]

**Review by lhecker — APPROVED** [review]

File: src/cascadia/TerminalControl/ControlCore.cpp (hunk 1 above)
Comment (carlos-zamora) [reply src/cascadia/TerminalControl/ControlCore.cpp:981]: Yeah, I'm thinking we may want to move all of the `TriggerSelection()` calls down to `TerminalSelection.cpp`. There's a few times we trigger something off the renderer in `Terminal.cpp`, so we'd basically do the same.
