### PR TITLE
Merge the PrintString functionality into AdaptDispatch

### LINKED ISSUE #780: Implement stream writing mechanism on buffer (a.k.a. WriteCharsLegacy2ElectricBoogaloo)
Apologies if this explanation is confusing. I've mentally internalized the problem here, but I'm not sure if I can fully articulate. Here goes...

When receiving characters in a stream fashion (in either conhost or the Terminal), there are a bunch of situations that occur that run off the golden path rails of "just put this into the buffer and move the cursor forward by one". 

A few major categories of these are:
1. C0 control characters (tab, backspace, newline, carriage return, etc.)
2. Surrogate pairs for UTF-16 (two wchar_ts are required to form one U+ codepoint)
3. An entire run of characters required to figure out a particular cell display or run of cells.

We need to solve 1 and 2 first. Solving 3 will probably require a bit more interaction with the `CustomTextLayout` in the DirectWrite renderer to perform some sort of read-ahead or multiple-pass calculation over text as it flows in stream-wise to figure out the columns it should take.

The existing manifests of this sort of work are `WriteCharsLegacy` in the console host (which is a thousand line or more monstrosity full of multi-pass switch cases, loops, and gotos) and the stream write thing in `TerminalControl` (I think, might be `TerminalConnection`) which @zadjii-msft affectionately warned against it becoming "WriteCharsLegacy2ElectricBoogaloo" in one of his comments.

I think what needs to be done here is:
1. Create a third entry point to the buffer object that accepts text in a stream write fashion, potentially "buffering" before it inserts into the buffer for reals (or has the ability to look-behind at what was just written) taking over the duties of the "WriteCharsLegacy" type methods into the buffer itself so at least 1 and 2 can be handled in a unified-ish manner.
2. Teach the buffer and/or let the buffer accept some sort of loose pfn that will connect it up to the text layout engine and let it query for column counts or glyph run information as stream characters show up and adjust the behavior of their neighboring glyphs.

### LINKED ISSUE #6162: Extra space cell inserted after unicode character
# Environment

```none
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18363.0 Microsoft Windows NT 10.0.18363.0

Terminal v1.0.1401.0
```

# Steps to reproduce

Write the following string to the terminal (Python):

```
>>> print("│\x1b[33m\U0001F862\x1b[0m│")
```

This string is a unicode box char,  followed by a foreground yellow escape, a [unicode arrow](https://www.fileformat.info/info/unicode/char/1f862/index.htm), a reset escape, and another box character. 

# Expected behavior

The string should render three characters: a vertical line, yellow arrow, vertical line.

# Actual behavior

There is an extra space after the arrow. 

Screen Shot 2020-05-23 at 14 45 16

Note that this only occurs with that particular unicode character. If I replace that unicode arrow with any other character then it renders as expected.

### LINKED ISSUE #6555: Narrow emoji >=U+10000 make WriteCharsLegacy sad ("wrong character insertion when scrolling to bash history")
_Notes from https://github.com/microsoft/terminal/issues/6555#issuecomment-646206984_

```
[0x4]   OpenConsoleFullPDB!IsGlyphFullWidth + 0x9   
[0x5]   OpenConsoleFullPDB!WriteCharsLegacy + 0x2a3                  <<<<<<<<<<<<<<<<<
[0x6]   OpenConsoleFullPDB!WriteBuffer::_DefaultStringCase + 0xaf   
[0x7]   OpenConsoleFullPDB!WriteBuffer::PrintString + 0x16   
[0x8]   OpenConsoleFullPDB!Microsoft::Console::VirtualTerminal::AdaptDispatch::PrintString + 0x61   
[0x9]   OpenConsoleFullPDB!Microsoft::Console::VirtualTerminal::OutputStateMachineEngine::ActionPrintString + 0x42   
[0xa]   OpenConsoleFullPDB!Microsoft::Console::VirtualTerminal::StateMachine::ProcessString + 0x197   
```

We're calling `IsGlyphFullWidth` once for each half of the surrogate pair. You can well imagine how nicely that works out.

---

# Environment

```none
Windows build number: Win32NT 10.0.19041.0 Microsoft Windows NT 10.0.19041.0
Windows Terminal version (if applicable): 1.0.1402.0

Using WSL Ubuntu LTS version 20.04
```

# Steps to reproduce

1. Install Microsoft Terminal from Windows Store. Keep the default settings.
2. Enable WSL and install Ubuntu 20.04 from Windows Store.
3. Start Ubuntu 20.04 via WSL2.
4. When bash prompt appears, run exactly this (from the first character until the end):
```bash
echo 🔥🌡  
```
the utf-16 equivalent (just to see the exact characters)
```none
\u0065\u0063\u0068\u006f\u0020\ud83d\udd25\ud83c\udf21\u0020\u0020
```
5. Press enter to see the result.
6. Press key UP 
7. Press key DOWN
8. Go to step 6. 

# Expected behavior

switch from 
```bash
echo 🔥🌡  
```
to 
```none

```
THIS PROBLEM CANNOT BE REPRODUCED ON OTHER TERMINAL EMULATORS 

# Actual behavior
character 'e' inserted at the beginning

### LINKED ISSUE #12440: Properly implement delayed EOL wrap in `Terminal::_WriteBuffer`
This issue tracks implementing delayed EOL wrap for `Terminal::_WriteBuffer`. More details on the exact issue below.

This is a subset of or step towards #780.

- - - - - - - - -
The problem is just that the `Terminal::_WriteBuffer` method doesn't implement delayed EOL wrap. As a very simple test case, run `printf "\e[999C*"` with a breakpoint in the `_WriteBuffer` method. You'll see it write out the `*` character and then increment the X coordinate beyond the width of the page, passing that invalid value to `_AdjustCursorPosition`. That should never happen.

What it should be doing is recording the delayed wrap, and leaving the cursor where it is in the final column. You can see how it's handled in conhost here:

https://github.com/microsoft/terminal/blob/2b202ce6d993404010337fe8ff205d7b240d60f5/src/host/_stream.cpp#L573-L588

If more output is received after that, then the cursor will need to be moved to the start of the next line, _before_ processing the output. Again you can see how that's handled in conhost here:

https://github.com/microsoft/terminal/blob/2b202ce6d993404010337fe8ff205d7b240d60f5/src/host/_stream.cpp#L365-L376

The bottom line is that WT doesn't have a fully functional `WriteBuffer` implementation - I think that's what #780 was meant to resolve.

_Originally posted by @j4james in https://github.com/microsoft/terminal/issues/8730#issuecomment-1028921497_

### LINKED ISSUE #12739: Cursor droppings are back in conhost
### Windows Terminal version

OpenConsole 8a34a0e59ac41bc805c308fb82bc7683e583d45d

### Windows build number

10.0.19041.1415

### Other Software

_No response_

### Steps to reproduce

1. You must be using a somewhat recent version of OpenConsole.
2. Open a WSL bash shell.
3. Execute the following: `printf "\e[2 q\e[9999C "; sleep 1`

The `CSI 2 q` is to get a non-blinking cursor which makes the issue easier to produce. The `CSI 9999C` moves the cursor to the end of the line, and the space initiates a delayed wrap. The sleep then gives the cursor a chance to be rendered before the next output will trigger the actual wrap.

### Expected Behavior

The output should wrap to the next line without leaving a visible cursor block behind.

### Actual Behavior

The cursor at the end of the line isn't cleared when the output wraps, so you end up with two cursors visible on the screen.

image

This doesn't occur in my inbox version of conhost, so I think it might be a regression.

### PR DESCRIPTION
**Pull request by j4james**
The main purpose of this PR was to merge the `ITerminalApi::PrintString`
implementations into a shared method in `AdaptDispatch`, and avoid the
VT code path depending on `WriteCharsLegacy`. But this refactoring has
also fixed some bugs that existed in the original implementations. 

This helps to close the gap between the Conhost and Terminal (#13408).

I started by taking the `WriteCharsLegacy` implementation, and stripping
out everything that didn't apply to the VT code path. What was left was
a fairly simple loop with the following steps:

1. Check if _delayed wrap_ is set, and if so, move to the next line.
2. Write out as much of the string as will fit on the current line.
3. If we reach the end of the line, set the _delayed wrap_ flag again.
4. Repeat the loop until the entire string has been output.

But step 2 was a little more complicated than necessary because of its
legacy history. It was copying the string into a temporary buffer,
manually estimated how much of it would fit, and then passing on that
partial buffer to the `TextBuffer::Write` method.

In the new implementation, we just pass the entire string directly to
`TextBuffer::WriteLine`, and that handles the clipping itself. The
returned `OutputCellIterator` tells us how much of the string is left.
This approach fixes some issues with wide characters, and should also
cope better with future buffer enhancements.

Another improvement from the new implementation is that the Terminal now
handles delayed EOL wrap correctly. However, the downside of this is
that it introduced a cursor-dropping bug that previously only affected
conhost. I hadn't originally intended to fix that, but it became more of
an issue now.

The root cause was the fact that we called `cursor.StartDeferDrawing()`
before outputting the text, and this was something I had adopted in the
new implementation as well. But I've now removed that, and instead just
call `cursor.SetIsOn(false)`. This seems to avoid the cursor droppings,
and hopefully still has similar performance benefits.

The other thing worth mentioning is that I've eliminated some special
casing handling for the `ENABLE_VIRTUAL_TERMINAL_PROCESSING` mode and
the `WC_DELAY_EOL_WRAP` flag in the `WriteCharsLegacy` function. They
were only used for VT output, so aren't needed here anymore.

## Validation Steps Performed

I've just been testing manually, writing out sample text both in ASCII
and with wide Unicode chars. I've made sure it wraps correctly when
exceeding the available space, but doesn't wrap when stopped at the last
column, and with `DECAWM` disabled, it doesn't wrap at all.

I've also confirmed that the test case from issue #12739 is now working
correctly, and the cursor no longer disappears in Windows Terminal when
writing to the last column (i.e. the delayed EOL wrap is working).

Closes #780
Closes #6162
Closes #6555
Closes #12440
Closes #12739

### CODE REVIEW

**Comment by j4james** [comment]
I've just realised there's another cursor-dropping case that can occur, similar to #12738, but when you've got a wide character at the end of the line. I think it's probably the result of the cursor bounds checking issue that I mentioned in https://github.com/microsoft/terminal/pull/13001#discussion_r862125419.

Technically this has always been a problem (at least it's not new to this PR), but once Windows Terminal is handling the delayed EOL wrap correctly, it's going to be more likely to occur in everyday usage. So perhaps it's something that needs to be fixed first.

**Comment by DHowett** [comment]
(We may hold this until 1.18 -- how do you feel about that? Or, does it fix issues that we should get ahead of that are new regressions in 1.17 as well?)

**Comment by j4james** [comment]
> (We may hold this until 1.18 -- how do you feel about that? Or, does it fix issues that we should get ahead of that are new regressions in 1.17 as well?)

Yeah, I'm happy to leave it until 1.18 - I don't think it's fixing anything major, and it's quite a big change, so there's always a risk it could be introducing new bugs.

**Comment by j4james** [comment]
One thing worth mentioning is that I had a PR ready to go for the `IRM` mode (#1947), which is built on top of this. But we've been without that for so long, I don't think it's the end of the world if it gets pushed back another release.

**Comment by zadjii-msft** [comment]
Oh man I really want to close out IRM and all these other threads, but yea we might want to hold this one. I think the 1.17 cutoff really snuck up on us after the holidays 😅

**Comment by j4james** [comment]
FYI, I found another two issues that are fixed by this PR: #6162 and #6555. It'll also fix at least some layout breaking cases in tmux (#6987). Essentially any time you use one of the characters from #6555 you would previously have ended up with a broken tmux layout, and now that doesn't happen.

I should add that this is probably largely thanks to the work Leonard has done in the `TextBuffer` code. But the `WriteCharsLegacy` implementation does its own width calculations, so it wasn't benefiting from those improvements, whereas the `PrintString` implementation in this PR relies on the buffer to determine the correct character widths.

**Comment by zadjii-msft** [comment]
Wait you're telling me there's a chance to fix #6987? @DHowett maybe we _should_ pull this in to 1.17

**Comment by j4james** [comment]
It's definitely not going to fix all of the #6987 issues (for example, the `U+FE0E` test case I demonstrated is still broken), but it should at least fix some of them.

The problem is you've got hundreds of people reporting the problem, but nobody ever narrows it down to an easily reproducible test case. So it's hard to tell if they're all triggered by the same thing, or they're all wildly different.

**Comment by DHowett** [comment]
> maybe we _should_ pull this in to 1.17

Chatted with Mike over teams and said, "If we can do a 3-signoff policy for this one, I'm in." We just did a bug bash where we folded this PR in for testing, so... I'm not terribly worried about it

File: src/terminal/adapter/adaptDispatch.cpp [hunk 1]
```diff
@@ -61,14 +61,98 @@ void AdaptDispatch::PrintString(const std::wstring_view string)
...
+void AdaptDispatch::_WriteToBuffer(const std::wstring_view string)
+{
+    auto& textBuffer = _api.GetTextBuffer();
+    auto& cursor = textBuffer.GetCursor();
+    auto cursorPosition = cursor.GetPosition();
+    const auto wrapAtEOL = _api.GetAutoWrapMode();
+    const auto attributes = textBuffer.GetCurrentAttributes();
+
+    // Turn off the cursor until we're done, so it isn't refreshed unnecessarily.
+    cursor.SetIsOn(false);
```
Comment (DHowett) [inline src/terminal/adapter/adaptDispatch.cpp:81]: I missed where this gets turned back on, but having tested it out I do believe that it _is_

**Review by DHowett — APPROVED** [review]
James, I simply can't even. _Seriously, thank you._

File: src/terminal/adapter/adaptDispatch.cpp (hunk 1 above)
Comment (j4james) [reply src/terminal/adapter/adaptDispatch.cpp:81]: That happens in the `_ApplyCursorMovementFlags` flags at the end of the method.

File: src/host/outputStream.cpp [hunk 2]
```diff
@@ -24,39 +24,6 @@ ConhostInternalGetSet::ConhostInternalGetSet(_In_ IIoProvider& io) :
...
-
-    auto& cursor = _io.GetActiveOutputBuffer().GetTextBuffer().GetCursor();
-    if (!cursor.IsOn())
-    {
-        cursor.SetIsOn(true);
-    }
-
-    // Defer the cursor drawing while we are iterating the string, for a better performance.
-    // We can not waste time displaying a cursor event when we know more text is coming right behind it.
-    cursor.StartDeferDrawing();
```
Comment (zadjii-msft) [inline src/host/outputStream.cpp:45]: /note: where'd this go

Comment (zadjii-msft) [reply src/host/outputStream.cpp:45]: oh duh 

> The root cause was the fact that we called cursor.StartDeferDrawing()
> before outputting the text, and this was something I had adopted in the
> new implementation as well. But I've now removed that, and instead just
> call cursor.SetIsOn(false). This seems to avoid the cursor droppings,
> and hopefully still has similar performance benefits.

**Review by zadjii-msft — APPROVED** [review]
Thank you for cleaning up one of my oldest messes. I can't tell you how happy I am that 

> This is not great but I need it demoable. Fix by making a buffer stream writer

will no longer be true. That was possibly one of my most egregious #fuckitshipit decisions in the Terminal codebase.

**Comment by zadjii-msft** [comment]
> One thing worth mentioning is that I had a PR ready to go for the `IRM` mode (#1947), which is built on top of this. But we've been without that for so long, I don't think it's the end of the world if it gets pushed back another release.

If you wanna fire that PR off we may as well pull that in for 1.17 too. This PR was a lot less scary than the label would imply, tbh. A fix for IRM might just be worth yolo'ing it.

**Comment by DHowett** [comment]
Agreed. I'm happy with a YOLO approach to IRM. James, you're a g-d d-mn star!

**Comment by lhecker** [comment]
I've also been working on IRM and got a PR about 75% done (tests are missing). But of course I'd be more than happy to merge @j4james's PR instead. Although it might be helpful to compare our approaches in either case. 🙂

**Comment by DHowett** [comment]
I would love to see both! We could even look at it as "now and future" or fold them together magically

**Comment by j4james** [comment]
I've just finished work for the day, and I'm a bit exhausted, but I'll try and put my IRM PR up later tonight after I've had something to eat. I think it does include a couple of basic unit tests, so you're welcome to take those for Leonard's PR of you prefer his approach.

**Comment by zadjii-msft** [comment]
@j4james also don't stress about it - this ain't your day job, it's ours 😝 We can absolutely ship without it, so take your time. We're in no rush.

**Comment by j4james** [comment]
I've submitted PR #14700 has a draft for now if you want to check it out. I haven't filled in the PR notes, but there's really not much to it. It's very much a hack, though, so I'd be more than happy to have it replaced by something better. It was just intended to be a quick fix.

**Comment by lhecker** [comment]
@j4james If you use WSL in OpenConsole, starting this PR, it won't scroll the viewport anymore when you type in your prompt, etc. I found that this branch is what made it work previously:
https://github.com/microsoft/terminal/blob/c79298d3fddb99f1acb80e512ff406867e316ee9/src/host/_stream.cpp#L269-L276

Do you remember whether this was an intentional change? I'd be happy to write a fix if it wasn't. (If you have any preferences where you'd like such a fix to be added in AdeptDispatch/etc., let me know!)

**Comment by j4james** [comment]
It's not so much that I wanted to remove the "snap on input" behaviour, but I suspect I chose not to replicate that part of `AdjustCursorPosition`, because the way it was implemented was breaking VT applications.

The issue is that VT code works within a specific area of the scrollback buffer, which is typically the visible viewport. But since the user can manually scroll that viewport, we have to track the VT viewport independently via the `_virtualBottom` field. However, when you call `SetViewportOrigin`, that potentially changes the `_virtualBottom`, and then your VT viewport can end up in the wrong place.

So while I'm sure it's fixable, it's probably not just a matter of reinstating that original code. Also be aware that the `_virtualBottom` code is quite fragile, so it's easy to break something inadvertently. Every time I've tried to fix an issue related to `_virtualBottom` I've ended up introducing another bug elsewhere.

**Comment by j4james** [comment]
I should add that I would recommend _not_ adjusting the horizontal viewport position for now, because in VT apps that's controlled by the horizontal cursor coupling mode (`DECHCCM`), which should be disabled by default.

There's actually also a vertical cursor coupling mode, but I'm not sure that's intended to apply to the scrollback situation we're dealing with here, and anyway that mode is supposed to be enabled by default.

**Comment by lhecker** [comment]
When you say you'd recommend against it, are you referring to snapping "on output" the way conhost did it before, or even snapping on input, the way Windows Terminal does it?

While the existence of snap-on-input or similar is not that big of a deal for most terminals including Windows Terminal, conhost has scroll-forward enabled by default and finding the prompt in the standard 9000-line scrollback is somewhat fiddly. Since the v1.18 OpenConsole will ship with the next Windows I'm worried people may complain about this change.

**Comment by DHowett** [comment]
> Since the v1.18 OpenConsole will ship with the next Windows I'm worried people may complain about this change.

It's actually _1.19_... and the gates for bug fixes are _practically closed._ Unless it's a bulletproof one-line fix, I don't think I could convince the triad to take it in 😄

**Comment by j4james** [comment]
If there is going to be any snapping, I think it should be on output, because that's what is expected from a VT standpoint, and is also what conhost always used to do.

I doubt anyone cares about horizontal snapping, because it's really annoying, and I doubt many people would be expecting that. But if you think it's a likely to generate complaints, I don't particular care what the default is. I'll add a mode for it one day anyway.
