### PR TITLE
Fixed Ctrl+Alt shortcuts conflicting with AltGr

### LINKED ISSUE #521: AltGR SEQUENCES DO NOT WORK -- Can't type any AltGr combinations in Windows Terminal
**Your Windows build number:**
 10.0.18362.86

**What you're doing and what's happening:**
Trying to enter the `@` sign on a Swedish keyboard in a PowerShell console using `Alt Gr` + `2`.  
See animated gif:

terminal

**What's wrong / what should be happening instead:**
Windows terminal shows `digit-argument` instead of outputting the `@` sign as expected.

It's possible this is a PEBKAC error somehow but the problem doesn't show up in the normal PowerShell console... 😓

### LINKED ISSUE #2254: Bug Report (default key mapping is not good if need use location setup which need AltGr to get some ascii-7 chars)
# Environment

```none
Windows build number: 1903 18362.267
Windows Terminal version (if applicable):  0.3.2142.0
```

# Steps to reproduce
Window Terminal have to be possible to use internationally.
"international localization" is the keyword which have to remember.

Cant give chars @ $ £ { [ ] } because keymapping ctrl+alt+1-9 kill those keys ex. in swedish, finnish, ... keyboards.

- @ = AltGr+2
- $ = AltGr+4
- ...

# Expected behavior

After I changed those tabbing keymapping ex. ctrl+shift+1, ctrl+shift+2, ... I got those important shell level characters from my keyboard as they have been since 199x.

# Actual behavior

Issue https://github.com/microsoft/terminal/issues/521 has been same problem, but it looks that this is not same, low level problem has fixed. 

Problem is same: AltGr not work. Current problem is easier to fix: Don't kill AltGr in default configuration using ctrl+alt+N (N=1-9) key mapping.

### PR DESCRIPTION
**Pull request by lhecker**
## Summary of the Pull Request

This moves the detection of AltGr keypresses in front of the shortcut handling.
This allows one to have Ctrl+Alt shortcuts, while simultaneously being able to use the AltGr key for special characters.

## References

This fixes a regression in v0.3.2142.0, which automatically creates `Ctrl+Alt+[0-9]` shortcuts for switching between tabs. These conflicted with the detection of the AltGr key. in `SendKeyEvent()`.
Refixes #521.

## PR Checklist
* [x] Closes #521, Closes #2254
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Requires documentation to be updated
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Detailed Description of the Pull Request / Additional comments

This PR has the flaw that it doesn't allow one to define AltGr shortcuts anymore.
Considering that it's probably more important to get a fix out of the door quickly I personally see this as a minor flaw though. VS Code has the same "flaw" for instance and doesn't allow AltGr combinations either.
We could fix it more correctly later on, by modifying the `IKeyBindings` interface and `KeyChord` class.

## Validation Steps Performed

* Enter AltGr-characters on my german keyboard and ensuring they appear in my shell.
* Ensure that `Ctrl+Alt+[0-9]` shortcuts simultaneously work.

### CODE REVIEW

**Comment by lhecker** [comment]
I've based this PR on a08666b btw, which is the common ancestor between master and release-0.3.
It should be possible to merge this PR into both branches without rebasing or cherry picking, etc.

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 1]
```diff
@@ -619,9 +619,24 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
...
+        // AltGr key combinations don't always contain any meaningful,
+        // pretranslated unicode character during WM_KEYDOWN.
+        // E.g. on a German keyboard AltGr+Q should result in a "@" character,
+        // but actually results in "Q" with Alt and Ctrl modifier states.
+        // By returning false though, we can abort handling this WM_KEYDOWN
+        // event and let the WM_CHAR handler kick in, which will be
+        // provided with an appropriate unicode character.
+        if (modifiers.IsAltGrPressed())
+        {
+            _SendKeyEvent();
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalControl/TermControl.cpp]: I’m not sure why we need to send an empty key event here.

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 2]
```diff
@@ -661,6 +664,31 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
         e.Handled(handled);
     }
 
+    void TermControl::_SendKeyEvent()
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalControl/TermControl.cpp]: Feel a bit weird about a void method wrapping a bool one and discarding the result

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 3]
```diff
@@ -661,6 +664,31 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
         e.Handled(handled);
     }
 
+    void TermControl::_SendKeyEvent()
+    {
+        _SendKeyEvent(0, {});
+    }
+
+    bool TermControl::_SendKeyEvent(WORD vkey, ControlKeyStates modifiers)
```
Comment (DHowett-MSFT) [inline src/cascadia/TerminalControl/TermControl.cpp]: nit: add a doc comment!

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 1 above)
Comment (lhecker) [reply src/cascadia/TerminalControl/TermControl.cpp]: The key event handler must call `_terminal->ClearSelection()`, because the char handler doesn't.
Additionally `_terminal->SetCursorVisible(true);` must be called on a key press as the comment at line 683 states.

**Comment by lhecker** [comment]
@DHowett-MSFT No problem. 😅 I guess I'm just 

I've amended this PR with comments for the two new functions. I've also tried to give them slightly more obvious names (although I failed at it I guess lol).
I'm not entirely sure how to beautify the code any further.
There's probably a reason for it, but IMHO the architecture between `TerminalControl::TermControl`, `Core::Terminal` and `Console::VirtualTerminal` feels kinda... redundant, as all 3 of them fiddle around with vkeys and modifiers. I believe merging these classes and resplitting the responsibilities might yield subjectively "better" code in the long run.

<details>
<summary>E.g. my thoughts regarding character handling...</summary>
You could for instance abstract AltGr, shortcut, etc. handling into one class each and concate them together to a stream of key/character event processors which implement the full, final keyboard handling.</br>
<code>TermControl</code> would also implement the common interface and be the final (self-referential) receiver in the chain.</br>
That way you do away with the current, loopy design, of <code>TermControl</code> handling a bit of the keys, pushing it down to <code>Terminal</code>, which implements a bit of the handling, which then pushes it down to <code>VirtualTerminal</code> which implements a bit of the handling and finally calls <code>TermControl</code> again through a <code>std::function</code> callback, which then stringifies the character/escape-sequence array and then calls <code>TermControl</code> again through a <code>std::function</code> callback which then sends it to the shell.</br>
It's very "loopy". 😄
</details>

**Comment by lhecker** [comment]
Alright... If you need any more of my <kbd>AltGr</kbd> expertisms: I've applied to the open position as well now. 😄😄

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 4]
```diff
@@ -619,35 +619,38 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
...
         const auto modifiers = _GetPressedModifierKeys();
-        const auto vkey = static_cast<WORD>(e.OriginalKey());
 
+        // AltGr key combinations don't always contain any meaningful,
+        // pretranslated unicode character during WM_KEYDOWN.
+        // E.g. on a German keyboard AltGr+Q should result in a "@" character,
+        // but actually results in "Q" with Alt and Ctrl modifier states.
+        // By returning false though, we can abort handling this WM_KEYDOWN
+        // event and let the WM_CHAR handler kick in, which will be
+        // provided with an appropriate unicode character.
```
Comment (zadjii-msft) [inline src/cascadia/TerminalControl/TermControl.cpp]: I'd maybe also mention in this comment something like the following:
```suggestion
        // provided with an appropriate unicode character.
        // GH#2235: Make sure to handle AltGr before trying keybindings, so 
        // Ctrl+Alt keybindings won't eat an AltGr keypress
```

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 5]
```diff
@@ -661,6 +664,45 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
         e.Handled(handled);
     }
 
+    // Method Description:
+    // - Some key events cannot be handled (e.g. AltGr combinations) and are
+    //   delegated to the character handler. Just like with _TrySendKeyEvent(),
+    //   the character handler counts on us though to:
+    // - Clears the current selection.
+    // - Makes the cursor briefly visible during typing.
+    void TermControl::_HandleVoidKeyEvent()
```
Comment (zadjii-msft) [inline src/cascadia/TerminalControl/TermControl.cpp]: nit: I think the name of this method could probably be better - the important meat of what this function is trying to accomplish isn't the sending of the void keypress, it's the dismissing of the selection and the cursor visibility.

Comment (lhecker) [reply src/cascadia/TerminalControl/TermControl.cpp]: Do you have a suggestion for the function name? I can't come up with anything. 😕
(If we had something different to `SendKeyEvent` - like e.g. `GenerateKeyEvent`, which returns an optional input sequence - we could more comfortably abstract "reset selection and cursor" I suppose. That way you could move the "reset selection and cursor" handling to the more correct WM_CHAR handler right?)

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 4 above)
Comment (lhecker) [reply src/cascadia/TerminalControl/TermControl.cpp]: FYI: I had to rebase your suggestion due to formatting issues.

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 6]
```diff
@@ -619,35 +619,41 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
...
 
+        // AltGr key combinations don't always contain any meaningful,
+        // pretranslated unicode character during WM_KEYDOWN.
+        // E.g. on a German keyboard AltGr+Q should result in a "@" character,
+        // but actually results in "Q" with Alt and Ctrl modifier states.
+        // By returning false though, we can abort handling this WM_KEYDOWN
+        // event and let the WM_CHAR handler kick in, which will be
+        // provided with an appropriate unicode character.
+        //
+        // GH#2235: Make sure to handle AltGr before trying keybindings,
```
[the remark this answers is not in the document]
Comment (zadjii-msft) [reply src/cascadia/TerminalControl/TermControl.cpp]: I usually like referencing the issue in the code near a bug fix like this. It can oftentimes provide a _lot_ more context than just the comment in the code.

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 7]
```diff
@@ -619,35 +619,41 @@ namespace winrt::Microsoft::Terminal::TerminalControl::implementation
...
         if (bindings)
         {
-            KeyChord chord(
+            handled = bindings.TryKeyChord({
                 modifiers.IsCtrlPressed(),
                 modifiers.IsAltPressed(),
                 modifiers.IsShiftPressed(),
-                vkey);
-            handled = bindings.TryKeyChord(chord);
+                vkey,
```
[the remark this answers is not in the document]
Comment (lhecker) [reply src/cascadia/TerminalControl/TermControl.cpp]: This is a list initialization expression, which is kinda akin to an array and I believe this project uses trailing commas for this. Right?
Do you want me to revert this change? It's technically not needed at all for this PR. 🙂
(It only snuck in, because I structured the code entirely differently in a previous attempt for this PR and I preferred block indents over visual indents. 🙈)

P.S.: In fact modern languages often allow (or even enforce) trailing commas on multiline expressions even, because it simplifies refactoring and diffs in the future.
If you want to add a trailing argument in the future and your `vkey` doesn't have a trailing comma already, your diff will contain changes to two lines, even though one of them only adds a comma. This also makes git blame harder to use. Realistically it's unlikely someone is going to write a better VCS anytime soon either, that would understand this change contextually.
In Go for instance this will yield an `missing ',' before newline in argument list` error.
Rust and Python (PEP8) follow the same reasoning after lengthy discussions each.

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 5 above)
Comment (lhecker) [reply src/cascadia/TerminalControl/TermControl.cpp]: The fact that `_TrySendKeyEvent()` supports a `vkey == 0` seemed kinda hacky to me and I wanted to hide this hacky fact even from calls within the same class. So I created a hacky-wrapper function and prevent other methods from being "spoiled". 😄
Do you want me to inline this function?

**Comment by zadjii-msft** [comment]
@DHowett-MSFT do the thing

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 7 above)
[the remark this answers is not in the document]
Comment (DHowett-MSFT) [reply src/cascadia/TerminalControl/TermControl.cpp]: I like this.
