### PR TITLE
Make sure to InvalidateAll on a resize

### LINKED ISSUE #5029: Alt+ Enter rendering error
# Environment

```none
Windows build number: [[Version 10.0.18363.720]]
Windows Terminal version (if applicable):  0.10.761.0

Any other software?
```

# Steps to reproduce
There are two bugs of Alt+Enter behavior.
 Text Disappear && Prompt Duplicate
a.  open terminal with WSL
b. type: ls -la or do whatever will print content over a page
c. **mouse scroll up** to the top
d. type Alt+Enter to Fullscreen
e. text outside orignal windows do not render.
d. scroll down to the bottom: type Alt+Enter several times
f. prompt duplicate several times.

I used zsh with the right side Prompt
image

# Actual behavior

image

image

# Expected behavior
We need to scroll the terminal  to force a re-rendering.
image

### PR DESCRIPTION
**Pull request by zadjii-msft**
## Summary of the Pull Request

Seriously just read the code on this one, it's so incredibly obvious what I did wrong

## References

Regressed with #4741 

## PR Checklist
* [x] Closes #5029
* [x] I work here
* [ ] Tests added/passed
* [n/a] Requires documentation to be updated

### CODE REVIEW

File: src/cascadia/TerminalCore/Terminal.cpp [hunk 1]
```diff
@@ -342,6 +342,9 @@ void Terminal::UpdateSettings(winrt::Microsoft::Terminal::Settings::ICoreSetting
     // If the old scrolloffset was 0, then we weren't scrolled back at all
     // before, and shouldn't be now either.
     _scrollOffset = originalOffsetWasZero ? 0 : ::base::ClampSub(_mutableViewport.Top(), newVisibleTop);
+
+    // GH#5029 - make sure to InvalidateAll here, so that we'll paint the entire visible viewport.
+    _buffer->GetRenderTarget().TriggerRedrawAll();
```
Comment (zadjii-msft) [inline src/cascadia/TerminalCore/Terminal.cpp]:
```suggestion
    try
    {
        _buffer->GetRenderTarget().TriggerRedrawAll();
    }
    CATCH_LOG();
```

**Comment by DHowett-MSFT** [comment]
@msftbot merge this in 5 minutes
