### PR TITLE
An attempted fix for the `SignalTextChanged` crash

### LINKED ISSUE #13357: Crash while holding a key
### Windows Terminal version

1.13.11432.0

### Windows build number

10.0.22621.1

### Other Software

in WSL I'm running 
- Debian 11 on kernel `5.10.102.1-microsoft-standard-WSL2` 
- fish shell (version 3.4.1) 
- vim (version 8.2)

### Steps to reproduce

I'm not sure what the exact steps to reproduce are, I've seen this crash a few times in the last couple days while holding a key in vim. Trying to find a more reliable way to reproduce but here's what is common across the crashes:

- terminal session was running for at least 1 hour (although one session lasted ~18 hours)
- terminal window contained multiple tabs with separate sessions on the same WSL2 vm
- when it crashes it takes every tab in the terminal window and the underlying WSL2 session with it
- a separate terminal window running an elevated powershell session survives the other window crashing
- crash occurs less than a second after I begin to hold a navigation key in vim (in debian on a WSL2 vm)
- before the crash, I'm able to hold navigation keys without issue
- I don't think it's related to #10957, fairly sure the motion I was performing in vim would not cause a bell. Also I'm able to run `tput bel` in a loop for at least 10 minutes without any issues (stopped at 10 mins for my ears' sake).

### Expected Behavior

Terminal window doesn't crash from underneath me while editing in vim.

### Actual Behavior

After a long time with no issues, terminal crashes less than a second after pressing and holding a navigation key (e.g. `j`, `h`) in vim. The crash takes out every terminal tab in the window and kills the WSL2 vm so I can't reattach and recover my state.

Event viewer report blames `Microsoft.Terminal.Control.dll` in each of the crashes that it has events logged for:

Logged at 6/21/2022 1:23:57 PM:
```
Faulting application name: WindowsTerminal.exe, version: 1.13.2205.23002, time stamp: 0x628bd6e5
Faulting module name: Microsoft.Terminal.Control.dll, version: 1.13.2205.23002, time stamp: 0x628bd501
Exception code: 0xc0000005
Fault offset: 0x00000000000a7031
Faulting process id: 0x0x81D0
Faulting application start time: 0x0x1D885A331CB7DF5
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.13.11432.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.13.11432.0_x64__8wekyb3d8bbwe\Microsoft.Terminal.Control.dll
Report Id: 231fb379-0618-424f-b270-4abcd9c76e91
Faulting package full name: Microsoft.WindowsTerminal_1.13.11432.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

Logged at 6/21/2022 12:14:47 PM:
```
Faulting application name: WindowsTerminal.exe, version: 1.13.2205.23002, time stamp: 0x628bd6e5
Faulting module name: Microsoft.Terminal.Control.dll, version: 1.13.2205.23002, time stamp: 0x628bd501
Exception code: 0xc0000005
Fault offset: 0x00000000000a7031
Faulting process id: 0x0x2E18
Faulting application start time: 0x0x1D8850DAF2A21D3
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.13.11432.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.13.11432.0_x64__8wekyb3d8bbwe\Microsoft.Terminal.Control.dll
Report Id: 16e18e82-72ce-4917-b27c-ad1086de5754
Faulting package full name: Microsoft.WindowsTerminal_1.13.11432.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

Logged at 6/20/2022 6:24:36 PM:
```
Faulting application name: WindowsTerminal.exe, version: 1.13.2205.23002, time stamp: 0x628bd6e5
Faulting module name: Microsoft.Terminal.Control.dll, version: 1.13.2205.23002, time stamp: 0x628bd501
Exception code: 0xc0000005
Fault offset: 0x00000000000a7031
Faulting process id: 0x0x7B30
Faulting application start time: 0x0x1D884FA55D2CF69
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.13.11432.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.13.11432.0_x64__8wekyb3d8bbwe\Microsoft.Terminal.Control.dll
Report Id: 5e7df318-5652-4433-8a12-0537323b2c06
Faulting package full name: Microsoft.WindowsTerminal_1.13.11432.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

Logged at 6/20/2022 4:05:15 PM:
```
Faulting application name: WindowsTerminal.exe, version: 1.13.2205.23002, time stamp: 0x628bd6e5
Faulting module name: Microsoft.Terminal.Control.dll, version: 1.13.2205.23002, time stamp: 0x628bd501
Exception code: 0xc0000005
Fault offset: 0x00000000000a5999
Faulting process id: 0x0x63FC
Faulting application start time: 0x0x1D880EA93FD3C3A
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.13.11432.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.13.11432.0_x64__8wekyb3d8bbwe\Microsoft.Terminal.Control.dll
Report Id: 157dd4ea-2879-4dd5-92bf-41d9449cc517
Faulting package full name: Microsoft.WindowsTerminal_1.13.11432.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

### PR DESCRIPTION
**Pull request by zadjii-msft**
This is conjecture - I was totally unable to repro the original crash here.
Based on the stacks in MSFT:39994969, it looks like we try to fire off a
`RaiseAutomationEvent`, which calls through UIA core, eventually to the point of
calling `ComPtr<WUX::Automation::Peers::IAutomationPeer>::{dtor}`. I'm guessing
based on the stacks that the TermControl has already been released and cleaned
up. However, the lambda in the `RunAsync` calls here only takes a ref to the
TCAP. The TCAP has an outstanding reference (maybe on the other side of the UIA
fence), and gets successfully resolved as strong, but when calling to
`RaiseAutomationEvent`, the `owner` we passed in is gonezo.

This explicitly passes a `weak_ref` to `TermControlAutomationPeer`, rather than
a raw ptr, so we can actually check if the control is still alive before _we_
dereference it. If it is, great, we've got a strong ref to it now and it won't
get torn down.

Again, this is hearsay. Without a repro, the only way we can confirm this is
gone is by just hoping the crashes go away. 🤞

* Might close #13357 (we'll reopen if it doesn't?)
* narrator still works

### CODE REVIEW

File: src/cascadia/TerminalControl/TermControlAutomationPeer.cpp [hunk 1]
```diff
@@ -134,8 +134,11 @@ namespace winrt::Microsoft::Terminal::Control::implementation
         dispatcher.RunAsync(Windows::UI::Core::CoreDispatcherPriority::Normal, [weakThis{ get_weak() }]() {
             if (auto strongThis{ weakThis.get() })
             {
```
Comment (zadjii-msft) [inline src/cascadia/TerminalControl/TermControlAutomationPeer.cpp:136]: You're gonna want: [whitespace off](https://github.com/microsoft/terminal/pull/13876/files?w=1)

File: src/cascadia/TerminalControl/TermControlAutomationPeer.cpp [hunk 2]
```diff
@@ -67,10 +67,10 @@ static constexpr bool IsReadable(std::wstring_view text)
 
 namespace winrt::Microsoft::Terminal::Control::implementation
 {
-    TermControlAutomationPeer::TermControlAutomationPeer(TermControl* owner,
+    TermControlAutomationPeer::TermControlAutomationPeer(winrt::weak_ref<TermControl> owner,
```
Comment (lhecker) [inline src/cascadia/TerminalControl/TermControlAutomationPeer.cpp:70]: I believe it would be better to pass a strong reference here (`winrt::com_ptr`) and only drop it down to a weak pointer down in `_termControl{ owner }`. I think the `weak_ref` constructor is implicit so it should just work.

File: src/cascadia/TerminalControl/TermControlAutomationPeer.cpp [hunk 3]
```diff
@@ -134,8 +134,11 @@ namespace winrt::Microsoft::Terminal::Control::implementation
         dispatcher.RunAsync(Windows::UI::Core::CoreDispatcherPriority::Normal, [weakThis{ get_weak() }]() {
             if (auto strongThis{ weakThis.get() })
             {
-                // The event that is raised when the text selection is modified.
-                strongThis->RaiseAutomationEvent(AutomationEvents::TextPatternOnTextSelectionChanged);
+                if (auto control{ strongThis->_termControl.get() })
```
Comment (lhecker) [inline src/cascadia/TerminalControl/TermControlAutomationPeer.cpp:137]: Tbh from the PR description alone I haven't understood why we need to hold a strong reference to `control` across the `RaiseAutomationEvent` call. What if `RaiseAutomationEvent` is doing anything asynchronously? In that case holding `control` wouldn't fix anything... 🤔

File: src/cascadia/TerminalControl/TermControl.cpp [hunk 4]
```diff
@@ -707,7 +707,8 @@ namespace winrt::Microsoft::Terminal::Control::implementation
                                              margins.Top,
                                              margins.Right,
                                              margins.Bottom };
-                _automationPeer = winrt::make<implementation::TermControlAutomationPeer>(this, padding, interactivityAutoPeer);
+                auto foo = get_weak();
```
Comment (carlos-zamora) [inline src/cascadia/TerminalControl/TermControl.cpp:710]:
```suggestion
```

**Review by carlos-zamora — APPROVED** [review]
Generally (at least for NVDA), I think the process is that we send an event, then NVDA calls `DocumentRange()` or `GetSelection()` to figure out what changed and cause NVDA to speak. Since the destruction process is the wild west, might be worth adding some `THROW_IF_NULL(_uiaProvider)` or something like that throughout?

Other than that, I think this is worth a shot. It doesn't hurt to check if we're still pointing to a `TermControl` that still exists. Could be that TCAP is lingering around when it should've dtor'd. idk

**Comment by DHowett** [comment]
> Since the destruction process is the wild west, might be worth adding some `THROW_IF_NULL(_uiaProvider)` or something like that throughout?

Won't that turn destruction "whoopsies" into guaranteed crashes of the entire Terminal and all of the tabs it is hosting? Is there a _safer_ way to do this?

**Comment by DHowett** [comment]
I'd prefer @lhecker be the second on this if he's comfortable with it.

File: src/cascadia/TerminalControl/TermControl.cpp (hunk 4 above)
Comment (DHowett) [reply src/cascadia/TerminalControl/TermControl.cpp:710]: yeah we should land this.. :P

File: src/cascadia/TerminalControl/TermControlAutomationPeer.cpp [hunk 5]
```diff
@@ -284,17 +296,27 @@ namespace winrt::Microsoft::Terminal::Control::implementation
...
+        if (auto control{ _termControl.get() })
         {
-            return _termControl->Title();
+            auto profileName = control->GetProfileName();
+            if (profileName.empty())
+            {
+                return control->Title();
+            }
+            else
+                return profileName;
```
Comment (DHowett) [inline src/cascadia/TerminalControl/TermControlAutomationPeer.cpp:307]: we don't use braceless condition bodies in this codebase :)

**Review by DHowett — CHANGES_REQUESTED** [review]

File: src/cascadia/TerminalControl/TermControlAutomationPeer.cpp (hunk 3 above)
Comment (zadjii-msft) [reply src/cascadia/TerminalControl/TermControlAutomationPeer.cpp:137]: Honestly, I'm not entirely sure this'll fix it. Without a solid repro, it was hard for me to figure out how exactly we were getting into this place where a com_ptr was being released, and what exactly the pointer was supposed to be pointing at. This is definitely a "maybe it works, if it doesn't, let's revert and try something else" kinda crash fix.

Comment (zadjii-msft) [reply src/cascadia/TerminalControl/TermControlAutomationPeer.cpp:137]: Regardless, passing in a raw pointer to an impl type has almost certainly got to be wrong.

File: src/cascadia/TerminalControl/TermControlAutomationPeer.cpp [hunk 6]
```diff
@@ -67,10 +67,10 @@ static constexpr bool IsReadable(std::wstring_view text)
 
 namespace winrt::Microsoft::Terminal::Control::implementation
 {
-    TermControlAutomationPeer::TermControlAutomationPeer(TermControl* owner,
+    TermControlAutomationPeer::TermControlAutomationPeer(winrt::com_ptr<TermControl> owner,
                                                          const Core::Padding padding,
                                                          Control::InteractivityAutomationPeer impl) :
-        TermControlAutomationPeerT<TermControlAutomationPeer>(*owner), // pass owner to FrameworkElementAutomationPeer
+        TermControlAutomationPeerT<TermControlAutomationPeer>(*owner.get()), // pass owner to FrameworkElementAutomationPeer
```
Comment (lhecker) [inline src/cascadia/TerminalControl/TermControlAutomationPeer.cpp:73]: `*owner.get()` creates a copy of the underlying `TermControl` class, doesn't it? How does this work? 🤔

**Review by lhecker — APPROVED** [review]
I'm not really in favor of this PR. There shouldn't be situation to begin with were NVDA calls us and the existence of `TermControl` is the make/break of whether WT crashes... As such I'd prefer fixing whatever UIA APIs we have that might crash WT, including any assumptions we have that WinUI won't suddenly call `AppHost::~AppHost` despite being 50 calls deep in the stack.

File: src/cascadia/TerminalControl/TermControlAutomationPeer.cpp (hunk 6 above)
Comment (DHowett) [reply src/cascadia/TerminalControl/TermControlAutomationPeer.cpp:73]: If `owner` is a `com_ptr<ProjectedType>`, it probably just copies the owning pointer.

**Comment by DHowett** [comment]
> I'm not really in favor of this PR.

You don't need to sign off on something you're not in favor of! Should we file a workitem to fix this more soundly? Should we take this as a "stopgap" until we can fix it more soundly?

File: src/cascadia/TerminalControl/TermControlAutomationPeer.cpp (hunk 6 above)
Comment (lhecker) [reply src/cascadia/TerminalControl/TermControlAutomationPeer.cpp:73]: `winrt::com_ptr<T>::get` returns `T*` according to https://docs.microsoft.com/en-us/uwp/cpp-ref-for-winrt/com-ptr#com_ptrget-function
`*owner.get()` should thus be of type `T`, aka `TermControl`. 🤔

Comment (DHowett) [reply src/cascadia/TerminalControl/TermControlAutomationPeer.cpp:73]: Oh, but, this is a silly thing. So.

It returns `T*`, and `*` returns `T&`. `winrt::implements` (which TermControl is eventually derived from) has an implicit conversion to _all projected types that it inherits_. This is an implicit conversion to, I would guess, `Xaml.UIElement` as a projected type. It captures a strong pointer through a `QueryInterface`!

**Comment by lhecker** [comment]
> You don't need to sign off on something you're not in favor of! Should we file a workitem to fix this more soundly? Should we take this as a "stopgap" until we can fix it more soundly?

Maybe I was too terse. 😄 I'm in favor of merging this, just not in favor of this PR because it's a stopgap. I think we should just continue to work on cleaning up our pointer safety and data sharing behavior. Maybe even do it consciously at some point instead of doing it on a case by case basis.
IMO we should remove any use of `this` (including implicit use) if it can be avoided and find and if possible remove implicit recursion like this one were class X calls Y which calls back into X (e.g. introduce class Z which is used by both X and Y, removing the need for recursion).

**Comment by DHowett** [comment]
> Maybe even do it consciously at some point instead of doing it on a case by case basis.
YES

**Comment by zadjii-msft** [comment]
Noted conversation, follow-up in #13896

**Review by DHowett — APPROVED** [review]
