### PR TITLE
AzureConnection: remove our dependency on cpprestsdk

### LINKED ISSUE #4575: Azure Cloud Shell Could not connect to Azure behind Corp Proxy
# Environment

```none
Windows build number: 10.0.18363.0
Windows Terminal version (if applicable): v0.9.433.0

Any other software?
```

# Steps to reproduce

Add a new "Azure Cloud Shell" tab to your terminal instance.

# Expected behavior

A prompt should appear asking to authenticate with Azure.

# Actual behavior

The message "Could not connect to Azure. You may not have internet or the server might be down." appears immediately in the new tab. Fiddler only shows a single outgoing SSL initiation request to login.microsoftonline.com with a 200 response and no followup communication. 

I recently had to update the cacert bundle for the azure cli located in C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\certifi\cacert.pem to include our corp proxy certificate which restored its functionality. Is there something similar here or should the terminal be using the windows store?

### PR DESCRIPTION
**Pull request by DHowett**
This pull request removes, in full, our dependency on cpprestsdk. This
allows us to shed 500KiB-1.2MiB from our package off the top and enables
the following future investments:

- Removal of the App CRT forwarders to save an additional ~500KiB
- Switching over to the HybridCRT and removing our dependency on _any
  CRT_.

cpprest was built on my dev box two or so years ago, and is in _utter_
violation of our compliance guidelines on SBOM et al.

In addition, this change allows us to use the proxy server configured
in Windows Settings.

I did this in four steps (represented roughly by the individual commits):

1. Switch from cpprest's http_client/json to Windows.Web.Http and
   Windows.Data.Json
2. Switch from websocketpp to winhttp.dll's WebSocket implementation¹
3. Remove all remaining utility classes
4. Purge all dependencies from all projects and scripts on cpprest.

I also took this opportunity to add a feature flag that allows Dev
builds to run AzureConnection in-process.

¹ Windows.Networking.Sockets' API is so unergonomic that it was simply
infeasible (and also _horrible_) to use it.

## Validation Steps

I've run the Azure Connection quite a bit inproc.

Closes #4575.
Might be related to #5977, #11714, and with the user agent thing maybe #14403.

### CODE REVIEW

File: src/cascadia/TerminalConnection/AzureConnection.cpp [hunk 1]
```diff
@@ -15,22 +15,24 @@
...
-static constexpr auto HttpUserAgent = L"Terminal/0.0";
+static constexpr std::wstring_view PasswordVaultResourceName = L"Terminal";
+static constexpr std::wstring_view HttpUserAgent = L"Terminal/0.0";
 
 static constexpr int USER_INPUT_COLOR = 93; // yellow - the color of something the user can type
 static constexpr int USER_INFO_COLOR = 97; // white - the color of clarifying information
 
+using namespace winrt::Windows::Foundation;
+namespace WDJ = ::winrt::Windows::Data::Json;
+namespace WSS = ::winrt::Windows::Storage::Streams;
```
Comment (DHowett) [inline src/cascadia/TerminalConnection/AzureConnection.cpp:33]: remove, unused

File: src/cascadia/TerminalConnection/AzureConnection.cpp [hunk 2]
```diff
@@ -287,44 +291,46 @@ namespace winrt::Microsoft::Terminal::TerminalConnection::implementation
     // - tenant - the unparsed tenant
     // Return value:
     // - a tuple containing the ID and display name of the tenant.
-    static Tenant _crackTenant(const json::value& jsonTenant)
+    static Tenant _crackTenant(const WDJ::IJsonValue& value)
     {
+        auto jsonTenant{ value.GetObjectW() };
```
Comment (DHowett) [inline src/cascadia/TerminalConnection/AzureConnection.cpp:296]: Yeah, `W`. APIs are hard.

File: src/cascadia/TerminalConnection/AzureConnection.cpp [hunk 3]
```diff
@@ -449,25 +462,29 @@ namespace winrt::Microsoft::Terminal::TerminalConnection::implementation
...
-            if (!credentialVersion.has_value() || credentialVersion.value() != CurrentCredentialVersion)
-            {
-                // ignore credentials that aren't from the latest credential revision
-                vault.Remove(entry);
-                oldVersionEncountered = true;
-                continue;
-            }
+                if (!credentialVersion.has_value() || credentialVersion.value() != CurrentCredentialVersion)
+                {
+                    // ignore credentials that aren't from the latest credential revision
```
Comment (DHowett) [inline src/cascadia/TerminalConnection/AzureConnection.cpp:476]: I could just solve the duplication TODO by bumping the version. How do y'all feel about that?

File: src/cascadia/TerminalConnection/AzureConnection.cpp [hunk 4]
```diff
@@ -889,99 +921,91 @@ namespace winrt::Microsoft::Terminal::TerminalConnection::implementation
...
+        auto uri{ fmt::format(L"{}providers/Microsoft.Portal/consoles/default?api-version=2020-04-01-preview", _resourceUri) };
 
-        // Initialize request
-        http_request shellRequest(L"PUT");
-        shellRequest.set_request_uri(L"providers/Microsoft.Portal/consoles/default?api-version=2018-10-01");
-        // { "properties": { "osType": "linux" } }
-        auto body = json::value::object({ { U("properties"), json::value::object({ { U("osType"), json::value::string(U("linux")) } }) } });
-        shellRequest.set_body(body);
+        WWH::HttpStringContent content{
+            LR"-({"properties": {"osType": "linux"}})-",
```
Comment (DHowett) [inline src/cascadia/TerminalConnection/AzureConnection.cpp:960]: I know. We were constructing this like a real JSON object. It just feels... wasteful.

File: src/cascadia/TerminalConnection/AzureConnection.cpp (hunk 1 above)
Comment (DHowett) [reply src/cascadia/TerminalConnection/AzureConnection.cpp:33]: not actually unused

File: src/cascadia/TerminalConnection/AzureConnection.cpp (hunk 3 above)
Comment (DHowett) [reply src/cascadia/TerminalConnection/AzureConnection.cpp:476]: Chose to do it. This invalidates all old credentials.

File: src/cascadia/TerminalConnection/AzureConnection.cpp [hunk 5]
```diff
@@ -15,22 +15,24 @@
...
-using namespace web::http::client;
-using namespace web::websockets::client;
 using namespace winrt::Windows::Security::Credentials;
 
-static constexpr int CurrentCredentialVersion = 1;
-static constexpr auto PasswordVaultResourceName = L"Terminal";
-static constexpr auto HttpUserAgent = L"Terminal/0.0";
+static constexpr int CurrentCredentialVersion = 2;
+static constexpr std::wstring_view PasswordVaultResourceName = L"Terminal";
+static constexpr std::wstring_view HttpUserAgent = L"Mozilla/5.0 (Windows NT 10.0) Terminal/1.0";
```
Comment (lhecker) [inline src/cascadia/TerminalConnection/AzureConnection.cpp:26]: image

File: src/cascadia/TerminalConnection/AzureConnection.cpp [hunk 6]
```diff
@@ -115,6 +117,8 @@ namespace winrt::Microsoft::Terminal::TerminalConnection::implementation
     // - creates the output thread (where we will do the authentication and actually connect to Azure)
     void AzureConnection::Start()
     {
+        _httpClient = winrt::Windows::Web::Http::HttpClient{};
+        _httpClient.DefaultRequestHeaders().UserAgent().TryParseAdd(HttpUserAgent);
```
Comment (lhecker) [inline src/cascadia/TerminalConnection/AzureConnection.cpp:121]: What happens if you leave this empty? Does it get a default user-agent?

File: src/cascadia/TerminalConnection/AzureConnection.cpp [hunk 7]
```diff
@@ -264,7 +265,10 @@ namespace winrt::Microsoft::Terminal::TerminalConnection::implementation
             if (_state == AzureState::TermConnected)
             {
                 // Close the websocket connection
-                _cloudShellSocket.close();
+                std::ignore = WinHttpWebSocketClose(_webSocket.get(), WINHTTP_WEB_SOCKET_SUCCESS_CLOSE_STATUS, nullptr, 0); // throw away the error
```
Comment (lhecker) [inline src/cascadia/TerminalConnection/AzureConnection.cpp:268]: Why not log it?

File: src/cascadia/TerminalConnection/AzureConnection.h [hunk 8]
```diff
@@ -56,30 +53,30 @@ namespace winrt::Microsoft::Terminal::TerminalConnection::implementation
         void _RunStoreState();
         void _RunConnectState();
 
-        const utility::string_t _loginUri{ U("https://login.microsoftonline.com/") };
-        const utility::string_t _resourceUri{ U("https://management.azure.com/") };
-        const utility::string_t _wantedResource{ U("https://management.core.windows.net/") };
+        const std::wstring_view _loginUri{ L"https://login.microsoftonline.com/" };
+        const std::wstring_view _resourceUri{ L"https://management.azure.com/" };
+        const std::wstring_view _wantedResource{ L"https://management.core.windows.net/" };
```
Comment (lhecker) [inline src/cascadia/TerminalConnection/AzureConnection.h:58]: Why are these members and not `static constexpr`?

File: src/cascadia/TerminalConnection/AzureConnection.h [hunk 9]
```diff
@@ -95,9 +92,16 @@ namespace winrt::Microsoft::Terminal::TerminalConnection::implementation
...
-        web::websockets::client::websocket_client _cloudShellSocket;
+        winrt::Windows::Web::Http::HttpClient _httpClient{ nullptr };
+        wil::unique_winhttp_hinternet _socketSessionHandle{};
+        wil::unique_winhttp_hinternet _socketConnectionHandle{};
+        wil::unique_winhttp_hinternet _webSocket{};
 
-        static std::optional<utility::string_t> _ParsePreferredShellType(const web::json::value& settingsResponse);
+        til::u8state _u8State{};
+        std::wstring _u16Str{};
+        std::array<char, 4096> _buffer{};
```
Comment (lhecker) [inline src/cascadia/TerminalConnection/AzureConnection.h:102]: I'd remove the `{}`. No need to eagerly initialize 4kB IMO. The other members above technically don't need the `{}` either, but that's more of a matter of taste (I forgot the proper idiom in tech).

File: src/cascadia/TerminalConnection/AzureConnection.cpp [hunk 10]
```diff
@@ -696,19 +713,18 @@ namespace winrt::Microsoft::Terminal::TerminalConnection::implementation
...
+            if (userSettings.HasKey(L"preferredShellType"))
             {
-                const auto preferredShellTypeValue = userSettings.at(L"preferredShellType");
-                return preferredShellTypeValue.as_string();
+                return userSettings.GetNamedString(L"preferredShellType");
             }
         }
 
-        return std::nullopt;
+        return winrt::hstring{};
```
Comment (lhecker) [inline src/cascadia/TerminalConnection/AzureConnection.cpp:727]: Wouldn't it make sense to just return "pwsh" here?

**Review by lhecker — APPROVED** [review]
I would prefer if all those `gsl::narrow_cast` were `gsl::narrow`, since it's unlikely to exceed 4GiB in practice anyways, but adds some welcome early "uh oh something's wrong here" warnings.

**Comment by DHowett** [comment]
1. `gsl::narrow` -> done

File: src/cascadia/TerminalConnection/AzureConnection.cpp (hunk 6 above)
Comment (DHowett) [reply src/cascadia/TerminalConnection/AzureConnection.cpp:121]: Testing

File: src/cascadia/TerminalConnection/AzureConnection.cpp (hunk 5 above)
Comment (DHowett) [reply src/cascadia/TerminalConnection/AzureConnection.cpp:26]: YOU'RE NOT WRONG

File: src/cascadia/TerminalConnection/AzureConnection.cpp (hunk 7 above)
Comment (DHowett) [reply src/cascadia/TerminalConnection/AzureConnection.cpp:268]: Nothing useful to learn. We're going down and releasing all the resources either way. If it doesn't close, well, that sucks, but winhttp gets to deal with it when we call CloseHandle

File: src/cascadia/TerminalConnection/AzureConnection.h (hunk 8 above)
Comment (DHowett) [reply src/cascadia/TerminalConnection/AzureConnection.h:58]: I'll change it to (1) static constexpr for the default values but (2) local wstring_views that point at those -- because eventually _we will change all 3 of thee depending on which azure cloud you are using_

File: src/cascadia/TerminalConnection/AzureConnection.h (hunk 9 above)
Comment (DHowett) [reply src/cascadia/TerminalConnection/AzureConnection.h:102]: Fair. I'll drop all 3. ConptyConnection uses this as well, which is where I copied it from

File: src/cascadia/TerminalConnection/AzureConnection.cpp (hunk 10 above)
Comment (DHowett) [reply src/cascadia/TerminalConnection/AzureConnection.cpp:727]: Done&done, good idea

File: src/cascadia/TerminalConnection/AzureConnection.cpp (hunk 6 above)
Comment (DHowett) [reply src/cascadia/TerminalConnection/AzureConnection.cpp:121]: there is NO user agent

File: src/cascadia/TerminalConnection/AzureConnection.h (hunk 9 above)
Comment (DHowett) [reply src/cascadia/TerminalConnection/AzureConnection.h]: I trusted youuuuuuuuuuuuuuuuuuu

         C:\a\_work\1\s\src\inc\til\u8u16convert.h(37): error C26495: Variable 'til::u8state::partials' is uninitialized. Always initialize a member variable (type.6). [C:\a\_work\1\s\src\cascadia\TerminalConnection\TerminalConnection.vcxproj]
         C:\a\_work\1\s\src\cascadia\TerminalConnection\AzureConnection.h(21): error C26495: Variable 'winrt::Microsoft::Terminal::TerminalConnection::implementation::AzureConnection::_buffer' is uninitialized. Always initialize a member variable (type.6). [C:\a\_work\1\s\src\cascadia\TerminalConnection\TerminalConnection.vcxproj]

File: src/cascadia/TerminalConnection/AzureConnection.cpp [hunk 11]
```diff
@@ -730,14 +746,38 @@ namespace winrt::Microsoft::Terminal::TerminalConnection::implementation
         _WriteStringWithNewline(RS_(L"AzureSuccess"));
 
         // Request for a terminal for said cloud shell
-        const auto shellType = _ParsePreferredShellType(settingsResponse);
+        auto shellType = _ParsePreferredShellType(settingsResponse);
```
Comment (PankajBhojwani) [inline src/cascadia/TerminalConnection/AzureConnection.cpp:749]: any reason we removed the `const` here?

File: src/cascadia/TerminalConnection/AzureConnection.cpp [hunk 12]
```diff
@@ -730,14 +746,38 @@ namespace winrt::Microsoft::Terminal::TerminalConnection::implementation
...
+            THROW_IF_WIN32_BOOL_FALSE(WinHttpSendRequest(requestHandle.get(), WINHTTP_NO_ADDITIONAL_HEADERS, 0, nullptr, 0, 0, 0));
+            THROW_IF_WIN32_BOOL_FALSE(WinHttpReceiveResponse(requestHandle.get(), nullptr));
+
+            socketHandle.reset(WinHttpWebSocketCompleteUpgrade(requestHandle.get(), 0));
+            THROW_LAST_ERROR_IF(!socketHandle);
+
+            requestHandle.reset(); // We no longer need the request once we've upgraded it.
+            // We have to keep the socket session and connection handles.
+            _socketSessionHandle = std::move(sessionHandle);
+            _socketConnectionHandle = std::move(connectionHandle);
```
Comment (PankajBhojwani) [inline src/cascadia/TerminalConnection/AzureConnection.cpp:778]: Why do we need to keep `_socketSessionHandle` and `_socketConnectionHandle`?

File: src/cascadia/TerminalConnection/AzureConnection.cpp [hunk 13]
```diff
@@ -756,54 +796,47 @@ namespace winrt::Microsoft::Terminal::TerminalConnection::implementation
     // - a http_request for the client to send
```
Comment (carlos-zamora) [inline src/cascadia/TerminalConnection/AzureConnection.cpp:796]: nit: add third arg to docs

File: src/cascadia/TerminalConnection/AzureConnection.cpp [hunk 14]
```diff
@@ -756,54 +796,47 @@ namespace winrt::Microsoft::Terminal::TerminalConnection::implementation
...
+
+        WWH::HttpRequestMessage request{ method, Uri{ uri } };
+        request.Content(content);
+
+        auto headers{ request.Headers() };
+        headers.Accept().TryParseAdd(L"application/json");
+
+        auto response{ _httpClient.SendRequestAsync(request).get() };
+        auto string{ response.Content().ReadAsStringAsync().get() };
+        auto jsonResult{ WDJ::JsonObject::Parse(string) };
```
Comment (carlos-zamora) [inline src/cascadia/TerminalConnection/AzureConnection.cpp:814]: const

probably on some of the other ones too

**Review by carlos-zamora — APPROVED** [review]

File: src/cascadia/TerminalConnection/AzureConnection.cpp (hunk 12 above)
Comment (DHowett) [reply src/cascadia/TerminalConnection/AzureConnection.cpp:778]: It's part of the winhttp contract. :)

File: src/cascadia/TerminalConnection/AzureConnection.cpp (hunk 11 above)
Comment (DHowett) [reply src/cascadia/TerminalConnection/AzureConnection.cpp:749]: nope. leftover from old code.

File: src/cascadia/TerminalConnection/AzureConnection.cpp (hunk 14 above)
Comment (DHowett) [reply src/cascadia/TerminalConnection/AzureConnection.cpp:814]: const doesn't mean anything to winrt classes, fwiw, but you're right.

File: src/cascadia/TerminalConnection/AzureConnection.cpp (hunk 5 above)
Comment (DHowett) [reply src/cascadia/TerminalConnection/AzureConnection.cpp:26]: Heh. If there is, it almost certainly requires us to move off of device code based authentication... which is work I've got booked for "some time after March".
