### PR TITLE
Delete the keybinding for NewTabProfile9 and SwitchToTab9

### LINKED ISSUE #826: Keyboard shortcut for 10th profile doesn't work
When you have more than 10 profiles, using the key shortcut CTRL+SHIFT+0 to launch the 10th profile doesn't work.  No-op.

Repro:
Load profiles.json
Copy one profile and paste it 11 more times (changing GUID)
Save profiles.json
Iterate through profile launching using CTRL+SHIFT+1 , 2, 3, etc. but when get to 0 it fails and doesn't launch that profile.

### PR DESCRIPTION
**Pull request by mKay00**
## Summary of the Pull Request
I deleted the keybinding for NewTabProfile0, because the keybinding doesn't work.

## References
#826

## PR Checklist
* [x] Closes #826 
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Requires documentation to be updated
* [x] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #826

## Detailed Description of the Pull Request / Additional comments
The keyboard shortcut <kbd>CTRL+SHIFT+0</kbd> is handled by something else (probably the input method editor: https://support.microsoft.com/en-us/help/967893/input-method-editor-keyboard-shortcut-ctrl-shift-0-switches-the-input) and can't be used. Discussion about this issue is in #826

### CODE REVIEW

**Comment by zadjii-msft** [comment]
I'm inclined to agree - probably just remove the default binding. In a hypothetical future PR, we'll pass args to the ShortcutAction instead of just having 10 OpenNewTabWitProfileN events, but lets just leave it for now.

You're also fine not adding a test for this quite yet, since we don't have TerminalApp tests set up yet.

**Comment by mKay00** [comment]
Makes sense. But why don't we use <kbd>Ctrl+0-9</kbd> instead? Then all shortcuts work correctly.

**Comment by zadjii-msft** [comment]
I kinda figured that the chances an app used Ctrl+0-9 was way higher than Ctrl+Shift+0-9.

**Comment by mKay00** [comment]
Okay, then I just unbind it.

File: src/cascadia/TerminalApp/CascadiaSettings.cpp [hunk 1]
```diff
@@ -279,8 +279,7 @@ void CascadiaSettings::_CreateDefaultKeybindings()
                               KeyChord{ KeyModifiers::Ctrl | KeyModifiers::Shift,
                                         static_cast<int>('9') });
     keyBindings.SetKeyBinding(ShortcutAction::NewTabProfile9,
-                              KeyChord{ KeyModifiers::Ctrl | KeyModifiers::Shift,
-                                        static_cast<int>('0') });
+                              KeyChord{ /* unbound, because CTRL + SHIFT + 0 is a system shortcut */ });
```
Comment (zadjii-msft) [inline src/cascadia/TerminalApp/CascadiaSettings.cpp]: I'd maybe just remove the entire `SetKeyBinding` call here, I'm not sure what binding an action to vkey=0 would do.

Comment (zadjii-msft) [reply src/cascadia/TerminalApp/CascadiaSettings.cpp]: (but leave the comment that ShortcutAction::NewTabProfile9 is unbound, because CTRL + SHIFT + 0 is a system shortcut

**Comment by timheuer** [comment]
My two cents...this feels like splitting hairs here.  From a UX perspective you are now leaving 10th profile unbound, so why not 11th-15th tab?  I think the initial goal was a reasonable 1-10 using known/predictable number values...but now since the 10th can't reliably be mapped to the global default, we're going to keep an unbound one in treating the 10th tab as special, but tab 11 is now writing you a sad letter wondering why it isn't important ;-).

I'm coming from an approach of simplifying the code maintenance, the user profile options, and the realistic liklihood that not having a 10th-n shortcut is a high use case.  Of course if you have customer data supporting the opposite of this approach, that should trump any comment I have here...but opposite of data-driven decision, this feels like leaving code in just to keep the list to an even 10...and weirdly leaving out 11-n to have any same capability.  Basically you're stating the bound for this feature is 10...I'm just saying simplify and make the bound 9...let customer-driven data/feedback alter the course in the future.

**Comment by mKay00** [comment]
I am with tim on this one. Make default 1-9 (maybe even with tab switching Alt+1-9) and maybe in a future PR when it is an argument passing, everybody can use as many profiles with whatever keybinding he wants?
I'll wait a little bit for the opinions of @zadjii-msft and @DHowett and then I'll do what they decide.

**Comment by zadjii-msft** [comment]
Well, I've certainly been convinced. There doesn't seem to be much marginal utility in leaving the 10th NewTab and SwitchToTab options, and when we support custom args in the keybindings, this won't even be an issue anymore.

**Comment by DHowett-MSFT** [comment]
Oh yeah. Totally convinced! Let’s yank the whole binding.

**Comment by mKay00** [comment]
Alright, I've deleted both NewTabProfile9 and SwitchToTabProfile9.
