### PR TITLE
Fix text scaling issues in settings UI

### LINKED ISSUE #12006: [Settings> Actions]: At 200% resize Text, Shortcut keys (Ctrl+numpad_minus & Ctrl+numpad_plus) are not fully visible inside Actions page.
### Windows Terminal version

1.12.3472.0

### Windows build number

10.0.22504.1010

### Other Software

Test Environment:
OS: Windows 11 Version Dev (OS Build 22504.1010)
App: Windows Terminal Preview
Screen Reader: Narrator
Tool: Accessibility Insights for Windows Version 1.1.1741.1

### Steps to reproduce

**Pre-requisites:**
1. Navigate to Settings>System> Dispaly.
2. Then Set Display Rsolution to 1280 x 768 and Scale at 100%.
3. Then Navigate to Settings>Accessibility>Text Size
4. Apply 200% text resize. 

**Repro Steps:**
1. Open Windows Terminal.
2. Open Settings page using 'Ctr+,'.
3. Then navigate inside Actions page and observe the issue.

**User Experience:**
Low vision users UX will not able good if they are not able to see the full text.

**Guideline Reference:**
https://www.w3.org/WAI/WCAG21/Understanding/resize-text

**Attachments:**
[At 200 resize Text, Shortcut keys are not fully visible inside Actions page..zip](https://github.com/microsoft/terminal/files/7750395/At.200.resize.Text.Shortcut.keys.are.not.fully.visible.inside.Actions.page.zip)

### Expected Behavior

At 200% resize Text, Shortcut keys (Ctrl+numpad_minus & Ctrl+numpad_plus) should be fully visible inside Actions page.

### Actual Behavior

At 200% resize Text, Shortcut keys (Ctrl+numpad_minus & Ctrl+numpad_plus) are not fully visible inside Actions page. User is only able to see 'Ctrl+numpad_mi' & 'Ctrl+numpad_pl'.

**Observation:** User can see full shortcut text in Shortcut editable mode.

### LINKED ISSUE #17897: [Windows Terminal - Settings - Color Schemes]: 'Add new' button's text is getting truncated and not visible properly at 200% text scaling.
### Windows Terminal version

1.22.2362.0

### Windows build number

27695.1000

### Other Software

**Test Environment:**
OS: Windows 11 Version Dev (OS Build 27695.1000)
App: Windows Terminal Preview

### Steps to reproduce

**Pre-requisite:**
Settings>Display>Display Resolution (1680*1050)>set scaling to 100%>Increase the text slider to 200% >Apply>Reopen the application.

**Repro steps:**
1. Open the 'windows terminal' application.
2. Follow the above-mentioned pre-requisite step.
3. Now open 'Settings'.
4. Navigate to the 'Color Schemes' tab and activate it.
5. Navigate to the 'Add new' button. 
6. Observe the issue.

**User experience:**
Users with low vision rely on zooming features for navigation will feel difficulty in understanding the button's name, if name gets truncated at 200% zoom.

**WCAG Reference Link:**
https://www.w3.org/WAI/WCAG21/Understanding/resize-text

**Attachment:**
[MAS1.4.4 - Add new button's text is not visble properly at 200% text scaling.zip](https://github.com/user-attachments/files/16958099/MAS1.4.4.-.Add.new.button.s.text.is.not.visble.properly.at.200.text.scaling.zip)

### Expected Behavior

'Add new' button's text should be properly visible at 200% text scaling.

### Actual Behavior

'Add new' button's text is getting truncated and not visible properly at 200% text scaling.

**Note:**
Same issue repro for 'Foreground colors' & 'Set as default' button. (Navigation Path: Windows Terminal> Settings> Color schemes> Add new> 'Foreground colors' & 'Set as default button').

### LINKED ISSUE #17898: [Windows Terminal - Settings - Color schemes]: 'Are you sure you want to delete this color scheme' text is getting truncated from 'Delete' dialog at 200% text scaling
### Windows Terminal version

1.22.2362.0

### Windows build number

27695.1000

### Other Software

**Test Environment:**
OS: Windows 11 Version Dev (OS Build 27695.1000)
App: Windows Terminal Preview

### Steps to reproduce

**Pre-requisite:**
Settings>Display>Display Resolution (1680*1050)>set scaling to 100%>Increase the text slider to 200% >Apply>Reopen the application.

**Repro steps:**
1. Open the 'windows terminal' application.
2. Follow the above-mentioned pre-requisite step.
3. Now expand the dropdown control.
4. Navigate to any application and open it.
5. Observe the issue.

**User experience:**
Users with low vision rely on zooming features for navigation will feel difficulty in understanding the tab name, if name gets truncated at 200% zoom.

**WCAG Reference Link:**
https://www.w3.org/WAI/WCAG21/Understanding/resize-text

**Attachment:**
[MAS1.4.4 - Are you sure you want to delete this color scheme text is getting truncated from delete dialog at 200% text scaling.zip](https://github.com/user-attachments/files/16958173/MAS1.4.4.-.Are.you.sure.you.want.to.delete.this.color.scheme.text.is.getting.truncated.from.delete.dialog.at.200.text.scaling.zip)

### Expected Behavior

'Are you sure you want to delete this color scheme' text should not get truncated and should be properly visible at 200% text scaling.

### Actual Behavior

'Are you sure you want to delete this color scheme' text is getting truncated from 'Delete' dialog at 200% text scaling.

**Note:**
Same issue repro for all 'Delete' dialogs throughout.

### PR DESCRIPTION
**Pull request by carlos-zamora**
## Summary of the Pull Request
Fixes some issues with truncated text in the settings UI when 200% text scaling is applied.

For #17897, a minimum height was applied instead of a plain "height". This ensures that the desired height is applied in general, but under 200% text scaling, we are allowed to grow past that, thus preventing the truncation of the text.

For #17898, flyouts have a scroll viewer inside them by default. We actually don't want the scroll viewer because that means the text will appear "truncated" when in reality, the user is expected to notice the small scrollbar and scroll horizontally (why that's the default, I will never know). This PR introduces a new style that can be applied to these flyouts to cause text wrapping instead of horizontal scrolling. Looked through the app for any instances where this happens.

For #12006, simply changing the column width from a static value to "auto" fixes the issue. Frankly, we care more about the text appearing as a whole (and as whole words). The name of the actions wrap properly anyways.

Closes #17897
Closes #17898
Closes #12006

### CODE REVIEW

**Comment by carlos-zamora** [comment]
## Color Schemes > Add New button truncated fix (#17897)
color schemes add new button no longer truncated

## Color Schemes > Delete flyout fix (#17898)
color schemes delete button flyout with wrapped text

## Actions > miscellaneous flyout fixes (similar to #17898)
actions page accept button flyout with wrapped text

actions page delete button flyout with wrapped text

## Actions > `ctrl+numpad_minus` keychord fix (#12006)
actions page keychord no longer truncated

File: src/cascadia/TerminalSettingsEditor/ActionsViewModel.cpp [hunk 1]
```diff
@@ -289,14 +289,17 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
...
 
                 const auto conflictingCmdName{ conflictingCmd.Name() };
                 TextBlock conflictingCommandNameTB{};
                 conflictingCommandNameTB.Text(fmt::format(L"\"{}\"", conflictingCmdName.empty() ? RS_(L"Actions_UnnamedCommandName") : conflictingCmdName));
                 conflictingCommandNameTB.FontStyle(Windows::UI::Text::FontStyle::Italic);
+                conflictingCommandNameTB.TextWrapping(TextWrapping::WrapWholeWords);
 
                 TextBlock confirmationQuestionTB{};
                 confirmationQuestionTB.Text(RS_(L"Actions_RenameConflictConfirmationQuestion"));
+                confirmationQuestionTB.TextWrapping(TextWrapping::WrapWholeWords);
```
Comment (lhecker) [inline src/cascadia/TerminalSettingsEditor/ActionsViewModel.cpp:302]: The documentation makes it seem like `WrapWholeWords` will not wrap very long words with no break opportunity like `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa`. I think we may have to use `Wrap` instead.

Comment (carlos-zamora) [reply src/cascadia/TerminalSettingsEditor/ActionsViewModel.cpp]: Urgh, yeah, just tested it and you're right. It looks like when it's set to `wrap`, it tries to wrap whole words, if possible. Changed it!

**Review by DHowett — APPROVED** [review]

**Review by lhecker — APPROVED** [review]
