### PR TITLE
Default initialize a CmdPal mode

### LINKED ISSUE #7254: Command palette no longer shows "no matching commands"
This is a likely regression from #6732 

image

### PR DESCRIPTION
**Pull request by leonMSFT**
Whoops, members are zero initialized in Debug builds but most likely not
in Release builds So, this PR adds a couple of default values to
`_currentMode` and its associated XAML strings to make cmdpal/ats work
deterministically on first use.  I also added a default value to
`_anchorKey` just to be safe.

Closes #7254

### CODE REVIEW

File: src/cascadia/TerminalApp/CommandPalette.cpp [hunk 1]
```diff
@@ -22,14 +22,21 @@ using namespace winrt::Windows::Foundation::Collections;
 namespace winrt::TerminalApp::implementation
 {
     CommandPalette::CommandPalette() :
-        _switcherStartIdx{ 0 }
+        _switcherStartIdx{ 0 },
+        _anchorKey{ VirtualKey::None }
```
Comment (DHowett) [inline src/cascadia/TerminalApp/CommandPalette.cpp:26]:
```suggestion
        _anchorKey{ VirtualKey::None },
        _currentMode { CommandPaletteMode::ActionMode }
```

File: src/cascadia/TerminalApp/CommandPalette.cpp [hunk 2]
```diff
@@ -22,14 +22,21 @@ using namespace winrt::Windows::Foundation::Collections;
...
     {
         InitializeComponent();
 
         _filteredActions = winrt::single_threaded_observable_vector<winrt::TerminalApp::Command>();
         _allCommands = winrt::single_threaded_vector<winrt::TerminalApp::Command>();
         _allTabActions = winrt::single_threaded_vector<winrt::TerminalApp::Command>();
 
+        // GH#7254 - default initialize a mode
+        _currentMode = CommandPaletteMode::ActionMode;
```
Comment (DHowett) [inline src/cascadia/TerminalApp/CommandPalette.cpp:35]:
```suggestion
```

**Comment by leonMSFT** [comment]
Oh absolutely, I should've been using `_switchToMode` actually!

**Comment by DHowett** [comment]
@msftbot merge this in 5 minutes
