### PR TITLE
Fix font size rounding in the settings UI

### LINKED ISSUE #14024: Odd behavior when using fractional font size in SUI
### Windows Terminal version

main c51bb3a7a

### Windows build number

10.0.19044.0

### Other Software

_No response_

### Steps to reproduce

build terminal with `Add support for fractional font size` commit included

### Expected Behavior

consistent fractional part

### Actual Behavior

when using any other fractional beside `.5` the font size is being expanded to 10 decimal places, overlapping the controls:

fractional_font_size

when incrementing/decrementing with the up/down arrows only the integer part is being changed, i.e. `13.5 , 14.5, 15.5`

### PR DESCRIPTION
**Pull request by lhecker**
This fixes an issue with c51bb3a, where some fractional font
sizes are displayed as something like 13.600000000001.

Closes #14024

## Validation Steps Performed
* Enter a font size of 13.6 and save
* NumberBox displays "13.6" ✅

### CODE REVIEW

File: src/cascadia/TerminalSettingsEditor/Appearances.cpp [hunk 1]
```diff
@@ -91,6 +91,16 @@ namespace winrt::Microsoft::Terminal::Settings::Editor::implementation
...
         InitializeComponent();
 
+        {
+            using namespace winrt::Windows::Globalization::NumberFormatting;
+            // > .NET rounds to 12 significant digits when displaying doubles, so we will [...]
+            // ...obviously not do that, because this is an UI element for humans. This prevents
+            // issues when displaying 32-bit floats, because WinUI is unaware about their existence.
+            SignificantDigitsNumberRounder rounder;
+            rounder.SignificantDigits(6);
+            _fontSizeBox().NumberFormatter().as<DecimalFormatter>().NumberRounder(rounder);
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/Appearances.cpp:101]: yikes. This is an implementation detail, but i no longer care :D

Comment (DHowett) [reply src/cascadia/TerminalSettingsEditor/Appearances.cpp:101]: can you `//BODGY` this?

**Review by DHowett — APPROVED** [review]

**Review by DHowett — APPROVED** [review]

**Review by DHowett — APPROVED** [review]
