### PR TITLE
Fix wrapped lines in `less` in Git for Windows

### LINKED ISSUE #5691: "git log --pretty=oneline" at the bottom of the buffer line-wraps wrong
The pager prints one screen-width of line, then enters deferred EOL mode, then prints more. When we were in the `newBottomLine` state (or whatever it is now), we fail to re-wrap it properly.

image

### PR DESCRIPTION
**Pull request by zadjii-msft**
## Summary of the Pull Request

This PR resolves an issue with the Git for Windows (MSYS) version of `less`. It _doesn't_ use VT processing for emitting text tothe buffer, so when it hits `WriteCharsLegacy`, `WC_DELAY_EOL_WRAP` is NOT set.

When this happens, `less` is writing some text that's longer than the width of the buffer to the last line of the buffer. We're hitting the 
```c++
    Status = AdjustCursorPosition(screenInfo, CursorPosition, WI_IsFlagSet(dwFlags, WC_KEEP_CURSOR_VISIBLE), psScrollY);
```
call in `_stream.cpp:560`.

The cursor is _currently_ at `{40, 29}`, the _start_ of the run of text that wrapped. We're trying to adjust it to `{0, 30}`, which would be the start of the next line of the buffer. However, the buffer is only 30 lines tall, so we've got to `IncrementCircularBuffer` first, so we can move the cursor there.

When that happens, we're going to paint frame. At the end of that frame, we're going to try and paint the cursor position. The cursor is still at `{40, 29}` here, so unfortunately, the `cursorIsInDeferredWrap` check in `XtermEngine::PaintCursor` is `false`. That means, conpty is going to try to move the cursor to where the console thinks the cursor actually is at the end of this frame, which is `{40, 29}`.

If we're painting the frame because we circled the buffer, then the cursor might still be in the position it was before the text was written to the buffer to cause the buffer to circle. In that case, then we DON'T want to paint the cursor here either, because it'll cause us to manually break this line. That's okay though, the frame will be painted again, after the circling is complete.

## PR Checklist
* [x] Closes #5691
* [x] I work here
* [x] Tests added/passed
* [n/a] Requires documentation to be updated

## Detailed Description of the Pull Request / Additional comments

I suppose that's the detailed description above

## Validation Steps Performed
* ran tests
* checked that the bug was actually fixed in the Terminal

### CODE REVIEW

File: src/renderer/vt/XtermEngine.cpp [hunk 1]
```diff
@@ -234,10 +234,17 @@ XtermEngine::XtermEngine(_In_ wil::unique_hfile hPipe,
...
+    //        before the text was written to the buffer to cause the buffer to
+    //        circle. In that case, then we DON'T want to paint the cursor here
+    //        either, because it'll cause us to manually break this line. That's
+    //        okay though, the frame will be painted again, after the circling
+    //        is complete.
     //   * _delayedEolWrap && _wrappedRow.has_value(): We think we've deferred
     //     the wrap of a line.
     // If they're all true, DON'T manually paint the cursor this frame.
-    if (!(cursorIsInDeferredWrap && _delayedEolWrap && _wrappedRow.has_value()))
+    if (!((cursorIsInDeferredWrap || _circled) && _delayedEolWrap && _wrappedRow.has_value()))
```
Comment (DHowett-MSFT) [inline src/renderer/vt/XtermEngine.cpp:247]: horrifying.

**Comment by carlos-zamora** [comment]
small changes like this freak me out, so I'mma hope @miniksa can take a look at it

File: src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp [hunk 2]
```diff
@@ -213,6 +215,9 @@ class TerminalCoreUnitTests::ConptyRoundtripTests final
 
     TEST_METHOD(NewLinesAtBottomWithBackground);
 
+    TEST_METHOD(WrapNewLineAtBottom);
+    TEST_METHOD(WrapNewLineAtBottomLikeMSYS);
```
Comment (miniksa) [inline src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp:219]: I just want to reiterate how happy I am that we're building tests like this that simulate our client applications and verify the desired behavior through the PTY.

File: src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp [hunk 3]
```diff
@@ -2975,3 +2980,368 @@ void ConptyRoundtripTests::NewLinesAtBottomWithBackground()
...
+            writeCharsLegacyHelper(charsInSecondLine);
+        }
+
+        if (paintEachNewline == PaintEveryLine ||
+            paintEachNewline == PaintAfterBothLines)
+        {
+            VERIFY_SUCCEEDED(renderer.PaintFrame());
+        }
+    }
+
```
Comment (miniksa) [inline src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp:3106]: Please add more comments explaining this. Whomever debugs this test in the future is going to have to decode the VT sequences as well as try to reason out why these modes have different behaviors. Leave as many breadcrumbs as you can.

File: src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp [hunk 4]
```diff
@@ -2975,3 +2980,368 @@ void ConptyRoundtripTests::NewLinesAtBottomWithBackground()
...
+    auto verifyBuffer = [&](const TextBuffer& tb, const til::rectangle viewport) {
+        const auto width = viewport.width<short>();
+        const auto isTerminal = viewport.top() != 0;
+
+        for (short row = 0; row < viewport.bottom<short>(); row++)
+        {
+            Log::Comment(NoThrowString().Format(L"Checking row %d", row));
+
+            const auto isWrapped = (row % 2) == 0;
```
Comment (miniksa) [inline src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp:3115]: Add comment reminding why odd/even affects wrap (shared test buffer state?)

File: src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp [hunk 5]
```diff
@@ -2975,3 +2980,368 @@ void ConptyRoundtripTests::NewLinesAtBottomWithBackground()
...
+    // Each of the lines of text in the buffer will look like the following:
+    //
+    // Line 1 chars: ~~~~~~~~~~~~~~~~~~ <wrap>
+    // Line 1 attrs: YYYYYYYDDDDDDDDDDD (First 30 are yellow FG, then default attrs)
+    // Line 2 chars: ~~~~~~~~~~________ <break> (there are width/2 '~'s here)
+    // Line 2 attrs: DDDDDDDDDDDDDDDDDD (all are default attrs)
+    //
+    // The last line of the buffer will be used as a "prompt" line, with a
+    // single ':' in it. This is similar to the way `less` typically displays
+    // it's prompt at the bottom of the buffer.
```
Comment (miniksa) [inline src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp:3231]: I don't know what this looks like offhand. Can you give the sample of the prompt line too since that's the BFD here?

File: src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp [hunk 6]
```diff
@@ -2975,3 +2980,368 @@ void ConptyRoundtripTests::NewLinesAtBottomWithBackground()
...
+    // actually repro'd this bug. The other variables were introduced as part of
+    // debugging, and are left for completeness.
+    BEGIN_TEST_METHOD_PROPERTIES()
+        TEST_METHOD_PROPERTY(L"Data:circledRows", L"{2, 4, 10}")
+        TEST_METHOD_PROPERTY(L"Data:paintEachNewline", L"{0, 1, 2}")
+        TEST_METHOD_PROPERTY(L"Data:writingMethod", L"{0, 1}")
+    END_TEST_METHOD_PROPERTIES();
+    constexpr int DontPaint = 0;
+    constexpr int PaintAfterBothLines = 1;
+    constexpr int PaintEveryLine = 2;
```
Comment (miniksa) [inline src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp:3177]: I'm not totally clear what you mean by these cases here or above. I could reason it out with the logic below.... but again, more comments is probably more better.

File: src/cascadia/UnitTests_TerminalCore/TestUtils.h [hunk 7]
```diff
@@ -68,13 +68,24 @@ class TerminalCoreUnitTests::TestUtils
     static void VerifyExpectedString(std::wstring_view expectedString,
                                      TextBufferCellIterator& iter)
     {
+        size_t currentCharIndex = 0;
         for (const auto wch : expectedString)
         {
+            WEX::TestExecution::SetVerifyOutput settings(WEX::TestExecution::VerifyOutputSettings::LogOnlyFailures);
```
Comment (miniksa) [inline src/cascadia/UnitTests_TerminalCore/TestUtils.h:74]: Why? 
```
// This test spews out a lot of verify logging by default because of the loops, so suppress that to only show the failures.
```

File: src/renderer/vt/XtermEngine.cpp (hunk 1 above)
Comment (miniksa) [reply src/renderer/vt/XtermEngine.cpp:247]: Agreed, but what're we gonna do... At least it's tested. Like I said last time we had one of these "organically growing crazy-pants wrapping fixes" in the PTY rendering.

File: src/renderer/vt/paint.cpp [hunk 8]
```diff
@@ -474,7 +474,7 @@ using namespace Microsoft::Console::Types;
                                      (totalWidth - numSpaces) :
                                      totalWidth;
 
-    if (cchActual == 0)
+    if (cchActual == 0 && !_delayedEolWrap)
```
Comment (miniksa) [inline src/renderer/vt/paint.cpp:477]: Comment explaining the new case.
