### PR TITLE
Fix crash when window width and height are too high

### LINKED ISSUE #859: Terminal crashes on startup when initial rows on screen (`initialRows` setting) is set too high
Using this commit: e3764b2081b74c67fb901b2c133380c5bd3787af

1. Make sure there is no existing Terminal settings file at: `%LocalAppData%\Packages\WindowsTerminalDev_8wekyb3d8bbwe\RoamingState\profiles.json`
2. Build Terminal with `tools\razzle.cmd & bcz`.
3. Open the OpenConsole.sln in Visual Studio, select debug/release and CPU architecture to match your build, and hit F5 to deploy and run the Terminal .appx package.
4. Open the newly created Terminal settings file, and change the `initialRows` setting from 30 to 1637.
5. Close and restart Terminal.

Observe that Terminal does not start at all. If you start Terminal under a debugger, you'll see that the release build crashes with an unhandled C++ exception. (I haven't tried the debug build.)

Setting `initialRows` to 1636 or less does not cause the problem, but setting it to 1637 (as above) or greater does cause it.

_Originally posted by @metathinker in https://github.com/microsoft/terminal/pull/843#discussion_r284818080_ - that PR does not fix or otherwise affect this bug.

### PR DESCRIPTION
**Pull request by dkter**
## Summary of the Pull Request

Currently, the program crashes with a window width or height greater than 32767 (accounting for window decorations). This can be caused when the `initialRows` and `initialColumns` settings are set too high (also depends on the font width and height). This fixes the issue by not allowing the window to expand beyond 32767x32767.

 
## References

#843 - relocated the ClampToShortMax helper for reuse elsewhere

## PR Checklist
* [x] Closes #859
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Requires documentation to be updated
* [x] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #859 

## Detailed Description of the Pull Request / Additional comments

I didn't add tests because there doesn't seem to be a test framework for the `WindowsTerminal` project yet.

### CODE REVIEW

File: src/cascadia/WindowsTerminal/AppHost.cpp [hunk 1]
```diff
@@ -131,8 +133,10 @@ void AppHost::_HandleCreateWindow(const HWND hwnd, const RECT proposedRect)
 
     auto initialSize = _app.GetLaunchDimensions(dpix);
 
-    const short _currentWidth = gsl::narrow<short>(ceil(initialSize.X));
-    const short _currentHeight = gsl::narrow<short>(ceil(initialSize.Y));
+    const short _currentWidth = Utils::ClampToShortMax(
```
Comment (zadjii-msft) [inline src/cascadia/WindowsTerminal/AppHost.cpp]: If we do end up clamping the window size when we create it, what happens to the buffer? Does it immediately on creation get resized to only fill the available space?

File: src/cascadia/TerminalCore/Terminal.cpp [hunk 2]
```diff
@@ -18,11 +18,6 @@ using namespace Microsoft::Console::Render;
 using namespace Microsoft::Console::Types;
```
Comment (zadjii-msft) [inline src/cascadia/TerminalCore/Terminal.cpp]: nit: I'd probably drop a 
```suggestion
using namespace Microsoft::Console::Types;
using namespace Microsoft::Console;
```
here

File: src/cascadia/TerminalCore/Terminal.cpp [hunk 3]
```diff
@@ -70,7 +65,8 @@ void Terminal::Create(COORD viewportSize, SHORT scrollbackLines, IRenderTarget&
 {
     _mutableViewport = Viewport::FromDimensions({ 0,0 }, viewportSize);
     _scrollbackLines = scrollbackLines;
-    const COORD bufferSize { viewportSize.X, _ClampToShortMax(viewportSize.Y + scrollbackLines, 1) };
+    const COORD bufferSize { viewportSize.X,
+                             ::Microsoft::Console::Utils::ClampToShortMax(viewportSize.Y + scrollbackLines, 1) };
```
Comment (zadjii-msft) [inline src/cascadia/TerminalCore/Terminal.cpp]:
```suggestion
                             Utils::ClampToShortMax(viewportSize.Y + scrollbackLines, 1) };
```

File: src/cascadia/TerminalCore/Terminal.cpp [hunk 4]
```diff
@@ -84,9 +80,10 @@ void Terminal::Create(COORD viewportSize, SHORT scrollbackLines, IRenderTarget&
 void Terminal::CreateFromSettings(winrt::Microsoft::Terminal::Settings::ICoreSettings settings,
             Microsoft::Console::Render::IRenderTarget& renderTarget)
 {
-    const COORD viewportSize{ _ClampToShortMax(settings.InitialCols(), 1), _ClampToShortMax(settings.InitialRows(), 1) };
+    const COORD viewportSize{ ::Microsoft::Console::Utils::ClampToShortMax(settings.InitialCols(), 1),
```
Comment (zadjii-msft) [inline src/cascadia/TerminalCore/Terminal.cpp]:
```suggestion
    const COORD viewportSize{ Utils::ClampToShortMax(settings.InitialCols(), 1),
```

File: src/cascadia/TerminalCore/Terminal.cpp [hunk 5]
```diff
@@ -84,9 +80,10 @@ void Terminal::Create(COORD viewportSize, SHORT scrollbackLines, IRenderTarget&
 void Terminal::CreateFromSettings(winrt::Microsoft::Terminal::Settings::ICoreSettings settings,
             Microsoft::Console::Render::IRenderTarget& renderTarget)
 {
-    const COORD viewportSize{ _ClampToShortMax(settings.InitialCols(), 1), _ClampToShortMax(settings.InitialRows(), 1) };
+    const COORD viewportSize{ ::Microsoft::Console::Utils::ClampToShortMax(settings.InitialCols(), 1),
+                              ::Microsoft::Console::Utils::ClampToShortMax(settings.InitialRows(), 1) };
```
Comment (zadjii-msft) [inline src/cascadia/TerminalCore/Terminal.cpp]:
```suggestion
                              Utils::ClampToShortMax(settings.InitialRows(), 1) };
```

File: src/cascadia/TerminalCore/Terminal.cpp [hunk 6]
```diff
@@ -84,9 +80,10 @@ void Terminal::Create(COORD viewportSize, SHORT scrollbackLines, IRenderTarget&
 void Terminal::CreateFromSettings(winrt::Microsoft::Terminal::Settings::ICoreSettings settings,
             Microsoft::Console::Render::IRenderTarget& renderTarget)
 {
-    const COORD viewportSize{ _ClampToShortMax(settings.InitialCols(), 1), _ClampToShortMax(settings.InitialRows(), 1) };
+    const COORD viewportSize{ ::Microsoft::Console::Utils::ClampToShortMax(settings.InitialCols(), 1),
+                              ::Microsoft::Console::Utils::ClampToShortMax(settings.InitialRows(), 1) };
     // TODO:MSFT:20642297 - Support infinite scrollback here, if HistorySize is -1
-    Create(viewportSize, _ClampToShortMax(settings.HistorySize(), 0), renderTarget);
+    Create(viewportSize, ::Microsoft::Console::Utils::ClampToShortMax(settings.HistorySize(), 0), renderTarget);
```
Comment (zadjii-msft) [inline src/cascadia/TerminalCore/Terminal.cpp]:
```suggestion
    Create(viewportSize, Utils::ClampToShortMax(settings.HistorySize(), 0), renderTarget);
```

File: src/cascadia/TerminalCore/Terminal.cpp (hunk 2 above)
Comment (dkter) [reply src/cascadia/TerminalCore/Terminal.cpp]: ah, I was copying the references in `Terminal::_InitializeColorTable`. I'll change those too

File: src/cascadia/WindowsTerminal/AppHost.cpp (hunk 1 above)
Comment (dkter) [reply src/cascadia/WindowsTerminal/AppHost.cpp]: I investigated a bit and it looks like the buffer resizes properly. Maybe someone more familiar with this codebase could confirm, but it looks alright to me. I also tried clamping the window size to something like 300 so I could see what's going on and it looks like the buffer resizes on launch exactly as expected.

File: src/types/ut_types/sources [hunk 7]
```diff
@@ -15,6 +15,7 @@ DLLDEF                  =
 SOURCES = \
     $(SOURCES) \
     UuidTests.cpp \
+    UtilsTests.cpp \
```
Comment (miniksa) [inline src/types/ut_types/sources]: Excellent. Was going to ask you to do this. Thank you.
