### PR TITLE
Fix font changes not resizing _invalidMap

### LINKED ISSUE #10855: Font size changes no longer result in render target resize
### Windows Terminal version (or Windows build number)

1.11

### Other Software

_No response_

### Steps to reproduce

Set size 36. Maximize window. Set size 14.

### Expected Behavior

_No response_

### Actual Behavior

image

### PR DESCRIPTION
**Pull request by lhecker**
The `_invalidMap` size is dependent on both `clientSize` as well
as `glyphCellSize` and must be resized when either changes.

## PR Checklist
* [x] Closes #10855
* [x] I work here

## Validation Steps Performed
* Changing font size with Ctrl+Mousewheel in fullscreen works ✔️

### CODE REVIEW

**Review by zadjii-msft — APPROVED** [review]

File: src/renderer/dx/DxRenderer.cpp [hunk 1]
```diff
@@ -1318,7 +1316,13 @@ try
             // And persist the new size.
             _displaySizePixels = clientSize;
 
-            _invalidMap.resize(clientSize / _fontRenderData->GlyphCell());
+            _invalidMap.resize(clientSize / glyphCellSize);
+            RETURN_IF_FAILED(InvalidateAll());
```
Comment (lhecker) [inline src/renderer/dx/DxRenderer.cpp:1320]: Woops that's a duplicate of the if condition below.

**Review by DHowett — APPROVED** [review]

**Comment by DHowett** [comment]
@msftbot merge this in 5 minutes
