### PR TITLE
Fix combining wt args and "wt new-tab" args in implicit context

### LINKED ISSUE #7318: Fails to launch maximized/fullscreen and the given profile
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18363.1016]
Windows Terminal version (if applicable): Version: 1.1.2233.0
```

# Steps to reproduce

Open **CMD** and start wt maximized/fullscreen and a given profile, e.i. `wt -M -p "Command Prompt"`

# Expected behavior

Windows Terminal opens in maximized mode with the "Command Prompt" profile

# Actual behavior

Doesn't start and gives error: 
image

# Additional information

- `wt -M`
launches the terminal in maximized mode with default profile
- `wt -p "Command Prompt" -d D:/ ; -M`
launches the terminal maximized and the given profile, but with a second tab with the default profile
- `wt -p "Command Prompt" -d D:/ ; -M split-pane -d D:/ -p "Windows PowerShell"`
launches the terminal with 2 tabs with the selected profiles in maximized mode
- `wt -M -p "Command Prompt" -d D:/ ; split-pane -d D:/ -p "Windows PowerShell"`
doesn't work

### PR DESCRIPTION
**Pull request by Don-Vito**
Currently when implicit tab command is specified (i.e., we have
parameters for new-tab, but don't have the explicit subcommand name) we
fallback to parsing the entire arg list as new tab command.

However, if we also have a launch profile (or anything else that might in
the future belong to the upper scope) it is passed as a parameter to the
new tab command, failing the parsing.

The idea behind my solution is to run the parser as a prefix command -
i.e., as long as we succeed to parse [options] / [subcommand] we will
parse them (populating the fields like a launch mode), but once we will
discover something unfamiliar, like profile, we will know that the
prefix is over and will handle the remaining suffix as a new tab
command.

## PR Checklist
* [x] CLA signed. 
* [x] Tests added/passed
* [x] I've discussed this with core contributors already.

## Validation Steps Performed
* UT added
* Manual run of different option

Closes #7318

### CODE REVIEW

**Review by zadjii-msft — APPROVED** [review]
oh well that was easy 😅 I didn't know about `prefix_command`, thanks for finding this!

File: src/cascadia/TerminalApp/AppCommandlineArgs.cpp [hunk 1]
```diff
@@ -69,50 +69,29 @@ int AppCommandlineArgs::ParseCommand(const Commandline& command)
...
-            _newTabCommand.subcommand->clear();
             _newTabCommand.subcommand->parse(args);
+            remainingParams = _newTabCommand.subcommand->remaining_size();
+        }
+
+        // if after parsing the prefix and (optionally) the implicit tab subcommand
+        // we still have unparsed parameters we need to fail
+        if (remainingParams > 0)
+        {
+            throw CLI::ExtrasError(args);
```
Comment (DHowett) [inline src/cascadia/TerminalApp/AppCommandlineArgs.cpp:89]: who catches this? Does it end up down on line 92 as a ParseError?

File: src/cascadia/TerminalApp/AppCommandlineArgs.cpp [hunk 2]
```diff
@@ -69,50 +69,29 @@ int AppCommandlineArgs::ParseCommand(const Commandline& command)
...
         }
-    }
-    catch (const CLI::CallForHelp& e)
```
Comment (DHowett) [inline src/cascadia/TerminalApp/AppCommandlineArgs.cpp:87]: are we losing support for CallForHelp?

**Comment by DHowett** [comment]
Don't mind me editing your bodies and titles -- I like to maintain imperative mood and some line wrapping rules, but I don't want to force the community to do that :smile:

File: src/cascadia/TerminalApp/AppCommandlineArgs.cpp (hunk 1 above)
Comment (Don-Vito) [reply src/cascadia/TerminalApp/AppCommandlineArgs.cpp:89]: Yes. It is caught there as a parse error. Implemented this to allow future handling. I can handle it immediately if you prefer.

File: src/cascadia/TerminalApp/AppCommandlineArgs.cpp (hunk 2 above)
Comment (Don-Vito) [reply src/cascadia/TerminalApp/AppCommandlineArgs.cpp:87]: From my understanding the CallForHelp was here only to prevent implicit subcommand parsing (the second catch clause). Now we don't have this catch clause, thus we can handle all exceptions the same way by calling _handleExit, that will still show the relevant UI.

**Review by Don-Vito — COMMENTED** [review]
> 
> 
> Don't mind me editing your bodies and titles -- I like to maintain imperative mood and some line wrapping rules, but I don't want to force the community to do that 😄

Sure! Actually, I didn't like the title in the first place - lately I simply copy the title of the issue to the PR... not sure it is a good approach 😊

**Review by DHowett — APPROVED** [review]
With my questions answered, I'll sign off. This is great. :smile:

**Comment by DHowett** [comment]
So, with regards to copying the issue being the right approach for a title... I like to follow [this guide](https://chris.beams.io/posts/git-commit/) on "good commit messages". It's obviously a personal style or opinion :smile: but it helps me out.

I use the same rules for PR bodies as commits because we use the PR title _as_ the commit and the PR body as the body.

The basic rules I follow:

* Title is 72 characters or less
* "Imperative" mood. Pretend that it completes the sentence, "This pull request will ..."
   * "This pull request will **7333: it crashes when I minimize it**"
   * "This pull request will **fix the crash on minimize**"
   * "This pull request will **Implementing support for OSC 9;4**" (bad: title describes what the author is doing, not what the commit is doing)
   * "This pull request will **implement support for OSC 9;4**" (flows more nicely)

I like to delete the HTML comments `<!--` in our template, as well, and format the body to 80 character hard wrap. That's a personal style.

I should get a request out on the msftbot people to remove HTML comments themselves! Otherwise it just clutters up the commit body when it DOES get merged.

**Comment by Don-Vito** [comment]
> 
> 
> So, with regards to copying the issue being the right approach for a title... I like to follow [this guide](https://chris.beams.io/posts/git-commit/) on "good commit messages". It's obviously a personal style or opinion 😄 but it helps me out.
> 
> I use the same rules for PR bodies as commits because we use the PR title _as_ the commit and the PR body as the body.
> 
> The basic rules I follow:
> 
>     * Title is 72 characters or less
> 
>     * "Imperative" mood. Pretend that it completes the sentence, "This pull request will ..."
>       
>       * "This pull request will **7333: it crashes when I minimize it**"
>       * "This pull request will **Fix the crash on minimize**"
>       * "This pull request will **Implementing support for OSC 300**" (bad: title describes what the author is doing, not what the commit is doing)
>       * "This pull request will **Implement support for OSC 300**" (flows more nicely)
> 
> 
> I like to delete the HTML comments `<!--` in our template, as well, and format the body to 80 character hard wrap. That's a personal style.
> 
> I should get a request out on the msftbot people to remove HTML comments themselves! Otherwise it just clutters up the commit body when it DOES get merged.

I like those guidelines and will try to follow them!
