### PR TITLE
Fix dispatching of system keys

### LINKED ISSUE #18331: Alt and F7 don't work in 1.23.3481.0
### Windows Terminal version

1.23.3481.0

### Windows build number

10.0.19045.5247

### Other Software

FAR Manager 3.0.6401.0 x64

when migrate from canary build terminal-1.23.3461.0 to next canary build terminal-1.23.3481.0
i have trouble with keys: Alt/RAlt and F7

### Steps to reproduce

run utility KeyEvents.exe and press Alt and F7

### Expected Behavior

result when press Alt:

terminal-1.23.3461.0 - good behavior
02:56:37 KEY_EVENT_RECORD: Dn, 1, Vk="VK_MENU" [18/0x0012], Scan=0x0038 uChar=[U=' ' (0x0000): A=' ' (0x00)]
         Ctrl=0x00000002 (cAsac - ecns) (Windowed)
02:56:37 KEY_EVENT_RECORD: Up, 1, Vk="VK_MENU" [18/0x0012], Scan=0x0038 uChar=[U=' ' (0x0000): A=' ' (0x00)]
         Ctrl=0x00000000 (casac - ecns) (Windowed)

result when press f7:

terminal-1.23.3461.0 - good behavior

03:08:36 KEY_EVENT_RECORD: Dn, 1, Vk="VK_F7" [118/0x0076], Scan=0x0041 uChar=[U=' ' (0x0000): A=' ' (0x00)]
         Ctrl=0x00000000 (casac - ecns) (Windowed)
03:08:36 KEY_EVENT_RECORD: Up, 1, Vk="VK_F7" [118/0x0076], Scan=0x0041 uChar=[U=' ' (0x0000): A=' ' (0x00)]
         Ctrl=0x00000000 (casac - ecns) (Windowed)

### Actual Behavior

result when press Alt:

terminal-1.23.3481.0 - bad behavior
02:54:44 KEY_EVENT_RECORD: Up, 1, Vk="VK_MENU" [18/0x0012], Scan=0x0038 uChar=[U=' ' (0x0000): A=' ' (0x00)]
         Ctrl=0x00000002 (cAsac - ecns) (Windowed)

result when press f7:

terminal-1.23.3481.0 - bad behavior
03:02:27 KEY_EVENT_RECORD: Dn, 1, Vk="VK_F7" [118/0x0076], Scan=0x0041 uChar=[U=' ' (0x0000): A=' ' (0x00)]
         Ctrl=0x00000000 (casac - ecns) (Windowed)
03:02:27 KEY_EVENT_RECORD: Dn, 1, Vk="VK_F7" [118/0x0076], Scan=0x0041 uChar=[U=' ' (0x0000): A=' ' (0x00)]
         Ctrl=0x00000000 (casac - ecns) (Windowed)

### PR DESCRIPTION
**Pull request by lhecker**
This fixes the bit check for key down and adds a few comments.

Closes #18331

## Validation Steps Performed
Printing the resulting INPUT_RECORDs shows both key down and up events when pressing F7. Alt-Space now also works again.

### CODE REVIEW

File: src/cascadia/WindowsTerminal/WindowEmperor.cpp [hunk 1]
```diff
@@ -438,15 +441,13 @@ void WindowEmperor::HandleCommandlineArgs(int nCmdShow)
     __assume(false);
 }
 
-void WindowEmperor::_dispatchSpecialKey(MSG& msg) const
+void WindowEmperor::_dispatchSpecialKey(const MSG& msg) const
 {
-    const auto hwnd = msg.hwnd;
+    // Each CoreInput window is a child of our IslandWindow.
+    // We can figure out the IslandWindow HWND via GetAncestor().
+    const auto hwnd = GetAncestor(msg.hwnd, GA_ROOT);
```
Comment (DHowett) [inline src/cascadia/WindowsTerminal/WindowEmperor.cpp:448]: huh, which one did this fix?

**Review by DHowett — APPROVED** [review]

File: src/cascadia/WindowsTerminal/WindowEmperor.cpp (hunk 1 above)
Comment (lhecker) [reply src/cascadia/WindowsTerminal/WindowEmperor.cpp:448]: You can consider this an extra. 😄 When I added this code you asked if we can't figure out the IslandWindow from a CoreInput target and I said no. Turns out we can.
