### PR TITLE
AtlasEngine: Properly detect shader model 4 support

### LINKED ISSUE #13985: Renderer encountered an unexpected error: -2147024809
### Windows Terminal version

1.16.2523.0

### Windows build number

10.0.19044.1889

### Other Software

I'm on an Intel Core i5-2500K CPU, using its integrated HD 3000 GPU. Graphics driver version 9.17.10.4459

### Steps to reproduce

Open Windows Terminal

### Expected Behavior

_No response_

### Actual Behavior

A "Warning" dialog pops up saying "Renderer encountered an unexpected error: -2147024809".

If I click OK it just pops up again, ad infinitum.

I assume it's related to the Atlas renderer that is now enabled by default in the preview version of Terminal.

### PR DESCRIPTION
**Pull request by lhecker**
Direct3D 10.0 and 10.1 only have optional support for shader model 4.
This commit fixes our assumption that it's always present by checking
`ComputeShaders_Plus_RawAndStructuredBuffers_Via_Shader_4_x` first.

Closes #13985

## Validation Steps Performed
* Set feature level to 10.1 via `dxcpl`
* `CheckFeatureSupport` is called and doesn't throw ✅

### CODE REVIEW

File: src/renderer/atlas/AtlasEngine.cpp [hunk 1]
```diff
@@ -639,16 +639,30 @@ void AtlasEngine::_createResources()
...
+    {
+        _r.d2dMode = true;
+    }
+    else if (featureLevel < D3D_FEATURE_LEVEL_11_0)
+    {
+        D3D11_FEATURE_DATA_D3D10_X_HARDWARE_OPTIONS options;
+        THROW_IF_FAILED(_r.device->CheckFeatureSupport(D3D11_FEATURE_D3D10_X_HARDWARE_OPTIONS, &options, sizeof(options)));
+        if (!options.ComputeShaders_Plus_RawAndStructuredBuffers_Via_Shader_4_x)
+        {
+            _r.d2dMode = true;
```
Comment (DHowett) [inline src/renderer/atlas/AtlasEngine.cpp:664]: any idea what percentage of hardware out there we're pushing back into WARP mode?

If it's high, should we support "d2dmode" on hardware instead of forcing WARP?

**Review by DHowett — APPROVED** [review]

File: src/renderer/atlas/AtlasEngine.cpp (hunk 1 above)
Comment (lhecker) [reply src/renderer/atlas/AtlasEngine.cpp:664]: Actually that's exactly what's happening here. 🙂
WARP is only enabled if the device is older than D3D 9.1 or if `useSoftwareRendering` is true.

Comment (DHowett) [reply src/renderer/atlas/AtlasEngine.cpp:664]: perfect.

**Review by zadjii-msft — APPROVED** [review]
