### PR TITLE
Correct for the size of the tabs when calculating our initial window size

### LINKED ISSUE #2061: Terminal is starting up at a size that's different from initialRows/initialCols
# Environment

```none
Windows build number: Microsoft Windows [Version 10.0.18362.264]
Windows Terminal version (if applicable): 8ffff8ea 0.2.1991.0
Any other software? WSL
```

# Steps to reproduce

The relevant-looking parts of profiles.json are:

```
{
    "globals" : 
    {
        "defaultProfile" : "{c6eaf9f4-32a7-5fdc-b5cf-066e8a4b1e40}",
        "initialCols" : 80,
        "initialRows" : 40,
    },
    "profiles" : 
    [
        {
            "commandline" : "wsl.exe -d Ubuntu-18.04",
            "fontFace" : "DejaVu Sans Mono for Powerline",
            "fontSize" : 9,
            "guid" : "{c6eaf9f4-32a7-5fdc-b5cf-066e8a4b1e40}",
            "padding" : "0, 0, 0, 0"
        }
    ]
```

# Expected behavior

I should see an 80x40 terminal.

# Actual behavior

I get an 80x37 terminal, with extra blank horizontal space after the last usable column:

image

### PR DESCRIPTION
**Pull request by zadjii-msft**
## Summary of the Pull Request

This fixes our calculation for the initial size of the window. WE weren't accounting for the height of the tabs, so the `initialRows` was consistently wrong.

## PR Checklist
* [x] Closes #2061
* [x] I work here
* [ ] Tests added/passed
* [n/a] Requires documentation to be updated

## Detailed Description of the Pull Request / Additional comments

For the tabs below the titlebar case, there's 6px (unscaled) of space that I cannot account for. I seriously have no idea where it's coming from. When we end up creating the first `TermControl` after startup, there's an inexplicable `6*scale` difference between the height of the `tabContent` and the `SwapChainPanel`'s size.

## Validation Steps Performed

Checked all six of the following cases:
* 1.0 DPI scaling, Tabs in Titlebar
* 1.25 DPI scaling, Tabs in Titlebar
* 1.0 DPI scaling, Tabs NOT in Titlebar, always show tabs
* 1.0 DPI scaling, Tabs NOT in Titlebar, DON'T always show tabs
* 1.25 DPI scaling, Tabs NOT in Titlebar, always show tabs
* 1.25 DPI scaling, Tabs NOT in Titlebar, DON'T always show tabs

### CODE REVIEW

File: src/cascadia/TerminalApp/AppLogic.cpp [hunk 1]
```diff
@@ -367,11 +367,44 @@ namespace winrt::TerminalApp::implementation
...
+            //
+            // Similarly to above, we'll measure it with an arbitrarily large
+            // available space, to make sure we get all the space it wants.
+            auto tabControl = TabRowControl();
+            tabControl.Measure({ SHRT_MAX, SHRT_MAX });
+
+            // For whatever reason, there's about 6px of unaccounted-for space
+            // in the application. I couldn't tell you where these 6px are
+            // coming from, but they need to be included in this math.
+            proposedSize.Y += (tabControl.DesiredSize().Height + 6) * scale;
```
Comment (miniksa) [inline src/cascadia/TerminalApp/AppLogic.cpp]: I mean I don't like it, but I trust you rooted around forever to try to find it and we'll just correct it later should something change.

File: src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp [hunk 2]
```diff
@@ -417,6 +417,8 @@ SIZE NonClientIslandWindow::GetTotalNonClientExclusiveSize(UINT dpi) const noexc
 
     islandFrame.top = -topBorderVisibleHeight;
 
+    // If we have a titlebar, this is being called after we've initialized, and
+    // we can just ask that titlebar how big it wants to be.
     const auto titleBarHeight = _titlebar ? static_cast<LONG>(_titlebar.ActualHeight()) : 0;
```
Comment (greg904) [inline src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp]: Isn't it adding the title bar twice now: Here and in `AppLogic::GetLaunchDimensions`? But this works because it's not initialized yet so it adds `0`.

Comment (zadjii-msft) [reply src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp]: Thanks for filing that! You're right, that method name is definitely confusing. IIRC, in the PR that introduced it there was some back and forth on the naming but we couldn't come up with a better name. With this PR, it should be a little easier to at least solve that bug (#4827).

**Comment by DHowett-MSFT** [comment]
Er did we ever figure out if greg904 was right? Probably we should have blocked this

**Comment by zadjii-msft** [comment]
Oh sorry, never replied to that - no, we're shockingly not. Hence the comment there. In startup, `_titlebar` is `nullptr`, so we don't add anything for it there.
