### PR TITLE
fix ~ not work as startingDirectory for WSL

### LINKED ISSUE #11432: ~ not work as startingDirectory for WSL
### Windows Terminal version (or Windows build number)

1.11.2731.0

### Other Software

WSL on Windows 11 version 10.0.22000.194

### Steps to reproduce

Put `~` as `startingDirectory` for a WSL Distro

### Expected Behavior

Start the profile at the `$HOME` directory exactly like when I manualy run the command `wsl.exe --cd "~" ` in PowerShell

### Actual Behavior

In my machine the terminal output say:
Le fichier spécifié est introuvable.

[processus terminé avec le code 4294967295]

### PR DESCRIPTION
**Pull request by LuanVSO**
## Summary of the Pull Request
fix #11432
 
## PR Checklist
* [x] Closes #11432
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx

## Validation Steps Performed
compiled and verified that "\~"  ,  "/usr/bin"  ,  "~/.config" and "/" as stating directory didn't get relative path resolve
verified that '.' did

### CODE REVIEW

File: src/cascadia/TerminalApp/TerminalPage.cpp [hunk 1]
```diff
@@ -941,7 +941,7 @@ namespace winrt::TerminalApp::implementation
             // process until later, on another thread, after we've already
             // restored the CWD to it's original value.
             winrt::hstring newWorkingDirectory{ settings.StartingDirectory() };
-            if (newWorkingDirectory.size() <= 1 ||
+            if (newWorkingDirectory.size() <= 1 &&
                 !(newWorkingDirectory[0] == L'~' || newWorkingDirectory[0] == L'/'))
```
Comment (j4james) [inline src/cascadia/TerminalApp/TerminalPage.cpp:945]: Wouldn't this potentially crash when `newWorkingDirectory` is blank? It's going to try to dereference `newWorkingDirectory[0]` when that's technically out of bounds.

Comment (LuanVSO) [reply src/cascadia/TerminalApp/TerminalPage.cpp:945]: Since c++11 it is guaranteed to just return the null terminator of the string

Comment (j4james) [reply src/cascadia/TerminalApp/TerminalPage.cpp:945]: That's a `winrt::hstring` though. Does that have the same guarantee?

Comment (LuanVSO) [reply src/cascadia/TerminalApp/TerminalPage.cpp:945]: I mean, if it doesn't it's kind of a bug in c++/winrt isn't it?

Comment (j4james) [reply src/cascadia/TerminalApp/TerminalPage.cpp:945]: I don't know. You'll have to take that up with the winrt authors. It definitely looks to me like the hstring array operator expects the index to be in range.

https://github.com/microsoft/cppwinrt/blob/71832b634d12271d540383df35bde0ea1c69156c/strings/base_string.h#L243

Comment (LuanVSO) [reply src/cascadia/TerminalApp/TerminalPage.cpp:945]: Oof

**Comment by zadjii-msft** [comment]
@msftbot make sure @DHowett signs off on this one

**Review by DHowett — APPROVED** [review]

**Comment by DHowett** [comment]
Thanks for handling this!

**Review by zadjii-msft — APPROVED** [review]
