### PR TITLE
Manually dismiss popups when the window moves, or the SUI scrolls

### LINKED ISSUE #9320: default profile menu once opened in startup settings goes above the window when scrolling  down
<!-- 
🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨

image

# Environment
Windows build number: Version 10.0.19042.844
Windows Terminal version (if applicable): 1.7.572.0

Any other software?
```

# Steps to reproduce

Settings-Startup-Default profile (tap arrow to open) and scroll down the window using mouse (the window not in maximize mode)

# Expected behavior

selection menu (Windows PowerShell, Command Prompt, Azure Cloud Shell) - when expanded (while scrolling down) it does not move to the screen above the Windows PowerShell window (the window is not in maximize mode)

# Actual behavior

The selection menu (Windows PowerShell, Command Prompt, Azure Cloud Shell) goes beyond the top edge of the Windows PowerShell window if the window is not in maximize mode

### PR DESCRIPTION
**Pull request by zadjii-msft**
## Summary of the Pull Request

BODGY!

This solution was suggested in https://github.com/microsoft/microsoft-ui-xaml/issues/4554#issuecomment-887815332.

When the window moves, or when a ScrollViewer scrolls, dismiss any popups that are visible. This happens automagically when an app is a real XAML app, but it doesn't work for XAML Islands.

## References
* upstream at https://github.com/microsoft/microsoft-ui-xaml/issues/4554

## PR Checklist
* [x] Closes #9320
* [x] I work here
* [ ] Tests added/passed
* [ ] Requires documentation to be updated

## Detailed Description of the Pull Request / Additional comments

Unfortunately, we've got a bunch of scroll viewers in our SUI. So I did something bodgyx2 to make our life a little easier.

`DismissAllPopups` can be used to dismiss all popups for a particular UI element. However, we've got a bunch of pages with scroll viewers that may or may not have popups in them. Rather than define the same exact body for all their `ViewChanging` events, the `HasScrollViewer` struct will just do it for you!

Inside the `HasScrollViewer` stuct, we can't get at the `XamlRoot()` that our subclass implements. I mean, _we_ can, but when XAML does it's codegen, _XAML_ won't be able to figure it out.

Fortunately for us, we don't need to! The sender is a UIElement, so we can just get _their_ `XamlRoot()`.

So, you can fix this for any SUI page with just a simple 

```diff
-    <ScrollViewer>
+    <ScrollViewer ViewChanging="ViewChanging">
```

```diff
-    struct AddProfile : AddProfileT<AddProfile>
+    struct AddProfile : public HasScrollViewer<AddProfile>, AddProfileT<AddProfile>
```

## Validation Steps Performed

* the window doesn't close when you move it
* the popups _do_ close when you move the window
* the popups close when you scroll any SUI page

### CODE REVIEW

**Comment by DHowett** [comment]
I had an even wackier idea.

Is it possible to do this?

```xml
<Page
    xmlns:local="whatever local is in these projects"
```

```xml
<ScrollViewer ViewChanging="local:StaticDismissHelperClass.ViewChanging">
```

(I wouldn't block for this suggestion, but it might make our lives easier if you can bind to like... static event handlers from other classes?)

File: src/cascadia/WindowsTerminal/AppHost.cpp [hunk 1]
```diff
@@ -1023,3 +1024,29 @@ void AppHost::_UpdateTrayIcon()
...
+
+// Method Description:
+// - BODGY workaround for GH#9320. When the window moves, dismiss all the popups
+//   in the UI tree. Xaml Islands unfortunately doesn't do this for us, see
+//   microsoft/microsoft-ui-xaml#4554
+// Arguments:
+// - <none>
+// Return Value:
+// - <none>
+void AppHost::_WindowMoved()
```
Comment (DHowett) [inline src/cascadia/WindowsTerminal/AppHost.cpp:1036]: Does enumerating all the popups every time the window moves during a drag make drag performance slower?

File: src/cascadia/TerminalSettingsEditor/Utils.h [hunk 2]
```diff
@@ -138,3 +138,41 @@ namespace winrt::Microsoft::Terminal::Settings
...
+// BODGY!
+//
+// The following function and struct are a workaround for GH#9320.
+//
+// DismissAllPopups can be used to dismiss all popups for a particular UI
+// element. However, we've got a bunch of pages with scroll viewers that may or
+// may not have popups in them. Rather than define the same exact body for all
+// their ViewChanging events, the HasScrollViewer struct will just do it for
+// you!
+inline void DismissAllPopups(winrt::Windows::UI::Xaml::XamlRoot const& xamlRoot)
```
Comment (DHowett) [inline src/cascadia/TerminalSettingsEditor/Utils.h:151]: It's fine to put this in the template class body; it will get emitted for every consumer, yes, but then it will get folded down into a single implementation by COMDAT folding/OPT:ICF. Otherwise, you might need to change the specifiers on this a little bit. Something about inline.

Then again, [someone on the LLVM mailing list](https://lists.llvm.org/pipermail/llvm-dev/2021-August/152031.html) had this to say on the matter:

> C++ `inline` means 'the definition is provided in line with the 
> declaration, the compiler and linker are responsible for ensuring that 
> exactly one definition exists in the final binary'
> ...
> ...
>   - C++ `inline`: Must exist in at least one compilation unit and the 
linker must discard duplicates.

Sounds like what we want. So you can ignore that part. :P

**Review by DHowett — APPROVED** [review]

File: src/cascadia/TerminalSettingsEditor/Launch.cpp [hunk 3]
```diff
@@ -6,6 +6,7 @@
 #include "Launch.g.cpp"
 #include "LaunchPageNavigationState.g.cpp"
 #include "EnumEntry.h"
+#include "Utils.h"
```
Comment (carlos-zamora) [inline src/cascadia/TerminalSettingsEditor/Launch.cpp:9]: This change is a bit odd. Curious, why?

File: src/cascadia/WindowsTerminal/pch.h [hunk 4]
```diff
@@ -62,6 +62,7 @@ Module Name:
 //  * ApplicationModel for finding the path to wt.exe
 #include <winrt/Windows.UI.Core.h>
 #include <winrt/Windows.UI.Xaml.Controls.h>
+#include <winrt/Windows.UI.Xaml.Controls.Primitives.h>
```
Comment (carlos-zamora) [inline src/cascadia/WindowsTerminal/pch.h:65]: Curious: we need this for `XamlRoot`?

**Review by carlos-zamora — APPROVED** [review]
BODGY indeed haha

File: src/cascadia/TerminalSettingsEditor/Launch.cpp (hunk 3 above)
Comment (zadjii-msft) [reply src/cascadia/TerminalSettingsEditor/Launch.cpp:9]: We don't need this one after all, turns out it's in the headers for most of these
```suggestion
```

File: src/cascadia/WindowsTerminal/AppHost.cpp (hunk 1 above)
Comment (zadjii-msft) [reply src/cascadia/WindowsTerminal/AppHost.cpp:1036]: Not that I could perceive even in debug

File: src/cascadia/WindowsTerminal/pch.h [hunk 5]
```diff
@@ -62,6 +62,7 @@ Module Name:
 //  * ApplicationModel for finding the path to wt.exe
 #include <winrt/Windows.UI.Core.h>
```
Comment (zadjii-msft) [inline src/cascadia/WindowsTerminal/pch.h:63]:
```suggestion
//  * ApplicationModel for finding the path to wt.exe
//  * Primitives for Popup (used by GetOpenPopupsForXamlRoot)
#include <winrt/Windows.UI.Core.h>
```

File: src/cascadia/WindowsTerminal/pch.h (hunk 4 above)
Comment (zadjii-msft) [reply src/cascadia/WindowsTerminal/pch.h:66]: Nah, we need it for [`Popup`](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.primitives.popup?view=winrt-20348)

**Comment by DHowett** [comment]
CONFLICTS :O
