### PR TITLE
Fix potential cursor redrawing crash

### LINKED ISSUE #2986: Crash in TextBufferCellIterator::TextBufferCellIterator() when moving cursor
# Environment
Windows 10.0.18362.0, 
Windows Terminal running in Debug mode, off commit 1caece74abdae9e57642fdc3761bb432238c75f8

## Any other software?

The [micro](https://github.com/zyedidia/micro) terminal text editor, with a few custom keybinds, as follows:

```json
{
        "CtrlRight": "WordRight",
        "CtrlLeft": "WordLeft",
        "CtrlShiftRight": "SelectWordRight",
        "CtrlShiftLeft": "SelectWordLeft"
}
```
# Steps to reproduce

I can easily reproduce this in `micro`, but I've had crashes from what miiiight be this issue in non-interactive-mode apps as well. The steps that tend to trigger this are as follows:

1) Open `micro`. The shell doesn't seem to matter.
2) Type at least one word.
3) Move the cursor to the end of the line.
4) With the above keybinds in place, press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>LeftArrow</kbd>.
5) Crash!

# Expected behavior

The text is highlighted one word to the left. Old Conhost seems to be able to handle this.

# Actual behavior

Crashiness.

# Additional Information

I ran this in Visual Studio to capture some debug output. Here's the stack trace:

```none
ucrtbased.dll!__threadid() + 101 bytes	Unknown
ucrtbased.dll!__threadid() + 515 bytes	Unknown
ucrtbased.dll!abort() + 29 bytes	Unknown
ucrtbased.dll!terminate() + 54 bytes	Unknown
vcruntime140_1d.dll!00007fff96842174()	Unknown
vcruntime140_1d.dll!00007fff96842e72()	Unknown
vcruntime140_1d.dll!__CxxFrameHandler4() + 251 bytes	Unknown
TerminalControl.dll!__GSHandlerCheck_EH4(_EXCEPTION_RECORD * ExceptionRecord, void * EstablisherFrame, _CONTEXT * ContextRecord, _DISPATCHER_CONTEXT * DispatcherContext) Line 73	C++
ntdll.dll!__chkstk() + 287 bytes	Unknown
ntdll.dll!RtlRaiseException() + 921 bytes	Unknown
ntdll.dll!KiUserExceptionDispatcher() + 46 bytes	Unknown
KernelBase.dll!RaiseException() + 105 bytes	Unknown
vcruntime140d.dll!_CxxThrowException() + 311 bytes	Unknown
TerminalControl.dll!wil::details::ThrowResultExceptionInternal(const wil::FailureInfo & failure) Line 2787	C++
TerminalControl.dll!wil::ThrowResultException(const wil::FailureInfo & failure) Line 2449	C++
TerminalControl.dll!wil::details::ReportFailure(void * callerReturnAddress, unsigned int lineNumber, const char * fileName, const char * functionName, const char * code, void * returnAddress, wil::FailureType type, HRESULT hr, const wchar_t * message, wil::details::ReportFailureOptions options) Line 3390	C++
TerminalControl.dll!wil::details::ReportFailure_Hr(void * callerReturnAddress, unsigned int lineNumber, const char * fileName, const char * functionName, const char * code, void * returnAddress, wil::FailureType type, HRESULT hr) Line 3451	C++
TerminalControl.dll!wil::details::in1diag5::_Throw_Hr(void * callerReturnAddress, unsigned int lineNumber, const char * fileName, const char * functionName, const char * code, HRESULT hr) Line 4970	C++
TerminalControl.dll!wil::details::in1diag5::Throw_HrIf(void * callerReturnAddress, unsigned int lineNumber, const char * fileName, const char * functionName, const char * code, HRESULT hr, bool condition) Line 5074	C++
--> TerminalControl.dll!TextBufferCellIterator::TextBufferCellIterator(const TextBuffer & buffer, _COORD pos, const Microsoft::Console::Types::Viewport limits) Line 48	C++
TerminalControl.dll!TextBufferCellIterator::TextBufferCellIterator(const TextBuffer & buffer, _COORD pos) Line 25	C++
TerminalControl.dll!Microsoft::Terminal::Core::Terminal::IsCursorDoubleWidth() Line 96	C++
TerminalControl.dll!Microsoft::Console::Render::Renderer::_PaintCursor(Microsoft::Console::Render::IRenderEngine * const pEngine) Line 749	C++
TerminalControl.dll!Microsoft::Console::Render::Renderer::_PaintFrameForEngine(Microsoft::Console::Render::IRenderEngine * const pEngine) Line 137	C++
TerminalControl.dll!Microsoft::Console::Render::Renderer::PaintFrame() Line 70	C++
TerminalControl.dll!Microsoft::Console::Render::RenderThread::_ThreadProc() Line 165	C++
TerminalControl.dll!Microsoft::Console::Render::RenderThread::s_ThreadProc(void * lpParameter) Line 148	C++
[External Code]	
```

At the time of this particular crash, `TextBufferCellIterator::TextBufferCellIterator()` received a `pos` argument with with dimensions `120x26`, and a `limits` arg with an LT of `0,0` and a RB of `119, 9028`, so altogether a `[120x9029]`-sized viewport.

Judging by the `failure` object up in WIL's `ThrowExceptionInternal`, the issue seems to be line 46 of `textBufferCellIterator.cpp`, `THROW_HR_IF(E_INVALIDARG, !limits.IsInBounds(pos));`. 

Some further digging reveals that `Viewport::IsInBounds(const COORD& pos)` is violating the "`pos.X < RightExclusive()`" constraint. `pos.X` is _exactly `120`, while `RightExclusive()` also returns exactly `120`.

Just <kbd>Ctrl</kbd>+<kbd>Arrow</kbd>ing around in Micro doesn't usually trigger this, although I can occasionally get crashes to occur when I'm at the extreme left edge of a line while navigating leftward. <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Arrow</kbd> is extremely reliable at triggering crashes, however.

### PR DESCRIPTION
**Pull request by skyline75489**
## Summary of the Pull Request

Fixes crash introduced by #2932 

 
## PR Checklist
* [x] Closes #2986
* [X] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ ] Tests added/passed
* [ ] Requires documentation to be updated
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan.

## Detailed Description of the Pull Request / Additional comments

See #2932

### CODE REVIEW

**Comment by skyline75489** [comment]
I've been tweaking around with #2932 and my other related PRs. For me if we don't include this fix, we better revert #2932 in case of very frequent crashes.

**Comment by skyline75489** [comment]
I found #2924 is also related to this. Feel free to cherry-pick or close this.

**Comment by DHowett-MSFT** [comment]
You will probably need to merge in `master` to get the CI pipeline to work again. Sorry about that!

**Comment by skyline75489** [comment]
@miniksa This is also a very important PR. If we don’t include this one, we better just revert #2932 , as I’ve experienced  severe crashes. To reproduce, just do cmatrix.

**Comment by DHowett-MSFT** [comment]
I think the real problem here is that some writer isn't locking the console buffer before writing, or some reader isn't locking the console before forcing the cursor to redraw. It looks like Cursor is updated in a  great number of places, and it'll be hard to audit callers in conhost (to find good examples of where locking is required around cursor manipulation.)

**Comment by skyline75489** [comment]
I was thinking the same thing. Furthermore, an obvious design issue is that cursor redrawing is related to the entire text buffer's refreshing. #2932 unintentionally made cursor redrawing slower and make this crush super severe.

**Comment by miniksa** [comment]
Yeah, this isn't right. This is just adjusting the parameters of the problem. We need to identify the locking issue for real.

The discussion about this is now crossing like 4 different PRs and issues. @DHowett-MSFT, is there a follow on task to investigate where the locking has gone wrong here (I saw that you reverted #2932).

**Comment by skyline75489** [comment]
I find that the read lock in `SetCursorVisible` indeed fixes the crash with no obvious performance panalty. 

CC @DHowett-MSFT @miniksa

**Comment by skyline75489** [comment]
Again theres' a catch ...

Adding lock  in `SetCursorVisible ` fixes the crash from `TermControl::_KeyDownHandler`, but the crash from `Renderer::PaintFrame()` is still there. I thought `LockConsole()` in `PaintFrame` prevents this but apparently it does not.

**Comment by skyline75489** [comment]
OK, here's what I got so far. There're mainly three threads that's competing for `_buffer` access, which are "Main Thread", "Render Thread", and "Output Thread".  "Main Thread" and "Output Thread" compete for the write lock. "Render Thread" competes for the read lock.

With #2932, there're race conditions which is not handled correctly

1. Crashes involves moving cursor are caused by `SetCursorVisible` which is called from `TermControl::_KeyDownHandler` (and `TermControl::_BlinkCursor`). The access is from main thread. But there is not read lock for this. Adding a read lock fixes this.
2. Crashes involving window resizing are caused by `_PaintCursor` which is called from `Renderer::PaintFrame()`, the access is from render thread. The root cause is the lock in main thread, which resides in `TermControl::_SwapChainSizeChanged`. This is this first function that gets called when resizing happenes. It acquires the lock and modified the buffer using `TextBuffer::ResizeTraditional` (in `Terminal::UserResize`). So far so good. But when it releases the lock, it is uncertain that whether render thread or output thread is a winner for the lock. If the output thread wins and acquires the lock, it will modify the buffer to adopt new window size and then notify render thread to paint frame. This route is good. But if it's the other way around then we have a problem. Suppose we have a window size 120 x 80 and cursor is at (21, 5).  And we set the new window width to something less than 21. Remember that at this very moment, the buffer still holds the old data which has the cursor position of (21, 5), and the buffer is already modified by `TextBuffer::ResizeTraditional`. Trying to access the cursor position in buffer will result in runtime exception. 

This second case is obviously more complicated and painful. I may be wrong but I don't think there's easy fix for this.

**Comment by skyline75489** [comment]
Ideally, the execution order of render thread and output thread should be in our control, as in #3075, quote:

>The terminal should read and parse as much data as possible, only stopping for updating its UI according to the monitor refresh rate, typically 60 times per second (or maybe at a hardwired 60Hz if refresh rate can't be detrmined or the concept doesn't exist – I don't know how it goes in VMware). If updating the UI takes so much time that there's hardly any time left for processing incoming data, it should start dropping frames.

The basic infrastructure is exactly like it. The render thread has a sleep interval that's limited to `s_FrameLimitMilliseconds`. But the output thread spend so much time doing layout work in `_outputHandlers`(in `ConhostConnection::_OutputThread`, which is essentially `Terminal::Write`). While the output thread is busy doing text layout, the render thread can easily be awaken from sleep and start rendering, adding extra burden to both CPU and GPU. This is the root cause of the slowness described in #3075, and also the root cause of these messy crashes.

I crafted some PR that's intended to reduce the CPU usage in output thread. But apparently it's not enough. Maybe the ultimate solution would be adding another thread for layout, freeing output thread from all those heavy work. I don't have a clear thought on this yet.

**Comment by skyline75489** [comment]
There you have it. Now it fixes the crashes. But truly this is a ugly solution to me.

File: src/cascadia/TerminalCore/Terminal.cpp [hunk 1]
```diff
@@ -533,6 +553,8 @@ void Terminal::_InitializeColorTable()
 // - isVisible: whether the cursor should be visible
 void Terminal::SetCursorVisible(const bool isVisible) noexcept
 {
+    auto lock = LockForReading();
```
Comment (miniksa) [inline src/cascadia/TerminalCore/Terminal.cpp]: Given that you're setting something about the buffer, this would be a `LockForWriting()`, not reading.

File: src/cascadia/TerminalCore/Terminal.cpp [hunk 2]
```diff
@@ -425,6 +440,11 @@ void Terminal::_WriteBuffer(const std::wstring_view& stringView)
             }
         }
 
+        if (proposedCursorPosition.X > bufferSize.RightInclusive())
```
Comment (miniksa) [inline src/cascadia/TerminalCore/Terminal.cpp]: Did you intentionally put this back? It looks like @DHowett-MSFT *just* removed this in #3212

File: src/cascadia/TerminalCore/Terminal.cpp [hunk 3]
```diff
@@ -178,6 +178,21 @@ void Terminal::UpdateSettings(winrt::Microsoft::Terminal::Settings::ICoreSetting
         proposedTop -= (proposedBottom - bufferSize.Y);
     }
 
+    Cursor& cursor = _buffer->GetCursor();
+    auto cursorPosition = cursor.GetPosition();
+    if (cursorPosition.X > viewportSize.X)
+    {
+        cursorPosition.X = viewportSize.X - 1;
```
Comment (miniksa) [inline src/cascadia/TerminalCore/Terminal.cpp]: I'm confused as to why the X dimension is reset to Size.X-1 and the Y direction is reset to Size.Y exactly.

I would think that the rectangle is either inclusive in both dimensions, or exclusive on both directions.

Additionally, the std::min/std::max functions are great for situations like this as a short hand way of writing this.

**Comment by miniksa** [comment]
Tagging as blocking. We'd like to either refine this and bring it in before we cut 0.6 or roll back #2932 and then perhaps release a patch release to 0.6 bringing it back later next week.

File: src/cascadia/TerminalCore/Terminal.cpp (hunk 2 above)
Comment (skyline75489) [reply src/cascadia/TerminalCore/Terminal.cpp]: The line the caused regression was `proposedCursorPosition.Y++;`. I only took the first line and reset `position.X` to a legal value.

File: src/cascadia/TerminalCore/Terminal.cpp (hunk 3 above)
Comment (skyline75489) [reply src/cascadia/TerminalCore/Terminal.cpp]: The runtime failure is caused by  https://github.com/microsoft/terminal/blob/429af0e6fa80412f1e9185845d856e3497a6cf78/src/buffer/out/textBufferCellIterator.cpp#L46

The `limits.IsInBounds` check is using `pos.X < RightExclusive()` so I have to use `Size.X - ` to pass it. Practially I've not seen crashes caused by `Size.Y`. But you are right, It should be unifed.

**Comment by skyline75489** [comment]
The thread dance is too complicated to fix. So I just tried limiting the cursor position. 

If we decided to rollback #2932 we'd better still keep an eye on the thread problem, which may be the cause of many other crashes like this.

File: src/cascadia/TerminalCore/Terminal.cpp [hunk 4]
```diff
@@ -178,6 +178,18 @@ void Terminal::UpdateSettings(winrt::Microsoft::Terminal::Settings::ICoreSetting
...
 
+    Cursor& cursor = _buffer->GetCursor();
+    auto cursorPosition = cursor.GetPosition();
+
+    // If the cursor is positioned beyond the range of the viewport, then
+    // set the cursor position to a legal value.
+    cursorPosition.X = std::min(cursorPosition.X, static_cast<SHORT>(viewportSize.X - 1));
+    cursorPosition.Y = std::min(cursorPosition.Y, static_cast<SHORT>(viewportSize.Y - 1));
+
+    cursor.StartDeferDrawing();
```
Comment (skyline75489) [inline src/cascadia/TerminalCore/Terminal.cpp]: This looks strange but it's necessary. Because `SetPosition` will call `RedrawCursor`, and eventually find its way to `Terminal::IsCursorDoubleWidth()`, causing the crash. So I had to disable redrawing first, correct the position, and enable redrawing.  IMO the `SetPosition` (and related method) are too aggresive doing redrawing, which is not a good design.

Comment (miniksa) [reply src/cascadia/TerminalCore/Terminal.cpp]: Yeah, you're right. We should likely fix the design on the redrawing and come up with something better. We can take this for now. I know it's ugly and complicated to fix the right way, but I'm glad you found something workable.

File: src/cascadia/TerminalCore/Terminal.cpp (hunk 2 above)
Comment (miniksa) [reply src/cascadia/TerminalCore/Terminal.cpp]: OK.

**Comment by miniksa** [comment]
@DHowett-MSFT brings up the point that this might make some sort of reverse line wrap bug with the X=0, but I'm willing to take it right now to stop crashing and cut a 0.6 candidate.

File: src/cascadia/TerminalCore/Terminal.cpp (hunk 2 above)
Comment (DHowett-MSFT) [reply src/cascadia/TerminalCore/Terminal.cpp]: This unfortunately caused #3277.
