### PR TITLE
Make sure we check to profile shortcuts with an index >9

### LINKED ISSUE #7325: Visual Error - shortcut CTRL+SHIFT+[dash,equals]
# Environment

```none
WT Version 1.1.2233
```

# Steps to reproduce

1. Have  lots of different profiles defined.
2. In `settings.json` extend additional shortcuts from the existing 1 to 9 for 0, - (dash), and = (equals) so that CTRL+SHIFT+[key] opens respective profile

# Expected behavior

In the menu for opening a tab/profile, the shortcut for extended shortcuts should appear as logically expected 

# Actual behavior

In the menu for opening a tab/profile, the shortcut newly defined 0 is appear next to relevant profile but the shortcut for dash and equals do not appear.

### PR DESCRIPTION
**Pull request by MichelleTanPY**
## Summary of the Pull Request
Update profile shortcut based on profiles defined.
1. Removed hard-coded value (9).

## PR Checklist
* [x] Closes #7325
* [x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [x] Tests added/passed

## Validation Steps Performed
profiles
Added more profiles and able to create new tab.
Note: This binding doesn't work tho ```{ "command": { "action": "newTab", "index": 10 }, "keys": "ctrl+shift+0" }```

### CODE REVIEW

File: src/cascadia/TerminalApp/TerminalPage.cpp [hunk 1]
```diff
@@ -462,8 +462,8 @@ namespace winrt::TerminalApp::implementation
             const auto& profile = _settings->GetProfiles()[profileIndex];
             auto profileMenuItem = WUX::Controls::MenuFlyoutItem{};
 
-            // add the keyboard shortcuts for the first 9 profiles
-            if (profileIndex < 9)
+            // add the keyboard shortcuts based on the number of profiles defined
+            if (profileIndex < profileCount)
```
Comment (DHowett) [inline src/cascadia/TerminalApp/TerminalPage.cpp:466]:
```suggestion
```

Since we're in a loop from 0 to profileCount, we're just guaranteed that this is true. We can simplify this code by removing the check. If you want, you can keep the `{}` for this block to keep it logically separated from the rest of the code, however.

Comment (MichelleTanPY) [reply src/cascadia/TerminalApp/TerminalPage.cpp]: Ok sure, make sense. I've removed that condition in the loop and updated the indentation.

**Comment by DHowett** [comment]
This is lovely. Thanks!
