### PR TITLE
Refrigerate our threads for later reuse 

### LINKED ISSUE #15410: Additional instances of WT crash on exit
### Windows Terminal version

1.18.1421.0

### Windows build number

10.0.19045.2728

### Other Software

N/A

### Steps to reproduce

This is probably related to
> All instances of Windows Terminal now run in the same process (https://github.com/microsoft/terminal/pull/14843)

1. Run WT.
2. Run WT again.

### Expected Behavior

Two WT windows

### Actual Behavior

Two WT windows and an extra error dialog:

image

image

Stack trace:
```
>	twinapi.appcore.dll!Microsoft::WRL::ActivationFactory<struct Microsoft::WRL::Implements<struct Microsoft::WRL::RuntimeClassFlags<3>,struct Windows::ApplicationModel::Core::ICoreApplication,struct Windows::ApplicationModel::Core::ICoreApplication2,struct Windows::ApplicationModel::Core::ICoreApplication3,struct Windows::ApplicationModel::Core::ICoreApplicationExit,struct Windows::ApplicationModel::Core::ICoreImmersiveApplication,struct Windows::ApplicationModel::Core::ICoreImmersiveApplication2,struct Windows::ApplicationModel::Core::ICoreImmersiveApplication3,struct Windows::ApplicationModel::Core::ICoreApplicationUnhandledError,struct Microsoft::WRL::Implements<struct Microsoft::WRL::RuntimeClassFlags<3>,struct Microsoft::WRL::CloakedIid<struct Windows::ApplicationModel::Core::ICoreApplicationUseCount>,struct Microsoft::WRL::CloakedIid<struct IServiceProvider>,struct Microsoft::WRL::CloakedIid<struct IObjectWithSite>,struct Microsoft::WRL::CloakedIid<struct Windows::ApplicationModel::Infrastructure::ICoreApplicationInitializat()	Unknown	Symbols loaded.
 	Windows.UI.Xaml.dll!ctl::ComPtr<Windows::Foundation::Collections::VectorChangedEventHandler<IInspectable *>>::InternalRelease() Line 346	C++	Symbols loaded.
 	[Inline Frame] Windows.UI.Xaml.dll!ctl::ComPtr<Windows::ApplicationModel::Core::ICoreApplication2>::{dtor}() Line 345	C++	Symbols loaded.
 	Windows.UI.Xaml.dll!DirectUI::FrameworkApplication::HookBackgroundActivationEvents(bool fRegister=false) Line 1233	C++	Symbols loaded.
 	Windows.UI.Xaml.dll!DirectUI::FrameworkApplication::~FrameworkApplication() Line 591	C++	Symbols loaded.
 	Windows.UI.Xaml.dll!ctl::ComObject<DirectUI::FrameworkApplication>::`scalar deleting destructor'(unsigned int)	C++	Symbols loaded.
 	Windows.UI.Xaml.dll!ctl::ComBase::ReleaseImpl() Line 307	C++	Symbols loaded.
 	[Inline Frame] TerminalApp.dll!winrt::Windows::Foundation::IUnknown::release_ref() Line 2161	C++	Symbols loaded.
 	[Inline Frame] TerminalApp.dll!winrt::Windows::Foundation::IUnknown::{dtor}() Line 2066	C++	Symbols loaded.
 	TerminalApp.dll!winrt::impl::root_implements<winrt::TerminalApp::implementation::PaletteItemTemplateSelector,winrt::TerminalApp::PaletteItemTemplateSelector,winrt::composing,winrt::Windows::UI::Xaml::Controls::IDataTemplateSelectorOverrides,winrt::Windows::UI::Xaml::Controls::IDataTemplateSelectorOverrides2>::~root_implements<winrt::TerminalApp::implementation::PaletteItemTemplateSelector,winrt::TerminalApp::PaletteItemTemplateSelector,winrt::composing,winrt::Windows::UI::Xaml::Controls::IDataTemplateSelectorOverrides,winrt::Windows::UI::Xaml::Controls::IDataTemplateSelectorOverrides2>() Line 7527	C++	Symbols loaded.
 	TerminalApp.dll!winrt::TerminalApp::implementation::App::`scalar deleting destructor'(unsigned int)	C++	Non-user code. Symbols loaded.
 	TerminalApp.dll!winrt::impl::produce_base<winrt::TerminalApp::implementation::App,winrt::TerminalApp::IApp,void>::Release() Line 7152	C++	Symbols loaded.
 	Windows.UI.Xaml.dll!ctl::release_interface<DirectUI::FrameworkApplication>(DirectUI::FrameworkApplication * & pInterface=0x000002c37f81c600) Line 137	C++	Non-user code. Symbols loaded.
 	[Inline Frame] Windows.UI.Xaml.dll!DirectUI::FrameworkApplication::GlobalDeinit() Line 668	C++	Non-user code. Symbols loaded.
 	Windows.UI.Xaml.dll!DeinitializeDll() Line 319	C++	Non-user code. Symbols loaded.
 	Windows.UI.Xaml.dll!DllMain(HINSTANCE__ * hinstDLL, unsigned int fdwReason, void * __formal) Line 394	C++	Non-user code. Symbols loaded.
 	Windows.UI.Xaml.dll!dllmain_dispatch(HINSTANCE__ * const instance=0x00007ff919460000, const unsigned long reason=0, void * const reserved=0x0000000000000001) Line 200	C++	Non-user code. Symbols loaded.
 	ntdll.dll!LdrpCallInitRoutine()	Unknown	Non-user code. Symbols loaded without source information.
 	ntdll.dll!LdrShutdownProcess()	Unknown	Non-user code. Symbols loaded without source information.
 	ntdll.dll!RtlExitUserProcess()	Unknown	Non-user code. Symbols loaded without source information.
 	kernel32.dll!ExitProcessImplementation()	Unknown	Non-user code. Symbols loaded without source information.
 	ucrtbase.dll!exit_or_terminate_process()	Unknown	Non-user code. Symbols loaded without source information.
 	ucrtbase.dll!common_exit()	Unknown	Non-user code. Symbols loaded without source information.
 	WindowsTerminal.exe!__scrt_common_main_seh() Line 295	C++	Non-user code. Symbols loaded.
 	kernel32.dll!BaseThreadInitThunk()	Unknown	Non-user code. Symbols loaded without source information.
 	ntdll.dll!RtlUserThreadStart()	Unknown	Non-user code. Symbols loaded without source information.

```

After closing the error dialog everything works normally.

### PR DESCRIPTION
**Pull request by zadjii-msft**
This is my proposed solution to #15384.

Basically, the issue is that we cannot ever close a `DesktopWindowXamlSource` ("DWXS"). If we do, then any other thread that tries to access XAML metadata will explode, which happens frequently. A DWXS is inextricably linked to an HWND. That means we have to not only reuse DWXS's, but the HWNDs themselves. XAML also isn't agile, so we've got to keep the `thread` that the DWXS was started on alive as well. 

To do this, we're going to introduce the ability to "refrigerate" and "reheat" window threads. 
* A window thread is "**hot**" if it's actively got a window, and is pumping window messages, and generally, is a normal thing. 
* When a window is closed, we need to "**refrigerate**" it's `WindowThread` and `IslandWindow`. `WindowEmperor` will take care of tracking the threads that are refrigerated. 
* When a new window is requested, the Emperor first try to "**reheat**"/"**microwave**" a refrigerated thread. When a thread gets reheated, we'll create a new AppHost (and `TerminalWindow`/`Page`), and we'll use the _existing_ `IslandWindow` for that instance. 

<sub>The metaphor is obviously ridiculous, but _you get it_ so who cares.</sub>

In this way, we'll keep all the windows we've ever created around in memory, for later reuse. This means that the leak goes from (~12MB x number of windows closed) to (~12MB x maximum number of simultaneously open Terminal windows). It's still not good. 

We won't do this on Windows 11, because the bug that is the fundamental premise of this issue is fixed already in the OS. 

I'm not 100% confident in this yet. 
* [x] There's still a d3d leak of some sort on exit in debug builds. (maybe #15306 related)
  * havent seen this in a while. Must have been a issue in an earlier revision. 
* [x] I need to validate more on Windows 11
  * [x] **BAD**: Closing the last tab on Windows 11 doesn't close the window
  * [x] **BAD**: Closing a window on Windows 11 doesn't close the window - it just closes the one tab item and keeps on choochin'
  * [x] **BAD**: Close last tab, open new one, attempt to close window - ALL windows go \*poof\*. Cause of course. No break into post-mortem either. 
* [x] more comments
* [ ] maybe a diagram
* [x] Restoring windows is at the wrong place entirely? I once reopened the Terminal with two persisted windows, and it created one at 0,0
* [x] Remaining code TODO!s: 0 (?)
* [ ] "warm-reloading" `useTabsInTitlebar` (change while terminal is running after closing a window, open a new one) REALLY doesn't work. Obviously restores the last kind of window. Yike. 

is all about #15384

closes #15410 along the way. Might fork that fix off.

### CODE REVIEW

File: src/cascadia/WindowsTerminal/WindowEmperor.cpp [hunk 1]
```diff
@@ -150,33 +205,67 @@ void WindowEmperor::_createNewWindowThread(const Remoting::WindowRequestedArgs&
...
-
-            // Manually trigger the cleanup callback. This will ensure that we
-            // remove the window from our list of windows, before we release the
-            // AppHost (and subsequently, the host's Logic() member that we use
-            // elsewhere).
-            removeWindow.reset();
+                if (auto self{ weakThis.lock() })
+                {
+                    auto lockedWindows{ self->_windows.lock() };
+                    lockedWindows->push_back(window);
```
[the remark this answers is not in the document]
Comment (zadjii-msft) [reply src/cascadia/WindowsTerminal/WindowEmperor.cpp:224]: I'm gonna be totally honest - I didn't think that much about this. I figured that with the frequency that windows are opened/closed, this is highly unlikely to be anywhere near a hot path.

File: src/cascadia/WindowsTerminal/WindowThread.cpp [hunk 2]
```diff
@@ -52,15 +78,102 @@ void WindowThread::RundownForExit()
...
+    _args = std::move(args);
+
+    _host = std::make_unique<::AppHost>(_appLogic,
+                                        _args,
+                                        _manager,
+                                        _peasant,
+                                        std::move(_warmWindow));
+
+    // raise the signal to unblock KeepWarm and start the window message loop again.
+    _microwaveBuzzer.notify_one();
```
Comment (lhecker) [inline src/cascadia/WindowsTerminal/WindowThread.cpp:174]: I just remember that C++20 added `std::binary_semaphore` and we could use it in place of a conditional variable. Instead of `notify_one()` it'd be [`release()`](https://en.cppreference.com/w/cpp/thread/counting_semaphore/release) and instead of `wait()` it'd be [`acquire()`](https://en.cppreference.com/w/cpp/thread/counting_semaphore/acquire).

File: src/cascadia/WindowsTerminal/WindowEmperor.cpp [hunk 3]
```diff
@@ -164,33 +215,66 @@ void WindowEmperor::_createNewWindowThread(const Remoting::WindowRequestedArgs&
...
+                    window->Refrigerate();
+                    decrementWindowCount.reset();
+
+                    if (auto self{ weakThis.lock() })
+                    {
+                        auto fridge{ self->_oldThreads.lock() };
+                        fridge->push_back(window);
+                    }
+                }
+            }
```
Comment (lhecker) [inline src/cascadia/WindowsTerminal/WindowEmperor.cpp:277]: Ah, I forgot to comment this:
I think we should see if we can move the things that both WindowEmperor and WindowThread need access to into its own little struct. This way we would resolve the circular dependency between the two. Instead of "A <-> B" it'd be "A -> C & B -> C". It would allow us to move this code into WindowThread in some way and likely make this a bit easier to understand. (I struggled to understand how the Refrigerate/Microwaving flow works.)

File: src/cascadia/WindowsTerminal/IslandWindow.cpp [hunk 4]
```diff
@@ -378,9 +382,32 @@ void IslandWindow::Initialize()
...
+    // the contents of the window will never resize.
+    UpdateWindow(_window.get());
+    ForceResize();
+}
 
 void IslandWindow::OnSize(const UINT width, const UINT height)
 {
+    // NOTE: This _isn't_ called by NonClientIslandWindow::OnSize. The
+    // NonClientIslandWindow has very different logic for positioning the
+    // DesktopWindowXamlSource inside it's HWND.
```
Comment (DHowett) [inline src/cascadia/WindowsTerminal/IslandWindow.cpp:409]:
```suggestion
    // DesktopWindowXamlSource inside its HWND.
```

File: src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp [hunk 5]
```diff
@@ -335,9 +335,17 @@ void NonClientIslandWindow::OnAppInitialized()
     IslandWindow::OnAppInitialized();
 }
 
-void NonClientIslandWindow::Initialize()
+void NonClientIslandWindow::Refrigerate() noexcept
 {
-    IslandWindow::Initialize();
+    IslandWindow::Refrigerate();
+    _dragBar.SizeChanged(_callbacks.dragBar_SizeChanged);
```
Comment (DHowett) [inline src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp:341]: should we use autorevokers here?

File: src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp [hunk 6]
```diff
@@ -349,15 +357,16 @@ void NonClientIslandWindow::Initialize()
...
     _rootGrid.RowDefinitions().Append(titlebarRow);
     _rootGrid.RowDefinitions().Append(contentRow);
 
     // Create our titlebar control
     _titlebar = winrt::TerminalApp::TitlebarControl{ reinterpret_cast<uint64_t>(GetHandle()) };
     _dragBar = _titlebar.DragBar();
 
-    _dragBar.SizeChanged({ this, &NonClientIslandWindow::_OnDragBarSizeChanged });
-    _rootGrid.SizeChanged({ this, &NonClientIslandWindow::_OnDragBarSizeChanged });
+    _callbacks.dragBar_SizeChanged = _dragBar.SizeChanged({ this, &NonClientIslandWindow::_OnDragBarSizeChanged });
```
Comment (DHowett) [inline src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp:368]: we don't use this underscore style anywhere else; why here?

File: src/cascadia/WindowsTerminal/NonClientIslandWindow.h [hunk 7]
```diff
@@ -95,4 +97,13 @@ class NonClientIslandWindow : public IslandWindow
...
     void _UpdateMaximizedState();
     void _UpdateIslandPosition(const UINT windowWidth, const UINT windowHeight);
+
+    struct Revokers
+    {
+        winrt::event_token dragBar_SizeChanged;
+        winrt::event_token rootGrid_SizeChanged;
+        winrt::event_token titlebar_Loaded;
+        // LOAD BEARING!!
+        //If you add events here, make sure they're revoked in NonClientIslandWindow::Refrigerate
```
Comment (DHowett) [inline src/cascadia/WindowsTerminal/NonClientIslandWindow.h:107]: see, autorevokers would make this much easier.. you could just set `_callbacks = {}`

Comment (DHowett) [reply src/cascadia/WindowsTerminal/NonClientIslandWindow.h:107]: (I feel like that is a pattern we've used elsewhere to great effect)

File: src/cascadia/WindowsTerminal/AppHost.cpp [hunk 8]
```diff
@@ -429,6 +450,47 @@ void AppHost::Close()
...
+    _window->MouseScrolled(_windowCallbacks.MouseScrolled);
+    _window->WindowActivated(_windowCallbacks.WindowActivated);
+    _window->WindowMoved(_windowCallbacks.WindowMoved);
+    _window->ShouldExitFullscreen(_windowCallbacks.ShouldExitFullscreen);
+    _window->WindowCloseButtonClicked(_windowCallbacks.WindowCloseButtonClicked);
+    _window->DragRegionClicked(_windowCallbacks.DragRegionClicked);
+    _window->WindowVisibilityChanged(_windowCallbacks.WindowVisibilityChanged);
+    _window->UpdateSettingsRequested(_windowCallbacks.UpdateSettingsRequested);
+    _window->MaximizeChanged(_windowCallbacks.MaximizeChanged);
+    _window->AutomaticShutdownRequested(_windowCallbacks.AutomaticShutdownRequested);
```
Comment (DHowett) [inline src/cascadia/WindowsTerminal/AppHost.cpp:464]: au to re vo ke rs!

Comment (DHowett) [reply src/cascadia/WindowsTerminal/AppHost.cpp:464]: UGH IT ISNT A WINRT TYPE STOP YOU'RE HURTING ME

File: src/cascadia/WindowsTerminal/AppHost.cpp [hunk 9]
```diff
@@ -429,6 +450,47 @@ void AppHost::Close()
...
+{
+    // After calling _window->Close() we should avoid creating more WinUI related actions.
+    // I suspect WinUI wouldn't like that very much. As such unregister all event handlers first.
+    _revokers = {};
+    _showHideWindowThrottler.reset();
+
+    // DO NOT CLOSE THE WINDOW
+    _window->Refrigerate();
+
+    _revokeWindowCallbacks();
```
Comment (DHowett) [inline src/cascadia/WindowsTerminal/AppHost.cpp:483]: should we revoke callbacks first?

File: src/cascadia/WindowsTerminal/AppHost.cpp [hunk 10]
```diff
@@ -44,13 +45,22 @@ AppHost::AppHost(const winrt::TerminalApp::AppLogic& logic,
 
     // _HandleCommandlineArgs will create a _windowLogic
     _useNonClientArea = _windowLogic.GetShowTabsInTitlebar();
-    if (_useNonClientArea)
+
+    const bool isWarmStart = window != nullptr;
+    if (isWarmStart)
     {
-        _window = std::make_unique<NonClientIslandWindow>(_windowLogic.GetRequestedTheme());
+        _window = std::move(window);
```
Comment (DHowett) [inline src/cascadia/WindowsTerminal/AppHost.cpp:52]: OK so this was my fear. We always pop off whatever kind of window we're given, and we never make sure it's the right kind. That means that on Windows 11 if I change "Show Tabs in Titlebar" new windows will get it right (no refrigeration) and on Windows 10 it may get it wrong (it will microwave the wrong kind of window).

File: src/cascadia/WindowsTerminal/AppHost.cpp [hunk 11]
```diff
@@ -65,16 +75,15 @@ AppHost::AppHost(const winrt::TerminalApp::AppLogic& logic,
...
-    _window->SetAutoHideWindow(_windowLogic.AutoHideWindow());
+    _windowCallbacks.MouseScrolled = _window->MouseScrolled({ this, &AppHost::_WindowMouseWheeled });
+    _windowCallbacks.WindowActivated = _window->WindowActivated({ this, &AppHost::_WindowActivated });
+    _windowCallbacks.WindowMoved = _window->WindowMoved({ this, &AppHost::_WindowMoved });
+    _windowCallbacks.ShouldExitFullscreen = _window->ShouldExitFullscreen({ &_windowLogic, &winrt::TerminalApp::TerminalWindow::RequestExitFullscreen });
 
-    _window->MakeWindow();
+    if (!isWarmStart)
+    {
+        _window->MakeWindow();
```
Comment (DHowett) [inline src/cascadia/WindowsTerminal/AppHost.cpp:85]: we could make MakeWindow a no-op if there already is a window and remove this check here

File: src/cascadia/WindowsTerminal/AppHost.cpp [hunk 12]
```diff
@@ -291,13 +308,14 @@ void AppHost::Initialize()
     // tearing down, after we've nulled out the window, during the dtor. That
     // can cause unexpected AV's everywhere.
     //
-    // _window callbacks don't need to be treated this way, because:
-    // * IslandWindow isn't a WinRT type (so it doesn't have neat revokers like this)
-    // * This particular bug scenario applies when we've already freed the window.
+    // _window callbacks are a little special:
+    // * IslandWindow isn't a WinRT type (so it doesn't have neat revokers like
+    //   this), so instead they go in their own special helper struct.
+    // * they all need to be manually revoked in .
```
Comment (DHowett) [inline src/cascadia/WindowsTerminal/AppHost.cpp:314]: I get it. I missed this comment.

Also the comment is incomplete. :D

**Review by DHowett — CHANGES_REQUESTED** [review]
8/11

File: src/cascadia/WindowsTerminal/AppHost.cpp (hunk 8 above)
Comment (zadjii-msft) [reply src/cascadia/WindowsTerminal/AppHost.cpp:464]: image

File: src/cascadia/WindowsTerminal/AppHost.cpp (hunk 10 above)
Comment (zadjii-msft) [reply src/cascadia/WindowsTerminal/AppHost.cpp:52]: On a scale of 1-blocking, where do we rate this?

**Comment by DHowett** [comment]
There are more unchecked TODOs in the PR body -- should we drive them down before merging?

**Comment by zadjii-msft** [comment]
> There are more unchecked TODOs in the PR body -- should we drive them down before merging?

I should more accurately update the PR body :wink:

File: src/cascadia/WindowsTerminal/AppHost.cpp (hunk 10 above)
Comment (DHowett) [reply src/cascadia/WindowsTerminal/AppHost.cpp:56]: I would call it blocking for this PR.

Comment (zadjii-msft) [reply src/cascadia/WindowsTerminal/AppHost.cpp:56]: brainstorm
* keep two drawers in the fridge, one for each type of window. Evaluate what's needed, and get one of those specifically. 
  * seems insane
* Totally leak the fridge when that setting changes
  * will make sure we make the right kind of window
  * seems insane
  * leaks a bunch of memory when the setting changes
* Find some way to exorcise a DWXS out of a window when we change that setting
  * pretty sure the DWXS is HARD pinned to the `HWND`
  * yes it's HARD linked to the `HWND` [`IDesktopWindowXamlSourceNative::AttachToWindow`](https://learn.microsoft.com/en-us/windows/win32/api/windows.ui.xaml.hosting.desktopwindowxamlsource/nf-windows-ui-xaml-hosting-desktopwindowxamlsource-idesktopwindowxamlsourcenative-attachtowindow#remarks): 
    > Make sure that your code calls the AttachToWindow method only once per [DesktopWindowXamlSource](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.hosting.desktopwindowxamlsource) object. Calling this method more than once for a DesktopWindowXamlSource object could result in a memory leak
  * ... goddard, options

Comment (lhecker) [reply src/cascadia/WindowsTerminal/AppHost.cpp:56]: Can't we just pin the setting for the entire duration the application is running? That's how the setting is documented anyways right?

Comment (zadjii-msft) [reply src/cascadia/WindowsTerminal/AppHost.cpp:56]: man I'd love that. That would sure be the easiest way.

Comment (zadjii-msft) [reply src/cascadia/WindowsTerminal/AppHost.cpp:56]: Er, after discussion, pinning probably isn't the best, cause warm-reloading `useTabsInTitlebar` _does_ work on Windows 11 today

Comment (DHowett) [reply src/cascadia/WindowsTerminal/AppHost.cpp:56]: After discussing the impact with Mike, I'm choosing to not consider this blocking any longer.

It impacts the following scenario:

1. Be on Win 10
2. Open two windows
3. Close one
4. Change the "tabs in titlebar" setting
5. Open a new one

**Comment by zadjii-msft** [comment]
Leaving notes here, because there's not another thread for "hot reload showTabsInTitlebar "

<details>
<summary>Notes that folks don't need to care about</summary>

If we could include NCIW.h in IW.cpp,

```cpp
unique_ptr<IslandWindow> IslandWindow::ConvertToOther(requestedTheme)
{
    return std::move(std::make_unique<NonClientIslandWindow>(this, requestedTheme));
}

IslandWindow::IslandWindow(std::unique_ptr<IslandWindow>& oldWindow) noexcept :
    IslandWindow{ requestedTheme }
{
    _interopWindowHandle = std::move(oldWindow->_interopWindowHandle);
    _source = std::move(oldWindow->_source);
    // oldWindow is dead now. It should be freed by the caller.
}
```

```cpp
NonClientIslandWindow::NonClientIslandWindow(std::unique_ptr<IslandWindow>& oldWindow, const ElementTheme& requestedTheme) noexcept :
    NonClientIslandWindow{ requestedTheme }
{
    _interopWindowHandle = std::move(oldWindow->_interopWindowHandle);
    _source = std::move(oldWindow->_source);
}

unique_ptr<IslandWindow> NonClientIslandWindow::ConvertToOther(requestedTheme) override
{
    return std::move(std::make_unique<IslandWindow>(this));
}
```

and then in apphost,

```
_window = std::move(_window.ConvertToOther(requestedTheme));
```


GAH but you STILL dont' know if you need to convert at all!

Like, you don't know if _useNonClientArea changed between that window and what we want to make, and we can't introspect that


</details>

---- 

hot reloading this is _hard_

File: src/cascadia/WindowsTerminal/AppHost.cpp (hunk 8 above)
Comment (DHowett) [reply src/cascadia/WindowsTerminal/AppHost.cpp:472]: Oh my GOD i almost left the same exact comment again, someone pls maim me

File: src/cascadia/WindowsTerminal/WindowEmperor.cpp [hunk 13]
```diff
@@ -518,8 +574,22 @@ LRESULT WindowEmperor::_messageHandler(UINT const message, WPARAM const wParam,
     return DefWindowProc(_window.get(), message, wParam, lParam);
 }
 
+// Close the Terminal application. This will exit the main thread for the
+// emperor itself. We should probably only ever be called when we have no
+// windows left, and we don't want to keep running anymore. This will discard
+// all our refrigerated windows. If we try to use XAML on Windows 10 after this,
+// we'll undoubtably crash.
```
Comment (DHowett) [inline src/cascadia/WindowsTerminal/WindowEmperor.cpp:581]:
```suggestion
// we'll undoubtedly crash.
```

**Review by DHowett — APPROVED** [review]
I'm cool with this. Let's drive down the rest of those checkboxes.

Thanks for handling this, Mike!
