### PR TITLE
AtlasEngine: Implement remaining underlines and builtin glyphs for D2D

### LINKED ISSUE #17224: Gaps between block elements when using Direct2D
### Windows Terminal version

Current main

### Windows build number

10.0.19045.4291

### Other Software

_No response_

### Steps to reproduce

- System-wide scale and layout (display settings): 100%
- WT PowerShell profile settings:
  - Font face: "Cascadia Mono"
  - Font size: "12.2"
  - Line height: "1.2"
  - Font weight: "Normal"
  - Builtin Glyphs: "On"
  - image
  - Graphics API: "Direct2D"
  - image

- Type "▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄" at the pwsh prompt
  ```pwsh
  "▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄"
  ```

### Expected Behavior

[Block elements](https://unicode.org/charts/PDF/U2580.pdf) are fused into a solid bar.

### Actual Behavior

image

### PR DESCRIPTION
**Pull request by lhecker**
This implements builtin glyphs for our Direct2D renderer, as well as
dashed and curly underlines. With this in place the only two features
it doesn't support are inverted cursors and VT soft fonts.
This allows us to remove the `_hack*` members introduced in a6a0e44.

The implementation of dashed underlines is trivial, while curly
underlines use quadratic bezier curves. Caching the curve as a sprite
is possible, however I feel like that can be done in the future.

Builtin glyphs on the other hand require a cache, because otherwise
filling the entire viewport with shaded glyphs would result in poor
performance. This is why it's built on top of `ID2D1SpriteBatch`.
Unfortunately the API causes an eager flush of other pending graphics
instructions, which is why there's still a decent perf hit.

Finally, as a little extra, this fixes the rounded powerline glyph
shapes being slightly cut off. The fix is to simply don't round the
position and radius of the ellipsis/semi-circle.

Closes #17224

## Validation Steps Performed
* RenderingTests.exe updated ✅
* All supported builtin glyphs look sorta right at different sizes ✅

### CODE REVIEW

File: src/renderer/atlas/BuiltinGlyphs.cpp [hunk 1]
```diff
@@ -1183,13 +1177,13 @@ void BuiltinGlyphs::DrawBuiltinGlyph(ID2D1Factory* factory, ID2D1DeviceContext*
         }
         case Shape_FilledEllipsis:
         {
-            const D2D1_ELLIPSE e{ { begXabs, begYabs }, endX, endY };
+            const D2D1_ELLIPSE e{ { rectX + begX, rectY + begY }, endX, endY };
```
Comment (DHowett) [inline src/renderer/atlas/BuiltinGlyphs.cpp:1180]: why this change? it doesn't take into account the line offsets any longer

File: src/renderer/atlas/BackendD3D.cpp [hunk 2]
```diff
@@ -295,20 +295,20 @@ void BackendD3D::_updateFontDependents(const RenderingPayload& p)
...
-        const auto height = std::max(3.0f, duBottom + duHeight - duTop);
-        const auto top = std::min(duTop, floorf(cellHeight - height - duHeight));
+        // We still need to ensure though that it doesn't clip out of the cellHeight at the bottom, which is why `position` has a min().
+        const auto height = std::max(3, duBottom + duHeight - duTop);
+        const auto position = std::min(duTop, cellHeight - height - duHeight);
 
         _curlyLineHalfHeight = height * 0.5f;
-        _curlyUnderline.position = gsl::narrow_cast<u16>(lrintf(top));
-        _curlyUnderline.height = gsl::narrow_cast<u16>(lrintf(height));
+        _curlyUnderline.position = gsl::narrow_cast<u16>(position);
```
Comment (DHowett) [inline src/renderer/atlas/BackendD3D.cpp:310]: no more rounding - all this math now uses truncation. is that OK?

Comment (DHowett) [reply src/renderer/atlas/BackendD3D.cpp:310]: (I don't 100% know why the changes to the D3D backend were needed -- can you explain? Did you test them again at different font sizes and scalings?)

File: src/renderer/atlas/BuiltinGlyphs.cpp (hunk 1 above)
Comment (lhecker) [reply src/renderer/atlas/BuiltinGlyphs.cpp:1180]: Filled shapes don't have any line width, so this will work just fine.
This change ensures that the rounded powerline glyphs aren't slightly cut off anymore.

File: src/renderer/atlas/BackendD3D.cpp (hunk 2 above)
Comment (lhecker) [reply src/renderer/atlas/BackendD3D.cpp:310]: I did this because I copied the code over to D2D. While doing so I noticed that this code doesn't actually do any floating point math whatsoever. As you can see I don't need to do any explicit integer/float casts anywhere in the preceding lines (which would normally be required during AuditMode). I changed the D3D part so that it's mostly identical to the D2D part.

File: src/renderer/atlas/AtlasEngine.cpp [hunk 3]
```diff
@@ -703,8 +702,6 @@ void AtlasEngine::_recreateFontDependentResources()
             _api.textFormatAxes[i] = { fontAxisValues.data(), fontAxisValues.size() };
         }
     }
-
-    _hackWantsBuiltinGlyphs = _p.s->font->builtinGlyphs && !_hackIsBackendD2D;
```
Comment (DHowett) [inline src/renderer/atlas/AtlasEngine.cpp:707]: I think this is where the preference to disable builtin glyphs is getting removed

**Review by DHowett — CHANGES_REQUESTED** [review]
tested, can't turn em off!

File: src/renderer/atlas/BuiltinGlyphs.cpp (hunk 1 above)
Comment (DHowett) [reply src/renderer/atlas/BuiltinGlyphs.cpp:1180]: okay but the empty glyphs DO have a line width - how does this apply on line 1186R?

Comment (DHowett) [reply src/renderer/atlas/BuiltinGlyphs.cpp:1180]: (looks fine on my screen)

**Review by DHowett — APPROVED** [review]

File: src/renderer/atlas/BackendD2D.cpp [hunk 4]
```diff
@@ -300,6 +308,138 @@ void BackendD2D::_drawText(RenderingPayload& p)
...
+
+        baselineX += row->glyphAdvances[i];
+    }
+
+    return baselineX;
+}
+
+void BackendD2D::_prepareBuiltinGlyphRenderTarget(const RenderingPayload& p)
+{
+    if (!_builtinGlyphBatch || _builtinGlyphsRenderTarget)
```
Comment (carlos-zamora) [inline src/renderer/atlas/BackendD2D.cpp:347]:
```suggestion
    if (!_builtinGlyphBatch || !_builtinGlyphsRenderTarget)
```

(I'm only like half-understanding what's going on so correct me if I'm wrong) Wouldn't we want to exit early if `_buildinGlyphsRenderTarget` _is not_ defined? I see we overwrite it a few lines later. Curious.

**Review by carlos-zamora — APPROVED** [review]

File: src/renderer/atlas/BackendD2D.cpp (hunk 4 above)
Comment (lhecker) [reply src/renderer/atlas/BackendD2D.cpp:347]: Ah, yeah that condition sucks. Let me split it apart and add comments!

File: src/renderer/atlas/BuiltinGlyphs.cpp (hunk 1 above)
Comment (lhecker) [reply src/renderer/atlas/BuiltinGlyphs.cpp:1185]: Ah right. More generally speaking, the `lineOffsetX/Y` code is only for snapping the coordinates of lines. In case of the "arc" shape glyph, this probably doesn't matter much because the entire glyph uses a lot of anti-aliasing anyway.

File: src/renderer/atlas/BackendD2D.cpp (hunk 4 above)
Comment (lhecker) [reply src/renderer/atlas/BackendD2D.cpp]: Should be much better now!

**Review by DHowett — APPROVED** [review]
these comments are amazing
